const deityIcons: Record<string, string> = {
  "ahura mazda": "ahura-mazda",
  amaterasu: "amaterasu",
  "amun-ra": "amun-ra",
  anahita: "anahita",
  "angra mainyu": "angra-mainyu",
  anubis: "anubis",
  aphrodite: "aphrodite",
  apollo: "apollo",
  ares: "ares",
  artemis: "artemis",
  asherah: "asherah",
  athena: "athena",
  baal: "baal-hadad",
  "baal-hadad": "baal-hadad",
  brahma: "brahma",
  brigantia: "brigantia",
  brigid: "brigid",
  chaac: "chaac",
  cocijo: "cocijo",
  demeter: "demeter",
  diana: "diana",
  dionysus: "dionysus",
  durga: "durga",
  ea: "enki-ea",
  enki: "enki-ea",
  enlil: "enlil",
  epona: "epona",
  erlik: "erlik",
  eshu: "eshu-eleggua",
  etugen: "etugen",
  etügen: "etugen",
  eleggua: "eshu-eleggua",
  freyja: "freyja",
  ganesha: "ganesha",
  "guan yu": "guandi",
  guandi: "guandi",
  guanyin: "guanyin",
  hachiman: "hachiman",
  hathor: "hathor",
  hephaestus: "hephaestus",
  hera: "hera",
  hermes: "hermes",
  horus: "horus",
  huitzilopochtli: "huitzilopochtli",
  inanna: "inanna-ishtar",
  inari: "inari",
  indra: "indra",
  inti: "inti",
  illapa: "illapa",
  isis: "isis",
  ishtar: "inanna-ishtar",
  itzamna: "itzamna",
  "jade emperor": "jade-emperor",
  juno: "juno",
  jupiter: "jupiter",
  "the jade emperor": "jade-emperor",
  kannon: "guanyin",
  "k'inich ajaw": "kinich-ajaw",
  krishna: "krishna",
  lakshmi: "lakshmi",
  lugus: "lugus",
  "mama cocha": "mama-cocha",
  "mama quilla": "mama-quilla",
  marduk: "marduk",
  mars: "mars",
  mazu: "mazu",
  minerva: "minerva",
  mithra: "mithra",
  murugan: "murugan",
  nanna: "nanna-sin",
  neptune: "neptune",
  odin: "odin",
  ogun: "ogun",
  olorun: "olorun",
  orunmila: "orunmila",
  oshun: "oshun",
  osiris: "osiris",
  pachamama: "pachamama",
  papa: "papa",
  parvati: "parvati",
  perun: "perun",
  poseidon: "poseidon",
  ptah: "ptah",
  quetzalcoatl: "quetzalcoatl",
  rangi: "rangi",
  rongo: "rongo",
  sedna: "sedna",
  sekhmet: "sekhmet",
  shango: "shango",
  shiva: "shiva",
  sin: "nanna-sin",
  tane: "tane",
  tāne: "tane",
  taranis: "taranis",
  tangaroa: "tangaroa",
  tengri: "tengri",
  tezcatlipoca: "tezcatlipoca",
  thoth: "thoth",
  thor: "thor",
  tlaloc: "tlaloc",
  umai: "umai",
  viracocha: "viracocha",
  vishnu: "vishnu",
  vesta: "vesta",
  yemoja: "yemoja",
  zeus: "zeus",
};

export function deityIconFor(name: string) {
  const slug = deityIcons[name.trim().toLocaleLowerCase()];
  return slug ? `/beliefs/deities/v1/icons/${slug}.png` : undefined;
}
