const deityIcons: Record<string, string> = {
  amaterasu: "amaterasu",
  "amun-ra": "amun-ra",
  anubis: "anubis",
  apollo: "apollo",
  artemis: "artemis",
  asherah: "asherah",
  athena: "athena",
  baal: "baal-hadad",
  "baal-hadad": "baal-hadad",
  brigid: "brigid",
  demeter: "demeter",
  dionysus: "dionysus",
  durga: "durga",
  ea: "enki-ea",
  enki: "enki-ea",
  enlil: "enlil",
  freyja: "freyja",
  ganesha: "ganesha",
  "guan yu": "guandi",
  guandi: "guandi",
  guanyin: "guanyin",
  hachiman: "hachiman",
  hathor: "hathor",
  huitzilopochtli: "huitzilopochtli",
  inanna: "inanna-ishtar",
  inari: "inari",
  indra: "indra",
  inti: "inti",
  isis: "isis",
  ishtar: "inanna-ishtar",
  "jade emperor": "jade-emperor",
  kannon: "guanyin",
  lakshmi: "lakshmi",
  marduk: "marduk",
  mazu: "mazu",
  nanna: "nanna-sin",
  odin: "odin",
  ogun: "ogun",
  oshun: "oshun",
  osiris: "osiris",
  perun: "perun",
  quetzalcoatl: "quetzalcoatl",
  sedna: "sedna",
  sekhmet: "sekhmet",
  shango: "shango",
  shiva: "shiva",
  sin: "nanna-sin",
  tangaroa: "tangaroa",
  tezcatlipoca: "tezcatlipoca",
  thor: "thor",
  tlaloc: "tlaloc",
  viracocha: "viracocha",
  vishnu: "vishnu",
  zeus: "zeus",
};

export function deityIconFor(name: string) {
  const slug = deityIcons[name.trim().toLocaleLowerCase()];
  return slug ? `/beliefs/deities/v1/icons/${slug}.png` : undefined;
}
