const deityIcons: Record<string, string> = {
  allah: "allah",
  "ahura mazda": "ahura-mazda",
  amaterasu: "amaterasu",
  "amida buddha": "amida-buddha",
  "amun-ra": "amun-ra",
  anahita: "anahita",
  "angra mainyu": "angra-mainyu",
  anubis: "anubis",
  aphrodite: "aphrodite",
  apollo: "apollo",
  ares: "ares",
  artemis: "artemis",
  asherah: "asherah",
  athena: "athena",
  baal: "baal-hadad",
  "baal-hadad": "baal-hadad",
  brahma: "brahma",
  brigantia: "brigantia",
  brigid: "brigid",
  chaac: "chaac",
  cocijo: "cocijo",
  demeter: "demeter",
  diana: "diana",
  dionysus: "dionysus",
  durga: "durga",
  ea: "enki-ea",
  enki: "enki-ea",
  enlil: "enlil",
  epona: "epona",
  erlik: "erlik",
  eshu: "eshu-eleggua",
  etugen: "etugen",
  etügen: "etugen",
  eleggua: "eshu-eleggua",
  freyja: "freyja",
  ganesha: "ganesha",
  "guan yu": "guandi",
  guandi: "guandi",
  guanyin: "guanyin",
  hachiman: "hachiman",
  hathor: "hathor",
  hephaestus: "hephaestus",
  hera: "hera",
  hermes: "hermes",
  heaven: "tian-heaven",
  horus: "horus",
  huitzilopochtli: "huitzilopochtli",
  inanna: "inanna-ishtar",
  inari: "inari",
  indra: "indra",
  inti: "inti",
  illapa: "illapa",
  isis: "isis",
  ishtar: "inanna-ishtar",
  itzamna: "itzamna",
  "jade emperor": "jade-emperor",
  juno: "juno",
  jupiter: "jupiter",
  "jesus christ": "jesus-christ",
  "jesus christ, the son": "jesus-christ",
  "the jade emperor": "jade-emperor",
  kannon: "guanyin",
  "k'inich ajaw": "kinich-ajaw",
  krishna: "krishna",
  lakshmi: "lakshmi",
  lugus: "lugus",
  "mama cocha": "mama-cocha",
  "mama quilla": "mama-quilla",
  marduk: "marduk",
  mars: "mars",
  mercury: "hermes",
  mazu: "mazu",
  minerva: "minerva",
  mithra: "mithra",
  murugan: "murugan",
  nanna: "nanna-sin",
  neptune: "neptune",
  odin: "odin",
  ogun: "ogun",
  olorun: "olorun",
  orunmila: "orunmila",
  oshun: "oshun",
  osiris: "osiris",
  pachamama: "pachamama",
  papa: "papa",
  parvati: "parvati",
  perun: "perun",
  poseidon: "poseidon",
  ptah: "ptah",
  quetzalcoatl: "quetzalcoatl",
  rangi: "rangi",
  rongo: "rongo",
  sedna: "sedna",
  sekhmet: "sekhmet",
  shango: "shango",
  shiva: "shiva",
  sin: "nanna-sin",
  tane: "tane",
  tāne: "tane",
  taranis: "taranis",
  tangaroa: "tangaroa",
  tengri: "tengri",
  tian: "tian-heaven",
  tezcatlipoca: "tezcatlipoca",
  thoth: "thoth",
  thor: "thor",
  tlaloc: "tlaloc",
  umai: "umai",
  viracocha: "viracocha",
  vishnu: "vishnu",
  vesta: "vesta",
  yemoja: "yemoja",
  zeus: "zeus",
  "god the father": "god-the-father",
  "holy spirit": "holy-spirit",
  "the holy spirit": "holy-spirit",
  yhwh: "yhwh",
  adad: "adad",
  agni: "agni",
  "ah puch": "ah-puch",
  "ai apaec": "ai-apaec",
  ala: "ala",
  "al-lat": "al-lat",
  "al-uzza": "al-uzza",
  "amesha spentas": "amesha-spentas",
  amma: "amma",
  anat: "anat",
  anu: "anu",
  "aphrodite-astarte": "aphrodite-astarte",
  api: "api",
  apolaki: "apolaki",
  argimpasa: "argimpasa",
  ashur: "ashur",
  "asase ya": "asase-ya",
  astar: "astar",
  atar: "atar",
  "batara guru": "batara-guru",
  bathala: "bathala",
  belatucadros: "belatucadros",
  bhairava: "bhairava",
  bodhisattvas: "bodhisattvas",
  buddha: "buddha",
  "the buddha": "buddha",
  chukwu: "chukwu",
  "city god": "city-god",
  coyote: "coyote",
  dazhbog: "dazhbog",
  degei: "degei",
  "devi/shakti": "devi-shakti",
  "dewi sri": "dewi-sri",
  el: "el",
  elal: "elal",
  "engai narok": "engai-narok",
  esus: "esus",
  freyr: "freyr",
  ganga: "ganga",
  gluskap: "gluskap",
  goitosyros: "goitosyros",
  haumea: "haumea",
  iyatiku: "iyatiku",
  "ix chel": "ix-chel",
  kaggen: "kaggen",
  ǀkaggen: "kaggen",
  "kaltash-ekwa": "kaltash-ekwa",
  kanaloa: "kanaloa",
  kane: "kane",
  kāne: "kane",
  katsinas: "katsinas",
  khandoba: "khandoba",
  "kitchen god": "kitchen-god",
  ku: "ku",
  kū: "ku",
  kukulkan: "kukulkan",
  lakapati: "lakapati",
  legba: "legba",
  leza: "leza",
  loki: "loki",
  lono: "lono",
  mahrem: "mahrem",
  manat: "manat",
  masauwu: "masauwu",
  maui: "maui",
  māui: "maui",
  "mawu-lisa": "mawu-lisa",
  "min mahagiri": "min-mahagiri",
  mwari: "mwari",
  nehanda: "nehanda",
  ninhursag: "ninhursag",
  nommo: "nommo",
  "numi-torum": "numi-torum",
  papaios: "papaios",
  pele: "pele",
  selu: "selu",
  shamash: "shamash",
  "shakyamuni buddha": "buddha",
  "sky woman": "sky-woman",
  soma: "soma",
  sraosha: "sraosha",
  supay: "supay",
  surya: "surya",
  tabiti: "tabiti",
  tagaloa: "tagaloa",
  thagimasadas: "thagimasadas",
  thagyamin: "thagyamin",
  "the amesha spentas": "amesha-spentas",
  "the three jewels": "three-jewels",
  "the dhamma": "three-jewels",
  "the dharma": "three-jewels",
  toutatis: "toutatis",
  tupa: "tupa",
  tupã: "tupa",
  tudigong: "tudigong",
  tyr: "tyr",
  umvelinqangi: "umvelinqangi",
  unkulunkulu: "unkulunkulu",
  varuna: "varuna",
  veles: "veles",
  verethragna: "verethragna",
  "wakan tanka": "wakan-tanka",
  wisakedjak: "wisakedjak",
  xiwangmu: "xiwangmu",
  "zeus-baal": "zeus-baal",
};

export function deityIconFor(name: string) {
  const slug = deityIcons[name.trim().toLocaleLowerCase()];
  return slug ? `/beliefs/deities/v1/icons/${slug}.png` : undefined;
}
