import { glyphs } from "../../render/glyphs";
import type { Power } from "./types";

/** First match wins, so the specific rules come before the general ones. */
const rules: [test: RegExp, glyph: string][] = [
  [
    /ancestral being|ancestral line|ancestral power|aumakua|the founders/,
    "ancestors",
  ],
  [/the country|its sites|belonging to place|obligation to place/, "earth"],
  [/creator|supreme being|the maker|first cause|reality and order/, "star"],
  [/life force|vital force|mauri|the animating/, "breath"],
  [
    /gathering place|the meeting|the square|village centre|village center/,
    "crowd",
  ],
  [/immortal|longevity|transcend|alchemy|paradise/, "spiral"],
  [/sage|virtue|filial|moral|ethic|teaching of the/, "book"],
  [/niche|the shelf|the corner of the house/, "shrine"],
  [/guardian spirit|tutelary|protector of the house/, "shield"],
  [/generative|potency|virility|male power/, "figure"],
  [
    /ancestor|forebear|lineage|the dead|family dead|departed|razana|mallqui/,
    "ancestors",
  ],
  [/grave|tomb|burial|cemetery|mausoleum|barrow|mound of/, "tomb"],
  [/skull|bone/, "bones"],
  [/plague|pestilence|pox|epidemic|sickness of the/, "plague"],
  [/heal|cure|medicine|physician|remedy/, "medicine-bundle"],
  [
    /childbirth|pregnan|infant|nursing|motherhood|the mother/,
    "mother-and-child",
  ],
  [/birth|fertility of women|conception/, "birth"],
  [/marriage|wedding|betroth|bind|oath|vow|covenant/, "knot"],
  [/elder|old age|seniority|the aged/, "elder"],
  [/twin/, "twins"],
  [
    /crowd|assembly|the people|congregation|community|sangha|parish|umma/,
    "crowd",
  ],
  [/\bsun\b|solar|daylight|noon|the disc/, "sun"],
  [/\bmoon\b|lunar|month/, "moon"],
  [/\bstar\b|constellation|zodiac|the heavens above/, "star"],
  [/eclipse/, "eclipse"],
  [/comet|omen in the sky/, "comet"],
  [/dawn|sunrise|morning/, "dawn"],
  [/night|darkness|the dark/, "night"],
  [/thunder|lightning/, "thunder"],
  [/storm|tempest|hurricane|typhoon|cyclone/, "storm"],
  [/\brain\b|monsoon|drought/, "rain"],
  [/\bsnow\b|frost|ice|winter|cold/, "snow"],
  [/\bhail\b/, "hail"],
  [/rainbow/, "rainbow"],
  [/\bcloud\b/, "cloud"],
  [/\bwind\b|breeze|the air|breath of the/, "wind"],
  [/sky|heaven|firmament|celestial|the high|cosmic|universe|creation/, "sky"],
  [/volcano|lava|the fire mountain/, "volcano"],
  [/mountain|peak|summit|cordillera|apu|the heights/, "mountain"],
  [/\bhill\b|rise|knoll|ridge/, "hill"],
  [/cliff|escarpment|crag/, "cliff"],
  [/\bcave\b|cavern|grotto|cenote|underworld|the below/, "cave"],
  [/desert|\bdune\b|sand|the waste/, "dune"],
  [/oasis/, "oasis"],
  [/standing stone|megalith|menhir|stela|the stone/, "standing-stone"],
  [/cairn|ovoo|stone heap/, "cairn"],
  [/\bsalt\b/, "salt"],
  [/\bore\b|metal|iron|copper|gold|silver|mine/, "ore"],
  [/waterfall|cataract|rapids/, "waterfall"],
  [/\blake\b|lagoon|pool|tank/, "lake"],
  [/marsh|swamp|reed|wetland|delta/, "marsh"],
  [/island|isle|atoll/, "island"],
  [/\bsea\b|ocean|tide|the deep|reef|coast|maritime|sailor/, "sea"],
  [/river|stream|the flood|the current|nile|ganges|irrigat|canal/, "river"],
  [
    /spring|the well\b|well water|water source|the waters|drinking water|water\b/,
    "spring",
  ],
  [/hearth|stove|the fire|flame|forge fire|kiln fire/, "fire"],
  [/threshold|doorway|the door|lintel|gate of the house/, "threshold"],
  [/\bgate\b|entrance|the passage|city gate/, "gate"],
  [/crossroad|the road|the path|the way|travel|journey|pilgrim/, "crossroads"],
  [/ladder|ascent|the climb|between worlds/, "ladder"],
  [/bridge|ford|crossing/, "crossroads"],
  [/house|home|the dwelling|the roof|domestic/, "house"],
  [/granary|store|harvest store|barn/, "granary"],
  [/field|furrow|plough|tilth|cultivat|farming|agricultur/, "plough"],
  [/sickle|reaping|the scythe/, "sickle"],
  [/harvest|abundance|plenty|prosperity|increase/, "grain"],
  [/maize|corn/, "maize"],
  [/rice|paddy/, "rice"],
  [/grain|barley|wheat|millet|sorghum|bread|the crop/, "grain"],
  [/olive/, "olive"],
  [/\bvine\b|wine|grape/, "vine"],
  [/\bpalm\b|date palm|coconut/, "palm"],
  [/gourd|calabash|melon/, "gourd"],
  [/\broot\b|tuber|yam|cassava/, "root"],
  [/\bseed\b|sowing|the germ/, "seed"],
  [/flower|blossom|bloom/, "flower"],
  [/lotus/, "lotus"],
  [/forest|grove|wood|jungle|the trees|sacred tree|the tree/, "tree"],
  [/\bbee\b|honey/, "bee"],
  [/cattle|cow|bull|ox|herd|the byre|livestock/, "cattle"],
  [/sheep|flock|the fleece|ram\b|lamb/, "sheep"],
  [/\bgoat\b/, "goat"],
  [/\bpig\b|boar|swine/, "pig"],
  [/\bdog\b|hound/, "dog"],
  [/horse|mare|stallion|the rider/, "horse"],
  [/camel/, "camel"],
  [/elephant/, "elephant"],
  [/jaguar|puma|leopard|the great cat|lion|tiger/, "jaguar"],
  [/bear\b/, "bear"],
  [/\bwolf\b|coyote|fox/, "wolf"],
  [/\bdeer\b|elk|caribou|reindeer|antelope|the stag/, "deer"],
  [/eagle|hawk|falcon|the great bird/, "eagle"],
  [/\bowl\b/, "owl"],
  [/raven|crow|magpie/, "raven"],
  [/\bbird\b|feather|winged/, "bird"],
  [/\bfish\b|fishing|the catch|whale/, "fish"],
  [/turtle|tortoise/, "turtle"],
  [/scorpion|spider/, "scorpion"],
  [/serpent|snake|dragon|naga/, "snake"],
  [/shell|conch|pearl/, "shell"],
  [/hunt|the chase|the quarry|game\b/, "hunt"],
  [/boat|canoe|the voyage|navigat|the paddle/, "canoe"],
  [/ship|fleet|the crossing by sea/, "boat"],
  [/net\b|fishing gear/, "net"],
  [/\brope\b|cord|binding/, "rope"],
  [/loom|weav|spinning|\bcloth\b|textile/, "loom"],
  [/thread|the spun|spindle/, "thread"],
  [/needle|sewing|stitch/, "needle"],
  [/\bpot\b|vessel|jar|urn|the bowl|pottery|ceramic/, "pot"],
  [/basket/, "basket"],
  [/mortar|grinding|the pestle/, "mortar"],
  [/knife|blade|the cut/, "knife"],
  [/anvil|smith|forge|metalwork|the hammer/, "anvil"],
  [/hammer|craft|making|artisan|builder/, "hammer"],
  [/kiln|firing|brick/, "kiln"],
  [/\blamp\b|the light|illuminat/, "lamp"],
  [/candle|taper/, "candle"],
  [/incense|smoke offering|censer/, "incense"],
  [/mirror|reflection/, "mirror"],
  [/\bcomb\b|hair/, "comb"],
  [/\bkey\b|the lock|opening/, "key"],
  [/\bbell\b|the chime/, "bell"],
  [/\bdrum\b/, "drum"],
  [/flute|pipe|music|song|the singer/, "flute"],
  [/mask|masquerade|the danced/, "mask"],
  [/\bbed\b|sleep|rest\b/, "bed"],
  [/cradle|the infant's/, "cradle"],
  [/dream|vision|trance/, "dream"],
  [/breath|the spirit within|soul/, "breath"],
  [/shadow|the double/, "shadow"],
  [/\bveil\b|the hidden|mystery|secret/, "veil"],
  [/spiral|the turning|cycle|rebirth|reincarnat/, "spiral"],
  [/\bmaze\b|labyrinth/, "maze"],
  [/hourglass|time|the hour|age of the world/, "hourglass"],
  [/fate|destiny|fortune|luck|the lot/, "scales-of-fate"],
  [/heart|love|desire|passion/, "heart"],
  [/wound|injury|the scar/, "wound"],
  [/footprint|the track/, "footprint"],
  [/\begg\b/, "egg"],
  [/altar|offering|sacrifice|libation|the gift/, "altar"],
  [/offering bowl|the bowl of/, "offering-bowl"],
  [/temple|the great house of|sanctuary/, "temple"],
  [/church|cathedral|chapel|the parish/, "cross"],
  [/mosque|minaret|the call to prayer/, "minaret"],
  [/stupa|pagoda|the relic mound/, "stupa"],
  [/shrine|the niche|household shrine/, "shrine"],
  [/pillar|column|the post/, "pillar"],
  [/tower|the high place built/, "tower"],
  [/relic|the remains of the saint/, "relic"],
  [/\bicon\b|the image|the painted/, "icon"],
  [/beads|rosary|prayer count/, "beads"],
  [/cross|christ|the crucified|trinity|gospel/, "cross"],
  [/crescent|allah|the prophet|quran|qur'an|sunnah|islam/, "crescent"],
  [/wheel|dharma|the teaching|buddha|nirvana|enlighten/, "wheel"],
  [/scroll|the written|manuscript|writing|reckon|record|scribe/, "scroll"],
  [/\bbook\b|scripture|the word|vedas|torah|sutra|canon/, "book"],
  [/tablet|the law|commandment|inscribed/, "tablet"],
  [/scales|weigh|judge|judgement|justice/, "scales"],
  [/\bcrown\b|king|queen|emperor|sovereign|monarch|royal/, "crown"],
  [/throne|the seat of|court\b/, "throne"],
  [/sceptre|scepter|the staff of office/, "sceptre"],
  [/\bstaff\b|the walking|the shepherd's/, "staff"],
  [/sword|war|battle|army|soldier|conquest|victory/, "sword"],
  [/shield|defence|defense|protect|guardian|warden|safety/, "shield"],
  [/spear|the hunt weapon|arrow|bow\b/, "spear"],
  [/\bcoin\b|trade|market|wealth|merchant|commerce|money/, "coin"],
  [/\beye\b|envy|the gaze|watching|the evil/, "eye"],
  [/\bhand\b|the touch|blessing|benediction/, "hand"],
  [/figure|the person|the self|individual/, "figure"],
  [/earth|land|soil|ground|territory|the place|boundary/, "earth"],
];

const matched = new Map<string, string>();

/** A shared glyph chosen by what the power is for. Two thousand powers cannot
 * each have their own art, and most of them want the same dozen pictures. */
export function glyphForPower(power: Power): string {
  const name = power.name.toLowerCase(),
    key = `${name} ${power.domain}`.toLowerCase();
  const cached = matched.get(key);
  if (cached) return cached;
  // What a power is called beats what it is for: "the waters, healing" is
  // water before it is medicine.
  const found =
    rules.find(([test]) => test.test(name))?.[1] ??
    rules.find(([test]) => test.test(key))?.[1] ??
    (power.rank === "paramount"
      ? "sun"
      : power.rank === "major"
        ? "shrine"
        : "house");
  const glyph = glyphs[found] ? found : "shrine";
  matched.set(key, glyph);
  return glyph;
}
export const iconRules = rules;
