// Generated by scripts/derive-officiants.ts from each belief system's own
// `specialist` sentence. Do not edit by hand; correct the sentence, or
// override the system in scripts/data/officiants.json, and re-run.
import type { Officiant } from "./types";

export const officiantsBySystem: Readonly<Record<string, readonly Officiant[]>> = {
  "andean-foragers": [
    { tier: "household", label: "Eldest", serves: "local", weight: 40 },
    { tier: "local", label: "Shaman", serves: "local", weight: 14 },
  ],
  "andean-regional-states": [
    { tier: "temple", label: "Temple priest", serves: "major", weight: 5 },
    { tier: "local", label: "Curaca", serves: "local", weight: 14 },
    { tier: "local", label: "Ayllu head", serves: "local", weight: 14 },
  ],
  "chavin-horizon": [
    { tier: "temple", label: "Temple attendant", serves: "major", weight: 5 },
    { tier: "household", label: "Family elder", serves: "local", weight: 40 },
  ],
  "moche-coast": [
    { tier: "local", label: "Village lord", serves: "local", weight: 14 },
    { tier: "temple", label: "War priest", serves: "major", weight: 5 },
    { tier: "household", label: "Family elder", serves: "local", weight: 40 },
  ],
  "nazca-coast": [
    { tier: "local", label: "Curaca", serves: "local", weight: 14 },
  ],
  "tiwanaku-altiplano": [
    { tier: "paramount", label: "State priest", serves: "paramount", weight: 1 },
    { tier: "local", label: "Curaca", serves: "local", weight: 14 },
    { tier: "household", label: "Family head", serves: "local", weight: 40 },
  ],
  "inca-state": [
    { tier: "paramount", label: "State priest", serves: "paramount", weight: 1 },
    { tier: "temple", label: "Temple attendant", serves: "major", weight: 5 },
    { tier: "local", label: "Curaca", serves: "local", weight: 14 },
    { tier: "household", label: "Household head", serves: "local", weight: 40 },
  ],
  "inca-village": [
    { tier: "local", label: "Curaca", serves: "local", weight: 14 },
    { tier: "local", label: "Elder", serves: "local", weight: 14 },
    { tier: "household", label: "Household head", serves: "local", weight: 40 },
  ],
  "colonial-syncretism": [
    { tier: "temple", label: "Catholic priest", serves: "major", weight: 5 },
    { tier: "local", label: "Curaca", serves: "local", weight: 14 },
    { tier: "local", label: "Elder", serves: "local", weight: 14 },
  ],
  "andean-village-modern": [
    { tier: "temple", label: "Catholic priest", serves: "major", weight: 5 },
    { tier: "local", label: "Curaca", serves: "local", weight: 14 },
    { tier: "local", label: "Elder woman", serves: "local", weight: 14 },
    { tier: "household", label: "Family head", serves: "local", weight: 40 },
  ],
  "aboriginal-australia-general": [
    { tier: "local", label: "Initiated knowledge holder", serves: "local", weight: 14 },
    { tier: "household", label: "Senior kin", serves: "local", weight: 40 },
  ],
  "oceanic-maritime-societies-early": [
    { tier: "local", label: "Elder", serves: "local", weight: 14 },
    { tier: "local", label: "Experienced navigator", serves: "local", weight: 14 },
  ],
  "papuan-highlands-early": [
    { tier: "local", label: "Initiated man", serves: "local", weight: 14 },
    { tier: "household", label: "Oldest of the men's house", serves: "local", weight: 40 },
  ],
  "early-melanesia-lapita": [
    { tier: "local", label: "Navigator", serves: "local", weight: 14 },
  ],
  "vanuatu-new-caledonia-tradition": [
    { tier: "local", label: "Chief", serves: "local", weight: 14 },
    { tier: "local", label: "Elder", serves: "local", weight: 14 },
  ],
  "samoan-polynesian": [
    { tier: "local", label: "Chief", serves: "local", weight: 14 },
    { tier: "local", label: "Specialist", serves: "local", weight: 14 },
    { tier: "local", label: "Keeper of genealogy", serves: "local", weight: 14 },
  ],
  "hawaiian-precontact": [
    { tier: "local", label: "Kāhuna : healer", serves: "local", weight: 14 },
    { tier: "temple", label: "Priest of the heiau", serves: "major", weight: 5 },
    { tier: "local", label: "Keeper of genealogy", serves: "local", weight: 14 },
  ],
  "maori-aotearoa-precontact": [
    { tier: "local", label: "Tohunga (specialist", serves: "local", weight: 14 },
    { tier: "temple", label: "Priest): tohunga whakairo", serves: "major", weight: 5 },
    { tier: "local", label: "Tohunga rongoā", serves: "local", weight: 14 },
    { tier: "local", label: "Tohunga ahi", serves: "local", weight: 14 },
  ],
  "micronesian-practice": [
    { tier: "paramount", label: "Master navigator", serves: "paramount", weight: 1 },
    { tier: "local", label: "Chief", serves: "local", weight: 14 },
  ],
  "pacific-mission-christianity": [
    { tier: "temple", label: "Pastor", serves: "major", weight: 5 },
    { tier: "temple", label: "Missionary", serves: "major", weight: 5 },
    { tier: "local", label: "Catechist", serves: "local", weight: 14 },
  ],
  "aboriginal-australia-colonial": [
    { tier: "local", label: "Elder", serves: "local", weight: 14 },
    { tier: "local", label: "Mission worker", serves: "local", weight: 14 },
    { tier: "local", label: "Catechist", serves: "local", weight: 14 },
  ],
  "samoan-tongan-early": [
    { tier: "paramount", label: "Master navigator", serves: "paramount", weight: 1 },
    { tier: "local", label: "Chief", serves: "local", weight: 14 },
    { tier: "local", label: "Keeper of genealogy", serves: "local", weight: 14 },
  ],
  "fiji-traditions": [
    { tier: "local", label: "Chief", serves: "local", weight: 14 },
    { tier: "local", label: "Elder", serves: "local", weight: 14 },
  ],
  "south-island-aotearoa": [
    { tier: "local", label: "Tohunga", serves: "local", weight: 14 },
    { tier: "local", label: "Community elder", serves: "local", weight: 14 },
    { tier: "local", label: "Specialist", serves: "local", weight: 14 },
  ],
  "neolithic-east-asia-foragers": [
    { tier: "local", label: "Ancestor speaker", serves: "local", weight: 14 },
    { tier: "household", label: "Eldest", serves: "local", weight: 40 },
  ],
  "early-bronze-farming-era": [
    { tier: "household", label: "Household head", serves: "local", weight: 40 },
    { tier: "local", label: "Village elder", serves: "local", weight: 14 },
    { tier: "local", label: "Shaman", serves: "local", weight: 14 },
  ],
  "shang-oracle": [
    { tier: "local", label: "Shaman", serves: "local", weight: 14 },
    { tier: "local", label: "Bone-reader", serves: "local", weight: 14 },
    { tier: "household", label: "Household head", serves: "local", weight: 40 },
  ],
  "zhou-heaven-rites": [
    { tier: "temple", label: "Ritual master", serves: "major", weight: 5 },
    { tier: "household", label: "Family head", serves: "local", weight: 40 },
  ],
  "warring-states-qin": [
    { tier: "local", label: "Shaman", serves: "local", weight: 14 },
    { tier: "local", label: "Diviner", serves: "local", weight: 14 },
    { tier: "household", label: "Household head", serves: "local", weight: 40 },
  ],
  "han-popular": [
    { tier: "temple", label: "Ritual master", serves: "major", weight: 5 },
    { tier: "household", label: "Household head", serves: "local", weight: 40 },
  ],
  "six-dynasties-buddhism": [
    { tier: "temple", label: "Buddhist monk", serves: "major", weight: 5 },
    { tier: "temple", label: "Nun", serves: "major", weight: 5 },
    { tier: "household", label: "Household head", serves: "local", weight: 40 },
  ],
  "tang-syncretism": [
    { tier: "temple", label: "Monk", serves: "major", weight: 5 },
    { tier: "temple", label: "Daoist priest", serves: "major", weight: 5 },
    { tier: "local", label: "Ritual specialist", serves: "local", weight: 14 },
    { tier: "household", label: "Household head", serves: "local", weight: 40 },
  ],
  "song-ming-pantheon": [
    { tier: "temple", label: "Daoist priest", serves: "major", weight: 5 },
    { tier: "temple", label: "Monk", serves: "major", weight: 5 },
    { tier: "household", label: "Household head", serves: "local", weight: 40 },
  ],
  "late-imperial-village": [
    { tier: "local", label: "Spirit medium", serves: "local", weight: 14 },
    { tier: "household", label: "Household head", serves: "local", weight: 40 },
    { tier: "household", label: "Family elder", serves: "local", weight: 40 },
  ],
  "korean-three-kingdoms": [
    { tier: "local", label: "Shaman", serves: "local", weight: 14 },
    { tier: "local", label: "Spirit medium", serves: "local", weight: 14 },
    { tier: "household", label: "Household head", serves: "local", weight: 40 },
  ],
  "koryo-buddhism": [
    { tier: "temple", label: "Buddhist monk", serves: "major", weight: 5 },
    { tier: "temple", label: "Nun", serves: "major", weight: 5 },
    { tier: "local", label: "Shaman", serves: "local", weight: 14 },
  ],
  "heian-shinto-buddhism": [
    { tier: "temple", label: "Shrine priest", serves: "major", weight: 5 },
    { tier: "temple", label: "Buddhist monk", serves: "major", weight: 5 },
    { tier: "household", label: "Household head", serves: "local", weight: 40 },
  ],
  "medieval-japan-pure-land": [
    { tier: "temple", label: "Pure Land monk", serves: "major", weight: 5 },
    { tier: "temple", label: "Local shrine priest", serves: "major", weight: 5 },
    { tier: "household", label: "Household head", serves: "local", weight: 40 },
  ],
  "tokugawa-household-buddhism": [
    { tier: "temple", label: "Registered parish priest", serves: "major", weight: 5 },
    { tier: "household", label: "Household head", serves: "local", weight: 40 },
    { tier: "household", label: "Family elder", serves: "local", weight: 40 },
  ],
  "joseon-korea-confucianism": [
    { tier: "local", label: "Confucian scholar", serves: "local", weight: 14 },
    { tier: "local", label: "Ritual specialist", serves: "local", weight: 14 },
    { tier: "local", label: "Shaman", serves: "local", weight: 14 },
  ],
  "ryukyu-ancestor-kami": [
    { tier: "local", label: "Female ritual specialist", serves: "local", weight: 14 },
    { tier: "household", label: "Household elder", serves: "local", weight: 40 },
  ],
  "southwest-china-farming": [
    { tier: "local", label: "Village elder", serves: "local", weight: 14 },
    { tier: "local", label: "Shaman", serves: "local", weight: 14 },
    { tier: "household", label: "Household head", serves: "local", weight: 40 },
  ],
  "tibetan-plateau-practice": [
    { tier: "local", label: "Shaman", serves: "local", weight: 14 },
    { tier: "local", label: "Ritual specialist", serves: "local", weight: 14 },
    { tier: "household", label: "Household head", serves: "local", weight: 40 },
  ],
  "modern-east-asia": [
    { tier: "temple", label: "Temple priest", serves: "major", weight: 5 },
    { tier: "local", label: "Daoist or Buddhist ritual specialist", serves: "local", weight: 14 },
    { tier: "household", label: "Family elder", serves: "local", weight: 40 },
  ],
  "regional-foragers-deep": [
    { tier: "local", label: "Trance healer", serves: "local", weight: 14 },
    { tier: "household", label: "Eldest", serves: "local", weight: 40 },
  ],
  "san-forager-practice": [
    { tier: "local", label: "Trance dancer", serves: "local", weight: 14 },
    { tier: "household", label: "Eldest", serves: "local", weight: 40 },
  ],
  "early-farmers-herders": [
    { tier: "household", label: "Lineage elder", serves: "local", weight: 40 },
    { tier: "local", label: "Smith", serves: "local", weight: 14 },
  ],
  "early-bantu-iron-age": [
    { tier: "household", label: "Lineage elder", serves: "local", weight: 40 },
    { tier: "local", label: "Smith", serves: "local", weight: 14 },
  ],
  "iron-age-development": [
    { tier: "household", label: "Lineage head", serves: "local", weight: 40 },
    { tier: "local", label: "Settlement elder", serves: "local", weight: 14 },
    { tier: "local", label: "Healer", serves: "local", weight: 14 },
    { tier: "local", label: "Smith", serves: "local", weight: 14 },
  ],
  "aksumite-pre-christian": [
    { tier: "household", label: "King", serves: "local", weight: 40 },
    { tier: "local", label: "Local elder", serves: "local", weight: 14 },
  ],
  "ethiopian-orthodox-christian": [
    { tier: "temple", label: "Priest ordained", serves: "major", weight: 5 },
    { tier: "temple", label: "Monk", serves: "major", weight: 5 },
  ],
  "early-swahili-coast": [
    { tier: "temple", label: "Imam", serves: "major", weight: 5 },
  ],
  "great-zimbabwe-shona": [
    { tier: "household", label: "King's medium", serves: "local", weight: 40 },
    { tier: "local", label: "Keeper of the sacred rock", serves: "local", weight: 14 },
  ],
  "medieval-kingdoms": [
    { tier: "household", label: "King or paramount chief", serves: "local", weight: 40 },
    { tier: "local", label: "Healer", serves: "local", weight: 14 },
    { tier: "temple", label: "Shrine keeper", serves: "major", weight: 5 },
  ],
  "nguni-ancestor-veneration": [
    { tier: "local", label: "Inyanga", serves: "local", weight: 14 },
    { tier: "local", label: "Isangoma", serves: "local", weight: 14 },
    { tier: "household", label: "Lineage elder", serves: "local", weight: 40 },
  ],
  "zulu-mfecane-era": [
    { tier: "household", label: "King's izinyanga", serves: "local", weight: 40 },
    { tier: "local", label: "Diviner", serves: "local", weight: 14 },
  ],
  "maasai-pastoral-practice": [
    { tier: "local", label: "Age-set elder", serves: "local", weight: 14 },
  ],
  "malagasy-razana-practice": [
    { tier: "household", label: "Elder of the lineage", serves: "local", weight: 40 },
    { tier: "local", label: "Keeper of the tomb", serves: "local", weight: 14 },
  ],
  "buganda-balubaale": [
    { tier: "local", label: "Healer", serves: "local", weight: 14 },
  ],
  "early-modern-regional-states": [
    { tier: "local", label: "Chief", serves: "local", weight: 14 },
    { tier: "household", label: "King", serves: "local", weight: 40 },
    { tier: "local", label: "Healer", serves: "local", weight: 14 },
    { tier: "local", label: "Diviner", serves: "local", weight: 14 },
    { tier: "local", label: "Prophetic medium", serves: "local", weight: 14 },
  ],
  "egypt-new-kingdom": [
    { tier: "temple", label: "Temple priest", serves: "major", weight: 5 },
    { tier: "household", label: "Household head", serves: "local", weight: 40 },
  ],
  "europe-foragers": [
    { tier: "local", label: "Elder or shaman know the song", serves: "local", weight: 14 },
  ],
  "europe-early-farming": [
    { tier: "temple", label: "Elder or priest", serves: "major", weight: 5 },
  ],
  "aegean-bronze-age": [
    { tier: "paramount", label: "Palace priest", serves: "paramount", weight: 1 },
    { tier: "local", label: "Shrine keeper", serves: "local", weight: 14 },
    { tier: "household", label: "Household head", serves: "local", weight: 40 },
  ],
  "classical-greek": [
    { tier: "temple", label: "Temple priest", serves: "major", weight: 5 },
    { tier: "household", label: "Household head", serves: "local", weight: 40 },
  ],
  "republican-roman": [
    { tier: "paramount", label: "Pontifex", serves: "paramount", weight: 1 },
    { tier: "temple", label: "Flamen", serves: "major", weight: 5 },
    { tier: "local", label: "Local cult priest", serves: "local", weight: 14 },
    { tier: "household", label: "Household head", serves: "local", weight: 40 },
  ],
  "imperial-roman": [
    { tier: "temple", label: "Imperial priest", serves: "major", weight: 5 },
    { tier: "household", label: "Household head", serves: "local", weight: 40 },
  ],
  "celtic-britain": [
    { tier: "local", label: "Druid or bard", serves: "local", weight: 14 },
    { tier: "local", label: "Chieftain call", serves: "local", weight: 14 },
  ],
  "celtic-gaul": [
    { tier: "temple", label: "Druid", serves: "major", weight: 5 },
    { tier: "local", label: "Vate", serves: "local", weight: 14 },
    { tier: "local", label: "Bard", serves: "local", weight: 14 },
    { tier: "household", label: "Household head", serves: "local", weight: 40 },
  ],
  "norse-scandinavia": [
    { tier: "local", label: "Often the chieftain or a woman", serves: "local", weight: 14 },
  ],
  "slavic-paganism": [
    { tier: "temple", label: "Priest or chieftain", serves: "major", weight: 5 },
  ],
  "frankish-christian-early": [
    { tier: "temple", label: "Priest", serves: "major", weight: 5 },
    { tier: "temple", label: "Abbot or bishop", serves: "major", weight: 5 },
  ],
  "catholic-high-medieval": [
    { tier: "temple", label: "Parish priest", serves: "major", weight: 5 },
    { tier: "temple", label: "Monk", serves: "major", weight: 5 },
  ],
  "reformation-protestant": [
    { tier: "temple", label: "Minister", serves: "major", weight: 5 },
  ],
  "orthodox-russia": [
    { tier: "temple", label: "Orthodox priest", serves: "major", weight: 5 },
    { tier: "temple", label: "Monk", serves: "major", weight: 5 },
  ],
  "catholic-early-modern": [
    { tier: "temple", label: "Priest", serves: "major", weight: 5 },
  ],
  "european-enlightenment": [
    { tier: "temple", label: "Priest", serves: "major", weight: 5 },
    { tier: "household", label: "Educated household head", serves: "local", weight: 40 },
  ],
  "european-industrial": [
    { tier: "temple", label: "Priest", serves: "major", weight: 5 },
    { tier: "local", label: "Teacher", serves: "local", weight: 14 },
    { tier: "local", label: "Doctor", serves: "local", weight: 14 },
  ],
  "byzantine-orthodox": [
    { tier: "temple", label: "Parish priest", serves: "major", weight: 5 },
    { tier: "temple", label: "Monk", serves: "major", weight: 5 },
  ],
  "post-roman-christian-mediterranean": [
    { tier: "temple", label: "Priest", serves: "major", weight: 5 },
    { tier: "temple", label: "Monk", serves: "major", weight: 5 },
  ],
  "latin-christendom-late-medieval": [
    { tier: "temple", label: "Parish priest", serves: "major", weight: 5 },
  ],
  "middle-period-americas": [
    { tier: "local", label: "Elder", serves: "local", weight: 14 },
    { tier: "local", label: "Healer", serves: "local", weight: 14 },
  ],
  "early-complex-americas": [
    { tier: "temple", label: "Priest", serves: "major", weight: 5 },
  ],
  "historic-contact-americas": [
    { tier: "local", label: "Healer", serves: "local", weight: 14 },
    { tier: "local", label: "Shaman", serves: "local", weight: 14 },
    { tier: "local", label: "Elder", serves: "local", weight: 14 },
    { tier: "local", label: "Ceremonial leader", serves: "local", weight: 14 },
  ],
  "ancestral-puebloan": [
    { tier: "local", label: "Elder", serves: "local", weight: 14 },
  ],
  "california-foragers": [
    { tier: "local", label: "Elder", serves: "local", weight: 14 },
    { tier: "local", label: "Healer", serves: "local", weight: 14 },
  ],
  "california-coast-maritime": [
    { tier: "local", label: "Elder", serves: "local", weight: 14 },
  ],
  "great-basin-foragers": [
    { tier: "local", label: "Elder", serves: "local", weight: 14 },
  ],
  "eastern-woodlands-early": [
    { tier: "local", label: "Elder", serves: "local", weight: 14 },
    { tier: "local", label: "Healer", serves: "local", weight: 14 },
  ],
  "mississippian-southeast": [
    { tier: "temple", label: "Priest serving the mound temple", serves: "major", weight: 5 },
    { tier: "local", label: "Chief", serves: "local", weight: 14 },
  ],
  "eastern-woodlands-algonquian": [
    { tier: "local", label: "Dreamer", serves: "local", weight: 14 },
    { tier: "local", label: "Healer", serves: "local", weight: 14 },
    { tier: "household", label: "Eldest", serves: "local", weight: 40 },
  ],
  "eastern-woodlands-iroquoian": [
    { tier: "local", label: "Clan mother", serves: "local", weight: 14 },
    { tier: "local", label: "Faith keeper", serves: "local", weight: 14 },
  ],
  "great-plains-historic": [
    { tier: "local", label: "Vision seeker", serves: "local", weight: 14 },
    { tier: "local", label: "Medicine person", serves: "local", weight: 14 },
    { tier: "household", label: "Household head", serves: "local", weight: 40 },
  ],
  "northwest-coast-historic": [
    { tier: "local", label: "Shaman", serves: "local", weight: 14 },
  ],
  "subarctic-boreal": [
    { tier: "local", label: "Elder", serves: "local", weight: 14 },
  ],
  "subarctic-historic": [
    { tier: "local", label: "Shaman", serves: "local", weight: 14 },
  ],
  "arctic-thule-inuit": [
    { tier: "local", label: "Shaman", serves: "local", weight: 14 },
  ],
  "taino-caribbean": [
    { tier: "paramount", label: "Cacique", serves: "paramount", weight: 1 },
    { tier: "local", label: "Nitaino", serves: "local", weight: 14 },
    { tier: "local", label: "Behique", serves: "local", weight: 14 },
    { tier: "household", label: "Household head", serves: "local", weight: 40 },
  ],
  "amazonia-early": [
    { tier: "local", label: "Shaman", serves: "local", weight: 14 },
  ],
  "amazonian-ethnographic": [
    { tier: "local", label: "Shaman", serves: "local", weight: 14 },
  ],
  "brazil-atlantic-coast": [
    { tier: "local", label: "Shaman", serves: "local", weight: 14 },
    { tier: "local", label: "Elder", serves: "local", weight: 14 },
  ],
  "patagonian-southern-cone": [
    { tier: "local", label: "Shaman", serves: "local", weight: 14 },
  ],
  "california-historic": [
    { tier: "local", label: "Elder", serves: "local", weight: 14 },
    { tier: "local", label: "Healer", serves: "local", weight: 14 },
  ],
  "great-basin-historic": [
    { tier: "local", label: "Elder", serves: "local", weight: 14 },
    { tier: "local", label: "Healer", serves: "local", weight: 14 },
  ],
  "caribbean-historic": [
    { tier: "local", label: "Healer", serves: "local", weight: 14 },
    { tier: "local", label: "Elder maintaining tradition", serves: "local", weight: 14 },
  ],
  "inner-eurasia-foragers": [
    { tier: "local", label: "Dream-marked shaman", serves: "local", weight: 14 },
    { tier: "household", label: "Eldest", serves: "local", weight: 40 },
  ],
  "steppe-bronze-age": [
    { tier: "local", label: "Spirit-marked shaman", serves: "local", weight: 14 },
    { tier: "household", label: "Eldest", serves: "local", weight: 40 },
  ],
  "caucasus-early-peoples": [
    { tier: "local", label: "Vision-marked seer", serves: "local", weight: 14 },
    { tier: "household", label: "Clan eldest", serves: "local", weight: 40 },
  ],
  "volga-uralic-peoples": [
    { tier: "local", label: "Shaman", serves: "local", weight: 14 },
    { tier: "local", label: "Herb-woman", serves: "local", weight: 14 },
    { tier: "household", label: "Eldest", serves: "local", weight: 40 },
  ],
  "scythian-practice": [
    { tier: "temple", label: "Priestess oracle", serves: "major", weight: 5 },
    { tier: "household", label: "King", serves: "local", weight: 40 },
  ],
  "post-scythian-steppe": [
    { tier: "local", label: "Shaman", serves: "local", weight: 14 },
    { tier: "local", label: "Chief", serves: "local", weight: 14 },
  ],
  "xiongnu-steppe": [
    { tier: "local", label: "Shaman", serves: "local", weight: 14 },
  ],
  "turkic-tengrism": [
    { tier: "local", label: "Shaman", serves: "local", weight: 14 },
  ],
  "sogdian-zoroastrianism": [
    { tier: "temple", label: "Fire priest", serves: "major", weight: 5 },
  ],
  "tibetan-bon": [
    { tier: "temple", label: "Bon po priest or shaman", serves: "major", weight: 5 },
    { tier: "local", label: "Head of a clan", serves: "local", weight: 14 },
  ],
  "siberian-shamanism": [
    { tier: "local", label: "Shaman", serves: "local", weight: 14 },
  ],
  "central-asian-islam": [
    { tier: "local", label: "Sufi teacher", serves: "local", weight: 14 },
    { tier: "temple", label: "Keeper of a shrine or holy site", serves: "major", weight: 5 },
  ],
  "mongol-chinggis": [
    { tier: "local", label: "Shaman", serves: "local", weight: 14 },
  ],
  "siberian-russian-hybrid": [
    { tier: "temple", label: "Orthodox priest", serves: "major", weight: 5 },
    { tier: "local", label: "Elder or shaman continue", serves: "local", weight: 14 },
  ],
  "tarim-basin-peoples": [
    { tier: "temple", label: "Monk", serves: "major", weight: 5 },
    { tier: "local", label: "Or an elder", serves: "local", weight: 14 },
  ],
  "post-mongol-steppe": [
    { tier: "local", label: "Shaman", serves: "local", weight: 14 },
    { tier: "local", label: "Leader", serves: "local", weight: 14 },
  ],
  "far-northeast-siberia": [
    { tier: "local", label: "Shaman", serves: "local", weight: 14 },
  ],
  "volga-river-peoples-medieval": [
    { tier: "household", label: "Eldest", serves: "local", weight: 40 },
    { tier: "temple", label: "Priest", serves: "major", weight: 5 },
  ],
  "mesoamerican-foragers": [
    { tier: "local", label: "Elder", serves: "local", weight: 14 },
    { tier: "local", label: "Weather. Shaman journey", serves: "local", weight: 14 },
  ],
  "early-mesoamerican-farming": [
    { tier: "local", label: "Elder", serves: "local", weight: 14 },
    { tier: "household", label: "Lineage head direct ritual. Shaman", serves: "local", weight: 40 },
  ],
  "olmec-early": [
    { tier: "local", label: "Shaman", serves: "local", weight: 14 },
    { tier: "household", label: "Lineage leader", serves: "local", weight: 40 },
  ],
  "maya-preclassic": [
    { tier: "local", label: "Shaman", serves: "local", weight: 14 },
  ],
  "maya-classic": [
    { tier: "paramount", label: "K'uhul ajaw", serves: "paramount", weight: 1 },
    { tier: "temple", label: "Temple priest", serves: "major", weight: 5 },
    { tier: "temple", label: "Ah kin", serves: "major", weight: 5 },
    { tier: "household", label: "Household head", serves: "local", weight: 40 },
  ],
  "central-american-traditions": [
    { tier: "local", label: "Shaman", serves: "local", weight: 14 },
    { tier: "household", label: "Divination. Lineage elder", serves: "local", weight: 40 },
  ],
  "teotihuacan-classical": [
    { tier: "temple", label: "Priest-administrator", serves: "major", weight: 5 },
  ],
  "zapotec-montealbán": [
    { tier: "temple", label: "Priest", serves: "major", weight: 5 },
    { tier: "local", label: "Elder", serves: "local", weight: 14 },
  ],
  "west-mexican-traditions": [
    { tier: "local", label: "Shaman", serves: "local", weight: 14 },
    { tier: "household", label: "Elder serve household", serves: "local", weight: 40 },
    { tier: "household", label: "Lineage shrine", serves: "local", weight: 40 },
  ],
  "mexica-aztec": [
    { tier: "paramount", label: "High priest", serves: "paramount", weight: 1 },
    { tier: "temple", label: "Tlamacazqui", serves: "major", weight: 5 },
    { tier: "local", label: "Calpulli priest", serves: "local", weight: 14 },
    { tier: "household", label: "Household head", serves: "local", weight: 40 },
  ],
  "maya-postclassic": [
    { tier: "temple", label: "Ah kin", serves: "major", weight: 5 },
    { tier: "local", label: "Shaman", serves: "local", weight: 14 },
    { tier: "household", label: "Household head", serves: "local", weight: 40 },
  ],
  "colonial-mesoamerica-syncretic": [
    { tier: "temple", label: "Spanish priest", serves: "major", weight: 5 },
    { tier: "local", label: "Shaman", serves: "local", weight: 14 },
  ],
  "modern-mesoamerica": [
    { tier: "temple", label: "Catholic priest", serves: "major", weight: 5 },
    { tier: "local", label: "Indigenou shaman", serves: "local", weight: 14 },
    { tier: "household", label: "Family elder each", serves: "local", weight: 40 },
  ],
  "prehistoric-foragers": [
    { tier: "local", label: "Elder or shaman", serves: "local", weight: 14 },
  ],
  "early-farming-neolithic": [
    { tier: "household", label: "Household head", serves: "local", weight: 40 },
    { tier: "local", label: "Elder woman", serves: "local", weight: 14 },
  ],
  "vedic-early": [
    { tier: "local", label: "Keeper", serves: "local", weight: 14 },
  ],
  "vedic-late-upanishadic": [
    { tier: "local", label: "Forest sage", serves: "local", weight: 14 },
  ],
  "early-buddhism": [
    { tier: "temple", label: "Bhikkhu", serves: "major", weight: 5 },
    { tier: "temple", label: "Bhikkhuni", serves: "major", weight: 5 },
    { tier: "household", label: "Lay householder", serves: "local", weight: 40 },
  ],
  "jainism": [
    { tier: "temple", label: "Jain monk or nun", serves: "major", weight: 5 },
  ],
  "gupta-puranic": [
    { tier: "temple", label: "Brahmin priest", serves: "major", weight: 5 },
  ],
  "tamil-shaivism": [
    { tier: "temple", label: "Shaiva priest", serves: "major", weight: 5 },
    { tier: "temple", label: "Keeper of the temple", serves: "major", weight: 5 },
  ],
  "krishna-vaishnavism": [
    { tier: "temple", label: "Temple priest", serves: "major", weight: 5 },
    { tier: "local", label: "Itinerant singer of Krishna's tale", serves: "local", weight: 14 },
  ],
  "sikh-gurus": [
    { tier: "paramount", label: "Guru", serves: "paramount", weight: 1 },
    { tier: "temple", label: "Granthi", serves: "major", weight: 5 },
    { tier: "household", label: "Household head", serves: "local", weight: 40 },
  ],
  "village-goddess-practice": [
    { tier: "temple", label: "Village priestess or priest", serves: "major", weight: 5 },
  ],
  "theravada-sri-lanka": [
    { tier: "temple", label: "Bhikkhu", serves: "major", weight: 5 },
    { tier: "temple", label: "Monastery abbot", serves: "major", weight: 5 },
    { tier: "household", label: "Lay householder", serves: "local", weight: 40 },
  ],
  "himalayan-newar": [
    { tier: "temple", label: "Brahmin priest", serves: "major", weight: 5 },
    { tier: "local", label: "Local shaman or juju", serves: "local", weight: 14 },
  ],
  "indo-islamic-sufi": [
    { tier: "temple", label: "Pir", serves: "major", weight: 5 },
    { tier: "temple", label: "Qazi", serves: "major", weight: 5 },
    { tier: "local", label: "Murid", serves: "local", weight: 14 },
    { tier: "household", label: "Household head", serves: "local", weight: 40 },
  ],
  "hindu-reform": [
    { tier: "temple", label: "Brahmin reformer", serves: "major", weight: 5 },
    { tier: "local", label: "Lay preacher", serves: "local", weight: 14 },
    { tier: "household", label: "Household head", serves: "local", weight: 40 },
  ],
  "maritime-island-practice": [
    { tier: "local", label: "Pilot", serves: "local", weight: 14 },
    { tier: "local", label: "Elder", serves: "local", weight: 14 },
    { tier: "local", label: "Keeper of the wind", serves: "local", weight: 14 },
  ],
  "deccan-regional": [
    { tier: "local", label: "Village headman", serves: "local", weight: 14 },
    { tier: "temple", label: "Priestess of the local goddess", serves: "major", weight: 5 },
  ],
  "northeast-regional": [
    { tier: "local", label: "Elder", serves: "local", weight: 14 },
    { tier: "local", label: "Shaman", serves: "local", weight: 14 },
    { tier: "local", label: "Keeper of the way of the forest", serves: "local", weight: 14 },
  ],
  "bengal-specific": [
    { tier: "temple", label: "Brahmin priest", serves: "major", weight: 5 },
  ],
  "se-asia-early-foragers": [
    { tier: "household", label: "Eldest tracker", serves: "local", weight: 40 },
    { tier: "local", label: "Keeper of path", serves: "local", weight: 14 },
  ],
  "se-asia-austronesian-animism": [
    { tier: "local", label: "Hyang speaker", serves: "local", weight: 14 },
    { tier: "household", label: "Eldest", serves: "local", weight: 40 },
  ],
  "se-asia-early-hindu-buddhism": [
    { tier: "paramount", label: "Court priest", serves: "paramount", weight: 1 },
    { tier: "temple", label: "Monk", serves: "major", weight: 5 },
    { tier: "local", label: "Village elder", serves: "local", weight: 14 },
  ],
  "se-asia-funan-hindu-buddhism": [
    { tier: "local", label: "Village elder", serves: "local", weight: 14 },
  ],
  "se-asia-angkorian-devaraja": [
    { tier: "temple", label: "Buddhist monk", serves: "major", weight: 5 },
    { tier: "local", label: "Village headmen", serves: "local", weight: 14 },
  ],
  "se-asia-theravada-burma": [
    { tier: "temple", label: "Monk", serves: "major", weight: 5 },
    { tier: "local", label: "Nat medium", serves: "local", weight: 14 },
    { tier: "household", label: "Household elder", serves: "local", weight: 40 },
  ],
  "se-asia-theravada-siam": [
    { tier: "temple", label: "Monk", serves: "major", weight: 5 },
    { tier: "household", label: "Household elder", serves: "local", weight: 40 },
  ],
  "se-asia-majapahit": [
    { tier: "paramount", label: "Court priest", serves: "paramount", weight: 1 },
    { tier: "temple", label: "Buddhist monk", serves: "major", weight: 5 },
    { tier: "local", label: "Village elder", serves: "local", weight: 14 },
  ],
  "se-asia-islamic-java-malay": [
    { tier: "temple", label: "Imam", serves: "major", weight: 5 },
  ],
  "se-asia-vietnamese-ancestor": [
    { tier: "household", label: "Household head", serves: "local", weight: 40 },
    { tier: "temple", label: "Kitchen shrine", serves: "major", weight: 5 },
    { tier: "temple", label: "Buddhist monk", serves: "major", weight: 5 },
    { tier: "local", label: "Medium", serves: "local", weight: 14 },
    { tier: "temple", label: "Village priest", serves: "major", weight: 5 },
  ],
  "se-asia-upland-animism": [
    { tier: "temple", label: "Village priest", serves: "major", weight: 5 },
    { tier: "household", label: "Eldest", serves: "local", weight: 40 },
  ],
  "se-asia-philippine-anito": [
    { tier: "household", label: "Household head", serves: "local", weight: 40 },
    { tier: "local", label: "Village elder", serves: "local", weight: 14 },
  ],
  "se-asia-sulawesi-moluccas-islam": [
    { tier: "temple", label: "Imam", serves: "major", weight: 5 },
    { tier: "local", label: "Elder", serves: "local", weight: 14 },
    { tier: "local", label: "Healer", serves: "local", weight: 14 },
  ],
  "se-asia-colonial-modernization": [
    { tier: "local", label: "Teacher", serves: "local", weight: 14 },
    { tier: "temple", label: "Priest", serves: "major", weight: 5 },
    { tier: "temple", label: "Monk", serves: "major", weight: 5 },
    { tier: "local", label: "Elder", serves: "local", weight: 14 },
  ],
  "west-asia-foragers": [
    { tier: "local", label: "Elder", serves: "local", weight: 14 },
  ],
  "west-asia-early-farming": [
    { tier: "local", label: "Elder", serves: "local", weight: 14 },
  ],
  "sumerian-city-states": [
    { tier: "temple", label: "Temple priest", serves: "major", weight: 5 },
    { tier: "local", label: "Diviner", serves: "local", weight: 14 },
  ],
  "old-babylonian": [
    { tier: "temple", label: "Temple priest", serves: "major", weight: 5 },
    { tier: "household", label: "Household head", serves: "local", weight: 40 },
  ],
  "neo-assyrian": [
    { tier: "temple", label: "Temple priest", serves: "major", weight: 5 },
    { tier: "household", label: "King", serves: "local", weight: 40 },
  ],
  "levantine-canaanite": [
    { tier: "temple", label: "Priest", serves: "major", weight: 5 },
    { tier: "local", label: "Elder", serves: "local", weight: 14 },
  ],
  "israelite-judahite": [
    { tier: "paramount", label: "High priest", serves: "paramount", weight: 1 },
    { tier: "local", label: "Prophet", serves: "local", weight: 14 },
  ],
  "second-temple-judaism": [
    { tier: "temple", label: "Priest", serves: "major", weight: 5 },
    { tier: "local", label: "Sage", serves: "local", weight: 14 },
  ],
  "achaemenid-zoroastrian": [
    { tier: "local", label: "Keeper of fire", serves: "local", weight: 14 },
  ],
  "hellenistic-syria": [
    { tier: "temple", label: "Greek priest", serves: "major", weight: 5 },
    { tier: "local", label: "Local leader", serves: "local", weight: 14 },
  ],
  "sasanian-zoroastrian": [
    { tier: "temple", label: "Organized into a priesthood", serves: "major", weight: 5 },
  ],
  "pre-islamic-arabia": [
    { tier: "temple", label: "Keeper of the shrine", serves: "major", weight: 5 },
  ],
  "early-islamic": [
    { tier: "temple", label: "Imam", serves: "major", weight: 5 },
  ],
  "medieval-sunni-islam": [
    { tier: "temple", label: "Imam", serves: "major", weight: 5 },
  ],
  "coptic-orthodox": [
    { tier: "temple", label: "Priest", serves: "major", weight: 5 },
  ],
  "ottoman-sufi": [
    { tier: "temple", label: "Imam", serves: "major", weight: 5 },
  ],
  "post-1069-egypt": [
    { tier: "temple", label: "Imam", serves: "major", weight: 5 },
  ],
  "nubian-nile-islam": [
    { tier: "temple", label: "Qadi", serves: "major", weight: 5 },
    { tier: "local", label: "Sheikh", serves: "local", weight: 14 },
    { tier: "household", label: "Household head", serves: "local", weight: 40 },
  ],
  "maghreb-berber-islam": [
    { tier: "temple", label: "Marabout", serves: "major", weight: 5 },
    { tier: "local", label: "Faqih", serves: "local", weight: 14 },
    { tier: "household", label: "Household head", serves: "local", weight: 40 },
  ],
  "arabian-peninsula-broader": [
    { tier: "temple", label: "Imam", serves: "major", weight: 5 },
  ],
  "persian-sufi-islam": [
    { tier: "temple", label: "Pir", serves: "major", weight: 5 },
    { tier: "temple", label: "Qadi", serves: "major", weight: 5 },
    { tier: "local", label: "Poet", serves: "local", weight: 14 },
    { tier: "household", label: "Household head", serves: "local", weight: 40 },
  ],
  "anatolian-ottoman-islam": [
    { tier: "temple", label: "Imam", serves: "major", weight: 5 },
  ],
  "caucasus-caspian-islam": [
    { tier: "local", label: "Elder keeper of tradition", serves: "local", weight: 14 },
    { tier: "local", label: "Leader", serves: "local", weight: 14 },
  ],
  "modern-west-asia-islam": [
    { tier: "temple", label: "Imam", serves: "major", weight: 5 },
    { tier: "local", label: "Scholar interpret", serves: "local", weight: 14 },
  ],
  "west-central-foragers": [
    { tier: "local", label: "Elder", serves: "local", weight: 14 },
  ],
  "early-bantu-farmers": [
    { tier: "household", label: "Lineage elder", serves: "local", weight: 40 },
    { tier: "local", label: "Smith", serves: "local", weight: 14 },
  ],
  "regional-kingdoms-era": [
    { tier: "household", label: "King or hi designated ritual deputy", serves: "local", weight: 40 },
    { tier: "local", label: "Smith", serves: "local", weight: 14 },
    { tier: "local", label: "Market elder", serves: "local", weight: 14 },
  ],
  "islamic-trade-era": [
    { tier: "temple", label: "Imam", serves: "major", weight: 5 },
    { tier: "local", label: "Local elder", serves: "local", weight: 14 },
  ],
  "yoruba-orisha": [
    { tier: "temple", label: "Babalawo", serves: "major", weight: 5 },
    { tier: "temple", label: "Iyalorisha", serves: "major", weight: 5 },
    { tier: "household", label: "Babalorisha", serves: "local", weight: 40 },
  ],
  "igbo-chi": [
    { tier: "temple", label: "Oracle priestess", serves: "major", weight: 5 },
    { tier: "household", label: "Eldest woman", serves: "local", weight: 40 },
  ],
  "akan-suman": [
    { tier: "temple", label: "Okomfo", serves: "major", weight: 5 },
    { tier: "local", label: "Shrine attendant", serves: "local", weight: 14 },
    { tier: "household", label: "Family head", serves: "local", weight: 40 },
  ],
  "dogon-mande": [
    { tier: "local", label: "Griot", serves: "local", weight: 14 },
    { tier: "local", label: "Hogon", serves: "local", weight: 14 },
    { tier: "household", label: "Family head", serves: "local", weight: 40 },
  ],
  "hausa-bori": [
    { tier: "local", label: "Mai bori", serves: "local", weight: 14 },
    { tier: "local", label: "Magajiya", serves: "local", weight: 14 },
    { tier: "local", label: "Mother", serves: "local", weight: 14 },
  ],
  "hausa-islamic": [
    { tier: "temple", label: "Imam", serves: "major", weight: 5 },
  ],
  "fon-vodun": [
    { tier: "temple", label: "Vodunon", serves: "major", weight: 5 },
    { tier: "household", label: "Hunon", serves: "local", weight: 40 },
  ],
  "kongo-nkisi": [
    { tier: "local", label: "Nganga (healer", serves: "local", weight: 14 },
    { tier: "household", label: "Family head", serves: "local", weight: 40 },
  ],
  "central-forest-spirits": [
    { tier: "local", label: "Elder", serves: "local", weight: 14 },
  ],
  "atlantic-trade-era": [
    { tier: "local", label: "Chief", serves: "local", weight: 14 },
    { tier: "local", label: "Specialist", serves: "local", weight: 14 },
    { tier: "temple", label: "Priest", serves: "major", weight: 5 },
  ],
  "colonial-period": [
    { tier: "local", label: "Traditional elder", serves: "local", weight: 14 },
  ],
  "yoruba-nineteenth-century-christian": [
    { tier: "temple", label: "Pastor", serves: "major", weight: 5 },
    { tier: "temple", label: "Missionary", serves: "major", weight: 5 },
    { tier: "local", label: "Catechist", serves: "local", weight: 14 },
  ],
};
