import type { NameKit } from "../context-types";

const surveyPdf =
  "https://ajba.um.edu.my/index.php/JIIE/article/download/26967/12343/60324";
const perséeNames =
  "https://www.persee.fr/doc/asean_0859-9009_1998_num_1_1_1571";
const oxfordTerms =
  "https://academic.oup.com/cornell-scholarship-online/book/60129/chapter-abstract/519885067";
const burmeseHistory =
  "https://www.cambridge.org/core/books/abs/burma/observations-on-some-of-the-indigenous-sources-for-burmese-history-down-to-1886/1E1A08A01E5E024442BDC127F78214A6";

const myanmarMainland: readonly [number, number, number, number] = [
  93, 15, 98, 25,
];

export const burmeseNameKits: NameKit[] = [
  {
    id: "names-burmese-modern-1885-2026",
    label: "Burmese personal names · Myanmar mainland, 1885–2026",
    scope: {
      years: [1885, 2027],
      cultures: ["southeast-asian"],
      bounds: myanmarMainland,
    },
    format: "personal",
    names: [
      "Ba",
      "Ni",
      "Mya",
      "Sein",
      "Zaw",
      "Hla",
      "Than",
      "Thant",
      "San",
      "Soe",
      "Min",
      "Thein",
      "Lin",
      "Thaw",
      "Htun",
      "Ngwe",
      "Win",
      "Aung",
      "Po",
      "Khin",
      "Tha",
      "Cho",
      "Han",
      "Thin",
      "Ohn",
      "Aye",
      "Shwe",
      "Swe",
      "Yi",
      "Yu",
      "Kyi",
      "Maw",
      "Kyin",
      "Tin",
      "Yin",
      "May",
      "Su",
      "Nyunt",
      "Mar",
      "Ba Than",
      "Hla Hla",
      "Aung Aung",
      "Khin Khin",
      "Tin Oo",
      "Aung San",
      "Khin Kyi",
      "Aye Aye",
      "Mya Mya",
    ],
    sources: [surveyPdf, perséeNames, oxfordTerms],
    note: "Burmese names carry no hereditary surname: the whole sequence, commonly two or three syllables, is one person's name. Honorifics such as U, Daw, Ko and Ma are titles and are omitted here.",
  },
  {
    id: "names-burmese-precolonial-continuity-1100-1885",
    label: "Burmese personal names · precolonial reconstruction, 1100–1885",
    scope: {
      years: [1100, 1885],
      cultures: ["southeast-asian"],
      bounds: myanmarMainland,
    },
    format: "personal",
    names: [
      "Aung",
      "Aye",
      "Ba",
      "Hla",
      "Khin",
      "Lin",
      "Mya",
      "Ohn",
      "San",
      "Sein",
      "Shwe",
      "Soe",
      "Su",
      "Than",
      "Thant",
      "Thein",
      "Thin",
      "Tin",
      "Win",
      "Yi",
      "Zaw",
      "Aung Aung",
      "Hla Hla",
      "Khin Khin",
      "Mya Mya",
      "Aye Aye",
      "Tin Oo",
      "Ba Than",
      "Aung San",
      "Khin Kyi",
    ],
    sources: [surveyPdf, perséeNames, oxfordTerms, burmeseHistory],
    note: "Burmese naming practice is described in surveys from the twentieth century onward; these forms are carried back to the Pagan period on the strength of that continuity. Regnal and monastic names follow separate conventions not represented here.",
  },
];
