import type { CharacterAppearance } from "../../../core/character";
import type { AppearanceKit, CommunityProfile } from "../context-types";

/**
 * Reusable visual palettes. These are art direction for a bounded scenario,
 * never estimates of population frequencies and never cues for personality or
 * occupation. Community profiles below choose the palette explicitly.
 */
const paletteEvidence = (note: string) => ({ sources: [], note });

const darkHair: readonly CharacterAppearance["hair"][] = [
  "cropped",
  "curls",
  "long",
  "braid",
  "bald",
];
const variedHair: readonly CharacterAppearance["hair"][] = [
  "cropped",
  "curls",
  "bob",
  "long",
  "braid",
  "topknot",
  "bald",
];

export const appearanceKits: AppearanceKit[] = [
  {
    id: "appearance.europe-broad",
    label: "Broad European visual palette",
    ...paletteEvidence(
      "Use a varied light-to-medium complexion and hair palette for broadly scoped European scenes.",
    ),
    skin: ["#f0ceb0", "#e4b994", "#d3a16a", "#b78464", "#a97143"],
    hairColors: ["#1f1712", "#3b281c", "#6b472d", "#9a6a3f", "#c2a078"],
    hairStyles: variedHair,
    garments: [
      "tunic",
      "long-tunic",
      "robe",
      "skirt",
      "shirt",
      "coat",
      "dress",
    ],
  },
  {
    id: "appearance.english-colonial-light",
    label: "English-colonial Virginia light-complexion palette",
    ...paletteEvidence(
      "Use a light-complexion range with natural hair-color variation for the English-colonial Virginia scenario.",
    ),
    skin: ["#f0ceb0", "#edc5a3", "#e4b994", "#dcb086"],
    hairColors: [
      "#171312",
      "#3b281c",
      "#6b472d",
      "#9a6a3f",
      "#c2a078",
      "#d2b98f",
    ],
    hairStyles: variedHair,
    garments: ["tunic", "long-tunic", "robe", "skirt", "wrap"],
  },
  {
    id: "appearance.africa-broad",
    label: "Broad African visual palette",
    ...paletteEvidence(
      "Use a varied medium-brown-to-deep-brown complexion palette and predominantly dark hair for broadly scoped African scenes.",
    ),
    skin: ["#70472f", "#5a3828", "#8c5d40", "#3f2922", "#a97143"],
    hairColors: ["#171312", "#241814", "#302019", "#3b281c"],
    hairStyles: darkHair,
    garments: ["wrap", "skirt", "tunic", "long-tunic", "robe"],
  },
  {
    id: "appearance.east-asia-broad",
    label: "Broad East Asian visual palette",
    ...paletteEvidence(
      "Use a light-to-tan complexion range and uniformly black hair for broadly scoped East Asian scenes.",
    ),
    skin: ["#f0ceb0", "#e8c39c", "#e4b994", "#d3a16a", "#c18a54"],
    hairColors: ["#12100f", "#171312", "#1d1815", "#241814"],
    hairStyles: ["cropped", "bob", "long", "braid", "topknot", "bald"],
    garments: ["tunic", "long-tunic", "robe", "skirt", "wrap"],
  },
  {
    id: "appearance.south-asia-broad",
    label: "Broad South Asian visual palette",
    ...paletteEvidence(
      "Use a tan-to-deep-brown complexion range and black hair for broadly scoped South Asian scenes.",
    ),
    skin: ["#d3a16a", "#c18a54", "#b78464", "#a97143", "#8c5d40", "#70472f"],
    hairColors: ["#12100f", "#171312", "#1d1815", "#241814"],
    hairStyles: ["cropped", "curls", "long", "braid", "topknot", "bald"],
    garments: ["tunic", "long-tunic", "robe", "skirt", "wrap"],
  },
  {
    id: "appearance.southeast-asia-broad",
    label: "Broad Southeast Asian visual palette",
    ...paletteEvidence(
      "Use a light-tan-to-medium-brown complexion range and black hair for broadly scoped Southeast Asian scenes.",
    ),
    skin: ["#e4b994", "#d3a16a", "#c18a54", "#b78464", "#a97143"],
    hairColors: ["#12100f", "#171312", "#1d1815", "#241814"],
    hairStyles: ["cropped", "bob", "long", "braid", "topknot", "bald"],
    garments: ["tunic", "long-tunic", "robe", "skirt", "wrap"],
  },
  {
    id: "appearance.west-asia-broad",
    label: "Broad West Asian and Inner Eurasian visual palette",
    ...paletteEvidence(
      "Use a light-to-medium complexion range and dark hair with a little brown variation for broadly scoped West Asian, North African and Inner Eurasian scenes.",
    ),
    skin: ["#f0ceb0", "#e4b994", "#d3a16a", "#c18a54", "#b78464", "#a97143"],
    hairColors: ["#12100f", "#171312", "#241814", "#3b281c", "#4a3020"],
    hairStyles: variedHair,
    garments: ["tunic", "long-tunic", "robe", "skirt", "wrap"],
  },
  {
    id: "appearance.americas-broad",
    label: "Broad American visual palette",
    ...paletteEvidence(
      "Use a varied medium-to-deep-brown complexion palette and dark hair for broadly scoped American scenes.",
    ),
    skin: ["#a97143", "#8c5d40", "#70472f", "#b78464", "#5a3828"],
    hairColors: ["#171312", "#241814", "#302019", "#3b281c"],
    hairStyles: ["cropped", "curls", "long", "braid", "topknot", "bald"],
    garments: ["wrap", "skirt", "tunic", "long-tunic", "robe"],
  },
  {
    id: "appearance.oceania-broad",
    label: "Broad Oceania visual palette",
    ...paletteEvidence(
      "Use a varied medium-brown-to-deep-brown complexion palette and dark hair for broadly scoped Oceania scenes.",
    ),
    skin: ["#8c5d40", "#70472f", "#5a3828", "#a97143", "#b78464"],
    hairColors: ["#171312", "#241814", "#302019", "#3b281c"],
    hairStyles: darkHair,
    garments: ["wrap", "skirt", "tunic", "long-tunic"],
  },
  {
    id: "appearance.congo-basin-1000-1800",
    label: "Congo Basin, 1000–1800 visual palette",
    ...paletteEvidence(
      "For Congo Basin communities between 1000 and 1800 CE, use deep-brown complexions and dark hair with modest art variation.",
    ),
    skin: ["#3f2922", "#4d3025", "#5a3828", "#70472f", "#8c5d40"],
    hairColors: ["#12100f", "#171312", "#241814", "#302019"],
    hairStyles: darkHair,
    garments: ["wrap", "skirt", "tunic", "long-tunic"],
  },
];

const profileEvidence = (note: string, sources: string[]) => ({
  sources,
  note,
});

const fallbackEvidence = (note: string) => ({ sources: [], note });

export const communityProfiles: CommunityProfile[] = [
  {
    id: "community.haitian-rural",
    label: "Haitian rural scenario · nineteenth century",
    scope: { years: [1800, 1900], bounds: [-74.6, 18, -71.5, 20.1] },
    priority: 80,
    appearance: "appearance.africa-broad",
    livelihoods: [
      "farmer",
      "herder",
      "fisher",
      "gatherer",
      "craftsperson",
      "trader",
      "traveler",
    ],
    allowedItems: [
      "water",
      "fruit",
      "berries",
      "wood",
      "fish",
      "tool",
      "obsidian",
      "grain",
      "wool",
      "fodder",
    ],
    ...fallbackEvidence(
      "A qualified rural Haitian starting scenario. Shared farming/herding mechanics and generic grain/wool are gameplay stand-ins awaiting local crop and livestock research.",
    ),
  },
  {
    id: "community.regional-europe",
    label: "Broad European regional art fallback",
    scope: {
      years: [-100000, 2027],
      cultures: ["european"],
    },
    priority: 1,
    appearance: "appearance.europe-broad",
    livelihoods: [
      "gatherer",
      "hunter",
      "farmer",
      "herder",
      "fisher",
      "craftsperson",
      "trader",
      "traveler",
    ],
    allowedItems: [
      "water",
      "fruit",
      "berries",
      "wood",
      "fish",
      "tool",
      "obsidian",
      "grain",
    ],
    ...fallbackEvidence(
      "Provide a broad European visual and livelihood fallback wherever a European-culture community has no scoped profile, colonial towns included.",
    ),
  },
  {
    id: "community.regional-africa",
    label: "Broad African regional art fallback",
    scope: {
      years: [-100000, 2027],
      cultures: ["west-central-african", "east-southern-african"],
    },
    priority: 1,
    appearance: "appearance.africa-broad",
    livelihoods: [
      "gatherer",
      "hunter",
      "farmer",
      "herder",
      "fisher",
      "craftsperson",
      "trader",
      "traveler",
    ],
    allowedItems: [
      "water",
      "fruit",
      "berries",
      "reeds",
      "wood",
      "fish",
      "tool",
      "obsidian",
      "grain",
    ],
    ...fallbackEvidence(
      "Provide a broad African visual and livelihood fallback when no scoped community profile is available.",
    ),
  },
  {
    id: "community.regional-east-asia",
    label: "Broad East Asian regional art fallback",
    scope: {
      years: [-100000, 2027],
      cultures: [
        "east-asian",
      ],
    },
    priority: 1,
    appearance: "appearance.east-asia-broad",
    livelihoods: [
      "gatherer",
      "hunter",
      "farmer",
      "herder",
      "fisher",
      "craftsperson",
      "trader",
      "traveler",
    ],
    allowedItems: [
      "water",
      "fruit",
      "berries",
      "reeds",
      "wood",
      "fish",
      "tool",
      "obsidian",
      "grain",
    ],
    ...fallbackEvidence(
      "Provide an East Asian visual and livelihood fallback when no scoped community profile is available.",
    ),
  },
  {
    id: "community.regional-south-asia",
    label: "Broad South Asian regional art fallback",
    scope: {
      years: [-100000, 2027],
      cultures: [
        "south-asian",
      ],
    },
    priority: 1,
    appearance: "appearance.south-asia-broad",
    livelihoods: [
      "gatherer",
      "hunter",
      "farmer",
      "herder",
      "fisher",
      "craftsperson",
      "trader",
      "traveler",
    ],
    allowedItems: [
      "water",
      "fruit",
      "berries",
      "reeds",
      "wood",
      "fish",
      "tool",
      "obsidian",
      "grain",
    ],
    ...fallbackEvidence(
      "Provide a South Asian visual and livelihood fallback when no scoped community profile is available.",
    ),
  },
  {
    id: "community.regional-southeast-asia",
    label: "Broad Southeast Asian regional art fallback",
    scope: {
      years: [-100000, 2027],
      cultures: [
        "southeast-asian",
      ],
    },
    priority: 1,
    appearance: "appearance.southeast-asia-broad",
    livelihoods: [
      "gatherer",
      "hunter",
      "farmer",
      "herder",
      "fisher",
      "craftsperson",
      "trader",
      "traveler",
    ],
    allowedItems: [
      "water",
      "fruit",
      "berries",
      "reeds",
      "wood",
      "fish",
      "tool",
      "obsidian",
      "grain",
    ],
    ...fallbackEvidence(
      "Provide a Southeast Asian visual and livelihood fallback when no scoped community profile is available.",
    ),
  },
  {
    id: "community.regional-west-asia",
    label: "Broad West Asian and Inner Eurasian regional art fallback",
    scope: {
      years: [-100000, 2027],
      cultures: [
        "north-african-west-asian",
        "inner-eurasian",
      ],
    },
    priority: 1,
    appearance: "appearance.west-asia-broad",
    livelihoods: [
      "gatherer",
      "hunter",
      "farmer",
      "herder",
      "fisher",
      "craftsperson",
      "trader",
      "traveler",
    ],
    allowedItems: [
      "water",
      "fruit",
      "berries",
      "reeds",
      "wood",
      "fish",
      "tool",
      "obsidian",
      "grain",
    ],
    ...fallbackEvidence(
      "Provide a West Asian, North African and Inner Eurasian visual and livelihood fallback when no scoped community profile is available.",
    ),
  },
  {
    id: "community.regional-americas",
    label: "Broad American regional art fallback",
    scope: {
      years: [-100000, 2027],
      cultures: ["mesoamerican", "andean", "other-indigenous-american"],
    },
    priority: 1,
    appearance: "appearance.americas-broad",
    livelihoods: [
      "gatherer",
      "hunter",
      "farmer",
      "herder",
      "fisher",
      "craftsperson",
      "trader",
      "traveler",
    ],
    allowedItems: [
      "water",
      "fruit",
      "berries",
      "reeds",
      "wood",
      "fish",
      "tool",
      "obsidian",
      "grain",
    ],
    ...fallbackEvidence(
      "Provide a broad American visual and livelihood fallback when no scoped community profile is available.",
    ),
  },
  {
    id: "community.regional-oceania",
    label: "Broad Oceania regional art fallback",
    scope: {
      years: [-100000, 2027],
      cultures: ["australian-pacific"],
    },
    priority: 1,
    appearance: "appearance.oceania-broad",
    livelihoods: [
      "gatherer",
      "hunter",
      "farmer",
      "herder",
      "fisher",
      "craftsperson",
      "trader",
      "traveler",
    ],
    allowedItems: [
      "water",
      "fruit",
      "berries",
      "reeds",
      "wood",
      "fish",
      "tool",
      "obsidian",
      "lizard",
    ],
    ...fallbackEvidence(
      "Provide a broad Oceania visual and livelihood fallback when no scoped community profile is available.",
    ),
  },
  {
    id: "community.congo-basin",
    label: "Congo Basin community, 1000–1800",
    scope: {
      years: [1000, 1800],
      communities: ["local", "indigenous-local"],
    },
    priority: 80,
    appearance: "appearance.congo-basin-1000-1800",
    livelihoods: [
      "gatherer",
      "farmer",
      "fisher",
      "hunter",
      "craftsperson",
      "trader",
      "traveler",
    ],
    allowedItems: [
      "water",
      "fruit",
      "berries",
      "reeds",
      "wood",
      "fish",
      "tool",
      "obsidian",
      "grain",
    ],
    ...profileEvidence("Bounded Congo Basin visual and livelihood defaults for communities in the 1000–1800 CE window.", ["https://www.metmuseum.org/toah/ht/08/afc.html"]),
  },
  {
    id: "community.australian-interior-pre1788",
    label: "Australian interior community before 1788",
    scope: {
      years: [-100000, 1788],
      bounds: [122, -31, 138, -15],
      communities: ["local", "indigenous-local"],
    },
    priority: 90,
    appearance: "appearance.oceania-broad",
    livelihoods: ["gatherer", "hunter", "fisher", "traveler", "craftsperson"],
    allowedItems: [
      "water",
      "fruit",
      "berries",
      "reeds",
      "wood",
      "fish",
      "tool",
      "obsidian",
      "lizard",
    ],
    ...profileEvidence("Use a dark-complexion, dark-hair visual default and mobile foraging, hunting, fishing, and craft roles for an Australian interior community before 1788.", [
        "https://australian.museum/about/history/exhibitions/indigenous-australians/",
      ]),
  },
  {
    id: "community.english-colonial",
    label: "English-colonial Virginia, 1607–1750",
    scope: {
      years: [1607, 1750],
      bounds: [-83.7, 36.5, -75.2, 39.5],
      communities: ["english-colonial"],
    },
    priority: 100,
    appearance: "appearance.english-colonial-light",
    livelihoods: [
      "farmer",
      "herder",
      "craftsperson",
      "trader",
      "traveler",
      "gatherer",
      "fisher",
    ],
    allowedItems: [
      "water",
      "fruit",
      "berries",
      "wood",
      "fish",
      "tool",
      "obsidian",
      "grain",
      "bread",
      "coin",
      "flax",
      "wool",
      "fodder",
    ],
    ...profileEvidence("Use a varied light-complexion visual default and English-colonial livelihood set for Virginia settlements from 1607 to 1750.", [
        "https://www.nps.gov/jame/learn/historyculture/the-virginia-company-of-london.htm",
      ]),
  },
  {
    id: "community.indigenous-local-virginia",
    label: "Indigenous local community in Virginia, 1607–1750",
    scope: {
      years: [1000, 1750],
      bounds: [-83.7, 36.5, -75.2, 39.5],
      communities: ["indigenous-local"],
    },
    priority: 95,
    appearance: "appearance.americas-broad",
    livelihoods: [
      "farmer",
      "gatherer",
      "hunter",
      "fisher",
      "craftsperson",
      "trader",
      "traveler",
    ],
    allowedItems: [
      "water",
      "fruit",
      "berries",
      "reeds",
      "wood",
      "fish",
      "tool",
      "obsidian",
      "grain",
    ],
    ...profileEvidence("Keep an Indigenous local Virginia community distinct from the English-colonial community when both are available in the same place and dates.", [
        "https://www.nps.gov/jame/learn/historyculture/chronology-of-powhatan-indian-activity.htm",
      ]),
  },
  {
    id: "community.african-diaspora-virginia",
    label: "African-diaspora community in Virginia, 1619–1750",
    scope: {
      years: [1619, 1750],
      bounds: [-83.7, 36.5, -75.2, 39.5],
      communities: ["african-diaspora"],
    },
    priority: 95,
    appearance: "appearance.africa-broad",
    nameTraditions: [{ tradition: "anglo-colonial-diaspora", weight: 1 }],
    livelihoods: [
      "farmer",
      "craftsperson",
      "trader",
      "fisher",
      "gatherer",
      "traveler",
    ],
    allowedItems: [
      "water",
      "fruit",
      "berries",
      "wood",
      "fish",
      "tool",
      "obsidian",
      "grain",
      "bread",
      "flax",
    ],
    ...profileEvidence("Keep an African-diaspora Virginia community distinct from both English-colonial and Indigenous local communities in the 1619–1750 window.", ["https://encyclopediavirginia.org/entries/africans-virginias-first/"]),
  },
  {
    id: "community.afrikaner",
    label: "Afrikaner community in southern Africa, 1700–2000",
    scope: {
      years: [1700, 2000],
      bounds: [16, -35, 33, -22],
      communities: ["settler-afrikaner"],
    },
    priority: 95,
    appearance: "appearance.europe-broad",
    nameTraditions: [{ tradition: "dutch", weight: 6 }, { tradition: "german", weight: 2 }, { tradition: "french", weight: 1 }],
    livelihoods: ["farmer", "herder", "craftsperson", "trader", "fisher", "gatherer", "traveler"],
    allowedItems: [
      "water", "fruit", "berries", "wood", "fish", "tool", "obsidian",
      "grain", "bread", "flax", "wool", "fodder", "coin",
    ],
    ...profileEvidence("Keep the Dutch-descended farming community of the Cape and the interior distinct from the British settler and African communities alongside it.", ["https://doi.org/10.1017/CHOL9780521228039"]),
  },
  {
    id: "community.british-southern-africa",
    label: "British settler community in southern Africa, 1806–2000",
    scope: {
      years: [1806, 2000],
      bounds: [16, -35, 33, -22],
      communities: ["settler-british"],
    },
    priority: 94,
    appearance: "appearance.europe-broad",
    nameTraditions: [{ tradition: "english", weight: 8 }, { tradition: "scottish", weight: 2 }],
    livelihoods: ["farmer", "herder", "craftsperson", "trader", "fisher", "gatherer", "traveler"],
    allowedItems: [
      "water", "fruit", "berries", "wood", "fish", "tool", "obsidian",
      "grain", "bread", "flax", "wool", "fodder", "coin",
    ],
    ...profileEvidence("British settlement in the Cape and Natal follows the occupation of 1806 and is distinct from the earlier Dutch-descended community.", ["https://doi.org/10.1017/CHOL9780521228039"]),
  },
  {
    id: "community.southern-african-bantu",
    label: "Nguni and Sotho-Tswana communities, 400–2000",
    scope: {
      years: [400, 2000],
      bounds: [16, -35, 33, -22],
      communities: ["indigenous-local"],
    },
    priority: 96,
    appearance: "appearance.africa-broad",
    nameTraditions: [{ tradition: "bantu-southern", weight: 6 }, { tradition: "zulu", weight: 2 }, { tradition: "xhosa", weight: 2 }, { tradition: "sotho-tswana", weight: 2 }],
    livelihoods: ["farmer", "herder", "craftsperson", "trader", "fisher", "gatherer", "traveler"],
    allowedItems: [
      "water", "fruit", "berries", "wood", "fish", "tool", "obsidian",
      "grain", "bread", "flax", "wool", "fodder", "coin",
    ],
    ...profileEvidence("The African majority of southern Africa, whose naming and appearance should not be collapsed into the settler communities beside them.", ["https://doi.org/10.1017/9781316334755"]),
  },
  {
    id: "community.cape-malay",
    label: "Cape Malay and Indian Ocean community, 1658–2000",
    scope: {
      years: [1658, 2000],
      bounds: [17, -35, 20, -32],
      communities: ["cape-malay"],
    },
    priority: 97,
    appearance: "appearance.southeast-asia-broad",
    nameTraditions: [{ tradition: "malay", weight: 5 }, { tradition: "indonesian", weight: 3 }, { tradition: "malay-islamic-historical", weight: 2 }],
    livelihoods: ["farmer", "herder", "craftsperson", "trader", "fisher", "gatherer", "traveler"],
    allowedItems: [
      "water", "fruit", "berries", "wood", "fish", "tool", "obsidian",
      "grain", "bread", "flax", "wool", "fodder", "coin",
    ],
    ...profileEvidence("People brought to the Cape from the Indonesian archipelago, India and Madagascar, mostly in bondage, whose descendants form a distinct Cape community.", ["https://doi.org/10.1017/CHOL9780521228039"]),
  },
  {
    id: "community.us-indigenous",
    label: "Indigenous communities of settler North America, 1750–2000",
    scope: {
      years: [1750, 2000],
      bounds: [-141, 25, -52, 60],
      communities: ["indigenous-local"],
    },
    priority: 92,
    appearance: "appearance.americas-broad",
    livelihoods: [
      "gatherer",
      "hunter",
      "farmer",
      "herder",
      "fisher",
      "craftsperson",
      "trader",
      "traveler",
    ],
    allowedItems: [
      "water",
      "fruit",
      "berries",
      "reeds",
      "wood",
      "fish",
      "tool",
      "obsidian",
      "grain",
    ],
    ...profileEvidence(
      "Indigenous people remained in and around the settler towns of North America throughout, which a gazetteer that swaps a region's culture label at a founding date would otherwise erase.",
      ["https://doi.org/10.1017/CHOL9780521382892"],
    ),
  },
  {
    id: "community.us-anglo",
    label: "Anglo-American community, 1750–2000",
    scope: {
      years: [1750, 2000],
      bounds: [-125, 25, -67, 52],
      communities: ["us-anglo"],
    },
    priority: 92,
    appearance: "appearance.europe-broad",
    nameTraditions: [{ tradition: "english", weight: 6 }, { tradition: "north-american-modern", weight: 6 }, { tradition: "german", weight: 3 }, { tradition: "celtic-irish", weight: 3 }, { tradition: "scandinavian", weight: 1 }],
    livelihoods: ["farmer", "herder", "craftsperson", "trader", "fisher", "gatherer", "traveler"],
    allowedItems: [
      "water", "fruit", "berries", "wood", "fish", "tool", "obsidian",
      "grain", "bread", "flax", "wool", "fodder", "coin",
    ],
    ...profileEvidence("The white majority of the nineteenth and twentieth-century United States, drawn from several European naming stocks rather than one.", ["https://doi.org/10.1017/CHOL9780521382892"]),
  },
  {
    id: "community.us-african-american",
    label: "African-American community, 1750–2000",
    scope: {
      years: [1750, 2000],
      bounds: [-125, 25, -67, 52],
      communities: ["african-diaspora"],
    },
    priority: 93,
    appearance: "appearance.africa-broad",
    nameTraditions: [{ tradition: "african-american", weight: 9 }, { tradition: "english", weight: 1 }],
    livelihoods: ["farmer", "herder", "craftsperson", "trader", "fisher", "gatherer", "traveler"],
    allowedItems: [
      "water", "fruit", "berries", "wood", "fish", "tool", "obsidian",
      "grain", "bread", "flax", "wool", "fodder", "coin",
    ],
    ...profileEvidence("An African-American community distinct from the white majority in naming and appearance, present across the whole period and the whole country.", ["https://doi.org/10.2307/2937399"]),
  },
  {
    id: "community.us-latino",
    label: "Latino community in the United States, 1848–2000",
    scope: {
      years: [1848, 2000],
      bounds: [-125, 25, -93, 42],
      communities: ["us-latino"],
    },
    priority: 93,
    appearance: "appearance.americas-broad",
    nameTraditions: [{ tradition: "spanish-latin-american", weight: 9 }, { tradition: "spanish-castilian", weight: 1 }],
    livelihoods: ["farmer", "herder", "craftsperson", "trader", "fisher", "gatherer", "traveler"],
    allowedItems: [
      "water", "fruit", "berries", "wood", "fish", "tool", "obsidian",
      "grain", "bread", "flax", "wool", "fodder", "coin",
    ],
    ...profileEvidence("Spanish-speaking communities of the southwest, present from before the annexation of 1848 and growing through the twentieth century.", ["https://doi.org/10.1017/CHOL9780521382892"]),
  },
  {
    id: "community.us-chinese",
    label: "Chinese-American community, 1850–2000",
    scope: {
      years: [1850, 2000],
      bounds: [-125, 32, -114, 49],
      communities: ["us-chinese"],
    },
    priority: 93,
    appearance: "appearance.east-asia-broad",
    nameTraditions: [{ tradition: "chinese-cantonese", weight: 9 }, { tradition: "chinese-mandarin", weight: 1 }],
    livelihoods: ["farmer", "herder", "craftsperson", "trader", "fisher", "gatherer", "traveler"],
    allowedItems: [
      "water", "fruit", "berries", "wood", "fish", "tool", "obsidian",
      "grain", "bread", "flax", "wool", "fodder", "coin",
    ],
    ...profileEvidence("Chinese settlement on the Pacific coast from the gold rush, concentrated in the cities and the railway towns.", ["https://doi.org/10.1017/CHOL9780521382892"]),
  },
  {
    id: "community.ottoman-muslim",
    label: "Ottoman Muslim community, 1450–1923",
    scope: {
      years: [1450, 1923],
      bounds: [19, 35, 45, 46],
      communities: ["ottoman-muslim"],
    },
    priority: 92,
    appearance: "appearance.west-asia-broad",
    nameTraditions: [{ tradition: "turkish", weight: 7 }, { tradition: "arabic-traditional", weight: 2 }, { tradition: "serbian", weight: 1 }],
    livelihoods: ["farmer", "herder", "craftsperson", "trader", "fisher", "gatherer", "traveler"],
    allowedItems: [
      "water", "fruit", "berries", "wood", "fish", "tool", "obsidian",
      "grain", "bread", "flax", "wool", "fodder", "coin",
    ],
    ...profileEvidence("The Muslim population of Ottoman Rumelia and Anatolia, one community among several in the same street rather than the whole of a city.", ["https://doi.org/10.1017/CHOL9780521291637"]),
  },
  {
    id: "community.ottoman-greek",
    label: "Ottoman Greek and Armenian community, 1450–1923",
    scope: {
      years: [1450, 1923],
      bounds: [19, 35, 45, 46],
      communities: ["ottoman-christian"],
    },
    priority: 92,
    appearance: "appearance.europe-broad",
    nameTraditions: [{ tradition: "greek", weight: 6 }, { tradition: "armenian", weight: 3 }, { tradition: "bulgarian", weight: 1 }],
    livelihoods: ["farmer", "herder", "craftsperson", "trader", "fisher", "gatherer", "traveler"],
    allowedItems: [
      "water", "fruit", "berries", "wood", "fish", "tool", "obsidian",
      "grain", "bread", "flax", "wool", "fodder", "coin",
    ],
    ...profileEvidence("The Orthodox and Armenian Christian communities of the Ottoman cities, self-governing in their own affairs under the millet arrangement.", ["https://doi.org/10.1017/CHOL9780521291637"]),
  },
  {
    id: "community.ottoman-jewish",
    label: "Sephardi community of the Ottoman cities, 1492–1923",
    scope: {
      years: [1492, 1923],
      bounds: [19, 35, 45, 46],
      communities: ["ottoman-jewish"],
    },
    priority: 93,
    appearance: "appearance.europe-broad",
    nameTraditions: [{ tradition: "jewish-ashkenazi", weight: 5 }, { tradition: "spanish-castilian", weight: 3 }, { tradition: "hebrew", weight: 2 }],
    livelihoods: ["farmer", "herder", "craftsperson", "trader", "fisher", "gatherer", "traveler"],
    allowedItems: [
      "water", "fruit", "berries", "wood", "fish", "tool", "obsidian",
      "grain", "bread", "flax", "wool", "fodder", "coin",
    ],
    ...profileEvidence("Sephardi Jews settled in Salonica, Istanbul and Izmir after the expulsion from Spain, and in Salonica the largest single community in the city.", ["https://doi.org/10.1017/CHOL9780521291637"]),
  },
  {
    id: "community.batavia-chinese",
    label: "Chinese community of the Indies ports, 1600–1949",
    scope: {
      years: [1600, 1949],
      bounds: [95, -11, 141, 7],
      communities: ["indies-chinese"],
    },
    priority: 93,
    appearance: "appearance.east-asia-broad",
    nameTraditions: [{ tradition: "chinese-cantonese", weight: 8 }, { tradition: "chinese-mandarin", weight: 2 }],
    livelihoods: ["farmer", "herder", "craftsperson", "trader", "fisher", "gatherer", "traveler"],
    allowedItems: [
      "water", "fruit", "berries", "wood", "fish", "tool", "obsidian",
      "grain", "bread", "flax", "wool", "fodder", "coin",
    ],
    ...profileEvidence("The Chinese merchant and artisan population of Batavia and the other Indies ports, on which the Dutch trading system depended.", ["https://doi.org/10.1017/CBO9781139195836"]),
  },
  {
    id: "community.batavia-dutch",
    label: "Dutch community of the Indies ports, 1600–1949",
    scope: {
      years: [1600, 1949],
      bounds: [95, -11, 141, 7],
      communities: ["indies-dutch"],
    },
    priority: 92,
    appearance: "appearance.europe-broad",
    nameTraditions: [{ tradition: "dutch", weight: 9 }, { tradition: "german", weight: 1 }],
    livelihoods: ["farmer", "herder", "craftsperson", "trader", "fisher", "gatherer", "traveler"],
    allowedItems: [
      "water", "fruit", "berries", "wood", "fish", "tool", "obsidian",
      "grain", "bread", "flax", "wool", "fodder", "coin",
    ],
    ...profileEvidence("The Dutch company and colonial population of the Indies ports, a small minority ruling a city that was mostly not Dutch.", ["https://doi.org/10.1017/CBO9781139195836"]),
  },
  {
    id: "community.indies-malay",
    label: "Malay and Javanese communities of the Indies, 600–2000",
    scope: {
      years: [600, 2000],
      bounds: [95, -11, 141, 7],
      communities: ["indigenous-local"],
    },
    priority: 94,
    appearance: "appearance.southeast-asia-broad",
    nameTraditions: [{ tradition: "javanese", weight: 5 }, { tradition: "malay", weight: 4 }, { tradition: "indonesian", weight: 2 }],
    livelihoods: ["farmer", "herder", "craftsperson", "trader", "fisher", "gatherer", "traveler"],
    allowedItems: [
      "water", "fruit", "berries", "wood", "fish", "tool", "obsidian",
      "grain", "bread", "flax", "wool", "fodder", "coin",
    ],
    ...profileEvidence("The Javanese and Malay majority of the archipelago, distinct from the Chinese and European communities in the port cities.", ["https://doi.org/10.1017/CBO9781139195836"]),
  },
];
