import type { NameKit } from "../context-types";

/**
 * Name examples are reusable input lists, not claims that every person in a
 * place had one of these names.  The people generated from them are fictional.
 */
const romanEpigraphy = "https://edh.ub.uni-heidelberg.de/";
const dmnes = "https://dmnes.org/";
const londonLives = "https://www.londonlives.org/";
const virginiaMuster =
  "https://www.nps.gov/jame/learn/historyculture/the-first-residents-of-jamestown.htm";

const attestedNames = (
  claim: string,
  sources: string[],
  status: "documented" | "inferred" = "inferred",
) => ({
  status,
  claim,
  sources,
  limitation:
    "An authored sample drawn from these documentary traditions, with normalized display spellings and regional/temporal extrapolation; they do not establish local frequency, complete gender coverage, or a naming rule for every household. Generated people are fictional, and a name source supports name use only, not appearance.",
});

export const nameKits: NameKit[] = [
  {
    id: "names-roman-italy-100bce-476ce",
    label: "Roman Italy · 100 BCE–476 CE",
    scope: {
      years: [-99, 476],
      cultures: ["european"],
      bounds: [8, 36, 19, 47],
    },
    names: [
      "Marcus",
      "Lucius",
      "Gaius",
      "Quintus",
      "Publius",
      "Titus",
      "Gnaeus",
      "Aulus",
      "Sextus",
      "Decimus",
      "Aurelius",
      "Cornelius",
      "Julius",
      "Claudius",
      "Antonius",
      "Flavius",
      "Valerius",
      "Aemilius",
      "Livia",
      "Julia",
      "Aurelia",
      "Cornelia",
      "Claudia",
      "Antonia",
      "Octavia",
      "Tullia",
      "Valeria",
      "Flavia",
    ],
    evidence: attestedNames(
      "Roman personal-name forms and gentilicia are represented in the Epigraphic Database Heidelberg's searchable corpus of Latin inscriptions; this kit is scoped to a Roman-Italy setting as a bounded gameplay sample.",
      [romanEpigraphy],
    ),
  },
  {
    id: "names-medieval-england-1100-1600",
    label: "England · medieval to early modern sample, 1100–1600",
    scope: {
      years: [1100, 1600],
      cultures: ["european"],
      bounds: [-6, 50.2, 2, 56],
    },
    names: [
      "William",
      "John",
      "Thomas",
      "Richard",
      "Robert",
      "Henry",
      "Geoffrey",
      "Hugh",
      "Walter",
      "Roger",
      "Simon",
      "Adam",
      "Nicholas",
      "Peter",
      "Alice",
      "Agnes",
      "Joan",
      "Margaret",
      "Matilda",
      "Isabel",
      "Katherine",
      "Cecily",
      "Eleanor",
      "Emma",
      "Ela",
      "Christina",
    ],
    evidence: attestedNames(
      "DMNES documents given names in European sources through 1600, including English forms; this is an inferred regional English sample whose display spellings are modernized for readability and should not be mistaken for a complete medieval name register.",
      [dmnes],
      "inferred",
    ),
  },
  {
    id: "names-early-modern-england-1600-1750",
    label: "England · early modern continuity sample, 1600–1750",
    scope: {
      years: [1600, 1750],
      cultures: ["european"],
      bounds: [-6, 50.2, 2, 56],
    },
    names: [
      "John",
      "William",
      "Thomas",
      "Richard",
      "Henry",
      "Edward",
      "George",
      "James",
      "Robert",
      "Charles",
      "Francis",
      "Samuel",
      "Joseph",
      "Elizabeth",
      "Mary",
      "Anne",
      "Alice",
      "Margaret",
      "Dorothy",
      "Susan",
      "Jane",
      "Katherine",
      "Joan",
      "Frances",
      "Eleanor",
    ],
    evidence: attestedNames(
      "DMNES documents European given names through 1600, while London Lives publishes primary London records beginning in 1690. The intervening and post-1600 use here is an inferred continuity sample; display spellings are modernized and this is not a frequency table.",
      [dmnes, londonLives],
      "inferred",
    ),
  },
  {
    id: "names-english-virginia-1607-1750",
    label: "English Virginia · 1607–1750",
    scope: {
      years: [1607, 1750],
      cultures: ["european"],
      bounds: [-84, 36, -75, 40],
      communities: ["english-colonial"],
    },
    names: [
      "John",
      "William",
      "Thomas",
      "Richard",
      "George",
      "Edward",
      "Henry",
      "James",
      "Robert",
      "Francis",
      "Samuel",
      "Joseph",
      "Elizabeth",
      "Anne",
      "Mary",
      "Margaret",
      "Alice",
      "Jane",
      "Katherine",
      "Joan",
      "Sarah",
      "Martha",
    ],
    evidence: attestedNames(
      "The National Park Service reproduces a source-based list of the known 104 English settlers who remained at Jamestown in 1607; male forms use that roster; female forms extend the English sample from DMNES. Regional use and continuity through 1750 are inferred.",
      [virginiaMuster, dmnes],
      "inferred",
    ),
  },
  {
    id: "names-medieval-italy-1200-1500",
    label: "Italy · medieval, 1200–1500",
    scope: {
      years: [1200, 1500],
      cultures: ["european"],
      bounds: [8, 36, 19, 47],
    },
    names: [
      "Giovanni",
      "Francesco",
      "Pietro",
      "Matteo",
      "Lorenzo",
      "Niccolò",
      "Antonio",
      "Domenico",
      "Jacopo",
      "Simone",
      "Andrea",
      "Bartolomeo",
      "Caterina",
      "Francesca",
      "Maria",
      "Giovanna",
      "Margherita",
      "Lucia",
      "Beatrice",
      "Agnes",
      "Costanza",
    ],
    evidence: attestedNames(
      "The Dictionary of Medieval Names from European Sources gathers documented medieval name forms, including Italian evidence, and records their source attestations; this kit is a regional sample rather than a claim about all Italian communities.",
      [dmnes],
    ),
  },
  {
    id: "names-early-modern-italy-1500-1750",
    label: "Italy · early modern, 1500–1750",
    scope: {
      years: [1500, 1750],
      cultures: ["european"],
      bounds: [8, 36, 19, 47],
    },
    names: [
      "Giovanni",
      "Francesco",
      "Giuseppe",
      "Antonio",
      "Pietro",
      "Lorenzo",
      "Carlo",
      "Domenico",
      "Matteo",
      "Paolo",
      "Marco",
      "Alessandro",
      "Maria",
      "Caterina",
      "Francesca",
      "Lucia",
      "Giovanna",
      "Beatrice",
      "Angela",
      "Isabella",
      "Maddalena",
    ],
    evidence: attestedNames(
      "DMNES documents European given names in sources written through 1600, including Italian forms. Applying the continuing forms to 1600–1750 is an explicitly inferred continuity sample for regional play.",
      [dmnes],
      "inferred",
    ),
  },
  {
    id: "names-medieval-france-1100-1500",
    label: "France · medieval, 1100–1500",
    scope: {
      years: [1100, 1500],
      cultures: ["european"],
      bounds: [-5, 42, 6, 50],
    },
    names: [
      "Jean",
      "Pierre",
      "Guillaume",
      "Étienne",
      "Philippe",
      "Jacques",
      "Martin",
      "Hugues",
      "Louis",
      "Gérard",
      "Robert",
      "Bernard",
      "Jeanne",
      "Marguerite",
      "Catherine",
      "Marie",
      "Isabelle",
      "Anne",
      "Agnès",
      "Perrine",
      "Madeleine",
    ],
    evidence: attestedNames(
      "DMNES documents medieval French name forms with dated source references; the selected forms are a small regional sample and do not represent every language or community within medieval France.",
      [dmnes],
    ),
  },
  {
    id: "names-early-modern-france-1500-1750",
    label: "France · early modern, 1500–1750",
    scope: {
      years: [1500, 1750],
      cultures: ["european"],
      bounds: [-5, 42, 6, 50],
    },
    names: [
      "Jean",
      "Pierre",
      "François",
      "Jacques",
      "Louis",
      "Charles",
      "Henri",
      "Antoine",
      "Nicolas",
      "Michel",
      "Paul",
      "Étienne",
      "Marie",
      "Jeanne",
      "Marguerite",
      "Catherine",
      "Anne",
      "Isabelle",
      "Louise",
      "Madeleine",
      "Françoise",
      "Charlotte",
    ],
    evidence: attestedNames(
      "DMNES documents European given names in sources written through 1600, including French forms. Applying the continuing forms to 1600–1750 is an explicitly inferred continuity sample for regional play.",
      [dmnes],
      "inferred",
    ),
  },
];
