import type { NameKit } from "../context-types";

/*
 * These are reusable name components, not lists of complete historical
 * people. The resolver/generator may combine them; that combination is an
 * inferred fictional display name and is never an attestation.
 */
const chineseSource = "https://www.loc.gov/catdir/pinyin/rom1.html";
const spanishSource = "https://www.boe.es/buscar/doc.php?id=BOE-A-2000-3842";
const normalizationLimit =
  "Names are normalized into Latin display strings and sampled as components; generated combinations are fictional, not attested persons. Romanization, accents, compound given names, marriage practices, minority traditions, and local historical variation are not fully represented, and a naming source does not establish appearance or occupation.";

export const structuredNameKits: NameKit[] = [
  {
    id: "names-china-family-personal-1000-2026",
    label:
      "Central/eastern China · family name followed by personal name, 1000–2026",
    scope: {
      years: [1000, 2027],
      cultures: ["east-asian"],
      bounds: [100, 20, 122, 42],
    },
    names: [
      "Wei",
      "Fang",
      "Min",
      "Jing",
      "Lei",
      "Hui",
      "Yan",
      "Mei",
      "Liang",
      "Qiang",
      "Xia",
      "Ying",
      "Jun",
      "Lan",
      "Tao",
      "Ning",
      "Hao",
      "Lin",
      "Xiu",
      "Ming",
    ],
    format: "family-personal",
    familyNames: [
      "Wang",
      "Li",
      "Zhang",
      "Liu",
      "Chen",
      "Yang",
      "Huang",
      "Zhao",
      "Wu",
      "Zhou",
      "Xu",
      "Sun",
      "Hu",
      "Zhu",
      "Gao",
      "Lin",
      "He",
      "Guo",
      "Ma",
      "Luo",
    ],
    evidence: {
      status: "inferred",
      claim:
        "The Library of Congress Pinyin romanization guidance preserves the Chinese convention of writing the family name separately before the given name; this bounded Chinese scenario supplies component forms for fictional generation. Earlier periods use an explicit reconstruction rather than a century-specific personal-name register.",
      sources: [chineseSource],
      limitation: `${normalizationLimit} The source establishes display ordering/romanization, not the date-specific prevalence of these components. Pinyin is a modern display convention even for earlier scenarios. This does not supply generation poems or historical naming taboos.`,
    },
  },
  {
    id: "names-spain-two-families-1900-2026",
    label: "Central Spain · personal name and two family names, 1900–2026",
    scope: {
      years: [1900, 2027],
      cultures: ["european"],
      bounds: [-6, 37, -1, 42],
    },
    names: [
      "María",
      "Carmen",
      "Isabel",
      "Ana",
      "Lucía",
      "Sofía",
      "Elena",
      "Laura",
      "Teresa",
      "Marta",
      "José",
      "Juan",
      "Antonio",
      "Carlos",
      "Miguel",
      "Francisco",
      "Javier",
      "Luis",
      "Manuel",
      "Pablo",
    ],
    format: "personal-two-families",
    familyNames: [
      "García",
      "Fernández",
      "González",
      "Rodríguez",
      "López",
      "Martínez",
      "Sánchez",
      "Pérez",
      "Martín",
      "Gómez",
      "Ruiz",
      "Díaz",
      "Moreno",
      "Muñoz",
      "Álvarez",
      "Romero",
      "Alonso",
      "Navarro",
      "Torres",
      "Domínguez",
    ],
    secondFamilyNames: [
      "García",
      "Fernández",
      "González",
      "Rodríguez",
      "López",
      "Martínez",
      "Sánchez",
      "Pérez",
      "Martín",
      "Gómez",
      "Ruiz",
      "Díaz",
      "Moreno",
      "Muñoz",
      "Álvarez",
      "Romero",
      "Alonso",
      "Navarro",
      "Torres",
      "Vázquez",
    ],
    evidence: {
      status: "inferred",
      claim:
        "Spain's official civil-registry regulation describes two parental surnames and provisions for choosing or reversing their order; this bounded modern Spain kit represents a personal name followed by two parental family names with fictional component combinations.",
      sources: [spanishSource],
      limitation: `${normalizationLimit} The engine currently uses household parent ordering, not a determination of paternal/maternal lineage. The cited regulation is from 2000; extending the prototype format across this date window is a scenario inference and does not establish the same order for every earlier period, Spanish-speaking country, or family circumstance.`,
    },
  },
];
