import type { NameKit } from "../context-types";

/*
 * These are reusable name components, not lists of complete historical
 * people. The resolver/generator may combine them; that combination is an
 * inferred fictional display name and is never an attestation.
 */
const chineseSource = "https://www.loc.gov/catdir/pinyin/rom1.html";
const spanishSource = "https://www.boe.es/buscar/doc.php?id=BOE-A-2000-3842";
export const structuredNameKits: NameKit[] = [
  {
    id: "names-china-family-personal-1000-2026",
    label:
      "Central/eastern China · family name followed by personal name, 1000–2026",
    scope: {
      years: [1000, 2027],
      cultures: ["east-asian"],
      bounds: [100, 20, 122, 42],
    },
    names: [
      "Wei",
      "Fang",
      "Min",
      "Jing",
      "Lei",
      "Hui",
      "Yan",
      "Mei",
      "Liang",
      "Qiang",
      "Xia",
      "Ying",
      "Jun",
      "Lan",
      "Tao",
      "Ning",
      "Hao",
      "Lin",
      "Xiu",
      "Ming",
    ],
    format: "family-personal",
    familyNames: [
      "Wang",
      "Li",
      "Zhang",
      "Liu",
      "Chen",
      "Yang",
      "Huang",
      "Zhao",
      "Wu",
      "Zhou",
      "Xu",
      "Sun",
      "Hu",
      "Zhu",
      "Gao",
      "Lin",
      "He",
      "Guo",
      "Ma",
      "Luo",
    ],
    sources: [chineseSource],
    note: "The family name precedes the given name. Pinyin is a modern display convention; generation poems and naming taboos are not modelled.",
  },
  {
    id: "names-spain-two-families-1900-2026",
    label: "Central Spain · personal name and two family names, 1900–2026",
    scope: {
      years: [1900, 2027],
      cultures: ["european"],
      bounds: [-6, 37, -1, 42],
    },
    names: [
      "María",
      "Carmen",
      "Isabel",
      "Ana",
      "Lucía",
      "Sofía",
      "Elena",
      "Laura",
      "Teresa",
      "Marta",
      "José",
      "Juan",
      "Antonio",
      "Carlos",
      "Miguel",
      "Francisco",
      "Javier",
      "Luis",
      "Manuel",
      "Pablo",
    ],
    format: "personal-two-families",
    familyNames: [
      "García",
      "Fernández",
      "González",
      "Rodríguez",
      "López",
      "Martínez",
      "Sánchez",
      "Pérez",
      "Martín",
      "Gómez",
      "Ruiz",
      "Díaz",
      "Moreno",
      "Muñoz",
      "Álvarez",
      "Romero",
      "Alonso",
      "Navarro",
      "Torres",
      "Domínguez",
    ],
    secondFamilyNames: [
      "García",
      "Fernández",
      "González",
      "Rodríguez",
      "López",
      "Martínez",
      "Sánchez",
      "Pérez",
      "Martín",
      "Gómez",
      "Ruiz",
      "Díaz",
      "Moreno",
      "Muñoz",
      "Álvarez",
      "Romero",
      "Alonso",
      "Navarro",
      "Torres",
      "Vázquez",
    ],
    sources: [spanishSource],
    note: "A personal name followed by one surname from each parent. Spanish civil registration has allowed the parents to choose the order since 2000; before that the father's came first.",
  },
];
