from heads import R

EXTRAS = {}
EXTRAS['sandals'] = R(
 "",
 "",
 "",
 "      tt        tt      ",
 "      ttt      ttt      ",
 "   kkkkttt    tttkkkk   ",
 "  kkkkkkttt  tttkkkkkk  ",
 "  kkkkkkkttttttkkkkkkk  ",
 "  kkkkkkkkktttkkkkkkkk  ",
 "  kkkkkkkkkkkkkkkkkkkk  ",
 "  KKKKKKKKKKKKKKKKKKKK  ",
 "   kkkkkkkkkkkkkkkkkk   ",
 "    kkkkkkkkkkkkkkkk    ",
 "     KKKKKKKKKKKKKK     ",
)
EXTRAS['shoes'] = R(
 "",
 "",
 "",
 "",
 "",
 "         oooooooo       ",
 "       oooooooooooo     ",
 "      oooooooooooooo    ",
 "     ootttttoooooooo    ",
 "    oooooooooooooooo    ",
 "   ooooooooooooooooo    ",
 "  kkkkkkkkkkkkkkkkkk    ",
 "  KKKKKKKKKKKKKKKKKK    ",
 "   kkkkkkkkkkkkkkkk     ",
)
EXTRAS['boots'] = R(
 "",
 "     tttttttt           ",
 "     oooooooo           ",
 "     oooooooo           ",
 "     oooooooo           ",
 "     oooooooo           ",
 "     oooooooo           ",
 "     oooooooo           ",
 "     oooooooo           ",
 "     ooooooooooo        ",
 "     ooooooooooooo      ",
 "    oooooooooooooooo    ",
 "    kkkkkkkkkkkkkkkk    ",
 "    KKKKKKKKKKKKKKKK    ",
)
EXTRAS['cord'] = R(
 "",
 "",
 "       oo::oo::oo       ",
 "     oo::oo::oo::oo     ",
 "    oo::oo::oo::oo:oo   ",
 "   oo::oo::oo::oo::oo   ",
 "   oo::oo::oo::oo::oo   ",
 "    oo::oo::oo::oo:oo   ",
 "     oo::oo::oo::oo     ",
 "        ooooooo         ",
 "        oo:::oo         ",
 "         oo:oo          ",
 "         o::o           ",
 "         o::o           ",
 "        oo::oo          ",
 "         o::o           ",
)
EXTRAS['sash'] = R(
 "",
 "",
 "",
 "  oooooooooooooooooooo  ",
 "  oooooooooooooooooooo  ",
 "  oooo::::::::::::oooo  ",
 "  oooooooooooooooooooo  ",
 "  ooooooooo::ooooooooo  ",
 "      ooooooooooo       ",
 "       ooooooooo        ",
 "        ooooooo         ",
 "        oo::ooo         ",
 "        ooooooo         ",
 "        oo::ooo         ",
 "         ooooo          ",
 "          ooo           ",
)
EXTRAS['leather'] = R(
 "",
 "",
 "",
 "",
 "   kkkkkkkkkkkkkkkkkk   ",
 "   kkkkkkkmmmmkkkkkkk   ",
 "   kkkkkkkmMMmkkkkkkk   ",
 "   kkkkkkkmmmmkkkkkkk   ",
 "   KKKKKKKKKKKKKKKKKK   ",
)
EXTRAS['belt-wide'] = R(
 "",
 "",
 "",
 "   kkkkkkkkkkkkkkkkkk   ",
 "   kkkkkkkkkkkkkkkkkk   ",
 "   kkkkkkmmmmmmkkkkkk   ",
 "   kkkkkkmMMMMmkkkkkk   ",
 "   kkkkkkmmmmmmkkkkkk   ",
 "   kkkkkkkkkkkkkkkkkk   ",
 "   KKKKKKKKKKKKKKKKKK   ",
)
EXTRAS['necklace'] = R(
 "",
 "",
 "      mm      mm        ",
 "    mm          mm      ",
 "   mm            mm     ",
 "  mm              mm    ",
 "  mm              mm    ",
 "   mm            mm     ",
 "    mm          mm      ",
 "     mm        mm       ",
 "      mm  MM  mm        ",
 "        mMMMMm          ",
 "         MMMM           ",
 "          MM            ",
)
EXTRAS['earrings'] = R(
 "",
 "",
 "",
 "     mmm        mmm     ",
 "     mMm        mMm     ",
 "     mmm        mmm     ",
 "      m          m      ",
 "      m          m      ",
 "     mmm        mmm     ",
 "    mMMMm      mMMMm    ",
 "    mMMMm      mMMMm    ",
 "     mmm        mmm     ",
)
