from drape import from_rows

def R(*rows):
    out = []
    for r in rows:
        assert len(r) <= 24, (len(r), r)
        out.append(r.ljust(24))
    assert len(out) <= 24, len(out)
    return from_rows(out + ['']*(24-len(out)))

HEADS = {}
HEADS['cap'] = R(
 "",
 "",
 "",
 "",
 "",
 "          oooo          ",
 "        oooooooo        ",
 "      oooooooooooo      ",
 "     oooooooooooooo     ",
 "    oooooooooooooooo    ",
 "   oooooooooooooooooo   ",
 "   oooooooooooooooooo   ",
 "   tttttttttttttttttt   ",
 "   tttttttttttttttttt   ",
)
HEADS['bowler'] = R(
 "",
 "",
 "",
 "",
 "         oooooo         ",
 "       oooooooooo       ",
 "      oooooooooooo      ",
 "      oooooooooooo      ",
 "      oooooooooooo      ",
 "      tttttttttttt      ",
 "      tttttttttttt      ",
 "   oooooooooooooooooo   ",
 "  oooooooooooooooooooo  ",
 "   oooooooooooooooooo   ",
)
HEADS['brimmed'] = R(
 "",
 "",
 "",
 "",
 "        oooooooo        ",
 "       oooooooooo       ",
 "      oooooooooooo      ",
 "      oooooooooooo      ",
 "      tttttttttttt      ",
 "      tttttttttttt      ",
 "  oooooooooooooooooooo  ",
 " oooooooooooooooooooooo ",
 "oooooooooooooooooooooooo",
 "  oooooooooooooooooooo  ",
)
HEADS['conical'] = R(
 "",
 "",
 "           oo           ",
 "          oooo          ",
 "          oooo          ",
 "         oooooo         ",
 "        oooooooo        ",
 "       oooooooooo       ",
 "      oooooooooooo      ",
 "     oooooooooooooo     ",
 "    oooooooooooooooo    ",
 "   oooooooooooooooooo   ",
 "  oooooooooooooooooooo  ",
 "  oooooooooooooooooooo  ",
)
HEADS['flat-cap'] = R(
 "",
 "",
 "",
 "",
 "",
 "        oooooooo        ",
 "      oooooooooooo      ",
 "    oooooooooooooooo    ",
 "   oooooooooooooooooo   ",
 "   oooooooooooooooooo   ",
 "  ooooooooooooooooooo   ",
 "  xxxxxxxxxxxxxxxx      ",
 "   xxxxxxxxxxxxx        ",
)
HEADS['ball-cap'] = R(
 "",
 "",
 "",
 "",
 "",
 "         oooooo         ",
 "       oooooooooo       ",
 "      oooooooooooo      ",
 "     oooooooooooooo     ",
 "     ottttttttttoo      ",
 "     oooooooooooo       ",
 "     xxxxxxxxxxxxxxx    ",
 "      xxxxxxxxxxxxx     ",
)
HEADS['fez'] = R(
 "",
 "",
 "       oooooooooo       ",
 "       oooooooooo       ",
 "      oooooooooooo      ",
 "      oooooooooooo      ",
 "      oooooooooooo      ",
 "      oooooooooooo      ",
 "     oooooooooooooo     ",
 "     oooooooooooooo     ",
 "     tttttttttttttt     ",
 "     tttttttttttttt     ",
)
HEADS['hood'] = R(
 "",
 "                 ooo    ",
 "              oooooo    ",
 "           ooooooooo    ",
 "        ooooooooooooo   ",
 "      oooooooooooooooo  ",
 "     ooooo::ooooooooo   ",
 "    oooo::ooooooooooo   ",
 "   ooooo::oooooooooo    ",
 "   oooo::ooooooooooo    ",
 "   ooooooooooooooooo    ",
 "    oooooooooooooooo    ",
 "     tttttttttttttt     ",
 "     tttttttttttttt     ",
)
HEADS['turban'] = R(
 "",
 "",
 "",
 "         oooooo         ",
 "      oooooooooooo      ",
 "    oooooooooooooooo    ",
 "    oooooooooooooooo    ",
 "    oo::::::::::::oo    ",
 "    oooooooooooooooo    ",
 "    oo::::::::::::oo    ",
 "    oooooooooooooooo    ",
 "     oooooooooooooo     ",
 "      oooooooooooo      ",
)
HEADS['wrap_head'] = R(
 "",
 "",
 "        oooooooo        ",
 "      oooooooooooo      ",
 "     ooo::oooooooo      ",
 "    oooo::ooooooooo     ",
 "    ooooo::oooooooo     ",
 "    oooooo::ooooooo     ",
 "    ooooooo::oooooo     ",
 "     ooooooo::ooooo     ",
 "      ooooooo::ooo      ",
 "       oooooooooo       ",
)
HEADS['headscarf'] = R(
 "",
 "",
 "",
 "        oooooooo        ",
 "      oooooooooooo      ",
 "     oooooooooooooo     ",
 "    oooooooooooooooo    ",
 "    oooooooooooooooo    ",
 "     oooooooooooooo     ",
 "      oooooooooooo      ",
 "       oooooooooo       ",
 "        oooooooo        ",
 "         oooooo         ",
 "          oooo          ",
)
HEADS['veil'] = R(
 "",
 "",
 "        oooooooo        ",
 "      oooooooooooo      ",
 "     oooooooooooooo     ",
 "     o:o:o:o:o:o:oo     ",
 "     oooooooooooooo     ",
 "     o:o:o:o:o:o:oo     ",
 "     oooooooooooooo     ",
 "     o:o:o:o:o:o:oo     ",
 "     oooooooooooooo     ",
 "      o:o:o:o:o:o       ",
 "      oooooooooooo      ",
)
HEADS['helmet'] = R(
 "",
 "",
 "         mmmmmm         ",
 "       mmmmmmmmmm       ",
 "      mmmmmmmmmmmm      ",
 "     mmmmmmmmmmmmmm     ",
 "     mmm        mmm     ",
 "     mm          mm     ",
 "     mm          mm     ",
 "     mmm        mmm     ",
 "     mmmm      mmmm     ",
 "     mmmmmmmmmmmmmm     ",
 "      mmmmmmmmmmmm      ",
)
HEADS['visor'] = R(
 "",
 "",
 "         oooooo         ",
 "       oooooooooo       ",
 "      oooooooooooo      ",
 "     oooooooooooooo     ",
 "     oo          oo     ",
 "     om  mmmmmm  mo     ",
 "     om  mmmmmm  mo     ",
 "     oo          oo     ",
 "     oooooooooooooo     ",
 "      oooooooooooo      ",
 "       tttttttttt       ",
)
HEADS['wig'] = R(
 "",
 "",
 "         oooooo         ",
 "       ooooooooo        ",
 "      oooo::ooooo       ",
 "     oooooo::oooooo     ",
 "    oooooooooooooooo    ",
 "   oooooooooooooooooo   ",
 "   oo::oooooooooo::oo   ",
 "   oooooooooooooooooo   ",
 "   oo::oooooooooo::oo   ",
 "    oooooooooooooooo    ",
 "      oooo::::oooo      ",
 "         oooooo         ",
 "          oooo          ",
)
HEADS['band'] = R(
 "",
 "",
 "",
 "",
 "",
 "",
 "     oooooooooooooo     ",
 "     otttttttttttto     ",
 "     oooooooooooooo     ",
)
HEADS['fillet'] = R(
 "",
 "",
 "",
 "",
 "",
 "",
 "     mmmmmmmmmmmmmm     ",
 "     mmmMmmmmmmMmmm     ",
 "     mmmmmmmmmmmmmm     ",
)
HEADS['plume'] = R(
 "",
 "                  OO    ",
 "                OOO     ",
 "              OOO       ",
 "             OO         ",
 "            OO          ",
 "           OO           ",
 "          Oo            ",
 "      ooooooooo         ",
 "    ooooooooooooo       ",
 "   ooooooooooooooo      ",
 "   tttttttttttttto      ",
 "  oooooooooooooooooo    ",
 "   oooooooooooooooo     ",
)
