/**
 * constants/gameData/cropData.ts
 * Detailed information about crops including planting seasons, care requirements, and market data
 */

export interface CropInfo {
  name: string;
  emoji: string;
  description: string;
  bestPlantingMonths: number[]; // 1-12
  waterNeeds: 'low' | 'moderate' | 'high';
  fertilizerNeeds: 'low' | 'moderate' | 'high';
  growthDays: number;
  basePrice: number; // Base price per unit
  tip?: string; // Additional tip shown when expanded
  farmTypes?: string[]; // Special farm type names (e.g., "Winery" for grapes)

  // Phase 4.1: Nutrient depletion/restoration
  nitrogenEffect: number; // -20 = heavy depletion, 0 = neutral, +30 = restoration
  phosphorusEffect: number;
  potassiumEffect: number;
  cropCategory: 'grain' | 'legume' | 'root' | 'vegetable' | 'fruit'; // For rotation logic
}

export const CROP_DATA: Record<string, CropInfo> = {
  // Grains
  wheat: {
    name: 'Wheat',
    emoji: '🌾',
    description: 'The grain that built civilizations from Mesopotamia to Manitoba, transforming nomads into tax-paying subjects. Winter wheat planted in autumn outsmarts spring frosts while summer wheat races seasons—either way, bread follows.',
    bestPlantingMonths: [3, 4, 9, 10], // Spring or fall
    waterNeeds: 'moderate',
    fertilizerNeeds: 'moderate',
    growthDays: 90,
    basePrice: 12,
    tip: 'Plant in early spring for summer harvest, or fall for winter wheat. Rotate with legumes to maintain soil fertility—continuous wheat cultivation leads to the "wheat sick" soil medieval farmers dreaded.',
    nitrogenEffect: -15, // Grains deplete nitrogen
    phosphorusEffect: -8,
    potassiumEffect: -5,
    cropCategory: 'grain',
  },
  barley: {
    name: 'Barley',
    emoji: '🌾',
    description: 'The oldest domesticated grain and brewing\'s best friend—Sumerian workers received beer rations in barley measure. Grows where wheat sulks, tolerating salt, sand, and the hangover of poor soil.',
    bestPlantingMonths: [3, 4, 10],
    waterNeeds: 'low',
    fertilizerNeeds: 'low',
    growthDays: 70,
    basePrice: 10,
    tip: 'More drought-tolerant than wheat. Excellent for beer production and livestock feed. Six-row varieties for fodder, two-row for malting—brewers are particular about their rows.',
    nitrogenEffect: -12,
    phosphorusEffect: -6,
    potassiumEffect: -4,
    cropCategory: 'grain',
  },
  rice: {
    name: 'Rice',
    emoji: '🌾',
    description: 'The aquatic grain that fed more humans than any crop in history, transforming swamps into civilization\'s granaries. Paddy cultivation is hydraulic engineering disguised as farming—flood, drain, time with precision or starve.',
    bestPlantingMonths: [4, 5, 6],
    waterNeeds: 'high',
    fertilizerNeeds: 'high',
    growthDays: 120,
    basePrice: 15,
    tip: 'Requires consistent flooding during growth, then draining for harvest. Best in lowland areas with reliable water sources. Labor-intensive but yields three times what wheat can manage per acre.',
    nitrogenEffect: -18,
    phosphorusEffect: -10,
    potassiumEffect: -8,
    cropCategory: 'grain',
  },
  oats: {
    name: 'Oats',
    emoji: '🌾',
    description: 'The Scottish staple that English snobs dismissed as horse food until Dr. Johnson defined it thus in his dictionary. Thrives in rain-soaked climates where wheat merely survives, producing porridge, whisky, and highland stubbornness.',
    bestPlantingMonths: [3, 4, 9],
    waterNeeds: 'moderate',
    fertilizerNeeds: 'low',
    growthDays: 75,
    basePrice: 9,
    tip: 'Thrives in cooler, wetter climates that wheat finds inhospitable. Excellent cover crop that improves soil structure while suppressing weeds. Feed horses or make porridge—ignore English prejudice.',
    nitrogenEffect: -10,
    phosphorusEffect: -5,
    potassiumEffect: -4,
    cropCategory: 'grain',
  },
  rye: {
    name: 'Rye',
    emoji: '🌾',
    description: 'The grain of northern winters and dark breads, surviving frosts that kill wheat while feeding peasants and distillers alike. Ergot fungus occasionally transformed it into medieval LSD, causing dancing plagues and witch trial hallucinations.',
    bestPlantingMonths: [9, 10],
    waterNeeds: 'low',
    fertilizerNeeds: 'low',
    growthDays: 150,
    basePrice: 11,
    tip: 'Most cold-tolerant grain—survives winters that would kill wheat. Plant in fall for spring harvest. Excellent for poor, sandy soils. Check for ergot (purple-black growths) before harvest to avoid poisoning.',
    nitrogenEffect: -13,
    phosphorusEffect: -6,
    potassiumEffect: -5,
    cropCategory: 'grain',
  },

  // Vegetables
  corn: {
    name: 'Corn',
    emoji: '🌽',
    description: 'Maize by any other name—the American gift that doubled European calories per acre and still couldn\'t save Ireland from potato famine. See \'maize\' entry for the respectful version honoring its indigenous origins.',
    bestPlantingMonths: [4, 5, 6],
    waterNeeds: 'high',
    fertilizerNeeds: 'high',
    growthDays: 90,
    basePrice: 14,
    tip: 'Plant after last frost. Benefits greatly from crop rotation with beans and squash (Three Sisters method). Knee-high by July 4th remains the American farmer\'s anxious measure.',
    nitrogenEffect: -20,
    phosphorusEffect: -12,
    potassiumEffect: -10,
    cropCategory: 'grain',
  },
  potatoes: {
    name: 'Potatoes',
    emoji: '🥔',
    description: 'The Andean tuber that fed Ireland until it didn\'t, causing mass starvation when monoculture met potato blight. More calories per acre than grain, easier to hide from tax collectors, harder to mill into taxable flour—peasants loved what lords couldn\'t easily measure.',
    bestPlantingMonths: [3, 4, 7, 8],
    waterNeeds: 'moderate',
    fertilizerNeeds: 'moderate',
    growthDays: 80,
    basePrice: 8,
    tip: 'Plant seed potatoes (not true seeds) 4 inches deep. Hill up soil as plants grow to prevent greening. Store in cool, dark places—light turns them poisonous green.',
    nitrogenEffect: -12,
    phosphorusEffect: -10,
    potassiumEffect: -15,
    cropCategory: 'root',
  },
  tomatoes: {
    name: 'Tomatoes',
    emoji: '🍅',
    description: 'The Aztec tomatl that Europeans thought poisonous for centuries—technically correct about the leaves, spectacularly wrong about the fruit. Italians finally risked it and invented pizza, proving culinary courage occasionally pays dividends.',
    bestPlantingMonths: [4, 5, 6],
    waterNeeds: 'high',
    fertilizerNeeds: 'high',
    growthDays: 75,
    basePrice: 12,
    tip: 'Requires staking or caging unless you prefer ground rot. Water consistently to prevent blossom end rot (calcium deficiency). Prune suckers for larger fruit but lower yields—quantity versus quality, the eternal choice.',
    nitrogenEffect: -18,
    phosphorusEffect: -12,
    potassiumEffect: -15,
    cropCategory: 'vegetable',
  },
  beans: {
    name: 'Beans',
    emoji: '🫘',
    description: 'The atmospheric nitrogen thieves that feed soil while feeding people—rhizobia bacteria colonize roots, stealing nitrogen from air and depositing it as fertilizer. The original regenerative agriculture, practiced millennia before the term existed.',
    bestPlantingMonths: [4, 5, 6],
    waterNeeds: 'moderate',
    fertilizerNeeds: 'low',
    growthDays: 65,
    basePrice: 13,
    tip: 'Fixes nitrogen in soil—rotate beans before nitrogen-hungry crops. Plant after frost danger passes. Bush varieties easier than pole varieties but yield less per square foot.',
    nitrogenEffect: 30,
    phosphorusEffect: -5,
    potassiumEffect: -5,
    cropCategory: 'legume',
  },
  peas: {
    name: 'Peas',
    emoji: '🫛',
    description: 'The spring legume that Gregor Mendel crossed into genetic immortality, discovering heredity by accident while breeding them. Cool-season nitrogen fixers that feed soil and Mendelian laws alike.',
    bestPlantingMonths: [3, 4, 8, 9],
    waterNeeds: 'moderate',
    fertilizerNeeds: 'low',
    growthDays: 60,
    basePrice: 11,
    tip: 'Plant early in spring or late summer—heat makes them bitter and sparse. Provide trellis for climbing varieties. Inoculate seeds with rhizobia if soil has never grown legumes.',
    nitrogenEffect: 28,
    phosphorusEffect: -4,
    potassiumEffect: -4,
    cropCategory: 'legume',
  },
  cabbage: {
    name: 'Cabbage',
    emoji: '🥬',
    description: 'The Germanic winter survival strategy, fermenting into sauerkraut that prevented scurvy on sailing ships and sustained sieges. Captain Cook credited it with keeping crews alive; Germans credit it with cultural identity.',
    bestPlantingMonths: [3, 4, 7, 8],
    waterNeeds: 'moderate',
    fertilizerNeeds: 'moderate',
    growthDays: 70,
    basePrice: 10,
    tip: 'Tolerates light frost—actually sweetens after cold exposure. Harvest before hard freeze. Fermentation into sauerkraut preserves it for months and multiplies vitamin C content.',
    nitrogenEffect: -15,
    phosphorusEffect: -8,
    potassiumEffect: -12,
    cropCategory: 'vegetable',
  },
  turnips: {
    name: 'Turnips',
    emoji: '🫚',
    description: 'The fast-growing root that fed livestock and desperate peasants alike, dismissed by the prosperous as animal fodder. Both root and greens edible—waste nothing was necessity, not virtue, when survival balanced on root vegetables.',
    bestPlantingMonths: [3, 4, 8, 9],
    waterNeeds: 'moderate',
    fertilizerNeeds: 'low',
    growthDays: 55,
    basePrice: 7,
    tip: 'Quick-maturing crop ready in under two months. Both roots and greens edible—harvest greens young. Plant in succession every 2-3 weeks for continuous supply.',
    nitrogenEffect: -8,
    phosphorusEffect: -6,
    potassiumEffect: -10,
    cropCategory: 'root',
  },

  // Fruits & Specialty
  grapes: {
    name: 'Grapes',
    emoji: '🍇',
    description: 'The fruit that launched wine, raisins, and religious metaphors about vines and vineyards. Mesopotamians fermented it, Christians blessed it, Islamic scholars debated it, wine merchants profited from it—all from patient vines producing for decades.',
    bestPlantingMonths: [3, 4],
    waterNeeds: 'moderate',
    fertilizerNeeds: 'moderate',
    growthDays: 365, // Perennial
    basePrice: 25,
    tip: 'Requires 2-3 years to establish before first harvest. Proper pruning essential—bad pruning means meager grapes for years. Terroir matters: same variety tastes different in different soils.',
    farmTypes: ['Vineyard', 'Winery'],
    nitrogenEffect: -12,
    phosphorusEffect: -8,
    potassiumEffect: -15,
    cropCategory: 'fruit',
  },
  olives: {
    name: 'Olives',
    emoji: '🫒',
    description: 'The Mediterranean trinity—oil, food, and peace symbols from trees that outlive empires. Plant for your grandchildren; some grove trees pre-date Christ while still producing olives, which is either inspiring or depressing depending on your timeframe preferences.',
    bestPlantingMonths: [3, 4, 10],
    waterNeeds: 'low',
    fertilizerNeeds: 'low',
    growthDays: 365, // Perennial
    basePrice: 30,
    tip: 'Drought-tolerant once established. Takes 5-8 years for first harvest, then produces for centuries. Press immediately for oil or cure in brine for table olives—raw olives are inedibly bitter.',
    farmTypes: ['Olive Grove', 'Olive Orchard'],
    nitrogenEffect: -8,
    phosphorusEffect: -6,
    potassiumEffect: -10,
    cropCategory: 'fruit',
  },
  cotton: {
    name: 'Cotton',
    emoji: '☁️',
    description: 'The fiber that clothed the world and enslaved millions—from Indian calicos that outraged British wool merchants to American plantations built on forced labor. Mechanization eventually replaced hands bloody from picking, though not before cotton picked history clean of innocence.',
    bestPlantingMonths: [4, 5],
    waterNeeds: 'moderate',
    fertilizerNeeds: 'high',
    growthDays: 150,
    basePrice: 22,
    tip: 'Highly profitable but labor-intensive and soil-depleting. Requires long, hot growing season—180+ frost-free days. Rotate aggressively or watch yields collapse as soil exhaustion sets in.',
    farmTypes: ['Cotton Plantation', 'Cotton Farm'],
    nitrogenEffect: -25,
    phosphorusEffect: -15,
    potassiumEffect: -18,
    cropCategory: 'vegetable',
  },
  tobacco: {
    name: 'Tobacco',
    emoji: '🍂',
    description: 'The addictive colonial cash crop that built Virginia\'s economy and destroyed lungs globally. Curing barns perfumed countryside with sweet decay while merchant ships carried leaves that enslaved planters to perpetual debt and consumers to perpetual craving.',
    bestPlantingMonths: [4, 5],
    waterNeeds: 'moderate',
    fertilizerNeeds: 'high',
    growthDays: 120,
    basePrice: 28,
    tip: 'Valuable but demanding—requires specific curing barns and knowledge. Heavy soil feeder; rotate with cover crops or face declining yields. Hand-harvest, hand-cure, hand-grade: labor costs are relentless.',
    farmTypes: ['Tobacco Plantation', 'Tobacco Farm'],
    nitrogenEffect: -22,
    phosphorusEffect: -14,
    potassiumEffect: -16,
    cropCategory: 'vegetable',
  },
  sugar: {
    name: 'Sugar Cane',
    emoji: '🎋',
    description: 'The sweetness that justified the unspeakable—sugar plantations fueled the slave trade, enriched merchants, rotted teeth, and created Caribbean monocultures. What began as luxury spice became working-class necessity, transforming global economics one teaspoon at a time.',
    bestPlantingMonths: [3, 4, 5],
    waterNeeds: 'high',
    fertilizerNeeds: 'high',
    growthDays: 365,
    basePrice: 35,
    tip: 'Requires tropical climate and abundant water. Brutally labor-intensive harvest—stalks cut by hand, processed quickly before sugar content drops. Ratoons (regrowth) produce for 3-5 years before replanting needed.',
    farmTypes: ['Sugar Plantation', 'Sugar Estate'],
    nitrogenEffect: -20,
    phosphorusEffect: -12,
    potassiumEffect: -15,
    cropCategory: 'vegetable',
  },
  flax: {
    name: 'Flax',
    emoji: '🌾',
    description: 'The dual-purpose crop producing linen thread and linseed oil from the same plant—textile or lamp fuel, clothing or light, thread or paint medium. Egyptian mummies wrapped in it three millennia ago prove linen\'s durability outlasts civilizations.',
    bestPlantingMonths: [3, 4],
    waterNeeds: 'moderate',
    fertilizerNeeds: 'low',
    growthDays: 90,
    basePrice: 16,
    tip: 'Seeds yield linseed oil (for paint, preservatives), stalks produce linen fiber (for cloth, rope). Retting process—controlled rotting in water—separates fiber from woody core. Timing is everything; over-rett and fibers rot too.',
    nitrogenEffect: -10,
    phosphorusEffect: -6,
    potassiumEffect: -8,
    cropCategory: 'vegetable',
  },
  millet: {
    name: 'Millet',
    emoji: '🌾',
    description: 'The humble grain that feeds millions where wheat and rice surrender to drought—Africa and India know its value though European histories ignore it. Nutritious, fast-growing, undemanding: virtues that impress subsistence farmers more than agricultural historians.',
    bestPlantingMonths: [5, 6],
    waterNeeds: 'low',
    fertilizerNeeds: 'low',
    growthDays: 75,
    basePrice: 9,
    tip: 'Excellent for marginal soils and dry climates where other grains fail. Fast-growing—ready in 75 days. Highly nutritious with more protein than rice. Birds love it too; netting helps at harvest.',
    nitrogenEffect: -8,
    phosphorusEffect: -5,
    potassiumEffect: -4,
    cropCategory: 'grain',
  },
  sorghum: {
    name: 'Sorghum',
    emoji: '🌾',
    description: 'The heat-loving grain that thrives where corn wilts and wheat withers—African origins, global reach, multiple uses from syrup to animal feed. Drought tolerance makes it climate change\'s favorite grain, though recognition came late as usual.',
    bestPlantingMonths: [5, 6],
    waterNeeds: 'low',
    fertilizerNeeds: 'low',
    growthDays: 90,
    basePrice: 10,
    tip: 'Thrives in hot, dry conditions—needs less water than corn. Used for grain, syrup (from sweet varieties), and animal feed. Wait until soil warms to plant; cold soil invites disease.',
    nitrogenEffect: -9,
    phosphorusEffect: -5,
    potassiumEffect: -5,
    cropCategory: 'grain',
  },
  lentils: {
    name: 'Lentils',
    emoji: '🫘',
    description: 'The biblical pottage for which Esau sold his birthright—protein-rich pulses feeding Middle Eastern civilizations since Neolithic times. Nitrogen-fixing roots and drought tolerance made them survival food that incidentally enriched soil for next year\'s wheat.',
    bestPlantingMonths: [3, 4, 9],
    waterNeeds: 'low',
    fertilizerNeeds: 'low',
    growthDays: 90,
    basePrice: 14,
    tip: 'Nitrogen-fixing legume—excellent rotation crop before wheat or barley. Stores indefinitely when dried. Thrives in cool weather; plant early spring or autumn. Harvest when pods rattle.',
    nitrogenEffect: 25, // Legumes fix nitrogen
    phosphorusEffect: -5,
    potassiumEffect: -3,
    cropCategory: 'legume',
  },
  apples: {
    name: 'Apples',
    emoji: '🍎',
    description: 'The fruit that tempted Eve, fed Newton\'s physics, and built American folklore around Johnny Appleseed—whose real mission was cider orchards, not wholesome snacks. Every apple is a genetic lottery; plant seeds and get wild apples, graft scions for reliable sweetness.',
    bestPlantingMonths: [3, 4, 10, 11],
    waterNeeds: 'moderate',
    fertilizerNeeds: 'moderate',
    growthDays: 365, // Perennial
    basePrice: 20,
    tip: 'Requires 3-5 years before first fruit, then decades of production. Proper pruning and fruit thinning essential—too many apples means small, bitter ones. Requires winter chill hours; check variety matches your climate.',
    farmTypes: ['Apple Orchard', 'Orchard'],
    nitrogenEffect: -10,
    phosphorusEffect: -8,
    potassiumEffect: -12,
    cropCategory: 'fruit',
  },
  pears: {
    name: 'Pears',
    emoji: '🍐',
    description: 'The elegant fruit that ripens off the tree, demanding judgment and patience—pick too early and they never sweeten, too late and the core rots while skin stays perfect. More fire blight resistant than apples but mysteriously less celebrated despite superior texture.',
    bestPlantingMonths: [3, 4, 11],
    waterNeeds: 'moderate',
    fertilizerNeeds: 'low',
    growthDays: 365, // Perennial
    basePrice: 18,
    tip: 'Pick before fully ripe and ripen indoors at room temperature—pears ripen from inside out. More tolerant of heavy clay soils than apples. Asian and European varieties require different climates.',
    farmTypes: ['Pear Orchard', 'Orchard'],
    nitrogenEffect: -8,
    phosphorusEffect: -6,
    potassiumEffect: -10,
    cropCategory: 'fruit',
  },
  plums: {
    name: 'Plums',
    emoji: '🍑',
    description: 'The stone fruit with more varieties than poets have metaphors—from tiny damsons to massive Santa Rosas, each adapted to different climates and uses. Fresh, dried as prunes, fermented into slivovitz: plums accommodate every preservation method humans invented.',
    bestPlantingMonths: [3, 4],
    waterNeeds: 'moderate',
    fertilizerNeeds: 'moderate',
    growthDays: 365, // Perennial
    basePrice: 17,
    tip: 'Excellent for fresh eating, jams, drying, and fermentation. Prune after harvest to maintain shape and productivity. Japanese and European varieties need different chill hours—match variety to your winter.',
    farmTypes: ['Plum Orchard', 'Orchard'],
    nitrogenEffect: -9,
    phosphorusEffect: -7,
    potassiumEffect: -11,
    cropCategory: 'fruit',
  },
  cherries: {
    name: 'Cherries',
    emoji: '🍒',
    description: 'The premium stone fruit that commands premium prices for good reason—birds steal half, rain splits the rest, and what survives demands gentle handling lest bruising destroy value. Sweet or sour, both require protection from avian thieves and weather caprices.',
    bestPlantingMonths: [3, 4],
    waterNeeds: 'moderate',
    fertilizerNeeds: 'moderate',
    growthDays: 365, // Perennial
    basePrice: 28,
    tip: 'Netting absolutely essential to protect from birds—they will strip a tree overnight. Rain during ripening causes splitting; covered orchards help but add cost. Sweet cherries self-incompatible; need pollinator variety nearby.',
    farmTypes: ['Cherry Orchard', 'Orchard'],
    nitrogenEffect: -10,
    phosphorusEffect: -8,
    potassiumEffect: -12,
    cropCategory: 'fruit',
  },
  dates: {
    name: 'Dates',
    emoji: '🌴',
    description: 'The desert palm fruit that made Saharan trade possible and oasis civilization viable—condensed sweetness in hostile heat, storing for months while providing concentrated calories. Female trees bear fruit; males pollinate; Mesopotamians discovered artificial pollination millennia before Mendel.',
    bestPlantingMonths: [3, 4],
    waterNeeds: 'low',
    fertilizerNeeds: 'low',
    growthDays: 365, // Perennial
    basePrice: 32,
    tip: 'Thrives in extreme heat and aridity—feet in water, head in fire as the Arabic saying goes. Takes 4-8 years to fruit, then produces for decades. One male tree pollinates 40 females; traditional growers hand-pollinate.',
    farmTypes: ['Date Palm Grove', 'Palm Grove'],
    nitrogenEffect: -5,
    phosphorusEffect: -4,
    potassiumEffect: -8,
    cropCategory: 'fruit',
  },

  // Additional grains and staples
  maize: {
    name: 'Maize',
    emoji: '🌽',
    description: 'The revolutionary gift of the Americas that transformed global agriculture with yields that made wheat seem positively miserly. Three Sisters companion planting turned subsistence into abundance.',
    bestPlantingMonths: [4, 5, 6],
    waterNeeds: 'moderate',
    fertilizerNeeds: 'high',
    growthDays: 90,
    basePrice: 14,
    tip: 'Plant alongside beans (nitrogen fixers) and squash (weed suppressors) for the legendary Three Sisters polyculture. Hill planting prevents toppling.',
    nitrogenEffect: -20,
    phosphorusEffect: -12,
    potassiumEffect: -10,
    cropCategory: 'grain',
  },

  quinoa: {
    name: 'Quinoa',
    emoji: '🌾',
    description: 'The Andean mother grain that sustained empires at elevations where lesser crops surrendered to altitude. A complete protein that modern nutritionists discovered some four millennia after the Incas.',
    bestPlantingMonths: [3, 4],
    waterNeeds: 'low',
    fertilizerNeeds: 'low',
    growthDays: 100,
    basePrice: 18,
    tip: 'Thrives in poor soils and high altitudes where other crops fail. Saponins in seed coat deter birds but require rinsing before consumption.',
    nitrogenEffect: -8,
    phosphorusEffect: -5,
    potassiumEffect: -6,
    cropCategory: 'grain',
  },

  // Root crops
  yams: {
    name: 'Yams',
    emoji: '🍠',
    description: 'Not to be confused with the sweet potato despite centuries of American confusion. True yams sustained West African civilizations and crossed the Atlantic in slave ships as familiar sustenance.',
    bestPlantingMonths: [3, 4, 5],
    waterNeeds: 'moderate',
    fertilizerNeeds: 'moderate',
    growthDays: 180,
    basePrice: 11,
    tip: 'Requires staking for climbing vines. Can grow massive (50+ pounds). Store in cool, dry conditions; they keep for months unlike their sweet potato impostors.',
    nitrogenEffect: -10,
    phosphorusEffect: -12,
    potassiumEffect: -15,
    cropCategory: 'root',
  },

  cassava: {
    name: 'Cassava',
    emoji: '🥔',
    description: 'The forgiveness plant of tropical agriculture—thrives in poor soil, survives drought, waits patiently underground until harvest suits the farmer. Contains cyanide until properly processed, teaching humility to the hasty.',
    bestPlantingMonths: [3, 4, 5, 6],
    waterNeeds: 'low',
    fertilizerNeeds: 'low',
    growthDays: 240,
    basePrice: 9,
    tip: 'Plant stem cuttings at angle. Harvest flexible (8-24 months). CRITICAL: Must be properly processed to remove cyanogenic glucosides before consumption—soak, ferment, or cook thoroughly.',
    nitrogenEffect: -6,
    phosphorusEffect: -8,
    potassiumEffect: -12,
    cropCategory: 'root',
  },

  taro: {
    name: 'Taro',
    emoji: '🍠',
    description: 'The poi plant that fed Polynesian voyagers across impossible oceans and sustained Hawaiian kingdoms. Both corm and leaf nourish, provided one respects the oxalic acid.',
    bestPlantingMonths: [3, 4, 5, 6],
    waterNeeds: 'high',
    fertilizerNeeds: 'moderate',
    growthDays: 180,
    basePrice: 13,
    tip: 'Grows in flooded paddies or dry land. Raw taro is toxic—always cook before eating. Harvest when leaves yellow. Excellent for tropical swamplands.',
    nitrogenEffect: -10,
    phosphorusEffect: -10,
    potassiumEffect: -14,
    cropCategory: 'root',
  },

  // Fiber and dye crops
  madder: {
    name: 'Madder',
    emoji: '🌿',
    description: 'The root that dressed European armies in red for centuries until aniline dyes rendered its cultivation quaint. Alizarin from madder painted everything from Turkish carpets to British redcoats.',
    bestPlantingMonths: [3, 4],
    waterNeeds: 'moderate',
    fertilizerNeeds: 'moderate',
    growthDays: 540, // 18 months for roots
    basePrice: 26,
    tip: 'Roots harvested after 18 months for best dye content. Requires well-drained soil. Historical mordanting with alum produces the finest Turkey red. Labor-intensive but highly profitable.',
    farmTypes: ['Dye Farm', 'Madder Farm'],
    nitrogenEffect: -12,
    phosphorusEffect: -8,
    potassiumEffect: -10,
    cropCategory: 'vegetable',
  },

  indigo: {
    name: 'Indigo',
    emoji: '🌿',
    description: 'The blue that built empires and broke bodies—from Indian plantations to Carolina swamps. The fermentation process smelled of hell but produced the truest blue known to premodern dyers.',
    bestPlantingMonths: [4, 5, 6],
    waterNeeds: 'moderate',
    fertilizerNeeds: 'moderate',
    growthDays: 90,
    basePrice: 32,
    tip: 'Cut plants before flowering for maximum indican content. Fermentation process is malodorous but critical—timing determines dye quality. Multiple harvests possible per season in warm climates.',
    farmTypes: ['Indigo Plantation', 'Dye Farm'],
    nitrogenEffect: -15,
    phosphorusEffect: -10,
    potassiumEffect: -12,
    cropCategory: 'vegetable',
  },

  woad: {
    name: 'Woad',
    emoji: '🌿',
    description: 'Europe\'s inferior answer to Indian indigo, grown desperately for blue dye until colonial trade made it obsolete. Caesar reported Britons painting themselves with it, though scholars debate whether warriors or mere fashion.',
    bestPlantingMonths: [3, 4, 8, 9],
    waterNeeds: 'moderate',
    fertilizerNeeds: 'low',
    growthDays: 75,
    basePrice: 18,
    tip: 'Biennial crop—leaves in first year, seeds in second. Fermentation process similar to indigo but yields weaker dye. Plant in autumn for spring harvest of best leaves.',
    farmTypes: ['Dye Farm'],
    nitrogenEffect: -10,
    phosphorusEffect: -6,
    potassiumEffect: -8,
    cropCategory: 'vegetable',
  },

  hemp: {
    name: 'Hemp',
    emoji: '🌿',
    description: 'The Puritan crop—useful for everything from rope to paper while remaining virtuously un-intoxicating. Colonial governments mandated its cultivation; navies depended on its fibers for rigging.',
    bestPlantingMonths: [4, 5],
    waterNeeds: 'moderate',
    fertilizerNeeds: 'moderate',
    growthDays: 90,
    basePrice: 15,
    tip: 'Dense planting produces tall, straight stalks ideal for fiber. Harvest before seed formation for best fiber quality. Retting (controlled rotting) separates fibers from woody core.',
    nitrogenEffect: -14,
    phosphorusEffect: -8,
    potassiumEffect: -10,
    cropCategory: 'vegetable',
  },

  jute: {
    name: 'Jute',
    emoji: '🌿',
    description: 'The golden fiber of Bengal that wove its way into global commerce as burlap and hessian. Monsoon-dependent cultivation created seasonal rhythms that structured Bengali village life.',
    bestPlantingMonths: [3, 4, 5],
    waterNeeds: 'high',
    fertilizerNeeds: 'moderate',
    growthDays: 120,
    basePrice: 14,
    tip: 'Requires warm, humid climate. Harvest before flowering for finest fiber. Retting in standing water for 15-20 days. Second only to cotton in global fiber production historically.',
    nitrogenEffect: -12,
    phosphorusEffect: -8,
    potassiumEffect: -10,
    cropCategory: 'vegetable',
  },

  // Stimulants and luxuries
  tea: {
    name: 'Tea',
    emoji: '🍵',
    description: 'The leaf that altered consciousness politely and sparked empires impolitely. From Buddhist monks seeking alertness to British smuggling opium for its purchase, tea rewrote economic and moral geographies.',
    bestPlantingMonths: [3, 4],
    waterNeeds: 'high',
    fertilizerNeeds: 'moderate',
    growthDays: 1095, // 3 years to first harvest
    basePrice: 45,
    tip: 'Requires acidic soil and consistent moisture. First harvest after 3 years; productive for decades. Pick only newest shoots and young leaves. Altitude and processing method determine quality grades.',
    farmTypes: ['Tea Plantation', 'Tea Estate'],
    nitrogenEffect: -12,
    phosphorusEffect: -8,
    potassiumEffect: -14,
    cropCategory: 'vegetable',
  },

  coffee: {
    name: 'Coffee',
    emoji: '☕',
    description: 'The Ethiopian berry that Sufis discovered for night prayers and capitalism weaponized for worker productivity. Shade-grown or sun-grown, the choice between ecology and expedience.',
    bestPlantingMonths: [4, 5],
    waterNeeds: 'high',
    fertilizerNeeds: 'moderate',
    growthDays: 1460, // 4 years to first harvest
    basePrice: 52,
    tip: 'Requires shade, altitude, and patience. Volcanic soil ideal. First harvest after 4 years. Two harvests annually in ideal conditions. Processing method (wet vs dry) dramatically affects flavor profile.',
    farmTypes: ['Coffee Plantation', 'Coffee Estate'],
    nitrogenEffect: -14,
    phosphorusEffect: -10,
    potassiumEffect: -16,
    cropCategory: 'fruit',
  },

  opium: {
    name: 'Opium Poppy',
    emoji: '🌸',
    description: 'The poppy of contradictions—medical miracle and imperial weapon, grown by impoverished farmers to impoverish Chinese smokers. Lancets score pods at dawn; morphine weeps into history.',
    bestPlantingMonths: [10, 11],
    waterNeeds: 'low',
    fertilizerNeeds: 'moderate',
    growthDays: 120,
    basePrice: 75,
    tip: 'Sow in autumn for spring harvest. Score pods after petals fall; harvest latex after overnight secretion. Highly regulated in modern times. Historical British-Indian monopoly devastated Chinese economy.',
    farmTypes: ['Opium Plantation'],
    nitrogenEffect: -10,
    phosphorusEffect: -8,
    potassiumEffect: -10,
    cropCategory: 'vegetable',
  },

  // Additional vegetables and crops
  squash: {
    name: 'Squash',
    emoji: '🎃',
    description: 'The ground-covering sister of the Three Sisters trio, smothering weeds while beans climbed corn stalks. Indigenous American polyculture at its most elegant.',
    bestPlantingMonths: [4, 5, 6],
    waterNeeds: 'moderate',
    fertilizerNeeds: 'moderate',
    growthDays: 80,
    basePrice: 10,
    tip: 'Plant between corn rows for natural weed suppression and soil moisture retention. Large leaves shade soil. Both fruit and flowers edible. Winter squash stores for months.',
    nitrogenEffect: -12,
    phosphorusEffect: -8,
    potassiumEffect: -10,
    cropCategory: 'vegetable',
  },

  chickpeas: {
    name: 'Chickpeas',
    emoji: '🫘',
    description: 'The Mediterranean legume that fed philosophers and peasants alike, fixing nitrogen while producing protein. Hummus\' humble origin.',
    bestPlantingMonths: [2, 3, 10],
    waterNeeds: 'low',
    fertilizerNeeds: 'low',
    growthDays: 100,
    basePrice: 13,
    tip: 'Drought-tolerant once established. Sow in autumn in Mediterranean climates, spring elsewhere. Nitrogen-fixing makes excellent rotation crop. Harvest when pods dry and rattle.',
    nitrogenEffect: 28,
    phosphorusEffect: -6,
    potassiumEffect: -6,
    cropCategory: 'legume',
  },

  soybeans: {
    name: 'Soybeans',
    emoji: '🫘',
    description: 'The Chinese gift to global protein supply, transformed by fermentation into myriad forms. Nitrogen-fixing nodules feed the soil while feeding civilizations.',
    bestPlantingMonths: [5, 6],
    waterNeeds: 'moderate',
    fertilizerNeeds: 'low',
    growthDays: 100,
    basePrice: 12,
    tip: 'Inoculate seeds with proper rhizobia bacteria for nitrogen fixation. Harvest when leaves yellow and pods dry. Rotation crop par excellence. Processing into tofu, tempeh, or fermented forms unlocks nutrition.',
    nitrogenEffect: 30,
    phosphorusEffect: -5,
    potassiumEffect: -8,
    cropCategory: 'legume',
  },

  groundnuts: {
    name: 'Groundnuts (Peanuts)',
    emoji: '🥜',
    description: 'The underground legume that feeds African and American soils while producing oil and protein. Carver discovered three hundred uses; history needed only deliciousness.',
    bestPlantingMonths: [4, 5],
    waterNeeds: 'moderate',
    fertilizerNeeds: 'low',
    growthDays: 120,
    basePrice: 15,
    tip: 'Requires warm soil. Flowers pollinate above ground but nuts develop below—hill soil around plant base. Nitrogen-fixing capability makes excellent rotation crop. Cure for 2-3 weeks after harvest.',
    nitrogenEffect: 25,
    phosphorusEffect: -7,
    potassiumEffect: -8,
    cropCategory: 'legume',
  },

  melons: {
    name: 'Melons',
    emoji: '🍈',
    description: 'Desert fruits that taught agriculture the value of sweetness and hydration. From Persian gardens to Silk Road oases, melons made arid summers endurable.',
    bestPlantingMonths: [4, 5, 6],
    waterNeeds: 'moderate',
    fertilizerNeeds: 'high',
    growthDays: 85,
    basePrice: 14,
    tip: 'Require warm soil and long season. Hill planting improves drainage. Reduce watering as fruit ripens for sweetness. Knock test for ripeness—dull thud indicates maturity.',
    nitrogenEffect: -15,
    phosphorusEffect: -10,
    potassiumEffect: -18,
    cropCategory: 'fruit',
  },

  'bok choy': {
    name: 'Bok Choy',
    emoji: '🥬',
    description: 'The Chinese cabbage that grows quickly and asks little, feeding stir-fries and soups across East Asia. Cool-season vigor meets culinary versatility.',
    bestPlantingMonths: [3, 4, 8, 9],
    waterNeeds: 'moderate',
    fertilizerNeeds: 'moderate',
    growthDays: 45,
    basePrice: 11,
    tip: 'Fast-growing—harvest in 45 days. Succession plant every 2 weeks for continuous supply. Bolts in heat—grow in cool seasons. Cut-and-come-again harvesting possible.',
    nitrogenEffect: -10,
    phosphorusEffect: -6,
    potassiumEffect: -8,
    cropCategory: 'vegetable',
  },

  radishes: {
    name: 'Radishes',
    emoji: '🔴',
    description: 'The sprinter of the vegetable world, ready in three weeks with peppery urgency. From French breakfast types to daikon giants, size and speed vary while pungency persists.',
    bestPlantingMonths: [3, 4, 5, 8, 9, 10],
    waterNeeds: 'moderate',
    fertilizerNeeds: 'low',
    growthDays: 25,
    basePrice: 8,
    tip: 'Fastest crop to maturity—ready in 3-4 weeks. Succession plant every week. Harvest promptly or they become woody and bitter. Excellent for breaking up heavy soil.',
    nitrogenEffect: -5,
    phosphorusEffect: -4,
    potassiumEffect: -6,
    cropCategory: 'root',
  },

  sunflowers: {
    name: 'Sunflowers',
    emoji: '🌻',
    description: 'The American heliotrope that gave Pre-Columbian farmers oil and followed conquistadors back to Europe. Faces east at dawn, having tracked the sun all night in reverse.',
    bestPlantingMonths: [4, 5, 6],
    waterNeeds: 'moderate',
    fertilizerNeeds: 'moderate',
    growthDays: 90,
    basePrice: 16,
    tip: 'Tap root seeks deep moisture—drought tolerant once established. Plant in blocks for better pollination. Protect from birds with netting. Harvest when back of head turns yellow-brown.',
    nitrogenEffect: -12,
    phosphorusEffect: -10,
    potassiumEffect: -12,
    cropCategory: 'vegetable',
  },

  'sweet potato': {
    name: 'Sweet Potato',
    emoji: '🍠',
    description: 'The tropical tuber often mistaken for a yam by Americans who should know better. Vitamin A abundance prevented blindness in children wherever it spread from American origins.',
    bestPlantingMonths: [5, 6],
    waterNeeds: 'moderate',
    fertilizerNeeds: 'low',
    growthDays: 100,
    basePrice: 12,
    tip: 'Requires warm soil and long season. Plant slips, not seeds. Harvest before first frost. Cure at warm temperature and high humidity for sweetness development and storage life.',
    nitrogenEffect: -8,
    phosphorusEffect: -10,
    potassiumEffect: -15,
    cropCategory: 'root',
  },

  breadfruit: {
    name: 'Breadfruit',
    emoji: '🥖',
    description: 'The Polynesian staple that Captain Bligh couldn\'t deliver before mutiny. Productive trees feed families for generations; roasted fruit tastes of bread hence the optimistic name.',
    bestPlantingMonths: [3, 4],
    waterNeeds: 'high',
    fertilizerNeeds: 'moderate',
    growthDays: 1825, // 5 years to first harvest
    basePrice: 35,
    tip: 'Requires tropical climate. First fruit after 5 years, then produces for decades. Trees can yield 200+ fruits annually. Harvest at mature green stage. Roast, boil, or ferment for preservation.',
    farmTypes: ['Breadfruit Grove'],
    nitrogenEffect: -10,
    phosphorusEffect: -8,
    potassiumEffect: -12,
    cropCategory: 'fruit',
  },

  coconut: {
    name: 'Coconut',
    emoji: '🥥',
    description: 'The tree of life that floats across oceans and feeds tropical civilizations. Water, meat, oil, fiber, thatch—every part serves, nothing wastes.',
    bestPlantingMonths: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12], // Year-round in tropics
    waterNeeds: 'moderate',
    fertilizerNeeds: 'low',
    growthDays: 2555, // 7 years to first harvest
    basePrice: 40,
    tip: 'Requires coastal tropical climate. First nuts after 7 years; productive for 80+ years. Plant nuts on side, partially buried. Salt-tolerant. Harvest timing determines use—young for water, mature for oil.',
    farmTypes: ['Coconut Plantation', 'Palm Grove'],
    nitrogenEffect: -8,
    phosphorusEffect: -6,
    potassiumEffect: -10,
    cropCategory: 'fruit',
  },

  spices: {
    name: 'Spices',
    emoji: '🌶️',
    description: 'The category that launched a thousand ships and justified countless atrocities. Pepper, cinnamon, cloves, nutmeg—each sparked voyages, wars, and empires built on preserved meat.',
    bestPlantingMonths: [4, 5, 6],
    waterNeeds: 'moderate',
    fertilizerNeeds: 'moderate',
    growthDays: 365,
    basePrice: 60,
    tip: 'Perennial crops requiring tropical conditions. Each spice has unique cultivation needs. Pepper vines climb; cinnamon bark strips; cloves are flower buds. Processing and drying critical for quality and value.',
    farmTypes: ['Spice Plantation'],
    nitrogenEffect: -10,
    phosphorusEffect: -8,
    potassiumEffect: -12,
    cropCategory: 'vegetable',
  },

  rubber: {
    name: 'Rubber',
    emoji: '⭕',
    description: 'The latex that oozed from Amazonian trees and industrialized into tires, transforming warfare and commerce. Plantations in Southeast Asia broke Brazilian monopoly through botanical theft disguised as science.',
    bestPlantingMonths: [4, 5],
    waterNeeds: 'high',
    fertilizerNeeds: 'moderate',
    growthDays: 2190, // 6 years to first tapping
    basePrice: 38,
    tip: 'Requires tropical climate and 6-7 years before tapping. Score bark in spiral pattern; latex flows into collection cups. Tree can be tapped for 25+ years. Morning tapping yields more latex.',
    farmTypes: ['Rubber Plantation'],
    nitrogenEffect: -12,
    phosphorusEffect: -8,
    potassiumEffect: -10,
    cropCategory: 'vegetable',
  },
};

// Helper function to get month name
export function getMonthName(month: number): string {
  const months = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'];
  return months[month - 1] || '';
}

// Helper to format planting season
export function formatPlantingSeason(months: number[]): string {
  if (months.length === 0) return 'Any time';
  if (months.length === 1) return getMonthName(months[0]);
  if (months.length === 2) return `${getMonthName(months[0])}-${getMonthName(months[1])}`;

  // Group consecutive months
  const ranges: string[] = [];
  let start = months[0];
  let prev = months[0];

  for (let i = 1; i <= months.length; i++) {
    const current = months[i];
    if (current !== prev + 1 || i === months.length) {
      if (start === prev) {
        ranges.push(getMonthName(start));
      } else {
        ranges.push(`${getMonthName(start)}-${getMonthName(prev)}`);
      }
      start = current;
    }
    prev = current;
  }

  return ranges.join(', ');
}
