/**
 * constants/gameData/itemDefinitions.ts - Base definitions for all items and crops.
 */
import { ItemDefinition, CulturalZone, ClimateType } from '../../types';

export const ITEM_DEFINITIONS: Record<string, ItemDefinition> = {
    // --- Tools ---
    AXE: { baseId: 'AXE', name: 'Axe', description: 'A sturdy axe for chopping wood or other materials.', emoji: '🪓', rarity: 'Common', value: 10, weight: 2.0, wearable: false, stackable: false, attack: 4, sustenance: 0, wieldable: true, throwable: false, craftingValue: 5, category: 'Tool', material: 'Iron', equipmentSlot: 'main_hand' },
    PICKAXE: { baseId: 'PICKAXE', name: 'Pickaxe', description: 'A heavy pickaxe for breaking rocks and mining ore.', emoji: '⛏️', rarity: 'Common', value: 12, weight: 3.0, wearable: false, stackable: false, attack: 3, sustenance: 0, wieldable: true, throwable: false, craftingValue: 6, category: 'Tool', material: 'Iron', equipmentSlot: 'main_hand' },
    STEEL_PICKAXE: { baseId: 'STEEL_PICKAXE', name: 'Steel Pickaxe', description: 'A well-made steel pickaxe, more efficient than iron.', emoji: '⛏️', rarity: 'Uncommon', value: 40, weight: 2.8, wearable: false, stackable: false, attack: 4, sustenance: 0, wieldable: true, throwable: false, craftingValue: 8, category: 'Tool', material: 'Steel', equipmentSlot: 'main_hand' },
    
    // --- Ores ---
    IRON_ORE: { baseId: 'IRON_ORE', name: 'Iron Ore', description: 'A chunk of rock rich with iron.', emoji: '🪨', rarity: 'Common', value: 5, weight: 2.5, wearable: false, stackable: true, attack: 1, sustenance: 0, wieldable: true, throwable: true, craftingValue: 4, category: 'Material', material: 'Iron', equipmentSlot: 'main_hand' },
    TIN_ORE: { baseId: 'TIN_ORE', name: 'Tin Ore', description: 'A soft, silvery-white metal ore.', emoji: '🪨', rarity: 'Common', value: 4, weight: 2.2, wearable: false, stackable: true, attack: 1, sustenance: 0, wieldable: true, throwable: true, craftingValue: 3, category: 'Material', equipmentSlot: 'main_hand' },
    COPPER_ORE: { baseId: 'COPPER_ORE', name: 'Copper Ore', description: 'Rock containing veins of reddish-brown copper.', emoji: '🪨', rarity: 'Common', value: 6, weight: 2.8, wearable: false, stackable: true, attack: 1, sustenance: 0, wieldable: true, throwable: true, craftingValue: 4, category: 'Material', material: 'Copper', equipmentSlot: 'main_hand' },
    GOLD_ORE: { baseId: 'GOLD_ORE', name: 'Gold Ore', description: 'A heavy rock with glittering flecks of gold.', emoji: '🌟', rarity: 'Rare', value: 50, weight: 3.5, wearable: false, stackable: true, attack: 1, sustenance: 0, wieldable: true, throwable: true, craftingValue: 10, category: 'Material', equipmentSlot: 'main_hand' },
    SILVER_ORE: { baseId: 'SILVER_ORE', name: 'Silver Ore', description: 'A rock with gleaming veins of silver.', emoji: '🪨', rarity: 'Uncommon', value: 25, weight: 3.0, wearable: false, stackable: true, attack: 1, sustenance: 0, wieldable: true, throwable: true, craftingValue: 8, category: 'Material' },
    LEAD_ORE: { baseId: 'LEAD_ORE', name: 'Lead Ore', description: 'A dense, dull grey ore.', emoji: '🪨', rarity: 'Common', value: 3, weight: 4.0, wearable: false, stackable: true, attack: 1, sustenance: 0, wieldable: true, throwable: true, craftingValue: 3, category: 'Material' },
    COAL: { baseId: 'COAL', name: 'Lump of Coal', description: 'A black, combustible sedimentary rock.', emoji: '⚫', rarity: 'Common', value: 2, weight: 1.0, wearable: false, stackable: true, attack: 0, sustenance: 0, wieldable: false, throwable: true, craftingValue: 2, category: 'Material' },
    ROCK_SALT: { baseId: 'ROCK_SALT', name: 'Rock Salt', description: 'A crystalline chunk of salt, useful for preserving food.', emoji: '🧂', rarity: 'Common', value: 4, weight: 1.0, wearable: false, stackable: true, attack: 0, sustenance: 0, wieldable: false, throwable: true, craftingValue: 1, category: 'Material' },
    CLAY_LUMP: { baseId: 'CLAY_LUMP', name: 'Lump of Clay', description: 'A soft lump of raw clay, ready for pottery.', emoji: '🏺', rarity: 'Common', value: 1, weight: 1.5, wearable: false, stackable: true, attack: 0, sustenance: 0, wieldable: false, throwable: true, craftingValue: 3, category: 'Material' },
    OCHRE_LUMP: { baseId: 'OCHRE_LUMP', name: 'Lump of Ochre', description: 'A soft, earthy pigment.', emoji: '🎨', rarity: 'Common', value: 8, weight: 0.5, wearable: false, stackable: true, attack: 0, sustenance: 0, wieldable: false, throwable: false, craftingValue: 3, category: 'Material' },
    FLINT_STONE: { baseId: 'FLINT_STONE', name: 'Flint Stone', description: 'A hard, sedimentary cryptocrystalline form of quartz.', emoji: '🪨', rarity: 'Common', value: 3, weight: 1.0, wearable: false, stackable: true, attack: 1, sustenance: 0, wieldable: true, throwable: true, craftingValue: 4, category: 'Material' },
    STONE_BLOCK: { baseId: 'STONE_BLOCK', name: 'Stone Block', description: 'A rough block of quarried stone.', emoji: '🧱', rarity: 'Common', value: 2, weight: 10.0, wearable: false, stackable: true, attack: 0, sustenance: 0, wieldable: false, throwable: false, craftingValue: 1, category: 'Material' },

    // --- Processed Metals ---
    IRON_INGOT: { baseId: 'IRON_INGOT', name: 'Iron Ingot', description: 'A bar of refined iron, ready for forging.', emoji: '🔩', rarity: 'Common', value: 15, weight: 2.0, wearable: false, stackable: true, attack: 2, sustenance: 0, wieldable: true, throwable: false, craftingValue: 6, category: 'Material', material: 'Iron' },
    COPPER_INGOT: { baseId: 'COPPER_INGOT', name: 'Copper Ingot', description: 'A bar of refined copper.', emoji: '🔩', rarity: 'Common', value: 18, weight: 2.2, wearable: false, stackable: true, attack: 2, sustenance: 0, wieldable: true, throwable: false, craftingValue: 6, category: 'Material', material: 'Copper' },
    TIN_INGOT: { baseId: 'TIN_INGOT', name: 'Tin Ingot', description: 'A bar of refined tin.', emoji: '🔩', rarity: 'Common', value: 12, weight: 2.0, wearable: false, stackable: true, attack: 1, sustenance: 0, wieldable: true, throwable: false, craftingValue: 5, category: 'Material' },
    GOLD_BAR: { baseId: 'GOLD_BAR', name: 'Gold Bar', description: 'A bar of pure, shining gold.', emoji: '💰', rarity: 'Rare', value: 150, weight: 2.8, wearable: false, stackable: true, attack: 2, sustenance: 0, wieldable: true, throwable: false, craftingValue: 10, category: 'Material' },
    SILVER_INGOT: { baseId: 'SILVER_INGOT', name: 'Silver Ingot', description: 'A bar of refined silver.', emoji: '🔩', rarity: 'Uncommon', value: 75, weight: 2.5, wearable: false, stackable: true, attack: 1, sustenance: 0, wieldable: true, throwable: false, craftingValue: 9, category: 'Material' },
    LEAD_BAR: { baseId: 'LEAD_BAR', name: 'Lead Bar', description: 'A heavy bar of refined lead.', emoji: '🔩', rarity: 'Common', value: 9, weight: 3.5, wearable: false, stackable: true, attack: 2, sustenance: 0, wieldable: true, throwable: false, craftingValue: 4, category: 'Material' },

    // --- Religious/Holy Site Items ---
    INCENSE: { baseId: 'INCENSE', name: 'Incense Sticks', description: 'Sticks that release a fragrant smoke when burned.', emoji: '🌬️', rarity: 'Common', value: 5, weight: 0.1, wearable: false, stackable: true, attack: 0, sustenance: 0, wieldable: false, throwable: false, craftingValue: 2, category: 'Material' },
    CANDLES: { baseId: 'CANDLES', name: 'Beeswax Candles', description: 'Candles made from pure beeswax.', emoji: '🕯️', rarity: 'Uncommon', value: 8, weight: 0.2, wearable: false, stackable: true, attack: 0, sustenance: 0, wieldable: false, throwable: false, craftingValue: 3, category: 'Tool' },
    RELIGIOUS_TEXT: { baseId: 'RELIGIOUS_TEXT', name: 'Religious Text', description: 'A scroll or book containing sacred writings.', emoji: '📜', rarity: 'Rare', value: 50, weight: 0.5, wearable: false, stackable: false, attack: 0, sustenance: 0, wieldable: false, throwable: false, craftingValue: 1, category: 'Document' },
    BLESSED_ARTIFACT: { baseId: 'BLESSED_ARTIFACT', name: 'Blessed Artifact', description: 'A small object imbued with a spiritual blessing.', emoji: '✨', rarity: 'Rare', value: 75, weight: 0.2, wearable: false, stackable: false, attack: 0, sustenance: 0, wieldable: false, throwable: false, craftingValue: 0, category: 'Special' },


    // --- Junk/Basic ---
    STICK: { baseId: 'STICK', name: 'Sturdy Stick', description: 'A solid piece of wood. Could be useful.', emoji: '🪵', rarity: 'Junk', value: 0, weight: 0.5, wearable: false, stackable: false, attack: 1, sustenance: 0, wieldable: true, throwable: true, craftingValue: 1, category: 'Tool', material: 'Wood', equipmentSlot: 'main_hand' },
    SMOOTH_STONE: { baseId: 'SMOOTH_STONE', name: 'Smooth Stone', description: 'A pleasant, smooth stone, worn by water.', emoji: '🪨', rarity: 'Junk', value: 0, weight: 0.2, wearable: false, stackable: true, attack: 1, sustenance: 0, wieldable: false, throwable: true, craftingValue: 1, category: 'Material', material: 'Stone' },
    DRY_LEAVES: { baseId: 'DRY_LEAVES', name: 'Dry Leaves', description: 'A handful of dry, brittle leaves. Good for tinder.', emoji: '🍂', rarity: 'Junk', value: 0, weight: 0.1, wearable: false, stackable: true, attack: 0, sustenance: -1, wieldable: false, throwable: false, craftingValue: 1, category: 'Material' },
    POTTERY_SHARD: { baseId: 'POTTERY_SHARD', name: 'Pottery Shard', description: 'A broken piece of old pottery.', emoji: '🏺', rarity: 'Junk', value: 0, weight: 0.1, wearable: false, stackable: true, attack: 0, sustenance: 0, wieldable: false, throwable: true, craftingValue: 1, category: 'Material' },
    DAMP_LOG: { baseId: 'DAMP_LOG', name: 'Damp Log', description: 'A waterlogged piece of wood. Not very useful right now.', emoji: '🪵', rarity: 'Junk', value: 0, weight: 1.5, wearable: false, stackable: true, attack: 0, sustenance: 0, wieldable: false, throwable: false, craftingValue: 1, category: 'Material' },
    ROOT: { baseId: 'ROOT', name: 'Tough Root', description: 'A fibrous, gnarled root.', emoji: '🌱', rarity: 'Junk', value: 0, weight: 0.3, wearable: false, stackable: true, attack: 0, sustenance: 1, wieldable: false, throwable: false, craftingValue: 1, category: 'Material' },
    EARTHWORM: { baseId: 'EARTHWORM', name: 'Earthworm', description: 'A wriggling earthworm. Good for bait.', emoji: '🪱', rarity: 'Junk', value: 1, weight: 0.1, wearable: false, stackable: true, attack: 0, sustenance: 2, wieldable: false, throwable: false, craftingValue: 0, category: 'Food' },

    // --- Common Items ---
    WOODEN_BOWL: { baseId: 'WOODEN_BOWL', name: 'Wooden Bowl', description: 'A simple carved wooden bowl.', emoji: '🥣', rarity: 'Common', value: 1, weight: 0.3, wearable: false, stackable: false, attack: 0, sustenance: 0, wieldable: false, throwable: false, craftingValue: 2, category: 'Tool' },
    CLAY_LAMP: { baseId: 'CLAY_LAMP', name: 'Clay Lamp', description: 'A small clay oil lamp.', emoji: '🪔', rarity: 'Common', value: 2, weight: 0.4, wearable: false, stackable: false, attack: 1, sustenance: 0, wieldable: true, throwable: false, craftingValue: 1, category: 'Tool', equipmentSlot: 'main_hand' },
    WOOL_TUNIC: { baseId: 'WOOL_TUNIC', name: 'Wool Tunic', description: 'A roughspun but warm woolen tunic.', emoji: '👕', rarity: 'Common', value: 5, weight: 1.0, wearable: true, equipmentSlot: 'torso', stackable: false, attack: 0, sustenance: 0, wieldable: false, throwable: false, craftingValue: 5, category: 'Apparel', material: 'Wool' },
    BREAD: { baseId: 'BREAD', name: 'Loaf of Bread', description: 'A simple, hearty loaf of bread.', emoji: '🍞', rarity: 'Common', value: 2, weight: 0.5, wearable: false, stackable: true, attack: 0, sustenance: 20, wieldable: false, throwable: false, craftingValue: 1, category: 'Food' },
    QUILL: { baseId: 'QUILL', name: 'Goose Quill', description: 'A feather prepared for writing.', emoji: '✒️', rarity: 'Common', value: 1, weight: 0.1, wearable: false, stackable: false, attack: 1, sustenance: 0, wieldable: true, throwable: false, craftingValue: 1, category: 'Tool', equipmentSlot: 'main_hand' },
    INK_POT: { baseId: 'INK_POT', name: 'Pot of Ink', description: 'A small pot of black ink.', emoji: '⚫', rarity: 'Common', value: 3, weight: 0.2, wearable: false, stackable: false, attack: 1, sustenance: 0, wieldable: true, throwable: false, craftingValue: 2, category: 'Material', equipmentSlot: 'main_hand' },
    SIMPLE_ROBE: { baseId: 'SIMPLE_ROBE', name: 'Simple Robe', description: 'A plain, functional robe.', emoji: '🥻', rarity: 'Common', value: 4, weight: 1.2, wearable: true, equipmentSlot: 'torso', stackable: false, attack: 0, sustenance: 0, wieldable: false, throwable: false, craftingValue: 4, category: 'Apparel', material: 'Linen' },
    LEATHER_APRON: { baseId: 'LEATHER_APRON', name: 'Leather Apron', description: 'A tough leather apron, stained from work.', emoji: '🎽', rarity: 'Common', value: 6, weight: 1.5, wearable: true, equipmentSlot: 'torso', stackable: false, attack: 0, sustenance: 0, wieldable: false, throwable: false, craftingValue: 3, category: 'Apparel', material: 'Leather' },
    ROPE: { baseId: 'ROPE', name: 'Coil of Rope', description: 'A length of sturdy hemp rope.', emoji: ' रस्सी', rarity: 'Common', value: 3, weight: 1.0, wearable: false, stackable: false, attack: 0, sustenance: 0, wieldable: false, throwable: false, craftingValue: 2, category: 'Tool' },
    SIMPLE_RING: { baseId: 'SIMPLE_RING', name: 'Simple Ring', description: 'A simple ring, perhaps of sentimental value.', emoji: '💍', rarity: 'Common', value: 10, weight: 0.1, wearable: true, equipmentSlot: 'ring1', stackable: false, attack: 0, sustenance: 0, wieldable: false, throwable: false, craftingValue: 1, category: 'Apparel', material: 'Metal' },
    ROPE_NECKLACE: { baseId: 'ROPE_NECKLACE', name: 'Rope Necklace', description: 'A simple necklace made of tied rope.', emoji: '📿', rarity: 'Common', value: 1, weight: 0.1, wearable: true, equipmentSlot: 'amulet', stackable: false, attack: 0, sustenance: 0, wieldable: false, throwable: false, craftingValue: 1, category: 'Apparel', material: 'Hemp' },
    CLOTH_HOOD: { baseId: 'CLOTH_HOOD', name: 'Cloth Hood', description: 'A simple hood of roughspun cloth, offering basic protection from the elements.', emoji: '👤', rarity: 'Common', value: 2, weight: 0.3, wearable: true, equipmentSlot: 'head', stackable: false, attack: 0, sustenance: 0, wieldable: false, throwable: false, craftingValue: 2, category: 'Apparel', material: 'Cloth' },
    LEATHER_CAP: { baseId: 'LEATHER_CAP', name: 'Leather Cap', description: 'A sturdy cap made of boiled leather.', emoji: '🧢', rarity: 'Common', value: 4, weight: 0.5, wearable: true, equipmentSlot: 'head', stackable: false, attack: 0, sustenance: 0, wieldable: false, throwable: false, craftingValue: 3, category: 'Apparel', material: 'Leather' },
    LEATHER_BOOTS: { baseId: 'LEATHER_BOOTS', name: 'Leather Boots', description: 'Durable leather boots, well-worn.', emoji: '🥾', rarity: 'Common', value: 5, weight: 1.2, wearable: true, equipmentSlot: 'feet', stackable: false, attack: 0, sustenance: 0, wieldable: false, throwable: false, craftingValue: 4, category: 'Apparel', material: 'Leather' },
    SANDALS: { baseId: 'SANDALS', name: 'Sandals', description: 'Simple sandals with leather straps, suitable for warm climates.', emoji: '👡', rarity: 'Common', value: 2, weight: 0.4, wearable: true, equipmentSlot: 'feet', stackable: false, attack: 0, sustenance: 0, wieldable: false, throwable: false, craftingValue: 2, category: 'Apparel', material: 'Leather' },

    // --- Textual Items ---
    BOOK: { baseId: 'BOOK', name: 'Old Book', description: 'A leather-bound book with worn pages.', emoji: '📖', rarity: 'Uncommon', value: 10, weight: 1.5, wearable: false, stackable: false, attack: 1, sustenance: 0, wieldable: true, throwable: true, craftingValue: 3, category: 'Document', material: 'Paper', equipmentSlot: 'main_hand' },
    SCROLL: { baseId: 'SCROLL', name: 'Weathered Scroll', description: 'A rolled piece of parchment, its contents faded.', emoji: '📜', rarity: 'Uncommon', value: 8, weight: 0.2, wearable: false, stackable: true, attack: 0, sustenance: 0, wieldable: false, throwable: false, craftingValue: 2, category: 'Document', material: 'Paper' },
    LETTER: { baseId: 'LETTER', name: 'Sealed Letter', description: 'A letter sealed with wax, its contents a mystery.', emoji: '✉️', rarity: 'Uncommon', value: 2, weight: 0.1, wearable: false, stackable: true, attack: 0, sustenance: 0, wieldable: false, throwable: false, craftingValue: 1, category: 'Document', material: 'Paper' },
    PARCHMENT_ROLL: { baseId: 'PARCHMENT_ROLL', name: 'Blank Parchment Roll', description: 'A roll of fresh parchment, ready for writing.', emoji: '📜', rarity: 'Common', value: 3, weight: 0.1, wearable: false, stackable: true, attack: 0, sustenance: 0, wieldable: false, throwable: false, craftingValue: 2, category: 'Document', material: 'Paper' },

    // --- Historically Specific Items ---
    WHETSTONE: { baseId: 'WHETSTONE', name: 'Whetstone', description: 'A stone for sharpening blades and tools.', emoji: '🪨', rarity: 'Common', value: 2, weight: 0.5, wearable: false, stackable: false, attack: 1, sustenance: 0, wieldable: true, throwable: true, craftingValue: 2, category: 'Tool', material: 'Stone', equipmentSlot: 'main_hand' },
    HORSESHOE: { baseId: 'HORSESHOE', name: 'Iron Horseshoe', description: 'A U-shaped iron shoe for horses.', emoji: '🔧', rarity: 'Common', value: 8, weight: 1.0, wearable: false, stackable: true, attack: 2, sustenance: 0, wieldable: true, throwable: false, craftingValue: 4, category: 'Tool', material: 'Iron' },
    HAMMER: { baseId: 'HAMMER', name: 'Smith\'s Hammer', description: 'A heavy hammer for metalworking.', emoji: '🔨', rarity: 'Common', value: 12, weight: 2.0, wearable: false, stackable: false, attack: 3, sustenance: 0, wieldable: true, throwable: false, craftingValue: 5, category: 'Tool', material: 'Iron', equipmentSlot: 'main_hand' },
    BELLOWS: { baseId: 'BELLOWS', name: 'Leather Bellows', description: 'Bellows for stoking a forge fire.', emoji: '💨', rarity: 'Common', value: 15, weight: 3.0, wearable: false, stackable: false, attack: 0, sustenance: 0, wieldable: false, throwable: false, craftingValue: 6, category: 'Tool' },
    PURSE: { baseId: 'PURSE', name: 'Leather Purse', description: 'A small leather purse for holding coins.', emoji: '👛', rarity: 'Common', value: 5, weight: 0.2, wearable: true, stackable: false, attack: 0, sustenance: 0, wieldable: false, throwable: false, craftingValue: 2, category: 'Container', material: 'Leather', equipmentSlot: 'belt' },
    SCALE: { baseId: 'SCALE', name: 'Merchant\'s Scale', description: 'Small brass scales for weighing precious goods.', emoji: '⚖️', rarity: 'Uncommon', value: 20, weight: 1.5, wearable: false, stackable: false, attack: 1, sustenance: 0, wieldable: true, throwable: false, craftingValue: 8, category: 'Tool', material: 'Bronze', equipmentSlot: 'main_hand' },
    SPICE_POUCH: { baseId: 'SPICE_POUCH', name: 'Spice Pouch', description: 'A small pouch containing aromatic spices.', emoji: '🧂', rarity: 'Uncommon', value: 15, weight: 0.3, wearable: false, stackable: true, attack: 0, sustenance: 0, wieldable: false, throwable: false, craftingValue: 3, category: 'Material' },
    SILK_CLOTH: { baseId: 'SILK_CLOTH', name: 'Silk Cloth', description: 'Fine silk cloth from the East.', emoji: '🧵', rarity: 'Uncommon', value: 25, weight: 0.2, wearable: false, stackable: true, attack: 0, sustenance: 0, wieldable: false, throwable: false, craftingValue: 6, category: 'Material', material: 'Silk' },
    IVORY_TUSK: { baseId: 'IVORY_TUSK', name: 'Small Ivory Piece', description: 'A piece of carved ivory.', emoji: '🦷', rarity: 'Rare', value: 80, weight: 1.0, wearable: false, stackable: true, attack: 1, sustenance: 0, wieldable: false, throwable: false, craftingValue: 10, category: 'Material' },
    PRAYER_BEADS: { baseId: 'PRAYER_BEADS', name: 'Prayer Beads', description: 'A string of wooden prayer beads.', emoji: '📿', rarity: 'Common', value: 8, weight: 0.2, wearable: true, stackable: false, attack: 0, sustenance: 0, wieldable: false, throwable: false, craftingValue: 3, category: 'Apparel', material: 'Wood', equipmentSlot: 'amulet' },
    KATANA: { baseId: 'KATANA', name: 'Katana', description: 'A curved Japanese sword, masterfully crafted.', emoji: '⚔️', rarity: 'Rare', value: 100, weight: 1.2, wearable: false, stackable: false, attack: 8, sustenance: 0, wieldable: true, throwable: false, craftingValue: 15, category: 'Weapon', material: 'Steel', equipmentSlot: 'main_hand' },
    SCIMITAR: { baseId: 'SCIMITAR', name: 'Curved Scimitar', description: 'A curved blade favored in the Middle East.', emoji: '⚔️', rarity: 'Uncommon', value: 40, weight: 1.0, wearable: false, stackable: false, attack: 5, sustenance: 0, wieldable: true, throwable: false, craftingValue: 8, category: 'Weapon', material: 'Steel', equipmentSlot: 'main_hand' },

    // --- MEDIEVAL CRAFT TOOLS ---
    SMITHS_ANVIL: { baseId: 'SMITHS_ANVIL', name: 'Smith\'s Anvil', description: 'A heavy iron anvil with a distinctive horn for shaping metal.', emoji: '🔨', rarity: 'Uncommon', value: 80, weight: 50.0, wearable: false, stackable: false, attack: 0, sustenance: 0, wieldable: false, throwable: false, craftingValue: 15, category: 'Tool', material: 'Iron' },
    FORGE_HEARTH: { baseId: 'FORGE_HEARTH', name: 'Forge Hearth', description: 'A stone-lined hearth for heating metal to forging temperature.', emoji: '🔥', rarity: 'Rare', value: 200, weight: 100.0, wearable: false, stackable: false, attack: 0, sustenance: 0, wieldable: false, throwable: false, craftingValue: 25, category: 'Tool' },
    TONGS: { baseId: 'TONGS', name: 'Blacksmith\'s Tongs', description: 'Long-handled tongs for gripping hot metal during forging.', emoji: '🔧', rarity: 'Common', value: 15, weight: 2.0, wearable: false, stackable: false, attack: 2, sustenance: 0, wieldable: true, throwable: false, craftingValue: 5, category: 'Tool', material: 'Iron', equipmentSlot: 'main_hand' },
    STONE_CHISEL: { baseId: 'STONE_CHISEL', name: 'Stone Chisel', description: 'A sharp steel chisel for carving stone and shaping masonry.', emoji: '🔧', rarity: 'Common', value: 8, weight: 0.8, wearable: false, stackable: false, attack: 2, sustenance: 0, wieldable: true, throwable: false, craftingValue: 4, category: 'Tool', material: 'Steel', equipmentSlot: 'main_hand' },

    // --- AGRICULTURAL & FARMING ---
    IRON_PLOW: { baseId: 'IRON_PLOW', name: 'Iron Plow', description: 'A heavy plow with iron share for breaking tough soil.', emoji: '🚜', rarity: 'Uncommon', value: 60, weight: 25.0, wearable: false, stackable: false, attack: 0, sustenance: 0, wieldable: false, throwable: false, craftingValue: 12, category: 'Tool', material: 'Iron' },
    GRAIN_SCYTHE: { baseId: 'GRAIN_SCYTHE', name: 'Grain Scythe', description: 'A long curved blade mounted on a wooden handle for cutting grain.', emoji: '🌾', rarity: 'Common', value: 25, weight: 3.0, wearable: false, stackable: false, attack: 4, sustenance: 0, wieldable: true, throwable: false, craftingValue: 6, category: 'Tool', material: 'Steel', equipmentSlot: 'main_hand' },
    HARVEST_SICKLE: { baseId: 'HARVEST_SICKLE', name: 'Harvest Sickle', description: 'A curved blade for cutting grain stalks close to the ground.', emoji: '🌾', rarity: 'Common', value: 12, weight: 1.5, wearable: false, stackable: false, attack: 3, sustenance: 0, wieldable: true, throwable: false, craftingValue: 4, category: 'Tool', material: 'Iron', equipmentSlot: 'main_hand' },
    GRAIN_FLAIL: { baseId: 'GRAIN_FLAIL', name: 'Grain Flail', description: 'Two wooden sticks connected by leather for threshing grain.', emoji: '🌾', rarity: 'Common', value: 8, weight: 2.0, wearable: false, stackable: false, attack: 3, sustenance: 0, wieldable: true, throwable: false, craftingValue: 3, category: 'Tool', material: 'Wood', equipmentSlot: 'main_hand' },
    
    // --- TEXTILE & CLOTHING PRODUCTION ---
    SPINNING_WHEEL: { baseId: 'SPINNING_WHEEL', name: 'Spinning Wheel', description: 'A wooden wheel for spinning fiber into thread.', emoji: '🎡', rarity: 'Uncommon', value: 45, weight: 15.0, wearable: false, stackable: false, attack: 0, sustenance: 0, wieldable: false, throwable: false, craftingValue: 10, category: 'Tool', material: 'Wood' },
    WEAVING_LOOM: { baseId: 'WEAVING_LOOM', name: 'Weaving Loom', description: 'A wooden frame for weaving thread into cloth.', emoji: '🧵', rarity: 'Uncommon', value: 65, weight: 20.0, wearable: false, stackable: false, attack: 0, sustenance: 0, wieldable: false, throwable: false, craftingValue: 12, category: 'Tool', material: 'Wood' },
    WOOL_CARDERS: { baseId: 'WOOL_CARDERS', name: 'Wool Cards', description: 'Two brushes with wire teeth for combing wool fiber.', emoji: '🧽', rarity: 'Common', value: 10, weight: 1.0, wearable: false, stackable: false, attack: 1, sustenance: 0, wieldable: true, throwable: false, craftingValue: 3, category: 'Tool', material: 'Wood' },
    SPINDLE: { baseId: 'SPINDLE', name: 'Drop Spindle', description: 'A wooden shaft with a weighted whorl for spinning fiber.', emoji: '🪡', rarity: 'Common', value: 3, weight: 0.5, wearable: false, stackable: false, attack: 1, sustenance: 0, wieldable: true, throwable: true, craftingValue: 2, category: 'Tool', material: 'Wood', equipmentSlot: 'main_hand' },

    // --- FOOD PROCESSING ---
    GRAIN_QUERN: { baseId: 'GRAIN_QUERN', name: 'Hand Quern', description: 'Two circular stones for grinding grain into flour by hand.', emoji: '🗿', rarity: 'Common', value: 20, weight: 15.0, wearable: false, stackable: false, attack: 0, sustenance: 0, wieldable: false, throwable: false, craftingValue: 8, category: 'Tool', material: 'Stone' },
    BUTTER_CHURN: { baseId: 'BUTTER_CHURN', name: 'Butter Churn', description: 'A wooden barrel with plunger for churning cream into butter.', emoji: '🥛', rarity: 'Common', value: 18, weight: 8.0, wearable: false, stackable: false, attack: 0, sustenance: 0, wieldable: false, throwable: false, craftingValue: 6, category: 'Tool', material: 'Wood' },
    CHEESE_PRESS: { baseId: 'CHEESE_PRESS', name: 'Cheese Press', description: 'A wooden frame for pressing whey from fresh cheese curds.', emoji: '🧀', rarity: 'Uncommon', value: 30, weight: 12.0, wearable: false, stackable: false, attack: 0, sustenance: 0, wieldable: false, throwable: false, craftingValue: 8, category: 'Tool', material: 'Wood' },

    // --- HISTORICAL FOODS & INGREDIENTS ---
    RYE: { baseId: 'RYE', name: 'Rye Grain', description: 'Dark grain that grows in poor soil, used for dense bread.', emoji: '🌾', rarity: 'Common', value: 1, weight: 0.4, wearable: false, stackable: true, attack: 0, sustenance: 10, wieldable: false, throwable: false, craftingValue: 1, category: 'Food' },
    MILLET: { baseId: 'MILLET', name: 'Millet Seeds', description: 'Small round seeds cultivated in dry regions.', emoji: '🌾', rarity: 'Common', value: 2, weight: 0.3, wearable: false, stackable: true, attack: 0, sustenance: 7, wieldable: false, throwable: false, craftingValue: 1, category: 'Food' },
    PEAS: { baseId: 'PEAS', name: 'Dried Peas', description: 'Protein-rich legumes, often made into porridge.', emoji: '🟢', rarity: 'Common', value: 2, weight: 0.4, wearable: false, stackable: true, attack: 0, sustenance: 12, wieldable: false, throwable: false, craftingValue: 1, category: 'Food' },
    LENTILS: { baseId: 'LENTILS', name: 'Lentils', description: 'Small brown legumes, a staple protein for the poor.', emoji: '🟤', rarity: 'Common', value: 3, weight: 0.4, wearable: false, stackable: true, attack: 0, sustenance: 14, wieldable: false, throwable: false, craftingValue: 1, category: 'Food' },
    SALT_PORK: { baseId: 'SALT_PORK', name: 'Salt Pork', description: 'Pork preserved in salt brine, essential for long voyages.', emoji: '🥓', rarity: 'Common', value: 8, weight: 2.0, wearable: false, stackable: true, attack: 0, sustenance: 25, wieldable: false, throwable: false, craftingValue: 2, category: 'Food' },
    SMOKED_FISH: { baseId: 'SMOKED_FISH', name: 'Smoked Fish', description: 'Fish preserved by smoking over a wood fire.', emoji: '🐟', rarity: 'Common', value: 6, weight: 1.5, wearable: false, stackable: true, attack: 0, sustenance: 20, wieldable: false, throwable: false, craftingValue: 2, category: 'Food' },
    
    // --- MILL PRODUCTS ---
    FLOUR: { baseId: 'FLOUR', name: 'Wheat Flour', description: 'Fine ground wheat, ready for baking.', emoji: '🌾', rarity: 'Common', value: 3, weight: 0.5, wearable: false, stackable: true, attack: 0, sustenance: 15, wieldable: false, throwable: false, craftingValue: 2, category: 'Food' },
    BARLEY_FLOUR: { baseId: 'BARLEY_FLOUR', name: 'Barley Flour', description: 'Coarse flour made from barley.', emoji: '🌾', rarity: 'Common', value: 2, weight: 0.5, wearable: false, stackable: true, attack: 0, sustenance: 12, wieldable: false, throwable: false, craftingValue: 2, category: 'Food' },
    RYE_FLOUR: { baseId: 'RYE_FLOUR', name: 'Rye Flour', description: 'Dark flour for hearty breads.', emoji: '🌾', rarity: 'Common', value: 2, weight: 0.5, wearable: false, stackable: true, attack: 0, sustenance: 13, wieldable: false, throwable: false, craftingValue: 2, category: 'Food' },
    MILLET_FLOUR: { baseId: 'MILLET_FLOUR', name: 'Millet Flour', description: 'Fine flour from millet grains.', emoji: '🌾', rarity: 'Common', value: 2, weight: 0.4, wearable: false, stackable: true, attack: 0, sustenance: 10, wieldable: false, throwable: false, craftingValue: 1, category: 'Food' },
    CORNMEAL: { baseId: 'CORNMEAL', name: 'Cornmeal', description: 'Ground corn for porridge and bread.', emoji: '🌽', rarity: 'Common', value: 3, weight: 0.5, wearable: false, stackable: true, attack: 0, sustenance: 14, wieldable: false, throwable: false, craftingValue: 2, category: 'Food' },
    RICE_FLOUR: { baseId: 'RICE_FLOUR', name: 'Rice Flour', description: 'Fine white flour from rice.', emoji: '🍚', rarity: 'Common', value: 4, weight: 0.4, wearable: false, stackable: true, attack: 0, sustenance: 12, wieldable: false, throwable: false, craftingValue: 2, category: 'Food' },
    OLIVE_OIL: { baseId: 'OLIVE_OIL', name: 'Olive Oil', description: 'Pressed oil from olives.', emoji: '🫒', rarity: 'Common', value: 8, weight: 0.8, wearable: false, stackable: true, attack: 0, sustenance: 5, wieldable: false, throwable: false, craftingValue: 3, category: 'Food' },
    RAW_SUGAR: { baseId: 'RAW_SUGAR', name: 'Raw Sugar', description: 'Crystallized cane sugar.', emoji: '🍬', rarity: 'Uncommon', value: 10, weight: 0.3, wearable: false, stackable: true, attack: 0, sustenance: 8, wieldable: false, throwable: false, craftingValue: 4, category: 'Food' },
    BEET_SUGAR: { baseId: 'BEET_SUGAR', name: 'Beet Sugar', description: 'Sugar extracted from beets.', emoji: '🍬', rarity: 'Uncommon', value: 8, weight: 0.3, wearable: false, stackable: true, attack: 0, sustenance: 8, wieldable: false, throwable: false, craftingValue: 3, category: 'Food' },
    COCOA_POWDER: { baseId: 'COCOA_POWDER', name: 'Cocoa Powder', description: 'Ground cocoa for chocolate.', emoji: '🍫', rarity: 'Uncommon', value: 15, weight: 0.3, wearable: false, stackable: true, attack: 0, sustenance: 5, wieldable: false, throwable: false, craftingValue: 5, category: 'Food' },
    GROUND_SPICES: { baseId: 'GROUND_SPICES', name: 'Ground Spices', description: 'Mixed ground spices.', emoji: '🌶️', rarity: 'Uncommon', value: 12, weight: 0.2, wearable: false, stackable: true, attack: 0, sustenance: 1, wieldable: false, throwable: false, craftingValue: 4, category: 'Food' },
    GROUND_COFFEE: { baseId: 'GROUND_COFFEE', name: 'Ground Coffee', description: 'Freshly ground coffee beans.', emoji: '☕', rarity: 'Common', value: 8, weight: 0.3, wearable: false, stackable: true, attack: 0, sustenance: 2, wieldable: false, throwable: false, craftingValue: 3, category: 'Food' },
    SOY_FLOUR: { baseId: 'SOY_FLOUR', name: 'Soy Flour', description: 'Protein-rich flour from soybeans.', emoji: '🌾', rarity: 'Common', value: 5, weight: 0.4, wearable: false, stackable: true, attack: 0, sustenance: 16, wieldable: false, throwable: false, craftingValue: 3, category: 'Food' },
    QUINOA_FLOUR: { baseId: 'QUINOA_FLOUR', name: 'Quinoa Flour', description: 'Nutritious flour from quinoa.', emoji: '🌾', rarity: 'Uncommon', value: 6, weight: 0.4, wearable: false, stackable: true, attack: 0, sustenance: 14, wieldable: false, throwable: false, craftingValue: 3, category: 'Food' },
    NUT_FLOUR: { baseId: 'NUT_FLOUR', name: 'Nut Flour', description: 'Finely ground nuts.', emoji: '🥜', rarity: 'Uncommon', value: 10, weight: 0.3, wearable: false, stackable: true, attack: 0, sustenance: 18, wieldable: false, throwable: false, craftingValue: 4, category: 'Food' },
    POLISHED_RICE: { baseId: 'POLISHED_RICE', name: 'Polished Rice', description: 'White rice with husks removed.', emoji: '🍚', rarity: 'Common', value: 5, weight: 0.5, wearable: false, stackable: true, attack: 0, sustenance: 20, wieldable: false, throwable: false, craftingValue: 2, category: 'Food' },
    SEA_SALT: { baseId: 'SEA_SALT', name: 'Sea Salt', description: 'Salt extracted from seawater.', emoji: '🧂', rarity: 'Common', value: 4, weight: 0.2, wearable: false, stackable: true, attack: 0, sustenance: 0, wieldable: false, throwable: false, craftingValue: 2, category: 'Material' },

    // --- Combat Consumables ---
    HEALING_POTION: { baseId: 'HEALING_POTION', name: 'Healing Potion', description: 'A simple potion that restores a small amount of health.', emoji: '🧪', rarity: 'Uncommon', value: 25, weight: 0.5, wearable: false, stackable: true, attack: 0, sustenance: 25, wieldable: false, throwable: false, craftingValue: 5, category: 'Consumable' },
    SMALL_BOMB: { baseId: 'SMALL_BOMB', name: 'Small Bomb', description: 'A small, explosive device. Deals damage to the opponent.', emoji: '💣', rarity: 'Rare', value: 40, weight: 1.0, wearable: false, stackable: true, attack: 0, sustenance: 0, wieldable: false, throwable: true, craftingValue: 7, category: 'Consumable', damage: 20 },
    REFRESHING_HERB: { baseId: 'REFRESHING_HERB', name: 'Refreshing Herb', description: 'A fragrant herb that restores some fatigue.', emoji: '🌿', rarity: 'Uncommon', value: 15, weight: 0.1, wearable: false, stackable: true, attack: 0, sustenance: 5, fatigueEffect: 10, wieldable: false, throwable: false, craftingValue: 4, category: 'Consumable' },
    SCROLL_OF_KNOWLEDGE: { baseId: 'SCROLL_OF_KNOWLEDGE', name: 'Scroll of Knowledge', description: 'A magical scroll that imparts a small amount of worldly experience.', emoji: '📜', rarity: 'Rare', value: 100, weight: 0.1, wearable: false, stackable: false, attack: 0, sustenance: 0, xpEffect: 15, wieldable: false, throwable: false, craftingValue: 8, category: 'Consumable' },

    // --- Common Forage ---
    WILD_BERRIES: { baseId: 'WILD_BERRIES', name: 'Wild Berries', description: 'A handful of wild, edible berries.', emoji: '🍓', rarity: 'Common', value: 1, weight: 0.2, wearable: false, stackable: true, attack: 0, sustenance: 5, fatigueEffect: 1, wieldable: false, throwable: false, craftingValue: 1, category: 'Food' },
    MUSHROOM: { baseId: 'MUSHROOM', name: 'Edible Mushroom', description: 'A common, earthy mushroom.', emoji: '🍄', rarity: 'Common', value: 1, weight: 0.1, wearable: false, stackable: true, attack: 0, sustenance: 2, wieldable: false, throwable: false, craftingValue: 1, category: 'Food' },
    VINE: { baseId: 'VINE', name: 'Tough Vine', description: 'A long, fibrous vine. Could be used to make rope.', emoji: '🌿', rarity: 'Common', value: 1, weight: 0.4, wearable: false, stackable: true, attack: 0, sustenance: 0, wieldable: false, throwable: false, craftingValue: 2, category: 'Material' },
    BIRDS_NEST: { baseId: 'BIRDS_NEST', name: 'Bird\'s Nest', description: 'A small, abandoned bird\'s nest made of twigs and mud.', emoji: '🐦', rarity: 'Uncommon', value: 1, weight: 0.2, wearable: false, stackable: false, attack: 0, sustenance: 0, wieldable: false, throwable: false, craftingValue: 1, category: 'Material' },
    PINE_CONE: { baseId: 'PINE_CONE', name: 'Pine Cone', description: 'A woody cone from a pine tree, good for tinder.', emoji: '🌲', rarity: 'Common', value: 0, weight: 0.1, wearable: false, stackable: true, attack: 0, sustenance: 0, wieldable: false, throwable: false, craftingValue: 1, category: 'Material' },
    
    // New Forage Items
    ACORNS: { baseId: 'ACORNS', name: 'Handful of Acorns', description: 'Acorns from an oak tree. Bitter, but can be made edible.', emoji: '🌰', rarity: 'Common', value: 1, weight: 0.3, wearable: false, stackable: true, attack: 0, sustenance: 1, wieldable: false, throwable: true, craftingValue: 1, category: 'Food' },
    TREE_BARK: { baseId: 'TREE_BARK', name: 'Tree Bark', description: 'A strip of tree bark. Can be used for tinder or cordage.', emoji: '🪵', rarity: 'Junk', value: 0, weight: 0.2, wearable: false, stackable: true, attack: 0, sustenance: 0, wieldable: false, throwable: false, craftingValue: 1, category: 'Material' },
    PINE_RESIN: { baseId: 'PINE_RESIN', name: 'Pine Resin', description: 'A sticky, fragrant resin from a pine tree. Useful for waterproofing or as an adhesive.', emoji: '💧', rarity: 'Uncommon', value: 4, weight: 0.1, wearable: false, stackable: true, attack: 0, sustenance: 0, wieldable: false, throwable: false, craftingValue: 3, category: 'Material' },
    HERB_BUNDLE: { baseId: 'HERB_BUNDLE', name: 'Herb Bundle', description: 'A bundle of common, fragrant herbs.', emoji: '🌿', rarity: 'Common', value: 2, weight: 0.1, wearable: false, stackable: true, attack: 0, sustenance: 0, fatigueEffect: 2, wieldable: false, throwable: false, craftingValue: 2, category: 'Food' },
    MEDICINAL_HERBS: { baseId: 'MEDICINAL_HERBS', name: 'Medicinal Herbs', description: 'A collection of rare herbs known for their healing properties.', emoji: '🌿', rarity: 'Rare', value: 10, weight: 0.1, wearable: false, stackable: true, attack: 0, sustenance: 2, fatigueEffect: 5, wieldable: false, throwable: false, craftingValue: 5, category: 'Material' },
    CACTUS_FRUIT: { baseId: 'CACTUS_FRUIT', name: 'Cactus Fruit', description: 'A juicy, sweet fruit from a cactus. Provides both food and water.', emoji: '🌵', rarity: 'Uncommon', value: 3, weight: 0.3, wearable: false, stackable: true, attack: 0, sustenance: 8, fatigueEffect: 3, wieldable: false, throwable: false, craftingValue: 1, category: 'Food' },
    STRANGE_FRUIT: { baseId: 'STRANGE_FRUIT', name: 'Strange Fruit', description: 'A bizarre, brightly colored fruit. You\'re not sure if it\'s edible.', emoji: '🥭', rarity: 'Rare', value: 7, weight: 0.4, wearable: false, stackable: true, attack: 0, sustenance: 10, fatigueEffect: -2, xpEffect: 5, wieldable: false, throwable: true, craftingValue: 3, category: 'Food' },
    
    // --- Rare/Ultra-Rare Forage ---
    GLOWING_MOSS: { baseId: 'GLOWING_MOSS', name: 'Glowing Moss', description: 'Moss that emits a faint, eerie light.', emoji: '✨', rarity: 'Ultra-rare', value: 20, weight: 0.1, wearable: false, stackable: true, attack: 0, sustenance: 0, wieldable: false, throwable: false, craftingValue: 7, category: 'Material' },
    OWL_FEATHER: { baseId: 'OWL_FEATHER', name: 'Owl Feather', description: 'A large, silent feather from an owl. Valued by fletchers and mystics.', emoji: '🪶', rarity: 'Ultra-rare', value: 15, weight: 0.1, wearable: false, stackable: true, attack: 0, sustenance: 0, wieldable: false, throwable: false, craftingValue: 6, category: 'Material' },
    
    // --- Animal Products ---
    BEEF: { baseId: 'BEEF', name: 'Beef', description: 'A hearty slab of cow meat.', emoji: '🥩', rarity: 'Common', value: 7, weight: 2.0, wearable: false, stackable: false, attack: 0, sustenance: 35, fatigueEffect: 5, wieldable: false, throwable: false, craftingValue: 1, category: 'Food' },
    COW_HIDE: { baseId: 'COW_HIDE', name: 'Cow Hide', description: 'The unprocessed hide of a cow.', emoji: '🐄', rarity: 'Common', value: 3, weight: 4.0, wearable: true, stackable: false, attack: 0, sustenance: 0, wieldable: false, throwable: false, craftingValue: 4, category: 'Material', material: 'Hide' },
    VENISON: { baseId: 'VENISON', name: 'Venison', description: 'A hearty slab of deer meat.', emoji: '🥩', rarity: 'Common', value: 8, weight: 2.0, wearable: false, stackable: false, attack: 0, sustenance: 40, fatigueEffect: 5, wieldable: false, throwable: false, craftingValue: 2, category: 'Food' },
    DEER_HIDE: { baseId: 'DEER_HIDE', name: 'Deer Hide', description: 'The unprocessed hide of a deer.', emoji: '🦌', rarity: 'Common', value: 4, weight: 3.0, wearable: true, stackable: false, attack: 0, sustenance: 0, wieldable: false, throwable: false, craftingValue: 6, category: 'Material', material: 'Hide' },
    WOLF_PELT: { baseId: 'WOLF_PELT', name: 'Wolf Pelt', description: 'The thick, grey pelt of a wolf.', emoji: '🐺', rarity: 'Uncommon', value: 15, weight: 2.5, wearable: true, stackable: false, attack: 0, sustenance: 0, wieldable: false, throwable: false, craftingValue: 8, category: 'Material', material: 'Pelt' },
    MEAT: { baseId: 'MEAT', name: 'Chunk of Meat', description: 'A hunk of mystery meat.', emoji: '🍖', rarity: 'Common', value: 5, weight: 2.0, wearable: false, stackable: false, attack: 0, sustenance: 30, fatigueEffect: 2, wieldable: false, throwable: false, craftingValue: 1, category: 'Food' },
    BEAR_HIDE: { baseId: 'BEAR_HIDE', name: 'Bear Hide', description: 'The massive, thick hide of a bear.', emoji: '🐻', rarity: 'Rare', value: 30, weight: 8.0, wearable: true, stackable: false, attack: 0, sustenance: 0, wieldable: false, throwable: false, craftingValue: 9, category: 'Material', material: 'Hide' },
    BEAR_CLAW: { baseId: 'BEAR_CLAW', name: 'Bear Claw', description: 'A large, sharp claw from a bear. Often used in jewelry or as a trophy.', emoji: '🐻', rarity: 'Uncommon', value: 12, weight: 0.2, wearable: false, stackable: true, attack: 2, sustenance: 0, wieldable: true, throwable: false, craftingValue: 4, category: 'Material', equipmentSlot: 'main_hand' },
    FOX_FUR: { baseId: 'FOX_FUR', name: 'Fox Fur', description: 'The soft, reddish fur of a fox.', emoji: '🦊', rarity: 'Uncommon', value: 18, weight: 1.0, wearable: true, stackable: false, attack: 0, sustenance: 0, wieldable: false, throwable: false, craftingValue: 7, category: 'Material', material: 'Fur' },
    TOUGH_HIDE: { baseId: 'TOUGH_HIDE', name: 'Tough Hide', description: 'A thick, durable hide from a hardy beast.', emoji: '🐗', rarity: 'Common', value: 6, weight: 4.0, wearable: true, stackable: false, attack: 0, sustenance: 0, wieldable: false, throwable: false, craftingValue: 5, category: 'Material', material: 'Hide' },
    BOAR_TUSK: { baseId: 'BOAR_TUSK', name: 'Boar Tusk', description: 'A sharp, curved tusk from a wild boar.', emoji: '🐗', rarity: 'Uncommon', value: 8, weight: 0.5, wearable: false, stackable: true, attack: 2, sustenance: 0, wieldable: true, throwable: false, craftingValue: 4, category: 'Material', equipmentSlot: 'main_hand' },
    EAGLE_FEATHER: { baseId: 'EAGLE_FEATHER', name: 'Eagle Feather', description: 'A majestic feather from a great eagle. Highly prized.', emoji: '🦅', rarity: 'Rare', value: 25, weight: 0.1, wearable: false, stackable: true, attack: 0, sustenance: 0, wieldable: false, throwable: false, craftingValue: 8, category: 'Material' },
    MAGIC_FEATHER: { baseId: 'MAGIC_FEATHER', name: 'Magic Feather', description: 'A feather that hums with a faint, magical energy.', emoji: '🪶', rarity: 'Ultra-rare', value: 50, weight: 0.1, wearable: false, stackable: true, attack: 0, sustenance: 0, wieldable: false, throwable: false, craftingValue: 10, category: 'Material' },
    SNAKE_SKIN: { baseId: 'SNAKE_SKIN', name: 'Snake Skin', description: 'The shed skin of a snake.', emoji: '🐍', rarity: 'Uncommon', value: 9, weight: 0.2, wearable: true, stackable: false, attack: 0, sustenance: 0, wieldable: false, throwable: false, craftingValue: 5, category: 'Material', material: 'Skin' },
    VENOM: { baseId: 'VENOM', name: 'Vial of Venom', description: 'A small vial of potent venom.', emoji: '🧪', rarity: 'Rare', value: 35, weight: 0.1, wearable: false, stackable: true, attack: 0, sustenance: 0, wieldable: false, throwable: false, craftingValue: 9, category: 'Material' },
    FISH_MEAT: { baseId: 'FISH_MEAT', name: 'Fish Meat', description: 'A flaky, edible fish.', emoji: '🐟', rarity: 'Common', value: 3, weight: 0.5, wearable: false, stackable: false, attack: 0, sustenance: 10, fatigueEffect: 2, wieldable: false, throwable: false, craftingValue: 1, category: 'Food' },
    BIOLUMINESCENT_GOOP: { baseId: 'BIOLUMINESCENT_GOOP', name: 'Bioluminescent Goop', description: 'A jar of glowing slime from a jellyfish.', emoji: '🧪', rarity: 'Uncommon', value: 8, weight: 0.5, wearable: false, stackable: true, attack: 0, sustenance: 0, wieldable: false, throwable: true, craftingValue: 5, category: 'Material' },
    WHALE_BLUBBER: { baseId: 'WHALE_BLUBBER', name: 'Whale Blubber', description: 'A large piece of whale blubber, excellent for lamp oil.', emoji: '🐋', rarity: 'Rare', value: 50, weight: 10.0, wearable: false, stackable: false, attack: 0, sustenance: 0, wieldable: false, throwable: false, craftingValue: 6, category: 'Material' },
    AMBERGRIS: { baseId: 'AMBERGRIS', name: 'Ambergris', description: 'A waxy substance from a whale, highly prized in perfumery.', emoji: '🌟', rarity: 'Ultra-rare', value: 200, weight: 1.0, wearable: false, stackable: false, attack: 0, sustenance: 0, wieldable: false, throwable: false, craftingValue: 10, category: 'Special' },

    // --- New Crop Items ---
    WHEAT: { baseId: 'WHEAT', name: 'Sheaf of Wheat', description: 'Grain, ready for milling.', emoji: '🌾', rarity: 'Common', value: 2, weight: 1.0, wearable: false, stackable: true, attack: 0, sustenance: 1, wieldable: false, throwable: false, craftingValue: 2, category: 'Material' },
    BARLEY: { baseId: 'BARLEY', name: 'Bag of Barley', description: 'Hardy grain used for bread and ale.', emoji: '🌾', rarity: 'Common', value: 2, weight: 1.0, wearable: false, stackable: true, attack: 0, sustenance: 1, wieldable: false, throwable: false, craftingValue: 2, category: 'Material' },
    CORN: { baseId: 'CORN', name: 'Ear of Corn', description: 'An ear of sweet, golden corn.', emoji: '🌽', rarity: 'Common', value: 3, weight: 0.8, wearable: false, stackable: true, attack: 0, sustenance: 4, wieldable: false, throwable: false, craftingValue: 2, category: 'Food', culturalAvailability: ['SOUTH_AMERICAN', 'NORTH_AMERICAN_PRE_COLUMBIAN'], eraAvailability: { startYear: -8000, endYear: 1492 } },
    RICE: { baseId: 'RICE', name: 'Bag of Rice', description: 'A small bag of uncooked rice.', emoji: '🍚', rarity: 'Common', value: 2, weight: 1.2, wearable: false, stackable: true, attack: 0, sustenance: 1, wieldable: false, throwable: false, craftingValue: 1, category: 'Material' },
    POTATO: { baseId: 'POTATO', name: 'Potato', description: 'A humble but filling potato.', emoji: '🥔', rarity: 'Common', value: 1, weight: 0.3, wearable: false, stackable: true, attack: 0, sustenance: 15, wieldable: false, throwable: true, craftingValue: 1, category: 'Food', culturalAvailability: ['SOUTH_AMERICAN'], eraAvailability: { startYear: -8000, endYear: 1536 } },
    YAM: { baseId: 'YAM', name: 'Yam', description: 'A starchy tuber, a staple in tropical regions.', emoji: '🍠', rarity: 'Common', value: 2, weight: 0.9, wearable: false, stackable: true, attack: 0, sustenance: 12, wieldable: false, throwable: false, craftingValue: 1, category: 'Food' },
    OLIVES: { baseId: 'OLIVES', name: 'Jar of Olives', description: 'Cured olives, ready for pressing into oil.', emoji: '🫒', rarity: 'Common', value: 5, weight: 0.7, wearable: false, stackable: true, attack: 0, sustenance: 2, wieldable: false, throwable: false, craftingValue: 4, category: 'Material' },
    GRAPES: { baseId: 'GRAPES', name: 'Bunch of Grapes', description: 'Sweet grapes, perfect for eating or making wine.', emoji: '🍇', rarity: 'Common', value: 4, weight: 0.5, wearable: false, stackable: true, attack: 0, sustenance: 5, wieldable: false, throwable: false, craftingValue: 3, category: 'Food' },
    COTTON: { baseId: 'COTTON', name: 'Bale of Cotton', description: 'Raw cotton, ready for spinning into thread.', emoji: '☁️', rarity: 'Common', value: 4, weight: 2.0, wearable: false, stackable: true, attack: 0, sustenance: 0, wieldable: false, throwable: false, craftingValue: 5, category: 'Material' },
    SUGAR_CANE: { baseId: 'SUGAR_CANE', name: 'Stalk of Sugar Cane', description: 'A sweet stalk that can be processed into sugar.', emoji: '🎋', rarity: 'Common', value: 3, weight: 1.5, wearable: false, stackable: true, attack: 0, sustenance: 2, wieldable: false, throwable: false, craftingValue: 3, category: 'Material' },

    // --- Terrain-Specific Items ---
    // Salt flat items
    SALT: { baseId: 'SALT', name: 'Salt', description: 'Pure salt crystals, essential for preserving food.', emoji: '🧂', rarity: 'Common', value: 3, weight: 0.2, wearable: false, stackable: true, attack: 0, sustenance: 0, wieldable: false, throwable: false, craftingValue: 2, category: 'Material' },
    MINERAL_CRYSTALS: { baseId: 'MINERAL_CRYSTALS', name: 'Mineral Crystals', description: 'Colorful crystalline formations from dried lake beds.', emoji: '💎', rarity: 'Uncommon', value: 15, weight: 0.5, wearable: false, stackable: true, attack: 0, sustenance: 0, wieldable: false, throwable: false, craftingValue: 5, category: 'Material' },
    LITHIUM_TRACE: { baseId: 'LITHIUM_TRACE', name: 'Lithium Salts', description: 'Valuable lithium-bearing salts with a distinctive blue tinge.', emoji: '🔷', rarity: 'Rare', value: 50, weight: 0.3, wearable: false, stackable: true, attack: 0, sustenance: 0, wieldable: false, throwable: false, craftingValue: 8, category: 'Material' },
    
    // Beach/coastal items
    SEA_GLASS: { baseId: 'SEA_GLASS', name: 'Sea Glass', description: 'Smooth, frosted glass polished by waves.', emoji: '🔮', rarity: 'Common', value: 5, weight: 0.1, wearable: false, stackable: true, attack: 0, sustenance: 0, wieldable: false, throwable: false, craftingValue: 2, category: 'Material' },
    SEASHELL: { baseId: 'SEASHELL', name: 'Seashell', description: 'A beautiful spiral shell from the shore.', emoji: '🐚', rarity: 'Common', value: 2, weight: 0.1, wearable: false, stackable: true, attack: 0, sustenance: 0, wieldable: false, throwable: false, craftingValue: 1, category: 'Material' },
    CRAB: { baseId: 'CRAB', name: 'Crab', description: 'A fresh crab, excellent eating.', emoji: '🦀', rarity: 'Common', value: 8, weight: 0.5, wearable: false, stackable: true, attack: 0, sustenance: 10, wieldable: false, throwable: false, craftingValue: 0, category: 'Food' },
    CLAM: { baseId: 'CLAM', name: 'Clam', description: 'A shellfish that can be eaten raw or cooked.', emoji: '🦪', rarity: 'Common', value: 6, weight: 0.3, wearable: false, stackable: true, attack: 0, sustenance: 6, wieldable: false, throwable: false, craftingValue: 0, category: 'Food' },
    DRIFTWOOD: { baseId: 'DRIFTWOOD', name: 'Driftwood', description: 'Sun-bleached wood from the sea.', emoji: '🪵', rarity: 'Common', value: 1, weight: 1.0, wearable: false, stackable: true, attack: 1, sustenance: 0, wieldable: true, throwable: false, craftingValue: 2, category: 'Material' },
    
    // Desert items
    FOSSIL: { baseId: 'FOSSIL', name: 'Ancient Fossil', description: 'Preserved remains of prehistoric life.', emoji: '🦴', rarity: 'Uncommon', value: 25, weight: 1.0, wearable: false, stackable: true, attack: 0, sustenance: 0, wieldable: false, throwable: false, craftingValue: 5, category: 'Material' },
    SCORPION: { baseId: 'SCORPION', name: 'Desert Scorpion', description: 'A venomous arachnid. Handle with care!', emoji: '🦂', rarity: 'Uncommon', value: 10, weight: 0.1, wearable: false, stackable: true, attack: 2, sustenance: 3, wieldable: false, throwable: true, craftingValue: 3, category: 'Food' },
    FLINT: { baseId: 'FLINT', name: 'Flint', description: 'Sharp stone excellent for tool making.', emoji: '🪨', rarity: 'Common', value: 4, weight: 0.5, wearable: false, stackable: true, attack: 2, sustenance: 0, wieldable: true, throwable: true, craftingValue: 4, category: 'Material' },
    
    // Wetland items
    PEAT: { baseId: 'PEAT', name: 'Peat', description: 'Compressed plant matter, burns well when dried.', emoji: '🟫', rarity: 'Common', value: 3, weight: 0.5, wearable: false, stackable: true, attack: 0, sustenance: 0, wieldable: false, throwable: false, craftingValue: 2, category: 'Material' },
    BOG_IRON: { baseId: 'BOG_IRON', name: 'Bog Iron', description: 'Iron deposits formed in swamps, can be smelted.', emoji: '🪨', rarity: 'Uncommon', value: 15, weight: 2.0, wearable: false, stackable: true, attack: 1, sustenance: 0, wieldable: false, throwable: false, craftingValue: 6, category: 'Material' },
    LEECH: { baseId: 'LEECH', name: 'Medicinal Leech', description: 'Used in traditional medicine for bloodletting.', emoji: '🩸', rarity: 'Common', value: 8, weight: 0.05, wearable: false, stackable: true, attack: 0, sustenance: 0, wieldable: false, throwable: false, craftingValue: 3, category: 'Material' },
    
    // Tundra items
    FROZEN_BERRIES: { baseId: 'FROZEN_BERRIES', name: 'Frozen Cloudberries', description: 'Berries preserved by permafrost, still edible.', emoji: '🫐', rarity: 'Common', value: 6, weight: 0.2, wearable: false, stackable: true, attack: 0, sustenance: 5, wieldable: false, throwable: false, craftingValue: 0, category: 'Food' },
    MAMMOTH_TUSK_FRAGMENT: { baseId: 'MAMMOTH_TUSK_FRAGMENT', name: 'Mammoth Ivory Fragment', description: 'Ancient ivory from extinct mammoths.', emoji: '🦣', rarity: 'Rare', value: 100, weight: 2.0, wearable: false, stackable: true, attack: 2, sustenance: 0, wieldable: true, throwable: false, craftingValue: 10, category: 'Material' },
    ICE_CRYSTAL: { baseId: 'ICE_CRYSTAL', name: 'Eternal Ice Crystal', description: 'Ice that never melts, radiates cold.', emoji: '❄️', rarity: 'Rare', value: 75, weight: 0.5, wearable: false, stackable: true, attack: 0, sustenance: 0, wieldable: false, throwable: false, craftingValue: 8, category: 'Special' },
    AMBER: { baseId: 'AMBER', name: 'Amber', description: 'Fossilized tree resin, sometimes with insects inside.', emoji: '🟠', rarity: 'Uncommon', value: 30, weight: 0.2, wearable: false, stackable: true, attack: 0, sustenance: 0, wieldable: false, throwable: false, craftingValue: 6, category: 'Material' },
    
    // Reef items
    CORAL_FRAGMENT: { baseId: 'CORAL_FRAGMENT', name: 'Coral Fragment', description: 'Colorful piece of coral, decorative.', emoji: '🪸', rarity: 'Common', value: 8, weight: 0.3, wearable: false, stackable: true, attack: 0, sustenance: 0, wieldable: false, throwable: false, craftingValue: 3, category: 'Material' },
    SEA_URCHIN: { baseId: 'SEA_URCHIN', name: 'Sea Urchin', description: 'Spiny sea creature, a delicacy in some cultures.', emoji: '🦔', rarity: 'Common', value: 12, weight: 0.2, wearable: false, stackable: true, attack: 1, sustenance: 8, wieldable: false, throwable: true, craftingValue: 0, category: 'Food' },
    SEAWEED: { baseId: 'SEAWEED', name: 'Seaweed', description: 'Nutritious sea vegetable.', emoji: '🌿', rarity: 'Common', value: 3, weight: 0.2, wearable: false, stackable: true, attack: 0, sustenance: 3, wieldable: false, throwable: false, craftingValue: 1, category: 'Food' },
    TROPICAL_FISH: { baseId: 'TROPICAL_FISH', name: 'Tropical Fish', description: 'Brightly colored reef fish.', emoji: '🐠', rarity: 'Common', value: 10, weight: 0.3, wearable: false, stackable: true, attack: 0, sustenance: 8, wieldable: false, throwable: false, craftingValue: 0, category: 'Food' },
    ABALONE_SHELL: { baseId: 'ABALONE_SHELL', name: 'Abalone Shell', description: 'Iridescent shell, highly prized.', emoji: '🌈', rarity: 'Uncommon', value: 30, weight: 0.4, wearable: false, stackable: true, attack: 0, sustenance: 0, wieldable: false, throwable: false, craftingValue: 5, category: 'Material' },
    PEARL: { baseId: 'PEARL', name: 'Pearl', description: 'A lustrous gem from an oyster.', emoji: '⚪', rarity: 'Rare', value: 200, weight: 0.05, wearable: true, stackable: true, attack: 0, sustenance: 0, wieldable: false, throwable: false, craftingValue: 10, category: 'Special' },
    
    // Mangrove items
    MANGROVE_BARK: { baseId: 'MANGROVE_BARK', name: 'Mangrove Bark', description: 'Tannic bark used for leather tanning.', emoji: '🪵', rarity: 'Common', value: 5, weight: 0.3, wearable: false, stackable: true, attack: 0, sustenance: 0, wieldable: false, throwable: false, craftingValue: 3, category: 'Material' },
    MUD_CRAB: { baseId: 'MUD_CRAB', name: 'Mud Crab', description: 'Large crab from mangrove swamps.', emoji: '🦀', rarity: 'Common', value: 8, weight: 0.5, wearable: false, stackable: true, attack: 0, sustenance: 10, wieldable: false, throwable: false, craftingValue: 0, category: 'Food' },
    OYSTER: { baseId: 'OYSTER', name: 'Oyster', description: 'Shellfish that might contain a pearl.', emoji: '🦪', rarity: 'Common', value: 6, weight: 0.2, wearable: false, stackable: true, attack: 0, sustenance: 6, wieldable: false, throwable: false, craftingValue: 0, category: 'Food' },
    MANGROVE_HONEY: { baseId: 'MANGROVE_HONEY', name: 'Mangrove Honey', description: 'Rare honey from mangrove flower nectar.', emoji: '🍯', rarity: 'Uncommon', value: 25, weight: 0.3, wearable: false, stackable: true, attack: 0, sustenance: 15, wieldable: false, throwable: false, craftingValue: 4, category: 'Food' },
    CROCODILE_SCALE: { baseId: 'CROCODILE_SCALE', name: 'Crocodile Scale', description: 'Tough scale, useful for armor crafting.', emoji: '🐊', rarity: 'Uncommon', value: 20, weight: 0.2, wearable: false, stackable: true, attack: 1, sustenance: 0, wieldable: false, throwable: false, craftingValue: 6, category: 'Material' },
    MANGROVE_WOOD: { baseId: 'MANGROVE_WOOD', name: 'Mangrove Wood', description: 'Dense, water-resistant wood perfect for boats.', emoji: '🪵', rarity: 'Common', value: 15, weight: 3.0, wearable: false, stackable: true, attack: 2, sustenance: 0, wieldable: true, throwable: false, craftingValue: 7, category: 'Material' },
    
    // Volcanic items
    OBSIDIAN: { baseId: 'OBSIDIAN', name: 'Obsidian', description: 'Volcanic glass, extremely sharp when knapped.', emoji: '⚫', rarity: 'Common', value: 12, weight: 0.5, wearable: false, stackable: true, attack: 3, sustenance: 0, wieldable: true, throwable: true, craftingValue: 6, category: 'Material' },
    SULFUR: { baseId: 'SULFUR', name: 'Sulfur', description: 'Yellow mineral used in alchemy and gunpowder.', emoji: '🟡', rarity: 'Common', value: 10, weight: 0.3, wearable: false, stackable: true, attack: 0, sustenance: 0, wieldable: false, throwable: false, craftingValue: 5, category: 'Material' },
    PUMICE_STONE: { baseId: 'PUMICE_STONE', name: 'Pumice Stone', description: 'Light volcanic rock that floats on water.', emoji: '🪨', rarity: 'Common', value: 4, weight: 0.1, wearable: false, stackable: true, attack: 0, sustenance: 0, wieldable: false, throwable: false, craftingValue: 2, category: 'Material' },
    VOLCANIC_ASH: { baseId: 'VOLCANIC_ASH', name: 'Volcanic Ash', description: 'Fine ash, excellent fertilizer.', emoji: '🌫️', rarity: 'Common', value: 3, weight: 0.2, wearable: false, stackable: true, attack: 0, sustenance: 0, wieldable: false, throwable: false, craftingValue: 2, category: 'Material' },
    
    // Estuary items
    RIVER_SHRIMP: { baseId: 'RIVER_SHRIMP', name: 'River Shrimp', description: 'Small freshwater shrimp.', emoji: '🦐', rarity: 'Common', value: 5, weight: 0.1, wearable: false, stackable: true, attack: 0, sustenance: 4, wieldable: false, throwable: false, craftingValue: 0, category: 'Food' },
    CATTAIL_ROOT: { baseId: 'CATTAIL_ROOT', name: 'Cattail Root', description: 'Edible wetland plant root.', emoji: '🌾', rarity: 'Common', value: 3, weight: 0.3, wearable: false, stackable: true, attack: 0, sustenance: 6, wieldable: false, throwable: false, craftingValue: 1, category: 'Food' },
    DUCK_EGG: { baseId: 'DUCK_EGG', name: 'Duck Egg', description: 'Large, nutritious egg.', emoji: '🥚', rarity: 'Common', value: 4, weight: 0.1, wearable: false, stackable: true, attack: 0, sustenance: 8, wieldable: false, throwable: true, craftingValue: 0, category: 'Food' },
    RIVER_REED: { baseId: 'RIVER_REED', name: 'River Reed', description: 'Useful for weaving and thatching.', emoji: '🌾', rarity: 'Common', value: 2, weight: 0.2, wearable: false, stackable: true, attack: 0, sustenance: 0, wieldable: false, throwable: false, craftingValue: 3, category: 'Material' },
    FRESHWATER_PEARL: { baseId: 'FRESHWATER_PEARL', name: 'Freshwater Pearl', description: 'A rare pearl from a river mussel.', emoji: '⚪', rarity: 'Rare', value: 150, weight: 0.05, wearable: true, stackable: true, attack: 0, sustenance: 0, wieldable: false, throwable: false, craftingValue: 9, category: 'Special' },
    
    // Cliff items
    SEABIRD_EGG: { baseId: 'SEABIRD_EGG', name: 'Seabird Egg', description: 'Nutritious egg from cliff-nesting birds.', emoji: '🥚', rarity: 'Common', value: 5, weight: 0.15, wearable: false, stackable: true, attack: 0, sustenance: 10, wieldable: false, throwable: true, craftingValue: 0, category: 'Food' },
    FEATHER: { baseId: 'FEATHER', name: 'Feather', description: 'Useful for arrows or decoration.', emoji: '🪶', rarity: 'Common', value: 2, weight: 0.01, wearable: false, stackable: true, attack: 0, sustenance: 0, wieldable: false, throwable: false, craftingValue: 2, category: 'Material' },
    CLIFF_FLOWER: { baseId: 'CLIFF_FLOWER', name: 'Cliff Flower', description: 'Hardy flower that grows on cliff faces.', emoji: '🌺', rarity: 'Uncommon', value: 10, weight: 0.05, wearable: true, stackable: true, attack: 0, sustenance: 0, wieldable: false, throwable: false, craftingValue: 3, category: 'Material' },
    GUANO: { baseId: 'GUANO', name: 'Guano', description: 'Bird droppings, excellent fertilizer.', emoji: '💩', rarity: 'Common', value: 4, weight: 0.5, wearable: false, stackable: true, attack: 0, sustenance: 0, wieldable: false, throwable: true, craftingValue: 3, category: 'Material' },
    RARE_ORCHID: { baseId: 'RARE_ORCHID', name: 'Rare Orchid', description: 'An extremely rare and beautiful orchid.', emoji: '🌸', rarity: 'Rare', value: 100, weight: 0.05, wearable: true, stackable: true, attack: 0, sustenance: 0, wieldable: false, throwable: false, craftingValue: 8, category: 'Special' },
    
    // Other special items
    BAMBOO: { baseId: 'BAMBOO', name: 'Bamboo', description: 'Versatile plant material for construction.', emoji: '🎋', rarity: 'Common', value: 4, weight: 0.5, wearable: false, stackable: true, attack: 1, sustenance: 0, wieldable: true, throwable: true, craftingValue: 4, category: 'Material' },
    CORAL_BRANCH: { baseId: 'CORAL_BRANCH', name: 'Living Coral', description: 'A branch of living coral. Taking this harms the reef.', emoji: '🪸', rarity: 'Uncommon', value: 15, weight: 0.5, wearable: false, stackable: true, attack: 0, sustenance: 0, wieldable: false, throwable: false, craftingValue: 4, category: 'Material' },
    
    // Urban scavenging items
    BREAD_CRUST: { baseId: 'BREAD_CRUST', name: 'Bread Crust', description: 'A stale crust of bread.', emoji: '🍞', rarity: 'Junk', value: 0, weight: 0.1, wearable: false, stackable: true, attack: 0, sustenance: 2, wieldable: false, throwable: false, craftingValue: 0, category: 'Food' },
    APPLE_CORE: { baseId: 'APPLE_CORE', name: 'Apple Core', description: 'The remains of an apple.', emoji: '🍎', rarity: 'Junk', value: 0, weight: 0.05, wearable: false, stackable: true, attack: 0, sustenance: 1, wieldable: false, throwable: true, craftingValue: 0, category: 'Food' },
    DISCARDED_CLOTH: { baseId: 'DISCARDED_CLOTH', name: 'Discarded Cloth', description: 'A torn piece of fabric.', emoji: '🧵', rarity: 'Junk', value: 1, weight: 0.1, wearable: false, stackable: true, attack: 0, sustenance: 0, wieldable: false, throwable: false, craftingValue: 1, category: 'Material' },
    BROKEN_POTTERY: { baseId: 'BROKEN_POTTERY', name: 'Broken Pottery', description: 'Shards of a broken pot.', emoji: '🏺', rarity: 'Junk', value: 0, weight: 0.2, wearable: false, stackable: true, attack: 1, sustenance: 0, wieldable: false, throwable: true, craftingValue: 0, category: 'Material' },
    BENT_NAIL: { baseId: 'BENT_NAIL', name: 'Bent Nail', description: 'A bent iron nail.', emoji: '🔩', rarity: 'Junk', value: 0, weight: 0.02, wearable: false, stackable: true, attack: 1, sustenance: 0, wieldable: false, throwable: true, craftingValue: 1, category: 'Material' },
    TORN_PAPER: { baseId: 'TORN_PAPER', name: 'Torn Paper', description: 'A scrap of torn paper.', emoji: '📄', rarity: 'Junk', value: 0, weight: 0.01, wearable: false, stackable: true, attack: 0, sustenance: 0, wieldable: false, throwable: false, craftingValue: 0, category: 'Material' },
    BUTTON: { baseId: 'BUTTON', name: 'Button', description: 'A small button that fell off something.', emoji: '🔘', rarity: 'Junk', value: 0, weight: 0.01, wearable: false, stackable: true, attack: 0, sustenance: 0, wieldable: false, throwable: false, craftingValue: 1, category: 'Material' },
    THREAD: { baseId: 'THREAD', name: 'Thread', description: 'A short length of thread.', emoji: '🧵', rarity: 'Junk', value: 1, weight: 0.01, wearable: false, stackable: true, attack: 0, sustenance: 0, wieldable: false, throwable: false, craftingValue: 1, category: 'Material' },
    
    // Urban theft items (already defined elsewhere but good to have)
    COIN: { baseId: 'COIN', name: 'Coin', description: 'A single coin of the realm.', emoji: '🪙', rarity: 'Common', value: 1, weight: 0.01, wearable: false, stackable: true, attack: 0, sustenance: 0, wieldable: false, throwable: true, craftingValue: 0, category: 'Currency' },
    CANDLE: { baseId: 'CANDLE', name: 'Candle', description: 'A wax candle for light.', emoji: '🕯️', rarity: 'Common', value: 2, weight: 0.1, wearable: false, stackable: true, attack: 0, sustenance: 0, wieldable: false, throwable: true, craftingValue: 1, category: 'Tool' },
    NAILS: { baseId: 'NAILS', name: 'Iron Nails', description: 'A handful of iron nails.', emoji: '🔩', rarity: 'Common', value: 3, weight: 0.2, wearable: false, stackable: true, attack: 0, sustenance: 0, wieldable: false, throwable: true, craftingValue: 2, category: 'Material' },
    PAPER: { baseId: 'PAPER', name: 'Sheet of Paper', description: 'Blank paper for writing.', emoji: '📜', rarity: 'Common', value: 5, weight: 0.01, wearable: false, stackable: true, attack: 0, sustenance: 0, wieldable: false, throwable: true, craftingValue: 2, category: 'Material' },

        // --- Professional & Historically Specific Tools ---
    BRIEFCASE: { baseId: 'BRIEFCASE', name: 'Leather Briefcase', description: 'A leather case for carrying important documents.', emoji: '💼', rarity: 'Uncommon', value: 20, weight: 1.5, wearable: false, stackable: false, attack: 1, sustenance: 0, wieldable: true, throwable: false, craftingValue: 8, category: 'Container', material: 'Leather', equipmentSlot: 'main_hand' },
    STETHOSCOPE: { baseId: 'STETHOSCOPE', name: 'Stethoscope', description: 'A medical instrument for listening to the heart and lungs.', emoji: '🩺', rarity: 'Rare', value: 40, weight: 0.3, wearable: true, stackable: false, attack: 0, sustenance: 0, wieldable: true, throwable: true, craftingValue: 10, category: 'Tool' },
    SYRINGE: { baseId: 'SYRINGE', name: 'Syringe', description: 'A primitive syringe for injections or drawing fluid.', emoji: '💉', rarity: 'Rare', value: 30, weight: 0.2, wearable: false, stackable: false, attack: 1, sustenance: 0, wieldable: true, throwable: true, craftingValue: 9, category: 'Tool' },
    HANDCUFFS: { baseId: 'HANDCUFFS', name: 'Handcuffs', description: 'A pair of metal restraints.', emoji: '🔗', rarity: 'Uncommon', value: 18, weight: 0.8, wearable: true, stackable: false, attack: 0, sustenance: 0, wieldable: true, throwable: true, craftingValue: 7, category: 'Tool' },
    FLASHLIGHT: { baseId: 'FLASHLIGHT', name: 'Flashlight', description: 'A battery-powered light source.', emoji: '🔦', rarity: 'Uncommon', value: 15, weight: 0.5, wearable: false, stackable: false, attack: 1, sustenance: 0, wieldable: true, throwable: false, craftingValue: 6, category: 'Tool', equipmentSlot: 'main_hand' },
    SMARTPHONE: { baseId: 'SMARTPHONE', name: 'Smartphone', description: 'A device of wondrous technology, capable of communication and storing knowledge.', emoji: '📱', rarity: 'Ultra-rare', value: 300, weight: 0.2, wearable: false, stackable: false, attack: 0, sustenance: 0, wieldable: true, throwable: true, craftingValue: 20, category: 'Special' },
    CHIMNEY_BRUSH: { baseId: 'CHIMNEY_BRUSH', name: 'Chimney Brush', description: 'A coarse brush on a long pole for cleaning soot from chimneys.', emoji: '🧹', rarity: 'Common', value: 7, weight: 2.0, wearable: false, stackable: false, attack: 2, sustenance: 0, wieldable: true, throwable: true, craftingValue: 4, category: 'Tool', material: 'Wood', equipmentSlot: 'main_hand' },
    SLATE_BOARD: { baseId: 'SLATE_BOARD', name: 'Slate Board', description: 'A flat piece of slate used for writing with chalk.', emoji: '칠판', rarity: 'Common', value: 5, weight: 1.0, wearable: false, stackable: false, attack: 1, sustenance: 0, wieldable: true, throwable: true, craftingValue: 3, category: 'Tool' },
    GOURD_FLASK: { baseId: 'GOURD_FLASK', name: 'Gourd Flask', description: 'A hollowed-out gourd used as a water container.', emoji: '🏺', rarity: 'Common', value: 2, weight: 0.2, wearable: false, stackable: false, attack: 0, sustenance: 0, wieldable: false, throwable: true, craftingValue: 2, category: 'Container' },
    STICK_CHART: { baseId: 'STICK_CHART', name: 'Stick Chart', description: 'A navigational chart made of sticks and shells, representing ocean currents and islands.', emoji: '🗺️', rarity: 'Rare', value: 60, weight: 0.4, wearable: false, stackable: false, attack: 0, sustenance: 0, wieldable: false, throwable: false, craftingValue: 12, category: 'Tool' },
    SOAP: { baseId: 'SOAP', name: 'Bar of Soap', description: 'A simple bar of soap made from ash and tallow.', emoji: '🧼', rarity: 'Common', value: 2, weight: 0.2, wearable: false, stackable: true, attack: 0, sustenance: 0, wieldable: false, throwable: false, craftingValue: 2, category: 'Material' },
    BANDAGE: { baseId: 'BANDAGE', name: 'Linen Bandage', description: 'A clean strip of linen for dressing wounds.', emoji: '🩹', rarity: 'Common', value: 3, weight: 0.1, wearable: false, stackable: true, attack: 0, sustenance: 0, wieldable: false, throwable: false, craftingValue: 2, category: 'Material' },
    BELL: { baseId: 'BELL', name: 'Hand Bell', description: 'A small bell with a handle.', emoji: '🔔', rarity: 'Uncommon', value: 10, weight: 0.5, wearable: false, stackable: false, attack: 1, sustenance: 0, wieldable: true, throwable: false, craftingValue: 5, category: 'Tool' },
    KEY: { baseId: 'KEY', name: 'Iron Key', description: 'A single, ornate iron key.', emoji: '🔑', rarity: 'Common', value: 4, weight: 0.1, wearable: false, stackable: true, attack: 1, sustenance: 0, wieldable: false, throwable: false, craftingValue: 3, category: 'Tool' },
    PAN: { baseId: 'PAN', name: 'Prospector\'s Pan', description: 'A shallow pan used for sifting gold from riverbeds.', emoji: '🍳', rarity: 'Common', value: 8, weight: 1.0, wearable: false, stackable: false, attack: 1, sustenance: 0, wieldable: true, throwable: true, craftingValue: 4, category: 'Tool', material: 'Iron', equipmentSlot: 'main_hand' },
    COFFEE_BEANS: { baseId: 'COFFEE_BEANS', name: 'Coffee Beans', description: 'A small pouch of unroasted coffee beans.', emoji: '☕', rarity: 'Uncommon', value: 12, weight: 0.4, wearable: false, stackable: true, attack: 0, sustenance: 1, wieldable: false, throwable: true, craftingValue: 3, category: 'Food' },
    BONES: { baseId: 'BONES', name: 'Small Bones', description: 'A handful of small animal bones, used for divination or crafting.', emoji: '🦴', rarity: 'Common', value: 1, weight: 0.2, wearable: false, stackable: true, attack: 0, sustenance: 0, wieldable: false, throwable: true, craftingValue: 1, category: 'Material' },
    BUCKET: { baseId: 'BUCKET', name: 'Wooden Bucket', description: 'A simple bucket made of wood and iron bands.', emoji: '🪣', rarity: 'Common', value: 3, weight: 1.2, wearable: false, stackable: false, attack: 1, sustenance: 0, wieldable: true, throwable: true, craftingValue: 3, category: 'Container' },

    // --- New Apparel ---
    STRAW_HAT: { baseId: 'STRAW_HAT', name: 'Straw Hat', description: 'A wide-brimmed hat woven from straw, good for sun protection.', emoji: '👒', rarity: 'Common', value: 3, weight: 0.3, wearable: true, equipmentSlot: 'head', stackable: false, attack: 0, sustenance: 0, wieldable: false, throwable: false, craftingValue: 2, category: 'Apparel', material: 'Straw' },
    FINE_CLOTHES: { baseId: 'FINE_CLOTHES', name: 'Fine Clothes', description: 'Well-made clothes of a high-quality fabric, suitable for a person of status.', emoji: '👔', rarity: 'Uncommon', value: 35, weight: 1.0, wearable: true, equipmentSlot: 'torso', stackable: false, attack: 0, sustenance: 0, wieldable: false, throwable: false, craftingValue: 8, category: 'Apparel', material: 'Silk' },
    SILK_ROBE: { baseId: 'SILK_ROBE', name: 'Silk Robe', description: 'A flowing robe made of fine silk.', emoji: '👘', rarity: 'Uncommon', value: 40, weight: 0.8, wearable: true, equipmentSlot: 'torso', stackable: false, attack: 0, sustenance: 0, wieldable: false, throwable: false, craftingValue: 9, category: 'Apparel', material: 'Silk' },
    
    // --- New Foods & Crops (as inventory items) ---
    TARO_ROOT: { baseId: 'TARO_ROOT', name: 'Taro Root', description: 'A starchy, edible root common in tropical climates.', emoji: '🍠', rarity: 'Common', value: 2, weight: 0.6, wearable: false, stackable: true, attack: 0, sustenance: 10, wieldable: false, throwable: false, craftingValue: 1, category: 'Food' },
    COCOA_BEANS: { baseId: 'COCOA_BEANS', name: 'Cocoa Beans', description: 'Raw beans from the cacao tree, bitter but valuable.', emoji: '🍫', rarity: 'Uncommon', value: 10, weight: 0.4, wearable: false, stackable: true, attack: 0, sustenance: 2, wieldable: false, throwable: false, craftingValue: 4, category: 'Food' },
    COCONUT: { baseId: 'COCONUT', name: 'Coconut', description: 'A hard-shelled fruit with edible meat and water inside.', emoji: '🥥', rarity: 'Common', value: 3, weight: 1.0, wearable: false, stackable: true, attack: 1, sustenance: 8, wieldable: true, throwable: true, craftingValue: 1, category: 'Food' },
    VEGETABLES: { baseId: 'VEGETABLES', name: 'Assorted Vegetables', description: 'A mix of fresh, common vegetables.', emoji: '🥕', rarity: 'Common', value: 2, weight: 0.5, wearable: false, stackable: true, attack: 0, sustenance: 6, wieldable: false, throwable: false, craftingValue: 1, category: 'Food' },
};

export interface CropDefinition {
    name: string;
    baseId: string;
    zones: CulturalZone[];
    climates: ClimateType[];
    eraStart?: number;
    eraEnd?: number;
}

export const CROPS_DATA: CropDefinition[] = [
    // Old World Grains
    { name: 'Wheat', baseId: 'WHEAT', zones: ['EUROPEAN', 'MENA', 'SOUTH_ASIAN', 'EAST_ASIAN'], climates: [ClimateType.TEMPERATE, ClimateType.ARID, ClimateType.MEDITERRANEAN] },
    { name: 'Barley', baseId: 'BARLEY', zones: ['EUROPEAN', 'MENA', 'SOUTH_ASIAN'], climates: [ClimateType.TEMPERATE, ClimateType.ARID, ClimateType.COLD, ClimateType.MEDITERRANEAN] },
    { name: 'Rye', baseId: 'RYE', zones: ['EUROPEAN'], climates: [ClimateType.COLD, ClimateType.TEMPERATE] },
    { name: 'Oats', baseId: 'OATS', zones: ['EUROPEAN'], climates: [ClimateType.COLD, ClimateType.TEMPERATE] },
    { name: 'Millet', baseId: 'MILLET', zones: ['EAST_ASIAN', 'SUB_SAHARAN_AFRICAN', 'SOUTH_ASIAN'], climates: [ClimateType.ARID, ClimateType.TEMPERATE, ClimateType.TROPICAL] },
    { name: 'Sorghum', baseId: 'SORGHUM', zones: ['SUB_SAHARAN_AFRICAN', 'MENA'], climates: [ClimateType.ARID, ClimateType.TROPICAL] },
    
    // Rice
    { name: 'Rice', baseId: 'RICE', zones: ['EAST_ASIAN', 'SOUTH_ASIAN', 'OCEANIA'], climates: [ClimateType.TROPICAL, ClimateType.SEMITROPICAL] },
    { name: 'Wild Rice', baseId: 'WILD_RICE', zones: ['NORTH_AMERICAN_PRE_COLUMBIAN'], climates: [ClimateType.TEMPERATE, ClimateType.COLD] },
    
    // Pre-Columbian American Crops (before 1492)
    { name: 'Maize', baseId: 'CORN', zones: ['NORTH_AMERICAN_PRE_COLUMBIAN', 'SOUTH_AMERICAN'], climates: [ClimateType.TEMPERATE, ClimateType.SEMITROPICAL, ClimateType.TROPICAL], eraEnd: 1492 },
    { name: 'Three Sisters (Corn, Beans, Squash)', baseId: 'THREE_SISTERS', zones: ['NORTH_AMERICAN_PRE_COLUMBIAN'], climates: [ClimateType.TEMPERATE], eraEnd: 1650 },
    { name: 'Quinoa', baseId: 'QUINOA', zones: ['SOUTH_AMERICAN'], climates: [ClimateType.COLD, ClimateType.TEMPERATE], eraEnd: 1532 },
    { name: 'Amaranth', baseId: 'AMARANTH', zones: ['NORTH_AMERICAN_PRE_COLUMBIAN', 'SOUTH_AMERICAN'], climates: [ClimateType.TEMPERATE, ClimateType.TROPICAL], eraEnd: 1521 },
    { name: 'Beans', baseId: 'BEANS', zones: ['NORTH_AMERICAN_PRE_COLUMBIAN', 'SOUTH_AMERICAN'], climates: [ClimateType.TEMPERATE, ClimateType.TROPICAL], eraEnd: 1492 },
    { name: 'Squash', baseId: 'SQUASH', zones: ['NORTH_AMERICAN_PRE_COLUMBIAN', 'SOUTH_AMERICAN'], climates: [ClimateType.TEMPERATE, ClimateType.SEMITROPICAL], eraEnd: 1492 },
    { name: 'Tomato', baseId: 'TOMATO', zones: ['SOUTH_AMERICAN'], climates: [ClimateType.TEMPERATE, ClimateType.SEMITROPICAL], eraEnd: 1521 },
    { name: 'Cacao', baseId: 'CACAO', zones: ['SOUTH_AMERICAN'], climates: [ClimateType.TROPICAL], eraEnd: 1521 },
    { name: 'Sunflower', baseId: 'SUNFLOWER', zones: ['NORTH_AMERICAN_PRE_COLUMBIAN'], climates: [ClimateType.TEMPERATE, ClimateType.ARID], eraEnd: 1510 },
    { name: 'Tobacco', baseId: 'TOBACCO', zones: ['NORTH_AMERICAN_PRE_COLUMBIAN', 'SOUTH_AMERICAN'], climates: [ClimateType.TEMPERATE, ClimateType.TROPICAL], eraEnd: 1560 },
    
    // Post-Columbian Exchange Crops
    { name: 'Corn', baseId: 'CORN', zones: ['EUROPEAN', 'SUB_SAHARAN_AFRICAN', 'EAST_ASIAN', 'SOUTH_ASIAN'], climates: [ClimateType.TEMPERATE, ClimateType.SEMITROPICAL], eraStart: 1492 },
    { name: 'Potato', baseId: 'POTATO', zones: ['SOUTH_AMERICAN'], climates: [ClimateType.COLD, ClimateType.TEMPERATE], eraEnd: 1570 },
    { name: 'Potato', baseId: 'POTATO', zones: ['EUROPEAN'], climates: [ClimateType.COLD, ClimateType.TEMPERATE], eraStart: 1570 },
    { name: 'Potato', baseId: 'POTATO', zones: ['SOUTH_ASIAN', 'EAST_ASIAN'], climates: [ClimateType.COLD, ClimateType.TEMPERATE], eraStart: 1600 },
    { name: 'Tomato', baseId: 'TOMATO', zones: ['EUROPEAN', 'MENA'], climates: [ClimateType.MEDITERRANEAN, ClimateType.TEMPERATE], eraStart: 1540 },
    { name: 'Tobacco', baseId: 'TOBACCO', zones: ['EUROPEAN', 'MENA', 'EAST_ASIAN'], climates: [ClimateType.TEMPERATE, ClimateType.SEMITROPICAL], eraStart: 1560 },
    
    // Root Crops
    { name: 'Yam', baseId: 'YAM', zones: ['SUB_SAHARAN_AFRICAN', 'OCEANIA', 'SOUTH_AMERICAN'], climates: [ClimateType.TROPICAL] },
    { name: 'Taro', baseId: 'TARO', zones: ['OCEANIA', 'EAST_ASIAN', 'SUB_SAHARAN_AFRICAN'], climates: [ClimateType.TROPICAL, ClimateType.SEMITROPICAL] },
    { name: 'Cassava', baseId: 'CASSAVA', zones: ['SOUTH_AMERICAN', 'SUB_SAHARAN_AFRICAN'], climates: [ClimateType.TROPICAL], eraStart: 1500 },
    { name: 'Sweet Potato', baseId: 'SWEET_POTATO', zones: ['SOUTH_AMERICAN', 'OCEANIA'], climates: [ClimateType.TROPICAL, ClimateType.SEMITROPICAL] },
    
    // Tree Crops and Orchards
    { name: 'Olive Grove', baseId: 'OLIVES', zones: ['EUROPEAN', 'MENA'], climates: [ClimateType.MEDITERRANEAN] },
    { name: 'Vineyard', baseId: 'GRAPES', zones: ['EUROPEAN', 'MENA'], climates: [ClimateType.TEMPERATE, ClimateType.MEDITERRANEAN] },
    { name: 'Date Palms', baseId: 'DATES', zones: ['MENA'], climates: [ClimateType.ARID, ClimateType.TROPICAL] },
    { name: 'Citrus Orchard', baseId: 'CITRUS', zones: ['EUROPEAN', 'MENA', 'EAST_ASIAN'], climates: [ClimateType.MEDITERRANEAN, ClimateType.SEMITROPICAL] },
    { name: 'Apple Orchard', baseId: 'APPLES', zones: ['EUROPEAN', 'EAST_ASIAN'], climates: [ClimateType.TEMPERATE, ClimateType.COLD] },
    { name: 'Peach Orchard', baseId: 'PEACHES', zones: ['EAST_ASIAN', 'EUROPEAN'], climates: [ClimateType.TEMPERATE] },
    { name: 'Almond Grove', baseId: 'ALMONDS', zones: ['EUROPEAN', 'MENA'], climates: [ClimateType.MEDITERRANEAN] },
    { name: 'Fig Orchard', baseId: 'FIGS', zones: ['EUROPEAN', 'MENA'], climates: [ClimateType.MEDITERRANEAN, ClimateType.SEMITROPICAL] },
    { name: 'Coconut Grove', baseId: 'COCONUTS', zones: ['OCEANIA', 'SOUTH_ASIAN', 'SUB_SAHARAN_AFRICAN'], climates: [ClimateType.TROPICAL] },
    { name: 'Banana Plantation', baseId: 'BANANAS', zones: ['SUB_SAHARAN_AFRICAN', 'SOUTH_ASIAN', 'OCEANIA', 'SOUTH_AMERICAN'], climates: [ClimateType.TROPICAL] },
    { name: 'Avocado Grove', baseId: 'AVOCADOS', zones: ['SOUTH_AMERICAN'], climates: [ClimateType.SEMITROPICAL, ClimateType.TROPICAL], eraEnd: 1519 },
    
    // Fiber and Industrial Crops
    { name: 'Cotton', baseId: 'COTTON', zones: ['SOUTH_ASIAN', 'MENA', 'SOUTH_AMERICAN', 'SUB_SAHARAN_AFRICAN'], climates: [ClimateType.ARID, ClimateType.TROPICAL, ClimateType.SEMITROPICAL] },
    { name: 'Flax', baseId: 'FLAX', zones: ['EUROPEAN', 'MENA'], climates: [ClimateType.TEMPERATE, ClimateType.COLD] },
    { name: 'Hemp', baseId: 'HEMP', zones: ['EUROPEAN', 'EAST_ASIAN'], climates: [ClimateType.TEMPERATE] },
    { name: 'Silk Mulberry', baseId: 'SILK', zones: ['EAST_ASIAN'], climates: [ClimateType.TEMPERATE, ClimateType.SEMITROPICAL] },
    { name: 'Indigo', baseId: 'INDIGO', zones: ['SOUTH_ASIAN', 'SUB_SAHARAN_AFRICAN'], climates: [ClimateType.TROPICAL, ClimateType.SEMITROPICAL] },
    
    // Sugar and Spices
    { name: 'Sugar Cane', baseId: 'SUGAR_CANE', zones: ['SOUTH_ASIAN', 'OCEANIA', 'SUB_SAHARAN_AFRICAN'], climates: [ClimateType.TROPICAL] },
    { name: 'Sugar Cane', baseId: 'SUGAR_CANE', zones: ['SOUTH_AMERICAN'], climates: [ClimateType.TROPICAL], eraStart: 1516 },
    { name: 'Tea', baseId: 'TEA', zones: ['EAST_ASIAN', 'SOUTH_ASIAN'], climates: [ClimateType.TEMPERATE, ClimateType.SEMITROPICAL] },
    { name: 'Coffee', baseId: 'COFFEE', zones: ['MENA', 'SUB_SAHARAN_AFRICAN'], climates: [ClimateType.TROPICAL, ClimateType.SEMITROPICAL], eraStart: 1400 },
    { name: 'Coffee', baseId: 'COFFEE', zones: ['SOUTH_AMERICAN'], climates: [ClimateType.TROPICAL, ClimateType.SEMITROPICAL], eraStart: 1720 },
    { name: 'Black Pepper', baseId: 'PEPPER', zones: ['SOUTH_ASIAN'], climates: [ClimateType.TROPICAL] },
    { name: 'Cinnamon', baseId: 'CINNAMON', zones: ['SOUTH_ASIAN'], climates: [ClimateType.TROPICAL] },
    { name: 'Nutmeg', baseId: 'NUTMEG', zones: ['OCEANIA'], climates: [ClimateType.TROPICAL] },


];