/**
 * constants/gameData/itemDefinitions.ts - Base definitions for all items and crops.
 */
import { ItemDefinition, CulturalZone, ClimateType } from '../../types';

export const ITEM_DEFINITIONS: Record<string, ItemDefinition> = {
    // --- Tools ---
    AXE: { baseId: 'AXE', name: 'Axe', description: 'A sturdy axe for chopping wood or other materials.', emoji: '🪓', rarity: 'Common', value: 10, weight: 2.0, wearable: false, stackable: false, attack: 4, sustenance: 0, wieldable: true, throwable: false, craftingValue: 5, category: 'Tool', material: 'Iron', equipmentSlot: 'main_hand' },
    PICKAXE: { baseId: 'PICKAXE', name: 'Pickaxe', description: 'A heavy pickaxe for breaking rocks and mining ore.', emoji: '⛏️', rarity: 'Common', value: 12, weight: 3.0, wearable: false, stackable: false, attack: 3, sustenance: 0, wieldable: true, throwable: false, craftingValue: 6, category: 'Tool', material: 'Iron', equipmentSlot: 'main_hand' },
    STEEL_PICKAXE: { baseId: 'STEEL_PICKAXE', name: 'Steel Pickaxe', description: 'A well-made steel pickaxe, more efficient than iron.', emoji: '⛏️', rarity: 'Uncommon', value: 40, weight: 2.8, wearable: false, stackable: false, attack: 4, sustenance: 0, wieldable: true, throwable: false, craftingValue: 8, category: 'Tool', material: 'Steel', equipmentSlot: 'main_hand' },
    
    // --- Ores ---
    IRON_ORE: { baseId: 'IRON_ORE', name: 'Iron Ore', description: 'A chunk of rock rich with iron.', emoji: '🪨', rarity: 'Common', value: 5, weight: 2.5, wearable: false, stackable: true, attack: 1, sustenance: 0, wieldable: true, throwable: true, craftingValue: 4, category: 'Material', material: 'Iron', equipmentSlot: 'main_hand' },
    TIN_ORE: { baseId: 'TIN_ORE', name: 'Tin Ore', description: 'A soft, silvery-white metal ore.', emoji: '🪨', rarity: 'Common', value: 4, weight: 2.2, wearable: false, stackable: true, attack: 1, sustenance: 0, wieldable: true, throwable: true, craftingValue: 3, category: 'Material', equipmentSlot: 'main_hand' },
    COPPER_ORE: { baseId: 'COPPER_ORE', name: 'Copper Ore', description: 'Rock containing veins of reddish-brown copper.', emoji: '🪨', rarity: 'Common', value: 6, weight: 2.8, wearable: false, stackable: true, attack: 1, sustenance: 0, wieldable: true, throwable: true, craftingValue: 4, category: 'Material', material: 'Copper', equipmentSlot: 'main_hand' },
    GOLD_ORE: { baseId: 'GOLD_ORE', name: 'Gold Ore', description: 'A heavy rock with glittering flecks of gold.', emoji: '🌟', rarity: 'Rare', value: 50, weight: 3.5, wearable: false, stackable: true, attack: 1, sustenance: 0, wieldable: true, throwable: true, craftingValue: 10, category: 'Material', equipmentSlot: 'main_hand' },
    SILVER_ORE: { baseId: 'SILVER_ORE', name: 'Silver Ore', description: 'A rock with gleaming veins of silver.', emoji: '🪨', rarity: 'Uncommon', value: 25, weight: 3.0, wearable: false, stackable: true, attack: 1, sustenance: 0, wieldable: true, throwable: true, craftingValue: 8, category: 'Material' },
    LEAD_ORE: { baseId: 'LEAD_ORE', name: 'Lead Ore', description: 'A dense, dull grey ore.', emoji: '🪨', rarity: 'Common', value: 3, weight: 4.0, wearable: false, stackable: true, attack: 1, sustenance: 0, wieldable: true, throwable: true, craftingValue: 3, category: 'Material' },
    COAL: { baseId: 'COAL', name: 'Lump of Coal', description: 'A black, combustible sedimentary rock.', emoji: '⚫', rarity: 'Common', value: 2, weight: 1.0, wearable: false, stackable: true, attack: 0, sustenance: 0, wieldable: false, throwable: true, craftingValue: 2, category: 'Material' },
    ROCK_SALT: { baseId: 'ROCK_SALT', name: 'Rock Salt', description: 'A crystalline chunk of salt, useful for preserving food.', emoji: '🧂', rarity: 'Common', value: 4, weight: 1.0, wearable: false, stackable: true, attack: 0, sustenance: 0, wieldable: false, throwable: true, craftingValue: 1, category: 'Material' },
    CLAY_LUMP: { baseId: 'CLAY_LUMP', name: 'Lump of Clay', description: 'A soft lump of raw clay, ready for pottery.', emoji: '🏺', rarity: 'Common', value: 1, weight: 1.5, wearable: false, stackable: true, attack: 0, sustenance: 0, wieldable: false, throwable: true, craftingValue: 3, category: 'Material' },
    OCHRE_LUMP: { baseId: 'OCHRE_LUMP', name: 'Lump of Ochre', description: 'A soft, earthy pigment.', emoji: '🎨', rarity: 'Common', value: 8, weight: 0.5, wearable: false, stackable: true, attack: 0, sustenance: 0, wieldable: false, throwable: false, craftingValue: 3, category: 'Material' },
    FLINT_STONE: { baseId: 'FLINT_STONE', name: 'Flint Stone', description: 'A hard, sedimentary cryptocrystalline form of quartz.', emoji: '🪨', rarity: 'Common', value: 3, weight: 1.0, wearable: false, stackable: true, attack: 1, sustenance: 0, wieldable: true, throwable: true, craftingValue: 4, category: 'Material' },
    STONE_BLOCK: { baseId: 'STONE_BLOCK', name: 'Stone Block', description: 'A rough block of quarried stone.', emoji: '🧱', rarity: 'Common', value: 2, weight: 10.0, wearable: false, stackable: true, attack: 0, sustenance: 0, wieldable: false, throwable: false, craftingValue: 1, category: 'Material' },

    // --- Processed Metals ---
    IRON_INGOT: { baseId: 'IRON_INGOT', name: 'Iron Ingot', description: 'A bar of refined iron, ready for forging.', emoji: '🔩', rarity: 'Common', value: 15, weight: 2.0, wearable: false, stackable: true, attack: 2, sustenance: 0, wieldable: true, throwable: false, craftingValue: 6, category: 'Material', material: 'Iron' },
    COPPER_INGOT: { baseId: 'COPPER_INGOT', name: 'Copper Ingot', description: 'A bar of refined copper.', emoji: '🔩', rarity: 'Common', value: 18, weight: 2.2, wearable: false, stackable: true, attack: 2, sustenance: 0, wieldable: true, throwable: false, craftingValue: 6, category: 'Material', material: 'Copper' },
    TIN_INGOT: { baseId: 'TIN_INGOT', name: 'Tin Ingot', description: 'A bar of refined tin.', emoji: '🔩', rarity: 'Common', value: 12, weight: 2.0, wearable: false, stackable: true, attack: 1, sustenance: 0, wieldable: true, throwable: false, craftingValue: 5, category: 'Material' },
    GOLD_BAR: { baseId: 'GOLD_BAR', name: 'Gold Bar', description: 'A bar of pure, shining gold.', emoji: '💰', rarity: 'Rare', value: 150, weight: 2.8, wearable: false, stackable: true, attack: 2, sustenance: 0, wieldable: true, throwable: false, craftingValue: 10, category: 'Material' },
    SILVER_INGOT: { baseId: 'SILVER_INGOT', name: 'Silver Ingot', description: 'A bar of refined silver.', emoji: '🔩', rarity: 'Uncommon', value: 75, weight: 2.5, wearable: false, stackable: true, attack: 1, sustenance: 0, wieldable: true, throwable: false, craftingValue: 9, category: 'Material' },
    LEAD_BAR: { baseId: 'LEAD_BAR', name: 'Lead Bar', description: 'A heavy bar of refined lead.', emoji: '🔩', rarity: 'Common', value: 9, weight: 3.5, wearable: false, stackable: true, attack: 2, sustenance: 0, wieldable: true, throwable: false, craftingValue: 4, category: 'Material' },

    // --- Religious/Holy Site Items ---
    INCENSE: { baseId: 'INCENSE', name: 'Incense Sticks', description: 'Sticks that release a fragrant smoke when burned.', emoji: '🌬️', rarity: 'Common', value: 5, weight: 0.1, wearable: false, stackable: true, attack: 0, sustenance: 0, wieldable: false, throwable: false, craftingValue: 2, category: 'Material' },
    CANDLES: { baseId: 'CANDLES', name: 'Beeswax Candles', description: 'Candles made from pure beeswax.', emoji: '🕯️', rarity: 'Uncommon', value: 8, weight: 0.2, wearable: false, stackable: true, attack: 0, sustenance: 0, wieldable: false, throwable: false, craftingValue: 3, category: 'Tool' },
    RELIGIOUS_TEXT: { baseId: 'RELIGIOUS_TEXT', name: 'Religious Text', description: 'A scroll or book containing sacred writings.', emoji: '📜', rarity: 'Rare', value: 50, weight: 0.5, wearable: false, stackable: false, attack: 0, sustenance: 0, wieldable: false, throwable: false, craftingValue: 1, category: 'Document' },
    BLESSED_ARTIFACT: { baseId: 'BLESSED_ARTIFACT', name: 'Blessed Artifact', description: 'A small object imbued with a spiritual blessing.', emoji: '✨', rarity: 'Rare', value: 75, weight: 0.2, wearable: false, stackable: false, attack: 0, sustenance: 0, wieldable: false, throwable: false, craftingValue: 0, category: 'Special' },


    // --- Junk/Basic ---
    STICK: { baseId: 'STICK', name: 'Sturdy Stick', description: 'A solid piece of wood. Could be useful.', emoji: '🪵', rarity: 'Junk', value: 0, weight: 0.5, wearable: false, stackable: false, attack: 1, sustenance: 0, wieldable: true, throwable: true, craftingValue: 1, category: 'Tool', material: 'Wood', equipmentSlot: 'main_hand' },
    SMOOTH_STONE: { baseId: 'SMOOTH_STONE', name: 'Smooth Stone', description: 'A pleasant, smooth stone, worn by water.', emoji: '🪨', rarity: 'Junk', value: 0, weight: 0.2, wearable: false, stackable: true, attack: 1, sustenance: 0, wieldable: false, throwable: true, craftingValue: 1, category: 'Material', material: 'Stone' },
    DRY_LEAVES: { baseId: 'DRY_LEAVES', name: 'Dry Leaves', description: 'A handful of dry, brittle leaves. Good for tinder.', emoji: '🍂', rarity: 'Junk', value: 0, weight: 0.1, wearable: false, stackable: true, attack: 0, sustenance: -1, wieldable: false, throwable: false, craftingValue: 1, category: 'Material' },
    POTTERY_SHARD: { baseId: 'POTTERY_SHARD', name: 'Pottery Shard', description: 'A broken piece of old pottery.', emoji: '🏺', rarity: 'Junk', value: 0, weight: 0.1, wearable: false, stackable: true, attack: 0, sustenance: 0, wieldable: false, throwable: true, craftingValue: 1, category: 'Material' },
    DAMP_LOG: { baseId: 'DAMP_LOG', name: 'Damp Log', description: 'A waterlogged piece of wood. Not very useful right now.', emoji: '🪵', rarity: 'Junk', value: 0, weight: 1.5, wearable: false, stackable: true, attack: 0, sustenance: 0, wieldable: false, throwable: false, craftingValue: 1, category: 'Material' },
    ROOT: { baseId: 'ROOT', name: 'Tough Root', description: 'A fibrous, gnarled root.', emoji: '🌱', rarity: 'Junk', value: 0, weight: 0.3, wearable: false, stackable: true, attack: 0, sustenance: 1, wieldable: false, throwable: false, craftingValue: 1, category: 'Material' },
    EARTHWORM: { baseId: 'EARTHWORM', name: 'Earthworm', description: 'A wriggling earthworm. Good for bait.', emoji: '🪱', rarity: 'Junk', value: 1, weight: 0.1, wearable: false, stackable: true, attack: 0, sustenance: 2, wieldable: false, throwable: false, craftingValue: 0, category: 'Food' },

    // --- Common Items ---
    WOODEN_BOWL: { baseId: 'WOODEN_BOWL', name: 'Wooden Bowl', description: 'A simple carved wooden bowl.', emoji: '🥣', rarity: 'Common', value: 1, weight: 0.3, wearable: false, stackable: false, attack: 0, sustenance: 0, wieldable: false, throwable: false, craftingValue: 2, category: 'Tool' },
    CLAY_LAMP: { baseId: 'CLAY_LAMP', name: 'Clay Lamp', description: 'A small clay oil lamp.', emoji: '🪔', rarity: 'Common', value: 2, weight: 0.4, wearable: false, stackable: false, attack: 1, sustenance: 0, wieldable: true, throwable: false, craftingValue: 1, category: 'Tool', equipmentSlot: 'main_hand' },
    WOOL_TUNIC: { baseId: 'WOOL_TUNIC', name: 'Wool Tunic', description: 'A roughspun but warm woolen tunic.', emoji: '👕', rarity: 'Common', value: 5, weight: 1.0, wearable: true, equipmentSlot: 'torso', stackable: false, attack: 0, sustenance: 0, wieldable: false, throwable: false, craftingValue: 5, category: 'Apparel', material: 'Wool' },
    BREAD: { baseId: 'BREAD', name: 'Loaf of Bread', description: 'A simple, hearty loaf of bread.', emoji: '🍞', rarity: 'Common', value: 2, weight: 0.5, wearable: false, stackable: true, attack: 0, sustenance: 20, wieldable: false, throwable: false, craftingValue: 1, category: 'Food' },
    QUILL: { baseId: 'QUILL', name: 'Goose Quill', description: 'A feather prepared for writing.', emoji: '✒️', rarity: 'Common', value: 1, weight: 0.1, wearable: false, stackable: false, attack: 1, sustenance: 0, wieldable: true, throwable: false, craftingValue: 1, category: 'Tool', equipmentSlot: 'main_hand' },
    INK_POT: { baseId: 'INK_POT', name: 'Pot of Ink', description: 'A small pot of black ink.', emoji: '⚫', rarity: 'Common', value: 3, weight: 0.2, wearable: false, stackable: false, attack: 1, sustenance: 0, wieldable: true, throwable: false, craftingValue: 2, category: 'Material', equipmentSlot: 'main_hand' },
    SIMPLE_ROBE: { baseId: 'SIMPLE_ROBE', name: 'Simple Robe', description: 'A plain, functional robe.', emoji: '🥻', rarity: 'Common', value: 4, weight: 1.2, wearable: true, equipmentSlot: 'torso', stackable: false, attack: 0, sustenance: 0, wieldable: false, throwable: false, craftingValue: 4, category: 'Apparel', material: 'Linen' },
    LEATHER_APRON: { baseId: 'LEATHER_APRON', name: 'Leather Apron', description: 'A tough leather apron, stained from work.', emoji: '🎽', rarity: 'Common', value: 6, weight: 1.5, wearable: true, equipmentSlot: 'torso', stackable: false, attack: 0, sustenance: 0, wieldable: false, throwable: false, craftingValue: 3, category: 'Apparel', material: 'Leather' },
    ROPE: { baseId: 'ROPE', name: 'Coil of Rope', description: 'A length of sturdy hemp rope.', emoji: ' रस्सी', rarity: 'Common', value: 3, weight: 1.0, wearable: false, stackable: false, attack: 0, sustenance: 0, wieldable: false, throwable: false, craftingValue: 2, category: 'Tool' },
    SIMPLE_RING: { baseId: 'SIMPLE_RING', name: 'Simple Ring', description: 'A simple ring, perhaps of sentimental value.', emoji: '💍', rarity: 'Common', value: 10, weight: 0.1, wearable: true, equipmentSlot: 'ring1', stackable: false, attack: 0, sustenance: 0, wieldable: false, throwable: false, craftingValue: 1, category: 'Apparel', material: 'Metal' },
    ROPE_NECKLACE: { baseId: 'ROPE_NECKLACE', name: 'Rope Necklace', description: 'A simple necklace made of tied rope.', emoji: '📿', rarity: 'Common', value: 1, weight: 0.1, wearable: true, equipmentSlot: 'amulet', stackable: false, attack: 0, sustenance: 0, wieldable: false, throwable: false, craftingValue: 1, category: 'Apparel', material: 'Hemp' },
    CLOTH_HOOD: { baseId: 'CLOTH_HOOD', name: 'Cloth Hood', description: 'A simple hood of roughspun cloth, offering basic protection from the elements.', emoji: '👤', rarity: 'Common', value: 2, weight: 0.3, wearable: true, equipmentSlot: 'head', stackable: false, attack: 0, sustenance: 0, wieldable: false, throwable: false, craftingValue: 2, category: 'Apparel', material: 'Cloth' },
    LEATHER_CAP: { baseId: 'LEATHER_CAP', name: 'Leather Cap', description: 'A sturdy cap made of boiled leather.', emoji: '🧢', rarity: 'Common', value: 4, weight: 0.5, wearable: true, equipmentSlot: 'head', stackable: false, attack: 0, sustenance: 0, wieldable: false, throwable: false, craftingValue: 3, category: 'Apparel', material: 'Leather' },
    LEATHER_BOOTS: { baseId: 'LEATHER_BOOTS', name: 'Leather Boots', description: 'Durable leather boots, well-worn.', emoji: '🥾', rarity: 'Common', value: 5, weight: 1.2, wearable: true, equipmentSlot: 'feet', stackable: false, attack: 0, sustenance: 0, wieldable: false, throwable: false, craftingValue: 4, category: 'Apparel', material: 'Leather' },
    SANDALS: { baseId: 'SANDALS', name: 'Sandals', description: 'Simple sandals with leather straps, suitable for warm climates.', emoji: '👡', rarity: 'Common', value: 2, weight: 0.4, wearable: true, equipmentSlot: 'feet', stackable: false, attack: 0, sustenance: 0, wieldable: false, throwable: false, craftingValue: 2, category: 'Apparel', material: 'Leather' },

    // --- Textual Items ---
    BOOK: { baseId: 'BOOK', name: 'Old Book', description: 'A leather-bound book with worn pages.', emoji: '📖', rarity: 'Uncommon', value: 10, weight: 1.5, wearable: false, stackable: false, attack: 1, sustenance: 0, wieldable: true, throwable: true, craftingValue: 3, category: 'Document', material: 'Paper', equipmentSlot: 'main_hand' },
    SCROLL: { baseId: 'SCROLL', name: 'Weathered Scroll', description: 'A rolled piece of parchment, its contents faded.', emoji: '📜', rarity: 'Uncommon', value: 8, weight: 0.2, wearable: false, stackable: true, attack: 0, sustenance: 0, wieldable: false, throwable: false, craftingValue: 2, category: 'Document', material: 'Paper' },
    LETTER: { baseId: 'LETTER', name: 'Sealed Letter', description: 'A letter sealed with wax, its contents a mystery.', emoji: '✉️', rarity: 'Uncommon', value: 2, weight: 0.1, wearable: false, stackable: true, attack: 0, sustenance: 0, wieldable: false, throwable: false, craftingValue: 1, category: 'Document', material: 'Paper' },
    PARCHMENT_ROLL: { baseId: 'PARCHMENT_ROLL', name: 'Blank Parchment Roll', description: 'A roll of fresh parchment, ready for writing.', emoji: '📜', rarity: 'Common', value: 3, weight: 0.1, wearable: false, stackable: true, attack: 0, sustenance: 0, wieldable: false, throwable: false, craftingValue: 2, category: 'Document', material: 'Paper' },

    // --- Historically Specific Items ---
    WHETSTONE: { baseId: 'WHETSTONE', name: 'Whetstone', description: 'A stone for sharpening blades and tools.', emoji: '🪨', rarity: 'Common', value: 2, weight: 0.5, wearable: false, stackable: false, attack: 1, sustenance: 0, wieldable: true, throwable: true, craftingValue: 2, category: 'Tool', material: 'Stone', equipmentSlot: 'main_hand' },
    HORSESHOE: { baseId: 'HORSESHOE', name: 'Iron Horseshoe', description: 'A U-shaped iron shoe for horses.', emoji: '🔧', rarity: 'Common', value: 8, weight: 1.0, wearable: false, stackable: true, attack: 2, sustenance: 0, wieldable: true, throwable: false, craftingValue: 4, category: 'Tool', material: 'Iron' },
    HAMMER: { baseId: 'HAMMER', name: 'Smith\'s Hammer', description: 'A heavy hammer for metalworking.', emoji: '🔨', rarity: 'Common', value: 12, weight: 2.0, wearable: false, stackable: false, attack: 3, sustenance: 0, wieldable: true, throwable: false, craftingValue: 5, category: 'Tool', material: 'Iron', equipmentSlot: 'main_hand' },
    BELLOWS: { baseId: 'BELLOWS', name: 'Leather Bellows', description: 'Bellows for stoking a forge fire.', emoji: '💨', rarity: 'Common', value: 15, weight: 3.0, wearable: false, stackable: false, attack: 0, sustenance: 0, wieldable: false, throwable: false, craftingValue: 6, category: 'Tool' },
    PURSE: { baseId: 'PURSE', name: 'Leather Purse', description: 'A small leather purse for holding coins.', emoji: '👛', rarity: 'Common', value: 5, weight: 0.2, wearable: true, stackable: false, attack: 0, sustenance: 0, wieldable: false, throwable: false, craftingValue: 2, category: 'Container', material: 'Leather', equipmentSlot: 'belt' },
    SCALE: { baseId: 'SCALE', name: 'Merchant\'s Scale', description: 'Small brass scales for weighing precious goods.', emoji: '⚖️', rarity: 'Uncommon', value: 20, weight: 1.5, wearable: false, stackable: false, attack: 1, sustenance: 0, wieldable: true, throwable: false, craftingValue: 8, category: 'Tool', material: 'Bronze', equipmentSlot: 'main_hand' },
    SPICE_POUCH: { baseId: 'SPICE_POUCH', name: 'Spice Pouch', description: 'A small pouch containing aromatic spices.', emoji: '🧂', rarity: 'Uncommon', value: 15, weight: 0.3, wearable: false, stackable: true, attack: 0, sustenance: 0, wieldable: false, throwable: false, craftingValue: 3, category: 'Material' },
    SILK_CLOTH: { baseId: 'SILK_CLOTH', name: 'Silk Cloth', description: 'Fine silk cloth from the East.', emoji: '🧵', rarity: 'Uncommon', value: 25, weight: 0.2, wearable: false, stackable: true, attack: 0, sustenance: 0, wieldable: false, throwable: false, craftingValue: 6, category: 'Material', material: 'Silk' },
    RICE: { baseId: 'RICE', name: 'Bowl of Rice', description: 'Steamed white rice, a staple grain.', emoji: '🍚', rarity: 'Common', value: 2, weight: 0.3, wearable: false, stackable: true, attack: 0, sustenance: 15, wieldable: false, throwable: false, craftingValue: 1, category: 'Food' },
    FISH_MEAT: { baseId: 'FISH_MEAT', name: 'Fresh Fish', description: 'A fresh-caught fish.', emoji: '🐟', rarity: 'Common', value: 3, weight: 0.8, wearable: false, stackable: true, attack: 0, sustenance: 12, wieldable: false, throwable: true, craftingValue: 1, category: 'Food' },
    IVORY_TUSK: { baseId: 'IVORY_TUSK', name: 'Small Ivory Piece', description: 'A piece of carved ivory.', emoji: '🦷', rarity: 'Rare', value: 80, weight: 1.0, wearable: false, stackable: true, attack: 1, sustenance: 0, wieldable: false, throwable: false, craftingValue: 10, category: 'Material' },
    PRAYER_BEADS: { baseId: 'PRAYER_BEADS', name: 'Prayer Beads', description: 'A string of wooden prayer beads.', emoji: '📿', rarity: 'Common', value: 8, weight: 0.2, wearable: true, stackable: false, attack: 0, sustenance: 0, wieldable: false, throwable: false, craftingValue: 3, category: 'Apparel', material: 'Wood', equipmentSlot: 'amulet' },
    KATANA: { baseId: 'KATANA', name: 'Katana', description: 'A curved Japanese sword, masterfully crafted.', emoji: '⚔️', rarity: 'Rare', value: 100, weight: 1.2, wearable: false, stackable: false, attack: 8, sustenance: 0, wieldable: true, throwable: false, craftingValue: 15, category: 'Weapon', material: 'Steel', equipmentSlot: 'main_hand' },
    SCIMITAR: { baseId: 'SCIMITAR', name: 'Curved Scimitar', description: 'A curved blade favored in the Middle East.', emoji: '⚔️', rarity: 'Uncommon', value: 40, weight: 1.0, wearable: false, stackable: false, attack: 5, sustenance: 0, wieldable: true, throwable: false, craftingValue: 8, category: 'Weapon', material: 'Steel', equipmentSlot: 'main_hand' },

    // --- MEDIEVAL CRAFT TOOLS ---
    SMITHS_ANVIL: { baseId: 'SMITHS_ANVIL', name: 'Smith\'s Anvil', description: 'A heavy iron anvil with a distinctive horn for shaping metal.', emoji: '🔨', rarity: 'Uncommon', value: 80, weight: 50.0, wearable: false, stackable: false, attack: 0, sustenance: 0, wieldable: false, throwable: false, craftingValue: 15, category: 'Tool', material: 'Iron' },
    FORGE_HEARTH: { baseId: 'FORGE_HEARTH', name: 'Forge Hearth', description: 'A stone-lined hearth for heating metal to forging temperature.', emoji: '🔥', rarity: 'Rare', value: 200, weight: 100.0, wearable: false, stackable: false, attack: 0, sustenance: 0, wieldable: false, throwable: false, craftingValue: 25, category: 'Tool' },
    TONGS: { baseId: 'TONGS', name: 'Blacksmith\'s Tongs', description: 'Long-handled tongs for gripping hot metal during forging.', emoji: '🔧', rarity: 'Common', value: 15, weight: 2.0, wearable: false, stackable: false, attack: 2, sustenance: 0, wieldable: true, throwable: false, craftingValue: 5, category: 'Tool', material: 'Iron', equipmentSlot: 'main_hand' },
    STONE_CHISEL: { baseId: 'STONE_CHISEL', name: 'Stone Chisel', description: 'A sharp steel chisel for carving stone and shaping masonry.', emoji: '🔧', rarity: 'Common', value: 8, weight: 0.8, wearable: false, stackable: false, attack: 2, sustenance: 0, wieldable: true, throwable: false, craftingValue: 4, category: 'Tool', material: 'Steel', equipmentSlot: 'main_hand' },

    // --- AGRICULTURAL & FARMING ---
    IRON_PLOW: { baseId: 'IRON_PLOW', name: 'Iron Plow', description: 'A heavy plow with iron share for breaking tough soil.', emoji: '🚜', rarity: 'Uncommon', value: 60, weight: 25.0, wearable: false, stackable: false, attack: 0, sustenance: 0, wieldable: false, throwable: false, craftingValue: 12, category: 'Tool', material: 'Iron' },
    GRAIN_SCYTHE: { baseId: 'GRAIN_SCYTHE', name: 'Grain Scythe', description: 'A long curved blade mounted on a wooden handle for cutting grain.', emoji: '🌾', rarity: 'Common', value: 25, weight: 3.0, wearable: false, stackable: false, attack: 4, sustenance: 0, wieldable: true, throwable: false, craftingValue: 6, category: 'Tool', material: 'Steel', equipmentSlot: 'main_hand' },
    HARVEST_SICKLE: { baseId: 'HARVEST_SICKLE', name: 'Harvest Sickle', description: 'A curved blade for cutting grain stalks close to the ground.', emoji: '🌾', rarity: 'Common', value: 12, weight: 1.5, wearable: false, stackable: false, attack: 3, sustenance: 0, wieldable: true, throwable: false, craftingValue: 4, category: 'Tool', material: 'Iron', equipmentSlot: 'main_hand' },
    GRAIN_FLAIL: { baseId: 'GRAIN_FLAIL', name: 'Grain Flail', description: 'Two wooden sticks connected by leather for threshing grain.', emoji: '🌾', rarity: 'Common', value: 8, weight: 2.0, wearable: false, stackable: false, attack: 3, sustenance: 0, wieldable: true, throwable: false, craftingValue: 3, category: 'Tool', material: 'Wood', equipmentSlot: 'main_hand' },
    
    // --- TEXTILE & CLOTHING PRODUCTION ---
    SPINNING_WHEEL: { baseId: 'SPINNING_WHEEL', name: 'Spinning Wheel', description: 'A wooden wheel for spinning fiber into thread.', emoji: '🎡', rarity: 'Uncommon', value: 45, weight: 15.0, wearable: false, stackable: false, attack: 0, sustenance: 0, wieldable: false, throwable: false, craftingValue: 10, category: 'Tool', material: 'Wood' },
    WEAVING_LOOM: { baseId: 'WEAVING_LOOM', name: 'Weaving Loom', description: 'A wooden frame for weaving thread into cloth.', emoji: '🧵', rarity: 'Uncommon', value: 65, weight: 20.0, wearable: false, stackable: false, attack: 0, sustenance: 0, wieldable: false, throwable: false, craftingValue: 12, category: 'Tool', material: 'Wood' },
    WOOL_CARDERS: { baseId: 'WOOL_CARDERS', name: 'Wool Cards', description: 'Two brushes with wire teeth for combing wool fiber.', emoji: '🧽', rarity: 'Common', value: 10, weight: 1.0, wearable: false, stackable: false, attack: 1, sustenance: 0, wieldable: true, throwable: false, craftingValue: 3, category: 'Tool', material: 'Wood' },
    SPINDLE: { baseId: 'SPINDLE', name: 'Drop Spindle', description: 'A wooden shaft with a weighted whorl for spinning fiber.', emoji: '🪡', rarity: 'Common', value: 3, weight: 0.5, wearable: false, stackable: false, attack: 1, sustenance: 0, wieldable: true, throwable: true, craftingValue: 2, category: 'Tool', material: 'Wood', equipmentSlot: 'main_hand' },

    // --- FOOD PROCESSING ---
    GRAIN_QUERN: { baseId: 'GRAIN_QUERN', name: 'Hand Quern', description: 'Two circular stones for grinding grain into flour by hand.', emoji: '🗿', rarity: 'Common', value: 20, weight: 15.0, wearable: false, stackable: false, attack: 0, sustenance: 0, wieldable: false, throwable: false, craftingValue: 8, category: 'Tool', material: 'Stone' },
    BUTTER_CHURN: { baseId: 'BUTTER_CHURN', name: 'Butter Churn', description: 'A wooden barrel with plunger for churning cream into butter.', emoji: '🥛', rarity: 'Common', value: 18, weight: 8.0, wearable: false, stackable: false, attack: 0, sustenance: 0, wieldable: false, throwable: false, craftingValue: 6, category: 'Tool', material: 'Wood' },
    CHEESE_PRESS: { baseId: 'CHEESE_PRESS', name: 'Cheese Press', description: 'A wooden frame for pressing whey from fresh cheese curds.', emoji: '🧀', rarity: 'Uncommon', value: 30, weight: 12.0, wearable: false, stackable: false, attack: 0, sustenance: 0, wieldable: false, throwable: false, craftingValue: 8, category: 'Tool', material: 'Wood' },

    // --- HISTORICAL FOODS & INGREDIENTS ---
    BARLEY: { baseId: 'BARLEY', name: 'Barley Grain', description: 'Hardy grain used for bread, porridge, and brewing ale.', emoji: '🌾', rarity: 'Common', value: 1, weight: 0.5, wearable: false, stackable: true, attack: 0, sustenance: 8, wieldable: false, throwable: false, craftingValue: 1, category: 'Food' },
    RYE: { baseId: 'RYE', name: 'Rye Grain', description: 'Dark grain that grows in poor soil, used for dense bread.', emoji: '🌾', rarity: 'Common', value: 1, weight: 0.4, wearable: false, stackable: true, attack: 0, sustenance: 10, wieldable: false, throwable: false, craftingValue: 1, category: 'Food' },
    MILLET: { baseId: 'MILLET', name: 'Millet Seeds', description: 'Small round seeds cultivated in dry regions.', emoji: '🌾', rarity: 'Common', value: 2, weight: 0.3, wearable: false, stackable: true, attack: 0, sustenance: 7, wieldable: false, throwable: false, craftingValue: 1, category: 'Food' },
    PEAS: { baseId: 'PEAS', name: 'Dried Peas', description: 'Protein-rich legumes, often made into porridge.', emoji: '🟢', rarity: 'Common', value: 2, weight: 0.4, wearable: false, stackable: true, attack: 0, sustenance: 12, wieldable: false, throwable: false, craftingValue: 1, category: 'Food' },
    LENTILS: { baseId: 'LENTILS', name: 'Lentils', description: 'Small brown legumes, a staple protein for the poor.', emoji: '🟤', rarity: 'Common', value: 3, weight: 0.4, wearable: false, stackable: true, attack: 0, sustenance: 14, wieldable: false, throwable: false, craftingValue: 1, category: 'Food' },
    SALT_PORK: { baseId: 'SALT_PORK', name: 'Salt Pork', description: 'Pork preserved in salt brine, essential for long voyages.', emoji: '🥓', rarity: 'Common', value: 8, weight: 2.0, wearable: false, stackable: true, attack: 0, sustenance: 25, wieldable: false, throwable: false, craftingValue: 2, category: 'Food' },
    SMOKED_FISH: { baseId: 'SMOKED_FISH', name: 'Smoked Fish', description: 'Fish preserved by smoking over a wood fire.', emoji: '🐟', rarity: 'Common', value: 6, weight: 1.5, wearable: false, stackable: true, attack: 0, sustenance: 20, wieldable: false, throwable: false, craftingValue: 2, category: 'Food' },

    // --- Combat Consumables ---
    HEALING_POTION: { baseId: 'HEALING_POTION', name: 'Healing Potion', description: 'A simple potion that restores a small amount of health.', emoji: '🧪', rarity: 'Uncommon', value: 25, weight: 0.5, wearable: false, stackable: true, attack: 0, sustenance: 25, wieldable: false, throwable: false, craftingValue: 5, category: 'Consumable' },
    SMALL_BOMB: { baseId: 'SMALL_BOMB', name: 'Small Bomb', description: 'A small, explosive device. Deals damage to the opponent.', emoji: '💣', rarity: 'Rare', value: 40, weight: 1.0, wearable: false, stackable: true, attack: 0, sustenance: 0, wieldable: false, throwable: true, craftingValue: 7, category: 'Consumable', damage: 20 },
    REFRESHING_HERB: { baseId: 'REFRESHING_HERB', name: 'Refreshing Herb', description: 'A fragrant herb that restores some fatigue.', emoji: '🌿', rarity: 'Uncommon', value: 15, weight: 0.1, wearable: false, stackable: true, attack: 0, sustenance: 5, fatigueEffect: 10, wieldable: false, throwable: false, craftingValue: 4, category: 'Consumable' },
    SCROLL_OF_KNOWLEDGE: { baseId: 'SCROLL_OF_KNOWLEDGE', name: 'Scroll of Knowledge', description: 'A magical scroll that imparts a small amount of worldly experience.', emoji: '📜', rarity: 'Rare', value: 100, weight: 0.1, wearable: false, stackable: false, attack: 0, sustenance: 0, xpEffect: 15, wieldable: false, throwable: false, craftingValue: 8, category: 'Consumable' },

    // --- Common Forage ---
    WILD_BERRIES: { baseId: 'WILD_BERRIES', name: 'Wild Berries', description: 'A handful of wild, edible berries.', emoji: '🍓', rarity: 'Common', value: 1, weight: 0.2, wearable: false, stackable: true, attack: 0, sustenance: 5, fatigueEffect: 1, wieldable: false, throwable: false, craftingValue: 1, category: 'Food' },
    MUSHROOM: { baseId: 'MUSHROOM', name: 'Edible Mushroom', description: 'A common, earthy mushroom.', emoji: '🍄', rarity: 'Common', value: 1, weight: 0.1, wearable: false, stackable: true, attack: 0, sustenance: 2, wieldable: false, throwable: false, craftingValue: 1, category: 'Food' },
    VINE: { baseId: 'VINE', name: 'Tough Vine', description: 'A long, fibrous vine. Could be used to make rope.', emoji: '🌿', rarity: 'Common', value: 1, weight: 0.4, wearable: false, stackable: true, attack: 0, sustenance: 0, wieldable: false, throwable: false, craftingValue: 2, category: 'Material' },
    BIRDS_NEST: { baseId: 'BIRDS_NEST', name: 'Bird\'s Nest', description: 'A small, abandoned bird\'s nest made of twigs and mud.', emoji: '🐦', rarity: 'Uncommon', value: 1, weight: 0.2, wearable: false, stackable: false, attack: 0, sustenance: 0, wieldable: false, throwable: false, craftingValue: 1, category: 'Material' },
    PINE_CONE: { baseId: 'PINE_CONE', name: 'Pine Cone', description: 'A woody cone from a pine tree, good for tinder.', emoji: '🌲', rarity: 'Common', value: 0, weight: 0.1, wearable: false, stackable: true, attack: 0, sustenance: 0, wieldable: false, throwable: false, craftingValue: 1, category: 'Material' },
    
    // New Forage Items
    ACORNS: { baseId: 'ACORNS', name: 'Handful of Acorns', description: 'Acorns from an oak tree. Bitter, but can be made edible.', emoji: '🌰', rarity: 'Common', value: 1, weight: 0.3, wearable: false, stackable: true, attack: 0, sustenance: 1, wieldable: false, throwable: true, craftingValue: 1, category: 'Food' },
    TREE_BARK: { baseId: 'TREE_BARK', name: 'Tree Bark', description: 'A strip of tree bark. Can be used for tinder or cordage.', emoji: '🪵', rarity: 'Junk', value: 0, weight: 0.2, wearable: false, stackable: true, attack: 0, sustenance: 0, wieldable: false, throwable: false, craftingValue: 1, category: 'Material' },
    PINE_RESIN: { baseId: 'PINE_RESIN', name: 'Pine Resin', description: 'A sticky, fragrant resin from a pine tree. Useful for waterproofing or as an adhesive.', emoji: '💧', rarity: 'Uncommon', value: 4, weight: 0.1, wearable: false, stackable: true, attack: 0, sustenance: 0, wieldable: false, throwable: false, craftingValue: 3, category: 'Material' },
    HERB_BUNDLE: { baseId: 'HERB_BUNDLE', name: 'Herb Bundle', description: 'A bundle of common, fragrant herbs.', emoji: '🌿', rarity: 'Common', value: 2, weight: 0.1, wearable: false, stackable: true, attack: 0, sustenance: 0, fatigueEffect: 2, wieldable: false, throwable: false, craftingValue: 2, category: 'Food' },
    MEDICINAL_HERBS: { baseId: 'MEDICINAL_HERBS', name: 'Medicinal Herbs', description: 'A collection of rare herbs known for their healing properties.', emoji: '🌿', rarity: 'Rare', value: 10, weight: 0.1, wearable: false, stackable: true, attack: 0, sustenance: 2, fatigueEffect: 5, wieldable: false, throwable: false, craftingValue: 5, category: 'Material' },
    CACTUS_FRUIT: { baseId: 'CACTUS_FRUIT', name: 'Cactus Fruit', description: 'A juicy, sweet fruit from a cactus. Provides both food and water.', emoji: '🌵', rarity: 'Uncommon', value: 3, weight: 0.3, wearable: false, stackable: true, attack: 0, sustenance: 8, fatigueEffect: 3, wieldable: false, throwable: false, craftingValue: 1, category: 'Food' },
    STRANGE_FRUIT: { baseId: 'STRANGE_FRUIT', name: 'Strange Fruit', description: 'A bizarre, brightly colored fruit. You\'re not sure if it\'s edible.', emoji: '🥭', rarity: 'Rare', value: 7, weight: 0.4, wearable: false, stackable: true, attack: 0, sustenance: 10, fatigueEffect: -2, xpEffect: 5, wieldable: false, throwable: true, craftingValue: 3, category: 'Food' },
    
    // --- Rare/Ultra-Rare Forage ---
    GLOWING_MOSS: { baseId: 'GLOWING_MOSS', name: 'Glowing Moss', description: 'Moss that emits a faint, eerie light.', emoji: '✨', rarity: 'Ultra-rare', value: 20, weight: 0.1, wearable: false, stackable: true, attack: 0, sustenance: 0, wieldable: false, throwable: false, craftingValue: 7, category: 'Material' },
    OWL_FEATHER: { baseId: 'OWL_FEATHER', name: 'Owl Feather', description: 'A large, silent feather from an owl. Valued by fletchers and mystics.', emoji: '🪶', rarity: 'Ultra-rare', value: 15, weight: 0.1, wearable: false, stackable: true, attack: 0, sustenance: 0, wieldable: false, throwable: false, craftingValue: 6, category: 'Material' },
    
    // --- Animal Products ---
    BEEF: { baseId: 'BEEF', name: 'Beef', description: 'A hearty slab of cow meat.', emoji: '🥩', rarity: 'Common', value: 7, weight: 2.0, wearable: false, stackable: false, attack: 0, sustenance: 35, fatigueEffect: 5, wieldable: false, throwable: false, craftingValue: 1, category: 'Food' },
    COW_HIDE: { baseId: 'COW_HIDE', name: 'Cow Hide', description: 'The unprocessed hide of a cow.', emoji: '🐄', rarity: 'Common', value: 3, weight: 4.0, wearable: true, stackable: false, attack: 0, sustenance: 0, wieldable: false, throwable: false, craftingValue: 4, category: 'Material', material: 'Hide' },
    VENISON: { baseId: 'VENISON', name: 'Venison', description: 'A hearty slab of deer meat.', emoji: '🥩', rarity: 'Common', value: 8, weight: 2.0, wearable: false, stackable: false, attack: 0, sustenance: 40, fatigueEffect: 5, wieldable: false, throwable: false, craftingValue: 2, category: 'Food' },
    DEER_HIDE: { baseId: 'DEER_HIDE', name: 'Deer Hide', description: 'The unprocessed hide of a deer.', emoji: '🦌', rarity: 'Common', value: 4, weight: 3.0, wearable: true, stackable: false, attack: 0, sustenance: 0, wieldable: false, throwable: false, craftingValue: 6, category: 'Material', material: 'Hide' },
    WOLF_PELT: { baseId: 'WOLF_PELT', name: 'Wolf Pelt', description: 'The thick, grey pelt of a wolf.', emoji: '🐺', rarity: 'Uncommon', value: 15, weight: 2.5, wearable: true, stackable: false, attack: 0, sustenance: 0, wieldable: false, throwable: false, craftingValue: 8, category: 'Material', material: 'Pelt' },
    MEAT: { baseId: 'MEAT', name: 'Chunk of Meat', description: 'A hunk of mystery meat.', emoji: '🍖', rarity: 'Common', value: 5, weight: 2.0, wearable: false, stackable: false, attack: 0, sustenance: 30, fatigueEffect: 2, wieldable: false, throwable: false, craftingValue: 1, category: 'Food' },
    BEAR_HIDE: { baseId: 'BEAR_HIDE', name: 'Bear Hide', description: 'The massive, thick hide of a bear.', emoji: '🐻', rarity: 'Rare', value: 30, weight: 8.0, wearable: true, stackable: false, attack: 0, sustenance: 0, wieldable: false, throwable: false, craftingValue: 9, category: 'Material', material: 'Hide' },
    BEAR_CLAW: { baseId: 'BEAR_CLAW', name: 'Bear Claw', description: 'A large, sharp claw from a bear. Often used in jewelry or as a trophy.', emoji: '🐻', rarity: 'Uncommon', value: 12, weight: 0.2, wearable: false, stackable: true, attack: 2, sustenance: 0, wieldable: true, throwable: false, craftingValue: 4, category: 'Material', equipmentSlot: 'main_hand' },
    FOX_FUR: { baseId: 'FOX_FUR', name: 'Fox Fur', description: 'The soft, reddish fur of a fox.', emoji: '🦊', rarity: 'Uncommon', value: 18, weight: 1.0, wearable: true, stackable: false, attack: 0, sustenance: 0, wieldable: false, throwable: false, craftingValue: 7, category: 'Material', material: 'Fur' },
    TOUGH_HIDE: { baseId: 'TOUGH_HIDE', name: 'Tough Hide', description: 'A thick, durable hide from a hardy beast.', emoji: '🐗', rarity: 'Common', value: 6, weight: 4.0, wearable: true, stackable: false, attack: 0, sustenance: 0, wieldable: false, throwable: false, craftingValue: 5, category: 'Material', material: 'Hide' },
    BOAR_TUSK: { baseId: 'BOAR_TUSK', name: 'Boar Tusk', description: 'A sharp, curved tusk from a wild boar.', emoji: '🐗', rarity: 'Uncommon', value: 8, weight: 0.5, wearable: false, stackable: true, attack: 2, sustenance: 0, wieldable: true, throwable: false, craftingValue: 4, category: 'Material', equipmentSlot: 'main_hand' },
    EAGLE_FEATHER: { baseId: 'EAGLE_FEATHER', name: 'Eagle Feather', description: 'A majestic feather from a great eagle. Highly prized.', emoji: '🦅', rarity: 'Rare', value: 25, weight: 0.1, wearable: false, stackable: true, attack: 0, sustenance: 0, wieldable: false, throwable: false, craftingValue: 8, category: 'Material' },
    MAGIC_FEATHER: { baseId: 'MAGIC_FEATHER', name: 'Magic Feather', description: 'A feather that hums with a faint, magical energy.', emoji: '🪶', rarity: 'Ultra-rare', value: 50, weight: 0.1, wearable: false, stackable: true, attack: 0, sustenance: 0, wieldable: false, throwable: false, craftingValue: 10, category: 'Material' },
    SNAKE_SKIN: { baseId: 'SNAKE_SKIN', name: 'Snake Skin', description: 'The shed skin of a snake.', emoji: '🐍', rarity: 'Uncommon', value: 9, weight: 0.2, wearable: true, stackable: false, attack: 0, sustenance: 0, wieldable: false, throwable: false, craftingValue: 5, category: 'Material', material: 'Skin' },
    VENOM: { baseId: 'VENOM', name: 'Vial of Venom', description: 'A small vial of potent venom.', emoji: '🧪', rarity: 'Rare', value: 35, weight: 0.1, wearable: false, stackable: true, attack: 0, sustenance: 0, wieldable: false, throwable: false, craftingValue: 9, category: 'Material' },
    FISH_MEAT: { baseId: 'FISH_MEAT', name: 'Fish Meat', description: 'A flaky, edible fish.', emoji: '🐟', rarity: 'Common', value: 3, weight: 0.5, wearable: false, stackable: false, attack: 0, sustenance: 10, fatigueEffect: 2, wieldable: false, throwable: false, craftingValue: 1, category: 'Food' },
    BIOLUMINESCENT_GOOP: { baseId: 'BIOLUMINESCENT_GOOP', name: 'Bioluminescent Goop', description: 'A jar of glowing slime from a jellyfish.', emoji: '🧪', rarity: 'Uncommon', value: 8, weight: 0.5, wearable: false, stackable: true, attack: 0, sustenance: 0, wieldable: false, throwable: true, craftingValue: 5, category: 'Material' },
    WHALE_BLUBBER: { baseId: 'WHALE_BLUBBER', name: 'Whale Blubber', description: 'A large piece of whale blubber, excellent for lamp oil.', emoji: '🐋', rarity: 'Rare', value: 50, weight: 10.0, wearable: false, stackable: false, attack: 0, sustenance: 0, wieldable: false, throwable: false, craftingValue: 6, category: 'Material' },
    AMBERGRIS: { baseId: 'AMBERGRIS', name: 'Ambergris', description: 'A waxy substance from a whale, highly prized in perfumery.', emoji: '🌟', rarity: 'Ultra-rare', value: 200, weight: 1.0, wearable: false, stackable: false, attack: 0, sustenance: 0, wieldable: false, throwable: false, craftingValue: 10, category: 'Special' },

    // --- New Crop Items ---
    WHEAT: { baseId: 'WHEAT', name: 'Sheaf of Wheat', description: 'Grain, ready for milling.', emoji: '🌾', rarity: 'Common', value: 2, weight: 1.0, wearable: false, stackable: true, attack: 0, sustenance: 1, wieldable: false, throwable: false, craftingValue: 2, category: 'Material' },
    BARLEY: { baseId: 'BARLEY', name: 'Bag of Barley', description: 'Hardy grain used for bread and ale.', emoji: '🌾', rarity: 'Common', value: 2, weight: 1.0, wearable: false, stackable: true, attack: 0, sustenance: 1, wieldable: false, throwable: false, craftingValue: 2, category: 'Material' },
    CORN: { baseId: 'CORN', name: 'Ear of Corn', description: 'An ear of sweet, golden corn.', emoji: '🌽', rarity: 'Common', value: 3, weight: 0.8, wearable: false, stackable: true, attack: 0, sustenance: 4, wieldable: false, throwable: false, craftingValue: 2, category: 'Food', culturalAvailability: ['SOUTH_AMERICAN', 'NORTH_AMERICAN_PRE_COLUMBIAN'], eraAvailability: { startYear: -8000, endYear: 1492 } },
    RICE: { baseId: 'RICE', name: 'Bag of Rice', description: 'A small bag of uncooked rice.', emoji: '🍚', rarity: 'Common', value: 2, weight: 1.2, wearable: false, stackable: true, attack: 0, sustenance: 1, wieldable: false, throwable: false, craftingValue: 1, category: 'Material' },
    POTATO: { baseId: 'POTATO', name: 'Potato', description: 'A humble but filling potato.', emoji: '🥔', rarity: 'Common', value: 1, weight: 0.3, wearable: false, stackable: true, attack: 0, sustenance: 15, wieldable: false, throwable: true, craftingValue: 1, category: 'Food', culturalAvailability: ['SOUTH_AMERICAN'], eraAvailability: { startYear: -8000, endYear: 1536 } },
    YAM: { baseId: 'YAM', name: 'Yam', description: 'A starchy tuber, a staple in tropical regions.', emoji: '🍠', rarity: 'Common', value: 2, weight: 0.9, wearable: false, stackable: true, attack: 0, sustenance: 12, wieldable: false, throwable: false, craftingValue: 1, category: 'Food' },
    OLIVES: { baseId: 'OLIVES', name: 'Jar of Olives', description: 'Cured olives, ready for pressing into oil.', emoji: '🫒', rarity: 'Common', value: 5, weight: 0.7, wearable: false, stackable: true, attack: 0, sustenance: 2, wieldable: false, throwable: false, craftingValue: 4, category: 'Material' },
    GRAPES: { baseId: 'GRAPES', name: 'Bunch of Grapes', description: 'Sweet grapes, perfect for eating or making wine.', emoji: '🍇', rarity: 'Common', value: 4, weight: 0.5, wearable: false, stackable: true, attack: 0, sustenance: 5, wieldable: false, throwable: false, craftingValue: 3, category: 'Food' },
    COTTON: { baseId: 'COTTON', name: 'Bale of Cotton', description: 'Raw cotton, ready for spinning into thread.', emoji: '☁️', rarity: 'Common', value: 4, weight: 2.0, wearable: false, stackable: true, attack: 0, sustenance: 0, wieldable: false, throwable: false, craftingValue: 5, category: 'Material' },
    SUGAR_CANE: { baseId: 'SUGAR_CANE', name: 'Stalk of Sugar Cane', description: 'A sweet stalk that can be processed into sugar.', emoji: '🎋', rarity: 'Common', value: 3, weight: 1.5, wearable: false, stackable: true, attack: 0, sustenance: 2, wieldable: false, throwable: false, craftingValue: 3, category: 'Material' },
};

export interface CropDefinition {
    name: string;
    baseId: string;
    zones: CulturalZone[];
    climates: ClimateType[];
    eraStart?: number;
    eraEnd?: number;
}

export const CROPS_DATA: CropDefinition[] = [
    { name: 'Wheat', baseId: 'WHEAT', zones: ['EUROPEAN', 'MENA'], climates: [ClimateType.TEMPERATE, ClimateType.ARID] },
    { name: 'Barley', baseId: 'BARLEY', zones: ['EUROPEAN', 'MENA', 'SOUTH_ASIAN'], climates: [ClimateType.TEMPERATE, ClimateType.ARID, ClimateType.COLD] },
    { name: 'Corn (Maize)', baseId: 'CORN', zones: ['NORTH_AMERICAN_PRE_COLUMBIAN', 'SOUTH_AMERICAN'], climates: [ClimateType.TEMPERATE, ClimateType.SEMITROPICAL, ClimateType.TROPICAL], eraEnd: 1492 },
    { name: 'Corn', baseId: 'CORN', zones: ['EUROPEAN', 'SUB_SAHARAN_AFRICAN', 'EAST_ASIAN', 'SOUTH_ASIAN'], climates: [ClimateType.TEMPERATE, ClimateType.SEMITROPICAL], eraStart: 1492 },
    { name: 'Rice', baseId: 'RICE', zones: ['EAST_ASIAN', 'SOUTH_ASIAN'], climates: [ClimateType.TROPICAL, ClimateType.SEMITROPICAL] },
    { name: 'Potato', baseId: 'POTATO', zones: ['SOUTH_AMERICAN'], climates: [ClimateType.COLD, ClimateType.TEMPERATE], eraEnd: 1536 },
    { name: 'Potato', baseId: 'POTATO', zones: ['EUROPEAN'], climates: [ClimateType.COLD, ClimateType.TEMPERATE], eraStart: 1536 },
    { name: 'Yam', baseId: 'YAM', zones: ['SUB_SAHARAN_AFRICAN', 'OCEANIA', 'SOUTH_AMERICAN'], climates: [ClimateType.TROPICAL] },
    { name: 'Olive Grove', baseId: 'OLIVES', zones: ['EUROPEAN', 'MENA'], climates: [ClimateType.TEMPERATE, ClimateType.SEMITROPICAL] },
    { name: 'Vineyard', baseId: 'GRAPES', zones: ['EUROPEAN', 'MENA'], climates: [ClimateType.TEMPERATE, ClimateType.ARID] },
    { name: 'Cotton', baseId: 'COTTON', zones: ['SOUTH_ASIAN', 'MENA', 'SOUTH_AMERICAN'], climates: [ClimateType.ARID, ClimateType.TROPICAL, ClimateType.SEMITROPICAL] },
    { name: 'Sugar Cane', baseId: 'SUGAR_CANE', zones: ['SOUTH_ASIAN', 'OCEANIA', 'SUB_SAHARAN_AFRICAN', 'SOUTH_AMERICAN'], climates: [ClimateType.TROPICAL] },
];