/**
 * Direct mapping of professions to their most appropriate game modes
 * Used to automatically suggest game modes based on player profession
 */

export const PROFESSION_GAME_MODES: Record<string, string> = {
  // ============================================
  // SURVIVAL MODE - Existential threats, refugees, disasters
  // ============================================
  'refugee': 'survival',
  'survivor': 'survival',
  'exile': 'survival',
  'displaced person': 'survival',
  'fugitive': 'survival',
  'enslaved person': 'survival',
  'slave': 'survival',
  'war captive': 'survival',
  'beggar': 'survival',
  'indentured servant': 'survival',
  'indentured labourer': 'survival',
  'mita worker': 'survival',
  'guano digger': 'survival',
  'coal miner': 'survival',
  'miner': 'survival',
  
  // ============================================
  // EXPLORATION MODE - Discovery, travel, navigation
  // ============================================
  'explorer': 'exploration',
  'wanderer': 'exploration',
  'scout': 'exploration',
  'navigator': 'exploration',
  'cartographer': 'exploration',
  'master navigator': 'exploration',
  'coureur de bois': 'exploration',
  'mountain man': 'exploration',
  'fur trapper': 'exploration',
  'voyageur': 'exploration',
  'surveyor': 'exploration',
  'gold prospector': 'exploration',
  'hunter': 'exploration',
  'buffalo hunter': 'exploration',
  'whale hunter': 'exploration',
  'whaler': 'exploration',
  
  // ============================================
  // COMMERCE MODE - Trade, business, merchants
  // ============================================
  'merchant': 'commerce',
  'trader': 'commerce',
  'shopkeeper': 'commerce',
  'small business owner': 'commerce',
  'bank president': 'commerce',
  'banker': 'commerce',
  'investment banker': 'commerce',
  'ceo': 'commerce',
  'tech ceo': 'commerce',
  'factory owner': 'commerce',
  'ship owner': 'commerce',
  'salesman': 'commerce',
  'market vendor': 'commerce',
  'street vendor': 'commerce',
  'peddler': 'commerce',
  'carpet merchant': 'commerce',
  'silk merchant': 'commerce',
  'spice merchant': 'commerce',
  'salt merchant': 'commerce',
  'rice merchant': 'commerce',
  'wool merchant': 'commerce',
  'tea trader': 'commerce',
  'silk trader': 'commerce',
  'spice trader': 'commerce',
  'gold trader': 'commerce',
  'salt trader': 'commerce',
  'silk road trader': 'commerce',
  'slave trader': 'commerce',
  'money changer': 'commerce',
  'coffee planter': 'commerce',
  'trading post clerk': 'commerce',
  'trading post worker': 'commerce',
  'portuguese factor': 'commerce',
  'mestizo trader': 'commerce',
  'tavern keeper': 'commerce',
  'innkeeper': 'commerce',
  'coffeehouse keeper': 'commerce',
  'tea house servant': 'commerce',
  'real estate agent': 'commerce',
  'marketing manager': 'commerce',
  
  // ============================================
  // SCHOLARSHIP MODE - Knowledge, teaching, research
  // ============================================
  'scholar': 'scholarship',
  'scribe': 'scholarship',
  'teacher': 'scholarship',
  'university professor': 'scholarship',
  'village teacher': 'scholarship',
  'mission teacher': 'scholarship',
  'librarian': 'scholarship',
  'historian': 'scholarship',
  'mathematician': 'scholarship',
  'astronomer': 'scholarship',
  'astrologer': 'scholarship',
  'alchemist': 'scholarship',
  'philosopher': 'scholarship',
  'islamic scholar': 'scholarship',
  'buddhist monk': 'scholarship',
  'monk': 'scholarship',
  'zen master': 'scholarship',
  'quranic teacher': 'scholarship',
  'court scribe': 'scholarship',
  'calligrapher': 'scholarship',
  'illuminator': 'scholarship',
  'printer': 'scholarship',
  'woodblock printer': 'scholarship',
  'newspaper editor': 'scholarship',
  'journalist': 'scholarship',
  'content creator': 'scholarship',
  'architect': 'scholarship',
  'civil engineer': 'scholarship',
  'engineer': 'scholarship',
  
  // ============================================
  // LEADERSHIP MODE - Governance, command, nobility
  // ============================================
  'chief': 'leadership',
  'king': 'leadership',
  'queen mother': 'leadership',
  'sultan': 'leadership',
  'sapa inca': 'leadership',
  'oba': 'leadership',
  'paramount chief': 'leadership',
  'village chief': 'leadership',
  'war chief': 'leadership',
  'war leader': 'leadership',
  'governor': 'leadership',
  'colonial governor': 'leadership',
  'spanish viceroy': 'leadership',
  'provincial governor': 'leadership',
  'local governor': 'leadership',
  'politician': 'leadership',
  'president': 'leadership',
  'mayor': 'leadership',
  'lord': 'leadership',
  'lady': 'leadership',
  'knight': 'leadership',
  'samurai': 'leadership',
  'centurion': 'leadership',
  'cavalry': 'leadership',
  'infantry': 'leadership',
  'legionary': 'leadership',
  'auxiliary': 'leadership',
  'janissary': 'leadership',
  'ashigaru': 'leadership',
  'mercenary': 'leadership',
  'landowner': 'leadership',
  'encomendero': 'leadership',
  'curaca': 'leadership',
  'coya': 'leadership',
  'high priest': 'leadership',
  'priest-king': 'leadership',
  'bishop': 'leadership',
  
  // ============================================
  // DIPLOMACY MODE - Negotiation, cultural bridge-building
  // ============================================
  'diplomat': 'diplomacy',
  'ambassador': 'diplomacy',
  'envoy': 'diplomacy',
  'emissary': 'diplomacy',
  'interpreter': 'diplomacy',
  'translator': 'diplomacy',
  'court interpreter': 'diplomacy',
  'negotiator': 'diplomacy',
  'peace broker': 'diplomacy',
  'courier': 'diplomacy',
  'chasqui runner': 'diplomacy',
  
  // ============================================
  // HEALER MODE - Medicine, health, healing
  // ============================================
  'healer': 'healer',
  'physician': 'healer',
  'doctor': 'healer',
  'surgeon': 'healer',
  'nurse': 'healer',
  'midwife': 'healer',
  'apothecary': 'healer',
  'herbalist': 'healer',
  'medicine gatherer': 'healer',
  'barber surgeon': 'healer',
  'plague doctor': 'healer',
  'shaman': 'healer',
  'witch': 'healer',
  'spirit medium': 'healer',
  'pharmacist': 'healer',
  'physical therapist': 'healer',
  'dental hygienist': 'healer',
  'wet nurse': 'healer',
  
  // ============================================
  // LEGAL MODE - Justice, law, moral dilemmas
  // ============================================
  'judge': 'legal',
  'lawyer': 'legal',
  'magistrate': 'legal',
  'county magistrate': 'legal',
  'local magistrate': 'legal',
  'bailiff': 'legal',
  'executioner': 'legal',
  'police officer': 'legal',
  'police constable': 'legal',
  'city guard': 'legal',
  'guard': 'legal',
  'border guard': 'legal',
  'native constable': 'legal',
  'security guard': 'legal',
  'watchman': 'legal',
  
  // ============================================
  // LIVELIHOOD MODE - Daily work, crafts, ordinary professions
  // ============================================
  // Farmers and Agricultural Workers
  'farmer': 'livelihood',
  'farm worker': 'livelihood',
  'rice farmer': 'livelihood',
  'corn farmer': 'livelihood',
  'cotton farmer': 'livelihood',
  'tobacco farmer': 'livelihood',
  'vegetable farmer': 'livelihood',
  'millet farmer': 'livelihood',
  'maize farmer': 'livelihood',
  'terrace farmer': 'livelihood',
  'chinampero': 'livelihood',
  'cash crop farmer': 'livelihood',
  'cacao grower': 'livelihood',
  'tea grower': 'livelihood',
  'spice grower': 'livelihood',
  'coca cultivator': 'livelihood',
  'breadfruit cultivator': 'livelihood',
  'taro farmer': 'livelihood',
  'date farmer': 'livelihood',
  'reservation farmer': 'livelihood',
  'habitant': 'livelihood',
  'homesteader': 'livelihood',
  'sod buster': 'livelihood',
  'plantation worker': 'livelihood',
  'hacienda peon': 'livelihood',
  'serf': 'livelihood',
  
  // Herders and Animal Workers
  'shepherd': 'livelihood',
  'cowherd': 'livelihood',
  'goat herder': 'livelihood',
  'cattle herder': 'livelihood',
  'camel herder': 'livelihood',
  'llama herder': 'livelihood',
  'duck herder': 'livelihood',
  'horse trainer': 'livelihood',
  'vaquero': 'livelihood',
  'cowboy': 'livelihood',
  'ranchero': 'livelihood',
  
  // Craftspeople and Artisans
  'blacksmith': 'livelihood',
  'carpenter': 'livelihood',
  'weaver': 'livelihood',
  'potter': 'livelihood',
  'jeweler': 'livelihood',
  'goldsmith': 'livelihood',
  'silversmith': 'livelihood',
  'swordsmith': 'livelihood',
  'gunsmith': 'livelihood',
  'weapon smith': 'livelihood',
  'metalsmith': 'livelihood',
  'metalworker': 'livelihood',
  'bronze caster': 'livelihood',
  'brass caster': 'livelihood',
  'iron smelter': 'livelihood',
  'glassblower': 'livelihood',
  'stonemason': 'livelihood',
  'mason': 'livelihood',
  'stone carver': 'livelihood',
  'jade carver': 'livelihood',
  'bone carver': 'livelihood',
  'ivory carver': 'livelihood',
  'obsidian knapper': 'livelihood',
  'toolmaker': 'livelihood',
  'flintknapper': 'livelihood',
  'sculptor': 'livelihood',
  'painter': 'livelihood',
  'court painter': 'livelihood',
  'cave painter': 'livelihood',
  'rock painter': 'livelihood',
  'tattoo artist': 'livelihood',
  'cobbler': 'livelihood',
  'tanner': 'livelihood',
  'hide processor': 'livelihood',
  'hide dresser': 'livelihood',
  'skin dresser': 'livelihood',
  'dyer': 'livelihood',
  'textile dyer': 'livelihood',
  'fuller': 'livelihood',
  'silk weaver': 'livelihood',
  'tapestry weaver': 'livelihood',
  'textile weaver': 'livelihood',
  'carpet weaver': 'livelihood',
  'carpet maker': 'livelihood',
  'basket maker': 'livelihood',
  'wampum maker': 'livelihood',
  'bead maker': 'livelihood',
  'feather worker': 'livelihood',
  'featherworker': 'livelihood',
  'lacquerware maker': 'livelihood',
  'lacquerware artisan': 'livelihood',
  'porcelain potter': 'livelihood',
  'pottery maker': 'livelihood',
  'tile maker': 'livelihood',
  'brick maker': 'livelihood',
  'bell founder': 'livelihood',
  'clockmaker': 'livelihood',
  'instrument maker': 'livelihood',
  'lens grinder': 'livelihood',
  'shipwright': 'livelihood',
  'canoe builder': 'livelihood',
  'canoe carver': 'livelihood',
  'totem carver': 'livelihood',
  'seal carver': 'livelihood',
  'paper maker': 'livelihood',
  'inkstick maker': 'livelihood',
  'fan maker': 'livelihood',
  'tatami maker': 'livelihood',
  'bamboo worker': 'livelihood',
  'cedar worker': 'livelihood',
  'woodcutter': 'livelihood',
  'charcoal maker': 'livelihood',
  'charcoal burner': 'livelihood',
  'tapa maker': 'livelihood',
  'tipi maker': 'livelihood',
  'traditional crafter': 'livelihood',
  
  // Food Preparation and Service
  'baker': 'livelihood',
  'butcher': 'livelihood',
  'cook': 'livelihood',
  'brewer': 'livelihood',
  'vintner': 'livelihood',
  'miller': 'livelihood',
  'tofu maker': 'livelihood',
  'noodle maker': 'livelihood',
  'waiter': 'livelihood',
  'bartender': 'livelihood',
  'barista': 'livelihood',
  'kava preparer': 'livelihood',
  'palm wine tapper': 'livelihood',
  
  // Transportation and Logistics
  'sailor': 'livelihood',
  'navy sailor': 'livelihood',
  'boatman': 'livelihood',
  'canoe paddler': 'livelihood',
  'chariot driver': 'livelihood',
  'coach driver': 'livelihood',
  'stagecoach driver': 'livelihood',
  'muleteer': 'livelihood',
  'caravan guide': 'livelihood',
  'taxi driver': 'livelihood',
  'cab driver': 'livelihood',
  'uber driver': 'livelihood',
  'truck driver': 'livelihood',
  'delivery driver': 'livelihood',
  'streetcar conductor': 'livelihood',
  'railway worker': 'livelihood',
  'railroad worker': 'livelihood',
  'railway engineer': 'livelihood',
  'railway investor': 'livelihood',
  'fireman': 'livelihood',
  'porter': 'livelihood',
  'stevedore': 'livelihood',
  'dock worker': 'livelihood',
  'docker': 'livelihood',
  'warehouse worker': 'livelihood',
  'rickshaw puller': 'livelihood',
  
  // Industrial and Factory Workers
  'factory worker': 'livelihood',
  'mill worker': 'livelihood',
  'textile worker': 'livelihood',
  'mine worker': 'livelihood',
  'smelter worker': 'livelihood',
  'oil worker': 'livelihood',
  'nitrate worker': 'livelihood',
  'rubber tapper': 'livelihood',
  'machinist': 'livelihood',
  'welder': 'livelihood',
  'mechanic': 'livelihood',
  'construction worker': 'livelihood',
  'builder': 'livelihood',
  'master builder': 'livelihood',
  
  // Service and Clerical Workers
  'secretary': 'livelihood',
  'clerk': 'livelihood',
  'accountant': 'livelihood',
  'office manager': 'livelihood',
  'telephone operator': 'livelihood',
  'telegraph operator': 'livelihood',
  'postal worker': 'livelihood',
  'census taker': 'livelihood',
  'tax collector': 'livelihood',
  'tax assessor': 'livelihood',
  'tax farmer': 'livelihood',
  'tribute collector': 'livelihood',
  'quipu keeper': 'livelihood',
  'granary keeper': 'livelihood',
  'temple keeper': 'livelihood',
  'fire keeper': 'livelihood',
  
  // Domestic and Personal Service
  'domestic servant': 'livelihood',
  'washerwoman': 'livelihood',
  'seamstress': 'livelihood',
  'governess': 'livelihood',
  'boarding school student': 'livelihood',
  'janitor': 'livelihood',
  'street sweeper': 'livelihood',
  'chimney sweep': 'livelihood',
  'rag picker': 'livelihood',
  'water carrier': 'livelihood',
  'gas lamp lighter': 'livelihood',
  'bathhouse attendant': 'livelihood',
  'hair stylist': 'livelihood',
  'perfumer': 'livelihood',
  'incense maker': 'livelihood',
  'chandler': 'livelihood',
  
  // Entertainment and Cultural Workers
  'court musician': 'livelihood',
  'dancer': 'livelihood',
  'temple dancer': 'livelihood',
  'jester': 'livelihood',
  'griot': 'livelihood',
  'photographer': 'livelihood',
  
  // Religious Workers (non-leadership)
  'priest': 'livelihood',
  'friar': 'livelihood',
  'nun': 'livelihood',
  'missionary': 'livelihood',
  'pilgrim': 'livelihood',
  'pardoner': 'livelihood',
  'hermit': 'livelihood',
  'ascetic': 'livelihood',
  'hindu priest': 'livelihood',
  'shinto priest': 'livelihood',
  'imam': 'livelihood',
  'muezzin': 'livelihood',
  'temple servant': 'livelihood',
  'oracle': 'livelihood',
  'diviner': 'livelihood',
  'bone oracle': 'livelihood',
  'rain maker': 'livelihood',
  
  // Fishing and Marine Workers
  'fisherman': 'livelihood',
  'fisher': 'livelihood',
  'salmon fisher': 'livelihood',
  'pearl diver': 'livelihood',
  'shell diver': 'livelihood',
  'beche-de-mer diver': 'livelihood',
  'fish weir builder': 'livelihood',
  
  // Gathering and Extraction
  'gatherer': 'livelihood',
  'honey gatherer': 'livelihood',
  'coconut harvester': 'livelihood',
  'tea picker': 'livelihood',
  'silk farmer': 'livelihood',
  'sandalwood cutter': 'livelihood',
  'lumberjack': 'livelihood',
  'maple sugar maker': 'livelihood',
  
  // Modern Service Workers
  'customer service rep': 'livelihood',
  'call center worker': 'livelihood',
  'cashier': 'livelihood',
  'grocery clerk': 'livelihood',
  'hotel clerk': 'livelihood',
  'personal trainer': 'livelihood',
  'handyman': 'livelihood',
  'software developer': 'livelihood',
  'firefighter': 'livelihood',
  
  // Market and Trade Workers (non-merchant)
  'market woman': 'livelihood',
  'flower seller': 'livelihood',
  'cowrie counter': 'livelihood',
  'ship provisioner': 'livelihood',
  
  // Military Support (non-combat)
  'squire': 'livelihood',
  'page': 'livelihood',
  'retainer': 'livelihood',
  'musket bearer': 'livelihood',
  'sepoy': 'livelihood',
  'presidio soldier': 'livelihood',
  
  // Other/Miscellaneous
  'newsboy': 'livelihood',
  'ball court player': 'livelihood',
  'gladiator': 'livelihood',
  'falconer': 'livelihood',
  'cliff dweller': 'livelihood',
  'nomad': 'livelihood',
  'ayllu member': 'livelihood',
  'mission indian': 'livelihood',
  'indian agent': 'livelihood',
  'british engineer': 'livelihood',
  'hut tax payer': 'livelihood',
  'indigenous laborer': 'livelihood',
  'canal worker': 'livelihood',
  'guild master': 'livelihood',
  'village elder': 'livelihood',
  'village headman': 'livelihood',
  'poison maker': 'livelihood',
  'silver miner': 'livelihood',
  'gold worker': 'livelihood',
  'thief': 'livelihood',
  'prostitute': 'livelihood',
  'gentleman': 'livelihood',
  'noblewoman': 'livelihood',
  'porcelain dealer': 'livelihood'
};

/**
 * Get the appropriate game mode for a given profession
 * @param profession The player's profession
 * @returns The suggested game mode ID, defaults to 'livelihood' if not found
 */
export function getProfessionGameMode(profession: string): string {
  if (!profession) return 'livelihood';
  
  // Try exact match first (case-insensitive)
  const normalizedProfession = profession.toLowerCase().trim();
  const exactMatch = PROFESSION_GAME_MODES[normalizedProfession];
  if (exactMatch) return exactMatch;
  
  // Try without common suffixes/prefixes
  const simplifiedProfession = normalizedProfession
    .replace(/^(a |an |the |senior |junior |master |apprentice |chief |head |lead )/, '')
    .replace(/( worker| laborer| assistant| manager| supervisor)$/, '');
  
  const simplifiedMatch = PROFESSION_GAME_MODES[simplifiedProfession];
  if (simplifiedMatch) return simplifiedMatch;
  
  // Default to livelihood mode for unmatched professions
  return 'livelihood';
}