import type { AtlasPlace } from "./types";
import legacy from "./places.generated.json" with { type: "json" };
// Named anchors describe orientation and feel, never an exact street plan.
const p = (
  id: string,
  name: string,
  lon: number,
  lat: number,
  climate: AtlasPlace["climate"],
  water: AtlasPlace["water"],
  culture: AtlasPlace["culture"],
  year: number,
  architecture: AtlasPlace["architecture"],
  aliases: string[] = [],
  settlement: AtlasPlace["settlement"] = "village",
  relief = 0.35,
): AtlasPlace => ({
  id,
  name,
  lon,
  lat,
  climate,
  water,
  culture,
  year,
  architecture,
  aliases,
  settlement,
  relief,
});
const anchors: AtlasPlace[] = [
  p(
    "rome",
    "Rome",
    12.48,
    41.9,
    "mediterranean",
    "river-ns",
    "european",
    100,
    "classical",
    ["roman", "ancient rome", "roma", "tiber", "ostia", "italy"],
    "city",
  ),
  p(
    "umbria",
    "Umbria",
    12.39,
    43.11,
    "mediterranean",
    "river-ns",
    "european",
    100,
    "classical",
    ["umbrian", "perugia", "apennine foothills"],
    "village",
    0.8,
  ),
  p(
    "london",
    "London",
    -0.12,
    51.51,
    "temperate",
    "river-ew",
    "european",
    1590,
    "timber",
    ["elizabethan london", "tudor london", "england", "britain"],
    "city",
    0.15,
  ),
  p(
    "normandy",
    "Normandy",
    -0.37,
    49.18,
    "temperate",
    "river-ns",
    "european",
    1250,
    "timber",
    ["norman", "caen", "rouen", "medieval"],
    "village",
    0.3,
  ),
  p(
    "paris",
    "Paris",
    2.35,
    48.85,
    "temperate",
    "river-ew",
    "european",
    1400,
    "timber",
    ["france"],
    "city",
    0.2,
  ),
  p(
    "athens",
    "Athens",
    23.72,
    37.98,
    "mediterranean",
    "none",
    "european",
    -399,
    "classical",
    ["greece", "greek"],
    "city",
    0.6,
  ),
  p(
    "alexandria",
    "Alexandria",
    29.92,
    31.2,
    "mediterranean",
    "coast-n",
    "north-african-west-asian",
    -249,
    "classical",
    ["hellenistic alexandria", "ptolemaic", "alexandreia"],
    "port",
    0.08,
  ),
  p(
    "nile",
    "Nile valley",
    31.24,
    30.04,
    "arid",
    "river-ns",
    "north-african-west-asian",
    -1299,
    "mudbrick",
    ["egypt", "cairo", "memphis"],
    "village",
    0.12,
  ),
  p(
    "konya",
    "Konya plain",
    32.83,
    37.67,
    "mediterranean",
    "river-ns",
    "north-african-west-asian",
    -6499,
    "mudbrick",
    [
      "neolithic",
      "catalhoyuk",
      "çatalhöyük",
      "anatolia",
      "konya",
      "early farmer",
    ],
    "village",
    0.15,
  ),
  p(
    "mesopotamia",
    "Mesopotamia",
    44.42,
    32.54,
    "arid",
    "river-ns",
    "north-african-west-asian",
    -1999,
    "mudbrick",
    ["babylon", "sumer", "ur", "iraq", "baghdad"],
    "city",
    0.08,
  ),
  p(
    "siberia",
    "Siberian interior",
    104.3,
    52.3,
    "boreal",
    "river-ew",
    "inner-eurasian",
    -14999,
    "timber",
    ["siberia", "siberian", "paleolithic", "palaeolithic", "baikal"],
    "camp",
    0.55,
  ),
  p(
    "mongolia",
    "Mongolian steppe",
    103.8,
    47.5,
    "tundra",
    "river-ew",
    "inner-eurasian",
    1250,
    "timber",
    ["mongolia", "mongolian"],
    "camp",
    0.55,
  ),
  p(
    "beijing",
    "Beijing",
    116.4,
    39.9,
    "temperate",
    "river-ns",
    "east-asian",
    1450,
    "courtyard",
    ["peking", "china", "ming"],
    "city",
    0.1,
  ),
  p(
    "kyoto",
    "Kyoto",
    135.77,
    35.01,
    "monsoon",
    "river-ns",
    "east-asian",
    1200,
    "courtyard",
    ["japan", "heian"],
    "city",
    0.5,
  ),
  p(
    "burma",
    "Burmese interior",
    94.9,
    21.17,
    "monsoon",
    "river-ns",
    "southeast-asian",
    1350,
    "timber",
    ["burma", "burmese", "myanmar", "bagan", "pagan"],
    "village",
    0.35,
  ),
  p(
    "java",
    "Central Java",
    110.2,
    -7.5,
    "monsoon",
    "river-ns",
    "southeast-asian",
    950,
    "timber",
    ["java", "javanese", "indonesia"],
    "village",
    0.7,
  ),
  p(
    "bengal",
    "Bengal delta",
    90.3,
    23.7,
    "monsoon",
    "river-ew",
    "south-asian",
    1500,
    "timber",
    ["bengal", "bangladesh"],
    "village",
    0.05,
  ),
  p(
    "delhi",
    "Delhi",
    77.23,
    28.61,
    "monsoon",
    "river-ns",
    "south-asian",
    1500,
    "courtyard",
    ["india", "hindustan"],
    "city",
    0.2,
  ),
  p(
    "haiti",
    "Haitian countryside",
    -72.28,
    19.05,
    "tropical",
    "river-ew",
    "west-central-african",
    1850,
    "board",
    ["haiti", "haitian", "saint domingue", "saint-domingue", "hispaniola"],
    "farm",
    0.75,
  ),
  p(
    "mexico",
    "Valley of Mexico",
    -99.13,
    19.43,
    "temperate",
    "lake",
    "mesoamerican",
    1450,
    "mudbrick",
    ["mexico", "tenochtitlan", "aztec"],
    "city",
    0.4,
  ),
  p(
    "cusco",
    "Cusco highlands",
    -71.97,
    -13.52,
    "temperate",
    "river-ns",
    "andean",
    1450,
    "mudbrick",
    ["cusco", "cuzco", "peru", "inca"],
    "village",
    0.95,
  ),
  p(
    "amazon",
    "Amazon basin",
    -60.02,
    -3.1,
    "tropical",
    "river-ew",
    "other-indigenous-american",
    1400,
    "timber",
    ["amazon", "amazonian"],
    "village",
    0.1,
  ),
  p(
    "virginia",
    "Virginia countryside",
    -78.3,
    37.6,
    "temperate",
    "river-ew",
    "european",
    1800,
    "board",
    ["virginia", "america", "united states"],
    "farm",
    0.4,
  ),
  p(
    "timbuktu",
    "Niger bend",
    -3.01,
    16.77,
    "arid",
    "river-ew",
    "west-central-african",
    1400,
    "mudbrick",
    ["timbuktu", "mali", "sahel"],
    "city",
    0.1,
  ),
  p(
    "congo",
    "Congo basin",
    23.2,
    -2.9,
    "tropical",
    "river-ew",
    "west-central-african",
    1500,
    "timber",
    ["congo"],
    "village",
    0.25,
  ),
  p(
    "ethiopia",
    "Ethiopian highlands",
    38.7,
    12.6,
    "monsoon",
    "river-ns",
    "east-southern-african",
    1400,
    "mudbrick",
    ["ethiopia", "abyssinia"],
    "village",
    0.9,
  ),
  p(
    "melbourne",
    "Melbourne",
    144.96,
    -37.81,
    "temperate",
    "river-ew",
    "european",
    1950,
    "board",
    ["melbourne", "victoria"],
    "city",
    0.15,
  ),
  p(
    "australia",
    "Australian interior",
    133.8,
    -23.7,
    "arid",
    "none",
    "australian-pacific",
    1400,
    "timber",
    ["australia", "aboriginal"],
    "camp",
    0.3,
  ),
  p(
    "polynesia",
    "Polynesian coast",
    -149.57,
    -17.56,
    "tropical",
    "coast-n",
    "australian-pacific",
    1400,
    "timber",
    ["polynesia", "tahiti", "pacific"],
    "village",
    0.6,
  ),
];
const aliases = new Set(
  anchors.flatMap((p) => [p.name, ...p.aliases].map((s) => s.toLowerCase())),
);
export const places: AtlasPlace[] = [
  ...anchors,
  ...(legacy as AtlasPlace[]).filter((p) => !aliases.has(p.name.toLowerCase())),
];
export const featuredPlaces = anchors;
