import type { FaunaProfile } from "./types";
import { directionalStudy } from "./types";

/** Four-direction art studies. Horses are kept stock; rabbits are wild and
 * present almost everywhere people are. */
export const directionalFauna: readonly FaunaProfile[] = [
  {
    id: "horse",
    label: "Horse study",
    category: "domestic",
    locomotion: "ground",
    social: "herd",
    activity: "diurnal",
    groupSize: [2, 6],
    habitats: [
      { tag: "pasture", weight: 1 },
      { tag: "open-grass", weight: 0.9 },
      { tag: "settlement", weight: 0.4 },
      { tag: "field", weight: 0.3 },
    ],
    // Domesticated on the Pontic-Caspian steppe and spread by the chariot and
    // then the rider: the Near East and China in the second millennium BCE,
    // Europe behind them, back to the Americas with Spanish ships.
    presence: [
      { years: [-3500, 10000], bounds: [25, 44, 60, 56] },
      { years: [-2000, 10000], bounds: [25, 25, 75, 50] },
      { years: [-1600, 10000], bounds: [-15, 30, 40, 62] },
      { years: [-1300, 10000], bounds: [75, 20, 135, 50] },
      { years: [-500, 10000], bounds: [-20, -5, 55, 35] },
      { years: [1519, 10000], bounds: [-170, -56, -30, 70] },
      { years: [1788, 10000], bounds: [110, -50, 180, -10] },
    ],
    keeping: { place: "paddock" },
    density: 0,
    young: { id: "foal", chance: 0.55 },
    pace: 1.6,
    settlementTolerance: 0.9,
    minimumSettlementDistance: 0,
    alertRadius: 3,
    cohesionRadius: 5,
    separationRadius: 2,
    calmDecisionSeconds: 50,
    urgentDecisionSeconds: 4,
    diet: ["grass", "plant"],
    ...directionalStudy("horse"),
  },
  {
    id: "foal",
    label: "Foal study",
    category: "domestic",
    locomotion: "ground",
    social: "herd",
    activity: "diurnal",
    groupSize: [1, 2],
    habitats: [
      { tag: "pasture", weight: 1 },
      { tag: "open-grass", weight: 0.7 },
      { tag: "settlement", weight: 0.4 },
    ],
    // A foal exists wherever kept horses do; it is not a separate range.
    presence: [
      { years: [-3500, 10000], bounds: [25, 44, 60, 56] },
      { years: [-2000, 10000], bounds: [25, 25, 75, 50] },
      { years: [-1600, 10000], bounds: [-15, 30, 40, 62] },
      { years: [-1300, 10000], bounds: [75, 20, 135, 50] },
      { years: [-500, 10000], bounds: [-20, -5, 55, 35] },
      { years: [1519, 10000], bounds: [-170, -56, -30, 70] },
      { years: [1788, 10000], bounds: [110, -50, 180, -10] },
    ],
    density: 0,
    pace: 1.2,
    settlementTolerance: 0.9,
    minimumSettlementDistance: 0,
    alertRadius: 4,
    cohesionRadius: 2,
    separationRadius: 1,
    calmDecisionSeconds: 25,
    urgentDecisionSeconds: 3,
    diet: ["grass", "plant"],
    ...directionalStudy("foal"),
  },
  {
    id: "rabbit",
    label: "Rabbit study",
    category: "wild",
    locomotion: "ground",
    social: "flock",
    activity: "crepuscular",
    groupSize: [2, 5],
    habitats: [
      { tag: "open-grass", weight: 1 },
      { tag: "scrub", weight: 0.9 },
      { tag: "field", weight: 0.8 },
      { tag: "forest-edge", weight: 0.6 },
      { tag: "pasture", weight: 0.5 },
    ],
    // Iberian by origin, carried round the Mediterranean by Rome, into
    // northern Europe by Norman warrens, and everywhere else by ship.
    presence: [
      { years: [-100000, 10000], bounds: [-10, 35, 4, 44] },
      { years: [-200, 10000], bounds: [-10, 30, 30, 46] },
      { years: [1100, 10000], bounds: [-11, 36, 30, 60] },
      { years: [1500, 10000], bounds: [-170, -56, -30, 70] },
      { years: [1859, 10000], bounds: [110, -50, 180, -10] },
    ],
    // Kept as well as wild from the Norman warrens on: a fenced coney-garth
    // beside the village, not a wild colony that happens to be there.
    keeping: { place: "paddock", from: 1100 },
    density: 2.6,
    young: { id: "rabbit-kit", chance: 0.45 },
    pace: 1.4,
    climbs: true,
    settlementTolerance: 0.35,
    minimumSettlementDistance: 2,
    alertRadius: 5,
    cohesionRadius: 4,
    separationRadius: 1.5,
    calmDecisionSeconds: 20,
    urgentDecisionSeconds: 2,
    diet: ["grass", "plant", "seed"],
    ...directionalStudy("rabbit"),
  },
  {
    id: "rabbit-kit",
    label: "Rabbit kit study",
    category: "wild",
    locomotion: "ground",
    social: "flock",
    activity: "crepuscular",
    groupSize: [2, 4],
    habitats: [
      { tag: "open-grass", weight: 1 },
      { tag: "scrub", weight: 0.9 },
      { tag: "field", weight: 0.6 },
    ],
    // Kits stay within a few metres of the warren, so their range is the
    // adult's range.
    presence: [
      { years: [-100000, 10000], bounds: [-10, 35, 4, 44] },
      { years: [-200, 10000], bounds: [-10, 30, 30, 46] },
      { years: [1100, 10000], bounds: [-11, 36, 30, 60] },
      { years: [1500, 10000], bounds: [-170, -56, -30, 70] },
      { years: [1859, 10000], bounds: [110, -50, 180, -10] },
    ],
    density: 0,
    pace: 1,
    climbs: true,
    settlementTolerance: 0.2,
    minimumSettlementDistance: 3,
    alertRadius: 6,
    cohesionRadius: 2,
    separationRadius: 1,
    calmDecisionSeconds: 12,
    urgentDecisionSeconds: 2,
    diet: ["grass", "plant"],
    ...directionalStudy("rabbit-kit"),
  },
];
