import type { FaunaProfile } from "./types";
import { frames } from "./types";

export const domesticFauna: readonly FaunaProfile[] = [
  {
    id: "chicken",
    label: "Chicken study",
    category: "domestic",
    locomotion: "ground",
    social: "flock",
    activity: "diurnal",
    groupSize: [2, 8],
    habitats: [
      { tag: "settlement", weight: 0.9 },
      { tag: "field", weight: 0.8 },
      { tag: "pasture", weight: 0.5 },
    ],
    settlementTolerance: 1,
    minimumSettlementDistance: 0,
    alertRadius: 3,
    cohesionRadius: 4,
    separationRadius: 1,
    calmDecisionSeconds: 45,
    urgentDecisionSeconds: 6,
    diet: ["seed", "plant", "invertebrate"],
    palette: ["#3d332a", "#8c4d31", "#bd7146", "#ead9aa", "#a84235", "#d5a552"],
    art: frames("chicken", { idle: 2, forage: 2, wander: 4, flee: 4 }),
  },
  {
    id: "sheep",
    label: "Sheep study",
    category: "domestic",
    locomotion: "ground",
    social: "herd",
    activity: "diurnal",
    groupSize: [3, 12],
    habitats: [
      { tag: "pasture", weight: 1 },
      { tag: "open-grass", weight: 0.8 },
      { tag: "scrub", weight: 0.25 },
    ],
    settlementTolerance: 0.8,
    minimumSettlementDistance: 0,
    alertRadius: 5,
    cohesionRadius: 6,
    separationRadius: 1.5,
    calmDecisionSeconds: 60,
    urgentDecisionSeconds: 6,
    diet: ["grass", "plant"],
    palette: ["#332f2a", "#4b4437", "#6f624d", "#c8c2a4", "#e4dfc5"],
    art: frames("sheep", {
      idle: 2,
      graze: 2,
      wander: 4,
      flee: 4,
      rest: 2,
    }),
  },
];
