import type { FaunaProfile } from "./types";
import { study } from "./types";

export const domesticFauna: readonly FaunaProfile[] = [
  {
    id: "chicken",
    label: "Chicken study",
    category: "domestic",
    locomotion: "ground",
    social: "flock",
    activity: "diurnal",
    groupSize: [3, 6],
    habitats: [
      { tag: "settlement", weight: 0.9 },
      { tag: "field", weight: 0.8 },
      { tag: "pasture", weight: 0.5 },
    ],
    // Domesticated in Southeast Asia and carried west along the trade
    // routes: the Near East and Mediterranean by the ninth century BCE,
    // sub-Saharan Africa a few centuries later, the Pacific with Polynesian
    // voyagers, the Americas with the Columbian exchange.
    presence: [
      { years: [-3500, 10000], bounds: [60, -12, 150, 50] },
      { years: [-900, 10000], bounds: [-20, 20, 60, 70] },
      { years: [-500, 10000], bounds: [-20, -35, 55, 20] },
      { years: [-1000, 10000], bounds: [110, -50, 180, -10] },
      { years: [1500, 10000], bounds: [-170, -56, -30, 70] },
    ],
    needs: "settled",
    keeping: { place: "yard" },
    density: 0,
    pace: 0.6,
    settlementTolerance: 1,
    minimumSettlementDistance: 0,
    alertRadius: 1,
    cohesionRadius: 3,
    separationRadius: 1,
    calmDecisionSeconds: 45,
    urgentDecisionSeconds: 6,
    prey: "small-animal",
    diet: ["seed", "plant", "invertebrate"],
    ...study("chicken"),
  },
  {
    id: "sheep",
    label: "Sheep study",
    category: "domestic",
    locomotion: "ground",
    social: "herd",
    activity: "diurnal",
    groupSize: [3, 8],
    habitats: [
      { tag: "pasture", weight: 1 },
      { tag: "open-grass", weight: 0.8 },
      { tag: "scrub", weight: 0.25 },
    ],
    // Domesticated in the hills round the Fertile Crescent; with the first
    // farmers into Europe and Africa, across the steppe into Asia, and in
    // European ships to the Americas and Australia.
    presence: [
      { years: [-9000, 10000], bounds: [25, 25, 65, 45] },
      { years: [-6500, 10000], bounds: [-20, 20, 60, 72] },
      { years: [-5000, 10000], bounds: [40, 5, 140, 55] },
      { years: [-3000, 10000], bounds: [-20, -35, 55, 20] },
      { years: [1493, 10000], bounds: [-170, -56, -30, 70] },
      { years: [1788, 10000], bounds: [110, -50, 180, -10] },
    ],
    needs: "herding",
    keeping: { place: "pen" },
    density: 0,
    pace: 0.5,
    settlementTolerance: 0.8,
    minimumSettlementDistance: 0,
    alertRadius: 1,
    cohesionRadius: 4,
    separationRadius: 1.5,
    calmDecisionSeconds: 60,
    urgentDecisionSeconds: 6,
    prey: "ungulate",
    diet: ["grass", "plant"],
    ...study("sheep"),
  },
  {
    id: "goat",
    label: "Goat study",
    category: "domestic",
    locomotion: "ground",
    social: "herd",
    activity: "diurnal",
    groupSize: [3, 7],
    habitats: [
      { tag: "pasture", weight: 1 },
      { tag: "scrub", weight: 0.9 },
      { tag: "rock", weight: 0.7 },
      { tag: "open-grass", weight: 0.6 },
    ],
    // Domesticated in the Zagros beside the sheep and spread with the same
    // farmers, but further into dry and broken country: goats take scrub and
    // rock a sheep cannot use, so they reach Arabia and the Sahel early.
    presence: [
      { years: [-8000, 10000], bounds: [35, 25, 60, 42] },
      { years: [-6000, 10000], bounds: [-20, 27, 60, 60] },
      { years: [-5000, 10000], bounds: [-20, -35, 55, 30] },
      { years: [-4000, 10000], bounds: [55, 5, 140, 55] },
      { years: [1493, 10000], bounds: [-170, -56, -30, 70] },
      { years: [1788, 10000], bounds: [110, -50, 180, -10] },
    ],
    needs: "herding",
    keeping: { place: "pen" },
    density: 0,
    pace: 0.6,
    climbs: true,
    settlementTolerance: 0.85,
    minimumSettlementDistance: 0,
    alertRadius: 2,
    cohesionRadius: 4,
    separationRadius: 1.5,
    calmDecisionSeconds: 45,
    urgentDecisionSeconds: 5,
    prey: "ungulate",
    diet: ["grass", "plant"],
    ...study("goat"),
  },
  {
    id: "pig",
    label: "Pig study",
    category: "domestic",
    locomotion: "ground",
    social: "herd",
    activity: "diurnal",
    groupSize: [2, 5],
    habitats: [
      { tag: "settlement", weight: 1 },
      { tag: "field", weight: 0.7 },
      { tag: "woodland", weight: 0.6 },
      { tag: "wetland", weight: 0.4 },
    ],
    // Domesticated twice, in Anatolia and in China, and kept by settled
    // farmers rather than herded. The Near Eastern range closes at the Arab
    // conquests, after which the pig keepers there are a minority the
    // generator does not model; Europe and China keep it throughout.
    presence: [
      { years: [-8000, 700], bounds: [30, 28, 50, 42] },
      { years: [-5500, 10000], bounds: [-20, 35, 40, 62] },
      { years: [-6000, 10000], bounds: [100, 18, 140, 50] },
      { years: [-1500, 10000], bounds: [95, -12, 180, 25] },
      { years: [1493, 10000], bounds: [-170, -56, -30, 70] },
      { years: [1788, 10000], bounds: [110, -50, 180, -10] },
    ],
    needs: "settled",
    keeping: { place: "yard" },
    density: 0,
    pace: 0.6,
    settlementTolerance: 1,
    minimumSettlementDistance: 0,
    alertRadius: 2,
    cohesionRadius: 3,
    separationRadius: 1.5,
    calmDecisionSeconds: 40,
    urgentDecisionSeconds: 5,
    prey: "ungulate",
    diet: ["plant", "seed", "invertebrate"],
    ...study("pig"),
  },
];
