import type { FaunaProfile } from "./types";
import { directionalStudy } from "./types";

// Nothing hunts a grown proboscidean; a pride took calves, not these.
const herd = {
  category: "wild",
  locomotion: "ground",
  social: "herd",
  activity: "diurnal",
  density: 0.12,
  pace: 0.8,
  settlementTolerance: 0.02,
  minimumSettlementDistance: 50,
  alertRadius: 9,
  cohesionRadius: 9,
  separationRadius: 4,
  calmDecisionSeconds: 90,
  urgentDecisionSeconds: 8,
} as const;

/** Ice Age animals drawn on the four-direction rigs: the proboscideans in
 * scripts/art/proboscidean.py, the deer in scripts/art/cervid.py, the cats in
 * scripts/art/felid.py, bison and rhinoceros in scripts/art/grazer.py. Ranges end
 * at the last dated remains in each region, not at a single date. */
export const megafauna: readonly FaunaProfile[] = [
  {
    ...herd,
    id: "woolly-mammoth",
    label: "Woolly mammoth",
    latin: "Mammuthus primigenius",
    groupSize: [3, 9],
    habitats: [
      { tag: "open-grass", weight: 1 },
      { tag: "scrub", weight: 0.6 },
      { tag: "wetland", weight: 0.4 },
      { tag: "shore", weight: 0.2 },
    ],
    // The mammoth steppe from Iberia to the Yukon. It left western Europe
    // with the Bølling-Allerød forests, the Siberian mainland around 9000 BC,
    // and lingered on St Paul Island until about 3600 BC (Graham et al. 2016)
    // and on Wrangel Island until about 2000 BC (Vartanyan et al. 1993),
    // while the pyramids were being built.
    presence: [
      { years: [-1000000, -11500], bounds: [-10, 42, 40, 72] },
      { years: [-1000000, -10500], bounds: [40, 42, 180, 78] },
      { years: [-1000000, -9000], bounds: [60, 64, 180, 78] },
      { years: [-1000000, -10500], bounds: [-170, 45, -60, 72] },
      { years: [-1000000, -3600], bounds: [-170.6, 57, -169.9, 57.4] },
      { years: [-1000000, -2000], bounds: [-180, 70.7, -177, 71.8] },
      { years: [-1000000, -2000], bounds: [178, 70.7, 180, 71.8] },
    ],
    diet: ["grass", "plant"],
    ...directionalStudy("woolly-mammoth"),
  },
  {
    ...herd,
    id: "columbian-mammoth",
    label: "Columbian mammoth",
    latin: "Mammuthus columbi",
    groupSize: [2, 8],
    habitats: [
      { tag: "open-grass", weight: 1 },
      { tag: "scrub", weight: 0.7 },
      { tag: "wetland", weight: 0.6 },
      { tag: "woodland", weight: 0.3 },
    ],
    // South of the ice from the Great Plains to Central America; the Clovis
    // kill sites of the plains and the Basin of Mexico, gone by about 10,800 BC.
    presence: [{ years: [-1000000, -10800], bounds: [-125, 12, -75, 50] }],
    diet: ["grass", "plant"],
    ...directionalStudy("columbian-mammoth"),
  },
  {
    ...herd,
    id: "american-mastodon",
    label: "American mastodon",
    latin: "Mammut americanum",
    groupSize: [1, 5],
    habitats: [
      { tag: "woodland", weight: 1 },
      { tag: "wetland", weight: 0.9 },
      { tag: "forest-edge", weight: 0.9 },
      { tag: "scrub", weight: 0.4 },
    ],
    // Spruce parkland and swamp forest, thickest around the Great Lakes and
    // the Atlantic seaboard, a few in the west. Among the last of the North
    // American megafauna, into the tenth millennium BC.
    presence: [
      { years: [-1000000, -9500], bounds: [-100, 25, -60, 60] },
      { years: [-1000000, -10500], bounds: [-125, 30, -100, 62] },
    ],
    diet: ["plant"],
    ...directionalStudy("american-mastodon"),
  },
  {
    id: "irish-elk",
    label: "Giant deer",
    latin: "Megaloceros giganteus",
    category: "wild",
    locomotion: "ground",
    social: "herd",
    activity: "crepuscular",
    groupSize: [2, 7],
    habitats: [
      { tag: "open-grass", weight: 1 },
      { tag: "scrub", weight: 0.8 },
      { tag: "forest-edge", weight: 0.7 },
      { tag: "wetland", weight: 0.5 },
    ],
    // Back into Ireland and Britain with the Allerød warmth and gone from the
    // west at the Younger Dryas; it lived on east of the Urals until about
    // 5700 BC (Stuart et al. 2004). The Russian plain between is a guess.
    presence: [
      { years: [-1000000, -10900], bounds: [-11, 42, 30, 60] },
      { years: [-1000000, -8000], bounds: [30, 45, 50, 60] },
      { years: [-1000000, -5700], bounds: [50, 50, 90, 62] },
    ],
    density: 0.5,
    pace: 1.1,
    settlementTolerance: 0.05,
    minimumSettlementDistance: 24,
    alertRadius: 9,
    cohesionRadius: 6,
    separationRadius: 2.5,
    calmDecisionSeconds: 75,
    urgentDecisionSeconds: 6,
    prey: "ungulate",
    diet: ["grass", "plant"],
    ...directionalStudy("irish-elk"),
  },
  {
    id: "reindeer",
    label: "Reindeer",
    latin: "Rangifer tarandus",
    category: "wild",
    locomotion: "ground",
    social: "herd",
    activity: "flexible",
    groupSize: [4, 14],
    habitats: [
      { tag: "open-grass", weight: 1 },
      { tag: "scrub", weight: 0.8 },
      { tag: "rock", weight: 0.5 },
      { tag: "woodland", weight: 0.4 },
    ],
    // South to Iberia while the ice stood: the Magdalenians are the "reindeer
    // age" for how much of their food it was. North with the Holocene to the
    // tundra and taiga, where it stays. Caribou are the same species.
    presence: [
      { years: [-1000000, -9500], bounds: [-10, 42, 30, 58] },
      { years: [-1000000, 10000], bounds: [5, 58, 180, 78] },
      { years: [-1000000, -10000], bounds: [-170, 42, -52, 50] },
      { years: [-1000000, 10000], bounds: [-170, 50, -52, 83] },
      { years: [-1000000, 10000], bounds: [-73, 60, -12, 84] },
    ],
    density: 0.6,
    pace: 1.1,
    settlementTolerance: 0.1,
    minimumSettlementDistance: 20,
    alertRadius: 7,
    cohesionRadius: 6,
    separationRadius: 1.5,
    calmDecisionSeconds: 70,
    urgentDecisionSeconds: 6,
    prey: "ungulate",
    diet: ["grass", "plant"],
    ...directionalStudy("reindeer"),
  },
  {
    id: "wild-horse",
    label: "Wild horse",
    latin: "Equus ferus",
    category: "wild",
    locomotion: "ground",
    social: "herd",
    activity: "diurnal",
    groupSize: [3, 10],
    habitats: [
      { tag: "open-grass", weight: 1 },
      { tag: "scrub", weight: 0.6 },
      { tag: "forest-edge", weight: 0.3 },
    ],
    // The commonest large animal of the Ice Age steppe and of its cave art.
    // Gone from the Americas with the other megafauna; thinned out of forested
    // Europe after the Neolithic; the tarpan of the Pontic steppe to the 1870s,
    // and Przewalski's horse in Dzungaria and Mongolia until the 1960s, then
    // returned there from zoos in the 1990s.
    presence: [
      { years: [-1000000, -10000], bounds: [-170, 25, -60, 70] },
      { years: [-1000000, -2500], bounds: [-10, 36, 30, 60] },
      { years: [-1000000, 1880], bounds: [30, 44, 60, 55] },
      { years: [-1000000, 1969], bounds: [60, 40, 120, 55] },
      { years: [1992, 10000], bounds: [94, 44, 104, 48] },
    ],
    density: 0.5,
    pace: 1.4,
    settlementTolerance: 0.05,
    minimumSettlementDistance: 30,
    alertRadius: 8,
    cohesionRadius: 5,
    separationRadius: 2,
    calmDecisionSeconds: 60,
    urgentDecisionSeconds: 4,
    prey: "ungulate",
    diet: ["grass", "plant"],
    ...directionalStudy("horse"),
  },
  {
    id: "cave-lion",
    label: "Cave lion",
    latin: "Panthera spelaea",
    category: "wild",
    locomotion: "ground",
    social: "pack",
    activity: "crepuscular",
    groupSize: [1, 4],
    habitats: [
      { tag: "open-grass", weight: 1 },
      { tag: "scrub", weight: 0.8 },
      { tag: "rock", weight: 0.6 },
      { tag: "forest-edge", weight: 0.4 },
    ],
    // The mammoth steppe from Iberia across Beringia into the Yukon; the
    // last dated bones are about 12,000 BC (Stuart and Lister 2011).
    presence: [
      { years: [-1000000, -12000], bounds: [-10, 35, 180, 72] },
      { years: [-1000000, -12000], bounds: [-170, 55, -125, 72] },
    ],
    density: 0.08,
    pace: 1.3,
    settlementTolerance: 0.02,
    minimumSettlementDistance: 30,
    alertRadius: 8,
    cohesionRadius: 4,
    separationRadius: 2,
    calmDecisionSeconds: 90,
    urgentDecisionSeconds: 4,
    diet: ["ungulate"],
    preyTags: ["ungulate"],
    ...directionalStudy("cave-lion"),
  },
  {
    id: "american-lion",
    label: "American lion",
    latin: "Panthera atrox",
    category: "wild",
    locomotion: "ground",
    social: "pack",
    activity: "crepuscular",
    groupSize: [1, 4],
    habitats: [
      { tag: "open-grass", weight: 1 },
      { tag: "scrub", weight: 0.8 },
      { tag: "forest-edge", weight: 0.5 },
    ],
    // South of the ice from Alberta to Mexico, gone with the horses and
    // camels it lived on, about 10,900 BC.
    presence: [{ years: [-1000000, -10900], bounds: [-125, 14, -75, 56] }],
    density: 0.08,
    pace: 1.4,
    settlementTolerance: 0.02,
    minimumSettlementDistance: 30,
    alertRadius: 8,
    cohesionRadius: 4,
    separationRadius: 2,
    calmDecisionSeconds: 90,
    urgentDecisionSeconds: 4,
    diet: ["ungulate"],
    preyTags: ["ungulate"],
    ...directionalStudy("american-lion"),
  },
  {
    id: "smilodon",
    label: "Sabre-toothed cat",
    latin: "Smilodon fatalis",
    category: "wild",
    locomotion: "ground",
    // Healed crippling injuries in the La Brea cats suggest others fed them.
    social: "pack",
    activity: "crepuscular",
    groupSize: [1, 3],
    habitats: [
      { tag: "woodland", weight: 1 },
      { tag: "forest-edge", weight: 1 },
      { tag: "scrub", weight: 0.8 },
      { tag: "open-grass", weight: 0.5 },
    ],
    // Both Americas, from California and Florida to Patagonia, to about
    // 10,000 BC.
    presence: [
      { years: [-1000000, -10000], bounds: [-125, 14, -65, 45] },
      { years: [-1000000, -10000], bounds: [-82, -45, -35, 14] },
    ],
    density: 0.08,
    pace: 1.2,
    settlementTolerance: 0.02,
    minimumSettlementDistance: 30,
    alertRadius: 7,
    cohesionRadius: 3,
    separationRadius: 2,
    calmDecisionSeconds: 90,
    urgentDecisionSeconds: 4,
    diet: ["ungulate"],
    preyTags: ["ungulate"],
    ...directionalStudy("smilodon"),
  },
  {
    id: "steppe-bison",
    label: "Steppe bison",
    latin: "Bison priscus",
    category: "wild",
    locomotion: "ground",
    social: "herd",
    activity: "diurnal",
    groupSize: [4, 14],
    habitats: [
      { tag: "open-grass", weight: 1 },
      { tag: "scrub", weight: 0.6 },
      { tag: "wetland", weight: 0.4 },
    ],
    // The mammoth steppe from Iberia to the Yukon, the bison of Altamira.
    // Gone from Europe as forest closed in; later in Yakutia, into the
    // Holocene (the date here is a round guess from the latest finds).
    presence: [
      { years: [-1000000, -9000], bounds: [-10, 35, 40, 72] },
      { years: [-1000000, -6000], bounds: [40, 35, 180, 75] },
      { years: [-1000000, -9000], bounds: [-170, 50, -100, 72] },
    ],
    density: 0.45,
    pace: 1.1,
    settlementTolerance: 0.05,
    minimumSettlementDistance: 30,
    alertRadius: 8,
    cohesionRadius: 7,
    separationRadius: 2.5,
    calmDecisionSeconds: 90,
    urgentDecisionSeconds: 6,
    prey: "ungulate",
    diet: ["grass", "plant"],
    ...directionalStudy("steppe-bison"),
  },
  {
    id: "american-bison",
    label: "American bison",
    latin: "Bison bison",
    category: "wild",
    locomotion: "ground",
    social: "herd",
    activity: "diurnal",
    groupSize: [6, 20],
    habitats: [
      { tag: "open-grass", weight: 1 },
      { tag: "scrub", weight: 0.6 },
      { tag: "forest-edge", weight: 0.4 },
    ],
    // Before 3000 BC its forebear Bison antiquus, drawn the same, across the
    // continent. Then the plains, and east of the Mississippi until it was
    // hunted out there by about 1830. Tens of millions fell to a few hundred
    // in the hide hunt of the 1870s and 80s; a couple of dozen held on in
    // Yellowstone, and every plains herd since is bred back from survivors.
    presence: [
      { years: [-1000000, -3000], bounds: [-125, 14, -75, 56] },
      { years: [-3000, 1884], bounds: [-115, 25, -90, 60] },
      { years: [-3000, 1830], bounds: [-95, 30, -75, 45] },
      { years: [-3000, 10000], bounds: [-125, 55, -105, 64] },
      { years: [-3000, 10000], bounds: [-111.2, 44.1, -109.8, 45.1] },
    ],
    density: 0.8,
    pace: 1.2,
    settlementTolerance: 0.1,
    minimumSettlementDistance: 20,
    alertRadius: 7,
    cohesionRadius: 8,
    separationRadius: 2.5,
    calmDecisionSeconds: 90,
    urgentDecisionSeconds: 6,
    prey: "ungulate",
    diet: ["grass", "plant"],
    ...directionalStudy("american-bison"),
  },
  {
    id: "wisent",
    label: "Wisent",
    latin: "Bison bonasus",
    category: "wild",
    locomotion: "ground",
    social: "herd",
    activity: "diurnal",
    groupSize: [2, 8],
    habitats: [
      { tag: "woodland", weight: 1 },
      { tag: "forest-edge", weight: 1 },
      { tag: "open-grass", weight: 0.5 },
      { tag: "wetland", weight: 0.4 },
    ],
    // The European forest bison. Out of the west in the Middle Ages; the
    // last wild ones were shot in Białowieża in 1919 and the Caucasus in
    // 1927. Bred back from zoo animals and let go in Białowieża from 1952,
    // the Carpathians later.
    presence: [
      { years: [-9000, 1300], bounds: [-5, 42, 15, 58] },
      { years: [-9000, 1919], bounds: [15, 42, 45, 60] },
      { years: [-9000, 1927], bounds: [38, 41, 47, 45] },
      { years: [1952, 10000], bounds: [23.5, 52.5, 24.2, 52.9] },
      { years: [1965, 10000], bounds: [22, 44, 27, 50] },
    ],
    density: 0.3,
    pace: 1.1,
    settlementTolerance: 0.05,
    minimumSettlementDistance: 28,
    alertRadius: 7,
    cohesionRadius: 6,
    separationRadius: 2.5,
    calmDecisionSeconds: 90,
    urgentDecisionSeconds: 6,
    prey: "ungulate",
    diet: ["grass", "plant"],
    ...directionalStudy("wisent"),
  },
  {
    id: "woolly-rhinoceros",
    label: "Woolly rhinoceros",
    latin: "Coelodonta antiquitatis",
    category: "wild",
    locomotion: "ground",
    social: "herd",
    activity: "diurnal",
    groupSize: [1, 3],
    habitats: [
      { tag: "open-grass", weight: 1 },
      { tag: "scrub", weight: 0.7 },
      { tag: "wetland", weight: 0.3 },
    ],
    // Across the steppe, never into the Americas. Gone from Europe first and
    // from north-east Siberia by about 12,000 BC.
    presence: [
      { years: [-1000000, -13000], bounds: [-10, 35, 40, 72] },
      { years: [-1000000, -12000], bounds: [40, 35, 170, 72] },
    ],
    density: 0.15,
    pace: 0.9,
    settlementTolerance: 0.02,
    minimumSettlementDistance: 35,
    alertRadius: 5,
    cohesionRadius: 4,
    separationRadius: 3,
    calmDecisionSeconds: 100,
    urgentDecisionSeconds: 6,
    diet: ["grass", "plant"],
    ...directionalStudy("woolly-rhinoceros"),
  },
];
