import type { FaunaProfile } from "./types";
import { study } from "./types";

export const temperateFauna: readonly FaunaProfile[] = [
  {
    id: "red-deer",
    label: "Red deer study",
    category: "wild",
    locomotion: "ground",
    social: "herd",
    activity: "crepuscular",
    groupSize: [2, 8],
    habitats: [
      { tag: "forest-edge", weight: 1 },
      { tag: "woodland", weight: 0.75 },
      { tag: "open-grass", weight: 0.65 },
    ],
    settlementTolerance: 0.1,
    minimumSettlementDistance: 28,
    alertRadius: 9,
    cohesionRadius: 8,
    separationRadius: 2,
    calmDecisionSeconds: 75,
    urgentDecisionSeconds: 6,
    diet: ["grass", "plant"],
    ...study("red-deer"),
  },
  {
    id: "gray-wolf",
    label: "Gray wolf study",
    category: "wild",
    locomotion: "ground",
    social: "pack",
    activity: "flexible",
    groupSize: [1, 5],
    habitats: [
      { tag: "woodland", weight: 0.9 },
      { tag: "forest-edge", weight: 0.8 },
      { tag: "scrub", weight: 0.45 },
    ],
    settlementTolerance: 0.05,
    minimumSettlementDistance: 42,
    alertRadius: 10,
    cohesionRadius: 9,
    separationRadius: 2,
    calmDecisionSeconds: 90,
    urgentDecisionSeconds: 6,
    diet: ["small-animal", "ungulate"],
    preyTags: ["small-animal", "ungulate"],
    ...study("gray-wolf"),
  },
];
