import type { FaunaProfile } from "./types";
import { directionalStudy } from "./types";

/** Cattle, dog, cat, donkey and camel, and the mice the cat is kept for: the animals a settlement works with rather
 * than only eats. Each is drawn in several forms and coats; see looks.ts. */
export const workingFauna: readonly FaunaProfile[] = [
  {
    id: "cattle",
    label: "Cattle study",
    latin: "Bos taurus",
    category: "domestic",
    locomotion: "ground",
    social: "herd",
    activity: "diurnal",
    groupSize: [3, 7],
    habitats: [
      { tag: "pasture", weight: 1 },
      { tag: "open-grass", weight: 0.9 },
      { tag: "field", weight: 0.4 },
      { tag: "wetland", weight: 0.3 },
    ],
    // Tamed twice from the aurochs: taurine cattle in the upper Euphrates,
    // zebu in the Indus valley. West with the first farmers, south through
    // the Sahara while it was green, east across the steppe, and over both
    // oceans in European ships.
    presence: [
      { years: [-8500, 10000], bounds: [30, 28, 50, 42] },
      { years: [-7000, 10000], bounds: [60, 5, 97, 36] },
      { years: [-6000, 10000], bounds: [-20, 27, 60, 62] },
      { years: [-5500, 10000], bounds: [-18, 5, 40, 27] },
      { years: [-3000, 10000], bounds: [60, 20, 140, 55] },
      { years: [-2000, 10000], bounds: [95, -11, 125, 30] },
      { years: [-1500, 10000], bounds: [10, -35, 52, 5] },
      { years: [1493, 10000], bounds: [-170, -56, -30, 70] },
      { years: [1788, 10000], bounds: [110, -50, 180, -10] },
    ],
    needs: "herding",
    // Where cattle are kept at all they are the herd that matters.
    keeping: { place: "pen", share: 2, ranging: 0.5 },
    density: 0,
    pace: 0.45,
    settlementTolerance: 0.85,
    minimumSettlementDistance: 0,
    alertRadius: 1,
    cohesionRadius: 5,
    separationRadius: 2,
    calmDecisionSeconds: 75,
    urgentDecisionSeconds: 7,
    prey: "ungulate",
    diet: ["grass", "plant"],
    ...directionalStudy("cattle"),
  },
  {
    id: "dog",
    label: "Dog study",
    latin: "Canis familiaris",
    category: "domestic",
    locomotion: "ground",
    social: "pair",
    activity: "flexible",
    groupSize: [1, 3],
    habitats: [
      { tag: "settlement", weight: 1 },
      { tag: "field", weight: 0.5 },
      { tag: "pasture", weight: 0.5 },
    ],
    // With people before farming, and everywhere people went. The dingo
    // reaches Australia by boat some three and a half thousand years ago.
    presence: [
      { years: [-13000, 10000], bounds: [-20, -35, 180, 75] },
      { years: [-11000, 10000], bounds: [-170, -56, -30, 75] },
      { years: [-1500, 10000], bounds: [110, -50, 180, -10] },
    ],
    keeping: { place: "yard" },
    density: 0,
    pace: 0.9,
    settlementTolerance: 1,
    minimumSettlementDistance: 0,
    alertRadius: 1,
    cohesionRadius: 4,
    separationRadius: 1.5,
    calmDecisionSeconds: 30,
    urgentDecisionSeconds: 4,
    diet: ["small-animal", "plant"],
    preyTags: ["rodent"],
    ...directionalStudy("dog"),
  },
  {
    id: "cat",
    label: "Cat study",
    latin: "Felis catus",
    category: "domestic",
    locomotion: "ground",
    social: "solitary",
    activity: "crepuscular",
    groupSize: [1, 1],
    habitats: [
      { tag: "settlement", weight: 1 },
      { tag: "field", weight: 0.4 },
    ],
    // Kept where grain is stored, and carried along the trade routes: Cyprus
    // and the Levant by the eighth millennium BCE, Egypt by the fourth, the
    // Greek and Roman world and then all Europe with the legions. China has
    // the domestic cat only from the Tang, by the Silk Road. The Swahili
    // coast has it by the ninth century; the Americas and Australia with the
    // ships of the colonisers.
    presence: [
      { years: [-7500, 10000], bounds: [25, 25, 60, 42] },
      { years: [-4000, 10000], bounds: [-17, 15, 36, 37] },
      { years: [-600, 10000], bounds: [-10, 35, 30, 46] },
      { years: [0, 10000], bounds: [-11, 35, 40, 72] },
      { years: [0, 10000], bounds: [40, 35, 90, 55] },
      { years: [-500, 10000], bounds: [60, 5, 97, 37] },
      { years: [700, 10000], bounds: [97, 18, 146, 50] },
      { years: [800, 10000], bounds: [92, -11, 125, 25] },
      { years: [800, 10000], bounds: [30, -35, 52, 15] },
      { years: [1000, 10000], bounds: [-18, 0, 30, 20] },
      { years: [1500, 10000], bounds: [-18, -35, 52, 15] },
      { years: [1500, 10000], bounds: [-170, -56, -30, 75] },
      { years: [1788, 10000], bounds: [110, -45, 180, -10] },
    ],
    needs: "settled",
    keeping: { place: "yard" },
    density: 0,
    pace: 0.8,
    climbs: true,
    settlementTolerance: 1,
    minimumSettlementDistance: 0,
    alertRadius: 2,
    cohesionRadius: 3,
    separationRadius: 2,
    calmDecisionSeconds: 40,
    urgentDecisionSeconds: 3,
    diet: ["small-animal"],
    // Mice, and only mice: a hen is bigger than it wants to argue with.
    preyTags: ["rodent"],
    ...directionalStudy("cat"),
  },
  {
    id: "mouse",
    label: "House mouse study",
    latin: "Mus musculus",
    category: "commensal",
    locomotion: "ground",
    gait: "scurry",
    social: "flock",
    activity: "flexible",
    groupSize: [1, 3],
    habitats: [{ tag: "settlement", weight: 1 }],
    // Into the Natufian houses of the Levant with the first stored grain, the
    // whole Old World behind farming, and the Americas and Australia in ships'
    // holds.
    presence: [
      { years: [-12000, 10000], bounds: [25, 25, 60, 42] },
      { years: [-4000, 10000], bounds: [-20, -35, 150, 72] },
      { years: [1500, 10000], bounds: [-170, -56, -30, 75] },
      { years: [1788, 10000], bounds: [110, -45, 180, -10] },
    ],
    needs: "settled",
    density: 0,
    pace: 1.1,
    settlementTolerance: 1,
    minimumSettlementDistance: 0,
    alertRadius: 1.5,
    cohesionRadius: 2,
    separationRadius: 1,
    calmDecisionSeconds: 12,
    urgentDecisionSeconds: 2,
    diet: ["seed"],
    prey: "rodent",
    ...directionalStudy("mouse"),
  },
  {
    id: "donkey",
    label: "Donkey study",
    latin: "Equus asinus",
    category: "domestic",
    locomotion: "ground",
    social: "pair",
    activity: "diurnal",
    groupSize: [1, 3],
    habitats: [
      { tag: "pasture", weight: 1 },
      { tag: "scrub", weight: 0.8 },
      { tag: "settlement", weight: 0.6 },
      { tag: "rock", weight: 0.4 },
    ],
    // Out of the Nubian wild ass in north-east Africa; the pack animal of
    // Egypt and Mesopotamia before the horse, then along every trade road.
    presence: [
      { years: [-4000, 10000], bounds: [25, 5, 60, 40] },
      { years: [-1500, 10000], bounds: [-12, 28, 45, 52] },
      { years: [-1000, 10000], bounds: [45, 8, 125, 46] },
      { years: [0, 10000], bounds: [-20, -35, 55, 20] },
      { years: [1500, 10000], bounds: [-170, -56, -30, 50] },
      { years: [1800, 10000], bounds: [110, -45, 155, -10] },
    ],
    needs: "settled",
    keeping: { place: "paddock", ranging: 0.12 },
    density: 0,
    pace: 0.6,
    climbs: true,
    settlementTolerance: 0.95,
    minimumSettlementDistance: 0,
    alertRadius: 1,
    cohesionRadius: 3,
    separationRadius: 1.5,
    calmDecisionSeconds: 70,
    urgentDecisionSeconds: 6,
    prey: "ungulate",
    diet: ["grass", "plant"],
    ...directionalStudy("donkey"),
  },
  {
    id: "camel",
    label: "Camel study",
    latin: "Camelus dromedarius",
    category: "domestic",
    locomotion: "ground",
    social: "herd",
    activity: "diurnal",
    groupSize: [2, 5],
    habitats: [
      { tag: "scrub", weight: 1 },
      { tag: "open-grass", weight: 0.7 },
      { tag: "pasture", weight: 0.6 },
      { tag: "rock", weight: 0.3 },
    ],
    // Two animals: the Bactrian of the cold Asian deserts, in harness by the
    // third millennium, and the dromedary of Arabia, which crosses into
    // Africa in numbers only under Rome. Australia imports it for the interior.
    presence: [
      { years: [-2500, 10000], bounds: [45, 30, 130, 56] },
      { years: [-1000, 10000], bounds: [33, 10, 62, 40] },
      { years: [-500, 10000], bounds: [60, 20, 78, 36] },
      { years: [100, 10000], bounds: [-18, 8, 40, 38] },
      { years: [1860, 10000], bounds: [112, -38, 150, -12] },
    ],
    needs: "herding",
    keeping: { place: "pen", ranging: 0.35 },
    density: 0,
    pace: 0.7,
    settlementTolerance: 0.8,
    minimumSettlementDistance: 0,
    alertRadius: 1,
    cohesionRadius: 5,
    separationRadius: 2,
    calmDecisionSeconds: 80,
    urgentDecisionSeconds: 7,
    prey: "ungulate",
    diet: ["plant", "grass"],
    ...directionalStudy("camel"),
  },
];
