import type { TravelLocation } from "../../../world/travel/types";
const source = "https://www.britannica.com/place/United-Kingdom/History";
const town = (
  id: string,
  name: string,
  landscape: string,
  lon: number,
  lat: number,
  rank: "town" | "city" = "town",
): TravelLocation => ({
  id,
  name,
  landscape,
  lon,
  lat,
  kind: "settlement",
  importance: 3,
  settlement: { from: 1000, to: 1500, rank, source },
  note: "Inferred medieval settlement scale for 1000–1500; this interval is scenario coverage, not a founding or abandonment date.",
});
export const britainTravel: TravelLocation[] = [
  town("london", "London", "Lower Thames valley", -0.12, 51.51, "city"),
  town("oxford", "Oxford", "Upper Thames valley", -1.2577, 51.752),
  town("edinburgh", "Edinburgh", "Lothian coast", -3.1883, 55.9533),
  town("york", "York", "Vale of York", -1.08, 53.97, "city"),
  town("lincoln", "Lincoln", "Witham valley", -0.54, 53.23),
  town("durham", "Durham", "Wear valley", -1.576, 54.776),
  town("carlisle", "Carlisle", "Solway plain", -2.936, 54.893),
  {
    id: "western-thames",
    name: "Western Thames valley",
    landscape: "Western Thames valley",
    lon: -0.72,
    lat: 51.55,
    kind: "landscape",
    importance: 2,
  },
  {
    id: "white-horse",
    name: "Vale of the White Horse",
    landscape: "Vale of the White Horse",
    lon: -1.52,
    lat: 51.62,
    kind: "landscape",
    importance: 2,
  },
  {
    id: "midland-fields",
    name: "Midland fields",
    landscape: "Midland fields",
    lon: -1.4,
    lat: 52.65,
    kind: "landscape",
    importance: 1,
  },
  {
    id: "pennine-moors",
    name: "Pennine moors",
    landscape: "Pennine moors",
    lon: -2.15,
    lat: 54.35,
    kind: "landscape",
    importance: 2,
  },
  {
    id: "border-hills",
    name: "Border hills",
    landscape: "Border hills",
    lon: -2.65,
    lat: 55.45,
    kind: "landscape",
    importance: 2,
  },
];
