import {
  AlignEndHorizontal,
  Amphora,
  Baby,
  Beef,
  Bell,
  Bird,
  Bone,
  BookOpen,
  Bug,
  Castle,
  Church,
  CircleDashed,
  CircleDot,
  Cloud,
  CloudMoon,
  CloudRain,
  CloudSun,
  Coins,
  Cross,
  Crown,
  Dog,
  DoorOpen,
  Droplet,
  Drum,
  Eclipse,
  Egg,
  Eye,
  EyeOff,
  Factory,
  Feather,
  Flame,
  Flower,
  Flower2,
  Footprints,
  Frame,
  Gem,
  Globe,
  Grape,
  Grid2x2,
  Hammer,
  Hand,
  Heart,
  HeartCrack,
  Home,
  Hourglass,
  Key,
  Lamp,
  Landmark,
  Layers,
  Link,
  Milestone,
  Moon,
  Mountain,
  Music,
  Network,
  Rabbit,
  Sailboat,
  Scale,
  Scissors,
  ScrollText,
  Shell,
  Shield,
  Shirt,
  ShoppingBasket,
  Skull,
  Soup,
  Sparkle,
  Sparkles,
  Spool,
  Sprout,
  Star,
  Sun,
  Sword,
  Swords,
  Tablet,
  Tornado,
  Tractor,
  TreePine,
  UserRound,
  Users,
  Utensils,
  VenetianMask,
  Wand,
  Warehouse,
  Waves,
  Waypoints,
  Wheat,
  Wind,
  Zap,
  Circle,
} from "lucide-react";
import type { LucideIcon } from "lucide-react";
import type { GlyphId } from "../render/glyphs";

/**
 * A line icon for each glyph a stance can carry. The world uses pixel glyphs;
 * the character panel is chrome rather than world, and reads better in the
 * same line weight as the rest of it.
 */
const icons: Partial<Record<GlyphId, LucideIcon>> = {
  "altar": Flame,
  "ancestors": Users,
  "anvil": Hammer,
  "basket": ShoppingBasket,
  "beads": CircleDot,
  "bell": Bell,
  "bird": Bird,
  "boat": Sailboat,
  "bones": Bone,
  "book": BookOpen,
  "breath": Wind,
  "cairn": Layers,
  "cattle": Beef,
  "cave": Mountain,
  "cliff": Mountain,
  "cloth": Shirt,
  "cloud": Cloud,
  "coin": Coins,
  "comb": Grid2x2,
  "comet": Sparkle,
  "constellation": Sparkles,
  "cradle": Baby,
  "crescent": Moon,
  "cross": Cross,
  "crossroads": Waypoints,
  "crowd": Users,
  "crown": Crown,
  "deer": Rabbit,
  "dog": Dog,
  "dream": CloudMoon,
  "drum": Drum,
  "dune": Waves,
  "earth": Globe,
  "eclipse": Eclipse,
  "egg": Egg,
  "elder": UserRound,
  "eye": Eye,
  "fire": Flame,
  "flower": Flower,
  "flute": Music,
  "footprint": Footprints,
  "gate": DoorOpen,
  "grain": Wheat,
  "granary": Warehouse,
  "hammer": Hammer,
  "hand": Hand,
  "heart": Heart,
  "hill": Mountain,
  "horse": Rabbit,
  "hourglass": Hourglass,
  "house": Home,
  "key": Key,
  "kiln": Factory,
  "knife": Utensils,
  "knot": Link,
  "ladder": AlignEndHorizontal,
  "lamp": Lamp,
  "loom": Grid2x2,
  "lotus": Flower2,
  "maize": Wheat,
  "marsh": Waves,
  "mask": VenetianMask,
  "maze": Network,
  "minaret": Landmark,
  "mirror": Frame,
  "mother-and-child": Baby,
  "needle": Feather,
  "net": Network,
  "night": Moon,
  "offering-bowl": Soup,
  "ore": Gem,
  "pillar": Landmark,
  "plough": Tractor,
  "pot": Amphora,
  "rain": CloudRain,
  "river": Waves,
  "rope": Link,
  "scales": Scale,
  "scales-of-fate": Scale,
  "sceptre": Wand,
  "scorpion": Bug,
  "scroll": ScrollText,
  "seed": Sprout,
  "shadow": Moon,
  "shell": Shell,
  "shield": Shield,
  "shrine": Church,
  "sickle": Scissors,
  "skull": Skull,
  "sky": CloudSun,
  "sleep": Moon,
  "spear": Swords,
  "spiral": Tornado,
  "spring": Droplet,
  "staff": Milestone,
  "standing-stone": Milestone,
  "star": Star,
  "stupa": Landmark,
  "sun": Sun,
  "sword": Sword,
  "tablet": Tablet,
  "thread": Spool,
  "threshold": DoorOpen,
  "throne": Crown,
  "thunder": Zap,
  "tomb": Landmark,
  "tower": Castle,
  "tree": TreePine,
  "veil": EyeOff,
  "vine": Grape,
  "waterfall": Waves,
  "wheel": CircleDashed,
  "wound": HeartCrack,
};
export const stanceIcon = (glyph: GlyphId): LucideIcon => icons[glyph] ?? Circle;
