/**
 * Event System Type Definitions
 * Defines all interfaces for the historically accurate event system
 */

import { BiomeType } from './index';
import { HistoricalEra } from '../constants/historicalEras';
import { CulturalZone } from '../constants/geography';

/**
 * Core Game Mode definition
 */
export interface GameMode {
  id: string;
  name: string;
  description: string;
  eventArchetypes: EventArchetype[];  // Only 3-4 per mode for simplicity
  victoryConditions: VictoryCondition[];
  defaultWeight: number;  // How often events trigger (0.1 - 1.0)
}

/**
 * Event archetype template
 */
export interface EventArchetype {
  id: string;
  template: string;  // Base description with [PLACEHOLDER] variables
  triggers: EventTrigger[];  // Simple conditions
  outcomes: EventOutcome[];  // 2-3 possible results per archetype
  variables: TemplateVariable[];  // What can be substituted
}

/**
 * Variables that can be substituted in templates
 */
export interface TemplateVariable {
  key: string;  // e.g., "RESOURCE", "HAZARD", "GOODS"
  options: string[];  // Possible values
  contextual?: boolean;  // If true, options depend on era/culture
}

/**
 * Event trigger conditions
 */
export interface EventTrigger {
  type: 'low_resource' | 'near_location' | 'time_based' | 'stat_check' | 'random' | 'always';
  condition: string;  // e.g., "health < 30", "near_city", "day % 7 == 0"
  probability: number;  // 0.0 to 1.0
}

/**
 * Possible outcome of an event choice
 */
export interface EventOutcome {
  id: string;
  description: string;
  buttonText: string;  // What appears on the choice button
  statChecks?: StatCheck[];  // Required stats for this choice
  effects: EventEffect[];
  weight: number;  // For random selection when no stat check
  historicalNote?: string;  // Educational context
}

/**
 * Stat requirement for an outcome
 */
export interface StatCheck {
  stat: 'strength' | 'dexterity' | 'constitution' | 'intelligence' | 'wisdom' | 'charisma';
  minimum: number;
  description?: string;  // e.g., "Wisdom 10+"
}

/**
 * Effect of an event outcome
 */
export interface EventEffect {
  type: 'stat_change' | 'item_add' | 'item_remove' | 'reputation' | 'location' | 'quest' | 'health' | 'fatigue';
  target: string;  // What to affect
  value: number | string;
  description?: string;  // For UI display
}

/**
 * Victory condition for a game mode
 */
export interface VictoryCondition {
  id: string;
  description: string;
  type: 'survival_days' | 'accumulate_wealth' | 'complete_quest' | 'reach_location' | 'reputation_level' | 'custom';
  target?: number | string;
  progress?: number;  // Current progress toward victory
}

/**
 * An instance of an event that occurs in game
 */
export interface EventInstance {
  id: string;
  archetypeId: string;  // Reference to the template
  title: string;
  description: string;  // Filled template with actual values
  outcomes: EventOutcome[];
  timestamp: number;
  location?: { x: number; y: number };
  isLLMGenerated?: boolean;
  historicalContext?: string;  // Educational content
  relatedSources?: string[];  // Primary source IDs
}

/**
 * Special NPC generated by LLM for scenarios
 */
export interface SpecialNPC {
  id: string;
  name: string;
  occupation: string;  // Historically accurate role
  description: string;
  dialogue: string[];
  location: { x: number; y: number };
  questId?: string;
  memory: NPCMemory[];
  isSpecial: true;  // Marker for special rendering
}

/**
 * NPC memory of interactions
 */
export interface NPCMemory {
  eventId: string;
  timestamp: number;
  playerChoice: string;
  outcome: string;
}

/**
 * Context for generating era/culture appropriate variables
 */
export interface EventContext {
  era: HistoricalEra;
  culturalZone: CulturalZone;
  biome?: BiomeType;
  season?: 'spring' | 'summer' | 'autumn' | 'winter';
  nearCity?: boolean;
  playerWealth?: 'poor' | 'modest' | 'wealthy';
  playerProfession?: string;
}

/**
 * LLM-enhanced scenario
 */
export interface LLMScenario {
  gameMode: GameMode;
  historicalContext: string;
  year: number;
  location: string;
  customEvents: EventArchetype[];
  specialNPCs: SpecialNPC[];
  victoryConditions: VictoryCondition[];
  educationalGoals: string[];
  primarySources?: string[];  // Relevant historical documents
}

/**
 * API usage tracking
 */
export interface APIUsageStats {
  totalCalls: number;
  sessionCalls: number;
  lastCallTimestamp?: number;
  dailyLimit?: number;
  costEstimate?: number;  // In cents
}

/**
 * Event system settings
 */
export interface EventSettings {
  frequency: 'realistic' | 'moderate' | 'frequent';
  historicalAccuracy: 'strict' | 'balanced' | 'relaxed';
  showRealOutcomes: 'always' | 'on_completion' | 'never';
  anachronismWarnings: boolean;
  apiUsageLimit?: number;  // Daily limit
  autoPauseOnEvent: boolean;
}

/**
 * Game mode types
 */
export type GameModeType =
  | 'survival'
  | 'exploration'
  | 'commerce'
  | 'scholarship'
  | 'leadership'
  | 'livelihood'
  | 'diplomacy'
  | 'healer'
  | 'legal';

/**
 * Event history entry
 */
export interface EventHistoryEntry {
  event: EventInstance;
  choiceIndex: number;
  outcome: EventOutcome;
  timestamp: number;
}