/**
 * What each prop is, said plainly, for the focus card. One or two sentences
 * a person on the street would say, not a note on the evidence. Keyed by the
 * catalog id; a prop missing here falls back to its own description.
 */
export const about: Record<string, string> = {
  "signpost-oak": "A carved board on a post, telling passers-by what is made or sold here.",
  "signpost-painted": "A painted sign on a post, telling passers-by what is made or sold here.",
  "signpost-lacquer": "A lacquered sign board naming the business inside.",
  "signpost-split": "A sign on a post, telling passers-by what is made or sold here.",
  "signpost-pennant": "A cloth pennant hung from a pole to show the shop is open and what it sells.",
  "signpost-bazaar": "A trader's sign, put out so the stall can be found in a crowded street.",
  saintNiche: "A small shrine in the wall with a painted saint. Neighbours leave candles and flowers and say a prayer as they pass.",
  burialStone: "A stone set up over a grave, to mark where someone is buried.",
  newsstand: "A stand selling newspapers and magazines.",
  streetFountain: "A public tap where anyone can fill a jug or take a drink.",
  streetNotice: "A board where official notices and announcements are posted for the street to read.",
  jizo: "A small stone statue of Jizō, a Buddhist guardian of children and travellers. People leave offerings and tie red bibs on it.",
  marketDisplay: "Goods set out in front of a shop so passers-by can see what is for sale.",
  waterStation: "Clay jars of drinking water left out for anyone passing. The porous clay keeps it cool.",
  marketCounter: "A low bench where a seller lays out goods to sell.",
  hideBag: "A bag made from animal hide, for carrying and keeping things.",
  pot: "An everyday clay pot for water, grain or food.",
  jar: "A clay jar for keeping food: grain, oil, pickles or wine.",
  jug: "A jug for carrying and pouring water.",
  amphora: "A tall two-handled clay jar for shipping wine or oil. The pointed base lets it be packed upright in sand or a ship's hold.",
  vat: "A big clay storage jar, half the height of a person, for a household's grain, oil or wine.",
  flask: "A small flask with a stopper, for oil, medicine or something to drink on the road.",
  bowl: "An open bowl for mixing, serving or eating.",
  glazed: "A glazed jar. The glaze seals the clay so it holds liquid without seeping.",
  basket: "An open woven basket for carrying produce or laundry.",
  liddedBasket: "A woven basket with a lid, for keeping things clean and dry.",
  sack: "A cloth sack for grain, flour or anything else loose.",
  standingStone: "A great stone set upright long ago. People still tell stories about who put it there.",
  waymark: "A marker at the side of the way, showing the road and how far to the next place.",
  waysideShrine: "A small roadside shrine where travellers stop to pray and leave an offering.",
  hayRick: "Hay stacked high to dry and keep, to feed the animals through winter.",
  dovecote: "A house for pigeons. They are kept for their eggs, meat and droppings, which make good manure.",
  chickenCoop: "A henhouse where the chickens are shut in at night, safe from foxes. The eggs are collected here.",
  crateStack: "Wooden crates of goods stacked up, waiting to be moved or sold.",
  grainSacks: "Sacks of grain, stacked after threshing or on their way to the mill.",
  flowerTub: "A tub of plants or herbs kept by the door.",
  chest: "A wooden chest for clothes, linen and valuables.",
  cookingPot: "A pot for cooking over the fire.",
  strappedChest: "A chest bound with straps to keep it shut and strong, for travel or valuables.",
  paintedChest: "A painted chest, often part of a bride's goods, for clothes and linen.",
  boulder: "A big boulder, too heavy to move.",
  fieldStone: "A rock turned up from the field and left at its edge.",
  crate: "A wooden crate for moving goods.",
  barrel: "A wooden barrel for ale, water, salt fish or anything that has to travel.",
  bucket: "A wooden pail for carrying water or milk.",
  well: "A well shared by the neighbourhood. People come here to draw water and hear the news.",
  roofedWell: "A well with a roof over it and a windlass to wind up the bucket.",
  spring: "A stone basin fed by a spring, where people fill their jugs.",
  trough: "A trough of water for the animals to drink from.",
  townWell: "The town's public well. Everyone comes here for water.",
  sickle: "A curved blade for cutting grain at harvest.",
  axe: "An axe for felling trees and splitting wood.",
  pick: "A pick for breaking hard ground and stone.",
  dryingRack: "A rack for drying fish, meat, herbs or washing in the sun and wind.",
  pump: "A hand pump that brings water up from a well below.",
  spade: "A spade for digging.",
  shovel: "A long-handled shovel for moving earth, dung or grain.",
  scythe: "A long blade on a pole for mowing hay and grain.",
  sheaf: "A bundle of cut grain stalks, tied and left to dry before threshing.",
  anvil: "A smith's anvil on a block of wood, where hot iron is hammered into shape.",
  loom: "An upright loom for weaving cloth.",
  bench: "A bench to sit on.",
  stool: "A stool to sit on.",
  privyShed: "A privy: a small shed over a pit, where the household goes to the toilet.",
  privyScreen: "A toilet pit with a screen round it for privacy. The household relieves itself here, and the pit is filled in and dug again when it is full.",
  privyBench: "A public latrine: a bench with holes, over a channel or pit. Several people use it at once.",
  privyStone: "A stone privy built over a pit.",
  privyNightSoil: "A privy whose pit is emptied by the night-soil men, who carry the waste off to spread on the fields.",
  privyOuthouse: "An outhouse: a wooden shed with a toilet over a pit.",
  privyMidden: "A midden, the household's rubbish heap: ashes, bones, broken pots and dung. It rots down and goes on the fields.",
  privyDung: "A heap of dung and straw from the animals, left to rot and spread on the fields.",
  granaryStaddle: "A granary raised on stone posts. The mushroom-shaped tops stop rats from climbing up to the grain.",
  granaryMud: "A granary made of mud, where the harvest is kept dry and safe from animals until it is needed.",
  granaryStilt: "A granary on stilts, raised off the damp ground and out of reach of rats.",
  granaryClay: "A clay silo where the harvest is sealed in against damp and pests.",
  shopSign: "A sign naming the shop.",
  shopSignEuro: "A sign hung out over the street, so people can find the shop.",
  shopSignSouk: "A sign over a stall in the market.",
  doorLantern: "Lanterns by the door, lit at dusk.",
  hitchingPost: "A post for tying up horses and donkeys.",
  beamScale: "A balance for weighing goods for sale.",
  plough: "A plough for turning the soil before sowing. It is pulled by oxen or horses.",
  waterButt: "A barrel that catches rainwater from the roof.",
  rake: "A rake for gathering hay or smoothing soil.",
  pitchfork: "A pitchfork for lifting hay and straw.",
  beehive: "A beehive. The bees are kept for honey and wax.",
  hideFrame: "An animal hide stretched on a frame to dry before it is scraped and cured.",
  knappingFloor: "A spot where flint and stone are chipped into blades and tools. The ground is covered in sharp flakes.",
  warpLoom: "An upright loom whose threads are pulled tight by hanging clay weights.",
  grainPit: "A pit dug in the ground and sealed, to store grain through the winter.",
  skullPost: "An animal skull set on a post, to guard the place or honour the animal.",
  shaduf: "A shaduf: a long pole with a bucket on one end and a weight on the other, for lifting water from the river or canal onto the fields.",
  zir: "A big porous clay jar of drinking water. Water seeping through the clay keeps it cool.",
  pipeHive: "Clay pipes stacked as beehives, kept for honey and wax.",
  logHive: "A hollow log used as a beehive.",
  calabash: "A dried gourd used as a bowl or bottle.",
  poundingMortar: "A mortar and pestle for pounding grain into flour.",
  charpoy: "A rope bed on a wooden frame, dragged outside to sit or sleep on in the heat.",
  stockPen: "A fenced pen for keeping animals in.",
  milkChurn: "A churn for carrying milk, or for churning it into butter.",
  farmCart: "A cart for carrying hay, harvest and goods.",
  firepit: "The shared fire, where people cook, warm themselves and talk.",
  campHearth: "An open fire for cooking and warmth.",
  communalHearth: "The village hearth, where people gather to cook and talk.",
  councilFire: "The fire where the elders meet to talk things over and settle disputes.",
  earthOven: "An oven dug into the ground. Food is buried with hot stones and left to cook slowly.",
  threeStoneHearth: "Three stones round a fire, with a pot set on top.",
  longFire: "A long fire for cooking or smoking food for many people at once.",
  seatLog: "A log laid down to sit on.",
  seatStone: "A flat stone to sit on.",
  seatMat: "A woven mat to sit on.",
  tannur: "A clay oven sunk in the ground. Flatbread is slapped onto its hot inner wall to bake.",
  brazier: "A standing brazier of burning coals, for warmth and light.",
  bakeOven: "The shared oven where the neighbours bring their dough to be baked.",
  teaStove: "A stove with a kettle always on, for tea.",
  fireBasket: "An iron basket of burning wood, for warmth and light.",
  drumFire: "An old oil drum with a fire in it, to keep warm by.",
  woodpile: "Firewood stacked to dry, for cooking and heating.",
  grinder: "A grinding stone for turning grain into flour by hand.",
  dustbin: "A metal bin for the household's rubbish.",
  drum: "A steel drum for storing oil, water or fuel.",
  barrow: "A wheelbarrow for carrying earth, dung or goods.",
  washingLine: "A line where the household's washing is hung out to dry.",
  tin: "A metal tin for keeping food or oil.",
  plastic: "A plastic bucket.",
  carton: "A cardboard box.",
  stick: "A stout stick, good for leaning on or hitting things.",
  spear: "A spear for hunting or fighting.",
  branch: "A fallen branch.",
};
