/**
 * Twenty-four-pixel garment art, one drawing per silhouette rather than per
 * garment: the cloth's dye and fibre colour it at draw time, so one tunic
 * serves madder wool and white polyester alike. Light falls from the upper
 * left, so the lit edge is `O` and the far edge `x` then `#`.
 *
 * `.` outline, `#` deep shade, `x` shade, `o` body, `O` highlight,
 * `:` a seam or a fold in the weave, `t`/`T` trim, `k`/`K` fixed leather,
 * `m`/`M` fixed metal, space empty.
 *
 * Generated art, hand-checked: the shapes come from a drape model in
 * scripts/garment_art/ rather than from typing spaces.
 */
export const GARMENT_ICON = 24;

/** One drawing: twenty-four rows of twenty-four channel letters. */
export type IconArt = readonly string[];

export const garmentArt: Record<string, IconArt> = {
  // ── body ──────────────────────────────────────────────────────────────
  tunic: [
    "                        ",
    "                        ",
    "      ...      ...      ",
    "    ..Ooo......Ooo..    ",
    "  ..Oooo#......Oooo#..  ",
    " .Oooooox#....Oooooox#. ",
    " .Ooooooo######ooooox#. ",
    " .Oooooooooooooooooox#. ",
    "  ....Oooooooooox#....  ",
    "     .OooOoooooxx#.     ",
    "     .Oooooooooxx#.     ",
    "     .OooOoooooxx#.     ",
    "     .OooOoooooxx#.     ",
    "     .OooOoooooox#.     ",
    "     .xxxOxxxxxxx#.     ",
    "     .tttttttttttt.     ",
    "     .Oooooooooox#.     ",
    "      ............      ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
  ],
  "long-tunic": [
    "                        ",
    "      ...      ...      ",
    "    ..Ooo......Ooo..    ",
    "  ..Oooo#......Oooo#..  ",
    " .Oooooox#....Oooooox#. ",
    " .Ooooooo######ooooox#. ",
    " .Oooooooooooooooooox#. ",
    "  ....Oooooooooox#....  ",
    "     .Oooooooooox#.     ",
    "     .OoOooooooox#.     ",
    "     .Oooooooooox#.     ",
    "     .OoOooooooox#.     ",
    "     .OoOooooooox#.     ",
    "     .OoOooooooox#.     ",
    "     .OoOooooooox#.     ",
    "     .Oooooooooox#.     ",
    "     .OoOooooooox#.     ",
    "     .OoOooooooox#.     ",
    "    .OooOoooooooox#.    ",
    "    .xxxOxxxxxxxxx#.    ",
    "    .tttttttttttttt.    ",
    "    .Oooooooooooox#.    ",
    "     ..............     ",
    "                        ",
  ],
  shirt: [
    "                        ",
    "                        ",
    "      ....    ....      ",
    "    ..Ooot....tooo..    ",
    "  ..Oo.Oot.#t.too.Oo..  ",
    " .Oooo.Oooo#toox#.Oooo. ",
    " .Oooo.Ooo##t#ox#.Oooo. ",
    " .Oooo.Oooo#toox#.Oooo. ",
    "  .....Oooo#toox#.....  ",
    "      .OOoo#toox#.      ",
    "      .Oooo#toox#.      ",
    "      .OOoo#toox#.      ",
    "      .OOoo#toox#.      ",
    "      .OOoo#toox#.      ",
    "      .OOoo#toox#.      ",
    "      .Oooo#toox#.      ",
    "      .OOoo#toox#.      ",
    "      .xOxx#txxx#.      ",
    "     .Oooooooooox#.     ",
    "      ............      ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
  ],
  coat: [
    "                        ",
    "      ....    ....      ",
    "    ..Ooot....tooo..    ",
    "  ..Ooooott#tttooox#..  ",
    " .Ooooootto#tottoooox#. ",
    ".Ooooootto##t#ottoooox#.",
    ".Oooooooooo#toooooooox#.",
    " .....Ooooo#tooox#..... ",
    "     .Ooooo#tooox#.     ",
    "     .OOooo#tooox#.     ",
    "     .Ooooo#tooox#.     ",
    "     .OOooo#tooox#.     ",
    "     .OOooo#tooox#.     ",
    "     .OOooo#tooox#.     ",
    "     .OOooo#tooox#.     ",
    "     .Ooooo#tooox#.     ",
    "    .OoOooo#toooox#.    ",
    "    .OoOooo#toooox#.    ",
    "    .OoOooo#toooox#.    ",
    "    .OoOooo#toooox#.    ",
    "    .Oooooo#toooox#.    ",
    "    .xxOxxx#txxxxx#.    ",
    "   .Oooooooooooooox#.   ",
    "    ................    ",
  ],
  robe: [
    "                        ",
    "      ...      ...      ",
    "    ..Ooo......Ooo..    ",
    " ...Ooooo#.#t.Ooooo#... ",
    ".Ooooooox#.#t.Ooooooox#.",
    "Ooooooooooo#tooooooooox#",
    "Oooooooooo##t#oooooooox#",
    "......Ooooo#tooox#......",
    "     .Ooooo#tooox#.     ",
    "     .Ooooo#tooox#.     ",
    "     .Ooooo#tooox#.     ",
    "     .OOooo#tooox#.     ",
    "     .OOooo#tooox#.     ",
    "    .OoOooo#toooox#.    ",
    "    .OoOooo#toooox#.    ",
    "    .Oooooo#toooox#.    ",
    "    .OoOooo#toooox#.    ",
    "    .OoOooo#toooox#.    ",
    "   .OooOooo#tooooox#.   ",
    "   .OooOooo#tooooxx#.   ",
    "   .xxxxxxx#txxxxxx#.   ",
    "   .tttttttttttttttt.   ",
    "   .Oooooooooooooox#.   ",
    "    ................    ",
  ],
  "open-robe": [
    "                        ",
    "                        ",
    "      ...      ...      ",
    "    ..Ooo......Ooo..    ",
    " ...Ooooott#tttooox#... ",
    ".Ooooooott.#t.ttooooox#.",
    "Ooooooottoo#toottooooox#",
    "Oooooooooo##t#oooooooox#",
    "......Ooooo#tooox#......",
    "     .Ooooo#tooox#.     ",
    "     .Ooooo#tooox#.     ",
    "     .OoOoo#tooox#.     ",
    "     .OoOoo#tooox#.     ",
    "    .OooOoo#toooox#.    ",
    "    .OooOoo#toooxx#.    ",
    "    .Oooooo#toooxx#.    ",
    "    .OooOoo#toooxx#.    ",
    "    .OooOoo#toooxx#.    ",
    "    .OooOoo#toooox#.    ",
    "   .OoooOoo#toooxox#.   ",
    "   .xxxxxxx#txxxxxx#.   ",
    "   .Oooooooooooooox#.   ",
    "    ................    ",
    "                        ",
  ],
  dress: [
    "                        ",
    "                        ",
    "        .      .        ",
    "      ..O......O..      ",
    "   ...Ooo......Ooo...   ",
    "  .Ooooox#....Ooooox#.  ",
    "  .Oooooo######oooox#.  ",
    "  .Oooooooooooooooox#.  ",
    "   .....Oooooox#.....   ",
    "       .Oooooox#.       ",
    "       .Oooooox#.       ",
    "       .Oooooox#.       ",
    "       .OoOooox#.       ",
    "      .OooOoooox#.      ",
    "      .OoOooooox#.      ",
    "     .Oooooooooxx#.     ",
    "     .OooOoooooxx#.     ",
    "    .OooOoooooooxx#.    ",
    "    .OooOoooooooox#.    ",
    "   .OoooOoooooooxox#.   ",
    "   .xxxxxxxxxxxxxxx#.   ",
    "  .tttttttttttttttttt.  ",
    " .Oooooooooooooooooox#. ",
    "  ....................  ",
  ],
  gown: [
    "                        ",
    "       ..      ..       ",
    "     ..Oo......Oo..     ",
    "  ...Oooo#....Oooo#...  ",
    "..Oooooox#....Oooooox#..",
    "Ooooox#.Ooo..Ooo.Ooooox#",
    "Ooooox#.Oo####x#.Ooooox#",
    "........Oooooox#........",
    "       .Oooooox#.       ",
    "       .Oooooox#.       ",
    "       .Oooooox#.       ",
    "       .OOoOoox#.       ",
    "      .OoOoOoxox#.      ",
    "      .OOoooooxx#.      ",
    "     .OoOoOoooxox#.     ",
    "     .OoooOoooxox#.     ",
    "    .OoOoOooooooox#.    ",
    "   .OooOoOoooooxoxx#.   ",
    "   .OooOoooooooxoxx#.   ",
    "  .OooOoOoooooooxoox#.  ",
    "  .xxxxxOxxxxxxxxxxx#.  ",
    " .tttttttttttttttttttt. ",
    " .Oooooooooooooooooox#. ",
    "  ....................  ",
  ],
  skirt: [
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "      ............      ",
    "     .tttttttttttt.     ",
    "     .tttttttttttt.     ",
    "     .OooOoooooxx#.     ",
    "     .OooOooxooxx#.     ",
    "     .Ooooooxooxx#.     ",
    "    .OooOooooxooox#.    ",
    "    .OooOooooxooxx#.    ",
    "    .OooOoooooooxx#.    ",
    "   .OoooOooooxooxox#.   ",
    "   .Ooooooooooxooxx#.   ",
    "   .OooOooooooxooox#.   ",
    "   .OooOooooooxooxx#.   ",
    "  .OoooOoooooooooxox#.  ",
    "  .OooOooooooooxooxx#.  ",
    "  .Ooooooooooooxooxx#.  ",
    " .xxxxOxxxxxxxxxxxxxx#. ",
    " .tttttttttttttttttttt. ",
    "  ....................  ",
  ],
  wrap: [
    "                        ",
    "                        ",
    "                        ",
    "    ................    ",
    "   .tttttttttttttttt.   ",
    "   .tttttttttttttttt.   ",
    "   .OooooOoooxoooox#.   ",
    "   .OooooOoooxoooxx#.   ",
    "   .OooooOoooooooxx#.   ",
    "   .OooooOoooxoooxx#.   ",
    "   .Oooooooooxoooxx#.   ",
    "   .OooooOoooxoooox#.   ",
    "   .OooooOoooxoooxx#.   ",
    "    .OooooOoooooxx#.    ",
    "    .OooooOoxoooxx#.    ",
    "    .Oooooooxoooxx#.    ",
    "    .OooooOoxoooox#.    ",
    "    .OooooOoxoooxx#.    ",
    "    .OooooOoooooxx#.    ",
    "    .xxxxxOxxxxxxx#.    ",
    "    .tttttttttttttt.    ",
    "     ..............     ",
    "                        ",
    "                        ",
  ],
  poncho: [
    "                        ",
    "                        ",
    "    .....      .....    ",
    "  ..Oooo#......Oooo#..  ",
    "..Ooooox#......Ooooox#..",
    "Oooooooox#....Oooooooox#",
    "Ooooooooo######ooooooox#",
    "Oooooooooooooooooooooox#",
    "....Oooooooooooooox#....",
    "   .Oooooooooooooox#.   ",
    "   .Oooooooooooooox#.   ",
    "   .Oooooooooooooox#.   ",
    "   .Oooooooooooooox#.   ",
    "   .Oooooooooooooox#.   ",
    "  .Oooooooooooooooox#.  ",
    "  .Oooooooooooooooox#.  ",
    "  .Oooooooooooooooox#.  ",
    "  .xxxxxxxxxxxxxxxxx#.  ",
    "  .tttttttttttttttttt.  ",
    "  .Oooooooooooooooox#.  ",
    "   ..................   ",
    "                        ",
    "                        ",
    "                        ",
  ],
  loincloth: [
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "    ................    ",
    "   .Oooooooooooooox#.   ",
    "   .tttttttttttttttt.   ",
    "   .tttttttttttttttt.   ",
    "    .Oooooooooooox#.    ",
    "    .Oooo::::::oox#.    ",
    "     .Oooooooooox#.     ",
    "     .Oooo::::oox#.     ",
    "      .Oooooooox#.      ",
    "      .Oooo::oox#.      ",
    "       .Oooooox#.       ",
    "        .Ooooo#.        ",
    "         .Oooo.         ",
    "          ....          ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
  ],
  suit: [
    "        ........        ",
    "      ..mmmmmmmm..      ",
    "     .mmmmmmmmmmmm.     ",
    "   ...Oooooooooox#...   ",
    "  .Oooooooooooooooox#.  ",
    " .Oooooooooooooooooox#. ",
    ".Oooooo::::::::::oooox#.",
    ".Ooooo::mmmmmmmm::ooox#.",
    ".Ooooo::mMMMMMMm::ooox#.",
    ".Ooooo::mmmmmmmm::ooox#.",
    ".Oooooo::::::::::oooox#.",
    " .Oooooooooooooooooox#. ",
    " .Ooooooooooooooooox#.  ",
    "  .tttttttttttttttt..   ",
    "  .Oooooooooooooox#.    ",
    "  .Ooooox#..Ooooox#.    ",
    "  .Ooooo#.  .Ooooo#.    ",
    "  .Ooooo#.  .Ooooo#.    ",
    "  .mmmmmm.  .mmmmmm.    ",
    "   ......    ......     ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
  ],
  // ── over ──────────────────────────────────────────────────────────────
  cloak: [
    "                        ",
    "                        ",
    "        ........        ",
    "      ..Oooooox#..      ",
    "    ..Oooooooooox#..    ",
    "   .Oooooooooooooox#.   ",
    "   .OoooOooOoooooox#.   ",
    "   .OoooOooOoooxoox#.   ",
    "    ..OoOooooooxx#..    ",
    "    .OooOooOoooxox#.    ",
    "    .OooooOoooooxx#.    ",
    "    .OoOooOoooooox#.    ",
    "   .OooOooOoooooxox#.   ",
    "   .OooOooooooooxox#.   ",
    "   .OooOooOoooooxox#.   ",
    "   .OooooOoooooooxx#.   ",
    "   .OoOooOoooooooox#.   ",
    "  .OooOooOoooooooxox#.  ",
    "  .OooOooooooooooxox#.  ",
    "  .OooOooOoooooooxox#.  ",
    " .xxxxxxxOxxxxxxxxxxx#. ",
    " .tttttttttttttttttttt. ",
    " .Oooooooooooooooooox#. ",
    "  ....................  ",
  ],
  "shoulder-cloth": [
    "                        ",
    "   ......        ...... ",
    "  .Ooooo#.      .Ooooo#.",
    "  .Ooooo#.      .Ooooo#.",
    "   .Ooooo#.    .Ooooo#. ",
    "   .Ooooo#.    .Ooooo#. ",
    "    .Ooooo#.  .Ooooo#.  ",
    "    .Ooooo#....Ooooo#.  ",
    "     .Oooooooooooox#.   ",
    "     .Oooooooooooox#.   ",
    "      .Oooooooooox#.    ",
    "      .Oooo::::oox#.    ",
    "       .Oooooooox#.     ",
    "       .tttttttttt.     ",
    "       .tttttttttt.     ",
    "        ..........      ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
  ],
  // ── head ──────────────────────────────────────────────────────────────
  band: [
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "     ..............     ",
    "    .Oooooooooooox#.    ",
    "    .Otttttttttttt#.    ",
    "    .Oooooooooooox#.    ",
    "     ..............     ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
  ],
  cap: [
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "          ....          ",
    "        ..Oooo..        ",
    "      ..Oooooox#..      ",
    "     .Oooooooooox#.     ",
    "    .Oooooooooooox#.    ",
    "   .Oooooooooooooox#.   ",
    "  .Oooooooooooooooox#.  ",
    "  .Oooooooooooooooox#.  ",
    "  .tttttttttttttttttt.  ",
    "  .tttttttttttttttttt.  ",
    "   ..................   ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
  ],
  hood: [
    "                 ...    ",
    "              ...Ooo.   ",
    "           ...Ooooo#.   ",
    "        ...Ooooooox#.   ",
    "      ..Ooooooooooox#.  ",
    "     .Oooooooooooooox#. ",
    "    .Ooooo::ooooooox#.  ",
    "   .Oooo::ooooooooox#.  ",
    "  .Ooooo::oooooooox#.   ",
    "  .Oooo::ooooooooox#.   ",
    "  .Ooooooooooooooox#.   ",
    "   .Oooooooooooooox#.   ",
    "    .tttttttttttttt.    ",
    "    .tttttttttttttt.    ",
    "     ..............     ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
  ],
  "wrap_head": [
    "                        ",
    "        ........        ",
    "      ..Oooooox#..      ",
    "     .Oooooooooox#.     ",
    "    .Ooo::oooooox#.     ",
    "   .Oooo::ooooooox#.    ",
    "   .Ooooo::oooooox#.    ",
    "   .Oooooo::ooooox#.    ",
    "   .Ooooooo::oooox#.    ",
    "    .Ooooooo::ooox#.    ",
    "     .Ooooooo::ox#.     ",
    "      .Oooooooox#.      ",
    "       ..........       ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
  ],
  turban: [
    "                        ",
    "                        ",
    "         ......         ",
    "      ...Ooooo#...      ",
    "    ..Oooooooooox#..    ",
    "   .Oooooooooooooox#.   ",
    "   .Oooooooooooooox#.   ",
    "   .Oo::::::::::::x#.   ",
    "   .Oooooooooooooox#.   ",
    "   .Oo::::::::::::x#.   ",
    "   .Oooooooooooooox#.   ",
    "    .Oooooooooooox#.    ",
    "     .Oooooooooox#.     ",
    "      ............      ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
  ],
  headscarf: [
    "                        ",
    "                        ",
    "        ........        ",
    "      ..Oooooox#..      ",
    "     .Oooooooooox#.     ",
    "    .Oooooooooooox#.    ",
    "   .Oooooooooooooox#.   ",
    "   .Oooooooooooooox#.   ",
    "    .Oooooooooooox#.    ",
    "     .Oooooooooox#.     ",
    "      .Oooooooox#.      ",
    "       .Oooooox#.       ",
    "        .Ooooo#.        ",
    "         .Oooo.         ",
    "          ....          ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
  ],
  veil: [
    "                        ",
    "        ........        ",
    "      ..Oooooox#..      ",
    "     .Oooooooooox#.     ",
    "    .Oooooooooooox#.    ",
    "    .O:o:o:o:o:o:x#.    ",
    "    .Oooooooooooox#.    ",
    "    .O:o:o:o:o:o:x#.    ",
    "    .Oooooooooooox#.    ",
    "    .O:o:o:o:o:o:x#.    ",
    "    .Oooooooooooox#.    ",
    "     .O:o:o:o:o:#..     ",
    "     .Oooooooooox#.     ",
    "      ............      ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
  ],
  brimmed: [
    "                        ",
    "                        ",
    "                        ",
    "        ........        ",
    "       .Oooooox#.       ",
    "      .Oooooooox#.      ",
    "     .Oooooooooox#.     ",
    "     .Oooooooooox#.     ",
    "     .tttttttttttt.     ",
    "  ....tttttttttttt....  ",
    " .Oooooooooooooooooox#. ",
    ".Oooooooooooooooooooox#.",
    "Oooooooooooooooooooooox#",
    "..Oooooooooooooooooox#..",
    "  ....................  ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
  ],
  conical: [
    "                        ",
    "           ..           ",
    "          .Oo.          ",
    "         .Oooo.         ",
    "         .Oooo.         ",
    "        .Ooooo#.        ",
    "       .Oooooox#.       ",
    "      .Oooooooox#.      ",
    "     .Oooooooooox#.     ",
    "    .Oooooooooooox#.    ",
    "   .Oooooooooooooox#.   ",
    "  .Oooooooooooooooox#.  ",
    " .Oooooooooooooooooox#. ",
    " .Oooooooooooooooooox#. ",
    "  ....................  ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
  ],
  bowler: [
    "                        ",
    "                        ",
    "                        ",
    "         ......         ",
    "       ..Ooooo#..       ",
    "      .Oooooooox#.      ",
    "     .Oooooooooox#.     ",
    "     .Oooooooooox#.     ",
    "     .Oooooooooox#.     ",
    "     .tttttttttttt.     ",
    "   ...tttttttttttt...   ",
    "  .Oooooooooooooooox#.  ",
    " .Oooooooooooooooooox#. ",
    "  .Oooooooooooooooox#.  ",
    "   ..................   ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
  ],
  "flat-cap": [
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "        ........        ",
    "      ..Oooooox#..      ",
    "    ..Oooooooooox#..    ",
    "   .Oooooooooooooox#.   ",
    "  .Oooooooooooooooox#.  ",
    "  .Oooooooooooooooox#.  ",
    " .Ooooooooooooooooox#.  ",
    " .xxxxxxxxxxxxxxx#...   ",
    "  .xxxxxxxxxxxx#..      ",
    "   .............        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
  ],
  "ball-cap": [
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "         ......         ",
    "       ..Ooooo#..       ",
    "      .Oooooooox#.      ",
    "     .Oooooooooox#.     ",
    "    .Oooooooooooox#.    ",
    "    .Ottttttttttx#.     ",
    "    .Oooooooooox#...    ",
    "    .xxxxxxxxxxxxxx#.   ",
    "     .xxxxxxxxxxxx#.    ",
    "      .............     ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
  ],
  fez: [
    "                        ",
    "       ..........       ",
    "      .Oooooooox#.      ",
    "      .Oooooooox#.      ",
    "     .Oooooooooox#.     ",
    "     .Oooooooooox#.     ",
    "     .Oooooooooox#.     ",
    "     .Oooooooooox#.     ",
    "    .Oooooooooooox#.    ",
    "    .Oooooooooooox#.    ",
    "    .tttttttttttttt.    ",
    "    .tttttttttttttt.    ",
    "     ..............     ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
  ],
  fillet: [
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "     ..............     ",
    "    .mmmmmmmmmmmmmm.    ",
    "    .mmmMmmmmmmMmmm.    ",
    "    .mmmmmmmmmmmmmm.    ",
    "     ..............     ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
  ],
  plume: [
    "                  ..    ",
    "                ..OO.   ",
    "              ..OOO.    ",
    "             .OOO..     ",
    "            .OO..       ",
    "           .OO.         ",
    "          .OO.          ",
    "      ....Oo...         ",
    "    ..Ooooooox#..       ",
    "   .Ooooooooooox#.      ",
    "  .Ooooooooooooox#.     ",
    "  .tttttttttttttt#..    ",
    " .Oooooooooooooooox#.   ",
    "  .Oooooooooooooox#.    ",
    "   ................     ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
  ],
  wig: [
    "                        ",
    "         ......         ",
    "       ..Ooooo#.        ",
    "      .Ooooooox#.       ",
    "     .Oooo::ooox#..     ",
    "    .Oooooo::oooox#.    ",
    "   .Oooooooooooooox#.   ",
    "  .Oooooooooooooooox#.  ",
    "  .Oo::oooooooooo::x#.  ",
    "  .Oooooooooooooooox#.  ",
    "  .Oo::oooooooooo::x#.  ",
    "   .Oooooooooooooox#.   ",
    "    ..Oooo::::oox#..    ",
    "      ...Ooooo#...      ",
    "         .Oooo.         ",
    "          ....          ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
  ],
  helmet: [
    "                        ",
    "         ......         ",
    "       ..mmmmmm..       ",
    "      .mmmmmmmmmm.      ",
    "     .mmmmmmmmmmmm.     ",
    "    .mmmmmmmmmmmmmm.    ",
    "    .mmm........mmm.    ",
    "    .mm.        .mm.    ",
    "    .mm.        .mm.    ",
    "    .mmm.      .mmm.    ",
    "    .mmmm......mmmm.    ",
    "    .mmmmmmmmmmmmmm.    ",
    "     .mmmmmmmmmmmm.     ",
    "      ............      ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
  ],
  visor: [
    "                        ",
    "         ......         ",
    "       ..Ooooo#..       ",
    "      .Oooooooox#.      ",
    "     .Oooooooooox#.     ",
    "    .Oooooooooooox#.    ",
    "    .Oo..........Oo.    ",
    "    .Om..mmmmmm..mo.    ",
    "    .Om..mmmmmm..mo.    ",
    "    .Oo..........Oo.    ",
    "    .Oooooooooooox#.    ",
    "     .Oooooooooox#.     ",
    "      .tttttttttt.      ",
    "       ..........       ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
  ],
  // ── legs ──────────────────────────────────────────────────────────────
  trousers: [
    "                        ",
    "                        ",
    "                        ",
    "      ............      ",
    "     .tttttttttttt.     ",
    "     .tttttttttttt.     ",
    "     .Oooooooooox#.     ",
    "     .Oooooooooox#.     ",
    "     .Oooo#..Oooo#.     ",
    "     .Oooo#..Oooo#.     ",
    "     .Oooo#..Oooo#.     ",
    "     .Oooo#..Oooo#.     ",
    "     .Oooo#..Oooo#.     ",
    "     .Oooo#..Oooo#.     ",
    "     .Oooo#..Oooo#.     ",
    "     .Oooo#..Oooo#.     ",
    "     .Oooo#..Oooo#.     ",
    "     .Oooo#..Oooo#.     ",
    "     .Oooo#..Oooo#.     ",
    "     .Oooo#..Oooo#.     ",
    "     .Oooo#..Oooo#.     ",
    "     .Oooo.  .Oooo.     ",
    "      ....    ....      ",
    "                        ",
  ],
  wide: [
    "                        ",
    "                        ",
    "                        ",
    "      ............      ",
    "     .tttttttttttt.     ",
    "     .tttttttttttt.     ",
    "     .Oooooooooox#.     ",
    "     .Oooooooooox#.     ",
    "     .Oooo#..Oooo#.     ",
    "     .Oooo#..Oooo#.     ",
    "     .Oooo#..Oooo#.     ",
    "     .Oooo#..Oooo#.     ",
    "    .Ooooo#..Ooooo#.    ",
    "    .Ooooo#..Ooooo#.    ",
    "    .Ooooo#..Ooooo#.    ",
    "    .Ooooo#..Ooooo#.    ",
    "    .Ooooo#..Ooooo#.    ",
    "   .Ooooox#..Ooooox#.   ",
    "   .Ooooox#..Ooooox#.   ",
    "   .Ooooox#..Ooooox#.   ",
    "   .Ooooox#..Ooooox#.   ",
    "   .Ooooo#.  .Ooooo#.   ",
    "    ......    ......    ",
    "                        ",
  ],
  hose: [
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "       ..........       ",
    "      .tttttttttt.      ",
    "      .tttttttttt.      ",
    "      .Oooooooox#.      ",
    "      .Oooooooox#.      ",
    "      .Oooo..Oooo.      ",
    "      .Oooo..Oooo.      ",
    "       .Ooo..Ooo.       ",
    "       .Ooo..Ooo.       ",
    "       .Ooo..Ooo.       ",
    "       .Ooo..Ooo.       ",
    "       .Ooo..Ooo.       ",
    "       .Ooo..Ooo.       ",
    "       .Ooo..Ooo.       ",
    "       .Ooo..Ooo.       ",
    "       .Ooo..Ooo.       ",
    "       .Ooo..Ooo.       ",
    "       .Ooo..Ooo.       ",
    "        ...  ...        ",
    "                        ",
  ],
  wrapped: [
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "      ............      ",
    "     .tttttttttttt.     ",
    "     .tttttttttttt.     ",
    "     .Oooooooooox#.     ",
    "     .Oooooooooox#.     ",
    "      .Oooo..Oooo.      ",
    "      .xxxx..xxxx.      ",
    "      .Oooo..Oooo.      ",
    "      .Oooo..Oooo.      ",
    "      .xxxx..xxxx.      ",
    "      .Oooo..Oooo.      ",
    "      .Oooo..Oooo.      ",
    "      .xxxx..xxxx.      ",
    "      .Oooo..Oooo.      ",
    "      .Oooo..Oooo.      ",
    "      .xxxx..xxxx.      ",
    "      .Oooo..Oooo.      ",
    "      .Oooo..Oooo.      ",
    "       ....  ....       ",
    "                        ",
  ],
  sarong: [
    "                        ",
    "                        ",
    "                        ",
    "    ................    ",
    "   .tttttttttttttttt.   ",
    "   .tttttttttttttttt.   ",
    "   .OoooOoooxooooox#.   ",
    "   .OoooOoooxoooxox#.   ",
    "   .OoooOoooooooxox#.   ",
    "   .OoooOoooxoooxox#.   ",
    "   .Ooooooooxoooxox#.   ",
    "   .OoooOoooxooooox#.   ",
    "   .OoooOoooxoooxox#.   ",
    "   .OoooOoooooooxox#.   ",
    "   .OooOoooooxoooxx#.   ",
    "   .Oooooooooxoooxx#.   ",
    "   .OooOoooooxoooox#.   ",
    "   .OooOoooooxoooxx#.   ",
    "   .OooOoooooooooxx#.   ",
    "   .OooOoooooxoooxx#.   ",
    "   .xxxxxxxxxxxxxxx#.   ",
    "   .tttttttttttttttt.   ",
    "    ................    ",
    "                        ",
  ],
  // ── feet ──────────────────────────────────────────────────────────────
  sandals: [
    "                        ",
    "                        ",
    "      ..        ..      ",
    "     .tt.      .tt.     ",
    "   ...ttt.    .ttt...   ",
    "  .kkkkttt.  .tttkkkk.  ",
    " .kkkkkkttt..tttkkkkkk. ",
    " .kkkkkkkttttttkkkkkkk. ",
    " .kkkkkkkkktttkkkkkkkk. ",
    " .kkkkkkkkkkkkkkkkkkkk. ",
    " .KKKKKKKKKKKKKKKKKKKK. ",
    "  .kkkkkkkkkkkkkkkkkk.  ",
    "   .kkkkkkkkkkkkkkkk.   ",
    "    .KKKKKKKKKKKKKK.    ",
    "     ..............     ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
  ],
  shoes: [
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "         ........       ",
    "       ..Oooooox#..     ",
    "      .Oooooooooox#.    ",
    "     .Oooooooooooox#.   ",
    "    .Ootttttoooooox#.   ",
    "   .Oooooooooooooox#.   ",
    "  .Ooooooooooooooox#.   ",
    " .kkkkkkkkkkkkkkkkkk.   ",
    " .KKKKKKKKKKKKKKKKKK.   ",
    "  .kkkkkkkkkkkkkkkk.    ",
    "   ................     ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
  ],
  boots: [
    "     ........           ",
    "    .tttttttt.          ",
    "    .Oooooox#.          ",
    "    .Oooooox#.          ",
    "    .Oooooox#.          ",
    "    .Oooooox#.          ",
    "    .Oooooox#.          ",
    "    .Oooooox#.          ",
    "    .Oooooox#...        ",
    "    .Ooooooooox#..      ",
    "    .Ooooooooooox#..    ",
    "   .Oooooooooooooox#.   ",
    "   .kkkkkkkkkkkkkkkk.   ",
    "   .KKKKKKKKKKKKKKKK.   ",
    "    ................    ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
  ],
  sneakers: [
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "          ......        ",
    "        ..Oooox#.       ",
    "       .Oootoooox.      ",
    "      .Ooottoooox#.     ",
    "    ..Oootttooooox.     ",
    "   .Oooottooooooox#.    ",
    "  .Ooooooooooooooox.    ",
    " .MMMMMMMMMMMMMMMMMM.   ",
    " .mmmmmmmmmmmmmmmmmm.   ",
    "  ..................    ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
  ],
  // ── belt ──────────────────────────────────────────────────────────────
  cord: [
    "                        ",
    "       ..........       ",
    "     ..Oo::oo::x#..     ",
    "    .Oo::oo::oo::x#..   ",
    "   .Oo::oo::oo::oo:x#.  ",
    "  .Oo::oo::oo::oo::x#.  ",
    "  .Oo::oo::oo::oo::x#.  ",
    "   .Oo::oo::oo::oo:x#.  ",
    "    .Oo::oo::oo::x#..   ",
    "     ...Ooooox#....     ",
    "       .Oo:::x#.        ",
    "        .Oo:o#.         ",
    "        .O::o.          ",
    "        .O::o.          ",
    "       .Oo::o#.         ",
    "        .O::o.          ",
    "         ....           ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
  ],
  sash: [
    "                        ",
    "                        ",
    "  ....................  ",
    " .Oooooooooooooooooox#. ",
    " .Oooooooooooooooooox#. ",
    " .Oooo::::::::::::oox#. ",
    " .Oooooooooooooooooox#. ",
    " .Ooooooooo::ooooooox#. ",
    "  ....Ooooooooox#.....  ",
    "      .Ooooooox#.       ",
    "       .Ooooox#.        ",
    "       .Oo::ox#.        ",
    "       .Ooooox#.        ",
    "       .Oo::ox#.        ",
    "        .Oooo#.         ",
    "         .Ooo.          ",
    "          ...           ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
  ],
  leather: [
    "                        ",
    "                        ",
    "                        ",
    "   ..................   ",
    "  .kkkkkkkkkkkkkkkkkk.  ",
    "  .kkkkkkkmmmmkkkkkkk.  ",
    "  .kkkkkkkmMMmkkkkkkk.  ",
    "  .kkkkkkkmmmmkkkkkkk.  ",
    "  .KKKKKKKKKKKKKKKKKK.  ",
    "   ..................   ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
  ],
  "belt-wide": [
    "                        ",
    "                        ",
    "   ..................   ",
    "  .kkkkkkkkkkkkkkkkkk.  ",
    "  .kkkkkkkkkkkkkkkkkk.  ",
    "  .kkkkkkmmmmmmkkkkkk.  ",
    "  .kkkkkkmMMMMmkkkkkk.  ",
    "  .kkkkkkmmmmmmkkkkkk.  ",
    "  .kkkkkkkkkkkkkkkkkk.  ",
    "  .KKKKKKKKKKKKKKKKKK.  ",
    "   ..................   ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
  ],
  // ── jewellery ─────────────────────────────────────────────────────────
  necklace: [
    "                        ",
    "      ..      ..        ",
    "    ..mm.    .mm..      ",
    "   .mm..      ..mm.     ",
    "  .mm.          .mm.    ",
    " .mm.            .mm.   ",
    " .mm.            .mm.   ",
    "  .mm.          .mm.    ",
    "   .mm.        .mm.     ",
    "    .mm.  ..  .mm.      ",
    "     .mm..MM..mm.       ",
    "      ..mMMMMm..        ",
    "        .MMMM.          ",
    "         .MM.           ",
    "          ..            ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
  ],
  chain: [
    "                        ",
    "    ..            ..    ",
    "   .Mm.          .mM.   ",
    "   .mM.          .Mm.   ",
    "    .Mm.        .mM.    ",
    "    .mM.        .Mm.    ",
    "     .Mm.      .mM.     ",
    "      .mM.    .Mm.      ",
    "       .MmMmMmMm.       ",
    "        ........        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
  ],
  glasses: [
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "  ....................  ",
    " .  ......    ......  . ",
    " . .      .  .      . . ",
    "   .      ....      .   ",
    "   .      .  .      .   ",
    "    ......    ......    ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
  ],
  sunglasses: [
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "  ....................  ",
    " . ........  ........ . ",
    " . ..MM....  ..MM.... . ",
    "  ..........  ........  ",
    "   ........    ........ ",
    "    ......      ......  ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
  ],
  earrings: [
    "                        ",
    "                        ",
    "     ...        ...     ",
    "    .mmm.      .mmm.    ",
    "    .mMm.      .mMm.    ",
    "    .mmm.      .mmm.    ",
    "     .m.        .m.     ",
    "     .m.        .m.     ",
    "    .mmm.      .mmm.    ",
    "   .mMMMm.    .mMMMm.   ",
    "   .mMMMm.    .mMMMm.   ",
    "    .mmm.      .mmm.    ",
    "     ...        ...     ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
  ],
};
