/**
 * Item icons, on the same twenty-four-pixel grid and the same light as the
 * garments. An item is not cloth, so each one carries its own two colours:
 * the body, and the accent that `t`/`T` draw in.
 *
 * Edit the art in scripts/garment_art/items.py, not here.
 */
import type { IconArt } from "./garment-art";

export const itemColors: Record<string, readonly [string, string]> = {
  "acorn": ["#a97a44", "#6b4a28"],
  "annatto": ["#c83a1c", "#7a3a20"],
  "bark": ["#7a5636", "#a88050"],
  "bast": ["#c8b88a", "#9a8a60"],
  "berries": ["#8e3a5c", "#5d8a3a"],
  "bread": ["#c08a45", "#e0b36a"],
  "bulbs": ["#d8c8b0", "#8a6aa8"],
  "cane": ["#9aa85c", "#6d7a3c"],
  "cannabis": ["#5a7a30", "#8aa848"],
  "capers": ["#6a8a40", "#4a6a2c"],
  "chamomile": ["#f4f1e6", "#e8c030"],
  "chilies": ["#d0301c", "#5d8a3a"],
  "clay": ["#a4674a", "#7c4a32"],
  "coca": ["#4a7a34", "#7aa850"],
  "coffee": ["#b02a20", "#4a6a2c"],
  "coin": ["#c9a24a", "#8a6a24"],
  "cooked-meat": ["#8a4a2a", "#e8d8bc"],
  "copper-ore": ["#8a8680", "#c87a44"],
  "copper-ore-poor": ["#8a8680", "#c87a44"],
  "copper-ore-rich": ["#8a8680", "#c87a44"],
  "cotton": ["#f2efe6", "#8a7a5a"],
  "cow-dung": ["#5a4228", "#7a5e3a"],
  "dirt": ["#6e5540", "#4d3a2c"],
  "dry-horse-dung": ["#a89868", "#c8b888"],
  "dung-cake": ["#a09070", "#7e6e52"],
  "dung-pellets": ["#3a2e20", "#5a4a34"],
  "ephedra": ["#7a8a4a", "#5a6a34"],
  "feathers": ["#efe9da", "#9a8f7a"],
  "fish": ["#9aa6ae", "#6a757d"],
  "flax": ["#9fb08a", "#8a7fc0"],
  "flint": ["#5c5a52", "#c8c4b4"],
  "fodder": ["#93a05a", "#6f7c3e"],
  "frond": ["#5f8f46", "#3f6a30"],
  "fruit": ["#c04a3c", "#5d8a3a"],
  "gold-ore": ["#8a8680", "#e8c030"],
  "gold-ore-poor": ["#8a8680", "#e8c030"],
  "gold-ore-rich": ["#8a8680", "#e8c030"],
  "goldenrod": ["#a8a048", "#e8c830"],
  "grain": ["#d6b96a", "#8c7a3a"],
  "granite": ["#8c8890", "#d8d4dc"],
  "grass-fibre": ["#c8c090", "#908a58"],
  "greens": ["#6a9a40", "#9cc860"],
  "gromwell": ["#6a3060", "#4a2040"],
  "henna": ["#6a7a38", "#a8602c"],
  "herbs": ["#5d8a3a", "#a8c060"],
  "hide": ["#8a5a36", "#c49a6c"],
  "horse-dung": ["#6a5a2e", "#8a7a44"],
  "indigo": ["#3a4a88", "#5a6ab0"],
  "iron-ore": ["#8a8680", "#9a5634"],
  "iron-ore-poor": ["#8a8680", "#9a5634"],
  "iron-ore-rich": ["#8a8680", "#9a5634"],
  "khat": ["#5a7a3a", "#8a5a3a"],
  "limestone": ["#cfc8b4", "#a49c88"],
  "lizard": ["#7d8f4a", "#4f5c2a"],
  "madder": ["#a8402c", "#7a2a1c"],
  "meat": ["#b8453a", "#ecdcc4"],
  "mud": ["#5f4a36", "#3f3124"],
  "mushroom": ["#b07a5c", "#e0d2b8"],
  "obsidian": ["#3a3444", "#6f6580"],
  "ore": ["#8a8680", "#b87444"],
  "ore-poor": ["#8a8680", "#b87444"],
  "ore-rich": ["#8a8680", "#b87444"],
  "papyrus": ["#8aa84a", "#5a7a2c"],
  "pebble": ["#a8a094", "#7a746a"],
  "pinecone": ["#7a5a38", "#5a4028"],
  "pituri": ["#7a7a44", "#5a5a30"],
  "poppy-pods": ["#8aa888", "#6a5080"],
  "reeds": ["#9aa85c", "#6d7a3c"],
  "resin": ["#d09a3a", "#f0c86a"],
  "river-rock": ["#8e9aa0", "#666f74"],
  "roots": ["#a07a4c", "#6a8a3a"],
  "roselle": ["#a01c34", "#5d8a3a"],
  "rushes": ["#6f8a44", "#4f6a30"],
  "safflower": ["#e8801c", "#e8c040"],
  "saffron": ["#b83018", "#e05030"],
  "sand": ["#d8c48c", "#b09a62"],
  "seeds": ["#b89a5c", "#7a6438"],
  "shell": ["#e0cdb4", "#b09070"],
  "silver-ore": ["#8a8680", "#e0e4ec"],
  "silver-ore-poor": ["#8a8680", "#e0e4ec"],
  "silver-ore-rich": ["#8a8680", "#e0e4ec"],
  "stick": ["#8a6a44", "#5e462c"],
  "stone": ["#9a9690", "#6e6b66"],
  "straw": ["#cdb46a", "#9c8340"],
  "tea": ["#3f6a30", "#6a9a40"],
  "tin-ore": ["#8a8680", "#c8c8c0"],
  "tin-ore-poor": ["#8a8680", "#c8c8c0"],
  "tin-ore-rich": ["#8a8680", "#c8c8c0"],
  "tobacco": ["#8a8a44", "#6a5a30"],
  "tool": ["#b8bdc4", "#6b4a2e"],
  "torch": ["#8a6a44", "#e08a2c"],
  "turmeric": ["#e0a020", "#a8701c"],
  "water": ["#b06a44", "#5a89b0"],
  "weld": ["#a8b040", "#e0d040"],
  "woad": ["#5a8a6a", "#3a5a8a"],
  "wood": ["#8a6038", "#5c3f24"],
  "wool": ["#e2ded0", "#b9b3a0"],
};

export const itemArt: Record<string, IconArt> = {
  "acorn": [
    "                        ",
    "                        ",
    "           .            ",
    "       ....t...         ",
    "      .tttttttt.        ",
    "     .tttttttttt.       ",
    "     .tttttttttt.       ",
    "      .Oooooox#.        ",
    "      .Oooooox#.        ",
    "      .Oooooox#.        ",
    "       .Ooooo#.         ",
    "        .Oooo.          ",
    "         .Oo.           ",
    "          ..            ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
  ],
  "annatto": [
    "                        ",
    "          ..            ",
    "         .tt.           ",
    "       ..tt.            ",
    "      .Oooo.   ....     ",
    "     .Oo::o#. .Oooo.    ",
    "     .Ooooo#..Oo::o#.   ",
    "      .Oooo. .Ooooo#.   ",
    "       .Oooo. .Oooo.    ",
    "      .Oo::o#. ....     ",
    "      .Ooooo#..Oooo.    ",
    "       .Oooo..Oo::o#.   ",
    "        .... .Ooooo#.   ",
    "              .Oooo.    ",
    "               ....     ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
  ],
  "bark": [
    "                        ",
    "                        ",
    "      .......           ",
    "    ..Ooooox#.          ",
    "   .Oooooooox#.         ",
    "  .Oootttttoox#.        ",
    "  .Ooottttttoox#.       ",
    "  .Oootttttttoox#.      ",
    "   .Oootttttttox#.      ",
    "    .Oooooooooox#.      ",
    "     ..Ooooooox#.       ",
    "       ..Ooooo#.        ",
    "         ......         ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
  ],
  "bast": [
    "                        ",
    "      .    .    .       ",
    "     .t.  .t.  .t.      ",
    "    .ttt..ttt..ttt.     ",
    "     .t.  .t.  .t.      ",
    "     .O.  .O.  .O.      ",
    "     .Oo. .O. .Oo.      ",
    "      .O. .O. .O.       ",
    "      .Oo..O..Oo.       ",
    "       .O..O..O.        ",
    "       .Ooooo#.         ",
    "        .O.O.O.         ",
    "       .O..O..O.        ",
    "      .O. .O. .O.       ",
    "       .   .   .        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
  ],
  "berries": [
    "                        ",
    "          ..            ",
    "         .tt.           ",
    "       ..tt.            ",
    "      .Oooo.   ....     ",
    "     .Oo::o#. .Oooo.    ",
    "     .Ooooo#..Oo::o#.   ",
    "      .Oooo. .Ooooo#.   ",
    "       .Oooo. .Oooo.    ",
    "      .Oo::o#. ....     ",
    "      .Ooooo#..Oooo.    ",
    "       .Oooo..Oo::o#.   ",
    "        .... .Ooooo#.   ",
    "              .Oooo.    ",
    "               ....     ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
  ],
  "bread": [
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "      ..........        ",
    "    ..Oooooooox#..      ",
    "   .Oooooooooooox#.     ",
    "  .Oooooooooooooox#.    ",
    " .Oooo:oooo:oooo:ox#.   ",
    " .Ooo:oooo:oooo:oox#.   ",
    " .Oooooooooooooooox#.   ",
    "  .Oooooooooooooox#.    ",
    "   .Oooooooooooox#.     ",
    "    ..Oooooooox#..      ",
    "      ..........        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
  ],
  "bulbs": [
    "                        ",
    "                        ",
    "           .            ",
    "       ....t...         ",
    "      .tttttttt.        ",
    "     .tttttttttt.       ",
    "     .tttttttttt.       ",
    "      .Oooooox#.        ",
    "      .Oooooox#.        ",
    "      .Oooooox#.        ",
    "       .Ooooo#.         ",
    "        .Oooo.          ",
    "         .Oo.           ",
    "          ..            ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
  ],
  "cane": [
    "         ....           ",
    "        .Oooo.          ",
    "        .Oooo.          ",
    "        .tttt.          ",
    "        .Oooo.          ",
    "        .Oooo.          ",
    "        .Oooo.          ",
    "        .tttt.          ",
    "        .Oooo.          ",
    "        .Oooo.          ",
    "        .Oooo.          ",
    "        .tttt.          ",
    "        .Oooo.          ",
    "        .Oooo.          ",
    "        .Oooo.          ",
    "         ....           ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
  ],
  "cannabis": [
    "                        ",
    "        .               ",
    "      ..t.              ",
    "     .Ooot.    .        ",
    "    .Ooooo#. ..t.       ",
    "     .Oooo. .Ooot.      ",
    "      .Oo. .Oooo#.      ",
    "      .Oo.  .Oooo.      ",
    "       .Oo...Oo..       ",
    "        .Oooo#.         ",
    "         .Ooo.          ",
    "         .Ooo.          ",
    "        .Oooo#.         ",
    "         .....          ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
  ],
  "capers": [
    "                        ",
    "          ..            ",
    "         .tt.           ",
    "       ..tt.            ",
    "      .Oooo.   ....     ",
    "     .Oo::o#. .Oooo.    ",
    "     .Ooooo#..Oo::o#.   ",
    "      .Oooo. .Ooooo#.   ",
    "       .Oooo. .Oooo.    ",
    "      .Oo::o#. ....     ",
    "      .Ooooo#..Oooo.    ",
    "       .Oooo..Oo::o#.   ",
    "        .... .Ooooo#.   ",
    "              .Oooo.    ",
    "               ....     ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
  ],
  "chamomile": [
    "                        ",
    "          ..            ",
    "         .tt.           ",
    "       ..tt.            ",
    "      .Oooo.   ....     ",
    "     .Oo::o#. .Oooo.    ",
    "     .Ooooo#..Oo::o#.   ",
    "      .Oooo. .Ooooo#.   ",
    "       .Oooo. .Oooo.    ",
    "      .Oo::o#. ....     ",
    "      .Ooooo#..Oooo.    ",
    "       .Oooo..Oo::o#.   ",
    "        .... .Ooooo#.   ",
    "              .Oooo.    ",
    "               ....     ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
  ],
  "chilies": [
    "                        ",
    "          ..            ",
    "         .tt.           ",
    "       ..tt.            ",
    "      .Oooo.   ....     ",
    "     .Oo::o#. .Oooo.    ",
    "     .Ooooo#..Oo::o#.   ",
    "      .Oooo. .Ooooo#.   ",
    "       .Oooo. .Oooo.    ",
    "      .Oo::o#. ....     ",
    "      .Ooooo#..Oooo.    ",
    "       .Oooo..Oo::o#.   ",
    "        .... .Ooooo#.   ",
    "              .Oooo.    ",
    "               ....     ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
  ],
  "clay": [
    "                        ",
    "                        ",
    "                        ",
    "      ........          ",
    "    ..Oooooox#..        ",
    "   .Oooooooooox#..      ",
    "  .Ooooo::oooooox#.     ",
    "  .Oooo::::oooooox#.    ",
    "  .Ooooo::ooooooox#.    ",
    "   .Oooooooooooox#.     ",
    "    .Oooooooooox#.      ",
    "     ............       ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
  ],
  "coca": [
    "                        ",
    "        .               ",
    "      ..t.              ",
    "     .Ooot.    .        ",
    "    .Ooooo#. ..t.       ",
    "     .Oooo. .Ooot.      ",
    "      .Oo. .Oooo#.      ",
    "      .Oo.  .Oooo.      ",
    "       .Oo...Oo..       ",
    "        .Oooo#.         ",
    "         .Ooo.          ",
    "         .Ooo.          ",
    "        .Oooo#.         ",
    "         .....          ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
  ],
  "coffee": [
    "                        ",
    "          ..            ",
    "         .tt.           ",
    "       ..tt.            ",
    "      .Oooo.   ....     ",
    "     .Oo::o#. .Oooo.    ",
    "     .Ooooo#..Oo::o#.   ",
    "      .Oooo. .Ooooo#.   ",
    "       .Oooo. .Oooo.    ",
    "      .Oo::o#. ....     ",
    "      .Ooooo#..Oooo.    ",
    "       .Oooo..Oo::o#.   ",
    "        .... .Ooooo#.   ",
    "              .Oooo.    ",
    "               ....     ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
  ],
  "coin": [
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "      ..........        ",
    "    ..Oooooooox#..      ",
    "   .Oooooooooooox#.     ",
    "   .Oottoooottoox#.     ",
    "   .Oooooooooooox#.     ",
    "   ..tttttttttttt..     ",
    "  .Oooooooooooooox#.    ",
    "  .Ootooooooootoox#.    ",
    "  .Oooooooooooooox#.    ",
    "  ..tttttttttttttt..    ",
    " .Oooooooooooooooox#.   ",
    " .Oooooooooooooooox#.   ",
    " .Oooooooooooooooox#.   ",
    "  .tttttttttttttttt.    ",
    "   ................     ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
  ],
  "cooked-meat": [
    "                        ",
    "                        ",
    "                        ",
    "       .......          ",
    "     ..Ooooox#..        ",
    "    .Ooooooooox#.       ",
    "   .Ooo:ooo:ooox#.      ",
    "  .Ooo:oottoo:ox#.      ",
    "  .Oooooottooooox#...   ",
    "  .Oo:oooooooo:ox#.tt.  ",
    "   .Ooooo:ooooooottt.   ",
    "    .Ooooooooooox#.tt.  ",
    "     ..Ooooooox#.. ..   ",
    "       .........        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
  ],
  "copper-ore": [
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "         ......         ",
    "       ..Ooooo#..       ",
    "     ..Oooottoox#..     ",
    "    .OooooottTooox#.    ",
    "   .Oottooooooooox#.    ",
    "   .OttTooooooottx#.    ",
    "   .OooooooooottTox#.   ",
    "    .Ooooottoooooox#.   ",
    "     .OoootTooooox#.    ",
    "      ..Ooooooox#..     ",
    "        .........       ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
  ],
  "copper-ore-poor": [
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "        ......          ",
    "      ..Ooooo#..        ",
    "     .Oooooooox#.       ",
    "    .Ooooooottox#.      ",
    "    .OooooooottTx#.     ",
    "    .Ooooooooooox#.     ",
    "     .Ooooooooox#.      ",
    "      ..Ooooox#..       ",
    "        .......         ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
  ],
  "copper-ore-rich": [
    "                        ",
    "                        ",
    "                        ",
    "        ......          ",
    "      ..Ooooo#...       ",
    "    ..OotttTooox#.      ",
    "   .OoottTTttooox#.     ",
    "  .Oooootttooottox#.    ",
    "  .OttooooooottTTtx#.   ",
    "  .OtTToooottttTtox#.   ",
    "  .OottooootTTtoooox#.  ",
    "   .Ooooooottoooottx#.  ",
    "    .OottoooooootTT#.   ",
    "     .OttToooooooox#.   ",
    "      ..Oooooooox#..    ",
    "        ..........      ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
  ],
  "cotton": [
    "                        ",
    "                        ",
    "       ........         ",
    "     ..Oooooox#..       ",
    "    .Oo::oooo::x#.      ",
    "   .Oooooo::oooox#.     ",
    "  .Oo::oooooooo::x#.    ",
    "  .Oooooo::oooooox#.    ",
    "  .Oo::ooooooo::ox#.    ",
    "  .Ooooo::oooooox#.     ",
    "   .Oo::oooooo::x#.     ",
    "    .Oooo::oooox#.      ",
    "     ..Oooooox#..       ",
    "       ........         ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
  ],
  "cow-dung": [
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "         ......         ",
    "      ...Ooooo#...      ",
    "    ..Ooottttttox#...   ",
    "   .Oootoooooooootox#.  ",
    "  .Ootoootttttttoootx#. ",
    " .Ootootoooooooootootx#.",
    " .Ootootttttttttttootx#.",
    "  .Oootoooooooooootox#. ",
    "   ..Oooottttttttox#..  ",
    "     ...Oooooooox#..    ",
    "        ..........      ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
  ],
  "dirt": [
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "        .   .           ",
    "      ..O...O.          ",
    "    ..Oooooox#..        ",
    "   .Oootoooooox#..      ",
    "  .Ooooooootoooox#.     ",
    "  .Oootooooooootx#.     ",
    "   .Oooooooooooox#.     ",
    "    ..............      ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
  ],
  "dry-horse-dung": [
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "          ....          ",
    "         .Oooo..        ",
    "        .Ootttx#.       ",
    "     ....Ooooo#....     ",
    "    .Oooo......Oooo.    ",
    "   .Ootttx#..Ootttx#.   ",
    "   .Ooooo#.  .Ooooo#.   ",
    "    .Oooo.    .Oooo.    ",
    "     ....      ....     ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
  ],
  "dung-cake": [
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "         ......         ",
    "      ...Ooooo#...      ",
    "    ..Ooottttttox#...   ",
    "   .Oootoooooooootox#.  ",
    "  .Ootoootttttttoootx#. ",
    " .Ootootoooooooootootx#.",
    " .Ootootttttttttttootx#.",
    "  .Oootoooooooooootox#. ",
    "   ..Oooottttttttox#..  ",
    "     ...Oooooooox#..    ",
    "        ..........      ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
  ],
  "dung-pellets": [
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "       ..    ..         ",
    "      .Oo.  .Oo.  ..    ",
    "     .Oto. .Oto. .Oo.   ",
    "   .. .Oo....Oo..Oto.   ",
    "  .Oo. ...Oo......Oo.   ",
    " .Oto.  .Oto. .Oo...    ",
    "  .Oo.   .Oo..Oto.      ",
    "   ..     ..  .Oo.      ",
    "               ..       ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
  ],
  "ephedra": [
    "    .       .       .   ",
    "   .O.     .O.     .O.  ",
    "   .O.    .Oo.    .Oo.  ",
    "   .t.    .t.     .t.   ",
    "   .t.    .t.     .t.   ",
    "   .t.    .t.     .t.   ",
    "   .t.    .t.     .t.   ",
    "   .t.    .t.     .t.   ",
    "   .t.    .t.     .t.   ",
    "   .t.    .t.     .t.   ",
    "   .t.    .t.     .t.   ",
    "   .t.    .t.     .t.   ",
    "   .t.    .t.     .t.   ",
    "    .      .       .    ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
  ],
  "feathers": [
    "                        ",
    "               ...      ",
    "             ..Ooo.     ",
    "           ..Oooo#.     ",
    "          .Oootox#.     ",
    "        ..Ootoo#..      ",
    "       .Ootoox#.        ",
    "     ..Otooo#..         ",
    "    .Ootoo#..           ",
    "   .Otoo#..             ",
    "  .too...               ",
    " .t...                  ",
    "  .                     ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
  ],
  "fish": [
    "                        ",
    "                        ",
    "                        ",
    "                 ..     ",
    "     ......     .Oo.    ",
    "   ..Ooooo#..  .Oooo.   ",
    "  .Oooooooox#..Oooo#.   ",
    " .Ootoooooooooooox#.    ",
    " .Oooooo::::ooooox#.    ",
    " .Ootoooooooooooox#.    ",
    "  .Oooooooox#..Oooo#.   ",
    "   ..Ooooo#..  .Oooo.   ",
    "     ......     .Oo.    ",
    "                 ..     ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
  ],
  "flax": [
    "                        ",
    "      .    .    .       ",
    "     .t.  .t.  .t.      ",
    "    .ttt..ttt..ttt.     ",
    "     .t.  .t.  .t.      ",
    "     .O.  .O.  .O.      ",
    "     .Oo. .O. .Oo.      ",
    "      .O. .O. .O.       ",
    "      .Oo..O..Oo.       ",
    "       .O..O..O.        ",
    "       .Ooooo#.         ",
    "        .O.O.O.         ",
    "       .O..O..O.        ",
    "      .O. .O. .O.       ",
    "       .   .   .        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
  ],
  "flint": [
    "                        ",
    "                        ",
    "                        ",
    "        ....            ",
    "      ..Oooo..          ",
    "     .Oooooox#..        ",
    "    .Ooooooooox#.       ",
    "   .Ooooooooooott.      ",
    "   .Ooooooooootttt.     ",
    "    .Oooooooootttt.     ",
    "     .Oooooooottt.      ",
    "      ..Ooooox#..       ",
    "        .......         ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
  ],
  "fodder": [
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "   .   .     .    .     ",
    "  .O. .O..  .O.. .O.    ",
    "  .Oo.Oo.O..Oo.O.Oo..   ",
    " .Ooooooooooooooooox#.  ",
    ".Ooooooooooooooooooox#. ",
    ".Ooootttoooottttooox#.  ",
    " .Ooooooooooooooooox#.  ",
    "  .Ooooooooooooooox#.   ",
    "   .................    ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
  ],
  "frond": [
    "  ..                    ",
    " .Oo..   ..             ",
    "  .Ooo. .Oo..  ..       ",
    "  ..Ooo..Oooo..Oo.      ",
    " .Oo.Ooo.Ooooooox#.     ",
    "  .Ooo.Oooooooooox#.    ",
    "   .Ottttttttttttox#.   ",
    "  .Ooo.Oooooooooox#.    ",
    " .Oo.Ooo.Ooooooox#.     ",
    "  ..Ooo..Oooo..Oo.      ",
    "  .Ooo. .Oo..  ..       ",
    " .Oo..   ..             ",
    "  ..                    ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
  ],
  "fruit": [
    "                        ",
    "           ..           ",
    "          .tt.          ",
    "       ...tt...         ",
    "     ..Oooooox#..       ",
    "    .Oooooooooox#.      ",
    "   .Oo::oooooooox#.     ",
    "   .Oo::oooooooox#.     ",
    "   .Oooooooooooox#.     ",
    "    .Oooooooooox#.      ",
    "     .Oooooooox#.       ",
    "      .Oooooox#.        ",
    "       ........         ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
  ],
  "gold-ore": [
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "         ......         ",
    "       ..Ooooo#..       ",
    "     ..Oooottoox#..     ",
    "    .OooooottTooox#.    ",
    "   .Oottooooooooox#.    ",
    "   .OttTooooooottx#.    ",
    "   .OooooooooottTox#.   ",
    "    .Ooooottoooooox#.   ",
    "     .OoootTooooox#.    ",
    "      ..Ooooooox#..     ",
    "        .........       ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
  ],
  "gold-ore-poor": [
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "        ......          ",
    "      ..Ooooo#..        ",
    "     .Oooooooox#.       ",
    "    .Ooooooottox#.      ",
    "    .OooooooottTx#.     ",
    "    .Ooooooooooox#.     ",
    "     .Ooooooooox#.      ",
    "      ..Ooooox#..       ",
    "        .......         ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
  ],
  "gold-ore-rich": [
    "                        ",
    "                        ",
    "                        ",
    "        ......          ",
    "      ..Ooooo#...       ",
    "    ..OotttTooox#.      ",
    "   .OoottTTttooox#.     ",
    "  .Oooootttooottox#.    ",
    "  .OttooooooottTTtx#.   ",
    "  .OtTToooottttTtox#.   ",
    "  .OottooootTTtoooox#.  ",
    "   .Ooooooottoooottx#.  ",
    "    .OottoooooootTT#.   ",
    "     .OttToooooooox#.   ",
    "      ..Oooooooox#..    ",
    "        ..........      ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
  ],
  "goldenrod": [
    "                        ",
    "      .    .    .       ",
    "     .t.  .t.  .t.      ",
    "    .ttt..ttt..ttt.     ",
    "     .t.  .t.  .t.      ",
    "     .O.  .O.  .O.      ",
    "     .Oo. .O. .Oo.      ",
    "      .O. .O. .O.       ",
    "      .Oo..O..Oo.       ",
    "       .O..O..O.        ",
    "       .Ooooo#.         ",
    "        .O.O.O.         ",
    "       .O..O..O.        ",
    "      .O. .O. .O.       ",
    "       .   .   .        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
  ],
  "grain": [
    "                        ",
    "      ..   ..   ..      ",
    "     .Oo. .Oo. .Oo.     ",
    "    .Oooo.Oooo.Oooo.    ",
    "    .O::o.O::o.O::o.    ",
    "    .Oooo.Oooo.Oooo.    ",
    "    .O::o.O::o.O::o.    ",
    "    .Oooo.Oooo.Oooo.    ",
    "     .tt. .tt. .tt.     ",
    "      .t. .t. .t..      ",
    "      .t. .t. .t.       ",
    "       .t..t..t.        ",
    "       .tttttt.         ",
    "        .t.t.t.         ",
    "       .t..t..t.        ",
    "        .  .  .         ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
  ],
  "granite": [
    "                        ",
    "                        ",
    "     ..........         ",
    "   ..Oooooooox#.        ",
    "  .Ooootooootox#.       ",
    "  .Ootoooooooox#.       ",
    " .Ooooootoooootx#.      ",
    " .Oootoooooootox#.      ",
    " .Ooooootoooooox#.      ",
    "  .Ootoooootooox#.      ",
    "   .Oooooooooox#.       ",
    "    ............        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
  ],
  "grass-fibre": [
    "                        ",
    "                        ",
    "                        ",
    "   ..                   ",
    "  .Oo......             ",
    "  ..Ooooox#....         ",
    " .Ooooooooooox#....     ",
    "  .Oooooooooooooox#.    ",
    " .ttttttttttttttttt..   ",
    "  .Oooooooooooooooox#.  ",
    "   ..Ooooooooooooox#.   ",
    "     ...Oooooooox#..    ",
    "        .....Ooo..      ",
    "             ...        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
  ],
  "greens": [
    "                        ",
    "        .               ",
    "      ..t.              ",
    "     .Ooot.    .        ",
    "    .Ooooo#. ..t.       ",
    "     .Oooo. .Ooot.      ",
    "      .Oo. .Oooo#.      ",
    "      .Oo.  .Oooo.      ",
    "       .Oo...Oo..       ",
    "        .Oooo#.         ",
    "         .Ooo.          ",
    "         .Ooo.          ",
    "        .Oooo#.         ",
    "         .....          ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
  ],
  "gromwell": [
    "                        ",
    "                        ",
    "      .......           ",
    "    ..Ooooox#.          ",
    "   .Oooooooox#.         ",
    "  .Oootttttoox#.        ",
    "  .Ooottttttoox#.       ",
    "  .Oootttttttoox#.      ",
    "   .Oootttttttox#.      ",
    "    .Oooooooooox#.      ",
    "     ..Ooooooox#.       ",
    "       ..Ooooo#.        ",
    "         ......         ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
  ],
  "henna": [
    "                        ",
    "        .               ",
    "      ..t.              ",
    "     .Ooot.    .        ",
    "    .Ooooo#. ..t.       ",
    "     .Oooo. .Ooot.      ",
    "      .Oo. .Oooo#.      ",
    "      .Oo.  .Oooo.      ",
    "       .Oo...Oo..       ",
    "        .Oooo#.         ",
    "         .Ooo.          ",
    "         .Ooo.          ",
    "        .Oooo#.         ",
    "         .....          ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
  ],
  "herbs": [
    "                        ",
    "        .               ",
    "      ..t.              ",
    "     .Ooot.    .        ",
    "    .Ooooo#. ..t.       ",
    "     .Oooo. .Ooot.      ",
    "      .Oo. .Oooo#.      ",
    "      .Oo.  .Oooo.      ",
    "       .Oo...Oo..       ",
    "        .Oooo#.         ",
    "         .Ooo.          ",
    "         .Ooo.          ",
    "        .Oooo#.         ",
    "         .....          ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
  ],
  "hide": [
    "                        ",
    "   ..            ..     ",
    "  .Oo..        ..Oo.    ",
    "  .Oooo........Oooo.    ",
    "   .Oooooooooooox#.     ",
    "    .Oooottttoox#.      ",
    "    .Oootttttttx#.      ",
    "    .Oootttttttx#.      ",
    "    .Oooottttoox#.      ",
    "   .Oooooooooooox#.     ",
    "  .Oooo........Oooo.    ",
    "  .Oo..        ..Oo.    ",
    "   ..            ..     ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
  ],
  "horse-dung": [
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "          ....          ",
    "         .Oooo..        ",
    "        .Ootttx#.       ",
    "     ....Ooooo#....     ",
    "    .Oooo......Oooo.    ",
    "   .Ootttx#..Ootttx#.   ",
    "   .Ooooo#.  .Ooooo#.   ",
    "    .Oooo.    .Oooo.    ",
    "     ....      ....     ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
  ],
  "indigo": [
    "                        ",
    "        .               ",
    "      ..t.              ",
    "     .Ooot.    .        ",
    "    .Ooooo#. ..t.       ",
    "     .Oooo. .Ooot.      ",
    "      .Oo. .Oooo#.      ",
    "      .Oo.  .Oooo.      ",
    "       .Oo...Oo..       ",
    "        .Oooo#.         ",
    "         .Ooo.          ",
    "         .Ooo.          ",
    "        .Oooo#.         ",
    "         .....          ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
  ],
  "iron-ore": [
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "         ......         ",
    "       ..Ooooo#..       ",
    "     ..Oooottoox#..     ",
    "    .OooooottTooox#.    ",
    "   .Oottooooooooox#.    ",
    "   .OttTooooooottx#.    ",
    "   .OooooooooottTox#.   ",
    "    .Ooooottoooooox#.   ",
    "     .OoootTooooox#.    ",
    "      ..Ooooooox#..     ",
    "        .........       ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
  ],
  "iron-ore-poor": [
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "        ......          ",
    "      ..Ooooo#..        ",
    "     .Oooooooox#.       ",
    "    .Ooooooottox#.      ",
    "    .OooooooottTx#.     ",
    "    .Ooooooooooox#.     ",
    "     .Ooooooooox#.      ",
    "      ..Ooooox#..       ",
    "        .......         ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
  ],
  "iron-ore-rich": [
    "                        ",
    "                        ",
    "                        ",
    "        ......          ",
    "      ..Ooooo#...       ",
    "    ..OotttTooox#.      ",
    "   .OoottTTttooox#.     ",
    "  .Oooootttooottox#.    ",
    "  .OttooooooottTTtx#.   ",
    "  .OtTToooottttTtox#.   ",
    "  .OottooootTTtoooox#.  ",
    "   .Ooooooottoooottx#.  ",
    "    .OottoooooootTT#.   ",
    "     .OttToooooooox#.   ",
    "      ..Oooooooox#..    ",
    "        ..........      ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
  ],
  "khat": [
    "                        ",
    "        .               ",
    "      ..t.              ",
    "     .Ooot.    .        ",
    "    .Ooooo#. ..t.       ",
    "     .Oooo. .Ooot.      ",
    "      .Oo. .Oooo#.      ",
    "      .Oo.  .Oooo.      ",
    "       .Oo...Oo..       ",
    "        .Oooo#.         ",
    "         .Ooo.          ",
    "         .Ooo.          ",
    "        .Oooo#.         ",
    "         .....          ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
  ],
  "limestone": [
    "                        ",
    "                        ",
    "                        ",
    "    ..............      ",
    "   .Oooooooooooox#.     ",
    "  .Oooooooooooooox#.    ",
    "  .Ooo::oooooo::ox#.    ",
    "  .Oooooooooooooox#.    ",
    "  .Oooooooooooooox#.    ",
    "   .Oooooooooooox#.     ",
    "    ..............      ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
  ],
  "lizard": [
    "                        ",
    "                        ",
    "                        ",
    "     ....               ",
    "    .Oooo...            ",
    "   .Oo::oox#..          ",
    "   .Oooooooox#...       ",
    "  .O..Ooooooooox#...    ",
    "  .O. .Ooooooooooox#.   ",
    " .O.   .Oooooox#...Oo.. ",
    "  .     .O....O.   ..Oo.",
    "       .Oo.  .Oo.    ..O",
    "        ..    ..       .",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
  ],
  "madder": [
    "                        ",
    "                        ",
    "      .......           ",
    "    ..Ooooox#.          ",
    "   .Oooooooox#.         ",
    "  .Oootttttoox#.        ",
    "  .Ooottttttoox#.       ",
    "  .Oootttttttoox#.      ",
    "   .Oootttttttox#.      ",
    "    .Oooooooooox#.      ",
    "     ..Ooooooox#.       ",
    "       ..Ooooo#.        ",
    "         ......         ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
  ],
  "meat": [
    "                        ",
    "                        ",
    "                        ",
    "       .......          ",
    "     ..Ooooox#..        ",
    "    .Ooooooooox#.       ",
    "   .Ooo:ooooooox#.      ",
    "  .Ooo:oottoooox#.      ",
    "  .Oooooottooooox#...   ",
    "  .Ooooooooooo:ox#.tt.  ",
    "   .Oooooooooooooottt.  ",
    "    .Ooooooooooox#.tt.  ",
    "     ..Ooooooox#.. ..   ",
    "       .........        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
  ],
  "mud": [
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "     ..    ...          ",
    "   ..Oo....Ooo...       ",
    "  .Oooooooooooox#.      ",
    " .Oooo::oooo::oox#.     ",
    " .Oooooooooooooox#.     ",
    "  .Oo.Ooooooox#.Oo.     ",
    "   .. ......... ..      ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
  ],
  "mushroom": [
    "                        ",
    "                        ",
    "       ........         ",
    "     ..Oooooox#..       ",
    "    .Oooooooooox#.      ",
    "   .Oooo::oooooox#..    ",
    "  .Oooooooooo::ooox#.   ",
    "  .Oooooooooooooox#.    ",
    "   .Oooooooooooox#.     ",
    "    ...tttttttt...      ",
    "      .tttttttt.        ",
    "       .tttttt.         ",
    "       .tttttt.         ",
    "      .tttttttt.        ",
    "       ........         ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
  ],
  "obsidian": [
    "                        ",
    "           ..           ",
    "          .Oo.          ",
    "         .Oooo.         ",
    "        .Ooooo#.        ",
    "       .Oooooox#.       ",
    "      .Oooooooox#.      ",
    "     .Oooooo:oox#.      ",
    "     .Ooooo::oox#.      ",
    "      .Oooo::ox#.       ",
    "       .Ooo::x#.        ",
    "        .Oo::#.         ",
    "         .Ooo.          ",
    "          .O.           ",
    "           .            ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
  ],
  "ore": [
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "         ......         ",
    "       ..Ooooo#..       ",
    "     ..Oooottoox#..     ",
    "    .OooooottTooox#.    ",
    "   .Oottooooooooox#.    ",
    "   .OttTooooooottx#.    ",
    "   .OooooooooottTox#.   ",
    "    .Ooooottoooooox#.   ",
    "     .OoootTooooox#.    ",
    "      ..Ooooooox#..     ",
    "        .........       ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
  ],
  "ore-poor": [
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "        ......          ",
    "      ..Ooooo#..        ",
    "     .Oooooooox#.       ",
    "    .Ooooooottox#.      ",
    "    .OooooooottTx#.     ",
    "    .Ooooooooooox#.     ",
    "     .Ooooooooox#.      ",
    "      ..Ooooox#..       ",
    "        .......         ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
  ],
  "ore-rich": [
    "                        ",
    "                        ",
    "                        ",
    "        ......          ",
    "      ..Ooooo#...       ",
    "    ..OotttTooox#.      ",
    "   .OoottTTttooox#.     ",
    "  .Oooootttooottox#.    ",
    "  .OttooooooottTTtx#.   ",
    "  .OtTToooottttTtox#.   ",
    "  .OottooootTTtoooox#.  ",
    "   .Ooooooottoooottx#.  ",
    "    .OottoooooootTT#.   ",
    "     .OttToooooooox#.   ",
    "      ..Oooooooox#..    ",
    "        ..........      ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
  ],
  "papyrus": [
    "    .       .       .   ",
    "   .O.     .O.     .O.  ",
    "   .O.    .Oo.    .Oo.  ",
    "   .t.    .t.     .t.   ",
    "   .t.    .t.     .t.   ",
    "   .t.    .t.     .t.   ",
    "   .t.    .t.     .t.   ",
    "   .t.    .t.     .t.   ",
    "   .t.    .t.     .t.   ",
    "   .t.    .t.     .t.   ",
    "   .t.    .t.     .t.   ",
    "   .t.    .t.     .t.   ",
    "   .t.    .t.     .t.   ",
    "    .      .       .    ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
  ],
  "pebble": [
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "        ......          ",
    "       .Ooooo#.         ",
    "      .Oooooox#.        ",
    "     .Oooo::oox#.       ",
    "     .Oooooooox#.       ",
    "      .Oooooox#.        ",
    "       ........         ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
  ],
  "pinecone": [
    "                        ",
    "                        ",
    "        ....            ",
    "       .Oooo..          ",
    "      .Oootox#..        ",
    "     .Ootooootx#.       ",
    "     .Oooootoox#.       ",
    "     .Ootooootx#.       ",
    "     .Oooootoox#.       ",
    "      .Ootooox#.        ",
    "       .Ooooo#.         ",
    "        .Oooo.          ",
    "         .Oo.           ",
    "          ..            ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
  ],
  "pituri": [
    "                        ",
    "        .               ",
    "      ..t.              ",
    "     .Ooot.    .        ",
    "    .Ooooo#. ..t.       ",
    "     .Oooo. .Ooot.      ",
    "      .Oo. .Oooo#.      ",
    "      .Oo.  .Oooo.      ",
    "       .Oo...Oo..       ",
    "        .Oooo#.         ",
    "         .Ooo.          ",
    "         .Ooo.          ",
    "        .Oooo#.         ",
    "         .....          ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
  ],
  "poppy-pods": [
    "                        ",
    "                        ",
    "           .            ",
    "       ....t...         ",
    "      .tttttttt.        ",
    "     .tttttttttt.       ",
    "     .tttttttttt.       ",
    "      .Oooooox#.        ",
    "      .Oooooox#.        ",
    "      .Oooooox#.        ",
    "       .Ooooo#.         ",
    "        .Oooo.          ",
    "         .Oo.           ",
    "          ..            ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
  ],
  "reeds": [
    "    .       .       .   ",
    "   .O.     .O.     .O.  ",
    "   .O.    .Oo.    .Oo.  ",
    "   .t.    .t.     .t.   ",
    "   .t.    .t.     .t.   ",
    "   .t.    .t.     .t.   ",
    "   .t.    .t.     .t.   ",
    "   .t.    .t.     .t.   ",
    "   .t.    .t.     .t.   ",
    "   .t.    .t.     .t.   ",
    "   .t.    .t.     .t.   ",
    "   .t.    .t.     .t.   ",
    "   .t.    .t.     .t.   ",
    "    .      .       .    ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
  ],
  "resin": [
    "                        ",
    "                        ",
    "         ..             ",
    "        .Oo.            ",
    "       .Oooo..          ",
    "      .Oootox#.         ",
    "     .Ooottoox#.        ",
    "     .Ooooooox#.        ",
    "      .Ooooox#.         ",
    "       .Oooo#.          ",
    "        .....           ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
  ],
  "river-rock": [
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "      ..........        ",
    "    ..Oooooooox#..      ",
    "   .Oooooooooooox#.     ",
    "  .Ooooo::ooooooox#.    ",
    "  .Oooooooooooooox#.    ",
    "   .Oooooooooooox#.     ",
    "    ..............      ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
  ],
  "roots": [
    "                        ",
    "        .               ",
    "      ..t.              ",
    "     .Ooot.    .        ",
    "    .Ooooo#. ..t.       ",
    "     .Oooo. .Ooot.      ",
    "      .Oo. .Oooo#.      ",
    "      .Oo.  .Oooo.      ",
    "       .Oo...Oo..       ",
    "        .Oooo#.         ",
    "         .Ooo.          ",
    "         .Ooo.          ",
    "        .Oooo#.         ",
    "         .....          ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
  ],
  "roselle": [
    "                        ",
    "          ..            ",
    "         .tt.           ",
    "       ..tt.            ",
    "      .Oooo.   ....     ",
    "     .Oo::o#. .Oooo.    ",
    "     .Ooooo#..Oo::o#.   ",
    "      .Oooo. .Ooooo#.   ",
    "       .Oooo. .Oooo.    ",
    "      .Oo::o#. ....     ",
    "      .Ooooo#..Oooo.    ",
    "       .Oooo..Oo::o#.   ",
    "        .... .Ooooo#.   ",
    "              .Oooo.    ",
    "               ....     ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
  ],
  "rushes": [
    "    .       .       .   ",
    "   .O.     .O.     .O.  ",
    "   .O.    .Oo.    .Oo.  ",
    "   .t.    .t.     .t.   ",
    "   .t.    .t.     .t.   ",
    "   .t.    .t.     .t.   ",
    "   .t.    .t.     .t.   ",
    "   .t.    .t.     .t.   ",
    "   .t.    .t.     .t.   ",
    "   .t.    .t.     .t.   ",
    "   .t.    .t.     .t.   ",
    "   .t.    .t.     .t.   ",
    "   .t.    .t.     .t.   ",
    "    .      .       .    ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
  ],
  "safflower": [
    "                        ",
    "          ..            ",
    "         .tt.           ",
    "       ..tt.            ",
    "      .Oooo.   ....     ",
    "     .Oo::o#. .Oooo.    ",
    "     .Ooooo#..Oo::o#.   ",
    "      .Oooo. .Ooooo#.   ",
    "       .Oooo. .Oooo.    ",
    "      .Oo::o#. ....     ",
    "      .Ooooo#..Oooo.    ",
    "       .Oooo..Oo::o#.   ",
    "        .... .Ooooo#.   ",
    "              .Oooo.    ",
    "               ....     ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
  ],
  "saffron": [
    "                        ",
    "      .    .    .       ",
    "     .t.  .t.  .t.      ",
    "    .ttt..ttt..ttt.     ",
    "     .t.  .t.  .t.      ",
    "     .O.  .O.  .O.      ",
    "     .Oo. .O. .Oo.      ",
    "      .O. .O. .O.       ",
    "      .Oo..O..Oo.       ",
    "       .O..O..O.        ",
    "       .Ooooo#.         ",
    "        .O.O.O.         ",
    "       .O..O..O.        ",
    "      .O. .O. .O.       ",
    "       .   .   .        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
  ],
  "sand": [
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "          .             ",
    "        ..t.            ",
    "      ..Oooo..          ",
    "    ..Oootoox#..        ",
    "   .Ooooooootox#..      ",
    "  .Ootoooooooooox#.     ",
    " .Oooooootooooooox#.    ",
    "  .................     ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
  ],
  "seeds": [
    "                        ",
    "      ..   ..   ..      ",
    "     .Oo. .Oo. .Oo.     ",
    "    .Oooo.Oooo.Oooo.    ",
    "    .O::o.O::o.O::o.    ",
    "    .Oooo.Oooo.Oooo.    ",
    "    .O::o.O::o.O::o.    ",
    "    .Oooo.Oooo.Oooo.    ",
    "     .tt. .tt. .tt.     ",
    "      .t. .t. .t..      ",
    "      .t. .t. .t.       ",
    "       .t..t..t.        ",
    "       .tttttt.         ",
    "        .t.t.t.         ",
    "       .t..t..t.        ",
    "        .  .  .         ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
  ],
  "shell": [
    "                        ",
    "                        ",
    "          ..            ",
    "        ..Oo..          ",
    "      ..Ooooo#..        ",
    "     .Oootoooox#..      ",
    "    .Ooootoooooox#.     ",
    "   .Ooootttooooox#.     ",
    "  .Oooootttoooooox#.    ",
    "  .Ooootoootooooox#.    ",
    "   .Oooooooooooox#.     ",
    "    .Oooooooooox#.      ",
    "     ............       ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
  ],
  "silver-ore": [
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "         ......         ",
    "       ..Ooooo#..       ",
    "     ..Oooottoox#..     ",
    "    .OooooottTooox#.    ",
    "   .Oottooooooooox#.    ",
    "   .OttTooooooottx#.    ",
    "   .OooooooooottTox#.   ",
    "    .Ooooottoooooox#.   ",
    "     .OoootTooooox#.    ",
    "      ..Ooooooox#..     ",
    "        .........       ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
  ],
  "silver-ore-poor": [
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "        ......          ",
    "      ..Ooooo#..        ",
    "     .Oooooooox#.       ",
    "    .Ooooooottox#.      ",
    "    .OooooooottTx#.     ",
    "    .Ooooooooooox#.     ",
    "     .Ooooooooox#.      ",
    "      ..Ooooox#..       ",
    "        .......         ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
  ],
  "silver-ore-rich": [
    "                        ",
    "                        ",
    "                        ",
    "        ......          ",
    "      ..Ooooo#...       ",
    "    ..OotttTooox#.      ",
    "   .OoottTTttooox#.     ",
    "  .Oooootttooottox#.    ",
    "  .OttooooooottTTtx#.   ",
    "  .OtTToooottttTtox#.   ",
    "  .OottooootTTtoooox#.  ",
    "   .Ooooooottoooottx#.  ",
    "    .OottoooooootTT#.   ",
    "     .OttToooooooox#.   ",
    "      ..Oooooooox#..    ",
    "        ..........      ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
  ],
  "stick": [
    "                        ",
    "                        ",
    "                        ",
    "                ....    ",
    "              ..Oooo.   ",
    "            ..Ooooo#.   ",
    "          ..Oooott..    ",
    "        ..Ooooo#..      ",
    "      ..Ooooo#..        ",
    "    ..Ooooo#..          ",
    "   .Ooooo#..            ",
    "  .Oooo#..              ",
    "  .Ooo..                ",
    "   ...                  ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
  ],
  "stone": [
    "                        ",
    "                        ",
    "                        ",
    "       ........         ",
    "     ..Oooooox#..       ",
    "    .Oooooooooox#.      ",
    "   .Oooooooooooox#.     ",
    "  .Oooooo::oooooox#.    ",
    "  .Oooooooooooooox#.    ",
    "   .Oooooooooooox#.     ",
    "    .Oooooooooox#.      ",
    "     ............       ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
  ],
  "straw": [
    "                        ",
    "                        ",
    "                        ",
    "   ..                   ",
    "  .Oo......             ",
    "  ..Ooooox#....         ",
    " .Ooooooooooox#....     ",
    "  .Oooooooooooooox#.    ",
    " .ttttttttttttttttt..   ",
    "  .Oooooooooooooooox#.  ",
    "   ..Ooooooooooooox#.   ",
    "     ...Oooooooox#..    ",
    "        .....Ooo..      ",
    "             ...        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
  ],
  "tea": [
    "                        ",
    "        .               ",
    "      ..t.              ",
    "     .Ooot.    .        ",
    "    .Ooooo#. ..t.       ",
    "     .Oooo. .Ooot.      ",
    "      .Oo. .Oooo#.      ",
    "      .Oo.  .Oooo.      ",
    "       .Oo...Oo..       ",
    "        .Oooo#.         ",
    "         .Ooo.          ",
    "         .Ooo.          ",
    "        .Oooo#.         ",
    "         .....          ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
  ],
  "tin-ore": [
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "         ......         ",
    "       ..Ooooo#..       ",
    "     ..Oooottoox#..     ",
    "    .OooooottTooox#.    ",
    "   .Oottooooooooox#.    ",
    "   .OttTooooooottx#.    ",
    "   .OooooooooottTox#.   ",
    "    .Ooooottoooooox#.   ",
    "     .OoootTooooox#.    ",
    "      ..Ooooooox#..     ",
    "        .........       ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
  ],
  "tin-ore-poor": [
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "        ......          ",
    "      ..Ooooo#..        ",
    "     .Oooooooox#.       ",
    "    .Ooooooottox#.      ",
    "    .OooooooottTx#.     ",
    "    .Ooooooooooox#.     ",
    "     .Ooooooooox#.      ",
    "      ..Ooooox#..       ",
    "        .......         ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
  ],
  "tin-ore-rich": [
    "                        ",
    "                        ",
    "                        ",
    "        ......          ",
    "      ..Ooooo#...       ",
    "    ..OotttTooox#.      ",
    "   .OoottTTttooox#.     ",
    "  .Oooootttooottox#.    ",
    "  .OttooooooottTTtx#.   ",
    "  .OtTToooottttTtox#.   ",
    "  .OottooootTTtoooox#.  ",
    "   .Ooooooottoooottx#.  ",
    "    .OottoooooootTT#.   ",
    "     .OttToooooooox#.   ",
    "      ..Oooooooox#..    ",
    "        ..........      ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
  ],
  "tobacco": [
    "  ..                    ",
    " .Oo..   ..             ",
    "  .Ooo. .Oo..  ..       ",
    "  ..Ooo..Oooo..Oo.      ",
    " .Oo.Ooo.Ooooooox#.     ",
    "  .Ooo.Oooooooooox#.    ",
    "   .Ottttttttttttox#.   ",
    "  .Ooo.Oooooooooox#.    ",
    " .Oo.Ooo.Ooooooox#.     ",
    "  ..Ooo..Oooo..Oo.      ",
    "  .Ooo. .Oo..  ..       ",
    " .Oo..   ..             ",
    "  ..                    ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
  ],
  "tool": [
    "                        ",
    "                        ",
    "          ....          ",
    "         .Oooo.         ",
    "        .Ooooo#.        ",
    "       .Oooooox#.       ",
    "      .Oooooox#.        ",
    "     .Oooooox#.         ",
    "    .Oooooox#.          ",
    "   .Oooooox#.           ",
    "  .tttooox#.            ",
    " .ttttttx#.             ",
    " .tttttttt.             ",
    "  .tttttt.              ",
    "   ......               ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
  ],
  "torch": [
    "                        ",
    "              .         ",
    "             .T.        ",
    "            .TtT.       ",
    "           .TttT.       ",
    "           .tTTt.       ",
    "          .tTTTt.       ",
    "          .ttTtt.       ",
    "         .xxxx#.        ",
    "         .xOxO#.        ",
    "        .Oxxx#.         ",
    "       .Ooo...          ",
    "      .Ooo.             ",
    "     .Ooo.              ",
    "    .Ooo.               ",
    "   .Ooo.                ",
    "  .Ooo.                 ",
    "   ...                  ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
  ],
  "turmeric": [
    "                        ",
    "                        ",
    "      .......           ",
    "    ..Ooooox#.          ",
    "   .Oooooooox#.         ",
    "  .Oootttttoox#.        ",
    "  .Ooottttttoox#.       ",
    "  .Oootttttttoox#.      ",
    "   .Oootttttttox#.      ",
    "    .Oooooooooox#.      ",
    "     ..Ooooooox#.       ",
    "       ..Ooooo#.        ",
    "         ......         ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
  ],
  "water": [
    "                        ",
    "        ......          ",
    "       .Ooooo#.         ",
    "       .O::::#.         ",
    "      .Oooooox#.   ..   ",
    "     .Oooooooox#. .Oo.  ",
    "    .Oooooooooox#.Ooo.  ",
    "    .Ooooooooooooox#.   ",
    "    .Oooooooooooox#.    ",
    "    .Oooooooooooox#.    ",
    "    .Ooottttttoox#.     ",
    "    .Oootttttttox#.     ",
    "     .Oooooooooox#.     ",
    "      .Oooooooox#.      ",
    "       .Oooooox#.       ",
    "        ........        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
  ],
  "weld": [
    "                        ",
    "        .               ",
    "      ..t.              ",
    "     .Ooot.    .        ",
    "    .Ooooo#. ..t.       ",
    "     .Oooo. .Ooot.      ",
    "      .Oo. .Oooo#.      ",
    "      .Oo.  .Oooo.      ",
    "       .Oo...Oo..       ",
    "        .Oooo#.         ",
    "         .Ooo.          ",
    "         .Ooo.          ",
    "        .Oooo#.         ",
    "         .....          ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
  ],
  "woad": [
    "                        ",
    "        .               ",
    "      ..t.              ",
    "     .Ooot.    .        ",
    "    .Ooooo#. ..t.       ",
    "     .Oooo. .Ooot.      ",
    "      .Oo. .Oooo#.      ",
    "      .Oo.  .Oooo.      ",
    "       .Oo...Oo..       ",
    "        .Oooo#.         ",
    "         .Ooo.          ",
    "         .Ooo.          ",
    "        .Oooo#.         ",
    "         .....          ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
  ],
  "wood": [
    "                        ",
    "                        ",
    "                        ",
    "   .................    ",
    "  .Ooooooooooooooox#.   ",
    "  .tttttttttttttttt#.   ",
    "  .Ooooooooooooooox#.   ",
    "   ...Oooooooox#....    ",
    "  .Ooooooooooooooox#.   ",
    "  .tttttttttttttttt#.   ",
    "  .Ooooooooooooooox#.   ",
    "   ...Oooooooox#....    ",
    "  .Ooooooooooooooox#.   ",
    "  .tttttttttttttttt#.   ",
    "  .Ooooooooooooooox#.   ",
    "   .................    ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
  ],
  "wool": [
    "                        ",
    "                        ",
    "       ........         ",
    "     ..Oooooox#..       ",
    "    .Oo::oooo::x#.      ",
    "   .Oooooo::oooox#.     ",
    "  .Oo::oooooooo::x#.    ",
    "  .Oooooo::oooooox#.    ",
    "  .Oo::ooooooo::ox#.    ",
    "  .Ooooo::oooooox#.     ",
    "   .Oo::oooooo::x#.     ",
    "    .Oooo::oooox#.      ",
    "     ..Oooooox#..       ",
    "       ........         ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
  ],
};
