/**
 * Item icons, on the same twenty-four-pixel grid and the same light as the
 * garments. An item is not cloth, so each one carries its own two colours:
 * the body, and the accent that `t`/`T` draw in.
 *
 * Edit the art in scripts/garment_art/items.py, not here.
 */
import type { IconArt } from "./garment-art";

export const itemColors: Record<string, readonly [string, string]> = {
  "acorn": ["#a97a44", "#6b4a28"],
  "bark": ["#7a5636", "#a88050"],
  "berries": ["#8e3a5c", "#5d8a3a"],
  "bread": ["#c08a45", "#e0b36a"],
  "cane": ["#9aa85c", "#6d7a3c"],
  "clay": ["#a4674a", "#7c4a32"],
  "coin": ["#c9a24a", "#8a6a24"],
  "cooked-meat": ["#8a4a2a", "#e8d8bc"],
  "dirt": ["#6e5540", "#4d3a2c"],
  "feathers": ["#efe9da", "#9a8f7a"],
  "fish": ["#9aa6ae", "#6a757d"],
  "flax": ["#9fb08a", "#8a7fc0"],
  "flint": ["#5c5a52", "#c8c4b4"],
  "fodder": ["#93a05a", "#6f7c3e"],
  "frond": ["#5f8f46", "#3f6a30"],
  "fruit": ["#c04a3c", "#5d8a3a"],
  "grain": ["#d6b96a", "#8c7a3a"],
  "granite": ["#8c8890", "#d8d4dc"],
  "herbs": ["#5d8a3a", "#a8c060"],
  "hide": ["#8a5a36", "#c49a6c"],
  "limestone": ["#cfc8b4", "#a49c88"],
  "lizard": ["#7d8f4a", "#4f5c2a"],
  "meat": ["#b8453a", "#ecdcc4"],
  "mud": ["#5f4a36", "#3f3124"],
  "mushroom": ["#b07a5c", "#e0d2b8"],
  "obsidian": ["#3a3444", "#6f6580"],
  "pebble": ["#a8a094", "#7a746a"],
  "pinecone": ["#7a5a38", "#5a4028"],
  "reeds": ["#9aa85c", "#6d7a3c"],
  "resin": ["#d09a3a", "#f0c86a"],
  "river-rock": ["#8e9aa0", "#666f74"],
  "sand": ["#d8c48c", "#b09a62"],
  "shell": ["#e0cdb4", "#b09070"],
  "stick": ["#8a6a44", "#5e462c"],
  "stone": ["#9a9690", "#6e6b66"],
  "straw": ["#cdb46a", "#9c8340"],
  "tool": ["#b8bdc4", "#6b4a2e"],
  "water": ["#b06a44", "#5a89b0"],
  "wood": ["#8a6038", "#5c3f24"],
  "wool": ["#e2ded0", "#b9b3a0"],
};

export const itemArt: Record<string, IconArt> = {
  "acorn": [
    "                        ",
    "                        ",
    "           .            ",
    "       ....t...         ",
    "      .tttttttt.        ",
    "     .tttttttttt.       ",
    "     .tttttttttt.       ",
    "      .Oooooox#.        ",
    "      .Oooooox#.        ",
    "      .Oooooox#.        ",
    "       .Ooooo#.         ",
    "        .Oooo.          ",
    "         .Oo.           ",
    "          ..            ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
  ],
  "bark": [
    "                        ",
    "                        ",
    "      .......           ",
    "    ..Ooooox#.          ",
    "   .Oooooooox#.         ",
    "  .Oootttttoox#.        ",
    "  .Ooottttttoox#.       ",
    "  .Oootttttttoox#.      ",
    "   .Oootttttttox#.      ",
    "    .Oooooooooox#.      ",
    "     ..Ooooooox#.       ",
    "       ..Ooooo#.        ",
    "         ......         ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
  ],
  "berries": [
    "                        ",
    "          ..            ",
    "         .tt.           ",
    "       ..tt.            ",
    "      .Oooo.   ....     ",
    "     .Oo::o#. .Oooo.    ",
    "     .Ooooo#..Oo::o#.   ",
    "      .Oooo. .Ooooo#.   ",
    "       .Oooo. .Oooo.    ",
    "      .Oo::o#. ....     ",
    "      .Ooooo#..Oooo.    ",
    "       .Oooo..Oo::o#.   ",
    "        .... .Ooooo#.   ",
    "              .Oooo.    ",
    "               ....     ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
  ],
  "bread": [
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "      ..........        ",
    "    ..Oooooooox#..      ",
    "   .Oooooooooooox#.     ",
    "  .Oooooooooooooox#.    ",
    " .Oooo:oooo:oooo:ox#.   ",
    " .Ooo:oooo:oooo:oox#.   ",
    " .Oooooooooooooooox#.   ",
    "  .Oooooooooooooox#.    ",
    "   .Oooooooooooox#.     ",
    "    ..Oooooooox#..      ",
    "      ..........        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
  ],
  "cane": [
    "         ....           ",
    "        .Oooo.          ",
    "        .Oooo.          ",
    "        .tttt.          ",
    "        .Oooo.          ",
    "        .Oooo.          ",
    "        .Oooo.          ",
    "        .tttt.          ",
    "        .Oooo.          ",
    "        .Oooo.          ",
    "        .Oooo.          ",
    "        .tttt.          ",
    "        .Oooo.          ",
    "        .Oooo.          ",
    "        .Oooo.          ",
    "         ....           ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
  ],
  "clay": [
    "                        ",
    "                        ",
    "                        ",
    "      ........          ",
    "    ..Oooooox#..        ",
    "   .Oooooooooox#..      ",
    "  .Ooooo::oooooox#.     ",
    "  .Oooo::::oooooox#.    ",
    "  .Ooooo::ooooooox#.    ",
    "   .Oooooooooooox#.     ",
    "    .Oooooooooox#.      ",
    "     ............       ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
  ],
  "coin": [
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "      ..........        ",
    "    ..Oooooooox#..      ",
    "   .Oooooooooooox#.     ",
    "   .Oottoooottoox#.     ",
    "   .Oooooooooooox#.     ",
    "   ..tttttttttttt..     ",
    "  .Oooooooooooooox#.    ",
    "  .Ootooooooootoox#.    ",
    "  .Oooooooooooooox#.    ",
    "  ..tttttttttttttt..    ",
    " .Oooooooooooooooox#.   ",
    " .Oooooooooooooooox#.   ",
    " .Oooooooooooooooox#.   ",
    "  .tttttttttttttttt.    ",
    "   ................     ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
  ],
  "cooked-meat": [
    "                        ",
    "                        ",
    "                        ",
    "       .......          ",
    "     ..Ooooox#..        ",
    "    .Ooooooooox#.       ",
    "   .Ooo:ooo:ooox#.      ",
    "  .Ooo:oottoo:ox#.      ",
    "  .Oooooottooooox#...   ",
    "  .Oo:oooooooo:ox#.tt.  ",
    "   .Ooooo:ooooooottt.   ",
    "    .Ooooooooooox#.tt.  ",
    "     ..Ooooooox#.. ..   ",
    "       .........        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
  ],
  "dirt": [
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "        .   .           ",
    "      ..O...O.          ",
    "    ..Oooooox#..        ",
    "   .Oootoooooox#..      ",
    "  .Ooooooootoooox#.     ",
    "  .Oootooooooootx#.     ",
    "   .Oooooooooooox#.     ",
    "    ..............      ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
  ],
  "feathers": [
    "                        ",
    "               ...      ",
    "             ..Ooo.     ",
    "           ..Oooo#.     ",
    "          .Oootox#.     ",
    "        ..Ootoo#..      ",
    "       .Ootoox#.        ",
    "     ..Otooo#..         ",
    "    .Ootoo#..           ",
    "   .Otoo#..             ",
    "  .too...               ",
    " .t...                  ",
    "  .                     ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
  ],
  "fish": [
    "                        ",
    "                        ",
    "                        ",
    "                 ..     ",
    "     ......     .Oo.    ",
    "   ..Ooooo#..  .Oooo.   ",
    "  .Oooooooox#..Oooo#.   ",
    " .Ootoooooooooooox#.    ",
    " .Oooooo::::ooooox#.    ",
    " .Ootoooooooooooox#.    ",
    "  .Oooooooox#..Oooo#.   ",
    "   ..Ooooo#..  .Oooo.   ",
    "     ......     .Oo.    ",
    "                 ..     ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
  ],
  "flax": [
    "                        ",
    "      .    .    .       ",
    "     .t.  .t.  .t.      ",
    "    .ttt..ttt..ttt.     ",
    "     .t.  .t.  .t.      ",
    "     .O.  .O.  .O.      ",
    "     .Oo. .O. .Oo.      ",
    "      .O. .O. .O.       ",
    "      .Oo..O..Oo.       ",
    "       .O..O..O.        ",
    "       .Ooooo#.         ",
    "        .O.O.O.         ",
    "       .O..O..O.        ",
    "      .O. .O. .O.       ",
    "       .   .   .        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
  ],
  "flint": [
    "                        ",
    "                        ",
    "                        ",
    "        ....            ",
    "      ..Oooo..          ",
    "     .Oooooox#..        ",
    "    .Ooooooooox#.       ",
    "   .Ooooooooooott.      ",
    "   .Ooooooooootttt.     ",
    "    .Oooooooootttt.     ",
    "     .Oooooooottt.      ",
    "      ..Ooooox#..       ",
    "        .......         ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
  ],
  "fodder": [
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "   .   .     .    .     ",
    "  .O. .O..  .O.. .O.    ",
    "  .Oo.Oo.O..Oo.O.Oo..   ",
    " .Ooooooooooooooooox#.  ",
    ".Ooooooooooooooooooox#. ",
    ".Ooootttoooottttooox#.  ",
    " .Ooooooooooooooooox#.  ",
    "  .Ooooooooooooooox#.   ",
    "   .................    ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
  ],
  "frond": [
    "  ..                    ",
    " .Oo..   ..             ",
    "  .Ooo. .Oo..  ..       ",
    "  ..Ooo..Oooo..Oo.      ",
    " .Oo.Ooo.Ooooooox#.     ",
    "  .Ooo.Oooooooooox#.    ",
    "   .Ottttttttttttox#.   ",
    "  .Ooo.Oooooooooox#.    ",
    " .Oo.Ooo.Ooooooox#.     ",
    "  ..Ooo..Oooo..Oo.      ",
    "  .Ooo. .Oo..  ..       ",
    " .Oo..   ..             ",
    "  ..                    ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
  ],
  "fruit": [
    "                        ",
    "           ..           ",
    "          .tt.          ",
    "       ...tt...         ",
    "     ..Oooooox#..       ",
    "    .Oooooooooox#.      ",
    "   .Oo::oooooooox#.     ",
    "   .Oo::oooooooox#.     ",
    "   .Oooooooooooox#.     ",
    "    .Oooooooooox#.      ",
    "     .Oooooooox#.       ",
    "      .Oooooox#.        ",
    "       ........         ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
  ],
  "grain": [
    "                        ",
    "      ..   ..   ..      ",
    "     .Oo. .Oo. .Oo.     ",
    "    .Oooo.Oooo.Oooo.    ",
    "    .O::o.O::o.O::o.    ",
    "    .Oooo.Oooo.Oooo.    ",
    "    .O::o.O::o.O::o.    ",
    "    .Oooo.Oooo.Oooo.    ",
    "     .tt. .tt. .tt.     ",
    "      .t. .t. .t..      ",
    "      .t. .t. .t.       ",
    "       .t..t..t.        ",
    "       .tttttt.         ",
    "        .t.t.t.         ",
    "       .t..t..t.        ",
    "        .  .  .         ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
  ],
  "granite": [
    "                        ",
    "                        ",
    "     ..........         ",
    "   ..Oooooooox#.        ",
    "  .Ooootooootox#.       ",
    "  .Ootoooooooox#.       ",
    " .Ooooootoooootx#.      ",
    " .Oootoooooootox#.      ",
    " .Ooooootoooooox#.      ",
    "  .Ootoooootooox#.      ",
    "   .Oooooooooox#.       ",
    "    ............        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
  ],
  "herbs": [
    "                        ",
    "        .               ",
    "      ..t.              ",
    "     .Ooot.    .        ",
    "    .Ooooo#. ..t.       ",
    "     .Oooo. .Ooot.      ",
    "      .Oo. .Oooo#.      ",
    "      .Oo.  .Oooo.      ",
    "       .Oo...Oo..       ",
    "        .Oooo#.         ",
    "         .Ooo.          ",
    "         .Ooo.          ",
    "        .Oooo#.         ",
    "         .....          ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
  ],
  "hide": [
    "                        ",
    "   ..            ..     ",
    "  .Oo..        ..Oo.    ",
    "  .Oooo........Oooo.    ",
    "   .Oooooooooooox#.     ",
    "    .Oooottttoox#.      ",
    "    .Oootttttttx#.      ",
    "    .Oootttttttx#.      ",
    "    .Oooottttoox#.      ",
    "   .Oooooooooooox#.     ",
    "  .Oooo........Oooo.    ",
    "  .Oo..        ..Oo.    ",
    "   ..            ..     ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
  ],
  "limestone": [
    "                        ",
    "                        ",
    "                        ",
    "    ..............      ",
    "   .Oooooooooooox#.     ",
    "  .Oooooooooooooox#.    ",
    "  .Ooo::oooooo::ox#.    ",
    "  .Oooooooooooooox#.    ",
    "  .Oooooooooooooox#.    ",
    "   .Oooooooooooox#.     ",
    "    ..............      ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
  ],
  "lizard": [
    "                        ",
    "                        ",
    "                        ",
    "     ....               ",
    "    .Oooo...            ",
    "   .Oo::oox#..          ",
    "   .Oooooooox#...       ",
    "  .O..Ooooooooox#...    ",
    "  .O. .Ooooooooooox#.   ",
    " .O.   .Oooooox#...Oo.. ",
    "  .     .O....O.   ..Oo.",
    "       .Oo.  .Oo.    ..O",
    "        ..    ..       .",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
  ],
  "meat": [
    "                        ",
    "                        ",
    "                        ",
    "       .......          ",
    "     ..Ooooox#..        ",
    "    .Ooooooooox#.       ",
    "   .Ooo:ooooooox#.      ",
    "  .Ooo:oottoooox#.      ",
    "  .Oooooottooooox#...   ",
    "  .Ooooooooooo:ox#.tt.  ",
    "   .Oooooooooooooottt.  ",
    "    .Ooooooooooox#.tt.  ",
    "     ..Ooooooox#.. ..   ",
    "       .........        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
  ],
  "mud": [
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "     ..    ...          ",
    "   ..Oo....Ooo...       ",
    "  .Oooooooooooox#.      ",
    " .Oooo::oooo::oox#.     ",
    " .Oooooooooooooox#.     ",
    "  .Oo.Ooooooox#.Oo.     ",
    "   .. ......... ..      ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
  ],
  "mushroom": [
    "                        ",
    "                        ",
    "       ........         ",
    "     ..Oooooox#..       ",
    "    .Oooooooooox#.      ",
    "   .Oooo::oooooox#..    ",
    "  .Oooooooooo::ooox#.   ",
    "  .Oooooooooooooox#.    ",
    "   .Oooooooooooox#.     ",
    "    ...tttttttt...      ",
    "      .tttttttt.        ",
    "       .tttttt.         ",
    "       .tttttt.         ",
    "      .tttttttt.        ",
    "       ........         ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
  ],
  "obsidian": [
    "                        ",
    "           ..           ",
    "          .Oo.          ",
    "         .Oooo.         ",
    "        .Ooooo#.        ",
    "       .Oooooox#.       ",
    "      .Oooooooox#.      ",
    "     .Oooooo:oox#.      ",
    "     .Ooooo::oox#.      ",
    "      .Oooo::ox#.       ",
    "       .Ooo::x#.        ",
    "        .Oo::#.         ",
    "         .Ooo.          ",
    "          .O.           ",
    "           .            ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
  ],
  "pebble": [
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "        ......          ",
    "       .Ooooo#.         ",
    "      .Oooooox#.        ",
    "     .Oooo::oox#.       ",
    "     .Oooooooox#.       ",
    "      .Oooooox#.        ",
    "       ........         ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
  ],
  "pinecone": [
    "                        ",
    "                        ",
    "        ....            ",
    "       .Oooo..          ",
    "      .Oootox#..        ",
    "     .Ootooootx#.       ",
    "     .Oooootoox#.       ",
    "     .Ootooootx#.       ",
    "     .Oooootoox#.       ",
    "      .Ootooox#.        ",
    "       .Ooooo#.         ",
    "        .Oooo.          ",
    "         .Oo.           ",
    "          ..            ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
  ],
  "reeds": [
    "    .       .       .   ",
    "   .O.     .O.     .O.  ",
    "   .O.    .Oo.    .Oo.  ",
    "   .t.    .t.     .t.   ",
    "   .t.    .t.     .t.   ",
    "   .t.    .t.     .t.   ",
    "   .t.    .t.     .t.   ",
    "   .t.    .t.     .t.   ",
    "   .t.    .t.     .t.   ",
    "   .t.    .t.     .t.   ",
    "   .t.    .t.     .t.   ",
    "   .t.    .t.     .t.   ",
    "   .t.    .t.     .t.   ",
    "    .      .       .    ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
  ],
  "resin": [
    "                        ",
    "                        ",
    "         ..             ",
    "        .Oo.            ",
    "       .Oooo..          ",
    "      .Oootox#.         ",
    "     .Ooottoox#.        ",
    "     .Ooooooox#.        ",
    "      .Ooooox#.         ",
    "       .Oooo#.          ",
    "        .....           ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
  ],
  "river-rock": [
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "      ..........        ",
    "    ..Oooooooox#..      ",
    "   .Oooooooooooox#.     ",
    "  .Ooooo::ooooooox#.    ",
    "  .Oooooooooooooox#.    ",
    "   .Oooooooooooox#.     ",
    "    ..............      ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
  ],
  "sand": [
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "          .             ",
    "        ..t.            ",
    "      ..Oooo..          ",
    "    ..Oootoox#..        ",
    "   .Ooooooootox#..      ",
    "  .Ootoooooooooox#.     ",
    " .Oooooootooooooox#.    ",
    "  .................     ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
  ],
  "shell": [
    "                        ",
    "                        ",
    "          ..            ",
    "        ..Oo..          ",
    "      ..Ooooo#..        ",
    "     .Oootoooox#..      ",
    "    .Ooootoooooox#.     ",
    "   .Ooootttooooox#.     ",
    "  .Oooootttoooooox#.    ",
    "  .Ooootoootooooox#.    ",
    "   .Oooooooooooox#.     ",
    "    .Oooooooooox#.      ",
    "     ............       ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
  ],
  "stick": [
    "                        ",
    "                        ",
    "                        ",
    "                ....    ",
    "              ..Oooo.   ",
    "            ..Ooooo#.   ",
    "          ..Oooott..    ",
    "        ..Ooooo#..      ",
    "      ..Ooooo#..        ",
    "    ..Ooooo#..          ",
    "   .Ooooo#..            ",
    "  .Oooo#..              ",
    "  .Ooo..                ",
    "   ...                  ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
  ],
  "stone": [
    "                        ",
    "                        ",
    "                        ",
    "       ........         ",
    "     ..Oooooox#..       ",
    "    .Oooooooooox#.      ",
    "   .Oooooooooooox#.     ",
    "  .Oooooo::oooooox#.    ",
    "  .Oooooooooooooox#.    ",
    "   .Oooooooooooox#.     ",
    "    .Oooooooooox#.      ",
    "     ............       ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
  ],
  "straw": [
    "                        ",
    "                        ",
    "                        ",
    "   ..                   ",
    "  .Oo......             ",
    "  ..Ooooox#....         ",
    " .Ooooooooooox#....     ",
    "  .Oooooooooooooox#.    ",
    " .ttttttttttttttttt..   ",
    "  .Oooooooooooooooox#.  ",
    "   ..Ooooooooooooox#.   ",
    "     ...Oooooooox#..    ",
    "        .....Ooo..      ",
    "             ...        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
  ],
  "tool": [
    "                        ",
    "                        ",
    "          ....          ",
    "         .Oooo.         ",
    "        .Ooooo#.        ",
    "       .Oooooox#.       ",
    "      .Oooooox#.        ",
    "     .Oooooox#.         ",
    "    .Oooooox#.          ",
    "   .Oooooox#.           ",
    "  .tttooox#.            ",
    " .ttttttx#.             ",
    " .tttttttt.             ",
    "  .tttttt.              ",
    "   ......               ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
  ],
  "water": [
    "                        ",
    "        ......          ",
    "       .Ooooo#.         ",
    "       .O::::#.         ",
    "      .Oooooox#.   ..   ",
    "     .Oooooooox#. .Oo.  ",
    "    .Oooooooooox#.Ooo.  ",
    "    .Ooooooooooooox#.   ",
    "    .Oooooooooooox#.    ",
    "    .Oooooooooooox#.    ",
    "    .Ooottttttoox#.     ",
    "    .Oootttttttox#.     ",
    "     .Oooooooooox#.     ",
    "      .Oooooooox#.      ",
    "       .Oooooox#.       ",
    "        ........        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
  ],
  "wood": [
    "                        ",
    "                        ",
    "                        ",
    "   .................    ",
    "  .Ooooooooooooooox#.   ",
    "  .tttttttttttttttt#.   ",
    "  .Ooooooooooooooox#.   ",
    "   ...Oooooooox#....    ",
    "  .Ooooooooooooooox#.   ",
    "  .tttttttttttttttt#.   ",
    "  .Ooooooooooooooox#.   ",
    "   ...Oooooooox#....    ",
    "  .Ooooooooooooooox#.   ",
    "  .tttttttttttttttt#.   ",
    "  .Ooooooooooooooox#.   ",
    "   .................    ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
  ],
  "wool": [
    "                        ",
    "                        ",
    "       ........         ",
    "     ..Oooooox#..       ",
    "    .Oo::oooo::x#.      ",
    "   .Oooooo::oooox#.     ",
    "  .Oo::oooooooo::x#.    ",
    "  .Oooooo::oooooox#.    ",
    "  .Oo::ooooooo::ox#.    ",
    "  .Ooooo::oooooox#.     ",
    "   .Oo::oooooo::x#.     ",
    "    .Oooo::oooox#.      ",
    "     ..Oooooox#..       ",
    "       ........         ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
    "                        ",
  ],
};
