/**
 * services/economyService.ts - Manages dynamic pricing models.
 */
import { MapData, Item, BiomeType, ItemDefinition, CulturalZone, HistoricalEra, NpcEntity } from '../types';
import { ITEM_DEFINITIONS, getItemDefinition } from '../constants/gameData/itemDefinitions';
import { createItemInstance } from '../utils/inventoryUtils';
import { parseDateString } from '../utils/dateUtils';
import { mapLocationToCulture } from '../utils/mapUtils';

interface PriceInfo {
  buyPrice: number;
  sellPrice: number;
}

/**
 * Calculates buy and sell prices for a given item based on map context.
 * This model is driven by the supply and demand generated by terrain structures and NPC goals.
 * 
 * @param itemBaseId - The base ID of the item (e.g., 'SUGAR_CANE').
 * @param mapData - The data of the current map to determine context.
 * @param npcs - An array of all NPCs on the map to factor in their demand.
 * @returns An object with calculated buyPrice and sellPrice.
 */
export function calculatePrices(itemBaseId: string, mapData: MapData, npcs: NpcEntity[]): PriceInfo {
  const definition = getItemDefinition(itemBaseId);
  if (!definition) {
    console.warn(`No item definition found for ${itemBaseId} in economyService.`);
    return { buyPrice: 999, sellPrice: 0 };
  }

  const baseValue = definition.value;
  let supplyScore = 1.0;
  let demandScore = 1.0;

  // Structure-based supply and demand
  if (mapData.terrainStructures) {
    for (const structure of mapData.terrainStructures) {
      if (structure.state === 'ruined') continue; // Ignore ruined structures
      
      if (structure.outputGoods?.includes(itemBaseId)) {
        supplyScore += 2.0; // Significant supply increase
      }
      if (structure.inputGoods?.includes(itemBaseId)) {
        demandScore += 1.5; // Significant demand increase
      }
    }
  }

  // NPC Goal-driven demand
  if(npcs) {
    for (const npc of npcs) {
        const goal = npc.personalGoal;
        if (
            goal &&
            goal.archetype === 'ACQUIRE' &&
            (goal.targetType === 'ITEM' || goal.targetType === 'RESOURCE') &&
            goal.targetId === itemBaseId
        ) {
            demandScore += 0.1; // Add small amount of demand per NPC
        }
    }
  }
  
  // Scarcity from lack of production
  if (supplyScore <= 1.0) {
      demandScore *= 1.5; // If no structure produces this, it's scarce
  }

  // Population-based demand for essentials
  if (definition.category === 'Food' || definition.category === 'Apparel' || definition.category === 'Tool') {
    const populationCenters = mapData.tiles.flat().filter(t => 
        t.biome === BiomeType.HAMLET || 
        t.biome === BiomeType.LOW_DENSITY_CITY || 
        t.biome === BiomeType.DENSE_CITY
    ).length;
    demandScore += populationCenters * 0.1; // Each settlement adds a little demand
  }

  // Calculate price modifier, ensuring it's within a reasonable range
  const priceModifier = Math.max(0.2, Math.min(5.0, demandScore / supplyScore));

  const randomFactor = 0.9 + Math.random() * 0.2; // +/- 10% random variance

  const buyPrice = Math.ceil(baseValue * priceModifier * randomFactor * 1.25); // Player buys from market (higher price)
  const sellPrice = Math.floor(baseValue * priceModifier * randomFactor * 0.75); // Player sells to market (lower price)

  return {
    buyPrice: Math.max(1, buyPrice),
    sellPrice: Math.max(1, sellPrice),
  };
}


/**
 * Generates the list of items available for sale in a marketplace based on local production.
 * @param mapData The current map data.
 * @param npcs All NPCs on the map to calculate demand.
 * @returns An array of item definitions with their calculated prices.
 */
export function getMarketInventory(mapData: MapData, era: HistoricalEra, culturalZone: CulturalZone, npcs: NpcEntity[]): (ItemDefinition & PriceInfo)[] {
    const availableGoods = new Set<string>();
    const dateInfo = parseDateString(mapData.timeSlice || '1650');
    const currentYear = dateInfo.year;

    // 1. Gather goods from active structures
    mapData.terrainStructures?.forEach(structure => {
        if (structure.state === 'active' && structure.outputGoods) {
            structure.outputGoods.forEach(goodId => availableGoods.add(goodId));
        }
    });
    
    // 2. Add goods from farms
    mapData.tiles.flat().forEach(tile => {
        if (tile.biome === BiomeType.FARMLAND && tile.cropType) {
            const cropId = tile.cropType.toUpperCase().replace(/ /g, '_');
            if (getItemDefinition(cropId)) {
                availableGoods.add(cropId);
            }
        }
    });

    // 3. Add some common non-producible goods to ensure a baseline inventory
    ['STICK', 'ROPE', 'CLAY_LAMP', 'WOODEN_BOWL', 'LEATHER_BOOTS', 'WOOL_TUNIC', 'HEALING_POTION'].forEach(id => availableGoods.add(id));

    // 4. Calculate prices for all available goods and filter by context
    const inventory = Array.from(availableGoods)
        .map(baseId => {
            const definition = getItemDefinition(baseId);
            if (!definition || definition.value === 0) return null;

            // Historical Era Check
            if (definition.eraAvailability) {
                if (currentYear < definition.eraAvailability.startYear || currentYear > definition.eraAvailability.endYear) {
                    return null;
                }
            }

            // Cultural Availability Check
            if (definition.culturalAvailability && !definition.culturalAvailability.includes(culturalZone)) {
                // Allow globally if it's post-columbian exchange for specific items
                if (!(baseId === 'POTATO' && currentYear > 1536) && !(baseId === 'CORN' && currentYear > 1492)) {
                    return null;
                }
            }
            
            const prices = calculatePrices(baseId, mapData, npcs);
            return {
                ...definition,
                ...prices
            };
        })
        .filter((item): item is (ItemDefinition & PriceInfo) => item !== null);
        
    return inventory;
}
