import type { TaskLore } from "./types";

const FORAGING: TaskLore["scope"] = { years: [-300000, -8000] };
// Later foragers beside farmers and states: only reached through forager trades.
const LATER_FORAGING: TaskLore["scope"] = { years: [-8000, 1950] };
const VILLAGES: TaskLore["scope"] = { years: [-10000, -3000] };
// Most of the world farmed and traded by hand until well after 1800; the
// industrial fallbacks are for Europe and the settler Americas.
const AGRARIAN: TaskLore["scope"] = { years: [-3500, 1914] };
const INDUSTRIAL: TaskLore["scope"] = { years: [1800, 1914], cultures: ["european"] };
const WARS: TaskLore["scope"] = { years: [1914, 1950] };

export const generalLore: TaskLore[] = [
  // Mobile foragers before farming.
  {
    id: "lore.general.forage-seasonal-round",
    scope: FORAGING,
    topics: [{ workplace: "wild" }, { goal: "forage" }, { scene: "gather" }],
    evidence: "inferred",
    title: "Gathering on the seasonal round",
    text: "For most of the human past, plant food came from knowing where things would ripen and being there first. Foragers moved camp through a yearly circuit: nut groves in autumn, roots and tubers dug with a fire-hardened stick in the dry season, seeds and berries after rain. At Ohalo II on the Sea of Galilee, 23,000 years ago, people ground over a hundred kinds of wild seed on a stone slab. Among recent foragers such as the Hadza and the Ju/'hoansi, women's gathering often supplied most of the calories, while men's hunting supplied the prized, less reliable meat. The pattern for the deep past is inferred from such peoples, from plant remains and from starch on grinding stones.",
    wiki: ["Ohalo II", "Hunter-gatherer", "Hadza people"],
  },
  {
    id: "lore.general.forage-hunting",
    scope: FORAGING,
    topics: [{ goal: "hunt" }, { goal: "hides" }, { scene: "walk" }],
    evidence: "documented",
    title: "Spears, spear-throwers and the first bows",
    text: "The oldest surviving hunting weapons are wooden throwing spears from Schöningen in Germany, about 300,000 years old, found among the butchered bones of wild horses. Stone points hafted onto shafts followed across Africa and Eurasia. The spear-thrower, a hooked stick that lengthens the arm, let a hunter cast a light dart much harder; carved ones survive from Ice Age France. Small stone points from Sibudu Cave in South Africa suggest bows and arrows by around 64,000 years ago. A kill was skinned on the spot: the hide was scraped, dried and later softened with brains or fat into clothing, bags and tent covers, which in cold climates mattered as much as the meat.",
    wiki: ["Spear-thrower", "Bow and arrow", "Hunting"],
  },
  {
    id: "lore.general.forage-shore-and-river",
    scope: FORAGING,
    topics: [{ workplace: "water" }, { goal: "fish" }, { goal: "reeds" }, { scene: "hang" }],
    evidence: "documented",
    title: "Shellfish, harpoons and the first shore camps",
    text: "Coasts and rivers fed people early. At Pinnacle Point in South Africa, people were collecting mussels and limpets at low tide about 164,000 years ago, timing trips to the spring tides. Barbed bone harpoons from Katanda on the Semliki River in Congo, around 90,000 years old, were used on large catfish. Heaps of discarded shells, called middens, mark shore camps on every inhabited coast. Fish and meat that could not be eaten fresh were split and hung on racks to dry in the wind and smoke over the fire, the oldest way of keeping food. Reeds and rushes from the same waters made mats, bedding and cordage.",
    wiki: ["Pinnacle Point", "Midden", "Fishing"],
  },
  {
    id: "lore.general.forage-knapping",
    scope: FORAGING,
    topics: [{ workplace: "workshop" }, { goal: "materials" }, { scene: "craft" }, { goal: "day-of-work" }],
    evidence: "documented",
    title: "Knapping stone: hand axes, prepared cores and blades",
    text: "The forager's workshop was a sitting place by the hearth, a hammerstone and a lump of flint, chert, quartzite or obsidian. Shaping stone by striking off flakes is called knapping, and it changed slowly over hundreds of millennia: the teardrop hand axe of the Acheulean, then the Levallois method of preparing a core so a single blow released a flake of planned shape, then long thin blades and tiny microliths set in rows along wooden hafts. Bone, antler, ivory and wood were worked with the stone tools, and scatters of waste flakes let archaeologists refit a single knapper's session flake by flake.",
    wiki: ["Knapping", "Acheulean", "Microlith"],
  },
  {
    id: "lore.general.forage-ochre-and-flint",
    scope: FORAGING,
    topics: [{ workplace: "extraction" }, { goal: "quarry" }],
    evidence: "documented",
    title: "Ochre mines and flint outcrops",
    text: "Foragers did dig for materials. At Blombos Cave in South Africa, about 100,000 years ago, people ground red ochre, mixed it with fat and charcoal, and stored the paste in abalone shells. At the Ngwenya mine in Eswatini, people quarried haematite for pigment tens of thousands of years ago. Good stone for tools was known by name and place: people returned to the same outcrops over generations and carried the best raw material long distances. Ochre went on bodies, hides, tools and the dead, and no one knows everything it meant; practical uses as glue and sunscreen are also likely.",
    wiki: ["Ochre", "Blombos Cave", "Ngwenya Mine"],
  },
  {
    id: "lore.general.forage-fire-and-food",
    scope: FORAGING,
    topics: [{ goal: "eat" }, { scene: "cook" }, { scene: "warm" }],
    evidence: "documented",
    title: "Fire and the first cooking",
    text: "Burnt bone and ash in Wonderwerk Cave, South Africa, suggest fire in use about a million years ago, and hearths are routine in caves like Qesem in Israel by 300,000 years ago. Cooking softens meat and makes starchy roots digestible, and some researchers argue it shaped the human body itself, with smaller teeth and guts. Foragers roasted meat in the embers, baked tubers in ash, and boiled food by dropping hot stones into water held in skin, bark or a hollow in the ground. The evening fire was also the heater, the light, the defence against predators and the place where the day was talked over.",
    wiki: ["Control of fire by early humans", "Paleolithic diet", "Hearth"],
  },
  {
    id: "lore.general.forage-camps",
    scope: FORAGING,
    topics: [{ workplace: "household" }, { goal: "household" }, { aim: "household-home" }, { goal: "sleep" }, { scene: "rest" }],
    evidence: "documented",
    title: "Windbreaks, caves and mammoth-bone houses",
    text: "A forager home was usually built in an afternoon and left within weeks: a brush shelter or windbreak, a hide tent, or a rock overhang, with the hearth at its heart and bedding of grass or skins around it. In the cold steppes of Ice Age Ukraine, at Mezhyrich about 15,000 years ago, people returned season after season to houses framed with hundreds of mammoth bones. Owning little made moving easy, and what mattered was not a house but the right to use a territory, usually held through kin. Keeping the camp meant fetching fuel, minding the fire, scraping hides and caring for small children.",
    wiki: ["Mezhyrich, Cherkasy Oblast", "Hunter-gatherer", "Upper Paleolithic"],
  },
  {
    id: "lore.general.forage-water",
    scope: FORAGING,
    topics: [{ goal: "water" }, { scene: "water" }],
    evidence: "documented",
    title: "Water without pots: springs, soaks and ostrich-egg flasks",
    text: "Before pottery, the whereabouts of water governed where a band could go. Camps were set near springs, rivers and lakes, and in dry country people knew the rock hollows and sand soaks that held water after rain. At Diepkloof Rock Shelter in South Africa, about 60,000 years ago, people carried water in ostrich eggshells engraved with hatched patterns; Kalahari San still did the same in recent times, burying filled shells as caches along routes. Skin bags, gourds and bark vessels served elsewhere. Drawing water was a daily walk, usually for women and children.",
    wiki: ["Diepkloof Rock Shelter", "San peoples", "Hunter-gatherer"],
  },
  {
    id: "lore.general.forage-carrying",
    scope: FORAGING,
    topics: [{ workplace: "carrying" }, { goal: "carry" }, { goal: "firewood" }, { goal: "wood" }, { scene: "haul" }],
    evidence: "inferred",
    title: "Everything on the back: moving camp and gathering fuel",
    text: "A mobile band owned only what it could carry. Among recent foragers a woman might carry a child, a digging stick, a skin bag of food and water, and gathered fuel all at once, over many kilometres a day. Men carried weapons and hunted meat, sometimes butchering a large kill in pieces for several trips. Fuel gathering was daily work: dead wood, dry dung on the steppe, bone where trees were scarce, as at Ice Age sites in Ukraine. Dogs, domesticated from wolves by at least 15,000 years ago, later helped haul. Weight ruled what was made, so tools were light, portable and often cached for return.",
    wiki: ["Nomad", "Hunter-gatherer", "Dog"],
  },
  {
    id: "lore.general.forage-exchange",
    scope: FORAGING,
    topics: [{ workplace: "market" }, { goal: "barter" }, { goal: "sell-goods" }, { scene: "market" }],
    evidence: "inferred",
    title: "Gifts and long-distance exchange before markets",
    text: "There were no markets, but goods travelled. At Olorgesailie in Kenya, about 320,000 years ago, people used obsidian brought from sources up to 90 kilometres away. Shell beads crossed hundreds of kilometres in Ice Age Europe and Africa. Recent foragers suggest how: the Ju/'hoansi keep hxaro partnerships, long-lasting relationships of delayed gift-giving with people in other bands, so that in a bad year a family has somewhere to go. Among foragers, trading hard with kin was shameful; generosity built the obligations that kept people alive.",
    wiki: ["Olorgesailie", "Gift economy", "ǃKung people"],
  },
  {
    id: "lore.general.forage-band-talk",
    scope: FORAGING,
    topics: [{ workplace: "civic" }, { goal: "civic-rounds" }, { goal: "news" }, { goal: "neighbour" }, { scene: "talk" }],
    evidence: "inferred",
    title: "Bands, talk and keeping everyone level",
    text: "Forager bands were small, often twenty to fifty people, and joined or split as food and tempers allowed. No one could give orders. Decisions came out of long talk at the fire, and news came with visitors from other bands, carried along with gossip about game and water. Recent foragers keep people level deliberately: the Ju/'hoansi mock a hunter's big kill so he stays modest, and meat is shared by rule. Someone who hoards or bullies faces ridicule, then being left out, and finally the band moves away from them. Anthropologists call this reverse dominance hierarchy.",
    wiki: ["Band society", "Egalitarianism", "Dunbar's number"],
  },
  {
    id: "lore.general.forage-aggregation",
    scope: FORAGING,
    topics: [{ scene: "gathering" }, { goal: "any-work" }],
    evidence: "hypothesis",
    title: "Aggregation camps: when the bands came together",
    text: "Once or twice a year, when food was plentiful in one place, many bands camped together. Recent foragers from the Arctic to Australia used these times for marriages, initiations, dances, trade and settling disputes. Archaeologists suggest some Ice Age sites with dense remains and rich art, such as parts of the Magdalenian Pyrenees, were such gatherings, and the sheer effort at Göbekli Tepe around 9500 BCE implies hundreds of foragers working together. It is an inference from site size and ethnography, not a recorded fact.",
    wiki: ["Band society", "Göbekli Tepe", "Upper Paleolithic"],
  },
  {
    id: "lore.general.forage-religion",
    scope: FORAGING,
    topics: [{ goal: "worship" }, { goal: "rites" }, { scene: "offer" }, { occasion: "day.patron-offering" }],
    evidence: "hypothesis",
    title: "Painted caves and the question of Ice Age religion",
    text: "What foragers believed is mostly beyond recovery. The evidence is suggestive: animals painted deep in dark caves like Chauvet and Lascaux, often where few could see them; lion-headed ivory figures; ochre and grave goods with the dead. Many recent foragers treat animals and places as persons to be respected, with specialists who enter trance to deal with them, and some researchers read the cave art that way. Others stress hunting magic, initiation or storytelling. Treat any specific account as a hypothesis.",
    wiki: ["Paleolithic religion", "Cave painting", "Chauvet Cave"],
  },
  {
    id: "lore.general.forage-burial",
    scope: FORAGING,
    topics: [{ aim: "remember-dead" }, { aim: "widowed-household" }, { occasion: "day.death-day" }, { occasion: "day.speak-of-dead" }],
    evidence: "documented",
    title: "The first graves: Qafzeh, Panga ya Saidi and Sungir",
    text: "People have buried their dead deliberately for at least 100,000 years. At Qafzeh in Israel a child was laid in a grave with red deer antlers on its chest; at Panga ya Saidi in Kenya, about 78,000 years ago, a small child was tucked into a pit with its head on something like a pillow. At Sungir in Russia, around 34,000 years ago, two children were buried with thousands of ivory beads that took years of work. Recent forager customs vary: some avoid naming the dead and move camp, others return to graves. How grief was shaped in the deep past is inferred from such graves alone.",
    wiki: ["Qafzeh Cave", "Panga ya Saidi", "Sungir"],
  },
  {
    id: "lore.general.forage-elders",
    scope: FORAGING,
    topics: [{ aim: "elder-kin" }, { occasion: "day.elder-kin" }],
    evidence: "inferred",
    title: "Grandmothers and the care of the old",
    text: "Old people in forager bands were not idle. Among the Hadza, grandmothers past childbearing dig more tubers than younger women and feed their daughters' children, an observation behind the grandmother hypothesis: long human lives after fertility may have evolved because older women improved their grandchildren's survival. Elders also held knowledge of droughts, routes and kin ties that no one else remembered. Care is ancient: the Neanderthal Shanidar 1 lived for years with a withered arm and a blind eye, which suggests others fed and protected him.",
    wiki: ["Grandmother hypothesis", "Shanidar Cave", "Hadza people"],
  },
  {
    id: "lore.general.forage-childhood",
    scope: FORAGING,
    topics: [{ aim: "raise-kin" }, { aim: "child-future" }, { occasion: "day.teach-child" }, { scene: "play" }],
    evidence: "inferred",
    title: "Growing up in a forager band",
    text: "Forager children were raised by many hands. Mothers nursed for three or four years, and siblings, aunts and grandmothers carried and fed the young, a pattern called alloparenting. Recent forager children spend much of the day in mixed-age play groups near camp, and their play is practice: small bows, digging sticks, toy huts, games of tracking. They learn by watching and trying, with little formal teaching, and join real foraging gradually. Toys and child-sized tools from the Palaeolithic are rare but known, and fingerprints of children survive on the walls of painted caves.",
    wiki: ["Alloparenting", "Hunter-gatherer"],
  },
  {
    id: "lore.general.forage-marriage",
    scope: FORAGING,
    topics: [{ aim: "marriage-hope" }, { aim: "shared-future" }, { occasion: "day.match" }],
    evidence: "hypothesis",
    title: "Marriage between bands: bride service and exchange",
    text: "Because bands were small, spouses usually came from another band, which is called exogamy, and every marriage tied groups together. Among many recent foragers, such as the Ju/'hoansi, a young husband lives with his wife's family for years and hunts for them, which is called bride service. Sister exchange between families is also common. Marriage was usually easy to end, and most adults remarried. Ancient DNA from Ice Age graves shows relatives were buried together while bands also mixed widely. How deep-past marriages were made is reconstructed from such peoples, not recorded.",
    wiki: ["Bride service", "Exogamy", "Hunter-gatherer"],
  },
  {
    id: "lore.general.forage-lean-times",
    scope: FORAGING,
    topics: [{ aim: "restore-household" }, { goal: "food-store" }, { occasion: "day.check-store" }, { occasion: "day.borrow" }],
    evidence: "inferred",
    title: "Sharing as the store against lean seasons",
    text: "Most tropical foragers stored little: the surest store was other people. Meat shared today was repaid when someone else was lucky, and a family in trouble moved in with kin elsewhere. In colder places people did store food: caches of dried meat and fish, frozen meat in pits, nuts in baskets. Late Ice Age foragers in Europe and the Levant stored more as they settled longer in one place, a step toward farming. Recovery from disaster meant moving, not rebuilding, and debts were counted in obligations, not goods.",
    wiki: ["Food storage", "Hunter-gatherer", "Gift economy"],
  },
  {
    id: "lore.general.forage-tending-wild",
    scope: FORAGING,
    topics: [{ workplace: "field" }, { goal: "sow" }, { goal: "weed" }, { goal: "harvest" }, { goal: "winter-field" }, { scene: "tend" }],
    evidence: "inferred",
    title: "Tending wild plants: burning, weeding and replanting",
    text: "Foragers did not farm, but they did manage plants. Aboriginal Australians burned country in patchy mosaics to bring on fresh grass and green shoots, a practice called fire-stick farming, and many peoples replanted the tops of yams they dug. At Ohalo II, 23,000 years ago, people harvested wild wheat and barley with flint sickles and pulled weeds of cultivation around them. The line between gathering a wild stand and cultivating it was blurred for thousands of years before true farming.",
    wiki: ["Fire-stick farming", "Ohalo II", "Neolithic Revolution"],
  },
  {
    id: "lore.general.forage-herds",
    scope: FORAGING,
    topics: [{ workplace: "pasture" }, { goal: "fodder" }, { goal: "wool" }, { scene: "herd" }],
    evidence: "documented",
    title: "Following the herds: reindeer, bison and horse",
    text: "No animal but the dog was domesticated before the end of the Ice Age, but some foragers lived closely with herds. Magdalenian people in France and Germany timed their year to reindeer migrations, killing at river crossings in autumn when hides and fat were best. On the plains, hunters drove bison and horse into gullies and traps. Watching herds, predicting their movements and never over-killing a place was the forager's version of husbandry. Reindeer herding as a way of life came much later, among Siberian and Sami peoples.",
    wiki: ["Reindeer herding", "Upper Paleolithic", "Hunting"],
  },
  {
    id: "lore.general.forage-knowing-country",
    scope: FORAGING,
    topics: [{ aim: "make-a-life" }, { aim: "find-belonging" }, { aim: "new-settlement" }, { aim: "mastery" }],
    evidence: "inferred",
    title: "Knowing country: how foragers belonged to land",
    text: "A forager's wealth was knowledge: which waterholes lasted, where honey was, how game behaved, which kin in other bands would take you in. Mastery came slowly, and a hunter reached his best in his thirties or forties. Moving to a new place meant asking the people whose country it was, usually through a kin link, and visitors who came empty-handed were still fed. Modern humans spread out of Africa across Asia, into Australia by at least 50,000 years ago and into the Americas by the end of the Ice Age, carrying these habits of belonging with them.",
    wiki: ["Hunter-gatherer", "Band society", "Upper Paleolithic"],
  },

  // Foragers alongside farmers and states, reached only through forager trades.
  {
    id: "lore.general.later-foragers",
    scope: LATER_FORAGING,
    topics: [{ trade: /^(Forager|Gatherer)\b/ }],
    evidence: "documented",
    title: "Foragers beside farmers: Hadza, San, Mbuti and Batek",
    text: "Foraging did not end when farming began. Across Africa, South and Southeast Asia, Australia, the Arctic and much of the Americas, people went on living by gathering and hunting into the twentieth century, often trading with farming neighbours. Mbuti of the Congo forest traded meat and honey to villagers for plantains and iron; Batek of Malaysia sold rattan and forest resins that ended up in distant markets. A forager's day was often shorter in hours than a farmer's, but these peoples were pushed onto marginal land by states and settlers, and colonial governments tried to settle them.",
    wiki: ["Hunter-gatherer", "Mbuti people", "Batek people"],
  },
  {
    id: "lore.general.later-hunters",
    scope: LATER_FORAGING,
    topics: [{ trade: /Hunter\b|Looking for game/ }],
    evidence: "documented",
    title: "Living by the hunt: bows, nets, blowguns and snares",
    text: "Hunting peoples fitted their weapons to their game. Mbuti hunters strung long nets through the forest and drove antelope into them with the women and children; Amazonian and Southeast Asian hunters shot monkeys and birds with poisoned blowgun darts; Plains peoples ran bison over cliffs; San hunters tracked antelope for days after a small poisoned arrow struck. Persistence hunting, running an animal down in heat, is recorded in the Kalahari. Meat was shared by rule, often through the owner of the arrow rather than the shooter, so luck was spread across the camp.",
    wiki: ["Hunting", "Persistence hunting", "San peoples"],
  },
  {
    id: "lore.general.later-trappers",
    scope: LATER_FORAGING,
    topics: [{ trade: /Trapper/ }],
    evidence: "documented",
    title: "Traps, weirs and the fur trade",
    text: "Traps let a hunter be in many places at once. Foragers set snares for rabbits and birds, deadfalls for larger game, and wicker fish and eel traps in streams. At Budj Bim in Australia, the Gunditjmara built stone channels and ponds to catch short-finned eels more than 6,000 years ago. From the 1500s, European demand for beaver and fox fur turned trapping in North America and Siberia into a commercial livelihood: Indigenous trappers traded pelts to French, Hudson's Bay and Russian merchants for guns, kettles and cloth, which reshaped their seasons and their debts.",
    wiki: ["Trapping", "Budj Bim", "Fur trade"],
  },
  {
    id: "lore.general.later-shore-hunters",
    scope: LATER_FORAGING,
    topics: [{ trade: /Shellfish|Seal|Walrus|Sea-turtle/ }],
    evidence: "documented",
    title: "Shore foragers: shellfish, seals and turtles",
    text: "Coasts offered food that stood still. Shell middens metres high mark centuries of shellfish gathering in Denmark, Brazil, Japan and Australia, usually women's and children's work at low tide. In the Arctic, Inuit hunters waited at seals' breathing holes in the sea ice with harpoons and hunted walrus from skin boats, and the blubber lit and heated their houses. Torres Strait and Pacific islanders speared or netted sea turtles on nesting beaches. Big catches were shared out by fixed rules among the crew and kin.",
    wiki: ["Midden", "Hunter-gatherer", "Hunting"],
  },

  // Early farming villages.
  {
    id: "lore.general.village-first-fields",
    scope: VILLAGES,
    topics: [{ workplace: "field" }, { goal: "sow" }, { goal: "weed" }, { goal: "harvest" }, { scene: "tend" }],
    evidence: "documented",
    title: "The first fields: digging sticks, hoes and flint sickles",
    text: "Farming began independently in several places: wheat, barley and lentils in the Fertile Crescent from about 9500 BCE; millet and rice in China; taro and banana in drained plots at Kuk Swamp in New Guinea; squash and then maize in Mexico. There were no ploughs. Ground was broken with digging sticks and stone or antler hoes, seed sown by hand, weeds pulled, and cereals cut with sickles of flint blades set in wood or bone, which wore a telltale gloss. The work was heavier than foraging and people's skeletons show it, with worn knees and backs.",
    wiki: ["Neolithic Revolution", "Kuk Swamp", "Sickle"],
  },
  {
    id: "lore.general.village-granaries",
    scope: VILLAGES,
    topics: [{ goal: "food-store" }, { occasion: "day.check-store" }, { scene: "gather" }],
    evidence: "documented",
    title: "Granaries, storage pits and the first pots",
    text: "Farming made storage the centre of life: a harvest had to last a year and keep seed for sowing. Some of the oldest granaries, raised on floors to let air under, were built near the Jordan valley around 9500 BCE, even before crops were fully domesticated. Villagers dug clay-lined pits, wove baskets, and in many regions made pottery to keep grain from damp and mice. Checking the store for mould and pests was constant. Stored food also meant wealth that could be owned, stolen or envied, one reason villages grew walls.",
    wiki: ["Granary", "Food storage", "Neolithic Revolution"],
  },
  {
    id: "lore.general.village-first-herds",
    scope: VILLAGES,
    topics: [{ workplace: "pasture" }, { goal: "fodder" }, { goal: "wool" }, { scene: "herd" }],
    evidence: "documented",
    title: "The first herds: goats, sheep, cattle and pigs",
    text: "Goats and sheep were domesticated in the Zagros and Taurus mountains around 8500 BCE, cattle from aurochs in the Near East and separately as zebu near Mehrgarh in South Asia, and pigs in both Anatolia and China. Early herds were kept mostly for meat. Milking came in early too, since dairy fats appear in Anatolian pots around 7000 BCE, but woolly sheep, ox-drawn ploughs and carts belong to the later 'secondary products revolution' of the fourth millennium BCE. Children and young men took animals out to graze and brought them back at night to pens.",
    wiki: ["Secondary products revolution", "Domestication of vertebrates", "Mehrgarh"],
  },
  {
    id: "lore.general.village-crafts",
    scope: VILLAGES,
    topics: [{ workplace: "workshop" }, { goal: "materials" }, { goal: "day-of-work" }, { scene: "craft" }, { occasion: "day.craft-power" }],
    evidence: "documented",
    title: "Pots, polished axes and the first looms",
    text: "Village life brought new crafts. Pottery was not a farmers' invention: Jōmon foragers in Japan made cooking pots around 14,000 BCE. But farming villages everywhere made it in quantity, coiling clay and firing it in open bonfires or simple kilns. Stone axes were ground and polished for felling trees. Flax was spun and woven on simple looms, and clay spindle whorls and loom weights are common finds. Most craft was done at home by the household, and full-time specialists were rare until towns grew.",
    wiki: ["Jōmon pottery", "Loom", "Flax"],
  },
  {
    id: "lore.general.village-mines",
    scope: VILLAGES,
    topics: [{ workplace: "extraction" }, { goal: "quarry" }],
    evidence: "documented",
    title: "Flint mines and axe-stone quarries",
    text: "Neolithic Europeans sank shafts through chalk to reach the best flint. At Spiennes in Belgium, from about 4400 BCE, miners dug shafts more than ten metres deep with antler picks and worked outward along the seams. At Krzemionki in Poland they mined striped flint for axes, and in the Langdale fells of England people shaped greenstone roughouts on scree slopes high above the valley. The axes travelled hundreds of kilometres from these places. Mining was likely seasonal work alongside farming, not a full-time trade.",
    wiki: ["Neolithic flint mines of Spiennes", "Krzemionki", "Langdale axe industry"],
  },
  {
    id: "lore.general.village-exchange",
    scope: VILLAGES,
    topics: [{ workplace: "market" }, { goal: "barter" }, { goal: "sell-goods" }, { goal: "stock" }, { scene: "market" }],
    evidence: "documented",
    title: "Obsidian, shells and jade: exchange without markets",
    text: "Early farmers had no markets or money, but valued things moved far. Obsidian from central Anatolia reached villages across the Levant; Spondylus shells from the Aegean were worn as bracelets in graves along the Danube; polished axes of Alpine jade reached Brittany and Britain. Most such goods probably moved hand to hand as gifts between exchange partners, as bride payments or at feasts, rather than being bartered for profit. Everyday goods were made and swapped within the village among kin.",
    wiki: ["Spondylus", "Obsidian", "Gift economy"],
  },
  {
    id: "lore.general.village-wells",
    scope: VILLAGES,
    topics: [{ goal: "water" }, { scene: "water" }],
    evidence: "documented",
    title: "The first wells: Cyprus, Atlit Yam and timber-lined shafts",
    text: "Settling down meant needing water in one place all year. Some of the oldest known wells were dug on Cyprus around 8400 BCE, at Kissonerga-Mylouthkia, cut through rock to groundwater. At Atlit Yam, a village now under the sea off Israel, a stone-lined well served a community around 6500 BCE. Linear Pottery farmers in central Europe around 5100 BCE lined wells with split oak timbers, which survive and can be tree-ring dated. Most villages still sat beside springs or rivers, and water was carried in pots and skins, mostly by women.",
    wiki: ["Kissonerga", "Atlit Yam", "Well"],
  },
  {
    id: "lore.general.village-houses",
    scope: VILLAGES,
    topics: [{ workplace: "household" }, { goal: "household" }, { aim: "household-home" }, { goal: "sleep" }, { scene: "rest" }, { occasion: "day.mend-home" }],
    evidence: "documented",
    title: "Houses that lasted: Çatalhöyük and the longhouse",
    text: "Farmers built to stay. At Çatalhöyük in Anatolia, around 7000 BCE, mud-brick houses were packed so tightly that people entered through the roof by ladder, and each house was replastered many times a year and rebuilt on its own ruins. In central Europe, Linear Pottery farmers built timber longhouses up to 40 metres long, with families, stores and perhaps animals under one roof. In China, early villages had sunken pit-houses. A house tied a family to its fields and its dead, and passing it on became a question for the first time.",
    wiki: ["Çatalhöyük", "Linear Pottery culture", "Longhouse"],
  },
  {
    id: "lore.general.village-diet",
    scope: VILLAGES,
    topics: [{ goal: "eat" }, { scene: "cook" }, { scene: "warm" }],
    evidence: "documented",
    title: "Porridge, flatbread and a narrower diet",
    text: "Early farmers ate a lot of grain: ground on a saddle quern, then boiled into porridge or baked as flatbread on hot stones. Rice was steamed and boiled in China, where fermented drinks of rice, honey and fruit were brewed at Jiahu by about 7000 BCE. Farming fed more people but not always better: early farmers' skeletons show more tooth decay, anaemia and shorter stature than those of foragers, since the diet was narrower and bad harvests hit hard. The hearth, often inside the house, cooked, heated and dried everything.",
    wiki: ["Quern-stone", "Jiahu", "Neolithic Revolution"],
  },
  {
    id: "lore.general.village-shrines",
    scope: VILLAGES,
    topics: [{ goal: "worship" }, { goal: "rites" }, { scene: "offer" }, { occasion: "day.patron-offering" }],
    evidence: "hypothesis",
    title: "Göbekli Tepe, bull horns and plastered skulls",
    text: "The earliest monuments came before or with farming. At Göbekli Tepe in Anatolia, around 9500 BCE, people raised circles of T-shaped stone pillars carved with foxes, snakes and vultures. At Çatalhöyük, rooms held bull horns set in plaster and painted walls. What these meant is argued over. Across the Neolithic Near East, special buildings, figurines and feasting refuse suggest rites centred on ancestors, animals and fertility, but names of gods or beliefs do not survive, so any account is reconstruction.",
    wiki: ["Göbekli Tepe", "Çatalhöyük", "Plastered human skulls"],
  },
  {
    id: "lore.general.village-ancestors",
    scope: VILLAGES,
    topics: [{ aim: "remember-dead" }, { aim: "widowed-household" }, { occasion: "day.death-day" }, { occasion: "day.speak-of-dead" }],
    evidence: "documented",
    title: "Ancestors under the floor and in the stone tomb",
    text: "Many early farmers kept their dead close. In the Levant around 7000 BCE, people buried the dead under house floors, later lifted their skulls, remodelled the faces in plaster with shells for eyes, and kept them among the living. At Çatalhöyük, burials lay beneath sleeping platforms. In Atlantic Europe from about 4500 BCE, communities built stone chambered tombs where bones of many generations were mixed and revisited. These practices suggest the dead remained members of the household and guarantors of its land, though their precise meaning is inferred.",
    wiki: ["Plastered human skulls", "Chambered cairn", "Veneration of the dead"],
  },
  {
    id: "lore.general.village-marriage",
    scope: VILLAGES,
    topics: [{ aim: "marriage-hope" }, { aim: "shared-future" }, { occasion: "day.match" }],
    evidence: "documented",
    title: "Brides who moved: marriage in the first villages",
    text: "Chemical signatures in teeth show where a person grew up. In Linear Pottery cemeteries of central Europe, around 5000 BCE, women were more often born elsewhere than men, which suggests men stayed on their family land and wives married in from other villages, a pattern called patrilocal residence. Ancient DNA from other Neolithic sites points the same way. Land and herds gave families something to pass on and so a stake in who married whom. What was given at a wedding in this period is unknown.",
    wiki: ["Patrilocal residence", "Linear Pottery culture", "Exogamy"],
  },
  {
    id: "lore.general.village-children-elders",
    scope: VILLAGES,
    topics: [{ aim: "raise-kin" }, { aim: "child-future" }, { aim: "elder-kin" }, { occasion: "day.teach-child" }, { occasion: "day.elder-kin" }, { scene: "play" }],
    evidence: "inferred",
    title: "More children and more work: the farming baby boom",
    text: "Settled farming brought more babies. Cemeteries show the share of young children rising sharply as villages spread, which demographers call the Neolithic demographic transition: soft porridge let mothers wean sooner and have children closer together. Children became useful early, scaring birds from crops, minding animals and younger siblings, carrying water. They still played, and clay figurines and small pots may be toys. Old people held knowledge of land and kin, and in a house-based village they were likely cared for at home. Mortality stayed high at every age.",
    wiki: ["Neolithic demographic transition", "Neolithic Revolution"],
  },
  {
    id: "lore.general.village-councils",
    scope: VILLAGES,
    topics: [{ workplace: "civic" }, { goal: "civic-rounds" }, { goal: "news" }, { goal: "neighbour" }, { scene: "talk" }, { scene: "gathering" }, { occasion: "day.quarrel" }],
    evidence: "inferred",
    title: "Keeping peace without chiefs: feasts and village talk",
    text: "Early villages had no kings or written law. Houses at Çatalhöyük are strikingly alike, which suggests no ruling family. Disputes were settled through kin and elders, and feasts, visible in pits full of cattle bones, bound neighbours in debt and friendship. Peace failed too: at Talheim in Germany, around 5000 BCE, 34 people were killed and thrown into a pit. News moved on foot with visitors, traders and brides. The anthropologist's picture of 'tribal' village life is a guide, not a record.",
    wiki: ["Talheim Death Pit", "Banquet", "Çatalhöyük"],
  },
  {
    id: "lore.general.village-carrying",
    scope: VILLAGES,
    topics: [{ workplace: "carrying" }, { goal: "carry" }, { goal: "firewood" }, { goal: "wood" }, { scene: "haul" }],
    evidence: "documented",
    title: "Carrying before the wheel, and the first managed woods",
    text: "There were no wheels until about 3500 BCE and no pack animals until donkeys were tamed in northeast Africa around 4000 BCE, so early farmers carried everything on backs and heads, or dragged it on sledges. Fuel came from clearing woodland for fields. People soon managed woods: Britain's Sweet Track, a plank walkway built across a Somerset marsh in 3807 BCE, used poles cut from hazel coppices, stools cut back so they grew straight rods. Canoes carried heavy loads along rivers and coasts.",
    wiki: ["Sweet Track", "Coppicing", "Neolithic Europe"],
  },
  {
    id: "lore.general.village-hard-years",
    scope: VILLAGES,
    topics: [{ aim: "restore-household" }, { occasion: "day.borrow" }, { occasion: "day.debt" }],
    evidence: "inferred",
    title: "Bad harvests in the first villages",
    text: "A farming village could not simply move on as foragers did. Early farmers spread risk by planting several crops in scattered plots, keeping animals as walking stores, sharing with kin, and falling back on wild food. When things went badly, whole villages were abandoned: the cold, dry spell around 6200 BCE, called the 8.2-kiloyear event, coincides with the desertion of sites across the Near East. Borrowing grain from a better-off household was likely common, and may be where lasting inequality began.",
    wiki: ["8.2-kiloyear event", "Neolithic Revolution", "Food storage"],
  },
  {
    id: "lore.general.village-still-foraging",
    scope: VILLAGES,
    topics: [{ workplace: "wild" }, { workplace: "water" }, { goal: "forage" }, { goal: "hunt" }, { goal: "fish" }, { goal: "hides" }, { goal: "reeds" }, { scene: "hang" }],
    evidence: "documented",
    title: "Hunting, fishing and gathering beside the fields",
    text: "Early farmers never stopped foraging. Bones from Neolithic villages include deer, boar and wildfowl; fish traps, nets and bone hooks are common near water; wild fruits, nuts and greens show up in their hearths. At Hemudu in the lower Yangtze, around 5000 BCE, rice farmers living in pile houses also ate huge amounts of water chestnuts, fish and turtles. Fish were split and dried on racks, and reeds cut for thatch and matting. For many generations foraging supplied a real share of the diet.",
    wiki: ["Hemudu culture", "Neolithic Revolution", "Fishing"],
  },
  {
    id: "lore.general.village-spread",
    scope: VILLAGES,
    topics: [{ aim: "new-settlement" }, { aim: "find-belonging" }, { aim: "make-a-life" }, { aim: "mastery" }, { scene: "walk" }],
    evidence: "documented",
    title: "Farmers on the move: how farming spread",
    text: "Farming mostly spread with farmers. Ancient DNA shows that the first farmers of Europe descended from Anatolian farmers who reached the Balkans around 6500 BCE and moved up the Danube as the Linear Pottery culture, founding new villages a generation's walk further on. Local foragers were partly absorbed. Similar expansions carried farming from southern China into Southeast Asia. A young couple starting out would clear new land at the edge of a daughter village, taking seed, animals and kin ties with them.",
    wiki: ["Neolithic Europe", "Linear Pottery culture", "Neolithic Revolution"],
  },

  // Agrarian states and towns before industry.
  {
    id: "lore.general.agrarian-plough-hoe",
    scope: AGRARIAN,
    topics: [{ workplace: "field" }, { goal: "sow" }, { goal: "weed" }, { goal: "harvest" }, { scene: "tend" }],
    evidence: "documented",
    title: "Plough, hoe and paddy: the farming year",
    text: "Before machines, most people everywhere were farmers, and their tools split the world. Across Eurasia and North Africa, oxen pulled a scratch-plough (ard) or later a heavy plough, and men usually ploughed. In much of sub-Saharan Africa, the Americas and the Pacific, fields were worked by hand with hoes and digging sticks, and women often did most of the farming. In monsoon Asia, rice seedlings were raised in nurseries and transplanted by hand into flooded paddies, stooping for days in the water. Harvest was the peak of labour: whole families reaped with sickles.",
    wiki: ["Ard (plough)", "Hoe-farming", "Paddy field"],
  },
  {
    id: "lore.general.agrarian-fallow-terraces",
    scope: AGRARIAN,
    topics: [{ goal: "winter-field" }, { goal: "fodder" }, { occasion: "day.check-store" }],
    evidence: "documented",
    title: "Keeping soil alive: fallow, manure, terraces and chinampas",
    text: "Every farming system had to restore fertility. Medieval European villages rotated winter grain, spring grain and fallow in open fields, grazing the fallow so animals manured it. Chinese farmers carried night soil from towns to fields. Andean and Southeast Asian farmers cut terraces into mountainsides to hold soil and water. The Aztecs built chinampas, raised beds of lake mud, in the shallows around Tenochtitlan. In slack seasons, men and women mended fences and ditches, cut hay and fodder for winter, and checked stored seed.",
    wiki: ["Three-field system", "Chinampa", "Terrace (earthworks)"],
  },
  {
    id: "lore.general.agrarian-pastoralism",
    scope: AGRARIAN,
    topics: [{ workplace: "pasture" }, { goal: "wool" }, { scene: "herd" }],
    evidence: "documented",
    title: "Shepherds, herders and the seasonal move",
    text: "Where land was too dry, cold or steep to farm, people lived from herds. Mongol and Turkic nomads moved horses, sheep and camels between summer and winter pastures; Bedouin followed rain with camels and goats; East African cattle-keepers counted wealth in cattle; Andean herders kept llamas and alpacas. Even farming villages sent flocks to upland pastures each summer, a move called transhumance. Herding was often the work of boys and young men, and flocks were sheared each spring for wool, spun into yarn by women through the year.",
    wiki: ["Pastoralism", "Transhumance", "Sheep farming"],
  },
  {
    id: "lore.general.agrarian-commons",
    scope: { ...AGRARIAN, cultures: ["european"] },
    topics: [{ workplace: "wild" }, { goal: "forage" }, { goal: "hunt" }, { goal: "wood" }, { goal: "hides" }, { scene: "gather" }],
    evidence: "documented",
    title: "Common land, royal forests and the right to glean",
    text: "The land beyond the fields fed farmers too. Villagers gathered nuts, berries, mushrooms and greens, cut bracken and wood, and turned out pigs to eat acorns, under rights set by custom. Lords and kings took some land for themselves: English 'royal forests' punished poaching of deer, and Chinese and Mughal emperors kept hunting parks. After harvest, the poor had a right to glean fallen grain, a custom known from the Bible to 19th-century Europe. In hard years, wild 'famine foods' such as acorn flour or roots saved lives.",
    wiki: ["Commons", "Gleaning", "Royal forest"],
  },
  {
    id: "lore.general.agrarian-fishing",
    scope: AGRARIAN,
    topics: [{ workplace: "water" }, { goal: "fish" }, { goal: "reeds" }, { scene: "hang" }],
    evidence: "documented",
    title: "Fish weirs, salt cod and the fishing year",
    text: "Fishing fed coasts and rivers everywhere. Weirs of stakes and wattle trapped fish on tides and rivers; nets, lines and spears worked from small boats. Salt and drying made fish a trade good: the Romans made fermented fish sauce, garum, in industrial vats; medieval Europeans ate dried and salted cod on the Church's many fast days; Chinese farmers raised carp in ponds beside rice fields. Fish were gutted, split and hung to dry on racks or in smokehouses. Reed beds supplied thatch, mats and baskets, cut in winter when stems were dry.",
    wiki: ["Fishing weir", "Dried and salted cod", "Fishing"],
  },
  {
    id: "lore.general.agrarian-mines",
    scope: AGRARIAN,
    topics: [{ workplace: "extraction" }, { goal: "quarry" }],
    evidence: "documented",
    title: "Mines and quarries by hand: Laurion, Potosí and the salt pans",
    text: "Before steam, mines were dug with picks, fire-setting and wedges, and drained by hand or by animal-driven wheels. The work was notoriously deadly and often forced. Athens' silver mines at Laurion were worked by thousands of slaves, their silver paying for the fleet that fought Persia in 480 BCE. After 1573, Spanish Peru drafted Andean men through the mita, adapted from the Inca labour tax, to dig silver at Potosí. Quarrying stone for temples and walls was often corvée work too, while salt pans on coasts were worked by families.",
    wiki: ["Lavrio", "Mit'a", "Potosí"],
  },
  {
    id: "lore.general.agrarian-guilds",
    scope: AGRARIAN,
    topics: [{ workplace: "workshop" }, { goal: "materials" }, { goal: "day-of-work" }, { aim: "mastery" }, { scene: "craft" }, { occasion: "day.craft-power" }],
    evidence: "documented",
    title: "Workshops, guilds and the long road to mastery",
    text: "Craft in towns was organised by trade. Roman craftsmen formed collegia; medieval European guilds fixed prices, quality and who could open a shop; Indian merchants and artisans had shreni; Ottoman esnaf and Chinese trade associations did the same. A boy, and less often a girl, was apprenticed for years, living in the master's house for board and training rather than wages, then worked as a journeyman before, with luck and money, becoming a master. Each craft had its patron: a saint, a god, a founding ancestor honoured at the guild's feast.",
    wiki: ["Guild", "Apprenticeship", "Shreni"],
  },
  {
    id: "lore.general.agrarian-markets",
    scope: AGRARIAN,
    topics: [{ workplace: "market" }, { goal: "sell-goods" }, { goal: "stock" }, { goal: "barter" }, { scene: "market" }],
    evidence: "documented",
    title: "Market days: bazaars, fairs and periodic markets",
    text: "Most country people traded on a fixed market day rather than in shops. Market towns across China ran on cycles of every few days, so pedlars could circuit them; Yoruba and Igbo markets in West Africa followed a four-day week; the great market at Tlatelolco in the Aztec capital drew crowds that Spanish witnesses put in the tens of thousands, with judges to settle disputes. Cities had permanent bazaars and souks arranged by trade. Barter was common alongside coin, cowrie shells, cacao beans, lengths of cloth or salt as money.",
    wiki: ["Market town", "Bazaar", "Tlatelolco (altepetl)"],
  },
  {
    id: "lore.general.agrarian-credit",
    scope: AGRARIAN,
    topics: [{ occasion: "day.borrow" }, { occasion: "day.debt" }, { aim: "restore-household" }],
    evidence: "documented",
    title: "Borrowing, debt bondage and debt cancellation",
    text: "Debt is older than coinage. Mesopotamian farmers borrowed seed grain against the next harvest at high interest, and kings periodically cancelled such debts by decree to stop families losing land. Where debts could not be paid, a son, daughter or the debtor himself might be pledged to work, a practice called debt bondage, known from Babylon to early modern India. Village credit ran on tally sticks and memory; moneylenders, temples and landlords lent in every agrarian state. Religious law often limited interest, Christian and Islamic rules against usury among them.",
    wiki: ["Debt bondage", "Tally stick", "Loan"],
  },
  {
    id: "lore.general.agrarian-granaries",
    scope: AGRARIAN,
    topics: [{ goal: "food-store" }, { scene: "gather" }],
    evidence: "documented",
    title: "Granaries against famine: jars, pits and state stores",
    text: "Households kept grain in jars, pits, lofts and raised granaries, and the anxious check of the store was a daily fact of life in the months before harvest. States stored too. Egyptian and Mesopotamian temples and palaces held grain as taxes and rations. Chinese dynasties from the Han onward ran 'ever-normal granaries' that bought grain when it was cheap and sold it when harvests failed. The Inca lined hillsides with storehouses called qollqa. Salt, drying, smoking, pickling and fermenting kept the rest.",
    wiki: ["Buffer stock scheme", "Granary", "Food storage"],
  },
  {
    id: "lore.general.agrarian-civic",
    scope: AGRARIAN,
    topics: [{ workplace: "civic" }, { goal: "civic-rounds" }],
    evidence: "documented",
    title: "Headmen, tax collectors and forced labour",
    text: "For most villagers, the state meant the tax. Village heads collected a share of the harvest in grain or goods, often as a fixed quota for which they were answerable. Many states rented out tax collection to the highest bidder, tax farming, from Rome to the Ottomans. Labour was taxed as well: corvée drafts built Egypt's canals and pyramids, China's walls and canals, and roads in the Inca realm. Scribes kept the lists that made this possible, and anyone who could write held a certain power.",
    wiki: ["Corvée", "Tax farming", "Mit'a"],
  },
  {
    id: "lore.general.agrarian-porters",
    scope: AGRARIAN,
    topics: [{ workplace: "carrying" }, { goal: "carry" }, { scene: "haul" }],
    evidence: "documented",
    title: "Porters, carrying poles and caravans",
    text: "Before railways, overland transport was slow and expensive, and water was far cheaper. In Mesoamerica, with no draught animals, professional porters called tlamemeh carried loads with tumplines across the forehead. Chinese porters balanced loads at both ends of a shoulder pole. Across Africa, head-loading was everyday work, often done by women. Camel caravans crossed the Sahara and Arabia; mule and donkey trains and llama herds on the Inca roads moved goods where wheels could not go, and caravanserais sheltered them at a day's intervals.",
    wiki: ["Tameme", "Carrying pole", "Caravan (travellers)"],
  },
  {
    id: "lore.general.agrarian-fuel",
    scope: AGRARIAN,
    topics: [{ goal: "firewood" }, { scene: "warm" }],
    evidence: "documented",
    title: "Firewood, charcoal, dung and peat",
    text: "Fuel was a daily chore and a constant cost. Villagers gathered fallen wood and cut coppice poles, often under strict customary rules. Towns bought firewood and charcoal made by charcoal burners in the forests. Where trees were scarce, people burned dried dung cakes, as on the Indian plains and the Central Asian steppe, or cut peat from bogs in Ireland and the Netherlands. Northern Chinese and Korean homes ran flues under brick sleeping platforms (kang, ondol) to warm the bed with the kitchen fire.",
    wiki: ["Charcoal burner", "Peat", "Kang (heated platform)"],
  },
  {
    id: "lore.general.agrarian-staples",
    scope: AGRARIAN,
    topics: [{ workplace: "household" }, { goal: "household" }, { goal: "eat" }, { scene: "cook" }],
    evidence: "documented",
    title: "Staple and relish: the pot at the centre of every meal",
    text: "Nearly everywhere, a meal was a large starch and a small relish. Europeans lived on bread, porridge and pottage; Chinese on rice or millet with vegetables; Mesoamericans on maize softened with lime, a process called nixtamalization, ground on a metate and made into tortillas; West Africans on millet, sorghum or yams pounded in mortars. Meat was for festivals. The daily work of grinding, pounding and cooking fell mostly on women and girls and could take hours; a Mesoamerican woman might spend a third of her day at the grindstone.",
    wiki: ["Staple food", "Nixtamalization", "Pottage"],
  },
  {
    id: "lore.general.agrarian-water",
    scope: AGRARIAN,
    topics: [{ goal: "water" }, { scene: "water" }],
    evidence: "documented",
    title: "Water before taps: wells, cisterns, qanats and carriers",
    text: "Water was carried, usually by women, girls and servants, in jars on heads or shoulders. Towns dug public wells and cut cisterns to catch rain; Constantinople's great cisterns held water brought by aqueduct. In Iran and the dry lands east and west of it, qanats, gently sloping tunnels, brought groundwater to fields and towns by gravity. In India, stepped wells let people walk down to the water table. The shaduf, a pole with a weight and bucket, lifted water from Egyptian and Mesopotamian canals. Cairo and Istanbul had professional water carriers.",
    wiki: ["Qanat", "Shadoof", "Stepwell"],
  },
  {
    id: "lore.general.agrarian-inheritance",
    scope: AGRARIAN,
    topics: [{ aim: "household-home" }],
    evidence: "documented",
    title: "Who gets the house: partible inheritance and primogeniture",
    text: "Whoever held land held life, so inheritance rules shaped every household. In China, family property was divided equally among sons; in Norman England, land went to the eldest son alone, leaving younger sons to the church, army or trade. In joint families of India, brothers kept the land together under the eldest. Japanese peasants passed the house intact to one heir. Daughters usually received a dowry instead of land, though in Islamic law they inherited half a son's share. Where land was divided, farms shrank each generation.",
    wiki: ["Partible inheritance", "Primogeniture", "Extended family"],
  },
  {
    id: "lore.general.agrarian-mending",
    scope: AGRARIAN,
    topics: [{ occasion: "day.mend-home" }, { goal: "sleep" }, { scene: "rest" }],
    evidence: "documented",
    title: "Thatch, daub and communal work: keeping a house standing",
    text: "Most houses were built by their owners from local materials: mud brick, wattle and daub, timber, stone, reed or palm thatch. They needed constant care. Thatch was patched and renewed every few decades; mud walls were replastered after the rains. Big jobs, raising a frame or thatching a roof, were done by neighbours together in exchange for food, drink and the promise of help back, a custom found in Irish meitheal, Andean ayni and Russian pomochi. Beds were shared by several family members, and many people slept in two parts.",
    wiki: ["Thatching", "Wattle and daub", "Communal work"],
  },
  {
    id: "lore.general.agrarian-marriage",
    scope: AGRARIAN,
    topics: [{ aim: "marriage-hope" }, { aim: "shared-future" }, { occasion: "day.match" }],
    evidence: "documented",
    title: "Bride price and dowry: how marriages were made",
    text: "Marriage was mainly a bargain between families. In much of Africa, and in parts of Asia and the Pacific, the groom's family paid bridewealth in cattle, cloth or money to the bride's family, compensating them for losing her work and children. In Europe, the Mediterranean and India, the bride's family paid a dowry. Parents, go-betweens or professional matchmakers arranged most first marriages, and the couple's wishes counted to different degrees. In northwestern Europe, people married late, in their mid-twenties, after years working to save; in much of Asia, girls married in their teens.",
    wiki: ["Bride price", "Dowry", "Arranged marriage"],
  },
  {
    id: "lore.general.agrarian-old-age",
    scope: AGRARIAN,
    topics: [{ aim: "elder-kin" }, { occasion: "day.elder-kin" }],
    evidence: "documented",
    title: "Old age before pensions: filial duty and retirement contracts",
    text: "Children were the only pension. Chinese teaching made filial piety the root of morality, and neglect of parents could be punished by law. In medieval Europe, ageing peasants often handed their land to a son or even a stranger in a written maintenance agreement, which specified a room, a place by the fire, and yearly quantities of grain, cloth and fuel. Monasteries and almshouses took in some without kin. Surviving to old age was not rare once childhood was passed; people of sixty or seventy were common in villages.",
    wiki: ["Filial piety", "Old age", "Extended family"],
  },
  {
    id: "lore.general.agrarian-childhood",
    scope: AGRARIAN,
    topics: [{ aim: "raise-kin" }, { aim: "child-future" }, { occasion: "day.teach-child" }],
    evidence: "documented",
    title: "Childhood as apprenticeship: work, fostering and schooling",
    text: "Children began helping at five or six and did real work by ten: herding, weeding, carrying water, spinning, minding babies. Most learned their parents' trade at home. Others were sent away: into apprenticeships, into service in another household, or, among the Irish, Norse and Caucasus peoples, into fosterage with another family to bind the two. Schooling was for few: temple and monastery schools, Chinese village schools preparing boys for examinations, Islamic Qur'an schools. Perhaps a third of children died before age five.",
    wiki: ["History of childhood", "Fosterage", "Apprenticeship"],
  },
  {
    id: "lore.general.agrarian-play",
    scope: AGRARIAN,
    topics: [{ scene: "play" }],
    evidence: "documented",
    title: "Board games and ball games: senet, mancala and patolli",
    text: "People played wherever they rested. Egyptians played senet on a board of thirty squares by 3000 BCE, and later linked it to the soul's journey. Mancala games, sowing seeds or stones around rows of pits, were played across Africa and western Asia, often scratched into the ground. The Aztecs gambled on patolli, a race game played with beans as dice. Children played with dolls, tops, knucklebones and hoops, and ball games ranged from the Mesoamerican rubber-ball game to kicking games in Chinese towns.",
    wiki: ["Senet", "Mancala", "Patolli"],
  },
  {
    id: "lore.general.agrarian-dead",
    scope: AGRARIAN,
    topics: [{ aim: "remember-dead" }, { occasion: "day.death-day" }, { occasion: "day.speak-of-dead" }],
    evidence: "documented",
    title: "Remembering the dead on their day",
    text: "Nearly every agrarian society kept a calendar for its dead. Chinese families set out food before ancestral tablets on death anniversaries and swept graves at Qingming. Hindus offer rice balls to ancestors in the shraddha rites, including each death anniversary. Medieval Catholics paid for masses on the anniversary of a death to shorten the soul's time in purgatory. Romans honoured the family dead each February at the Parentalia. Such rites kept the dead part of the household, and failure to perform them could be blamed for illness or misfortune.",
    wiki: ["Veneration of the dead", "Requiem", "Mourning"],
  },
  {
    id: "lore.general.agrarian-widows",
    scope: AGRARIAN,
    topics: [{ aim: "widowed-household" }],
    evidence: "documented",
    title: "Widowhood: remarriage, levirate and the widow's third",
    text: "A widow's fate depended on law and on her husband's kin. In levirate marriage, found in ancient Israel and many African societies, the dead man's brother married his widow to keep her and her children in the family. English common law gave widows a dower, a third of the husband's land for life. Late imperial China honoured widows who never remarried with memorial arches, and pressed families not to let them. Everywhere, many widows headed households, running farms and shops, and some did well.",
    wiki: ["Levirate marriage", "Dower", "Widow chastity"],
  },
  {
    id: "lore.general.agrarian-worship",
    scope: AGRARIAN,
    topics: [{ goal: "worship" }, { goal: "rites" }, { scene: "offer" }, { occasion: "day.patron-offering" }],
    evidence: "documented",
    title: "Household shrines and temple offerings",
    text: "Most worship happened at home: Romans offered to their Lares at the hearth, Chinese households honoured the Kitchen God, Hindu homes kept a puja shelf, Yoruba households kept shrines to their orisha. Small daily offerings of food, incense, lamps or flowers asked for protection. Temples, churches and mosques set the larger calendar with festivals, pilgrimages and fixed days of rest or prayer. In many states temples were also landlords and granaries, and an offering could be both worship and a kind of tax.",
    wiki: ["Household deity", "Pilgrimage", "Palace economy"],
  },
  {
    id: "lore.general.agrarian-news",
    scope: AGRARIAN,
    topics: [{ goal: "news" }, { goal: "neighbour" }, { scene: "talk" }, { scene: "gathering" }, { occasion: "day.friend" }, { occasion: "day.quarrel" }],
    evidence: "documented",
    title: "News by mouth: criers, gazettes and the village well",
    text: "Most news travelled by word of mouth at the well, market, tavern, church door and barber's shop. Governments published by voice: town criers read proclamations in the square. Rome posted daily acta diurna in the Forum; the Chinese court circulated a gazette, the dibao, to officials from the Tang onward. Merchants and pilgrims carried distant news, often weeks or months old. Villages settled disputes in assemblies of elders or before a headman, and quarrels between neighbours could run for generations.",
    wiki: ["Town crier", "Acta Diurna", "Dibao"],
  },
  {
    id: "lore.general.agrarian-travel",
    scope: AGRARIAN,
    topics: [{ aim: "find-belonging" }, { aim: "new-settlement" }, { scene: "walk" }],
    evidence: "documented",
    title: "Strangers and hospitality: caravanserais and the guest-right",
    text: "Travel was dangerous and strangers needed protection. Many cultures made hospitality a sacred duty: Greek xenia under Zeus, the Bedouin guest-right of three days, the ritual guest-friendship of Germanic and Celtic halls. On trade routes, caravanserais offered walled courtyards for animals and rooms for merchants. Newcomers to a village usually needed a sponsor, often kin or a patron, to get land or work. Colonists founding new settlements, from Greek colonies to Chinese frontier farms, carried their cults and their elders' customs with them.",
    wiki: ["Xenia (Greek)", "Caravanserai", "Hospitality"],
  },
  {
    id: "lore.general.agrarian-service",
    scope: AGRARIAN,
    topics: [{ aim: "make-a-life" }, { goal: "any-work" }],
    evidence: "documented",
    title: "Making a start: service, land and the late marriage",
    text: "A young person's path to independence was to gain land or a trade. In northwestern Europe from the late Middle Ages, many youths spent their teens and twenties as servants living in other households, saving to marry, which historians call the western European marriage pattern. Elsewhere, sons stayed on family land under their father and set up house only when it was divided. For the landless, the choices were wage work, soldiering, migration to towns, or joining a religious order.",
    wiki: ["Western European marriage pattern", "Apprenticeship", "Serfdom"],
  },
  {
    id: "lore.general.agrarian-bathing",
    scope: AGRARIAN,
    topics: [{ occasion: "day.bathe" }],
    evidence: "documented",
    title: "Bathhouses, sweat baths and the river",
    text: "Bathing was often public and social. Roman towns had thermae with hot, warm and cold rooms heated by underfloor hypocausts. Islamic cities built hammams near mosques, and Ottoman towns kept them as places for women's gatherings. Mesoamericans used the temazcal, a steam bath of stone or adobe, for cleansing, healing and after childbirth. Japanese towns had bathhouses, and northern Europeans and Russians sweat-bathed in saunas and banyas. Many people simply washed in rivers, and hauled water made daily washing modest.",
    wiki: ["Public bathing", "Hammam", "Temazcal"],
  },
  {
    id: "lore.general.agrarian-toothache",
    scope: AGRARIAN,
    topics: [{ occasion: "day.toothache" }],
    evidence: "documented",
    title: "Toothache and the tooth worm",
    text: "From Babylon to medieval Europe, China and Mesoamerica, toothache was widely blamed on a worm boring through the tooth. Remedies included herbal pastes, henbane smoke, charms and prayers to saints such as Apollonia. Sugar was scarce, so decay was less common than today, but coarse bread ground with grit wore teeth down. When a tooth had to go, it was pulled by a barber, smith or travelling tooth-drawer at a fair, without anaesthetic. Etruscans and Phoenicians made gold wire bridges for the wealthy.",
    wiki: ["Tooth worm", "History of dental treatments"],
  },

  // The industrial and colonial world, 1800-1914.
  {
    id: "lore.general.industrial-cash-crops",
    scope: INDUSTRIAL,
    topics: [{ workplace: "field" }, { goal: "sow" }, { goal: "weed" }, { goal: "harvest" }, { goal: "winter-field" }, { scene: "tend" }],
    evidence: "documented",
    title: "Cash crops, guano and indentured labour",
    text: "The 19th century tied farmers everywhere to world markets. Cotton from the American South, Egypt and India fed Lancashire mills; coffee, sugar, tea, rubber and cocoa spread through colonies; peasants were pushed to grow crops for sale to pay taxes in cash. After slavery was abolished in the British Empire in 1834, some 1.3 million Indian indentured labourers were shipped to plantations in the Caribbean, Fiji, Mauritius and Natal. Peruvian guano and later chemical fertilisers raised yields in Europe, and machines like the reaper spread on the grain frontiers.",
    wiki: ["Cash crop", "Indian indenture system", "History of Peru (1845–1866)"],
  },
  {
    id: "lore.general.industrial-ranching",
    scope: INDUSTRIAL,
    topics: [{ workplace: "pasture" }, { goal: "fodder" }, { goal: "wool" }, { scene: "herd" }],
    evidence: "documented",
    title: "Ranches, cattle drives and herders' lost pastures",
    text: "Settler states turned grasslands into ranches. Texas cowboys drove longhorns north to railheads in the 1860s–80s; Argentina and Uruguay became cattle countries, and Australia and New Zealand sheep countries, and refrigerated ships carried their frozen meat to Britain from 1882. Pastoral peoples lost land to these ranches and to colonial reserves: the Maasai were moved off their best grazing in Kenya by treaties of 1904 and 1911. Rinderpest, brought to Africa in the 1880s, killed most of the continent's cattle and brought famine to herding peoples.",
    wiki: ["Cattle drives in the United States", "Pastoralism", "Transhumance"],
  },
  {
    id: "lore.general.industrial-frontier",
    scope: INDUSTRIAL,
    topics: [{ workplace: "wild" }, { goal: "forage" }, { goal: "hunt" }, { goal: "wood" }, { goal: "hides" }, { scene: "gather" }],
    evidence: "documented",
    title: "Frontier extraction: rubber, fur, timber and hides",
    text: "Industry drew raw materials from the world's forests and plains. Wild rubber for bicycle and car tyres was tapped in the Amazon, where tappers were trapped in debt to traders, and in King Leopold's Congo, where quotas were enforced by mutilation and killing. Commercial hunters killed tens of millions of North American bison in the 1870s–80s for hides to make factory belts. Timber and fur frontiers moved across Siberia and Canada. Gathering from the wild became, for many, wage or debt labour for a distant market.",
    wiki: ["Amazon rubber cycle", "Landolphia owariensis", "Fur trade"],
  },
  {
    id: "lore.general.industrial-whaling-canning",
    scope: INDUSTRIAL,
    topics: [{ workplace: "water" }, { goal: "fish" }, { goal: "reeds" }, { scene: "hang" }],
    evidence: "documented",
    title: "Whalers, canneries and steam fishing",
    text: "Whale oil lit the streets and oiled the machines of the early industrial world. American whaling ships from New Bedford and Nantucket sailed voyages of three or four years, their crews including Pacific islanders, Cape Verdeans and Native Americans. Canning, invented in France around 1810, turned fish into a world commodity: sardines from Brittany, salmon from the Columbia River. Steam trawlers from the 1880s emptied North Sea grounds, while most coastal fishers everywhere still worked from small boats and split, salted and dried their catch by hand.",
    wiki: ["History of whaling", "Canning", "Fishing"],
  },
  {
    id: "lore.general.industrial-mining",
    scope: INDUSTRIAL,
    topics: [{ workplace: "extraction" }, { goal: "quarry" }],
    evidence: "documented",
    title: "Coal pits and gold rushes",
    text: "Coal powered the century. In British, Belgian and German pits, men hewed coal by hand while women and children hauled it until laws of the 1840s barred them from underground work. Explosions of firedamp killed hundreds at a time. Gold rushes in California (1848), Australia (1851) and the Witwatersrand (1886) drew migrants from across the world; on the Rand, African miners were housed in closed compounds on short contracts. Mining towns grew overnight, with saloons, boarding houses and company stores.",
    wiki: ["History of coal mining", "Witwatersrand Gold Rush", "Child labour"],
  },
  {
    id: "lore.general.industrial-factory",
    scope: INDUSTRIAL,
    topics: [{ workplace: "workshop" }, { goal: "materials" }, { goal: "day-of-work" }, { aim: "mastery" }, { scene: "craft" }, { occasion: "day.craft-power" }],
    evidence: "documented",
    title: "Factories, outwork and the handloom weaver's fall",
    text: "Machines broke the old workshop world. Factory owners gathered workers under one roof and one clock, often for twelve or more hours a day. Before and alongside factories, merchants 'put out' spinning and weaving to families in their cottages. Skilled handloom weavers in England saw their wages collapse, and Luddites smashed machines in 1811–16. Indian weavers suffered as cheap Lancashire cloth flooded their markets. Guilds lost their legal powers across Europe and Japan; trade unions slowly took their place, and apprenticeships shortened.",
    wiki: ["Factory system", "Putting-out system", "Luddites"],
  },
  {
    id: "lore.general.industrial-markets",
    scope: INDUSTRIAL,
    topics: [{ workplace: "market" }, { goal: "sell-goods" }, { goal: "stock" }, { goal: "barter" }, { scene: "market" }],
    evidence: "documented",
    title: "World prices, department stores and the village market",
    text: "Railways, steamships and the telegraph made prices worldwide: wheat in Chicago, cotton in Liverpool, rice in Rangoon moved together. Commodity exchanges such as the Chicago Board of Trade, founded in 1848, traded crops not yet grown. In cities, department stores like Paris's Bon Marché sold fixed-price goods to a new middle class. Most people still shopped at weekly markets and small shops, often on credit, and barter persisted in villages. Colonial rule spread coins and banknotes where cowries or cloth had served.",
    wiki: ["Commodity market", "Department store", "Market town"],
  },
  {
    id: "lore.general.industrial-transport",
    scope: INDUSTRIAL,
    topics: [{ workplace: "carrying" }, { goal: "carry" }, { scene: "haul" }],
    evidence: "documented",
    title: "Railways, rickshaws and the last porters",
    text: "Railways cut the cost of moving goods overland by as much as nine-tenths and the time by more. Yet muscle still carried the last mile. The rickshaw, introduced in Japan around 1869, spread across Asian cities and was pulled by rural migrants. Porters, often called 'coolies' by Europeans, loaded ships and carried goods in Asian and African ports and on colonial expeditions, where caravans of hundreds of men carried everything on their heads. Carters and draymen with horses were among the largest occupations in European cities.",
    wiki: ["Pulled rickshaw", "Coolie", "Steamship"],
  },
  {
    id: "lore.general.industrial-state",
    scope: INDUSTRIAL,
    topics: [{ workplace: "civic" }, { goal: "civic-rounds" }],
    evidence: "documented",
    title: "Census, police and conscription: the modern state arrives",
    text: "Governments came to know their people individually. Regular national censuses spread from the early 1800s; British India's first all-India census began in 1871 and fixed caste categories in print. Uniformed police forces, following London's Metropolitan Police of 1829, replaced watchmen. Mass conscription, from Napoleonic France to Meiji Japan in 1873, took young men for years of service. Colonial states registered land, taxed households in cash and recruited chiefs and headmen as their agents.",
    wiki: ["Census", "Conscription"],
  },
  {
    id: "lore.general.industrial-water",
    scope: INDUSTRIAL,
    topics: [{ goal: "water" }, { scene: "water" }],
    evidence: "documented",
    title: "From the pump to the pipe: cholera and clean water",
    text: "Crowded industrial cities drew water from polluted rivers and shared pumps, and cholera swept the world in repeated pandemics. In 1854 John Snow traced a London outbreak to a single water pump on Broad Street. Great sewer systems followed, built in London by Bazalgette from 1859, and filtered piped water reached many European and American homes by 1900. Poorer districts, and most of the world's towns and villages, still depended on standpipes, wells and water sellers carrying skins or cans.",
    wiki: ["1854 Broad Street cholera outbreak", "London sewer system", "Water supply"],
  },
  {
    id: "lore.general.industrial-food",
    scope: INDUSTRIAL,
    topics: [{ workplace: "household" }, { goal: "household" }, { goal: "eat" }, { goal: "food-store" }, { scene: "cook" }, { occasion: "day.check-store" }],
    evidence: "documented",
    title: "Tinned food, white bread and colonial famine",
    text: "Industrial food arrived: canned meat and milk, cheap sugar and tea, and white flour from steel roller mills. Urban workers ate bread, potatoes and sweet tea, and meat when they could afford it. Yet famine did not end; it was reshaped by markets and empire. Ireland lost a million people to hunger in 1845–52 while food was exported; drought and grain exports killed perhaps 6–10 million in India in 1876–78. Households still stored food in cellars, crocks and bins, and cooking moved from open hearths to cast-iron ranges.",
    wiki: ["Canning", "Great Famine (Ireland)", "Great Famine of 1876–1878"],
  },
  {
    id: "lore.general.industrial-hard-times",
    scope: INDUSTRIAL,
    topics: [{ aim: "restore-household" }, { occasion: "day.borrow" }, { occasion: "day.debt" }],
    evidence: "documented",
    title: "Pawnshops and friendly societies",
    text: "Working families lived week to week, and illness, injury or layoff could ruin them. The pawnshop was the working-class bank: Sunday clothes pledged on Monday and redeemed on Saturday. Workers clubbed together in friendly societies and burial clubs, paying pennies weekly for sick pay and a decent funeral; in Asia and Africa, rotating savings clubs did similar work. Moneylenders thrived in colonial villages where taxes had to be paid in cash. The poor law workhouse, deliberately harsh, was the last resort in Britain.",
    wiki: ["Pawnbroker", "Friendly society"],
  },
  {
    id: "lore.general.industrial-fuel-light",
    scope: INDUSTRIAL,
    topics: [{ goal: "firewood" }, { scene: "warm" }, { goal: "sleep" }, { scene: "rest" }],
    evidence: "documented",
    title: "Coal fires, kerosene lamps and longer evenings",
    text: "In industrial cities, coal replaced wood in the kitchen and the grate, and smoke blackened everything. From the 1860s, kerosene from Pennsylvania and later Baku was shipped around the world, and cheap kerosene lamps lengthened evenings in villages from China to Africa. Gas lighting spread through city streets and wealthier homes. Most rural people still gathered firewood or dung, and forests near growing towns vanished. Artificial light shifted sleep later and into one block, ending the old habit of waking in the night.",
    wiki: ["Kerosene lamp", "Gas lighting", "Polyphasic sleep"],
  },
  {
    id: "lore.general.industrial-religion",
    scope: INDUSTRIAL,
    topics: [{ goal: "worship" }, { goal: "rites" }, { scene: "offer" }, { occasion: "day.patron-offering" }],
    evidence: "documented",
    title: "Missions, revivals and reformed religions",
    text: "The 19th century was religiously restless. Protestant and Catholic missions spread across Africa, Asia and the Pacific with schools and clinics. Reform movements answered them: the Brahmo Samaj and Arya Samaj in India, Islamic reformers in Egypt, and Meiji Japan's State Shinto, which separated shrines from Buddhism and made the emperor's worship national. In industrial towns, revivals and new churches competed for workers, while many still kept household saints, shrines and offerings much as their grandparents had.",
    wiki: ["Christian mission", "State Shinto"],
  },
  {
    id: "lore.general.industrial-news",
    scope: INDUSTRIAL,
    topics: [{ goal: "news" }, { goal: "neighbour" }, { scene: "talk" }, { scene: "gathering" }, { occasion: "day.friend" }],
    evidence: "documented",
    title: "Penny papers, the telegraph and the post",
    text: "News accelerated. The electric telegraph from the 1840s, and undersea cables from 1866, carried reports between continents in hours. Cheap 'penny press' newspapers were read aloud in taverns, coffee houses and workshops to those who could not read. Britain's uniform penny post of 1840 let ordinary people send letters for a flat rate, and migrants' letters home became a flood. Neighbours still met at the pump, the chapel and the pub, and working men formed clubs, unions and reading rooms.",
    wiki: ["Penny press", "Electrical telegraph", "Uniform Penny Post"],
  },
  {
    id: "lore.general.industrial-childhood",
    scope: INDUSTRIAL,
    topics: [{ aim: "raise-kin" }, { aim: "child-future" }, { occasion: "day.teach-child" }, { scene: "play" }],
    evidence: "documented",
    title: "Factory children and the coming of school",
    text: "Early factories relied on children: in 1830s Britain, children as young as six worked mill shifts of twelve hours. Factory Acts from 1833 slowly limited their hours. Compulsory elementary schooling spread from Prussia to Britain (1870–80), Japan (1872) and most of Europe and the Americas by 1900, and literacy rose sharply. In colonies, mission schools taught a small minority. Children's play moved into streets and yards, with marbles, hoops, skipping and cheap manufactured toys.",
    wiki: ["Child labour", "Compulsory education", "History of childhood"],
  },
  {
    id: "lore.general.industrial-marriage",
    scope: INDUSTRIAL,
    topics: [{ aim: "marriage-hope" }, { aim: "shared-future" }, { occasion: "day.match" }],
    evidence: "documented",
    title: "Wages, civil marriage and love matches",
    text: "Wage work loosened parents' grip on marriage: a young factory worker did not need to wait for land. Civil marriage registered by the state spread from Napoleonic France. Ideals of the love match grew in Europe and America, though families still weighed prospects closely. Elsewhere, dowries grew in some places as cash entered the countryside, and migration separated couples for years: Chinese and Indian migrant men sent money home to wives they rarely saw, and 'picture brides' crossed the Pacific to marry men known only from photographs.",
    wiki: ["Dowry", "Bride price", "Arranged marriage"],
  },
  {
    id: "lore.general.industrial-old-age",
    scope: INDUSTRIAL,
    topics: [{ aim: "elder-kin" }, { occasion: "day.elder-kin" }],
    evidence: "documented",
    title: "The first old-age pensions",
    text: "As children left for cities and colonies, the old were more often left behind. Germany under Bismarck introduced the first national old-age insurance in 1889, paying from age 70; Denmark, New Zealand and Britain (1908) followed with pensions for the aged poor. Most old people in the world still lived with and worked for their children, and in industrial towns grandmothers minded children while mothers worked. The dread of ending in the workhouse or poorhouse shaped working-class thrift.",
    wiki: ["Pension", "Old age", "Filial piety"],
  },
  {
    id: "lore.general.industrial-mourning",
    scope: INDUSTRIAL,
    topics: [{ aim: "remember-dead" }, { occasion: "day.death-day" }, { occasion: "day.speak-of-dead" }],
    evidence: "documented",
    title: "Mourning dress, garden cemeteries and death photographs",
    text: "The 19th-century middle class made mourning elaborate. Widows in Britain and America wore black crape for a year or more, then grey and mauve; hair from the dead was worked into brooches. Garden cemeteries such as Père Lachaise (1804) replaced crowded churchyards, and families visited graves on anniversaries. Photographers made post-mortem portraits, often the only picture of a dead child. Burial clubs let the poor avoid the shame of a pauper's grave. Elsewhere, ancestral rites continued and adapted to migration.",
    wiki: ["Post-mortem photography", "Mourning", "Friendly society"],
  },
  {
    id: "lore.general.industrial-widows",
    scope: INDUSTRIAL,
    topics: [{ aim: "widowed-household" }],
    evidence: "documented",
    title: "Widows in the industrial century",
    text: "Industrial accidents and mining disasters made widows by the hundred in a single day, and most received nothing but what neighbours collected. Widows took in washing, lodgers and sewing, or ran small shops. In India, reformers campaigned against the ban on high-caste widows remarrying; the Hindu Widows' Remarriage Act of 1856 made such marriages legal, though few took place at first, and sati had been banned in 1829. Widows' pensions for mothers began in some American states from 1911.",
    wiki: ["Hindu Widows' Remarriage Act, 1856", "Widow", "Friendly society"],
  },
  {
    id: "lore.general.industrial-migration",
    scope: INDUSTRIAL,
    topics: [{ aim: "new-settlement" }, { aim: "find-belonging" }, { aim: "make-a-life" }, { scene: "walk" }],
    evidence: "documented",
    title: "The age of mass migration",
    text: "Between 1815 and 1914 some 50 million Europeans emigrated, mostly to the Americas and Australia, and millions of Chinese and Indians moved to Southeast Asia, the Caribbean, Africa and the Pacific. Steamships made the crossing a matter of weeks. Migrants followed kin and neighbours through chain migration, so whole villages reassembled in new cities, with mutual aid societies, clan associations and churches. Many went intending to return, and a large share did. Their remittances rebuilt houses and bought land back home.",
    wiki: ["European emigration", "Overseas Chinese", "Indian indenture system"],
  },
  {
    id: "lore.general.industrial-housing",
    scope: INDUSTRIAL,
    topics: [{ aim: "household-home" }, { occasion: "day.mend-home" }],
    evidence: "documented",
    title: "Tenements, back-to-backs and company towns",
    text: "Cities grew faster than housing. Workers crowded into tenements in New York, back-to-back rows in Manchester, and chawls in Bombay, with whole families in one room and shared privies. Some employers built company towns where the firm owned the houses, the store and the church. Few working people owned their home; rent day was the week's dread. In the countryside, most families still built and repaired their own houses, and land rather than house remained the main inheritance.",
    wiki: ["Tenement", "Company town"],
  },

  // 1914-1950.
  {
    id: "lore.general.wars-farming",
    scope: WARS,
    topics: [{ workplace: "field" }, { goal: "sow" }, { goal: "weed" }, { goal: "harvest" }, { goal: "winter-field" }, { scene: "tend" }],
    evidence: "documented",
    title: "Tractors, collective farms and the Dust Bowl",
    text: "Machines and states reshaped farming. Ford's cheap Fordson tractor, from 1917, began replacing horses in North America, and ploughing up the dry southern plains helped cause the Dust Bowl of the 1930s. In the Soviet Union, peasants were forced into collective farms from 1929, and millions died in the famines that followed. Colonial governments pushed compulsory cash crops, such as cotton in Mozambique. Yet most of the world's farmers, in China, India and Africa, still worked with hoes, oxen and hand sickles.",
    wiki: ["Collectivization in the Soviet Union", "Dust Bowl", "Fordson"],
  },
  {
    id: "lore.general.wars-herders",
    scope: WARS,
    topics: [{ workplace: "pasture" }, { goal: "fodder" }, { goal: "wool" }, { scene: "herd" }],
    evidence: "documented",
    title: "Herders forced to settle",
    text: "Modern states distrusted people who moved. Soviet collectivisation forced Kazakh nomads to settle and seized their animals; in the famine of 1930–33 about 1.5 million people died and herds fell by nine-tenths. Reza Shah's Iran forcibly settled tribes such as the Qashqai in the 1930s. Colonial borders cut across old migration routes in Africa and the Middle East. Where herders kept moving, trucks and veterinary campaigns began to change their work, and wool and meat went to distant markets.",
    wiki: ["Kazakh famine of 1930–1933", "Pastoralism", "Collectivization in the Soviet Union"],
  },
  {
    id: "lore.general.wars-factory",
    scope: WARS,
    topics: [{ workplace: "workshop" }, { goal: "materials" }, { goal: "day-of-work" }, { aim: "mastery" }, { scene: "craft" }, { occasion: "day.craft-power" }],
    evidence: "documented",
    title: "The assembly line and the wartime factory",
    text: "Ford's moving assembly line of 1913 cut the time to build a car from about twelve hours to ninety minutes, and its methods spread to every industry. Two world wars turned factories to munitions and drew millions of women into jobs once closed to them, from British shell factories to American aircraft plants, whose worker became 'Rosie the Riveter'. Skilled craftwork survived in repair shops and small workshops worldwide, and village artisans still made most things for rural people.",
    wiki: ["Assembly line", "Rosie the Riveter"],
  },
  {
    id: "lore.general.wars-mining",
    scope: WARS,
    topics: [{ workplace: "extraction" }, { goal: "quarry" }, { workplace: "wild" }, { goal: "forage" }, { goal: "hunt" }, { goal: "wood" }, { scene: "gather" }],
    evidence: "documented",
    title: "Miners, strikes and forced labour",
    text: "Coal and oil were strategic in two world wars. Miners were among the best-organised workers: the British miners' lockout triggered the 1926 general strike. Under Nazi Germany, millions of forced labourers from occupied Europe worked in mines and factories, as did prisoners in the Soviet Gulag's mining camps. In the countryside, people still gathered from the wild, and wartime shortages sent them back to foraging nuts, mushrooms and wild greens and cutting their own fuel.",
    wiki: ["1926 United Kingdom general strike", "Forced labour under German rule during World War II"],
  },
  {
    id: "lore.general.wars-rationing",
    scope: WARS,
    topics: [{ workplace: "market" }, { goal: "sell-goods" }, { goal: "stock" }, { goal: "barter" }, { goal: "eat" }, { goal: "food-store" }, { scene: "market" }, { scene: "cook" }, { occasion: "day.check-store" }],
    evidence: "documented",
    title: "Ration books, queues and the black market",
    text: "Both world wars brought rationing: in Britain from 1940, each person had coupons for set amounts of bacon, butter, sugar, meat and tea, and rationing lasted until 1954. Queues, allotments and home preserving became part of life. Where rationing met shortage, black markets flourished, and barter returned; in postwar Germany cigarettes served as currency. In occupied and besieged places hunger was extreme, as in Leningrad and the Bengal famine of 1943, when three million died.",
    wiki: ["Rationing in the United Kingdom", "Black market"],
  },
  {
    id: "lore.general.wars-depression",
    scope: WARS,
    topics: [{ aim: "restore-household" }, { occasion: "day.borrow" }, { occasion: "day.debt" }],
    evidence: "documented",
    title: "The Great Depression and public relief",
    text: "From 1929 the Great Depression threw a quarter of American workers out of work, and collapsing crop prices ruined farmers from Brazil's coffee growers to Malaya's rubber smallholders. Families pawned belongings, took in lodgers, moved in with relatives and went on the road. Governments experimented with public relief: the American New Deal's Works Progress Administration employed millions from 1935. Debt drove many farmers off their land, and it was the decade when many learned to 'make do and mend'.",
    wiki: ["Great Depression", "Works Progress Administration", "Pawnbroker"],
  },
  {
    id: "lore.general.wars-state",
    scope: WARS,
    topics: [{ workplace: "civic" }, { goal: "civic-rounds" }],
    evidence: "documented",
    title: "Papers, please: conscription and the total-war state",
    text: "Two world wars made governments reach into every home. Most combatant states conscripted young men, and some women; identity cards, introduced widely in wartime, had to be carried and shown. Police and officials enforced blackouts, rationing and labour direction. New states and revolutions, from the Soviet Union to Turkey and later India and Pakistan, used census, school and registry to remake their populations, and colonial governments recruited millions of soldiers and porters from Africa and Asia.",
    wiki: ["Conscription", "Identity document", "Census"],
  },
  {
    id: "lore.general.wars-carrying",
    scope: WARS,
    topics: [{ workplace: "carrying" }, { goal: "carry" }, { scene: "haul" }],
    evidence: "documented",
    title: "Lorries, bicycles and porters at war",
    text: "Motor lorries took over road haulage between the wars, and buses reached villages that had never seen a car. The bicycle became the working vehicle of millions in China, India, Southeast Asia and Europe, carrying goods as well as riders. Muscle still mattered: in the East African campaign of the First World War, the British and Germans used over a million African porters, and tens of thousands died. Rickshaw pullers remained a large workforce in Asian cities.",
    wiki: ["Pulled rickshaw", "Conscription"],
  },
  {
    id: "lore.general.wars-displaced",
    scope: WARS,
    topics: [{ aim: "new-settlement" }, { aim: "find-belonging" }, { aim: "make-a-life" }, { scene: "walk" }],
    evidence: "documented",
    title: "Refugees and the displaced",
    text: "The years 1914–1950 uprooted more people than any before. The Greek–Turkish population exchange of 1923 moved about 1.6 million. After the Second World War, Europe held millions of 'displaced persons' in camps, and 12 million or more Germans were expelled from eastern Europe. The partition of India in 1947 moved some 15 million people and killed perhaps a million. Refugees rebuilt lives through kin networks, relief agencies and new states, often in camps that became permanent towns.",
    wiki: ["Partition of India", "Displaced persons camps in post–World War II Europe"],
  },
  {
    id: "lore.general.wars-radio",
    scope: WARS,
    topics: [{ goal: "news" }, { goal: "neighbour" }, { scene: "talk" }, { scene: "gathering" }, { occasion: "day.friend" }],
    evidence: "documented",
    title: "Radio in the living room and the village square",
    text: "Broadcast radio arrived in the 1920s and within twenty years was the world's fastest news. Families gathered around the set for news, music and serials; villages without electricity listened to a single set in the square or café. Governments quickly used it: Roosevelt's fireside chats, Nazi Germany's cheap 'people's receiver' built for propaganda, and wartime broadcasts to occupied countries. Newspapers, newsreels at the cinema and the gossip of neighbours still carried much of what people knew.",
    wiki: ["Golden Age of Radio", "Propaganda"],
  },
  {
    id: "lore.general.wars-utilities",
    scope: WARS,
    topics: [{ goal: "water" }, { scene: "water" }, { goal: "firewood" }, { scene: "warm" }, { workplace: "household" }, { goal: "household" }],
    evidence: "documented",
    title: "Electric light, the primus stove and the standpipe",
    text: "Electricity reached most city homes in industrial countries by the 1930s but few farms; in 1930 only about one American farm in ten had it, and rural electrification programmes began in 1935. The paraffin-burning Primus stove, a Swedish design, cooked meals from Arctic expeditions to Asian kitchens. Most of the world still fetched water from wells, rivers and shared standpipes, and burned wood, charcoal or dung. Housework remained long, though washing machines and vacuum cleaners appeared in wealthier homes.",
    wiki: ["Rural electrification", "Primus stove", "Water supply"],
  },
  {
    id: "lore.general.wars-mourning",
    scope: WARS,
    topics: [{ aim: "remember-dead" }, { aim: "widowed-household" }, { occasion: "day.death-day" }, { occasion: "day.speak-of-dead" }],
    evidence: "documented",
    title: "Mass death, war memorials and war widows",
    text: "The First World War killed about 10 million soldiers, and the influenza pandemic of 1918–20 killed perhaps 50 million people worldwide. Because most soldiers' bodies were never brought home, communities built war memorials listing names, and nations buried an unknown soldier in their capitals to stand for all. Millions of war widows raised children on small pensions, often never remarrying because a generation of men was gone. The Second World War multiplied the dead again, and private anniversaries were kept alongside national days of remembrance.",
    wiki: ["War memorial", "Tomb of the Unknown Soldier", "Spanish flu"],
  },
  {
    id: "lore.general.wars-childhood",
    scope: WARS,
    topics: [{ aim: "raise-kin" }, { aim: "child-future" }, { occasion: "day.teach-child" }, { scene: "play" }],
    evidence: "documented",
    title: "Evacuees, schools and children in wartime",
    text: "Schooling spread fast in this period, and new states used it to make citizens. War tore childhood apart too. In September 1939 Britain evacuated about 1.5 million people, mostly children, from cities to the countryside. The Kindertransport carried some 10,000 Jewish children from Nazi-ruled lands to Britain. Children in occupied and bombed cities queued for food, scavenged, and played in ruins. In much of the world, children still worked on farms and in family trades, their schooling fitted around the harvest.",
    wiki: ["Evacuations of civilians in the United Kingdom during the Second World War", "Kindertransport", "Compulsory education"],
  },
  {
    id: "lore.general.wars-marriage",
    scope: WARS,
    topics: [{ aim: "marriage-hope" }, { aim: "shared-future" }, { occasion: "day.match" }],
    evidence: "documented",
    title: "Wartime weddings and changing marriage laws",
    text: "Wars hurried marriages along, and tens of thousands of soldiers married abroad; American 'war brides' from Britain, Australia and Japan crossed the oceans after 1945. Revolutions rewrote family law: Soviet Russia allowed divorce on request in 1918, Turkey's 1926 civil code banned polygamy, and China's 1950 Marriage Law abolished arranged marriage and concubinage. Yet in most villages families still arranged matches, with dowry or bridewealth, and the couple might meet only at the wedding.",
    wiki: ["War bride", "Kemalism", "Arranged marriage"],
  },
  {
    id: "lore.general.wars-old-age",
    scope: WARS,
    topics: [{ aim: "elder-kin" }, { occasion: "day.elder-kin" }],
    evidence: "documented",
    title: "Social security and old age between the wars",
    text: "Pensions spread among industrial nations: the United States passed its Social Security Act in 1935 after the Depression wiped out many elders' savings, and Britain's postwar welfare state followed in 1946–48. Life expectancy rose as infections were controlled, so more people lived to be old. Across most of the world, however, the old still depended on sons, daughters and daughters-in-law, and war and migration often took those very children away.",
    wiki: ["Social Security Act", "Pension", "Old age"],
  },
  {
    id: "lore.general.wars-religion",
    scope: WARS,
    topics: [{ goal: "worship" }, { goal: "rites" }, { scene: "offer" }, { occasion: "day.patron-offering" }],
    evidence: "documented",
    title: "Faith under revolution and war",
    text: "Revolutionary states attacked religion. The Soviet Union closed most churches, mosques and synagogues in its campaign of 1928–41, and priests were shot or sent to camps. Kemalist Turkey abolished the caliphate in 1924, closed Sufi lodges and moved the call to prayer into Turkish. Mexico's government fought Catholic rebels in the Cristero War. Yet war also filled churches and shrines, and household prayer, pilgrimage and offerings to local saints and spirits carried on quietly through all of it.",
    wiki: ["USSR anti-religious campaign (1928–1941)", "Kemalism"],
  },
  {
    id: "lore.general.wars-housing",
    scope: WARS,
    topics: [{ aim: "household-home" }, { occasion: "day.mend-home" }, { goal: "sleep" }, { scene: "rest" }],
    evidence: "documented",
    title: "Council houses, shanty towns and the bombed-out home",
    text: "Governments began building homes for workers: Vienna's municipal housing of the 1920s, British council estates, and Soviet communal flats where families shared kitchens. Bombing in the Second World War destroyed millions of homes, from London in the Blitz to Tokyo and German cities, and families slept in shelters and cellars. In fast-growing colonial and Latin American cities, migrants built their own shanty towns. In the countryside, people still built and mended their houses with neighbours' help.",
    wiki: ["Public housing", "The Blitz"],
  },
  {
    id: "lore.general.wars-fishing",
    scope: WARS,
    topics: [{ workplace: "water" }, { goal: "fish" }, { goal: "reeds" }, { scene: "hang" }],
    evidence: "documented",
    title: "Motor boats, freezers and fishing in wartime",
    text: "Diesel and petrol engines spread to fishing boats between the wars, letting small crews go further, and quick-freezing, developed by Clarence Birdseye in the 1920s, began to replace salting. Fishing fleets were requisitioned in both wars to sweep mines, and fishing grounds closed by war recovered their stocks. Most of the world's fishers still worked from sail or paddle boats with nets and lines and dried or smoked their catch on shore.",
    wiki: ["Fishing", "Canning"],
  },
];
