
import React, { useState, useEffect, useRef } from 'react';
import { GameDate } from '../types';
import { generateHistoricalSummary } from '../services/llmService';

interface WikipediaArticleProps {
    gameDate: GameDate;
    currentRegion: string;
    localArea: string;
    useLlm: boolean;
    overrideSearchTerm?: string | null;
    onTermUsed?: () => void;
}

const WikipediaArticle: React.FC<WikipediaArticleProps> = ({
    gameDate,
    currentRegion,
    localArea,
    useLlm,
    overrideSearchTerm,
    onTermUsed
}) => {
    const [articleText, setArticleText] = useState<string>('');
    const [isLoading, setIsLoading] = useState<boolean>(true);
    const [error, setError] = useState<string | null>(null);
    const cache = useRef<Map<string, string>>(new Map());
    const processedOverride = useRef<string | null>(null);

    useEffect(() => {
        const fetchArticle = async () => {
            // If override is null now, but we just processed one, don't refetch
            if (!overrideSearchTerm && processedOverride.current) {
                processedOverride.current = null; // Reset for next time
                return;
            }

            setIsLoading(true);
            setError(null);
            setArticleText('');

            // Use override term if provided, otherwise use localArea/currentRegion
            const searchTitle = overrideSearchTerm || localArea || currentRegion;

            // Don't include year in cache key - we want fresh Wikipedia for each term
            const cacheKey = `${searchTitle}-${useLlm}`;

            // Only use cache if we have an exact match AND it's not an override term
            // (override terms should always fetch fresh)
            if (!overrideSearchTerm && cache.current.has(cacheKey)) {
                setArticleText(cache.current.get(cacheKey)!);
                setIsLoading(false);
                return;
            }

            try {
                let summaryText = '';

                // Try Wikipedia first
                try {
                    const wikipediaUrl = `https://en.wikipedia.org/api/rest_v1/page/summary/${encodeURIComponent(searchTitle)}`;
                    const response = await fetch(wikipediaUrl);
                    if (!response.ok) {
                        if (response.status === 404) throw new Error('Not Found');
                        throw new Error(`Wikipedia API error: ${response.statusText}`);
                    }
                    const data = await response.json();
                    const summary = data.extract || `No summary available for ${searchTitle}.`;
                    const wikiUrl = data.content_urls?.desktop?.page;

                    // Check if Wikipedia result is too short (less than ~150 chars = roughly 1 paragraph)
                    if (summary.length < 150 && overrideSearchTerm) {
                        throw new Error('Wikipedia result too short');
                    }

                    summaryText = summary;
                    if (wikiUrl) {
                        summaryText += `\n\n[Source: Wikipedia](${wikiUrl})`;
                    }
                } catch (wikiError) {
                    // If we have an override term (clicked word), explain that term specifically
                    if (overrideSearchTerm) {
                        summaryText = await generateHistoricalSummary(gameDate.year, currentRegion, `${overrideSearchTerm} in ${localArea}`);
                        summaryText += "\n\n(Generated by AI - Wikipedia article not found)";
                    } else if (useLlm) {
                        // Otherwise use the standard regional summary
                        summaryText = await generateHistoricalSummary(gameDate.year, currentRegion, localArea);
                        summaryText += "\n\n(Generated by AI as a fallback)";
                    } else {
                        // No LLM, just show error
                        summaryText = `Could not find information about "${searchTitle}". Try a different search term.`;
                    }
                }

                setArticleText(summaryText);
                cache.current.set(cacheKey, summaryText);

                // Mark this override as processed
                if (overrideSearchTerm) {
                    processedOverride.current = overrideSearchTerm;
                }
            } catch (llmError) {
                console.error("LLM fetch failed:", llmError);
                setError("Could not retrieve historical information at this time.");
            } finally {
                setIsLoading(false);

                // Clear override AFTER everything is done
                if (overrideSearchTerm && onTermUsed) {
                    onTermUsed();
                }
            }
        };

        if (currentRegion && localArea) {
            fetchArticle();
        }

    }, [gameDate, currentRegion, localArea, useLlm, overrideSearchTerm]);

    // Parse and render article with working links
    const renderArticle = (text: string) => {
        const paragraphs = text.split('\n\n').slice(0, 3); // Only show first 3 paragraphs

        return paragraphs.map((paragraph, pIndex) => {
            // Check if this is a Wikipedia link paragraph
            const linkMatch = paragraph.match(/\[Source: Wikipedia\]\((https?:\/\/[^)]+)\)/);

            if (linkMatch) {
                return (
                    <p key={pIndex} className="text-xs text-slate-500 mt-4 pt-3 border-t border-slate-700/50">
                        <a
                            href={linkMatch[1]}
                            target="_blank"
                            rel="noopener noreferrer"
                            className="text-amber-400 hover:text-amber-300 underline transition-colors"
                        >
                            Source: Wikipedia →
                        </a>
                    </p>
                );
            }

            return (
                <p key={pIndex} className="mb-4 leading-relaxed text-slate-300">
                    {paragraph}
                </p>
            );
        });
    };

    return (
        <div className="p-4">
            {isLoading && (
                <div className="flex items-center justify-center h-48">
                    <div className="animate-spin rounded-full h-8 w-8 border-b-2 border-amber-400"></div>
                </div>
            )}
            {error && <p className="text-red-400 italic text-sm">{error}</p>}
            {!isLoading && !error && (
                <div className="space-y-3 text-sm">
                    {renderArticle(articleText)}
                </div>
            )}
        </div>
    );
};

export default WikipediaArticle;
