
import React, { useState, useEffect, useRef } from 'react';
import { GameDate } from '../types';
import { generateHistoricalSummary } from '../services/llmService';

interface WikipediaArticleProps {
    gameDate: GameDate;
    currentRegion: string;
    localArea: string;
    useLlm: boolean;
}

const WikipediaArticle: React.FC<WikipediaArticleProps> = ({ gameDate, currentRegion, localArea, useLlm }) => {
    const [articleText, setArticleText] = useState<string>('');
    const [isLoading, setIsLoading] = useState<boolean>(true);
    const [error, setError] = useState<string | null>(null);
    const cache = useRef<Map<string, string>>(new Map());

    useEffect(() => {
        const fetchArticle = async () => {
            setIsLoading(true);
            setError(null);
            setArticleText('');

            const cacheKey = `${localArea}-${currentRegion}-${gameDate.year}-${useLlm}`;
            if (cache.current.has(cacheKey)) {
                setArticleText(cache.current.get(cacheKey)!);
                setIsLoading(false);
                return;
            }

            const searchTitle = localArea || currentRegion;

            try {
                let summaryText = '';
                if (useLlm) {
                    summaryText = await generateHistoricalSummary(gameDate.year, currentRegion, localArea);
                } else {
                    try {
                        const response = await fetch(`https://en.wikipedia.org/api/rest_v1/page/summary/${encodeURIComponent(searchTitle)}`);
                        if (!response.ok) {
                            if (response.status === 404) throw new Error('Not Found');
                            throw new Error(`Wikipedia API error: ${response.statusText}`);
                        }
                        const data = await response.json();
                        const summary = data.extract || `No summary available for ${searchTitle}.`;
                        const wikiUrl = data.content_urls?.desktop?.page;

                        summaryText = summary;
                        if (wikiUrl) {
                            summaryText += `\n\n[Source: Wikipedia](${wikiUrl})`;
                        }
                    } catch (wikiError) {
                        console.warn(`Wikipedia fetch for "${searchTitle}" failed, falling back to LLM. Reason:`, wikiError);
                        const summary = await generateHistoricalSummary(gameDate.year, currentRegion, localArea);
                        summaryText = summary + "\n\n(Generated by AI as a fallback)";
                    }
                }
                setArticleText(summaryText);
                cache.current.set(cacheKey, summaryText);
            } catch (llmError) {
                console.error("LLM fetch failed:", llmError);
                setError("Could not retrieve historical information at this time.");
            } finally {
                setIsLoading(false);
            }
        };

        if (currentRegion && localArea) {
            fetchArticle();
        }

    }, [gameDate, currentRegion, localArea, useLlm]);

    return (
        <div className="p-4 text-slate-300 text-sm">
            {isLoading && (
                <div className="flex items-center justify-center h-48">
                    <div className="animate-spin rounded-full h-8 w-8 border-b-2 border-amber-400"></div>
                </div>
            )}
            {error && <p className="text-red-400 italic">{error}</p>}
            {!isLoading && !error && (
                <div className="prose prose-sm prose-invert max-w-none">
                    {articleText.split('\n\n').map((paragraph, index) => (
                        <p key={index}>{paragraph}</p>
                    ))}
                </div>
            )}
        </div>
    );
};

export default WikipediaArticle;
