import type { Venue } from "./types";

const ALL: [number, number] = [-1000000, 10001];
const EUROPE: [number, number, number, number] = [-11, 34, 45, 72];
const JAPAN: [number, number, number, number] = [128, 30, 146, 46];
const WEST_ASIA: [number, number, number, number] = [-12, 20, 62, 45];
const EAST_ASIA: [number, number, number, number] = [98, 18, 146, 46];
const MESOAMERICA: [number, number, number, number] = [-106, 12, -84, 24];
const ANDES: [number, number, number, number] = [-82, -25, -62, 2];

/**
 * The places people go when the work is done. One row per institution that
 * really existed somewhere, scoped; the archetype it belongs to is `kind`.
 *
 * Coverage is deliberately uneven. The open-ground rows carry every scope, so
 * a settlement with no authored buildings still gives its people somewhere to
 * be; a named institution is an addition on top of that, never the only
 * option.
 */
export const venues: readonly Venue[] = [
  /* --- open ground: available everywhere, no building --------------- */
  {
    id: "venue.crossroads",
    label: "The crossroads",
    kind: "crossroads",
    scope: { years: ALL },
    minBuildings: 0,
    slot: "evening",
    minutes: 40,
    activity: "visit",
    weight: 14,
    open: true,
    note: "Where two ways meet and people stop without having arranged to.",
    sources: [],
  },
  {
    id: "venue.washing-place",
    label: "The washing place",
    kind: "washing-place",
    scope: { years: ALL },
    minBuildings: 0,
    tags: ["communal", "oral"],
    slot: "midday",
    minutes: 45,
    activity: "draw-water",
    weight: 10,
    open: true,
    note: "The river stones or the fountain kerb, where the work is done in company.",
    sources: [],
  },
  {
    id: "venue.shrine",
    label: "The shrine",
    kind: "shrine",
    scope: { years: ALL },
    minBuildings: 0,
    tags: ["devout", "traditionalist", "mystical"],
    slot: "evening",
    minutes: 25,
    activity: "visit",
    weight: 9,
    open: true,
    note: "A local power or the family dead, visited alone or nearly so.",
    sources: [],
  },
  {
    id: "venue.market-ground",
    label: "The market ground",
    kind: "market",
    scope: { years: ALL },
    minBuildings: 8,
    slot: "midday",
    minutes: 50,
    activity: "visit",
    weight: 16,
    open: true,
    note: "Exchange and news in the same hour; the one place everybody passes.",
    sources: [],
  },
  {
    id: "venue.promenade",
    label: "The promenade",
    kind: "promenade",
    scope: { years: [-500, 10001] },
    minBuildings: 60,
    ranks: ["middling", "gentry", "elite"],
    tags: ["hierarchical", "worldly"],
    slot: "evening",
    minutes: 45,
    activity: "visit",
    weight: 10,
    open: true,
    note: "A walk taken to be seen taking it, on the one street built for it.",
    sources: [],
  },
  /* --- drink and talk ----------------------------------------------- */
  {
    id: "venue.tavern",
    label: "The tavern",
    kind: "tavern",
    // Mesopotamian tavern-keepers are in Hammurabi's laws; the steppe and
    // the oases beyond Iran had nothing like them for a long while after.
    scope: { years: [-2000, 10001], bounds: [-18, 20, 62, 72] },
    minBuildings: 14,
    tags: ["worldly", "communal"],
    slot: "evening",
    minutes: 70,
    activity: "visit",
    weight: 16,
    sign: "board",
    note: "Drink sold by the measure, and the only warm room that is nobody's house.",
    sources: [],
  },
  {
    id: "venue.alehouse",
    label: "The alehouse",
    kind: "tavern",
    scope: { years: [1100, 1900], bounds: EUROPE, cultures: ["european"] },
    minBuildings: 10,
    tags: ["worldly", "communal"],
    slot: "evening",
    minutes: 70,
    activity: "visit",
    weight: 14,
    sign: "board",
    note: "A house that brews and hangs out a bush; the parish's other meeting place.",
    sources: [],
  },
  {
    id: "venue.izakaya",
    label: "The izakaya",
    kind: "tavern",
    scope: { years: [1650, 10001], bounds: JAPAN, cultures: ["east-asian"] },
    minBuildings: 14,
    tags: ["worldly", "communal"],
    slot: "evening",
    minutes: 60,
    activity: "visit",
    weight: 14,
    sign: "lantern",
    note: "A sake shop that began letting customers drink where they bought.",
    sources: [],
  },
  {
    id: "venue.pulqueria",
    label: "The pulquería",
    kind: "tavern",
    scope: {
      years: [1550, 10001],
      bounds: MESOAMERICA,
      cultures: ["mesoamerican"],
    },
    minBuildings: 12,
    tags: ["worldly", "communal"],
    slot: "evening",
    minutes: 60,
    activity: "visit",
    weight: 14,
    sign: "board",
    note: "Maguey beer sold from a counter, watched by every authority in turn.",
    sources: [],
  },
  {
    id: "venue.chicheria",
    label: "The chichería",
    kind: "tavern",
    scope: { years: [1400, 10001], bounds: ANDES, cultures: ["andean"] },
    minBuildings: 10,
    tags: ["worldly", "communal"],
    slot: "evening",
    minutes: 60,
    activity: "visit",
    weight: 14,
    sign: "board",
    note: "Maize beer brewed and sold by a household, marked by a pole and a flag.",
    sources: [],
  },
  {
    id: "venue.coffee-house",
    label: "The coffee house",
    kind: "coffee-house",
    scope: { years: [1650, 10001], bounds: EUROPE, cultures: ["european"] },
    minBuildings: 40,
    tags: ["literate", "reformist", "sceptical", "rationalist"],
    slot: "midday",
    minutes: 65,
    activity: "visit",
    weight: 13,
    sign: "board",
    note: "A penny for the dish and the newspapers free; where an argument is expected.",
    sources: [],
  },
  {
    id: "venue.kahvehane",
    label: "The coffee house",
    kind: "coffee-house",
    scope: {
      years: [1550, 10001],
      bounds: WEST_ASIA,
      cultures: ["north-african-west-asian"],
    },
    minBuildings: 25,
    tags: ["literate", "worldly", "sceptical"],
    slot: "evening",
    minutes: 70,
    activity: "visit",
    weight: 15,
    sign: "lantern",
    note: "Coffee, a storyteller and a backgammon board; closed by decree more than once.",
    sources: [],
  },
  {
    id: "venue.chaikhana",
    label: "The tea house",
    kind: "coffee-house",
    scope: {
      years: [1400, 10001],
      bounds: [50, 25, 100, 48],
      cultures: ["inner-eurasian"],
    },
    minBuildings: 20,
    tags: ["oral", "communal", "literate"],
    slot: "midday",
    minutes: 60,
    activity: "visit",
    weight: 13,
    sign: "board",
    note: "A platform, a samovar and the day's news off the road.",
    sources: [],
  },
  {
    id: "venue.teahouse-east",
    label: "The tea house",
    kind: "coffee-house",
    scope: { years: [800, 10001], bounds: EAST_ASIA, cultures: ["east-asian"] },
    minBuildings: 20,
    tags: ["literate", "quietist", "worldly"],
    slot: "midday",
    minutes: 55,
    activity: "visit",
    weight: 13,
    sign: "lantern",
    note: "Tea taken slowly in company, and the storyteller's pitch in the corner.",
    sources: [],
  },
  /* --- devotion and learning ---------------------------------------- */
  {
    id: "venue.temple-court-east",
    label: "The temple court",
    kind: "temple-yard",
    scope: { years: [-200, 10001], cultures: ["east-asian"] },
    minBuildings: 10,
    tags: ["devout", "communal", "traditionalist"],
    slot: "evening",
    minutes: 50,
    activity: "visit",
    weight: 15,
    marker: {
      variant: 1,
      name: "Incense burner",
      description:
        "A bronze censer on three legs, full of ash. Visitors light sticks of incense here before going up to the hall.",
    },
    note: "The open court of a Buddhist or Daoist temple, where people burn incense, draw fortune sticks and meet on festival days.",
    sources: [],
  },
  {
    id: "venue.temple-court-south",
    label: "The temple court",
    kind: "temple-yard",
    scope: { years: [300, 10001], cultures: ["south-asian"] },
    minBuildings: 10,
    tags: ["devout", "communal", "traditionalist"],
    slot: "evening",
    minutes: 50,
    activity: "visit",
    weight: 15,
    marker: {
      variant: 2,
      name: "Lamp pillar",
      description:
        "A stone pillar ringed with brackets for clay oil lamps, lit all at once on festival nights.",
    },
    note: "The walled court round a Hindu or Jain temple, where people walk round the shrine and wait for the lamps to be waved.",
    sources: [],
  },
  {
    id: "venue.wat",
    label: "The monastery grounds",
    kind: "temple-yard",
    scope: { years: [500, 10001], cultures: ["southeast-asian"] },
    minBuildings: 10,
    tags: ["devout", "communal", "traditionalist"],
    slot: "evening",
    minutes: 50,
    activity: "visit",
    weight: 15,
    marker: {
      variant: 6,
      name: "Chedi",
      description:
        "A whitewashed brick reliquary with a bell-shaped body and a ringed spire. Relics or the ashes of the dead are sealed inside.",
    },
    note: "The grounds of a Buddhist monastery, where monks live and the village comes to make merit, learn and hold its festivals.",
    sources: [],
  },
  {
    id: "venue.temple-precinct",
    label: "The temple precinct",
    kind: "temple-yard",
    scope: {
      years: [-800, 399],
      bounds: [-10, 28, 50, 48],
      cultures: ["european", "north-african-west-asian"],
    },
    minBuildings: 10,
    tags: ["devout", "communal", "traditionalist"],
    slot: "evening",
    minutes: 50,
    activity: "visit",
    weight: 15,
    marker: {
      variant: 4,
      name: "Altar",
      description:
        "A stone altar in the open before the temple, carved with a garland. Sacrifices were burned here, not inside.",
    },
    note: "The walled ground round a temple, where sacrifices were made in public and the meat shared out.",
    sources: [],
  },
  {
    id: "venue.churchyard",
    label: "The churchyard",
    kind: "temple-yard",
    scope: { years: [700, 10001], bounds: EUROPE, cultures: ["european"] },
    minBuildings: 10,
    tags: ["devout", "communal", "traditionalist"],
    slot: "evening",
    minutes: 40,
    activity: "visit",
    weight: 15,
    marker: {
      variant: 3,
      name: "Churchyard cross",
      description:
        "A stone cross on three steps. Processions stopped at it and preachers spoke from its steps.",
    },
    note: "The ground round the parish church: burials, fairs, notices read out after the service.",
    sources: [],
  },
  {
    id: "venue.mosque-court",
    label: "The mosque courtyard",
    kind: "temple-yard",
    scope: { years: [650, 10001], cultures: ["north-african-west-asian"] },
    minBuildings: 10,
    tags: ["devout", "communal", "traditionalist"],
    slot: "evening",
    minutes: 40,
    activity: "visit",
    weight: 15,
    marker: {
      variant: 5,
      name: "Ablution fountain",
      description:
        "A stone basin with taps round it, for washing hands, face and feet before prayer.",
    },
    note: "The open court of a mosque, where people wash before prayer and talk after it.",
    sources: [],
  },
  {
    id: "venue.sacred-grove",
    label: "The sacred grove",
    kind: "shrine",
    scope: { years: ALL, bounds: [55, 50, 180, 72], cultures: ["inner-eurasian"] },
    minBuildings: 0,
    tags: ["devout", "traditionalist", "mystical"],
    slot: "evening",
    minutes: 30,
    activity: "visit",
    weight: 12,
    open: true,
    marker: {
      variant: 0,
      name: "Spirit storehouse",
      description:
        "A small log store on a single post, holding the carved spirit figures and the offerings made to them. Cloth tied here is a gift.",
    },
    note: "A stand of trees outside the settlement where the spirits are kept and fed. Women and outsiders were often barred from parts of it.",
    sources: [],
  },
  {
    id: "venue.school",
    label: "The school",
    kind: "school",
    scope: { years: [-1000, 10001] },
    minBuildings: 30,
    tags: ["literate", "rationalist", "devout"],
    slot: "midday",
    minutes: 60,
    activity: "visit",
    weight: 8,
    sign: "board",
    building: "hall-union-hall",
    eras: [
      {
        from: 400,
        to: 1500,
        building: "hall-grammar-hall",
        cultures: ["european"],
      },
      {
        from: 1500,
        to: 1800,
        building: "hall-charity-school",
        cultures: ["european"],
      },
    ],
    note: "Letters taught by rote to whoever is sent, in one borrowed room.",
    sources: [],
  },
  {
    id: "venue.madrasa",
    label: "The madrasa",
    kind: "school",
    scope: {
      years: [1000, 1950],
      bounds: WEST_ASIA,
      cultures: ["north-african-west-asian"],
    },
    minBuildings: 35,
    ranks: ["middling", "gentry", "elite"],
    tags: ["literate", "devout", "rationalist"],
    slot: "midday",
    minutes: 80,
    activity: "visit",
    weight: 10,
    sign: "lantern",
    building: "hall-madrasa",
    note: "Law and grammar round a courtyard, endowed and open to its students' hours.",
    sources: [],
  },
  {
    id: "venue.terakoya",
    label: "The temple school",
    kind: "school",
    scope: { years: [1600, 1880], bounds: JAPAN, cultures: ["east-asian"] },
    minBuildings: 20,
    tags: ["literate", "traditionalist"],
    slot: "midday",
    minutes: 60,
    activity: "visit",
    weight: 10,
    sign: "board",
    building: "hall-union-hall",
    note: "Writing and the abacus taught to townsmen's children beside the temple.",
    sources: [],
  },
  /* --- washing ------------------------------------------------------- */
  {
    id: "venue.bath-house",
    label: "The bath house",
    kind: "bath",
    scope: { years: [-500, 10001] },
    minBuildings: 35,
    tags: ["worldly", "communal"],
    slot: "midday",
    minutes: 70,
    activity: "visit",
    weight: 12,
    sign: "lantern",
    building: "hall-thermae",
    eras: [
      { from: 400, to: 1500, building: "hall-stew", cultures: ["european"] },
      { from: 1500, to: 1800, building: "hall-bagnio", cultures: ["european"] },
    ],
    note: "Hot water taken in company, and the business done while waiting for it.",
    sources: [],
  },
  {
    id: "venue.hammam",
    label: "The hammam",
    kind: "bath",
    scope: {
      years: [700, 10001],
      bounds: WEST_ASIA,
      cultures: ["north-african-west-asian"],
    },
    minBuildings: 25,
    tags: ["communal", "devout", "worldly"],
    slot: "midday",
    minutes: 90,
    activity: "visit",
    weight: 15,
    sign: "lantern",
    building: "hall-hammam",
    note: "Washing required before prayer, and the day's other great sociable hour.",
    sources: [],
  },
  {
    id: "venue.sento",
    label: "The bath house",
    kind: "bath",
    scope: { years: [1600, 10001], bounds: JAPAN, cultures: ["east-asian"] },
    minBuildings: 18,
    tags: ["communal", "worldly", "egalitarian"],
    slot: "evening",
    minutes: 60,
    activity: "visit",
    weight: 16,
    sign: "lantern",
    building: "hall-sento",
    note: "Every rank in the same water, which is what made it worth remarking on.",
    sources: [],
  },
  /* --- performance and contest --------------------------------------- */
  {
    id: "venue.opera-house",
    label: "The opera house",
    kind: "theatre",
    scope: { years: [1680, 1950], bounds: EUROPE, cultures: ["european"] },
    minBuildings: 120,
    ranks: ["gentry", "elite"],
    tags: ["hierarchical", "worldly", "literate"],
    slot: "evening",
    minutes: 150,
    activity: "visit",
    weight: 12,
    sign: "lantern",
    building: "theatre-opera-house",
    eras: [{ from: 1680, to: 1800, building: "theatre-court-opera" }],
    note: "A box taken for the season, and the performance the least of what happens there.",
    sources: [],
  },
  {
    id: "venue.playhouse",
    label: "The playhouse",
    kind: "theatre",
    scope: { years: [1570, 1950], bounds: EUROPE, cultures: ["european"] },
    minBuildings: 70,
    tags: ["worldly", "oral"],
    slot: "midday",
    minutes: 120,
    activity: "visit",
    weight: 11,
    sign: "board",
    building: "theatre-playhouse",
    eras: [{ from: 1570, to: 1800, building: "theatre-globe" }],
    note: "A penny to stand in the yard, more to sit; the audience audible throughout.",
    sources: [],
  },
  {
    id: "venue.noh-stage",
    label: "The noh stage",
    kind: "theatre",
    scope: { years: [1400, 1950], bounds: JAPAN, cultures: ["east-asian"] },
    minBuildings: 60,
    ranks: ["gentry", "elite"],
    tags: ["hierarchical", "ascetic", "traditionalist"],
    slot: "midday",
    minutes: 150,
    activity: "visit",
    weight: 12,
    sign: "lantern",
    building: "theatre-noh-stage",
    note: "Slow, masked and patronised by the warrior houses that alone could attend.",
    sources: [],
  },
  {
    id: "venue.kabuki-theatre",
    label: "The kabuki theatre",
    kind: "theatre",
    scope: { years: [1650, 1950], bounds: JAPAN, cultures: ["east-asian"] },
    minBuildings: 70,
    ranks: ["labouring", "middling"],
    tags: ["worldly", "oral", "individualist"],
    slot: "midday",
    minutes: 180,
    activity: "visit",
    weight: 14,
    sign: "board",
    building: "theatre-kabuki-theatre",
    note: "A whole day's entertainment for the townsmen, and disreputable by statute.",
    sources: [],
  },
  {
    id: "venue.wayang",
    label: "The shadow-play ground",
    kind: "theatre",
    scope: {
      years: [900, 10001],
      bounds: [95, -11, 141, 8],
      cultures: ["southeast-asian"],
    },
    minBuildings: 12,
    tags: ["oral", "communal", "traditionalist"],
    slot: "evening",
    minutes: 180,
    activity: "visit",
    weight: 14,
    open: true,
    note: "A screen, a lamp and a night's recitation, paid for by whoever has cause.",
    sources: [],
  },
  {
    id: "venue.cinema",
    label: "The picture house",
    kind: "theatre",
    scope: { years: [1910, 10001] },
    // Small towns had one. The threshold was set for an opera house and is
    // wrong for a building that only needed a hall and a projector.
    minBuildings: 40,
    // Not a gate anybody enforced: the opera and the picture house shared a
    // city and not an audience, and the ranks are how the two coexist here.
    ranks: ["destitute", "labouring", "middling"],
    tags: ["worldly", "individualist"],
    slot: "evening",
    minutes: 110,
    activity: "visit",
    weight: 18,
    sign: "lantern",
    building: "theatre-picture-house",
    note: "The cheapest seat in any town, and for thirty years the most crowded.",
    sources: [],
  },
  {
    id: "venue.amphitheatre",
    label: "The amphitheatre",
    kind: "arena",
    scope: {
      years: [-100, 500],
      bounds: [-11, 30, 40, 56],
      cultures: ["european"],
    },
    minBuildings: 100,
    tags: ["martial", "worldly", "civic"],
    slot: "midday",
    minutes: 180,
    activity: "visit",
    weight: 14,
    sign: "board",
    note: "Seating assigned by rank, which is half of what the building is for.",
    sources: [],
  },
  {
    id: "venue.ball-court",
    label: "The ball court",
    kind: "arena",
    scope: {
      years: [-1400, 1550],
      bounds: MESOAMERICA,
      cultures: ["mesoamerican"],
    },
    minBuildings: 20,
    tags: ["devout", "martial", "civic"],
    slot: "midday",
    minutes: 120,
    activity: "visit",
    weight: 15,
    sign: "board",
    building: "meso-ballcourt",
    note: "A game played between two stone walls, and not only a game.",
    sources: [],
  },
  {
    id: "venue.wrestling-ground",
    label: "The wrestling ground",
    kind: "arena",
    scope: { years: [-1000, 10001] },
    minBuildings: 6,
    tags: ["martial", "communal"],
    slot: "evening",
    minutes: 70,
    activity: "play",
    weight: 11,
    open: true,
    note: "Flat ground, a ring of onlookers, and standing to be won in an afternoon.",
    sources: [],
  },
  /* --- decision and association -------------------------------------- */
  {
    id: "venue.assembly",
    label: "The assembly ground",
    kind: "assembly",
    scope: { years: ALL },
    minBuildings: 6,
    tags: ["civic", "communal", "egalitarian"],
    slot: "midday",
    minutes: 80,
    activity: "visit",
    weight: 12,
    open: true,
    note: "Where a thing is argued in front of everyone it concerns.",
    sources: [],
  },
  {
    id: "venue.town-hall",
    label: "The town hall",
    kind: "assembly",
    scope: { years: [1200, 10001], bounds: EUROPE, cultures: ["european"] },
    minBuildings: 45,
    ranks: ["middling", "gentry", "elite"],
    tags: ["civic", "literate", "hierarchical"],
    slot: "midday",
    minutes: 90,
    activity: "visit",
    weight: 11,
    sign: "lantern",
    building: "hall-town-hall",
    eras: [
      { from: 400, to: 1500, building: "hall-moot-hall" },
      { from: 1500, to: 1800, building: "hall-rathaus" },
    ],
    note: "The corporation's own room, with the measures and the charter locked in it.",
    sources: [],
  },
  {
    id: "venue.guild-hall",
    label: "The guild hall",
    kind: "lodge",
    scope: { years: [1100, 1900], bounds: EUROPE, cultures: ["european"] },
    minBuildings: 45,
    ranks: ["middling", "gentry"],
    tags: ["particularist", "civic", "mercantile"],
    livelihoods: [
      "smith",
      "blacksmith",
      "cooper",
      "tailor",
      "weaver",
      "carpenter",
      "baker",
      "butcher",
      "mason",
      "stonemason",
      "cobbler",
      "saddler",
      "journeyman",
      "guild-master",
    ],
    slot: "evening",
    minutes: 90,
    activity: "visit",
    weight: 16,
    sign: "board",
    building: "hall-town-hall",
    eras: [
      { from: 400, to: 1500, building: "hall-moot-hall" },
      { from: 1500, to: 1800, building: "hall-rathaus" },
    ],
    note: "The trade's own room, its feast and its funeral fund, shut to everyone else.",
    sources: [],
  },
  {
    id: "venue.sufi-lodge",
    label: "The lodge",
    kind: "lodge",
    scope: {
      years: [1100, 10001],
      bounds: [-12, 8, 100, 45],
      cultures: [
        "north-african-west-asian",
        "south-asian",
        "inner-eurasian",
        "west-central-african",
        "southeast-asian",
      ],
    },
    minBuildings: 18,
    tags: ["mystical", "devout", "ascetic", "communal"],
    slot: "evening",
    minutes: 100,
    activity: "visit",
    weight: 13,
    sign: "lantern",
    building: "hall-madrasa",
    note: "A hall for the order's recitation, and beds for travellers on the way through.",
    sources: [],
  },
  {
    id: "venue.union-hall",
    label: "The union hall",
    kind: "lodge",
    scope: { years: [1850, 10001] },
    minBuildings: 50,
    ranks: ["destitute", "labouring", "middling"],
    tags: ["egalitarian", "reformist", "communal", "revolutionary"],
    slot: "evening",
    minutes: 85,
    activity: "visit",
    weight: 14,
    sign: "board",
    building: "hall-union-hall",
    note: "A hired room, a subscription book, and the only place the trade meets whole.",
    sources: [],
  },
  {
    id: "venue.age-set-house",
    label: "The age-set house",
    kind: "lodge",
    scope: {
      years: [-500, 1950],
      bounds: [8, -32, 52, 16],
      cultures: ["east-southern-african"],
    },
    minBuildings: 6,
    tags: ["communal", "martial", "egalitarian"],
    slot: "evening",
    minutes: 90,
    activity: "visit",
    weight: 15,
    sign: "board",
    building: "hall-union-hall",
    note: "Those initiated together sleep, eat and answer to each other here.",
    sources: [],
  },
  /* --- stakes --------------------------------------------------------- */
  {
    id: "venue.gaming-house",
    label: "The gaming house",
    kind: "gaming-house",
    scope: { years: [-500, 10001] },
    minBuildings: 30,
    tags: ["worldly", "individualist", "sceptical"],
    slot: "evening",
    minutes: 80,
    activity: "visit",
    weight: 8,
    sign: "lantern",
    note: "Dice or cards for money, tolerated in proportion to who is playing.",
    sources: [],
  },
  {
    id: "venue.dice-pitch",
    label: "The dice pitch",
    kind: "gaming-house",
    scope: { years: ALL },
    minBuildings: 8,
    tags: ["worldly", "individualist"],
    slot: "evening",
    minutes: 50,
    activity: "play",
    weight: 7,
    open: true,
    note: "A wall, a patch of dirt and a game that has been played on both since.",
    sources: [],
  },
  /* --- outside Europe, MENA and East Asia -------------------------- */
  {
    id: "venue.sweat-lodge",
    label: "The sweat lodge",
    kind: "bath",
    scope: { years: [-3000, 10001], bounds: [-170, 12, -52, 72] },
    minBuildings: 0,
    tags: ["devout", "communal", "traditionalist", "oral"],
    slot: "evening",
    minutes: 90,
    activity: "visit",
    weight: 16,
    sign: "lantern",
    building: "hall-sweat-lodge",
    note: "Heat, steam and song in the dark, for purification rather than for washing; entered and left in a fixed order, and not a bath house with a different roof.",
    sources: [],
  },
  {
    id: "venue.temazcal",
    label: "The temazcal",
    kind: "bath",
    scope: { years: [-1200, 10001], bounds: [-106, 12, -84, 24] },
    minBuildings: 4,
    tags: ["devout", "communal", "traditionalist"],
    slot: "evening",
    minutes: 70,
    activity: "visit",
    weight: 16,
    sign: "lantern",
    building: "meso-temazcal",
    note: "A low vaulted sweat house heated by a stone wall, used for healing, after childbirth and before ceremony.",
    sources: [],
  },
  {
    id: "venue.andean-sweat-house",
    label: "The sweat house",
    kind: "bath",
    scope: { years: [-1000, 10001], bounds: [-82, -25, -62, 2] },
    minBuildings: 4,
    tags: ["devout", "communal", "traditionalist"],
    slot: "evening",
    minutes: 60,
    activity: "visit",
    weight: 14,
    sign: "lantern",
    building: "hall-sweat-lodge",
    note: "Steam raised over hot stones in a low stone chamber, taken for illness and for cold.",
    sources: [],
  },
  {
    id: "venue.river-bathing",
    label: "The bathing steps",
    kind: "bath",
    scope: { years: [-1500, 10001], bounds: [66, 5, 93, 37] },
    minBuildings: 6,
    tags: ["devout", "communal", "traditionalist"],
    slot: "midday",
    minutes: 60,
    activity: "draw-water",
    weight: 20,
    open: true,
    note: "Steps down to the water where washing, bathing and the morning's devotions are the same act.",
    sources: [],
  },
  {
    id: "venue.kiva",
    label: "The kiva",
    kind: "lodge",
    scope: { years: [700, 10001], bounds: [-114, 31, -104, 40] },
    minBuildings: 6,
    tags: ["devout", "communal", "traditionalist", "particularist"],
    slot: "evening",
    minutes: 110,
    activity: "visit",
    weight: 18,
    sign: "lantern",
    building: "hall-kiva",
    note: "A round chamber sunk into the ground, entered by a ladder through the roof; the room a clan or a society keeps and works in.",
    sources: [],
  },
  {
    id: "venue.mens-house",
    label: "The men's house",
    kind: "lodge",
    scope: { years: [-1000, 10001], bounds: [130, -12, 156, 2] },
    minBuildings: 4,
    tags: ["communal", "martial", "particularist", "devout"],
    slot: "evening",
    minutes: 100,
    activity: "visit",
    weight: 18,
    sign: "board",
    building: "hall-carved-gable",
    note: "A tall painted house on posts holding what the initiated may see and the rest of the village may not.",
    sources: [],
  },
  {
    id: "venue.meeting-house",
    label: "The meeting house",
    kind: "assembly",
    scope: { years: [1200, 10001], bounds: [165, -48, 180, -33] },
    minBuildings: 4,
    tags: ["communal", "oral", "traditionalist", "civic"],
    slot: "evening",
    minutes: 120,
    activity: "visit",
    weight: 20,
    sign: "board",
    building: "hall-carved-gable",
    note: "The carved house on the marae, itself an ancestor: the ridge its spine, the bargeboards its arms, and everything of consequence said inside it.",
    sources: [],
  },
  {
    id: "venue.toguna",
    label: "The talking shelter",
    kind: "assembly",
    scope: { years: [1000, 10001], bounds: [-8, 12, 8, 17] },
    minBuildings: 4,
    tags: ["communal", "oral", "civic", "traditionalist"],
    slot: "midday",
    minutes: 80,
    activity: "visit",
    weight: 20,
    sign: "board",
    building: "hall-open-shelter",
    note: "A shelter roofed thick with millet stalk on carved posts, built too low to stand in so that an argument cannot become a fight.",
    sources: [],
  },
  {
    id: "venue.kgotla",
    label: "The kgotla",
    kind: "assembly",
    scope: { years: [1400, 10001], bounds: [16, -32, 34, -17] },
    minBuildings: 4,
    tags: ["communal", "civic", "hierarchical", "oral"],
    slot: "midday",
    minutes: 100,
    activity: "visit",
    weight: 20,
    open: true,
    note: "A half-circle of thorn fence round a tree where the ward's business is heard and anyone present may speak.",
    sources: [],
  },
  {
    id: "venue.longhouse-council",
    label: "The council house",
    kind: "assembly",
    scope: { years: [1400, 10001], bounds: [-80, 40, -70, 47] },
    minBuildings: 4,
    tags: ["communal", "civic", "egalitarian", "oral"],
    slot: "evening",
    minutes: 120,
    activity: "visit",
    weight: 18,
    sign: "board",
    building: "hall-open-shelter",
    note: "The long bark-covered house the council sits in, with the clan mothers naming those who hold its seats.",
    sources: [],
  },
  {
    id: "venue.ramada",
    label: "The brush arbour",
    kind: "assembly",
    scope: { years: [-2000, 10001], bounds: [-118, 14, -96, 38] },
    minBuildings: 3,
    tags: ["communal", "oral"],
    slot: "midday",
    minutes: 70,
    activity: "visit",
    weight: 16,
    sign: "board",
    building: "hall-open-shelter",
    note: "Four posts and a roof of brush: shade to work and talk under, which in that country is the whole of what a public room needs to be.",
    sources: [],
  },
  {
    id: "venue.gurukula",
    label: "The teacher's house",
    kind: "school",
    scope: { years: [-800, 1900], bounds: [66, 5, 93, 37] },
    minBuildings: 10,
    tags: ["literate", "oral", "devout", "hierarchical"],
    slot: "midday",
    minutes: 90,
    activity: "visit",
    weight: 12,
    sign: "board",
    building: "hall-open-shelter",
    note: "Pupils living in the teacher's household and learning by recitation, under the veranda or the tree outside it.",
    sources: [],
  },
  {
    id: "venue.quranic-school",
    label: "The Qur'an school",
    kind: "school",
    scope: { years: [1100, 10001], bounds: [-17, 8, 25, 20] },
    minBuildings: 8,
    tags: ["literate", "devout", "oral"],
    slot: "midday",
    minutes: 70,
    activity: "visit",
    weight: 14,
    sign: "board",
    building: "hall-open-shelter",
    note: "Children at a master's feet with wooden tablets, reciting until the board is learnt and then washing it clean.",
    sources: [],
  },
  {
    id: "venue.calmecac",
    label: "The calmecac",
    kind: "school",
    scope: { years: [1300, 1560], bounds: [-106, 12, -84, 24] },
    minBuildings: 20,
    ranks: ["gentry", "elite"],
    tags: ["literate", "devout", "hierarchical", "ascetic"],
    slot: "midday",
    minutes: 110,
    activity: "visit",
    weight: 14,
    sign: "lantern",
    building: "meso-calmecac",
    note: "The school attached to the temple where the sons of lords learnt the calendar, the songs and a great deal of fasting.",
    sources: [],
  },
  {
    id: "venue.telpochcalli",
    label: "The youths' house",
    kind: "school",
    scope: { years: [1300, 1560], bounds: [-106, 12, -84, 24] },
    minBuildings: 12,
    ranks: ["destitute", "labouring", "middling"],
    tags: ["communal", "martial", "oral"],
    slot: "evening",
    minutes: 100,
    activity: "visit",
    weight: 16,
    sign: "board",
    building: "meso-telpochcalli",
    note: "The ward's house for young commoners: work, arms and dancing, and where most of the city was actually brought up.",
    sources: [],
  },
];
