/**
 * constants/gameData/regionalHistory/eastAsia.ts
 * Century and region-specific historical descriptions for East Asia
 */

import { RegionalHistoryData } from '../../../types/regionalHistory';

export const EAST_ASIA_REGIONAL_HISTORY: RegionalHistoryData['EAST_ASIAN'] = {
    "North China Plain": {
        "-3000": "The Longshan culture develops sophisticated pottery and walled settlements. Early Chinese civilization emerges along the Yellow River with agriculture and ancestor worship.",
        "-2000": "The legendary Xia Dynasty may have existed in this period, though archaeological evidence is debated. Bronze working begins. Urban settlements grow larger.",
        "-1000": "The Zhou Dynasty establishes the Mandate of Heaven concept. Bronze technology reaches its zenith. The feudal system organizes society into hierarchical relationships.",
        "-600": "The Spring and Autumn period sees dozens of states compete while acknowledging Zhou kings as nominal overlords. Confucius begins teaching moral philosophy in an age of constant warfare.",
        "-500": "The Warring States period intensifies as major powers absorb smaller states. Iron weapons and cavalry transform warfare. Philosophical schools including Confucianism, Daoism, and Legalism compete for influence.",
        "-400": "Seven major states remain in brutal competition. Qin state in the west adopts Legalist reforms and builds military strength. The age produces great philosophers and military strategists.",
        "-300": "Qin state continues aggressive expansion using Legalist organization and superior iron weapons. The Mandate of Heaven concept justifies the conquest of rival states.",
        "-200": "Qin Shi Huang unifies China in 221 BCE, creating the first empire. Standardization of writing, currency, and measurements follows. The Great Wall is connected and expanded.",
        "-100": "The Han Dynasty consolidates power after civil war. The Silk Road opens trade with Central Asia and beyond. Confucianism becomes state ideology while Buddhism begins arriving.",
        "0": "Han Dynasty reaches its zenith with firm control over the Yellow River valley. Bureaucratic administration based on Confucian learning creates an educated elite.",
        "100": "The Later Han Dynasty faces challenges from court factions and regional warlords. Paper and porcelain production advances. Buddhism spreads along trade routes.",
        "200": "The Han Dynasty collapses into the Three Kingdoms period. Warfare devastates the north. The Romance of the Three Kingdoms era begins its legendary status.",
        "300": "Northern China fragments as nomadic invasions disrupt Chinese rule. The Jin Dynasty briefly unifies the north before losing control. Mass southern migration begins.",
        "400": "The Sixteen Kingdoms period sees chaos as various nomadic dynasties compete for control. Buddhism flourishes as a unifying force amid political fragmentation.",
        "500": "The Northern Wei Dynasty, established by Xianbei nomads, controls much of the north. Buddhism becomes state-sponsored. Chinese and nomadic cultures blend into a new synthesis.",
        "600": "The Sui Dynasty briefly reunifies China, connecting north and south with the Grand Canal. Massive public works projects drain resources, leading to rebellion and collapse.",
        "700": "The Tang Dynasty presides over a golden age. Chang'an becomes the world's largest and most cosmopolitan city. The equal-field system distributes land to peasants.",
        "800": "Tang power peaks before the An Lushan Rebellion devastates the north. The dynasty never fully recovers its earlier strength. Regional military governors gain autonomy.",
        "900": "Tang Dynasty collapses. The Five Dynasties period brings rapid succession of short-lived regimes. Warfare and instability plague the north.",
        "1000": "The Northern Song Dynasty controls the region but faces constant pressure from the Khitan Liao state to the north. A sophisticated urban culture develops despite military weakness.",
        "1100": "The Jurchen Jin Dynasty conquers the north, forcing Song to flee south. Beijing becomes a major capital. The region experiences cultural blending between Chinese and Jurchen.",
        "1200": "Mongol invasions devastate the north. The Jin Dynasty falls. Kublai Khan establishes the Yuan Dynasty with Beijing (Khanbaliq) as capital of a vast empire.",
        "1300": "Mongol Yuan Dynasty rules but faces growing Chinese resentment. The regime relies on Central Asian and European administrators while excluding Chinese from high office.",
        "1400": "The Ming Dynasty expels the Mongols and moves the capital to Beijing. The Forbidden City is constructed. The Great Wall is rebuilt in its current brick form.",
        "1500": "Ming Dynasty faces Mongol raids and Japanese piracy. The state emphasizes agriculture and Neo-Confucian orthodoxy. The examination system reaches full development.",
        "1600": "Late Ming Dynasty suffers internal rebellions and Manchu invasions from the northeast. Fiscal crisis and famines weaken the regime. Beijing falls to rebels then Manchus.",
        "1700": "The Qing Dynasty consolidates Manchu rule. Prosperity returns under strong emperors. Population grows dramatically. Agricultural expansion continues.",
        "1800": "Qing Dynasty faces internal rebellions and Western pressure. The Opium Wars force unequal treaties. The Taiping Rebellion devastates the region with tens of millions dead.",
        "1900": "The Qing Dynasty collapses in 1911-12. The Republic struggles with warlordism. Beijing changes hands between rival factions. Japanese invasion looms."
    },

    "South China": {
        "-3000": "Neolithic cultures along the Yangtze River independently develop rice agriculture. The Liangzhu culture creates sophisticated jade working and early urbanism.",
        "-2000": "Bronze Age cultures develop wet-rice cultivation techniques. The region maintains distinct cultural traditions from the Yellow River civilizations to the north.",
        "-1000": "The Chu kingdom emerges as a major power with its own cultural traditions. Southern bronze working and lacquer techniques develop distinctive styles.",
        "-500": "The Yangtze valley develops sophisticated wet-rice agriculture. The states of Wu and Yue compete before being conquered by northern powers.",
        "-400": "The Chu kingdom dominates the Yangtze region with a distinct southern culture. Shamanic traditions coexist with northern Chinese influence.",
        "-300": "Qin expansion reaches the Yangtze valley. The region's sophisticated irrigation systems impress northern conquerors.",
        "-200": "Han Dynasty rule integrates the south into the empire. The region becomes a major rice-producing area. Local aristocracies maintain influence.",
        "0": "Southern China prospers under Han rule. Trade networks connect the Yangtze with Southeast Asia. Iron tools and animal power increase agricultural productivity.",
        "100": "The Later Han Dynasty's rule brings continued agricultural development. Buddhism arrives via southern trade routes as well as the Silk Road.",
        "200": "The Three Kingdoms period sees the Wu kingdom based in the Yangtze delta. Southern naval power becomes strategically important.",
        "300": "Jin Dynasty control is tenuous. Local aristocratic families dominate regional politics. Wet-rice agriculture continues advancing.",
        "400": "The south becomes a refuge for Chinese fleeing nomadic invasions of the north. The Eastern Jin Dynasty rules from Nanjing. Southern Chinese culture flourishes.",
        "500": "The Southern Dynasties period sees rapid succession of regimes based in Nanjing. Buddhism flourishes with magnificent monasteries. Literature and art develop distinctive southern styles.",
        "600": "The Sui Dynasty reunifies north and south. The Grand Canal connects the Yangtze to the Yellow River, transforming trade and strategic logistics.",
        "700": "Under Tang rule, the Yangtze region becomes economically vital. Rice surpluses feed the capital. The south's population and wealth grow to match the north.",
        "800": "The An Lushan Rebellion drives more migration south. The Yangtze delta becomes the empire's economic center. Canal trade flourishes.",
        "900": "While the north fragments, southern kingdoms maintain stability. The Wu-Yue kingdom in the delta preserves culture and commerce.",
        "1000": "The Southern Song Dynasty rules from Hangzhou after losing the north. The Yangtze delta becomes the world's most prosperous region. Maritime trade expands dramatically.",
        "1100": "Southern Song culture reaches great heights despite military pressure. Hangzhou rivals any city in the world. Neo-Confucianism develops as a philosophical synthesis.",
        "1200": "The Mongol invasion devastates the south last. Marco Polo visits Hangzhou and marvels at its wealth. The Yuan Dynasty attempts to control the economic heartland.",
        "1300": "Yuan rule faces resistance in the south. The region's sophisticated commercial economy clashes with Mongol military culture. Secret societies organize.",
        "1400": "The Ming Dynasty, founded by a southern rebel, makes Nanjing its first capital. The Yangtze delta prospers from government support and maritime trade.",
        "1500": "Southern coastal commerce flourishes despite official restrictions. Portuguese traders establish Macau. The region becomes a center of international trade.",
        "1600": "Late Ming commercial economy reaches unprecedented sophistication. Silk and porcelain exports enrich merchants. Publishing and printing flourish.",
        "1700": "Early Qing rule brings peace and prosperity. Population grows rapidly. The Yangtze delta remains the empire's economic powerhouse.",
        "1800": "The Opium Wars open southern ports to British trade. The Taiping Rebellion begins in the south, causing massive destruction before being suppressed.",
        "1900": "Treaty ports transform southern coastal cities. Shanghai emerges as China's modern commercial center. Revolutionary movements take root in the south."
    },

    "West China and Tibet": {
        "-300": "The Qin state conquers Sichuan, gaining control of its rich agricultural basin. The region's productivity helps fuel Qin's unification wars.",
        "-200": "Han Dynasty firmly controls Sichuan. Silk Road routes pass through western regions. The empire establishes a military presence in Central Asian oases.",
        "100": "The Later Han Dynasty maintains western garrisons. Buddhism enters from India via Tibet and Central Asia. The Tibetan plateau remains largely independent.",
        "300": "Jin Dynasty control over the west weakens. Tibetan tribes begin organizing. Sichuan becomes contested between northern and southern regimes.",
        "500": "Sichuan provides an agricultural base for southern dynasties. Tibet develops as a distinct civilization with Buddhism spreading from Nepal and India.",
        "600": "The Tibetan Empire emerges as a major power, competing with Tang China for Central Asian control. Songtsen Gampo unifies Tibet and adopts Buddhism.",
        "700": "The Tibetan Empire reaches its zenith, controlling much of Central Asia and briefly occupying Tang Chang'an. Buddhism becomes deeply integrated into Tibetan culture.",
        "800": "Tibet begins fragmenting after the anti-Buddhist persecution. Tang Dynasty regains some western influence. Sichuan prospers as a Tang stronghold.",
        "900": "Political fragmentation continues in Tibet. Buddhist monasteries preserve learning during the 'dark period.' Sichuan becomes a base for late Tang warlords.",
        "1000": "Tibetan Buddhism experiences a renaissance with Indian and Nepalese influence. Sichuan prospers under Song rule. Tea and horse trade connects the regions.",
        "1100": "Tibetan monasteries gain political power. Different Buddhist lineages compete. The Mongols begin taking interest in the region.",
        "1200": "Mongol conquest brings Tibet into the Yuan Empire through patron-priest relationships. The Sakya school gains prominence. Sichuan suffers from Mongol invasions.",
        "1300": "Yuan Dynasty rules both regions. Tibetan lamas gain influence at the Mongol court. The unique relationship between religious and secular power develops.",
        "1400": "Ming Dynasty controls Sichuan but exercises loose authority over Tibet through religious ties. Gelugpa (Yellow Hat) school emerges.",
        "1500": "The Dalai Lama institution is established. Mongols renew ties with Tibetan Buddhism. Sichuan prospers as a Ming province rich in agricultural and mineral resources.",
        "1600": "The Fifth Dalai Lama consolidates power with Mongol military support. The Potala Palace is built. Sichuan faces devastation from Ming-Qing transition warfare.",
        "1700": "Qing Dynasty extends authority over Tibet. The Dalai Lama and Panchen Lama share spiritual authority. Sichuan recovers and population expands.",
        "1800": "Qing control over Tibet weakens. British interest from India increases. Sichuan remains a prosperous agricultural region supplying the empire.",
        "1900": "The 13th Dalai Lama asserts independence as Qing falls. British expeditions reach Lhasa. Sichuan becomes a warlord base during the Republic period."
    },

    "Mongolia and Manchuria": {
        "-300": "The Xiongnu confederation emerges on the steppe, threatening Chinese states. Nomadic pastoralism dominates the economy and culture.",
        "-200": "The Xiongnu Empire reaches its height, extracting tribute from Han China. Constant warfare shapes the steppe peoples into formidable cavalry forces.",
        "0": "Han military campaigns weaken Xiongnu power. The confederation splits into northern and southern factions. The steppe becomes contested terrain.",
        "100": "The Xianbei emerge as the dominant steppe power. Manchuria sees Chinese agricultural settlement expanding alongside nomadic peoples.",
        "200": "Fragmentation on the steppe allows multiple tribal confederations to arise. Some Xianbei tribes invade northern China during the Three Kingdoms collapse.",
        "300": "The Xianbei establish kingdoms in northern China. Manchuria becomes a borderland between Chinese and nomadic cultures. The Rouran rise on the Mongolian steppe.",
        "400": "The Rouran Khaganate dominates Mongolia. Various Turkic tribes begin their westward migrations. Manchuria experiences cultural mixing.",
        "500": "The Göktürk Khaganate replaces Rouran power. The term 'Turk' enters Chinese records. Manchuria remains divided between tribal groups.",
        "600": "The First Turkic Khaganate splits. Tang China extends influence over the eastern steppe. Manchurian Tungusic peoples maintain autonomy.",
        "700": "The Uyghur Khaganate allies with Tang China. Manichaeism and Buddhism spread on the steppe. Manchuria sees competing Chinese and nomadic influences.",
        "800": "The Uyghur Khaganate collapses. The Kyrgyz briefly dominate Mongolia. The Khitan people consolidate power in Manchuria and eastern Mongolia.",
        "900": "The Khitan Liao Dynasty rules Manchuria and threatens northern China. They create a dual administration system for nomadic and agricultural populations.",
        "1000": "The Liao Dynasty controls the region, balancing steppe traditions with Chinese administrative practices. The Jurchen tribes grow stronger in Manchuria.",
        "1100": "The Jurchen Jin Dynasty overthrows Liao and conquers northern China. Mongolia sees the rise of new tribal confederations.",
        "1200": "Genghis Khan unifies the Mongol tribes and launches world conquest. The Mongol Empire emerges from the steppe to dominate Eurasia.",
        "1300": "After Kublai Khan moves the capital to China, Mongolia remains the empire's spiritual homeland. Tibetan Buddhism begins spreading among Mongols.",
        "1400": "Ming Dynasty expels the Mongols. The Northern Yuan continues on the steppe. Manchuria becomes a contested borderland. Tribes fragment into competing groups.",
        "1500": "Altan Khan reunifies much of Mongolia and converts to Tibetan Buddhism. The Jurchen in Manchuria reorganize under new leadership.",
        "1600": "Nurhaci unifies Manchurian Jurchen tribes, creating the Later Jin state. Mongols are incorporated as military allies. The conquest of China begins.",
        "1700": "The Qing Dynasty rules from Beijing but maintains close ties to Mongolia and Manchuria. Mongol princes become part of the Qing imperial system.",
        "1800": "Qing rule continues but Russian expansion threatens from the north. Traditional nomadic economy declines. Population pressure increases on the steppe.",
        "1900": "Mongolian independence movements emerge as Qing collapses. Russian and Japanese competition for Manchuria intensifies. Modern borders begin forming."
    },

    "Japan": {
        "-3000": "The Jōmon culture continues its long tradition of hunter-gatherer societies with sophisticated pottery. Coastal and forest resources sustain semi-sedentary communities.",
        "-2000": "Late Jōmon cultures develop complex societies despite remaining primarily hunter-gatherers. Regional trading networks and ritual centers emerge.",
        "-1000": "The transition from Jōmon to Yayoi begins late in this period as rice agriculture and bronze tools arrive from Korea, transforming Japanese society.",
        "-300": "The Yayoi period sees wet-rice agriculture transform Japanese society. Metal tools arrive from Korea. Hundreds of small kingdoms compete.",
        "0": "The Kofun period begins with powerful regional chiefs building massive burial mounds. Connections to Korea bring continental culture and technology.",
        "100": "Yamato polity emerges in the Kinai region. Chinese historical records mention the 'Queen of Wa.' Korean kingdoms maintain close ties.",
        "200": "The Yamato court extends influence across Honshu. Buddhism and Chinese writing begin arriving via Korea. The imperial institution takes shape.",
        "300": "Massive kofun tumuli demonstrate elite power. Horse-riding culture from the continent transforms warfare. Chinese influence increases through Korean intermediaries.",
        "400": "Buddhism is officially introduced. The Yamato court adopts Chinese-style administration. Literate culture spreads among the elite.",
        "500": "The Soga clan dominates the court and promotes Buddhism. Prince Shotoku creates a constitution blending Buddhism and Confucianism. Temple-building flourishes.",
        "600": "Japanese embassies to Sui China bring back continental learning. The Taika Reforms attempt to recreate Chinese centralized government.",
        "700": "The Nara period sees the height of Chinese-style government. Buddhism becomes state-sponsored. The capital at Nara mirrors Tang Chang'an in miniature.",
        "800": "The Heian period begins with the capital moving to Kyoto. Aristocratic culture reaches refinement. Fujiwara regents dominate behind the throne.",
        "900": "The kana syllabaries are developed, enabling vernacular literature. The Tale of Genji epitomizes aristocratic culture. Imperial power becomes ceremonial.",
        "1000": "Fujiwara dominance continues. Provincial warrior families grow stronger. Buddhism develops distinctly Japanese forms. Aristocratic aesthetics flourish.",
        "1100": "The Genpei War between Taira and Minamoto clans ends Fujiwara dominance. Warrior culture rises while courtly traditions continue in Kyoto.",
        "1200": "The Kamakura shogunate creates military rule. Zen Buddhism spreads among warriors. Mongol invasions unite the country but bankrupt the shogunate.",
        "1300": "The Ashikaga shogunate establishes power in Kyoto. Zen-influenced culture flourishes. Trade with China enriches coastal regions.",
        "1400": "The Onin War devastates Kyoto, beginning the Warring States period. Daimyo compete for power. Portuguese traders arrive bringing guns.",
        "1500": "Oda Nobunaga begins unification through military force. Christianity spreads rapidly. Firearms transform warfare. Castle-building reaches new heights.",
        "1600": "Tokugawa Ieyasu completes unification. The Edo shogunate creates a stable feudal order. Christians are persecuted. Japan enters isolation.",
        "1700": "The Tokugawa peace allows urban culture to flourish. Edo becomes the world's largest city. Merchant wealth grows despite low official status.",
        "1800": "The shogunate faces financial crisis. Western ships demand trade. The Meiji Restoration overthrows the shogunate and begins rapid modernization.",
        "1900": "Japan defeats Russia, becoming the first Asian power to defeat a European nation. Industrialization proceeds rapidly. Imperial expansion into Korea and China begins."
    },

    "Korea": {
        "-3000": "Neolithic Jeulmun pottery culture develops along the coasts and rivers. Early agricultural communities practice millet farming while maintaining hunting and gathering.",
        "-2000": "Bronze Age Mumun pottery culture spreads across the peninsula. Rice agriculture arrives from China. Dolmen burials mark elite graves.",
        "-1000": "Gojoseon emerges as the first Korean kingdom in the north. Bronze technology advances. Chinese cultural influence begins but local traditions remain strong.",
        "-200": "The ancient Korean kingdoms of Gojoseon develop in Manchuria and northern Korea. Bronze Age culture flourishes. Chinese commanderies are established in the north.",
        "0": "The Three Kingdoms period begins as Goguryeo, Baekje, and Silla emerge. Chinese influence spreads through trade and conflict. Iron technology advances.",
        "100": "The Three Kingdoms consolidate power. Buddhism arrives from China. Each kingdom develops distinct characteristics while competing for dominance.",
        "300": "Goguryeo in the north becomes a major power, resisting Chinese invasions. Baekje and Silla compete in the south. Culture flourishes in all three kingdoms.",
        "400": "The Three Kingdoms reach their height. Buddhism becomes state religion. Korean culture blends Chinese influence with native traditions. Conflicts with Japan occur.",
        "500": "Goguryeo successfully defends against Sui Chinese invasions. Baekje maintains maritime power. Silla begins its rise with Tang Chinese alliance.",
        "600": "Silla conquers Baekje with Tang help, then defeats Goguryeo. The peninsula is unified for the first time. Tang influence is strong but eventually expelled.",
        "700": "The Unified Silla kingdom prospers. Buddhism dominates religious life. The capital Gyeongju rivals any East Asian city. Trade with Tang China and Japan flourishes.",
        "800": "Silla begins declining as aristocratic factionalism weakens central power. Provincial magnates grow stronger. The examination system is adopted from China.",
        "900": "The Later Three Kingdoms period sees Silla fragment. Wang Geon founds Goryeo, which will reunify the peninsula by the century's end.",
        "1000": "The Goryeo Dynasty consolidates power and moves the capital to Kaesong. Buddhism reaches its zenith. Celadon pottery achieves perfection.",
        "1100": "Goryeo faces Khitan and Jurchen invasions but survives. The Tripitaka Koreana woodblocks are carved. Military officers seize power from aristocrats.",
        "1200": "Mongol invasions devastate Korea. Goryeo becomes a Yuan tributary. The court flees to Ganghwa Island. Cultural survival continues despite foreign domination.",
        "1300": "Goryeo remains under Mongol influence. Intermarriage with Mongol royalty occurs. Neo-Confucianism begins replacing Buddhism among scholars.",
        "1400": "Yi Seong-gye founds the Joseon Dynasty. The capital moves to Seoul (Hanyang). Neo-Confucianism becomes state ideology. Hangul alphabet is created.",
        "1500": "Joseon prospers under strong kings. The examination system based on Neo-Confucianism flourishes. Japanese invasions devastate the peninsula in the 1590s.",
        "1600": "Korea recovers from Japanese invasions only to face Manchu invasions. Joseon becomes a Qing tributary but maintains autonomy and cultural pride.",
        "1700": "Joseon experiences a cultural renaissance. Practical Learning (Silhak) challenges orthodox Neo-Confucianism. Population and commerce expand.",
        "1800": "Korea maintains isolation from Western powers. Internal factional conflicts weaken the government. The 'Hermit Kingdom' faces growing external pressure.",
        "1900": "Japan forcibly opens Korea, then annexes it in 1910. Korean independence movements emerge. Modernization occurs under colonial rule."
    },

    "Central Asian Oases": {
        "-300": "The Silk Road takes shape connecting China to Central Asia. Sogdian merchants establish trading networks. Buddhism spreads from India.",
        "-200": "Han Dynasty extends control to the Tarim Basin. The oasis city-states become tributaries. Trade flourishes under Chinese protection.",
        "0": "The Kushan Empire links Central Asia to India. Buddhism spreads along trade routes. Gandhara art blends Greek and Buddhist influences.",
        "200": "The Silk Road reaches its classical height. Sogdian city-states prosper as intermediaries. Buddhism dominates religious life alongside Zoroastrianism.",
        "400": "The oasis states maintain independence from larger empires. Buddhism flourishes with magnificent cave temples. Sogdian becomes the lingua franca of trade.",
        "600": "Tang Chinese expansion brings the Tarim Basin under control. Arab armies reach the region from the west. Cultural crossroads intensifies.",
        "700": "The Battle of Talas ends Tang expansion westward. The region becomes contested between Tang China, Tibet, and the Abbasid Caliphate.",
        "800": "The Uyghur Khaganate controls the eastern oases. Buddhism and Manichaeism coexist. Chinese influence wanes as local Turkic powers rise.",
        "900": "The Uyghur kingdom in the Tarim Basin maintains prosperity. Buddhism gradually gives way to Islam from the west. Persian cultural influence grows.",
        "1000": "Islamization accelerates under Turkic dynasties. Buddhism retreats eastward. The region becomes culturally Turkic and religiously Islamic.",
        "1100": "The Qarluq and later Qara Khitai control the region. The western and eastern ends of the Silk Road grow culturally distinct.",
        "1200": "Mongol conquest devastates cities but revives trade. The Pax Mongolica allows unprecedented movement across Eurasia. Marco Polo passes through.",
        "1300": "The region fragments into Mongol successor states. Timur rises to power from Transoxiana, creating a new empire centered on Samarkand.",
        "1400": "The Timurid Empire makes Samarkand and Herat centers of Islamic culture. Persian becomes the literary language. Astronomy and mathematics flourish.",
        "1500": "Uzbek dynasties replace Timurid power. Bukhara and Samarkand remain major centers. The rise of oceanic trade routes diminishes the Silk Road's importance.",
        "1600": "The Khanates of Bukhara, Khiva, and Kokand compete. Islamic scholarship continues. The region becomes increasingly isolated from global trade.",
        "1700": "The Central Asian khanates maintain independence despite growing Russian and Qing pressure. Internal conflicts weaken resistance to outside powers.",
        "1800": "Russian expansion conquers the khanates. Qing Dynasty controls the eastern Tarim Basin. The Great Game between Britain and Russia begins.",
        "1900": "Russian rule modernizes infrastructure but faces local resistance. The region becomes part of Russian Turkestan. The Basmachi revolt against Soviet power erupts."
    },

    "Kazakh Steppes": {
        "-300": "Saka and Scythian peoples dominate the steppes. Nomadic pastoralism and horse-riding culture flourish. Trade routes cross the region.",
        "0": "The Xiongnu confederation extends influence westward. The steppe becomes a highway for cultural and genetic exchange between East and West.",
        "300": "Hun migrations westward may originate partly from these steppes. Various nomadic confederations compete for pasture and trade access.",
        "500": "Turkic tribes emerge as the dominant power. The term 'Turk' enters history. The Göktürk Khaganate rules vast steppe territories.",
        "700": "The Second Turkic Khaganate controls the region before fragmenting. Turkic peoples spread across the steppes, beginning their long dominance.",
        "800": "The Karluk confederation and other Turkic groups compete. Islamic influence begins reaching the steppes from the south.",
        "900": "Various Turkic tribes including the Oghuz migrate westward toward the Islamic world. The steppes serve as a reservoir of military manpower.",
        "1000": "The Kipchak confederation dominates the western steppes. Gradually, the ancestors of modern Kazakhs form from Turkic tribal mixing.",
        "1200": "Mongol conquest under Genghis Khan's sons incorporates the steppes into Mongol successor states. The Golden Horde rules the western portion.",
        "1300": "The Golden Horde fragments. Turkic-Mongol mixing creates new identities. The Uzbek confederation rises in the eastern steppes.",
        "1400": "The Kazakh Khanate emerges from the split in the Uzbek confederation. The name 'Kazakh' appears, meaning 'free warrior' or 'breakaway.'",
        "1500": "The Kazakh Khanate consolidates with three main hordes (jüz). Nomadic pastoralism continues as the economic base. Islam becomes universal.",
        "1600": "Kazakhs compete with Oirat Mongols for pasture. Internal divisions between the three hordes create instability. Trade routes remain important.",
        "1700": "Dzungar Mongol invasions devastate Kazakh tribes. The hordes seek Russian protection, beginning the process of Russian incorporation.",
        "1800": "Russian rule gradually extends over the steppes. Traditional nomadic life continues but under colonial administration. Revolts are suppressed.",
        "1900": "Russian colonization intensifies. Kazakhs face land confiscation for Slavic settlers. The 1916 revolt against Russian rule is brutally crushed."
    },

    "Siberia": {
        "0": "Various Paleo-Siberian peoples inhabit this vast, sparsely populated region. Reindeer herding, hunting, and fishing sustain small communities.",
        "500": "Turkic tribes begin expanding into southern Siberia. Indigenous peoples maintain their traditional lifestyles in the forests and tundra.",
        "800": "The Kyrgyz briefly dominate the Yenisei region after defeating the Uyghurs. Turkic cultures spread northward.",
        "1000": "Various Tungusic, Turkic, and Paleo-Siberian peoples coexist. Shamanic traditions dominate spiritual life. Trading networks connect communities.",
        "1200": "Mongol expansion brings Siberia nominally under Mongol control, though direct rule is limited. Tribute systems connect Siberia to the Mongol states.",
        "1400": "The Siberian Khanate emerges as a successor state to the Golden Horde. Most of Siberia remains under indigenous peoples' control.",
        "1500": "The Khanate of Sibir controls western Siberia. Russian Cossacks begin exploring beyond the Urals. First contacts occur.",
        "1600": "Russian conquest of the Siberian Khanate opens the region. Cossacks rapidly push eastward, reaching the Pacific. The fur trade drives expansion.",
        "1700": "Russian rule extends across Siberia. Indigenous peoples are incorporated through tribute systems. Mining and fur trading create frontier settlements.",
        "1800": "Siberia becomes Russia's penal colony. Gold discoveries attract settlers. The Trans-Siberian Railway construction begins, transforming connectivity.",
        "1900": "The Trans-Siberian Railway enables mass settlement. The Russian Civil War sees fighting across Siberia. Soviet rule brings forced collectivization and Gulag camps."
    }
};
