/** Eleven-pixel glyphs for the powers people address. One shared set, matched
 * by what a power is for, because two thousand of them cannot each have art.
 * `.` contour, `o` body, `O` highlight, space empty. */
export const coreGlyphs: Record<string, string[]> = {
  sun: [
    "     .     ",
    "  .  o  .  ",
    "   .ooo.   ",
    "  ooOOOoo  ",
    " .oOOOOOo. ",
    ".o OOOOO o.",
    " .oOOOOOo. ",
    "  ooOOOoo  ",
    "   .ooo.   ",
    "  .  o  .  ",
    "     .     ",
  ],
  moon: [
    "    ..     ",
    "  ..oo..   ",
    " .ooo  ..  ",
    ".oooO   .. ",
    ".oooOO   . ",
    ".oooOO   . ",
    ".oooO   .. ",
    " .ooo  ..  ",
    "  ..oo..   ",
    "    ..     ",
    "           ",
  ],
  star: [
    "     .     ",
    "     o     ",
    "    .O.    ",
    "    oOo    ",
    ".oo.OOO.oo.",
    " .ooOOOoo. ",
    "    oOo    ",
    "   .oOo.   ",
    "   o. .o   ",
    "  .     .  ",
    "           ",
  ],
  sky: [
    "     .     ",
    "  .. o ..  ",
    "    ...    ",
    "  ..ooo..  ",
    " .oOOOOOo. ",
    ".oOOOOOOOo.",
    ".ooooooooo.",
    " ......... ",
    "           ",
    " ......... ",
    " .ooooooo. ",
  ],
  storm: [
    "  ....     ",
    " .oOOo...  ",
    ".oOOOOOOo. ",
    " .ooooooo. ",
    "   ..O..   ",
    "    OO.    ",
    "   .OO     ",
    "  .OOOO.   ",
    "    OO.    ",
    "   .O      ",
    "   .       ",
  ],
  rain: [
    "  ....     ",
    " .oOOo...  ",
    ".oOOOOOOo. ",
    " .ooooooo. ",
    "  .  .  .  ",
    "  o  o  o  ",
    "  o  o  o  ",
    "  .  .  .  ",
    " o  o  o   ",
    " o  o  o   ",
    " .  .  .   ",
  ],
  wind: [
    "           ",
    "  ......   ",
    " .oooooo.  ",
    ".o     .o. ",
    "      .oo  ",
    "  ........ ",
    " .oooooooo.",
    ".o      .o.",
    "   .oooo.  ",
    "  .oooooo. ",
    "           ",
  ],
  mountain: [
    "           ",
    "     .     ",
    "    .O.    ",
    "   .OOo.   ",
    "  .oOOoo.  ",
    " .ooooooo. ",
    " .oo.  .o. ",
    ".ooo. .. o.",
    ".oo. .oOo .",
    ".o. .ooooo.",
    "...........",
  ],
  cave: [
    "...........",
    ".ooooooooo.",
    ".oo.....oo.",
    ".o.     .o.",
    ".o.  .  .o.",
    ".o. ... .o.",
    ".o.......o.",
    ".o.......o.",
    ".o.......o.",
    ".o.......o.",
    "...........",
  ],
  earth: [
    "           ",
    "           ",
    "  .......  ",
    " .ooooooo. ",
    ".oOOOOOOOo.",
    ".ooooooooo.",
    ".o.o.o.o.o.",
    ".ooooooooo.",
    ".o.o.o.o.o.",
    " .ooooooo. ",
    "  .......  ",
  ],
  river: [
    "           ",
    "  ...      ",
    " .ooo..    ",
    " .oOOoo..  ",
    "  .oOOoo.. ",
    "   .oOOoo. ",
    "  ..ooOOo. ",
    " .oo..oOo. ",
    " .oOoo.oo. ",
    "  .oOo..o. ",
    "   ...  .. ",
  ],
  sea: [
    "           ",
    "           ",
    "  ..   ..  ",
    " .oo. .oo. ",
    ".oOOo.oOOo.",
    "..oo...oo..",
    "  ..   ..  ",
    " ..   ..   ",
    ".oo. .oo.  ",
    ".oOo.oOOo. ",
    "..o...oo.. ",
  ],
  spring: [
    "    ...    ",
    "   .oOo.   ",
    "    .o.    ",
    "  .......  ",
    " .ooooooo. ",
    " .o.....o. ",
    " .o.ooo.o. ",
    " .o.oOo.o. ",
    " .o.ooo.o. ",
    " .ooooooo. ",
    "  .......  ",
  ],
  fire: [
    "     .     ",
    "    .O.    ",
    "   .OOo.   ",
    "  .OOOOo.  ",
    " .OOOOOOo. ",
    " .oOOOOoo. ",
    " .ooOOooo. ",
    "  .ooooo.  ",
    "   .....   ",
    " ......... ",
    " .ooooooo. ",
  ],
  tree: [
    "    ...    ",
    "  ..ooo..  ",
    " .oOOOOOo. ",
    ".oOOOOOOOo.",
    ".oOOOOOOOo.",
    " .oOOOOOo. ",
    "  ..ooo..  ",
    "    .o.    ",
    "    .o.    ",
    "   .ooo.   ",
    "  .......  ",
  ],
  grain: [
    "     .     ",
    "    .O.    ",
    "   .oOo.   ",
    "  .O.o.O.  ",
    "  .oOoOo.  ",
    " .O.oOo.O. ",
    " .oOoOoOo. ",
    "  .. o ..  ",
    "    .o.    ",
    "    .o.    ",
    "   .....   ",
  ],
  flower: [
    "    ...    ",
    "  ..oOo..  ",
    " .oOo.oOo. ",
    " .oO.O.Oo. ",
    "  .o.O.o.  ",
    " .oO.O.Oo. ",
    " .oOo.oOo. ",
    "  ..oOo..  ",
    "    .o.    ",
    "   .oo.    ",
    "    ..     ",
  ],
  cattle: [
    "           ",
    " ..     .. ",
    ".oo.   .oo.",
    ".oOo...oOo.",
    " .ooooooo. ",
    " .oOoooOo. ",
    " .ooooooo. ",
    "  .o...o.  ",
    "  .oooo o. ",
    "   .ooo.   ",
    "    ...    ",
  ],
  horse: [
    "       ..  ",
    "      .oo. ",
    "   ....oOo.",
    "  .oooooo. ",
    " .oOOOoo.  ",
    ".oOOOOo.   ",
    ".oOOOOOo.  ",
    ".oooooooo. ",
    ".o. .o..o. ",
    ".o. .o. o. ",
    "...  ..  . ",
  ],
  bird: [
    "        .. ",
    "   .....oo.",
    " ..ooooooo.",
    ".oOOOOOoo. ",
    ".oOOOOo..  ",
    " .oooo.    ",
    "  .oo.     ",
    "   ..      ",
    "           ",
    "           ",
    "           ",
  ],
  fish: [
    "           ",
    "        .. ",
    "  .....  o.",
    " .ooooo..o.",
    ".oOOoooo.o.",
    ".oOOOOooooo",
    ".oOoooooo.o",
    " .ooooo..o.",
    "  .....  o.",
    "        .. ",
    "           ",
  ],
  snake: [
    "  .....    ",
    " .ooooo..  ",
    ".oOo.oOOo. ",
    ".oo.  .oo. ",
    " ..   .oo. ",
    "     .oo.  ",
    "   ..oo.   ",
    "  .ooo.    ",
    " .ooo...   ",
    " .ooooooo. ",
    "  ........ ",
  ],
  hunt: [
    "   ..      ",
    "  .oO.     ",
    " .oO.      ",
    " .oo.    . ",
    ".oo.   ..O.",
    ".oo.oooooOO",
    ".oo.   ..O.",
    " .oo.    . ",
    " .oO.      ",
    "  .oO.     ",
    "   ..      ",
  ],
  house: [
    "     .     ",
    "    .O.    ",
    "   .OOO.   ",
    "  .OOOOO.  ",
    " .OOOOOOO. ",
    ".ooooooooo.",
    ".o.......o.",
    ".o..ooo..o.",
    ".o..oOo..o.",
    ".o..ooo..o.",
    "...........",
  ],
  shrine: [
    "    ...    ",
    "   .oOo.   ",
    "  ..ooo..  ",
    " .ooooooo. ",
    ".ooooooooo.",
    " .o.....o. ",
    " .o.ooo.o. ",
    " .o.oOo.o. ",
    " .o.oOo.o. ",
    " .o.ooo.o. ",
    " ......... ",
  ],
  tomb: [
    "    ...    ",
    "  ..ooo..  ",
    " .ooooooo. ",
    " .oOoooOo. ",
    " .ooooooo. ",
    " .o.....o. ",
    " .o.ooo.o. ",
    " .o.....o. ",
    " .ooooooo. ",
    "...........",
    ".ooooooooo.",
  ],
  ancestors: [
    "    ...    ",
    "    .O.    ",
    " .. .Oo. ..",
    ".o. .Oo. .o",
    ".O. .Oo. .O",
    ".o. .oo. .o",
    ".o. .oo. .o",
    ".o. .oo. .o",
    ".o. .oo. .o",
    "...........",
    ".ooooooooo.",
  ],
  crossroads: [
    "    ...    ",
    "   .oOo.   ",
    "   .ooo.   ",
    "....ooo....",
    ".oooooooooo",
    ".oOOOOOOOOo",
    ".oooooooooo",
    "....ooo....",
    "   .ooo.   ",
    "   .ooo.   ",
    "   .....   ",
  ],
  boat: [
    "     .     ",
    "    .oo.   ",
    "    .oOo.  ",
    "    .oOOo. ",
    "    .oOOOo.",
    "    .o.....",
    "...........",
    ".ooooooooo.",
    " .ooooooo. ",
    "  .......  ",
    "  ..  ..   ",
  ],
  pot: [
    "   .....   ",
    "  .ooooo.  ",
    "  ..ooo..  ",
    " .ooooooo. ",
    ".oOOooooOo.",
    ".oOoooooOo.",
    ".oOoooooOo.",
    ".ooooooooo.",
    " .ooooooo. ",
    "  .oooo.   ",
    "   .....   ",
  ],
  loom: [
    "...........",
    ".ooooooooo.",
    ".o.o.o.o.o.",
    ".ooooooooo.",
    ".o.o.o.o.o.",
    ".ooooooooo.",
    ".o.o.o.o.o.",
    ".ooooooooo.",
    ".o.o.o.o.o.",
    ".ooooooooo.",
    "...........",
  ],
  hammer: [
    "  .......  ",
    " .ooooooo. ",
    ".oOOOOOOOo.",
    ".ooooooooo.",
    " ...ooo... ",
    "   .ooo.   ",
    "   .oOo.   ",
    "   .oOo.   ",
    "   .oOo.   ",
    "   .ooo.   ",
    "   .....   ",
  ],
  scroll: [
    "  .......  ",
    " .ooooooo. ",
    ".oOoooooOo.",
    ".oOoooooOo.",
    ".oOo...oOo.",
    ".oOo...oOo.",
    ".oOo...oOo.",
    ".oOoooooOo.",
    ".oOoooooOo.",
    " .ooooooo. ",
    "  .......  ",
  ],
  scales: [
    "     .     ",
    "    .O.    ",
    "...........",
    ".o.  o  .o.",
    ".o.  o  .o.",
    ".o.  o  .o.",
    ".ooo o ooo.",
    " ...  ...  ",
    "    .o.    ",
    "   .ooo.   ",
    "  .......  ",
  ],
  spear: [
    "     .     ",
    "    .O.    ",
    "   .oOo.   ",
    "   .oOo.   ",
    "    .o.    ",
    "    .o.    ",
    "   ..o..   ",
    "    .o.    ",
    "    .o.    ",
    "    .o.    ",
    "    ...    ",
  ],
  mask: [
    "  .......  ",
    " .ooooooo. ",
    ".ooooooooo.",
    ".o.oo.oo.o.",
    ".o.....  o.",
    ".ooo.ooooo.",
    ".oo..o..oo.",
    " .o.....o. ",
    " .ooooooo. ",
    "  .ooooo.  ",
    "   .....   ",
  ],
  eye: [
    "           ",
    "   .....   ",
    " ..ooooo.. ",
    ".oooooooooo",
    ".oo.ooo.ooo",
    ".oo.oOo.ooo",
    ".oo.ooo.ooo",
    ".oooooooooo",
    " ..ooooo.. ",
    "   .....   ",
    "           ",
  ],
  hand: [
    "   .. ..   ",
    "  .oo.oo.  ",
    " ..oo.oo.. ",
    ".oooo.oooo.",
    ".oOooooooo.",
    ".oOooooooo.",
    ".oOooooooo.",
    " .ooooooo. ",
    "  .ooooo.  ",
    "   .ooo.   ",
    "   .....   ",
  ],
  cross: [
    "    ...    ",
    "   .oOo.   ",
    "   .oOo.   ",
    "...........",
    ".ooooOoooo.",
    ".oOOOOOOOo.",
    "...........",
    "   .oOo.   ",
    "   .oOo.   ",
    "   .oOo.   ",
    "   .....   ",
  ],
  crescent: [
    "    ...    ",
    "  ..ooo..  ",
    " .ooo...   ",
    ".ooo.      ",
    ".ooo.   .  ",
    ".ooo.  .O. ",
    ".ooo.   .  ",
    ".ooo.      ",
    " .ooo...   ",
    "  ..ooo..  ",
    "    ...    ",
  ],
  wheel: [
    "   .....   ",
    " ..ooooo.. ",
    ".oo..o..oo.",
    ".o.  o  .o.",
    ".o...o...o.",
    ".oooooooooo",
    ".o...o...o.",
    ".o.  o  .o.",
    ".oo..o..oo.",
    " ..ooooo.. ",
    "   .....   ",
  ],
  lotus: [
    "     .     ",
    "  .  o  .  ",
    " .o..O..o. ",
    " .ooOOOoo. ",
    ".ooOOOOOoo.",
    ".oOOOOOOOo.",
    " .ooooooo. ",
    "  .......  ",
    "   .ooo.   ",
    "  .ooooo.  ",
    "   .....   ",
  ],
  book: [
    "  .......  ",
    " .oo.o.oo. ",
    ".oOo.o.oOo.",
    ".oOo.o.oOo.",
    ".oOo.o.oOo.",
    ".oOo.o.oOo.",
    ".oOo.o.oOo.",
    ".oOo.o.oOo.",
    " .oo.o.oo. ",
    "  .......  ",
    "           ",
  ],
};
