/** Household glyphs: the things families own, work with, and sometimes address. */
export const householdGlyphs: Record<string, string[]> = {
  threshold: [
    "   .....   ",
    "  .ooooo.  ",
    " .oOoooOo. ",
    " .ooooooo. ",
    " .o     o. ",
    " .o     o. ",
    " .o     o. ",
    " .o     o. ",
    " .ooooooo. ",
    "  .ooooo.  ",
    "   .....   ",
  ],
  bed: [
    "  .......  ",
    " .ooooooo. ",
    ".oOoooooOo.",
    ".ooooooooo.",
    ".o.     .o.",
    ".o.     .o.",
    ".o.     .o.",
    ".ooooooooo.",
    " .ooooooo. ",
    "  .ooooo.  ",
    "   .....   ",
  ],
  cradle: [
    "   .....   ",
    "  .oOooo.  ",
    " .oOoOoOo. ",
    ".oOoOoOoOo.",
    ".oOoOoOoOo.",
    ".oOoOoOoOo.",
    " .ooooooo. ",
    "  .ooooo.  ",
    "   .ooo.   ",
    "   .....   ",
    "           ",
  ],
  granary: [
    "   .....   ",
    "  .ooooo.  ",
    " .oOoooOo. ",
    ".oOoooooOo.",
    ".ooooooooo.",
    ".o.     o. ",
    ".o.ooo .o. ",
    ".o.oOo..o. ",
    ".ooooooooo.",
    " .ooooooo. ",
    "   .....   ",
  ],
  plough: [
    "        .. ",
    "       .oO.",
    "      .oO. ",
    "     .oO.  ",
    "    .oo.   ",
    "   .oo.    ",
    "  .oOo.    ",
    " .oOOoo.   ",
    ".oOOooo.   ",
    "..ooo..    ",
    "...........",
  ],
  sickle: [
    "       .   ",
    "      .O.  ",
    "     .Oo.  ",
    "    .Oo.   ",
    "   .Oo.    ",
    "  .Oo....  ",
    " .ooo.     ",
    "  .oo.     ",
    "   .o.     ",
    "   ...     ",
    "           ",
  ],
  net: [
    " .......   ",
    " .o.o.o.   ",
    " .......   ",
    " .o.o.o.   ",
    " .......   ",
    " .o.o.o.   ",
    " .......   ",
    " .o.o.o.   ",
    " .......   ",
    " .o.o.o.   ",
    " .......   ",
  ],
  canoe: [
    "    ...    ",
    "   .oOo.   ",
    "  .oOoOo.  ",
    " .oOoOoOo. ",
    ".oOoOoOoOo.",
    " .ooooooo. ",
    "  .......  ",
    "           ",
    "           ",
    "           ",
    "           ",
  ],
  anvil: [
    "           ",
    "  .......  ",
    " .ooooooo. ",
    ".oOOOOOOo. ",
    ".ooooooooo.",
    ".oo.oooo.o.",
    ".oo.oo.oOo.",
    " .o.oo.ooo.",
    " .o...ooo. ",
    "  .....o.  ",
    "       .   ",
  ],
  kiln: [
    "    ...    ",
    "  ..ooo..  ",
    " .oOoooOo. ",
    ".oOoooooOo.",
    ".ooooooooo.",
    ".o.     o. ",
    ".o.ooooo.o.",
    ".o.oOoOo.o.",
    ".o.......o.",
    "...........",
    "           ",
  ],
  basket: [
    "   .....   ",
    "  .ooooo.  ",
    " .oOoooOo. ",
    ".ooooooooo.",
    ".o.o.o.o.o.",
    ".ooooooooo.",
    ".o.o.o.o.o.",
    ".ooooooooo.",
    " .ooooooo. ",
    "  .ooooo.  ",
    "   .....   ",
  ],
  cloth: [
    "   .....   ",
    "  .ooooo.  ",
    " .oOoooOo. ",
    " .oOoooOo. ",
    ".ooooooooo.",
    ".ooooooooo.",
    " .oOoooOo. ",
    " .oOoooOo. ",
    " .oOoooOo. ",
    "  .ooooo.  ",
    "   .....   ",
  ],
  needle: [
    "        .  ",
    "       .O. ",
    "      .Oo. ",
    "     .Oo.  ",
    "    .Oo.   ",
    "   .Oo.    ",
    "  .Oo.     ",
    " .Oo.      ",
    ".oo.       ",
    ".o.        ",
    "..         ",
  ],
  mortar: [
    "   .....   ",
    "  .ooooo.  ",
    " .oOoooOo. ",
    ".oOoooooOo.",
    ".ooooooooo.",
    ".ooooooooo.",
    " .ooo.ooo. ",
    "  .oOOOo.  ",
    "  .oOOOo.  ",
    "   .ooo.   ",
    "   .....   ",
  ],
  knife: [
    "        .  ",
    "       .O. ",
    "      .OOo.",
    "     .OOOo.",
    "    .OOOOo.",
    "   .OOOOOo.",
    "  .OOOOOOo.",
    "   .oooooo.",
    "    .ooo.  ",
    "     ...   ",
    "           ",
  ],
  lamp: [
    "   .....   ",
    "  .ooooo.  ",
    " .oOoooOo. ",
    ".oOoooooOo.",
    ".ooooooooo.",
    ".o.......o.",
    ".o.oOoOo.o.",
    ".o.......o.",
    " .ooooooo. ",
    "  .ooooo.  ",
    "   .....   ",
  ],
  candle: [
    "    ...    ",
    "   .oOo.   ",
    "   .oOo.   ",
    "   .oOo.   ",
    "   .oOo.   ",
    "   .oOo.   ",
    "   .ooo.   ",
    "  .ooooo.  ",
    "  .ooooo.  ",
    "   .ooo.   ",
    "   .....   ",
  ],
  mirror: [
    "   .....   ",
    "  .ooooo.  ",
    " .oOoooOo. ",
    ".oOoOoOoOo.",
    ".oOoOoOoOo.",
    ".oOoOoOoOo.",
    ".oOoOoOoOo.",
    ".oOoOoOoOo.",
    " .oOoooOo. ",
    "  .ooooo.  ",
    "   .....   ",
  ],
  drum: [
    "   .....   ",
    "  .ooooo.  ",
    " .oOoooOo. ",
    ".oOoooooOo.",
    ".ooooooooo.",
    ".o.......o.",
    ".o.ooooo.o.",
    ".o.ooooo.o.",
    ".ooooooooo.",
    " .ooooooo. ",
    "   .....   ",
  ],
  flute: [
    "        .  ",
    "       .O. ",
    "      .Oo. ",
    "     .Oo.  ",
    "    .OO.   ",
    "   .oOo.   ",
    "  .oOoOo.  ",
    " .ooOOooo. ",
    ".oooOooooo.",
    ".ooooooooo.",
    " .ooooooo. ",
  ],
  bell: [
    "    ...    ",
    "   .oOo.   ",
    "  .oOoOo.  ",
    " .oOoOoOo. ",
    ".oOoOoOoOo.",
    ".ooooooooo.",
    ".o.......o.",
    ".o.ooooo.o.",
    ".ooooooooo.",
    " .ooooooo. ",
    "   .....   ",
  ],
  comb: [
    " .......   ",
    " .ooooo.   ",
    " .oOooo.   ",
    " .ooooo.   ",
    " .oo.oo.   ",
    " .oo.oo.   ",
    " .oo.oo.   ",
    " .oo.oo.   ",
    " .oo.oo.   ",
    " .oo.oo.   ",
    " .......   ",
  ],
  key: [
    "           ",
    "  .......  ",
    " .ooooooo. ",
    ".oOOOOOOOo.",
    ".oooooo.oo.",
    " .ooooo.oo.",
    "    .....o.",
    "    .oOooo.",
    "    .ooooo.",
    "     .ooo. ",
    "      ...  ",
  ],
  rope: [
    "   .ooo.   ",
    "   .oOo.   ",
    "  .oOoOo.  ",
    "  .oOoOo.  ",
    " .oOoOoOo. ",
    " .oOoOoOo. ",
    ".oOoOoOoOo.",
    ".oOoOoOoOo.",
    ".ooooooooo.",
    " .ooooooo. ",
    "  .......  ",
  ],
};
