/** Eleven-pixel glyphs for the crops and creatures people tend. */
export const livingGlyphs: Record<string, string[]> = {
  maize: [
    "     .     ",
    "    .o.    ",
    "   .oOo.   ",
    "  ..ooo..  ",
    "  .oOoOo.  ",
    "  .ooooo.  ",
    "  .oOoOo.  ",
    "   .ooo.   ",
    "   .oOo.   ",
    "    .o.    ",
    "    ...    ",
  ],
  rice: [
    "    .O.    ",
    "   .oOo.   ",
    "   .ooo.   ",
    "  .o...o.  ",
    "  .o. .o.  ",
    " .oo. .oo. ",
    " .ooo.ooo. ",
    "  .ooooo.  ",
    "  .o...o.  ",
    "   .ooo.   ",
    "   .....   ",
  ],
  olive: [
    "    ...    ",
    "  ..ooo..  ",
    " .oOOOOOo. ",
    ".oOOoOOOOo.",
    ".oOoooooOo.",
    ".oOoooooOo.",
    ".oOOoOOOOo.",
    " .oOOOOOo. ",
    "  ..ooo..  ",
    "    .o.    ",
    "    ...    ",
  ],
  vine: [
    "   .....   ",
    " ..oOo..   ",
    ".ooooo..   ",
    ".ooo.   .  ",
    ".ooo. ..o. ",
    ".ooo..oOo. ",
    ".ooo.ooo.  ",
    " .ooooo.   ",
    "  .oOo.    ",
    "   .oo.    ",
    "    ..     ",
  ],
  palm: [
    "     .     ",
    "    .O.    ",
    "   .oOo.   ",
    "   .ooo.   ",
    "   .ooo.   ",
    "  ..ooo..  ",
    " .oooOooo. ",
    " .ooooooo. ",
    "  .ooooo.  ",
    "    .o.    ",
    "    ...    ",
  ],
  gourd: [
    "   .....   ",
    "  .ooooo.  ",
    " .oOOOOOo. ",
    ".oOOOOOOOo.",
    ".oOOoooOOo.",
    ".oOoooooOo.",
    " .oOOoOOo. ",
    " .oOOOOOo. ",
    "  .ooooo.  ",
    "   .ooo.   ",
    "    ...    ",
  ],
  root: [
    "    ...    ",
    "   .oOo.   ",
    "  .ooooo.  ",
    " .ooooooo. ",
    " .oOoooOo. ",
    ".oo .oo .o.",
    ".o.  .o  o.",
    ".o   .o  o.",
    ".  . .  .  ",
    " .     .   ",
    "           ",
  ],
  bee: [
    "       ..  ",
    "      .oo. ",
    "    ..oOo. ",
    "   .ooooo. ",
    "  .oOOOOo. ",
    " .oo o oo. ",
    " .oOo . o. ",
    "  .ooo o.  ",
    "   ..oo..  ",
    "    .. ..  ",
    "           ",
  ],
  sheep: [
    "  ..       ",
    " .ooo.     ",
    ".oOOOo.    ",
    ".ooooo..   ",
    ".oo.oo.o.  ",
    ".o. o..oo. ",
    ".o. .oo.o. ",
    " .o.ooo.o. ",
    " .o.ooo.o. ",
    "  .o.o.o.  ",
    "  .. ...   ",
  ],
  goat: [
    "   ..      ",
    "  .oo.     ",
    " .oOo..    ",
    ".ooo...    ",
    ".oo.oo...  ",
    ".o. .o..o. ",
    ".o. .oo.o. ",
    " .o.oo..o. ",
    "  .oo. .o. ",
    "   .o. .o. ",
    "   .. .oo. ",
  ],
  pig: [
    "      ..   ",
    "    ..oo.  ",
    "   .ooooo. ",
    "  .oOOOOo. ",
    "  .o.oo.o. ",
    ".oo.oo.oo. ",
    ".o.  .o  o.",
    ".o.  .oo.o.",
    " .o .o.o.o.",
    " .o.o.o.o. ",
    "  .....  . ",
  ],
  dog: [
    "       ..  ",
    "      .oo. ",
    "    ..oOo. ",
    "   .ooooo. ",
    "  .oOOOoo. ",
    " .oOOOo.   ",
    ".oOOOOo.   ",
    ".oooooo..  ",
    ".o..o..o.  ",
    ".o..o. .o. ",
    "...  ..... ",
  ],
  camel: [
    "       .   ",
    "      .O.  ",
    "     .oOo. ",
    "    .ooooo.",
    "   .o.oooo.",
    "  .oo.oOOo.",
    " .ooo.oooo.",
    ".ooooooooo.",
    ".o.  .o.o. ",
    ".o. .o...o.",
    "...  ..    ",
  ],
  elephant: [
    "      ..   ",
    "     .oo.  ",
    "    .oOo.  ",
    "   .ooooo. ",
    "  .oOOooo. ",
    " .oOOooooo.",
    ".oOOo.oooo.",
    ".oo.o.oooo.",
    ".o..o.oo.o.",
    ".o .oo oooo",
    ".. ........",
  ],
  jaguar: [
    "      ..   ",
    "     .oo.  ",
    "    .oOOo. ",
    "   .oOOOo. ",
    "  .oOOOOOo.",
    " .oOOooooo.",
    ".oOoooo.oo.",
    ".ooooo...o.",
    ".o..oo.oo. ",
    ".o. .ooo.  ",
    "..  ....   ",
  ],
  bear: [
    "   ..  ..  ",
    "  .oo..oo. ",
    " .oOo.oOo. ",
    ".oOOo.oOOo.",
    ".oOOOoOOOo.",
    " .oOOOOOo. ",
    " .ooooooo. ",
    "  .o...o.  ",
    "  .oooooo. ",
    "   .oooo.  ",
    "   .....   ",
  ],
  wolf: [
    "       ..  ",
    "      .oo. ",
    "   ...oOo. ",
    "  .oooooo. ",
    " .oOOOoo.  ",
    ".oOOOOo.   ",
    ".oOOOOOo.  ",
    ".oooooooo. ",
    ".o. .o..o. ",
    ".o. .o. o. ",
    "...  ..  . ",
  ],
  eagle: [
    "  ..   ..  ",
    " .oo. .oo. ",
    ".oOOo.oOOo.",
    ".oOOoooOOo.",
    " .oOo.oOo. ",
    "  ..o.o..  ",
    "   .ooo.   ",
    "   .oOo..  ",
    "   .ooo.o. ",
    "   .o.o..  ",
    "   ...     ",
  ],
  owl: [
    "   .....   ",
    " ..ooooo.. ",
    ".ooO.O.ooo.",
    ".oooOOOooo.",
    ".oooOOOooo.",
    ".ooO.O.ooo.",
    ".ooooooooo.",
    " .ooooooo. ",
    "  .ooooo.  ",
    "  .ooooo.  ",
    "   .....   ",
  ],
  raven: [
    "  .......  ",
    " .ooooooo. ",
    ".oOOOOOOo. ",
    ".oOOOOOo.  ",
    ".ooooo.    ",
    " .oooo.    ",
    " .oooo.    ",
    "  .oo.     ",
    "  .oo.     ",
    "   ..      ",
    "           ",
  ],
  turtle: [
    "    ...    ",
    "  ..ooo..  ",
    " .oOOOOOo. ",
    ".oOOOOOOOo.",
    ".oOoOoOoOo.",
    ".ooooooooo.",
    " .ooooooo. ",
    "  .o...o.  ",
    "  .o...o.  ",
    "   .o.o.   ",
    "   .....   ",
  ],
  scorpion: [
    "       .   ",
    "      .O.  ",
    "     .oOo. ",
    "    .ooooo.",
    "   .oOOOo. ",
    "  .oOoooOo.",
    " .oo o ooo.",
    ".oo.o.o.o. ",
    ".o.  .o...o",
    "..   ..    ",
    "           ",
  ],
  shell: [
    "   .....   ",
    "  .ooooo.  ",
    " .oOOOOOo. ",
    ".oOOOOOOOo.",
    ".oOo.oooOo.",
    ".oOo.oOoOo.",
    ".oOo.oOoOo.",
    " .oOoooOo. ",
    "  .ooooo.  ",
    "   .ooo.   ",
    "    ...    ",
  ],
  deer: [
    "   ..   .. ",
    "  .oo. .oo.",
    " .oOo.oOOo.",
    ".ooo..oOOo.",
    ".oo.oo.ooo.",
    ".o. oOo.o. ",
    ".o. ooo.o. ",
    " .o.oo..o. ",
    " .o.oo..o. ",
    "  .o....o. ",
    "   .....   ",
  ],
};
