/** Eleven-pixel glyphs for people and the human body: figure, kinship,
 * condition, and the thread of a life. `.` contour, `o` body, `O` highlight,
 * space empty. */
export const personGlyphs: Record<string, string[]> = {
  figure: [
    "     .     ",
    "    .O.    ",
    "   .ooo.   ",
    "   .oOo.   ",
    "    .o.    ",
    "   .ooo.   ",
    "   .oOo.   ",
    "    .o.    ",
    "   .o.o.   ",
    "   .o. o.  ",
    "    .   .  ",
  ],
  "mother-and-child": [
    "   ..      ",
    "  .oO.     ",
    " .ooo.     ",
    " .oOo.     ",
    " ..o.....  ",
    "   .o.ooo. ",
    "   ...oOo. ",
    "    .ooo.  ",
    "    .o. o. ",
    "    .    . ",
    "           ",
  ],
  elder: [
    "    ...    ",
    "   .oOo.   ",
    "  .ooooo.  ",
    "  .oOoOo.  ",
    "   .ooo.   ",
    "  .o...o.  ",
    "  .ooooo.  ",
    "   .oOo.   ",
    "   .o.o.   ",
    "   .o   o. ",
    "    .   .  ",
  ],
  twins: [
    "  ..   ..  ",
    " .oO. .oO. ",
    ".ooo..ooo. ",
    ".oOo..oOo. ",
    " .o.  .o.  ",
    ".ooo..ooo. ",
    ".oOo..oOo. ",
    " .o.  .o.  ",
    " .o.o.o.o. ",
    " .o.  .o.  ",
    "  .    .   ",
  ],
  crowd: [
    "           ",
    "  ..   ..  ",
    " .oO. .oO. ",
    " .oo. .oo. ",
    ".....o.....",
    ".oo.ooo.oo.",
    "ooo.ooo.ooo",
    "  ..   ..  ",
    " .oO....oO.",
    ".ooo.oo.ooo",
    "ooooooooooo",
  ],
  footprint: [
    "           ",
    "           ",
    "    ...    ",
    "   .ooo.   ",
    "   .oOo.   ",
    "   .ooo.   ",
    "  .o...o.  ",
    "  .o.O.o.  ",
    "  .ooooo.  ",
    "  .o...o.  ",
    "   .....   ",
  ],
  heart: [
    "           ",
    " ..  O  .. ",
    ".ooO.OO.oo.",
    ".oOoOoOoOo.",
    ".oOoOoOoOo.",
    ".oOoOoOoOo.",
    " .oOoOoOo. ",
    " .oOoOoOo. ",
    "  .oOoOo.  ",
    "   .oOo.   ",
    "    ...    ",
  ],
  breath: [
    "           ",
    "           ",
    "     o     ",
    "    oOo    ",
    "   oOOOo   ",
    "  .oOOOo.  ",
    "   .oOo.   ",
    "    .o.    ",
    "     .     ",
    "           ",
    "           ",
  ],
  sleep: [
    "    ...    ",
    "   .oOo.   ",
    "  .o...o.  ",
    "  .o.O.o.  ",
    "  .ooooo.  ",
    "   .ooo.   ",
    "   .ooo.   ",
    "    ...    ",
    "  ..   ..  ",
    " .oO. .oO. ",
    ".ooo..ooo. ",
  ],
  dream: [
    "           ",
    "  .........",
    " .ooooooo. ",
    ".oOOOOOOOo.",
    ".ooooooooo.",
    ".ooooooooo.",
    ".oo     oo.",
    ".oo.o.o.oo.",
    ".oo.ooo.oo.",
    ".ooooooooo.",
    " ......... ",
  ],
  plague: [
    "           ",
    "    ...    ",
    "   .oOo.   ",
    "  .oOOOo.  ",
    "  .oOOOo.  ",
    " .oOOOOOo. ",
    " .o.oOo.o. ",
    " .oOoOoOo. ",
    "  .oOoOo.  ",
    "   .ooo.   ",
    "    ...    ",
  ],
  wound: [
    "           ",
    "           ",
    "    .O.    ",
    "   .OOO.   ",
    "  .OOOOO.  ",
    "  .oOOOo.  ",
    "  .oOOOo.  ",
    "   .ooo.   ",
    "    ...    ",
    "           ",
    "           ",
  ],
  birth: [
    "     .     ",
    "    .O.    ",
    "   .oOo.   ",
    "   .o...   ",
    "   .oO.    ",
    "   .ooo.   ",
    "    .o.    ",
    "   .ooo.   ",
    "   .oOo.   ",
    "    .o.    ",
    "    ...    ",
  ],
  seed: [
    "           ",
    "    ...    ",
    "   .ooo.   ",
    "  .oOOOo.  ",
    "  .oOOOo.  ",
    "  .oOOOo.  ",
    "  .ooooo.  ",
    "   .ooo.   ",
    "   .oOo.   ",
    "    .o.    ",
    "    .      ",
  ],
  egg: [
    "    ...    ",
    "   .oOo.   ",
    "  .oOOOo.  ",
    " .oOOOOOo. ",
    ".oOOOOOOOo.",
    ".oOOOOOOOo.",
    ".oOOOOOOOo.",
    " .oOOOOOo. ",
    "  .oOOOo.  ",
    "   .ooo.   ",
    "    ...    ",
  ],
  spiral: [
    "    ...    ",
    "   .ooo.   ",
    "  .o   o.  ",
    "  .o .oo.  ",
    "  .o .oOo. ",
    "  .o .ooo. ",
    "  .o...oo. ",
    "   .ooOoo. ",
    "   .ooooo. ",
    "    .ooo.  ",
    "     ...   ",
  ],
  maze: [
    " ........  ",
    " .oo.oo.o. ",
    " .o. .o..o.",
    " .o...o.o. ",
    " .oooo.o.o.",
    " .o. .o.o. ",
    " .o.oo.o.o.",
    " .o...o....",
    " .oooooooo.",
    " .o.o.o.o. ",
    " ........  ",
  ],
  "scales-of-fate": [
    "    .O.    ",
    "   .OOO.   ",
    "   .OOO.   ",
    "   .ooo.   ",
    "    .o.    ",
    "....ooo....",
    ".ooooooooo.",
    ".oOoooooOo.",
    ".ooooooooo.",
    "  .......  ",
    "   .....   ",
  ],
  hourglass: [
    "  .......  ",
    " .ooooooo. ",
    ".oOOOOOOOo.",
    ".oooo.oooo.",
    " .ooo.ooo. ",
    "  .o. .o.  ",
    " .ooo.ooo. ",
    ".oooo.oooo.",
    ".oOOOOOOOo.",
    " .ooooooo. ",
    "  .......  ",
  ],
  thread: [
    "     ..    ",
    "    .oo.   ",
    "    .oO.   ",
    "    .ooo.  ",
    "     .o.   ",
    "     .o.   ",
    "    .oo.   ",
    "   .ooo.   ",
    "   .oOo.   ",
    "  ..ooo..  ",
    " .ooooooo. ",
  ],
  veil: [
    "  .......  ",
    " .ooooooo. ",
    ".oOOOOOOOo.",
    ".ooooooooo.",
    ".o.o.o.o.o.",
    ".ooooooooo.",
    ".o.o.o.o.o.",
    ".ooooooooo.",
    ".o.o.o.o.o.",
    ".ooooooooo.",
    "...........",
  ],
  shadow: [
    "     .     ",
    "    .O.    ",
    "   .ooo.   ",
    "   .oOo.   ",
    "    .o.    ",
    "   .ooo.   ",
    "   .oOo.   ",
    "    .o.    ",
    "   .o.o... ",
    "   .o. ..  ",
    "    .  ....",
  ],
};
