/** Sacred glyphs: things of worship, rule and rite. */
export const sacredGlyphs: Record<string, string[]> = {
  altar: [
    "     .     ",
    "    .O.    ",
    "   .ooo.   ",
    "  .ooooo.  ",
    " .ooooooo. ",
    ".ooooooooo.",
    ".o.o.o.o.o.",
    ".ooooooooo.",
    " .ooooooo. ",
    "  .ooooo.  ",
    "   .....   ",
  ],
  temple: [
    "    ...    ",
    "   .oOo.   ",
    "  .ooooo.  ",
    " .ooooooo. ",
    ".ooooooooo.",
    ".o.......o.",
    ".o..ooo..o.",
    ".o..oOo..o.",
    ".o..ooo..o.",
    " .ooooooo. ",
    "  .......  ",
  ],
  pillar: [
    "   .....   ",
    "  .ooooo.  ",
    " .oOooooOo.",
    ".ooooooooo.",
    ".oOooooooOo",
    ".ooooooooo.",
    ".oOooooooOo",
    ".ooooooooo.",
    " .oOooooOo.",
    "  .ooooo.  ",
    "   .....   ",
  ],
  stupa: [
    "     .     ",
    "    .O.    ",
    "   .oOo.   ",
    "  .ooooo.  ",
    " .ooooooo. ",
    ".ooooooooo.",
    " .ooooooo. ",
    "  .ooooo.  ",
    "   .ooo.   ",
    "    .o.    ",
    "    ...    ",
  ],
  minaret: [
    "   .....   ",
    "  .ooooo.  ",
    "  .ooooo.  ",
    "  .oOooo.  ",
    " ...ooo... ",
    "  .ooooo.  ",
    "  .oOooo.  ",
    "  .ooooo.  ",
    "   .ooo.   ",
    "    .o.    ",
    "    ...    ",
  ],
  tower: [
    "  .......  ",
    " .ooooooo. ",
    ".oOoooooOo.",
    ".ooooooooo.",
    ".oOoooooOo.",
    ".ooooooooo.",
    ".oOoooooOo.",
    ".ooooooooo.",
    ".oOoooooOo.",
    " .ooooooo. ",
    "  .......  ",
  ],
  cairn: [
    "     .     ",
    "    .O.    ",
    "   .ooo.   ",
    "  .ooooo.  ",
    " .ooo.ooo. ",
    ".ooo...ooo.",
    " .o.....o. ",
    "  .o...o.  ",
    "   .ooo.   ",
    "  .ooooo.  ",
    "   .....   ",
  ],
  beads: [
    "   .....   ",
    "  .ooooo.  ",
    " .oOoooOo. ",
    ".ooo.ooo.o.",
    ".oOo...oOo.",
    ".ooooooooo.",
    ".oOo.o.oOo.",
    " .oOoooOo. ",
    "  .ooooo.  ",
    "   .ooo.   ",
    "   .....   ",
  ],
  incense: [
    "    ...    ",
    "   .oOo.   ",
    "   .ooo.   ",
    "  .o.o.o.  ",
    "  .o...o.  ",
    "   .ooo.   ",
    "   .oOo.   ",
    "    .o.    ",
    "    .o.    ",
    "   .ooo.   ",
    "    ...    ",
  ],
  "offering-bowl": [
    "  .......  ",
    " .ooooooo. ",
    ".oOOOOOOOo.",
    ".oOOoooOOo.",
    ".oOoooooOo.",
    ".ooooooooo.",
    " .ooooooo. ",
    "  .ooooo.  ",
    "   .ooo.   ",
    "    ...    ",
    "           ",
  ],
  relic: [
    "  .......  ",
    " .ooooooo. ",
    ".oOoooooOo.",
    ".oOo...oOo.",
    ".oOo...oOo.",
    ".oOoooooOo.",
    ".oOo...oOo.",
    ".oOoooooOo.",
    " .ooooooo. ",
    "  .......  ",
    "           ",
  ],
  icon: [
    "  .......  ",
    " .ooooooo. ",
    ".ooooooooo.",
    ".o.oo.oo.o.",
    ".o.oOo.oo.o",
    ".o.oooo..o.",
    ".o.ooooo.o.",
    ".ooooooooo.",
    " .ooooooo. ",
    "  .......  ",
    "           ",
  ],
  ladder: [
    "  .......  ",
    " .o.....o. ",
    " .o.....o. ",
    " .o.....o. ",
    ".oo.....oo.",
    ".oo.....oo.",
    ".oo.....oo.",
    ".oo.....oo.",
    " .o.....o. ",
    " .o.....o. ",
    "  .......  ",
  ],
  gate: [
    "  .......  ",
    " .o.....o. ",
    ".oo.   .oo.",
    ".oo.   .oo.",
    ".oo.   .oo.",
    ".oo.ooo.oo.",
    ".oo.oOo.oo.",
    ".oo.   .oo.",
    ".oo.   .oo.",
    " .o.....o. ",
    "  .......  ",
  ],
  crown: [
    "     .     ",
    "   .O.O.   ",
    "  .oOoOOo. ",
    "  .o.O.Oo. ",
    " .ooo.ooo. ",
    ".ooooooooo.",
    ".oOoooooOo.",
    ".ooooooooo.",
    " .ooooooo. ",
    "  .ooooo.  ",
    "   .....   ",
  ],
  throne: [
    ".ooooooooo.",
    ".o...o...o.",
    ".o...o...o.",
    ".oOOOOOOOo.",
    ".oOoooooOo.",
    ".oOoooooOo.",
    ".o.ooooo.o.",
    ".o.o...o.o.",
    ".o.ooooo.o.",
    " .ooooooo. ",
    "  .......  ",
  ],
  sceptre: [
    "    ...    ",
    "   .oOo.   ",
    "   .ooo.   ",
    "   .oOo.   ",
    "    .o.    ",
    "    .o.    ",
    "   .ooo.   ",
    "   .oOo.   ",
    "   .oOo.   ",
    "    .o.    ",
    "    ...    ",
  ],
  sword: [
    "     .     ",
    "    .O.    ",
    "   .oOo.   ",
    "   .oOo.   ",
    "    .o.    ",
    "    .o.    ",
    "   ..o..   ",
    "   .ooo.   ",
    "  .ooooo.  ",
    "  .ooooo.  ",
    "   .....   ",
  ],
  shield: [
    "   .....   ",
    "  .ooooo.  ",
    " .ooooooo. ",
    ".oOOOOOOOo.",
    ".oOoooooOo.",
    ".oOoooooOo.",
    ".oOoooooOo.",
    ".oOoooooOo.",
    " .ooooooo. ",
    "  .ooooo.  ",
    "   .....   ",
  ],
  skull: [
    "   .....   ",
    "  .ooooo.  ",
    " .oOoooOo. ",
    ".ooooooooo.",
    ".ooo.o.ooo.",
    ".ooo.o.ooo.",
    ".ooooooooo.",
    ".o.ooooo.o.",
    " .oo...oo. ",
    "  .ooooo.  ",
    "   .....   ",
  ],
  bones: [
    " .o.   .o. ",
    ".oo.   .oo.",
    ".ooo. .ooo.",
    " .ooooooo. ",
    "  .ooooo.  ",
    "   .ooo.   ",
    "  .ooooo.  ",
    " .ooooooo. ",
    ".ooo. .ooo.",
    ".oo.   .oo.",
    " .o.   .o. ",
  ],
  "medicine-bundle": [
    "    ...    ",
    "   .o.o.   ",
    "   .ooo.   ",
    "  ..ooo..  ",
    " .o.ooo.o. ",
    " .ooooooo. ",
    ".oOOoooooo.",
    ".oOOoooooo.",
    ".oOooooooo.",
    " .ooooooo. ",
    "  .......  ",
  ],
  knot: [
    "   .....   ",
    "  .ooooo.  ",
    " .oo.oo.o. ",
    ".oo.oo.ooo.",
    ".o.oo.oooo.",
    ".ooo.ooooo.",
    ".oooo.oooo.",
    ".ooooo.ooo.",
    " .ooooooo. ",
    "  .ooooo.  ",
    "   .....   ",
  ],
  staff: [
    "    ...    ",
    "   .oOo.   ",
    "   .ooo.   ",
    "   .oOo.   ",
    "    .o.    ",
    "   .ooo.   ",
    "   .ooo.   ",
    "    .o.    ",
    "    .o.    ",
    "    .o.    ",
    "    ...    ",
  ],
  tablet: [
    "  .......  ",
    " .ooooooo. ",
    ".oOoooooOo.",
    ".o. . . .o.",
    ".o. . . .o.",
    ".o. . . .o.",
    ".o. . . .o.",
    ".ooooooooo.",
    " .ooooooo. ",
    "  .ooooo.  ",
    "   .....   ",
  ],
  coin: [
    "   .....   ",
    "  .ooooo.  ",
    " .oOoooOo. ",
    ".ooooooooo.",
    ".oOo...oOo.",
    ".ooo.o.ooo.",
    ".oOo...oOo.",
    ".ooooooooo.",
    " .oOoooOo. ",
    "  .ooooo.  ",
    "   .....   ",
  ],
};
