/** Weather, sky, and landscape: the powers of earth and sky that people address. */
export const skyLandGlyphs: Record<string, string[]> = {
  cloud: [
    "           ",
    "           ",
    "    ...    ",
    "   .ooo.   ",
    "  .ooooo.  ",
    " .oOoOoOo. ",
    " .ooooooo. ",
    "  .ooooo.  ",
    "   .....   ",
    "           ",
    "           ",
  ],
  thunder: [
    "           ",
    "     .     ",
    "    .o.    ",
    "   .ooo.   ",
    "  .oo..o.  ",
    " .o.  .o.  ",
    ".o.   .oo. ",
    ".o.    .o. ",
    " o      o. ",
    " .     .o. ",
    "     ...   ",
  ],
  snow: [
    " .   .   . ",
    " .o. o .o. ",
    "  .o.o.o.  ",
    "   .ooo.   ",
    ".oo.oOo.oo.",
    ".ooooOoooo.",
    ".oo.oOo.oo.",
    "   .ooo.   ",
    "  .o.o.o.  ",
    " .o. o .o. ",
    " .   .   . ",
  ],
  hail: [
    "           ",
    "   .o.o.   ",
    "  .o.o.o.  ",
    "  .ooooo.  ",
    " .o.oOo.o. ",
    " .ooooooo. ",
    "  .o.o.o.  ",
    "   .o.o.   ",
    "   o.o.o   ",
    "    o.o    ",
    "           ",
  ],
  rainbow: [
    "           ",
    "           ",
    "   .....   ",
    "  .ooooo.  ",
    " .oOoOoOo. ",
    " .o.o.o.o. ",
    " .o.   .o. ",
    "  .o   o.  ",
    "   .....   ",
    "           ",
    "           ",
  ],
  comet: [
    "        .  ",
    "       .O. ",
    "      .oO. ",
    "     .ooo. ",
    "    .oOo.  ",
    "   .oOo.   ",
    "  .ooo.    ",
    " .ooo.     ",
    ".ooo.      ",
    ".oo.       ",
    ".o.        ",
  ],
  eclipse: [
    "   .....   ",
    "  .ooooo.  ",
    " .ooooooo. ",
    ".ooooooooo.",
    ".ooooooooo.",
    ".oooOooooo.",
    ".ooooooooo.",
    ".ooooooooo.",
    " .ooooooo. ",
    "  .......  ",
    "           ",
  ],
  dawn: [
    "     .     ",
    "    .O.    ",
    "   .OOO.   ",
    "  .OOOOO.  ",
    " .OOOOOOo. ",
    ".ooooooooo.",
    ".oooooooo. ",
    "  .ooooo.  ",
    "   .ooo.   ",
    "    ...    ",
    "           ",
  ],
  night: [
    "           ",
    "   .....   ",
    "  .ooooo.  ",
    " .ooooooo. ",
    ".ooooooooo.",
    ".o.O  o.o. ",
    ".o o O.ooo.",
    " .ooooooo. ",
    "  .ooooo.  ",
    "   .....   ",
    "           ",
  ],
  constellation: [
    "           ",
    "  .  . .  .",
    "  o  o o  o",
    "  . .O.  . ",
    " .o o.o.o. ",
    ". o.o. o.o.",
    ".  . o O  .",
    " .   o  .  ",
    "   o   o   ",
    "  .  ..    ",
    "           ",
  ],
  waterfall: [
    "           ",
    "...........",
    "    o o    ",
    "    o o    ",
    "    o.o    ",
    "   o o o   ",
    "   o.o.o   ",
    "  o o o o  ",
    "  .ooooo.  ",
    " .oOoooOo. ",
    "  .......  ",
  ],
  lake: [
    "           ",
    "           ",
    "  .......  ",
    " .ooooooo. ",
    ".oOoooooOo.",
    ".ooooooooo.",
    ".oOoooooOo.",
    " .ooooooo. ",
    "  .......  ",
    "           ",
    "           ",
  ],
  marsh: [
    "           ",
    "     .     ",
    "     .     ",
    "  .  .     ",
    "  .  .  .  ",
    "  .  .  .  ",
    "  .  .  .  ",
    "...........",
    ".ooooooooo.",
    " .ooooooo. ",
    "  .......  ",
  ],
  island: [
    "           ",
    "     .     ",
    "    ...    ",
    "   .oOo.   ",
    "     .     ",
    "     .     ",
    "    ...    ",
    "   .ooo.   ",
    "...........",
    ".o.o.o.o.o.",
    "           ",
  ],
  cliff: [
    "           ",
    ".........  ",
    ".ooooooo.  ",
    ".o         ",
    ".o         ",
    ".o         ",
    ".o         ",
    ".o         ",
    ".o         ",
    ".o         ",
    ".o         ",
  ],
  dune: [
    "           ",
    "           ",
    "        .  ",
    "       .o. ",
    "      .ooo.",
    "    .ooooo.",
    "   .oooooo.",
    "  .ooooooo.",
    " .oooooooo.",
    "...........",
    "           ",
  ],
  oasis: [
    "  .     .  ",
    " ...   ... ",
    "  .     .  ",
    "  .     .  ",
    "  .     .  ",
    "...........",
    " .ooooooo. ",
    ".oOoooooOo.",
    " .ooooooo. ",
    "  .......  ",
    "           ",
  ],
  volcano: [
    "     .     ",
    "    .O.    ",
    "   .oOo.   ",
    "  .ooooo.  ",
    " .ooooooo. ",
    ".ooooooooo.",
    ".o.  . .o. ",
    ".o. .O. .o.",
    ".o.oOoo.oo.",
    "...........",
    ".ooooooooo.",
  ],
  "standing-stone": [
    "           ",
    "    ...    ",
    "   .ooo.   ",
    "   .oOo.   ",
    "   .ooo.   ",
    "   .ooo.   ",
    "   .ooo.   ",
    "   .ooo.   ",
    "   .ooo.   ",
    "   .....   ",
    "           ",
  ],
  salt: [
    "           ",
    "   .....   ",
    "  .ooooo.  ",
    " .oOoooOo. ",
    ".oOoOoOoOo.",
    ".oOoOoOoOo.",
    " .oOoOoOo. ",
    "  .ooooo.  ",
    "   .ooo.   ",
    "    ...    ",
    "           ",
  ],
  ore: [
    "           ",
    "   .....   ",
    " ..ooooo.. ",
    ".oooO.ooo o",
    ".ooO.O.oo.o",
    ".oO.O.Ooo.o",
    ".oo.O.oooo.",
    ".ooooO.ooo.",
    " .ooo.oooo.",
    " ..oooooo. ",
    "   ......  ",
  ],
  hill: [
    "           ",
    "           ",
    "      .    ",
    "     .O.   ",
    "    .oOo.  ",
    "  .ooooo.  ",
    " .oooooo.  ",
    ".ooooooo.  ",
    ".ooooo..   ",
    "..oo...    ",
    "           ",
  ],
};
