

/**
 * types/biomes/base.ts - Base BiomeType definition
 */

export enum BiomeType {
  DEEP_OCEAN = 'DEEP_OCEAN',
  SHALLOW_OCEAN = 'SHALLOW_OCEAN',
  BEACH = 'BEACH',
  GRASSLAND = 'GRASSLAND',
  FOREST = 'FOREST',
  DENSE_FOREST = 'DENSE_FOREST',
  HILLS = 'HILLS',
  MOUNTAIN = 'MOUNTAIN',
  HIGH_PEAK = 'HIGH_PEAK',
  SNOW = 'SNOW', 
  RIVER = 'RIVER',
  MAJOR_RIVER = 'MAJOR_RIVER', 
  RIVERBANK = 'RIVERBANK',
  HAMLET = 'HAMLET',
  LOW_DENSITY_CITY = 'LOW_DENSITY_CITY',
  DENSE_CITY = 'DENSE_CITY',
  URBAN = 'URBAN', // Legacy
  JUNGLE = 'JUNGLE',     
  DESERT = 'DESERT',     
  OASIS = 'OASIS',       
  WETLANDS = 'WETLANDS',
  REEF = 'REEF',         
  SCRUB = 'SCRUB',

  TUNDRA = 'TUNDRA',
  STEPPE = 'STEPPE',
  MANGROVE = 'MANGROVE',
  VOLCANIC_SOIL = 'VOLCANIC_SOIL',
  VOLCANIC_ROCK = 'VOLCANIC_ROCK',
  ACTIVE_LAVA = 'ACTIVE_LAVA',
  SHOALS_TILE = 'SHOALS_TILE', // Specific tile type for shoals areas
  SALT_FLATS = 'SALT_FLATS',
  HOT_SPRINGS = 'HOT_SPRINGS',
  RUINS = 'RUINS',
  ESTUARY = 'ESTUARY',
  FRESHWATER_LAKE = 'FRESHWATER_LAKE',
  CLIFF = 'CLIFF',
  PALACE = 'PALACE',
  HOLY_SITE = 'HOLY_SITE',
  FARMLAND = 'FARMLAND',
  MARKETPLACE = 'MARKETPLACE',
  GOVERNMENT_DISTRICT = 'GOVERNMENT_DISTRICT',
  CITY_CENTER = 'CITY_CENTER',
}