import type { InteriorProfile } from "./types";

/**
 * Halls of government and teaching, laid out in rows (`program: "rows"`)
 * facing a dais whose `styles.altar` names it, or round a teacher
 * (`program: "gather"` with a `lectern`). `table` in a room's furnishings
 * sets a council table before the dais.
 */
export const civic: InteriorProfile[] = [
  {
    id: "council-chamber",
    uses: ["venue.town-hall", "venue.guild-hall", "civic.english-market-hall"],
    program: "rows",
    regulars: { hours: [9, 12], fill: 0.3 },
    styles: { altar: "dais-europe", stool: "chair" },
    label: "Council chamber",
    region: "Latin Europe",
    period: "1200 – 1900",
    when: { start: { year: 1200 }, end: { year: 1900 } },
    basis: "documented",
    note: "The council room of a town or guild hall, as at Lüneburg, York's Merchant Adventurers and the guildhalls of the Low Countries: panelled walls, the mayor's chair under a cloth of estate and the town's arms, aldermen round a table covered in cloth, benches for those who came to be heard, the town chest with its several locks.",
    shapes: ["rect"],
    size: [13, 12],
    door: "door",
    windowStyle: "lattice",
    fire: "none",
    smokehole: false,
    seating: "chair",
    sleep: "none",
    trades: ["household"],
    furnish: ["table", "chest", "frame", "frame", "map", "lamp"],
    looks: [
      { wall: "timber", floor: "plank", wear: 0.4, soot: 0.3 },
      { wall: "plaster", dado: "panel", floor: "plank", wear: 0.25, soot: 0.2 },
      { wall: "panel", floor: "parquet", wear: 0.1, soot: 0.1 },
    ],
    colorways: [
      { name: "Oak and crimson", wall: "#c8b48c", trim: "#3a2a1a", floor: "#8a6a48", wood: "#6a4a2c", accent: "#8a1e26" },
      { name: "Dutch green", wall: "#dcd6c4", trim: "#2a2a24", floor: "#9a8a6a", wood: "#4a3626", accent: "#2a5a3a" },
    ],
  },
  {
    id: "roman-basilica",
    uses: ["civic.republican-imperial-italy"],
    program: "rows",
    regulars: { hours: [8, 13], fill: 0.2 },
    styles: { altar: "tribunal", pole: "stone" },
    label: "Basilica",
    region: "Roman Italy",
    period: "130 BCE – 400 CE",
    when: { start: { year: -130 }, end: { year: 400 } },
    basis: "archaeological",
    note: "The basilica of a Roman forum, as at Pompeii and Fano: a colonnaded hall for business and lawsuits, the tribunal raised in its apse with the magistrate's curule chair, the emperor's statue behind and the lictors' fasces. Litigants and idlers stood.",
    shapes: ["apse"],
    size: [13, 16],
    door: "door",
    windowStyle: "shutter",
    fire: "none",
    smokehole: false,
    seating: "floor",
    sleep: "none",
    pole: true,
    trades: ["household"],
    furnish: ["lamp", "lamp"],
    looks: [
      { wall: "plaster", floor: "flag", wear: 0.3, soot: 0.2 },
      { wall: "plaster", dado: "panel", floor: "tile", wear: 0.2, soot: 0.1 },
      { wall: "stripe", dado: "panel", floor: "tile", wear: 0.05, soot: 0.05 },
    ],
    colorways: [
      { name: "Marble and Pompeian red", wall: "#b04a32", trim: "#e8dcc4", floor: "#d8ccb4", wood: "#6a4a30", accent: "#e0b040" },
      { name: "Grey marble", wall: "#d0ccc4", trim: "#5a5650", floor: "#c4beb4", wood: "#5a4030", accent: "#8a2a2a" },
    ],
  },
  {
    id: "grammar-school",
    uses: ["venue.school"],
    program: "rows",
    regulars: { hours: [7, 12], fill: 0.5 },
    styles: { altar: "school-grammar", pew: "desk" },
    label: "Grammar school",
    region: "Europe",
    period: "1400 – 1850",
    when: { start: { year: 1400 }, end: { year: 1850 } },
    basis: "documented",
    note: "One long room, as at Winchester's School and the Latin schools of the Netherlands: the master's raised desk at the end, a motto board over it, pupils on forms at sloped desks, hornbooks for the youngest and the birch on the wall.",
    shapes: ["rect"],
    size: [11, 13],
    door: "door",
    windowStyle: "lattice",
    fire: "none",
    smokehole: false,
    seating: "chair",
    sleep: "none",
    trades: ["household"],
    furnish: ["chest", "frame"],
    looks: [
      { wall: "plaster", floor: "plank", wear: 0.5, soot: 0.3 },
      { wall: "plaster", dado: "panel", floor: "plank", wear: 0.35, soot: 0.2 },
      { wall: "panel", floor: "plank", wear: 0.2, soot: 0.1 },
    ],
    colorways: [
      { name: "Limewash and oak", wall: "#e0d8c4", trim: "#4a3a2a", floor: "#8a6a48", wood: "#6a4a30", accent: "#2a3a5a" },
      { name: "Old brick", wall: "#b0745a", trim: "#3a2a20", floor: "#7a5a3e", wood: "#5a3e28", accent: "#5a2a2a" },
    ],
  },
  {
    id: "board-school",
    uses: ["venue.school"],
    program: "rows",
    regulars: { hours: [8, 15], fill: 0.6 },
    styles: { altar: "school-board", pew: "desk" },
    label: "Schoolroom",
    region: "Industrial world",
    period: "1850 – 1960",
    when: { start: { year: 1850 }, end: { year: 1960 } },
    basis: "documented",
    note: "The schoolroom of mass elementary education, from the English board schools to the Prussian Volksschule and the American graded school: rows of fixed desks, a blackboard, a wall map pulled down, the teacher's desk with a handbell and a globe.",
    shapes: ["rect"],
    size: [11, 12],
    door: "door",
    windowStyle: "shutter",
    fire: "stove",
    smokehole: false,
    seating: "chair",
    sleep: "none",
    trades: ["household"],
    furnish: ["clock", "frame", "shelf"],
    looks: [
      { wall: "plaster", floor: "plank", wear: 0.4, soot: 0.2 },
      { wall: "plaster", dado: "panel", floor: "plank", wear: 0.25, soot: 0.1 },
      { wall: "plaster", dado: "panel", floor: "parquet", wear: 0.1, soot: 0.05 },
    ],
    colorways: [
      { name: "Institution green", wall: "#c8d4b8", trim: "#3a4a3a", floor: "#8a7050", wood: "#6a4a30", accent: "#2a4a6a" },
      { name: "Cream and brown", wall: "#e4dcc4", trim: "#4a3626", floor: "#8a6a48", wood: "#5a3e28", accent: "#6a2a2a" },
    ],
  },
  {
    id: "terakoya",
    uses: ["venue.terakoya"],
    program: "rows",
    regulars: { hours: [8, 14], fill: 0.5 },
    styles: { altar: "terakoya", pew: "lowdesk", frame: "scroll" },
    label: "Terakoya",
    region: "Japan",
    period: "1600 – 1880",
    when: { start: { year: 1600 }, end: { year: 1880 } },
    basis: "documented",
    note: "The writing schools of Edo and the castle towns, held in a temple or the master's house: pupils kneeling at low desks on tatami copying the master's models, which hang on the wall; brushes, inkstones, a stack of copybooks.",
    shapes: ["rect"],
    size: [11, 11],
    door: "door",
    windowStyle: "shoji",
    fire: "none",
    smokehole: false,
    seating: "chair",
    sleep: "none",
    trades: ["household"],
    furnish: ["frame", "lantern", "shelf"],
    looks: [
      { wall: "plaster", floor: "mat", wear: 0.4, soot: 0.3 },
      { wall: "shoji", floor: "mat", wear: 0.2, soot: 0.15 },
      { wall: "shoji", floor: "mat", wear: 0.05, soot: 0.05 },
    ],
    colorways: [
      { name: "Cedar and tatami", wall: "#d8c8a0", trim: "#3d2e24", floor: "#b8a070", wood: "#6a4a30", accent: "#3f5a7a" },
      { name: "Kurobi soot", wall: "#8a7a64", trim: "#1e1814", floor: "#a89060", wood: "#3a2a1e", accent: "#8a2a2a" },
    ],
  },
  {
    id: "madrasa",
    uses: ["venue.madrasa", "venue.sufi-lodge"],
    program: "gather",
    regulars: { hours: [7, 13], fill: 0.5 },
    styles: { shelf: "niche" },
    label: "Madrasa",
    region: "Islamic world",
    period: "1000 – 1950",
    when: { start: { year: 1000 }, end: { year: 1950 } },
    basis: "documented",
    note: "A teaching hall of the madrasas founded from the Seljuk Nizamiyya onward: students in a circle, the halqa, round a teacher and his book on its folding stand, books in the wall niches, carpets and lamps. A Sufi lodge's circle is drawn the same way.",
    shapes: ["rect"],
    size: [11, 10],
    door: "door",
    windowStyle: "lattice",
    fire: "none",
    smokehole: false,
    seating: "floor",
    sleep: "none",
    trades: ["household"],
    furnish: ["lectern", "shelf", "shelf", "lamp", "lamp", "plates"],
    looks: [
      { wall: "plaster", floor: "rushes", wear: 0.3, soot: 0.2 },
      { wall: "plaster", dado: "zellige", floor: "flag", wear: 0.2, soot: 0.1 },
      { wall: "plaster", dado: "zellige", floor: "carpet", wear: 0.05, soot: 0.05 },
    ],
    colorways: [
      { name: "Limewash and turquoise", wall: "#e8e0d0", trim: "#5a4a38", floor: "#c8b8a0", wood: "#5a3e2a", accent: "#2a7a8a" },
      { name: "Sandstone and lapis", wall: "#d4bc94", trim: "#4a3626", floor: "#b8a080", wood: "#4a3020", accent: "#2a3a8a" },
    ],
  },
  {
    id: "quranic-school",
    uses: ["venue.quranic-school"],
    program: "gather",
    regulars: { hours: [6, 11], fill: 0.5 },
    styles: { cushions: "petate" },
    label: "Qur'anic school",
    region: "West Africa",
    period: "1100 – present",
    when: { start: { year: 1100 }, end: { year: 2100 } },
    basis: "documented",
    note: "The Qur'anic schools of Timbuktu, Djenné and the Hausa towns: pupils on mats round their teacher, copying verses onto wooden boards in ink they wash off to write the next lesson.",
    shapes: ["rect"],
    size: [9, 8],
    door: "opening",
    windowStyle: "none",
    fire: "none",
    smokehole: false,
    seating: "floor",
    sleep: "none",
    trades: ["household"],
    furnish: ["lectern", "jars", "basket"],
    looks: [
      { wall: "mud", floor: "sand", wear: 0.4, soot: 0.2 },
      { wall: "mud", floor: "earth", wear: 0.3, soot: 0.1 },
      { wall: "mud", floor: "mat", wear: 0.2, soot: 0.1 },
    ],
    colorways: [
      { name: "Banco and indigo", wall: "#b88a5a", trim: "#5a3a22", floor: "#c8a878", wood: "#5a3e2a", accent: "#2a3a6a" },
      { name: "Red earth", wall: "#a8643e", trim: "#4a2a1a", floor: "#b88a5a", wood: "#4a3020", accent: "#d0a030" },
    ],
  },
];
