import type { InteriorProfile } from "./types";

/**
 * Halls of government and teaching, laid out in rows (`program: "rows"`)
 * facing a dais whose `styles.altar` names it, or round a teacher
 * (`program: "gather"` with a `lectern`). `table` in a room's furnishings
 * sets a council table before the dais.
 */
export const civic: InteriorProfile[] = [
  {
    id: "council-chamber",
    uses: ["venue.town-hall", "venue.guild-hall", "civic.english-market-hall"],
    program: "rows",
    regulars: { hours: [9, 12], fill: 0.3 },
    styles: { altar: "dais-europe", stool: "chair" },
    label: "Council chamber",
    region: "Latin Europe",
    period: "1200 – 1900",
    when: { start: { year: 1200 }, end: { year: 1900 } },
    basis: "documented",
    note: "The council room of a town or guild hall, as at Lüneburg, York's Merchant Adventurers and the guildhalls of the Low Countries: panelled walls, the mayor's chair under a cloth of estate and the town's arms, aldermen round a table covered in cloth, benches for those who came to be heard, the town chest with its several locks.",
    shapes: ["rect"],
    size: [13, 12],
    door: "door",
    windowStyle: "lattice",
    fire: "none",
    smokehole: false,
    seating: "chair",
    sleep: "none",
    trades: ["household"],
    furnish: ["table", "chest", "frame", "frame", "map", "lamp"],
    looks: [
      { wall: "timber", floor: "plank", wear: 0.4, soot: 0.3 },
      { wall: "plaster", dado: "panel", floor: "plank", wear: 0.25, soot: 0.2 },
      { wall: "panel", floor: "parquet", wear: 0.1, soot: 0.1 },
    ],
    colorways: [
      { name: "Oak and crimson", wall: "#c8b48c", trim: "#3a2a1a", floor: "#8a6a48", wood: "#6a4a2c", accent: "#8a1e26" },
      { name: "Dutch green", wall: "#dcd6c4", trim: "#2a2a24", floor: "#9a8a6a", wood: "#4a3626", accent: "#2a5a3a" },
    ],
  },
  {
    id: "roman-basilica",
    uses: ["civic.republican-imperial-italy"],
    program: "rows",
    regulars: { hours: [8, 13], fill: 0.2 },
    styles: { altar: "tribunal", pole: "stone" },
    label: "Basilica",
    region: "Roman Italy",
    period: "130 BCE – 400 CE",
    when: { start: { year: -130 }, end: { year: 400 } },
    basis: "archaeological",
    note: "The basilica of a Roman forum, as at Pompeii and Fano: a colonnaded hall for business and lawsuits, the tribunal raised in its apse with the magistrate's curule chair, the emperor's statue behind and the lictors' fasces. Litigants and idlers stood.",
    shapes: ["apse"],
    size: [13, 16],
    door: "door",
    windowStyle: "shutter",
    fire: "none",
    smokehole: false,
    seating: "floor",
    sleep: "none",
    pole: true,
    trades: ["household"],
    furnish: ["lamp", "lamp"],
    looks: [
      { wall: "plaster", floor: "flag", wear: 0.3, soot: 0.2 },
      { wall: "plaster", dado: "panel", floor: "tile", wear: 0.2, soot: 0.1 },
      { wall: "stripe", dado: "panel", floor: "tile", wear: 0.05, soot: 0.05 },
    ],
    colorways: [
      { name: "Marble and Pompeian red", wall: "#b04a32", trim: "#e8dcc4", floor: "#d8ccb4", wood: "#6a4a30", accent: "#e0b040" },
      { name: "Grey marble", wall: "#d0ccc4", trim: "#5a5650", floor: "#c4beb4", wood: "#5a4030", accent: "#8a2a2a" },
    ],
  },
  {
    id: "grammar-school",
    uses: ["venue.school"],
    program: "rows",
    regulars: { hours: [7, 12], fill: 0.5 },
    styles: { altar: "school-grammar", pew: "desk" },
    label: "Grammar school",
    region: "Europe",
    period: "1400 – 1850",
    when: { start: { year: 1400 }, end: { year: 1850 } },
    basis: "documented",
    note: "One long room, as at Winchester's School and the Latin schools of the Netherlands: the master's raised desk at the end, a motto board over it, pupils on forms at sloped desks, hornbooks for the youngest and the birch on the wall.",
    shapes: ["rect"],
    size: [11, 13],
    door: "door",
    windowStyle: "lattice",
    fire: "none",
    smokehole: false,
    seating: "chair",
    sleep: "none",
    trades: ["household"],
    furnish: ["chest", "frame"],
    looks: [
      { wall: "plaster", floor: "plank", wear: 0.5, soot: 0.3 },
      { wall: "plaster", dado: "panel", floor: "plank", wear: 0.35, soot: 0.2 },
      { wall: "panel", floor: "plank", wear: 0.2, soot: 0.1 },
    ],
    colorways: [
      { name: "Limewash and oak", wall: "#e0d8c4", trim: "#4a3a2a", floor: "#8a6a48", wood: "#6a4a30", accent: "#2a3a5a" },
      { name: "Old brick", wall: "#b0745a", trim: "#3a2a20", floor: "#7a5a3e", wood: "#5a3e28", accent: "#5a2a2a" },
    ],
  },
  {
    id: "board-school",
    uses: ["venue.school"],
    program: "rows",
    regulars: { hours: [8, 15], fill: 0.6 },
    styles: { altar: "school-board", pew: "desk" },
    label: "Schoolroom",
    region: "Industrial world",
    period: "1850 – 1960",
    when: { start: { year: 1850 }, end: { year: 1960 } },
    basis: "documented",
    note: "The schoolroom of mass elementary education, from the English board schools to the Prussian Volksschule and the American graded school: rows of fixed desks, a blackboard, a wall map pulled down, the teacher's desk with a handbell and a globe.",
    shapes: ["rect"],
    size: [11, 12],
    door: "door",
    windowStyle: "shutter",
    fire: "stove",
    smokehole: false,
    seating: "chair",
    sleep: "none",
    trades: ["household"],
    furnish: ["clock", "frame", "shelf"],
    looks: [
      { wall: "plaster", floor: "plank", wear: 0.4, soot: 0.2 },
      { wall: "plaster", dado: "panel", floor: "plank", wear: 0.25, soot: 0.1 },
      { wall: "plaster", dado: "panel", floor: "parquet", wear: 0.1, soot: 0.05 },
    ],
    colorways: [
      { name: "Institution green", wall: "#c8d4b8", trim: "#3a4a3a", floor: "#8a7050", wood: "#6a4a30", accent: "#2a4a6a" },
      { name: "Cream and brown", wall: "#e4dcc4", trim: "#4a3626", floor: "#8a6a48", wood: "#5a3e28", accent: "#6a2a2a" },
    ],
  },
  {
    id: "terakoya",
    uses: ["venue.terakoya"],
    program: "rows",
    regulars: { hours: [8, 14], fill: 0.5 },
    styles: { altar: "terakoya", pew: "lowdesk", frame: "scroll" },
    label: "Terakoya",
    region: "Japan",
    period: "1600 – 1880",
    when: { start: { year: 1600 }, end: { year: 1880 } },
    basis: "documented",
    note: "The writing schools of Edo and the castle towns, held in a temple or the master's house: pupils kneeling at low desks on tatami copying the master's models, which hang on the wall; brushes, inkstones, a stack of copybooks.",
    shapes: ["rect"],
    size: [11, 11],
    door: "door",
    windowStyle: "shoji",
    fire: "none",
    smokehole: false,
    seating: "chair",
    sleep: "none",
    trades: ["household"],
    furnish: ["frame", "lantern", "shelf"],
    looks: [
      { wall: "plaster", floor: "mat", wear: 0.4, soot: 0.3 },
      { wall: "shoji", floor: "mat", wear: 0.2, soot: 0.15 },
      { wall: "shoji", floor: "mat", wear: 0.05, soot: 0.05 },
    ],
    colorways: [
      { name: "Cedar and tatami", wall: "#d8c8a0", trim: "#3d2e24", floor: "#b8a070", wood: "#6a4a30", accent: "#3f5a7a" },
      { name: "Kurobi soot", wall: "#8a7a64", trim: "#1e1814", floor: "#a89060", wood: "#3a2a1e", accent: "#8a2a2a" },
    ],
  },
  {
    id: "madrasa",
    uses: ["venue.madrasa", "venue.sufi-lodge"],
    program: "gather",
    regulars: { hours: [7, 13], fill: 0.5 },
    styles: { shelf: "niche" },
    label: "Madrasa",
    region: "Islamic world",
    period: "1000 – 1950",
    when: { start: { year: 1000 }, end: { year: 1950 } },
    basis: "documented",
    note: "A teaching hall of the madrasas founded from the Seljuk Nizamiyya onward: students in a circle, the halqa, round a teacher and his book on its folding stand, books in the wall niches, carpets and lamps. A Sufi lodge's circle is drawn the same way.",
    shapes: ["rect"],
    size: [11, 10],
    door: "door",
    windowStyle: "lattice",
    fire: "none",
    smokehole: false,
    seating: "floor",
    sleep: "none",
    trades: ["household"],
    furnish: ["lectern", "shelf", "shelf", "lamp", "lamp", "plates"],
    looks: [
      { wall: "plaster", floor: "rushes", wear: 0.3, soot: 0.2 },
      { wall: "plaster", dado: "zellige", floor: "flag", wear: 0.2, soot: 0.1 },
      { wall: "plaster", dado: "zellige", floor: "carpet", wear: 0.05, soot: 0.05 },
    ],
    colorways: [
      { name: "Limewash and turquoise", wall: "#e8e0d0", trim: "#5a4a38", floor: "#c8b8a0", wood: "#5a3e2a", accent: "#2a7a8a" },
      { name: "Sandstone and lapis", wall: "#d4bc94", trim: "#4a3626", floor: "#b8a080", wood: "#4a3020", accent: "#2a3a8a" },
    ],
  },
  {
    id: "quranic-school",
    uses: ["venue.quranic-school"],
    program: "gather",
    regulars: { hours: [6, 11], fill: 0.5 },
    styles: { cushions: "petate" },
    label: "Qur'anic school",
    region: "West Africa",
    period: "1100 – present",
    when: { start: { year: 1100 }, end: { year: 2100 } },
    basis: "documented",
    note: "The Qur'anic schools of Timbuktu, Djenné and the Hausa towns: pupils on mats round their teacher, copying verses onto wooden boards in ink they wash off to write the next lesson.",
    shapes: ["rect"],
    size: [9, 8],
    door: "opening",
    windowStyle: "none",
    fire: "none",
    smokehole: false,
    seating: "floor",
    sleep: "none",
    trades: ["household"],
    furnish: ["lectern", "jars", "basket"],
    looks: [
      { wall: "mud", floor: "sand", wear: 0.4, soot: 0.2 },
      { wall: "mud", floor: "earth", wear: 0.3, soot: 0.1 },
      { wall: "mud", floor: "mat", wear: 0.2, soot: 0.1 },
    ],
    colorways: [
      { name: "Banco and indigo", wall: "#b88a5a", trim: "#5a3a22", floor: "#c8a878", wood: "#5a3e2a", accent: "#2a3a6a" },
      { name: "Red earth", wall: "#a8643e", trim: "#4a2a1a", floor: "#b88a5a", wood: "#4a3020", accent: "#d0a030" },
    ],
  },
];

/** Houses where a people meets, sleeps or is brought up together, and the
 * schools and halls that do the same work elsewhere. */
export const assemblies: InteriorProfile[] = [
  {
    id: "wharenui",
    uses: ["venue.meeting-house"],
    program: "gather",
    regulars: { hours: [18, 24], fill: 0.6 },
    styles: { ledge: "mattress" },
    label: "Wharenui",
    region: "Aotearoa",
    period: "1200 – present",
    when: { start: { year: 1200 }, end: { year: 2100 } },
    basis: "documented",
    note: "The meeting house on the marae, itself an ancestor: carved poupou of the hapū's forebears down the walls with paua-shell eyes, tukutuku lattice woven between them, kowhaiwhai scrolls painted on the rafters, and mattresses laid along both walls for the visitors who sleep where they have been welcomed. The great carved houses are of the nineteenth century; earlier whare whakairo were smaller.",
    shapes: ["rect"],
    size: [14, 9],
    door: "door",
    windowStyle: "none",
    fire: "none",
    smokehole: false,
    seating: "chair",
    sleep: "none",
    trades: ["household"],
    furnish: ["basket"],
    looks: [
      { wall: "whakairo", floor: "rushes", wear: 0.3, soot: 0.2 },
      { wall: "whakairo", floor: "rushes", wear: 0.2, soot: 0.1 },
      { wall: "whakairo", floor: "rushes", wear: 0.1, soot: 0.05 },
    ],
    colorways: [
      { name: "Kokowai", wall: "#8a2a1e", trim: "#1a1412", floor: "#b8a070", wood: "#5a2a1e", accent: "#2a4a6a" },
      { name: "Totara", wall: "#7a3a24", trim: "#241812", floor: "#a89060", wood: "#6a3a22", accent: "#6a2a4a" },
    ],
  },
  {
    id: "council-longhouse",
    uses: ["venue.longhouse-council"],
    program: "gather",
    regulars: { hours: [17, 23], fill: 0.6 },
    styles: { ledge: "platform", pegs: "wampum" },
    label: "Council longhouse",
    region: "Haudenosaunee lands",
    period: "1400 – present",
    when: { start: { year: 1400 }, end: { year: 2100 } },
    basis: "documented",
    note: "The council of the Haudenosaunee under the Great Law, held in a bark longhouse: the Onondaga keep the fire, the Mohawk and Seneca sit on one side of it and the Oneida and Cayuga on the other, and the wampum belts that hold the law are read aloud. The raised platforms down both walls are where a longhouse's families slept.",
    shapes: ["rect"],
    size: [15, 8],
    door: "flap",
    windowStyle: "none",
    fire: "firepit",
    smokehole: true,
    seating: "chair",
    sleep: "none",
    trades: ["household"],
    furnish: ["pegs", "pegs", "basket"],
    looks: [
      { wall: "bark", floor: "earth", wear: 0.4, soot: 0.6 },
      { wall: "bark", floor: "earth", wear: 0.3, soot: 0.5 },
      { wall: "bark", floor: "earth", wear: 0.2, soot: 0.4 },
    ],
    colorways: [
      { name: "Elm bark", wall: "#7a6448", trim: "#2a2018", floor: "#7a6044", wood: "#5a4030", accent: "#4a2a5a" },
      { name: "Smoked bark", wall: "#5a4a38", trim: "#1e1812", floor: "#6a5038", wood: "#4a3424", accent: "#8a2a1e" },
    ],
  },
  {
    id: "haus-tambaran",
    uses: ["venue.mens-house"],
    program: "gather",
    regulars: { hours: [16, 23], fill: 0.6 },
    styles: { ledge: "platform", altar: "orator-stool" },
    label: "Men's house",
    region: "Sepik and New Guinea",
    period: "1000 BCE – present",
    when: { start: { year: -1000 }, end: { year: 2100 } },
    basis: "documented",
    note: "The Iatmul men's house on the Sepik, the ngeko, as Bateson described it: the gable's spirit faces painted again inside on panels of sago spathe, the slit gongs lying on the floor, and the orator's stool, an ancestor carved with a seat before him, which a man strikes with a bundle of leaves to claim the floor in debate.",
    shapes: ["rect"],
    size: [14, 10],
    door: "opening",
    windowStyle: "none",
    fire: "firepit",
    smokehole: false,
    seating: "chair",
    sleep: "none",
    trades: ["household"],
    furnish: ["basket"],
    looks: [
      { wall: "spathe", floor: "earth", wear: 0.4, soot: 0.5 },
      { wall: "spathe", floor: "earth", wear: 0.3, soot: 0.4 },
      { wall: "spathe", floor: "earth", wear: 0.2, soot: 0.3 },
    ],
    colorways: [
      { name: "Ochre and soot", wall: "#3a2a1e", trim: "#1a1412", floor: "#6a5038", wood: "#5a3e28", accent: "#a8442a" },
      { name: "Sago palm", wall: "#5a4a34", trim: "#241a12", floor: "#7a6040", wood: "#6a4a30", accent: "#c89a3a" },
    ],
  },
  {
    id: "age-set-house",
    uses: ["venue.age-set-house"],
    program: "gather",
    regulars: { hours: [18, 24], fill: 0.7 },
    styles: { cushions: "hide", pegs: "maasai" },
    label: "Warriors' house",
    region: "East Africa",
    period: "500 BCE – 1950",
    when: { start: { year: -500 }, end: { year: 1950 } },
    basis: "documented",
    note: "A house of the young men's age-set, as in the Maasai manyata the murran keep together: a low loaf of poles plastered with dung, a fire in the middle, hides to sit and sleep on, spears and the age-set's painted buffalo-hide shields by the wall.",
    shapes: ["oval"],
    size: [10, 8],
    door: "opening",
    windowStyle: "none",
    fire: "firepit",
    smokehole: false,
    seating: "floor",
    sleep: "none",
    trades: ["household"],
    furnish: ["pegs", "pegs", "jars", "basket"],
    looks: [
      { wall: "mud", floor: "earth", wear: 0.5, soot: 0.6 },
      { wall: "mud", floor: "earth", wear: 0.4, soot: 0.5 },
      { wall: "mud", floor: "earth", wear: 0.3, soot: 0.4 },
    ],
    colorways: [
      { name: "Dung and ash", wall: "#7a6a54", trim: "#3a2e24", floor: "#7a6448", wood: "#5a4030", accent: "#a82a1e" },
      { name: "Red earth", wall: "#9a6a48", trim: "#3a2418", floor: "#8a5a3a", wood: "#5a3a24", accent: "#2a3a6a" },
    ],
  },
  {
    id: "telpochcalli",
    uses: ["venue.telpochcalli"],
    program: "gather",
    regulars: { hours: [17, 23], fill: 0.6 },
    styles: { cushions: "petate", pegs: "aztec", altar: "huehuetl" },
    label: "Telpochcalli",
    region: "Aztec Mexico",
    period: "1300 – 1560",
    when: { start: { year: 1300 }, end: { year: 1560 } },
    basis: "documented",
    note: "The ward's house of young commoners, as Sahagún's informants described it: they swept, hauled and trained at arms here by day, and at dusk went to sing and dance to the huehuetl and teponaztli. Its god was Tezcatlipoca, the smoking mirror.",
    shapes: ["rect"],
    size: [12, 10],
    door: "curtain",
    windowStyle: "none",
    fire: "brazier",
    smokehole: false,
    seating: "floor",
    sleep: "none",
    trades: ["household"],
    furnish: ["pegs", "pegs", "pegs", "jars"],
    looks: [
      { wall: "plaster", dado: "band", floor: "earth", wear: 0.4, soot: 0.3 },
      { wall: "plaster", dado: "band", floor: "flag", wear: 0.3, soot: 0.2 },
      { wall: "plaster", dado: "band", floor: "flag", wear: 0.2, soot: 0.1 },
    ],
    colorways: [
      { name: "Stucco and red", wall: "#e4dccc", trim: "#5a2a1e", floor: "#b8a888", wood: "#6a4a30", accent: "#a82a1e" },
      { name: "Lime and turquoise", wall: "#ded6c4", trim: "#2a3a3a", floor: "#a89a7a", wood: "#5a4030", accent: "#2a7a8a" },
    ],
  },
  {
    id: "calmecac",
    uses: ["venue.calmecac"],
    program: "rows",
    regulars: { hours: [6, 14], fill: 0.6 },
    styles: { cushions: "petate", altar: "codex-seat" },
    label: "Calmecac",
    region: "Aztec Mexico",
    period: "1300 – 1560",
    when: { start: { year: 1300 }, end: { year: 1560 } },
    basis: "documented",
    note: "The temple school of the nobility, after the Florentine Codex and the Codex Mendoza: boys on mats before a priest on his reed seat, the screenfold books of the calendar and the songs opened out before them, copal burning in long-handled censers.",
    shapes: ["rect"],
    size: [11, 10],
    door: "curtain",
    windowStyle: "none",
    fire: "brazier",
    smokehole: false,
    seating: "floor",
    sleep: "none",
    trades: ["household"],
    furnish: ["cushions", "jars"],
    looks: [
      { wall: "plaster", dado: "band", floor: "flag", wear: 0.3, soot: 0.3 },
      { wall: "plaster", dado: "band", floor: "flag", wear: 0.2, soot: 0.2 },
      { wall: "plaster", dado: "band", floor: "flag", wear: 0.1, soot: 0.1 },
    ],
    colorways: [
      { name: "Stucco and red", wall: "#e4dccc", trim: "#5a2a1e", floor: "#c8bca4", wood: "#6a4a30", accent: "#a82a1e" },
      { name: "Soot and jade", wall: "#c8c0b0", trim: "#1e1a18", floor: "#b0a48a", wood: "#4a3020", accent: "#2a7a5a" },
    ],
  },
  {
    id: "gurukula",
    uses: ["venue.gurukula"],
    program: "rows",
    regulars: { hours: [6, 12], fill: 0.6 },
    styles: { cushions: "petate", altar: "guru-seat" },
    label: "Gurukula",
    region: "South Asia",
    period: "800 BCE – 1900",
    when: { start: { year: -800 }, end: { year: 1900 } },
    basis: "documented",
    note: "Pupils living in the teacher's house and learning by recitation, as the Upanishads and the dharmashastras lay it down: the guru on his deerskin, the palm-leaf book on its folding stand, the pupils on grass mats before him, mango leaves over the door and a lamp before the water-pot.",
    shapes: ["rect"],
    size: [10, 9],
    door: "opening",
    windowStyle: "lattice",
    fire: "none",
    smokehole: false,
    seating: "floor",
    sleep: "none",
    trades: ["household"],
    furnish: ["cushions", "jars", "lamp"],
    looks: [
      { wall: "mud", floor: "earth", wear: 0.3, soot: 0.2 },
      { wall: "mud", dado: "band", floor: "earth", wear: 0.2, soot: 0.1 },
      { wall: "plaster", dado: "band", floor: "flag", wear: 0.1, soot: 0.05 },
    ],
    colorways: [
      { name: "Cow-dung and lime", wall: "#c8b490", trim: "#5a3a26", floor: "#9a7a58", wood: "#6a4a30", accent: "#c86a1e" },
      { name: "Red earth", wall: "#b8805a", trim: "#4a2a1a", floor: "#8a6040", wood: "#5a3a24", accent: "#e8c050" },
    ],
  },
  {
    id: "union-hall",
    uses: ["venue.union-hall"],
    program: "rows",
    regulars: { hours: [18, 22], fill: 0.6 },
    styles: { altar: "union-banner", pew: "chairs" },
    label: "Union hall",
    region: "Industrial world",
    period: "1850 – present",
    when: { start: { year: 1850 }, end: { year: 2100 } },
    basis: "documented",
    note: "A branch meeting in its hall: rows of chairs before the platform, the chairman's table with the minute book and the water jug, and the branch banner of painted silk behind it, clasped hands and a motto, as George Tutill's workshop painted them for trades from the miners to the dockers.",
    shapes: ["rect"],
    size: [12, 12],
    door: "door",
    windowStyle: "shutter",
    fire: "stove",
    smokehole: false,
    seating: "chair",
    sleep: "none",
    trades: ["household"],
    furnish: ["clock", "frame", "frame"],
    looks: [
      { wall: "brick", floor: "plank", wear: 0.5, soot: 0.4 },
      { wall: "plaster", dado: "panel", floor: "plank", wear: 0.3, soot: 0.2 },
      { wall: "plaster", dado: "panel", floor: "parquet", wear: 0.1, soot: 0.1 },
    ],
    colorways: [
      { name: "Crimson banner", wall: "#d8ccb4", trim: "#3a2a20", floor: "#7a5e44", wood: "#5a3e28", accent: "#a81e2a" },
      { name: "Navy banner", wall: "#c8c8b8", trim: "#2a2a30", floor: "#7a6048", wood: "#4a3424", accent: "#1e3a8a" },
    ],
  },
];
