import type { InteriorProfile } from "./types";

export const eastAsia: InteriorProfile[] = [
  {
    id: "japanese-minka",
    rooms: [
      { id: "doma", label: "Doma", role: "entry", size: [7, 9], fire: "hearth", seating: "floor", furnish: ["jars", "sacks", "basket", "firewood", "broom"], kits: { household: ["quern", "basket"] }, clutter: ["shoes", "grain", "pot"], looks: [{ floor: "earth", wall: "mud" }, { floor: "earth", wall: "mud" }, { floor: "earth", wall: "mud" }] },
      { id: "hiroma", label: "Hiroma", role: "hall", size: [9, 9], fire: "irori", clutter: ["cup", "cloth", "book"] },
      { id: "zashiki", label: "Zashiki", role: "hall", size: [8, 8], fire: "none", furnish: ["shrine", "frame", "lowtable", "cushions", "screen", "lantern"], clutter: ["flowers", "book"], looks: [{ floor: "mat" }, { floor: "mat", wall: "shoji" }, { floor: "mat", wall: "shoji" }] },
      { id: "nando", label: "Nando", role: "sleep", size: [6, 6], fire: "none", sleep: "mat", windowStyle: "none", furnish: ["chest", "shelf", "lantern"], clutter: ["cloth"], looks: [{ floor: "plank" }, { floor: "mat" }, { floor: "mat" }] },
    ],
    styles: { frame: "scroll", shelf: "tansu" },
    clutter: ["shoes", "cup", "book", "cloth", "flowers"],
    label: "Minka farmhouse",
    region: "Japan",
    period: "1650 – 1900",
    when: { start: { year: 1650 }, end: { year: 1900 } },
    basis: "documented",
    note: "Surviving minka: an irori sunk in the board floor with a pot on an adjustable hook, earthen walls, paper-screen openings, tatami in the better rooms, a kamidana shelf. Soot-blackened rafters are typical.",
    shapes: ["rect", "L"],
    size: [12, 9],
    door: "door",
    windowStyle: "shoji",
    fire: "irori",
    smokehole: true,
    seating: "floor",
    sleep: "mat",
    trades: ["household", "weaver", "potter", "scholar"],
    furnish: ["shrine", "chest", "lantern", "lowtable", "cushions", "basket", "jars", "cat", "frame", "frame"],
    looks: [
      { wall: "mud", floor: "earth", wear: 0.45, soot: 0.6 },
      { wall: "mud", floor: "plank", wear: 0.25, soot: 0.45 },
      { wall: "shoji", floor: "mat", wear: 0.05, soot: 0.15, furnish: ["screen"] },
    ],
    colorways: [
      { name: "Cedar and earth", wall: "#b89a72", trim: "#3d2e24", floor: "#9a7a52", wood: "#5a3e2a", accent: "#3f5a7a" },
      { name: "Kurobi soot", wall: "#8a7a64", trim: "#1e1814", floor: "#6a5238", wood: "#3a2a1e", accent: "#8a2a2a" },
      { name: "Pale hinoki", wall: "#d8c8a0", trim: "#6b4a30", floor: "#c8b080", wood: "#9a7a52", accent: "#4a6a4a" },
    ],
  },
  {
    id: "ming-study",
    styles: { frame: "scroll", shelf: "bookcase", stool: "chair" },
    clutter: ["book", "paper", "cup", "flowers"],
    label: "Scholar's study",
    region: "Jiangnan, China",
    period: "1450 – 1700",
    when: { start: { year: 1450 }, end: { year: 1700 } },
    basis: "documented",
    note: "Ming furniture survives in numbers, and manuals such as the Zhangwu zhi describe the ideal study: chairs and a painting table, a lattice window on a garden, a screen, rocks and potted trees.",
    shapes: ["rect", "courtyard", "L"],
    size: [12, 9],
    door: "door",
    windowStyle: "lattice",
    fire: "brazier",
    smokehole: false,
    seating: "chair",
    sleep: "bed",
    trades: ["scholar", "household", "merchant"],
    furnish: ["screen", "plant", "lamp", "chest", "jars", "scrolls", "shelf", "rug", "cat", "frame", "frame"],
    looks: [
      { wall: "plaster", floor: "earth", wear: 0.4, soot: 0.2 },
      { wall: "plaster", floor: "flag", wear: 0.2, soot: 0.08 },
      { wall: "panel", floor: "parquet", wear: 0.02, soot: 0, furnish: ["map", "screen"] },
    ],
    colorways: [
      { name: "Cinnabar", wall: "#e4d6b4", trim: "#7a1f1f", floor: "#6b4b36", wood: "#4a2e22", accent: "#2e6b52" },
      { name: "Ink and jade", wall: "#d8d4c4", trim: "#2a2a2e", floor: "#5a5a58", wood: "#3a2a22", accent: "#3a7a6a" },
      { name: "Huanghuali", wall: "#e8dcc0", trim: "#8a5a2a", floor: "#7a5a3a", wood: "#a8743a", accent: "#2f4f7a" },
    ],
  },
  {
    id: "korean-ondol-room",
    styles: { frame: "scroll", shelf: "tansu" },
    clutter: ["shoes", "cup", "book", "cloth"],
    label: "Ondol room",
    region: "Korea",
    period: "1600 – 1900",
    when: { start: { year: 1600 }, end: { year: 1900 } },
    basis: "documented",
    note: "Joseon hanok rooms: a floor heated from beneath and finished in oiled paper, hanji screen doors, a folding screen, low tables and bedding stored by day. No open fire in the room itself.",
    shapes: ["rect", "L"],
    size: [10, 8],
    door: "door",
    windowStyle: "shoji",
    fire: "none",
    smokehole: false,
    seating: "floor",
    sleep: "mat",
    trades: ["household", "scholar", "weaver"],
    furnish: ["lowtable", "cushions", "chest", "lantern", "screen", "jars", "cat", "frame", "frame"],
    looks: [
      { wall: "mud", floor: "paper", wear: 0.4, soot: 0.05 },
      { wall: "plaster", floor: "paper", wear: 0.2, soot: 0 },
      { wall: "shoji", floor: "paper", wear: 0.02, soot: 0, furnish: ["screen", "map"] },
    ],
    colorways: [
      { name: "Oiled paper amber", wall: "#e8dcc0", trim: "#5a3a24", floor: "#d8a860", wood: "#6a4a30", accent: "#2f5a8a" },
      { name: "Pine and white", wall: "#f0ece0", trim: "#4a3a2a", floor: "#c89a58", wood: "#7a5a3a", accent: "#8a2a3a" },
      { name: "Persimmon", wall: "#e4d0b0", trim: "#6a2e1e", floor: "#c8905a", wood: "#5a3a26", accent: "#d8702a" },
    ],
  },
];
