import type { InteriorProfile } from "./types";

export const europe: InteriorProfile[] = [
  {
    id: "flemish-townhouse",
    styles: { shelf: "hutch", stool: "chair" },
    clutter: ["shoes", "cup", "cloth", "toy", "book"],
    label: "Flemish townhouse",
    region: "Low Countries",
    period: "1600 – 1700",
    when: { start: { year: 1600 }, end: { year: 1700 } },
    basis: "documented",
    note: "Genre painting and surviving houses: brick, whitewash, black-and-white stone floors in grander homes, box beds, Delft tiles around the hearth.",
    shapes: ["rect", "L"],
    size: [12, 9],
    door: "door",
    windowStyle: "shutter",
    fire: "hearth",
    smokehole: false,
    seating: "chair",
    sleep: "bed",
    trades: ["household", "weaver", "merchant", "scholar", "potter"],
    furnish: ["chest", "lamp", "plant", "basket", "jars", "shelf", "rug", "cat", "frame", "frame"],
    looks: [
      { wall: "plaster", floor: "plank", wear: 0.5, soot: 0.25 },
      { wall: "brick", floor: "plank", wear: 0.25, soot: 0.1 },
      { wall: "plaster", floor: "tile", dado: "zellige", wear: 0.02, soot: 0, furnish: ["map", "tapestry"] },
    ],
    colorways: [
      { name: "Brick and oak", wall: "#a4533d", trim: "#d8cdb8", floor: "#8a6a48", wood: "#5a3b26", accent: "#2f5d8a" },
      { name: "Whitewash and Delft", wall: "#e8e2d4", trim: "#2a3040", floor: "#b8b0a0", wood: "#4a3222", accent: "#2f4f9a" },
      { name: "Leiden umber", wall: "#8a6a4a", trim: "#2a1e16", floor: "#6a5038", wood: "#3a2618", accent: "#8a2a2a" },
    ],
  },
  {
    id: "norse-longhouse",
    styles: { table: "trestle" },
    clutter: ["bowl", "yarn", "cloth", "grain"],
    label: "Norse longhouse",
    region: "Scandinavia and the North Atlantic",
    period: "800 – 1050",
    when: { start: { year: 800 }, end: { year: 1050 } },
    basis: "archaeological",
    note: "Bow-sided halls with a long central hearth, earth floors and raised side benches from Hofstaðir, Borg and Hedeby. Wall hangings and painted woodwork are inferred from saga and grave finds.",
    shapes: ["oval", "rect"],
    size: [16, 8],
    door: "door",
    windowStyle: "none",
    fire: "firepit",
    smokehole: true,
    seating: "chair",
    sleep: "mat",
    trades: ["household", "weaver", "hunter"],
    furnish: ["chest", "hides", "quern", "jars", "basket", "pegs", "cat"],
    looks: [
      { wall: "reed", floor: "earth", wear: 0.6, soot: 0.8 },
      { wall: "timber", floor: "rushes", wear: 0.35, soot: 0.55 },
      { wall: "timber", floor: "rushes", dado: "panel", wear: 0.15, soot: 0.3, furnish: ["tapestry", "lamp"] },
    ],
    colorways: [
      { name: "Smoked oak", wall: "#6a5440", trim: "#2e2218", floor: "#5e4a36", wood: "#4a3424", accent: "#8a2f2a" },
      { name: "Birch and red ochre", wall: "#9a8a70", trim: "#4a3020", floor: "#6e5a44", wood: "#5b4331", accent: "#a8442a" },
      { name: "Turf and wool", wall: "#5a5a40", trim: "#2e2a1e", floor: "#5a4a34", wood: "#4a3a28", accent: "#3f5a7a" },
    ],
  },
  {
    id: "medieval-cottage",
    styles: { table: "trestle" },
    clutter: ["grain", "bowl", "pot", "cloth", "toy"],
    label: "Peasant cottage",
    region: "England",
    period: "1250 – 1450",
    when: { start: { year: 1250 }, end: { year: 1450 } },
    basis: "archaeological",
    note: "Excavated crofts such as Wharram Percy: one or two bays, an open hearth mid-floor, wattle and daub on a timber frame, rushes strewn over beaten earth.",
    shapes: ["rect", "L"],
    size: [10, 7],
    door: "door",
    windowStyle: "shutter",
    fire: "firepit",
    smokehole: true,
    seating: "chair",
    sleep: "mat",
    trades: ["household", "weaver", "potter"],
    furnish: ["chest", "jars", "basket", "quern", "pegs", "sacks", "cat"],
    looks: [
      { wall: "mud", floor: "earth", wear: 0.7, soot: 0.8, windows: 0 },
      { wall: "timber", floor: "rushes", wear: 0.45, soot: 0.55 },
      { wall: "timber", floor: "rushes", wear: 0.2, soot: 0.3, furnish: ["tapestry", "lamp"] },
    ],
    colorways: [
      { name: "Limewash and oak", wall: "#d8cdb0", trim: "#4a3624", floor: "#6e5a40", wood: "#5a4230", accent: "#7a3a2a" },
      { name: "Raw daub", wall: "#a89070", trim: "#3a2a1c", floor: "#5e4c36", wood: "#4a3626", accent: "#4a6a3a" },
      { name: "Ochre-washed", wall: "#c8a060", trim: "#4a3020", floor: "#6a5238", wood: "#5a3e28", accent: "#2f4f6a" },
    ],
  },
];
