import type { InteriorProfile } from "./types";

export const modern: InteriorProfile[] = [
  {
    id: "art-deco-apartments",
    label: "Art deco apartment building",
    region: "New York, Paris, Shanghai, Bombay",
    period: "1925 – 1940",
    when: { start: { year: 1925 }, end: { year: 1940 } },
    basis: "documented",
    note: "Surviving lobbies and period photographs: terrazzo floors with brass inlay, fluted panelling and chevron friezes, a lift with a dial indicator, palms, club chairs; the flats behind had parquet, a sofa and a cabinet radio.",
    shapes: ["rect", "apse"],
    size: [16, 10],
    door: "door",
    windowStyle: "shutter",
    fire: "none",
    smokehole: false,
    seating: "chair",
    sleep: "none",
    trades: ["household"],
    furnish: ["elevator", "clock", "plant", "armchair", "armchair", "sofa", "lamp", "plant", "rug", "frame", "frame"],
    styles: { counter: "deco", table: "round", stool: "chair", shelf: "bookcase" },
    kits: { household: ["counter"] },
    clutter: ["paper", "flowers"],
    looks: [
      { wall: "plaster", floor: "tile", wear: 0.35, soot: 0 },
      { wall: "deco", floor: "terrazzo", wear: 0.15, soot: 0 },
      { wall: "deco", floor: "terrazzo", dado: "panel", wear: 0.02, soot: 0 },
    ],
    colorways: [
      { name: "Chrome and jade", wall: "#d8d0bc", trim: "#1e2a2a", floor: "#c8c0ac", wood: "#3a2a22", accent: "#2e7a6a" },
      { name: "Black lacquer and gold", wall: "#2e2a2a", trim: "#b8903a", floor: "#d8ccb4", wood: "#2a1e1a", accent: "#b8903a" },
      { name: "Peach and silver", wall: "#e8c4a8", trim: "#5a6a7a", floor: "#d8c8b8", wood: "#5a3a2a", accent: "#4a7aa8" },
    ],
    rooms: [
      { id: "lobby", label: "Lobby", role: "lobby", size: [16, 10] },
      {
        id: "flat",
        label: "Flat, living room",
        role: "entry",
        size: [12, 9],
        furnish: ["frame", "frame", "sofa", "armchair", "radio", "rug", "lamp", "shelf", "clock", "plant", "table"],
        kits: { household: [] },
        clutter: ["book", "paper", "cup", "flowers", "shoes"],
        looks: [{ wall: "wallpaper", floor: "plank" }, { wall: "deco", floor: "parquet" }, { wall: "deco", floor: "parquet", dado: "panel" }],
      },
      {
        id: "flat-bedroom",
        label: "Flat, bedroom",
        role: "sleep",
        size: [9, 7],
        sleep: "bed",
        furnish: ["frame", "dresser", "lamp", "rug", "clock", "chest"],
        kits: { household: [] },
        clutter: ["shoes", "book", "cloth"],
        looks: [{ wall: "wallpaper", floor: "plank" }, { wall: "deco", floor: "carpet" }, { wall: "deco", floor: "carpet", dado: "panel" }],
      },
    ],
  },
  {
    id: "farmhouse-1930s",
    label: "Farmhouse",
    region: "American Midwest",
    period: "1920 – 1945",
    when: { start: { year: 1920 }, end: { year: 1945 } },
    basis: "documented",
    note: "Farm Security Administration photographs and surviving houses: a parlour stove and a cabinet radio, wallpapered rooms, a kitchen range beside an oak icebox, linoleum, a pantry lined with preserves.",
    shapes: ["rect", "L"],
    size: [11, 8],
    door: "door",
    windowStyle: "shutter",
    fire: "stove",
    smokehole: false,
    seating: "chair",
    sleep: "none",
    trades: ["household"],
    furnish: ["sofa", "armchair", "radio", "clock", "rug", "lamp", "plant", "shelf", "cat", "frame", "frame"],
    styles: { stool: "chair", shelf: "hutch", table: "plain" },
    kits: { household: [] },
    clutter: ["book", "cup", "shoes", "toy", "yarn"],
    looks: [
      { wall: "plaster", floor: "plank", wear: 0.55, soot: 0.2 },
      { wall: "wallpaper", floor: "plank", wear: 0.3, soot: 0.1 },
      { wall: "wallpaper", floor: "parquet", dado: "panel", wear: 0.1, soot: 0.05 },
    ],
    colorways: [
      { name: "Butter and gingham", wall: "#e8d8a0", trim: "#6a4a30", floor: "#9a7048", wood: "#6a4428", accent: "#b83a3a" },
      { name: "Faded rose", wall: "#d8b0a8", trim: "#5a4a3a", floor: "#8a6a4a", wood: "#5a3e2a", accent: "#4a6a8a" },
      { name: "Sage", wall: "#b8c4a0", trim: "#4a3a2a", floor: "#8a6e4e", wood: "#6a4a30", accent: "#a85a2a" },
    ],
    rooms: [
      { id: "parlour", label: "Parlour", role: "entry", size: [11, 8] },
      {
        id: "kitchen",
        label: "Kitchen",
        role: "kitchen",
        size: [11, 8],
        fire: "none",
        furnish: ["shelf", "lamp", "basket", "jars", "cat"],
        kits: { household: ["range", "icebox"] },
        styles: { shelf: "open" },
        clutter: ["bowl", "pot", "cup", "cloth", "grain"],
        looks: [{ wall: "plaster", floor: "plank" }, { wall: "plaster", floor: "linoleum" }, { wall: "wallpaper", floor: "linoleum", dado: "panel" }],
      },
      {
        id: "dining",
        label: "Dining room",
        role: "hall",
        size: [10, 8],
        fire: "none",
        furnish: ["frame", "frame", "table", "shelf", "clock", "lamp", "rug", "plant"],
        clutter: ["cup", "flowers", "paper"],
      },
      {
        id: "pantry",
        label: "Pantry",
        role: "store",
        size: [6, 5],
        fire: "none",
        windowStyle: "none",
        seating: "floor",
        furnish: ["shelf", "sacks", "jars", "crate", "basket"],
        styles: { shelf: "open" },
        clutter: ["grain", "pot"],
      },
      {
        id: "bedroom",
        label: "Bedroom",
        role: "sleep",
        size: [10, 8],
        fire: "none",
        sleep: "bed",
        furnish: ["frame", "chest", "lamp", "rug", "clock", "shelf"],
        clutter: ["shoes", "cloth", "book"],
      },
    ],
  },
];
