import type { InteriorProfile } from "./types";

export const northAfrica: InteriorProfile[] = [
  {
    id: "maghrebi-dar",
    styles: { shelf: "niche", table: "round" },
    kits: { merchant: ["sacks", "jars", "basket", "crate"] },
    clutter: ["shoes", "cup", "cloth", "flowers", "bowl"],
    label: "Maghrebi courtyard house",
    region: "Morocco and the Maghreb",
    period: "14th – 19th century",
    when: { start: { year: 1300 }, end: { year: 1900 } },
    basis: "documented",
    note: "Fez and Marrakesh houses turn inward on a tiled court. Zellige dados, carved stucco friezes, cedar lattice windows, low divans and a charcoal kanoun are well recorded; the humble version is inferred.",
    shapes: ["courtyard", "rect", "L"],
    size: [12, 10],
    door: "door",
    windowStyle: "lattice",
    fire: "brazier",
    smokehole: false,
    seating: "floor",
    sleep: "mat",
    trades: ["household", "weaver", "merchant", "scholar", "potter"],
    furnish: ["divan", "cushions", "lantern", "jars", "chest", "plant", "basket", "shelf", "rug", "cat"],
    looks: [
      { wall: "mud", floor: "earth", wear: 0.5, soot: 0.25, windows: 1 },
      { wall: "plaster", floor: "tile", dado: "zellige", wear: 0.25, soot: 0.08 },
      { wall: "plaster", floor: "tile", dado: "zellige", wear: 0.03, soot: 0, furnish: ["divan", "lantern"] },
    ],
    colorways: [
      { name: "Fez cedar and cobalt", wall: "#ece2cf", trim: "#2f6f78", floor: "#6a8fa0", wood: "#8a5a36", accent: "#1f4f8f" },
      { name: "Marrakesh rose", wall: "#d9876a", trim: "#3d6b4a", floor: "#b85c3c", wood: "#6e4428", accent: "#c0582e" },
      { name: "Tetouan white and green", wall: "#f0ece0", trim: "#2e7a4f", floor: "#d8d0bc", wood: "#7a5234", accent: "#2e7a4f" },
      { name: "Saffron court", wall: "#e8c77a", trim: "#7a2e2a", floor: "#c9a36a", wood: "#6b4428", accent: "#2f5d8a" },
    ],
  },
  {
    id: "amazigh-house",
    styles: { shelf: "niche" },
    clutter: ["grain", "bowl", "yarn", "pot"],
    label: "Amazigh mountain house",
    region: "High Atlas",
    period: "18th – 20th century",
    when: { start: { year: 1700 }, end: { year: 1970 } },
    basis: "documented",
    note: "Rammed-earth rooms with a smoke-blackened ceiling, a floor loom and a hearth. Rugs and blankets woven in the house carry the colour; ethnographic photographs are the main source.",
    shapes: ["rect", "L"],
    size: [10, 8],
    door: "door",
    windowStyle: "shutter",
    fire: "firepit",
    smokehole: true,
    seating: "floor",
    sleep: "mat",
    trades: ["weaver", "household", "potter"],
    furnish: ["jars", "basket", "quern", "hides", "chest", "pegs", "rug", "cat"],
    looks: [
      { wall: "mud", floor: "earth", wear: 0.6, soot: 0.7, windows: 0 },
      { wall: "mud", floor: "earth", wear: 0.35, soot: 0.45, windows: 1 },
      { wall: "plaster", floor: "carpet", wear: 0.15, soot: 0.2, furnish: ["tapestry"] },
    ],
    colorways: [
      { name: "Red earth", wall: "#a85a3c", trim: "#4a2e22", floor: "#8a5438", wood: "#5a3a26", accent: "#b8302a" },
      { name: "Ochre pisé", wall: "#c89a62", trim: "#5a3a24", floor: "#9a7448", wood: "#5e4028", accent: "#d9a02a" },
      { name: "Grey stone valley", wall: "#8a8278", trim: "#3a342e", floor: "#7a6e60", wood: "#5a4632", accent: "#8a2e5a" },
    ],
  },
];
