import { bce } from "../history/dates";
import type { InteriorProfile } from "./types";

export const prehistoric: InteriorProfile[] = [
  {
    id: "catalhoyuk-house",
    clutter: ["grain", "bowl", "shards"],
    label: "Çatalhöyük house",
    region: "Central Anatolia",
    period: "7100 – 5950 BCE",
    when: { start: bce(7100), end: bce(5950) },
    basis: "archaeological",
    note: "Entered by ladder through the roof, which is also the smoke and light hole. Replastered white walls, red-painted panels, plastered bull horns and raised sleeping platforms are excavated; room contents are inferred.",
    shapes: ["rect"],
    size: [8, 7],
    door: "none",
    windowStyle: "none",
    fire: "firepit",
    smokehole: true,
    seating: "floor",
    sleep: "boxbed",
    trades: ["household", "weaver", "potter"],
    furnish: ["horns", "basket", "quern", "jars", "hides"],
    looks: [
      { wall: "mud", floor: "earth", wear: 0.5, soot: 0.5 },
      { wall: "plaster", floor: "earth", wear: 0.25, soot: 0.3 },
      { wall: "plaster", floor: "earth", dado: "stripe", wear: 0.1, soot: 0.15, furnish: ["horns"] },
    ],
    colorways: [
      { name: "Lime white and red ochre", wall: "#e6dccb", trim: "#8a3a2a", floor: "#b8a080", wood: "#6a4a30", accent: "#a8302a" },
      { name: "Clay tan", wall: "#c8a882", trim: "#5a3a2a", floor: "#a08462", wood: "#5e4230", accent: "#3a3a3a" },
      { name: "Smoke-dimmed", wall: "#a89a84", trim: "#3a2a22", floor: "#8a7660", wood: "#4a3626", accent: "#8a2a22" },
    ],
  },
  {
    id: "skara-brae-house",
    clutter: ["shards", "bowl", "grain"],
    label: "Skara Brae house",
    region: "Orkney",
    period: "3180 – 2500 BCE",
    when: { start: bce(3180), end: bce(2500) },
    basis: "archaeological",
    note: "Stone-built rooms with a square central hearth, a stone dresser facing the low doorway, and stone box beds either side. The roof covering and any textiles are unknown.",
    shapes: ["round", "rect"],
    size: [9, 9],
    door: "opening",
    windowStyle: "none",
    fire: "firepit",
    smokehole: true,
    seating: "floor",
    sleep: "boxbed",
    trades: ["household", "hunter", "potter"],
    furnish: ["dresser", "jars", "hides", "basket", "quern"],
    looks: [
      { wall: "stone", floor: "earth", wear: 0.5, soot: 0.5 },
      { wall: "stone", floor: "flag", wear: 0.3, soot: 0.35 },
      { wall: "stone", floor: "flag", wear: 0.15, soot: 0.2, furnish: ["hides"] },
    ],
    colorways: [
      { name: "Orkney flagstone", wall: "#8a8478", trim: "#4a4640", floor: "#6e6a60", wood: "#5a4a38", accent: "#8a6a3a" },
      { name: "Sandstone", wall: "#a8906a", trim: "#5a4a36", floor: "#8a7658", wood: "#5e4a34", accent: "#6a3a2a" },
    ],
  },
  {
    id: "lbk-longhouse",
    clutter: ["grain", "shards", "pot"],
    label: "Linear Pottery longhouse",
    region: "Central Europe",
    period: "5500 – 4900 BCE",
    when: { start: bce(5500), end: bce(4900) },
    basis: "archaeological",
    note: "Post-built timber halls up to 40 m long with wattle-and-daub walls; loom weights and querns are common finds. Hearth positions and the interior division are inferred from postholes.",
    shapes: ["rect"],
    size: [18, 7],
    door: "opening",
    windowStyle: "none",
    fire: "firepit",
    smokehole: true,
    seating: "floor",
    sleep: "mat",
    trades: ["household", "weaver", "potter"],
    furnish: ["quern", "jars", "basket", "hides", "pegs"],
    looks: [
      { wall: "mud", floor: "earth", wear: 0.55, soot: 0.6 },
      { wall: "timber", floor: "earth", wear: 0.35, soot: 0.45 },
      { wall: "timber", floor: "rushes", wear: 0.2, soot: 0.3 },
    ],
    colorways: [
      { name: "Loess daub", wall: "#b89a72", trim: "#4a3624", floor: "#8a7050", wood: "#5a4230", accent: "#8a3a2a" },
      { name: "Weathered oak", wall: "#8a7a62", trim: "#3a2c20", floor: "#6a5a44", wood: "#4a3a2a", accent: "#4a5a3a" },
    ],
  },
];
