import type { InteriorProfile } from "./types";

/**
 * Places that serve drink, one profile per culture and era. A new one needs:
 *  - a profile here: its rooms, finishes, `venues` it houses and `regulars`;
 *    the taproom's `program` is `serve`, and its `seating` lays it out
 *    (`chair` for boards and forms, `floor` for low tables and cushions);
 *  - `styles.bar`, the drink served, which picks the counter, the stock behind
 *    it and what stands on the tables (pixel.ts, under "bar", "casks" and
 *    `tavernBoard`). Reuse a drink where one fits; a new one is three cases;
 *  - a line in `PUBLIC` (select.ts) for where and when it stands.
 */
export const taverns: InteriorProfile[] = [
  {
    id: "english-tavern",
    uses: ["venue.tavern", "venue.alehouse"],
    regulars: { hours: [17, 23], fill: 0.3 },
    rooms: [
      {
        id: "taproom",
        program: "serve",
        label: "Taproom",
        role: "entry",
        size: [14, 10],
        furnish: ["tankards", "tally", "plates", "clock", "horns", "frame", "tankards", "pegs", "sacks", "cat"],
        clutter: ["cup", "cup", "bowl", "shoes", "pipe"],
      },
      {
        id: "parlour",
        label: "Parlour",
        role: "hall",
        size: [8, 7],
        trades: ["household"],
        seating: "chair",
        furnish: ["frame", "frame", "plates", "lamp", "rug", "dresser", "plant"],
        kits: { household: [] },
        looks: [{ floor: "plank" }, { floor: "plank", wall: "panel" }, { floor: "carpet", wall: "panel" }],
        clutter: ["cup", "book", "pipe"],
      },
      {
        id: "kitchen",
        label: "Kitchen",
        role: "kitchen",
        size: [8, 7],
        trades: ["household"],
        furnish: ["shelf", "jars", "firewood", "basket", "sacks", "pegs", "broom"],
        kits: { household: [] },
        clutter: ["pot", "bowl", "grain"],
      },
      {
        id: "chamber",
        label: "Chamber",
        role: "sleep",
        size: [7, 6],
        trades: ["household"],
        fire: "none",
        sleep: "bed",
        seating: "floor",
        kits: { household: [] },
        furnish: ["chest", "frame", "lamp", "pegs"],
        looks: [{ floor: "plank" }, { floor: "plank" }, { floor: "plank", wall: "panel" }],
        clutter: ["cloth", "shoes"],
      },
      {
        id: "cellar",
        label: "Cellar",
        role: "store",
        size: [8, 5],
        trades: ["household"],
        fire: "none",
        windowStyle: "none",
        seating: "floor",
        furnish: ["casks", "casks", "crate", "sacks", "jars"],
        kits: { household: [] },
        looks: [{ wall: "stone", floor: "earth" }, { wall: "stone", floor: "flag" }, { wall: "stone", floor: "flag" }],
        clutter: ["shards"],
      },
    ],
    styles: { stool: "stool", shelf: "hutch" },
    label: "Northern European tavern",
    region: "Britain and the North Sea lands",
    period: "1450 – 1850",
    when: { start: { year: 1450 }, end: { year: 1850 } },
    basis: "documented",
    note: "English probate inventories, Peter Clark's alehouse studies and the Dutch tavern scenes of Steen and van Ostade give the furniture: forms, settles, a fire, casks on a stillage, pewter pots. The bar as a counter is later than most of the period; here it stands for the tap-room hatch and serving board.",
    shapes: ["rect"],
    size: [14, 10],
    door: "door",
    windowStyle: "shutter",
    fire: "hearth",
    smokehole: false,
    seating: "chair",
    sleep: "none",
    trades: ["host"],
    furnish: ["sacks"],
    looks: [
      { wall: "timber", floor: "flag", wear: 0.6, soot: 0.55 },
      { wall: "plaster", dado: "panel", floor: "flag", wear: 0.4, soot: 0.4 },
      { wall: "plaster", dado: "panel", floor: "plank", wear: 0.2, soot: 0.25 },
    ],
    colorways: [
      { name: "Smoked oak", wall: "#b89a6c", trim: "#4a3020", floor: "#7d7466", wood: "#6a4528", accent: "#8a2a22" },
      { name: "Red Lion", wall: "#a8644a", trim: "#3a2618", floor: "#857a6a", wood: "#5a3a22", accent: "#2f5a3a" },
      { name: "Whitewash and pewter", wall: "#d8cfb8", trim: "#3a3634", floor: "#958b7c", wood: "#5e4430", accent: "#2f4a7a" },
    ],
  },
  {
    id: "izakaya",
    uses: ["venue.izakaya"],
    regulars: { hours: [17, 24], fill: 0.35 },
    rooms: [
      {
        id: "mise",
        program: "serve",
        label: "Mise",
        role: "entry",
        size: [13, 10],
        furnish: ["tally", "tally", "frame", "lantern", "lantern", "jars", "cat"],
        clutter: ["cup", "cup", "shoes", "bowl"],
      },
      {
        id: "daidokoro",
        label: "Daidokoro",
        role: "kitchen",
        size: [7, 7],
        trades: ["household"],
        fire: "irori",
        furnish: ["jars", "basket", "firewood", "shelf", "sacks"],
        kits: { household: [] },
        looks: [{ floor: "earth", wall: "mud" }, { floor: "earth", wall: "mud" }, { floor: "plank", wall: "mud" }],
        clutter: ["pot", "bowl"],
      },
      {
        id: "nando",
        label: "Nando",
        role: "sleep",
        size: [6, 6],
        trades: ["household"],
        sleep: "mat",
        windowStyle: "none",
        kits: { household: [] },
        furnish: ["chest", "shelf", "lantern"],
        clutter: ["cloth"],
      },
      {
        id: "kura",
        label: "Kura",
        role: "store",
        size: [7, 5],
        trades: ["household"],
        windowStyle: "none",
        furnish: ["casks", "casks", "jars", "sacks"],
        kits: { household: [] },
        looks: [{ wall: "mud", floor: "earth" }, { wall: "mud", floor: "earth" }, { wall: "plaster", floor: "plank" }],
        clutter: ["shards"],
      },
    ],
    styles: { bar: "sake", frame: "scroll", shelf: "tansu" },
    label: "Izakaya",
    region: "Japan",
    period: "1700 – present",
    when: { start: { year: 1700 }, end: { year: 2100 } },
    basis: "reconstructed",
    note: "Edo sake shops that let customers drink on the spot, known from ukiyo-e and gesaku fiction: straw-wrapped casks, a counter, menu slips on the wall, red lanterns. Drinkers often sat on benches or barrels on an earth floor; the raised tatami here is the later and grander arrangement.",
    shapes: ["rect"],
    size: [13, 10],
    door: "door",
    windowStyle: "shoji",
    fire: "none",
    smokehole: false,
    seating: "floor",
    sleep: "none",
    trades: ["host"],
    furnish: ["lantern"],
    looks: [
      { wall: "mud", floor: "mat", wear: 0.45, soot: 0.4 },
      { wall: "plaster", floor: "mat", wear: 0.25, soot: 0.25 },
      { wall: "shoji", floor: "mat", wear: 0.08, soot: 0.1 },
    ],
    colorways: [
      { name: "Cedar and lantern red", wall: "#b89a72", trim: "#3d2e24", floor: "#a88a5a", wood: "#5a3e2a", accent: "#a8302a" },
      { name: "Kurobi soot", wall: "#8a7a64", trim: "#1e1814", floor: "#8a7048", wood: "#3a2a1e", accent: "#2f4a7a" },
      { name: "Pale hinoki", wall: "#d8c8a0", trim: "#6b4a30", floor: "#c0a878", wood: "#9a7a52", accent: "#8a2a2a" },
    ],
  },
  {
    id: "kahvehane",
    uses: ["venue.kahvehane", "venue.coffee-house"],
    regulars: { hours: [16, 23], fill: 0.35 },
    rooms: [
      {
        id: "kahve",
        program: "serve",
        label: "Coffee room",
        role: "entry",
        size: [13, 10],
        furnish: ["divan", "divan", "divan", "tally", "plates", "plates", "frame", "lantern", "cat"],
        clutter: ["cup", "cup", "shoes", "book"],
      },
      {
        id: "ocak",
        label: "Roasting room",
        role: "kitchen",
        size: [7, 6],
        trades: ["household"],
        fire: "brazier",
        furnish: ["sacks", "sacks", "jars", "shelf", "basket"],
        kits: { household: ["quern"] },
        looks: [{ floor: "earth" }, { floor: "flag" }, { floor: "tile" }],
        clutter: ["grain", "pot"],
      },
      {
        id: "oda",
        label: "Oda",
        role: "sleep",
        size: [6, 6],
        trades: ["household"],
        sleep: "mat",
        kits: { household: [] },
        furnish: ["chest", "cushions", "rug", "lamp"],
        clutter: ["cloth"],
      },
    ],
    styles: { bar: "coffee", frame: "levha", shelf: "niche" },
    label: "Kahvehane",
    region: "Maghreb to Persia",
    period: "1510 – present",
    when: { start: { year: 1510 }, end: { year: 2100 } },
    basis: "documented",
    note: "Coffee houses opened in Cairo and Mecca by the 1510s and in Istanbul in 1554, recorded by travellers and in miniatures: raised benches round the walls, a hearth where the coffee is made in long-handled pots, cups on shelves, Iznik tiles and calligraphy. Water pipes are later than the first houses.",
    shapes: ["rect"],
    size: [13, 10],
    door: "door",
    windowStyle: "lattice",
    fire: "none",
    smokehole: false,
    seating: "floor",
    sleep: "none",
    trades: ["host"],
    furnish: ["lantern"],
    looks: [
      { wall: "plaster", floor: "earth", wear: 0.5, soot: 0.35 },
      { wall: "plaster", dado: "zellige", floor: "flag", wear: 0.3, soot: 0.2 },
      { wall: "plaster", dado: "zellige", floor: "carpet", wear: 0.1, soot: 0.1 },
    ],
    colorways: [
      { name: "Iznik blue", wall: "#e2d8c4", trim: "#3a3228", floor: "#a89478", wood: "#5e4430", accent: "#2f5a9a" },
      { name: "Coral and turquoise", wall: "#d8c8ac", trim: "#4a3626", floor: "#9a8468", wood: "#6a4a30", accent: "#b8442e" },
      { name: "Smoked walnut", wall: "#b8a07c", trim: "#2e241c", floor: "#8a7458", wood: "#4a3222", accent: "#2f7a6a" },
    ],
  },
];

/** Places people gather round a fire rather than are served: one room,
 * `program: "gather"`, the seats ringed by `seating` (`floor` on the ground,
 * `chair` a bench against the wall). Styles carry the culture as above. */
export const gatherings: InteriorProfile[] = [
  {
    id: "sweat-lodge",
    uses: ["venue.sweat-lodge"],
    program: "gather",
    regulars: { hours: [17, 22], fill: 0.6 },
    styles: { firepit: "stones", cushions: "boughs" },
    label: "Sweat lodge",
    region: "North American plains and woodlands",
    period: "3000 BCE – present",
    when: { start: { year: -3000 }, end: { year: 2100 } },
    basis: "documented",
    note: "The Lakota inipi as described to Joseph Epes Brown and in later ethnography: a low dome of bent willow under hides, stones heated outside and carried to a pit in the middle, water poured on them in the dark, sage spread to sit on. Practice varied widely across nations; this is one tradition standing for many.",
    shapes: ["round"],
    size: [8, 8],
    door: "flap",
    windowStyle: "none",
    fire: "firepit",
    smokehole: false,
    seating: "floor",
    sleep: "none",
    trades: ["household"],
    furnish: ["basket"],
    looks: [
      { wall: "hide", floor: "earth", wear: 0.4, soot: 0.3 },
      { wall: "hide", floor: "earth", wear: 0.3, soot: 0.2 },
      { wall: "hide", floor: "earth", wear: 0.2, soot: 0.1 },
    ],
    colorways: [
      { name: "Buffalo hide", wall: "#8a6a4a", trim: "#3a2a1e", floor: "#7a5e40", wood: "#6a5034", accent: "#a8302a" },
      { name: "Canvas and willow", wall: "#b8a888", trim: "#4a3a28", floor: "#8a7050", wood: "#7a6040", accent: "#2f5a8a" },
    ],
  },
  {
    id: "kiva",
    uses: ["venue.kiva"],
    program: "gather",
    regulars: { hours: [19, 23], fill: 0.5 },
    label: "Kiva",
    region: "Ancestral Puebloan Southwest",
    period: "700 – present",
    when: { start: { year: 700 }, end: { year: 2100 } },
    basis: "archaeological",
    note: "Round kivas excavated at Mesa Verde and Chaco: entered by a ladder through the roof, a fire pit in the floor with the sipapu beside it, a plastered bench all round the wall. The painted band follows the murals at Kuaua and Awatovi; the deflector and ventilator shaft are left out.",
    shapes: ["round"],
    size: [11, 11],
    door: "none",
    windowStyle: "none",
    fire: "firepit",
    smokehole: true,
    seating: "chair",
    sleep: "none",
    trades: ["household"],
    furnish: ["sipapu", "jars"],
    looks: [
      { wall: "mud", floor: "earth", wear: 0.4, soot: 0.5 },
      { wall: "mud", dado: "stripe", floor: "earth", wear: 0.25, soot: 0.35 },
      { wall: "mud", dado: "stripe", floor: "earth", wear: 0.1, soot: 0.2 },
    ],
    colorways: [
      { name: "Adobe and ochre", wall: "#c8a07a", trim: "#5a3a26", floor: "#9a7a58", wood: "#6a4a30", accent: "#a8402a" },
      { name: "Gypsum white", wall: "#ddd0bc", trim: "#4a3a2e", floor: "#a08a6a", wood: "#5e4430", accent: "#2f7a7a" },
    ],
  },
  {
    id: "temazcal",
    uses: ["venue.temazcal", "venue.sweat-lodge"],
    program: "gather",
    regulars: { hours: [16, 20], fill: 0.6 },
    styles: { cushions: "petate", hearth: "firebox" },
    label: "Temazcal",
    region: "Mesoamerica",
    period: "1200 BCE – present",
    when: { start: { year: -1200 }, end: { year: 2100 } },
    basis: "documented",
    note: "Sweat baths of stone and adobe, known from Maya sites such as Piedras Negras and the Codex Magliabechiano: a low vaulted room, a firebox built into one wall that heats it from outside, water thrown on the hot wall, bathers lying on palm mats. The firebox stands here as a hearth in the back wall.",
    shapes: ["rect"],
    size: [7, 6],
    door: "curtain",
    windowStyle: "none",
    fire: "hearth",
    smokehole: false,
    seating: "floor",
    sleep: "none",
    trades: ["household"],
    furnish: ["jars"],
    looks: [
      { wall: "stone", floor: "earth", wear: 0.4, soot: 0.6 },
      { wall: "mud", floor: "earth", wear: 0.3, soot: 0.5 },
      { wall: "plaster", floor: "flag", wear: 0.2, soot: 0.4 },
    ],
    colorways: [
      { name: "Volcanic stone", wall: "#7a6a5e", trim: "#3a2e28", floor: "#8a7258", wood: "#5a4030", accent: "#2f7a6a" },
      { name: "Lime and ochre", wall: "#d0b890", trim: "#5a3a26", floor: "#9a7a58", wood: "#6a4a30", accent: "#a8402a" },
    ],
  },
];

/** Bath houses: rooms in the order bathers pass through them, each a gather
 * room round its water (`pool`, `styles.pool` hot, cold or a wooden `tub`)
 * or its heated stone (`slab`), with `basin`s along the wall. */
export const baths: InteriorProfile[] = [
  {
    id: "roman-baths",
    uses: ["venue.bath-house"],
    regulars: { hours: [13, 18], fill: 0.45 },
    rooms: [
      { id: "apodyterium", label: "Apodyterium", role: "entry", program: "gather", size: [8, 8], seating: "chair", fire: "none", furnish: ["shelf", "shelf", "lamp"], clutter: ["shoes", "cloth"] },
      { id: "frigidarium", label: "Frigidarium", role: "hall", program: "gather", size: [9, 9], seating: "chair", fire: "none", furnish: ["pool"], styles: { pool: "cold" }, clutter: ["cloth"] },
      { id: "tepidarium", label: "Tepidarium", role: "hall", program: "gather", size: [8, 8], seating: "chair", fire: "brazier", furnish: ["lamp"], clutter: ["cloth"] },
      { id: "caldarium", label: "Caldarium", role: "hall", program: "gather", size: [10, 9], seating: "chair", fire: "none", furnish: ["pool", "basin"], clutter: ["cloth"] },
    ],
    styles: { shelf: "niche" },
    label: "Roman baths",
    region: "Roman Empire",
    period: "200 BCE – 640 CE",
    when: { start: { year: -200 }, end: { year: 640 } },
    basis: "archaeological",
    note: "The small public balneum as at the Stabian and Forum Baths of Pompeii: changing room with wall niches, cold plunge, warm room with its bronze brazier, hot room with a heated pool and the labrum basin, walked through in a row. Floors over a hypocaust; the furnace and the exercise court are left out. Kept up in the west until the sixth century and in the east until the Arab conquests.",
    shapes: ["rect"],
    size: [8, 8],
    door: "door",
    windowStyle: "shutter",
    fire: "none",
    smokehole: false,
    seating: "chair",
    sleep: "none",
    trades: ["household"],
    furnish: [],
    looks: [
      { wall: "plaster", floor: "flag", wear: 0.4, soot: 0.2 },
      { wall: "plaster", dado: "panel", floor: "tile", wear: 0.2, soot: 0.1 },
      { wall: "stripe", dado: "panel", floor: "tile", wear: 0.05, soot: 0.05 },
    ],
    colorways: [
      { name: "Pompeian red", wall: "#b04a32", trim: "#e8dcc4", floor: "#d8ccb4", wood: "#6a4a30", accent: "#e0b040" },
      { name: "Ochre and black", wall: "#d0a050", trim: "#2a2420", floor: "#c8bca4", wood: "#5a3e2a", accent: "#2f6a7a" },
      { name: "Marble white", wall: "#e4dcd0", trim: "#7a6e64", floor: "#dcd4c8", wood: "#6a5040", accent: "#8a2a2a" },
    ],
  },
  {
    id: "hammam",
    uses: ["venue.hammam", "venue.bath-house"],
    regulars: { hours: [7, 19], fill: 0.45 },
    rooms: [
      { id: "camekan", label: "Camekan", role: "entry", program: "gather", size: [10, 9], seating: "chair", fire: "none", furnish: ["pool", "lamp", "plates"], styles: { pool: "cold" }, clutter: ["shoes", "shoes", "cloth"] },
      { id: "sogukluk", label: "Soğukluk", role: "hall", program: "gather", size: [6, 7], seating: "chair", fire: "none", furnish: ["basin"], clutter: ["cloth"] },
      { id: "sicaklik", label: "Sıcaklık", role: "hall", program: "gather", size: [10, 10], shapes: ["round"], seating: "chair", fire: "none", furnish: ["slab", "basin"], clutter: ["cloth"] },
    ],
    label: "Hammam",
    region: "Islamic world, al-Andalus to Persia",
    period: "660 – present",
    when: { start: { year: 660 }, end: { year: 2100 } },
    basis: "documented",
    note: "The bath as built from Umayyad Syria to Ottoman Istanbul: an entrance hall with a fountain and raised benches for undressing, a cool passage, and the domed hot room with its heated marble platform and basins round the walls, lit through glass in the dome. Women's hours and separate halls are not shown.",
    shapes: ["rect"],
    size: [10, 9],
    door: "door",
    windowStyle: "none",
    fire: "none",
    smokehole: true,
    seating: "chair",
    sleep: "none",
    trades: ["household"],
    furnish: [],
    looks: [
      { wall: "plaster", floor: "flag", wear: 0.4, soot: 0.2 },
      { wall: "plaster", dado: "zellige", floor: "tile", wear: 0.2, soot: 0.1 },
      { wall: "plaster", dado: "zellige", floor: "tile", wear: 0.05, soot: 0.05 },
    ],
    colorways: [
      { name: "Marble and turquoise", wall: "#e4ddd0", trim: "#6a6258", floor: "#d4ccc0", wood: "#5e4430", accent: "#2f7a8a" },
      { name: "Limewash and terracotta", wall: "#d8c8b0", trim: "#5a4030", floor: "#c4ae96", wood: "#6a4a30", accent: "#b8442e" },
    ],
  },
  {
    id: "sento",
    uses: ["venue.sento", "venue.bath-house"],
    regulars: { hours: [15, 23], fill: 0.45 },
    rooms: [
      { id: "datsuiba", label: "Datsuiba", role: "entry", program: "gather", size: [8, 8], seating: "chair", fire: "none", furnish: ["shelf", "shelf", "basket", "lantern"], clutter: ["shoes", "cloth"] },
      { id: "yuya", label: "Yuya", role: "hall", program: "gather", size: [9, 8], seating: "chair", fire: "none", furnish: ["pool", "basin", "lantern"], styles: { pool: "tub" }, clutter: ["cloth", "bowl"] },
    ],
    styles: { shelf: "tansu" },
    label: "Sento",
    region: "Japan",
    period: "1590 – present",
    when: { start: { year: 1590 }, end: { year: 2100 } },
    basis: "documented",
    note: "Edo public baths from ukiyo-e and Shikitei Sanba's Ukiyoburo: a wooden-floored changing room with shelves for clothes, a washing floor, and the deep hot tub behind its low doorway. The tub is drawn open; the low zakuro-guchi screen over it, and the tiled walls and Mount Fuji murals of the twentieth century, are left out.",
    shapes: ["rect"],
    size: [8, 8],
    door: "door",
    windowStyle: "lattice",
    fire: "none",
    smokehole: false,
    seating: "chair",
    sleep: "none",
    trades: ["household"],
    furnish: [],
    looks: [
      { wall: "plaster", floor: "plank", wear: 0.4, soot: 0.2 },
      { wall: "plaster", floor: "plank", wear: 0.25, soot: 0.1 },
      { wall: "shoji", floor: "plank", wear: 0.1, soot: 0.05 },
    ],
    colorways: [
      { name: "Cedar and steam", wall: "#c8b898", trim: "#4a3626", floor: "#b09670", wood: "#7a5a3a", accent: "#2f4a7a" },
      { name: "Dark pine", wall: "#a89878", trim: "#2e241c", floor: "#8a7050", wood: "#5a3e2a", accent: "#a8302a" },
    ],
  },
];
