import type { InteriorProfile } from "./types";

export const southAsia: InteriorProfile[] = [
  {
    id: "rajasthani-haveli",
    styles: { frame: "miniature", shelf: "niche", bed: "charpai" },
    clutter: ["shoes", "cup", "flowers", "cloth"],
    label: "Haveli room",
    region: "Rajasthan",
    period: "1700 – 1900",
    when: { start: { year: 1700 }, end: { year: 1900 } },
    basis: "documented",
    note: "Havelis of Shekhawati and Jaisalmer open onto a chowk; painted walls, stone jali screens, floor seating on a gaddi with bolsters, and a household shrine are well recorded.",
    shapes: ["courtyard", "rect", "L"],
    size: [12, 10],
    door: "door",
    windowStyle: "lattice",
    fire: "brazier",
    smokehole: false,
    seating: "floor",
    sleep: "bed",
    trades: ["household", "merchant", "weaver", "scholar"],
    furnish: ["divan", "shrine", "cushions", "lantern", "chest", "jars", "plant", "shelf", "rug", "cat", "frame", "frame"],
    looks: [
      { wall: "mud", floor: "earth", wear: 0.5, soot: 0.2 },
      { wall: "plaster", floor: "flag", dado: "stripe", wear: 0.25, soot: 0.05 },
      { wall: "panel", floor: "carpet", dado: "zellige", wear: 0.03, soot: 0, furnish: ["tapestry", "divan"] },
    ],
    colorways: [
      { name: "Indigo and lime", wall: "#dfe4e8", trim: "#2a3a7a", floor: "#c8b89a", wood: "#6a4428", accent: "#2f4fa8" },
      { name: "Saffron", wall: "#e8b85a", trim: "#8a2a1e", floor: "#b8905a", wood: "#6a3e22", accent: "#a82a4a" },
      { name: "Pink sandstone", wall: "#d8a08a", trim: "#6a3a2a", floor: "#c08870", wood: "#5a3a26", accent: "#2e7a6a" },
    ],
  },
  {
    id: "gangetic-village-house",
    styles: { shelf: "niche", bed: "charpai" },
    kits: { merchant: ["sacks", "jars", "basket"] },
    clutter: ["grain", "pot", "bowl", "shoes", "toy"],
    label: "Village house",
    region: "Gangetic plain",
    period: "1800 – 1950",
    when: { start: { year: 1800 }, end: { year: 1950 } },
    basis: "documented",
    note: "Mud walls and floor renewed with a clay and cow-dung wash, a clay chulha, a string charpai, clay storage jars and a hand quern. Painted wall motifs vary by region.",
    shapes: ["rect", "L", "courtyard"],
    size: [10, 8],
    door: "door",
    windowStyle: "shutter",
    fire: "brazier",
    smokehole: false,
    seating: "floor",
    sleep: "bed",
    trades: ["household", "weaver", "potter"],
    furnish: ["jars", "quern", "shrine", "basket", "sacks", "lantern", "pegs", "cat"],
    looks: [
      { wall: "mud", floor: "earth", wear: 0.55, soot: 0.45, windows: 0 },
      { wall: "mud", floor: "earth", wear: 0.3, soot: 0.3 },
      { wall: "plaster", floor: "flag", dado: "stripe", wear: 0.1, soot: 0.1, furnish: ["tapestry"] },
    ],
    colorways: [
      { name: "Ochre mud", wall: "#b8885a", trim: "#5a3a24", floor: "#9a7048", wood: "#5a3e28", accent: "#b8302a" },
      { name: "White lime", wall: "#e4dccb", trim: "#6a4a30", floor: "#a88a62", wood: "#6a4a30", accent: "#2f5a8a" },
      { name: "Indigo wash", wall: "#8aa0c0", trim: "#3a3a5a", floor: "#9a8060", wood: "#5a4028", accent: "#d8a02a" },
    ],
  },
];
