import { bce } from "../history/dates";
import type { InteriorProfile } from "./types";

export const tents: InteriorProfile[] = [
  {
    id: "bedouin-tent",
    clutter: ["cup", "cloth", "bowl"],
    label: "Bedouin goat-hair tent",
    region: "Arabia and the Levant",
    period: "Long practised; recorded 1800 – 1960",
    when: { start: { year: -1000 }, end: { year: 1960 } },
    basis: "documented",
    note: "The bayt al-sha'r: woven goat-hair strips on poles, divided by a patterned curtain, carpets and cushions on the sand, a coffee hearth with brass pots at the men's side.",
    shapes: ["rect"],
    size: [14, 7],
    door: "opening",
    windowStyle: "none",
    fire: "firepit",
    smokehole: false,
    seating: "floor",
    sleep: "mat",
    pole: true,
    trades: ["household", "weaver", "merchant"],
    furnish: ["cushions", "lowtable", "hides", "basket", "jars", "lantern", "rug"],
    looks: [
      { wall: "hide", floor: "sand", wear: 0.45, soot: 0.2 },
      { wall: "stripe", floor: "carpet", wear: 0.25, soot: 0.1 },
      { wall: "stripe", floor: "carpet", wear: 0.1, soot: 0.05, furnish: ["cushions", "divan"] },
    ],
    colorways: [
      { name: "Black goat hair", wall: "#2e2824", trim: "#7a2a24", floor: "#c9a878", wood: "#6a4a30", accent: "#b0302a" },
      { name: "Brown hair, gold weft", wall: "#4a3a2e", trim: "#d6b04a", floor: "#d0b488", wood: "#6a4a30", accent: "#d6b04a" },
    ],
  },
  {
    id: "mongol-ger",
    styles: { chest: "painted" },
    clutter: ["cup", "bowl", "cloth", "toy"],
    label: "Mongol ger",
    region: "Mongolian steppe",
    period: "1200 – present",
    when: { start: { year: 1200 } },
    basis: "documented",
    note: "Felt over a lattice wall, a crown ring open to the sky, two painted posts, beds and chests round the walls, the altar opposite the door. An iron stove replaced the open hearth from the 19th century.",
    shapes: ["round"],
    size: [10, 10],
    door: "door",
    windowStyle: "none",
    fire: "stove",
    smokehole: true,
    seating: "floor",
    sleep: "bed",
    pole: true,
    trades: ["household", "hunter", "weaver"],
    furnish: ["shrine", "chest", "cushions", "lowtable", "hides", "basket", "rug"],
    looks: [
      { wall: "felt", floor: "earth", wear: 0.45, soot: 0.35 },
      { wall: "felt", floor: "carpet", wear: 0.2, soot: 0.15 },
      { wall: "felt", floor: "carpet", wear: 0.05, soot: 0.05, furnish: ["chest", "tapestry"] },
    ],
    colorways: [
      { name: "White felt, orange paint", wall: "#e4dccb", trim: "#c8581e", floor: "#a8402a", wood: "#c8581e", accent: "#2f5aa8" },
      { name: "Blue silk", wall: "#d8d4c4", trim: "#2a4a8a", floor: "#8a2a2a", wood: "#b8502a", accent: "#2a6aa8" },
      { name: "Smoked felt", wall: "#a8a090", trim: "#6a3a22", floor: "#6a4a3a", wood: "#8a4a26", accent: "#8a2a2a" },
    ],
  },
  {
    id: "plains-tipi",
    clutter: ["bowl", "cloth"],
    label: "Plains tipi",
    region: "Great Plains",
    period: "1700 – 1890",
    when: { start: { year: 1700 }, end: { year: 1890 } },
    basis: "documented",
    note: "Bison-hide cover on a pole cone, a fire at the centre under the smoke flaps, a hide liner painted with the owner's designs, robes and parfleche cases round the edge.",
    shapes: ["round"],
    size: [9, 9],
    door: "flap",
    windowStyle: "none",
    fire: "firepit",
    smokehole: true,
    seating: "floor",
    sleep: "mat",
    trades: ["household", "hunter", "weaver"],
    furnish: ["hides", "pack", "basket", "pegs", "coolamon"],
    looks: [
      { wall: "hide", floor: "earth", wear: 0.45, soot: 0.5 },
      { wall: "hide", floor: "earth", wear: 0.25, soot: 0.35, furnish: ["hides"] },
      { wall: "hide", floor: "earth", dado: "stripe", wear: 0.1, soot: 0.2, furnish: ["hides", "hides"] },
    ],
    colorways: [
      { name: "Bison hide", wall: "#c8b08a", trim: "#5a3a24", floor: "#7a6448", wood: "#6a4a30", accent: "#a8302a" },
      { name: "Smoke-tanned", wall: "#a88a62", trim: "#4a2e1e", floor: "#6e5a40", wood: "#5a3e28", accent: "#2f4f8a" },
    ],
  },
  {
    id: "roman-army-tent",
    clutter: ["cup", "cloth", "bowl"],
    label: "Roman army tent",
    region: "Roman frontiers",
    period: "1st – 3rd century",
    when: { start: bce(50), end: { year: 300 } },
    basis: "archaeological",
    note: "The papilio of an eight-man contubernium: goatskin panels sewn together, found at Vindolanda. Bedrolls, kit bundles and a lamp; cooking was done outside.",
    shapes: ["rect"],
    size: [8, 6],
    door: "flap",
    windowStyle: "none",
    fire: "none",
    smokehole: false,
    seating: "floor",
    sleep: "mat",
    pole: true,
    trades: ["household"],
    furnish: ["pack", "pack", "lantern", "jars", "chest"],
    looks: [
      { wall: "hide", floor: "earth", wear: 0.5, soot: 0.05 },
      { wall: "hide", floor: "earth", wear: 0.3, soot: 0.05 },
      { wall: "hide", floor: "mat", wear: 0.15, soot: 0, furnish: ["chest"] },
    ],
    colorways: [
      { name: "Goatskin, legion red", wall: "#a8845a", trim: "#4a3020", floor: "#6a6040", wood: "#6a4a30", accent: "#a8302a" },
      { name: "Weathered leather", wall: "#8a6a48", trim: "#3a2618", floor: "#5e5a3e", wood: "#5a3e28", accent: "#c8a040" },
    ],
  },
  {
    id: "modern-tent",
    clutter: ["cup", "paper", "book", "shoes"],
    label: "Camping tent",
    region: "Anywhere",
    period: "1970 – present",
    when: { start: { year: 1970 } },
    basis: "modern",
    note: "A nylon dome: a sewn-in groundsheet, sleeping bags and pads, a battery lantern, packs and a cool box. The stove stays in the porch.",
    shapes: ["oval", "rect"],
    size: [7, 6],
    door: "flap",
    windowStyle: "none",
    fire: "none",
    smokehole: false,
    seating: "floor",
    sleep: "mat",
    trades: ["household"],
    furnish: ["pack", "lantern", "crate", "pack"],
    looks: [
      { wall: "canvas", floor: "mat", wear: 0.35, soot: 0 },
      { wall: "canvas", floor: "mat", wear: 0.15, soot: 0 },
      { wall: "canvas", floor: "carpet", wear: 0.02, soot: 0, furnish: ["cushions", "lantern"] },
    ],
    colorways: [
      { name: "Forest green", wall: "#4a7a4a", trim: "#2a3a2a", floor: "#5a6a7a", wood: "#6a6a6a", accent: "#d8702a" },
      { name: "Expedition orange", wall: "#d8702a", trim: "#3a3a3a", floor: "#5a5a60", wood: "#7a7a7a", accent: "#2f6aa8" },
      { name: "Glacier blue", wall: "#6a8ab0", trim: "#2a3040", floor: "#4a5060", wood: "#8a8a8a", accent: "#d8c040" },
    ],
  },
];
