import type { InteriorProfile, Look } from "./types";

/**
 * Theatres: a room in rows (`program: "rows"`) facing a stage nine tiles wide,
 * whose `styles.altar` names it; `pew: "seat"` gives plush seats, `cushions`
 * the floor boxes of a Japanese house, neither a standing pit.
 */
const dark = (wall: Look["wall"], floor: Look["floor"], dado?: Look["wall"]): [Look, Look, Look] => [
  { wall, floor, wear: 0.5, soot: 0.3, windows: 0 },
  { wall, floor, dado, wear: 0.3, soot: 0.2, windows: 0 },
  { wall, floor, dado, wear: 0.1, soot: 0.1, windows: 0 },
];
const theatre = (p: Omit<InteriorProfile, "program" | "shapes" | "size" | "door" | "windowStyle" | "fire" | "smokehole" | "sleep" | "trades">): InteriorProfile => ({
  program: "rows",
  shapes: ["rect"],
  size: [15, 14],
  door: "door",
  windowStyle: "none",
  fire: "none",
  smokehole: false,
  sleep: "none",
  trades: ["household"],
  ...p,
});

export const theatres: InteriorProfile[] = [
  theatre({
    id: "elizabethan-playhouse",
    uses: ["venue.playhouse"],
    regulars: { hours: [14, 17], fill: 0.8 },
    styles: { altar: "stage-elizabethan" },
    label: "Playhouse",
    region: "England",
    period: "1570 – 1660",
    when: { start: { year: 1570 }, end: { year: 1660 } },
    basis: "documented",
    note: "The open playhouse of the Globe and the Swan, from de Witt's drawing and the 1997 reconstruction: a platform stage before the tiring-house with its two doors and the gallery over them, the painted heavens on two posts, the groundlings standing in the yard. The galleries round the yard are not drawn.",
    seating: "floor",
    furnish: [],
    looks: dark("timber", "earth"),
    colorways: [{ name: "Oak and limewash", wall: "#d8ccb0", trim: "#3a2a1a", floor: "#8a7050", wood: "#6a4a2c", accent: "#8a2a1a" }, { name: "Painted", wall: "#c8b490", trim: "#2a2018", floor: "#7a6448", wood: "#5a3e26", accent: "#2a3a6a" }],
  }),
  theatre({
    id: "proscenium-playhouse",
    uses: ["venue.playhouse"],
    regulars: { hours: [18, 23], fill: 0.7 },
    styles: { altar: "stage-playhouse", pew: "seat" },
    label: "Playhouse",
    region: "Europe",
    period: "1660 – 1950",
    when: { start: { year: 1660 }, end: { year: 1950 } },
    basis: "documented",
    note: "The indoor theatre after the Restoration and through the nineteenth century: a proscenium framing painted wings and backcloth, a curtain, footlights, rows in the pit. Boxes and galleries are not drawn.",
    seating: "chair",
    furnish: ["lamp", "lamp"],
    looks: dark("panel", "plank", "panel"),
    colorways: [{ name: "Crimson and cream", wall: "#d8c8a8", trim: "#4a2a1a", floor: "#6a4a30", wood: "#6a4a2c", accent: "#8a1a24" }, { name: "Green and gilt", wall: "#a8b898", trim: "#2a3a2a", floor: "#6a5038", wood: "#5a3e26", accent: "#2a5a3a" }],
  }),
  theatre({
    id: "opera-house",
    uses: ["venue.opera-house"],
    regulars: { hours: [19, 23], fill: 0.8 },
    styles: { altar: "stage-opera", pew: "seat" },
    label: "Opera house",
    region: "Europe",
    period: "1680 – 1950",
    when: { start: { year: 1680 }, end: { year: 1950 } },
    basis: "documented",
    note: "The Italian opera house as at La Scala and the Palais Garnier: a gilded proscenium, red velvet curtains, a painted landscape, the orchestra in its pit before the stage, plush rows below the tiers of boxes, which are not drawn.",
    seating: "chair",
    furnish: ["lamp", "lamp"],
    looks: dark("panel", "broadloom", "panel"),
    colorways: [{ name: "Gold and crimson", wall: "#c8a878", trim: "#5a2a1a", floor: "#7a2a2a", wood: "#6a3a22", accent: "#a01c28" }, { name: "Ivory and blue", wall: "#e0d4bc", trim: "#3a3a5a", floor: "#3a4a7a", wood: "#5a3e26", accent: "#2a3a7a" }],
  }),
  theatre({
    id: "noh-theatre",
    uses: ["venue.noh-stage"],
    regulars: { hours: [10, 16], fill: 0.6 },
    styles: { altar: "stage-noh" },
    label: "Noh theatre",
    region: "Japan",
    period: "1400 – 1950",
    when: { start: { year: 1400 }, end: { year: 1950 } },
    basis: "documented",
    note: "The noh stage as fixed by the Edo period: a cypress platform under its own temple roof, the great pine painted on the back panel, the bridge by which the actors come on, the corner pillars, white gravel between stage and audience, who sit on the floor.",
    seating: "floor",
    furnish: ["cushions"],
    looks: dark("plaster", "plank"),
    colorways: [{ name: "Cypress", wall: "#d8c8a0", trim: "#3d2e24", floor: "#a88a5a", wood: "#c8a878", accent: "#3f5a7a" }, { name: "Aged", wall: "#b8a888", trim: "#2a2018", floor: "#8a7048", wood: "#a8885a", accent: "#7a2a2a" }],
  }),
  theatre({
    id: "kabuki-theatre",
    uses: ["venue.kabuki-theatre"],
    regulars: { hours: [9, 18], fill: 0.8 },
    styles: { altar: "stage-kabuki" },
    label: "Kabuki theatre",
    region: "Japan",
    period: "1650 – 1950",
    when: { start: { year: 1650 }, end: { year: 1950 } },
    basis: "documented",
    note: "The Edo kabuki house, from Okumura Masanobu's prints: the wide stage behind its striped curtain of black, persimmon and green, the audience on the floor in boxes. The hanamichi walkway through them is not drawn.",
    seating: "floor",
    furnish: ["cushions", "lantern", "lantern"],
    looks: dark("plaster", "mat"),
    colorways: [{ name: "Lantern red", wall: "#c8a07a", trim: "#3a1a14", floor: "#a88a5a", wood: "#6a4a30", accent: "#a8302a" }, { name: "Soot", wall: "#8a7a64", trim: "#1e1814", floor: "#8a7048", wood: "#3a2a1e", accent: "#2f4a7a" }],
  }),
  theatre({
    id: "cinema",
    uses: ["venue.cinema"],
    regulars: { hours: [14, 23], fill: 0.7 },
    styles: { altar: "stage-cinema", pew: "seat" },
    label: "Picture house",
    region: "Everywhere films were shown",
    period: "1910 – present",
    when: { start: { year: 1910 }, end: { year: 2100 } },
    basis: "documented",
    note: "The picture palace of the interwar years: a screen framed in Art Deco gilt between drawn curtains, rows of plush tip-up seats, green exit lights.",
    seating: "chair",
    furnish: [],
    looks: dark("deco", "broadloom", "deco"),
    colorways: [{ name: "Deco gold", wall: "#c8a878", trim: "#2a1a14", floor: "#6a1a24", wood: "#4a2a1a", accent: "#a01c28" }, { name: "Jade and silver", wall: "#8aa898", trim: "#1a2a24", floor: "#2a3a4a", wood: "#3a3a3a", accent: "#2a6a5a" }],
  }),
];
