import type { InteriorProfile } from "./types";

/**
 * Places of worship: `program: "rows"` faces the room to its altar, whose
 * `styles.altar` names the tradition (pixel.ts `altar`); `seating` gives pews
 * (`chair`), and `prayer` or `cushions` in the furnishings gives rugs or
 * cushions in rows. With none of these the congregation stands, as it did in
 * a medieval nave. Custodians lodge nearby and the congregation comes in as
 * `regulars` at service.
 */
export const worship: InteriorProfile[] = [
  {
    id: "romanesque-church",
    uses: ["religious.romanesque-parish", "venue.churchyard"],
    program: "rows",
    regulars: { hours: [8, 11], fill: 0.6 },
    styles: { altar: "romanesque", pole: "stone" },
    label: "Romanesque parish church",
    region: "Latin Christendom",
    period: "900 – 1150",
    when: { start: { year: 900 }, end: { year: 1150 } },
    basis: "archaeological",
    note: "Thick-walled naves with round-arched arcades and an apse painted with Christ in Majesty, as at Sant Climent de Taüll and Saint-Savin. No seating: the congregation stood, the old and sick at the walls.",
    shapes: ["apse"],
    size: [11, 15],
    door: "door",
    windowStyle: "stained",
    fire: "none",
    smokehole: false,
    seating: "floor",
    sleep: "none",
    pole: true,
    trades: ["household"],
    furnish: ["font"],
    looks: [
      { wall: "stone", floor: "earth", wear: 0.4, soot: 0.4 },
      { wall: "plaster", floor: "flag", wear: 0.3, soot: 0.3 },
      { wall: "plaster", dado: "stripe", floor: "flag", wear: 0.15, soot: 0.2 },
    ],
    colorways: [
      { name: "Limewash and ochre", wall: "#d8ccb4", trim: "#5a4a3a", floor: "#9a8c78", wood: "#5a3e2a", accent: "#a83a2a" },
      { name: "Grey ashlar", wall: "#a8a49c", trim: "#4a4640", floor: "#8a8478", wood: "#4a3626", accent: "#3a5a8a" },
    ],
  },
  {
    id: "orthodox-church",
    uses: ["religious.romanesque-parish", "religious.gothic-parish", "venue.churchyard"],
    program: "rows",
    regulars: { hours: [8, 11], fill: 0.7 },
    styles: { altar: "screen-iconostasis", pole: "stone" },
    label: "Orthodox church",
    region: "Byzantium, the Balkans and Rus'",
    period: "500 – present",
    when: { start: { year: 500 }, end: { year: 2100 } },
    basis: "documented",
    note: "The Byzantine and Orthodox church: the iconostasis across the sanctuary with the Royal Doors between the Theotokos and Christ, rows of feasts and the Deesis above; walls frescoed with saints over painted marble; candles banked before the icons; the congregation standing. Before about 1000 the screen was the lower, open templon.",
    shapes: ["rect"],
    size: [13, 14],
    door: "door",
    windowStyle: "lattice",
    fire: "none",
    smokehole: false,
    seating: "floor",
    sleep: "none",
    pole: true,
    trades: ["household"],
    furnish: ["tapers", "tapers", "tapers"],
    looks: [
      { wall: "plaster", floor: "flag", wear: 0.3, soot: 0.5 },
      { wall: "fresco", floor: "flag", wear: 0.2, soot: 0.4 },
      { wall: "fresco", floor: "tile", wear: 0.1, soot: 0.3 },
    ],
    colorways: [
      { name: "Lapis and ochre", wall: "#d8c49a", trim: "#5a3a26", floor: "#a89a84", wood: "#5a3e2a", accent: "#a8302a" },
      { name: "Smoke and gold", wall: "#a8946a", trim: "#3a2618", floor: "#8a8070", wood: "#4a3222", accent: "#2a4a8a" },
    ],
  },
  {
    id: "gothic-church",
    uses: ["religious.gothic-parish", "religious.romanesque-parish", "venue.churchyard"],
    program: "rows",
    regulars: { hours: [8, 11], fill: 0.6 },
    styles: { altar: "gothic", pole: "stone" },
    label: "Gothic parish church",
    region: "Latin Christendom",
    period: "1150 – 1540",
    when: { start: { year: 1150 }, end: { year: 1540 } },
    basis: "documented",
    note: "The late medieval parish church of churchwardens' accounts and surviving fabric: pointed arcades, glass in the windows, a painted triptych over the high altar, a font by the door. Pews came only in the fifteenth century; before them the nave was open floor.",
    shapes: ["apse"],
    size: [11, 16],
    door: "door",
    windowStyle: "stained",
    fire: "none",
    smokehole: false,
    seating: "floor",
    sleep: "none",
    pole: true,
    trades: ["household"],
    furnish: ["font", "pulpit"],
    looks: [
      { wall: "plaster", floor: "flag", wear: 0.4, soot: 0.3 },
      { wall: "plaster", floor: "tile", wear: 0.25, soot: 0.2 },
      { wall: "plaster", dado: "panel", floor: "tile", wear: 0.1, soot: 0.1 },
    ],
    colorways: [
      { name: "Limewash and gilt", wall: "#e0d6c2", trim: "#5a4a3a", floor: "#a89a84", wood: "#5a3e2a", accent: "#a8302a" },
      { name: "Painted stone", wall: "#c8bca4", trim: "#3a3430", floor: "#8a8070", wood: "#4a3222", accent: "#2f4a8a" },
    ],
  },
  {
    id: "reformed-church",
    uses: ["religious.gothic-parish", "venue.churchyard"],
    program: "rows",
    regulars: { hours: [9, 12], fill: 0.6 },
    styles: { altar: "reformed", pew: "box", pole: "stone" },
    label: "Reformed parish church",
    region: "Britain, the Low Countries, northern Germany and Scandinavia",
    period: "1540 – 1900",
    when: { start: { year: 1540 }, end: { year: 1900 } },
    basis: "documented",
    note: "A medieval nave refitted for preaching after the Reformation: whitewashed walls, box pews, a pulpit with its sounding board, the communion table under boards of the Commandments, Creed and Lord's Prayer, clear leaded glass.",
    shapes: ["apse"],
    size: [11, 16],
    door: "door",
    windowStyle: "lattice",
    fire: "none",
    smokehole: false,
    seating: "chair",
    sleep: "none",
    pole: true,
    trades: ["household"],
    furnish: ["font", "pulpit"],
    looks: [
      { wall: "plaster", floor: "flag", wear: 0.4, soot: 0.2 },
      { wall: "plaster", floor: "flag", wear: 0.25, soot: 0.1 },
      { wall: "plaster", dado: "panel", floor: "tile", wear: 0.1, soot: 0.05 },
    ],
    colorways: [
      { name: "Whitewash and oak", wall: "#ece6d8", trim: "#4a3a2a", floor: "#a8a090", wood: "#6a4a30", accent: "#2f3a5a" },
      { name: "Dutch grey", wall: "#e4e2da", trim: "#2a2a2a", floor: "#b0aaa0", wood: "#4a3a2e", accent: "#5a2a2a" },
    ],
  },
  {
    id: "baroque-church",
    uses: ["religious.gothic-parish", "religious.spanish-american-church", "venue.churchyard"],
    program: "rows",
    regulars: { hours: [7, 11], fill: 0.6 },
    styles: { altar: "baroque", pole: "stone" },
    label: "Baroque Catholic church",
    region: "Catholic Europe and Spanish America",
    period: "1520 – 1900",
    when: { start: { year: 1520 }, end: { year: 1900 } },
    basis: "documented",
    note: "The Counter-Reformation church of Spain, Italy and the viceroyalties: a gilded retablo filling the head of the nave with saints in niches and the Virgin at its heart, benches for the congregation, painted walls and a marble or tiled floor.",
    shapes: ["apse"],
    size: [11, 16],
    door: "door",
    windowStyle: "lattice",
    fire: "none",
    smokehole: false,
    seating: "chair",
    sleep: "none",
    pole: true,
    trades: ["household"],
    furnish: ["font", "pulpit"],
    looks: [
      { wall: "plaster", floor: "flag", wear: 0.35, soot: 0.2 },
      { wall: "plaster", dado: "panel", floor: "tile", wear: 0.2, soot: 0.15 },
      { wall: "plaster", dado: "panel", floor: "tile", wear: 0.05, soot: 0.05 },
    ],
    colorways: [
      { name: "Whitewash and gold", wall: "#ece2cc", trim: "#6a4a2a", floor: "#c8b8a0", wood: "#5a3a22", accent: "#8a1e2a" },
      { name: "Colonial blue", wall: "#d4dce0", trim: "#3a3a4a", floor: "#b8a890", wood: "#4a3020", accent: "#2a4a8a" },
    ],
  },
  {
    id: "mosque",
    uses: ["venue.mosque-court", "religious.ottoman-mosque", "religious.arab-mosque", "religious.maghrebi-mosque", "religious.persian-mosque"],
    regulars: { hours: [12, 14], fill: 0.7 },
    rooms: [
      { id: "sahn", label: "Sahn", role: "entry", size: [11, 9], shapes: ["courtyard"], fire: "none", pole: false, furnish: ["plant", "plant"], clutter: ["shoes", "shoes", "shoes"], looks: [{ floor: "flag" }, { floor: "flag" }, { floor: "tile" }] },
      { id: "haram", label: "Prayer hall", role: "sanctum", program: "rows", size: [13, 10], fire: "none", furnish: ["prayer", "pulpit", "lamp"], clutter: ["book"], looks: [{ floor: "mat" }, { floor: "flag" }, { floor: "carpet" }] },
    ],
    styles: { altar: "mihrab", pulpit: "minbar", pole: "stone" },
    label: "Congregational mosque",
    region: "Islamic world",
    period: "650 – present",
    when: { start: { year: 650 }, end: { year: 2100 } },
    basis: "documented",
    note: "The courtyard mosque as at Damascus, Kairouan and Córdoba: an open court with its fountain for ablution, then the pillared prayer hall carpeted in ranks facing the mihrab in the qibla wall, the minbar beside it. Ottoman domed halls are drawn the same way here.",
    shapes: ["rect"],
    size: [11, 9],
    door: "door",
    windowStyle: "lattice",
    fire: "none",
    smokehole: false,
    seating: "floor",
    sleep: "none",
    pole: true,
    trades: ["household"],
    furnish: [],
    looks: [
      { wall: "plaster", floor: "flag", wear: 0.3, soot: 0.1 },
      { wall: "plaster", dado: "zellige", floor: "carpet", wear: 0.2, soot: 0.05 },
      { wall: "plaster", dado: "zellige", floor: "carpet", wear: 0.05, soot: 0.05 },
    ],
    colorways: [
      { name: "Limewash and turquoise", wall: "#e8e0d0", trim: "#5a4a38", floor: "#c8b8a0", wood: "#5a3e2a", accent: "#2a7a8a" },
      { name: "Red carpet and gilt", wall: "#e0d8c8", trim: "#4a3a2a", floor: "#b8a890", wood: "#4a3020", accent: "#a8302a" },
    ],
  },
  {
    id: "chinese-temple",
    uses: ["venue.temple-court-east", "religious.chinese-temple", "religious.korean-temple"],
    program: "rows",
    regulars: { hours: [7, 17], fill: 0.3 },
    styles: { altar: "buddha", pole: "red" },
    label: "Buddhist hall",
    region: "China, Korea and Vietnam",
    period: "500 – present",
    when: { start: { year: 500 }, end: { year: 2100 } },
    basis: "documented",
    note: "The main hall of a Chinese monastery as at Nanchan and Foguang: red lacquered columns, the gilded Buddha on a lotus throne behind an altar of incense, candles and flowers, kneeling cushions before it, a silk valance above.",
    shapes: ["rect"],
    size: [13, 11],
    door: "door",
    windowStyle: "lattice",
    fire: "none",
    smokehole: false,
    seating: "floor",
    sleep: "none",
    pole: true,
    trades: ["household"],
    furnish: ["cushions", "lantern", "lantern"],
    looks: [
      { wall: "plaster", floor: "flag", wear: 0.3, soot: 0.3 },
      { wall: "plaster", floor: "flag", wear: 0.2, soot: 0.2 },
      { wall: "plaster", floor: "tile", wear: 0.05, soot: 0.1 },
    ],
    colorways: [
      { name: "Vermilion and gold", wall: "#c8a07a", trim: "#5a1a14", floor: "#8a8478", wood: "#6a2a1e", accent: "#c8902a" },
      { name: "Ochre and green", wall: "#d0b48a", trim: "#2a3a2a", floor: "#8a8070", wood: "#5a2a1e", accent: "#2a6a4a" },
    ],
  },
  {
    id: "japanese-temple",
    uses: ["venue.temple-court-east", "religious.japanese-temple"],
    program: "rows",
    regulars: { hours: [6, 17], fill: 0.3 },
    styles: { altar: "buddha-jp", pole: "timber" },
    label: "Hondō",
    region: "Japan",
    period: "600 – present",
    when: { start: { year: 600 }, end: { year: 2100 } },
    basis: "documented",
    note: "The main hall of a Japanese temple: unpainted timber posts, a dark lacquered altar, the gilded Buddha before a flame mandorla, incense and offering lamps, worshippers kneeling on the boards.",
    shapes: ["rect"],
    size: [13, 11],
    door: "door",
    windowStyle: "shoji",
    fire: "none",
    smokehole: false,
    seating: "floor",
    sleep: "none",
    pole: true,
    trades: ["household"],
    furnish: ["cushions", "lantern", "lantern"],
    looks: [
      { wall: "plaster", floor: "plank", wear: 0.3, soot: 0.3 },
      { wall: "shoji", floor: "plank", wear: 0.15, soot: 0.2 },
      { wall: "shoji", floor: "mat", wear: 0.05, soot: 0.1 },
    ],
    colorways: [
      { name: "Aged cypress", wall: "#d8c8a8", trim: "#3a2a1e", floor: "#9a7a52", wood: "#6a4a30", accent: "#7a2a2a" },
      { name: "Black lacquer", wall: "#c8bca0", trim: "#1a1210", floor: "#7a6040", wood: "#4a3020", accent: "#a8802a" },
    ],
  },
  {
    id: "hindu-temple",
    uses: ["venue.temple-court-south"],
    regulars: { hours: [6, 12], fill: 0.4 },
    rooms: [
      { id: "mandapa", label: "Mandapa", role: "entry", program: "rows", size: [11, 10], fire: "none", furnish: ["lamp", "lamp"], clutter: ["flowers", "flowers", "shoes"] },
      { id: "garbhagriha", label: "Garbhagriha", role: "sanctum", program: "rows", size: [7, 5], fire: "none", windowStyle: "none", furnish: [], styles: { altar: "hindu" }, clutter: ["flowers"] },
    ],
    styles: { pole: "stone" },
    label: "Hindu temple",
    region: "South Asia",
    period: "500 – present",
    when: { start: { year: 500 }, end: { year: 2100 } },
    basis: "documented",
    note: "From the Gupta temples on: a pillared hall, the mandapa, leading to the small dark garbhagriha where the god stands garlanded, lit by oil lamps, bells hung at the door.",
    shapes: ["rect"],
    size: [11, 10],
    door: "door",
    windowStyle: "lattice",
    fire: "none",
    smokehole: false,
    seating: "floor",
    sleep: "none",
    pole: true,
    trades: ["household"],
    furnish: [],
    looks: [
      { wall: "stone", floor: "flag", wear: 0.3, soot: 0.4 },
      { wall: "plaster", dado: "stripe", floor: "flag", wear: 0.2, soot: 0.3 },
      { wall: "plaster", dado: "stripe", floor: "tile", wear: 0.1, soot: 0.2 },
    ],
    colorways: [
      { name: "Sandstone", wall: "#c89a6a", trim: "#5a3a26", floor: "#a88a6a", wood: "#5a3a22", accent: "#d06a1a" },
      { name: "Granite", wall: "#9a948a", trim: "#3a3630", floor: "#8a847a", wood: "#4a3626", accent: "#c0302a" },
    ],
  },
  {
    id: "wat",
    uses: ["venue.wat"],
    program: "rows",
    regulars: { hours: [6, 12], fill: 0.4 },
    styles: { altar: "buddha", pole: "red" },
    label: "Ubosot",
    region: "Mainland Southeast Asia",
    period: "1250 – present",
    when: { start: { year: 1250 }, end: { year: 2100 } },
    basis: "documented",
    note: "The ordination hall of a Thai, Lao or Khmer monastery: a great gilded Buddha at the end of a long hall, red and gold columns, worshippers kneeling on mats. The walls would be covered in murals of the Buddha's lives; here they are plain.",
    shapes: ["rect"],
    size: [11, 13],
    door: "door",
    windowStyle: "shutter",
    fire: "none",
    smokehole: false,
    seating: "floor",
    sleep: "none",
    pole: true,
    trades: ["household"],
    furnish: ["cushions", "lantern"],
    looks: [
      { wall: "plaster", floor: "tile", wear: 0.3, soot: 0.2 },
      { wall: "plaster", floor: "tile", wear: 0.2, soot: 0.1 },
      { wall: "plaster", dado: "stripe", floor: "carpet", wear: 0.05, soot: 0.05 },
    ],
    colorways: [
      { name: "Red and gold", wall: "#c8584a", trim: "#3a1a14", floor: "#a89078", wood: "#5a2a1a", accent: "#e0a830" },
      { name: "Lime and lacquer", wall: "#e0d4b8", trim: "#2a1a14", floor: "#a8987e", wood: "#4a2a1a", accent: "#a8302a" },
    ],
  },
  {
    id: "classical-temple",
    uses: ["venue.temple-precinct"],
    program: "rows",
    regulars: { hours: [8, 12], fill: 0.15 },
    styles: { altar: "classical", pole: "stone" },
    label: "Temple cella",
    region: "Greek and Roman Mediterranean",
    period: "600 BCE – 400 CE",
    when: { start: { year: -600 }, end: { year: 400 } },
    basis: "archaeological",
    note: "The cella that housed the god's image, as at the Parthenon and the Maison Carrée: an inner colonnade, the statue on its base, a small altar for incense. Sacrifice was at the great altar outside; few came in.",
    shapes: ["rect"],
    size: [9, 13],
    door: "door",
    windowStyle: "none",
    fire: "none",
    smokehole: false,
    seating: "floor",
    sleep: "none",
    pole: true,
    trades: ["household"],
    furnish: ["lamp", "lamp"],
    looks: [
      { wall: "plaster", floor: "flag", wear: 0.3, soot: 0.3 },
      { wall: "plaster", dado: "panel", floor: "tile", wear: 0.2, soot: 0.2 },
      { wall: "plaster", dado: "panel", floor: "tile", wear: 0.05, soot: 0.1 },
    ],
    colorways: [
      { name: "Marble and red", wall: "#b04a32", trim: "#e8dcc4", floor: "#d8ccb4", wood: "#6a4a30", accent: "#e0b040" },
      { name: "White marble", wall: "#e4dcd0", trim: "#7a6e64", floor: "#dcd4c8", wood: "#6a5040", accent: "#2a4a8a" },
    ],
  },
  {
    id: "mesopotamian-temple",
    uses: ["religious.mesopotamian-temple", "religious.hittite-temple"],
    program: "rows",
    regulars: { hours: [7, 11], fill: 0.15 },
    styles: { altar: "mesopotamian" },
    label: "Temple cella",
    region: "Mesopotamia and Anatolia",
    period: "3000 – 500 BCE",
    when: { start: { year: -3000 }, end: { year: -500 } },
    basis: "archaeological",
    note: "The broad cella of a Mesopotamian temple, as at Tell Asmar and Ur: buttressed mudbrick, the god's statue in a niche with its horned crown, an offering table of bread and beer. The worshipper statues that stood along the benches are not drawn.",
    shapes: ["rect"],
    size: [11, 8],
    door: "door",
    windowStyle: "none",
    fire: "none",
    smokehole: false,
    seating: "floor",
    sleep: "none",
    trades: ["household"],
    furnish: ["lamp"],
    looks: [
      { wall: "mud", floor: "earth", wear: 0.4, soot: 0.4 },
      { wall: "mud", floor: "flag", wear: 0.3, soot: 0.3 },
      { wall: "plaster", dado: "stripe", floor: "flag", wear: 0.1, soot: 0.2 },
    ],
    colorways: [
      { name: "Mudbrick", wall: "#b8946a", trim: "#5a3a26", floor: "#9a7a58", wood: "#5a3e2a", accent: "#2a4a9a" },
      { name: "Whitewash", wall: "#ddd0b8", trim: "#5a4030", floor: "#a88a68", wood: "#5a3e2a", accent: "#a8402a" },
    ],
  },
  {
    id: "maya-temple",
    uses: ["religious.maya-temple-pyramid", "religious.mesoamerican-temple-pyramid"],
    program: "rows",
    regulars: { hours: [6, 9], fill: 0.1 },
    styles: { altar: "maya" },
    label: "Temple shrine",
    region: "Mesoamerica",
    period: "250 – 1550",
    when: { start: { year: 250 }, end: { year: 1550 } },
    basis: "archaeological",
    note: "The small dark room on a pyramid's summit, as at Tikal and Palenque: plastered walls painted red, a carved and painted image, copal smoking in an effigy censer. Only priests went in.",
    shapes: ["rect"],
    size: [7, 6],
    door: "curtain",
    windowStyle: "none",
    fire: "none",
    smokehole: false,
    seating: "floor",
    sleep: "none",
    trades: ["household"],
    furnish: [],
    looks: [
      { wall: "plaster", floor: "flag", wear: 0.3, soot: 0.5 },
      { wall: "plaster", floor: "flag", wear: 0.2, soot: 0.4 },
      { wall: "plaster", dado: "band", floor: "flag", wear: 0.1, soot: 0.3 },
    ],
    colorways: [
      { name: "Maya red", wall: "#a8402a", trim: "#3a1a14", floor: "#b8a88a", wood: "#5a3a22", accent: "#2a7a8a" },
      { name: "Lime white", wall: "#ddd4c0", trim: "#5a3a26", floor: "#a8987e", wood: "#5a3a22", accent: "#a8302a" },
    ],
  },
  {
    id: "chavin-gallery",
    uses: ["religious.andean-platform-temple"],
    program: "rows",
    regulars: { hours: [5, 8], fill: 0.1 },
    styles: { altar: "lanzon" },
    label: "Temple gallery",
    region: "Andes",
    period: "1000 – 200 BCE",
    when: { start: { year: -1000 }, end: { year: -200 } },
    basis: "archaeological",
    note: "The Old Temple at Chavín de Huántar: narrow galleries of dressed stone in the dark of the platform, and where two cross, the Lanzón, a granite blade carved with a fanged god whose eyes look up, rising through the roof. Water ran through channels under the floor and could be made to roar.",
    shapes: ["rect"],
    size: [7, 7],
    door: "opening",
    windowStyle: "none",
    fire: "none",
    smokehole: false,
    seating: "floor",
    sleep: "none",
    trades: ["household"],
    furnish: [],
    looks: [
      { wall: "stone", floor: "flag", wear: 0.3, soot: 0.5 },
      { wall: "stone", floor: "flag", wear: 0.2, soot: 0.4 },
      { wall: "stone", floor: "flag", wear: 0.1, soot: 0.3 },
    ],
    colorways: [
      { name: "Granite and shadow", wall: "#6a665c", trim: "#2a2622", floor: "#7a7468", wood: "#4a3a2a", accent: "#8a3a2a" },
      { name: "Grey limestone", wall: "#8a867a", trim: "#3a3630", floor: "#8a8478", wood: "#4a3a2a", accent: "#3a6a7a" },
    ],
  },
  {
    id: "moche-huaca",
    uses: ["religious.andean-platform-temple"],
    program: "rows",
    regulars: { hours: [6, 10], fill: 0.15 },
    styles: { altar: "ai-apaec" },
    label: "Huaca shrine",
    region: "Andes",
    period: "200 BCE – 1400",
    when: { start: { year: -200 }, end: { year: 1400 } },
    basis: "archaeological",
    note: "A room on an adobe platform painted in relief, after the Moche Huaca de la Luna: registers of the fanged god's face in stepped diamonds and of stepped waves, red, yellow, white and black, stirrup-spout bottles set before him. The coast's later huacas, Chimú and others, are drawn from the same building.",
    shapes: ["rect"],
    size: [9, 7],
    door: "opening",
    windowStyle: "none",
    fire: "none",
    smokehole: false,
    seating: "floor",
    sleep: "none",
    trades: ["household"],
    furnish: ["jars"],
    looks: [
      { wall: "frieze", floor: "earth", wear: 0.3, soot: 0.2 },
      { wall: "frieze", floor: "earth", wear: 0.2, soot: 0.1 },
      { wall: "frieze", floor: "flag", wear: 0.1, soot: 0.05 },
    ],
    colorways: [
      { name: "Adobe", wall: "#b89a78", trim: "#3a2418", floor: "#a88a68", wood: "#5a3a22", accent: "#a83a24" },
      { name: "Sun-dried", wall: "#c8aa84", trim: "#4a2e1e", floor: "#b8987a", wood: "#5a3a22", accent: "#e0b040" },
    ],
  },
  {
    id: "inca-temple",
    uses: ["religious.andean-platform-temple"],
    program: "rows",
    regulars: { hours: [6, 10], fill: 0.2 },
    styles: { altar: "inca-sun" },
    label: "Temple of the Sun",
    region: "Inca Andes",
    period: "1400 – 1600",
    when: { start: { year: 1400 }, end: { year: 1600 } },
    basis: "documented",
    note: "An Inca temple as the chroniclers saw the Coricancha in Cusco: walls of fitted ashlar with trapezoidal niches, sheathed in gold in the greatest of them, the Punchao, a gold sun with a face, in its niche, and maize, chicha in gold keros and silver llamas offered before it.",
    shapes: ["rect"],
    size: [10, 7],
    door: "opening",
    windowStyle: "none",
    fire: "none",
    smokehole: false,
    seating: "floor",
    sleep: "none",
    trades: ["household"],
    furnish: ["jars"],
    looks: [
      { wall: "ashlar", floor: "flag", wear: 0.2, soot: 0.2 },
      { wall: "ashlar", floor: "flag", wear: 0.1, soot: 0.1 },
      { wall: "ashlar", floor: "flag", wear: 0.05, soot: 0.05 },
    ],
    colorways: [
      { name: "Andesite", wall: "#8a8478", trim: "#2a2622", floor: "#8a8274", wood: "#4a3424", accent: "#a83a24" },
      { name: "Limestone", wall: "#b0a896", trim: "#3a342c", floor: "#a09682", wood: "#4a3424", accent: "#2a6a8a" },
    ],
  },
  {
    id: "mound-temple",
    uses: ["religious.mississippian-platform-mound"],
    program: "gather",
    regulars: { hours: [5, 9], fill: 0.2 },
    styles: { altar: "etowah", ledge: "platform" },
    label: "Mound temple",
    region: "Mississippian Southeast",
    period: "800 – 1600",
    when: { start: { year: 800 }, end: { year: 1600 } },
    basis: "archaeological",
    note: "The temple on a platform mound, as at Etowah and as the Natchez kept theirs for the French: a sacred fire never let out in the middle, cane benches round the wall, and the ancestors, a pair of painted marble figures, a man cross-legged and a woman kneeling, under a copper plate of the falcon dancer.",
    shapes: ["rect"],
    size: [10, 9],
    door: "opening",
    windowStyle: "none",
    fire: "firepit",
    smokehole: true,
    seating: "chair",
    sleep: "none",
    trades: ["household"],
    furnish: ["basket"],
    looks: [
      { wall: "reed", floor: "earth", wear: 0.3, soot: 0.5 },
      { wall: "mud", floor: "earth", wear: 0.2, soot: 0.4 },
      { wall: "mud", floor: "earth", wear: 0.1, soot: 0.3 },
    ],
    colorways: [
      { name: "Daub and cane", wall: "#a88a64", trim: "#3a2a1c", floor: "#8a6a48", wood: "#5a3e26", accent: "#a83a2a" },
      { name: "Whitewashed clay", wall: "#d0c4a8", trim: "#3a2a1c", floor: "#9a7a58", wood: "#5a3e26", accent: "#2a2a2a" },
    ],
  },
];
