/*
 * Ports the Historical Persona Generator's society-capability table and its
 * common-work substrate into UHS.
 *
 * HPG gates ordinary work on what a society could actually do at a place and
 * year — a smith needs smelting, a market seller needs markets, a scribe needs
 * writing. UHS had three gates (water, settled, cultivation) and eight jobs.
 *
 * The capability dates come across by calling HPG's own resolver, so they stay
 * in step with it. HPG's place exceptions are matched on place-name regexes and
 * are re-expressed as boxes in scripts/data/capability-overrides.json; the work
 * itself is parsed out of commonProfessions.ts, whose roles are one per line.
 *
 * Run: npx tsx scripts/port-livelihoods.ts [path-to-hpg]
 */
import { readFileSync, writeFileSync } from "node:fs";
import { resolve as resolvePath } from "node:path";

const hpg = process.argv[2] ?? `${process.env.HOME}/code/historical-persona-generator`;
const { capabilityAvailableFrom, capabilityAvailableUntil } = await import(
  resolvePath(hpg, "src/constants/societyCapabilities.ts")
);

const CAPABILITIES = [
  "writing", "metallurgy", "settled_agriculture", "heritable_land", "draft_animals",
  "guilds", "coinage", "urban_settlement", "european_contact", "market_exchange",
  "wage_labor", "retained_military_service", "guild_apprenticeship",
] as const;

/** HPG's eight cultural zones against UHS's twelve cultures. */
const ZONE_CULTURES: Record<string, string[]> = {
  EUROPEAN: ["european"],
  MENA: ["north-african-west-asian"],
  EAST_ASIAN: ["east-asian", "inner-eurasian"],
  SOUTH_ASIAN: ["south-asian"],
  SOUTHEAST_ASIAN: ["southeast-asian"],
  SUB_SAHARAN_AFRICAN: ["west-central-african", "east-southern-african"],
  SOUTH_AMERICAN: ["andean"],
  NORTH_AMERICAN_PRE_COLUMBIAN: ["other-indigenous-american", "mesoamerican"],
  OCEANIA: ["australian-pacific"],
};

const FLOOR = -1000000, CEIL = 10001;
const clamp = (y: number) => (!Number.isFinite(y) ? (y < 0 ? FLOOR : CEIL) : Math.round(y));

const windows: { capability: string; culture: string; from: number; to: number }[] = [];
for (const capability of CAPABILITIES) {
  for (const [zone, cultures] of Object.entries(ZONE_CULTURES)) {
    const from = capabilityAvailableFrom(capability, { year: 0, culturalZone: zone });
    const to = capabilityAvailableUntil(capability, { year: 0, culturalZone: zone });
    for (const culture of cultures)
      windows.push({ capability, culture, from: clamp(from), to: clamp(to) });
  }
}

const overrides = JSON.parse(readFileSync("scripts/data/capability-overrides.json", "utf8"));
const work = JSON.parse(readFileSync("scripts/data/livelihood-work.json", "utf8"));

/* --- the work itself ---------------------------------------------------- */

const source = readFileSync(
  resolvePath(hpg, "src/constants/characterData/commonProfessions.ts"),
  "utf8",
);
const TIERS = ["PREHISTORIC_WORK", "VILLAGE_WORK", "TOWN_WORK", "INDUSTRIAL_WORK", "MODERN_WORK"];
const shorthand = {
  HEAVY: { minStrength: 5, minStamina: 4 },
  STEADY: { minStamina: 3 },
  DEFT: { minDexterity: 4 },
  CAREFUL: { minDexterity: 4, minPerception: 4 },
};

type Role = {
  id: string; label: string; tier: string; activity: string;
  inventory: Record<string, number>;
  needs: string[]; needsAny: string[]; excludes: string[];
  sex?: "male" | "female";
};

const slug = (s: string) =>
  s.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "");

const roles = new Map<string, Role>();
for (const tier of TIERS) {
  const block = source.slice(source.indexOf(`const ${tier}: CommonRole[] = [`));
  for (const line of block.slice(0, block.indexOf("\n];")).split("\n")) {
    if (!line.startsWith("  r(")) continue;
    // The argument list is plain data plus the four shorthand stat profiles.
    const args = new Function(
      ...Object.keys(shorthand),
      `return [${line.trim().replace(/^r\(/, "").replace(/\),?$/, "")}]`,
    )(...Object.values(shorthand)) as [string, string, string, any?, any?];
    const [label, , keywords, extra = {}, gate = {}] = args;
    const id = slug(label);
    const key = keywords.split(/\s+/).find((k: string) => work.keywords[k]);
    const shape = work.keywords[key ?? ""] ?? work._default;
    // A role in more than one tier keeps the earliest; the tiers are ordered.
    if (roles.has(id)) continue;
    roles.set(id, {
      id, label, tier: tier.replace("_WORK", "").toLowerCase(),
      activity: shape.activity, inventory: shape.inventory,
      needs: gate.needs ?? [], needsAny: gate.needsAny ?? [], excludes: gate.excludes ?? [],
      sex: extra.genderBias === "Male" ? "male" : extra.genderBias === "Female" ? "female" : undefined,
    });
  }
}

/* --- output ------------------------------------------------------------- */

const header = `// Generated by scripts/port-livelihoods.ts from the Historical Persona
// Generator. Do not edit by hand; edit the source, scripts/data/livelihood-work.json
// or scripts/data/capability-overrides.json and re-run.
`;

writeFileSync(
  "src/content/characters/capabilities.generated.ts",
  header +
    `import type { CapabilityOverride, CapabilityWindow } from "./context-types";\n\n` +
    `export const capabilityWindows: readonly CapabilityWindow[] = [\n` +
    windows.map((w) =>
      `  { capability: ${JSON.stringify(w.capability)}, culture: ${JSON.stringify(w.culture)}, from: ${w.from}, to: ${w.to} },`,
    ).join("\n") +
    `\n];\n\n` +
    `/** Places the zone date gets wrong. The narrowest matching box wins. */\n` +
    `export const capabilityOverrides: readonly CapabilityOverride[] = [\n` +
    overrides.overrides.map((o: any) =>
      `  {\n    id: ${JSON.stringify(o.id)},\n    label: ${JSON.stringify(o.label)},\n` +
      `    bounds: ${JSON.stringify(o.bounds)},\n` +
      (o.cultures ? `    cultures: ${JSON.stringify(o.cultures)},\n` : "") +
      `    capabilities: {\n` +
      Object.entries(o.capabilities).map(([c, y]) =>
        `      ${c}: ${y === null ? CEIL : clamp(y as number)},`,
      ).join("\n") +
      `\n    },\n  },`,
    ).join("\n") +
    `\n];\n`,
);

writeFileSync(
  "src/content/characters/livelihoods.generated.ts",
  header +
    `import type { Livelihood } from "./context-types";\n\n` +
    `/** The ordinary work, gated on what the society could do. */\n` +
    `export const commonLivelihoods: readonly Livelihood[] = [\n` +
    [...roles.values()].map((r) =>
      `  {\n    id: ${JSON.stringify(r.id)},\n    label: ${JSON.stringify(r.label)},\n` +
      `    activity: ${JSON.stringify(r.activity)},\n    tier: ${JSON.stringify(r.tier)},\n` +
      (r.needs.length ? `    capabilities: ${JSON.stringify(r.needs)},\n` : "") +
      (r.needsAny.length ? `    anyCapability: ${JSON.stringify(r.needsAny)},\n` : "") +
      (r.excludes.length ? `    withoutCapability: ${JSON.stringify(r.excludes)},\n` : "") +
      (r.sex ? `    sex: ${JSON.stringify(r.sex)},\n` : "") +
      `    inventory: ${JSON.stringify(r.inventory)},\n  },`,
    ).join("\n") +
    `\n];\n`,
);

const byTier = [...roles.values()].reduce<Record<string, number>>(
  (n, r) => ({ ...n, [r.tier]: (n[r.tier] ?? 0) + 1 }), {},
);
console.error(
  `${roles.size} roles (${Object.entries(byTier).map(([t, n]) => `${t} ${n}`).join(", ")}), ` +
  `${windows.length} capability windows, ${overrides.overrides.length} place overrides`,
);
