"""Build travel labels from pinned Natural Earth physical polygons (stdlib only)."""
import hashlib
import json
import re
import urllib.request
from collections import defaultdict
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
REV = 'ca96624a56bd078437bca8184e78163e5039ad19'
SOURCES = {
    'ne_10m_geography_regions_polys': 'b7b26e50ea917d3696aec87f932def2bf5f890f5770e441d59c162c6f4c92a77',
    'ne_10m_geography_marine_polys': '53f865e8ffa966cdd402145c82c5cd14ee7ce974cd0eb9a3f59f03a4cfd2d66c',
}
OUT = ROOT / 'src/content/geography/travel/generated'
OUT.mkdir(parents=True, exist_ok=True)


def simplify(points, tolerance=.015):
    if len(points) < 4:
        return points
    a, b = points[0], points[-1]
    dx, dy = b[0]-a[0], b[1]-a[1]
    denominator = dx*dx+dy*dy or 1
    best, at = 0, 0
    for i, p in enumerate(points[1:-1], 1):
        t = max(0, min(1, ((p[0]-a[0])*dx+(p[1]-a[1])*dy)/denominator))
        d = (p[0]-a[0]-t*dx)**2+(p[1]-a[1]-t*dy)**2
        if d > best:
            best, at = d, i
    if best <= tolerance*tolerance:
        return [a, b]
    return simplify(points[:at+1], tolerance)[:-1] + simplify(points[at:], tolerance)


def ring_area(ring):
    return abs(sum(a[0]*b[1]-b[0]*a[1] for a, b in zip(ring, ring[1:]))) / 2


groups, sources, seen = defaultdict(list), [], set()
for source, expected in SOURCES.items():
    url = f'https://raw.githubusercontent.com/nvkelso/natural-earth-vector/{REV}/geojson/{source}.geojson'
    cache = ROOT / 'scripts/source-cache' / f'{source}.geojson'
    cache.parent.mkdir(parents=True, exist_ok=True)
    if not cache.exists():
        cache.write_bytes(urllib.request.urlopen(url, timeout=120).read())
    raw = cache.read_bytes()
    if hashlib.sha256(raw).hexdigest() != expected:
        raise ValueError(f'Source checksum mismatch: {source}')
    sources.append({'url': url, 'sha256': expected, 'license': 'Public domain — Natural Earth'})
    marine = 'marine' in source
    for f in json.loads(raw)['features']:
        p = {k.lower(): v for k, v in f['properties'].items()}
        if p['featurecla'] in ['Dragons-be-here', 'Lake']:
            continue
        if not (p.get('name_en') or p.get('name')):
            continue
        group = 'marine' if marine else re.sub(r'[^a-z]+', '-', p['region'].lower()).strip('-')
        identity = f"ne:{group}:{p['ne_id']}"
        seen.add(identity)
        name = (p.get('name_en') or p['name']).strip()
        if name.isupper():
            name = name.title()
        # Prefer the source's shorter full name over truncating a longer translation.
        if len(name) > 34 and len(p['name']) < len(name):
            name = p['name'].title() if p['name'].isupper() else p['name']
        polygons = f['geometry']['coordinates']
        if f['geometry']['type'] == 'Polygon':
            polygons = [polygons]
        compiled = []
        for poly in polygons:
            rings = []
            for ring in poly:
                reduced = simplify(ring)
                if len(reduced) < 4:
                    reduced = ring
                rings.append([[round(x, 4), round(y, 4)] for x, y, *_ in reduced])
            compiled.append(rings)
        points = [pt for poly in compiled for ring in poly for pt in ring]
        bounds = [min(p[0] for p in points), min(p[1] for p in points), max(p[0] for p in points), max(p[1] for p in points)]
        record = {'id': identity, 'sourceId': str(p['ne_id']), 'name': name, 'kind': p['featurecla'], 'marine': marine,
                  'bounds': bounds, 'area': round(sum(ring_area(poly[0]) for poly in compiled), 5), 'polygons': compiled}
        group = 'marine' if marine else re.sub(r'[^a-z]+', '-', p['region'].lower()).strip('-')
        groups[group].append(record)
imports = []
for i, (group, records) in enumerate(sorted(groups.items())):
    merged = {}
    for r in records:
        old = merged.get(r['id'])
        if old:
            old['polygons'].extend(r['polygons'])
            old['area'] += r['area']
            old['bounds'] = [min(old['bounds'][0], r['bounds'][0]), min(old['bounds'][1], r['bounds'][1]), max(old['bounds'][2], r['bounds'][2]), max(old['bounds'][3], r['bounds'][3])]
        else:
            merged[r['id']] = r
    records = sorted(merged.values(), key=lambda r: r['id'])
    (OUT / f'{group}.json').write_text(json.dumps(records, separators=(',', ':'), ensure_ascii=False)+'\n')
    imports.append(f'import data{i} from "./{group}.json";')
(OUT / 'index.ts').write_text('// Generated by scripts/prepare-travel-names.py.\n'+'\n'.join(imports)+'\nexport const physicalRegions = ['+', '.join(f'...data{i}' for i in range(len(imports)))+'];\n')
(OUT / 'sources.json').write_text(json.dumps({'revision': REV, 'sources': sources, 'features': len(seen), 'toleranceDegrees': .015}, indent=2)+'\n')
print(f'{len(seen)} regions; {sum(p.stat().st_size for p in OUT.glob("*.json")):,} bytes across {len(groups)} regional files')
