import type { UrbanFormRule } from "./types";

export const africaForms: UrbanFormRule[] = [
  {
    id: "west-african-ward-compounds",
    storeys: 1,
    label: "Walled wards of family compounds",
    culture: "west-central-african",
    from: 800,
    to: 1900,
    bounds: [-18, 3, 22, 18],
    plan: "organic",
    block: [24, 20],
    regularity: 0.14,
    courts: 0.86,
    deadEnds: 0.4,
    tiers: [3, 2, 1],
    surface: "earth",
    gates: 4,
    wall: "earth",
    plaza: "offset",
    plazaScale: 0.2,
    civic: "side",
    square: { focus: "tree", corners: ["well", "bench"], hearth: "brazier" },
    evidence: {
      status: "inferred",
      sources: [],
      note: "Wards of walled family compounds, reached from a few broad routes by narrow shared passages, follow descriptions of the ward layout of Benin City and the walled wards of Kano. Compound dimensions and the generated pattern are an inference.",
    },
  },
  {
    id: "swahili-stone-town",
    storeys: 2,
    label: "Stone town on narrow lanes",
    culture: "east-southern-african",
    from: 1000,
    to: 1900,
    bounds: [37, -14, 44, 4],
    plan: "organic",
    block: [17, 14],
    regularity: 0.1,
    courts: 0.72,
    deadEnds: 0.38,
    tiers: [2, 1, 1],
    gates: 3,
    wall: "none",
    plaza: "waterfront",
    plazaScale: 0.14,
    civic: "side",
    square: { focus: "well", corners: ["bench", "planter"], hearth: "hidden" },
    evidence: {
      status: "inferred",
      sources: [],
      note: "Tall stone houses on lanes too narrow for carts, opening onto a seafront, follow the surviving fabric of Lamu and Zanzibar Stone Town. Lane widths here are a gameplay approximation.",
    },
  },
  {
    id: "southern-african-enclosures",
    storeys: 1,
    label: "Enclosures around a central court",
    culture: "east-southern-african",
    from: 1000,
    to: 1900,
    bounds: [16, -35, 40, -8],
    plan: "radial",
    block: [22, 20],
    regularity: 0.2,
    courts: 0.84,
    deadEnds: 0.22,
    tiers: [3, 1, 1],
    surface: "earth",
    gates: 3,
    wall: "masonry",
    plaza: "crossing",
    plazaScale: 0.26,
    civic: "side",
    square: { focus: "tree", corners: ["brazier", "bench"], hearth: "brazier" },
    evidence: {
      status: "inferred",
      sources: [],
      note: "Curving walled enclosures grouped around a central open area follow the arrangement recorded at Great Zimbabwe and later Shona settlements. The engine approximates the enclosures with rectangular blocks and does not reproduce a surveyed site.",
    },
  },
];
