import type { UrbanFormRule } from "./types";

export const americasForms: UrbanFormRule[] = [
  {
    id: "mesoamerican-precinct-grid",
    storeys: 1,
    label: "Quarters around a ceremonial precinct",
    culture: "mesoamerican",
    from: -200,
    to: 1550,
    bounds: [-106, 13, -85, 23],
    plan: "orthogonal",
    block: [28, 24],
    regularity: 0.86,
    courts: 0.66,
    deadEnds: 0.1,
    tiers: [3, 1, 0],
    gates: 4,
    wall: "none",
    plaza: "crossing",
    plazaScale: 0.34,
    civic: "head",
    evidence: {
      status: "inferred",
      sources: [],
      note: "A very large central open precinct with residential compounds on a grid of avenues follows the mapped layout of Teotihuacan and the causeway-divided quarters of Tenochtitlan. Compound sizes and the generated street pattern are an inference.",
    },
  },
  {
    id: "andean-kancha-blocks",
    storeys: 1,
    label: "Walled compounds around patios",
    culture: "andean",
    from: 1100,
    to: 1600,
    bounds: [-80, -22, -65, -6],
    plan: "orthogonal",
    block: [20, 18],
    regularity: 0.8,
    courts: 0.88,
    deadEnds: 0.08,
    tiers: [2, 0, 0],
    gates: 3,
    wall: "none",
    plaza: "crossing",
    plazaScale: 0.28,
    civic: "head",
    evidence: {
      status: "inferred",
      sources: [],
      note: "Rectangular walled compounds of rooms opening onto a shared patio, set on narrow straight streets beside a large plaza, follow the kancha plan recorded in Inca Cusco. Compound dimensions here are illustrative.",
    },
  },
];
