import type { UrbanFormRule } from "./types";

export const eastAsiaForms: UrbanFormRule[] = [
  {
    id: "chinese-ward-grid",
    storeys: 1,
    label: "Ward grid on a north-south axis",
    culture: "east-asian",
    from: -1000,
    to: 1912,
    bounds: [100, 20, 126, 45],
    plan: "orthogonal",
    block: [30, 22],
    regularity: 0.94,
    courts: 0.62,
    deadEnds: 0.12,
    tiers: [3, 1, 0],
    gates: 4,
    wall: "masonry",
    plaza: "crossing",
    plazaScale: 0.24,
    civic: "head",
    square: { focus: "stele", corners: ["well", "bench"], hearth: "hidden" },
    evidence: {
      status: "inferred",
      sources: [],
      note: "Large walled wards, wide axial avenues and narrow interior lanes follow the ideal capital plan of the Kaogongji chapter of the Zhouli and the surveyed grid of Ming Beijing. Block dimensions, ward counts and the generated street pattern are an inference for this engine, not a reconstruction of any surveyed city.",
    },
  },
  {
    id: "japanese-capital-grid",
    storeys: 1,
    label: "Chequerboard capital blocks",
    culture: "east-asian",
    from: 700,
    to: 1600,
    bounds: [128, 30, 146, 46],
    plan: "orthogonal",
    block: [24, 24],
    regularity: 0.97,
    courts: 0.5,
    deadEnds: 0.06,
    tiers: [2, 1, 0],
    gates: 4,
    wall: "none",
    plaza: "crossing",
    plazaScale: 0.2,
    civic: "head",
    square: {
      focus: "stele",
      corners: ["well", "tree", "bench", "tree"],
      hearth: "hidden",
    },
    evidence: {
      status: "inferred",
      sources: [],
      note: "Square blocks on a strict module follow the Heian-kyo and Heijo-kyo capital plans, themselves modelled on Chang'an. Applying it to a procedural neighborhood is an inference; the generator does not reproduce a named capital's ward divisions.",
    },
  },
];
