import type { UrbanFormRule } from "./types";

export const europeForms: UrbanFormRule[] = [
  {
    id: "roman-insula-grid",
    storeys: 3,
    label: "Insula blocks on a cardo and decumanus",
    culture: "european",
    from: -400,
    to: 500,
    bounds: [-8, 30, 32, 52],
    plan: "orthogonal",
    block: [26, 18],
    regularity: 0.92,
    courts: 0.55,
    deadEnds: 0.05,
    tiers: [2, 1, 0],
    gates: 4,
    wall: "masonry",
    plaza: "crossing",
    plazaScale: 0.22,
    civic: "head",
    evidence: {
      status: "inferred",
      sources: [
        "https://pompeiisites.org/wp-content/uploads/Pompei-ING-LR-link.pdf",
      ],
      note: "Rectangular insulae between two wider crossing streets, with a forum at the crossing, follow the surveyed block plan of Pompeii. Extending it to a procedural neighborhood is an inference, not a reconstruction of a Roman city.",
    },
  },
  {
    id: "medieval-market-town",
    storeys: 2,
    label: "Irregular blocks around a market place",
    culture: "european",
    from: 500,
    to: 1500,
    bounds: [-12, 35, 34, 64],
    plan: "organic",
    block: [22, 14],
    regularity: 0.16,
    courts: 0.34,
    deadEnds: 0.28,
    tiers: [2, 1, 0],
    gates: 4,
    wall: "masonry",
    plaza: "offset",
    plazaScale: 0.17,
    civic: "head",
    evidence: {
      status: "inferred",
      sources: [
        "https://historicengland.org.uk/education/schools-resources/educational-images/guildhall-market-place-lavenham-suffolk-cc001481",
      ],
      note: "A widened market place off the main through route, narrow burgage-depth plots and irregular back lanes follow the recorded plan form of English and north European market towns. Block proportions here are illustrative.",
    },
  },
  {
    id: "early-modern-european-town",
    storeys: 3,
    label: "Straightened streets and deep plots",
    culture: "european",
    from: 1500,
    to: 1850,
    bounds: [-12, 35, 40, 64],
    plan: "organic",
    block: [26, 16],
    regularity: 0.46,
    courts: 0.4,
    deadEnds: 0.16,
    tiers: [2, 1, 0],
    gates: 3,
    wall: "masonry",
    plaza: "offset",
    plazaScale: 0.19,
    civic: "head",
    evidence: {
      status: "inferred",
      sources: [],
      note: "Partly regularised streets over an older irregular core, with courts behind street ranges, is a broad reading of early modern European town plans rather than a claim about any one city.",
    },
  },
  {
    id: "colonial-survey-grid",
    storeys: 2,
    label: "Surveyed rectangular grid",
    culture: "european",
    from: 1600,
    to: 1950,
    bounds: [-125, 20, -58, 52],
    plan: "orthogonal",
    block: [34, 16],
    regularity: 0.99,
    courts: 0.22,
    deadEnds: 0.02,
    tiers: [2, 1, 0],
    gates: 4,
    wall: "none",
    plaza: "crossing",
    plazaScale: 0.16,
    civic: "head",
    evidence: {
      status: "inferred",
      sources: [],
      note: "Long rectangular blocks on a uniform survey module follow the 1683 Philadelphia plan and the 1811 Commissioners' Plan for Manhattan. The generator uses the module, not a named city's actual streets.",
    },
  },
];
