import type { CultureId } from "../../history/types";
import type { UrbanFormRule } from "./types";

/** The atlas assigns `culture` from coordinates, so for the Americas it names
 * the region's indigenous family whatever the date. These two entries describe
 * the fabric actually laid out in that region in that period; they are keyed to
 * every family the region carries so a nineteenth-century city is not given a
 * fallback layout for want of a matching key. */
const americas: CultureId[] = [
  "other-indigenous-american",
  "mesoamerican",
  "andean",
];

const spanishGrid = americas.map(
  (culture): UrbanFormRule => ({
    id: "laws-of-the-indies-grid",
    label: "Square blocks around a plaza mayor",
    culture,
    from: 1550,
    to: 1900,
    bounds: [-118, -40, -35, 33],
    plan: "orthogonal",
    block: [24, 24],
    regularity: 0.98,
    courts: 0.76,
    deadEnds: 0.03,
    tiers: [4, 2, 1],
    storeys: 2,
    gates: 4,
    wall: "none",
    plaza: "crossing",
    plazaScale: 0.19,
    civic: "head",
    squares: 1,
    square: {
      focus: "cross",
      corners: ["fountain", "tree", "planter", "tree"],
      daisCorners: "planter",
      hearth: "hidden",
    },
    evidence: {
      status: "inferred",
      sources: [],
      note: "Uniform square blocks measured out from a central arcaded plaza, with the principal civic and church frontages on that plaza, follow the town-planning ordinances issued for Spanish America in 1573. Those are prescriptions and were applied unevenly; courtyard houses and block sizes here are illustrative.",
    },
  }),
);

const industrialGrid = americas.map(
  (culture): UrbanFormRule => ({
    id: "modern-survey-grid",
    label: "Surveyed grid on long blocks",
    culture,
    from: 1850,
    to: 2026,
    bounds: [-170, 20, -52, 72],
    plan: "orthogonal",
    block: [36, 16],
    regularity: 0.99,
    courts: 0.18,
    deadEnds: 0.02,
    tiers: [5, 2, 1],
    storeys: 5,
    gates: 4,
    wall: "none",
    plaza: "crossing",
    plazaScale: 0.13,
    civic: "head",
    districts: [
      { plan: "orthogonal", block: [22, 14], regularity: 0.96 },
      { plan: "orthogonal", block: [28, 16], regularity: 0.97 },
      { plan: "orthogonal", block: [36, 18], regularity: 0.99 },
    ],
    squares: 2,
    diagonals: 1,
    verge: 2,
    greenSpaces: 0.12,
    furniture: ["lamp", "tree", "planter"],
    square: {
      focus: "statue",
      corners: ["fountain", "tree", "bench", "tree"],
      daisCorners: "planter",
      hearth: "hidden",
    },
    evidence: {
      status: "inferred",
      sources: [],
      note: "Long rectangular blocks on a uniform module, with service alleys rather than courts, continue the survey-grid plans of North American cities into the industrial period. The generator uses the module, not a named city's streets.",
    },
  }),
);

const latinGrid = americas.map(
  (culture): UrbanFormRule => ({
    id: "latin-american-metropolis",
    label: "Damero core, colonias and self-built periphery",
    culture,
    from: 1900,
    to: 2026,
    bounds: [-118, -56, -34, 33],
    plan: "orthogonal",
    block: [24, 24],
    regularity: 0.95,
    courts: 0.55,
    deadEnds: 0.08,
    tiers: [5, 2, 1],
    storeys: 3,
    gates: 4,
    wall: "none",
    plaza: "crossing",
    plazaScale: 0.17,
    civic: "head",
    districts: [
      { plan: "orthogonal", block: [24, 24], regularity: 0.97 },
      { plan: "orthogonal", block: [30, 20], regularity: 0.9 },
      { plan: "organic", block: [12, 10], regularity: 0.3 },
    ],
    squares: 2,
    diagonals: 1,
    verge: 1,
    furniture: ["lamp", "tree"],
    square: {
      focus: "cross",
      corners: ["fountain", "tree", "bench", "tree"],
      daisCorners: "planter",
      hearth: "hidden",
    },
    evidence: {
      status: "inferred",
      sources: [],
      note: "The colonial square-block damero at the centre, rectilinear colonias and avenues laid out from the 1900s, and self-built settlement on the periphery after 1940 follow the growth of Mexico City, Buenos Aires and Lima. Block sizes are illustrative.",
    },
  }),
);

const sovietBloc = (["european", "inner-eurasian"] as const).map(
  (culture): UrbanFormRule => ({
    id: "soviet-microdistricts",
    label: "Tenement rings and prefabricated microdistricts",
    culture,
    from: 1955,
    to: 2026,
    bounds: [20, 36, 90, 70],
    plan: "orthogonal",
    block: [44, 36],
    regularity: 0.9,
    courts: 0.12,
    deadEnds: 0.4,
    tiers: [6, 2, 1],
    storeys: 5,
    gates: 4,
    wall: "none",
    plaza: "crossing",
    plazaScale: 0.2,
    civic: "head",
    districts: [
      { plan: "organic", block: [16, 12], regularity: 0.45 },
      { plan: "orthogonal", block: [30, 22], regularity: 0.9 },
      { plan: "orthogonal", block: [48, 40], regularity: 0.94 },
    ],
    squares: 1,
    verge: 2,
    greenSpaces: 0.14,
    furniture: ["lamp", "tree"],
    square: { focus: "statue", corners: ["tree", "bench"], hearth: "hidden" },
    evidence: {
      status: "inferred",
      sources: [],
      note: "Superblocks of freestanding five- and nine-storey slabs round a school and shops, reached from wide avenues, follow the microdistrict (mikrorayon) norms applied across the Soviet Union from 1957. The older core keeps its irregular streets.",
    },
  }),
);

/** Fabrics laid out after about 1900, when planning offices, cadastral survey
 * and vehicle traffic reshaped street layout in ways the older regional entries
 * do not describe. Without these, every city after 1912 fell through to the
 * generic fallback, whatever it was and wherever it stood. */
export const modernForms: UrbanFormRule[] = [
  ...spanishGrid,
  ...industrialGrid,
  ...latinGrid,
  ...sovietBloc,
  {
    id: "japanese-machi",
    label: "Fine-grained blocks and land-readjustment grids",
    culture: "east-asian",
    from: 1920,
    to: 2026,
    bounds: [128, 30, 146, 46],
    plan: "organic",
    block: [16, 12],
    regularity: 0.55,
    courts: 0.05,
    deadEnds: 0.25,
    tiers: [4, 1, 1],
    storeys: 3,
    gates: 4,
    wall: "none",
    plaza: "offset",
    plazaScale: 0.12,
    civic: "side",
    districts: [
      { plan: "organic", block: [12, 10], regularity: 0.4 },
      { plan: "orthogonal", block: [20, 14], regularity: 0.82 },
      { plan: "organic", block: [14, 12], regularity: 0.5 },
    ],
    squares: 1,
    furniture: ["lamp"],
    square: { focus: "tree", corners: ["bench", "planter"], hearth: "hidden" },
    evidence: {
      status: "inferred",
      sources: [],
      note: "Very small blocks on narrow lanes, with main roads only at the edges of each neighbourhood and rectangular land-readjustment (kukaku seiri) districts laid out after the 1923 earthquake and the war, follow the fabric of Tokyo and Osaka. Illustrative dimensions.",
    },
  },
  {
    id: "old-city-and-civil-lines",
    label: "Old city, civil lines and housing colonies",
    culture: "south-asian",
    from: 1880,
    to: 2026,
    bounds: [60, 5, 97, 37],
    plan: "organic",
    block: [12, 10],
    regularity: 0.35,
    courts: 0.45,
    deadEnds: 0.3,
    tiers: [5, 2, 1],
    storeys: 4,
    gates: 4,
    wall: "none",
    plaza: "offset",
    plazaScale: 0.14,
    civic: "side",
    districts: [
      { plan: "organic", block: [12, 10], regularity: 0.35 },
      { plan: "orthogonal", block: [34, 26], regularity: 0.85 },
      { plan: "orthogonal", block: [24, 18], regularity: 0.72 },
    ],
    squares: 1,
    verge: 2,
    greenSpaces: 0.1,
    furniture: ["lamp", "tree"],
    square: { focus: "statue", corners: ["tree", "bench"], hearth: "hidden" },
    evidence: {
      status: "inferred",
      sources: [],
      note: "A dense old city of lanes beside the open, tree-lined civil lines and cantonments the colonial government laid out, then numbered housing colonies after independence, as in Delhi, Lucknow and Lahore. Illustrative dimensions.",
    },
  },
  {
    id: "medina-and-ville-nouvelle",
    label: "Old medina beside a planned new town",
    culture: "north-african-west-asian",
    from: 1912,
    to: 2026,
    bounds: [-18, 12, 65, 42],
    plan: "organic",
    block: [12, 10],
    regularity: 0.25,
    courts: 0.7,
    deadEnds: 0.45,
    tiers: [5, 2, 1],
    storeys: 5,
    gates: 4,
    wall: "none",
    plaza: "gate",
    plazaScale: 0.15,
    civic: "head",
    districts: [
      { plan: "organic", block: [12, 10], regularity: 0.25 },
      { plan: "orthogonal", block: [28, 22], regularity: 0.9 },
      { plan: "orthogonal", block: [24, 20], regularity: 0.75 },
    ],
    squares: 1,
    diagonals: 1,
    verge: 1,
    furniture: ["lamp", "tree"],
    square: { focus: "fountain", corners: ["tree", "bench"], hearth: "hidden" },
    evidence: {
      status: "inferred",
      sources: [],
      note: "The old walled city left intact beside a gridded new town of boulevards and apartment blocks, as Prost laid out Casablanca and Rabat from 1914, with later housing beyond both. The same doubling is found from Tunis to Damascus. Illustrative dimensions.",
    },
  },
  ...(["west-central-african", "east-southern-african"] as const).map(
    (culture): UrbanFormRule => ({
      id: "colonial-grid-and-townships",
      label: "Colonial grid, townships and self-built quarters",
      culture,
      from: 1900,
      to: 2026,
      bounds: [-18, -35, 52, 18],
      plan: "orthogonal",
      block: [26, 20],
      regularity: 0.9,
      courts: 0.2,
      deadEnds: 0.1,
      tiers: [5, 2, 1],
      storeys: 4,
      gates: 4,
      wall: "none",
      plaza: "crossing",
      plazaScale: 0.15,
      civic: "head",
      districts: [
        { plan: "orthogonal", block: [26, 20], regularity: 0.9 },
        { plan: "orthogonal", block: [18, 14], regularity: 0.75 },
        { plan: "organic", block: [12, 10], regularity: 0.3 },
      ],
      squares: 1,
      verge: 1,
      greenSpaces: 0.08,
      furniture: ["lamp", "tree"],
      square: { focus: "statue", corners: ["tree", "bench"], hearth: "hidden" },
      evidence: {
        status: "inferred",
        sources: [],
        note: "An administrative grid of offices and bungalows, planned townships on a smaller module and self-built quarters that outgrow both, as in Nairobi, Lagos and Johannesburg. Illustrative dimensions.",
      },
    }),
  ),
  {
    id: "shophouse-grid-and-kampung",
    label: "Shophouse grid, new estates and kampung",
    culture: "southeast-asian",
    from: 1900,
    to: 2026,
    bounds: [92, -11, 142, 24],
    plan: "orthogonal",
    block: [22, 14],
    regularity: 0.8,
    courts: 0.1,
    deadEnds: 0.15,
    tiers: [5, 2, 1],
    storeys: 3,
    gates: 4,
    wall: "none",
    plaza: "waterfront",
    plazaScale: 0.13,
    civic: "side",
    districts: [
      { plan: "orthogonal", block: [22, 14], regularity: 0.8 },
      { plan: "orthogonal", block: [34, 26], regularity: 0.85 },
      { plan: "organic", block: [12, 10], regularity: 0.3 },
    ],
    squares: 1,
    verge: 1,
    furniture: ["lamp", "tree"],
    square: { focus: "tree", corners: ["bench", "planter"], hearth: "hidden" },
    evidence: {
      status: "inferred",
      sources: [],
      note: "Narrow shophouse blocks on a grid by the river or harbour, later housing estates on a larger module, and kampung of lanes filling the ground between, as in Singapore, Kuala Lumpur and Jakarta. Illustrative dimensions.",
    },
  },
  {
    id: "australasian-grid",
    label: "Colonial grid and quarter-acre suburbs",
    culture: "european",
    from: 1840,
    to: 2026,
    bounds: [110, -48, 179, -10],
    plan: "orthogonal",
    block: [30, 18],
    regularity: 0.97,
    courts: 0.1,
    deadEnds: 0.04,
    tiers: [5, 2, 1],
    storeys: 3,
    gates: 4,
    wall: "none",
    plaza: "crossing",
    plazaScale: 0.13,
    civic: "head",
    districts: [
      { plan: "orthogonal", block: [30, 18], regularity: 0.97 },
      { plan: "orthogonal", block: [26, 16], regularity: 0.9 },
      { plan: "orthogonal", block: [32, 20], regularity: 0.85 },
    ],
    squares: 1,
    verge: 1,
    greenSpaces: 0.12,
    furniture: ["lamp", "tree"],
    square: { focus: "statue", corners: ["tree", "bench"], hearth: "hidden" },
    evidence: {
      status: "inferred",
      sources: [],
      note: "A surveyed central grid with service lanes, as Hoddle laid out Melbourne in 1837 and Light laid out Adelaide, with detached suburbs spreading along the rail and tram lines. Illustrative dimensions.",
    },
  },
  {
    id: "chinese-superblock",
    label: "Compounds on wide arterials",
    culture: "east-asian",
    from: 1912,
    to: 2026,
    bounds: [100, 18, 126, 46],
    plan: "orthogonal",
    block: [40, 30],
    regularity: 0.92,
    courts: 0.7,
    deadEnds: 0.3,
    tiers: [6, 2, 1],
    storeys: 3,
    gates: 4,
    wall: "none",
    plaza: "crossing",
    plazaScale: 0.2,
    civic: "head",
    districts: [
      { plan: "organic", block: [14, 12], regularity: 0.5 },
      { plan: "orthogonal", block: [40, 30], regularity: 0.92 },
    ],
    squares: 1,
    verge: 1,
    furniture: ["lamp", "tree"],
    square: { focus: "statue", corners: ["tree", "bench"], hearth: "hidden" },
    evidence: {
      status: "inferred",
      sources: [],
      note: "Very large residential compounds reached from a few wide arterials, with the interior served by its own lanes, follow the work-unit and later gated-estate pattern that dominates twentieth-century Chinese city building. Block dimensions here are illustrative, and the engine builds street ranges rather than apartment blocks.",
    },
  },
  {
    id: "japanese-colonial-grid",
    label: "Surveyed colonial grid",
    culture: "east-asian",
    from: 1895,
    to: 1960,
    bounds: [119, 21, 146, 46],
    plan: "orthogonal",
    block: [26, 18],
    regularity: 0.97,
    courts: 0.4,
    deadEnds: 0.05,
    tiers: [4, 2, 1],
    storeys: 2,
    gates: 4,
    wall: "none",
    plaza: "crossing",
    plazaScale: 0.15,
    civic: "head",
    squares: 1,
    furniture: ["lamp"],
    square: {
      focus: "statue",
      corners: ["tree", "bench", "planter", "bench"],
      daisCorners: "planter",
      hearth: "hidden",
    },
    evidence: {
      status: "inferred",
      sources: [],
      note: "A regular surveyed grid with diagonal-free rectangular blocks follows the city-plan ordinances applied in Taiwanese and Japanese cities from the late 1890s, of which the Taichung plan of 1900 is an early example. The engine uses the module; it does not reproduce a particular plan or its buildings.",
    },
  },
  {
    id: "perimeter-block-city",
    label: "Boulevards and perimeter blocks",
    culture: "european",
    from: 1850,
    to: 2026,
    bounds: [-12, 35, 40, 64],
    plan: "orthogonal",
    block: [30, 22],
    regularity: 0.9,
    courts: 0.82,
    deadEnds: 0.08,
    tiers: [5, 2, 1],
    storeys: 3,
    gates: 4,
    wall: "none",
    plaza: "crossing",
    plazaScale: 0.16,
    civic: "head",
    districts: [
      { plan: "organic", block: [14, 11], regularity: 0.4 },
      { plan: "orthogonal", block: [26, 20], regularity: 0.9 },
      { plan: "orthogonal", block: [30, 22], regularity: 0.95 },
    ],
    squares: 2,
    diagonals: 2,
    verge: 1,
    furniture: ["lamp", "tree", "planter"],
    square: {
      focus: "fountain",
      corners: ["statue", "tree", "bench", "tree"],
      daisCorners: "planter",
      hearth: "hidden",
    },
    evidence: {
      status: "inferred",
      sources: [],
      note: "Closed blocks built to the street line around a shared interior court, on boulevards cut wider than the streets they replaced, follow the Haussmann works in Paris and Cerda's Eixample in Barcelona. Applying it broadly across Europe is an inference; individual cities differ substantially.",
    },
  },
  {
    id: "modern-survey-grid",
    label: "Surveyed grid on long blocks",
    culture: "european",
    from: 1850,
    to: 2026,
    bounds: [-170, 20, -52, 72],
    plan: "orthogonal",
    block: [36, 16],
    regularity: 0.99,
    courts: 0.18,
    deadEnds: 0.02,
    tiers: [5, 2, 1],
    storeys: 3,
    gates: 4,
    wall: "none",
    plaza: "crossing",
    plazaScale: 0.13,
    civic: "head",
    districts: [
      { plan: "orthogonal", block: [22, 14], regularity: 0.96 },
      { plan: "orthogonal", block: [28, 16], regularity: 0.97 },
      { plan: "orthogonal", block: [36, 18], regularity: 0.99 },
    ],
    squares: 2,
    diagonals: 1,
    verge: 1,
    furniture: ["lamp", "tree", "planter"],
    square: {
      focus: "statue",
      corners: ["fountain", "tree", "bench", "tree"],
      daisCorners: "planter",
      hearth: "hidden",
    },
    evidence: {
      status: "inferred",
      sources: [],
      note: "Long rectangular blocks on a uniform module, with service alleys rather than courts, continue the survey-grid plans of North American cities into the industrial period. The generator uses the module, not a named city's streets.",
    },
  },
];
