import type { CultureId } from "../../history/types";
import type { UrbanFormRule } from "./types";

/** The atlas assigns `culture` from coordinates, so for the Americas it names
 * the region's indigenous family whatever the date. These two entries describe
 * the fabric actually laid out in that region in that period; they are keyed to
 * every family the region carries so a nineteenth-century city is not given a
 * fallback layout for want of a matching key. */
const americas: CultureId[] = [
  "other-indigenous-american",
  "mesoamerican",
  "andean",
];

const spanishGrid = americas.map(
  (culture): UrbanFormRule => ({
    id: "laws-of-the-indies-grid",
    label: "Square blocks around a plaza mayor",
    culture,
    from: 1550,
    to: 1900,
    bounds: [-118, -40, -35, 33],
    plan: "orthogonal",
    block: [24, 24],
    regularity: 0.98,
    courts: 0.76,
    deadEnds: 0.03,
    tiers: [4, 2, 1],
    storeys: 2,
    gates: 4,
    wall: "none",
    plaza: "crossing",
    plazaScale: 0.19,
    civic: "head",
    squares: 1,
    square: {
      focus: "cross",
      corners: ["fountain", "tree", "planter", "tree"],
      daisCorners: "planter",
      hearth: "hidden",
    },
    evidence: {
      status: "inferred",
      sources: [],
      note: "Uniform square blocks measured out from a central arcaded plaza, with the principal civic and church frontages on that plaza, follow the town-planning ordinances issued for Spanish America in 1573. Those are prescriptions and were applied unevenly; courtyard houses and block sizes here are illustrative.",
    },
  }),
);

const industrialGrid = americas.map(
  (culture): UrbanFormRule => ({
    id: "modern-survey-grid",
    label: "Surveyed grid on long blocks",
    culture,
    from: 1850,
    to: 2026,
    bounds: [-125, 20, -58, 52],
    plan: "orthogonal",
    block: [36, 16],
    regularity: 0.99,
    courts: 0.18,
    deadEnds: 0.02,
    tiers: [5, 2, 1],
    storeys: 5,
    gates: 4,
    wall: "none",
    plaza: "crossing",
    plazaScale: 0.13,
    civic: "head",
    districts: [
      { plan: "orthogonal", block: [22, 14], regularity: 0.96 },
      { plan: "orthogonal", block: [28, 16], regularity: 0.97 },
      { plan: "orthogonal", block: [36, 18], regularity: 0.99 },
    ],
    squares: 2,
    diagonals: 1,
    verge: 2,
    greenSpaces: 0.12,
    furniture: ["lamp", "tree", "planter"],
    square: {
      focus: "statue",
      corners: ["fountain", "tree", "bench", "tree"],
      daisCorners: "planter",
      hearth: "hidden",
    },
    evidence: {
      status: "inferred",
      sources: [],
      note: "Long rectangular blocks on a uniform module, with service alleys rather than courts, continue the survey-grid plans of North American cities into the industrial period. The generator uses the module, not a named city's streets.",
    },
  }),
);

/** Fabrics laid out after about 1900, when planning offices, cadastral survey
 * and vehicle traffic reshaped street layout in ways the older regional entries
 * do not describe. Without these, every city after 1912 fell through to the
 * generic fallback, whatever it was and wherever it stood. */
export const modernForms: UrbanFormRule[] = [
  ...spanishGrid,
  ...industrialGrid,
  {
    id: "chinese-superblock",
    label: "Compounds on wide arterials",
    culture: "east-asian",
    from: 1912,
    to: 2026,
    bounds: [100, 18, 126, 46],
    plan: "orthogonal",
    block: [40, 30],
    regularity: 0.92,
    courts: 0.7,
    deadEnds: 0.3,
    tiers: [6, 2, 1],
    storeys: 3,
    gates: 4,
    wall: "none",
    plaza: "crossing",
    plazaScale: 0.2,
    civic: "head",
    districts: [
      { plan: "organic", block: [14, 12], regularity: 0.5 },
      { plan: "orthogonal", block: [40, 30], regularity: 0.92 },
    ],
    squares: 1,
    verge: 1,
    furniture: ["lamp", "tree"],
    square: { focus: "statue", corners: ["tree", "bench"], hearth: "hidden" },
    evidence: {
      status: "inferred",
      sources: [],
      note: "Very large residential compounds reached from a few wide arterials, with the interior served by its own lanes, follow the work-unit and later gated-estate pattern that dominates twentieth-century Chinese city building. Block dimensions here are illustrative, and the engine builds street ranges rather than apartment blocks.",
    },
  },
  {
    id: "japanese-colonial-grid",
    label: "Surveyed colonial grid",
    culture: "east-asian",
    from: 1895,
    to: 1960,
    bounds: [119, 21, 146, 46],
    plan: "orthogonal",
    block: [26, 18],
    regularity: 0.97,
    courts: 0.4,
    deadEnds: 0.05,
    tiers: [4, 2, 1],
    storeys: 2,
    gates: 4,
    wall: "none",
    plaza: "crossing",
    plazaScale: 0.15,
    civic: "head",
    squares: 1,
    furniture: ["lamp"],
    square: {
      focus: "statue",
      corners: ["tree", "bench", "planter", "bench"],
      daisCorners: "planter",
      hearth: "hidden",
    },
    evidence: {
      status: "inferred",
      sources: [],
      note: "A regular surveyed grid with diagonal-free rectangular blocks follows the city-plan ordinances applied in Taiwanese and Japanese cities from the late 1890s, of which the Taichung plan of 1900 is an early example. The engine uses the module; it does not reproduce a particular plan or its buildings.",
    },
  },
  {
    id: "perimeter-block-city",
    label: "Boulevards and perimeter blocks",
    culture: "european",
    from: 1850,
    to: 2026,
    bounds: [-12, 35, 40, 64],
    plan: "orthogonal",
    block: [30, 22],
    regularity: 0.9,
    courts: 0.82,
    deadEnds: 0.08,
    tiers: [5, 2, 1],
    storeys: 3,
    gates: 4,
    wall: "none",
    plaza: "crossing",
    plazaScale: 0.16,
    civic: "head",
    districts: [
      { plan: "organic", block: [14, 11], regularity: 0.4 },
      { plan: "orthogonal", block: [26, 20], regularity: 0.9 },
      { plan: "orthogonal", block: [30, 22], regularity: 0.95 },
    ],
    squares: 2,
    diagonals: 2,
    verge: 1,
    furniture: ["lamp", "tree", "planter"],
    square: {
      focus: "fountain",
      corners: ["statue", "tree", "bench", "tree"],
      daisCorners: "planter",
      hearth: "hidden",
    },
    evidence: {
      status: "inferred",
      sources: [],
      note: "Closed blocks built to the street line around a shared interior court, on boulevards cut wider than the streets they replaced, follow the Haussmann works in Paris and Cerda's Eixample in Barcelona. Applying it broadly across Europe is an inference; individual cities differ substantially.",
    },
  },
  {
    id: "modern-survey-grid",
    label: "Surveyed grid on long blocks",
    culture: "european",
    from: 1850,
    to: 2026,
    bounds: [-125, 20, -58, 52],
    plan: "orthogonal",
    block: [36, 16],
    regularity: 0.99,
    courts: 0.18,
    deadEnds: 0.02,
    tiers: [5, 2, 1],
    storeys: 3,
    gates: 4,
    wall: "none",
    plaza: "crossing",
    plazaScale: 0.13,
    civic: "head",
    districts: [
      { plan: "orthogonal", block: [22, 14], regularity: 0.96 },
      { plan: "orthogonal", block: [28, 16], regularity: 0.97 },
      { plan: "orthogonal", block: [36, 18], regularity: 0.99 },
    ],
    squares: 2,
    diagonals: 1,
    verge: 1,
    furniture: ["lamp", "tree", "planter"],
    square: {
      focus: "statue",
      corners: ["fountain", "tree", "bench", "tree"],
      daisCorners: "planter",
      hearth: "hidden",
    },
    evidence: {
      status: "inferred",
      sources: [],
      note: "Long rectangular blocks on a uniform module, with service alleys rather than courts, continue the survey-grid plans of North American cities into the industrial period. The generator uses the module, not a named city's streets.",
    },
  },
];
