import type { UrbanFormRule } from "./types";

export const southAsiaForms: UrbanFormRule[] = [
  {
    id: "indus-street-grid",
    storeys: 2,
    label: "Gridded streets and lanes",
    culture: "south-asian",
    from: -2600,
    to: -1700,
    bounds: [66, 22, 76, 32],
    plan: "orthogonal",
    block: [22, 18],
    regularity: 0.9,
    courts: 0.7,
    deadEnds: 0.18,
    tiers: [3, 2, 1],
    surface: "earth",
    gates: 3,
    wall: "none",
    plaza: "offset",
    plazaScale: 0.16,
    civic: "side",
    square: { focus: "well", corners: ["bench", "brazier"], hearth: "brazier" },
    evidence: {
      status: "inferred",
      sources: [],
      note: "Wide straight streets with narrower lanes serving courtyard houses follow the excavated street pattern at Mohenjo-daro and Harappa. Dimensions and the arrangement here are an inference for this engine.",
    },
  },
  {
    id: "shastra-town-grid",
    storeys: 2,
    label: "Quartered town on cardinal streets",
    culture: "south-asian",
    from: -400,
    to: 1900,
    bounds: [66, 6, 92, 35],
    plan: "orthogonal",
    block: [26, 20],
    regularity: 0.78,
    courts: 0.72,
    deadEnds: 0.2,
    tiers: [4, 2, 1],
    surface: "earth",
    gates: 4,
    wall: "earth",
    plaza: "crossing",
    plazaScale: 0.18,
    civic: "head",
    square: {
      focus: "tree",
      corners: ["well", "stele", "bench", "stele"],
      daisCorners: "none",
      hearth: "brazier",
    },
    evidence: {
      status: "inferred",
      sources: [],
      note: "Cardinal main streets dividing a town into quarters, with courtyard houses on narrow lanes, follow the town-planning prescriptions in the Arthashastra and the Manasara Shilpashastra. Those are normative texts; actual towns varied widely, and this layout is an inference rather than a surveyed plan.",
    },
  },
];
