import type { UrbanFormRule } from "./types";

export const southeastAsiaForms: UrbanFormRule[] = [
  {
    id: "angkorian-hydraulic-grid",
    storeys: 1,
    label: "Temple precinct on a moated grid",
    culture: "southeast-asian",
    from: 800,
    to: 1450,
    bounds: [101, 9, 108, 16],
    plan: "orthogonal",
    block: [28, 24],
    regularity: 0.95,
    courts: 0.6,
    deadEnds: 0.06,
    tiers: [4, 2, 1],
    surface: "earth",
    gates: 4,
    wall: "masonry",
    plaza: "crossing",
    plazaScale: 0.3,
    civic: "head",
    square: {
      focus: "altar",
      corners: ["stele", "brazier"],
      daisCorners: "none",
      hearth: "brazier",
    },
    evidence: {
      status: "inferred",
      sources: [],
      note: "A cardinal grid of axes and water channels around a central precinct follows the surveyed layout of Angkor Thom and the Angkorian hydraulic plan. The engine reproduces the grid, not the temple complexes or reservoirs.",
    },
  },
  {
    id: "riverine-trading-town",
    storeys: 1,
    label: "Trading town along the water",
    culture: "southeast-asian",
    from: 800,
    to: 1900,
    bounds: [92, -11, 142, 24],
    plan: "linear",
    block: [22, 14],
    regularity: 0.3,
    courts: 0.4,
    deadEnds: 0.24,
    tiers: [3, 2, 1],
    surface: "earth",
    gates: 2,
    wall: "none",
    plaza: "waterfront",
    plazaScale: 0.16,
    civic: "side",
    square: {
      focus: "kiosk",
      corners: ["well", "bench", "planter", "bench"],
      hearth: "hidden",
    },
    evidence: {
      status: "inferred",
      sources: [],
      note: "A built spine following a river or shore with short lanes running back from it follows descriptions of Ayutthaya and Melaka as water-oriented trading towns. Proportions here are illustrative.",
    },
  },
];
