import type { UrbanFormRule } from "./types";

/** Also carries the inner Eurasian caravan-town entry, which shares the
 * courtyard-and-lane fabric while organising it around a very large maidan. */
export const westAsiaForms: UrbanFormRule[] = [
  {
    id: "mesopotamian-lane-fabric",
    storeys: 2,
    label: "Courtyard houses on winding lanes",
    culture: "north-african-west-asian",
    from: -3000,
    to: 650,
    bounds: [25, 12, 65, 42],
    plan: "organic",
    block: [20, 16],
    regularity: 0.18,
    courts: 0.78,
    deadEnds: 0.34,
    tiers: [2, 1, 1],
    surface: "earth",
    gates: 3,
    wall: "masonry",
    plaza: "offset",
    plazaScale: 0.14,
    civic: "side",
    square: { focus: "well", corners: ["brazier", "bench"], hearth: "brazier" },
    evidence: {
      status: "inferred",
      sources: [],
      note: "Dense courtyard houses reached by irregular lanes and blind alleys follow the excavated domestic quarters at Ur and Babylon. The generated street pattern is an inference, not an excavation plan.",
    },
  },
  {
    // A Greek foundation, not a grown city: the grid is the point of it.
    id: "hippodamian-foundation",
    storeys: 2,
    label: "Surveyed grid on a colonnaded axis",
    culture: "north-african-west-asian",
    from: -332,
    to: 30,
    bounds: [20, 27, 40, 42],
    plan: "orthogonal",
    block: [30, 18],
    regularity: 0.96,
    courts: 0.6,
    deadEnds: 0.04,
    tiers: [4, 2, 1],
    gates: 4,
    wall: "masonry",
    plaza: "crossing",
    plazaScale: 0.2,
    civic: "head",
    square: {
      focus: "statue",
      corners: ["fountain", "bench"],
      hearth: "hidden",
    },
    evidence: {
      status: "inferred",
      sources: [],
      note: "Uniform rectangular blocks on two wide crossing avenues follow the Hippodamian plans recorded at Miletus and Priene and the reported grid of Hellenistic Alexandria. The engine uses the module; it does not reproduce a surveyed city or its named monuments.",
    },
  },
  {
    id: "medina-quarter",
    storeys: 2,
    label: "Quarters on blind alleys",
    culture: "north-african-west-asian",
    from: 650,
    to: 1900,
    bounds: [-12, 12, 65, 42],
    plan: "organic",
    block: [18, 15],
    regularity: 0.12,
    courts: 0.82,
    deadEnds: 0.46,
    tiers: [3, 1, 1],
    gates: 4,
    wall: "masonry",
    plaza: "offset",
    plazaScale: 0.13,
    civic: "side",
    square: {
      focus: "fountain",
      corners: ["well", "bench", "planter", "bench"],
      hearth: "hidden",
    },
    evidence: {
      status: "inferred",
      sources: [],
      note: "A few through routes between gates, residential quarters served by private dead-end alleys, and courtyard houses turned away from the street follow the widely described fabric of North African and West Asian medinas. Proportions here are illustrative; individual cities differ substantially.",
    },
  },
  {
    id: "maidan-caravan-town",
    storeys: 2,
    label: "Courtyard fabric around a great square",
    culture: "inner-eurasian",
    from: 1200,
    to: 1900,
    bounds: [52, 32, 82, 48],
    plan: "radial",
    block: [22, 17],
    regularity: 0.34,
    courts: 0.74,
    deadEnds: 0.3,
    tiers: [4, 2, 1],
    gates: 4,
    wall: "earth",
    plaza: "crossing",
    plazaScale: 0.3,
    civic: "head",
    square: {
      focus: "fountain",
      corners: ["kiosk", "bench", "planter", "bench"],
      hearth: "hidden",
    },
    evidence: {
      status: "inferred",
      sources: [],
      note: "A dominant public square with routes converging on it, surrounded by courtyard fabric, follows the Registan ensemble at Samarkand and comparable Timurid maidans. The square's size relative to the whole settlement here is a gameplay choice.",
    },
  },
];
