import { ANTIQUITY, DEEP, EARLY, EARLY_MODERN, HISTORIC, HOLOCENE, INDUSTRIAL, MEDIEVAL, MODERN, PREMODERN, type SkillContext } from "./types";

export const marksmanship: SkillContext = {
  entries: [
    { eras: DEEP, wiki: ["Spear-thrower", "Bow and arrow"], sources: ["kelly", "keeley"] },
    { eras: HOLOCENE, wiki: ["Bow and arrow", "Sling (weapon)", "Microlith"], sources: ["keeley", "mithen"] },
    { eras: EARLY, wiki: ["Composite bow", "Sling (weapon)"], sources: ["chase", "vanDeMieroop"] },
    { eras: ANTIQUITY, wiki: ["Balearic slingers", "Composite bow", "Scythians"], sources: ["chase", "keeganWar"] },
    { eras: MEDIEVAL, wiki: ["English longbow", "Crossbow", "Mounted archery"], sources: ["hardy", "chase"] },
    { eras: EARLY_MODERN, wiki: ["Arquebus", "Musket", "Matchlock"], sources: ["chase", "perrin"] },
    { eras: INDUSTRIAL, wiki: ["Rifle", "Minié ball"], sources: ["keeganFace", "bayly"] },
    { eras: MODERN, wiki: ["Marksman", "Shooting sports", "Sniper"], sources: ["keeganWar"] },
    { cultures: ["european"], eras: MEDIEVAL, wiki: ["English longbow", "Crossbow", "Archery"], sources: ["hardy"] },
    { cultures: ["north-african-west-asian"], eras: HISTORIC, wiki: ["Sling (weapon)", "Composite bow", "Turkish bow"], sources: ["chase", "vanDeMieroop"] },
    { cultures: ["inner-eurasian"], eras: PREMODERN, wiki: ["Mounted archery", "Composite bow", "Eurasian nomads"], sources: ["anthony", "allsen", "barfield"] },
    { cultures: ["south-asian"], eras: HISTORIC, wiki: ["Dhanurveda", "Composite bow"], sources: ["thapar", "chase"] },
    { cultures: ["east-asian"], eras: HISTORIC, wiki: ["Chinese archery", "Kyūdō", "Crossbow"], sources: ["selby", "perrin"] },
    { cultures: ["southeast-asian"], eras: PREMODERN, wiki: ["Blowgun", "Crossbow"], sources: ["reid", "bellwoodIndo"] },
    { cultures: ["west-central-african"], eras: PREMODERN, wiki: ["Arrow poison", "Bow and arrow"], sources: ["thornton", "vansinaPaths"] },
    { cultures: ["east-southern-african"], eras: PREMODERN, wiki: ["Arrow poison", "San peoples"], sources: ["leeKung", "ehret"] },
    { cultures: ["mesoamerican"], eras: PREMODERN, wiki: ["Spear-thrower", "Sling (weapon)"], sources: ["hassigWar", "clendinnen"] },
    { cultures: ["andean"], eras: PREMODERN, wiki: ["Sling (weapon)", "Bolas"], sources: ["daltroy"] },
    { cultures: ["other-indigenous-american"], eras: PREMODERN, wiki: ["Bow and arrow", "Spear-thrower"], sources: ["hamalainen", "keeley"] },
    { cultures: ["australian-pacific"], eras: PREMODERN, wiki: ["Boomerang", "Woomera (spear-thrower)"], sources: ["blainey", "gammage"] },
    { wiki: ["Archery", "Sling (weapon)"], sources: ["chase", "hardy"] },
  ],
  techniques: {
    "long-arm": { wiki: "Spear-thrower", note: "The spear-thrower lengthened the arm and roughly doubled a throw's force, long before the bow." },
    hurler: { wiki: "Sling (weapon)", note: "Slingers were feared soldiers from the Balearic Islands to the Andes, and a slung stone could break bone." },
    "heavy-draw": { wiki: "English longbow", note: "Longbows recovered from the Mary Rose needed great strength to draw, and archers' skeletons show it." },
    "pinning-shot": { note: "Hunters often aimed to cripple and then follow; poison and tracking finished what the arrow began." },
    deadeye: { wiki: "Kyūdō", note: "In Japanese kyūdō, breath and posture matter as much as the target itself." },
    volley: { wiki: "Volley fire", note: "Massed volleys traded single accuracy for the weight of many arrows or shots at once." },
  },
};

export const arms: SkillContext = {
  entries: [
    { eras: DEEP, wiki: ["Prehistoric warfare", "Spear", "Club (weapon)"], sources: ["keeley"] },
    { eras: HOLOCENE, wiki: ["Prehistoric warfare", "Talheim Death Pit"], sources: ["keeley"] },
    { eras: EARLY, wiki: ["Khopesh", "Spear"], sources: ["keeganWar", "vanDeMieroop"] },
    { eras: ANTIQUITY, wiki: ["Hoplite", "Phalanx", "Roman legion"], sources: ["hanson", "keeganWar"] },
    { eras: MEDIEVAL, wiki: ["Knight", "Longsword"], sources: ["oakeshott", "keeganFace"] },
    { eras: EARLY_MODERN, wiki: ["Pike and shot", "Rapier"], sources: ["anglo", "chase"] },
    { eras: INDUSTRIAL, wiki: ["Bayonet", "Cavalry"], sources: ["keeganFace", "bayly"] },
    { eras: MODERN, wiki: ["Hand-to-hand combat", "Trench warfare", "Martial arts"], sources: ["keeganFace", "keeganWar"] },
    { cultures: ["european", "north-african-west-asian"], eras: [...EARLY, ...ANTIQUITY], wiki: ["Hoplite", "Phalanx", "Roman legion"], sources: ["hanson", "keeganWar"] },
    { cultures: ["european"], eras: MEDIEVAL, wiki: ["Knight", "Longsword", "Historical European martial arts"], sources: ["oakeshott", "anglo"] },
    { cultures: ["european"], eras: EARLY_MODERN, wiki: ["Historical European martial arts", "Rapier", "Pike and shot"], sources: ["anglo"] },
    { cultures: ["north-african-west-asian"], eras: [...MEDIEVAL, ...EARLY_MODERN], wiki: ["Mamluk", "Damascus steel"], sources: ["keeganWar"] },
    { cultures: ["inner-eurasian"], eras: PREMODERN, wiki: ["Eurasian nomads", "Sabre"], sources: ["barfield", "beckwith"] },
    { cultures: ["south-asian"], eras: PREMODERN, wiki: ["Talwar", "Kalaripayattu", "War elephant"], sources: ["thapar", "keeganWar"] },
    { cultures: ["east-asian"], eras: PREMODERN, wiki: ["Samurai", "Japanese sword", "Chinese martial arts"], sources: ["friday", "diCosmo"] },
    { cultures: ["southeast-asian"], eras: PREMODERN, wiki: ["Kris", "Pencak silat"], sources: ["reid"] },
    { cultures: ["west-central-african"], eras: PREMODERN, wiki: ["Dahomey Amazons", "Military history of Africa"], sources: ["thornton", "iliffe"] },
    { cultures: ["east-southern-african"], eras: PREMODERN, wiki: ["Assegai", "Impi"], sources: ["iliffe", "ehret"] },
    { cultures: ["mesoamerican"], eras: PREMODERN, wiki: ["Aztec warfare", "Macuahuitl", "Jaguar warrior"], sources: ["hassigWar", "clendinnen"] },
    { cultures: ["andean"], eras: PREMODERN, wiki: ["Inca army", "Mace (bludgeon)"], sources: ["daltroy"] },
    { cultures: ["other-indigenous-american"], eras: PREMODERN, wiki: ["Tomahawk", "Gunstock war club"], sources: ["whiteMiddle", "keeley"] },
    { cultures: ["australian-pacific"], eras: PREMODERN, wiki: ["Mere (weapon)", "Taiaha"], sources: ["thomas", "kirch"] },
    { wiki: ["Hand-to-hand combat", "Martial arts"], sources: ["keeley", "anglo"] },
  ],
  techniques: {
    "heavy-swing": { note: "Weight and momentum did the work of many premodern weapons, from stone maces to the two-handed axe." },
    "sure-grip": { wiki: "Hilt", note: "Grips of wrapped leather, cord and ray skin kept a weapon from turning in a sweating hand." },
    "double-strike": { wiki: "Fencing", note: "Fencing manuals teach combinations, blows that set up the next." },
    lunge: { wiki: "Lunge (fencing)", note: "The lunge, reaching with the front foot, was systematised by Renaissance fencing masters." },
    sweep: { note: "Wide cuts suited open ground and loose order; tight formations demanded thrusts instead." },
    riposte: { wiki: "Riposte", note: "A riposte answers a parry at once, turning defence into attack." },
  },
};
