import { AFTER_ICE, ANTIQUITY, DEEP, EARLY, EARLY_MODERN, HISTORIC, HOLOCENE, INDUSTRIAL, MEDIEVAL, MODERN, PREMODERN, type SkillContext } from "./types";

export const hunting: SkillContext = {
  entries: [
    { eras: DEEP, wiki: ["Hunter-gatherer", "Upper Paleolithic", "Persistence hunting"], sources: ["kelly", "mithen", "leeDevore"] },
    { eras: HOLOCENE, wiki: ["Mesolithic", "Microlith", "Hunter-gatherer"], sources: ["mithen", "kelly"] },
    { eras: EARLY, wiki: ["Lion Hunt of Ashurbanipal", "Hunting"], sources: ["allsen", "vanDeMieroop"] },
    { eras: ANTIQUITY, wiki: ["Venatio", "Hunting"], sources: ["allsen", "keeganWar"] },
    { eras: MEDIEVAL, wiki: ["Falconry", "Hunting"], sources: ["allsen", "cummins"] },
    { eras: EARLY_MODERN, wiki: ["Fur trade", "Hunting"], sources: ["whiteMiddle", "allsen"] },
    { eras: INDUSTRIAL, wiki: ["Big-game hunting", "Fur trade"], sources: ["mackenzie", "isenberg"] },
    { eras: MODERN, wiki: ["Conservation movement", "Poaching", "Wildlife management"], sources: ["jacoby", "mcneill"] },
    { cultures: ["european"], eras: HISTORIC, wiki: ["Medieval hunting", "Royal forest", "Falconry"], sources: ["cummins", "almond"] },
    { cultures: ["north-african-west-asian"], eras: HISTORIC, wiki: ["Lion Hunt of Ashurbanipal", "Falconry", "Saluki"], sources: ["allsen", "vanDeMieroop"] },
    { cultures: ["inner-eurasian"], eras: PREMODERN, wiki: ["Berkutchi", "Falconry", "Mounted archery"], sources: ["allsen", "barfield"] },
    { cultures: ["south-asian"], eras: [...HISTORIC, ...INDUSTRIAL], wiki: ["Tiger hunting", "Falconry"], sources: ["allsen", "gadgilGuha"] },
    { cultures: ["east-asian"], eras: HISTORIC, wiki: ["Matagi", "Falconry"], sources: ["allsen", "elvin"] },
    { cultures: ["southeast-asian"], eras: PREMODERN, wiki: ["Blowgun", "Orang Asli"], sources: ["kelly", "bellwoodIndo"] },
    { cultures: ["west-central-african"], eras: PREMODERN, wiki: ["Mbuti people", "Bushmeat"], sources: ["vansinaPaths", "kelly"] },
    { cultures: ["east-southern-african"], eras: AFTER_ICE, wiki: ["San peoples", "Arrow poison"], sources: ["leeKung", "kelly"] },
    { cultures: ["east-southern-african", "south-asian"], eras: INDUSTRIAL, wiki: ["Big-game hunting", "Game reserve"], sources: ["mackenzie"] },
    { cultures: ["mesoamerican"], eras: AFTER_ICE, wiki: ["White-tailed deer", "Spear-thrower"], sources: ["coe", "mann"] },
    { cultures: ["andean"], eras: AFTER_ICE, wiki: ["Vicuña", "Spear-thrower"], sources: ["daltroy", "mann"] },
    { cultures: ["other-indigenous-american"], eras: PREMODERN, wiki: ["American bison hunting", "Buffalo jump", "Plains Indians"], sources: ["isenberg", "krech", "hamalainen"] },
    { cultures: ["australian-pacific"], eras: PREMODERN, wiki: ["Aboriginal Australians", "Fire-stick farming", "Boomerang"], sources: ["gammage", "blainey"] },
    { wiki: ["Hunting", "Hunter-gatherer"], sources: ["kelly", "allsen"] },
  ],
  techniques: {
    stalker: { wiki: "Deer stalking", note: "Getting within range of an animal that has not yet noticed you, by wind, cover and patience, was the heart of hunting before long-range guns." },
    butcher: { wiki: "Butcher", note: "Cut-marks on bones are some of the oldest evidence of human behaviour; using the whole carcass, hide and sinew included, was the norm." },
    "clean-kill": { wiki: "Fair chase", note: "Knowing where to strike an animal was craft knowledge passed from hunter to hunter, and a quick kill was valued for practical as well as moral reasons." },
    "quick-windup": { note: "Speed of the blow mattered most at close quarters, as with a spear held against a boar or a club against small game." },
    "big-game": { wiki: "Megafauna", note: "Mammoth, bison and aurochs hunts took cooperation and planning, and the archaeology of kill sites shows how they were organised." },
    tracker: { wiki: "Tracking (hunting)", note: "Among the San, reading tracks was an art of inference that some scholars see as close to scientific reasoning." },
  },
};

export const foraging: SkillContext = {
  entries: [
    { eras: DEEP, wiki: ["Hunter-gatherer", "Paleolithic diet"], sources: ["kelly", "leeKung", "sahlins"] },
    { eras: HOLOCENE, wiki: ["Mesolithic", "Neolithic Revolution"], sources: ["mithen", "barker"] },
    { eras: EARLY, wiki: ["Famine food", "Non-timber forest product"], sources: ["scott", "kelly"] },
    { eras: ANTIQUITY, wiki: ["De materia medica", "Famine food"], sources: ["scott", "kelly"] },
    { eras: MEDIEVAL, wiki: ["Gleaning", "Commons", "Pannage"], sources: ["wickham", "rackhamCountryside"] },
    { eras: EARLY_MODERN, wiki: ["Commons", "Famine food"], sources: ["thompson", "rackhamCountryside"] },
    { eras: INDUSTRIAL, wiki: ["Enclosure", "Gleaning"], sources: ["thompson", "osterhammel"] },
    { eras: MODERN, wiki: ["Non-timber forest product", "Mushroom hunting"], sources: ["mcneill", "kelly"] },
    { cultures: ["european"], eras: [...MEDIEVAL, ...EARLY_MODERN, ...INDUSTRIAL], wiki: ["Gleaning", "Commons", "Pannage"], sources: ["thompson", "rackhamCountryside"] },
    { cultures: ["north-african-west-asian"], eras: [...DEEP, ...HOLOCENE], wiki: ["Natufian culture", "Kebaran culture", "Emmer"], sources: ["barYosef", "scott", "mithen"] },
    { cultures: ["north-african-west-asian"], eras: [...HISTORIC, ...INDUSTRIAL], wiki: ["Terfezia", "Bedouin"], sources: ["bulliet", "kelly"] },
    { cultures: ["inner-eurasian"], eras: PREMODERN, wiki: ["Siberian pine", "Evenks"], sources: ["kelly", "beckwith"] },
    { cultures: ["south-asian"], eras: PREMODERN, wiki: ["Madhuca longifolia", "Adivasi", "Non-timber forest product"], sources: ["gadgilGuha", "thapar"] },
    { cultures: ["east-asian"], eras: [...HOLOCENE, ...EARLY], wiki: ["Jōmon period", "Acorn"], sources: ["kelly", "elvin"] },
    { cultures: ["east-asian"], eras: [...ANTIQUITY, ...MEDIEVAL, ...EARLY_MODERN, ...INDUSTRIAL], wiki: ["Matsutake", "Satoyama"], sources: ["elvin", "totman"] },
    { cultures: ["southeast-asian"], eras: PREMODERN, wiki: ["Metroxylon sagu", "Orang Asli", "Non-timber forest product"], sources: ["bellwoodIndo", "reid"] },
    { cultures: ["west-central-african"], eras: PREMODERN, wiki: ["Mbuti people", "Kola nut"], sources: ["vansinaPaths", "kelly"] },
    { cultures: ["east-southern-african"], eras: PREMODERN, wiki: ["San peoples", "Mongongo"], sources: ["leeKung", "iliffe"] },
    { cultures: ["mesoamerican"], eras: PREMODERN, wiki: ["Opuntia", "Agave"], sources: ["coe", "mann"] },
    { cultures: ["andean"], eras: PREMODERN, wiki: ["Totora (plant)", "Chuño"], sources: ["daltroy", "murra"] },
    { cultures: ["other-indigenous-american"], eras: PREMODERN, wiki: ["Acorn", "Wild rice", "Native American use of fire in ecosystems"], sources: ["anderson", "cronon"] },
    { cultures: ["australian-pacific"], eras: PREMODERN, wiki: ["Bush tucker", "Fire-stick farming", "Aboriginal Australians"], sources: ["gammage", "blainey"] },
    { wiki: ["Hunter-gatherer", "Non-timber forest product"], sources: ["kelly", "sahlins"] },
  ],
  techniques: {
    "gentle-hands": { wiki: "Traditional ecological knowledge", note: "Many gathering peoples harvested so the plant would bear again: leaving roots, taking a share, returning in season." },
    "quick-picker": { note: "Studies of living foragers measure gathering in return per hour, and skilled gatherers get far more from the same patch." },
    "second-helping": { wiki: "Optimal foraging theory", note: "Knowing where the rich patches are, and when, is most of what makes a forager good at it." },
    "keen-eye": { note: "Children learned hundreds of plants by sight from their elders; that botanical knowledge is often more detailed than a scientist's field guide." },
    seasoned: { wiki: "Food preservation", note: "Roots, nuts and dried fruit stored against the lean months carried foragers through the year." },
    "healers-lore": { wiki: "Herbal medicine", note: "Plant medicine was everywhere the first medicine, and many modern drugs began as remedies gathered wild." },
  },
};

export const farming: SkillContext = {
  entries: [
    { eras: DEEP, wiki: ["Ohalo II", "Neolithic Revolution"], sources: ["barker", "mithen"] },
    { eras: HOLOCENE, wiki: ["Neolithic Revolution", "Fertile Crescent", "Domestication"], sources: ["barker", "bellwood", "scott"] },
    { eras: EARLY, wiki: ["Irrigation", "Ard (plough)"], sources: ["scott", "vanDeMieroop"] },
    { eras: ANTIQUITY, wiki: ["Agriculture in ancient Rome", "Latifundium"], sources: ["scott", "white"] },
    { eras: MEDIEVAL, wiki: ["Agriculture in the Middle Ages", "Three-field system"], sources: ["duby", "wickham"] },
    { eras: EARLY_MODERN, wiki: ["Columbian exchange", "Crop rotation"], sources: ["crosby", "overton"] },
    { eras: INDUSTRIAL, wiki: ["British Agricultural Revolution", "Guano"], sources: ["overton", "beckert"] },
    { eras: MODERN, wiki: ["Green Revolution", "Mechanised agriculture", "Tractor"], sources: ["fitzgerald", "cullather", "mcneill"] },
    { cultures: ["north-african-west-asian"], eras: [...EARLY, ...ANTIQUITY], wiki: ["Agriculture in Mesopotamia", "Ancient Egyptian agriculture", "Irrigation"], sources: ["scott", "vanDeMieroop"] },
    { cultures: ["north-african-west-asian"], eras: [...MEDIEVAL, ...EARLY_MODERN, ...INDUSTRIAL], wiki: ["Arab Agricultural Revolution", "Qanat"], sources: ["watson", "bulliet"] },
    { cultures: ["european"], eras: ANTIQUITY, wiki: ["Agriculture in ancient Rome", "Latifundium"], sources: ["white", "duby"] },
    { cultures: ["european"], eras: MEDIEVAL, wiki: ["Agriculture in the Middle Ages", "Three-field system", "Open-field system"], sources: ["duby", "white"] },
    { cultures: ["european"], eras: [...EARLY_MODERN, ...INDUSTRIAL], wiki: ["British Agricultural Revolution", "Enclosure", "Crop rotation"], sources: ["overton", "thompson"] },
    { cultures: ["inner-eurasian"], eras: PREMODERN, wiki: ["Oasis", "Fergana Valley"], sources: ["beckwith", "perdue"] },
    { cultures: ["south-asian"], eras: PREMODERN, wiki: ["Agriculture in India", "Kharif crop", "Rabi crop"], sources: ["habib", "thapar", "gadgilGuha"] },
    { cultures: ["east-asian"], eras: PREMODERN, wiki: ["Paddy field", "History of rice cultivation", "Agriculture in China"], sources: ["bray", "elvin", "pomeranz"] },
    { cultures: ["southeast-asian"], eras: PREMODERN, wiki: ["Banaue Rice Terraces", "Shifting cultivation", "Paddy field"], sources: ["reid", "bellwoodIndo"] },
    { cultures: ["west-central-african"], eras: PREMODERN, wiki: ["Oryza glaberrima", "Yam (vegetable)", "Bantu expansion"], sources: ["carney", "ehret", "vansinaPaths"] },
    { cultures: ["east-southern-african"], eras: PREMODERN, wiki: ["Sorghum", "Finger millet", "Bantu expansion"], sources: ["ehret", "iliffe"] },
    { cultures: ["mesoamerican"], eras: PREMODERN, wiki: ["Agriculture in Mesoamerica", "Chinampa", "Milpa"], sources: ["coe", "mann"] },
    { cultures: ["andean"], eras: PREMODERN, wiki: ["Terrace (earthworks)", "Potato", "Chuño"], sources: ["murra", "daltroy"] },
    { cultures: ["other-indigenous-american"], eras: PREMODERN, wiki: ["Three Sisters (agriculture)", "Eastern Agricultural Complex"], sources: ["cronon", "mann"] },
    { cultures: ["australian-pacific"], eras: PREMODERN, wiki: ["Kuk Swamp", "Taro"], sources: ["kirch", "gammage"] },
    { wiki: ["History of agriculture", "Agriculture"], sources: ["bellwood", "scott"] },
  ],
  techniques: {
    "green-thumb": { note: "Experience let a farmer read soil and weather and work faster, knowledge usually learned by working beside parents and neighbours." },
    "good-seed": { wiki: "Seed saving", note: "Choosing the best seed for next year's sowing, year after year, is how every crop was domesticated." },
    "strong-back": { note: "Skeletons of early farmers show the toll of grinding and hoeing: worn joints and backs more than their foraging ancestors." },
    "weather-eye": { wiki: "Weather lore", note: "Farmers everywhere kept sayings and signs for rain and frost, some sound and some not." },
    "seed-saver": { wiki: "Landrace", note: "Seed kept on the farm made local varieties suited to one valley's soil and weather." },
    fallow: { wiki: "Fallow", note: "Resting land, or rotating what grows on it, restored fields before artificial fertiliser." },
  },
};

export const animals: SkillContext = {
  entries: [
    { eras: DEEP, wiki: ["Domestication of the dog", "Domestication of vertebrates"], sources: ["cluttonBrock"] },
    { eras: HOLOCENE, wiki: ["Domestication of vertebrates", "Pastoralism"], sources: ["cluttonBrock", "barker"] },
    { eras: EARLY, wiki: ["Domestication of the horse", "Secondary products revolution"], sources: ["anthony", "cluttonBrock"] },
    { eras: ANTIQUITY, wiki: ["Horses in warfare", "Chariot"], sources: ["kelekna", "anthony"] },
    { eras: MEDIEVAL, wiki: ["Transhumance", "Horse collar"], sources: ["kelekna", "white"] },
    { eras: EARLY_MODERN, wiki: ["Columbian exchange", "Livestock"], sources: ["crosby", "djAnderson"] },
    { eras: INDUSTRIAL, wiki: ["Cattle drives in the United States", "Selective breeding"], sources: ["crosby", "osterhammel"] },
    { eras: MODERN, wiki: ["Intensive animal farming", "Veterinary medicine"], sources: ["mcneill", "cluttonBrock"] },
    { cultures: ["european"], eras: PREMODERN, wiki: ["Transhumance", "Shepherd", "Animal husbandry"], sources: ["cluttonBrock", "rackhamCountryside"] },
    { cultures: ["north-african-west-asian"], eras: PREMODERN, wiki: ["Dromedary", "Bedouin", "Transhumance"], sources: ["bulliet", "cluttonBrock"] },
    { cultures: ["inner-eurasian"], eras: PREMODERN, wiki: ["Eurasian nomads", "Nomadic pastoralism", "Domestication of the horse"], sources: ["anthony", "barfield", "kelekna"] },
    { cultures: ["south-asian"], eras: PREMODERN, wiki: ["Zebu", "War elephant", "Cattle in religion and mythology"], sources: ["gadgilGuha", "thapar"] },
    { cultures: ["east-asian"], eras: PREMODERN, wiki: ["Water buffalo", "Domestic pig"], sources: ["elvin", "bray"] },
    { cultures: ["southeast-asian"], eras: PREMODERN, wiki: ["Water buffalo", "Asian elephant"], sources: ["reid", "bellwoodIndo"] },
    { cultures: ["west-central-african"], eras: PREMODERN, wiki: ["N'Dama", "Fulani herdsmen", "Tsetse fly"], sources: ["ehret", "iliffe"] },
    { cultures: ["east-southern-african"], eras: PREMODERN, wiki: ["Pastoralism", "Maasai people", "Cattle in religion and mythology"], sources: ["evansPritchard", "ehret"] },
    { cultures: ["mesoamerican"], eras: PREMODERN, wiki: ["Domestic turkey", "Xoloitzcuintle"], sources: ["coe", "cluttonBrock"] },
    { cultures: ["andean"], eras: PREMODERN, wiki: ["Llama", "Alpaca", "Camelidae"], sources: ["murra", "daltroy"] },
    { cultures: ["other-indigenous-american"], eras: [...HOLOCENE, ...EARLY, ...ANTIQUITY, ...MEDIEVAL], wiki: ["Travois", "Domestication of the dog"], sources: ["cluttonBrock"] },
    { cultures: ["other-indigenous-american"], eras: [...EARLY_MODERN, ...INDUSTRIAL], wiki: ["Plains Indians", "Columbian exchange"], sources: ["hamalainen", "djAnderson"] },
    { cultures: ["australian-pacific"], eras: PREMODERN, wiki: ["Dingo", "Domestic pig"], sources: ["kirch", "cluttonBrock"] },
    { wiki: ["Animal husbandry", "Domestication of vertebrates"], sources: ["cluttonBrock", "kelekna"] },
  ],
  techniques: {
    "calm-hand": { wiki: "Herding", note: "Good handlers move animals by reading their flight zone and moving slowly, knowledge that herders held long before it was studied." },
    "steady-nerve": { note: "Herding meant standing up to bulls, stallions and predators; injuries from livestock were a common way to be hurt." },
    drover: { wiki: "Droving", note: "Drovers walked cattle and sheep hundreds of miles to market along roads worn by their herds." },
    rider: { wiki: "Equestrianism", note: "Riding spread from the steppe and changed war, trade and herding wherever the horse went." },
    tamer: { wiki: "Tame animal", note: "Taming a single animal differs from domesticating a species, but many households kept tamed wild creatures." },
    "beast-speaker": { note: "Herding calls, whistles and songs directed animals across much of the world, and some are still in use." },
  },
};
