import { ANTIQUITY, DEEP, EARLY, EARLY_MODERN, HOLOCENE, INDUSTRIAL, MEDIEVAL, MODERN, PREMODERN, type SkillContext } from "./types";

export const speech: SkillContext = {
  entries: [
    { eras: DEEP, wiki: ["Origin of language", "Oral tradition"], sources: ["dunbar", "ong"] },
    { eras: HOLOCENE, wiki: ["Oral tradition", "Storytelling"], sources: ["ong", "vansinaOral"] },
    { eras: EARLY, wiki: ["History of writing", "Epic of Gilgamesh"], sources: ["goody", "vanDeMieroop"] },
    { eras: ANTIQUITY, wiki: ["Rhetoric", "Oral-formulaic composition"], sources: ["kennedy", "lord"] },
    { eras: MEDIEVAL, wiki: ["Bard", "Sermon", "Troubadour"], sources: ["ong", "lord"] },
    { eras: EARLY_MODERN, wiki: ["Printing press", "Ballad"], sources: ["burke", "anderson1983"] },
    { eras: INDUSTRIAL, wiki: ["Public speaking", "Literacy"], sources: ["anderson1983", "goody"] },
    { eras: MODERN, wiki: ["Mass media", "Radio"], sources: ["anderson1983", "ong"] },
    { cultures: ["european", "north-african-west-asian"], eras: [...EARLY, ...ANTIQUITY], wiki: ["Rhetoric", "Homeric Question", "Oral-formulaic composition"], sources: ["kennedy", "lord"] },
    { cultures: ["european"], eras: [...MEDIEVAL, ...EARLY_MODERN], wiki: ["Bard", "Ballad", "Sermon"], sources: ["burke", "ong"] },
    { cultures: ["north-african-west-asian"], eras: [...MEDIEVAL, ...EARLY_MODERN, ...INDUSTRIAL], wiki: ["Maqama", "One Thousand and One Nights"], sources: ["ong", "goody"] },
    { cultures: ["inner-eurasian"], eras: PREMODERN, wiki: ["Epic of Manas", "Akyn"], sources: ["lord", "beckwith"] },
    { cultures: ["south-asian"], eras: PREMODERN, wiki: ["Vedas", "Panchatantra", "Oral tradition"], sources: ["thapar", "ong"] },
    { cultures: ["east-asian"], eras: PREMODERN, wiki: ["Rakugo", "Pingshu"], sources: ["ong", "goody"] },
    { cultures: ["southeast-asian"], eras: PREMODERN, wiki: ["Wayang", "Pantun"], sources: ["reid", "ong"] },
    { cultures: ["west-central-african"], eras: PREMODERN, wiki: ["Griot", "Epic of Sundiata", "Oral tradition"], sources: ["hale", "finnegan", "vansinaOral"] },
    { cultures: ["east-southern-african"], eras: PREMODERN, wiki: ["Panegyric", "Oral tradition"], sources: ["finnegan", "vansinaOral"] },
    { cultures: ["mesoamerican"], eras: PREMODERN, wiki: ["Florentine Codex", "Popol Vuh"], sources: ["clendinnen", "coe"] },
    { cultures: ["andean"], eras: PREMODERN, wiki: ["Quipu", "Quechua languages"], sources: ["daltroy", "ong"] },
    { cultures: ["other-indigenous-american"], eras: PREMODERN, wiki: ["Wampum", "Winter count"], sources: ["whiteMiddle", "ong"] },
    { cultures: ["australian-pacific"], eras: PREMODERN, wiki: ["Songline", "The Dreaming"], sources: ["blainey", "thomas"] },
    { wiki: ["Oral tradition", "Storytelling", "Orality"], sources: ["ong", "goody"] },
  ],
  techniques: {
    "warm-word": { wiki: "Etiquette", note: "Greetings, gifts and asking after family open talk nearly everywhere, though the forms differ enormously." },
    "first-impression": { note: "Dress, bearing and a known name told strangers who you were before you spoke." },
    storyteller: { wiki: "Storytelling", note: "Tellers held whole epics in memory, recomposing them in each telling." },
    "silver-tongue": { wiki: "Rhetoric", note: "Rhetoric was taught as a craft, from Greek law courts to Chinese court memorials." },
    "good-ear": { wiki: "Multilingualism", note: "Most people in history lived among several languages and picked up what they needed to trade and marry." },
    elder: { wiki: "Elder (administrative title)", note: "Age, wisdom and a record of fair dealing earned a hearing in village councils." },
  },
};

export const trade: SkillContext = {
  entries: [
    { eras: DEEP, wiki: ["Gift economy", "Obsidian", "Barter"], sources: ["mauss", "sahlins"] },
    { eras: HOLOCENE, wiki: ["Obsidian", "Spondylus"], sources: ["mauss", "mithen"] },
    { eras: EARLY, wiki: ["Meluhha", "Tin sources and trade in ancient times"], sources: ["vanDeMieroop", "curtin"] },
    { eras: ANTIQUITY, wiki: ["Silk Road", "Incense trade route"], sources: ["hansen", "curtin"] },
    { eras: MEDIEVAL, wiki: ["Champagne fairs", "Hanseatic League", "Indian Ocean trade"], sources: ["abuLughod", "curtin"] },
    { eras: EARLY_MODERN, wiki: ["Dutch East India Company", "Atlantic slave trade"], sources: ["braudel", "curtin"] },
    { eras: INDUSTRIAL, wiki: ["Free trade", "Cotton"], sources: ["beckert", "polanyi"] },
    { eras: MODERN, wiki: ["Globalization", "Containerization"], sources: ["levinson", "polanyi"] },
    { cultures: ["european"], eras: [...MEDIEVAL, ...EARLY_MODERN], wiki: ["Champagne fairs", "Hanseatic League", "Peddler"], sources: ["braudel", "abuLughod"] },
    { cultures: ["north-african-west-asian"], eras: PREMODERN, wiki: ["Souk", "Caravanserai"], sources: ["bulliet", "abuLughod"] },
    { cultures: ["west-central-african", "north-african-west-asian"], eras: [...MEDIEVAL, ...EARLY_MODERN], wiki: ["Trans-Saharan trade", "Mali Empire", "Caravan (travellers)"], sources: ["curtin", "abuLughod"] },
    { cultures: ["west-central-african"], eras: PREMODERN, wiki: ["Cowrie", "Kola nut"], sources: ["curtin", "iliffe"] },
    { cultures: ["inner-eurasian"], eras: PREMODERN, wiki: ["Silk Road", "Sogdia", "Caravanserai"], sources: ["hansen", "beckwith"] },
    { cultures: ["east-asian"], eras: PREMODERN, wiki: ["Canton System", "Tea Horse Road"], sources: ["pomeranz", "perdue"] },
    { cultures: ["south-asian", "east-southern-african"], eras: PREMODERN, wiki: ["Indian Ocean trade", "Monsoon", "Swahili coast"], sources: ["chaudhuri", "curtin"] },
    { cultures: ["southeast-asian"], eras: PREMODERN, wiki: ["Malacca Sultanate", "Spice trade"], sources: ["reid", "chaudhuri"] },
    { cultures: ["mesoamerican"], eras: PREMODERN, wiki: ["Pochteca", "Tlatelolco (altepetl)", "Cocoa bean"], sources: ["hassigTrade", "clendinnen"] },
    { cultures: ["andean"], eras: PREMODERN, wiki: ["Vertical archipelago", "Quipu"], sources: ["murra", "daltroy"] },
    { cultures: ["other-indigenous-american"], eras: PREMODERN, wiki: ["Fur trade", "Wampum"], sources: ["whiteMiddle", "cronon"] },
    { cultures: ["australian-pacific"], eras: PREMODERN, wiki: ["Kula ring", "Gift economy"], sources: ["malinowski", "mauss", "thomas"] },
    { wiki: ["Trade", "Marketplace", "Barter"], sources: ["curtin", "braudel"] },
  ],
  techniques: {
    haggler: { wiki: "Bargaining", note: "Haggling was the ordinary way to set a price in most markets before fixed-price shops." },
    "fair-dealer": { wiki: "Reputation", note: "Merchants far from home depended on reputation and kin networks more than on courts." },
    packhorse: { wiki: "Packhorse", note: "Pack animals and porters carried most goods overland until railways." },
    appraiser: { note: "Weighing, testing coin and judging cloth were skills every trader needed, and fraud was a constant worry." },
    middleman: { wiki: "Arbitrage", note: "Buying where goods were cheap and selling where they were dear was the trader's whole business." },
    "known-face": { wiki: "Merchant", note: "Communities of merchants settled abroad, as brokers between their home and their hosts." },
  },
};
