export type Source = {
  author: string;
  title: string;
  year: number;
  /** One line on why it matters here. */
  note: string;
};

/** Secondary works the skill notes cite. Every entry is a real, published
 * work; notes flag the contested ones rather than leaving them out. */
export const SOURCES = {
  leeDevore: { author: "Richard B. Lee and Irven DeVore, eds.", title: "Man the Hunter", year: 1968, note: "The conference volume that made the study of living foragers a field." },
  leeKung: { author: "Richard B. Lee", title: "The !Kung San: Men, Women, and Work in a Foraging Society", year: 1979, note: "How much work foraging takes, measured over years in the Kalahari." },
  sahlins: { author: "Marshall Sahlins", title: "Stone Age Economics", year: 1972, note: "The 'original affluent society': foragers who met their needs by wanting little." },
  kelly: { author: "Robert L. Kelly", title: "The Lifeways of Hunter-Gatherers: The Foraging Spectrum", year: 2013, note: "The standard synthesis of how foragers hunt, gather, move and share." },
  mithen: { author: "Steven Mithen", title: "After the Ice: A Global Human History, 20,000–5000 BC", year: 2003, note: "A continent-by-continent walk through the end of the Ice Age." },
  barYosef: { author: "Ofer Bar-Yosef", title: "The Natufian Culture in the Levant, Threshold to the Origins of Agriculture", year: 1998, note: "Settled foragers of the Levant who harvested wild cereals before farming." },
  scott: { author: "James C. Scott", title: "Against the Grain: A Deep History of the Earliest States", year: 2017, note: "Why early farming and grain states were less of a bargain than they look." },
  barker: { author: "Graeme Barker", title: "The Agricultural Revolution in Prehistory: Why Did Foragers Become Farmers?", year: 2006, note: "The origins of farming region by region, and how gradual they were." },
  bellwood: { author: "Peter Bellwood", title: "First Farmers: The Origins of Agricultural Societies", year: 2005, note: "Where farming began, and how farmers and their languages spread." },
  gammage: { author: "Bill Gammage", title: "The Biggest Estate on Earth: How Aborigines Made Australia", year: 2011, note: "Fire and planned burning as land management across the continent." },
  anderson: { author: "M. Kat Anderson", title: "Tending the Wild: Native American Knowledge and the Management of California's Natural Resources", year: 2005, note: "Gathering as cultivation: pruning, burning and tending wild plants." },
  mann: { author: "Charles C. Mann", title: "1491: New Revelations of the Americas Before Columbus", year: 2005, note: "A popular synthesis of the managed landscapes of the pre-contact Americas." },
  rackhamCountryside: { author: "Oliver Rackham", title: "The History of the Countryside", year: 1986, note: "Hedges, woods, heaths and commons as records of how people used land." },
  rackhamTrees: { author: "Oliver Rackham", title: "Trees and Woodland in the British Landscape", year: 1976, note: "Coppice, pollard and timber: woodland as a managed crop." },
  thompson: { author: "E. P. Thompson", title: "Customs in Common", year: 1991, note: "Common rights to glean, graze and gather, and the fight to keep them." },
  duby: { author: "Georges Duby", title: "Rural Economy and Country Life in the Medieval West", year: 1968, note: "Fields, tools, lords and harvests across medieval Europe." },
  white: { author: "Lynn White Jr.", title: "Medieval Technology and Social Change", year: 1962, note: "The heavy plough and horse collar; influential and much argued with." },
  overton: { author: "Mark Overton", title: "Agricultural Revolution in England: The Transformation of the Agrarian Economy 1500–1850", year: 1996, note: "Yields, rotations and enclosure, measured rather than assumed." },
  bray: { author: "Francesca Bray", title: "Science and Civilisation in China, Vol. 6 Part 2: Agriculture", year: 1984, note: "Chinese farming technique, from rice paddies to ploughs." },
  pomeranz: { author: "Kenneth Pomeranz", title: "The Great Divergence: China, Europe, and the Making of the Modern World Economy", year: 2000, note: "Compares the farms and forests of the Yangzi delta and England around 1800." },
  habib: { author: "Irfan Habib", title: "The Agrarian System of Mughal India, 1556–1707", year: 1963, note: "Crops, peasants and revenue under the Mughals." },
  murra: { author: "John V. Murra", title: "The Economic Organization of the Inka State", year: 1980, note: "Herds, terraces and storehouses in the Andean economy." },
  carney: { author: "Judith A. Carney", title: "Black Rice: The African Origins of Rice Cultivation in the Americas", year: 2001, note: "West African rice knowledge and its passage across the Atlantic." },
  fitzgerald: { author: "Deborah Fitzgerald", title: "Every Farm a Factory: The Industrial Ideal in American Agriculture", year: 2003, note: "Tractors, accounting and the remaking of the farm in the 1920s." },
  cullather: { author: "Nick Cullather", title: "The Hungry World: America's Cold War Battle Against Poverty in Asia", year: 2010, note: "The Green Revolution's seeds, fertiliser and politics." },
  cluttonBrock: { author: "Juliet Clutton-Brock", title: "A Natural History of Domesticated Mammals", year: 1999, note: "How each herd animal came to live with people." },
  anthony: { author: "David W. Anthony", title: "The Horse, the Wheel, and Language", year: 2007, note: "Riding and herding on the Eurasian steppe, from the archaeology up." },
  kelekna: { author: "Pita Kelekna", title: "The Horse in Human History", year: 2009, note: "The horse's reach across Eurasia and the Americas." },
  djAnderson: { author: "Virginia DeJohn Anderson", title: "Creatures of Empire: How Domestic Animals Transformed Early America", year: 2004, note: "Colonists' free-ranging livestock and the conflicts they caused." },
  evansPritchard: { author: "E. E. Evans-Pritchard", title: "The Nuer", year: 1940, note: "Cattle as wealth, kinship and daily time among Nilotic herders." },
  crosby: { author: "Alfred W. Crosby", title: "Ecological Imperialism: The Biological Expansion of Europe, 900–1900", year: 1986, note: "How European animals, plants and germs remade other continents." },
  allsen: { author: "Thomas T. Allsen", title: "The Royal Hunt in Eurasian History", year: 2006, note: "Hunting as statecraft and training for war, from Persia to China." },
  cummins: { author: "John Cummins", title: "The Hound and the Hawk: The Art of Medieval Hunting", year: 1988, note: "The techniques and rituals of the medieval hunt." },
  almond: { author: "Richard Almond", title: "Medieval Hunting", year: 2003, note: "Who hunted in medieval England, peasants and poachers included." },
  krech: { author: "Shepard Krech III", title: "The Ecological Indian: Myth and History", year: 1999, note: "Native American hunting and the environment, against the stereotype; debated." },
  isenberg: { author: "Andrew C. Isenberg", title: "The Destruction of the Bison: An Environmental History, 1750–1920", year: 2000, note: "Horses, markets and drought on the Great Plains." },
  mackenzie: { author: "John M. MacKenzie", title: "The Empire of Nature: Hunting, Conservation and British Imperialism", year: 1988, note: "Hunting, game laws and colonial rule in Africa and India." },
  hardy: { author: "Robert Hardy", title: "Longbow: A Social and Military History", year: 1976, note: "The English longbow and the practice that made archers." },
  selby: { author: "Stephen Selby", title: "Chinese Archery", year: 2000, note: "Archery in Chinese texts, from ritual contests to war." },
  chase: { author: "Kenneth Chase", title: "Firearms: A Global History to 1700", year: 2003, note: "Why guns spread where they did, and bows held on elsewhere." },
  perrin: { author: "Noel Perrin", title: "Giving Up the Gun: Japan's Reversion to the Sword, 1543–1879", year: 1979, note: "A classic, and now much-questioned, account of Japan and the gun." },
  keeley: { author: "Lawrence H. Keeley", title: "War Before Civilization", year: 1996, note: "The archaeology of fighting among foragers and early farmers." },
  hanson: { author: "Victor Davis Hanson", title: "The Western Way of War: Infantry Battle in Classical Greece", year: 1989, note: "The hoplite's experience of battle." },
  anglo: { author: "Sydney Anglo", title: "The Martial Arts of Renaissance Europe", year: 2000, note: "Fencing manuals and how people learned to fight." },
  oakeshott: { author: "Ewart Oakeshott", title: "The Sword in the Age of Chivalry", year: 1964, note: "Medieval swords, typed and dated." },
  friday: { author: "Karl F. Friday", title: "Samurai, Warfare and the State in Early Medieval Japan", year: 2004, note: "How warriors actually fought, against the later legend." },
  thornton: { author: "John K. Thornton", title: "Warfare in Atlantic Africa, 1500–1800", year: 1999, note: "Armies, weapons and tactics of West and West-Central Africa." },
  hassigWar: { author: "Ross Hassig", title: "Aztec Warfare: Imperial Expansion and Political Control", year: 1988, note: "Training, weapons and campaigns in the Aztec empire." },
  perlin: { author: "John Perlin", title: "A Forest Journey: The Role of Wood in the Development of Civilization", year: 1989, note: "Wood as the fuel and timber of every early civilisation." },
  radkau: { author: "Joachim Radkau", title: "Wood: A History", year: 2012, note: "The age of wood before coal, and the fears of running out." },
  williams: { author: "Michael Williams", title: "Deforesting the Earth: From Prehistory to Global Crisis", year: 2003, note: "Clearing forests worldwide over ten thousand years." },
  menzies: { author: "Nicholas K. Menzies", title: "Forest and Land Management in Imperial China", year: 1994, note: "Plantations, temple woods and timber in late imperial China." },
  totman: { author: "Conrad Totman", title: "The Green Archipelago: Forestry in Preindustrial Japan", year: 1989, note: "How Tokugawa Japan came to plant and ration its forests." },
  whittaker: { author: "John C. Whittaker", title: "Flintknapping: Making and Understanding Stone Tools", year: 1994, note: "How stone tools were made, by a practising knapper." },
  stocks: { author: "Denys A. Stocks", title: "Experiments in Egyptian Archaeology: Stoneworking Technology in Ancient Egypt", year: 2003, note: "Copper saws, sand abrasive and the cutting of hard stone." },
  protzen: { author: "Jean-Pierre Protzen", title: "Inca Architecture and Construction at Ollantaytambo", year: 1993, note: "How Inca masons quarried, shaped and fitted stone." },
  parkerPearson: { author: "Mike Parker Pearson", title: "Stonehenge: Exploring the Greatest Stone Age Mystery", year: 2012, note: "Who moved the stones, and how, from recent excavation." },
  gimpel: { author: "Jean Gimpel", title: "The Cathedral Builders", year: 1961, note: "Masons, lodges and wages on medieval building sites." },
  ong: { author: "Walter J. Ong", title: "Orality and Literacy: The Technologizing of the Word", year: 1982, note: "How speaking cultures remember, argue and tell." },
  lord: { author: "Albert B. Lord", title: "The Singer of Tales", year: 1960, note: "How oral poets compose long songs as they perform." },
  goody: { author: "Jack Goody", title: "The Domestication of the Savage Mind", year: 1977, note: "What writing changes, and what it does not." },
  hale: { author: "Thomas A. Hale", title: "Griots and Griottes: Masters of Words and Music", year: 1998, note: "West Africa's hereditary keepers of speech, song and genealogy." },
  finnegan: { author: "Ruth Finnegan", title: "Oral Literature in Africa", year: 1970, note: "Praise poetry, riddles and tales across the continent." },
  dunbar: { author: "Robin Dunbar", title: "Grooming, Gossip, and the Evolution of Language", year: 1996, note: "A speculative case that talk began as social grooming." },
  burke: { author: "Peter Burke", title: "Popular Culture in Early Modern Europe", year: 1978, note: "Ballads, sermons, carnival and the talk of the street." },
  kennedy: { author: "George A. Kennedy", title: "The Art of Persuasion in Greece", year: 1963, note: "Greek rhetoric in the assembly and the courts." },
  curtin: { author: "Philip D. Curtin", title: "Cross-Cultural Trade in World History", year: 1984, note: "Trade diasporas: merchants living among strangers." },
  abuLughod: { author: "Janet L. Abu-Lughod", title: "Before European Hegemony: The World System A.D. 1250–1350", year: 1989, note: "The linked markets from Bruges to Hangzhou." },
  braudel: { author: "Fernand Braudel", title: "Civilization and Capitalism, 15th–18th Century, Vol. 2: The Wheels of Commerce", year: 1982, note: "Markets, fairs, pedlars and shops, from the ground up." },
  mauss: { author: "Marcel Mauss", title: "The Gift", year: 1925, note: "Gifts that oblige a return: exchange before and beside markets." },
  malinowski: { author: "Bronisław Malinowski", title: "Argonauts of the Western Pacific", year: 1922, note: "The kula ring's voyages of ceremonial exchange." },
  polanyi: { author: "Karl Polanyi", title: "The Great Transformation", year: 1944, note: "How markets came to rule over the societies they once served." },
  hansen: { author: "Valerie Hansen", title: "The Silk Road: A New History", year: 2012, note: "The Silk Road from excavated documents: mostly local trade." },
  chaudhuri: { author: "K. N. Chaudhuri", title: "Trade and Civilisation in the Indian Ocean", year: 1985, note: "Monsoon trade from the rise of Islam to 1750." },
  hassigTrade: { author: "Ross Hassig", title: "Trade, Tribute, and Transportation: The Sixteenth-Century Political Economy of the Valley of Mexico", year: 1985, note: "Markets, porters and the pochteca merchants." },
  lewis: { author: "David Lewis", title: "We, the Navigators: The Ancient Art of Landfinding in the Pacific", year: 1972, note: "Stars, swells and birds: navigating without instruments." },
  finney: { author: "Ben Finney", title: "Voyage of Rediscovery: A Cultural Odyssey through Polynesia", year: 1994, note: "Sailing a double canoe across the Pacific to test the old routes." },
  sumption: { author: "Jonathan Sumption", title: "Pilgrimage: An Image of Mediaeval Religion", year: 1975, note: "Why and how medieval Christians walked to shrines." },
  dunn: { author: "Ross E. Dunn", title: "The Adventures of Ibn Battuta", year: 1986, note: "A fourteenth-century traveller across the Muslim world." },
  hyslop: { author: "John Hyslop", title: "The Inka Road System", year: 1984, note: "The Andean road network, surveyed on foot." },
  chevallier: { author: "Raymond Chevallier", title: "Roman Roads", year: 1976, note: "How Roman roads were built and travelled." },
  solnit: { author: "Rebecca Solnit", title: "Wanderlust: A History of Walking", year: 2000, note: "Walking as pilgrimage, protest and thought." },
  reich: { author: "David Reich", title: "Who We Are and How We Got Here", year: 2018, note: "Ancient DNA and the great migrations of prehistory." },
  schivelbusch: { author: "Wolfgang Schivelbusch", title: "The Railway Journey", year: 1977, note: "How trains changed the experience of time and distance." },
  reid: { author: "Anthony Reid", title: "Southeast Asia in the Age of Commerce, 1450–1680", year: 1988, note: "Markets, ships, food and daily life across island and mainland Southeast Asia." },
  bellwoodIndo: { author: "Peter Bellwood", title: "Prehistory of the Indo-Malaysian Archipelago", year: 1985, note: "Foragers, farmers and seafarers of island Southeast Asia before history." },
  elvin: { author: "Mark Elvin", title: "The Retreat of the Elephants: An Environmental History of China", year: 2004, note: "Three thousand years of Chinese farming, forests and water." },
  gadgilGuha: { author: "Madhav Gadgil and Ramachandra Guha", title: "This Fissured Land: An Ecological History of India", year: 1992, note: "Foragers, herders, peasants and the forests of the subcontinent." },
  thapar: { author: "Romila Thapar", title: "Early India: From the Origins to AD 1300", year: 2002, note: "The standard history of early South Asia." },
  iliffe: { author: "John Iliffe", title: "Africans: The History of a Continent", year: 1995, note: "African history as the long story of peopling a difficult land." },
  ehret: { author: "Christopher Ehret", title: "The Civilizations of Africa: A History to 1800", year: 2002, note: "Farming, herding and states across Africa, much of it from language evidence." },
  vansinaPaths: { author: "Jan Vansina", title: "Paths in the Rainforests: Toward a History of Political Tradition in Equatorial Africa", year: 1990, note: "Village, house and district in the forests of Central Africa." },
  vansinaOral: { author: "Jan Vansina", title: "Oral Tradition as History", year: 1985, note: "How historians can read spoken tradition as evidence." },
  coe: { author: "Michael D. Coe", title: "Mexico: From the Olmecs to the Aztecs", year: 1962, note: "The long-standing survey of ancient Mesoamerica." },
  clendinnen: { author: "Inga Clendinnen", title: "Aztecs: An Interpretation", year: 1991, note: "Everyday life, ritual and war in Tenochtitlan." },
  daltroy: { author: "Terence N. D'Altroy", title: "The Incas", year: 2002, note: "The Inca state, its roads, storehouses and khipu records." },
  cronon: { author: "William Cronon", title: "Changes in the Land: Indians, Colonists, and the Ecology of New England", year: 1983, note: "How two ways of using land met in colonial New England." },
  whiteMiddle: { author: "Richard White", title: "The Middle Ground: Indians, Empires, and Republics in the Great Lakes Region, 1650–1815", year: 1991, note: "Trade, diplomacy and misunderstanding between Native peoples and Europeans." },
  hamalainen: { author: "Pekka Hämäläinen", title: "The Comanche Empire", year: 2008, note: "Horses, trade and raiding made the Comanche a power on the southern Plains." },
  thomas: { author: "Nicholas Thomas", title: "Islanders: The Pacific in the Age of Empire", year: 2010, note: "Pacific Islanders as voyagers, traders and makers of their own history." },
  kirch: { author: "Patrick V. Kirch", title: "On the Road of the Winds: An Archaeological History of the Pacific Islands before European Contact", year: 2000, note: "The settlement of the Pacific, island by island." },
  blainey: { author: "Geoffrey Blainey", title: "Triumph of the Nomads: A History of Ancient Australia", year: 1975, note: "An early popular history of Aboriginal Australia before 1788." },
  beckwith: { author: "Christopher I. Beckwith", title: "Empires of the Silk Road: A History of Central Eurasia from the Bronze Age to the Present", year: 2009, note: "Central Eurasia as a centre rather than a periphery; opinionated." },
  barfield: { author: "Thomas J. Barfield", title: "The Perilous Frontier: Nomadic Empires and China", year: 1989, note: "How steppe herders and Chinese states shaped each other." },
  diCosmo: { author: "Nicola Di Cosmo", title: "Ancient China and Its Enemies: The Rise of Nomadic Power in East Asian History", year: 2002, note: "The early northern frontier and the herders beyond it." },
  perdue: { author: "Peter C. Perdue", title: "China Marches West: The Qing Conquest of Central Eurasia", year: 2005, note: "Horses, grain and war on the Qing frontier." },
  bulliet: { author: "Richard W. Bulliet", title: "The Camel and the Wheel", year: 1975, note: "Why camels replaced wheeled carts across the Middle East." },
  watson: { author: "Andrew M. Watson", title: "Agricultural Innovation in the Early Islamic World", year: 1983, note: "New crops and irrigation carried across the Islamic world; argued over since." },
  vanDeMieroop: { author: "Marc Van De Mieroop", title: "A History of the Ancient Near East, ca. 3000–323 BC", year: 2004, note: "The standard survey of Mesopotamia and its neighbours." },
  wickham: { author: "Chris Wickham", title: "Framing the Early Middle Ages: Europe and the Mediterranean, 400–800", year: 2005, note: "Peasants, aristocrats and exchange after Rome." },
  mcneill: { author: "J. R. McNeill", title: "Something New Under the Sun: An Environmental History of the Twentieth-Century World", year: 2000, note: "How the twentieth century changed land, water and air." },
  bayly: { author: "C. A. Bayly", title: "The Birth of the Modern World, 1780–1914", year: 2004, note: "A global history of the long nineteenth century." },
  osterhammel: { author: "Jürgen Osterhammel", title: "The Transformation of the World: A Global History of the Nineteenth Century", year: 2014, note: "Mobility, cities, frontiers and work in the nineteenth century." },
  jacoby: { author: "Karl Jacoby", title: "Crimes Against Nature: Squatters, Poachers, Thieves, and the Hidden History of American Conservation", year: 2001, note: "What conservation laws meant for the people who used to hunt the land." },
  keeganFace: { author: "John Keegan", title: "The Face of Battle", year: 1976, note: "What combat was like for the soldier at Agincourt, Waterloo and the Somme." },
  keeganWar: { author: "John Keegan", title: "A History of Warfare", year: 1993, note: "A sweeping survey of war as culture." },
  anderson1983: { author: "Benedict Anderson", title: "Imagined Communities", year: 1983, note: "Print, language and the making of nations." },
  beckert: { author: "Sven Beckert", title: "Empire of Cotton: A Global History", year: 2014, note: "Cotton, slavery and the making of global capitalism." },
  levinson: { author: "Marc Levinson", title: "The Box: How the Shipping Container Made the World Smaller and the World Economy Bigger", year: 2006, note: "How the container remade trade after 1956." },
} satisfies Record<string, Source>;
export type SourceId = keyof typeof SOURCES;
