import type { Crop, CropId } from "./types";

/** Calendars are the drawn stage per season on a northern calendar. Where a
 * crop is sown at different times in different regions (barley, flax, wheat
 * under the monsoon) the calendar is the most common one; the parcel art does
 * not need the exception. */
export const crops: Record<CropId, Crop> = {
  wheat: {
    id: "wheat",
    label: "Wheat",
    kind: "grain",
    yields: "grain",
    height: "mid",
    climates: ["temperate", "mediterranean", "arid", "monsoon"],
    calendar: { autumn: "sown", winter: "green", spring: "green", summer: "ripe" },
    hue: "#d9b45a",
    evidence: {
      status: "documented",
      note: "Winter wheat is sown in autumn, overwinters as a low green mat and ripens in early summer; it was the bread grain of the Mediterranean, Europe and West Asia and the winter crop of north India and north China.",
      sources: ["https://www.fao.org/4/y4011e/y4011e04.htm"],
    },
  },
  barley: {
    id: "barley",
    label: "Barley",
    kind: "grain",
    yields: "grain",
    height: "mid",
    climates: ["temperate", "mediterranean", "arid", "boreal"],
    calendar: { autumn: "sown", winter: "green", spring: "green", summer: "ripe" },
    hue: "#cfb163",
    evidence: {
      status: "documented",
      note: "Barley tolerates salt, drought and cold better than wheat and was the staple grain of Mesopotamia and much of the ancient Near East; in the north it was sown in spring, in the south in autumn.",
      sources: ["https://en.wikipedia.org/wiki/Barley"],
    },
  },
  rye: {
    id: "rye",
    label: "Rye",
    kind: "grain",
    yields: "grain",
    height: "tall",
    climates: ["temperate", "boreal"],
    calendar: { autumn: "sown", winter: "green", spring: "green", summer: "ripe" },
    hue: "#c7a866",
    evidence: {
      status: "documented",
      note: "Rye stands taller than wheat, grows on poor sandy soil and cold winters, and was the bread grain of northern and eastern Europe from the early Middle Ages.",
      sources: ["https://en.wikipedia.org/wiki/Rye"],
    },
  },
  oats: {
    id: "oats",
    label: "Oats",
    kind: "grain",
    yields: "grain",
    height: "mid",
    climates: ["temperate", "boreal"],
    calendar: { spring: "sown", summer: "green", autumn: "ripe", winter: "stubble" },
    hue: "#d8c27a",
    evidence: {
      status: "documented",
      note: "Oats are a spring-sown crop of cool wet climates, the horse feed and porridge grain of northern Europe and the usual spring course in a three-course rotation.",
      sources: ["https://en.wikipedia.org/wiki/Oat"],
    },
  },
  millet: {
    id: "millet",
    label: "Millet",
    kind: "grain",
    yields: "grain",
    height: "mid",
    climates: ["temperate", "arid", "monsoon", "tropical"],
    calendar: { spring: "sown", summer: "green", autumn: "ripe", winter: "stubble" },
    hue: "#d6b04c",
    evidence: {
      status: "documented",
      note: "Foxtail and broomcorn millet were the first staples of the Yellow River valley, and pearl millet of the Sahel; all are quick summer crops sown with the rains and cut in autumn.",
      sources: ["https://en.wikipedia.org/wiki/Millet"],
    },
  },
  sorghum: {
    id: "sorghum",
    label: "Sorghum",
    kind: "grain",
    yields: "grain",
    height: "tall",
    climates: ["arid", "tropical", "monsoon"],
    calendar: { spring: "sown", summer: "green", autumn: "ripe", winter: "stubble" },
    hue: "#b5713a",
    evidence: {
      status: "documented",
      note: "Sorghum, domesticated in the Sudanic belt, stands over head height and carries a reddish seed head; it is the dry-season grain of the African savanna and of Deccan India.",
      sources: ["https://www.fao.org/4/t0818e/T0818E04.htm"],
    },
  },
  teff: {
    id: "teff",
    label: "Teff",
    kind: "grain",
    yields: "grain",
    height: "low",
    climates: ["tropical", "monsoon", "arid"],
    calendar: { spring: "bare", summer: "sown", autumn: "green", winter: "ripe" },
    hue: "#c9a25e",
    evidence: {
      status: "documented",
      note: "Teff is a fine-stemmed grass of the Ethiopian highlands, sown with the summer rains and harvested in November and December.",
      sources: ["https://en.wikipedia.org/wiki/Eragrostis_tef"],
    },
  },
  rice: {
    id: "rice",
    label: "Wet rice",
    kind: "grain",
    yields: "grain",
    height: "mid",
    wet: true,
    climates: ["monsoon", "tropical", "temperate"],
    calendar: { spring: "sown", summer: "green", autumn: "ripe", winter: "bare" },
    hue: "#d9c05a",
    evidence: {
      status: "documented",
      note: "Paddy rice is transplanted into flooded bunded basins in late spring, stands green through summer and is drained and cut in autumn; the basin lies bare or in a winter crop until the next flood.",
      sources: ["https://www.fao.org/4/y4751e/y4751e04.htm"],
    },
  },
  "dry-rice": {
    id: "dry-rice",
    label: "Upland rice",
    kind: "grain",
    yields: "grain",
    height: "mid",
    climates: ["tropical", "monsoon"],
    calendar: { spring: "sown", summer: "green", autumn: "ripe", winter: "bare" },
    hue: "#d1b95c",
    evidence: {
      status: "documented",
      note: "Upland or dry rice is broadcast on rain-fed hill clearings without bunds or flooding, mostly in swidden systems of Southeast Asia and West Africa.",
      sources: ["https://en.wikipedia.org/wiki/Upland_rice"],
    },
  },
  maize: {
    id: "maize",
    label: "Maize",
    kind: "grain",
    yields: "grain",
    height: "tall",
    climates: ["temperate", "mediterranean", "tropical", "monsoon", "arid"],
    calendar: { spring: "sown", summer: "green", autumn: "ripe", winter: "stubble" },
    hue: "#e0b640",
    evidence: {
      status: "documented",
      note: "Maize was domesticated in southern Mexico and spread through the Americas before 1500 and across the Old World after; it stands over a person by late summer and dries to a pale gold in autumn.",
      sources: ["https://en.wikipedia.org/wiki/Maize"],
    },
  },
  beans: {
    id: "beans",
    label: "Beans",
    kind: "vegetable",
    height: "low",
    climates: ["temperate", "mediterranean", "tropical", "monsoon", "arid"],
    calendar: { spring: "sown", summer: "green", autumn: "ripe", winter: "bare" },
    hue: "#7f9a4a",
    evidence: {
      status: "documented",
      note: "Common beans were grown up maize stalks in the Mesoamerican milpa; broad beans and pulses filled the same fixing role in Old World rotations.",
      sources: ["https://en.wikipedia.org/wiki/Three_Sisters_(agriculture)"],
    },
  },
  squash: {
    id: "squash",
    label: "Squash",
    kind: "vegetable",
    height: "low",
    climates: ["temperate", "mediterranean", "tropical", "monsoon", "arid"],
    calendar: { spring: "sown", summer: "green", autumn: "ripe", winter: "bare" },
    hue: "#d98a2e",
    evidence: {
      status: "documented",
      note: "Squash sprawls as a ground cover between maize hills, the third of the three sisters, and ripens in autumn.",
      sources: ["https://en.wikipedia.org/wiki/Three_Sisters_(agriculture)"],
    },
  },
  potato: {
    id: "potato",
    label: "Potato",
    kind: "root",
    height: "low",
    climates: ["temperate", "boreal", "tropical"],
    calendar: { spring: "sown", summer: "green", autumn: "ripe", winter: "bare" },
    hue: "#8fa04e",
    evidence: {
      status: "documented",
      note: "The potato was domesticated in the high Andes and grown on terraces there; in Europe it became a field crop only in the eighteenth century.",
      sources: ["https://www.fao.org/potato-2008/en/potato/origins.html"],
    },
  },
  quinoa: {
    id: "quinoa",
    label: "Quinoa",
    kind: "grain",
    yields: "grain",
    height: "mid",
    climates: ["tropical", "arid", "temperate"],
    calendar: { spring: "sown", summer: "green", autumn: "ripe", winter: "bare" },
    hue: "#c66a5a",
    evidence: {
      status: "documented",
      note: "Quinoa is an Andean altiplano crop with red and yellow seed heads, grown above the limit for maize.",
      sources: ["https://www.fao.org/quinoa-2013/what-is-quinoa/en/"],
    },
  },
  yam: {
    id: "yam",
    label: "Yam",
    kind: "root",
    height: "mid",
    climates: ["tropical", "monsoon"],
    calendar: { spring: "sown", summer: "green", autumn: "ripe", winter: "bare" },
    hue: "#9fae4c",
    evidence: {
      status: "documented",
      note: "West African yams are planted in mounds at the start of the rains, their vines staked, and dug in the dry season; the yam belt runs from Côte d'Ivoire to Cameroon.",
      sources: ["https://en.wikipedia.org/wiki/Yam_(vegetable)"],
    },
  },
  cassava: {
    id: "cassava",
    label: "Cassava",
    kind: "root",
    height: "mid",
    climates: ["tropical", "monsoon"],
    calendar: { spring: "sown", summer: "green", autumn: "green", winter: "ripe" },
    hue: "#7c9648",
    evidence: {
      status: "documented",
      note: "Cassava, an Amazonian domesticate, reached West Africa with the Portuguese in the sixteenth century; it is a shrub left in the ground nine to eighteen months and dug as needed.",
      sources: ["https://www.fao.org/4/x5032e/x5032E02.htm"],
    },
  },
  taro: {
    id: "taro",
    label: "Taro",
    kind: "root",
    height: "low",
    wet: true,
    climates: ["tropical", "monsoon"],
    calendar: { spring: "sown", summer: "green", autumn: "ripe", winter: "bare" },
    hue: "#5f8f4a",
    evidence: {
      status: "documented",
      note: "Taro is grown in flooded pondfields in Southeast Asia and the Pacific, with broad leaves over a bunded basin much like a rice paddy.",
      sources: ["https://en.wikipedia.org/wiki/Taro"],
    },
  },
  sugarcane: {
    id: "sugarcane",
    label: "Sugarcane",
    kind: "grain",
    height: "tall",
    climates: ["tropical", "monsoon", "arid"],
    calendar: { spring: "sown", summer: "green", autumn: "green", winter: "ripe" },
    hue: "#8fa85a",
    evidence: {
      status: "documented",
      note: "Cane is a giant grass planted from cuttings and cut in the dry season a year or more later; it was grown in India and the Islamic Mediterranean, then on plantations in the Atlantic world.",
      sources: ["https://en.wikipedia.org/wiki/Sugarcane"],
    },
  },
  olive: {
    id: "olive",
    label: "Olive",
    kind: "tree",
    yields: "fruit",
    height: "tall",
    climates: ["mediterranean", "arid"],
    calendar: { spring: "green", summer: "green", autumn: "ripe", winter: "green" },
    hue: "#6f7d3f",
    evidence: {
      status: "documented",
      note: "Olives are an evergreen orchard tree of the Mediterranean, harvested from October into winter; groves are widely spaced on terraced or stony ground.",
      sources: ["https://en.wikipedia.org/wiki/Olive"],
    },
  },
  vine: {
    id: "vine",
    label: "Vine",
    kind: "vine",
    yields: "fruit",
    height: "low",
    climates: ["mediterranean", "temperate"],
    calendar: { spring: "green", summer: "green", autumn: "ripe", winter: "bare" },
    hue: "#6b4c7a",
    evidence: {
      status: "documented",
      note: "Vineyards are pruned to bare stumps in winter, leaf out in spring and are picked in September and October.",
      sources: ["https://en.wikipedia.org/wiki/Viticulture"],
    },
  },
  date: {
    id: "date",
    label: "Date palm",
    kind: "tree",
    yields: "fruit",
    height: "tall",
    climates: ["arid"],
    calendar: { spring: "green", summer: "green", autumn: "ripe", winter: "green" },
    hue: "#b8823c",
    evidence: {
      status: "documented",
      note: "Date palms line the canals and oases of Mesopotamia, Arabia and the Sahara, with vegetables and grain grown in their shade; fruit ripens in late summer and autumn.",
      sources: ["https://en.wikipedia.org/wiki/Date_palm"],
    },
  },
  orchard: {
    id: "orchard",
    label: "Orchard",
    kind: "tree",
    yields: "fruit",
    height: "tall",
    climates: ["temperate", "mediterranean", "monsoon", "boreal"],
    calendar: { spring: "green", summer: "green", autumn: "ripe", winter: "bare" },
    hue: "#c25b4a",
    evidence: {
      status: "inferred",
      note: "A generic deciduous fruit orchard of apples, pears, plums or citrus by climate, planted near the settlement and picked in autumn.",
      sources: ["https://en.wikipedia.org/wiki/Orchard"],
    },
  },
  flax: {
    id: "flax",
    label: "Flax",
    kind: "fibre",
    yields: "flax",
    height: "mid",
    climates: ["temperate", "boreal", "mediterranean", "arid"],
    calendar: { spring: "sown", summer: "ripe", autumn: "stubble", winter: "bare" },
    hue: "#8fa3c9",
    evidence: {
      status: "documented",
      note: "Flax is a quick hundred-day crop pulled in midsummer for linen fibre; in Egypt it was a winter crop sown on the falling flood.",
      sources: ["https://en.wikipedia.org/wiki/Flax"],
    },
  },
  cotton: {
    id: "cotton",
    label: "Cotton",
    kind: "fibre",
    height: "mid",
    climates: ["arid", "monsoon", "tropical", "mediterranean"],
    calendar: { spring: "sown", summer: "green", autumn: "ripe", winter: "stubble" },
    hue: "#e8e2d2",
    evidence: {
      status: "documented",
      note: "Cotton was grown in the Indus valley by the third millennium BC and became an irrigated summer cash crop of Egypt and the Deccan; bolls open white in autumn.",
      sources: ["https://en.wikipedia.org/wiki/History_of_cotton"],
    },
  },
  vegetables: {
    id: "vegetables",
    label: "Vegetable garden",
    kind: "vegetable",
    height: "low",
    climates: ["temperate", "mediterranean", "tropical", "monsoon", "arid", "boreal"],
    calendar: { spring: "sown", summer: "green", autumn: "ripe", winter: "bare" },
    hue: "#6f9a48",
    evidence: {
      status: "inferred",
      note: "Mixed garden plots of greens, onions, pulses and gourds beside the houses, whatever the region; the species vary and the look does not.",
      sources: ["https://en.wikipedia.org/wiki/Kitchen_garden"],
    },
  },
  pasture: {
    id: "pasture",
    label: "Pasture",
    kind: "pasture",
    yields: "fodder",
    height: "low",
    climates: ["temperate", "mediterranean", "tropical", "monsoon", "arid", "boreal", "tundra"],
    calendar: { spring: "green", summer: "ripe", autumn: "green", winter: "bare" },
    hue: "#8fb04f",
    evidence: {
      status: "documented",
      note: "Grazing land and hay meadow, cut once in summer and grazed after; the largest land use of most farming systems by area.",
      sources: ["https://en.wikipedia.org/wiki/Pasture"],
    },
  },
  fallow: {
    id: "fallow",
    label: "Fallow",
    kind: "fallow",
    height: "low",
    climates: ["temperate", "mediterranean", "tropical", "monsoon", "arid", "boreal", "tundra"],
    calendar: { spring: "bare", summer: "bare", autumn: "bare", winter: "bare" },
    hue: "#a08c66",
    evidence: {
      status: "documented",
      note: "A parcel rested for a season or years, ploughed to kill weeds and grazed by the village stock; in swidden systems it returns to bush for a decade or more.",
      sources: ["https://en.wikipedia.org/wiki/Crop_rotation"],
    },
  },
};
