import type { CultureId } from "../history/types";
import type { FarmSystem, FarmSystemRule } from "./types";

/** The atlas keys the Americas to their indigenous families whatever the
 * date, as in urban-form/modern.ts, so a modern system is listed under every
 * family whose region it covers. */
const americas: CultureId[] = [
  "other-indigenous-american",
  "mesoamerican",
  "andean",
];

const mediterraneanCultures: CultureId[] = [
  "european",
  "north-african-west-asian",
];

const mediterraneanTerraces = mediterraneanCultures.map(
  (culture): FarmSystemRule => ({
    id: "mediterranean-terrace-and-wheat",
    label: "Olive and vine terraces over wheat land",
    culture,
    from: -800,
    to: 1950,
    bounds: [-10, 30, 40, 45],
    climates: ["mediterranean", "arid"],
    geometry: "terrace",
    module: [20, 5],
    regularity: 0.35,
    boundary: "wall",
    irrigation: "none",
    crops: [
      { id: "wheat", share: 0.3 },
      { id: "barley", share: 0.1 },
      { id: "olive", share: 0.2 },
      { id: "vine", share: 0.15 },
      { id: "fallow", share: 0.15 },
      { id: "pasture", share: 0.1 },
    ],
    orchard: 0.3,
    slopeLimit: 5,
    riverside: 0.2,
    reach: 2,
    commons: true,
    outbuildings: ["press", "threshing-floor", "well", "shrine"],
    evidence: {
      status: "documented",
      note: "The Mediterranean triad of wheat, olive and vine, with dry-stone terraces on the slopes and biennial fallow on the plain, is described from classical Greece to the twentieth century.",
      sources: [
        "https://en.wikipedia.org/wiki/Agriculture_in_ancient_Greece",
        "https://en.wikipedia.org/wiki/Terrace_(earthworks)",
      ],
    },
  }),
);

const mechanised = [...americas, "european", "east-asian"].map((culture) => {
  const bounds: FarmSystemRule["bounds"] =
    culture === "european"
      ? [-12, 35, 40, 64]
      : culture === "east-asian"
        ? [100, 18, 146, 46]
        : [-125, -56, -34, 56];
  const rule: FarmSystemRule = {
    id: "modern-mechanised-plantation",
    label: "Large machine-worked fields",
    culture: culture as CultureId,
    from: 1950,
    to: 2026,
    bounds,
    geometry: "plantation",
    module: [36, 24],
    regularity: 0.9,
    boundary: "none",
    irrigation: "none",
    crops: [
      { id: "wheat", share: 0.35 },
      { id: "maize", share: 0.3 },
      { id: "rice", share: 0.1 },
      { id: "pasture", share: 0.25 },
    ],
    orchard: 0.25,
    slopeLimit: 2,
    riverside: 0,
    reach: 2.2,
    commons: false,
    outbuildings: ["barn", "granary"],
    evidence: {
      status: "documented",
      note: "Post-war consolidation removed hedges and bunds to fit tractors and combines, leaving a few grain crops in large unbounded fields with market gardens and orchards held near the towns.",
      sources: ["https://en.wikipedia.org/wiki/Mechanised_agriculture"],
    },
  };
  return rule;
});

export const farmSystems: FarmSystemRule[] = [
  {
    id: "medieval-open-field-strips",
    label: "Open-field strips in three courses",
    culture: "european",
    from: 800,
    to: 1750,
    bounds: [-10, 42, 32, 62],
    geometry: "strip",
    module: [4, 24],
    regularity: 0.5,
    boundary: "baulk",
    irrigation: "none",
    crops: [
      { id: "wheat", share: 0.22 },
      { id: "rye", share: 0.1 },
      { id: "barley", share: 0.12 },
      { id: "oats", share: 0.14 },
      { id: "fallow", share: 0.3 },
      { id: "pasture", share: 0.12 },
    ],
    orchard: 0.15,
    slopeLimit: 2,
    riverside: 0.3,
    reach: 2.2,
    commons: true,
    outbuildings: ["barn", "mill", "dovecote", "hayrick"],
    evidence: {
      status: "documented",
      note: "Villages across the English Midlands and the north European plain held their arable as unfenced strips in two or three great fields, one lying fallow each year, with meadow and common waste beyond.",
      sources: ["https://en.wikipedia.org/wiki/Open-field_system"],
    },
  },
  {
    id: "enclosed-hedged-fields",
    label: "Enclosed hedged fields",
    culture: "european",
    from: 1700,
    to: 1950,
    bounds: [-11, 43, 16, 62],
    geometry: "block",
    module: [16, 12],
    regularity: 0.6,
    boundary: "hedge",
    irrigation: "none",
    crops: [
      { id: "wheat", share: 0.2 },
      { id: "barley", share: 0.12 },
      { id: "oats", share: 0.1 },
      { id: "potato", share: 0.08 },
      { id: "pasture", share: 0.5 },
    ],
    orchard: 0.2,
    slopeLimit: 3,
    riverside: 0.2,
    reach: 2,
    commons: false,
    outbuildings: ["barn", "hayrick", "mill"],
    evidence: {
      status: "documented",
      note: "Parliamentary and private enclosure in Britain, and similar consolidation in the Low Countries and Denmark, replaced strips with hedged rectangular fields and put much of the land under grass in rotation with turnips and clover.",
      sources: ["https://en.wikipedia.org/wiki/Enclosure"],
    },
  },
  ...mediterraneanTerraces,
  {
    id: "nile-flood-basins",
    label: "Nile flood basins",
    culture: "north-african-west-asian",
    from: -3000,
    to: 1900,
    bounds: [29, 22, 35, 32],
    geometry: "basin",
    module: [8, 8],
    regularity: 0.4,
    boundary: "ditch",
    irrigation: "flood",
    crops: [
      { id: "wheat", share: 0.35 },
      { id: "barley", share: 0.25 },
      { id: "flax", share: 0.15 },
      { id: "cotton", share: 0.05 },
      { id: "vegetables", share: 0.1 },
      { id: "pasture", share: 0.1 },
    ],
    orchard: 0.2,
    slopeLimit: 1,
    riverside: 0.9,
    reach: 2.4,
    commons: false,
    outbuildings: ["granary", "threshing-floor", "shrine", "well"],
    evidence: {
      status: "documented",
      note: "The floodplain was divided by earth dykes into basins that filled with the August inundation and were sown as it drained; wheat, barley and flax were the ancient crops, with cotton added under Muhammad Ali. Perennial irrigation ended the basins after the Aswan Low Dam.",
      sources: [
        "https://en.wikipedia.org/wiki/Ancient_Egyptian_agriculture",
        "https://en.wikipedia.org/wiki/Irrigation_in_Egypt",
      ],
    },
  },
  {
    id: "mesopotamian-canal-strips",
    label: "Canal-fed strips and date groves",
    culture: "north-african-west-asian",
    from: -3500,
    to: 1500,
    bounds: [38, 29, 50, 37],
    climates: ["arid", "mediterranean"],
    geometry: "ribbon",
    module: [4, 24],
    regularity: 0.45,
    boundary: "ditch",
    irrigation: "canal",
    crops: [
      { id: "barley", share: 0.4 },
      { id: "wheat", share: 0.1 },
      { id: "date", share: 0.15 },
      { id: "vegetables", share: 0.05 },
      { id: "fallow", share: 0.3 },
    ],
    orchard: 0.25,
    slopeLimit: 1,
    riverside: 0.8,
    reach: 2.2,
    commons: false,
    outbuildings: ["granary", "threshing-floor", "shrine"],
    evidence: {
      status: "documented",
      note: "Sumerian and later fields were long narrow plots running back from a feeder canal, sown mostly with salt-tolerant barley and rested in alternate years, with date palms along the watercourses.",
      sources: [
        "https://en.wikipedia.org/wiki/Agriculture_in_Mesopotamia",
        "https://www.fao.org/4/w6537e/w6537e05.htm",
      ],
    },
  },
  {
    id: "east-asian-wet-rice-basins",
    label: "Bunded rice paddies",
    culture: "east-asian",
    from: -1000,
    to: 1950,
    bounds: [100, 18, 146, 34],
    geometry: "basin",
    module: [8, 8],
    regularity: 0.4,
    boundary: "bund",
    irrigation: "river",
    crops: [
      { id: "rice", share: 0.7 },
      { id: "wheat", share: 0.1 },
      { id: "vegetables", share: 0.1 },
      { id: "orchard", share: 0.1 },
    ],
    orchard: 0.3,
    slopeLimit: 2,
    riverside: 0.7,
    reach: 2,
    commons: false,
    outbuildings: ["granary", "shrine", "threshing-floor", "well"],
    evidence: {
      status: "documented",
      note: "Rice paddies of the Yangtze basin, south China, Korea and Japan are small level basins behind earth bunds, fed from streams and ponds, with a winter crop of wheat or rape on drained fields in the later period.",
      sources: ["https://en.wikipedia.org/wiki/Paddy_field"],
    },
  },
  {
    id: "north-china-millet-wheat-blocks",
    label: "Dry-farmed millet and wheat blocks",
    culture: "east-asian",
    from: -1500,
    to: 1950,
    bounds: [100, 34, 130, 46],
    geometry: "block",
    module: [16, 12],
    regularity: 0.55,
    boundary: "none",
    irrigation: "well",
    crops: [
      { id: "millet", share: 0.35 },
      { id: "wheat", share: 0.3 },
      { id: "sorghum", share: 0.1 },
      { id: "vegetables", share: 0.1 },
      { id: "fallow", share: 0.15 },
    ],
    orchard: 0.15,
    slopeLimit: 2,
    riverside: 0.4,
    reach: 2.2,
    commons: false,
    outbuildings: ["granary", "threshing-floor", "well", "shrine"],
    evidence: {
      status: "documented",
      note: "The loess and North China Plain grew millet, then wheat and sorghum, on rain-fed and well-watered unfenced plots; rice was marginal north of the Huai.",
      sources: ["https://en.wikipedia.org/wiki/Agriculture_in_China"],
    },
  },
  {
    id: "south-asian-paddy-and-millet",
    label: "Monsoon paddy with millet and cotton",
    culture: "south-asian",
    from: -1500,
    to: 1950,
    bounds: [60, 5, 95, 36],
    geometry: "basin",
    module: [8, 8],
    regularity: 0.35,
    boundary: "bund",
    irrigation: "well",
    crops: [
      { id: "rice", share: 0.35 },
      { id: "millet", share: 0.2 },
      { id: "wheat", share: 0.15 },
      { id: "cotton", share: 0.1 },
      { id: "sugarcane", share: 0.05 },
      { id: "fallow", share: 0.15 },
    ],
    orchard: 0.2,
    slopeLimit: 2,
    riverside: 0.5,
    reach: 2.2,
    commons: true,
    outbuildings: ["well", "granary", "shrine", "threshing-floor"],
    evidence: {
      status: "documented",
      note: "A summer kharif crop of rice, millets and cotton sown with the monsoon and a winter rabi crop of wheat and pulses, on bunded fields fed by tanks and wells, is the pattern from the Vedic period to the twentieth century.",
      sources: ["https://en.wikipedia.org/wiki/History_of_agriculture_in_the_Indian_subcontinent"],
    },
  },
  {
    id: "southeast-asian-paddy-basins",
    label: "Paddy basins and hill swiddens",
    culture: "southeast-asian",
    from: -1000,
    to: 1950,
    bounds: [92, -12, 142, 28],
    geometry: "basin",
    module: [8, 8],
    regularity: 0.35,
    boundary: "bund",
    irrigation: "river",
    crops: [
      { id: "rice", share: 0.55 },
      { id: "dry-rice", share: 0.15 },
      { id: "taro", share: 0.05 },
      { id: "vegetables", share: 0.1 },
      { id: "orchard", share: 0.15 },
    ],
    orchard: 0.35,
    slopeLimit: 4,
    riverside: 0.7,
    reach: 2,
    commons: true,
    outbuildings: ["granary", "shrine", "well"],
    evidence: {
      status: "documented",
      note: "Lowland deltas and valley floors carry bunded wet rice while hill villages burn swiddens for dry rice; fruit trees and gardens crowd the settlement edge.",
      sources: ["https://en.wikipedia.org/wiki/Rice_production_in_Southeast_Asia"],
    },
  },
  {
    id: "mesoamerican-milpa-clearings",
    label: "Milpa clearings",
    culture: "mesoamerican",
    from: -1500,
    to: 1900,
    bounds: [-110, 5, -80, 26],
    geometry: "clearing",
    module: [10, 9],
    regularity: 0.15,
    boundary: "none",
    irrigation: "none",
    crops: [
      { id: "maize", share: 0.4 },
      { id: "beans", share: 0.1 },
      { id: "squash", share: 0.1 },
      { id: "fallow", share: 0.4 },
    ],
    orchard: 0.15,
    slopeLimit: 4,
    riverside: 0.2,
    reach: 2.2,
    commons: true,
    outbuildings: ["granary", "shrine"],
    evidence: {
      status: "documented",
      note: "A milpa is a slashed and burned clearing planted with maize, beans and squash together for two or three years, then left to bush for several more, so most of the farmed land at any time is fallow.",
      sources: ["https://en.wikipedia.org/wiki/Milpa"],
    },
  },
  {
    id: "andean-terraces",
    label: "Andean terraces",
    culture: "andean",
    from: -1000,
    to: 1900,
    bounds: [-82, -35, -60, 12],
    geometry: "terrace",
    module: [20, 5],
    regularity: 0.5,
    boundary: "wall",
    irrigation: "canal",
    crops: [
      { id: "potato", share: 0.35 },
      { id: "quinoa", share: 0.15 },
      { id: "maize", share: 0.25 },
      { id: "fallow", share: 0.15 },
      { id: "pasture", share: 0.1 },
    ],
    orchard: 0.1,
    slopeLimit: 6,
    riverside: 0.3,
    reach: 2,
    commons: true,
    outbuildings: ["granary", "shrine"],
    evidence: {
      status: "documented",
      note: "Stone-walled terraces (andenes) on valley sides carried maize on the lower irrigated benches and potatoes and quinoa above, with long fallow cycles and llama pasture on the puna.",
      sources: ["https://en.wikipedia.org/wiki/Inca_agriculture"],
    },
  },
  {
    id: "west-african-bush-fallow",
    label: "Bush-fallow clearings",
    culture: "west-central-african",
    from: -500,
    to: 1950,
    bounds: [-18, -15, 32, 18],
    geometry: "clearing",
    module: [10, 9],
    regularity: 0.1,
    boundary: "none",
    irrigation: "none",
    crops: [
      { id: "yam", share: 0.2 },
      { id: "millet", share: 0.15 },
      { id: "sorghum", share: 0.15 },
      { id: "cassava", share: 0.1 },
      { id: "fallow", share: 0.4 },
    ],
    orchard: 0.15,
    slopeLimit: 3,
    riverside: 0.3,
    reach: 2.2,
    commons: true,
    outbuildings: ["granary", "shrine"],
    evidence: {
      status: "documented",
      note: "Savanna villages grew millet and sorghum, forest villages yams, in hoe-cleared plots cropped for a few years and rested under bush for many; cassava spread through the belt after the sixteenth century.",
      sources: [
        "https://en.wikipedia.org/wiki/Shifting_cultivation",
        "https://en.wikipedia.org/wiki/Agriculture_in_Nigeria",
      ],
    },
  },
  {
    id: "inner-eurasian-pastoral",
    label: "Open steppe pasture",
    culture: "inner-eurasian",
    from: -800,
    to: 1900,
    bounds: [20, 35, 130, 60],
    geometry: "block",
    module: [40, 40],
    regularity: 0,
    boundary: "none",
    irrigation: "none",
    crops: [{ id: "pasture", share: 1 }],
    orchard: 0,
    slopeLimit: 4,
    riverside: 0.4,
    reach: 3,
    commons: true,
    outbuildings: [],
    evidence: {
      status: "documented",
      note: "Steppe nomads from the Scythians to the Kazakhs held no fields, moving herds between seasonal pastures along the rivers; there is nothing to fence and the grazing reaches to the horizon.",
      sources: ["https://en.wikipedia.org/wiki/Eurasian_nomads"],
    },
  },
  {
    id: "north-american-section-grid",
    label: "Surveyed section grid",
    culture: "other-indigenous-american",
    from: 1850,
    to: 2026,
    bounds: [-125, 25, -60, 55],
    geometry: "plantation",
    module: [40, 40],
    regularity: 1,
    boundary: "fence",
    irrigation: "none",
    crops: [
      { id: "wheat", share: 0.35 },
      { id: "maize", share: 0.35 },
      { id: "pasture", share: 0.3 },
    ],
    orchard: 0.1,
    slopeLimit: 2,
    riverside: 0.1,
    reach: 2.4,
    commons: false,
    outbuildings: ["barn", "granary"],
    evidence: {
      status: "documented",
      note: "The Public Land Survey System laid a square-mile grid over the land west of the Ohio, and homesteads fenced their quarter sections with rails and then barbed wire for wheat, corn and stock.",
      sources: ["https://en.wikipedia.org/wiki/Public_Land_Survey_System"],
    },
  },
  ...mechanised,
];

/** An unprofiled place farms a plainly labelled generic pattern, never
 * another region's system. */
export const genericFarming: FarmSystem = {
  id: "illustrative-farmland",
  label: "Illustrative farmland",
  geometry: "block",
  module: [12, 10],
  regularity: 0.3,
  boundary: "none",
  irrigation: "none",
  crops: [
    { id: "wheat", share: 0.2 },
    { id: "millet", share: 0.15 },
    { id: "vegetables", share: 0.1 },
    { id: "fallow", share: 0.25 },
    { id: "pasture", share: 0.3 },
  ],
  orchard: 0.15,
  slopeLimit: 3,
  riverside: 0.3,
  reach: 2,
  commons: true,
  outbuildings: ["granary"],
  evidence: {
    status: "fictional",
    note: "A generic arrangement of grain plots, fallow and grazing around the settlement. Field systems have not been researched for this location and date.",
    sources: [],
  },
};
