import type { ReligiousRule } from "./types";

export const nearEastReligious: ReligiousRule[] = [
  {
    id: "roman-temple-africa",
    faith: "Roman",
    recipe: "roman-temple",
    labels: { small: "Temple", medium: "Temple", large: "Capitolium" },
    culture: "north-african-west-asian",
    from: -146,
    to: 392,
    bounds: [-10, 29, 25, 37.6],
    side: "north",
    about:
      "The house of a god on its podium at the head of the forum, as at Dougga, Sabratha and Leptis: the cult statue inside, the altar before the steps.",
    forecourt: 2,
    evidence: {
      status: "inferred",
      sources: [],
      note: "Roman Africa's temples follow the Italian podium temple; the Punic sanctuaries before them are not yet drawn.",
    },
  },
  {
    id: "greek-temple-ionia",
    faith: "Greek",
    recipe: "greek-temple",
    labels: { small: "Temple", medium: "Temple", large: "Great temple" },
    culture: "north-african-west-asian",
    from: -700,
    to: 392,
    bounds: [26, 35, 31, 41.5],
    side: "north",
    about:
      "The house of the city's god in its sanctuary, as at Ephesus, Didyma and Priene: the image inside, the altar out in front.",
    forecourt: 2,
    evidence: {
      status: "inferred",
      sources: [],
      note: "Drawn with the Doric temple; the Ionic of Ionia's great temples is a look the Roman temple carries.",
    },
  },
  {
    id: "mesopotamian-temple",
    faith: "Mesopotamian",
    recipe: "mesopotamian-temple",
    labels: { small: "Shrine", medium: "Temple", large: "Great temple" },
    culture: "north-african-west-asian",
    from: -3000,
    to: -539,
    bounds: [38, 29, 50, 38],
    side: "north",
    about:
      "The house of the city's god, in a walled court: priests offer there at dawn and dusk, the god's statue is fed and clothed, and none but the temple's own go in past the court.",
    forecourt: 2,
    warded: true,
    evidence: {
      status: "inferred",
      sources: [],
      note: "A niched and buttressed mud-brick enclosure with a towered gate, storerooms round a court and the god's house at the back follows the excavated temples of Nippur, Assur and Old Babylonian Ur. Kassite and Neo-Babylonian temples are not yet told apart.",
    },
  },
  {
    id: "hittite-temple",
    faith: "Hittite",
    recipe: "hittite-temple",
    labels: { small: "Shrine", medium: "Temple", large: "Great temple" },
    culture: "north-african-west-asian",
    from: -1650,
    to: -1180,
    bounds: [26, 35.5, 45, 42.5],
    side: "north",
    about:
      "A house of the thousand gods of Hatti in its walled court: the storerooms hold the god's grain and tablets, and the temple's guards keep the unclean from its gate.",
    forecourt: 2,
    warded: true,
    evidence: {
      status: "inferred",
      sources: [],
      note: "A stone socle under mud brick and timber, a gate flanked by lions, storerooms round a court and a pillared portico before the cella follow Temple I and the upper-city temples at Hattusa. Hittite instructions for temple officials order guards at the gates by night and day.",
    },
  },
  {
    id: "ottoman-mosque",
    faith: "Islam",
    recipe: "ottoman-mosque",
    labels: { small: "Mosque", medium: "Friday mosque", large: "Great mosque" },
    culture: "north-african-west-asian",
    from: 1400,
    to: 1923,
    bounds: [26, 36.8, 45, 42.5],
    side: "north",
    about:
      "The Friday mosque: its court and fountain open to all who come to pray, the great dome over the hall, and the call to prayer from its minarets five times a day.",
    forecourt: 2,
    evidence: {
      status: "inferred",
      sources: [],
      note: "A great lead dome on a drum over a square hall with half-domes and buttress turrets, a domed portico, pencil minarets with balconies and lead cones, and a court of small domes round a canopied ablution fountain, after the Ottoman mosques of Bursa, Edirne and Sinan's Istanbul. Smaller towns had one minaret and a single dome; the number of minarets follows the building's size.",
    },
  },
  {
    id: "arab-mosque",
    faith: "Islam",
    recipe: "arab-mosque",
    labels: { small: "Mosque", medium: "Friday mosque", large: "Great mosque" },
    culture: "north-african-west-asian",
    from: 640,
    to: 2100,
    bounds: [25, 12, 48, 37.5],
    side: "north",
    about:
      "The congregational mosque: the court where the town washes before prayer, the long hall of columns facing Mecca, and the minaret over the square.",
    forecourt: 2,
    evidence: {
      status: "inferred",
      sources: [],
      note: "A court with arcades and a basin, a broad flat-roofed hall of many columns with a gabled transept to the mihrab and a dome before it, and a square minaret in stages, after the Umayyad mosque of Damascus and the mosques of Fustat, Cairo and Aleppo; the alternating light and dark courses are Mamluk ablaq. Early mosques were plainer, and Ottoman Damascus and Cairo also built domed mosques in the imperial style.",
    },
  },
  {
    id: "maghrebi-mosque",
    faith: "Islam",
    recipe: "maghrebi-mosque",
    labels: { small: "Mosque", medium: "Friday mosque", large: "Great mosque" },
    culture: "north-african-west-asian",
    from: 700,
    to: 2100,
    bounds: [-18, 20, 12, 37.4],
    side: "north",
    about:
      "The Friday mosque: its court and fountain, the hall of parallel aisles roofed in green tile, and the square minaret over the town.",
    forecourt: 2,
    evidence: {
      status: "inferred",
      sources: [],
      note: "Whitewashed walls, a hall of aisles running toward the qibla under parallel ridges of green glazed tile, a gate under a tiled hood, and a square minaret with carved and tiled lozenge panels, merlons and a lantern topped with gilt balls, after Kairouan, the Qarawiyyin at Fez and the Kutubiyya at Marrakesh.",
    },
  },
  {
    id: "persian-mosque",
    faith: "Islam",
    recipe: "persian-mosque",
    labels: { small: "Mosque", medium: "Friday mosque", large: "Great mosque" },
    culture: "north-african-west-asian",
    from: 1000,
    to: 2100,
    bounds: [48, 26, 63, 40],
    side: "north",
    about:
      "The Friday mosque: a long pool in the court, the tiled iwan opening onto it, the dome over the sanctuary behind, and minarets on either side.",
    forecourt: 2,
    evidence: {
      status: "inferred",
      sources: [],
      note: "A brick court with a pool, a tall iwan faced in tile before an onion dome on a high drum, and slender tiled minarets beside it, after the Seljuk four-iwan mosques and the Safavid mosques of Isfahan; the turquoise and cobalt faience belongs to the later centuries, earlier domes being plain brick.",
    },
  },
];
