import type { Stance } from "../types";
const w = "https://en.wikipedia.org/wiki/";

export const andes: readonly Stance[] = [
  {
    id: "stance.ayni",
    label: "Labour given is labour owed",
    short: "Reciprocal",
    icon: "hand",
    clause: "keeps an account of days owed and given",
    kind: "economic",
    tags: ["communal", "agrarian", "egalitarian"],
    scope: { years: [-1000, 10001] },
    weight: 22,
    lean: "orthodox",
    wiki: `${w}Ayni`,
    note: "Work on a neighbour's field creates a debt in days that will be called in, which is how a household roofs a house without money.",
    sources: [],
  },
  {
    id: "stance.ayllu",
    label: "The kin group holds the ground",
    short: "Kin-held land",
    icon: "hill",
    clause: "works fields the kin group holds at several heights",
    kind: "economic",
    tags: ["communal", "agrarian", "traditionalist"],
    scope: { years: [-1000, 10001] },
    weight: 20,
    wiki: `${w}Ayllu`,
    note: "Fields at several altitudes are held by one descent group so that a failure at one height is covered by another.",
    sources: [],
  },
  {
    id: "stance.huaca",
    label: "The place itself is owed",
    short: "Place-bound",
    icon: "standing-stone",
    clause: "owes a named peak or spring and no other",
    kind: "cosmic",
    tags: ["traditionalist", "devout", "agrarian"],
    scope: { years: [-1500, 10001] },
    weight: 20,
    wiki: `${w}Huaca`,
    note: "A peak, a spring or an ancestor's body is a power with a name, attended by the group descended from it and by nobody else.",
    sources: [],
  },
  {
    id: "stance.mita",
    label: "The turn of service",
    short: "Labour-tribute",
    icon: "basket",
    clause: "pays obligation in turns of labour",
    kind: "political",
    tags: ["hierarchical", "communal", "traditionalist"],
    scope: { years: [1400, 1825] },
    weight: 16,
    wiki: `${w}Mit%27a`,
    note: "Obligation is paid in rotations of labour rather than in goods, an Inca arrangement the Spanish kept and drove into the mines.",
    sources: [],
  },
  {
    id: "stance.pachacuti",
    label: "The world turns over",
    short: "Cyclical",
    icon: "wheel",
    clause: "expects the world to turn and the low to come up",
    kind: "cosmic",
    tags: ["millenarian", "restorationist", "oral"],
    scope: { years: [-500, 10001] },
    weight: 10,
    wiki: `${w}Pachacuti`,
    note: "Time proceeds by reversals in which what is below comes up, which made the conquest legible and gave later risings their shape.",
    sources: [],
  },
  {
    id: "stance.mummy-ancestors",
    label: "The dead of the lineage remain present",
    short: "Ancestor-keeping",
    icon: "tomb",
    clause: "consults and feeds the preserved dead",
    kind: "cosmic",
    tags: ["traditionalist", "devout", "hierarchical"],
    scope: { years: [-1000, 1650] },
    weight: 14,
    wiki: `${w}Mallqui`,
    note: "Preserved ancestors are brought out, consulted and fed, and go on owning the estate they held alive.",
    sources: [],
  },
];
