import type { Stance } from "../types";
const w = "https://en.wikipedia.org/wiki/";

export const australiaPacific: readonly Stance[] = [
  {
    id: "stance.the-law",
    label: "The Law laid down in the country",
    short: "The Law",
    icon: "footprint",
    clause: "reads the Law in the country the ancestors made",
    kind: "cosmic",
    tags: ["traditionalist", "oral", "devout", "agrarian"],
    scope: { years: [-50000, 10001], bounds: [112, -44, 154, -10] },
    weight: 24,
    lean: "orthodox",
    wiki: `${w}Dreaming_(Australian_Aboriginal_art)`,
    note: "The ancestral beings made the country and left the rules in it; the country is the record, and people belong to it rather than owning it.",
    sources: [],
  },
  {
    id: "stance.custodianship",
    label: "Country is held in trust, not owned",
    short: "Custodial",
    icon: "earth",
    clause: "holds the country in trust and cannot transfer it",
    kind: "economic",
    tags: ["communal", "traditionalist", "oral"],
    scope: { years: [-50000, 10001], bounds: [112, -44, 154, -10] },
    weight: 22,
    wiki: `${w}Native_title_in_Australia`,
    note: "A group is responsible for particular ground and for the songs and burning that keep it, and cannot transfer either.",
    sources: [],
  },
  {
    id: "stance.kinship-obligation",
    label: "Everyone is placed in the kin system",
    short: "Kin-ordered",
    icon: "knot",
    clause: "places every person met within the kin system",
    kind: "ethical",
    tags: ["communal", "traditionalist", "hierarchical"],
    scope: { years: [-50000, 10001], bounds: [112, -44, 154, -10] },
    weight: 20,
    wiki: `${w}Australian_Aboriginal_kinship`,
    note: "Every person one meets is assigned a relation, which settles who may marry, who must be avoided, and who must be fed.",
    sources: [],
  },
  {
    id: "stance.mana-tapu",
    label: "Mana and tapu",
    short: "Mana and tapu",
    icon: "shell",
    clause: "keeps the prohibitions that protect a dangerous potency",
    kind: "cosmic",
    tags: ["hierarchical", "devout", "traditionalist"],
    scope: { years: [-1500, 10001], bounds: [150, -50, 220, 22] },
    weight: 22,
    lean: "orthodox",
    wiki: `${w}Mana`,
    note: "Effectiveness is a substance a person or object carries, protected by prohibitions whose breach is dangerous to everybody nearby.",
    sources: [],
  },
  {
    id: "stance.utu",
    label: "Every account is balanced",
    short: "Balancing",
    icon: "scales",
    clause: "returns a gift and an injury alike",
    kind: "ethical",
    tags: ["particularist", "martial", "communal"],
    scope: { years: [1000, 10001], bounds: [165, -48, 180, -33] },
    weight: 16,
    wiki: `${w}Utu_(M%C4%81ori_concept)`,
    note: "A gift and an injury both require a return; the return is owed by the group and may be made long after anyone has forgotten the cause.",
    sources: [],
  },
  {
    id: "stance.navigator",
    label: "The sea is known and can be read",
    short: "Wayfinding",
    icon: "star",
    clause: "reads the swell and the stars as a chart",
    kind: "cosmic",
    tags: ["oral", "empirical"],
    scope: { years: [-1500, 10001], bounds: [130, -25, 230, 25] },
    weight: 14,
    wiki: `${w}Polynesian_navigation`,
    note: "Stars, swell and birds hold as reliable a record as any chart, kept by families who train for it and guard it.",
    sources: [],
  },
  {
    id: "stance.cargo-prophet",
    label: "Prophetic movement",
    short: "Prophetic",
    icon: "boat",
    clause: "expects the foreigners' goods to come without them",
    kind: "cosmic",
    tags: ["millenarian", "restorationist", "devout"],
    scope: { years: [1880, 10001], bounds: [130, -25, 180, 5] },
    weight: 6,
    lean: "heterodox",
    wiki: `${w}Cargo_cult`,
    note: "A prophet explains where the foreigners' goods come from and what must be done to receive them directly; usually as much a political refusal as a religious claim.",
    sources: [],
  },
];
