import type { Stance } from "../types";

const w = "https://en.wikipedia.org/wiki/";

export const eastAsia: readonly Stance[] = [
  {
    id: "stance.confucian",
    label: "Confucian",
    icon: "book",
    clause: "keeps each relation and performs the rites exactly",
    kind: "ethical",
    tags: ["hierarchical", "traditionalist", "literate", "civic"],
    scope: { years: [-500, 10001] },
    weight: 20,
    lean: "orthodox",
    wiki: `${w}Confucianism`,
    note: "Order comes from each person keeping the relation they stand in — son to father, subject to ruler — and from ritual performed exactly.",
    sources: [],
  },
  {
    id: "stance.legalist",
    label: "Legalist",
    icon: "tablet",
    clause: "trusts published law and severe punishment",
    kind: "political",
    tags: ["hierarchical", "rationalist", "martial"],
    scope: { years: [-400, 1912] },
    ranks: ["middling", "gentry", "elite"],
    weight: 6,
    wiki: `${w}Legalism_(Chinese_philosophy)`,
    note: "People respond to reward and punishment and to nothing else, so the law should be published, uniform, and severe.",
    sources: [],
  },
  {
    id: "stance.mohist",
    label: "Mohist",
    icon: "scales",
    clause: "would care for everyone impartially",
    kind: "ethical",
    tags: ["universalist", "rationalist", "egalitarian", "ascetic"],
    scope: { years: [-450, -150] },
    weight: 3,
    lean: "heterodox",
    wiki: `${w}Mohism`,
    note: "Impartial care for everyone alike, against the graded love of the Confucians, plus a hard objection to funerals that ruin the family.",
    sources: [],
  },
  {
    id: "stance.daoist",
    label: "Daoist",
    icon: "river",
    clause: "holds that the way works by not forcing",
    kind: "cosmic",
    tags: ["quietist", "mystical", "sceptical"],
    scope: { years: [-400, 10001] },
    weight: 12,
    wiki: `${w}Taoism`,
    note: "The way works by not forcing; the sage governs by leaving alone, and the useless tree is the one that reaches its full age.",
    sources: [],
  },
  {
    id: "stance.mandate-of-heaven",
    label: "Mandate of Heaven",
    short: "Heaven's mandate",
    icon: "sky",
    clause: "reads a famine as Heaven withdrawing its warrant",
    kind: "political",
    tags: ["hierarchical", "devout", "traditionalist"],
    scope: { years: [-1000, 1912] },
    weight: 18,
    lean: "orthodox",
    wiki: `${w}Mandate_of_Heaven`,
    note: "Heaven appoints the dynasty and withdraws the appointment, which makes a flood or a famine an argument about legitimacy.",
    sources: [],
  },
  {
    id: "stance.filial-piety",
    label: "Filial piety",
    icon: "ancestors",
    clause: "puts the debt to a parent first",
    kind: "ethical",
    tags: ["hierarchical", "traditionalist", "communal"],
    scope: { years: [-1000, 10001] },
    weight: 22,
    lean: "orthodox",
    wiki: `${w}Filial_piety`,
    note: "The first obligation and the model for all the others; mourning a parent properly could take three years out of an official career.",
    sources: [],
  },
  {
    id: "stance.chan-quietist",
    label: "Chan quietist",
    icon: "lotus",
    clause: "looks for sudden insight rather than accumulated merit",
    kind: "temper",
    tags: ["mystical", "quietist", "ascetic"],
    scope: { years: [600, 10001] },
    weight: 7,
    wiki: `${w}Chan_Buddhism`,
    note: "Sudden insight rather than accumulated merit, and a suspicion of texts held by a tradition that produced a great many of them.",
    sources: [],
  },
  {
    id: "stance.pure-land",
    label: "Pure Land devotee",
    short: "Pure Land",
    icon: "lotus",
    clause: "trusts that calling the name is enough",
    kind: "cosmic",
    tags: ["devout", "egalitarian", "oral"],
    scope: { years: [500, 10001] },
    weight: 14,
    wiki: `${w}Pure_Land_Buddhism`,
    note: "Calling the name is enough, which put release within reach of people who could not read, retire, or pay for a rite.",
    sources: [],
  },
  {
    id: "stance.neo-confucian",
    label: "Neo-Confucian",
    icon: "mirror",
    clause: "looks for principle by the investigation of things",
    kind: "cosmic",
    tags: ["rationalist", "literate", "traditionalist", "ascetic"],
    scope: { years: [1100, 1900] },
    ranks: ["middling", "gentry", "elite"],
    weight: 10,
    wiki: `${w}Neo-Confucianism`,
    note: "Principle runs through everything and can be reached by the investigation of things, which meant study and self-discipline rather than ritual alone.",
    sources: [],
  },
  {
    id: "stance.wang-yangming",
    label: "Innate-knowledge school",
    short: "Innate knowing",
    icon: "heart",
    clause: "holds that knowing and acting are one",
    kind: "ethical",
    tags: ["individualist", "mystical", "egalitarian"],
    scope: { years: [1500, 1750] },
    weight: 4,
    lean: "heterodox",
    wiki: `${w}Wang_Yangming`,
    note: "Knowing and acting are one, and the knowledge is already in the person, which made the examination curriculum look beside the point.",
    sources: [],
  },
  {
    id: "stance.kokugaku",
    label: "Nativist",
    icon: "shrine",
    clause: "wants the foreign additions stripped away",
    kind: "political",
    tags: ["particularist", "restorationist", "literate"],
    scope: { years: [1700, 1900], bounds: [128, 30, 146, 46] },
    weight: 6,
    wiki: `${w}Kokugaku`,
    note: "Strip away the Chinese and Buddhist additions to recover what the islands believed first — a philological project that turned political.",
    sources: [],
  },
  {
    id: "stance.bushido",
    label: "The way of the warrior",
    short: "Bushido",
    icon: "sword",
    clause: "puts the lord above the family and the self",
    kind: "ethical",
    tags: ["martial", "hierarchical", "ascetic"],
    scope: { years: [1200, 1900], bounds: [128, 30, 146, 46] },
    ranks: ["gentry", "elite"],
    weight: 10,
    wiki: `${w}Bushido`,
    note: "Loyalty to the lord above the family and above the self, codified most fully in the long peace when there was no fighting to do.",
    sources: [],
  },
  {
    id: "stance.meiji-modernizer",
    label: "Meiji modernizer",
    icon: "kiln",
    clause: "would take the foreigners' machines to keep them out",
    kind: "economic",
    tags: ["reformist", "rationalist", "civic", "particularist"],
    scope: { years: [1868, 1930], bounds: [126, 28, 148, 46] },
    weight: 10,
    wiki: `${w}Meiji_Restoration`,
    note: "Take the foreigners' machines and institutions in order not to be taken by the foreigners; rich country, strong army.",
    sources: [],
  },
  {
    id: "stance.self-strengthening",
    label: "Self-strengthener",
    short: "Self-strengthen",
    icon: "anvil",
    clause: "wants Western use on Chinese substance",
    kind: "economic",
    tags: ["reformist", "traditionalist", "martial"],
    scope: { years: [1861, 1900], bounds: [100, 18, 128, 45] },
    ranks: ["middling", "gentry", "elite"],
    weight: 6,
    wiki: `${w}Self-Strengthening_Movement`,
    note: "Chinese learning for the substance, Western learning for the use — a formula its critics said could not be held for long.",
    sources: [],
  },
  {
    id: "stance.taiping",
    label: "Taiping",
    icon: "comet",
    clause: "expects a kingdom on earth with the land held in common",
    kind: "cosmic",
    tags: ["millenarian", "revolutionary", "egalitarian", "devout"],
    scope: { years: [1850, 1866], bounds: [104, 20, 122, 34] },
    weight: 4,
    lean: "heterodox",
    wiki: `${w}Taiping_Rebellion`,
    note: "A Christian kingdom on earth with land held in common, which killed more people than any other war of the century.",
    sources: [],
  },
  {
    id: "stance.may-fourth",
    label: "New Culture radical",
    short: "New Culture",
    icon: "lamp",
    clause: "wants science and democracy against the old family order",
    kind: "ethical",
    tags: ["revolutionary", "rationalist", "literate", "egalitarian"],
    scope: { years: [1915, 1950], bounds: [100, 18, 128, 45] },
    ranks: ["middling", "gentry"],
    weight: 6,
    wiki: `${w}New_Culture_Movement`,
    note: "Science and democracy against the old family order, in the plain written language rather than the classical one.",
    sources: [],
  },
  {
    id: "stance.geomancer",
    label: "Geomantic",
    icon: "hill",
    clause: "will not site a house or a grave without advice",
    kind: "cosmic",
    tags: ["traditionalist", "mystical"],
    scope: { years: [-200, 10001] },
    weight: 14,
    wiki: `${w}Feng_shui`,
    note: "Where a house or a grave is placed decides how the family does, so siting is a matter for a specialist and for litigation.",
    sources: [],
  },
];
