import type { Stance } from "../types";
const w = "https://en.wikipedia.org/wiki/";

export const eastSouthernAfrica: readonly Stance[] = [
  {
    id: "stance.ubuntu",
    label: "Personhood through others",
    short: "Ubuntu",
    icon: "crowd",
    clause: "holds that a person is a person through others",
    kind: "ethical",
    tags: ["communal", "egalitarian", "oral"],
    scope: { years: [-500, 10001] },
    weight: 20,
    lean: "orthodox",
    wiki: `${w}Ubuntu_philosophy`,
    note: "A person is a person through other people; standing apart is not independence but a kind of incompleteness.",
    sources: [],
  },
  {
    id: "stance.cattle-standing",
    label: "Cattle are the measure",
    short: "Cattle-reckoning",
    icon: "cattle",
    clause: "reckons a household's history in its herd",
    kind: "economic",
    tags: ["agrarian", "hierarchical", "traditionalist"],
    scope: { years: [-500, 10001] },
    weight: 20,
    wiki: `${w}Cattle_in_religion_and_mythology`,
    note: "Herds carry marriage payments, settle feuds and record a lineage's history; selling them for coin is a loss whatever the price.",
    sources: [],
  },
  {
    id: "stance.rainmaker",
    label: "The rain answers to a person",
    short: "Rain-calling",
    icon: "rain",
    clause: "holds a drought to be somebody's responsibility",
    kind: "cosmic",
    tags: ["devout", "hierarchical", "oral"],
    scope: { years: [-500, 1950] },
    weight: 14,
    wiki: `${w}Rainmaking_(ritual)`,
    note: "A drought is somebody's responsibility and somebody's opportunity, which made the rain specialist a political figure.",
    sources: [],
  },
  {
    id: "stance.age-set",
    label: "The age-set before the family",
    short: "Age-set loyal",
    icon: "spear",
    clause: "owes the age-set more than a brother",
    kind: "ethical",
    tags: ["communal", "martial", "egalitarian"],
    scope: { years: [-500, 10001] },
    weight: 14,
    wiki: `${w}Age_set`,
    note: "Those circumcised or initiated together move through life as one body, owing each other more than they owe their brothers.",
    sources: [],
  },
  {
    id: "stance.swahili-cosmopolitan",
    label: "Coastal cosmopolitan",
    short: "Coastal",
    icon: "boat",
    clause: "faces the monsoon rather than the interior",
    kind: "economic",
    tags: ["mercantile", "universalist", "literate"],
    scope: { years: [800, 10001], bounds: [38, -15, 52, 4] },
    ranks: ["middling", "gentry", "elite"],
    weight: 10,
    wiki: `${w}Swahili_culture`,
    note: "A town facing the monsoon rather than the interior, Muslim, stone-built, and reckoning descent toward the sea.",
    sources: [],
  },
  {
    id: "stance.spirit-possession",
    label: "The afflicted are ridden",
    short: "Possession",
    icon: "drum",
    clause: "expects a spirit to speak through the afflicted",
    kind: "cosmic",
    tags: ["mystical", "oral", "communal"],
    scope: { years: [-500, 10001] },
    weight: 12,
    wiki: `${w}Zar`,
    note: "A spirit speaks through the sufferer and makes demands that the household must meet, which gives a voice to people who have few other ways to make one.",
    sources: [],
  },
];
