import type { Stance } from "../types";

const w = "https://en.wikipedia.org/wiki/";
const MED: [number, number, number, number] = [-10, 30, 42, 48];

/** Named European positions before the nineteenth century. The ideologies that
 * spread out of Europe and were taken up elsewhere live in `modern.ts`, so a
 * Bengali social democrat does not have to be filed as a European. */
export const european: readonly Stance[] = [
  /* --- classical -------------------------------------------------------- */
  {
    id: "stance.arete",
    label: "Arete",
    icon: "crown",
    clause: "seeks the excellence proper to a station",
    kind: "ethical",
    tags: ["civic", "martial", "hierarchical"],
    scope: { years: [-800, -100], bounds: MED },
    ranks: ["middling", "gentry", "elite"],
    weight: 12,
    lean: "orthodox",
    wiki: `${w}Arete`,
    note: "Excellence proper to one's station, shown in public and judged by those competent to judge it. Not a private virtue and not available to everybody.",
    sources: [],
  },
  {
    id: "stance.stoic",
    label: "Stoic",
    icon: "cliff",
    clause: "minds only what lies in a person's own power",
    kind: "ethical",
    tags: ["ascetic", "rationalist", "universalist", "literate"],
    scope: { years: [-300, 400], bounds: [-10, 25, 50, 55] },
    weight: 8,
    wiki: `${w}Stoicism`,
    note: "Only what is in one's own power is worth minding; the rest, including one's own death, is to be met without complaint.",
    sources: [],
  },
  {
    id: "stance.epicurean",
    label: "Epicurean",
    icon: "vine",
    clause: "wants a quiet life among friends",
    kind: "ethical",
    tags: ["sceptical", "quietist", "literate", "individualist"],
    scope: { years: [-300, 400], bounds: MED },
    ranks: ["middling", "gentry", "elite"],
    weight: 5,
    lean: "heterodox",
    wiki: `${w}Epicureanism`,
    note: "The gods exist and take no interest; death is nothing to us; the aim is a quiet life among friends, out of public affairs.",
    sources: [],
  },
  {
    id: "stance.cynic",
    label: "Cynic",
    icon: "dog",
    clause: "treats convention as a costume",
    kind: "ethical",
    tags: ["ascetic", "egalitarian", "sceptical"],
    scope: { years: [-400, 300], bounds: MED },
    weight: 3,
    lean: "heterodox",
    wiki: `${w}Cynicism_(philosophy)`,
    note: "Convention is a costume; the philosopher lives in public on nothing and says to powerful men what nobody else will.",
    sources: [],
  },
  {
    id: "stance.platonist",
    label: "Platonist",
    icon: "cave",
    clause: "looks past appearances for the form behind them",
    kind: "cosmic",
    tags: ["rationalist", "literate", "mystical"],
    scope: { years: [-380, 600], bounds: MED },
    ranks: ["middling", "gentry", "elite"],
    weight: 5,
    wiki: `${w}Platonism`,
    note: "What is seen is a poor copy of what is; the work of a mind is to get past appearances to the form behind them.",
    sources: [],
  },
  {
    id: "stance.aristotelian",
    label: "Aristotelian",
    icon: "scroll",
    clause: "asks what end a thing is for",
    kind: "cosmic",
    tags: ["rationalist", "empirical", "literate"],
    scope: { years: [-330, 1700], bounds: [-10, 25, 55, 60] },
    ranks: ["middling", "gentry", "elite"],
    weight: 6,
    wiki: `${w}Aristotelianism`,
    note: "Everything has an end proper to it and can be understood by finding out what that is. Survived as the frame of university teaching for two thousand years.",
    sources: [],
  },
  {
    id: "stance.mos-maiorum",
    label: "The custom of the ancestors",
    short: "Ancestral custom",
    icon: "ancestors",
    clause: "holds that a novelty is its own objection",
    kind: "political",
    tags: ["traditionalist", "civic", "hierarchical"],
    scope: { years: [-500, 300], bounds: MED },
    weight: 14,
    lean: "orthodox",
    wiki: `${w}Mos_maiorum`,
    note: "Roman public life was governed by unwritten precedent, and the argument against any novelty was that it was one.",
    sources: [],
  },
  {
    id: "stance.republican-liberty",
    label: "Republican liberty",
    short: "Republican",
    icon: "pillar",
    clause: "will be subject to no man's will",
    kind: "political",
    tags: ["civic", "martial", "egalitarian"],
    scope: { years: [-500, 100], bounds: MED },
    ranks: ["middling", "gentry", "elite"],
    weight: 8,
    wiki: `${w}Classical_republicanism`,
    note: "To be free is to be subject to no man's will, which makes a generous master no better than a cruel one.",
    sources: [],
  },
  /* --- medieval --------------------------------------------------------- */
  {
    id: "stance.three-orders",
    label: "The three orders",
    short: "Three orders",
    icon: "ladder",
    clause: "takes prayer, war and work for God's arrangement",
    kind: "political",
    tags: ["hierarchical", "traditionalist", "devout"],
    scope: { years: [900, 1600], bounds: [-10, 36, 30, 60] },
    weight: 20,
    lean: "orthodox",
    wiki: `${w}Three-order_feudal_society`,
    note: "Some pray, some fight, some work, and the arrangement is held to be God's rather than anyone's. The people who did the working were not consulted.",
    sources: [],
  },
  {
    id: "stance.chivalric",
    label: "Chivalric",
    icon: "shield",
    clause: "holds to the code among armed men",
    kind: "ethical",
    tags: ["martial", "hierarchical", "devout"],
    scope: { years: [1050, 1600], bounds: [-10, 36, 30, 60] },
    ranks: ["gentry", "elite"],
    weight: 12,
    wiki: `${w}Chivalry`,
    note: "A code binding armed men to each other and to the church, and conspicuously not to anyone they might ride over.",
    sources: [],
  },
  {
    id: "stance.scholastic",
    label: "Scholastic",
    icon: "book",
    clause: "expects faith and reason to be reconciled by argument",
    kind: "cosmic",
    tags: ["rationalist", "literate", "devout"],
    scope: { years: [1100, 1650], bounds: [-10, 36, 30, 60] },
    ranks: ["middling", "gentry", "elite"],
    weight: 8,
    wiki: `${w}Scholasticism`,
    note: "Faith and reason cannot finally conflict, so an apparent conflict is a problem in the argument and can be worked out by disputation.",
    sources: [],
  },
  {
    id: "stance.nominalist",
    label: "Nominalist",
    icon: "needle",
    clause: "allows that only particular things exist",
    kind: "cosmic",
    tags: ["sceptical", "rationalist", "literate"],
    scope: { years: [1300, 1650], bounds: [-10, 36, 30, 60] },
    ranks: ["middling", "gentry", "elite"],
    weight: 4,
    lean: "heterodox",
    wiki: `${w}Nominalism`,
    note: "Only particular things exist; the universals are names we find convenient. Corrosive of the scholastic system it grew inside.",
    sources: [],
  },
  {
    id: "stance.franciscan-poverty",
    label: "Apostolic poverty",
    short: "Apostolic",
    icon: "basket",
    clause: "holds that the apostles owned nothing",
    kind: "economic",
    tags: ["ascetic", "devout", "egalitarian"],
    scope: { years: [1200, 1600], bounds: [-10, 36, 30, 60] },
    weight: 6,
    lean: "heterodox",
    wiki: `${w}Apostolic_poverty`,
    note: "Christ and the apostles owned nothing, so a church that owns a great deal has some explaining to do. The explaining was done with fire more than once.",
    sources: [],
  },
  {
    id: "stance.joachimite",
    label: "Joachimite",
    icon: "comet",
    clause: "expects the third age to begin shortly",
    kind: "cosmic",
    tags: ["millenarian", "mystical", "devout"],
    scope: { years: [1200, 1600], bounds: [-10, 36, 30, 60] },
    weight: 3,
    lean: "heterodox",
    wiki: `${w}Joachim_of_Fiore`,
    note: "History runs in three ages and the third is about to begin, which made every disturbance look like the schedule being kept.",
    sources: [],
  },
  {
    id: "stance.cathar",
    label: "Dualist",
    icon: "eclipse",
    clause: "takes the material world for an evil power's work",
    kind: "cosmic",
    tags: ["ascetic", "mystical", "devout"],
    scope: { years: [1100, 1330], bounds: [-2, 41, 14, 48] },
    weight: 4,
    lean: "heterodox",
    wiki: `${w}Catharism`,
    note: "The material world is the work of an evil power and the good one had no hand in it, so the body is a prison rather than a gift.",
    sources: [],
  },
  {
    id: "stance.lollard",
    label: "Lollard",
    icon: "tablet",
    clause: "wants the scripture in the common tongue",
    kind: "temper",
    tags: ["reformist", "literate", "egalitarian"],
    scope: { years: [1380, 1540], bounds: [-8, 50, 2, 59] },
    weight: 4,
    lean: "heterodox",
    wiki: `${w}Lollardy`,
    note: "The scripture in English, in the hands of anyone who can read it, and no need of a priest to say what it means.",
    sources: [],
  },
  /* --- early modern ----------------------------------------------------- */
  {
    id: "stance.humanist",
    label: "Humanist",
    icon: "scroll",
    clause: "is formed by the ancients read in the original",
    kind: "ethical",
    tags: ["literate", "civic", "rationalist"],
    scope: { years: [1380, 1700], bounds: [-10, 36, 30, 60] },
    ranks: ["middling", "gentry", "elite"],
    weight: 8,
    wiki: `${w}Renaissance_humanism`,
    note: "The ancients wrote better and lived better, and a person is formed by reading them in the original rather than by disputation.",
    sources: [],
  },
  {
    id: "stance.erasmian",
    label: "Erasmian",
    icon: "comb",
    clause: "would mend the church by learning and ridicule",
    kind: "temper",
    tags: ["reformist", "literate", "universalist"],
    scope: { years: [1500, 1650], bounds: [-10, 36, 30, 60] },
    ranks: ["middling", "gentry", "elite"],
    weight: 4,
    wiki: `${w}Erasmus`,
    note: "Reform the church by learning and ridicule rather than by schism, a position that satisfied neither side once the schism came.",
    sources: [],
  },
  {
    id: "stance.lutheran-vocation",
    label: "The calling",
    icon: "hammer",
    clause: "takes ordinary work for the service God asks",
    kind: "economic",
    tags: ["devout", "individualist", "worldly"],
    scope: { years: [1520, 1900], bounds: [4, 46, 30, 62] },
    weight: 12,
    wiki: `${w}Calling_(Christianity)`,
    note: "Ordinary work is itself the service God asks, which dignified the trades and removed the monastery's monopoly on holiness.",
    sources: [],
  },
  {
    id: "stance.calvinist-election",
    label: "Predestinarian",
    icon: "scales-of-fate",
    clause: "holds the saved to have been chosen beforehand",
    kind: "cosmic",
    tags: ["devout", "literate", "ascetic"],
    scope: { years: [1540, 1850], bounds: [-6, 50, 12, 61] },
    weight: 10,
    wiki: `${w}Unconditional_election`,
    note: "The saved were chosen before the world was made and nothing done since alters the list, which is meant to console and frequently does not.",
    sources: [],
  },
  {
    id: "stance.anabaptist",
    label: "Anabaptist communalist",
    short: "Anabaptist",
    icon: "river",
    clause: "wants goods held in common and no oath sworn",
    kind: "economic",
    tags: ["communal", "egalitarian", "devout", "ascetic"],
    scope: { years: [1525, 1800], bounds: [2, 45, 22, 56] },
    weight: 3,
    lean: "heterodox",
    wiki: `${w}Anabaptism`,
    note: "Baptism for adults who choose it, goods held in common, and no oath to any magistrate. Persecuted by every other party at once.",
    sources: [],
  },
  {
    id: "stance.reason-of-state",
    label: "Reason of state",
    short: "Reason of state",
    icon: "mask",
    clause: "allows a ruler the necessary wrong",
    kind: "political",
    tags: ["worldly", "sceptical", "hierarchical"],
    scope: { years: [1510, 1800], bounds: [-10, 36, 30, 60] },
    ranks: ["gentry", "elite"],
    weight: 6,
    wiki: `${w}Raison_d%27%C3%A9tat`,
    note: "The state's survival is its own justification, and a ruler who will not do the necessary wrong has mistaken his office for a private conscience.",
    sources: [],
  },
  {
    id: "stance.divine-right",
    label: "Divine right of kings",
    short: "Divine right",
    icon: "crown",
    clause: "holds that a king answers to God alone",
    kind: "political",
    tags: ["hierarchical", "devout", "traditionalist"],
    scope: { years: [1580, 1800], bounds: [-10, 36, 30, 62] },
    weight: 14,
    lean: "orthodox",
    wiki: `${w}Divine_right_of_kings`,
    note: "The king answers to God alone, so resisting him is blasphemy rather than treason. Sharpened, not inherited, in the wars of religion.",
    sources: [],
  },
  {
    id: "stance.ancient-constitution",
    label: "Ancient constitutionalist",
    short: "Constitutional",
    icon: "standing-stone",
    clause: "holds the liberties older than the crown",
    kind: "political",
    tags: ["traditionalist", "civic", "literate"],
    scope: { years: [1590, 1800], bounds: [-8, 42, 20, 60] },
    ranks: ["middling", "gentry", "elite"],
    weight: 8,
    wiki: `${w}Ancient_constitution_of_England`,
    note: "The liberties are older than the crown and were never granted, so a king who abridges them is the innovator.",
    sources: [],
  },
  {
    id: "stance.leveller",
    label: "Leveller",
    icon: "hand",
    clause: "claims a voice in who governs",
    kind: "political",
    tags: ["egalitarian", "reformist", "civic"],
    scope: { years: [1640, 1700], bounds: [-8, 50, 2, 59] },
    ranks: ["labouring", "middling"],
    weight: 3,
    lean: "heterodox",
    wiki: `${w}Levellers`,
    note: "The poorest he that is in England has a life to live as the greatest he, and therefore a voice in who governs him.",
    sources: [],
  },
  {
    id: "stance.digger",
    label: "Digger",
    icon: "sickle",
    clause: "would dig the common ground without asking",
    kind: "economic",
    tags: ["communal", "egalitarian", "agrarian", "revolutionary"],
    scope: { years: [1648, 1700], bounds: [-8, 50, 2, 59] },
    ranks: ["destitute", "labouring"],
    weight: 2,
    lean: "heterodox",
    wiki: `${w}Diggers`,
    note: "The earth was made a common treasury, so the commons are to be dug and planted by anyone who needs to, without asking.",
    sources: [],
  },
  {
    id: "stance.hermeticist",
    label: "Hermeticist",
    icon: "maze",
    clause: "reads the world as a web of correspondences",
    kind: "cosmic",
    tags: ["mystical", "literate", "rationalist"],
    scope: { years: [1450, 1750], bounds: [-10, 36, 30, 60] },
    ranks: ["middling", "gentry", "elite"],
    weight: 4,
    lean: "heterodox",
    wiki: `${w}Hermeticism`,
    note: "An ancient wisdom older than the philosophers, in which the world is a web of correspondences a trained mind can operate.",
    sources: [],
  },
  {
    id: "stance.demonologist",
    label: "Demonologist",
    icon: "scorpion",
    clause: "holds that malice is contracted for by pact",
    kind: "cosmic",
    tags: ["devout", "literate", "particularist"],
    scope: { years: [1480, 1750], bounds: [-10, 36, 30, 62] },
    weight: 8,
    wiki: `${w}Witch_hunt`,
    note: "Malice is not merely worked but contracted for, by pact with a named adversary, and the remedy is judicial. An educated position, not a folk one.",
    sources: [],
  },
  {
    id: "stance.mercantilist",
    label: "Mercantilist",
    icon: "boat",
    clause: "wants the bullion kept in and the manufactures out",
    kind: "economic",
    tags: ["mercantile", "particularist", "civic"],
    scope: { years: [1600, 1820], bounds: [-10, 36, 30, 62] },
    ranks: ["middling", "gentry", "elite"],
    weight: 10,
    lean: "orthodox",
    wiki: `${w}Mercantilism`,
    note: "Trade is a fixed quantity and what one kingdom gains another loses, so bullion is kept in and manufactures kept out.",
    sources: [],
  },
  {
    id: "stance.natural-law",
    label: "Natural law",
    icon: "scales",
    clause: "holds some obligations binding without revelation",
    kind: "political",
    tags: ["rationalist", "universalist", "literate"],
    scope: { years: [1600, 1900], bounds: [-10, 36, 30, 62] },
    ranks: ["middling", "gentry", "elite"],
    weight: 8,
    wiki: `${w}Natural_law`,
    note: "There are obligations binding on rulers and strangers alike, discoverable by reason without revelation — which is what made them usable between states of different religions.",
    sources: [],
  },
  {
    id: "stance.jansenist",
    label: "Jansenist",
    icon: "thread",
    clause: "is rigorist about grace and about the confessional",
    kind: "temper",
    tags: ["ascetic", "devout", "literate"],
    scope: { years: [1640, 1790], bounds: [-5, 42, 8, 52] },
    weight: 3,
    lean: "heterodox",
    wiki: `${w}Jansenism`,
    note: "Rigorist about grace and about the confessional, austere in manner, and suppressed by a church that found it insufficiently obedient.",
    sources: [],
  },
  {
    id: "stance.pietist",
    label: "Pietist",
    icon: "heart",
    clause: "counts a changed life above correct doctrine",
    kind: "temper",
    tags: ["devout", "mystical", "communal"],
    scope: { years: [1670, 1900], bounds: [2, 45, 30, 60] },
    weight: 6,
    wiki: `${w}Pietism`,
    note: "Inward feeling and a changed life count for more than correct doctrine, and the small meeting for more than the parish.",
    sources: [],
  },
  {
    id: "stance.deist",
    label: "Deist",
    icon: "wheel",
    clause: "allows a creator who does not interfere",
    kind: "cosmic",
    tags: ["rationalist", "sceptical", "literate", "universalist"],
    scope: { years: [1670, 1900], bounds: [-10, 36, 30, 62] },
    ranks: ["middling", "gentry", "elite"],
    weight: 6,
    lean: "heterodox",
    wiki: `${w}Deism`,
    note: "A creator who set the thing running and does not interfere, which leaves the moral law standing and the miracles out.",
    sources: [],
  },
  {
    id: "stance.physiocrat",
    label: "Physiocrat",
    icon: "grain",
    clause: "holds that only the land yields a true surplus",
    kind: "economic",
    tags: ["agrarian", "rationalist", "reformist"],
    scope: { years: [1750, 1820], bounds: [-10, 36, 30, 62] },
    ranks: ["middling", "gentry", "elite"],
    weight: 4,
    wiki: `${w}Physiocracy`,
    note: "Only land produces a true surplus; trade and manufacture merely move it about. The first argument for letting the grain trade alone.",
    sources: [],
  },
  {
    id: "stance.enlightenment-universalism",
    label: "Enlightenment universalism",
    short: "Universalist",
    icon: "lamp",
    clause: "judges every custom by one reason",
    kind: "ethical",
    tags: ["universalist", "rationalist", "reformist", "literate"],
    scope: { years: [1720, 1900], bounds: [-10, 30, 40, 66] },
    ranks: ["middling", "gentry", "elite"],
    weight: 10,
    wiki: `${w}Age_of_Enlightenment`,
    note: "One human nature everywhere, one reason to judge by, and local custom as evidence about custom rather than about what is right.",
    sources: [],
  },
  {
    id: "stance.jacobin",
    label: "Jacobin",
    icon: "cross",
    clause: "would enforce virtue on the republic's behalf",
    kind: "political",
    tags: ["revolutionary", "egalitarian", "civic", "universalist"],
    scope: { years: [1789, 1830], bounds: [-10, 36, 30, 62] },
    weight: 4,
    lean: "heterodox",
    wiki: `${w}Jacobin`,
    note: "The republic is one and indivisible, virtue is enforceable, and the emergency justifies whatever the emergency requires.",
    sources: [],
  },
  {
    id: "stance.burkean",
    label: "Burkean conservative",
    short: "Burkean",
    icon: "tree",
    clause: "will not reform a society from first principles",
    kind: "political",
    tags: ["traditionalist", "hierarchical", "reformist"],
    scope: { years: [1790, 10001], bounds: [-10, 30, 40, 66] },
    ranks: ["middling", "gentry", "elite"],
    weight: 8,
    wiki: `${w}Conservatism`,
    note: "A society is an inheritance no living generation is entitled to spend, so reform must go slowly and never from first principles.",
    sources: [],
  },
  {
    id: "stance.throne-and-altar",
    label: "Throne and altar",
    short: "Throne and altar",
    icon: "throne",
    clause: "wants the old order restored entire",
    kind: "political",
    tags: ["hierarchical", "devout", "restorationist"],
    scope: { years: [1790, 1920], bounds: [-10, 36, 40, 62] },
    weight: 8,
    wiki: `${w}Legitimists`,
    note: "The revolution was a punishment, the remedy is the old order entire, and a constitutional monarchy is merely a slower surrender.",
    sources: [],
  },
  {
    id: "stance.ultramontane",
    label: "Ultramontane",
    icon: "minaret",
    clause: "looks to Rome over the national bishops",
    kind: "temper",
    tags: ["devout", "hierarchical", "universalist"],
    scope: { years: [1800, 1970], bounds: [-10, 36, 30, 60] },
    weight: 6,
    wiki: `${w}Ultramontanism`,
    note: "Authority runs to Rome and not through the national bishops or the state, which made it a live political question in every Catholic country.",
    sources: [],
  },
  {
    id: "stance.romantic",
    label: "Romantic",
    icon: "waterfall",
    clause: "prefers feeling and the particular to system",
    kind: "ethical",
    tags: ["individualist", "particularist", "mystical"],
    scope: { years: [1790, 1900], bounds: [-10, 30, 40, 66] },
    ranks: ["middling", "gentry", "elite"],
    weight: 6,
    wiki: `${w}Romanticism`,
    note: "Feeling and the particular against system and the general; the old songs and the untidy landscape preferred to the improved ones.",
    sources: [],
  },
  {
    id: "stance.chartist",
    label: "Chartist",
    icon: "scroll",
    clause: "wants the vote before the factory question",
    kind: "political",
    tags: ["egalitarian", "reformist", "civic"],
    scope: { years: [1838, 1870], bounds: [-8, 50, 2, 59] },
    ranks: ["destitute", "labouring", "middling"],
    weight: 6,
    wiki: `${w}Chartism`,
    note: "Six points, of which the vote for every man is the first; the argument that the factory question cannot be settled until the franchise is.",
    sources: [],
  },
];
