import type { Stance } from "../types";

const ALL: [number, number] = [-1000000, 10001];
const w = "https://en.wikipedia.org/wiki/";

/**
 * Positions with no proper name, held very widely and for a very long time.
 * These are the backbone: a scope with no authored tradition of its own still
 * produces a person who believes something, which is the honest reading of a
 * thin record rather than a blank one.
 *
 * Their weights are high on purpose. A named tradition is a minority position
 * almost everywhere it appears.
 */
export const generals: readonly Stance[] = [
  /* --- cosmic ----------------------------------------------------------- */
  {
    id: "general.dead-remain",
    label: "The dead remain among the living",
    short: "Ghost-minded",
    icon: "ancestors",
    clause: "keeps the household dead close and fed",
    kind: "cosmic",
    tags: ["traditionalist", "oral", "devout"],
    scope: { years: ALL },
    weight: 22,
    wiki: `${w}Ancestor_veneration`,
    note: "The household's own dead stay near it, are fed at the usual times, and take offence at being forgotten.",
    sources: [],
  },
  {
    id: "general.ancestors-judge",
    label: "The ancestors judge the living",
    short: "Ancestor-judged",
    icon: "scales",
    clause: "values the judgement of the ancestors",
    kind: "cosmic",
    tags: ["traditionalist", "communal", "oral"],
    scope: { years: ALL },
    weight: 16,
    wiki: `${w}Ancestor_veneration`,
    note: "A run of bad years is read as a verdict on how the lineage has been conducting itself, and answered with an offering rather than a change of method.",
    sources: [],
  },
  {
    id: "general.malice-works",
    label: "Misfortune is worked by a malicious neighbour",
    short: "Witchcraft",
    icon: "eye",
    clause: "reads misfortune as a neighbour's malice",
    kind: "cosmic",
    tags: ["particularist", "oral"],
    scope: { years: ALL },
    weight: 18,
    wiki: `${w}Witchcraft`,
    note: "Illness and loss have an author, usually close by and usually somebody already resented. The accusation follows the grudge, not the symptom.",
    sources: [],
  },
  {
    id: "general.powers-in-the-land",
    label: "The land itself holds powers",
    short: "Animist",
    icon: "spring",
    clause: "owes something to every spring and stone",
    kind: "cosmic",
    tags: ["traditionalist", "agrarian", "oral"],
    scope: { years: ALL },
    weight: 20,
    wiki: `${w}Animism`,
    note: "A spring, a stand of trees or a particular stone is owed something before it is used, and the obligation is to that place and no other.",
    sources: [],
  },
  {
    id: "general.dreams-true",
    label: "Dreams carry true information",
    short: "Dream-reading",
    icon: "sleep",
    clause: "treats a dream as news about the waking world",
    kind: "cosmic",
    tags: ["mystical", "oral"],
    scope: { years: ALL },
    weight: 14,
    wiki: `${w}Dream#Religion`,
    note: "What is seen asleep is about the waking world: a warning, a message from the dead, or an instruction that can be acted on in the morning.",
    sources: [],
  },
  {
    id: "general.omens-read",
    label: "The world announces what is coming",
    short: "Omen-reading",
    icon: "bird",
    clause: "reads what is coming in birds and weather",
    kind: "cosmic",
    tags: ["traditionalist", "oral"],
    scope: { years: ALL },
    weight: 15,
    wiki: `${w}Divination`,
    note: "Birds, weather, entrails and the fall of lots all carry notice of what is intended, for anyone who has learned to read them.",
    sources: [],
  },
  {
    id: "general.first-people",
    label: "The first people did it rightly and we have slipped",
    short: "Declinist",
    icon: "footprint",
    clause: "believes the first people did it rightly",
    kind: "cosmic",
    tags: ["traditionalist", "restorationist", "oral"],
    scope: { years: ALL },
    weight: 14,
    wiki: `${w}Golden_Age`,
    note: "The right way of doing things was settled at the beginning and has been eroding since; the work of the present is to hold what is left.",
    sources: [],
  },
  {
    id: "general.turning-world",
    label: "The world turns and comes round again",
    short: "Cyclical",
    icon: "wheel",
    clause: "expects the age to come round again",
    kind: "cosmic",
    tags: ["traditionalist", "agrarian"],
    scope: { years: ALL },
    weight: 12,
    wiki: `${w}Eternal_return`,
    note: "Ages, seasons and dynasties run their course and repeat, so nothing is finally lost and nothing is finally gained.",
    sources: [],
  },
  {
    id: "general.all-written",
    label: "All of it is already written",
    short: "Fated",
    icon: "scroll",
    clause: "holds that every hour was fixed beforehand",
    kind: "cosmic",
    tags: ["quietist", "devout"],
    scope: { years: ALL },
    weight: 12,
    wiki: `${w}Predestination`,
    note: "The hour and manner of every death was fixed before it, which is a reason for steadiness rather than for despair.",
    sources: [],
  },
  {
    id: "general.stars-incline",
    label: "The stars incline but do not compel",
    short: "Astrological",
    icon: "constellation",
    clause: "allows the stars to incline but not compel",
    kind: "cosmic",
    tags: ["literate", "rationalist"],
    scope: { years: [-1800, 10001] },
    ranks: ["middling", "gentry", "elite"],
    weight: 8,
    wiki: `${w}Astrology`,
    note: "The heavens set a disposition that a person of discipline can work against, which is how astrology survived alongside doctrines of free will.",
    sources: [],
  },
  {
    id: "general.soul-wanders",
    label: "Sickness is the soul gone out of the body",
    short: "Soul-loss",
    icon: "breath",
    clause: "takes sickness for a soul gone wandering",
    kind: "cosmic",
    tags: ["mystical", "oral"],
    scope: { years: ALL },
    weight: 10,
    wiki: `${w}Shamanism`,
    note: "The cure is to find what has gone and bring it back, which is work for a specialist rather than for a herb.",
    sources: [],
  },
  {
    id: "general.judged-after",
    label: "The dead are judged",
    short: "Judgement-minded",
    icon: "scales",
    clause: "expects a reckoning after death",
    kind: "cosmic",
    tags: ["devout", "universalist"],
    scope: { years: [-2500, 10001] },
    weight: 16,
    wiki: `${w}Afterlife`,
    note: "What was done in life is weighed after it, which makes the conduct of a poor person matter as much as a powerful one's.",
    sources: [],
  },
  {
    id: "general.reborn",
    label: "The dead return in another body",
    short: "Rebirth-minded",
    icon: "egg",
    clause: "expects the dead to return in another body",
    kind: "cosmic",
    tags: ["traditionalist"],
    scope: { years: ALL },
    weight: 10,
    wiki: `${w}Reincarnation`,
    note: "A death is a departure rather than an end, and a newborn may be greeted as somebody the household already knows.",
    sources: [],
  },
  {
    id: "general.simply-gone",
    label: "The dead are simply gone",
    short: "Death is an end",
    icon: "bones",
    clause: "believes the dead are simply gone",
    kind: "cosmic",
    tags: ["sceptical", "worldly"],
    scope: { years: ALL },
    weight: 5,
    lean: "heterodox",
    wiki: `${w}Annihilationism`,
    note: "Held quietly in most places and openly in few. Usually argued from what a body plainly does rather than from any doctrine.",
    sources: [],
  },
  /* --- political -------------------------------------------------------- */
  {
    id: "general.rule-by-descent",
    label: "Rule belongs to the line that has always held it",
    short: "Dynastic",
    icon: "crown",
    clause: "holds that rule belongs to the old line",
    kind: "political",
    tags: ["hierarchical", "traditionalist"],
    scope: { years: ALL },
    weight: 22,
    lean: "orthodox",
    wiki: `${w}Hereditary_monarchy`,
    note: "The claim rests on descent and nothing else, and a capable outsider is still an outsider.",
    sources: [],
  },
  {
    id: "general.sacred-king",
    label: "The ruler holds power from the powers themselves",
    short: "Sacred kingship",
    icon: "throne",
    clause: "holds that the ruler's power comes from the powers",
    kind: "political",
    tags: ["hierarchical", "devout", "traditionalist"],
    scope: { years: [-3500, 10001] },
    weight: 18,
    lean: "orthodox",
    wiki: `${w}Sacred_king`,
    note: "The harvest, the rain and the ruler's health are one question, which makes a bad season a political event.",
    sources: [],
  },
  {
    id: "general.council-of-elders",
    label: "Nothing is decided but in council",
    short: "Council-minded",
    icon: "elder",
    clause: "will settle nothing but in council",
    kind: "political",
    tags: ["communal", "traditionalist", "oral"],
    scope: { years: ALL },
    weight: 18,
    wiki: `${w}Council_of_elders`,
    note: "Authority sits with those old enough to remember the last time, and a decision is not made until the talking has exhausted itself.",
    sources: [],
  },
  {
    id: "general.generous-headman",
    label: "A leader is whoever gives the most away",
    short: "Big-man",
    icon: "offering-bowl",
    clause: "follows whoever gives the most away",
    kind: "political",
    tags: ["communal", "egalitarian", "oral"],
    scope: { years: ALL },
    weight: 12,
    wiki: `${w}Big_man_(anthropology)`,
    note: "Standing is built by feeding people and dissolves when the giving stops; it cannot be inherited and is exhausting to hold.",
    sources: [],
  },
  {
    id: "general.might-holds",
    label: "Rule belongs to whoever can hold it",
    short: "Might-is-right",
    icon: "sword",
    clause: "thinks rule belongs to whoever can hold it",
    kind: "political",
    tags: ["martial", "worldly", "sceptical"],
    scope: { years: ALL },
    weight: 10,
    wiki: `${w}Might_makes_right`,
    note: "Said more often by those near power than by those under it, and usually while a succession is unsettled.",
    sources: [],
  },
  {
    id: "general.ruler-forfeits",
    label: "A ruler who fails is owed nothing",
    short: "Conditional",
    icon: "skull",
    clause: "owes a failed ruler nothing",
    kind: "political",
    tags: ["reformist", "communal"],
    scope: { years: ALL },
    weight: 8,
    lean: "heterodox",
    wiki: `${w}Tyrannicide`,
    note: "Obedience was conditional on protection and on the rains; the old formula for removing a king is usually older than the king.",
    sources: [],
  },
  {
    id: "general.custom-above-ruler",
    label: "Custom binds the ruler too",
    short: "Custom-bound",
    icon: "standing-stone",
    clause: "holds custom binding on the ruler too",
    kind: "political",
    tags: ["traditionalist", "civic"],
    scope: { years: ALL },
    weight: 14,
    wiki: `${w}Rule_according_to_higher_law`,
    note: "There is a way things have always been done, and a ruler who departs from it is not exercising power but forfeiting it.",
    sources: [],
  },
  {
    id: "general.foreign-rule-is-none",
    label: "The stranger's rule is no rule",
    short: "Unreconciled",
    icon: "spear",
    clause: "grants the stranger's rule no legitimacy",
    kind: "political",
    tags: ["particularist", "martial", "restorationist"],
    scope: { years: ALL },
    weight: 10,
    wiki: `${w}Resistance_movement`,
    note: "Taxes are paid because soldiers are near, not because anything is owed, and the obligation ends the moment the soldiers do.",
    sources: [],
  },
  {
    id: "general.rank-is-ordained",
    label: "High and low are in the nature of things",
    short: "Rank-ordained",
    icon: "ladder",
    clause: "takes high and low for the nature of things",
    kind: "political",
    tags: ["hierarchical", "traditionalist", "devout"],
    scope: { years: ALL },
    weight: 20,
    lean: "orthodox",
    wiki: `${w}Social_stratification`,
    note: "Rank is a fact about the world like weather, and resenting it is as useful as resenting rain.",
    sources: [],
  },
  {
    id: "general.rank-is-made",
    label: "The high were not always high",
    short: "Rank-doubting",
    icon: "hammer",
    clause: "remembers that the high were not always high",
    kind: "political",
    tags: ["egalitarian", "reformist"],
    scope: { years: ALL },
    ranks: ["destitute", "labouring", "middling"],
    weight: 6,
    lean: "heterodox",
    wiki: `${w}Egalitarianism`,
    note: "Held that the present arrangement was made by somebody, within memory or just outside it, and can therefore be unmade.",
    sources: [],
  },
  /* --- ethical ---------------------------------------------------------- */
  {
    id: "general.hospitality",
    label: "The stranger at the door is sacred",
    short: "Hospitable",
    icon: "threshold",
    clause: "treats the stranger at the door as sacred",
    kind: "ethical",
    tags: ["traditionalist", "communal", "devout"],
    scope: { years: ALL },
    weight: 20,
    wiki: `${w}Hospitality`,
    note: "Food and a night's shelter are owed before the guest's business is asked, and the obligation runs both ways afterwards.",
    sources: [],
  },
  {
    id: "general.blood-for-blood",
    label: "Blood is owed for blood",
    short: "Feuding",
    icon: "wound",
    clause: "holds that blood is owed for blood",
    kind: "ethical",
    tags: ["particularist", "martial", "traditionalist"],
    scope: { years: ALL },
    weight: 14,
    wiki: `${w}Blood_feud`,
    note: "The debt belongs to the lineage rather than the man, may be settled in cattle, and does not expire because time has passed.",
    sources: [],
  },
  {
    id: "general.shame-before-neighbours",
    label: "What the neighbours say is what matters",
    short: "Shame-minded",
    icon: "crowd",
    clause: "minds what the neighbours will say",
    kind: "ethical",
    tags: ["communal", "traditionalist"],
    scope: { years: ALL },
    weight: 22,
    wiki: `${w}Shame_society`,
    note: "Conduct is regulated by who is watching rather than by conscience, which makes exposure worse than the act.",
    sources: [],
  },
  {
    id: "general.lineage-first",
    label: "The lineage before the self",
    short: "Lineage-first",
    icon: "house",
    clause: "puts the lineage before the self",
    kind: "ethical",
    tags: ["communal", "hierarchical", "traditionalist"],
    scope: { years: ALL },
    weight: 20,
    wiki: `${w}Kinship`,
    note: "A marriage, a debt or a quarrel is the family's affair; a person who decides such a thing alone has done something close to theft.",
    sources: [],
  },
  {
    id: "general.deference-to-age",
    label: "Age is owed deference",
    short: "Deferential",
    icon: "staff",
    clause: "defers to age in every room",
    kind: "ethical",
    tags: ["hierarchical", "traditionalist"],
    scope: { years: ALL },
    weight: 18,
    wiki: `${w}Gerontocracy`,
    note: "Seniority settles who speaks first and who is answered, in a room and in a household, regardless of who is right.",
    sources: [],
  },
  {
    id: "general.generosity-makes",
    label: "A person is made by what they give away",
    short: "Open-handed",
    icon: "offering-bowl",
    clause: "counts giving away the making of a person",
    kind: "ethical",
    tags: ["communal", "egalitarian"],
    scope: { years: ALL },
    weight: 14,
    wiki: `${w}Gift_economy`,
    note: "Holding on is the failure, not the poverty; a feast that ruins the host has still done what it was for.",
    sources: [],
  },
  {
    id: "general.keep-your-word",
    label: "A word given is a thing given",
    short: "Oath-keeping",
    icon: "knot",
    clause: "holds a word given to be a thing given",
    kind: "ethical",
    tags: ["traditionalist", "civic"],
    scope: { years: ALL },
    weight: 16,
    wiki: `${w}Oath`,
    note: "Held with an oath and witnesses because writing was unavailable or untrusted, and breaking it was a matter for the powers, not the courts.",
    sources: [],
  },
  {
    id: "general.purity",
    label: "Some things must be kept apart",
    short: "Purity-minded",
    icon: "veil",
    clause: "keeps the polluted things apart",
    kind: "ethical",
    tags: ["traditionalist", "devout", "particularist"],
    scope: { years: ALL },
    weight: 16,
    wiki: `${w}Ritual_purification`,
    note: "Food, birth, death and certain work carry contamination that has to be washed off or waited out before ordinary life resumes.",
    sources: [],
  },
  {
    id: "general.moderation",
    label: "Enough, and no more",
    short: "Temperate",
    icon: "scales",
    clause: "wants enough and no more",
    kind: "ethical",
    tags: ["ascetic", "quietist"],
    scope: { years: ALL },
    weight: 12,
    wiki: `${w}Temperance_(virtue)`,
    note: "Excess is held to bring its own punishment without anyone needing to administer it.",
    sources: [],
  },
  {
    id: "general.take-the-day",
    label: "Take what the day offers",
    short: "Present-minded",
    icon: "flower",
    clause: "takes what the day offers",
    kind: "ethical",
    tags: ["worldly", "individualist"],
    scope: { years: ALL },
    weight: 8,
    lean: "heterodox",
    wiki: `${w}Carpe_diem`,
    note: "Reasoned from how short and uncertain a life is, which is an argument the well-off make in verse and the poor make in practice.",
    sources: [],
  },
  {
    id: "general.work-is-worth",
    label: "A person is worth what they can do",
    short: "Merit-minded",
    icon: "hand",
    clause: "measures a person by what they can do",
    kind: "ethical",
    tags: ["egalitarian", "individualist"],
    scope: { years: ALL },
    weight: 12,
    wiki: `${w}Work_ethic`,
    note: "Skill and stamina are held to settle standing more honestly than birth does; common among people with skill and no birth.",
    sources: [],
  },
  /* --- economic --------------------------------------------------------- */
  {
    id: "general.land-of-the-lineage",
    label: "Land belongs to the lineage, not a person",
    short: "Lineage land",
    icon: "cairn",
    clause: "holds the land for the lineage, never to sell",
    kind: "economic",
    tags: ["communal", "agrarian", "traditionalist"],
    scope: { years: ALL },
    weight: 20,
    wiki: `${w}Customary_land`,
    note: "The living hold it for the dead and the unborn; selling it is not a bad bargain but a category error.",
    sources: [],
  },
  {
    id: "general.land-to-the-worker",
    label: "Land belongs to whoever works it",
    short: "Land to tillers",
    icon: "plough",
    clause: "thinks the land belongs to whoever works it",
    kind: "economic",
    tags: ["agrarian", "egalitarian"],
    scope: { years: ALL },
    ranks: ["destitute", "labouring", "middling"],
    weight: 14,
    wiki: `${w}Land_reform`,
    note: "A claim made by tenants and squatters in almost every agrarian society, and conceded in very few of them.",
    sources: [],
  },
  {
    id: "general.land-is-the-rulers",
    label: "All land is the ruler's to grant",
    short: "Crown land",
    icon: "sceptre",
    clause: "grants that all land is the ruler's to give",
    kind: "economic",
    tags: ["hierarchical", "traditionalist"],
    scope: { years: [-3000, 10001] },
    weight: 14,
    lean: "orthodox",
    wiki: `${w}Eminent_domain`,
    note: "What a household holds is a grant that can be withdrawn, which is the legal theory behind most pre-modern taxation.",
    sources: [],
  },
  {
    id: "general.commons",
    label: "The waste and the wood are everyone's",
    short: "Commoning",
    icon: "marsh",
    clause: "takes the wood and the waste by right",
    kind: "economic",
    tags: ["communal", "agrarian"],
    scope: { years: ALL },
    weight: 16,
    wiki: `${w}Commons`,
    note: "Pasture, fuel and fallen wood are taken by right rather than by permission, and fencing them is the theft.",
    sources: [],
  },
  {
    id: "general.wealth-is-favour",
    label: "Wealth is a sign of favour",
    short: "Wealth as favour",
    icon: "sun",
    clause: "reads wealth as a sign of favour",
    kind: "economic",
    tags: ["hierarchical", "devout", "worldly"],
    scope: { years: ALL },
    weight: 16,
    lean: "orthodox",
    wiki: `${w}Prosperity_theology`,
    note: "Read backwards as readily as forwards: the poor are held to have done something to deserve it.",
    sources: [],
  },
  {
    id: "general.wealth-is-danger",
    label: "Wealth endangers the soul",
    short: "Wealth-wary",
    icon: "needle",
    clause: "thinks wealth a danger to the soul",
    kind: "economic",
    tags: ["ascetic", "devout"],
    scope: { years: [-1000, 10001] },
    weight: 12,
    wiki: `${w}Vow_of_poverty`,
    note: "Not an argument for equality; an argument that the rich are in trouble and the poor are not, which suited everybody.",
    sources: [],
  },
  {
    id: "general.hoard-shames",
    label: "A hoard shames its holder",
    short: "Anti-hoarding",
    icon: "pot",
    clause: "is shamed by a hoard",
    kind: "economic",
    tags: ["communal", "egalitarian"],
    scope: { years: ALL },
    weight: 12,
    wiki: `${w}Reciprocity_(cultural_anthropology)`,
    note: "Surplus is held to be owed outward. In societies without storage this is insurance; where there is storage it becomes an accusation.",
    sources: [],
  },
  {
    id: "general.usury-is-theft",
    label: "Lending at interest is theft",
    short: "Anti-usury",
    icon: "coin",
    clause: "calls lending at interest theft",
    kind: "economic",
    tags: ["traditionalist", "devout", "communal"],
    scope: { years: [-2000, 10001] },
    weight: 14,
    wiki: `${w}Usury`,
    note: "Prohibited in most of the traditions the game covers, and practised throughout them by people the prohibition did not bind.",
    sources: [],
  },
  {
    id: "general.just-price",
    label: "A thing has a right price",
    short: "Just price",
    icon: "scales",
    clause: "holds that a thing has a right price",
    kind: "economic",
    tags: ["traditionalist", "civic", "mercantile"],
    scope: { years: [-1000, 10001] },
    weight: 14,
    wiki: `${w}Just_price`,
    note: "Set by custom and the assize rather than by what the buyer will bear; raising it in a famine is the standard trigger for a riot.",
    sources: [],
  },
  {
    id: "general.market-decides",
    label: "A thing is worth what it fetches",
    short: "Market-minded",
    icon: "boat",
    clause: "thinks a thing is worth what it fetches",
    kind: "economic",
    tags: ["mercantile", "worldly", "individualist"],
    scope: { years: [-500, 10001] },
    weight: 10,
    lean: "heterodox",
    wiki: `${w}Market_(economics)`,
    note: "A minority and often resented position before the eighteenth century, associated with merchants and with grain in a bad year.",
    sources: [],
  },
  {
    id: "general.debt-binds",
    label: "A debt holds the person, not the goods",
    short: "Debt-binding",
    icon: "rope",
    clause: "expects a debt to hold the debtor's body",
    kind: "economic",
    tags: ["hierarchical", "traditionalist"],
    scope: { years: ALL },
    weight: 12,
    wiki: `${w}Debt_bondage`,
    note: "Default is answered with the debtor's labour or their child's, which made lending safe and made a bad harvest permanent.",
    sources: [],
  },
  {
    id: "general.skill-is-property",
    label: "The trade is the craftsman's own",
    short: "Guild-minded",
    icon: "anvil",
    clause: "keeps the trade's knowledge to those sworn to it",
    kind: "economic",
    tags: ["mercantile", "particularist", "civic"],
    scope: { years: [-1000, 10001] },
    ranks: ["labouring", "middling"],
    weight: 12,
    wiki: `${w}Guild`,
    note: "Knowledge of the work is held collectively by those who have it and withheld from everyone else, by oath and by apprenticeship.",
    sources: [],
  },
];
