import type { Stance } from "../types";
const w = "https://en.wikipedia.org/wiki/";

export const indigenousAmericas: readonly Stance[] = [
  {
    id: "stance.animals-are-persons",
    label: "The animals are people of another kind",
    short: "Animal-persons",
    icon: "deer",
    clause: "treats the kill as a transaction with a person",
    kind: "cosmic",
    tags: ["traditionalist", "oral", "devout"],
    scope: { years: [-10000, 10001] },
    weight: 22,
    lean: "orthodox",
    wiki: `${w}Animism`,
    note: "Game gives itself to a hunter who has behaved correctly and withholds itself from one who has not, so the kill is a transaction.",
    sources: [],
  },
  {
    id: "stance.consensus-council",
    label: "Nothing binds without consent",
    short: "Consensual",
    icon: "crossroads",
    clause: "will not call it settled while a dissenter stands",
    kind: "political",
    tags: ["egalitarian", "communal", "oral", "civic"],
    scope: { years: [-2000, 10001] },
    weight: 18,
    wiki: `${w}Consensus_decision-making`,
    note: "A chief persuades and cannot command; a decision reached without a dissenter having been answered is not a decision.",
    sources: [],
  },
  {
    id: "stance.great-law",
    label: "The Great Law of Peace",
    short: "Great Law",
    icon: "tree",
    clause: "holds to the council's seats and the clan mothers' choice",
    kind: "political",
    tags: ["civic", "communal", "traditionalist"],
    scope: { years: [1450, 10001], bounds: [-80, 42, -73, 45] },
    weight: 12,
    wiki: `${w}Great_Law_of_Peace`,
    note: "Nations confederated under a council with named seats, the clan mothers choosing and able to remove those who hold them.",
    sources: [],
  },
  {
    id: "stance.give-away",
    label: "Standing comes from giving it away",
    short: "Give-away",
    icon: "offering-bowl",
    clause: "claims standing by distributing goods in public",
    kind: "economic",
    tags: ["communal", "egalitarian"],
    scope: { years: [-2000, 10001] },
    weight: 16,
    wiki: `${w}Potlatch`,
    note: "Rank is claimed by distributing goods in public, on a scale that can impoverish the host and is meant to.",
    sources: [],
  },
  {
    id: "stance.vision-seeking",
    label: "A person seeks their own vision",
    short: "Vision-seeking",
    icon: "dream",
    clause: "fasted alone for a name and a direction",
    kind: "temper",
    tags: ["mystical", "individualist", "ascetic"],
    scope: { years: [-2000, 10001] },
    weight: 14,
    wiki: `${w}Vision_quest`,
    note: "Fasting alone until something is given, which supplies a name, a protector and a direction for a life, and is not transferable.",
    sources: [],
  },
  {
    id: "stance.prophet-revival",
    label: "Prophetic revival",
    short: "Prophetic",
    icon: "comet",
    clause: "expects the world put back by refusing the traders' goods",
    kind: "cosmic",
    tags: ["millenarian", "restorationist", "devout"],
    scope: { years: [1750, 1920] },
    weight: 8,
    lean: "heterodox",
    wiki: `${w}Ghost_Dance`,
    note: "A messenger returns with instructions for putting the world back: refuse the traders' goods, perform the dance, and the dead come home.",
    sources: [],
  },
  {
    id: "stance.treaty-as-kinship",
    label: "A treaty makes relatives",
    short: "Treaty-kin",
    icon: "knot",
    clause: "takes an agreement for a relation to be renewed",
    kind: "political",
    tags: ["communal", "traditionalist", "oral"],
    scope: { years: [1600, 10001] },
    weight: 10,
    wiki: `${w}Covenant_Chain`,
    note: "An agreement creates an ongoing relation to be renewed with gifts, not a document that settles a matter once.",
    sources: [],
  },
];
