import type { Stance } from "../types";
const w = "https://en.wikipedia.org/wiki/";

export const innerEurasia: readonly Stance[] = [
  {
    id: "stance.sky-mandate",
    label: "Heaven's warrant",
    icon: "sky",
    clause: "reads success in the field as the sky's appointment",
    kind: "political",
    tags: ["hierarchical", "martial", "devout"],
    scope: { years: [-200, 1700] },
    weight: 16,
    lean: "orthodox",
    wiki: `${w}Tengrism`,
    note: "The sky appoints one ruler for the peoples of the felt tents, and success in the field is the evidence that it has.",
    sources: [],
  },
  {
    id: "stance.guest-right",
    label: "The guest is untouchable",
    short: "Guest-right",
    icon: "threshold",
    clause: "holds shelter owed to any traveller absolutely",
    kind: "ethical",
    tags: ["traditionalist", "communal"],
    scope: { years: [-1000, 10001] },
    weight: 18,
    wiki: `${w}Hospitality`,
    note: "In country where a night outside kills, shelter is owed absolutely, and a host who lets harm come to a guest is finished.",
    sources: [],
  },
  {
    id: "stance.steppe-shamanic",
    label: "Shamanic",
    icon: "drum",
    clause: "leaves the spirits to the specialist",
    kind: "cosmic",
    tags: ["mystical", "oral", "traditionalist"],
    scope: { years: [-2000, 10001] },
    weight: 16,
    wiki: `${w}Shamanism`,
    note: "Specialists travel to where the spirits are and come back with the answer, which is not a thing the ordinary person attempts.",
    sources: [],
  },
  {
    id: "stance.yasa",
    label: "The law of the ancestors' code",
    short: "The Yasa",
    icon: "tablet",
    clause: "holds the code binding on the ruling house too",
    kind: "political",
    tags: ["hierarchical", "traditionalist", "martial"],
    scope: { years: [1200, 1600] },
    weight: 8,
    wiki: `${w}Yassa`,
    note: "A code binding on the ruling house as well as the ranks, including a toleration of every religion that prayed for the khan.",
    sources: [],
  },
  {
    id: "stance.tibetan-tantric",
    label: "Tantric Buddhist",
    icon: "stupa",
    clause: "expects release in one lifetime under a teacher",
    kind: "cosmic",
    tags: ["mystical", "literate", "ascetic"],
    scope: { years: [800, 10001], bounds: [75, 26, 103, 40] },
    weight: 14,
    wiki: `${w}Tibetan_Buddhism`,
    note: "Release available in one lifetime through practices transmitted by a teacher, in a country organised around the monasteries that hold them.",
    sources: [],
  },
  {
    id: "stance.pastoral-mobility",
    label: "Land is for moving over",
    short: "Pastoral",
    icon: "horse",
    clause: "takes a fence for a theft and a misunderstanding",
    kind: "economic",
    tags: ["communal", "agrarian", "traditionalist"],
    scope: { years: [-2000, 10001] },
    weight: 18,
    wiki: `${w}Nomadic_pastoralism`,
    note: "Pasture is used in season and by right of custom, not held; a fence is both a theft and a misunderstanding of the country.",
    sources: [],
  },
];
