import type { Stance } from "../types";
const w = "https://en.wikipedia.org/wiki/";

export const mesoamerica: readonly Stance[] = [
  {
    id: "stance.debt-to-the-powers",
    label: "The world is kept going by payment",
    short: "Debt to the gods",
    icon: "sun",
    clause: "holds that the sun rises because it is paid for",
    kind: "cosmic",
    tags: ["devout", "traditionalist", "civic"],
    scope: { years: [-1200, 1600] },
    weight: 22,
    lean: "orthodox",
    wiki: `${w}Aztec_religion`,
    note: "The sun rises because it is paid for, in blood drawn from one's own body as much as from anyone else's, and the debt does not clear.",
    sources: [],
  },
  {
    id: "stance.day-sign",
    label: "The day a person is born decides them",
    short: "Day-sign",
    icon: "wheel",
    clause: "reads a character off the day of birth",
    kind: "cosmic",
    tags: ["traditionalist", "literate"],
    scope: { years: [-800, 10001] },
    weight: 18,
    wiki: `${w}Tonalpohualli`,
    note: "The calendar assigns a character and a fortune at birth, read by a specialist, and a bad sign can sometimes be delayed by naming later.",
    sources: [],
  },
  {
    id: "stance.ages-of-the-world",
    label: "This world has ended before",
    short: "World-ages",
    icon: "eclipse",
    clause: "expects this creation to end as four did before",
    kind: "cosmic",
    tags: ["millenarian", "traditionalist"],
    scope: { years: [-800, 1700] },
    weight: 14,
    wiki: `${w}Five_Suns`,
    note: "Four creations preceded this one and each was destroyed; the present is the fifth and is not expected to be the last.",
    sources: [],
  },
  {
    id: "stance.calpulli",
    label: "The ward holds the land",
    short: "Ward-held land",
    icon: "maize",
    clause: "holds a plot lent by the ward, never owned",
    kind: "economic",
    tags: ["communal", "agrarian", "civic"],
    scope: { years: [-200, 1650] },
    weight: 16,
    wiki: `${w}Calpulli`,
    note: "Plots are allotted by the ward to households that work them and revert when they do not; a household cannot sell what it was lent.",
    sources: [],
  },
  {
    id: "stance.flowery-war-ethic",
    label: "Capture rather than kill",
    short: "Capture-war",
    icon: "net",
    clause: "counts rank in men taken alive",
    kind: "ethical",
    tags: ["martial", "hierarchical", "devout"],
    scope: { years: [1300, 1550] },
    ranks: ["middling", "gentry", "elite"],
    weight: 10,
    wiki: `${w}Flower_war`,
    note: "Rank in war is counted in men taken alive, which shaped the weapons, the tactics, and the catastrophe of 1519.",
    sources: [],
  },
  {
    id: "stance.costumbre",
    label: "The old practice kept under the new",
    short: "Costumbre",
    icon: "mask",
    clause: "gives the saints the festivals and the mountains the offerings",
    kind: "temper",
    tags: ["traditionalist", "communal", "oral"],
    scope: { years: [1550, 10001] },
    weight: 16,
    wiki: `${w}Folk_Catholicism`,
    note: "The saints given the festivals and the mountains given the offerings, in an arrangement the parish priest either tolerates or does not.",
    sources: [],
  },
];
