import type { Stance } from "../types";

const w = "https://en.wikipedia.org/wiki/";

/**
 * Positions that spread past the culture that first stated them. Filed here
 * rather than under a region so that a Bengali social democrat or a Peruvian
 * anarchist is not recorded as a European; the dates are when each became
 * available somewhere a player is likely to be standing, not when it was
 * invented.
 */
export const modern: readonly Stance[] = [
  {
    id: "stance.classical-liberal",
    label: "Classical liberal",
    short: "Liberal",
    icon: "key",
    clause: "wants the state kept small and the tariff off",
    kind: "political",
    tags: ["individualist", "reformist", "mercantile", "universalist"],
    scope: { years: [1770, 10001] },
    ranks: ["middling", "gentry", "elite"],
    weight: 12,
    wiki: `${w}Classical_liberalism`,
    note: "Government exists to secure persons and property and should do little else; the career open to talents, and the tariff taken off.",
    sources: [],
  },
  {
    id: "stance.abolitionist",
    label: "Abolitionist",
    icon: "rope",
    clause: "holds that slavery cannot be mended, only ended",
    kind: "ethical",
    tags: ["universalist", "reformist", "devout"],
    scope: { years: [1780, 1900] },
    weight: 6,
    lean: "heterodox",
    wiki: `${w}Abolitionism`,
    note: "Slavery is not a bad institution but no institution at all, and cannot be mended by regulating it. A minority position for most of its life.",
    sources: [],
  },
  {
    id: "stance.utilitarian",
    label: "Utilitarian",
    icon: "scales",
    clause: "counts everyone's happiness as one",
    kind: "ethical",
    tags: ["rationalist", "reformist", "universalist", "literate"],
    scope: { years: [1790, 10001] },
    ranks: ["middling", "gentry", "elite"],
    weight: 7,
    wiki: `${w}Utilitarianism`,
    note: "The right act is whichever produces the most happiness counted head by head, with nobody's counting for more than anybody's.",
    sources: [],
  },
  {
    id: "stance.romantic-nationalist",
    label: "Romantic nationalist",
    short: "Nationalist",
    icon: "flute",
    clause: "thinks a people with its own songs deserves a state",
    kind: "political",
    tags: ["particularist", "restorationist", "civic"],
    scope: { years: [1800, 10001] },
    weight: 12,
    wiki: `${w}Romantic_nationalism`,
    note: "A people with its own language and songs is entitled to its own state, and the borders drawn by dynasties are an insult to it.",
    sources: [],
  },
  {
    id: "stance.utopian-socialist",
    label: "Utopian socialist",
    short: "Utopian",
    icon: "granary",
    clause: "would build the new order and let people see it work",
    kind: "economic",
    tags: ["communal", "egalitarian", "reformist"],
    scope: { years: [1800, 1900] },
    weight: 4,
    lean: "heterodox",
    wiki: `${w}Utopian_socialism`,
    note: "The new arrangement is to be demonstrated by building one and letting people see it work, rather than by taking power first.",
    sources: [],
  },
  {
    id: "stance.positivist",
    label: "Positivist",
    icon: "ladder",
    clause: "expects society to yield to the same method as nature",
    kind: "cosmic",
    tags: ["rationalist", "empirical", "literate", "universalist"],
    scope: { years: [1830, 1950] },
    ranks: ["middling", "gentry", "elite"],
    weight: 6,
    wiki: `${w}Positivism`,
    note: "Knowledge passes through theological and metaphysical stages to the scientific, and society itself can be studied and administered that way.",
    sources: [],
  },
  {
    id: "stance.marxist",
    label: "Marxist",
    icon: "hammer",
    clause: "reads history as the struggle between classes",
    kind: "economic",
    tags: ["revolutionary", "egalitarian", "rationalist", "literate"],
    scope: { years: [1860, 10001] },
    weight: 8,
    lean: "heterodox",
    wiki: `${w}Marxism`,
    note: "History is the history of class struggle, the present arrangement produces the class that will end it, and the ending is not a matter of persuasion.",
    sources: [],
  },
  {
    id: "stance.anarchist",
    label: "Anarchist",
    icon: "gate",
    clause: "holds the state itself to be the problem",
    kind: "political",
    tags: ["revolutionary", "egalitarian", "communal", "individualist"],
    scope: { years: [1860, 10001] },
    ranks: ["destitute", "labouring", "middling"],
    weight: 5,
    lean: "heterodox",
    wiki: `${w}Anarchism`,
    note: "The state is the problem and not the instrument, so a workers' state would be the same boot on the same neck.",
    sources: [],
  },
  {
    id: "stance.syndicalist",
    label: "Syndicalist",
    icon: "net",
    clause: "looks to the union and the general strike",
    kind: "economic",
    tags: ["revolutionary", "communal", "egalitarian"],
    scope: { years: [1880, 1970] },
    ranks: ["destitute", "labouring"],
    weight: 5,
    lean: "heterodox",
    wiki: `${w}Syndicalism`,
    note: "The union is the unit of the future society, and the general strike is how it arrives — not a parliament and not a party.",
    sources: [],
  },
  {
    id: "stance.social-democrat",
    label: "Social democrat",
    icon: "scales",
    clause: "wants the same ends reached by the ballot",
    kind: "political",
    tags: ["egalitarian", "reformist", "civic"],
    scope: { years: [1875, 10001] },
    weight: 12,
    wiki: `${w}Social_democracy`,
    note: "The same destination by the ballot and the inspectorate, on the argument that a revolution costs more than it delivers.",
    sources: [],
  },
  {
    id: "stance.fabian",
    label: "Fabian",
    icon: "needle",
    clause: "prefers to change things by drafting the report",
    kind: "political",
    tags: ["reformist", "rationalist", "literate", "egalitarian"],
    scope: { years: [1884, 1960] },
    ranks: ["middling", "gentry"],
    weight: 3,
    wiki: `${w}Fabian_Society`,
    note: "Change by permeation: draft the report, brief the minister, and let the measure pass without anyone noticing whose it was.",
    sources: [],
  },
  {
    id: "stance.suffragist",
    label: "Suffragist",
    icon: "hand",
    clause: "wants the vote extended to women",
    kind: "political",
    tags: ["egalitarian", "reformist", "civic"],
    scope: { years: [1860, 1960] },
    weight: 5,
    lean: "heterodox",
    wiki: `${w}Women%27s_suffrage`,
    note: "The vote for women, argued from the same principles already conceded for men, which is what made it so hard to answer.",
    sources: [],
  },
  {
    id: "stance.feminist",
    label: "Feminist",
    icon: "mother-and-child",
    clause: "holds the order between the sexes to be made, not given",
    kind: "ethical",
    tags: ["egalitarian", "reformist", "universalist"],
    scope: { years: [1890, 10001] },
    weight: 8,
    wiki: `${w}Feminism`,
    note: "The arrangement between the sexes is made rather than natural, and what is made can be altered.",
    sources: [],
  },
  {
    id: "stance.marxist-leninist",
    label: "Marxist-Leninist",
    icon: "star",
    clause: "trusts a disciplined party to take the state",
    kind: "political",
    tags: ["revolutionary", "egalitarian", "hierarchical", "literate"],
    scope: { years: [1917, 10001] },
    weight: 8,
    lean: "heterodox",
    wiki: `${w}Marxism%E2%80%93Leninism`,
    note: "A disciplined party takes the state and holds it on the class's behalf, on the argument that the class left alone reaches only trade unionism.",
    sources: [],
  },
  {
    id: "stance.anti-colonial-nationalist",
    label: "Anti-colonial nationalist",
    short: "Anti-colonial",
    icon: "spear",
    clause: "wants the foreigners out before anything else",
    kind: "political",
    tags: ["revolutionary", "particularist", "civic"],
    scope: { years: [1890, 10001] },
    weight: 12,
    wiki: `${w}Decolonization`,
    note: "Independence first and the arrangement of society afterwards, which held together people who agreed on nothing else.",
    sources: [],
  },
  {
    id: "stance.pan-africanist",
    label: "Pan-Africanist",
    icon: "drum",
    clause: "takes the continent and its diaspora for one people",
    kind: "political",
    tags: ["universalist", "revolutionary", "civic"],
    scope: { years: [1900, 10001] },
    weight: 6,
    wiki: `${w}Pan-Africanism`,
    note: "The continent and its diaspora as one political subject, on the argument that separate independences can be picked off separately.",
    sources: [],
  },
  {
    id: "stance.gandhian",
    label: "Gandhian",
    icon: "loom",
    clause: "refuses without violence and spins the household's cloth",
    kind: "ethical",
    tags: ["ascetic", "communal", "agrarian", "universalist"],
    scope: { years: [1915, 10001] },
    weight: 6,
    wiki: `${w}Gandhism`,
    note: "Refusal without violence, self-sufficiency in the village, and the claim that the means chosen become the society arrived at.",
    sources: [],
  },
  {
    id: "stance.fascist",
    label: "Fascist",
    icon: "tower",
    clause: "wants the nation made one body with one will",
    kind: "political",
    tags: ["hierarchical", "martial", "particularist", "revolutionary"],
    scope: { years: [1919, 1950] },
    weight: 6,
    wiki: `${w}Fascism`,
    note: "The nation as a single body with one will, the parties abolished, and violence treated as evidence of seriousness rather than of failure.",
    sources: [],
  },
  {
    id: "stance.technocrat",
    label: "Technocrat",
    icon: "kiln",
    clause: "would leave the questions to the competent",
    kind: "economic",
    tags: ["rationalist", "empirical", "hierarchical"],
    scope: { years: [1920, 10001] },
    ranks: ["middling", "gentry", "elite"],
    weight: 8,
    wiki: `${w}Technocracy`,
    note: "The questions are technical and the technically competent should settle them, which spares everyone the arguing.",
    sources: [],
  },
  {
    id: "stance.developmentalist",
    label: "Developmentalist",
    icon: "anvil",
    clause: "expects the state to build what the market will not",
    kind: "economic",
    tags: ["rationalist", "civic", "reformist"],
    scope: { years: [1945, 10001] },
    weight: 10,
    wiki: `${w}Developmental_state`,
    note: "The state builds the industry the market will not, protects it while it is weak, and is judged on the growth rate.",
    sources: [],
  },
  {
    id: "stance.existentialist",
    label: "Existentialist",
    icon: "shadow",
    clause: "allows no excuse for what a person has chosen",
    kind: "cosmic",
    tags: ["individualist", "sceptical", "literate"],
    scope: { years: [1930, 2000] },
    ranks: ["middling", "gentry", "elite"],
    weight: 4,
    lean: "heterodox",
    wiki: `${w}Existentialism`,
    note: "No given purpose and no excuse; a person is what they have done and is answerable for having chosen it.",
    sources: [],
  },
  {
    id: "stance.liberation-theologian",
    label: "Liberation theologian",
    short: "Liberationist",
    icon: "cross",
    clause: "reads the gospel as taking the poor's side",
    kind: "ethical",
    tags: ["devout", "egalitarian", "revolutionary", "communal"],
    scope: { years: [1960, 10001] },
    weight: 5,
    lean: "heterodox",
    wiki: `${w}Liberation_theology`,
    note: "The gospel read as taking the side of the poor in an actual conflict, which put its clergy at odds with their own hierarchy.",
    sources: [],
  },
  {
    id: "stance.neoliberal",
    label: "Neoliberal",
    icon: "coin",
    clause: "trusts the market with most decisions",
    kind: "economic",
    tags: ["mercantile", "individualist", "rationalist", "reformist"],
    scope: { years: [1975, 10001] },
    weight: 10,
    wiki: `${w}Neoliberalism`,
    note: "The market as the best available instrument for most decisions, and the state's job to build the markets where none exist.",
    sources: [],
  },
  {
    id: "stance.environmentalist",
    label: "Environmentalist",
    icon: "tree",
    clause: "thinks the damage is cumulative and unpaid for",
    kind: "cosmic",
    tags: ["universalist", "reformist", "agrarian"],
    scope: { years: [1960, 10001] },
    weight: 10,
    wiki: `${w}Environmentalism`,
    note: "The damage is cumulative, the accounting has been leaving it out, and the bill falls due on people who did not incur it.",
    sources: [],
  },
  {
    id: "stance.revivalist",
    label: "Religious revivalist",
    short: "Revivalist",
    icon: "fire",
    clause: "wants the faith felt again rather than merely kept",
    kind: "temper",
    tags: ["devout", "millenarian", "restorationist"],
    scope: { years: [1730, 10001] },
    weight: 12,
    wiki: `${w}Christian_revival`,
    note: "The tradition has gone cold and must be felt again rather than merely kept; the meeting rather than the parish, and conversion rather than upbringing.",
    sources: [],
  },
  {
    id: "stance.fundamentalist",
    label: "Fundamentalist",
    icon: "book",
    clause: "holds the tradition as a list that cannot be negotiated",
    kind: "temper",
    tags: ["devout", "traditionalist", "literate", "restorationist"],
    scope: { years: [1900, 10001] },
    weight: 8,
    wiki: `${w}Fundamentalism`,
    note: "A modern position rather than an old one: the tradition restated as a list of non-negotiable propositions, because modernity had put them in question.",
    sources: [],
  },
  {
    id: "stance.secular-nationalist",
    label: "Secular nationalist",
    short: "Secularist",
    icon: "pillar",
    clause: "puts the nation where the confession used to be",
    kind: "political",
    tags: ["civic", "rationalist", "particularist", "reformist"],
    scope: { years: [1900, 10001] },
    weight: 9,
    wiki: `${w}Secular_state`,
    note: "The nation rather than the confession as the thing everybody has in common, promoted hard by states with more than one confession in them.",
    sources: [],
  },
  {
    id: "stance.consumer-individualist",
    label: "Consumer individualist",
    short: "Consumerist",
    icon: "mirror",
    clause: "assembles a life out of what can be bought",
    kind: "ethical",
    tags: ["individualist", "worldly", "mercantile"],
    scope: { years: [1950, 10001] },
    weight: 14,
    lean: "orthodox",
    wiki: `${w}Consumerism`,
    note: "A life is assembled from what a person chooses to buy and to be, and the choosing is held to be the freedom.",
    sources: [],
  },
  {
    id: "stance.welfare-consensus",
    label: "Welfare-state consensus",
    short: "Welfarist",
    icon: "cradle",
    clause: "expects the nation to insure against a life's accidents",
    kind: "economic",
    tags: ["civic", "egalitarian", "reformist"],
    scope: { years: [1945, 10001] },
    weight: 12,
    lean: "orthodox",
    wiki: `${w}Welfare_state`,
    note: "Insurance against the accidents of a life, organised at the scale of the nation because no household can carry them.",
    sources: [],
  },
  {
    id: "stance.scientific-materialist",
    label: "Scientific materialist",
    short: "Materialist",
    icon: "ore",
    clause: "allows nothing that matter cannot account for",
    kind: "cosmic",
    tags: ["rationalist", "empirical", "sceptical", "literate"],
    scope: { years: [1860, 10001] },
    weight: 10,
    wiki: `${w}Materialism`,
    note: "Matter and its motions account for everything including the mind, and what cannot be shown that way is not yet knowledge.",
    sources: [],
  },
];
