import type { Stance } from "../types";

const w = "https://en.wikipedia.org/wiki/";

export const southAsia: readonly Stance[] = [
  {
    id: "stance.dharma-of-station",
    label: "The duty of one's own station",
    short: "Svadharma",
    icon: "wheel",
    clause: "keeps the duty proper to a birth",
    kind: "ethical",
    tags: ["hierarchical", "traditionalist", "devout"],
    scope: { years: [-800, 10001] },
    weight: 22,
    lean: "orthodox",
    wiki: `${w}Dharma`,
    note: "Better one's own duty done badly than another's done well; the obligation is particular to the birth rather than the same for everyone.",
    sources: [],
  },
  {
    id: "stance.karma-rebirth",
    label: "Act and consequence across lives",
    short: "Karmic",
    icon: "seed",
    clause: "reads this life as payment for a former one",
    kind: "cosmic",
    tags: ["traditionalist", "devout"],
    scope: { years: [-800, 10001] },
    weight: 24,
    lean: "orthodox",
    wiki: `${w}Karma`,
    note: "The present life is being paid for out of a former one, which explains a misfortune without blaming anyone now living.",
    sources: [],
  },
  {
    id: "stance.renunciant",
    label: "Renunciant",
    icon: "staff",
    clause: "has left the household, the caste and the name",
    kind: "ethical",
    tags: ["ascetic", "mystical", "individualist"],
    scope: { years: [-700, 10001] },
    weight: 8,
    wiki: `${w}Sannyasa`,
    note: "Leaves the household, the caste obligations and the name, on the argument that the round of rebirth is not escaped from inside them.",
    sources: [],
  },
  {
    id: "stance.advaita",
    label: "Advaita",
    icon: "mirror",
    clause: "holds the self and the ground of things to be one",
    kind: "cosmic",
    tags: ["mystical", "rationalist", "literate"],
    scope: { years: [700, 10001] },
    ranks: ["middling", "gentry", "elite"],
    weight: 7,
    wiki: `${w}Advaita_Vedanta`,
    note: "The self and the ground of everything are not two things; the appearance of separateness is the error to be undone.",
    sources: [],
  },
  {
    id: "stance.bhakti",
    label: "Bhakti devotionalist",
    short: "Bhakti",
    icon: "flute",
    clause: "loves the god directly and in the local tongue",
    kind: "temper",
    tags: ["devout", "egalitarian", "mystical", "oral"],
    scope: { years: [600, 10001] },
    weight: 16,
    wiki: `${w}Bhakti_movement`,
    note: "Love of the god directly, in the local language and without a priest, which is why so much of its poetry is by people of low caste and by women.",
    sources: [],
  },
  {
    id: "stance.carvaka",
    label: "Cārvāka materialist",
    short: "Cārvāka",
    icon: "eye",
    clause: "allows only what the senses report",
    kind: "cosmic",
    tags: ["sceptical", "worldly", "empirical"],
    scope: { years: [-600, 1400] },
    weight: 2,
    lean: "heterodox",
    wiki: `${w}Charvaka`,
    note: "Only what is perceived exists; there is no next life and the rites are a livelihood for those who perform them. Known mostly from its opponents.",
    sources: [],
  },
  {
    id: "stance.ahimsa",
    label: "Non-harm",
    icon: "lotus",
    clause: "will not injure a living thing",
    kind: "ethical",
    tags: ["ascetic", "universalist", "devout"],
    scope: { years: [-600, 10001] },
    weight: 12,
    wiki: `${w}Ahimsa`,
    note: "Not injuring any living thing, held strictly enough by some to govern what may be eaten, farmed, and walked on.",
    sources: [],
  },
  {
    id: "stance.theravada",
    label: "Theravāda",
    icon: "beads",
    clause: "works at the ending of suffering",
    kind: "cosmic",
    tags: ["ascetic", "literate", "quietist"],
    scope: { years: [-250, 10001] },
    weight: 12,
    wiki: `${w}Theravada`,
    note: "Suffering, its cause and its ending, worked at by the monastic order while the laity make merit by supporting it.",
    sources: [],
  },
  {
    id: "stance.tantric",
    label: "Tantric",
    icon: "spiral",
    clause: "seeks power by what the orthodox call polluting",
    kind: "cosmic",
    tags: ["mystical", "particularist"],
    scope: { years: [500, 10001] },
    weight: 6,
    lean: "heterodox",
    wiki: `${w}Tantra`,
    note: "Power reached through practices the orthodox find polluting, on the argument that what binds an ordinary person can release an initiated one.",
    sources: [],
  },
  {
    id: "stance.sikh-egalitarian",
    label: "Sikh",
    icon: "sword",
    clause: "eats with every caste and bears arms for the weak",
    kind: "ethical",
    tags: ["egalitarian", "devout", "martial", "communal"],
    scope: { years: [1500, 10001], bounds: [68, 27, 80, 35] },
    weight: 10,
    wiki: `${w}Sikhism`,
    note: "One god, no caste at the shared kitchen, and after the seventeenth century an obligation to bear arms for those who cannot.",
    sources: [],
  },
  {
    id: "stance.sufi-syncretic",
    label: "Sufi",
    icon: "flute",
    clause: "walks the path under a master at the shrine",
    kind: "temper",
    tags: ["mystical", "universalist", "devout"],
    scope: { years: [1000, 10001] },
    weight: 12,
    wiki: `${w}Sufism`,
    note: "The shrine of a saint attended by people of every community, which is what made it useful and what made the reformers object to it.",
    sources: [],
  },
  {
    id: "stance.brahmo",
    label: "Brahmo reformer",
    icon: "lamp",
    clause: "wants one god without images and the old abuses gone",
    kind: "temper",
    tags: ["reformist", "rationalist", "literate", "universalist"],
    scope: { years: [1828, 1940], bounds: [85, 20, 93, 27] },
    ranks: ["middling", "gentry", "elite"],
    weight: 5,
    wiki: `${w}Brahmo_Samaj`,
    note: "One god without images, the old texts read critically, and a campaign against caste, child marriage and widow-burning.",
    sources: [],
  },
  {
    id: "stance.arya-samaj",
    label: "Arya Samaj revivalist",
    short: "Arya Samaj",
    icon: "fire",
    clause: "wants the Vedas and nothing written after them",
    kind: "temper",
    tags: ["restorationist", "reformist", "literate"],
    scope: { years: [1875, 10001] },
    weight: 6,
    wiki: `${w}Arya_Samaj`,
    note: "Back to the Vedas and nothing after them: against images, against caste by birth, and against the missionaries on their own ground.",
    sources: [],
  },
  {
    id: "stance.ambedkarite",
    label: "Anti-caste radical",
    short: "Anti-caste",
    icon: "ladder",
    clause: "takes caste for the tradition itself, not a distortion",
    kind: "political",
    tags: ["egalitarian", "revolutionary", "civic", "literate"],
    scope: { years: [1920, 10001] },
    ranks: ["destitute", "labouring", "middling"],
    weight: 6,
    wiki: `${w}Dalit_Buddhist_movement`,
    note: "Caste is not a distortion of the tradition but the tradition, so the remedy is to leave it and to write the protections into law.",
    sources: [],
  },
  {
    id: "stance.zamindar-order",
    label: "The order of the revenue settlement",
    short: "Zamindari",
    icon: "granary",
    clause: "defends the right to collect as ancient property",
    kind: "economic",
    tags: ["hierarchical", "agrarian", "traditionalist"],
    scope: { years: [1600, 1950] },
    ranks: ["gentry", "elite"],
    weight: 8,
    wiki: `${w}Zamindar`,
    note: "The right to collect from a district, held as property and defended as ancient, though most of the settlements were recent.",
    sources: [],
  },
];
