import type { Stance } from "../types";
const w = "https://en.wikipedia.org/wiki/";

export const southeastAsia: readonly Stance[] = [
  {
    id: "stance.merit-making",
    label: "Merit-making",
    icon: "offering-bowl",
    clause: "makes merit publicly and often",
    kind: "ethical",
    tags: ["devout", "communal", "hierarchical"],
    scope: { years: [200, 10001] },
    weight: 22,
    lean: "orthodox",
    wiki: `${w}Merit_(Buddhism)`,
    note: "Feeding the monks, gilding the stupa and sponsoring a son's ordination all move the account forward, and are done publicly.",
    sources: [],
  },
  {
    id: "stance.galactic-polity",
    label: "The centre and its reflections",
    short: "Mandala order",
    icon: "lotus",
    clause: "expects power to fade with distance rather than stop",
    kind: "political",
    tags: ["hierarchical", "devout", "traditionalist"],
    scope: { years: [400, 1900] },
    weight: 14,
    lean: "orthodox",
    wiki: `${w}Mandala_(political_model)`,
    note: "Power radiates from a capital and fades with distance rather than stopping at a border, so a village may owe two kings at once.",
    sources: [],
  },
  {
    id: "stance.potency",
    label: "Power is a substance a person accumulates",
    short: "Potency",
    icon: "lamp",
    clause: "reads authority off a person's visible calm",
    kind: "cosmic",
    tags: ["hierarchical", "mystical", "traditionalist"],
    scope: { years: [-200, 10001] },
    weight: 16,
    wiki: `${w}Semangat`,
    note: "Authority is read off a person's visible calm and good fortune, which are taken as evidence of a potency that can be gathered and lost.",
    sources: [],
  },
  {
    id: "stance.spirits-of-place",
    label: "The owners of the place",
    short: "Place-owners",
    icon: "shrine",
    clause: "asks the ground's owner before cutting or building",
    kind: "cosmic",
    tags: ["traditionalist", "oral", "agrarian"],
    scope: { years: [-2000, 10001] },
    weight: 20,
    wiki: `${w}Nat_(spirit)`,
    note: "The spirit that held the ground before the house did is housed at the corner of it and consulted before anything is built or cut.",
    sources: [],
  },
  {
    id: "stance.adat",
    label: "Adat",
    icon: "cloth",
    clause: "keeps the village's customary law alongside the written one",
    kind: "ethical",
    tags: ["traditionalist", "communal", "oral"],
    scope: { years: [-500, 10001], bounds: [95, -11, 141, 8] },
    weight: 18,
    wiki: `${w}Adat`,
    note: "Customary law of the village, held to run alongside the written law of whatever religion or state has arrived since.",
    sources: [],
  },
  {
    id: "stance.santri-reformist",
    label: "Reformist Muslim",
    icon: "book",
    clause: "is impatient with the older syncretic practice",
    kind: "temper",
    tags: ["reformist", "literate", "devout"],
    scope: { years: [1900, 10001], bounds: [95, -11, 127, 8] },
    weight: 8,
    wiki: `${w}Santri`,
    note: "Schooled, scripturally strict, and impatient with the older syncretic practice, which it regards as the village's rather than the faith's.",
    sources: [],
  },
];
