import type { Stance } from "../types";

const ALL: [number, number] = [-1000000, 10001];
const w = "https://en.wikipedia.org/wiki/";

/**
 * How a person holds whatever else they believe. These cross every era and
 * culture the game covers, because the range of temperaments is not what
 * changes between one century and another; the things available to be
 * temperate or zealous about are.
 */
export const tempers: readonly Stance[] = [
  {
    id: "temper.devout",
    label: "Devout",
    icon: "altar",
    clause: "keeps the observances exactly",
    kind: "temper",
    tags: ["devout", "traditionalist"],
    scope: { years: ALL },
    weight: 14,
    lean: "orthodox",
    wiki: `${w}Piety`,
    note: "Keeps the observances fully and expects others to, and reads a lapse in a neighbour as a thing that will be paid for by everyone.",
    sources: [],
  },
  {
    id: "temper.observant",
    label: "Conventionally observant",
    short: "Observant",
    icon: "bell",
    clause: "keeps the ordinary observances",
    kind: "temper",
    tags: ["traditionalist"],
    scope: { years: ALL },
    weight: 30,
    wiki: `${w}Ritual`,
    note: "Does what the calendar and the household require, at the usual times, without much thought about it either way.",
    sources: [],
  },
  {
    id: "temper.formalist",
    label: "Keeps the forms, believes little",
    short: "Outwardly pious",
    icon: "mask",
    clause: "keeps the forms and believes little",
    kind: "temper",
    tags: ["sceptical", "worldly"],
    scope: { years: ALL },
    weight: 8,
    lean: "heterodox",
    wiki: `${w}Religious_conformity`,
    note: "Attends, gives, and stands in the right place, while privately holding that none of it does anything. Conformity was cheap and dissent was not.",
    sources: [],
  },
  {
    id: "temper.mystic",
    label: "Mystic",
    icon: "spiral",
    clause: "seeks the divine without a priest",
    kind: "temper",
    tags: ["mystical", "devout", "ascetic"],
    scope: { years: ALL },
    weight: 4,
    lean: "heterodox",
    wiki: `${w}Mysticism`,
    note: "Seeks contact with the powers directly rather than through whoever is appointed to arrange it, which is why the appointed rarely welcome it.",
    sources: [],
  },
  {
    id: "temper.zealot",
    label: "Zealot",
    icon: "fire",
    clause: "will not suffer a lax neighbour",
    kind: "temper",
    tags: ["devout", "martial", "particularist"],
    scope: { years: ALL },
    weight: 3,
    wiki: `${w}Zealotry`,
    note: "Holds that the observance is not a private matter and that a community which tolerates laxity has already agreed to its own punishment.",
    sources: [],
  },
  {
    id: "temper.sceptic",
    label: "Sceptic",
    icon: "eye",
    clause: "doubts what cannot be shown",
    kind: "temper",
    tags: ["sceptical", "rationalist"],
    scope: { years: ALL },
    weight: 5,
    lean: "heterodox",
    wiki: `${w}Philosophical_skepticism`,
    note: "Suspends judgement on what cannot be shown, and is usually careful about who hears them say so.",
    sources: [],
  },
  {
    id: "temper.latitudinarian",
    label: "Accommodating",
    icon: "cloud",
    clause: "thinks the disputed points not worth quarrelling over",
    kind: "temper",
    tags: ["universalist", "worldly"],
    scope: { years: ALL },
    weight: 6,
    wiki: `${w}Religious_toleration`,
    note: "Holds that the disputed points are not worth the trouble they cause, and that decent conduct settles more than doctrine does.",
    sources: [],
  },
  {
    id: "temper.syncretist",
    label: "Syncretist",
    icon: "crossroads",
    clause: "honours whatever power seems to answer",
    kind: "temper",
    tags: ["universalist", "worldly"],
    scope: { years: ALL },
    weight: 8,
    wiki: `${w}Syncretism`,
    note: "Takes what works from whatever is to hand, and sees no contradiction in honouring a power the incoming clergy do not recognise.",
    sources: [],
  },
  {
    id: "temper.convert",
    label: "Recent convert",
    icon: "threshold",
    clause: "came to the faith lately and holds it hard",
    kind: "temper",
    tags: ["devout", "reformist"],
    scope: { years: ALL },
    weight: 4,
    wiki: `${w}Religious_conversion`,
    note: "Came to it lately and holds it harder than those raised in it, with the old practice still close enough to be argued against.",
    sources: [],
  },
  {
    id: "temper.indifferent",
    label: "Indifferent",
    icon: "shadow",
    clause: "has never given the question much thought",
    kind: "temper",
    tags: ["worldly", "quietist"],
    scope: { years: ALL },
    weight: 10,
    wiki: `${w}Apatheism`,
    note: "Has not thought about it and does not intend to. The day is long and the question does not come up.",
    sources: [],
  },
  {
    id: "temper.ascetic",
    label: "Ascetic",
    icon: "thread",
    clause: "gives up what others take",
    kind: "temper",
    tags: ["ascetic", "devout"],
    scope: { years: ALL },
    weight: 3,
    lean: "heterodox",
    wiki: `${w}Asceticism`,
    note: "Gives up what others take, on the understanding that the giving up is itself the work rather than a preparation for it.",
    sources: [],
  },
  {
    id: "temper.literalist",
    label: "Literalist",
    icon: "tablet",
    clause: "takes the sacred text exactly as written",
    kind: "temper",
    tags: ["traditionalist", "literate", "devout"],
    scope: { years: [-1500, 10001] },
    weight: 5,
    wiki: `${w}Religious_text`,
    note: "Takes the received text to mean exactly what it says, and treats the commentators' softenings as evasions.",
    sources: [],
  },
  {
    id: "temper.allegorist",
    label: "Allegorist",
    icon: "veil",
    clause: "reads the awkward passages as figures",
    kind: "temper",
    tags: ["literate", "mystical", "rationalist"],
    scope: { years: [-400, 10001] },
    ranks: ["middling", "gentry", "elite"],
    weight: 4,
    wiki: `${w}Allegory`,
    note: "Reads the awkward passages as figures for something else, which keeps the text defensible and annoys the literalists.",
    sources: [],
  },
  {
    id: "temper.anticlerical",
    label: "Anticlerical",
    icon: "knife",
    clause: "doubts the clergy rather than the powers",
    kind: "temper",
    tags: ["sceptical", "reformist"],
    scope: { years: [-500, 10001] },
    weight: 5,
    lean: "heterodox",
    wiki: `${w}Anti-clericalism`,
    note: "Doubts the specialists rather than the powers, and can generally name what the local one owns and how he came by it.",
    sources: [],
  },
  {
    id: "temper.dreamer",
    label: "Dream-guided",
    icon: "dream",
    clause: "acts on what comes in sleep",
    kind: "temper",
    tags: ["mystical", "oral"],
    scope: { years: ALL },
    weight: 7,
    wiki: `${w}Dream#Religion`,
    note: "Treats what comes in sleep as information about the waking world and acts on it, sometimes against advice.",
    sources: [],
  },
  {
    id: "temper.fatalist",
    label: "Fatalist",
    icon: "scales-of-fate",
    clause: "holds that the outcome is already fixed",
    kind: "temper",
    tags: ["quietist", "traditionalist"],
    scope: { years: ALL },
    weight: 8,
    wiki: `${w}Fatalism`,
    note: "Holds that the outcome is fixed and that effort changes the effort, not the outcome. Often steadier under disaster than the hopeful are.",
    sources: [],
  },
  {
    id: "temper.enthusiast",
    label: "Enthusiast",
    icon: "thunder",
    clause: "expects the divine to act audibly and now",
    kind: "temper",
    tags: ["devout", "mystical", "millenarian"],
    scope: { years: [1500, 10001] },
    weight: 4,
    lean: "heterodox",
    wiki: `${w}Enthusiasm`,
    note: "Expects the divine to act audibly and now, and takes the composure of the settled clergy as evidence that they have stopped listening.",
    sources: [],
  },
  {
    id: "temper.freethinker",
    label: "Free-thinker",
    icon: "lamp",
    clause: "will accept nothing on authority alone",
    kind: "temper",
    tags: ["sceptical", "rationalist", "literate"],
    scope: { years: [1650, 10001] },
    ranks: ["middling", "gentry", "elite"],
    weight: 4,
    lean: "heterodox",
    wiki: `${w}Freethought`,
    note: "Holds that a belief should be reached by reasoning rather than accepted on authority, and says so in print where the law allows.",
    sources: [],
  },
  {
    id: "temper.secular",
    label: "Secular",
    icon: "hourglass",
    clause: "lives as though the question never arose",
    kind: "temper",
    tags: ["sceptical", "rationalist"],
    scope: { years: [1800, 10001] },
    weight: 8,
    wiki: `${w}Secularity`,
    note: "Lives as if the question does not arise, without the hostility of the anticlerical or the care of the indifferent to avoid it.",
    sources: [],
  },
  {
    id: "temper.atheist",
    label: "Atheist",
    icon: "night",
    clause: "denies the powers outright",
    kind: "temper",
    tags: ["sceptical", "rationalist", "literate"],
    scope: { years: [1700, 10001] },
    weight: 3,
    lean: "heterodox",
    wiki: `${w}Atheism`,
    note: "Denies outright. Before the nineteenth century this was rare, dangerous to state, and usually alleged against people who did not hold it.",
    sources: [],
  },
];
