import type { Stance } from "../types";
const w = "https://en.wikipedia.org/wiki/";

export const westCentralAfrica: readonly Stance[] = [
  {
    id: "stance.wealth-in-people",
    label: "Wealth is counted in people",
    short: "Wealth in people",
    icon: "crowd",
    clause: "counts wealth in dependants rather than in goods",
    kind: "economic",
    tags: ["communal", "hierarchical", "agrarian"],
    scope: { years: [-1000, 10001] },
    weight: 22,
    lean: "orthodox",
    wiki: `${w}Wealth_in_people`,
    note: "Land was plentiful and hands were not, so a big man is one with dependants, and marriage, clientage and captivity are all ways of getting them.",
    sources: [],
  },
  {
    id: "stance.ancestral-mediation",
    label: "The dead speak for the living",
    short: "Ancestral",
    icon: "ancestors",
    clause: "addresses the lineage dead, not the remote creator",
    kind: "cosmic",
    tags: ["traditionalist", "devout", "communal"],
    scope: { years: [-2000, 10001] },
    weight: 20,
    wiki: `${w}Traditional_African_religion`,
    note: "The creator is remote and does not attend to particulars; the lineage dead do, and are the ones actually addressed.",
    sources: [],
  },
  {
    id: "stance.affliction-has-an-author",
    label: "Affliction is caused by someone",
    short: "Affliction",
    icon: "mask",
    clause: "asks who caused an affliction, not what",
    kind: "cosmic",
    tags: ["particularist", "oral"],
    scope: { years: [-2000, 10001] },
    weight: 20,
    wiki: `${w}Witchcraft_in_Africa`,
    note: "Diagnosis is a social enquiry rather than a medical one: the question is who, and the answer reorganises the village.",
    sources: [],
  },
  {
    id: "stance.matrilineal-claim",
    label: "Descent runs through the mother",
    short: "Matrilineal",
    icon: "mother-and-child",
    clause: "reckons the heir through the mother's line",
    kind: "ethical",
    tags: ["communal", "traditionalist"],
    scope: { years: [-1000, 10001] },
    weight: 14,
    wiki: `${w}Matrilineality`,
    note: "A man's heir is his sister's son, which puts a mother's brother where a father would otherwise be and makes inheritance a different argument.",
    sources: [],
  },
  {
    id: "stance.sahelian-scholar",
    label: "Sahelian scholar",
    icon: "scroll",
    clause: "holds the written law against the local court",
    kind: "temper",
    tags: ["literate", "devout", "universalist"],
    scope: { years: [1000, 10001], bounds: [-17, 10, 25, 20] },
    ranks: ["middling", "gentry", "elite"],
    weight: 10,
    wiki: `${w}Timbuktu_Manuscripts`,
    note: "A lettered class with libraries and correspondents across the desert, holding the written law against the courts of local kings.",
    sources: [],
  },
  {
    id: "stance.sacred-kingship-wca",
    label: "The king must not be seen to eat",
    short: "Sacred kingship",
    icon: "throne",
    clause: "expects a king hedged about with prohibitions",
    kind: "political",
    tags: ["hierarchical", "devout", "traditionalist"],
    scope: { years: [-500, 1950] },
    weight: 14,
    wiki: `${w}Divine_king`,
    note: "The ruler is hedged with prohibitions that mark him as no longer an ordinary person, and which can be used to remove him.",
    sources: [],
  },
  {
    id: "stance.jihad-reform",
    label: "Reforming jihad",
    icon: "spear",
    clause: "would replace a lax king by force of arms",
    kind: "political",
    tags: ["devout", "revolutionary", "restorationist", "literate"],
    scope: { years: [1720, 1900], bounds: [-17, 8, 20, 18] },
    weight: 6,
    wiki: `${w}Fula_jihads`,
    note: "Scholars declaring the nominally Muslim kings to be unbelievers and replacing them, which made several of the largest states in the region.",
    sources: [],
  },
];
