import type { Stance } from "../types";

const w = "https://en.wikipedia.org/wiki/";
const EGYPT: [number, number, number, number] = [24, 22, 36, 32];

export const westAsia: readonly Stance[] = [
  {
    id: "stance.maat",
    label: "Maat",
    icon: "scales",
    clause: "holds order, truth and the river's course to be one",
    kind: "cosmic",
    tags: ["hierarchical", "traditionalist", "civic"],
    scope: { years: [-3000, 300], bounds: EGYPT },
    weight: 20,
    lean: "orthodox",
    wiki: `${w}Maat`,
    note: "Order, truth and the proper course of the river are one thing, maintained by the king and undone by any lie or theft.",
    sources: [],
  },
  {
    id: "stance.weighed-heart",
    label: "The heart is weighed",
    short: "Heart-weighing",
    icon: "heart",
    clause: "expects the heart weighed against a feather",
    kind: "ethical",
    tags: ["devout", "universalist"],
    scope: { years: [-2500, 300], bounds: EGYPT },
    weight: 16,
    wiki: `${w}Maat#Weighing_of_the_heart`,
    note: "What was done is assessed against a feather after death, with a list of the things one must be able to deny having done.",
    sources: [],
  },
  {
    id: "stance.dualist-zoroastrian",
    label: "Zoroastrian dualist",
    short: "Zoroastrian",
    icon: "fire",
    clause: "counts every choice toward the good power's victory",
    kind: "cosmic",
    tags: ["devout", "universalist", "civic"],
    scope: { years: [-1200, 10001], bounds: [40, 25, 65, 42] },
    weight: 14,
    wiki: `${w}Zoroastrianism`,
    note: "Two powers at war and every person's choice counting toward the outcome, with the good one expected to win.",
    sources: [],
  },
  {
    id: "stance.covenant",
    label: "Covenantal",
    icon: "knot",
    clause: "reads a national disaster as a breach of terms",
    kind: "political",
    tags: ["particularist", "devout", "literate"],
    scope: { years: [-900, 10001], bounds: [30, 28, 40, 36] },
    weight: 14,
    wiki: `${w}Covenant_(biblical)`,
    note: "An agreement between a people and their god with terms on both sides, which makes a national disaster a breach to be investigated.",
    sources: [],
  },
  {
    id: "stance.prophetic-justice",
    label: "Prophetic",
    icon: "scales",
    clause: "counts the sacrifices worthless while the widow is robbed",
    kind: "ethical",
    tags: ["egalitarian", "devout", "reformist"],
    scope: { years: [-800, 10001], bounds: [28, 25, 50, 40] },
    weight: 8,
    lean: "heterodox",
    wiki: `${w}Nevi%27im`,
    note: "The sacrifices are worth nothing while the widow is robbed, said to the king's face and written down afterwards.",
    sources: [],
  },
  {
    id: "stance.rabbinic",
    label: "Rabbinic",
    icon: "scroll",
    clause: "settles the law by argument among the learned",
    kind: "temper",
    tags: ["literate", "traditionalist", "rationalist"],
    scope: { years: [200, 10001] },
    weight: 8,
    wiki: `${w}Rabbinic_Judaism`,
    note: "The law worked out by argument among those who have studied it, with the disagreements preserved rather than resolved.",
    sources: [],
  },
  {
    id: "stance.mutazilite",
    label: "Mu'tazilite",
    icon: "lamp",
    clause: "expects God to be just in a recognisable sense",
    kind: "cosmic",
    tags: ["rationalist", "literate", "universalist"],
    scope: { years: [750, 1100], bounds: [28, 20, 62, 42] },
    ranks: ["middling", "gentry", "elite"],
    weight: 5,
    lean: "heterodox",
    wiki: `${w}Mu%27tazilism`,
    note: "God is just in a sense a person can recognise, the Qur'an is created rather than eternal, and human acts are genuinely the human's.",
    sources: [],
  },
  {
    id: "stance.ashari",
    label: "Ash'ari traditionalist",
    short: "Ash'ari",
    icon: "tablet",
    clause: "holds God's will unbound by human reasoning",
    kind: "cosmic",
    tags: ["devout", "traditionalist", "literate"],
    scope: { years: [900, 10001] },
    weight: 14,
    lean: "orthodox",
    wiki: `${w}Ash%27arism`,
    note: "God's will is not bound by what people think reasonable; causes do not compel, and the fire burns because He wills it each time.",
    sources: [],
  },
  {
    id: "stance.falsafa",
    label: "Falsafa",
    icon: "star",
    clause: "continues the Greek argument in Arabic",
    kind: "cosmic",
    tags: ["rationalist", "literate", "empirical"],
    scope: { years: [800, 1400], bounds: [-10, 20, 70, 45] },
    ranks: ["middling", "gentry", "elite"],
    weight: 4,
    lean: "heterodox",
    wiki: `${w}Early_Islamic_philosophy`,
    note: "The Greek inheritance continued and argued with in Arabic, on the view that revelation and demonstration cannot finally disagree.",
    sources: [],
  },
  {
    id: "stance.sharia-jurist",
    label: "Jurist",
    icon: "book",
    clause: "settles conduct by a school of law, not a decree",
    kind: "ethical",
    tags: ["literate", "traditionalist", "civic"],
    scope: { years: [750, 10001] },
    ranks: ["middling", "gentry", "elite"],
    weight: 12,
    lean: "orthodox",
    wiki: `${w}Fiqh`,
    note: "Conduct settled by a school of law with its own chain of reasoning, and a ruler's decree having no standing against it.",
    sources: [],
  },
  {
    id: "stance.sufi-west",
    label: "Sufi",
    icon: "spiral",
    clause: "walks the path under a master in the lodge",
    kind: "temper",
    tags: ["mystical", "ascetic", "universalist"],
    scope: { years: [850, 10001] },
    weight: 14,
    wiki: `${w}Sufism`,
    note: "The path walked under a master in a lodge, with the jurists tolerating it at some times and burning its extravagant members at others.",
    sources: [],
  },
  {
    id: "stance.khaldunian",
    label: "Cyclical historian",
    short: "Cyclical",
    icon: "dune",
    clause: "expects group feeling to be spent in four generations",
    kind: "political",
    tags: ["rationalist", "empirical", "literate", "sceptical"],
    scope: { years: [1380, 1800], bounds: [-12, 20, 50, 40] },
    ranks: ["gentry", "elite"],
    weight: 3,
    lean: "heterodox",
    wiki: `${w}Asabiyyah`,
    note: "Group feeling is strongest on the desert edge, carries a dynasty into the cities, and is spent by comfort in about four generations.",
    sources: [],
  },
  {
    id: "stance.millet-order",
    label: "The order of the communities",
    short: "Millet order",
    icon: "gate",
    clause: "lets each confession govern its own",
    kind: "political",
    tags: ["hierarchical", "particularist", "traditionalist"],
    scope: { years: [1450, 1920], bounds: [18, 28, 50, 46] },
    weight: 12,
    lean: "orthodox",
    wiki: `${w}Millet_(Ottoman_Empire)`,
    note: "Each confession governs its own in matters of marriage and inheritance, under its own clergy, and pays for the privilege.",
    sources: [],
  },
  {
    id: "stance.salafi-reformist",
    label: "Salafi reformist",
    icon: "spring",
    clause: "wants the shrines left and the first generations followed",
    kind: "temper",
    tags: ["restorationist", "reformist", "literate"],
    scope: { years: [1880, 10001] },
    weight: 8,
    wiki: `${w}Salafi_movement`,
    note: "Back past the schools and the shrines to the first generations, argued as the way to meet Europe rather than as a retreat from it.",
    sources: [],
  },
  {
    id: "stance.kemalist",
    label: "Kemalist",
    icon: "tower",
    clause: "would carry the whole programme by the state",
    kind: "political",
    tags: ["civic", "rationalist", "reformist", "particularist"],
    scope: { years: [1923, 10001], bounds: [25, 35, 45, 43] },
    weight: 10,
    wiki: `${w}Kemalism`,
    note: "A republic, a Latin alphabet, the religious orders closed, and the whole programme carried by the state rather than argued for.",
    sources: [],
  },
  {
    id: "stance.arab-nationalist",
    label: "Arab nationalist",
    icon: "crescent",
    clause: "takes the language rather than the confession as common ground",
    kind: "political",
    tags: ["particularist", "civic", "revolutionary", "universalist"],
    scope: { years: [1910, 10001], bounds: [-12, 12, 55, 38] },
    weight: 10,
    wiki: `${w}Arab_nationalism`,
    note: "One people divided by borders the Europeans drew, with the language rather than the confession as what is held in common.",
    sources: [],
  },
  {
    id: "stance.zionist",
    label: "Zionist",
    icon: "key",
    clause: "wants a territory and a state",
    kind: "political",
    tags: ["particularist", "civic", "reformist"],
    scope: { years: [1890, 10001] },
    weight: 6,
    wiki: `${w}Zionism`,
    note: "A territory and a state, argued from the view that emancipation in Europe had been offered and had not held.",
    sources: [],
  },
];
