import { useEffect, useRef, useState } from "react";
import {
  runDialogueBatch,
  type DialogueBatchProgress,
  type DialogueSample,
} from "./dialogue-tester";

export function DialogueTester({ onClose }: { onClose: () => void }) {
  const [query, setQuery] = useState("What's your job?");
  const [samples, setSamples] = useState<DialogueSample[]>([]);
  const [progress, setProgress] = useState<DialogueBatchProgress>();
  const [error, setError] = useState("");
  const [running, setRunning] = useState(false);
  const abort = useRef<AbortController | null>(null);
  useEffect(() => () => abort.current?.abort(), []);

  const run = async () => {
    abort.current?.abort();
    const controller = new AbortController();
    abort.current = controller;
    setRunning(true);
    setSamples([]);
    setError("");
    setProgress({
      completed: 0,
      target: 5,
      status: "Choosing randomized starts…",
    });
    try {
      const result = await runDialogueBatch(
        query,
        setProgress,
        controller.signal,
      );
      setSamples(result);
    } catch (cause) {
      if (!(cause instanceof DOMException && cause.name === "AbortError"))
        setError(cause instanceof Error ? cause.message : String(cause));
    } finally {
      if (abort.current === controller) abort.current = null;
      setRunning(false);
    }
  };

  return (
    <div className="dialogue-tester">
      <div className="eyebrow">DEVELOPER TOOL</div>
      <h2>NPC dialogue tester</h2>
      <p>
        One query, five NPCs from separate randomized game starts. Each reply
        uses the NPC, setting, and nearby context generated by the game.
      </p>
      <label htmlFor="dialogue-test-query">Player says</label>
      <textarea
        id="dialogue-test-query"
        rows={3}
        maxLength={600}
        value={query}
        onChange={(event) => setQuery(event.target.value)}
        disabled={running}
      />
      <div className="dialogue-tester-actions">
        <button
          className="action"
          onClick={() => void run()}
          disabled={running || !query.trim()}
        >
          {running ? "Generating five replies…" : "Run five NPCs"}
        </button>
        {running && (
          <button className="action" onClick={() => abort.current?.abort()}>
            Cancel
          </button>
        )}
      </div>
      {progress && (
        <p className="dialogue-tester-progress" aria-live="polite">
          {progress.status}
        </p>
      )}
      {error && (
        <p role="alert" className="dialogue-tester-error">
          {error}
        </p>
      )}
      {!!samples.length && (
        <ol className="dialogue-tester-results">
          {samples.map((sample, index) => (
            <li key={`${sample.place}-${sample.year}-${index}`}>
              <div className="dialogue-tester-person">
                <strong>{sample.name}</strong> · {sample.role}
                <small>
                  {sample.place} · {sample.era} ·{" "}
                  {sample.year <= 0
                    ? `${1 - sample.year} BCE`
                    : `${sample.year} CE`}
                </small>
              </div>
              <p>
                {sample.error ? `Error: ${sample.error}` : `“${sample.reply}”`}
              </p>
            </li>
          ))}
        </ol>
      )}
      <small className="dialogue-tester-footnote">
        Uses live API calls. In development, the same runner is available as
        <code>window.uhsDialogueTester.run(query)</code>.
      </small>
      <button className="action dialogue-tester-close" onClick={onClose}>
        Close
      </button>
    </div>
  );
}
