/**
 * Named wild plants: which grow where, how a bloom is drawn, and what a cut
 * one gives up. Picks are hashed from world position, so the renderer, the
 * hover label and the engine's harvest always agree on the plant.
 */
import type { ItemDef, ItemId } from "../../core/types";
import { waterHash as hash } from "../../core/water-field";
import type { Ecology } from "./profiles";

export type FloraRegion =
  | "europe"
  | "med"
  | "westasia"
  | "southasia"
  | "eastasia"
  | "seasia"
  | "northasia"
  | "africa"
  | "safrica"
  | "naeast"
  | "nawest"
  | "mesoamerica"
  | "samerica"
  | "australia";
/** Where a plant grows. `*` for the cosmopolitan and circumpolar ones. */
type Range = FloraRegion | "*";
/** Siberia shares its flora with both ends of the Palearctic. */
const alias: Partial<Record<FloraRegion, FloraRegion[]>> = {
  northasia: ["europe", "eastasia"],
};
const inBox = (
  lon: number,
  lat: number,
  w: number,
  s: number,
  e: number,
  n: number,
) => lon >= w && lon <= e && lat >= s && lat <= n;
export function floraRegion(lon: number, lat: number): FloraRegion {
  if (inBox(lon, lat, 110, -50, 180, -10)) return "australia";
  if (lon < -30) {
    if (lat > 25 || (lat > 15 && lon < -118))
      return lon < -100 ? "nawest" : "naeast";
    return lat > 5 ? "mesoamerica" : "samerica";
  }
  if (lat >= 50 && lon >= 60) return "northasia";
  if (lon > 92 && lat > 20) return "eastasia";
  // The steppe and the Tarim belong with Iran, not with Europe or India.
  if (lon >= 55 && lat >= 35) return "westasia";
  if (lat >= 45) return "europe";
  if (inBox(lon, lat, 60, 5, 92, 35)) return "southasia";
  if (inBox(lon, lat, -18, 27, 36, 45)) return "med";
  if (inBox(lon, lat, 35, 12, 75, 50)) return "westasia";
  if (inBox(lon, lat, 92, 20, 150, 55)) return "eastasia";
  if (inBox(lon, lat, 92, -11, 160, 20)) return "seasia";
  if (lat < 30 && lon < 55) return lat < -22 ? "safrica" : "africa";
  return "europe";
}

/** What kind of growth a species stands in for. Sprites map onto these. */
export type FloraForm =
  | "bloom"
  | "shrub"
  | "heath"
  | "scrub"
  | "grass"
  | "reed"
  | "fern";
export type BloomHabit = "head" | "spike" | "umbel" | "mat" | "bell";
export type BloomLook = {
  habit: BloomHabit;
  petal: string;
  centre: string;
  /** Stem height: -1 low, 0 middling, 1 tall. */
  size: -1 | 0 | 1;
};
/** Item, chance per cut, count. A chance of 1 always yields. */
type Yield = readonly [ItemId, number, number?];
export type Species = {
  id: string;
  common: string;
  latin: string;
  form: FloraForm;
  range: Range[];
  eco?: Ecology[];
  weight: number;
  yields: Yield[];
  look?: BloomLook;
};

const G: Ecology = "grassland",
  S: Ecology = "dry-scrub",
  T: Ecology = "temperate-woodland",
  B: Ecology = "boreal-woodland",
  R: Ecology = "tropical-woodland",
  W: Ecology = "wetland",
  V: Ecology = "savanna",
  N: Ecology = "tundra",
  D: Ecology = "desert";
const look = (
  habit: BloomHabit,
  petal: string,
  centre: string,
  size: -1 | 0 | 1 = 0,
): BloomLook => ({ habit, petal, centre, size });
const sp = (
  id: string,
  common: string,
  latin: string,
  form: FloraForm,
  range: Range[],
  eco: Ecology[] | undefined,
  weight: number,
  yields: Yield[] = [],
  bloom?: BloomLook,
): Species => ({
  id,
  common,
  latin,
  form,
  range,
  eco,
  weight,
  yields,
  look: bloom,
});

export const flora: Species[] = [
  // Europe and the Mediterranean.
  sp(
    "corn-poppy",
    "Corn poppy",
    "Papaver rhoeas",
    "bloom",
    ["europe", "med", "westasia"],
    [G, S, T],
    3,
    [],
    look("head", "#d8402e", "#2a1e1a"),
  ),
  sp(
    "cornflower",
    "Cornflower",
    "Centaurea cyanus",
    "bloom",
    ["europe", "westasia"],
    [G],
    2,
    [],
    look("head", "#4f6fd0", "#9db2ee"),
  ),
  sp(
    "oxeye",
    "Oxeye daisy",
    "Leucanthemum vulgare",
    "bloom",
    ["europe", "northasia"],
    [G, T, B],
    3,
    [],
    look("head", "#f6f3e8", "#fbe27a"),
  ),
  sp(
    "chamomile",
    "Chamomile",
    "Matricaria chamomilla",
    "bloom",
    ["europe", "med", "westasia"],
    [G, S],
    1.5,
    [["chamomile", 0.8]],
    look("head", "#f4f1e6", "#f3cf3e", -1),
  ),
  sp(
    "meadow-buttercup",
    "Meadow buttercup",
    "Ranunculus acris",
    "bloom",
    ["europe", "northasia"],
    [G, W, T],
    3,
    [],
    look("mat", "#f3cf3e", "#fbeea0"),
  ),
  sp(
    "red-clover",
    "Red clover",
    "Trifolium pratense",
    "bloom",
    ["europe", "westasia"],
    [G, T],
    2,
    [["fodder", 0.5]],
    look("head", "#d67fae", "#f0c0d8", -1),
  ),
  sp(
    "cowslip",
    "Cowslip",
    "Primula veris",
    "bloom",
    ["europe"],
    [G, T],
    1.5,
    [["greens", 0.3]],
    look("mat", "#f2d04a", "#e89a2a"),
  ),
  sp(
    "primrose",
    "Primrose",
    "Primula vulgaris",
    "bloom",
    ["europe"],
    [T],
    2,
    [],
    look("mat", "#f4e9a0", "#e8b83a"),
  ),
  sp(
    "wild-carrot",
    "Wild carrot",
    "Daucus carota",
    "bloom",
    ["europe", "med", "westasia"],
    [G, S],
    2,
    [["roots", 0.4]],
    look("umbel", "#f4f1e2", "#d9d6bf", 1),
  ),
  sp(
    "yarrow",
    "Yarrow",
    "Achillea millefolium",
    "bloom",
    ["europe", "westasia", "northasia", "naeast", "nawest"],
    [G, B, T],
    2,
    [["herbs", 0.6]],
    look("umbel", "#efe8da", "#d8cfb8"),
  ),
  sp(
    "nettle",
    "Stinging nettle",
    "Urtica dioica",
    "bloom",
    ["europe", "westasia", "northasia", "naeast", "nawest"],
    [T, W, G],
    1.5,
    [
      ["bast", 0.8],
      ["greens", 0.5],
    ],
    look("spike", "#7d9a58", "#a8c060", 1),
  ),
  sp(
    "woad",
    "Woad",
    "Isatis tinctoria",
    "bloom",
    ["europe", "med", "westasia"],
    [G, S],
    0.5,
    [["woad", 0.8]],
    look("umbel", "#e8d040", "#c8a820", 1),
  ),
  sp(
    "weld",
    "Weld",
    "Reseda luteola",
    "bloom",
    ["europe", "med", "westasia"],
    [S, G],
    0.5,
    [["weld", 0.8]],
    look("spike", "#d8d070", "#b8b050", 1),
  ),
  sp(
    "madder",
    "Madder",
    "Rubia tinctorum",
    "bloom",
    ["med", "westasia"],
    [S, G],
    0.4,
    [["madder", 0.7]],
    look("mat", "#d8d890", "#a8a060"),
  ),
  sp(
    "saffron",
    "Saffron crocus",
    "Crocus sativus",
    "bloom",
    ["med", "westasia", "southasia"],
    [S, G],
    0.2,
    [["saffron", 0.5]],
    look("head", "#9c6ad0", "#e0401e", -1),
  ),
  sp(
    "pale-flax",
    "Pale flax",
    "Linum bienne",
    "bloom",
    ["europe", "med", "westasia"],
    [G, S],
    1,
    [["flax", 0.7]],
    look("head", "#a8b8e8", "#f0f0f8", 1),
  ),
  sp(
    "harebell",
    "Harebell",
    "Campanula rotundifolia",
    "bloom",
    ["europe", "northasia", "naeast", "nawest"],
    [G, B, N],
    2,
    [],
    look("bell", "#8a9ce0", "#c8d4f0"),
  ),
  sp(
    "wild-thyme",
    "Wild thyme",
    "Thymus serpyllum",
    "bloom",
    ["europe", "med"],
    [S, G],
    1.5,
    [["herbs", 0.8]],
    look("mat", "#c890c8", "#e8c0e8"),
  ),
  sp(
    "crown-anemone",
    "Crown anemone",
    "Anemone coronaria",
    "bloom",
    ["med", "westasia"],
    [S, G],
    1.5,
    [],
    look("head", "#c02848", "#2a2030"),
  ),
  sp(
    "ramsons",
    "Wild garlic",
    "Allium ursinum",
    "bloom",
    ["europe"],
    [T],
    1,
    [["greens", 1]],
    look("umbel", "#f6f3ea", "#e2e0cc", -1),
  ),
  sp(
    "purslane",
    "Purslane",
    "Portulaca oleracea",
    "bloom",
    ["med", "westasia", "southasia", "africa", "safrica"],
    [S, G, V],
    1,
    [["greens", 0.9]],
    look("mat", "#f0d040", "#a8c060", -1),
  ),
  sp(
    "opium-poppy",
    "Opium poppy",
    "Papaver somniferum",
    "bloom",
    ["med", "westasia", "southasia"],
    [G, S],
    0.25,
    [["poppy-pods", 0.9]],
    look("head", "#d9c2e6", "#5a2d6a", 1),
  ),
  sp(
    "safflower",
    "Safflower",
    "Carthamus tinctorius",
    "bloom",
    ["westasia", "southasia", "africa"],
    [S, G, V],
    0.4,
    [["safflower", 0.8]],
    look("head", "#f08a20", "#e8c040"),
  ),
  sp(
    "wild-emmer",
    "Wild emmer",
    "Triticum dicoccoides",
    "grass",
    ["westasia"],
    [G, S],
    0.4,
    [["grain", 0.6]],
  ),
  sp(
    "wild-barley",
    "Wild barley",
    "Hordeum spontaneum",
    "grass",
    ["westasia", "med"],
    [G, S],
    0.6,
    [["grain", 0.5]],
  ),
  sp(
    "cannabis-indica",
    "Cannabis",
    "Cannabis indica",
    "bloom",
    ["southasia", "westasia"],
    [G, S, T],
    0.2,
    [
      ["bast", 1],
      ["cannabis", 0.6],
    ],
    look("spike", "#6f9a3c", "#9cbc58", 1),
  ),
  sp(
    "hemp",
    "Hemp",
    "Cannabis sativa",
    "bloom",
    ["eastasia", "northasia", "westasia"],
    [G, T],
    0.3,
    [["bast", 1, 2]],
    look("spike", "#7aa044", "#a6c464", 1),
  ),
  // South and Southeast Asia.
  sp(
    "indigo",
    "True indigo",
    "Indigofera tinctoria",
    "bloom",
    ["southasia", "seasia", "africa"],
    [R, V, G],
    0.5,
    [["indigo", 0.8]],
    look("spike", "#d07898", "#a85070"),
  ),
  sp(
    "tulsi",
    "Holy basil",
    "Ocimum tenuiflorum",
    "bloom",
    ["southasia", "seasia"],
    [R, G],
    1,
    [["herbs", 0.9]],
    look("spike", "#b890c8", "#d8c0e0"),
  ),
  sp(
    "green-amaranth",
    "Green amaranth",
    "Amaranthus viridis",
    "bloom",
    ["southasia", "seasia", "africa", "safrica"],
    [G, V],
    1,
    [["greens", 0.8]],
    look("spike", "#8aa848", "#b0c868"),
  ),
  sp(
    "celosia",
    "Silver cock's-comb",
    "Celosia argentea",
    "bloom",
    ["africa", "southasia", "seasia"],
    [V, R],
    1,
    [["greens", 0.6]],
    look("spike", "#e8a0c0", "#f0d0e0"),
  ),
  sp(
    "water-spinach",
    "Water spinach",
    "Ipomoea aquatica",
    "bloom",
    ["seasia", "southasia", "eastasia"],
    [W],
    1,
    [["greens", 1]],
    look("mat", "#f0e0f0", "#c070a0", -1),
  ),
  sp(
    "jute",
    "Jute",
    "Corchorus capsularis",
    "bloom",
    ["southasia", "seasia"],
    [W, R],
    0.8,
    [["bast", 1, 2]],
    look("head", "#f0d848", "#c8a830", 1),
  ),
  // East Asia.
  sp(
    "balloon-flower",
    "Balloon flower",
    "Platycodon grandiflorus",
    "bloom",
    ["eastasia", "northasia"],
    [G, T],
    1.5,
    [["roots", 0.5]],
    look("head", "#6a70d0", "#b0b8f0"),
  ),
  sp(
    "wild-chrysanthemum",
    "Wild chrysanthemum",
    "Chrysanthemum indicum",
    "bloom",
    ["eastasia"],
    [G, T],
    1.5,
    [["herbs", 0.5]],
    look("head", "#f0d030", "#e0a020", -1),
  ),
  sp(
    "ramie",
    "Ramie",
    "Boehmeria nivea",
    "bloom",
    ["eastasia", "seasia"],
    [T, R],
    0.7,
    [["bast", 1, 2]],
    look("spike", "#8aa860", "#b8c890", 1),
  ),
  sp(
    "gromwell",
    "Purple gromwell",
    "Lithospermum erythrorhizon",
    "bloom",
    ["eastasia", "northasia"],
    [G],
    0.3,
    [["gromwell", 0.7]],
    look("head", "#f4f2ea", "#e0dcc8", -1),
  ),
  sp(
    "day-lily",
    "Tawny day lily",
    "Hemerocallis fulva",
    "bloom",
    ["eastasia"],
    [G, T, W],
    1.5,
    [["greens", 0.6]],
    look("head", "#e87830", "#c04818", 1),
  ),
  // Africa.
  sp(
    "roselle",
    "Roselle",
    "Hibiscus sabdariffa",
    "bloom",
    ["africa"],
    [V, R, G],
    0.6,
    [["roselle", 0.8]],
    look("head", "#e8c8c8", "#901830", 1),
  ),
  sp(
    "gazania",
    "Treasure flower",
    "Gazania krebsiana",
    "bloom",
    ["safrica"],
    [S, G],
    2,
    [],
    look("head", "#f07820", "#301810", -1),
  ),
  sp(
    "spider-plant",
    "Spider plant",
    "Cleome gynandra",
    "bloom",
    ["africa", "southasia", "safrica"],
    [V, G],
    1.5,
    [["greens", 0.9]],
    look("umbel", "#f4eef0", "#c080b0"),
  ),
  sp(
    "kenaf",
    "Kenaf",
    "Hibiscus cannabinus",
    "bloom",
    ["africa", "southasia"],
    [V, W],
    0.6,
    [["bast", 0.9]],
    look("head", "#f0e070", "#6a2030", 1),
  ),
  sp(
    "aloe",
    "Aloe",
    "Aloe vera",
    "bloom",
    ["westasia"],
    [S, V],
    0.8,
    [["herbs", 0.4]],
    look("spike", "#e05030", "#f0a040", 1),
  ),
  // North America.
  sp(
    "milkweed",
    "Common milkweed",
    "Asclepias syriaca",
    "bloom",
    ["naeast"],
    [G, T],
    1.5,
    [["bast", 0.7]],
    look("umbel", "#d8a0b8", "#c07898", 1),
  ),
  sp(
    "dogbane",
    "Indian hemp",
    "Apocynum cannabinum",
    "bloom",
    ["naeast", "nawest"],
    [G, W, T],
    1,
    [["bast", 1, 2]],
    look("umbel", "#f2e6ea", "#d8b8c4"),
  ),
  sp(
    "black-eyed-susan",
    "Black-eyed Susan",
    "Rudbeckia hirta",
    "bloom",
    ["naeast"],
    [G],
    3,
    [],
    look("head", "#f0b820", "#3a2418"),
  ),
  sp(
    "coneflower",
    "Purple coneflower",
    "Echinacea purpurea",
    "bloom",
    ["naeast"],
    [G],
    1.5,
    [["herbs", 0.6]],
    look("head", "#c070b0", "#a05020"),
  ),
  sp(
    "goldenrod",
    "Canada goldenrod",
    "Solidago canadensis",
    "bloom",
    ["naeast", "nawest"],
    [G, T],
    2.5,
    [["goldenrod", 0.4]],
    look("spike", "#e8c830", "#c8a020", 1),
  ),
  sp(
    "blue-flag",
    "Blue flag",
    "Iris versicolor",
    "bloom",
    ["naeast"],
    [W],
    1,
    [],
    look("head", "#6a58c0", "#e8d060", 1),
  ),
  sp(
    "bergamot",
    "Wild bergamot",
    "Monarda fistulosa",
    "bloom",
    ["naeast", "nawest"],
    [G],
    2,
    [["herbs", 0.8]],
    look("head", "#c898d0", "#b070b8"),
  ),
  sp(
    "lupine",
    "Sundial lupine",
    "Lupinus perennis",
    "bloom",
    ["naeast"],
    [G, T],
    2,
    [],
    look("spike", "#6a70d8", "#b0b8f0"),
  ),
  sp(
    "camas",
    "Camas",
    "Camassia quamash",
    "bloom",
    ["nawest"],
    [G, W],
    1,
    [["bulbs", 0.8]],
    look("spike", "#6a78d8", "#a8b0f0"),
  ),
  sp(
    "california-poppy",
    "California poppy",
    "Eschscholzia californica",
    "bloom",
    ["nawest"],
    [G, S],
    2.5,
    [],
    look("head", "#f0901c", "#f0c030", -1),
  ),
  sp(
    "coyote-tobacco",
    "Coyote tobacco",
    "Nicotiana attenuata",
    "bloom",
    ["nawest"],
    [S, G],
    0.3,
    [["tobacco", 0.7]],
    look("head", "#f2f0e4", "#b8c8a0", 1),
  ),
  sp(
    "sunflower",
    "Common sunflower",
    "Helianthus annuus",
    "bloom",
    ["nawest", "naeast", "mesoamerica"],
    [G, S],
    1.5,
    [["seeds", 0.6]],
    look("head", "#f0c020", "#5a3a18", 1),
  ),
  // Mesoamerica and South America.
  sp(
    "cempasuchil",
    "Aztec marigold",
    "Tagetes erecta",
    "bloom",
    ["mesoamerica"],
    [G, S, R],
    2,
    [["herbs", 0.4]],
    look("head", "#f09020", "#d06010"),
  ),
  sp(
    "chia",
    "Chia",
    "Salvia hispanica",
    "bloom",
    ["mesoamerica"],
    [S, G],
    1,
    [["seeds", 0.9]],
    look("spike", "#7a68c8", "#b0a8e0"),
  ),
  sp(
    "huauhtli",
    "Amaranth",
    "Amaranthus hypochondriacus",
    "bloom",
    ["mesoamerica"],
    [G],
    0.8,
    [
      ["seeds", 0.7],
      ["greens", 0.5],
    ],
    look("spike", "#a82848", "#d05070", 1),
  ),
  sp(
    "cosmos",
    "Garden cosmos",
    "Cosmos bipinnatus",
    "bloom",
    ["mesoamerica"],
    [G],
    2,
    [],
    look("head", "#e080b8", "#f0d040"),
  ),
  sp(
    "dahlia",
    "Scarlet dahlia",
    "Dahlia coccinea",
    "bloom",
    ["mesoamerica"],
    [G, T],
    1,
    [["roots", 0.4]],
    look("head", "#d84020", "#f0c030"),
  ),
  sp(
    "wild-tobacco",
    "Aztec tobacco",
    "Nicotiana rustica",
    "bloom",
    ["mesoamerica", "samerica", "naeast"],
    [G, S],
    0.3,
    [["tobacco", 0.7]],
    look("head", "#e8e4a0", "#a8b070", 1),
  ),
  sp(
    "nasturtium",
    "Nasturtium",
    "Tropaeolum majus",
    "bloom",
    ["samerica"],
    [G, T, R],
    1.5,
    [["greens", 1]],
    look("head", "#f07020", "#e8c030", -1),
  ),
  sp(
    "verbena",
    "Purpletop vervain",
    "Verbena bonariensis",
    "bloom",
    ["samerica"],
    [G],
    2,
    [],
    look("spike", "#9a68c8", "#c0a0e0", 1),
  ),
  sp(
    "alstroemeria",
    "Peruvian lily",
    "Alstroemeria aurea",
    "bloom",
    ["samerica"],
    [G, T],
    1.5,
    [["roots", 0.3]],
    look("head", "#f09060", "#c04830"),
  ),
  // Australia.
  sp(
    "cape-aloe-flower",
    "Cape aloe",
    "Aloe ferox",
    "bloom",
    ["safrica"],
    [S, V, G],
    1,
    [["herbs", 0.4]],
    look("spike", "#e05030", "#f0a040", 1),
  ),
  sp(
    "kangaroo-paw",
    "Kangaroo paw",
    "Anigozanthos manglesii",
    "bloom",
    ["australia"],
    [S, G],
    1.5,
    [],
    look("spike", "#d83020", "#5a8a30", 1),
  ),
  sp(
    "everlasting",
    "Golden everlasting",
    "Xerochrysum bracteatum",
    "bloom",
    ["australia"],
    [G, S],
    3,
    [],
    look("head", "#f0c020", "#c08020"),
  ),
  sp(
    "murnong",
    "Yam daisy",
    "Microseris walteri",
    "bloom",
    ["australia"],
    [G, T],
    1.5,
    [["roots", 0.9]],
    look("head", "#f2d040", "#e0b020", -1),
  ),
  // Circumpolar tundra.
  sp(
    "arctic-poppy",
    "Arctic poppy",
    "Papaver radicatum",
    "bloom",
    ["*"],
    [N],
    2,
    [],
    look("head", "#f0d840", "#b0a030", -1),
  ),
  sp(
    "purple-saxifrage",
    "Purple saxifrage",
    "Saxifraga oppositifolia",
    "bloom",
    ["*"],
    [N],
    2,
    [],
    look("mat", "#b060b0", "#e0a0e0", -1),
  ),
  sp(
    "moss-campion",
    "Moss campion",
    "Silene acaulis",
    "bloom",
    ["*"],
    [N, B],
    1.5,
    [],
    look("mat", "#e070a0", "#f0b0cc", -1),
  ),

  // Shrubs.
  sp("bramble", "Bramble", "Rubus fruticosus", "shrub", ["europe"], [T, G], 3, [
    ["berries", 0.6, 2],
  ]),
  sp(
    "dog-rose",
    "Dog rose",
    "Rosa canina",
    "shrub",
    ["europe", "med", "westasia"],
    [G, T, S],
    2,
    [["berries", 0.5]],
  ),
  sp(
    "blackthorn",
    "Blackthorn",
    "Prunus spinosa",
    "shrub",
    ["europe"],
    [G, T],
    2,
    [["berries", 0.4]],
  ),
  sp("elder", "Elder", "Sambucus nigra", "shrub", ["europe"], [T], 1.5, [
    ["berries", 0.5],
  ]),
  sp("broom", "Broom", "Cytisus scoparius", "shrub", ["europe"], [G, T], 1.5, [
    ["bast", 0.3],
  ]),
  sp("myrtle", "Myrtle", "Myrtus communis", "shrub", ["med"], [S, T], 2, [
    ["berries", 0.5],
  ]),
  sp("mastic", "Mastic", "Pistacia lentiscus", "shrub", ["med"], [S], 2, [
    ["resin", 0.3],
  ]),
  sp(
    "liquorice",
    "Liquorice",
    "Glycyrrhiza glabra",
    "shrub",
    ["westasia", "med"],
    [S, G],
    1,
    [["roots", 0.6]],
  ),
  sp(
    "henna",
    "Henna",
    "Lawsonia inermis",
    "shrub",
    ["africa", "westasia", "southasia"],
    [S, V],
    0.6,
    [["henna", 0.7]],
  ),
  sp(
    "tree-cotton",
    "Tree cotton",
    "Gossypium arboreum",
    "shrub",
    ["southasia", "africa"],
    [V, S, R],
    0.5,
    [["cotton", 0.6]],
  ),
  sp(
    "karonda",
    "Karonda",
    "Carissa carandas",
    "shrub",
    ["southasia"],
    [S, V, R],
    1.5,
    [["berries", 0.6]],
  ),
  sp(
    "turmeric",
    "Turmeric",
    "Curcuma longa",
    "shrub",
    ["southasia", "seasia"],
    [R, W],
    0.7,
    [["turmeric", 0.7]],
  ),
  sp(
    "galangal",
    "Galangal",
    "Alpinia galanga",
    "shrub",
    ["seasia", "southasia"],
    [R],
    1,
    [["roots", 0.6]],
  ),
  sp(
    "torch-ginger",
    "Torch ginger",
    "Etlingera elatior",
    "shrub",
    ["seasia"],
    [R],
    1,
    [["greens", 0.5]],
  ),
  sp(
    "melastoma",
    "Singapore rhododendron",
    "Melastoma malabathricum",
    "shrub",
    ["seasia", "southasia"],
    [R, W, G],
    1.5,
    [["berries", 0.4]],
  ),
  sp(
    "tea",
    "Tea",
    "Camellia sinensis",
    "shrub",
    ["eastasia", "seasia"],
    [T, R],
    0.6,
    [["tea", 0.7]],
  ),
  sp(
    "paper-mulberry",
    "Paper mulberry",
    "Broussonetia papyrifera",
    "shrub",
    ["eastasia", "seasia"],
    [T, R],
    1,
    [["bast", 0.8]],
  ),
  sp(
    "goji",
    "Chinese wolfberry",
    "Lycium chinense",
    "shrub",
    ["eastasia"],
    [G, S],
    1.5,
    [["berries", 0.6]],
  ),
  sp(
    "coffee",
    "Arabica coffee",
    "Coffea arabica",
    "shrub",
    ["africa"],
    [R, T],
    0.3,
    [["coffee", 0.6]],
  ),
  sp("khat", "Khat", "Catha edulis", "shrub", ["africa"], [T, R, S], 0.2, [
    ["khat", 0.6],
  ]),
  sp(
    "sugarbush",
    "Sugarbush",
    "Protea repens",
    "shrub",
    ["safrica"],
    [S],
    1.5,
    [],
  ),
  sp(
    "bowstring-hemp",
    "Bowstring hemp",
    "Sansevieria hyacinthoides",
    "shrub",
    ["africa", "southasia", "safrica"],
    [V, S],
    1,
    [["bast", 1]],
  ),
  sp(
    "serviceberry",
    "Serviceberry",
    "Amelanchier canadensis",
    "shrub",
    ["naeast"],
    [T, B, G],
    2,
    [["berries", 0.6]],
  ),
  sp(
    "sumac",
    "Staghorn sumac",
    "Rhus typhina",
    "shrub",
    ["naeast"],
    [T, G],
    1.5,
    [["berries", 0.5]],
  ),
  sp("salal", "Salal", "Gaultheria shallon", "shrub", ["nawest"], [T, B], 1.5, [
    ["berries", 0.6],
  ]),
  sp(
    "chiltepin",
    "Chiltepin",
    "Capsicum annuum var. glabriusculum",
    "shrub",
    ["mesoamerica", "nawest"],
    [S, R],
    0.6,
    [["chilies", 0.6]],
  ),
  sp(
    "annatto",
    "Annatto",
    "Bixa orellana",
    "shrub",
    ["mesoamerica", "samerica"],
    [R],
    0.7,
    [["annatto", 0.7]],
  ),
  sp(
    "upland-cotton",
    "Upland cotton",
    "Gossypium hirsutum",
    "shrub",
    ["mesoamerica"],
    [S, V, R],
    0.5,
    [["cotton", 0.6]],
  ),
  sp(
    "sea-island-cotton",
    "Sea Island cotton",
    "Gossypium barbadense",
    "shrub",
    ["samerica"],
    [S, V, R],
    0.5,
    [["cotton", 0.6]],
  ),
  sp(
    "guava",
    "Guava",
    "Psidium guajava",
    "shrub",
    ["samerica", "mesoamerica"],
    [R],
    1,
    [["fruit", 0.5]],
  ),
  sp("coca", "Coca", "Erythroxylum coca", "shrub", ["samerica"], [R, T], 0.2, [
    ["coca", 0.7],
  ]),
  sp(
    "yerba-mate",
    "Yerba mate",
    "Ilex paraguariensis",
    "shrub",
    ["samerica"],
    [R, T],
    0.5,
    [["tea", 0.6]],
  ),
  sp(
    "wattle",
    "Golden wattle",
    "Acacia pycnantha",
    "shrub",
    ["australia"],
    [T, S, G],
    2,
    [["seeds", 0.5]],
  ),
  sp(
    "quandong",
    "Quandong",
    "Santalum acuminatum",
    "shrub",
    ["australia"],
    [S],
    1,
    [["fruit", 0.5]],
  ),
  sp("crowberry", "Crowberry", "Empetrum nigrum", "shrub", ["*"], [N, B], 1, [
    ["berries", 0.6],
  ]),

  sp(
    "sickle-bush",
    "Sickle bush",
    "Dichrostachys cinerea",
    "shrub",
    ["africa", "safrica"],
    [V, S, G],
    2,
    [["stick", 0.5]],
  ),
  sp(
    "raisin-bush",
    "Raisin bush",
    "Grewia flava",
    "shrub",
    ["africa", "safrica"],
    [V, S, D],
    2,
    [["berries", 0.6]],
  ),
  sp(
    "tea-tree",
    "Manuka",
    "Leptospermum scoparium",
    "shrub",
    ["australia"],
    [T, W, S],
    2,
    [["herbs", 0.3]],
  ),
  sp(
    "chilca",
    "Chilca",
    "Baccharis latifolia",
    "shrub",
    ["samerica"],
    [G, S, T],
    2.5,
    [["herbs", 0.3]],
  ),
  sp(
    "bush-clover",
    "Bush clover",
    "Lespedeza bicolor",
    "shrub",
    ["eastasia"],
    [G, T],
    2,
    [["fodder", 0.4]],
  ),
  sp(
    "kerria",
    "Kerria",
    "Kerria japonica",
    "shrub",
    ["eastasia"],
    [T],
    1.5,
    [],
  ),
  sp("hazel", "Hazel", "Corylus avellana", "shrub", ["europe"], [T, G], 2, [
    ["stick", 0.5],
  ]),

  // Heath.
  sp(
    "heather",
    "Heather",
    "Calluna vulgaris",
    "heath",
    ["europe"],
    [G, B, T, N],
    3,
    [],
  ),
  sp(
    "bell-heather",
    "Bell heather",
    "Erica cinerea",
    "heath",
    ["europe"],
    [G, S],
    1.5,
    [],
  ),
  sp(
    "bilberry",
    "Bilberry",
    "Vaccinium myrtillus",
    "heath",
    ["europe", "northasia"],
    [B, T, N],
    2,
    [["berries", 0.7, 2]],
  ),
  sp(
    "lavender",
    "French lavender",
    "Lavandula stoechas",
    "heath",
    ["med"],
    [S],
    2,
    [["herbs", 0.7]],
  ),
  sp(
    "azalea",
    "Azalea",
    "Rhododendron simsii",
    "heath",
    ["eastasia"],
    [T, R],
    2,
    [],
  ),
  sp(
    "rooibos",
    "Rooibos",
    "Aspalathus linearis",
    "heath",
    ["safrica"],
    [S],
    1,
    [["tea", 0.7]],
  ),
  sp(
    "lowbush-blueberry",
    "Lowbush blueberry",
    "Vaccinium angustifolium",
    "heath",
    ["naeast"],
    [B, T, G],
    2,
    [["berries", 0.7, 2]],
  ),
  sp(
    "manzanita",
    "Manzanita",
    "Arctostaphylos glauca",
    "heath",
    ["nawest"],
    [S, T],
    2,
    [["berries", 0.5]],
  ),
  sp(
    "lingonberry",
    "Lingonberry",
    "Vaccinium vitis-idaea",
    "heath",
    ["*"],
    [B, N],
    1.5,
    [["berries", 0.6]],
  ),

  // Scrub.
  sp("gorse", "Gorse", "Ulex europaeus", "scrub", ["europe"], [G, S], 2, [
    ["stick", 0.5],
  ]),
  sp(
    "juniper",
    "Common juniper",
    "Juniperus communis",
    "scrub",
    ["europe", "northasia", "westasia", "naeast", "nawest"],
    [B, N, G, S],
    1.5,
    [["berries", 0.3]],
  ),
  sp(
    "wormwood",
    "Wormwood",
    "Artemisia absinthium",
    "scrub",
    ["europe", "westasia"],
    [G, S],
    1.5,
    [["herbs", 0.6]],
  ),
  sp("rosemary", "Rosemary", "Salvia rosmarinus", "scrub", ["med"], [S], 2, [
    ["herbs", 0.9],
  ]),
  sp(
    "caper",
    "Caper",
    "Capparis spinosa",
    "scrub",
    ["med", "westasia", "southasia"],
    [S, D],
    1,
    [["capers", 0.6]],
  ),
  sp(
    "rockrose",
    "Cretan rockrose",
    "Cistus creticus",
    "scrub",
    ["med", "westasia"],
    [S],
    2,
    [["resin", 0.3]],
  ),
  sp(
    "ephedra",
    "Joint pine",
    "Ephedra distachya",
    "scrub",
    ["westasia", "med"],
    [D, S, G],
    0.5,
    [["ephedra", 0.6]],
  ),
  sp(
    "sagebrush",
    "Big sagebrush",
    "Artemisia tridentata",
    "scrub",
    ["nawest"],
    [S, G, D],
    3,
    [
      ["bast", 0.5],
      ["herbs", 0.4],
    ],
  ),
  sp(
    "yucca",
    "Banana yucca",
    "Yucca baccata",
    "scrub",
    ["nawest", "mesoamerica"],
    [D, S],
    1.5,
    [["bast", 1]],
  ),
  sp(
    "creosote",
    "Creosote bush",
    "Larrea tridentata",
    "scrub",
    ["nawest", "mesoamerica"],
    [D, S],
    2,
    [["resin", 0.4]],
  ),
  sp(
    "maguey",
    "Maguey",
    "Agave americana",
    "scrub",
    ["mesoamerica", "nawest"],
    [S, D],
    1.5,
    [["bast", 1, 2]],
  ),
  sp(
    "umbrella-thorn",
    "Umbrella thorn",
    "Vachellia tortilis",
    "scrub",
    ["africa", "westasia", "safrica"],
    [V, D, S],
    2,
    [["stick", 0.5]],
  ),
  sp(
    "saltbush",
    "Old man saltbush",
    "Atriplex nummularia",
    "scrub",
    ["australia"],
    [S, D],
    2,
    [["greens", 0.6]],
  ),
  sp(
    "pituri",
    "Pituri",
    "Duboisia hopwoodii",
    "scrub",
    ["australia"],
    [D, S],
    0.2,
    [["pituri", 0.6]],
  ),

  sp(
    "jujube",
    "Wild jujube",
    "Ziziphus nummularia",
    "scrub",
    ["southasia", "westasia"],
    [S, D, V],
    2,
    [["berries", 0.5]],
  ),
  sp(
    "sodom-apple",
    "Sodom apple",
    "Calotropis procera",
    "scrub",
    ["africa", "southasia", "westasia"],
    [S, V],
    1.5,
    [["bast", 0.5]],
  ),
  sp(
    "spekboom",
    "Spekboom",
    "Portulacaria afra",
    "scrub",
    ["safrica"],
    [S],
    2.5,
    [["greens", 0.6]],
  ),
  sp(
    "tola",
    "Tola",
    "Parastrephia lepidophylla",
    "scrub",
    ["samerica"],
    [G, N, D],
    2,
    [["stick", 0.6]],
  ),

  // Cacti belong to the Americas; the Old World's succulents are spurges,
  // aloes and ice plants that took the same shapes independently.
  sp(
    "prickly-pear",
    "Engelmann's prickly pear",
    "Opuntia engelmannii",
    "scrub",
    ["nawest", "mesoamerica"],
    [D, S],
    3,
    [["berries", 0.6]],
  ),
  sp(
    "nopal",
    "Nopal",
    "Opuntia ficus-indica",
    "scrub",
    ["mesoamerica"],
    [S, D],
    2.5,
    [
      ["greens", 0.6],
      ["berries", 0.5],
    ],
  ),
  sp(
    "cholla",
    "Teddy-bear cholla",
    "Cylindropuntia bigelovii",
    "scrub",
    ["nawest"],
    [D],
    2,
    [],
  ),
  sp(
    "barrel-cactus",
    "Fishhook barrel cactus",
    "Ferocactus wislizeni",
    "scrub",
    ["nawest", "mesoamerica"],
    [D, S],
    1.5,
    [["berries", 0.4]],
  ),
  sp(
    "hedgehog-cactus",
    "Strawberry hedgehog",
    "Echinocereus engelmannii",
    "scrub",
    ["nawest"],
    [D, S],
    1.5,
    [["berries", 0.5]],
  ),
  sp(
    "ocotillo",
    "Ocotillo",
    "Fouquieria splendens",
    "scrub",
    ["nawest", "mesoamerica"],
    [D],
    2,
    [["stick", 0.8]],
  ),
  sp(
    "organ-pipe",
    "Organ pipe cactus",
    "Stenocereus thurberi",
    "scrub",
    ["nawest", "mesoamerica"],
    [D, S],
    1,
    [["berries", 0.5]],
  ),
  sp(
    "pasacana",
    "Pasacana",
    "Leucostele atacamensis",
    "scrub",
    ["samerica"],
    [D, N],
    1.5,
    [["stick", 0.6]],
  ),
  sp(
    "woolly-cushion",
    "Woolly puna cactus",
    "Austrocylindropuntia floccosa",
    "scrub",
    ["samerica"],
    [N, D],
    1,
    [["berries", 0.3]],
  ),
  sp(
    "aloe-vera",
    "Aloe vera",
    "Aloe vera",
    "scrub",
    ["westasia", "africa"],
    [D, S],
    1.5,
    [["herbs", 0.6]],
  ),
  sp(
    "cape-aloe",
    "Cape aloe",
    "Aloe ferox",
    "scrub",
    ["safrica"],
    [S, V, D],
    2,
    [["herbs", 0.6]],
  ),
  sp(
    "desert-rose",
    "Desert rose",
    "Adenium obesum",
    "scrub",
    ["africa", "westasia"],
    [D, S, V],
    1,
    [],
  ),
  sp(
    "welwitschia",
    "Welwitschia",
    "Welwitschia mirabilis",
    "scrub",
    ["safrica"],
    [D],
    0.6,
    [],
  ),
  sp(
    "resin-spurge",
    "Resin spurge",
    "Euphorbia resinifera",
    "scrub",
    ["med"],
    [S, D],
    1,
    [["resin", 0.5]],
  ),
  sp(
    "leafless-spurge",
    "Leafless spurge",
    "Euphorbia caducifolia",
    "scrub",
    ["southasia"],
    [D, S],
    2,
    [["resin", 0.3]],
  ),
  sp(
    "pigface",
    "Pigface",
    "Carpobrotus rossii",
    "scrub",
    ["australia"],
    [S, D],
    1.5,
    [["berries", 0.4]],
  ),
  sp(
    "sour-fig",
    "Sour fig",
    "Carpobrotus edulis",
    "scrub",
    ["safrica"],
    [S, D],
    1.5,
    [["berries", 0.5]],
  ),
  sp(
    "houseleek",
    "Houseleek",
    "Sempervivum tectorum",
    "scrub",
    ["europe"],
    [G, S],
    0.5,
    [["herbs", 0.4]],
  ),

  // Grasses.
  sp(
    "cocksfoot",
    "Cock's-foot",
    "Dactylis glomerata",
    "grass",
    ["europe", "northasia", "westasia"],
    undefined,
    3,
    [["fodder", 0.4]],
  ),
  sp(
    "tufted-hair-grass",
    "Tufted hair-grass",
    "Deschampsia cespitosa",
    "grass",
    ["europe", "northasia", "naeast", "nawest"],
    [W, G, B, N],
    2,
    [["straw", 0.5]],
  ),
  sp("esparto", "Esparto", "Stipa tenacissima", "grass", ["med"], [S, G], 2, [
    ["grass-fibre", 1],
  ]),
  sp(
    "thatching-grass",
    "Thatching grass",
    "Hyparrhenia hirta",
    "grass",
    ["med", "africa", "safrica"],
    [S, V, G],
    2,
    [["straw", 0.6]],
  ),
  sp(
    "feather-grass",
    "Feather grass",
    "Stipa capillata",
    "grass",
    ["westasia", "europe", "northasia"],
    [G, S],
    2,
    [["grass-fibre", 0.4]],
  ),
  sp(
    "munj",
    "Munj grass",
    "Saccharum bengalense",
    "grass",
    ["southasia"],
    undefined,
    1.5,
    [["grass-fibre", 0.8]],
  ),
  sp(
    "kusha",
    "Kusha grass",
    "Desmostachya bipinnata",
    "grass",
    ["southasia", "westasia", "africa"],
    undefined,
    1.5,
    [["grass-fibre", 0.7]],
  ),
  sp(
    "silvergrass",
    "Chinese silver grass",
    "Miscanthus sinensis",
    "grass",
    ["eastasia"],
    undefined,
    3,
    [["straw", 0.7]],
  ),
  sp(
    "cogon",
    "Cogon grass",
    "Imperata cylindrica",
    "grass",
    ["eastasia", "seasia", "southasia", "africa", "safrica"],
    undefined,
    2,
    [["straw", 0.8]],
  ),
  sp(
    "red-oat-grass",
    "Red oat grass",
    "Themeda triandra",
    "grass",
    ["africa", "australia", "safrica"],
    [V, G],
    3,
    [["straw", 0.6]],
  ),
  sp(
    "wild-sorghum",
    "Wild sorghum",
    "Sorghum arundinaceum",
    "grass",
    ["africa"],
    [V, G],
    0.6,
    [["grain", 0.4]],
  ),
  sp(
    "big-bluestem",
    "Big bluestem",
    "Andropogon gerardii",
    "grass",
    ["naeast"],
    undefined,
    3,
    [["fodder", 0.5]],
  ),
  sp(
    "sweetgrass",
    "Sweetgrass",
    "Hierochloe odorata",
    "grass",
    ["naeast", "nawest", "europe", "northasia"],
    [G, W],
    1,
    [["grass-fibre", 0.8]],
  ),
  sp(
    "ricegrass",
    "Indian ricegrass",
    "Achnatherum hymenoides",
    "grass",
    ["nawest"],
    [S, G],
    2,
    [["seeds", 0.6]],
  ),
  sp(
    "teosinte",
    "Teosinte",
    "Zea mays subsp. parviglumis",
    "grass",
    ["mesoamerica"],
    [S, G, R],
    0.4,
    [["grain", 0.4]],
  ),
  sp(
    "zacaton",
    "Zacatón",
    "Muhlenbergia macroura",
    "grass",
    ["mesoamerica"],
    undefined,
    2,
    [["grass-fibre", 0.8]],
  ),
  sp("ichu", "Ichu", "Jarava ichu", "grass", ["samerica"], undefined, 2, [
    ["grass-fibre", 0.8],
  ]),
  sp(
    "pampas-grass",
    "Pampas grass",
    "Cortaderia selloana",
    "grass",
    ["samerica"],
    [G, W],
    2,
    [["straw", 0.6]],
  ),
  sp(
    "spinifex",
    "Spinifex",
    "Triodia pungens",
    "grass",
    ["australia"],
    [S],
    2,
    [
      ["resin", 0.4],
      ["grass-fibre", 0.5],
    ],
  ),
  sp(
    "native-millet",
    "Native millet",
    "Panicum decompositum",
    "grass",
    ["australia"],
    [G, S],
    1.5,
    [["seeds", 0.6]],
  ),

  // Reeds, rushes and sedges.
  sp(
    "common-reed",
    "Common reed",
    "Phragmites australis",
    "reed",
    ["*"],
    undefined,
    3,
    [["reeds", 1]],
  ),
  sp(
    "bulrush",
    "Bulrush",
    "Typha latifolia",
    "reed",
    [
      "europe",
      "northasia",
      "westasia",
      "eastasia",
      "naeast",
      "nawest",
      "mesoamerica",
    ],
    undefined,
    2,
    [
      ["rushes", 1],
      ["roots", 0.3],
    ],
  ),
  sp(
    "soft-rush",
    "Soft rush",
    "Juncus effusus",
    "reed",
    ["europe", "northasia", "med", "eastasia", "naeast", "nawest"],
    undefined,
    2,
    [["rushes", 1]],
  ),
  sp("sedge", "Tussock sedge", "Carex stricta", "reed", ["*"], undefined, 1.5, [
    ["rushes", 0.8],
  ]),
  sp(
    "papyrus",
    "Papyrus",
    "Cyperus papyrus",
    "reed",
    ["africa", "med", "westasia"],
    undefined,
    2,
    [["papyrus", 1]],
  ),
  sp(
    "igusa",
    "Mat rush",
    "Juncus decipiens",
    "reed",
    ["eastasia"],
    undefined,
    1.5,
    [["rushes", 1]],
  ),
  sp(
    "wild-rice-asia",
    "Wild rice",
    "Oryza rufipogon",
    "reed",
    ["southasia", "seasia", "eastasia"],
    undefined,
    1,
    [["grain", 0.5]],
  ),
  sp(
    "wild-rice",
    "Northern wild rice",
    "Zizania palustris",
    "reed",
    ["naeast"],
    undefined,
    1,
    [["grain", 0.6]],
  ),
  sp(
    "tule",
    "Tule",
    "Schoenoplectus acutus",
    "reed",
    ["nawest", "mesoamerica"],
    undefined,
    2,
    [["reeds", 1]],
  ),
  sp(
    "totora",
    "Totora",
    "Schoenoplectus californicus",
    "reed",
    ["samerica"],
    undefined,
    2,
    [["reeds", 1]],
  ),
  sp(
    "cumbungi",
    "Cumbungi",
    "Typha domingensis",
    "reed",
    ["australia", "africa", "southasia", "safrica"],
    undefined,
    2,
    [
      ["rushes", 1],
      ["roots", 0.4],
    ],
  ),
  sp(
    "cape-thatching-reed",
    "Cape thatching reed",
    "Elegia tectorum",
    "reed",
    ["safrica"],
    undefined,
    2,
    [["reeds", 1]],
  ),
  sp(
    "mat-rush",
    "Spiny mat-rush",
    "Lomandra longifolia",
    "reed",
    ["australia"],
    undefined,
    1.5,
    [["rushes", 1]],
  ),

  // Ferns.
  sp("bracken", "Bracken", "Pteridium aquilinum", "fern", ["*"], undefined, 3, [
    ["straw", 0.5],
  ]),
  sp(
    "ostrich-fern",
    "Ostrich fern",
    "Matteuccia struthiopteris",
    "fern",
    ["naeast", "nawest", "europe", "northasia", "eastasia"],
    [T, B, W],
    1.5,
    [["greens", 0.7]],
  ),
  sp(
    "vegetable-fern",
    "Vegetable fern",
    "Diplazium esculentum",
    "fern",
    ["seasia", "southasia"],
    undefined,
    2,
    [["greens", 1]],
  ),
  sp(
    "nardoo",
    "Nardoo",
    "Marsilea drummondii",
    "fern",
    ["australia"],
    [W, G],
    1,
    [["seeds", 0.7]],
  ),
];

const bySprite: Record<string, FloraForm> = {
  flowers: "bloom",
  "nature-understory-flowering-heath": "heath",
  "nature-understory-low-heath": "heath",
  bush: "shrub",
  "nature-understory-low-leafy-shrub": "shrub",
  "ecology-berry-bush": "shrub",
  "nature-understory-tropical-ginger": "shrub",
  "nature-understory-sagebrush": "scrub",
  "nature-dry-scrub-small": "scrub",
  "nature-dry-scrub-medium": "scrub",
  "nature-dry-thorn-scrub": "scrub",
  grass: "grass",
  "ecology-grazing": "grass",
  "nature-understory-dry-bunchgrass": "grass",
  reeds: "reed",
  "nature-understory-sedge": "reed",
  "nature-understory-woodland-fern": "fern",
};
/** The form a decoration sprite stands for, if it is something we can name. */
export const floraForm = (sprite: string | undefined) =>
  sprite ? bySprite[sprite] : undefined;
/** Heath and scrub borrow from shrubs where a region has none of their own. */
const fallback: Partial<Record<FloraForm, FloraForm>> = {
  heath: "shrub",
  scrub: "shrub",
};
const neighbours: Partial<Record<Ecology, Ecology[]>> = {
  grassland: [T, V, S],
  "dry-scrub": [V, G, D],
  "temperate-woodland": [G, B, W],
  "boreal-woodland": [N, T],
  "tropical-woodland": [V, W],
  wetland: [T, R, G],
  savanna: [S, G, R],
  tundra: [B],
  desert: [S, V],
};
const pools = new Map<string, Species[]>();
function pool(
  form: FloraForm,
  region: FloraRegion,
  ecology: Ecology,
): Species[] {
  const key = `${form}:${region}:${ecology}`;
  let found = pools.get(key);
  if (found) return found;
  const regions = alias[region] ?? [region];
  const here = (s: Species) =>
    s.form === form && s.range.some((r) => r === "*" || regions.includes(r));
  const fits = (s: Species) => !s.eco || s.eco.includes(ecology);
  const local = flora.filter(here);
  found = local.filter(fits);
  // Too few fit to keep a rarity rare: let in what grows in the nearest
  // ecologies, nearest first, and only then the rest of the region. A desert
  // borrows from dry scrub before it borrows a forest ginger.
  const weight = () => found!.reduce((n, s) => n + s.weight, 0);
  for (const near of neighbours[ecology] ?? []) {
    if (weight() >= 4) break;
    found = [
      ...new Set([
        ...found,
        ...local.filter((s) => s.eco?.includes(near) && !s.range.includes("*")),
      ]),
    ];
  }
  if (!found.length) found = local.filter((s) => !s.range.includes("*"));
  if (!found.length && fallback[form])
    found = pool(fallback[form]!, region, ecology);
  pools.set(key, found);
  return found;
}
/** A weighted pick. `roll` is 0-1. */
export function pickSpecies(
  form: FloraForm,
  region: FloraRegion,
  ecology: Ecology,
  roll: number,
): Species | undefined {
  const list = pool(form, region, ecology);
  if (!list.length) return undefined;
  const total = list.reduce((n, s) => n + s.weight, 0);
  let r = roll * total;
  for (const s of list) if ((r -= s.weight) < 0) return s;
  return list.at(-1);
}
/** The plant standing on a cell, from its decoration sprite. */
export function speciesAt(
  sprite: string | undefined,
  region: FloraRegion,
  ecology: Ecology,
  x: number,
  y: number,
) {
  const form = floraForm(sprite);
  return form && pickSpecies(form, region, ecology, hash(x, y, 811));
}
export const speciesById = new Map(flora.map((s) => [s.id, s]));
export const bloomSpecies = flora.filter((s) => s.look);
export const speciesLabel = (s: Species) => `${s.common} (${s.latin})`;

const def = (
  id: ItemId,
  name: string,
  sprite: string,
  value: number,
  description: string,
  extra: Partial<ItemDef> = {},
): ItemDef => ({ id, name, sprite, value, description, ...extra });
/** What cut plants give up. The sprite is the world art when dropped. */
export const floraItems: Record<ItemId, ItemDef> = Object.fromEntries(
  [
    def(
      "bast",
      "Bast fibre",
      "flax",
      1,
      "Stripped stem fibre. Twists into cord.",
      { flammable: true },
    ),
    def(
      "rushes",
      "Rushes",
      "reeds",
      1,
      "Pith-filled stems for mats, baskets and rushlights.",
      { flammable: true, floats: true },
    ),
    def(
      "grass-fibre",
      "Grass fibre",
      "grain",
      1,
      "Tough leaf blades for rope, sandals and baskets.",
      { flammable: true },
    ),
    def(
      "papyrus",
      "Papyrus stems",
      "reeds",
      2,
      "Split, laid and pressed, the pith makes a writing sheet.",
      { flammable: true, floats: true },
    ),
    def(
      "cotton",
      "Cotton bolls",
      "flowers",
      3,
      "Seed fibre, ready for ginning and spinning.",
      { flammable: true },
    ),
    def("greens", "Greens", "flowers", 1, "Tender leaves and shoots.", {
      edible: 3,
    }),
    def(
      "roots",
      "Edible roots",
      "flowers",
      1,
      "Starchy roots, better roasted.",
      { edible: 5 },
    ),
    def(
      "bulbs",
      "Camas bulbs",
      "flowers",
      2,
      "Pit-roasted for a day, they turn sweet.",
      { edible: 6 },
    ),
    def("seeds", "Wild seeds", "grain", 1, "Parched and ground into meal.", {
      edible: 4,
    }),
    def(
      "capers",
      "Caper buds",
      "flowers",
      2,
      "Unopened buds, pickled in brine.",
      { edible: 2 },
    ),
    def(
      "chilies",
      "Chiltepin peppers",
      "ecology-berries-item",
      2,
      "Tiny and fierce.",
      { edible: 1 },
    ),
    def(
      "roselle",
      "Roselle calyces",
      "ecology-berries-item",
      2,
      "Tart red calyces. Steeped for drink or dye.",
      { edible: 2 },
    ),
    def(
      "chamomile",
      "Chamomile flowers",
      "flowers",
      2,
      "Dried and steeped for a calming tisane.",
    ),
    def("tea", "Tea leaves", "flowers", 3, "Leaves for steeping."),
    def(
      "coffee",
      "Coffee cherries",
      "ecology-berries-item",
      4,
      "The seeds are roasted and brewed.",
    ),
    def(
      "woad",
      "Woad leaves",
      "flowers",
      3,
      "Fermented in a vat, they dye cloth blue.",
    ),
    def(
      "weld",
      "Weld",
      "flowers",
      3,
      "Dyer's rocket. The brightest fast yellow.",
    ),
    def(
      "madder",
      "Madder root",
      "flowers",
      4,
      "Ground root that dyes turkey red.",
    ),
    def(
      "indigo",
      "Indigo leaves",
      "flowers",
      5,
      "Steeped and beaten, they yield blue dye cakes.",
    ),
    def(
      "safflower",
      "Safflower petals",
      "flowers",
      4,
      "Dye for yellow and, with care, rose-red.",
    ),
    def(
      "henna",
      "Henna leaves",
      "flowers",
      3,
      "Dried and powdered, a red-orange stain for skin and hair.",
    ),
    def(
      "annatto",
      "Annatto seeds",
      "ecology-berries-item",
      3,
      "Red-orange dye and body paint.",
    ),
    def("turmeric", "Turmeric root", "flowers", 3, "A yellow dye and a spice."),
    def(
      "goldenrod",
      "Goldenrod tops",
      "flowers",
      2,
      "Flower heads that dye wool yellow.",
    ),
    def(
      "gromwell",
      "Gromwell root",
      "flowers",
      5,
      "Murasaki root: a costly purple dye.",
    ),
    def(
      "saffron",
      "Saffron",
      "flowers",
      20,
      "Hand-picked stigmas. Worth more than their weight in silver.",
    ),
    def(
      "poppy-pods",
      "Poppy pods",
      "flowers",
      12,
      "Scored green, they weep opium latex.",
    ),
    def(
      "cannabis",
      "Cannabis flowers",
      "flowers",
      10,
      "Resinous flowering tops.",
    ),
    def(
      "coca",
      "Coca leaves",
      "flowers",
      8,
      "Chewed with lime against hunger and cold.",
    ),
    def("khat", "Khat leaves", "flowers", 8, "Chewed fresh as a stimulant."),
    def(
      "tobacco",
      "Tobacco leaves",
      "flowers",
      6,
      "Dried for smoking and ceremony.",
    ),
    def(
      "pituri",
      "Pituri leaves",
      "flowers",
      10,
      "Cured and chewed; traded across the continent.",
    ),
    def(
      "ephedra",
      "Ephedra stems",
      "reeds",
      5,
      "Bitter green stems, pressed for a stimulant drink.",
    ),
  ].map((d) => [d.id, d]),
);
