import type { Festival, Occasion } from "./types";

type Bounds = [number, number, number, number];
const WCA = ["west-central-african" as const];
const ESA = ["east-southern-african" as const];

const NOK = { years: [-900, 0] as [number, number], bounds: [6, 8, 10, 11] as Bounds, cultures: WCA };
const IFE = { years: [1000, 1900] as [number, number], bounds: [4, 7, 5.2, 8] as Bounds, cultures: WCA };
const BENIN = { years: [1300, 1950] as [number, number], bounds: [5, 5.8, 6.4, 7] as Bounds, cultures: WCA };
const IGBO = { years: [900, 1950] as [number, number], bounds: [6.4, 4.4, 8.8, 7.2] as Bounds, cultures: WCA };
const AKAN = { years: [1400, 1950] as [number, number], bounds: [-3.5, 4.7, 1, 8.5] as Bounds, cultures: WCA };
const ASANTE = { years: [1680, 1950] as [number, number], bounds: [-3, 5.8, 0.5, 8] as Bounds, cultures: WCA };
const MANDE = { years: [1230, 1950] as [number, number], bounds: [-17, 10, -2, 16] as Bounds, cultures: WCA };
const SAHEL_ISLAM = { years: [1100, 1950] as [number, number], bounds: [-17, 11, 15, 18] as Bounds, cultures: WCA };
const TIMBUKTU = { years: [1325, 1600] as [number, number], bounds: [-5, 15.5, -1, 18] as Bounds, cultures: WCA };
const DOGON = { years: [1400, 1950] as [number, number], bounds: [-4, 13.8, -2.8, 15.2] as Bounds, cultures: WCA };
const HAUSA = { years: [1000, 1950] as [number, number], bounds: [5, 10.5, 11, 14] as Bounds, cultures: WCA };
const FULBE = { years: [1400, 1950] as [number, number], bounds: [-17, 9, 15, 17] as Bounds, cultures: WCA };
const NIGER_FISHERS = { years: [800, 1950] as [number, number], bounds: [-6, 12, 4, 17.5] as Bounds, cultures: WCA };
const KONGO = { years: [1390, 1900] as [number, number], bounds: [12, -8, 17, -3.5] as Bounds, cultures: WCA };
const KONGO_CHRISTIAN = { years: [1510, 1860] as [number, number], bounds: [12, -8, 17, -3.5] as Bounds, cultures: WCA };
const KUBA = { years: [1620, 1950] as [number, number], bounds: [20, -6, 23.5, -3.5] as Bounds, cultures: WCA };
const ITURI = { years: [-3000, 1950] as [number, number], bounds: [26, -1, 31, 4] as Bounds, cultures: WCA };
const PALM_BELT = { years: [-500, 1950] as [number, number], bounds: [-17, -10, 30, 10] as Bounds, cultures: WCA };
const BANTU_IRON = { years: [-500, 1950] as [number, number], bounds: [-18, -35, 52, 18] as Bounds };
const GOLD_COAST_COCOA = { years: [1890, 1950] as [number, number], bounds: [-3.5, 5, 1, 7.5] as Bounds, cultures: WCA };
const WEST_MISSION = { years: [1880, 1950] as [number, number], bounds: [-18, -12, 32, 9] as Bounds, cultures: WCA };

const AKSUM = { years: [100, 700] as [number, number], bounds: [37, 12.5, 41, 16] as Bounds, cultures: ESA };
const AKSUM_PAGAN = { years: [100, 340] as [number, number], bounds: [37, 12.5, 41, 16] as Bounds, cultures: ESA };
const ETHIOPIA = { years: [340, 1950] as [number, number], bounds: [35, 9, 43, 16] as Bounds, cultures: ESA };
const OROMO = { years: [1500, 1950] as [number, number], bounds: [34, 3, 43, 9] as Bounds, cultures: ESA };
const SWAHILI = { years: [900, 1950] as [number, number], bounds: [38.5, -11, 42, -1.5] as Bounds, cultures: ESA };
const GREAT_LAKES = { years: [1400, 1950] as [number, number], bounds: [29, -3, 34, 2.5] as Bounds, cultures: ESA };
const MAASAI = { years: [1600, 1950] as [number, number], bounds: [34, -6, 38, 1] as Bounds, cultures: ESA };
const MADAGASCAR = { years: [1700, 1950] as [number, number], bounds: [45, -24, 50, -16] as Bounds, cultures: ESA };
const KALAHARI = { years: [-20000, 1950] as [number, number], bounds: [16, -28, 26, -17] as Bounds, cultures: ESA };
const DRAKENSBERG = { years: [-3000, 1500] as [number, number], bounds: [27.5, -31, 30.5, -28] as Bounds, cultures: ESA };
const MAPUNGUBWE = { years: [1075, 1220] as [number, number], bounds: [28.5, -23, 30.5, -21.5] as Bounds, cultures: ESA };
const SHONA = { years: [1100, 1950] as [number, number], bounds: [28, -22, 33, -15] as Bounds, cultures: ESA };
const GREAT_ZIMBABWE = { years: [1200, 1450] as [number, number], bounds: [29.5, -21, 32.5, -19] as Bounds, cultures: ESA };
const NGUNI_SOTHO = { years: [1400, 1950] as [number, number], bounds: [24, -34, 33, -24] as Bounds, cultures: ESA };
const ZULU = { years: [1780, 1950] as [number, number], bounds: [29, -31, 32.9, -27] as Bounds, cultures: ESA };
const SOTHO = { years: [1600, 1950] as [number, number], bounds: [27, -30.7, 29.5, -28.5] as Bounds, cultures: ESA };
const RAND = { years: [1886, 1950] as [number, number], bounds: [26, -27, 29, -25.5] as Bounds, cultures: ESA };
const SOUTH_MISSION = { years: [1880, 1950] as [number, number], bounds: [18, -35, 38, -8] as Bounds, cultures: ESA };

export const africaOccasions: Occasion[] = [
  {
    id: "day.nok.terracotta",
    label: "Modelling a terracotta head",
    scope: NOK,
    evidence: "inferred",
    when: [{ type: "work", match: /pott|clay|kiln/i }, { type: "chance", p: 0.3 }],
    weight: 5,
    part: "midday",
    place: "work",
    activity: "work",
    minutes: 60,
    text: "Model a clay head with pierced eyes and piled hair, for firing.",
    note: "Nok heads are hollow, with D-shaped or triangular eyes pierced through the pupil.",
    sources: ["https://en.wikipedia.org/wiki/Nok_culture"],
  },
  {
    id: "day.africa.furnace-medicine",
    label: "Medicines for the smelting furnace",
    scope: BANTU_IRON,
    evidence: "documented",
    when: [{ type: "work", match: /smith|smelt|iron|forge/i }, { type: "chance", p: 0.25 }],
    weight: 6,
    part: "morning",
    place: "work",
    activity: "work",
    minutes: 45,
    text: "Bury medicines under the furnace floor and sleep apart from women before the smelt.",
    note: "Across Bantu Africa the furnace was treated as a womb giving birth to iron, and smelters kept sexual taboos.",
    sources: ["https://en.wikipedia.org/wiki/Iron_metallurgy_in_Africa"],
    serves: ["mastery"],
  },
  {
    id: "day.africa.bonfire-pots",
    label: "Firing pots in the open",
    scope: { years: [-8000, 1950], cultures: [...WCA, ...ESA] },
    evidence: "documented",
    when: [{ type: "work", match: /pott|clay/i }, { type: "sex", is: "female" }, { type: "chance", p: 0.3 }],
    weight: 5,
    part: "midday",
    place: "edge",
    activity: "work",
    minutes: 60,
    text: "Fire the dried pots in the open under a heap of grass and bark.",
    note: "Most African pottery was built by women without a wheel and fired in a bonfire rather than a kiln.",
    sources: ["https://en.wikipedia.org/wiki/African_pottery"],
  },
  {
    id: "day.africa.palm-wine",
    label: "Tapping the palm",
    scope: PALM_BELT,
    evidence: "documented",
    when: [{ type: "work", match: /palm|tap|wine|farm/i }, { type: "chance", p: 0.3 }],
    weight: 4,
    part: "morning",
    place: "wild",
    activity: "gather",
    minutes: 40,
    carry: "vessel",
    text: "Climb the palm for the night's sap and pour the first drops for the ancestors.",
    sources: ["https://en.wikipedia.org/wiki/Palm_wine"],
  },
  {
    id: "day.ife.beads",
    label: "Drawing glass beads",
    scope: IFE,
    evidence: "documented",
    when: [{ type: "work", match: /bead|glass|craft|smith/i }, { type: "chance", p: 0.3 }],
    weight: 5,
    part: "midday",
    place: "work",
    activity: "work",
    minutes: 50,
    text: "Draw blue glass beads from the crucibles for the Ooni's regalia.",
    note: "Ife made its own glass beads in crucibles, found in quantity at Igbo Olokun.",
    sources: ["https://en.wikipedia.org/wiki/Ile-Ife"],
  },
  {
    id: "day.benin.court",
    label: "Attendance at the Oba's palace",
    scope: BENIN,
    evidence: "documented",
    when: [{ type: "rank", any: ["gentry", "elite"] }, { type: "chance", p: 0.3 }, { type: "adult" }],
    weight: 5,
    part: "morning",
    place: "gathering",
    activity: "visit",
    minutes: 60,
    text: "Kneel among the chiefs in the Oba's audience court, beneath the brass plaques.",
    sources: ["https://en.wikipedia.org/wiki/Kingdom_of_Benin"],
  },
  {
    id: "day.benin.igun",
    label: "Casting for the palace",
    scope: BENIN,
    evidence: "documented",
    when: [{ type: "work", match: /cast|brass|bronze|smith/i }, { type: "chance", p: 0.35 }],
    weight: 6,
    part: "midday",
    place: "work",
    activity: "work",
    minutes: 60,
    text: "Build the wax model of a commemorative head for the Oba's ancestral altar.",
    note: "The Igun Eronmwon guild cast only for the palace, by the lost-wax method.",
    sources: ["https://en.wikipedia.org/wiki/Benin_Bronzes"],
    serves: ["mastery"],
  },
  {
    id: "day.igbo.nkwo",
    label: "Nkwo market",
    scope: IGBO,
    evidence: "documented",
    when: [{ type: "cycle", every: 4, on: 3 }, { type: "adult" }],
    weight: 6,
    part: "midday",
    place: "market",
    activity: "visit",
    minutes: 50,
    carry: "basket",
    text: "Carry yams and cassava to the Nkwo market: it comes round every fourth day.",
    note: "The Igbo week is four market days, Eke, Orie, Afo and Nkwo; each town's market keeps one of them.",
    sources: ["https://en.wikipedia.org/wiki/Igbo_calendar"],
  },
  {
    id: "day.igbo.eke-rest",
    label: "Keeping off the farm on Eke",
    scope: IGBO,
    evidence: "inferred",
    when: [{ type: "cycle", every: 4, on: 0 }, { type: "work", match: /farm|yam|field|till/i }],
    weight: 5,
    part: "morning",
    place: "home",
    activity: "rest",
    minutes: 40,
    text: "Leave the farm untouched: it is Eke, and the earth is Ala's today.",
    note: "Many Igbo towns forbade farm work on one day of the four, usually the day sacred to Ala.",
    sources: ["https://en.wikipedia.org/wiki/Igbo_calendar"],
  },
  {
    id: "day.igbo.kola",
    label: "Breaking kola with a friend",
    scope: IGBO,
    evidence: "documented",
    when: [{ type: "kin", kind: "friend" }, { type: "sex", is: "male" }, { type: "chance", p: 0.3 }],
    weight: 5,
    part: "evening",
    place: { kin: "friend" },
    activity: "visit",
    minutes: 40,
    text: "Break kola with {friend} in the obi and pray over it before talking.",
    note: "He who brings kola brings life: the host presents it, the eldest blesses and breaks it.",
    sources: ["https://en.wikipedia.org/wiki/Kola_nut"],
  },
  {
    id: "day.igbo.ozo",
    label: "Sitting with the ozo titleholders",
    scope: IGBO,
    evidence: "documented",
    when: [{ type: "rank", any: ["gentry", "elite"] }, { type: "sex", is: "male" }, { type: "chance", p: 0.25 }],
    weight: 4,
    part: "evening",
    place: "gathering",
    activity: "visit",
    minutes: 60,
    text: "Sit with the red-capped ozo men to judge a land dispute.",
    sources: ["https://en.wikipedia.org/wiki/Igbo_people"],
  },
  {
    id: "day.igbo.bride-wine",
    label: "Palm wine for a bride's family",
    scope: IGBO,
    evidence: "documented",
    when: [{ type: "seek-match" }],
    weight: 6,
    part: "evening",
    place: "door",
    activity: "visit",
    minutes: 60,
    carry: "vessel",
    text: "Carry a pot of palm wine to the girl's father to open talk of {child}'s marriage.",
    note: "Igbo marriage ends with the groom's party bringing wine, igba nkwu, but talks open with it too.",
    sources: ["https://en.wikipedia.org/wiki/Palm_wine"],
    serves: ["marriage-hope"],
  },
  {
    id: "day.akan.gold-weights",
    label: "Weighing gold dust",
    scope: AKAN,
    evidence: "documented",
    when: [{ type: "work", match: /gold|trad|merchant|smith/i }, { type: "chance", p: 0.35 }],
    weight: 6,
    part: "midday",
    place: "market",
    activity: "work",
    minutes: 40,
    text: "Weigh a customer's gold dust against your brass weights, blowing off the sand.",
    note: "Every Akan trader carried a box of cast-brass weights, scales and spoons for gold dust.",
    sources: ["https://en.wikipedia.org/wiki/Akan_goldweights"],
  },
  {
    id: "day.akan.kente",
    label: "Weaving kente strips",
    scope: ASANTE,
    evidence: "documented",
    when: [{ type: "work", match: /weav|cloth/i }, { type: "chance", p: 0.4 }],
    weight: 6,
    part: "midday",
    place: "work",
    activity: "work",
    minutes: 70,
    text: "Weave narrow silk-shot strips of kente at your treadle loom for a chief's cloth.",
    note: "Bonwire weavers unravelled imported silk to weave the Asantehene's cloths.",
    sources: ["https://en.wikipedia.org/wiki/Kente_cloth"],
    serves: ["mastery"],
  },
  {
    id: "day.akan.stool-rites",
    label: "Feeding the blackened stools",
    scope: ASANTE,
    evidence: "documented",
    when: [{ type: "cycle", every: 13, on: 0 }, { type: "rank", any: ["gentry", "elite"] }],
    weight: 10,
    part: "morning",
    place: "sanctuary",
    activity: "visit",
    minutes: 50,
    carry: "vessel",
    text: "Offer mashed yam and rum to the blackened stools of the ancestors: it is Adae.",
    note: "Adae falls twice in the 42-day adaduanan cycle, when the stool-house is opened to feed the dead chiefs.",
    sources: ["https://en.wikipedia.org/wiki/Akan_calendar"],
    serves: ["remember-dead"],
  },
  {
    id: "day.akan.funeral-anniversary",
    label: "An anniversary funeral",
    scope: AKAN,
    evidence: "documented",
    when: [{ type: "anniversary", kind: "died" }],
    weight: 14,
    part: "evening",
    place: "gathering",
    activity: "visit",
    minutes: 70,
    text: "Wear dark adinkra cloth and pour drink on the ground for your {dead}.",
    note: "Akan families hold an anniversary funeral a year on, with drumming and a cloth stamped with adinkra.",
    sources: ["https://en.wikipedia.org/wiki/Adinkra_symbols"],
    serves: ["remember-dead"],
  },
  {
    id: "day.gold-coast.cocoa",
    label: "Carrying cocoa to the buyer",
    scope: GOLD_COAST_COCOA,
    evidence: "documented",
    when: [{ type: "work", match: /farm|cocoa|field/i }, { type: "season", any: ["autumn", "winter"] }, { type: "chance", p: 0.3 }],
    weight: 5,
    part: "midday",
    place: "edge",
    activity: "haul",
    minutes: 60,
    carry: "bundle",
    text: "Head-load your dried cocoa beans to the buying station on the lorry road.",
    note: "By 1911 the Gold Coast was the world's largest cocoa exporter, nearly all of it from African smallholders.",
    sources: ["https://en.wikipedia.org/wiki/Tetteh_Quarshie"],
  },
  {
    id: "day.mande.jeli",
    label: "Reciting Sunjata",
    scope: MANDE,
    evidence: "documented",
    when: [{ type: "work", match: /griot|jeli|praise|sing|bard|music|drum/i }, { type: "chance", p: 0.4 }],
    weight: 7,
    part: "evening",
    place: "door",
    activity: "visit",
    minutes: 80,
    text: "Sing the deeds of Sunjata at a patron's door, naming his ancestors one by one.",
    note: "Jeliw are hereditary, and a family's genealogy is theirs to keep and to praise for a fee.",
    sources: ["https://en.wikipedia.org/wiki/Epic_of_Sundiata", "https://en.wikipedia.org/wiki/Griot"],
    serves: ["mastery"],
  },
  {
    id: "day.sahel.friday",
    label: "Friday prayer",
    scope: SAHEL_ISLAM,
    evidence: "documented",
    when: [{ type: "cycle", every: 7, on: 2 }, { type: "sex", is: "male" }, { type: "adult" }, { type: "observance", levels: ["devout", "regular", "occasional"] }],
    weight: 8,
    part: "midday",
    place: "sanctuary",
    activity: "visit",
    minutes: 45,
    text: "Go to the congregational prayer at the mud-brick mosque: it is Friday.",
    sources: ["https://en.wikipedia.org/wiki/Friday_prayer"],
  },
  {
    id: "day.timbuktu.copying",
    label: "Copying a manuscript",
    scope: TIMBUKTU,
    evidence: "documented",
    when: [{ type: "tag", any: ["literate", "devout"] }, { type: "chance", p: 0.3 }, { type: "adult" }],
    weight: 5,
    part: "midday",
    place: "sanctuary",
    activity: "work",
    minutes: 70,
    text: "Copy a commentary on Maliki law onto Venetian paper at Sankore.",
    note: "Timbuktu's scholars imported paper by caravan and copied books for sale and for their own libraries.",
    sources: ["https://en.wikipedia.org/wiki/Timbuktu_manuscripts"],
    serves: ["mastery"],
  },
  {
    id: "day.timbuktu.salt",
    label: "Buying Taghaza salt",
    scope: TIMBUKTU,
    evidence: "documented",
    when: [{ type: "work", match: /trad|merchant|sell/i }, { type: "season", any: ["winter", "spring"] }, { type: "chance", p: 0.3 }],
    weight: 5,
    part: "morning",
    place: "market",
    activity: "visit",
    minutes: 50,
    text: "Bargain for slabs of Taghaza salt off the camels just in from the desert.",
    note: "Ibn Battuta saw salt slabs used as currency, cut at Taghaza and carried south by camel.",
    sources: ["https://en.wikipedia.org/wiki/Taghaza"],
  },
  {
    id: "day.niger.bozo",
    label: "Gift to the river spirit",
    scope: NIGER_FISHERS,
    evidence: "inferred",
    when: [{ type: "work", match: /fish|net|boat|canoe/i }, { type: "chance", p: 0.25 }],
    weight: 5,
    part: "morning",
    place: "edge",
    activity: "visit",
    minutes: 25,
    text: "Throw kola and sour milk into the Niger for its spirit before the nets go out.",
    note: "Bozo and Sorko fishers held the river's rights from its spirits by old pacts.",
    sources: ["https://en.wikipedia.org/wiki/Bozo_people"],
  },
  {
    id: "day.fulbe.transhumance",
    label: "Driving the herd to the floodplain",
    scope: FULBE,
    evidence: "documented",
    when: [{ type: "work", match: /herd|cattl|cow/i }, { type: "date", dayOfYear: 340 }],
    weight: 12,
    part: "morning",
    place: "wild",
    activity: "graze",
    minutes: 80,
    text: "Swim the herd across the Niger to the dry-season pastures of the inland delta.",
    note: "At Diafarabé the return crossing is a festival, the dewgal, dated each year by the falling flood.",
    sources: ["https://en.wikipedia.org/wiki/Fula_people"],
  },
  {
    id: "day.dogon.toguna",
    label: "Talk in the toguna",
    scope: DOGON,
    evidence: "documented",
    when: [{ type: "sex", is: "male" }, { type: "adult" }, { type: "chance", p: 0.3 }],
    weight: 4,
    part: "midday",
    place: "gathering",
    activity: "visit",
    minutes: 50,
    text: "Sit under the low toguna roof with the elders and talk out a quarrel.",
    note: "The roof is built too low to stand up in, so no one can rise in anger.",
    sources: ["https://en.wikipedia.org/wiki/Toguna"],
  },
  {
    id: "day.dogon.binu",
    label: "Offering at the binu shrine",
    scope: DOGON,
    evidence: "documented",
    when: [{ type: "season", any: ["spring"] }, { type: "work", match: /farm|millet|field/i }, { type: "chance", p: 0.3 }],
    weight: 5,
    part: "morning",
    place: "sanctuary",
    activity: "visit",
    minutes: 30,
    text: "Pour millet gruel over the binu shrine's stones to call the rains.",
    sources: ["https://en.wikipedia.org/wiki/Dogon_people"],
  },
  {
    id: "day.hausa.dye-pits",
    label: "The indigo pits",
    scope: HAUSA,
    evidence: "documented",
    when: [{ type: "work", match: /dye|cloth|weav|indigo/i }, { type: "chance", p: 0.4 }],
    weight: 6,
    part: "morning",
    place: "work",
    activity: "work",
    minutes: 70,
    text: "Steep the cloth in the indigo pits by the Kano gate and beat it to a shine.",
    note: "Kano's dye pits at Kofar Mata are said to date from the fifteenth century.",
    sources: ["https://en.wikipedia.org/wiki/Kano"],
  },
  {
    id: "day.hausa.zaure",
    label: "News in the entrance hall",
    scope: HAUSA,
    evidence: "documented",
    when: [{ type: "sex", is: "male" }, { type: "trait", key: "extraversion", above: 55 }],
    weight: 3,
    part: "evening",
    place: "home",
    activity: "visit",
    minutes: 45,
    text: "Sit in your zaure and hear the news from whoever comes to the gate.",
    note: "Married women kept to the inner compound; the zaure entrance hut was where men received callers.",
    sources: ["https://en.wikipedia.org/wiki/Hausa_architecture"],
  },
  {
    id: "day.hausa.bori",
    label: "A bori possession dance",
    scope: HAUSA,
    evidence: "documented",
    when: [{ type: "sex", is: "female" }, { type: "tag", any: ["mystical"] }, { type: "chance", p: 0.2 }],
    weight: 4,
    part: "evening",
    place: "gathering",
    activity: "visit",
    minutes: 90,
    text: "Dance to the goge fiddle until a bori spirit mounts one of the women.",
    note: "Bori adepts were mostly women, and the practice survived alongside Islam into the twentieth century.",
    sources: ["https://en.wikipedia.org/wiki/Maguzawa"],
  },
  {
    id: "day.kongo.nkisi",
    label: "Consulting the nganga",
    scope: KONGO,
    evidence: "documented",
    when: [{ type: "fortune", below: 0.35 }, { type: "chance", p: 0.3 }, { type: "adult" }],
    weight: 5,
    part: "evening",
    place: "door",
    activity: "visit",
    minutes: 45,
    text: "Pay the nganga to drive a nail into the nkisi against whoever wronged you.",
    note: "Each nail or blade in an nkisi nkondi records an oath or a plea that roused it.",
    sources: ["https://en.wikipedia.org/wiki/Nkisi"],
  },
  {
    id: "day.kongo.raffia",
    label: "Weaving raffia",
    scope: KONGO,
    evidence: "documented",
    when: [{ type: "work", match: /weav|cloth|raffia/i }, { type: "sex", is: "male" }, { type: "chance", p: 0.4 }],
    weight: 5,
    part: "midday",
    place: "work",
    activity: "work",
    minutes: 70,
    text: "Weave a square of raffia cloth fine enough to pass as money.",
    note: "Portuguese visitors compared Kongo raffia to velvet; standard squares served as currency.",
    sources: ["https://en.wikipedia.org/wiki/Kingdom_of_Kongo"],
  },
  {
    id: "day.kongo.parent",
    label: "Greeting an elder of the clan",
    scope: KONGO,
    evidence: "inferred",
    when: [{ type: "kin", kind: "parent", minAge: 55 }],
    weight: 4,
    part: "morning",
    place: { kin: "parent" },
    activity: "visit",
    minutes: 30,
    carry: "vessel",
    text: "Greet {parent} with cupped, clapping hands and share a gourd of palm wine.",
    sources: ["https://en.wikipedia.org/wiki/Kingdom_of_Kongo"],
    serves: ["elder-kin"],
  },
  {
    id: "day.kuba.embroidery",
    label: "Cut-pile embroidery",
    scope: KUBA,
    evidence: "documented",
    when: [{ type: "sex", is: "female" }, { type: "adult" }, { type: "chance", p: 0.3 }],
    weight: 5,
    part: "midday",
    place: "home",
    activity: "work",
    minutes: 70,
    text: "Stitch cut-pile velvet into a raffia square the men wove.",
    note: "Kuba men wove the raffia panels; women embroidered and cut the pile, often while talking together.",
    sources: ["https://en.wikipedia.org/wiki/Kuba_Kingdom"],
  },
  {
    id: "day.kuba.nyim",
    label: "Tribute for the nyim",
    scope: KUBA,
    evidence: "documented",
    when: [{ type: "fortune", above: 0.6 }, { type: "chance", p: 0.2 }, { type: "adult" }],
    weight: 4,
    part: "morning",
    place: "gathering",
    activity: "haul",
    minutes: 50,
    carry: "bundle",
    text: "Bring your village's share of cloth and camwood to the nyim's collectors.",
    sources: ["https://en.wikipedia.org/wiki/Kuba_Kingdom"],
  },
  {
    id: "day.ituri.molimo",
    label: "Singing the molimo",
    scope: ITURI,
    evidence: "documented",
    when: [{ type: "sex", is: "male" }, { type: "adult" }, { type: "chance", p: 0.15 }],
    weight: 6,
    part: "evening",
    place: "wild",
    activity: "visit",
    minutes: 90,
    text: "Sing through the night with the molimo trumpet, to wake the forest back to goodness.",
    note: "Turnbull's Mbuti brought out the molimo after a death, singing to a forest they thought had fallen asleep.",
    sources: ["https://en.wikipedia.org/wiki/Mbuti_people"],
  },
  {
    id: "day.ituri.net-hunt",
    label: "The net hunt",
    scope: ITURI,
    evidence: "documented",
    when: [{ type: "adult" }, { type: "chance", p: 0.35 }],
    weight: 5,
    part: "morning",
    place: "wild",
    activity: "gather",
    minutes: 90,
    text: "Stretch your net in the long line while the women beat the forest toward it.",
    sources: ["https://en.wikipedia.org/wiki/Mbuti_people"],
  },
  {
    id: "day.west.mission-sunday",
    label: "Sunday at the mission",
    scope: WEST_MISSION,
    evidence: "documented",
    when: [{ type: "cycle", every: 7, on: 4 }, { type: "chance", p: 0.45 }],
    weight: 6,
    part: "morning",
    place: "sanctuary",
    activity: "visit",
    minutes: 90,
    text: "Walk to the mission church in a clean cloth and sing hymns in your own language.",
    note: "Missions printed Bibles and hymnals in Yoruba, Twi, Kikongo and dozens more before 1900.",
    sources: ["https://en.wikipedia.org/wiki/Christianity_in_Africa"],
  },
  {
    id: "day.aksum.mahrem",
    label: "Sacrifice to Mahrem",
    scope: AKSUM_PAGAN,
    evidence: "documented",
    when: [{ type: "observance", levels: ["devout", "regular"] }, { type: "chance", p: 0.2 }, { type: "adult" }],
    weight: 5,
    part: "morning",
    place: "sanctuary",
    activity: "visit",
    minutes: 40,
    text: "Bring a goat to the altar of Mahrem, the god who begot the king.",
    note: "Ezana's early inscriptions call him son of the unconquered Mahrem, before he turned Christian.",
    sources: ["https://en.wikipedia.org/wiki/Ezana_of_Axum"],
  },
  {
    id: "day.aksum.adulis",
    label: "Ivory for Adulis",
    scope: AKSUM,
    evidence: "documented",
    when: [{ type: "work", match: /trad|merchant|carav/i }, { type: "chance", p: 0.3 }],
    weight: 5,
    part: "morning",
    place: "market",
    activity: "haul",
    minutes: 60,
    carry: "bundle",
    text: "Load tusks for the road down to Adulis and the Red Sea ships.",
    note: "The Periplus names Adulis as the port for Aksum's ivory, tortoiseshell and rhinoceros horn.",
    sources: ["https://en.wikipedia.org/wiki/Adulis"],
  },
  {
    id: "day.ethiopia.wednesday",
    label: "The Wednesday fast",
    scope: ETHIOPIA,
    evidence: "documented",
    when: [{ type: "cycle", every: 7, on: 0 }, { type: "adult" }, { type: "observance", levels: ["devout", "regular", "occasional"] }],
    weight: 6,
    part: "midday",
    place: "home",
    activity: "cook",
    minutes: 30,
    text: "Eat nothing until the ninth hour, then only shiro and injera: it is Wednesday.",
    note: "Wednesday is kept for the day Christ was betrayed, Friday for the day he died; neither allows meat or milk.",
    sources: ["https://en.wikipedia.org/wiki/Ethiopian_Orthodox_Tewahedo_Church"],
  },
  {
    id: "day.ethiopia.friday",
    label: "The Friday fast",
    scope: ETHIOPIA,
    evidence: "documented",
    when: [{ type: "cycle", every: 7, on: 2 }, { type: "adult" }, { type: "observance", levels: ["devout", "regular", "occasional"] }],
    weight: 6,
    part: "midday",
    place: "home",
    activity: "cook",
    minutes: 30,
    text: "Keep from meat, milk and butter until afternoon: it is Friday.",
    sources: ["https://en.wikipedia.org/wiki/Ethiopian_Orthodox_Tewahedo_Church"],
  },
  {
    id: "day.ethiopia.qidase",
    label: "The Sunday liturgy",
    scope: ETHIOPIA,
    evidence: "documented",
    when: [{ type: "cycle", every: 7, on: 4 }, { type: "observance", levels: ["devout", "regular"] }],
    weight: 7,
    part: "morning",
    place: "sanctuary",
    activity: "visit",
    minutes: 90,
    text: "Stand barefoot through the Ge'ez liturgy in the round church's outer ring.",
    sources: ["https://en.wikipedia.org/wiki/Ethiopian_Orthodox_Tewahedo_Church"],
  },
  {
    id: "day.ethiopia.mahber",
    label: "The mahber's monthly feast",
    scope: ETHIOPIA,
    evidence: "documented",
    when: [{ type: "cycle", every: 9, on: 6 }, { type: "adult" }, { type: "chance", p: 0.4 }],
    weight: 6,
    part: "evening",
    place: "door",
    activity: "visit",
    minutes: 70,
    text: "Share bread and tella with your mahber on the twenty-first, Mary's day.",
    note: "A mahber is a fellowship pledged to one saint, meeting in turn at members' houses on that saint's monthly day.",
    sources: ["https://en.wikipedia.org/wiki/Ethiopian_Orthodox_Tewahedo_Church"],
  },
  {
    id: "day.ethiopia.debtera",
    label: "Practising zema",
    scope: ETHIOPIA,
    evidence: "documented",
    when: [{ type: "work", match: /scribe|priest|deacon|clerk|teach|scholar/i }, { type: "chance", p: 0.4 }],
    weight: 6,
    part: "midday",
    place: "sanctuary",
    activity: "work",
    minutes: 60,
    text: "Chant Yared's hymns with the prayer-staff and sistrum until the notation sits in you.",
    sources: ["https://en.wikipedia.org/wiki/Yared"],
    serves: ["mastery"],
  },
  {
    id: "day.ethiopia.tezkar",
    label: "A tezkar memorial feast",
    scope: ETHIOPIA,
    evidence: "documented",
    when: [{ type: "anniversary", kind: "died" }],
    weight: 14,
    part: "midday",
    place: "home",
    activity: "visit",
    minutes: 80,
    text: "Feed the priests and the poor with bread and tella for your {dead}.",
    note: "The tezkar is held on the fortieth day and again on the yearly return of the death.",
    sources: ["https://en.wikipedia.org/wiki/Ethiopian_Orthodox_Tewahedo_Church"],
    serves: ["remember-dead"],
  },
  {
    id: "day.ethiopia.coffee",
    label: "The coffee ceremony",
    scope: { ...ETHIOPIA, years: [1880, 1950] },
    evidence: "documented",
    when: [{ type: "sex", is: "female" }, { type: "adult" }, { type: "chance", p: 0.35 }],
    weight: 4,
    part: "evening",
    place: "home",
    activity: "cook",
    minutes: 60,
    text: "Roast green coffee over coals on a floor strewn with grass, and pour three rounds.",
    note: "Orthodox Christians shunned coffee as a Muslim drink until the reign of Menelik II.",
    sources: ["https://en.wikipedia.org/wiki/Coffee_ceremony"],
  },
  {
    id: "day.oromo.odaa",
    label: "Assembly under the odaa tree",
    scope: OROMO,
    evidence: "documented",
    when: [{ type: "sex", is: "male" }, { type: "adult" }, { type: "chance", p: 0.2 }],
    weight: 5,
    part: "midday",
    place: "gathering",
    activity: "visit",
    minutes: 70,
    text: "Sit under the odaa sycamore while the gadaa officers hear the case.",
    note: "Each gadaa grade governs for eight years, then hands power to the next.",
    sources: ["https://en.wikipedia.org/wiki/Gadaa"],
  },
  {
    id: "day.swahili.friday",
    label: "Friday prayer",
    scope: SWAHILI,
    evidence: "documented",
    when: [{ type: "cycle", every: 7, on: 2 }, { type: "sex", is: "male" }, { type: "adult" }, { type: "observance", levels: ["devout", "regular", "occasional"] }],
    weight: 8,
    part: "midday",
    place: "sanctuary",
    activity: "visit",
    minutes: 45,
    text: "Go to the Friday mosque of coral stone for the congregational prayer.",
    sources: ["https://en.wikipedia.org/wiki/Swahili_coast"],
  },
  {
    id: "day.swahili.dhows",
    label: "Meeting the dhows",
    scope: SWAHILI,
    evidence: "documented",
    when: [{ type: "work", match: /trad|merchant|sell|ship/i }, { type: "season", any: ["winter", "spring"] }, { type: "chance", p: 0.35 }],
    weight: 6,
    part: "morning",
    place: "edge",
    activity: "visit",
    minutes: 60,
    text: "Wade out to meet the dhows the kaskazi wind has blown down from Arabia.",
    note: "The northeast monsoon carried ships south from November; the southwest one took them home from April.",
    sources: ["https://en.wikipedia.org/wiki/Dhow"],
  },
  {
    id: "day.swahili.chuo",
    label: "Walking a child to Qur'an school",
    scope: SWAHILI,
    evidence: "documented",
    when: [{ type: "kin", kind: "child", minAge: 5, maxAge: 12 }, { type: "chance", p: 0.35 }],
    weight: 4,
    part: "morning",
    place: "sanctuary",
    activity: "visit",
    minutes: 25,
    text: "Walk {child} to the chuo to recite from the wooden slate.",
    sources: ["https://en.wikipedia.org/wiki/Swahili_culture"],
    serves: ["child-future"],
  },
  {
    id: "day.lakes.matooke",
    label: "Steaming matooke",
    scope: GREAT_LAKES,
    evidence: "documented",
    when: [{ type: "sex", is: "female" }, { type: "adult" }, { type: "chance", p: 0.4 }],
    weight: 5,
    part: "evening",
    place: "hearth",
    activity: "cook",
    minutes: 60,
    text: "Steam peeled green bananas in their own leaves until soft.",
    sources: ["https://en.wikipedia.org/wiki/Matoke"],
  },
  {
    id: "day.lakes.barkcloth",
    label: "Beating barkcloth",
    scope: GREAT_LAKES,
    evidence: "documented",
    when: [{ type: "work", match: /cloth|bark|weav|tailor/i }, { type: "chance", p: 0.4 }],
    weight: 6,
    part: "midday",
    place: "work",
    activity: "work",
    minutes: 70,
    text: "Beat the mutuba bark with a grooved mallet until it spreads into cloth.",
    note: "Ganda barkcloth-making belonged to a hereditary clan of makers serving the Kabaka.",
    sources: ["https://en.wikipedia.org/wiki/Barkcloth"],
  },
  {
    id: "day.lakes.kabaka",
    label: "Tribute to the Kabaka",
    scope: GREAT_LAKES,
    evidence: "documented",
    when: [{ type: "rank", any: ["middling", "gentry"] }, { type: "chance", p: 0.15 }, { type: "adult" }],
    weight: 4,
    part: "morning",
    place: "gathering",
    activity: "haul",
    minutes: 60,
    carry: "vessel",
    text: "Carry pots of banana beer to your chief for the Kabaka's enclosure.",
    sources: ["https://en.wikipedia.org/wiki/Buganda"],
  },
  {
    id: "day.maasai.blood",
    label: "Drawing blood from a steer",
    scope: MAASAI,
    evidence: "documented",
    when: [{ type: "work", match: /herd|cattl|cow/i }, { type: "chance", p: 0.25 }],
    weight: 5,
    part: "morning",
    place: "work",
    activity: "tend",
    minutes: 30,
    carry: "vessel",
    text: "Shoot a blunted arrow into a steer's neck vein to draw blood for the milk.",
    sources: ["https://en.wikipedia.org/wiki/Maasai_people"],
  },
  {
    id: "day.maasai.moran",
    label: "With the age-set",
    scope: MAASAI,
    evidence: "documented",
    when: [{ type: "sex", is: "male" }, { type: "tag", any: ["martial", "communal"] }, { type: "chance", p: 0.3 }],
    weight: 5,
    part: "evening",
    place: { venue: "lodge" },
    activity: "visit",
    minutes: 80,
    text: "Eat meat with your age-mates in the manyatta, never where women see you.",
    note: "Moran were forbidden to eat meat seen by married women; they ate it in the bush or their own camp.",
    sources: ["https://en.wikipedia.org/wiki/Maasai_people"],
  },
  {
    id: "day.maasai.child-cattle",
    label: "Teaching the herd's names",
    scope: MAASAI,
    evidence: "inferred",
    when: [{ type: "kin", kind: "child", minAge: 5, maxAge: 14 }, { type: "chance", p: 0.3 }],
    weight: 4,
    part: "evening",
    place: "work",
    activity: "tend",
    minutes: 40,
    text: "Show {child} how to know every cow by her colour, horns and name.",
    sources: ["https://en.wikipedia.org/wiki/Maasai_people"],
    serves: ["child-future"],
  },
  {
    id: "day.madagascar.famadihana",
    label: "The turning of the bones",
    scope: MADAGASCAR,
    evidence: "documented",
    when: [{ type: "season", any: ["winter"] }, { type: "chance", p: 0.06 }],
    weight: 8,
    part: "midday",
    place: "edge",
    activity: "visit",
    minutes: 120,
    text: "Wrap the ancestors in fresh silk lamba and dance with them before the tomb.",
    note: "The Merina open the family tomb every five to seven years, in the dry winter months.",
    sources: ["https://en.wikipedia.org/wiki/Famadihana"],
    serves: ["remember-dead"],
  },
  {
    id: "day.kalahari.healing-dance",
    label: "The healing dance",
    scope: KALAHARI,
    evidence: "documented",
    when: [{ type: "adult" }, { type: "chance", p: 0.2 }],
    weight: 6,
    part: "evening",
    place: "hearth",
    activity: "visit",
    minutes: 120,
    text: "Sing round the fire, clapping, while the healers dance into trance.",
    note: "The women sit and sing; the men circle until n/om boils up their spines.",
    sources: ["https://en.wikipedia.org/wiki/San_people"],
  },
  {
    id: "day.kalahari.hxaro",
    label: "Hxaro gift",
    scope: KALAHARI,
    evidence: "documented",
    when: [{ type: "kin", kind: "friend" }, { type: "chance", p: 0.2 }],
    weight: 4,
    part: "evening",
    place: { kin: "friend" },
    activity: "visit",
    minutes: 30,
    text: "Give {friend} a string of ostrich-eggshell beads, to be repaid some season later.",
    note: "Hxaro partners owed each other hospitality in their own lands when drought came.",
    sources: ["https://en.wikipedia.org/wiki/San_people"],
  },
  {
    id: "day.kalahari.mongongo",
    label: "Mongongo nuts",
    scope: KALAHARI,
    evidence: "documented",
    when: [{ type: "sex", is: "female" }, { type: "chance", p: 0.4 }],
    weight: 4,
    part: "morning",
    place: "wild",
    activity: "gather",
    minutes: 90,
    carry: "bundle",
    text: "Walk to the mongongo groves with your kaross and fill it with nuts.",
    sources: ["https://en.wikipedia.org/wiki/Schinziophyton"],
  },
  {
    id: "day.drakensberg.eland",
    label: "Painting the eland",
    scope: DRAKENSBERG,
    evidence: "hypothesis",
    when: [{ type: "tag", any: ["mystical"] }, { type: "chance", p: 0.15 }],
    weight: 4,
    part: "midday",
    place: "wild",
    activity: "work",
    minutes: 60,
    text: "Paint an eland on the shelter wall with ochre mixed in its own blood.",
    note: "Eland blood has been identified in some paint; the eland was the San's most potent animal.",
    sources: ["https://en.wikipedia.org/wiki/Drakensberg"],
  },
  {
    id: "day.mapungubwe.hill",
    label: "Climbing to the hilltop court",
    scope: MAPUNGUBWE,
    evidence: "inferred",
    when: [{ type: "rank", any: ["labouring", "middling"] }, { type: "chance", p: 0.2 }],
    weight: 4,
    part: "morning",
    place: "gathering",
    activity: "haul",
    minutes: 50,
    carry: "bundle",
    text: "Carry grain and ivory up the hill path to the ruler, who lives apart above you.",
    note: "Mapungubwe is the first place in southern Africa where the elite lived physically above commoners.",
    sources: ["https://en.wikipedia.org/wiki/Kingdom_of_Mapungubwe"],
  },
  {
    id: "day.zimbabwe.walls",
    label: "Coursing the granite walls",
    scope: GREAT_ZIMBABWE,
    evidence: "inferred",
    when: [{ type: "work", match: /mason|build|stone|wall/i }, { type: "chance", p: 0.4 }],
    weight: 5,
    part: "midday",
    place: "work",
    activity: "work",
    minutes: 70,
    text: "Lay split granite blocks in courses, without mortar, along the Great Enclosure wall.",
    sources: ["https://en.wikipedia.org/wiki/Great_Zimbabwe"],
    serves: ["mastery"],
  },
  {
    id: "day.shona.bira",
    label: "A bira for the ancestors",
    scope: SHONA,
    evidence: "documented",
    when: [{ type: "observance", levels: ["devout", "regular"] }, { type: "chance", p: 0.15 }, { type: "adult" }],
    weight: 6,
    part: "evening",
    place: "hearth",
    activity: "visit",
    minutes: 150,
    carry: "vessel",
    text: "Brew beer and play mbira all night, until a family spirit speaks through its medium.",
    sources: ["https://en.wikipedia.org/wiki/Mbira"],
    serves: ["remember-dead"],
  },
  {
    id: "day.nguni.lobola",
    label: "Talking lobola",
    scope: NGUNI_SOTHO,
    evidence: "documented",
    when: [{ type: "seek-match" }],
    weight: 7,
    part: "midday",
    place: "door",
    activity: "visit",
    minutes: 60,
    text: "Send your go-between to haggle over how many cattle {child}'s marriage will cost.",
    sources: ["https://en.wikipedia.org/wiki/Lobolo"],
    serves: ["marriage-hope"],
  },
  {
    id: "day.nguni.amadlozi",
    label: "A goat for the amadlozi",
    scope: NGUNI_SOTHO,
    evidence: "documented",
    when: [{ type: "fortune", below: 0.3 }, { type: "chance", p: 0.2 }, { type: "adult" }],
    weight: 5,
    part: "evening",
    place: "home",
    activity: "visit",
    minutes: 60,
    text: "Kill a goat in the cattle byre so the ancestors will lift the misfortune.",
    note: "The byre and the back of the great hut were where the shades were thought to stay.",
    sources: ["https://en.wikipedia.org/wiki/Zulu_traditional_religion"],
  },
  {
    id: "day.zulu.utshwala",
    label: "Brewing sorghum beer",
    scope: ZULU,
    evidence: "documented",
    when: [{ type: "sex", is: "female" }, { type: "adult" }, { type: "chance", p: 0.3 }],
    weight: 5,
    part: "morning",
    place: "hearth",
    activity: "cook",
    minutes: 60,
    carry: "vessel",
    text: "Strain the fermented sorghum into the ukhamba pot for the men's gathering.",
    sources: ["https://en.wikipedia.org/wiki/Umqombothi"],
  },
  {
    id: "day.zulu.imbongi",
    label: "Praising the chief",
    scope: ZULU,
    evidence: "documented",
    when: [{ type: "work", match: /praise|poet|sing|bard/i }, { type: "chance", p: 0.4 }],
    weight: 6,
    part: "morning",
    place: "gathering",
    activity: "visit",
    minutes: 40,
    text: "Stride before the chief's kraal shouting his izibongo, the praises of his line.",
    sources: ["https://en.wikipedia.org/wiki/Imbongi"],
    serves: ["mastery"],
  },
  {
    id: "day.sotho.pitso",
    label: "A pitso at the chief's court",
    scope: SOTHO,
    evidence: "documented",
    when: [{ type: "sex", is: "male" }, { type: "adult" }, { type: "chance", p: 0.15 }],
    weight: 5,
    part: "midday",
    place: "gathering",
    activity: "visit",
    minutes: 80,
    text: "Stand at the pitso and say your piece: here even the chief must listen.",
    note: "Moshoeshoe called lipitso on the big questions, and men spoke against him openly.",
    sources: ["https://en.wikipedia.org/wiki/Moshoeshoe_I"],
  },
  {
    id: "day.rand.remittance",
    label: "Money sent home",
    scope: RAND,
    evidence: "documented",
    when: [{ type: "work", match: /mine|miner|shaft/i }, { type: "chance", p: 0.2 }],
    weight: 5,
    part: "evening",
    place: "gathering",
    activity: "visit",
    minutes: 40,
    text: "Pay a clerk to write a letter home and send part of your wages with it.",
    note: "Most Rand miners were migrants on contracts, their families left in the reserves or Mozambique.",
    sources: ["https://en.wikipedia.org/wiki/Witwatersrand_Gold_Rush"],
    serves: ["raise-kin", "restore-household"],
  },
  {
    id: "day.rand.compound-dance",
    label: "Sunday dance in the compound",
    scope: RAND,
    evidence: "documented",
    when: [{ type: "cycle", every: 7, on: 4 }, { type: "sex", is: "male" }],
    weight: 6,
    part: "midday",
    place: "gathering",
    activity: "play",
    minutes: 90,
    text: "Stamp out the gumboot dance with your team in the compound on Sunday.",
    sources: ["https://en.wikipedia.org/wiki/Gumboot_dance"],
  },
  {
    id: "day.south.mission-sunday",
    label: "Sunday at the mission",
    scope: SOUTH_MISSION,
    evidence: "documented",
    when: [{ type: "cycle", every: 7, on: 4 }, { type: "chance", p: 0.45 }],
    weight: 6,
    part: "morning",
    place: "sanctuary",
    activity: "visit",
    minutes: 90,
    text: "Walk to the mission church in your best blanket and sing the Sesotho or isiZulu hymns.",
    sources: ["https://en.wikipedia.org/wiki/Christianity_in_Africa"],
  },
  {
    id: "day.africa.hut-tax",
    label: "Finding the hut tax",
    scope: { years: [1890, 1950], bounds: [-18, -35, 52, 18] as Bounds, cultures: [...WCA, ...ESA] },
    evidence: "documented",
    when: [{ type: "fortune", below: 0.35 }, { type: "adult" }, { type: "chance", p: 0.2 }],
    weight: 4,
    part: "midday",
    place: "market",
    activity: "visit",
    minutes: 45,
    carry: "bundle",
    text: "Sell a goat for coin to pay the hut tax before the collector comes.",
    note: "Colonial hut taxes, payable only in cash, were meant to drive men into wage work.",
    sources: ["https://en.wikipedia.org/wiki/Hut_tax"],
  },
];

export const africaFestivals: Festival[] = [
  {
    id: "fest.igbo.iri-ji",
    label: "the New Yam festival",
    scope: IGBO,
    evidence: "documented",
    date: { dayOfYear: 220 },
    rest: true,
    place: "gathering",
    minutes: 150,
    text: "It is Iri ji: the old yams are finished, the new ones roasted and offered first to Ala.",
    note: "Each town fixes its own day between August and October; this is a representative date.",
    sources: ["https://en.wikipedia.org/wiki/New_Yam_Festival_of_the_Igbo"],
  },
  {
    id: "fest.benin.igue",
    label: "Igue",
    scope: BENIN,
    evidence: "documented",
    date: { dayOfYear: 355 },
    rest: false,
    place: "gathering",
    minutes: 90,
    text: "It is Igue: the Oba renews his mystic strength, and households bless their heads with ewere leaves.",
    sources: ["https://en.wikipedia.org/wiki/Kingdom_of_Benin"],
  },
  {
    id: "fest.asante.akwasidae",
    label: "Akwasidae",
    scope: ASANTE,
    evidence: "documented",
    date: { every: 13, on: 0 },
    rest: false,
    place: "gathering",
    minutes: 90,
    text: "It is Akwasidae: the chief sits in state under his umbrella, and talking drums greet the ancestors.",
    note: "The Sunday Adae of the 42-day cycle; stool-rooms are opened only to the chief and stool-keepers.",
    sources: ["https://en.wikipedia.org/wiki/Akan_calendar"],
  },
  {
    id: "fest.asante.odwira",
    label: "the Odwira",
    scope: ASANTE,
    evidence: "documented",
    date: { dayOfYear: 258 },
    rest: true,
    place: "gathering",
    minutes: 180,
    text: "It is the Odwira: the dead chiefs are fed new yam, and every subject chief comes to Kumasi to renew his oath.",
    note: "Held around September after the yam harvest; the exact day was set each year by the court.",
    sources: ["https://en.wikipedia.org/wiki/Odwira_festival"],
  },
  {
    id: "fest.djenne.crepissage",
    label: "the plastering of the Great Mosque",
    scope: { years: [1907, 1950], bounds: [-4.8, 13.6, -4.3, 14.2] as Bounds, cultures: WCA },
    evidence: "documented",
    date: { dayOfYear: 100 },
    rest: true,
    place: "sanctuary",
    minutes: 180,
    text: "It is the crépissage: the whole town carries mud up the ladders to replaster the Great Mosque before the rains.",
    note: "The two quarters of Djenné race each other, with the masons' guild directing.",
    sources: ["https://en.wikipedia.org/wiki/Great_Mosque_of_Djenn%C3%A9"],
  },
  {
    id: "fest.kongo.santiago",
    label: "the feast of Saint James",
    scope: KONGO_CHRISTIAN,
    evidence: "documented",
    date: { dayOfYear: 206 },
    rest: true,
    place: "gathering",
    minutes: 150,
    text: "It is São Tiago: the nobles bring tribute to the king and dance with swords in honour of Afonso's victory.",
    note: "Kongo held that Saint James appeared in the sky to win Afonso I his throne in 1509.",
    sources: ["https://en.wikipedia.org/wiki/Afonso_I_of_Kongo"],
  },
  {
    id: "fest.ethiopia.timkat",
    label: "Timkat",
    scope: ETHIOPIA,
    evidence: "documented",
    date: { dayOfYear: 19 },
    rest: true,
    place: "edge",
    minutes: 180,
    text: "It is Timkat: the tabots go down to the water in procession, and the priests sprinkle everyone.",
    sources: ["https://en.wikipedia.org/wiki/Timkat"],
  },
  {
    id: "fest.ethiopia.meskel",
    label: "Meskel",
    scope: ETHIOPIA,
    evidence: "documented",
    date: { dayOfYear: 270 },
    rest: true,
    place: "gathering",
    minutes: 150,
    text: "It is Meskel: the great demera bonfire burns for the finding of the True Cross, among the yellow daisies.",
    sources: ["https://en.wikipedia.org/wiki/Meskel"],
  },
  {
    id: "fest.ethiopia.enkutatash",
    label: "Enkutatash",
    scope: ETHIOPIA,
    evidence: "documented",
    date: { dayOfYear: 254 },
    rest: true,
    place: "gathering",
    minutes: 120,
    text: "It is Enkutatash, the new year: the rains are over and girls go door to door singing with flowers.",
    sources: ["https://en.wikipedia.org/wiki/Enkutatash"],
  },
  {
    id: "fest.swahili.mwaka",
    label: "the Swahili new year",
    scope: SWAHILI,
    evidence: "documented",
    date: { dayOfYear: 205 },
    rest: false,
    place: "edge",
    minutes: 120,
    text: "It is Siku ya Mwaka: the men beat each other with banana stems, and an old hut is burnt for luck.",
    note: "The Persian-derived solar new year, best recorded at Makunduchi on Zanzibar.",
    sources: ["https://en.wikipedia.org/wiki/Mwaka_Kogwa"],
  },
  {
    id: "fest.zulu.umkhosi",
    label: "the umkhosi of first fruits",
    scope: ZULU,
    evidence: "documented",
    date: { dayOfYear: 360 },
    rest: true,
    place: "gathering",
    minutes: 180,
    text: "It is the umkhosi: the king tastes the new crops first, and no one eats them until he has.",
    note: "Held at the king's great place near midsummer, at a new moon the doctors chose.",
    sources: ["https://en.wikipedia.org/wiki/Umkhosi_Wokweshwama"],
  },
];
