import type { Festival, Occasion } from "./types";

type Bounds = [number, number, number, number];
const IND = "other-indigenous-american" as const;
const EU = "european" as const;

const AMERICAS: Bounds = [-170, -56, -32, 83];
const PALEO = { years: [-13000, -1500] as [number, number], bounds: AMERICAS, cultures: [IND] };
const NW_COAST = { years: [1200, 1950] as [number, number], bounds: [-135, 42, -115, 62] as Bounds, cultures: [IND] };
const CALIFORNIA = { years: [-3000, 1950] as [number, number], bounds: [-125, 32, -114, 42] as Bounds, cultures: [IND] };
const PUEBLO = { years: [700, 1950] as [number, number], bounds: [-114, 31, -104, 38] as Bounds, cultures: [IND] };
const MISSISSIPPIAN = { years: [800, 1600] as [number, number], bounds: [-100, 25, -75, 44] as Bounds, cultures: [IND] };
const SOUTHEAST = { years: [1600, 1950] as [number, number], bounds: [-92, 29, -76, 37] as Bounds, cultures: [IND] };
const HAUDENOSAUNEE = { years: [1200, 1950] as [number, number], bounds: [-80, 41, -73, 45.5] as Bounds, cultures: [IND] };
const PLAINS = { years: [1700, 1950] as [number, number], bounds: [-110, 30, -94, 55] as Bounds, cultures: [IND] };
const ARCTIC = { years: [1000, 1950] as [number, number], bounds: [-180, 60, -60, 83] as Bounds, cultures: [IND] };
const SUBARCTIC = { years: [-3000, 1950] as [number, number], bounds: [-140, 48, -55, 64] as Bounds, cultures: [IND] };
const TAINO = { years: [600, 1550] as [number, number], bounds: [-85, 17, -64, 24] as Bounds, cultures: [IND] };
const AMAZONIA = { years: [-500, 1950] as [number, number], bounds: [-80, -16, -44, 6] as Bounds, cultures: [IND] };

const SETTLER = { years: [1500, 1950] as [number, number], bounds: AMERICAS, cultures: [EU] };
const NEW_ENGLAND = { years: [1620, 1790] as [number, number], bounds: [-74, 41, -69.5, 45.5] as Bounds, cultures: [EU] };
const NEW_FRANCE = { years: [1608, 1850] as [number, number], bounds: [-80, 44.5, -60, 50] as Bounds, cultures: [EU] };
const CHESAPEAKE = { years: [1620, 1800] as [number, number], bounds: [-78, 36, -75, 40] as Bounds, cultures: [EU] };
const SUGAR_ISLANDS = { years: [1640, 1838] as [number, number], bounds: [-85, 10, -59, 23] as Bounds, cultures: [EU] };
const SLAVE_SOUTH = { years: [1700, 1865] as [number, number], bounds: [-95, 29, -75, 39] as Bounds, cultures: [EU] };
const US = { years: [1776, 1950] as [number, number], bounds: [-125, 24, -66, 49] as Bounds, cultures: [EU] };
const BRAZIL = { years: [1550, 1950] as [number, number], bounds: [-74, -34, -34, 5] as Bounds, cultures: [EU] };
const RIO_DE_LA_PLATA = { years: [1750, 1950] as [number, number], bounds: [-73, -45, -53, -22] as Bounds, cultures: [EU] };

const ENSLAVED = /field hand|household servant|bound labourer/i;

export const americasOccasions: Occasion[] = [
  {
    id: "day.paleo.flute-point",
    label: "Fluting a Clovis point",
    scope: { ...PALEO, years: [-11200, -10500] },
    evidence: "documented",
    when: [{ type: "work", match: /hunt|mammoth|knap/i }, { type: "chance", p: 0.35 }],
    weight: 6,
    part: "midday",
    place: "home",
    activity: "work",
    minutes: 40,
    text: "Flute a spear point from the chert carried back from the quarry.",
    note: "Clovis knappers struck a long channel flake from each face of the point's base, a step that often broke it.",
    sources: ["https://en.wikipedia.org/wiki/Clovis_point"],
    serves: ["mastery"],
  },
  {
    id: "day.paleo.ochre-grave",
    label: "Ochre for the dead",
    scope: PALEO,
    evidence: "inferred",
    when: [{ type: "anniversary", kind: "died" }],
    weight: 12,
    part: "evening",
    place: "edge",
    activity: "visit",
    minutes: 25,
    text: "Sprinkle red ochre where your {dead} lies, {years} years gone.",
    note: "The Anzick child in Montana was buried about 12,800 years ago under Clovis tools thickly coated in red ochre.",
    sources: ["https://en.wikipedia.org/wiki/Anzick-1"],
    serves: ["remember-dead"],
  },
  {
    id: "day.plains.buffalo-jump",
    label: "The buffalo jump",
    scope: { years: [-3700, 1750], bounds: [-115, 40, -100, 55], cultures: [IND] },
    evidence: "documented",
    when: [{ type: "season", any: ["autumn"] }, { type: "work", match: /bison|buffalo|hunt/i }, { type: "chance", p: 0.3 }],
    weight: 6,
    part: "morning",
    place: "edge",
    activity: "haul",
    minutes: 90,
    text: "Help drive the bison down the stone-lined lanes toward the cliff.",
    note: "Head-Smashed-In in Alberta was used for close to six thousand years.",
    sources: ["https://en.wikipedia.org/wiki/Head-Smashed-In_Buffalo_Jump"],
  },
  {
    id: "day.archaic.poverty-point",
    label: "Earth for the ridges",
    scope: { years: [-1700, -1100], bounds: [-93, 31, -90, 34], cultures: [IND] },
    evidence: "documented",
    when: [{ type: "adult" }, { type: "chance", p: 0.3 }],
    weight: 5,
    part: "morning",
    place: "sanctuary",
    activity: "haul",
    minutes: 60,
    carry: "basket",
    text: "Carry baskets of earth up the ridges at Poverty Point.",
    note: "The ridges and mounds were raised a basketload at a time by foragers, without farming.",
    sources: ["https://en.wikipedia.org/wiki/Poverty_Point"],
  },
  {
    id: "day.nw-coast.potlatch-blankets",
    label: "Blankets for the potlatch",
    scope: NW_COAST,
    evidence: "documented",
    when: [{ type: "rank", any: ["gentry", "elite"] }, { type: "season", any: ["autumn", "winter"] }],
    weight: 6,
    part: "evening",
    place: "home",
    activity: "work",
    minutes: 40,
    text: "Count out the blankets and coppers set aside for the potlatch.",
    note: "Canada outlawed the potlatch from 1885 to 1951, and families held them in secret.",
    sources: ["https://en.wikipedia.org/wiki/Potlatch"],
    serves: ["raise-kin"],
  },
  {
    id: "day.nw-coast.eulachon",
    label: "Rendering eulachon",
    scope: NW_COAST,
    evidence: "documented",
    when: [{ type: "season", any: ["spring"] }, { type: "work", match: /fish|salmon|weir/i }],
    weight: 7,
    part: "midday",
    place: "edge",
    activity: "cook",
    minutes: 60,
    text: "Render eulachon oil in the canoe vats for the grease trail.",
    note: "The rendered grease was carried inland along trails named for it.",
    sources: ["https://en.wikipedia.org/wiki/Eulachon"],
  },
  {
    id: "day.nw-coast.cedar-bark",
    label: "Cedar bark",
    scope: NW_COAST,
    evidence: "documented",
    when: [{ type: "season", any: ["spring"] }, { type: "sex", is: "female" }, { type: "chance", p: 0.3 }],
    weight: 5,
    part: "morning",
    place: "wild",
    activity: "gather",
    minutes: 50,
    carry: "bundle",
    text: "Peel a strip of red cedar bark for mats, leaving the tree alive.",
    sources: ["https://en.wikipedia.org/wiki/Culturally_modified_tree"],
  },
  {
    id: "day.california.leach-acorns",
    label: "Leaching acorn meal",
    scope: CALIFORNIA,
    evidence: "documented",
    when: [{ type: "sex", is: "female" }, { type: "adult" }, { type: "season", any: ["autumn", "winter"] }],
    weight: 6,
    part: "midday",
    place: "well",
    activity: "draw-water",
    minutes: 60,
    carry: "vessel",
    text: "Leach the acorn meal in the sand basin until the bitterness is gone.",
    note: "Hot water poured through tanbark-oak meal again and again carried off the tannin.",
    sources: ["https://en.wikipedia.org/wiki/Acorn"],
  },
  {
    id: "day.california.big-time",
    label: "The Big Time",
    scope: { ...CALIFORNIA, years: [1500, 1950] },
    evidence: "documented",
    when: [{ type: "season", any: ["autumn"] }, { type: "chance", p: 0.2 }],
    weight: 5,
    part: "evening",
    place: "gathering",
    activity: "visit",
    minutes: 90,
    carry: "basket",
    text: "Go to the Big Time at the roundhouse, with baskets to trade.",
    note: "Miwok and Pomo towns hosted neighbours for days of dancing, gambling and exchange after the acorn harvest.",
    sources: ["https://en.wikipedia.org/wiki/Miwok"],
  },
  {
    id: "day.california.mission-bell",
    label: "The mission bell",
    scope: { years: [1769, 1834], bounds: [-124, 32, -116, 39], cultures: [IND, EU] },
    evidence: "documented",
    when: [{ type: "adult" }, { type: "rank", any: ["destitute", "labouring"] }],
    weight: 6,
    part: "morning",
    place: "sanctuary",
    activity: "visit",
    minutes: 30,
    text: "Answer the mission bell for prayers before the day's work in the fields.",
    note: "Baptised neophytes could not leave the mission without permission, and soldiers brought runaways back.",
    sources: ["https://en.wikipedia.org/wiki/Spanish_missions_in_California"],
  },
  {
    id: "day.chaco.road",
    label: "The road to Chaco",
    scope: { years: [850, 1150], bounds: [-111, 34, -106, 38], cultures: [IND] },
    evidence: "hypothesis",
    when: [{ type: "adult" }, { type: "chance", p: 0.15 }],
    weight: 4,
    part: "morning",
    place: "edge",
    activity: "haul",
    minutes: 60,
    carry: "bundle",
    text: "Walk the straight road to the great houses of Chaco with turquoise.",
    note: "The roads run dead straight over mesas; whether they carried goods, pilgrims or only meaning is argued.",
    sources: ["https://en.wikipedia.org/wiki/Chaco_Culture_National_Historical_Park"],
  },
  {
    id: "day.pueblo.kiva",
    label: "Down into the kiva",
    scope: PUEBLO,
    evidence: "documented",
    when: [{ type: "sex", is: "male" }, { type: "adult" }, { type: "observance", levels: ["devout", "regular"] }],
    weight: 5,
    part: "evening",
    place: { venue: "lodge" },
    activity: "visit",
    minutes: 70,
    text: "Go down the ladder into the kiva to rehearse the songs for the dance.",
    sources: ["https://en.wikipedia.org/wiki/Kiva"],
  },
  {
    id: "day.pueblo.piki",
    label: "Piki bread",
    scope: { ...PUEBLO, years: [1300, 1950] },
    evidence: "documented",
    when: [{ type: "sex", is: "female" }, { type: "adult" }, { type: "chance", p: 0.35 }],
    weight: 5,
    part: "morning",
    place: "hearth",
    activity: "cook",
    minutes: 50,
    text: "Spread blue corn batter paper-thin on the hot piki stone.",
    sources: ["https://en.wikipedia.org/wiki/Piki"],
  },
  {
    id: "day.pueblo.katsina-doll",
    label: "A katsina doll",
    scope: { ...PUEBLO, years: [1300, 1950] },
    evidence: "documented",
    when: [{ type: "kin", kind: "child", maxAge: 12 }, { type: "sex", is: "male" }, { type: "season", any: ["winter", "spring"] }],
    weight: 5,
    part: "evening",
    place: "home",
    activity: "work",
    minutes: 50,
    text: "Carve a katsina doll from cottonwood root, for {child} at the dance.",
    note: "At the dances the katsinam themselves hand the dolls to girls.",
    sources: ["https://en.wikipedia.org/wiki/Kachina"],
    serves: ["raise-kin"],
  },
  {
    id: "day.pueblo.soyal",
    label: "Prayer feathers for Soyal",
    scope: { ...PUEBLO, years: [1300, 1950] },
    evidence: "documented",
    when: [{ type: "date", dayOfYear: 354 }],
    weight: 14,
    part: "morning",
    place: "sanctuary",
    activity: "visit",
    minutes: 40,
    text: "Make prayer feathers for Soyal: the sun turns back at the solstice.",
    sources: ["https://en.wikipedia.org/wiki/Soyal"],
  },
  {
    id: "day.cahokia.chunkey",
    label: "Chunkey",
    scope: MISSISSIPPIAN,
    evidence: "documented",
    when: [{ type: "sex", is: "male" }, { type: "trait", key: "extraversion", above: 45 }, { type: "chance", p: 0.3 }],
    weight: 5,
    part: "evening",
    place: "gathering",
    activity: "play",
    minutes: 60,
    text: "Throw your pole after the chunkey stone rolling across the plaza.",
    note: "Cahokia's Grand Plaza was levelled with fill, and chunkey stones turn up across the Mississippian world.",
    sources: ["https://en.wikipedia.org/wiki/Chunkey"],
  },
  {
    id: "day.mississippian.new-fire",
    label: "Before the new corn",
    scope: MISSISSIPPIAN,
    evidence: "inferred",
    when: [{ type: "date", dayOfYear: 208 }],
    weight: 12,
    part: "morning",
    place: "home",
    activity: "work",
    minutes: 40,
    text: "Smash last year's pots and sweep the house clean for the new corn.",
    note: "Projected back from the historic busk, when every hearth was put out and relit from the new fire.",
    sources: ["https://en.wikipedia.org/wiki/Green_Corn_Ceremony"],
  },
  {
    id: "day.southeast.stickball",
    label: "Stickball",
    scope: SOUTHEAST,
    evidence: "documented",
    when: [{ type: "sex", is: "male" }, { type: "adult" }, { type: "chance", p: 0.2 }],
    weight: 5,
    part: "midday",
    place: "gathering",
    activity: "play",
    minutes: 90,
    text: "Play stickball against the next town, the little brother of war.",
    sources: ["https://en.wikipedia.org/wiki/Stickball"],
  },
  {
    id: "day.southeast.black-drink",
    label: "The black drink",
    scope: SOUTHEAST,
    evidence: "documented",
    when: [{ type: "sex", is: "male" }, { type: "rank", any: ["middling", "gentry", "elite"] }, { type: "chance", p: 0.3 }],
    weight: 4,
    part: "morning",
    place: "gathering",
    activity: "visit",
    minutes: 40,
    text: "Drink the black drink in the square ground before the council sits.",
    note: "Brewed from yaupon holly, a caffeinated tea, and drunk to purify before deliberation.",
    sources: ["https://en.wikipedia.org/wiki/Black_drink"],
  },
  {
    id: "day.haudenosaunee.three-sisters",
    label: "The Three Sisters",
    scope: HAUDENOSAUNEE,
    evidence: "documented",
    when: [{ type: "season", any: ["spring"] }, { type: "sex", is: "female" }, { type: "adult" }],
    weight: 7,
    part: "morning",
    place: "work",
    activity: "tend",
    minutes: 60,
    carry: "basket",
    text: "Plant corn, beans and squash together in each hill: the Three Sisters.",
    note: "The fields belonged to the women's lineages, and the clan mothers directed the work.",
    sources: ["https://en.wikipedia.org/wiki/Three_Sisters_(agriculture)"],
  },
  {
    id: "day.haudenosaunee.condolence",
    label: "Condolence",
    scope: HAUDENOSAUNEE,
    evidence: "documented",
    when: [{ type: "adult" }, { type: "tag", any: ["communal", "traditionalist"] }, { type: "chance", p: 0.1 }],
    weight: 4,
    part: "evening",
    place: "door",
    activity: "visit",
    minutes: 40,
    text: "Carry wampum strings to a grieving family to wipe the tears from their eyes.",
    sources: ["https://en.wikipedia.org/wiki/Wampum"],
  },
  {
    id: "day.anishinaabe.wild-rice",
    label: "Ricing",
    scope: { years: [1200, 1950], bounds: [-97, 44, -84, 50], cultures: [IND] },
    evidence: "documented",
    when: [{ type: "season", any: ["autumn"] }, { type: "adult" }],
    weight: 7,
    part: "morning",
    place: "wild",
    activity: "gather",
    minutes: 90,
    text: "Knock wild rice into the canoe with the cedar sticks.",
    note: "Manoomin is the food that grows on water, which Anishinaabe tradition says marked the end of their migration west.",
    sources: ["https://en.wikipedia.org/wiki/Wild_rice"],
  },
  {
    id: "day.woodlands.sugar-bush",
    label: "The sugar bush",
    scope: { years: [1600, 1950], bounds: [-92, 40, -66, 50], cultures: [IND, EU] },
    evidence: "documented",
    when: [{ type: "season", any: ["spring"] }, { type: "chance", p: 0.4 }],
    weight: 6,
    part: "midday",
    place: "wild",
    activity: "cook",
    minutes: 80,
    carry: "vessel",
    text: "Boil down maple sap at the sugar bush while the nights still freeze.",
    sources: ["https://en.wikipedia.org/wiki/Maple_syrup"],
  },
  {
    id: "day.plains.quillwork",
    label: "Quillwork for a cradleboard",
    scope: PLAINS,
    evidence: "documented",
    when: [{ type: "sex", is: "female" }, { type: "kin", kind: "child", maxAge: 1 }],
    weight: 6,
    part: "evening",
    place: "home",
    activity: "work",
    minutes: 60,
    text: "Sew dyed porcupine quills onto the cradleboard for {child}.",
    sources: ["https://en.wikipedia.org/wiki/Quillwork"],
    serves: ["raise-kin"],
  },
  {
    id: "day.plains.winter-count",
    label: "The winter count",
    scope: PLAINS,
    evidence: "documented",
    when: [{ type: "season", any: ["winter"] }, { type: "rank", any: ["gentry", "elite"] }, { type: "chance", p: 0.2 }],
    weight: 5,
    part: "evening",
    place: "home",
    activity: "work",
    minutes: 45,
    text: "Paint this winter's picture on the hide of the winter count.",
    note: "Lakota keepers added one image a year, named for the year's most remembered event.",
    sources: ["https://en.wikipedia.org/wiki/Winter_count"],
  },
  {
    id: "day.plains.ghost-dance",
    label: "The Ghost Dance",
    scope: { years: [1889, 1892], bounds: [-120, 32, -94, 50], cultures: [IND] },
    evidence: "documented",
    when: [{ type: "tag", any: ["millenarian", "devout", "restorationist"] }],
    weight: 7,
    part: "evening",
    place: "gathering",
    activity: "visit",
    minutes: 120,
    text: "Dance the Ghost Dance in the circle, so the dead and the buffalo return.",
    note: "Wovoka's teaching spread from Nevada; the army's fear of it ended at Wounded Knee in 1890.",
    sources: ["https://en.wikipedia.org/wiki/Ghost_Dance"],
    serves: ["remember-dead"],
  },
  {
    id: "day.plains.ration-day",
    label: "Ration day",
    scope: { years: [1868, 1920], bounds: [-115, 30, -94, 50], cultures: [IND] },
    evidence: "documented",
    when: [{ type: "cycle", every: 4, on: 1 }, { type: "adult" }],
    weight: 6,
    part: "morning",
    place: "market",
    activity: "visit",
    minutes: 90,
    carry: "bundle",
    text: "Walk in to the agency for the ration issue of beef and flour.",
    note: "Beef was often issued on the hoof, and men rode the cattle down as if hunting.",
    sources: ["https://en.wikipedia.org/wiki/Indian_agent"],
  },
  {
    id: "day.americas.boarding-school",
    label: "Word to the boarding school",
    scope: { years: [1879, 1950], bounds: [-170, 25, -55, 72], cultures: [IND] },
    evidence: "documented",
    when: [{ type: "kin", kind: "child", minAge: 6, maxAge: 17 }, { type: "chance", p: 0.1 }],
    weight: 5,
    part: "evening",
    place: "home",
    activity: "visit",
    minutes: 30,
    text: "Send word to {child} at the boarding school, far from home.",
    note: "Children were taken to schools where their own language was forbidden, and many did not come home.",
    sources: ["https://en.wikipedia.org/wiki/American_Indian_boarding_schools"],
    serves: ["raise-kin"],
  },
  {
    id: "day.inuit.seal-partners",
    label: "Seal-sharing partners",
    scope: ARCTIC,
    evidence: "documented",
    when: [{ type: "season", any: ["winter", "spring"] }, { type: "work", match: /seal|walrus|hunt/i }],
    weight: 7,
    part: "evening",
    place: "door",
    activity: "haul",
    minutes: 40,
    carry: "bundle",
    text: "Carry each seal-sharing partner their own joint of today's seal.",
    note: "Netsilik partners were named for the part of the seal each always received.",
    sources: ["https://en.wikipedia.org/wiki/Netsilik_Inuit"],
  },
  {
    id: "day.inuit.qulliq",
    label: "Tending the qulliq",
    scope: ARCTIC,
    evidence: "documented",
    when: [{ type: "sex", is: "female" }, { type: "adult" }, { type: "season", any: ["winter", "autumn"] }],
    weight: 5,
    part: "evening",
    place: "hearth",
    activity: "warm",
    minutes: 30,
    text: "Trim the moss wick of the qulliq so the seal-oil lamp burns without smoke.",
    sources: ["https://en.wikipedia.org/wiki/Qulliq"],
  },
  {
    id: "day.subarctic.snowshoes",
    label: "Lacing snowshoes",
    scope: SUBARCTIC,
    evidence: "documented",
    when: [{ type: "season", any: ["autumn"] }, { type: "adult" }, { type: "chance", p: 0.35 }],
    weight: 5,
    part: "evening",
    place: "home",
    activity: "work",
    minutes: 60,
    text: "Lace new snowshoes with babiche before the deep snow comes.",
    sources: ["https://en.wikipedia.org/wiki/Snowshoe"],
  },
  {
    id: "day.subarctic.fur-post",
    label: "Furs to the post",
    scope: { ...SUBARCTIC, years: [1670, 1950] },
    evidence: "documented",
    when: [{ type: "season", any: ["spring"] }, { type: "work", match: /trap|fur|hunt/i }],
    weight: 7,
    part: "midday",
    place: "market",
    activity: "haul",
    minutes: 60,
    carry: "bundle",
    text: "Carry the winter's furs to the Company post against the autumn's credit.",
    note: "Traders advanced goods on credit in autumn and counted it in made beaver in spring.",
    sources: ["https://en.wikipedia.org/wiki/Hudson%27s_Bay_Company"],
  },
  {
    id: "day.taino.batey",
    label: "The ball game on the batey",
    scope: TAINO,
    evidence: "documented",
    when: [{ type: "adult" }, { type: "trait", key: "extraversion", above: 45 }, { type: "chance", p: 0.25 }],
    weight: 5,
    part: "evening",
    place: "gathering",
    activity: "play",
    minutes: 60,
    text: "Play ball on the batey, keeping the rubber ball up with hips and shoulders.",
    note: "Spaniards had never seen a ball that bounced, and wrote about it at length.",
    sources: ["https://en.wikipedia.org/wiki/Ta%C3%ADno"],
  },
  {
    id: "day.taino.zemi",
    label: "Cassava for the zemi",
    scope: TAINO,
    evidence: "documented",
    when: [{ type: "patron" }, { type: "observance", levels: ["devout", "regular"] }],
    weight: 5,
    part: "morning",
    place: "home",
    activity: "visit",
    minutes: 15,
    text: "Set cassava bread before {patron}, the zemi on its shelf.",
    sources: ["https://en.wikipedia.org/wiki/Zemi"],
  },
  {
    id: "day.taino.areito",
    label: "The areíto",
    scope: TAINO,
    evidence: "documented",
    when: [{ type: "chance", p: 0.15 }],
    weight: 4,
    part: "evening",
    place: "gathering",
    activity: "visit",
    minutes: 90,
    text: "Dance the areíto and sing back the deeds of the old caciques.",
    note: "Areítos were the Taíno's sung history, led by a caller and answered by the dancers.",
    sources: ["https://en.wikipedia.org/wiki/Ta%C3%ADno"],
  },
  {
    id: "day.amazonia.tipiti",
    label: "Pressing manioc",
    scope: AMAZONIA,
    evidence: "documented",
    when: [{ type: "sex", is: "female" }, { type: "adult" }],
    weight: 6,
    part: "morning",
    place: "hearth",
    activity: "cook",
    minutes: 50,
    text: "Squeeze the grated bitter manioc in the tipiti to drain its poison.",
    sources: ["https://en.wikipedia.org/wiki/Tipiti"],
  },
  {
    id: "day.amazonia.garden",
    label: "Burning a new garden",
    scope: AMAZONIA,
    evidence: "documented",
    when: [{ type: "kin", kind: "partner" }, { type: "season", any: ["summer"] }, { type: "chance", p: 0.3 }],
    weight: 5,
    part: "morning",
    place: "wild",
    activity: "work",
    minutes: 80,
    text: "Burn the felled trees of the new garden with {partner}, before the rains.",
    note: "Men felled the forest; the garden it made was the women's.",
    sources: ["https://en.wikipedia.org/wiki/Slash-and-burn"],
  },
  {
    id: "day.amazonia.drinking-feast",
    label: "Manioc beer",
    scope: AMAZONIA,
    evidence: "documented",
    when: [{ type: "sex", is: "female" }, { type: "adult" }, { type: "chance", p: 0.2 }],
    weight: 4,
    part: "midday",
    place: "hearth",
    activity: "cook",
    minutes: 60,
    carry: "vessel",
    text: "Chew manioc for the beer the whole village will drink at the feast.",
    note: "Saliva starts the ferment; Léry watched Tupinambá women do it in 1557.",
    sources: ["https://en.wikipedia.org/wiki/Cassava"],
  },
  {
    id: "day.tupinamba.weeping",
    label: "The greeting of tears",
    scope: { years: [1000, 1650], bounds: [-50, -26, -34, -2], cultures: [IND] },
    evidence: "documented",
    when: [{ type: "sex", is: "female" }, { type: "adult" }, { type: "chance", p: 0.1 }],
    weight: 4,
    part: "evening",
    place: "door",
    activity: "visit",
    minutes: 25,
    text: "Weep aloud over a returning kinsman, as courtesy demands of a welcome.",
    note: "Léry was greeted this way: women sat by the guest and wept, praising his journey.",
    sources: ["https://en.wikipedia.org/wiki/Tupinamb%C3%A1_people"],
  },
  {
    id: "day.patagonia.bolas",
    label: "Hunting with the bolas",
    scope: { years: [1700, 1900], bounds: [-75, -56, -56, -30], cultures: [IND] },
    evidence: "documented",
    when: [{ type: "sex", is: "male" }, { type: "adult" }, { type: "work", match: /guanaco|hunt/i }],
    weight: 6,
    part: "morning",
    place: "wild",
    activity: "haul",
    minutes: 90,
    text: "Ride out with the bolas after guanaco and rhea.",
    sources: ["https://en.wikipedia.org/wiki/Tehuelche_people"],
  },
  {
    id: "day.new-england.sabbath-eve",
    label: "Sundown on Saturday",
    scope: NEW_ENGLAND,
    evidence: "documented",
    when: [{ type: "cycle", every: 7, on: 3 }, { type: "adult" }],
    weight: 8,
    part: "evening",
    place: "home",
    activity: "rest",
    minutes: 30,
    text: "Lay down your work at sundown: the Sabbath begins.",
    note: "Puritans reckoned the Lord's day from Saturday sunset, as the Hebrew day runs.",
    sources: ["https://en.wikipedia.org/wiki/Sabbatarianism"],
  },
  {
    id: "day.new-england.lecture",
    label: "Thursday lecture",
    scope: NEW_ENGLAND,
    evidence: "documented",
    when: [{ type: "cycle", every: 7, on: 1 }, { type: "observance", levels: ["devout", "regular"] }],
    weight: 6,
    part: "midday",
    place: "sanctuary",
    activity: "visit",
    minutes: 70,
    text: "Walk to the Thursday lecture at the meeting house.",
    note: "Boston's weekday lecture drew people from the surrounding towns, and was a market day besides.",
    sources: ["https://en.wikipedia.org/wiki/Puritans"],
  },
  {
    id: "day.new-england.town-meeting",
    label: "Town meeting",
    scope: { ...NEW_ENGLAND, years: [1635, 1950] },
    evidence: "documented",
    when: [{ type: "date", dayOfYear: 65 }, { type: "sex", is: "male" }, { type: "adult" }],
    weight: 13,
    part: "midday",
    place: "gathering",
    activity: "visit",
    minutes: 120,
    text: "Vote at the March town meeting on roads, schools and the minister's pay.",
    sources: ["https://en.wikipedia.org/wiki/Town_meeting"],
    serves: ["shared-future"],
  },
  {
    id: "day.new-france.cens",
    label: "Cens et rentes",
    scope: NEW_FRANCE,
    evidence: "documented",
    when: [{ type: "date", dayOfYear: 315 }, { type: "rank", any: ["labouring", "middling"] }, { type: "adult" }],
    weight: 13,
    part: "midday",
    place: "door",
    activity: "visit",
    minutes: 40,
    carry: "basket",
    text: "Bring the seigneur his cens et rentes at Martinmas, with a capon or two.",
    sources: ["https://en.wikipedia.org/wiki/Seigneurial_system_of_New_France"],
    serves: ["household-home"],
  },
  {
    id: "day.new-france.voyageur",
    label: "Signing on for the canoes",
    scope: { ...NEW_FRANCE, years: [1680, 1850], bounds: [-80, 44.5, -70, 48] },
    evidence: "documented",
    when: [{ type: "season", any: ["spring"] }, { type: "sex", is: "male" }, { type: "fortune", below: 0.5 }, { type: "chance", p: 0.2 }],
    weight: 5,
    part: "midday",
    place: "market",
    activity: "visit",
    minutes: 40,
    text: "Sign on with the canoes going up to the pays d'en haut.",
    note: "Montreal's merchants hired habitants' sons by notarised contract for the season's paddle west.",
    sources: ["https://en.wikipedia.org/wiki/Voyageurs"],
    serves: ["restore-household"],
  },
  {
    id: "day.chesapeake.tobacco",
    label: "Worming the tobacco",
    scope: CHESAPEAKE,
    evidence: "documented",
    when: [{ type: "season", any: ["summer"] }, { type: "work", match: /tobacco|farm|field|planter|husband|yeoman|servant/i }],
    weight: 6,
    part: "morning",
    place: "work",
    activity: "tend",
    minutes: 70,
    text: "Pick the hornworms off the tobacco, row by row, before the heat.",
    sources: ["https://en.wikipedia.org/wiki/Tobacco_in_the_American_colonies"],
  },
  {
    id: "day.plantation.provision-ground",
    label: "The provision ground",
    scope: SUGAR_ISLANDS,
    evidence: "documented",
    when: [{ type: "cycle", every: 7, on: 4 }, { type: "work", match: ENSLAVED }],
    weight: 8,
    part: "morning",
    place: "edge",
    activity: "tend",
    minutes: 90,
    carry: "basket",
    text: "Work your own provision ground in the hills: Sunday is the one day it is yours.",
    note: "Jamaican planters left the enslaved to grow their own food, and the surplus fed the island's Sunday markets.",
    sources: ["https://en.wikipedia.org/wiki/Sugar_plantations_in_the_Caribbean"],
    serves: ["household-home"],
  },
  {
    id: "day.plantation.crop-over",
    label: "Crop over",
    scope: SUGAR_ISLANDS,
    evidence: "documented",
    when: [{ type: "date", dayOfYear: 200 }, { type: "work", match: ENSLAVED }],
    weight: 12,
    part: "evening",
    place: "gathering",
    activity: "visit",
    minutes: 90,
    text: "Dance at crop over: the last of the cane is cut.",
    sources: ["https://en.wikipedia.org/wiki/Crop_Over"],
  },
  {
    id: "day.plantation.praise-house",
    label: "The ring shout",
    scope: SLAVE_SOUTH,
    evidence: "documented",
    when: [{ type: "work", match: ENSLAVED }, { type: "cycle", every: 7, on: 4 }],
    weight: 7,
    part: "evening",
    place: "gathering",
    activity: "visit",
    minutes: 90,
    text: "Slip away to the praise house for the ring shout.",
    note: "Worship out of the owners' hearing was punished in many places and kept up anyway.",
    sources: ["https://en.wikipedia.org/wiki/Ring_shout"],
  },
  {
    id: "day.plantation.abroad",
    label: "A pass to see family",
    scope: SLAVE_SOUTH,
    evidence: "documented",
    when: [{ type: "work", match: ENSLAVED }, { type: "kin", kind: "partner" }, { type: "cycle", every: 7, on: 3 }],
    weight: 7,
    part: "evening",
    place: "edge",
    activity: "visit",
    minutes: 60,
    text: "Walk the miles to {partner} on the next plantation, with a Saturday pass.",
    note: "Husbands and wives owned by different people were said to be married abroad.",
    sources: ["https://en.wikipedia.org/wiki/Slavery_in_the_United_States"],
    serves: ["shared-future"],
  },
  {
    id: "day.us.camp-meeting",
    label: "The camp meeting",
    scope: { ...US, years: [1800, 1900] },
    evidence: "documented",
    when: [{ type: "season", any: ["summer"] }, { type: "observance", levels: ["devout", "regular"] }, { type: "chance", p: 0.2 }],
    weight: 6,
    part: "evening",
    place: "edge",
    activity: "visit",
    minutes: 120,
    text: "Hear the preaching at the camp meeting until the torches burn down.",
    sources: ["https://en.wikipedia.org/wiki/Camp_meeting"],
  },
  {
    id: "day.us.barn-raising",
    label: "A barn raising",
    scope: { ...US, years: [1780, 1930] },
    evidence: "documented",
    when: [{ type: "adult" }, { type: "tag", any: ["communal", "agrarian"] }, { type: "chance", p: 0.08 }],
    weight: 5,
    part: "midday",
    place: "door",
    activity: "haul",
    minutes: 150,
    text: "Help raise a neighbour's barn, and stay for the supper after.",
    sources: ["https://en.wikipedia.org/wiki/Barn_raising"],
  },
  {
    id: "day.us.quilting-bee",
    label: "The quilting bee",
    scope: { ...US, years: [1790, 1950] },
    evidence: "documented",
    when: [{ type: "sex", is: "female" }, { type: "adult" }, { type: "chance", p: 0.15 }],
    weight: 5,
    part: "midday",
    place: "door",
    activity: "work",
    minutes: 120,
    carry: "bundle",
    text: "Bring your needle and thimble to the quilting bee at a neighbour's.",
    sources: ["https://en.wikipedia.org/wiki/Quilting"],
  },
  {
    id: "day.us.sunday-school",
    label: "Sunday school",
    scope: { ...US, years: [1820, 1950] },
    evidence: "documented",
    when: [{ type: "cycle", every: 7, on: 4 }, { type: "kin", kind: "child", minAge: 5, maxAge: 14 }],
    weight: 6,
    part: "morning",
    place: "sanctuary",
    activity: "visit",
    minutes: 50,
    text: "Walk {child} to Sunday school before the service.",
    sources: ["https://en.wikipedia.org/wiki/Sunday_school"],
    serves: ["child-future"],
  },
  {
    id: "day.us.baseball",
    label: "The town nine",
    scope: { ...US, years: [1866, 1950] },
    evidence: "documented",
    when: [{ type: "cycle", every: 7, on: 3 }, { type: "sex", is: "male" }, { type: "trait", key: "extraversion", above: 45 }],
    weight: 5,
    part: "midday",
    place: "gathering",
    activity: "play",
    minutes: 120,
    text: "Play ball for the town nine against the next county.",
    sources: ["https://en.wikipedia.org/wiki/History_of_baseball_in_the_United_States"],
  },
  {
    id: "day.us.chautauqua",
    label: "The Chautauqua tent",
    scope: { ...US, years: [1874, 1932] },
    evidence: "documented",
    when: [{ type: "season", any: ["summer"] }, { type: "tag", any: ["literate", "reformist", "devout"] }, { type: "chance", p: 0.25 }],
    weight: 5,
    part: "evening",
    place: "gathering",
    activity: "visit",
    minutes: 100,
    text: "Hear the lecturers and the band under the Chautauqua tent.",
    sources: ["https://en.wikipedia.org/wiki/Chautauqua"],
  },
  {
    id: "day.us.county-fair",
    label: "The county fair",
    scope: { ...US, years: [1811, 1950] },
    evidence: "documented",
    when: [{ type: "date", dayOfYear: 255 }, { type: "adult" }],
    weight: 13,
    part: "midday",
    place: "market",
    activity: "visit",
    minutes: 120,
    carry: "basket",
    text: "Show your best stock and preserves at the county fair.",
    note: "Elkanah Watson's Berkshire show of 1811 is counted the first county fair.",
    sources: ["https://en.wikipedia.org/wiki/County_fair"],
    serves: ["mastery"],
  },
  {
    id: "day.us.saturday-town",
    label: "Saturday in town",
    scope: { ...US, years: [1850, 1950] },
    evidence: "inferred",
    when: [{ type: "cycle", every: 7, on: 3 }, { type: "tag", any: ["agrarian"] }, { type: "adult" }],
    weight: 5,
    part: "midday",
    place: "market",
    activity: "visit",
    minutes: 70,
    carry: "basket",
    text: "Drive the wagon into town for Saturday trading and the week's news.",
    sources: [],
  },
  {
    id: "day.us.saloon",
    label: "The saloon",
    scope: { ...US, years: [1840, 1920] },
    evidence: "documented",
    when: [{ type: "sex", is: "male" }, { type: "adult" }, { type: "tag", any: ["worldly"] }, { type: "chance", p: 0.3 }],
    weight: 4,
    part: "evening",
    place: "market",
    activity: "visit",
    minutes: 60,
    text: "Stand at the saloon bar for a nickel beer and the free lunch.",
    note: "Prohibition closed the saloons in 1920.",
    sources: ["https://en.wikipedia.org/wiki/Western_saloon"],
  },
  {
    id: "day.us.decoration-day",
    label: "Decoration Day",
    scope: { ...US, years: [1868, 1950] },
    evidence: "documented",
    when: [{ type: "date", dayOfYear: 150 }],
    weight: 13,
    part: "morning",
    place: "edge",
    activity: "visit",
    minutes: 50,
    carry: "basket",
    text: "Lay flowers on the soldiers' graves: it is Decoration Day.",
    sources: ["https://en.wikipedia.org/wiki/Memorial_Day"],
    serves: ["remember-dead"],
  },
  {
    id: "day.us.world-series",
    label: "The World Series on the radio",
    scope: { ...US, years: [1925, 1950] },
    evidence: "documented",
    when: [{ type: "date", dayOfYear: 278 }, { type: "sex", is: "male" }],
    weight: 12,
    part: "midday",
    place: "market",
    activity: "visit",
    minutes: 90,
    text: "Crowd round the radio in the shop window for the World Series.",
    sources: ["https://en.wikipedia.org/wiki/World_Series"],
  },
  {
    id: "day.plata.mate",
    label: "Mate before dawn",
    scope: RIO_DE_LA_PLATA,
    evidence: "documented",
    when: [{ type: "adult" }, { type: "chance", p: 0.4 }],
    weight: 4,
    part: "morning",
    place: "hearth",
    activity: "warm",
    minutes: 25,
    text: "Pass the mate gourd round the fire before riding out.",
    sources: ["https://en.wikipedia.org/wiki/Mate_(drink)"],
  },
  {
    id: "day.plata.yerra",
    label: "The branding",
    scope: RIO_DE_LA_PLATA,
    evidence: "documented",
    when: [{ type: "season", any: ["spring"] }, { type: "work", match: /cattle|herd|drover|gaucho|transhum/i }],
    weight: 7,
    part: "morning",
    place: "edge",
    activity: "graze",
    minutes: 120,
    text: "Ride to the yerra, the estancia's branding of the year's calves.",
    note: "Neighbours rode in to help and the day ended in an asado.",
    sources: ["https://en.wikipedia.org/wiki/Gaucho"],
  },
  {
    id: "day.brazil.sao-joao",
    label: "São João bonfires",
    scope: BRAZIL,
    evidence: "documented",
    when: [{ type: "date", dayOfYear: 175 }],
    weight: 13,
    part: "evening",
    place: "gathering",
    activity: "warm",
    minutes: 80,
    text: "Light the São João bonfire for roasting green corn with the neighbours.",
    note: "In Brazil the June feasts fall in the dry season and the maize harvest, not midsummer.",
    sources: ["https://en.wikipedia.org/wiki/Festa_Junina"],
  },
  {
    id: "day.brazil.coffee-harvest",
    label: "The coffee harvest",
    scope: { ...BRAZIL, years: [1830, 1950], bounds: [-54, -25, -40, -18] },
    evidence: "documented",
    when: [{ type: "season", any: ["winter"] }, { type: "work", match: /coffee|farm|field|colon|husband|labour/i }],
    weight: 6,
    part: "morning",
    place: "work",
    activity: "gather",
    minutes: 90,
    carry: "basket",
    text: "Pick coffee cherries onto the cloth spread under the rows.",
    note: "Enslaved Africans picked the coffee until 1888; Italian colonos took their place.",
    sources: ["https://en.wikipedia.org/wiki/Coffee_production_in_Brazil"],
  },
];

const CHRISTMAS = {
  evidence: "documented" as const,
  date: { dayOfYear: 359 },
  rest: true,
  place: "sanctuary" as const,
  minutes: 120,
  text: "It is Christmas Day: church or midnight mass, then the best meal of the year.",
  sources: ["https://en.wikipedia.org/wiki/Christmas"],
};

export const americasFestivals: Festival[] = [
  {
    id: "fest.us.independence-day",
    label: "the Fourth of July",
    scope: { ...US, years: [1800, 1950] },
    evidence: "documented",
    date: { dayOfYear: 185 },
    rest: true,
    place: "gathering",
    minutes: 150,
    text: "It is the Fourth of July: the Declaration read aloud, a parade, and fireworks after dark.",
    sources: ["https://en.wikipedia.org/wiki/Independence_Day_(United_States)"],
  },
  {
    id: "fest.us.thanksgiving",
    label: "Thanksgiving",
    scope: { ...US, years: [1863, 1950] },
    evidence: "documented",
    date: { dayOfYear: 329 },
    rest: true,
    place: "hearth",
    minutes: 150,
    text: "It is Thanksgiving: church in the morning, then turkey with the whole family.",
    note: "Lincoln fixed it on the last Thursday of November; the date here is an average.",
    sources: ["https://en.wikipedia.org/wiki/Thanksgiving_(United_States)"],
  },
  // New England's Puritans refused Christmas, so before 1750 it is kept only south of them and in New France.
  { ...CHRISTMAS, id: "fest.americas.christmas-south", label: "Christmas", scope: { ...SETTLER, years: [1500, 1750], bounds: [-170, -56, -32, 41] } },
  { ...CHRISTMAS, id: "fest.new-france.christmas", label: "Christmas", scope: { ...NEW_FRANCE, years: [1608, 1750] } },
  { ...CHRISTMAS, id: "fest.americas.christmas", label: "Christmas", scope: { ...SETTLER, years: [1750, 1950] } },
  {
    id: "fest.brazil.carnival",
    label: "Carnival",
    scope: { ...BRAZIL, years: [1840, 1950] },
    evidence: "documented",
    date: { dayOfYear: 50 },
    rest: true,
    place: "gathering",
    minutes: 180,
    text: "It is Carnival: masks, drums and the street processions before Lent.",
    note: "Moveable with Easter; fixed here in mid-February.",
    sources: ["https://en.wikipedia.org/wiki/Brazilian_Carnival"],
  },
  {
    id: "fest.southeast.green-corn",
    label: "the Green Corn busk",
    scope: SOUTHEAST,
    evidence: "documented",
    date: { dayOfYear: 208 },
    rest: true,
    place: "gathering",
    minutes: 150,
    text: "It is the busk: fast, drink the black drink, and take home the new fire from the square ground.",
    note: "Held when the corn ripened, in July or August; old wrongs short of murder were forgiven.",
    sources: ["https://en.wikipedia.org/wiki/Green_Corn_Ceremony"],
  },
  {
    id: "fest.haudenosaunee.midwinter",
    label: "the Midwinter ceremony",
    scope: { ...HAUDENOSAUNEE, years: [1600, 1950] },
    evidence: "documented",
    date: { dayOfYear: 35 },
    rest: true,
    place: "sanctuary",
    minutes: 150,
    text: "It is Midwinter: stir the ashes in every house, and give thanks in the longhouse.",
    note: "Set by the new moon after the Pleiades stand overhead at dusk; the date here is typical.",
    sources: ["https://en.wikipedia.org/wiki/Haudenosaunee"],
  },
  {
    id: "fest.haudenosaunee.strawberry",
    label: "the Strawberry festival",
    scope: HAUDENOSAUNEE,
    evidence: "documented",
    date: { dayOfYear: 165 },
    rest: false,
    place: "sanctuary",
    minutes: 90,
    text: "It is the Strawberry festival: drink the berry juice and thank the first fruit of the year.",
    sources: ["https://en.wikipedia.org/wiki/Iroquois"],
  },
  {
    id: "fest.plains.sun-dance",
    label: "the Sun Dance",
    scope: { ...PLAINS, years: [1750, 1950], bounds: [-110, 40, -94, 55] },
    evidence: "documented",
    date: { dayOfYear: 180 },
    rest: true,
    place: "gathering",
    minutes: 180,
    text: "It is the Sun Dance: the bands camp in one great circle around the cottonwood pole.",
    note: "Held at midsummer; the United States banned it from 1883 and it went on in secret.",
    sources: ["https://en.wikipedia.org/wiki/Sun_Dance"],
  },
  {
    id: "fest.nw-coast.first-salmon",
    label: "the First Salmon ceremony",
    scope: NW_COAST,
    evidence: "documented",
    date: { dayOfYear: 140 },
    rest: false,
    place: "edge",
    minutes: 90,
    text: "It is the first salmon: share its flesh with everyone and return its bones to the river.",
    sources: ["https://en.wikipedia.org/wiki/Indigenous_peoples_of_the_Pacific_Northwest_Coast"],
  },
  {
    id: "fest.inuit.sedna",
    label: "the Sedna feast",
    scope: { ...ARCTIC, years: [1700, 1950], bounds: [-95, 60, -60, 75] },
    evidence: "documented",
    date: { dayOfYear: 290 },
    rest: true,
    place: "gathering",
    minutes: 150,
    text: "It is the Sedna feast: everyone crowds into the qaggiq, the great snow house, to sing and wrestle.",
    note: "Boas saw it on Baffin Island in the 1880s, as the autumn storms began.",
    sources: ["https://en.wikipedia.org/wiki/Sedna_(mythology)"],
  },
  {
    id: "fest.new-england.sabbath",
    label: "the Sabbath",
    scope: NEW_ENGLAND,
    evidence: "documented",
    date: { every: 7, on: 4 },
    rest: true,
    place: "sanctuary",
    minutes: 180,
    text: "It is the Sabbath: two sermons at the meeting house, and no work, travel or play.",
    sources: ["https://en.wikipedia.org/wiki/Sabbatarianism"],
  },
  {
    id: "fest.americas.settler-sunday",
    label: "Sunday",
    scope: SETTLER,
    evidence: "documented",
    date: { every: 7, on: 4 },
    rest: true,
    place: "sanctuary",
    minutes: 90,
    text: "It is Sunday: go to church or to mass, and keep the day from work.",
    sources: ["https://en.wikipedia.org/wiki/Sabbath_in_Christianity"],
  },
];
