import type { Festival, Occasion } from "./types";

const ANATOLIA_NEOLITHIC = { years: [-9000, -5500] as [number, number], bounds: [26, 36, 45, 42] as [number, number, number, number] };
const STEPPE_BRONZE = { years: [-2000, -800] as [number, number], bounds: [25, 35, 130, 60] as [number, number, number, number], cultures: ["inner-eurasian" as const] };
const CENTRAL_ASIA_BRONZE = { years: [-2300, -900] as [number, number], bounds: [52, 33, 75, 46] as [number, number, number, number], cultures: ["inner-eurasian" as const] };
const CHINA = { years: [618, 1912] as [number, number], bounds: [98, 18, 125, 46] as [number, number, number, number], cultures: ["east-asian" as const] };

export const asiaOccasions: Occasion[] = [
  {
    id: "day.anatolia.replaster",
    label: "Re-plastering the walls",
    scope: ANATOLIA_NEOLITHIC,
    evidence: "documented",
    when: [{ type: "adult" }, { type: "chance", p: 0.35 }],
    weight: 5,
    part: "midday",
    place: "home",
    activity: "work",
    minutes: 50,
    carry: "vessel",
    text: "Lay a fresh coat of white clay plaster over the house walls.",
    note: "Çatalhöyük walls carry up to hundreds of thin plaster layers; how often they were renewed is argued over.",
    sources: ["https://en.wikipedia.org/wiki/%C3%87atalh%C3%B6y%C3%BCk"],
    serves: ["household-home", "new-settlement"],
  },
  {
    id: "day.anatolia.platform",
    label: "Plastering over the dead",
    scope: ANATOLIA_NEOLITHIC,
    evidence: "hypothesis",
    when: [{ type: "anniversary", kind: "died" }],
    weight: 16,
    part: "evening",
    place: "home",
    activity: "tend",
    minutes: 40,
    text: "Smooth new plaster over the platform where your {dead} lies beneath the floor.",
    note: "Burial under house platforms is documented; marking a death's day there is our guess.",
    sources: ["https://en.wikipedia.org/wiki/%C3%87atalh%C3%B6y%C3%BCk"],
    serves: ["remember-dead"],
  },
  {
    id: "day.anatolia.rooftops",
    label: "Talk across the roofs",
    scope: ANATOLIA_NEOLITHIC,
    evidence: "documented",
    when: [{ type: "trait", key: "extraversion", above: 45 }],
    weight: 3,
    part: "evening",
    place: "gathering",
    activity: "visit",
    minutes: 35,
    text: "Climb up and talk with the neighbours across the rooftops.",
    note: "Houses were entered through the roof, and the roofscape was where people worked and met.",
    sources: ["https://en.wikipedia.org/wiki/%C3%87atalh%C3%B6y%C3%BCk"],
  },
  {
    id: "day.anatolia.obsidian",
    label: "Knapping obsidian",
    scope: ANATOLIA_NEOLITHIC,
    evidence: "inferred",
    when: [{ type: "adult" }, { type: "chance", p: 0.3 }],
    weight: 3,
    part: "midday",
    place: "home",
    activity: "work",
    minutes: 35,
    text: "Strike fresh blades from a core of Cappadocian obsidian.",
    sources: ["https://en.wikipedia.org/wiki/G%C3%B6ll%C3%BCdag"],
  },
  {
    id: "day.anatolia.first-sheaf",
    label: "The first sheaf",
    scope: ANATOLIA_NEOLITHIC,
    evidence: "hypothesis",
    when: [{ type: "season", any: ["autumn"] }, { type: "chance", p: 0.4 }],
    weight: 5,
    part: "morning",
    place: "sanctuary",
    activity: "visit",
    minutes: 25,
    carry: "basket",
    text: "Leave the first sheaf by the bench set with bull horns.",
    note: "The horn-set benches are real; a harvest offering at them is a reconstruction.",
    sources: ["https://en.wikipedia.org/wiki/%C3%87atalh%C3%B6y%C3%BCk"],
  },
  {
    id: "day.steppe.hearth-portion",
    label: "The hearth's portion",
    scope: STEPPE_BRONZE,
    evidence: "inferred",
    when: [{ type: "observance", levels: ["devout", "regular"] }],
    weight: 4,
    part: "morning",
    place: "hearth",
    activity: "cook",
    minutes: 15,
    text: "Give the hearth fire the first of the meat before anyone eats.",
    sources: ["https://en.wikipedia.org/wiki/Proto-Indo-Iranian_religion"],
    serves: ["household-home"],
  },
  {
    id: "day.steppe.cairn",
    label: "A stone for the cairn",
    scope: STEPPE_BRONZE,
    evidence: "inferred",
    when: [{ type: "chance", p: 0.3 }],
    weight: 3,
    part: "evening",
    place: "edge",
    activity: "visit",
    minutes: 30,
    text: "Add a stone to the cairn on the pass road, for whoever of yours is travelling.",
    sources: ["https://en.wikipedia.org/wiki/Ovoo"],
  },
  {
    id: "day.steppe.horses",
    label: "Hooves before the move",
    scope: STEPPE_BRONZE,
    evidence: "inferred",
    when: [{ type: "season", any: ["spring"] }, { type: "work", match: /horse/i }],
    weight: 5,
    part: "morning",
    place: "work",
    activity: "tend",
    minutes: 40,
    text: "Look over the horses' hooves before the move to summer pasture.",
    sources: ["https://en.wikipedia.org/wiki/Andronovo_culture"],
  },
  {
    id: "day.central-asia.tin",
    label: "Bartering for tin",
    scope: CENTRAL_ASIA_BRONZE,
    evidence: "documented",
    when: [{ type: "work", match: /smith|metal|armou?r|bronze|found|cast/i }, { type: "chance", p: 0.35 }],
    weight: 6,
    part: "midday",
    place: "market",
    activity: "visit",
    minutes: 35,
    carry: "bundle",
    text: "Barter for Zeravshan tin to alloy the next batch of bronze.",
    note: "Bronze Age tin mines at Mushiston and Karnab in the Zeravshan valley are among the few known in Eurasia.",
    sources: ["https://en.wikipedia.org/wiki/Zarafshan_River"],
  },
  {
    id: "day.central-asia.sauma",
    label: "Pressing the *sauma",
    scope: CENTRAL_ASIA_BRONZE,
    evidence: "hypothesis",
    when: [{ type: "observance", levels: ["devout"] }, { type: "adult" }],
    weight: 5,
    part: "morning",
    place: "hearth",
    activity: "cook",
    minutes: 30,
    text: "Help press the *sauma stalks at the fire before dawn.",
    note: "Indo-Iranian *sauma is reconstructed from Vedic soma and Avestan haoma; residue claims from Gonur Tepe are disputed.",
    sources: ["https://en.wikipedia.org/wiki/Haoma"],
  },
  {
    id: "day.central-asia.new-fire",
    label: "The new fire of the year",
    scope: CENTRAL_ASIA_BRONZE,
    evidence: "hypothesis",
    when: [{ type: "date", dayOfYear: 80 }],
    weight: 16,
    part: "evening",
    place: "hearth",
    activity: "warm",
    minutes: 45,
    text: "Put out the old hearth and kindle a new fire at the turn of the year.",
    note: "Nowruz at the spring equinox is attested much later; a Bronze Age forerunner is a guess.",
    sources: ["https://en.wikipedia.org/wiki/Nowruz"],
  },
  {
    id: "day.china.incense-first",
    label: "Incense on the first",
    scope: CHINA,
    evidence: "documented",
    when: [{ type: "cycle", every: 9, on: 0 }, { type: "adult" }],
    weight: 8,
    part: "morning",
    place: "home",
    activity: "visit",
    minutes: 15,
    text: "Burn incense before the ancestral tablets: it is the first of the month.",
    sources: ["https://en.wikipedia.org/wiki/Ancestral_shrine"],
    serves: ["remember-dead"],
  },
  {
    id: "day.china.incense-fifteenth",
    label: "Incense on the fifteenth",
    scope: CHINA,
    evidence: "documented",
    when: [{ type: "cycle", every: 9, on: 4 }, { type: "adult" }],
    weight: 8,
    part: "morning",
    place: "home",
    activity: "visit",
    minutes: 15,
    text: "Burn incense before the ancestral tablets: it is the full moon.",
    sources: ["https://en.wikipedia.org/wiki/Ancestral_shrine"],
    serves: ["remember-dead"],
  },
  {
    id: "day.china.kitchen-god",
    label: "Seeing off the Kitchen God",
    scope: CHINA,
    evidence: "documented",
    when: [{ type: "date", dayOfYear: 28 }],
    weight: 16,
    part: "evening",
    place: "hearth",
    activity: "cook",
    minutes: 20,
    text: "Smear malt sugar on the Kitchen God's lips before he goes up to report on the house.",
    sources: ["https://en.wikipedia.org/wiki/Kitchen_God"],
    serves: ["household-home"],
  },
];

export const asiaFestivals: Festival[] = [
  {
    id: "fest.china.new-year",
    label: "the New Year",
    scope: CHINA,
    evidence: "documented",
    date: { dayOfYear: 36 },
    rest: true,
    place: "gathering",
    minutes: 120,
    text: "It is the New Year: no work, new clothes, and calls on kin.",
    note: "The date moves with the moon between late January and mid-February.",
    sources: ["https://en.wikipedia.org/wiki/Chinese_New_Year"],
  },
  {
    id: "fest.china.qingming",
    label: "Qingming",
    scope: CHINA,
    evidence: "documented",
    date: { dayOfYear: 95 },
    rest: true,
    place: "edge",
    minutes: 120,
    text: "It is Qingming: sweep the family graves and leave food for the dead.",
    sources: ["https://en.wikipedia.org/wiki/Qingming_Festival"],
  },
  {
    id: "fest.china.mid-autumn",
    label: "the Mid-Autumn festival",
    scope: { ...CHINA, years: [1000, 1912] },
    evidence: "documented",
    date: { dayOfYear: 263 },
    rest: false,
    place: "gathering",
    minutes: 60,
    text: "Watch the full moon rise, with round cakes, at the Mid-Autumn festival.",
    sources: ["https://en.wikipedia.org/wiki/Mid-Autumn_Festival"],
  },
];
