import type { Occasion } from "./types";

const FORAGERS = { years: [-300000, -9000] as [number, number] };
const MODERN = { years: [1900, 10001] as [number, number] };

/**
 * The two ends of the range that belong to no one region: people who lived by
 * foraging before any farming, and the twentieth-century town that looks
 * alike from Lagos to Osaka.
 */
export const deepAndModernOccasions: Occasion[] = [
  {
    id: "day.forager.share-meat",
    label: "Sharing out the kill",
    scope: FORAGERS,
    evidence: "inferred",
    when: [{ type: "adult" }, { type: "chance", p: 0.3 }],
    weight: 4,
    part: "evening",
    place: "hearth",
    activity: "warm",
    minutes: 40,
    text: "Share out the meat so that every hearth gets its portion.",
    note: "Among recorded foragers the hunter rarely keeps the kill; it goes round by rule.",
    sources: ["https://en.wikipedia.org/wiki/Demand_sharing"],
  },
  {
    id: "day.forager.knap",
    label: "Knapping a point",
    scope: FORAGERS,
    evidence: "documented",
    when: [{ type: "adult" }, { type: "chance", p: 0.35 }],
    weight: 3,
    part: "midday",
    place: "home",
    activity: "work",
    minutes: 40,
    text: "Knap a new point from the good flint and haft it.",
    sources: ["https://en.wikipedia.org/wiki/Knapping"],
  },
  {
    id: "day.forager.hide",
    label: "Scraping a hide",
    scope: FORAGERS,
    evidence: "documented",
    when: [{ type: "adult" }, { type: "chance", p: 0.3 }],
    weight: 3,
    part: "midday",
    place: "home",
    activity: "tend",
    minutes: 45,
    text: "Scrape the fat from a hide with an end-scraper.",
    sources: ["https://en.wikipedia.org/wiki/Scraper_(archaeology)"],
  },
  {
    id: "day.forager.ochre",
    label: "Grinding ochre",
    scope: FORAGERS,
    evidence: "documented",
    when: [{ type: "chance", p: 0.2 }],
    weight: 3,
    part: "evening",
    place: "hearth",
    activity: "warm",
    minutes: 25,
    text: "Grind red ochre with fat and paint it on for the gathering.",
    sources: ["https://en.wikipedia.org/wiki/Ochre"],
  },
  {
    id: "day.forager.teach-tracks",
    label: "Teaching tracks",
    scope: FORAGERS,
    evidence: "inferred",
    when: [{ type: "kin", kind: "child", minAge: 6, maxAge: 15 }],
    weight: 4,
    part: "morning",
    place: "wild",
    activity: "gather",
    minutes: 40,
    text: "Walk {child} out and show which tracks are fresh.",
    serves: ["raise-kin", "child-future"],
    sources: [],
  },
  {
    id: "day.forager.scout",
    label: "Scouting the next camp",
    scope: FORAGERS,
    evidence: "inferred",
    when: [{ type: "trait", key: "openness", above: 50 }, { type: "chance", p: 0.25 }],
    weight: 3,
    part: "midday",
    place: "wild",
    activity: "visit",
    minutes: 50,
    text: "Walk out to see whether the next camp has water and game.",
    serves: ["new-settlement"],
    sources: [],
  },
  {
    id: "day.forager.story",
    label: "Telling it at the fire",
    scope: FORAGERS,
    evidence: "inferred",
    when: [{ type: "trait", key: "extraversion", above: 55 }, { type: "chance", p: 0.4 }],
    weight: 3,
    part: "evening",
    place: "hearth",
    activity: "warm",
    minutes: 40,
    text: "Tell the day's hunt at the fire, with the parts acted out.",
    sources: [],
  },
  {
    id: "day.modern.cinema",
    label: "The pictures",
    scope: MODERN,
    evidence: "documented",
    when: [{ type: "trait", key: "openness", above: 45 }, { type: "chance", p: 0.25 }],
    weight: 4,
    part: "evening",
    place: { venue: "theatre" },
    activity: "visit",
    minutes: 110,
    text: "Queue for the evening picture show.",
    sources: ["https://en.wikipedia.org/wiki/Movie_theater"],
    fallback: true,
  },
  {
    id: "day.modern.letter",
    label: "Writing to family away",
    scope: MODERN,
    evidence: "inferred",
    when: [{ type: "tag", any: ["literate"] }, { type: "chance", p: 0.2 }],
    weight: 3,
    part: "evening",
    place: "home",
    activity: "visit",
    minutes: 30,
    text: "Write to the relatives who moved to the city, and post it.",
    sources: [],
    fallback: true,
  },
  {
    id: "day.modern.clinic",
    label: "The clinic",
    scope: { years: [1920, 10001] },
    evidence: "inferred",
    when: [{ type: "kin", kind: "child", maxAge: 6 }, { type: "chance", p: 0.1 }],
    weight: 5,
    part: "morning",
    place: "door",
    activity: "visit",
    minutes: 60,
    text: "Take {child} to the clinic for the injection.",
    serves: ["raise-kin"],
    sources: ["https://en.wikipedia.org/wiki/Vaccination_schedule"],
    fallback: true,
  },
  {
    id: "day.modern.wireless",
    label: "The wireless",
    scope: { years: [1925, 10001] },
    evidence: "documented",
    when: [{ type: "chance", p: 0.3 }],
    weight: 2,
    part: "evening",
    place: "home",
    activity: "rest",
    minutes: 40,
    text: "Sit by the wireless for the evening news.",
    sources: ["https://en.wikipedia.org/wiki/Golden_age_of_radio"],
    fallback: true,
  },
  {
    id: "day.modern.football",
    label: "The match",
    scope: MODERN,
    evidence: "documented",
    when: [{ type: "cycle", every: 7, on: 3 }, { type: "trait", key: "extraversion", above: 50 }, { type: "sex", is: "male" }],
    weight: 4,
    part: "midday",
    place: "edge",
    activity: "visit",
    minutes: 110,
    text: "Stand on the terraces for the afternoon match.",
    sources: ["https://en.wikipedia.org/wiki/Association_football_culture"],
    fallback: true,
  },
  {
    id: "day.modern.photograph",
    label: "A photograph",
    scope: MODERN,
    evidence: "inferred",
    when: [{ type: "anniversary", kind: "wed" }, { type: "kin", kind: "partner" }],
    weight: 10,
    part: "midday",
    place: "market",
    activity: "visit",
    minutes: 40,
    text: "Sit for a photograph with {partner}: {nth} year married.",
    serves: ["shared-future"],
    sources: ["https://en.wikipedia.org/wiki/Portrait_photography"],
    fallback: true,
  },
];
