import type { Festival, Occasion } from "./types";

type Box = [number, number, number, number];
const EA = ["east-asian" as const];
const CN: Box = [98, 18, 123, 46];
const KR: Box = [124, 33, 129.6, 43];
const JP: Box = [129.7, 30, 146, 46];

const YANGSHAO = { years: [-5000, -2900] as [number, number], bounds: [104, 32, 116, 38] as Box, cultures: EA };
const LONGSHAN = { years: [-3000, -1900] as [number, number], bounds: [110, 33, 122, 40] as Box, cultures: EA };
const LIANGZHU = { years: [-3300, -2300] as [number, number], bounds: [118, 29, 122, 32.5] as Box, cultures: EA };
const SHANG = { years: [-1600, -1046] as [number, number], bounds: [110, 32, 122, 40] as Box, cultures: EA };
const ZHOU = { years: [-1046, -221] as [number, number], bounds: CN, cultures: EA };
const HAN = { years: [-206, 220] as [number, number], bounds: CN, cultures: EA };
const EARLY_IMPERIAL = { years: [-206, 618] as [number, number], bounds: CN, cultures: EA };
const LATE_IMPERIAL = { years: [960, 1912] as [number, number], bounds: CN, cultures: EA };
const REPUBLIC = { years: [1912, 1950] as [number, number], bounds: CN, cultures: EA };

const JOMON = { years: [-14000, -900] as [number, number], bounds: JP, cultures: EA };
const YAYOI = { years: [-900, 250] as [number, number], bounds: JP, cultures: EA };
const KOFUN = { years: [250, 600] as [number, number], bounds: JP, cultures: EA };
const HEIAN = { years: [710, 1185] as [number, number], bounds: JP, cultures: EA };
const MEDIEVAL_JAPAN = { years: [1185, 1603] as [number, number], bounds: JP, cultures: EA };
const EDO = { years: [1603, 1868] as [number, number], bounds: JP, cultures: EA };
const MODERN_JAPAN = { years: [1868, 1950] as [number, number], bounds: JP, cultures: EA };

const MUMUN = { years: [-1500, -300] as [number, number], bounds: KR, cultures: EA };
const SILLA = { years: [-57, 935] as [number, number], bounds: [126.5, 34.5, 129.6, 37.5] as Box, cultures: EA };
const GORYEO = { years: [918, 1392] as [number, number], bounds: KR, cultures: EA };
const JOSEON = { years: [1392, 1950] as [number, number], bounds: KR, cultures: EA };

export const eastAsiaOccasions: Occasion[] = [
  {
    id: "day.yangshao.fish-basin",
    label: "Painting the fish-face basin",
    scope: YANGSHAO,
    evidence: "documented",
    when: [{ type: "work", match: /pot|clay|kiln/i }, { type: "chance", p: 0.35 }],
    weight: 6,
    part: "midday",
    place: "work",
    activity: "work",
    minutes: 45,
    text: "Paint the fish-and-face design in black on a red basin before firing.",
    note: "The masked face flanked by fish is the signature motif of the Banpo pottery.",
    sources: ["https://en.wikipedia.org/wiki/Banpo", "https://en.wikipedia.org/wiki/Yangshao_culture"],
  },
  {
    id: "day.yangshao.child-urn",
    label: "The urn by the house",
    scope: YANGSHAO,
    evidence: "hypothesis",
    when: [{ type: "anniversary", kind: "died", as: ["son", "daughter"] }],
    weight: 16,
    part: "evening",
    place: "home",
    activity: "visit",
    minutes: 25,
    text: "Sit by the urn under the eaves where your {dead} was laid.",
    note: "At Banpo small children were buried in urns beside the houses, the lids pierced with a small hole.",
    sources: ["https://en.wikipedia.org/wiki/Banpo"],
    serves: ["remember-dead"],
  },
  {
    id: "day.longshan.scapula",
    label: "Reading a shoulder blade",
    scope: LONGSHAN,
    evidence: "documented",
    when: [{ type: "observance", levels: ["devout", "regular"] }, { type: "adult" }, { type: "chance", p: 0.25 }],
    weight: 5,
    part: "evening",
    place: "hearth",
    activity: "warm",
    minutes: 30,
    text: "Scorch a sheep's shoulder blade in the fire and read the cracks.",
    note: "Longshan sites have unprepared burnt scapulae, the ancestors of the Shang oracle bones.",
    sources: ["https://en.wikipedia.org/wiki/Longshan_culture", "https://en.wikipedia.org/wiki/Scapulimancy"],
  },
  {
    id: "day.liangzhu.dam",
    label: "Earth for the dam",
    scope: LIANGZHU,
    evidence: "inferred",
    when: [{ type: "season", any: ["winter"] }, { type: "adult" }, { type: "chance", p: 0.3 }],
    weight: 5,
    part: "morning",
    place: "edge",
    activity: "haul",
    minutes: 60,
    carry: "bundle",
    text: "Carry grass-wrapped bundles of clay up to the dam in the hills.",
    note: "The Liangzhu dams were built of clay packed in bundles of grass and reed.",
    sources: ["https://en.wikipedia.org/wiki/Archaeological_Ruins_of_Liangzhu_City"],
    serves: ["new-settlement"],
  },
  {
    id: "day.shang.plastron",
    label: "A question for the diviners",
    scope: SHANG,
    evidence: "inferred",
    when: [{ type: "rank", any: ["gentry", "elite"] }, { type: "chance", p: 0.25 }],
    weight: 6,
    part: "morning",
    place: "sanctuary",
    activity: "visit",
    minutes: 40,
    text: "Bring a question for the diviners to crack into a turtle plastron.",
    note: "Most inscribed bones are the king's, but Anyang also yields divinations by non-royal lineages.",
    sources: ["https://en.wikipedia.org/wiki/Oracle_bone"],
  },
  {
    id: "day.shang.day-name",
    label: "The ancestor's day",
    scope: SHANG,
    evidence: "inferred",
    when: [{ type: "cycle", every: 3, on: 0 }, { type: "observance", levels: ["devout", "regular"] }, { type: "adult" }],
    weight: 6,
    part: "morning",
    place: "hearth",
    activity: "visit",
    minutes: 25,
    carry: "vessel",
    text: "Pour millet wine for the ancestor whose day-name falls today.",
    note: "Shang kings sacrificed to each ancestor on the day of the ten-day week that matched his name, such as Da Yi on a yi day.",
    sources: ["https://en.wikipedia.org/wiki/Shang_dynasty", "https://en.wikipedia.org/wiki/Heavenly_Stems"],
    serves: ["remember-dead"],
  },
  {
    id: "day.zhou.she-altar",
    label: "The altar of the soil",
    scope: ZHOU,
    evidence: "documented",
    when: [{ type: "season", any: ["spring"] }, { type: "adult" }, { type: "chance", p: 0.3 }],
    weight: 6,
    part: "morning",
    place: "sanctuary",
    activity: "visit",
    minutes: 40,
    carry: "vessel",
    text: "Offer wine and meat at the she altar of the soil before the ploughing.",
    sources: ["https://en.wikipedia.org/wiki/Sheji"],
  },
  {
    id: "day.zhou.odes",
    label: "Reciting the Odes",
    scope: { ...ZHOU, years: [-600, -221] },
    evidence: "documented",
    when: [{ type: "rank", any: ["gentry", "elite"] }, { type: "kin", kind: "friend" }, { type: "trait", key: "openness", above: 45 }],
    weight: 5,
    part: "evening",
    place: { kin: "friend" },
    activity: "visit",
    minutes: 40,
    text: "Trade verses from the Odes with {friend}, as a gentleman should.",
    note: "Confucius told his son that without studying the Odes he would have nothing to say.",
    sources: ["https://en.wikipedia.org/wiki/Classic_of_Poetry"],
  },
  {
    id: "day.china.market-drum",
    label: "Before the market drum",
    scope: { years: [-206, 907], bounds: CN, cultures: EA },
    evidence: "documented",
    when: [{ type: "adult" }, { type: "chance", p: 0.3 }],
    weight: 4,
    part: "midday",
    place: "market",
    activity: "visit",
    minutes: 45,
    carry: "basket",
    text: "Get to the walled market before the drum sounds to close its gates.",
    note: "Tang Chang'an's East and West Markets opened at noon to three hundred drumbeats and shut at dusk to a gong.",
    sources: ["https://en.wikipedia.org/wiki/Chang%27an"],
  },
  {
    id: "day.china.cold-food",
    label: "The Cold Food day",
    scope: EARLY_IMPERIAL,
    evidence: "documented",
    when: [{ type: "date", dayOfYear: 93 }],
    weight: 14,
    part: "morning",
    place: "hearth",
    activity: "cook",
    minutes: 15,
    text: "Eat cold barley gruel and light no fire, for Jie Zitui.",
    note: "Around Taiyuan the fire ban once ran a whole month, and Han and Wei rulers tried to shorten it.",
    sources: ["https://en.wikipedia.org/wiki/Cold_Food_Festival"],
  },
  {
    id: "day.han.xiwangmu",
    label: "A prayer to the Queen Mother",
    scope: HAN,
    evidence: "documented",
    when: [{ type: "observance", levels: ["devout"] }, { type: "chance", p: 0.3 }],
    weight: 5,
    part: "evening",
    place: "sanctuary",
    activity: "visit",
    minutes: 25,
    text: "Pray to Xiwangmu, Queen Mother of the West, for long life.",
    note: "In 3 BCE crowds passed her tokens from hand to hand across the empire, expecting her coming.",
    sources: ["https://en.wikipedia.org/wiki/Queen_Mother_of_the_West"],
  },
  {
    id: "day.china.morning-greeting",
    label: "The morning greeting",
    scope: { years: [-206, 1950], bounds: CN, cultures: EA },
    evidence: "documented",
    when: [{ type: "kin", kind: "parent", minAge: 55 }, { type: "trait", key: "agreeableness", above: 50 }],
    weight: 5,
    part: "morning",
    place: { kin: "parent" },
    activity: "visit",
    minutes: 15,
    carry: "vessel",
    text: "Bring warm water to {parent} and ask how the night passed.",
    note: "The Book of Rites has a son settle his parents at night and ask after them at dawn.",
    sources: ["https://en.wikipedia.org/wiki/Filial_piety", "https://en.wikipedia.org/wiki/Book_of_Rites"],
    serves: ["elder-kin"],
  },
  {
    id: "day.china.hungry-ghosts",
    label: "Feeding the hungry ghosts",
    scope: { years: [500, 1950], bounds: CN, cultures: EA },
    evidence: "documented",
    when: [{ type: "date", dayOfYear: 228 }],
    weight: 14,
    part: "evening",
    place: "edge",
    activity: "visit",
    minutes: 40,
    carry: "basket",
    text: "Set out rice and burn paper money for the hungry ghosts at the lane's end.",
    note: "Held on the fifteenth of the seventh lunar month, which falls in August or early September.",
    sources: ["https://en.wikipedia.org/wiki/Ghost_Festival"],
    serves: ["remember-dead"],
  },
  {
    id: "day.china.double-ninth",
    label: "Climbing on the Double Ninth",
    scope: { years: [-100, 1950], bounds: CN, cultures: EA },
    evidence: "documented",
    when: [{ type: "date", dayOfYear: 290 }],
    weight: 14,
    part: "midday",
    place: "edge",
    activity: "visit",
    minutes: 60,
    text: "Climb a hill with a sprig of dogwood and drink chrysanthemum wine.",
    note: "Held on the ninth of the ninth lunar month, in October; later also a day for honouring the old.",
    sources: ["https://en.wikipedia.org/wiki/Double_Ninth_Festival"],
    serves: ["elder-kin"],
  },
  {
    id: "day.song.storyteller",
    label: "The storyteller in the wazi",
    scope: { years: [960, 1279], bounds: CN, cultures: EA },
    evidence: "documented",
    when: [{ type: "trait", key: "extraversion", above: 45 }, { type: "chance", p: 0.2 }],
    weight: 4,
    part: "evening",
    place: "gathering",
    activity: "visit",
    minutes: 60,
    text: "Stand in the crowd at the pleasure quarter to hear the Three Kingdoms told.",
    note: "Meng Yuanlao names storytellers in Kaifeng's wazi who did nothing but the Three Kingdoms.",
    sources: ["https://en.wikipedia.org/wiki/Dongjing_Meng_Hua_Lu"],
  },
  {
    id: "day.china.teahouse",
    label: "Tea and news",
    scope: { years: [960, 1950], bounds: CN, cultures: EA },
    evidence: "documented",
    when: [{ type: "sex", is: "male" }, { type: "adult" }, { type: "chance", p: 0.25 }],
    weight: 4,
    part: "morning",
    place: { venue: "coffee-house" },
    activity: "visit",
    minutes: 50,
    text: "Take a pot of tea at the teahouse and hear what the town is saying.",
    sources: ["https://en.wikipedia.org/wiki/Chinese_tea_culture"],
  },
  {
    id: "day.china.eight-legged",
    label: "Practising the eight-legged essay",
    scope: { years: [1487, 1905], bounds: CN, cultures: EA },
    evidence: "documented",
    when: [{ type: "work", match: /schol|student|tutor|teach|clerk|official|scribe/i }],
    weight: 6,
    part: "evening",
    place: "home",
    activity: "work",
    minutes: 60,
    text: "Copy out a model eight-legged essay against the next examinations.",
    note: "Commercial collections of successful exam essays sold in the hundreds of titles.",
    sources: ["https://en.wikipedia.org/wiki/Eight-legged_essay", "https://en.wikipedia.org/wiki/Imperial_examination"],
    serves: ["mastery", "child-future"],
  },
  {
    id: "day.china.temple-fair",
    label: "The temple fair",
    scope: LATE_IMPERIAL,
    evidence: "documented",
    when: [{ type: "cycle", every: 9, on: 3 }, { type: "chance", p: 0.5 }],
    weight: 6,
    part: "midday",
    place: { venue: "temple-yard" },
    activity: "visit",
    minutes: 60,
    text: "Browse the stalls and the acrobats at the temple fair.",
    note: "Beijing's big temples kept fixed fair days each month: Longfu Temple on the ninth and tenth.",
    sources: ["https://en.wikipedia.org/wiki/Temple_fair"],
  },
  {
    id: "day.china.lu-ban",
    label: "Lu Ban's birthday",
    scope: LATE_IMPERIAL,
    evidence: "documented",
    when: [{ type: "date", dayOfYear: 200 }, { type: "work", match: /carpent|join|mason|build|wood/i }],
    weight: 14,
    part: "morning",
    place: "sanctuary",
    activity: "visit",
    minutes: 50,
    text: "Burn incense to Lu Ban with the carpenters' guild, then eat together.",
    note: "His birthday fell on the thirteenth of the sixth lunar month, in July.",
    sources: ["https://en.wikipedia.org/wiki/Lu_Ban"],
  },
  {
    id: "day.republic.new-life",
    label: "Minding the New Life rules",
    scope: { ...REPUBLIC, years: [1934, 1949] },
    evidence: "documented",
    when: [{ type: "adult" }, { type: "chance", p: 0.15 }],
    weight: 3,
    part: "morning",
    place: "home",
    activity: "tend",
    minutes: 20,
    text: "Sweep the doorstep before the New Life inspectors come round.",
    note: "The movement's rules ran to not spitting, fastening every button and queueing.",
    sources: ["https://en.wikipedia.org/wiki/New_Life_Movement"],
  },
  {
    id: "day.jomon.acorns",
    label: "Leaching acorns",
    scope: JOMON,
    evidence: "documented",
    when: [{ type: "season", any: ["autumn", "winter"] }, { type: "chance", p: 0.4 }],
    weight: 5,
    part: "midday",
    place: "edge",
    activity: "gather",
    minutes: 45,
    carry: "basket",
    text: "Leave the acorns in the spring-fed pit to wash the bitterness out.",
    note: "Waterlogged Jomon storage pits still hold acorns and horse chestnuts.",
    sources: ["https://en.wikipedia.org/wiki/J%C5%8Dmon_period"],
  },
  {
    id: "day.jomon.dogu",
    label: "Breaking a dogu",
    scope: JOMON,
    evidence: "hypothesis",
    when: [{ type: "fortune", below: 40 }, { type: "chance", p: 0.15 }],
    weight: 5,
    part: "evening",
    place: "edge",
    activity: "visit",
    minutes: 20,
    text: "Bury the pieces of a broken dogu figure, to carry a sickness away.",
    note: "Most dogu are found deliberately broken; why is not known.",
    sources: ["https://en.wikipedia.org/wiki/Dog%C5%AB"],
  },
  {
    id: "day.yayoi.paddy",
    label: "Treading the paddy",
    scope: YAYOI,
    evidence: "documented",
    when: [{ type: "season", any: ["spring"] }, { type: "adult" }, { type: "chance", p: 0.4 }],
    weight: 5,
    part: "morning",
    place: "edge",
    activity: "tend",
    minutes: 60,
    text: "Tread the paddy mud smooth in wooden field-clogs.",
    note: "Wooden tageta and paddy dikes were found at the Toro site in Shizuoka.",
    sources: ["https://en.wikipedia.org/wiki/Yayoi_period"],
  },
  {
    id: "day.yayoi.bone",
    label: "Scorching a deer bone",
    scope: YAYOI,
    evidence: "documented",
    when: [{ type: "fortune", above: 30 }, { type: "adult" }, { type: "chance", p: 0.15 }],
    weight: 5,
    part: "evening",
    place: "hearth",
    activity: "warm",
    minutes: 25,
    text: "Scorch a deer's shoulder blade to see whether the journey will go well.",
    note: "The Wei zhi says the Wa burn bones to divine before any undertaking.",
    sources: ["https://en.wikipedia.org/wiki/Wa_(Japan)"],
  },
  {
    id: "day.kofun.haniwa",
    label: "Shaping haniwa",
    scope: KOFUN,
    evidence: "documented",
    when: [{ type: "work", match: /pot|clay|kiln/i }],
    weight: 6,
    part: "midday",
    place: "work",
    activity: "work",
    minutes: 60,
    text: "Build up clay cylinders for the haniwa ring around the lord's mound.",
    sources: ["https://en.wikipedia.org/wiki/Haniwa"],
  },
  {
    id: "day.heian.poem",
    label: "A poem tied to a branch",
    scope: HEIAN,
    evidence: "documented",
    when: [{ type: "rank", any: ["gentry", "elite"] }, { type: "kin", kind: "partner" }, { type: "chance", p: 0.3 }],
    weight: 6,
    part: "morning",
    place: "home",
    activity: "rest",
    minutes: 30,
    text: "Write a poem for {partner} and send it tied to a sprig of plum.",
    note: "Married couples often lived apart; the husband visited by night and sent a poem at dawn.",
    sources: ["https://en.wikipedia.org/wiki/Heian_period", "https://en.wikipedia.org/wiki/Waka_(poetry)"],
  },
  {
    id: "day.japan.nembutsu",
    label: "Calling Amida's name",
    scope: MEDIEVAL_JAPAN,
    evidence: "documented",
    when: [{ type: "observance", levels: ["devout", "regular"] }, { type: "chance", p: 0.4 }],
    weight: 5,
    part: "evening",
    place: "sanctuary",
    activity: "visit",
    minutes: 30,
    text: "Chant Namu Amida Butsu with the others at the chapel.",
    sources: ["https://en.wikipedia.org/wiki/Nianfo", "https://en.wikipedia.org/wiki/J%C5%8Ddo-sh%C5%AB"],
  },
  {
    id: "day.japan.yokkaichi",
    label: "The fixed-day market",
    scope: { years: [1200, 1650], bounds: JP, cultures: EA },
    evidence: "documented",
    when: [{ type: "cycle", every: 3, on: 1 }, { type: "adult" }],
    weight: 6,
    part: "midday",
    place: "market",
    activity: "visit",
    minutes: 45,
    carry: "basket",
    text: "Take your goods to the fixed-day market: it meets three days a month.",
    note: "Place names like Yokkaichi, the fourth-day market, record these thrice-monthly fairs.",
    sources: ["https://en.wikipedia.org/wiki/Yokkaichi"],
  },
  {
    id: "day.japan.taue",
    label: "Planting to the field drums",
    scope: { years: [900, 1950], bounds: JP, cultures: EA },
    evidence: "documented",
    when: [{ type: "date", dayOfYear: 165 }, { type: "sex", is: "female" }, { type: "adult" }],
    weight: 12,
    part: "morning",
    place: "edge",
    activity: "tend",
    minutes: 90,
    text: "Plant rice seedlings in a line with the other women, to the field drums.",
    note: "The planting women, saotome, set seedlings to songs and drums led by a sanbai singer.",
    sources: ["https://en.wikipedia.org/wiki/Mibu_no_Hana_Taue"],
  },
  {
    id: "day.edo.sento",
    label: "An evening at the sento",
    scope: { years: [1603, 1950], bounds: JP, cultures: EA },
    evidence: "documented",
    when: [{ type: "chance", p: 0.35 }],
    weight: 4,
    part: "evening",
    place: { venue: "bath" },
    activity: "visit",
    minutes: 50,
    text: "Soak at the sento and stay for the talk in the room upstairs.",
    note: "Edo bathhouses had a men's lounge on the second floor with tea, sweets and go boards.",
    sources: ["https://en.wikipedia.org/wiki/Sent%C5%8D"],
  },
  {
    id: "day.edo.kabuki",
    label: "A day at the kabuki",
    scope: EDO,
    evidence: "documented",
    when: [{ type: "rank", any: ["middling", "gentry"] }, { type: "chance", p: 0.06 }],
    weight: 4,
    part: "midday",
    place: { venue: "theatre" },
    activity: "visit",
    minutes: 180,
    text: "Spend the day at the kabuki with a box lunch for the interval.",
    note: "Makunouchi, 'between the acts', is the name of the lunch box eaten there.",
    sources: ["https://en.wikipedia.org/wiki/Kabuki", "https://en.wikipedia.org/wiki/Bento"],
  },
  {
    id: "day.edo.ennichi",
    label: "Kannon's fair day",
    scope: { years: [1603, 1950], bounds: JP, cultures: EA },
    evidence: "documented",
    when: [{ type: "cycle", every: 9, on: 6 }, { type: "chance", p: 0.5 }],
    weight: 6,
    part: "evening",
    place: { venue: "temple-yard" },
    activity: "visit",
    minutes: 50,
    text: "Visit Kannon on her fair day and buy a potted plant from the stalls.",
    note: "The eighteenth of each month was Kannon's ennichi, and Asakusa filled with night stalls.",
    sources: ["https://en.wikipedia.org/wiki/Sens%C5%8D-ji"],
  },
  {
    id: "day.edo.koshin",
    label: "The Koshin vigil",
    scope: EDO,
    evidence: "documented",
    when: [{ type: "cycle", every: 18, on: 7 }, { type: "adult" }],
    weight: 8,
    part: "evening",
    place: "gathering",
    activity: "warm",
    minutes: 90,
    text: "Sit up all night with the Koshin group, so the three worms cannot report you.",
    note: "Every sixtieth day the worms were thought to leave the sleeping body and tell heaven your sins.",
    sources: ["https://en.wikipedia.org/wiki/K%C5%8Dshin"],
  },
  {
    id: "day.edo.terakoya",
    label: "To the temple school",
    scope: { years: [1603, 1872], bounds: JP, cultures: EA },
    evidence: "documented",
    when: [{ type: "kin", kind: "child", minAge: 6, maxAge: 13 }, { type: "chance", p: 0.5 }],
    weight: 5,
    part: "morning",
    place: { venue: "school" },
    activity: "visit",
    minutes: 20,
    carry: "bundle",
    text: "Walk {child} to the terakoya with brush, inkstone and copybook.",
    sources: ["https://en.wikipedia.org/wiki/Terakoya"],
    serves: ["child-future"],
  },
  {
    id: "day.edo.setsubun",
    label: "Scattering beans",
    scope: { years: [1603, 1950], bounds: JP, cultures: EA },
    evidence: "documented",
    when: [{ type: "date", dayOfYear: 34 }],
    weight: 16,
    part: "evening",
    place: "home",
    activity: "play",
    minutes: 20,
    text: "Scatter roasted soybeans out of the door to drive the demons off.",
    note: "The cry is 'Oni wa soto, fuku wa uchi': demons out, luck in.",
    sources: ["https://en.wikipedia.org/wiki/Setsubun"],
    serves: ["household-home"],
  },
  {
    id: "day.japan.radio-taiso",
    label: "Radio calisthenics",
    scope: { ...MODERN_JAPAN, years: [1928, 1950] },
    evidence: "documented",
    when: [{ type: "season", any: ["summer"] }, { type: "chance", p: 0.4 }],
    weight: 4,
    part: "morning",
    place: "gathering",
    activity: "play",
    minutes: 15,
    text: "Do the radio exercises with the neighbourhood in the morning cool.",
    sources: ["https://en.wikipedia.org/wiki/Radio_calisthenics"],
  },
  {
    id: "day.mumun.dolmen",
    label: "Dragging a capstone",
    scope: MUMUN,
    evidence: "inferred",
    when: [{ type: "adult" }, { type: "sex", is: "male" }, { type: "chance", p: 0.12 }],
    weight: 5,
    part: "midday",
    place: "edge",
    activity: "haul",
    minutes: 90,
    text: "Haul on the ropes to drag a capstone for the new dolmen.",
    note: "The Korean peninsula holds perhaps a third of the world's dolmens.",
    sources: ["https://en.wikipedia.org/wiki/Gochang,_Hwasun_and_Ganghwa_Dolmen_Sites"],
    serves: ["remember-dead"],
  },
  {
    id: "day.silla.gabae",
    label: "Weaving for the gabae",
    scope: SILLA,
    evidence: "documented",
    when: [{ type: "season", any: ["summer", "autumn"] }, { type: "sex", is: "female" }, { type: "chance", p: 0.35 }],
    weight: 6,
    part: "evening",
    place: "gathering",
    activity: "work",
    minutes: 60,
    text: "Spin hemp late with your side of the village for the weaving contest.",
    note: "The Samguk sagi says the losing side stood the winners a feast at the full moon of the eighth month.",
    sources: ["https://en.wikipedia.org/wiki/Chuseok"],
  },
  {
    id: "day.goryeo.celadon",
    label: "Inlaying celadon",
    scope: { ...GORYEO, years: [1150, 1392] },
    evidence: "documented",
    when: [{ type: "work", match: /pot|clay|kiln/i }],
    weight: 6,
    part: "midday",
    place: "work",
    activity: "work",
    minutes: 60,
    text: "Inlay white and black slip into cranes on a celadon bowl.",
    note: "Sanggam inlay was a Goryeo invention, made at kilns like Gangjin.",
    sources: ["https://en.wikipedia.org/wiki/Korean_celadon"],
    serves: ["mastery"],
  },
  {
    id: "day.joseon.gije",
    label: "The death-day rite",
    scope: JOSEON,
    evidence: "documented",
    when: [{ type: "anniversary", kind: "died" }],
    weight: 16,
    part: "evening",
    place: "home",
    activity: "cook",
    minutes: 60,
    text: "Set the jesa table for your {dead} at midnight, {years} years on.",
    note: "The gije was held in the first hour of the death-day, the eldest son presiding.",
    sources: ["https://en.wikipedia.org/wiki/Jesa"],
    serves: ["remember-dead"],
  },
  {
    id: "day.joseon.jang",
    label: "The five-day market",
    scope: { ...JOSEON, years: [1600, 1950] },
    evidence: "documented",
    when: [{ type: "cycle", every: 5, on: 2 }, { type: "adult" }],
    weight: 6,
    part: "midday",
    place: "market",
    activity: "visit",
    minutes: 50,
    carry: "bundle",
    text: "Go to the jang, the five-day market: it meets today.",
    note: "Peddlers, bobusang, walked a circuit of towns whose markets met on staggered days.",
    sources: ["https://en.wikipedia.org/wiki/Bobusang"],
  },
  {
    id: "day.joseon.seodang",
    label: "To the village school",
    scope: { ...JOSEON, years: [1392, 1910] },
    evidence: "documented",
    when: [{ type: "kin", kind: "child", minAge: 6, maxAge: 15 }, { type: "sex", is: "male" }, { type: "chance", p: 0.4 }],
    weight: 5,
    part: "morning",
    place: { venue: "school" },
    activity: "visit",
    minutes: 20,
    text: "Send {child} to the seodang with the Thousand Character Classic.",
    sources: ["https://en.wikipedia.org/wiki/Seodang", "https://en.wikipedia.org/wiki/Thousand_Character_Classic"],
    serves: ["child-future"],
  },
  {
    id: "day.joseon.sarangbang",
    label: "Books in the sarangbang",
    scope: { ...JOSEON, years: [1392, 1910] },
    evidence: "documented",
    when: [{ type: "rank", any: ["gentry", "elite"] }, { type: "kin", kind: "friend" }, { type: "sex", is: "male" }],
    weight: 5,
    part: "evening",
    place: { kin: "friend" },
    activity: "visit",
    minutes: 60,
    text: "Read the Analects aloud with {friend} in his sarangbang.",
    note: "The sarangbang was the men's reception room of a yangban house, apart from the women's quarters.",
    sources: ["https://en.wikipedia.org/wiki/Yangban"],
  },
  {
    id: "day.korea.samsin",
    label: "Water for Samsin Halmeoni",
    scope: { ...JOSEON, years: [918, 1950] },
    evidence: "documented",
    when: [{ type: "kin", kind: "child", maxAge: 5 }, { type: "sex", is: "female" }, { type: "chance", p: 0.3 }],
    weight: 5,
    part: "morning",
    place: "home",
    activity: "tend",
    minutes: 15,
    carry: "vessel",
    text: "Set out clear water and rice for Samsin Halmeoni, who guards {child}.",
    note: "The birth grandmother was kept on a shelf in the inner room with a gourd of rice.",
    sources: ["https://en.wikipedia.org/wiki/Korean_shamanism"],
    serves: ["raise-kin"],
  },
  {
    id: "day.korea.changpo",
    label: "Washing in iris water",
    scope: JOSEON,
    evidence: "documented",
    when: [{ type: "date", dayOfYear: 160 }, { type: "sex", is: "female" }],
    weight: 14,
    part: "morning",
    place: "well",
    activity: "draw-water",
    minutes: 25,
    carry: "vessel",
    text: "Wash your hair in water boiled with sweet-flag leaves: it is Dano.",
    sources: ["https://en.wikipedia.org/wiki/Dano_(festival)"],
  },
];

export const eastAsiaFestivals: Festival[] = [
  {
    id: "fest.han.la",
    label: "the La sacrifice",
    scope: EARLY_IMPERIAL,
    evidence: "documented",
    date: { dayOfYear: 12 },
    rest: false,
    place: "hearth",
    minutes: 90,
    text: "It is the La: the year's end sacrifice to the ancestors and the household gods, and a feast.",
    note: "It fell on the third xu day after the winter solstice; the twelfth month is still called la yue.",
    sources: ["https://en.wikipedia.org/wiki/Laba_Festival"],
  },
  {
    id: "fest.china.lantern",
    label: "the Lantern Festival",
    scope: { years: [600, 1950], bounds: CN, cultures: EA },
    evidence: "documented",
    date: { dayOfYear: 50 },
    rest: false,
    place: "gathering",
    minutes: 90,
    text: "It is the Lantern Festival: lanterns hang in every street, with riddles pasted on them.",
    note: "The fifteenth of the first lunar month, late February or early March.",
    sources: ["https://en.wikipedia.org/wiki/Lantern_Festival"],
  },
  {
    id: "fest.china.dragon-boat",
    label: "the Dragon Boat festival",
    scope: { years: [300, 1950], bounds: CN, cultures: EA },
    evidence: "documented",
    date: { dayOfYear: 160 },
    rest: false,
    place: "edge",
    minutes: 90,
    text: "It is the Double Fifth: dragon boats race on the river and mugwort hangs by the doors.",
    note: "The fifth of the fifth lunar month, in June; the races were said to search for the drowned Qu Yuan.",
    sources: ["https://en.wikipedia.org/wiki/Dragon_Boat_Festival"],
  },
  {
    id: "fest.japan.shogatsu-old",
    label: "Shogatsu",
    scope: { years: [1603, 1873], bounds: JP, cultures: EA },
    evidence: "documented",
    date: { dayOfYear: 36 },
    rest: true,
    place: "gathering",
    minutes: 120,
    text: "It is Shogatsu: pine at the gates, rice cakes, and New Year calls on masters and kin.",
    note: "Before 1873 the lunisolar New Year fell between late January and mid-February.",
    sources: ["https://en.wikipedia.org/wiki/Japanese_New_Year"],
  },
  {
    id: "fest.japan.shogatsu",
    label: "Shogatsu",
    scope: { years: [1873, 1950], bounds: JP, cultures: EA },
    evidence: "documented",
    date: { dayOfYear: 1 },
    rest: true,
    place: "gathering",
    minutes: 120,
    text: "It is Shogatsu: pine at the gates, ozoni soup, and New Year calls on kin.",
    note: "Japan moved the New Year to 1 January when it adopted the Gregorian calendar in 1873.",
    sources: ["https://en.wikipedia.org/wiki/Japanese_New_Year"],
  },
  {
    id: "fest.japan.obon",
    label: "O-Bon",
    scope: { years: [1603, 1950], bounds: JP, cultures: EA },
    evidence: "documented",
    date: { dayOfYear: 227 },
    rest: true,
    place: "gathering",
    minutes: 120,
    text: "It is O-Bon: welcome fires for the returning dead, and the Bon dance in the square.",
    note: "Apprentices and servants had their holiday home, yabuiri, on the sixteenth of the seventh month.",
    sources: ["https://en.wikipedia.org/wiki/Bon_Festival"],
  },
  {
    id: "fest.goguryeo.dongmaeng",
    label: "Dongmaeng",
    scope: { years: [-37, 668], bounds: [122, 37, 130, 43], cultures: EA },
    evidence: "documented",
    date: { dayOfYear: 300 },
    rest: true,
    place: "sanctuary",
    minutes: 150,
    text: "It is Dongmaeng: the whole country gathers to sacrifice to Heaven after the harvest.",
    note: "The Sanguozhi puts it in the tenth month, when the king welcomed the Sui god from a great cave east of the capital.",
    sources: ["https://en.wikipedia.org/wiki/Goguryeo"],
  },
  {
    id: "fest.goryeo.palgwanhoe",
    label: "the Palgwanhoe",
    scope: GORYEO,
    evidence: "documented",
    date: { dayOfYear: 345 },
    rest: false,
    place: "sanctuary",
    minutes: 120,
    text: "It is the Palgwanhoe: lanterns, offerings to Buddha and the spirits of mountain and river.",
    note: "Taejo's Ten Injunctions told his heirs never to drop it; the capital held it in the eleventh month.",
    sources: ["https://en.wikipedia.org/wiki/Goryeo"],
  },
  {
    id: "fest.korea.dano",
    label: "Dano",
    scope: JOSEON,
    evidence: "documented",
    date: { dayOfYear: 160 },
    rest: false,
    place: "gathering",
    minutes: 90,
    text: "It is Dano: ssireum wrestling for the men and the swing for the women.",
    sources: ["https://en.wikipedia.org/wiki/Dano_(festival)"],
  },
  {
    id: "fest.korea.chuseok",
    label: "Chuseok",
    scope: JOSEON,
    evidence: "documented",
    date: { dayOfYear: 263 },
    rest: true,
    place: "edge",
    minutes: 120,
    text: "It is Chuseok: songpyeon for the ancestors, and the family graves weeded and tidied.",
    note: "The fifteenth of the eighth lunar month, between mid-September and early October.",
    sources: ["https://en.wikipedia.org/wiki/Chuseok"],
  },
];
