import type { Festival, Occasion } from "./types";

type Box = [number, number, number, number];
const NA = ["north-african-west-asian" as const];
const EGYPT: Box = [24.5, 22, 33.8, 31.7];
const THEBES: Box = [32.3, 25.4, 33, 26.1];
const NUBIA: Box = [29, 14, 35, 22.5];
const MAGHREB: Box = [-17, 20, 25, 37.5];
const SAHARA: Box = [-17, 16, 25, 31];

const GREEN_SAHARA = { years: [-7500, -3500] as [number, number], bounds: [-10, 15, 34, 30] as Box };
const PREDYNASTIC = { years: [-4500, -3100] as [number, number], bounds: [29, 24, 33.8, 31.7] as Box };
const PHARAONIC = { years: [-3100, -332] as [number, number], bounds: EGYPT, cultures: NA };
const NEW_KINGDOM = { years: [-1550, -1069] as [number, number], bounds: EGYPT, cultures: NA };
const DEIR = { years: [-1500, -1069] as [number, number], bounds: THEBES };
const LATE = { years: [-700, 400] as [number, number], bounds: EGYPT, cultures: NA };
const ROMAN_EGYPT = { years: [-30, 400] as [number, number], bounds: EGYPT, cultures: NA };
const COPTIC = { years: [330, 1000] as [number, number], bounds: EGYPT, cultures: NA };
const KUSH = { years: [-800, 350] as [number, number], bounds: NUBIA };
const ISLAMIC_EGYPT = { years: [900, 1950] as [number, number], bounds: EGYPT, cultures: NA };
const CAIRO = { years: [969, 1900] as [number, number], bounds: [30.9, 29.8, 31.6, 30.3] as Box };
const MAGHREB_ISLAM = { years: [750, 1950] as [number, number], bounds: MAGHREB, cultures: NA };
const AMAZIGH = { years: [-500, 1950] as [number, number], bounds: [-17, 20, 12, 37.5] as Box, cultures: NA };
const CARAVAN = { years: [1000, 1950] as [number, number], bounds: SAHARA };
const NORTH_AFRICA_ISLAM = { years: [900, 1950] as [number, number], bounds: [-17, 20, 33.8, 37.5] as Box, cultures: NA };

export const egyptNorthAfricaOccasions: Occasion[] = [
  {
    id: "day.green-sahara.first-milk",
    label: "The first milk to the herd",
    scope: GREEN_SAHARA,
    evidence: "hypothesis",
    when: [{ type: "work", match: /herd|cattle|cow|pastor/i }, { type: "chance", p: 0.3 }],
    weight: 4,
    part: "morning",
    place: "edge",
    activity: "tend",
    minutes: 25,
    carry: "vessel",
    text: "Pour the first milk on the ground for the cattle that went before.",
    note: "Cattle were buried like people under tumuli at Nabta Playa; a milk offering is our guess.",
    sources: ["https://en.wikipedia.org/wiki/Nabta_Playa"],
  },
  {
    id: "day.nabta.solstice",
    label: "Watching the sun from the stone circle",
    scope: { ...GREEN_SAHARA, bounds: [29.5, 21, 32.5, 24] as Box },
    evidence: "hypothesis",
    when: [{ type: "date", dayOfYear: 172 }, { type: "adult" }],
    weight: 12,
    part: "morning",
    place: "sanctuary",
    activity: "visit",
    minutes: 40,
    text: "Stand in the stone circle and watch the sun rise through the gap: the rains are near.",
    note: "One sightline of the Nabta Playa circle has been read as pointing to midsummer sunrise, when the rains came.",
    sources: ["https://en.wikipedia.org/wiki/Nabta_Playa"],
  },
  {
    id: "day.predynastic.grave-jar",
    label: "Bringing a jar to the grave",
    scope: PREDYNASTIC,
    evidence: "hypothesis",
    when: [{ type: "anniversary", kind: "died" }],
    weight: 14,
    part: "evening",
    place: "edge",
    activity: "visit",
    minutes: 40,
    carry: "vessel",
    text: "Set a jar of beer on the desert edge where your {dead} lies curled in the sand.",
    note: "Naqada dead were buried contracted in desert-edge pits with pots of food and drink; returning on the day is a guess.",
    sources: ["https://en.wikipedia.org/wiki/Naqada_culture"],
    serves: ["remember-dead"],
  },
  {
    id: "day.egypt.phyle",
    label: "Hauling stone with the gang",
    scope: { years: [-2650, -2150], bounds: [30.8, 29.3, 31.5, 30.2] as Box, cultures: NA },
    evidence: "documented",
    when: [{ type: "work", match: /build|stone|quarr|mason|haul|labou?r/i }, { type: "chance", p: 0.4 }],
    weight: 5,
    part: "morning",
    place: "work",
    activity: "haul",
    minutes: 60,
    text: "Haul stone on the sledge with your gang, the Friends of Khufu.",
    note: "Graffiti at Giza name the work gangs, such as 'Friends of Khufu' and 'Drunkards of Menkaure'.",
    sources: ["https://en.wikipedia.org/wiki/Giza_pyramid_complex"],
  },
  {
    id: "day.egypt.offering-formula",
    label: "Speaking the offering formula",
    scope: PHARAONIC,
    evidence: "documented",
    when: [{ type: "adult" }, { type: "chance", p: 0.2 }],
    weight: 3,
    part: "evening",
    place: "edge",
    activity: "visit",
    minutes: 15,
    text: "Speak the offering formula at the tombs on your way: a thousand of bread and beer.",
    note: "Tomb chapels asked passers-by to recite the hetep-di-nesu, since the spoken words fed the dead.",
    sources: ["https://en.wikipedia.org/wiki/Offering_formula"],
    serves: ["remember-dead"],
  },
  {
    id: "day.egypt.letter-to-dead",
    label: "Writing to the dead",
    scope: { years: [-2600, -1500], bounds: EGYPT, cultures: NA },
    evidence: "documented",
    when: [{ type: "anniversary", kind: "died" }, { type: "fortune", below: 45 }],
    weight: 16,
    part: "evening",
    place: "edge",
    activity: "visit",
    minutes: 35,
    carry: "vessel",
    text: "Write to your {dead} on a food bowl and leave it at the tomb: ask them to end the trouble.",
    note: "The Cairo Bowl and others carry letters asking a dead relative to intercede against illness or a hostile spirit.",
    sources: ["https://en.wikipedia.org/wiki/Letters_to_the_dead"],
    serves: ["remember-dead", "widowed-household"],
  },
  {
    id: "day.egypt.tomb-meal",
    label: "A meal at the tomb chapel",
    scope: NEW_KINGDOM,
    evidence: "inferred",
    when: [{ type: "anniversary", kind: "died" }],
    weight: 14,
    part: "evening",
    place: "edge",
    activity: "visit",
    minutes: 50,
    carry: "basket",
    text: "Carry bread, beer and a lotus to your {dead}'s tomb chapel and eat there with them.",
    sources: ["https://en.wikipedia.org/wiki/Beautiful_Festival_of_the_Valley"],
    serves: ["remember-dead"],
  },
  {
    id: "day.egypt.bes-taweret",
    label: "A lamp for Bes and Taweret",
    scope: { years: [-2000, -30], bounds: EGYPT, cultures: NA },
    evidence: "documented",
    when: [{ type: "kin", kind: "child", maxAge: 4 }],
    weight: 6,
    part: "evening",
    place: "hearth",
    activity: "visit",
    minutes: 15,
    text: "Set a lamp before Bes and Taweret in the wall niche to guard {child} tonight.",
    note: "Deir el-Medina houses had niches and painted Bes figures in the front room, where birth and nursing happened.",
    sources: ["https://en.wikipedia.org/wiki/Bes", "https://en.wikipedia.org/wiki/Taweret"],
    serves: ["raise-kin"],
  },
  {
    id: "day.egypt.ani-parent",
    label: "Bread for an old parent",
    scope: NEW_KINGDOM,
    evidence: "documented",
    when: [{ type: "kin", kind: "parent", minAge: 55 }],
    weight: 5,
    part: "midday",
    place: { kin: "parent" },
    activity: "visit",
    minutes: 30,
    carry: "basket",
    text: "Carry bread to {parent}, as Ani teaches: double what was given to you.",
    note: "The Instruction of Ani tells a son to repay his mother double the bread she gave him.",
    sources: ["https://en.wikipedia.org/wiki/Instruction_of_Any"],
    serves: ["elder-kin"],
  },
  {
    id: "day.egypt.lotus-partner",
    label: "A lotus for a lover",
    scope: NEW_KINGDOM,
    evidence: "inferred",
    when: [{ type: "kin", kind: "partner" }, { type: "chance", p: 0.2 }],
    weight: 3,
    part: "evening",
    place: "home",
    activity: "visit",
    minutes: 25,
    text: "Bring {partner} a blue lotus and a jar of sweet beer from the river.",
    note: "The Chester Beatty love songs call the beloved 'sister' and fill the garden with lotus and mandrake.",
    sources: ["https://en.wikipedia.org/wiki/Ancient_Egyptian_love_poetry"],
    serves: ["shared-future"],
  },
  {
    id: "day.deir.absence",
    label: "Staying home from the tomb",
    scope: DEIR,
    evidence: "documented",
    when: [{ type: "work", match: /stone|mason|carv|paint|build|quarr|sculpt|draught|labou?r/i }, { type: "chance", p: 0.12 }],
    weight: 5,
    part: "morning",
    place: "home",
    activity: "cook",
    minutes: 60,
    text: "Stay home from the tomb to brew beer: the scribe will write it in the register.",
    note: "An absence ostracon lists 'brewing beer', 'stung by a scorpion' and 'embalming his brother' as reasons.",
    sources: ["https://en.wikipedia.org/wiki/Deir_el-Medina"],
  },
  {
    id: "day.deir.ration",
    label: "Drawing the month's ration",
    scope: DEIR,
    evidence: "documented",
    when: [{ type: "cycle", every: 9, on: 8 }, { type: "adult" }],
    weight: 7,
    part: "midday",
    place: "market",
    activity: "haul",
    minutes: 40,
    carry: "bundle",
    text: "Collect your month's emmer and barley from the scribe of the tomb.",
    note: "A foreman drew about four sacks of emmer and one and a half of barley a month; some went to beer.",
    sources: ["https://en.wikipedia.org/wiki/Deir_el-Medina"],
  },
  {
    id: "day.deir.oracle",
    label: "Asking Amenhotep's oracle",
    scope: DEIR,
    evidence: "documented",
    when: [{ type: "fortune", below: 40 }, { type: "chance", p: 0.2 }, { type: "adult" }],
    weight: 5,
    part: "midday",
    place: "sanctuary",
    activity: "visit",
    minutes: 40,
    text: "Put your question to the deified Amenhotep as the bearers carry his statue by.",
    note: "The god answered disputes over donkeys and stolen goods by moving his bearers forward or back.",
    sources: ["https://en.wikipedia.org/wiki/Amenhotep_I"],
  },
  {
    id: "day.egypt.scribe-libation",
    label: "A drop for Imhotep",
    scope: { years: [-1550, 100], bounds: EGYPT, cultures: NA },
    evidence: "documented",
    when: [{ type: "work", match: /scrib|writ|clerk|account/i }],
    weight: 5,
    part: "morning",
    place: "work",
    activity: "work",
    minutes: 10,
    text: "Pour a drop from your water-pot for Imhotep before the day's writing.",
    note: "Scribes are said to have poured a libation to Imhotep, patron of their craft, before writing.",
    sources: ["https://en.wikipedia.org/wiki/Imhotep"],
  },
  {
    id: "day.egypt.dykes",
    label: "Walking the dykes at the flood",
    scope: { years: [-3100, 1950], bounds: EGYPT },
    evidence: "documented",
    when: [{ type: "season", any: ["summer"] }, { type: "work", match: /farm|field|fellah|plough|peasant|cultiv/i }],
    weight: 6,
    part: "morning",
    place: "edge",
    activity: "tend",
    minutes: 50,
    text: "Walk the basin dykes, packing mud into the weak places before the flood tops them.",
    note: "Basin irrigation held the flood in earth-banked fields for weeks before letting it drain.",
    sources: ["https://en.wikipedia.org/wiki/Flooding_of_the_Nile"],
    serves: ["household-home"],
  },
  {
    id: "day.egypt.corvee",
    label: "Called up for the corvée",
    scope: PHARAONIC,
    evidence: "documented",
    when: [{ type: "season", any: ["summer", "autumn"] }, { type: "work", match: /farm|field|plough|peasant|cultiv/i }, { type: "chance", p: 0.15 }],
    weight: 4,
    part: "midday",
    place: "edge",
    activity: "haul",
    minutes: 70,
    text: "Report for the corvée at the canal: your fields are under water anyway.",
    note: "Shabti figures were made to answer for their owner when called to this labour in the afterlife.",
    sources: ["https://en.wikipedia.org/wiki/Corv%C3%A9e", "https://en.wikipedia.org/wiki/Ushabti"],
  },
  {
    id: "day.egypt.sowing-flock",
    label: "Treading in the seed",
    scope: PHARAONIC,
    evidence: "documented",
    when: [{ type: "season", any: ["autumn"] }, { type: "work", match: /farm|field|plough|peasant|herd|shep/i }],
    weight: 5,
    part: "morning",
    place: "work",
    activity: "tend",
    minutes: 45,
    text: "Drive the sheep over the fresh-sown mud to tread the seed in.",
    note: "Herodotus says Egyptians sowed and let swine tread the seed in; tomb scenes show sheep doing it.",
    sources: ["https://en.wikipedia.org/wiki/Agriculture_in_ancient_Egypt"],
  },
  {
    id: "day.egypt.renenutet",
    label: "The first sheaf to Renenutet",
    scope: PHARAONIC,
    evidence: "documented",
    when: [{ type: "season", any: ["spring"] }, { type: "work", match: /farm|field|harvest|peasant|cultiv/i }, { type: "chance", p: 0.35 }],
    weight: 6,
    part: "morning",
    place: "work",
    activity: "visit",
    minutes: 20,
    carry: "bundle",
    text: "Lay the first sheaf before the little shrine of Renenutet at the threshing floor.",
    note: "Harvest and granary scenes show a cobra-headed Renenutet receiving offerings beside the grain.",
    sources: ["https://en.wikipedia.org/wiki/Renenutet"],
  },
  {
    id: "day.egypt.boat-grain",
    label: "Carrying the temple's grain",
    scope: { years: [-3100, 400], bounds: EGYPT, cultures: NA },
    evidence: "inferred",
    when: [{ type: "work", match: /boat|ferry|sail|river|barge/i }, { type: "season", any: ["spring", "summer"] }, { type: "chance", p: 0.35 }],
    weight: 5,
    part: "morning",
    place: "work",
    activity: "haul",
    minutes: 60,
    carry: "bundle",
    text: "Load the temple's grain sacks aboard for the ride north on the current.",
    note: "The Nile flows north and the wind blows south, so boats drifted down and sailed back up.",
    sources: ["https://en.wikipedia.org/wiki/Ancient_Egyptian_trade"],
  },
  {
    id: "day.egypt.linen",
    label: "Splicing flax for linen",
    scope: { years: [-4500, 400], bounds: EGYPT, cultures: NA },
    evidence: "documented",
    when: [{ type: "work", match: /weav|spin|linen|flax|textile/i }],
    weight: 5,
    part: "midday",
    place: "work",
    activity: "work",
    minutes: 50,
    text: "Splice wet flax strips end to end into fine linen thread.",
    note: "Egyptian linen thread was made by splicing flax fibres before spinning, not by drafting.",
    sources: ["https://en.wikipedia.org/wiki/Linen"],
  },
  {
    id: "day.egypt.potter",
    label: "Treading Nile clay",
    scope: { years: [-4500, 1950], bounds: EGYPT },
    evidence: "inferred",
    when: [{ type: "work", match: /pot|clay|ceram/i }],
    weight: 5,
    part: "morning",
    place: "work",
    activity: "work",
    minutes: 40,
    text: "Tread Nile silt with chopped straw into clay for the day's water jars.",
    note: "Khnum was pictured shaping people on a potter's wheel.",
    sources: ["https://en.wikipedia.org/wiki/Khnum"],
  },
  {
    id: "day.egypt.khoiak-osiris",
    label: "Watering the grain-Osiris",
    scope: LATE,
    evidence: "documented",
    when: [{ type: "season", any: ["autumn"] }, { type: "observance", levels: ["devout", "regular"] }, { type: "chance", p: 0.35 }],
    weight: 5,
    part: "morning",
    place: "sanctuary",
    activity: "tend",
    minutes: 20,
    carry: "vessel",
    text: "Moisten the grain-Osiris in its mould until the green shoots show.",
    note: "In the month of Khoiak, Osiris figures of earth and barley were watered until they sprouted.",
    sources: ["https://en.wikipedia.org/wiki/Corn_mummy"],
  },
  {
    id: "day.egypt.animal-mummy",
    label: "Dedicating an ibis to Thoth",
    scope: LATE,
    evidence: "documented",
    when: [{ type: "observance", levels: ["devout", "regular", "occasional"] }, { type: "chance", p: 0.1 }, { type: "adult" }],
    weight: 4,
    part: "midday",
    place: "sanctuary",
    activity: "visit",
    minutes: 40,
    text: "Buy a wrapped ibis from the temple keepers as a gift to Thoth.",
    note: "Millions of mummified ibises, cats and falcons were bought as votives at Saqqara, Tuna el-Gebel and Bubastis.",
    sources: ["https://en.wikipedia.org/wiki/Animal_mummy"],
  },
  {
    id: "day.egypt.serapeum-dream",
    label: "Sleeping in the temple of Serapis",
    scope: { years: [-300, 391], bounds: EGYPT, cultures: NA },
    evidence: "documented",
    when: [{ type: "fortune", below: 35 }, { type: "chance", p: 0.15 }, { type: "adult" }],
    weight: 5,
    part: "evening",
    place: "sanctuary",
    activity: "rest",
    minutes: 60,
    text: "Sleep in the precinct of Serapis and wait for a healing dream.",
    note: "Temple incubation for cures and dream interpretation was practised at the Serapeum and at Saqqara.",
    sources: ["https://en.wikipedia.org/wiki/Incubation_(ritual)"],
  },
  {
    id: "day.roman-egypt.letter-home",
    label: "A letter home",
    scope: ROMAN_EGYPT,
    evidence: "documented",
    when: [{ type: "kin", kind: "parent" }, { type: "chance", p: 0.15 }, { type: "adult" }],
    weight: 3,
    part: "evening",
    place: "home",
    activity: "rest",
    minutes: 30,
    text: "Dictate a letter to {parent} on papyrus: send greetings, and ask for a warm cloak.",
    note: "Letters found at Oxyrhynchus and Karanis are full of greetings to kin and requests for clothes.",
    sources: ["https://en.wikipedia.org/wiki/Oxyrhynchus_Papyri"],
    serves: ["elder-kin"],
  },
  {
    id: "day.roman-egypt.portrait",
    label: "Sitting for a mummy portrait",
    scope: { years: [30, 300], bounds: EGYPT, cultures: NA },
    evidence: "documented",
    when: [{ type: "rank", any: ["middling", "gentry", "elite"] }, { type: "chance", p: 0.05 }, { type: "adult" }],
    weight: 3,
    part: "midday",
    place: "door",
    activity: "visit",
    minutes: 50,
    text: "Sit for the painter of wax portraits, for the panel to cover your face at burial.",
    sources: ["https://en.wikipedia.org/wiki/Fayum_mummy_portraits"],
  },
  {
    id: "day.coptic.wednesday-fast",
    label: "The Wednesday fast",
    scope: COPTIC,
    evidence: "documented",
    when: [{ type: "cycle", every: 7, on: 0 }, { type: "observance", levels: ["devout", "regular"] }, { type: "adult" }],
    weight: 5,
    part: "evening",
    place: "hearth",
    activity: "cook",
    minutes: 35,
    text: "Cook lentils in oil, with no meat or milk: it is the Wednesday fast.",
    note: "The Coptic Church fasts on Wednesdays and Fridays for most of the year.",
    sources: ["https://en.wikipedia.org/wiki/Fasting_in_Christianity"],
  },
  {
    id: "day.coptic.abba",
    label: "A word from the hermit",
    scope: { ...COPTIC, years: [300, 700] as [number, number] },
    evidence: "documented",
    when: [{ type: "tag", any: ["ascetic", "mystical", "devout"] }, { type: "chance", p: 0.2 }, { type: "adult" }],
    weight: 5,
    part: "midday",
    place: "wild",
    activity: "visit",
    minutes: 60,
    carry: "basket",
    text: "Walk out to the hermit's cell with bread and ask the abba for a word.",
    note: "The Sayings of the Desert Fathers record visitors asking 'Abba, speak a word to me.'",
    sources: ["https://en.wikipedia.org/wiki/Desert_Fathers"],
  },
  {
    id: "day.coptic.mar-girgis",
    label: "The mulid of Mar Girgis",
    scope: { years: [1700, 1950], bounds: [30, 30.3, 32.5, 31.6] as Box, cultures: NA },
    evidence: "inferred",
    when: [{ type: "date", dayOfYear: 235 }, { type: "adult" }],
    weight: 12,
    part: "midday",
    place: "sanctuary",
    activity: "visit",
    minutes: 70,
    text: "Walk to Mit Damsis for the mulid of Mar Girgis, with its swings and sweets.",
    note: "Muslims as well as Copts crowd the August mulid of Saint George at Mit Damsis.",
    sources: ["https://en.wikipedia.org/wiki/Mawlid"],
  },
  {
    id: "day.kerma.bucrania",
    label: "A skull for the grave",
    scope: { years: [-2500, -1500], bounds: [29.5, 18, 32, 21] as Box },
    evidence: "hypothesis",
    when: [{ type: "anniversary", kind: "died" }],
    weight: 14,
    part: "evening",
    place: "edge",
    activity: "visit",
    minutes: 40,
    text: "Lay an ox skull on the south side of your {dead}'s grave mound.",
    note: "Kerma tumuli were ringed with cattle skulls, thousands at the largest; adding them later is our guess.",
    sources: ["https://en.wikipedia.org/wiki/Kerma_culture"],
    serves: ["remember-dead"],
  },
  {
    id: "day.kush.apedemak",
    label: "Beer for Apedemak",
    scope: { ...KUSH, years: [-300, 350] as [number, number] },
    evidence: "inferred",
    when: [{ type: "observance", levels: ["devout", "regular"] }, { type: "chance", p: 0.2 }, { type: "adult" }],
    weight: 5,
    part: "morning",
    place: "sanctuary",
    activity: "visit",
    minutes: 30,
    carry: "vessel",
    text: "Bring a bowl of sorghum beer to the lion god Apedemak at his temple.",
    note: "Apedemak, lion-headed war god of Meroe, had no Egyptian counterpart; sorghum was the Meroitic staple.",
    sources: ["https://en.wikipedia.org/wiki/Apedemak"],
  },
  {
    id: "day.kush.saqia",
    label: "Driving the waterwheel oxen",
    scope: { years: [-200, 1950], bounds: NUBIA },
    evidence: "documented",
    when: [{ type: "work", match: /farm|field|garden|cultiv|peasant|irrig/i }, { type: "season", any: ["winter", "spring"] }],
    weight: 5,
    part: "morning",
    place: "work",
    activity: "tend",
    minutes: 60,
    text: "Drive the oxen round the saqia to lift water onto the riverbank plots.",
    note: "The ox-driven waterwheel reached Nubia in Meroitic times and let fields be watered above the flood line.",
    sources: ["https://en.wikipedia.org/wiki/Sakia"],
  },
  {
    id: "day.makuria.graffito",
    label: "A prayer on the church wall",
    scope: { years: [600, 1450], bounds: NUBIA },
    evidence: "documented",
    when: [{ type: "observance", levels: ["devout", "regular"] }, { type: "chance", p: 0.1 }, { type: "adult" }],
    weight: 4,
    part: "midday",
    place: "sanctuary",
    activity: "visit",
    minutes: 30,
    text: "Scratch a prayer to the Archangel Raphael on the church wall, in Old Nubian.",
    note: "Hundreds of visitors' prayers cover the walls of the church at Banganarti.",
    sources: ["https://en.wikipedia.org/wiki/Banganarti"],
  },
  {
    id: "day.egypt.nile-crier",
    label: "The crier of the Nile",
    scope: CAIRO,
    evidence: "documented",
    when: [{ type: "season", any: ["summer"] }, { type: "chance", p: 0.3 }],
    weight: 4,
    part: "morning",
    place: "gathering",
    activity: "visit",
    minutes: 20,
    text: "Listen for the crier calling how many fingers the Nile rose overnight.",
    note: "From the Nilometer on Roda Island, a crier announced the flood's daily rise through the streets.",
    sources: ["https://en.wikipedia.org/wiki/Nilometer"],
  },
  {
    id: "day.egypt.thursday-tombs",
    label: "Visiting the family tomb",
    scope: ISLAMIC_EGYPT,
    evidence: "documented",
    when: [{ type: "cycle", every: 7, on: 1 }, { type: "chance", p: 0.3 }, { type: "adult" }],
    weight: 5,
    part: "morning",
    place: "edge",
    activity: "visit",
    minutes: 45,
    carry: "basket",
    text: "Take palm fronds and bread to the family tomb and give the bread to the poor.",
    note: "Lane saw Cairenes visit the tombs on Thursday mornings with palm branches and food for the poor.",
    sources: ["https://en.wikipedia.org/wiki/City_of_the_Dead_(Cairo)"],
    serves: ["remember-dead"],
  },
  {
    id: "day.egypt.coffee-sira",
    label: "The poet at the coffee house",
    scope: { years: [1600, 1950], bounds: EGYPT, cultures: NA },
    evidence: "documented",
    when: [{ type: "sex", is: "male" }, { type: "chance", p: 0.25 }, { type: "adult" }],
    weight: 4,
    part: "evening",
    place: { venue: "coffee-house" },
    activity: "visit",
    minutes: 70,
    text: "Listen to the poet recite the Sira of Abu Zayd to his rebab at the coffee house.",
    note: "Lane counted some fifty shu'ara in 1830s Cairo who recited only the Hilali epic.",
    sources: ["https://en.wikipedia.org/wiki/Taghribat_Bani_Hilal"],
  },
  {
    id: "day.egypt.zar",
    label: "The zar",
    scope: { years: [1800, 1950], bounds: [24.5, 12, 36, 31.7] as Box, cultures: NA },
    evidence: "documented",
    when: [{ type: "sex", is: "female" }, { type: "trait", key: "neuroticism", above: 60 }, { type: "chance", p: 0.1 }, { type: "adult" }],
    weight: 5,
    part: "evening",
    place: "door",
    activity: "visit",
    minutes: 80,
    text: "Join the zar at a neighbour's house and dance to please the spirit that troubles you.",
    sources: ["https://en.wikipedia.org/wiki/Zar_(spirit)"],
  },
  {
    id: "day.north-africa.kuttab",
    label: "Walking a child to the kuttab",
    scope: NORTH_AFRICA_ISLAM,
    evidence: "documented",
    when: [{ type: "kin", kind: "child", minAge: 5, maxAge: 11 }, { type: "chance", p: 0.4 }],
    weight: 4,
    part: "morning",
    place: "door",
    activity: "visit",
    minutes: 25,
    text: "Walk {child} to the kuttab to chant the day's verses from a wooden slate.",
    note: "Pupils wrote their verses on a wooden board, recited them, and washed the board clean.",
    sources: ["https://en.wikipedia.org/wiki/Kuttab"],
    serves: ["child-future", "raise-kin"],
  },
  {
    id: "day.north-africa.hammam",
    label: "The Thursday hammam",
    scope: NORTH_AFRICA_ISLAM,
    evidence: "documented",
    when: [{ type: "cycle", every: 7, on: 1 }, { type: "chance", p: 0.5 }],
    weight: 5,
    part: "evening",
    place: { venue: "bath" },
    activity: "visit",
    minutes: 70,
    text: "Go to the hammam to sweat clean before the Friday prayer.",
    sources: ["https://en.wikipedia.org/wiki/Hammam"],
  },
  {
    id: "day.maghreb.marabout",
    label: "Visiting the marabout's tomb",
    scope: MAGHREB_ISLAM,
    evidence: "documented",
    when: [{ type: "fortune", below: 45 }, { type: "chance", p: 0.25 }, { type: "adult" }],
    weight: 5,
    part: "midday",
    place: "sanctuary",
    activity: "visit",
    minutes: 50,
    carry: "basket",
    text: "Bind a rag to the grille of the marabout's tomb and ask for his baraka.",
    note: "Whitewashed domed tombs of local saints dot the Maghreb; visitors ask the saint to intercede.",
    sources: ["https://en.wikipedia.org/wiki/Marabout"],
  },
  {
    id: "day.maghreb.souk-khemis",
    label: "Souk el-Khemis",
    scope: { years: [900, 1950], bounds: [-10, 28, -1, 36] as Box, cultures: NA },
    evidence: "inferred",
    when: [{ type: "cycle", every: 7, on: 1 }, { type: "adult" }],
    weight: 6,
    part: "morning",
    place: "market",
    activity: "visit",
    minutes: 60,
    carry: "basket",
    text: "Ride the donkey to Souk el-Khemis: it is Thursday market.",
    note: "Rural Moroccan markets are named for their weekday, and many towns still carry the name.",
    sources: ["https://en.wikipedia.org/wiki/Souk"],
  },
  {
    id: "day.maghreb.ashura",
    label: "Drums for Ashura",
    scope: MAGHREB_ISLAM,
    evidence: "documented",
    when: [{ type: "date", dayOfYear: 238 }, { type: "kin", kind: "child", maxAge: 12 }],
    weight: 12,
    part: "midday",
    place: "market",
    activity: "visit",
    minutes: 30,
    text: "Buy {child} a clay taarija drum for Ashura: children splash each other with water.",
    note: "Ashura moves eleven days a year through the solar calendar; this date is one representative year.",
    sources: ["https://en.wikipedia.org/wiki/Ashura"],
    serves: ["raise-kin"],
  },
  {
    id: "day.amazigh.yennayer-couscous",
    label: "The Yennayer couscous",
    scope: AMAZIGH,
    evidence: "documented",
    when: [{ type: "date", dayOfYear: 13 }, { type: "adult" }],
    weight: 14,
    part: "evening",
    place: "hearth",
    activity: "cook",
    minutes: 60,
    text: "Cook couscous with seven vegetables, a date stone hidden in it for the lucky one.",
    note: "Yennayer keeps the Julian New Year, now 12 to 14 January in the Gregorian calendar.",
    sources: ["https://en.wikipedia.org/wiki/Yennayer"],
    serves: ["household-home"],
  },
  {
    id: "day.amazigh.taghonja",
    label: "Carrying the rain bride",
    scope: { ...AMAZIGH, years: [1500, 1950] as [number, number] },
    evidence: "inferred",
    when: [{ type: "season", any: ["spring", "autumn"] }, { type: "sex", is: "female" }, { type: "chance", p: 0.1 }],
    weight: 4,
    part: "midday",
    place: "gathering",
    activity: "visit",
    minutes: 45,
    text: "Carry the ladle-doll Taghonja round the village and sing to Anzar for rain.",
    note: "Ethnographers recorded women dressing a wooden ladle as a bride for the rain-spirit Anzar in dry years.",
    sources: ["https://en.wikipedia.org/wiki/Anzar_(god)"],
  },
  {
    id: "day.africa.saturn-stela",
    label: "A stela for Saturn",
    scope: { years: [-146, 300], bounds: [-2, 32, 12, 37.5] as Box, cultures: NA },
    evidence: "documented",
    when: [{ type: "fortune", above: 55 }, { type: "chance", p: 0.1 }, { type: "adult" }],
    weight: 4,
    part: "morning",
    place: "sanctuary",
    activity: "visit",
    minutes: 45,
    text: "Set up a carved stela to African Saturn on the hill, with a lamb for his altar.",
    note: "Saturn, heir to Punic Baal Hammon, has left thousands of votive stelae in Roman Africa.",
    sources: ["https://en.wikipedia.org/wiki/Baal_Hammon"],
  },
  {
    id: "day.garamantes.foggara",
    label: "Clearing the foggara",
    scope: { years: [-400, 600], bounds: [10, 24, 16, 28] as Box },
    evidence: "documented",
    when: [{ type: "adult" }, { type: "chance", p: 0.25 }],
    weight: 4,
    part: "morning",
    place: "wild",
    activity: "gather",
    minutes: 60,
    carry: "basket",
    text: "Climb down the shaft to clear sand from the foggara that waters the oasis.",
    note: "The Garamantes cut hundreds of kilometres of underground channels to draw fossil water in the Fezzan.",
    sources: ["https://en.wikipedia.org/wiki/Garamantes"],
  },
  {
    id: "day.sahara.azalai",
    label: "Loading the salt caravan",
    scope: CARAVAN,
    evidence: "documented",
    when: [{ type: "work", match: /caravan|camel|salt|trad|merchant|drover/i }, { type: "chance", p: 0.3 }],
    weight: 6,
    part: "morning",
    place: "edge",
    activity: "haul",
    minutes: 60,
    carry: "bundle",
    text: "Lash two slabs of Taoudenni salt to each camel for the road south.",
    note: "The azalai carried rock salt from Taghaza, later Taoudenni, to Timbuktu, a camel bearing about four slabs.",
    sources: ["https://en.wikipedia.org/wiki/Azalai", "https://en.wikipedia.org/wiki/Taoudenni"],
  },
  {
    id: "day.sahara.tea",
    label: "Three glasses of tea",
    scope: { years: [1850, 1950], bounds: [-17, 16, 25, 37.5] as Box },
    evidence: "documented",
    when: [{ type: "kin", kind: "friend" }, { type: "trait", key: "extraversion", above: 45 }, { type: "chance", p: 0.3 }],
    weight: 4,
    part: "evening",
    place: "hearth",
    activity: "warm",
    minutes: 45,
    text: "Brew green tea with mint and sugar and pour {friend} the three glasses.",
    note: "British tea spread through Morocco and the desert after the 1850s; the first glass is bitter, the third sweet.",
    sources: ["https://en.wikipedia.org/wiki/Maghrebi_mint_tea"],
  },
  {
    id: "day.egypt.cotton-worm",
    label: "Picking cotton-worm eggs",
    scope: { years: [1860, 1950], bounds: EGYPT, cultures: NA },
    evidence: "documented",
    when: [{ type: "season", any: ["summer"] }, { type: "kin", kind: "child", minAge: 7, maxAge: 14 }, { type: "rank", any: ["destitute", "labouring"] }],
    weight: 5,
    part: "morning",
    place: "edge",
    activity: "gather",
    minutes: 60,
    text: "Send {child} out with the gang to pick cotton-worm eggs off the leaves.",
    note: "Children were hired in their thousands each summer to pick leafworm egg clusters by hand.",
    sources: ["https://en.wikipedia.org/wiki/Cotton_in_Egypt"],
    serves: ["child-future"],
  },
  {
    id: "day.algeria.permit",
    label: "Queuing for a travel permit",
    scope: { years: [1881, 1945], bounds: [-2, 19, 9, 37.2] as Box, cultures: NA },
    evidence: "documented",
    when: [{ type: "rank", any: ["destitute", "labouring", "middling"] }, { type: "chance", p: 0.06 }, { type: "adult" }],
    weight: 3,
    part: "morning",
    place: "gathering",
    activity: "visit",
    minutes: 60,
    text: "Queue at the administrator's office for a permit to leave the commune.",
    note: "Under the Code de l'indigénat, Algerian Muslims needed a permit to travel beyond their district.",
    sources: ["https://en.wikipedia.org/wiki/Code_de_l%27indig%C3%A9nat"],
  },
];

export const egyptNorthAfricaFestivals: Festival[] = [
  {
    id: "fest.deir.tenth-day",
    label: "the tenth day",
    scope: { ...DEIR, bounds: [32.5, 25.6, 32.7, 25.8] as Box },
    evidence: "documented",
    date: { every: 10, on: 9 },
    rest: true,
    place: "hearth",
    minutes: 60,
    text: "It is the last day of the ten-day week: the tomb crew stays home in the village.",
    sources: ["https://en.wikipedia.org/wiki/Deir_el-Medina"],
  },
  {
    id: "fest.thebes.opet",
    label: "the Opet festival",
    scope: { years: [-1550, -1069], bounds: THEBES },
    evidence: "documented",
    date: { dayOfYear: 240 },
    rest: true,
    place: "gathering",
    minutes: 150,
    text: "It is Opet: Amun's barque goes up the river to Luxor, with bread and beer handed out on the way.",
    note: "Kept in the second month of the flood; the civil calendar slipped a day every four years against the sun.",
    sources: ["https://en.wikipedia.org/wiki/Opet_Festival"],
  },
  {
    id: "fest.thebes.valley",
    label: "the Beautiful Festival of the Valley",
    scope: { years: [-2050, -1069], bounds: THEBES },
    evidence: "documented",
    date: { dayOfYear: 125 },
    rest: false,
    place: "edge",
    minutes: 120,
    text: "It is the Festival of the Valley: families follow Amun west and feast all night in their tomb chapels.",
    note: "Held at the new moon of the second month of summer; the date here is one representative year.",
    sources: ["https://en.wikipedia.org/wiki/Beautiful_Festival_of_the_Valley"],
  },
  {
    id: "fest.egypt.wag",
    label: "the Wag festival",
    scope: PHARAONIC,
    evidence: "documented",
    date: { dayOfYear: 217 },
    rest: false,
    place: "edge",
    minutes: 60,
    text: "It is the Wag festival for the dead: bring bread, beer and lit torches to the tombs.",
    note: "Kept on the eighteenth of Thoth, the first month; one of the oldest feasts, named in Old Kingdom tombs.",
    sources: ["https://en.wikipedia.org/wiki/Wag_festival"],
  },
  {
    id: "fest.egypt.coptic-sunday",
    label: "the Lord's day",
    scope: { years: [350, 900], bounds: EGYPT, cultures: NA },
    evidence: "documented",
    date: { every: 7, on: 4 },
    rest: true,
    place: "sanctuary",
    minutes: 90,
    text: "It is Sunday: go to the liturgy, and leave the fields and the loom.",
    sources: ["https://en.wikipedia.org/wiki/Coptic_Orthodox_Church"],
  },
  {
    id: "fest.egypt.nayrouz",
    label: "Nayrouz",
    scope: { years: [350, 1385], bounds: EGYPT, cultures: NA },
    evidence: "documented",
    date: { dayOfYear: 254 },
    rest: false,
    place: "gathering",
    minutes: 90,
    text: "It is Nayrouz, the Coptic New Year: masked revellers in the streets, water thrown, dates and melons eaten.",
    note: "The Mamluk sultan Barquq banned its street carnival in the 1380s.",
    sources: ["https://en.wikipedia.org/wiki/Nayrouz"],
  },
  {
    id: "fest.cairo.wafa-al-nil",
    label: "the Cutting of the Canal",
    scope: CAIRO,
    evidence: "documented",
    date: { dayOfYear: 227 },
    rest: true,
    place: "edge",
    minutes: 120,
    text: "It is Wafa al-Nil: the flood has reached sixteen cubits, and the dam of the Khalij is cut.",
    note: "The day varied with the flood; mid-August was usual. The Khalij canal was filled in in 1899.",
    sources: ["https://en.wikipedia.org/wiki/Khalij_(Cairo)"],
  },
  {
    id: "fest.egypt.sham-el-nessim",
    label: "Sham el-Nessim",
    scope: { years: [900, 1950], bounds: EGYPT, cultures: NA },
    evidence: "documented",
    date: { dayOfYear: 105 },
    rest: false,
    place: "edge",
    minutes: 120,
    text: "It is Sham el-Nessim: eat salt fish, onions and coloured eggs out in the fields.",
    note: "Falls on the Monday after Coptic Easter, so it moves; this date is one representative year.",
    sources: ["https://en.wikipedia.org/wiki/Sham_el-Nessim"],
  },
  {
    id: "fest.north-africa.mawlid",
    label: "the Mawlid of the Prophet",
    scope: NORTH_AFRICA_ISLAM,
    evidence: "documented",
    date: { dayOfYear: 300 },
    rest: false,
    place: "gathering",
    minutes: 120,
    text: "It is the Mawlid: lamps hung in the lanes, sugar dolls for the children, and dhikr at night.",
    note: "Kept on 12 Rabi' al-Awwal, which moves through the solar year; this is one representative date.",
    sources: ["https://en.wikipedia.org/wiki/Mawlid"],
  },
  {
    id: "fest.north-africa.eid-al-adha",
    label: "the Feast of the Sacrifice",
    scope: NORTH_AFRICA_ISLAM,
    evidence: "documented",
    date: { dayOfYear: 218 },
    rest: true,
    place: "gathering",
    minutes: 150,
    text: "It is Eid al-Kabir: a ram is slaughtered at every door that can afford one, and the meat shared out.",
    note: "10 Dhu al-Hijja moves eleven days a year against the sun; this date is one representative year.",
    sources: ["https://en.wikipedia.org/wiki/Eid_al-Adha"],
  },
];
