import type { Festival, Occasion } from "./types";

type Box = [number, number, number, number];
const eu = (years: [number, number], bounds: Box) => ({ years, bounds, cultures: ["european" as const] });

const MESO = eu([-9700, -5000], [-11, 43, 32, 70]);
const LBK = eu([-5500, -4900], [3, 46, 26, 53]);
const MEGALITH_IRELAND = eu([-3300, -2400], [-11, 51.3, -5.3, 55.5]);
const MEGALITH_BRITAIN = eu([-3000, -2000], [-6, 49.8, 2, 56]);
const STEPPE_WEST = eu([-2800, -800], [-11, 44, 40, 62]);
const NORDIC_BRONZE = eu([-1700, -500], [5, 54, 20, 62]);
const MINOAN = eu([-2000, -1450], [23.4, 34.8, 26.4, 35.7]);
const MYCENAEAN = eu([-1450, -1180], [20.5, 36.3, 24.5, 39.5]);
const GREEK = eu([-700, -146], [19, 35, 29, 42]);
const ATHENS = eu([-566, -86], [23.3, 37.7, 24.2, 38.4]);
const HELLENISTIC = eu([-323, -30], [19, 34, 32, 42]);
const ETRURIA = eu([-700, -90], [9.5, 41.8, 13, 44.5]);
const GAUL = eu([-500, 50], [-5, 42, 8, 51]);
const IRELAND = eu([-300, 1100], [-11, 51.3, -5.3, 55.5]);
const EARLY_ENGLISH = eu([450, 700], [-6, 50, 2, 56]);
const NORSE = eu([750, 1100], [4, 54, 32, 71.5]);
const ICELAND = eu([930, 1262], [-25, 63, -13, 67]);
const SLAVIC = eu([600, 1950], [14, 44, 45, 62]);
const BALTIC = eu([1000, 1950], [20, 53.5, 28.5, 59.5]);
const CONSTANTINOPLE = eu([330, 1204], [28.5, 40.8, 29.3, 41.3]);
const ORTHODOX = eu([600, 1950], [19, 34, 60, 70]);
// North of 56 the Norse and Balts kept their own gods until about 1100.
const LATIN = eu([800, 1520], [-11, 36, 25, 56]);
const ENGLAND = eu([1100, 1750], [-6, 49.8, 2, 56]);
const CHRISTENDOM = eu([400, 1950], [-11, 34, 45, 56]);
const CHRISTENDOM_NORTH = eu([1100, 1950], [-11, 56, 45, 72]);
const EARLY_MODERN = eu([1520, 1800], [-11, 36, 30, 66]);
const MODERN = eu([1914, 1950], [-11, 35, 40, 70]);
const BRITAIN_MODERN = eu([1923, 1950], [-8, 49.5, 2, 59]);

export const europeDeepOccasions: Occasion[] = [
  {
    id: "day.palaeo.needle",
    label: "Sewing with a bone needle",
    scope: eu([-24000, -9700], [-10, 36, 40, 58]),
    evidence: "documented",
    when: [{ type: "season", any: ["autumn", "winter"] }, { type: "chance", p: 0.25 }, { type: "adult" }],
    weight: 5,
    part: "evening",
    place: "hearth",
    activity: "work",
    minutes: 50,
    text: "Sew fitted hide leggings with an eyed bone needle and sinew thread.",
    note: "Eyed bone needles appear in the Solutrean and are common in Magdalenian sites.",
    sources: ["https://en.wikipedia.org/wiki/Sewing_needle"],
  },
  {
    id: "day.palaeo.cave-painting",
    label: "Painting in the deep cave",
    scope: eu([-36000, -11000], [-10, 36, 8, 48]),
    evidence: "hypothesis",
    when: [{ type: "trait", key: "openness", above: 60 }, { type: "chance", p: 0.1 }, { type: "adult" }],
    weight: 4,
    part: "evening",
    place: "wild",
    activity: "visit",
    minutes: 60,
    text: "Carry a fat lamp into the cave and paint the horses on the rock.",
    note: "Stone fat-lamps were found at Lascaux; why the animals were painted in the dark is unknown.",
    sources: ["https://en.wikipedia.org/wiki/Lascaux"],
  },
  {
    id: "day.palaeo.ivory",
    label: "Carving mammoth ivory",
    scope: eu([-40000, -20000], [0, 42, 40, 55]),
    evidence: "inferred",
    when: [{ type: "trait", key: "conscientiousness", above: 55 }, { type: "chance", p: 0.2 }],
    weight: 4,
    part: "evening",
    place: "hearth",
    activity: "work",
    minutes: 50,
    text: "Carve a figure from a slip of mammoth ivory by the fire.",
    sources: ["https://en.wikipedia.org/wiki/Venus_of_Hohle_Fels"],
  },
  {
    id: "day.meso.hazelnuts",
    label: "Roasting hazelnuts",
    scope: MESO,
    evidence: "documented",
    when: [{ type: "season", any: ["autumn"] }, { type: "chance", p: 0.35 }],
    weight: 6,
    part: "midday",
    place: "hearth",
    activity: "cook",
    minutes: 50,
    carry: "basket",
    text: "Roast the hazelnuts in the pit so they keep through winter.",
    note: "A pit at Staosnaig on Colonsay held the burnt shells of several hundred thousand hazelnuts.",
    sources: ["https://en.wikipedia.org/wiki/Mesolithic_Britain"],
  },
  {
    id: "day.meso.antler-frontlet",
    label: "Wearing the antler frontlet",
    scope: eu([-9300, -8000], [-6, 50, 12, 58]),
    evidence: "hypothesis",
    when: [{ type: "work", match: /hunt/i }, { type: "chance", p: 0.1 }],
    weight: 5,
    part: "evening",
    place: "gathering",
    activity: "play",
    minutes: 40,
    text: "Put on the red deer frontlet and dance the deer before the hunt.",
    note: "Star Carr yielded 33 deer-skull frontlets with the antlers pared and eyeholes cut.",
    sources: ["https://en.wikipedia.org/wiki/Star_Carr"],
  },
  {
    id: "day.meso.fish-weir",
    label: "Mending the fish weir",
    scope: MESO,
    evidence: "documented",
    when: [{ type: "work", match: /fish/i }, { type: "chance", p: 0.3 }],
    weight: 5,
    part: "morning",
    place: "edge",
    activity: "work",
    minutes: 50,
    text: "Weave new hazel rods into the fish weir where the current broke it.",
    note: "Wattle fish traps of this age survive at Tybrind Vig and Halsskov in Denmark.",
    sources: ["https://en.wikipedia.org/wiki/Ertebølle_culture"],
  },
  {
    id: "day.lbk.spondylus",
    label: "Trading for Spondylus shell",
    scope: LBK,
    evidence: "documented",
    when: [{ type: "rank", any: ["middling", "gentry", "elite"] }, { type: "chance", p: 0.1 }, { type: "adult" }],
    weight: 5,
    part: "midday",
    place: "gathering",
    activity: "visit",
    minutes: 40,
    text: "Trade a polished stone adze for a bracelet of Aegean Spondylus shell.",
    note: "Spondylus gaederopus from the Aegean was worn in LBK graves as far as the Rhine.",
    sources: ["https://en.wikipedia.org/wiki/Linear_Pottery_culture"],
  },
  {
    id: "day.lbk.longhouse-daub",
    label: "Daubing the longhouse",
    scope: LBK,
    evidence: "documented",
    when: [{ type: "season", any: ["autumn"] }, { type: "chance", p: 0.25 }, { type: "adult" }],
    weight: 5,
    part: "morning",
    place: "home",
    activity: "work",
    minutes: 60,
    text: "Dig clay from the pits along the longhouse wall to daub the wattle.",
    note: "The long pits flanking every LBK house are where the wall clay was dug.",
    sources: ["https://en.wikipedia.org/wiki/Longhouse"],
    serves: ["household-home"],
  },
  {
    id: "day.newgrange.solstice",
    label: "Waiting for the midwinter sun",
    scope: MEGALITH_IRELAND,
    evidence: "hypothesis",
    when: [{ type: "date", dayOfYear: 355 }],
    weight: 14,
    part: "morning",
    place: "sanctuary",
    activity: "visit",
    minutes: 40,
    text: "Wait in the passage for the dawn sun to reach the chamber.",
    note: "At Newgrange the winter-solstice sunrise shines through the roof-box down the 19-metre passage.",
    sources: ["https://en.wikipedia.org/wiki/Newgrange"],
    serves: ["remember-dead"],
  },
  {
    id: "day.bronze.hearth-fire",
    label: "Feeding the hearth fire",
    scope: STEPPE_WEST,
    evidence: "hypothesis",
    when: [{ type: "observance", levels: ["devout", "regular"] }, { type: "chance", p: 0.3 }, { type: "adult" }],
    weight: 5,
    part: "morning",
    place: "hearth",
    activity: "visit",
    minutes: 15,
    text: "Feed the hearth fire a spoon of fat and call it *H₁n̥gʷnis.",
    note: "Vedic Agni, Latin ignis and Lithuanian ugnis descend from one word for fire as a living thing.",
    sources: ["https://en.wikipedia.org/wiki/Proto-Indo-European_mythology"],
  },
  {
    id: "day.bronze.oak-perkunos",
    label: "An offering at the thunder oak",
    scope: STEPPE_WEST,
    evidence: "hypothesis",
    when: [{ type: "season", any: ["summer"] }, { type: "chance", p: 0.15 }, { type: "adult" }],
    weight: 5,
    part: "evening",
    place: "wild",
    activity: "visit",
    minutes: 30,
    text: "Hang a bull's horn on the old oak for *Perkʷunos: thunder is coming.",
    note: "Perun, Perkūnas and Fjörgyn keep the oak-and-thunder link across Slavic, Baltic and Norse.",
    sources: ["https://en.wikipedia.org/wiki/Perkwunos"],
  },
  {
    id: "day.bronze.guest",
    label: "Taking in a guest",
    scope: STEPPE_WEST,
    evidence: "hypothesis",
    when: [{ type: "trait", key: "agreeableness", above: 50 }, { type: "chance", p: 0.12 }, { type: "adult" }],
    weight: 4,
    part: "evening",
    place: "home",
    activity: "cook",
    minutes: 45,
    text: "Feed the stranger at your fire: *Dyēus watches how guests are treated.",
    note: "Latin hostis and hospes and English guest share the root *gʰóstis, a bond of host and guest.",
    sources: ["https://en.wikipedia.org/wiki/Xenia_(Greek)"],
  },
  {
    id: "day.nordic.bog-offering",
    label: "Sinking a bronze in the bog",
    scope: NORDIC_BRONZE,
    evidence: "inferred",
    when: [{ type: "fortune", above: 0.6 }, { type: "chance", p: 0.08 }, { type: "adult" }],
    weight: 5,
    part: "evening",
    place: "wild",
    activity: "visit",
    minutes: 40,
    text: "Sink a bronze axe in the bog pool as a gift to the powers.",
    note: "Danish bogs gave up hoards of unused bronzes and the lurs, all laid down on purpose.",
    sources: ["https://en.wikipedia.org/wiki/Votive_deposit"],
  },
  {
    id: "day.nordic.rock-carving",
    label: "Pecking a ship into the rock",
    scope: eu([-1700, -500], [10, 57.5, 13, 60]),
    evidence: "inferred",
    when: [{ type: "chance", p: 0.12 }, { type: "adult" }],
    weight: 5,
    part: "midday",
    place: "wild",
    activity: "work",
    minutes: 60,
    text: "Peck a ship with its crew into the smooth rock above the shore.",
    sources: ["https://en.wikipedia.org/wiki/Rock_carvings_at_Tanum"],
  },
  {
    id: "day.minoan.peak-sanctuary",
    label: "Climbing to the peak sanctuary",
    scope: MINOAN,
    evidence: "inferred",
    when: [{ type: "observance", levels: ["devout", "regular"] }, { type: "chance", p: 0.1 }],
    weight: 5,
    part: "morning",
    place: "wild",
    activity: "visit",
    minutes: 70,
    carry: "bundle",
    text: "Climb to the peak sanctuary and leave a clay model of your aching limb.",
    note: "Peak sanctuaries such as Petsofas are strewn with clay human and animal figurines and model limbs.",
    sources: ["https://en.wikipedia.org/wiki/Minoan_peak_sanctuary"],
  },
  {
    id: "day.mycenae.flax-tax",
    label: "Delivering flax to the palace",
    scope: MYCENAEAN,
    evidence: "documented",
    when: [{ type: "work", match: /farm|field|flax|weav/i }, { type: "season", any: ["autumn"] }, { type: "chance", p: 0.25 }],
    weight: 6,
    part: "midday",
    place: "gathering",
    activity: "haul",
    minutes: 45,
    carry: "bundle",
    text: "Deliver your flax to the palace scribes and watch them mark it on clay.",
    note: "Pylos Linear B tablets list flax owed by named villages to the palace.",
    sources: ["https://en.wikipedia.org/wiki/Palace_of_Nestor"],
  },
  {
    id: "day.greek.hestia",
    label: "The first portion to Hestia",
    scope: GREEK,
    evidence: "documented",
    when: [{ type: "observance", levels: ["devout", "regular", "occasional"] }, { type: "adult" }],
    weight: 5,
    part: "evening",
    place: "hearth",
    activity: "visit",
    minutes: 10,
    text: "Throw the first morsel of the meal into the hearth for Hestia.",
    sources: ["https://en.wikipedia.org/wiki/Hestia"],
    serves: ["household-home"],
  },
  {
    id: "day.greek.noumenia",
    label: "The new moon offering",
    scope: GREEK,
    evidence: "documented",
    when: [{ type: "cycle", every: 9, on: 0 }, { type: "adult" }],
    weight: 7,
    part: "morning",
    place: "home",
    activity: "visit",
    minutes: 20,
    text: "Garland the household herm and burn frankincense: it is the Noumenia.",
    note: "The first of the month was the holiest day for household offerings.",
    sources: ["https://en.wikipedia.org/wiki/Noumenia"],
  },
  {
    id: "day.athens.agora",
    label: "Morning in the Agora",
    scope: ATHENS,
    evidence: "documented",
    when: [{ type: "sex", is: "male" }, { type: "chance", p: 0.3 }, { type: "adult" }],
    weight: 4,
    part: "morning",
    place: "market",
    activity: "visit",
    minutes: 50,
    carry: "basket",
    text: "Buy fish in the Agora and hear the news under the painted stoa.",
    note: "Shopping was men's or slaves' work in Athens; citizen women mostly stayed out of the market.",
    sources: ["https://en.wikipedia.org/wiki/Ancient_Agora_of_Athens"],
  },
  {
    id: "day.athens.ekklesia",
    label: "The assembly on the Pnyx",
    scope: eu([-508, -322], [23.3, 37.7, 24.2, 38.4]),
    evidence: "documented",
    when: [{ type: "sex", is: "male" }, { type: "cycle", every: 9, on: 2 }, { type: "tag", any: ["civic", "egalitarian", "communal"] }, { type: "adult" }],
    weight: 6,
    part: "morning",
    place: { venue: "assembly" },
    activity: "visit",
    minutes: 90,
    text: "Climb the Pnyx for the assembly before the Scythian archers rope in latecomers.",
    note: "The assembly met about forty times a year; public slaves swept laggards in with a red-dyed rope.",
    sources: ["https://en.wikipedia.org/wiki/Ecclesia_(ancient_Greece)"],
  },
  {
    id: "day.athens.deme",
    label: "The deme meeting",
    scope: eu([-508, -86], [23.3, 37.7, 24.2, 38.4]),
    evidence: "documented",
    when: [{ type: "sex", is: "male" }, { type: "chance", p: 0.08 }, { type: "adult" }],
    weight: 4,
    part: "midday",
    place: "gathering",
    activity: "visit",
    minutes: 60,
    text: "Vouch for a neighbour's son at the deme meeting when he is enrolled.",
    note: "At eighteen a youth was scrutinised and entered on his deme's register of citizens.",
    sources: ["https://en.wikipedia.org/wiki/Deme"],
  },
  {
    id: "day.greek.symposium",
    label: "A symposium",
    scope: GREEK,
    evidence: "documented",
    when: [{ type: "sex", is: "male" }, { type: "rank", any: ["gentry", "elite"] }, { type: "chance", p: 0.2 }],
    weight: 5,
    part: "evening",
    place: "door",
    activity: "visit",
    minutes: 90,
    text: "Recline at {friend}'s symposium, flicking the wine lees at the kottabos stand.",
    note: "Kottabos, flicking the last drops from a kylix at a target, was the symposium's game.",
    sources: ["https://en.wikipedia.org/wiki/Kottabos"],
  },
  {
    id: "day.greek.gymnasium",
    label: "At the gymnasium",
    scope: GREEK,
    evidence: "documented",
    when: [{ type: "sex", is: "male" }, { type: "rank", any: ["middling", "gentry", "elite"] }, { type: "chance", p: 0.3 }],
    weight: 4,
    part: "midday",
    place: "gathering",
    activity: "play",
    minutes: 60,
    text: "Wrestle at the gymnasium, then clean off the oil and dust with a strigil.",
    sources: ["https://en.wikipedia.org/wiki/Gymnasium_(ancient_Greece)"],
  },
  {
    id: "day.athens.choes",
    label: "The Choes",
    scope: ATHENS,
    evidence: "documented",
    when: [{ type: "date", dayOfYear: 56 }, { type: "kin", kind: "child", minAge: 3, maxAge: 5 }],
    weight: 14,
    part: "midday",
    place: "home",
    activity: "play",
    minutes: 40,
    text: "Give {child} a little painted jug of new wine: it is the Choes of the Anthesteria.",
    note: "Children of about three got miniature choes at the Anthesteria; many were buried with them.",
    sources: ["https://en.wikipedia.org/wiki/Anthesteria"],
    serves: ["raise-kin"],
  },
  {
    id: "day.athens.eleusis",
    label: "Walking to Eleusis",
    scope: ATHENS,
    evidence: "documented",
    when: [{ type: "date", dayOfYear: 267 }, { type: "observance", levels: ["devout", "regular"] }],
    weight: 12,
    part: "midday",
    place: "edge",
    activity: "visit",
    minutes: 90,
    text: "Walk the Sacred Way to Eleusis with the initiates, shouting for Iacchus.",
    sources: ["https://en.wikipedia.org/wiki/Eleusinian_Mysteries"],
  },
  {
    id: "day.hellenistic.asklepieion",
    label: "Sleeping in the Asklepieion",
    scope: HELLENISTIC,
    evidence: "documented",
    when: [{ type: "trait", key: "neuroticism", above: 60 }, { type: "chance", p: 0.05 }],
    weight: 5,
    part: "evening",
    place: "sanctuary",
    activity: "rest",
    minutes: 60,
    text: "Sleep in the god's portico at the Asklepieion and wait for a healing dream.",
    note: "Cure inscriptions at Epidauros record dreams in which Asklepios treated the sleeper.",
    sources: ["https://en.wikipedia.org/wiki/Asclepeion"],
  },
  {
    id: "day.hellenistic.gymnasiarch-oil",
    label: "Free oil from the gymnasiarch",
    scope: HELLENISTIC,
    evidence: "documented",
    when: [{ type: "sex", is: "male" }, { type: "fortune", below: 0.5 }, { type: "chance", p: 0.15 }],
    weight: 4,
    part: "morning",
    place: "gathering",
    activity: "visit",
    minutes: 30,
    carry: "vessel",
    text: "Collect your oil at the gymnasium, paid for this year by the gymnasiarch.",
    note: "Honorific decrees praise gymnasiarchs who bought the oil for everyone out of their own purse.",
    sources: ["https://en.wikipedia.org/wiki/Gymnasiarch"],
  },
  {
    id: "day.etruria.banquet",
    label: "An Etruscan banquet",
    scope: ETRURIA,
    evidence: "documented",
    when: [{ type: "rank", any: ["gentry", "elite"] }, { type: "kin", kind: "partner" }, { type: "chance", p: 0.2 }],
    weight: 5,
    part: "evening",
    place: "home",
    activity: "visit",
    minutes: 90,
    text: "Recline beside {partner} at the banquet while the double pipes play.",
    note: "Greek writers were shocked that Etruscan wives reclined at dinner with their husbands.",
    sources: ["https://en.wikipedia.org/wiki/Tomb_of_the_Leopards"],
  },
  {
    id: "day.etruria.tomb",
    label: "A meal at the family tomb",
    scope: ETRURIA,
    evidence: "inferred",
    when: [{ type: "anniversary", kind: "died" }],
    weight: 14,
    part: "midday",
    place: "edge",
    activity: "visit",
    minutes: 50,
    carry: "basket",
    text: "Carry food to {dead}'s tomb in the necropolis, dead {years} years now.",
    sources: ["https://en.wikipedia.org/wiki/Banditaccia"],
    serves: ["remember-dead"],
  },
  {
    id: "day.etruria.haruspex",
    label: "Watching the haruspex",
    scope: ETRURIA,
    evidence: "documented",
    when: [{ type: "fortune", below: 0.4 }, { type: "chance", p: 0.1 }, { type: "adult" }],
    weight: 4,
    part: "morning",
    place: "sanctuary",
    activity: "visit",
    minutes: 40,
    text: "Pay the haruspex to read the sheep's liver about your trouble.",
    note: "The bronze Liver of Piacenza maps the organ into regions ruled by named gods.",
    sources: ["https://en.wikipedia.org/wiki/Liver_of_Piacenza"],
  },
  {
    id: "day.gaul.mistletoe",
    label: "The mistletoe cutting",
    scope: GAUL,
    evidence: "documented",
    when: [{ type: "cycle", every: 9, on: 1 }, { type: "observance", levels: ["devout", "regular"] }, { type: "chance", p: 0.2 }],
    weight: 5,
    part: "morning",
    place: "wild",
    activity: "visit",
    minutes: 50,
    text: "Watch the druid cut mistletoe from the oak on the sixth day of the moon.",
    note: "Pliny has the druids cut oak mistletoe with a golden sickle on the moon's sixth day.",
    sources: ["https://en.wikipedia.org/wiki/Druid"],
  },
  {
    id: "day.ireland.beltane",
    label: "Driving cattle between the Beltane fires",
    scope: IRELAND,
    evidence: "documented",
    when: [{ type: "date", dayOfYear: 121 }, { type: "work", match: /herd|cattle|cow|farm/i }],
    weight: 14,
    part: "morning",
    place: "edge",
    activity: "graze",
    minutes: 50,
    text: "Drive the cattle between the two Beltane fires before they go to summer pasture.",
    note: "Sanas Cormaic, about 900 CE, says cattle were driven between two fires on Beltane against disease.",
    sources: ["https://en.wikipedia.org/wiki/Beltane"],
  },
  {
    id: "day.ireland.imbolc",
    label: "Imbolc",
    scope: IRELAND,
    evidence: "inferred",
    when: [{ type: "date", dayOfYear: 32 }, { type: "work", match: /herd|shep|sheep|farm/i }],
    weight: 12,
    part: "morning",
    place: "work",
    activity: "tend",
    minutes: 30,
    text: "Milk the ewes that have lambed and set the first milk aside for Brigid.",
    note: "Early Irish glosses tie Imbolc to ewes' milk; its link to the goddess Brigid is inferred.",
    sources: ["https://en.wikipedia.org/wiki/Imbolc"],
  },
  {
    id: "day.ireland.lughnasa",
    label: "The Lughnasa fair",
    scope: IRELAND,
    evidence: "documented",
    when: [{ type: "date", dayOfYear: 213 }, { type: "adult" }],
    weight: 12,
    part: "midday",
    place: "gathering",
    activity: "visit",
    minutes: 80,
    text: "Go up to the hill for the Lughnasa fair: races, bargains and matches made.",
    note: "The Óenach Tailten was held at Lughnasa at Teltown in Meath.",
    sources: ["https://en.wikipedia.org/wiki/Lughnasadh"],
    serves: ["marriage-hope"],
  },
  {
    id: "day.english.modraniht",
    label: "Mothers' Night",
    scope: EARLY_ENGLISH,
    evidence: "documented",
    when: [{ type: "date", dayOfYear: 358 }, { type: "adult" }],
    weight: 12,
    part: "evening",
    place: "hearth",
    activity: "warm",
    minutes: 50,
    text: "Sit up all night by the fire: it is Modraniht, the Mothers' Night.",
    note: "Bede names the heathen English eve of the year Modraniht; what was done on it he does not say.",
    sources: ["https://en.wikipedia.org/wiki/Modranicht"],
  },
  {
    id: "day.norse.jol",
    label: "Drinking the Yule",
    scope: NORSE,
    evidence: "documented",
    when: [{ type: "date", dayOfYear: 358 }, { type: "adult" }],
    weight: 14,
    part: "evening",
    place: "hearth",
    activity: "warm",
    minutes: 90,
    text: "Drink the Yule ale in the hall, pledging toasts to Odin and Freyr.",
    note: "Hákonar saga góða describes the jólablót toasts: Odin's cup, then Njörðr's and Freyr's.",
    sources: ["https://en.wikipedia.org/wiki/Yule"],
  },
  {
    id: "day.norse.thing",
    label: "The þing",
    scope: NORSE,
    evidence: "documented",
    when: [{ type: "sex", is: "male" }, { type: "rank", any: ["middling", "gentry", "elite"] }, { type: "chance", p: 0.06 }],
    weight: 5,
    part: "midday",
    place: { venue: "assembly" },
    activity: "visit",
    minutes: 90,
    text: "Ride to the þing to press your claim with sworn witnesses behind you.",
    sources: ["https://en.wikipedia.org/wiki/Thing_(assembly)"],
  },
  {
    id: "day.iceland.althing",
    label: "Riding to the Althing",
    scope: ICELAND,
    evidence: "documented",
    when: [{ type: "date", dayOfYear: 172 }, { type: "rank", any: ["gentry", "elite"] }],
    weight: 14,
    part: "morning",
    place: "edge",
    activity: "visit",
    minutes: 60,
    text: "Ride to Þingvellir for the Althing and set up your booth by the Law Rock.",
    note: "The Althing met for two weeks around midsummer; chieftains kept turf booths there.",
    sources: ["https://en.wikipedia.org/wiki/Althing"],
  },
  {
    id: "day.slavic.kupala",
    label: "Kupala night",
    scope: SLAVIC,
    evidence: "documented",
    when: [{ type: "date", dayOfYear: 174 }, { type: "seek-match" }],
    weight: 14,
    part: "evening",
    place: "edge",
    activity: "play",
    minutes: 60,
    text: "Float a wreath of flowers down the river to see whose bank it reaches.",
    note: "The Stoglav council of 1551 condemned the Kupala-night games; the rites are older.",
    sources: ["https://en.wikipedia.org/wiki/Kupala_Night"],
    serves: ["marriage-hope"],
  },
  {
    id: "day.slavic.dziady",
    label: "Dziady, the ancestors' supper",
    scope: eu([900, 1950], [22, 50, 33, 57]),
    evidence: "documented",
    when: [{ type: "date", dayOfYear: 305 }, { type: "adult" }],
    weight: 14,
    part: "evening",
    place: "hearth",
    activity: "cook",
    minutes: 60,
    text: "Set a place and a spoonful of each dish for the dead: it is Dziady.",
    sources: ["https://en.wikipedia.org/wiki/Dziady"],
    serves: ["remember-dead"],
  },
  {
    id: "day.baltic.jani-cheese",
    label: "Making the Jāņi cheese",
    scope: BALTIC,
    evidence: "documented",
    when: [{ type: "date", dayOfYear: 172 }, { type: "sex", is: "female" }, { type: "adult" }],
    weight: 12,
    part: "midday",
    place: "hearth",
    activity: "cook",
    minutes: 60,
    text: "Press the caraway cheese for Jāņi and weave oak-leaf crowns for the men.",
    sources: ["https://en.wikipedia.org/wiki/J%C4%81%C5%86i"],
  },
  {
    id: "day.baltic.veli",
    label: "Feeding the veļi",
    scope: BALTIC,
    evidence: "documented",
    when: [{ type: "season", any: ["autumn"] }, { type: "anniversary", kind: "died" }],
    weight: 14,
    part: "evening",
    place: "home",
    activity: "cook",
    minutes: 45,
    text: "Heat the bathhouse and set out food for {dead}'s soul in the season of souls.",
    note: "In the Latvian veļu laiks the dead were feasted and given the sauna before being sent off.",
    sources: ["https://en.wikipedia.org/wiki/Dziady"],
    serves: ["remember-dead"],
  },
  {
    id: "day.byzantium.hippodrome",
    label: "The races in the Hippodrome",
    scope: CONSTANTINOPLE,
    evidence: "documented",
    when: [{ type: "tag", any: ["worldly", "communal", "martial"] }, { type: "chance", p: 0.12 }],
    weight: 5,
    part: "midday",
    place: "gathering",
    activity: "visit",
    minutes: 90,
    text: "Shout for the Greens in the Hippodrome, cursing every Blue.",
    sources: ["https://en.wikipedia.org/wiki/Chariot_racing"],
  },
  {
    id: "day.orthodox.fast",
    label: "The Wednesday and Friday fast",
    scope: ORTHODOX,
    evidence: "documented",
    when: [{ type: "cycle", every: 7, on: 2 }, { type: "observance", levels: ["devout", "regular"] }],
    weight: 6,
    part: "midday",
    place: "home",
    activity: "cook",
    minutes: 30,
    text: "Cook beans with no oil: it is a fast day, as every Friday.",
    note: "The Didache already has Christians fasting on Wednesdays and Fridays; Orthodox practice kept both.",
    sources: ["https://en.wikipedia.org/wiki/Fasting_in_Christianity"],
  },
  {
    id: "day.orthodox.name-day",
    label: "A name day",
    scope: eu([1600, 1950], [19, 34, 30, 46]),
    evidence: "documented",
    when: [{ type: "patron" }, { type: "chance", p: 0.02 }, { type: "adult" }],
    weight: 8,
    part: "evening",
    place: "home",
    activity: "cook",
    minutes: 60,
    text: "Keep open house for your name day, the feast of {patron}.",
    sources: ["https://en.wikipedia.org/wiki/Name_day"],
  },
  {
    id: "day.orthodox.pascha-eggs",
    label: "Red eggs for Pascha",
    scope: ORTHODOX,
    evidence: "documented",
    when: [{ type: "date", dayOfYear: 104 }, { type: "adult" }],
    weight: 12,
    part: "morning",
    place: "hearth",
    activity: "cook",
    minutes: 40,
    text: "Boil the eggs red in onion skins for Pascha.",
    note: "Pascha moves with the moon; this is a representative mid-April day.",
    sources: ["https://en.wikipedia.org/wiki/Easter_egg"],
  },


  {
    id: "day.latin.friday-fish",
    label: "Friday fish",
    scope: LATIN,
    evidence: "documented",
    when: [{ type: "cycle", every: 7, on: 2 }, { type: "adult" }],
    weight: 5,
    part: "midday",
    place: "market",
    activity: "visit",
    minutes: 25,
    carry: "basket",
    text: "Buy salt herring for dinner: it is Friday, and no flesh may be eaten.",
    sources: ["https://en.wikipedia.org/wiki/Friday_fast"],
  },
  {
    id: "day.latin.candlemas",
    label: "Candlemas",
    scope: LATIN,
    evidence: "documented",
    when: [{ type: "date", dayOfYear: 33 }, { type: "adult" }],
    weight: 12,
    part: "morning",
    place: "sanctuary",
    activity: "visit",
    minutes: 40,
    text: "Carry your candle to church to be blessed: it is Candlemas.",
    note: "The blessed candles were kept at home and lit against storms and at the deathbed.",
    sources: ["https://en.wikipedia.org/wiki/Candlemas"],
  },
  {
    id: "day.latin.ash-wednesday",
    label: "Ash Wednesday",
    scope: eu([1100, 1950], [-11, 36, 25, 60]),
    evidence: "documented",
    when: [{ type: "date", dayOfYear: 54 }, { type: "observance", levels: ["devout", "regular", "occasional"] }],
    weight: 12,
    part: "morning",
    place: "sanctuary",
    activity: "visit",
    minutes: 30,
    text: "Kneel for the ashes on your forehead: Lent begins, and meat is put away.",
    note: "Ash Wednesday moves with Easter; this is a representative late-February day.",
    sources: ["https://en.wikipedia.org/wiki/Ash_Wednesday"],
  },
  {
    id: "day.latin.martinmas",
    label: "Martinmas slaughter",
    scope: eu([800, 1900], [-11, 42, 25, 56]),
    evidence: "documented",
    when: [{ type: "date", dayOfYear: 315 }, { type: "work", match: /farm|herd|butch|pig|swine|cattle/i }],
    weight: 14,
    part: "morning",
    place: "work",
    activity: "work",
    minutes: 90,
    text: "Slaughter the beasts there is no hay to winter: it is Martinmas.",
    sources: ["https://en.wikipedia.org/wiki/St._Martin%27s_Day"],
  },
  {
    id: "day.england.lammas",
    label: "The Lammas loaf",
    scope: eu([900, 1600], [-6, 49.8, 2, 56]),
    evidence: "documented",
    when: [{ type: "date", dayOfYear: 213 }, { type: "work", match: /farm|field|bak|mill|reap/i }],
    weight: 12,
    part: "morning",
    place: "sanctuary",
    activity: "visit",
    minutes: 30,
    carry: "basket",
    text: "Take a loaf of the new wheat to church to be blessed: it is Lammas.",
    note: "The Anglo-Saxon Chronicle calls 1 August hlafmæsse, loaf-mass.",
    sources: ["https://en.wikipedia.org/wiki/Lammas"],
  },
  {
    id: "day.england.lady-day",
    label: "Lady Day rent",
    scope: ENGLAND,
    evidence: "documented",
    when: [{ type: "date", dayOfYear: 84 }, { type: "rank", any: ["labouring", "middling"] }, { type: "adult" }],
    weight: 14,
    part: "midday",
    place: "door",
    activity: "visit",
    minutes: 30,
    text: "Pay the half-year's rent to the steward: it is Lady Day.",
    note: "Lady Day was also the first day of the legal year in England until 1752.",
    sources: ["https://en.wikipedia.org/wiki/Lady_Day"],
    serves: ["household-home"],
  },
  {
    id: "day.manor.boon-work",
    label: "Boon work on the demesne",
    scope: eu([1000, 1400], [-6, 43, 12, 56]),
    evidence: "documented",
    when: [{ type: "season", any: ["summer", "autumn"] }, { type: "rank", any: ["labouring"] }, { type: "chance", p: 0.2 }, { type: "adult" }],
    weight: 6,
    part: "morning",
    place: "edge",
    activity: "tend",
    minutes: 120,
    text: "Reap the lord's corn at the boon work: the reeve has called every household.",
    note: "Boon-reapers were usually owed a meal from the lord, sometimes with ale.",
    sources: ["https://en.wikipedia.org/wiki/Manorialism"],
  },
  {
    id: "day.england.plough-monday",
    label: "Plough Monday",
    scope: eu([1400, 1900], [-6, 49.8, 2, 56]),
    evidence: "documented",
    when: [{ type: "date", dayOfYear: 10 }, { type: "work", match: /plough|plow|farm/i }, { type: "sex", is: "male" }],
    weight: 12,
    part: "midday",
    place: "gathering",
    activity: "play",
    minutes: 60,
    text: "Haul the decorated plough door to door, begging pennies for the plough light.",
    sources: ["https://en.wikipedia.org/wiki/Plough_Monday"],
  },
  {
    id: "day.england.rogation",
    label: "Beating the bounds",
    scope: ENGLAND,
    evidence: "documented",
    when: [{ type: "date", dayOfYear: 130 }, { type: "kin", kind: "child", minAge: 6, maxAge: 14 }],
    weight: 12,
    part: "morning",
    place: "edge",
    activity: "visit",
    minutes: 70,
    text: "Walk the parish bounds with {child} so the boundary stones are remembered.",
    note: "Rogationtide moves with Easter; boys were sometimes bumped on the marker stones to fix them in memory.",
    sources: ["https://en.wikipedia.org/wiki/Beating_the_bounds"],
    serves: ["child-future"],
  },
  {
    id: "day.england.may-day",
    label: "Bringing in the may",
    scope: eu([1300, 1900], [-8, 49.5, 2, 59]),
    evidence: "documented",
    when: [{ type: "date", dayOfYear: 121 }, { type: "trait", key: "extraversion", above: 40 }],
    weight: 12,
    part: "morning",
    place: "wild",
    activity: "gather",
    minutes: 50,
    carry: "bundle",
    text: "Go out at dawn and bring home green branches and hawthorn: it is May Day.",
    sources: ["https://en.wikipedia.org/wiki/May_Day"],
  },
  {
    id: "day.latin.market-charter",
    label: "Charter market day",
    scope: eu([1200, 1520], [-6, 49.8, 2, 56]),
    evidence: "documented",
    when: [{ type: "cycle", every: 7, on: 1 }, { type: "rank", any: ["labouring", "middling"] }, { type: "adult" }],
    weight: 5,
    part: "morning",
    place: "market",
    activity: "visit",
    minutes: 45,
    carry: "basket",
    text: "Take eggs and cheese to the Thursday market the king's charter allows.",
    note: "Royal charters granted a market on one named weekday; over 2,000 were issued in England by 1500.",
    sources: ["https://en.wikipedia.org/wiki/Market_town"],
  },
  {
    id: "day.latin.guild-feast",
    label: "The guild feast",
    scope: eu([1200, 1600], [-11, 36, 25, 60]),
    evidence: "documented",
    when: [{ type: "craft-power" }, { type: "rank", any: ["middling", "gentry"] }, { type: "chance", p: 0.04 }],
    weight: 8,
    part: "evening",
    place: { venue: "lodge" },
    activity: "visit",
    minutes: 90,
    text: "Feast with your guild in the hall on the day of {craftPower}.",
    sources: ["https://en.wikipedia.org/wiki/Guild"],
  },
  {
    id: "day.latin.pilgrim-badge",
    label: "A pilgrim's badge",
    scope: LATIN,
    evidence: "documented",
    when: [{ type: "observance", levels: ["devout"] }, { type: "chance", p: 0.05 }],
    weight: 5,
    part: "midday",
    place: "sanctuary",
    activity: "visit",
    minutes: 50,
    text: "Kneel at the saint's shrine and buy a lead pilgrim badge for your hat.",
    sources: ["https://en.wikipedia.org/wiki/Pilgrim_badge"],
  },
  {
    id: "day.reformation.catechism",
    label: "Catechism on Sunday afternoon",
    scope: eu([1530, 1800], [4, 46, 25, 60]),
    evidence: "documented",
    when: [{ type: "cycle", every: 7, on: 4 }, { type: "kin", kind: "child", minAge: 7, maxAge: 14 }],
    weight: 6,
    part: "evening",
    place: "home",
    activity: "visit",
    minutes: 30,
    text: "Hear {child} recite Luther's Small Catechism before supper.",
    note: "Luther wrote the Small Catechism in 1529 for the head of the household to teach.",
    sources: ["https://en.wikipedia.org/wiki/Luther%27s_Small_Catechism"],
    serves: ["raise-kin"],
  },
  {
    id: "day.earlymodern.coffeehouse",
    label: "Coffee and the gazette",
    scope: eu([1650, 1800], [-11, 36, 30, 66]),
    evidence: "documented",
    when: [{ type: "tag", any: ["literate", "mercantile", "worldly"] }, { type: "chance", p: 0.25 }],
    weight: 4,
    part: "midday",
    place: { venue: "coffee-house" },
    activity: "visit",
    minutes: 50,
    text: "Read the gazette over a dish of coffee, arguing about the war.",
    sources: ["https://en.wikipedia.org/wiki/English_coffeehouses_in_the_17th_and_18th_centuries"],
  },
  {
    id: "day.earlymodern.carnival-mask",
    label: "Masked for carnival",
    scope: EARLY_MODERN,
    evidence: "documented",
    when: [{ type: "date", dayOfYear: 48 }, { type: "trait", key: "extraversion", above: 50 }],
    weight: 12,
    part: "evening",
    place: "gathering",
    activity: "play",
    minutes: 70,
    text: "Put on a mask and go out pelting the crowd with scented eggs: it is carnival.",
    note: "Carnival ran to Shrove Tuesday, which moves with Easter; this is a representative day.",
    sources: ["https://en.wikipedia.org/wiki/Carnival"],
  },
  {
    id: "day.europe-modern.cinema",
    label: "The pictures",
    scope: MODERN,
    evidence: "documented",
    when: [{ type: "cycle", every: 7, on: 3 }, { type: "chance", p: 0.35 }],
    weight: 5,
    part: "evening",
    place: { venue: "theatre" },
    activity: "visit",
    minutes: 110,
    text: "Queue for the pictures with {friend} and sit through the newsreel twice.",
    note: "By the late 1930s Britons bought some 20 million cinema tickets a week.",
    sources: ["https://en.wikipedia.org/wiki/Cinema_of_the_United_Kingdom"],
  },
  {
    id: "day.europe-modern.football",
    label: "The Saturday match",
    scope: MODERN,
    evidence: "documented",
    when: [{ type: "cycle", every: 7, on: 3 }, { type: "sex", is: "male" }, { type: "rank", any: ["labouring", "middling"] }, { type: "chance", p: 0.4 }],
    weight: 6,
    part: "midday",
    place: "gathering",
    activity: "visit",
    minutes: 110,
    text: "Stand on the terraces for the three o'clock kick-off after the Saturday half-day.",
    sources: ["https://en.wikipedia.org/wiki/Saturday_3pm_blackout"],
  },
  {
    id: "day.europe-modern.dance-hall",
    label: "The dance hall",
    scope: MODERN,
    evidence: "documented",
    when: [{ type: "cycle", every: 7, on: 3 }, { type: "seek-match" }],
    weight: 7,
    part: "evening",
    place: "gathering",
    activity: "play",
    minutes: 90,
    text: "Dance the foxtrot at the palais, hoping to be walked home.",
    sources: ["https://en.wikipedia.org/wiki/Hammersmith_Palais"],
    serves: ["marriage-hope"],
  },
  {
    id: "day.europe-modern.wireless",
    label: "Listening to the wireless",
    scope: BRITAIN_MODERN,
    evidence: "documented",
    when: [{ type: "kin", kind: "partner" }, { type: "fortune", above: 0.3 }, { type: "chance", p: 0.3 }],
    weight: 4,
    part: "evening",
    place: "home",
    activity: "rest",
    minutes: 50,
    text: "Sit with {partner} by the wireless for the BBC dance-band hour.",
    sources: ["https://en.wikipedia.org/wiki/History_of_broadcasting"],
  },
  {
    id: "day.europe-modern.tram",
    label: "The tram into town",
    scope: eu([1914, 1950], [-11, 40, 40, 62]),
    evidence: "documented",
    when: [{ type: "fortune", above: 0.3 }, { type: "chance", p: 0.2 }, { type: "adult" }],
    weight: 3,
    part: "midday",
    place: "market",
    activity: "visit",
    minutes: 50,
    carry: "basket",
    text: "Take the tram into the centre to look in the department-store windows.",
    sources: ["https://en.wikipedia.org/wiki/Trams_in_Europe"],
  },
  {
    id: "day.europe-modern.ration-queue",
    label: "The ration queue",
    scope: eu([1940, 1950], [-11, 35, 40, 70]),
    evidence: "documented",
    when: [{ type: "chance", p: 0.35 }, { type: "adult" }],
    weight: 6,
    part: "morning",
    place: "market",
    activity: "visit",
    minutes: 60,
    carry: "basket",
    text: "Queue at the grocer's with the ration book for the week's fat and sugar.",
    sources: ["https://en.wikipedia.org/wiki/Rationing_in_the_United_Kingdom"],
    serves: ["household-home"],
  },
  {
    id: "day.europe-modern.allotment",
    label: "Digging for victory",
    scope: eu([1939, 1950], [-8, 49.5, 2, 59]),
    evidence: "documented",
    when: [{ type: "trait", key: "conscientiousness", above: 45 }, { type: "chance", p: 0.25 }, { type: "adult" }],
    weight: 4,
    part: "evening",
    place: "edge",
    activity: "tend",
    minutes: 60,
    text: "Dig potatoes on your allotment: Dig for Victory.",
    sources: ["https://en.wikipedia.org/wiki/Dig_for_Victory"],
  },
  {
    id: "day.europe-modern.front-socks",
    label: "Knitting for the front",
    scope: eu([1914, 1919], [-11, 35, 40, 70]),
    evidence: "documented",
    when: [{ type: "sex", is: "female" }, { type: "chance", p: 0.3 }, { type: "adult" }],
    weight: 4,
    part: "evening",
    place: "home",
    activity: "work",
    minutes: 50,
    text: "Knit khaki socks for the men at the front.",
    sources: ["https://en.wikipedia.org/wiki/Knitting#History"],
  },
  {
    id: "day.europe-modern.pools",
    label: "The pools coupon",
    scope: BRITAIN_MODERN,
    evidence: "documented",
    when: [{ type: "cycle", every: 7, on: 1 }, { type: "rank", any: ["labouring"] }, { type: "sex", is: "male" }],
    weight: 4,
    part: "evening",
    place: "home",
    activity: "rest",
    minutes: 25,
    text: "Fill in the football pools coupon, dreaming of the first dividend.",
    sources: ["https://en.wikipedia.org/wiki/Football_pools"],
  },
  {
    id: "day.europe-modern.may-day-march",
    label: "The May Day march",
    scope: eu([1890, 1950], [-11, 35, 40, 70]),
    evidence: "documented",
    when: [{ type: "date", dayOfYear: 121 }, { type: "tag", any: ["revolutionary", "reformist", "egalitarian"] }, { type: "rank", any: ["labouring"] }],
    weight: 14,
    part: "midday",
    place: "gathering",
    activity: "visit",
    minutes: 90,
    text: "March behind the union banner: it is the workers' May Day.",
    sources: ["https://en.wikipedia.org/wiki/International_Workers%27_Day"],
  },
];

export const europeDeepFestivals: Festival[] = [
  {
    id: "fest.neolithic.midwinter-feast",
    label: "the midwinter feast",
    scope: MEGALITH_BRITAIN,
    evidence: "inferred",
    date: { dayOfYear: 356 },
    rest: false,
    place: "gathering",
    minutes: 120,
    text: "It is midwinter: roast the pigs and watch the sun set down the stone avenue.",
    note: "Pig teeth at Durrington Walls show most were slaughtered at about nine months: midwinter.",
    sources: ["https://en.wikipedia.org/wiki/Durrington_Walls"],
  },
  {
    id: "fest.athens.panathenaia",
    label: "the Panathenaia",
    scope: ATHENS,
    evidence: "documented",
    date: { dayOfYear: 215 },
    rest: true,
    place: "sanctuary",
    minutes: 150,
    text: "It is the Panathenaia: the new peplos goes up to Athena, and a hundred cattle are shared out.",
    sources: ["https://en.wikipedia.org/wiki/Panathenaic_Games"],
  },
  {
    id: "fest.athens.dionysia",
    label: "the City Dionysia",
    scope: ATHENS,
    evidence: "documented",
    date: { dayOfYear: 85 },
    rest: false,
    place: "gathering",
    minutes: 150,
    text: "It is the City Dionysia: the tragedies play from dawn in the theatre of Dionysus.",
    sources: ["https://en.wikipedia.org/wiki/Dionysia"],
  },
  {
    id: "fest.ireland.samhain",
    label: "Samhain",
    scope: IRELAND,
    evidence: "documented",
    date: { dayOfYear: 305 },
    rest: false,
    place: "gathering",
    minutes: 120,
    text: "It is Samhain: the herds are in, the year turns, and the dead walk abroad.",
    note: "Early Irish tales set assemblies and feasts at Samhain and make it the night the síd mounds open.",
    sources: ["https://en.wikipedia.org/wiki/Samhain"],
  },
  {
    id: "fest.norse.winter-nights",
    label: "the Winter Nights",
    scope: NORSE,
    evidence: "documented",
    date: { dayOfYear: 288 },
    rest: false,
    place: "gathering",
    minutes: 120,
    text: "It is the Winter Nights: the blót for a good year, and the fattest beasts slaughtered.",
    note: "Ynglinga saga has a blót at the start of winter for a good year, one at midwinter, one in summer.",
    sources: ["https://en.wikipedia.org/wiki/Winter_Nights"],
  },
  {
    id: "fest.christendom.easter",
    label: "Easter",
    scope: CHRISTENDOM,
    evidence: "documented",
    date: { dayOfYear: 105 },
    rest: true,
    place: "sanctuary",
    minutes: 120,
    text: "It is Easter: the fast is broken after the long vigil, and nobody works.",
    note: "Easter moves between 22 March and 25 April; this is a representative mid-April day.",
    sources: ["https://en.wikipedia.org/wiki/Easter"],
  },  {
    id: "fest.christendom.easter-north",
    label: "Easter",
    scope: CHRISTENDOM_NORTH,
    evidence: "documented",
    date: { dayOfYear: 105 },
    rest: true,
    place: "sanctuary",
    minutes: 120,
    text: "It is Easter: the fast is broken after the long vigil, and nobody works.",
    note: "Easter moves between 22 March and 25 April; this is a representative mid-April day.",
    sources: ["https://en.wikipedia.org/wiki/Easter"],
  },
  {
    id: "fest.latin.corpus-christi",
    label: "Corpus Christi",
    scope: eu([1320, 1520], [-11, 36, 25, 60]),
    evidence: "documented",
    date: { dayOfYear: 161 },
    rest: true,
    place: "gathering",
    minutes: 150,
    text: "It is Corpus Christi: the host is carried through the streets and the guilds play their pageants.",
    note: "Corpus Christi moves with Easter; this is a representative early-June day.",
    sources: ["https://en.wikipedia.org/wiki/Feast_of_Corpus_Christi"],
  },
  {
    id: "fest.europe.shrove-tuesday",
    label: "Shrove Tuesday",
    scope: eu([1300, 1900], [-8, 49.5, 2, 59]),
    evidence: "documented",
    date: { dayOfYear: 51 },
    rest: false,
    place: "gathering",
    minutes: 90,
    text: "It is Shrove Tuesday: pancakes, and the whole parish at the mob football.",
    note: "Shrove Tuesday moves with Easter; this is a representative late-February day.",
    sources: ["https://en.wikipedia.org/wiki/Royal_Shrovetide_Football"],
  },
  {
    id: "fest.europe-modern.armistice",
    label: "Armistice Day",
    scope: eu([1919, 1950], [-8, 42, 7, 59]),
    evidence: "documented",
    date: { dayOfYear: 315 },
    rest: false,
    place: "gathering",
    minutes: 40,
    text: "It is Armistice Day: at eleven o'clock everything stops for the two minutes' silence.",
    sources: ["https://en.wikipedia.org/wiki/Armistice_Day"],
  },
];
