import type { Festival, Occasion } from "./types";

const EUROPE: [number, number, number, number] = [-11, 34, 45, 72];
const BRITAIN: [number, number, number, number] = [-8, 49.5, 2, 59];
const CHRISTIAN = { years: [500, 1950] as [number, number], bounds: EUROPE, cultures: ["european" as const] };
const INDUSTRIAL_BRITAIN = { years: [1780, 1914] as [number, number], bounds: BRITAIN, cultures: ["european" as const] };

export const europeOccasions: Occasion[] = [
  {
    id: "day.europe.saint-candle",
    label: "A candle for a saint",
    scope: { years: [500, 1520], bounds: EUROPE, cultures: ["european"] },
    evidence: "documented",
    when: [{ type: "patron" }, { type: "observance", levels: ["devout", "regular"] }],
    weight: 5,
    part: "morning",
    place: "sanctuary",
    activity: "visit",
    minutes: 20,
    text: "Light a candle before {patron} and ask for help.",
    sources: ["https://en.wikipedia.org/wiki/Patron_saint"],
  },
  {
    id: "day.europe.michaelmas-rent",
    label: "Michaelmas rent",
    scope: { years: [1000, 1900], bounds: BRITAIN, cultures: ["european"] },
    evidence: "documented",
    when: [{ type: "date", dayOfYear: 272 }, { type: "rank", any: ["labouring", "middling"] }, { type: "adult" }],
    weight: 14,
    part: "midday",
    place: "door",
    activity: "visit",
    minutes: 30,
    text: "Pay the half-year's rent: it is Michaelmas, a quarter day.",
    sources: ["https://en.wikipedia.org/wiki/Quarter_days"],
    serves: ["household-home"],
  },
  {
    id: "day.europe.anniversary-flowers",
    label: "A wedding anniversary",
    scope: { years: [1840, 1960], bounds: EUROPE, cultures: ["european"] },
    evidence: "inferred",
    when: [{ type: "anniversary", kind: "wed" }, { type: "kin", kind: "partner" }],
    weight: 14,
    part: "evening",
    place: "market",
    activity: "visit",
    minutes: 25,
    carry: "basket",
    text: "Buy flowers for your {nth} wedding anniversary with {partner}.",
    note: "Marking wedding anniversaries, and naming the silver and golden ones, spread through the nineteenth-century middle class.",
    sources: ["https://en.wikipedia.org/wiki/Wedding_anniversary"],
    serves: ["shared-future"],
  },
  {
    id: "day.europe.bandstand",
    label: "The band in the park",
    scope: { years: [1850, 1940], bounds: EUROPE, cultures: ["european"] },
    evidence: "documented",
    when: [{ type: "cycle", every: 7, on: 4 }, { type: "trait", key: "openness", above: 48 }],
    weight: 6,
    part: "evening",
    place: "gathering",
    activity: "visit",
    minutes: 60,
    text: "Hear the band play in the park after church.",
    sources: ["https://en.wikipedia.org/wiki/Bandstand"],
  },
  {
    id: "day.europe.newspaper",
    label: "Reading the paper",
    scope: { years: [1780, 1950], bounds: EUROPE, cultures: ["european"] },
    evidence: "documented",
    when: [{ type: "tag", any: ["literate", "reformist", "rationalist"] }, { type: "chance", p: 0.3 }],
    weight: 4,
    part: "evening",
    place: { venue: "tavern" },
    activity: "visit",
    minutes: 40,
    text: "Read the newspaper aloud to whoever will listen.",
    note: "One copy passed through many hands, and was often read out in a public house to those who could not read.",
    sources: ["https://en.wikipedia.org/wiki/History_of_British_newspapers"],
  },
  {
    id: "day.britain.sunday-joint",
    label: "The Sunday joint",
    scope: INDUSTRIAL_BRITAIN,
    evidence: "documented",
    when: [{ type: "cycle", every: 7, on: 4 }, { type: "rank", any: ["labouring", "destitute"] }, { type: "adult" }],
    weight: 6,
    part: "morning",
    place: "market",
    activity: "visit",
    minutes: 20,
    carry: "basket",
    text: "Take the Sunday joint to the baker's to be roasted in his oven.",
    note: "Households with no oven of their own paid the baker a penny or two to use his on a Sunday.",
    sources: ["https://en.wikipedia.org/wiki/Sunday_roast"],
  },
  {
    id: "day.britain.burial-club",
    label: "The burial club",
    scope: INDUSTRIAL_BRITAIN,
    evidence: "documented",
    when: [{ type: "cycle", every: 7, on: 3 }, { type: "rank", any: ["labouring"] }, { type: "adult" }],
    weight: 5,
    part: "evening",
    place: { venue: "tavern" },
    activity: "visit",
    minutes: 30,
    text: "Pay your pennies into the burial club at the public house.",
    note: "Friendly societies and burial clubs commonly met, and kept their box, in a public house.",
    sources: ["https://en.wikipedia.org/wiki/Friendly_society"],
  },
  {
    id: "day.britain.pawn",
    label: "Pawning the Sunday clothes",
    scope: INDUSTRIAL_BRITAIN,
    evidence: "documented",
    when: [{ type: "cycle", every: 7, on: 5 }, { type: "fortune", below: 0.5 }, { type: "adult" }],
    weight: 6,
    part: "morning",
    place: "market",
    activity: "visit",
    minutes: 20,
    carry: "bundle",
    text: "Pawn the Sunday clothes until Saturday's wages come in.",
    sources: ["https://en.wikipedia.org/wiki/Pawnbroker"],
    serves: ["restore-household"],
  },
  {
    id: "day.britain.saint-monday",
    label: "Saint Monday",
    scope: { years: [1700, 1880], bounds: BRITAIN, cultures: ["european"] },
    evidence: "documented",
    when: [{ type: "cycle", every: 7, on: 5 }, { type: "trait", key: "conscientiousness", below: 50 }, { type: "work", match: /smith|weav|shoe|cobbl|tailor|cutler|carpent|joiner|potter|work/i }],
    weight: 6,
    part: "midday",
    place: { venue: "tavern" },
    activity: "visit",
    minutes: 70,
    text: "Keep Saint Monday at the public house and let the work wait.",
    note: "Artisans paid by the piece commonly took Monday off and made it up later in the week.",
    sources: ["https://en.wikipedia.org/wiki/Saint_Monday"],
  },
];

export const europeFestivals: Festival[] = [
  {
    id: "fest.europe.lords-day",
    label: "the Lord's day",
    scope: { years: [500, 1520], bounds: EUROPE, cultures: ["european"] },
    evidence: "documented",
    date: { every: 7, on: 4 },
    rest: true,
    place: "sanctuary",
    minutes: 90,
    text: "It is Sunday: hear mass, and do no servile work.",
    sources: ["https://en.wikipedia.org/wiki/Sabbath_in_Christianity"],
  },
  {
    id: "fest.europe.sunday",
    label: "Sunday",
    scope: { years: [1520, 1950], bounds: EUROPE, cultures: ["european"] },
    evidence: "documented",
    date: { every: 7, on: 4 },
    rest: true,
    place: "sanctuary",
    minutes: 90,
    text: "It is Sunday: go to church, and keep the day from work.",
    sources: ["https://en.wikipedia.org/wiki/Sabbath_in_Christianity"],
  },
  {
    id: "fest.europe.christmas",
    label: "Christmas",
    scope: CHRISTIAN,
    evidence: "documented",
    date: { dayOfYear: 359 },
    rest: true,
    place: "sanctuary",
    minutes: 120,
    text: "It is Christmas Day: church, then the best meal of the year.",
    sources: ["https://en.wikipedia.org/wiki/Christmas"],
  },
  {
    id: "fest.europe.midsummer",
    label: "St John's Eve",
    scope: CHRISTIAN,
    evidence: "documented",
    date: { dayOfYear: 174 },
    rest: false,
    place: "gathering",
    minutes: 60,
    text: "Go to the bonfires on St John's Eve.",
    sources: ["https://en.wikipedia.org/wiki/Saint_John%27s_Eve"],
  },
];
