import type { Occasion } from "./types";

const ALL: [number, number] = [-1000000, 10001];

/**
 * What anyone anywhere might do on a given day. Stand-ins for the unrecorded:
 * a scope with its own named occasions discounts these, so a Roman gives the
 * Lares their garland rather than "an offering".
 */
export const generalOccasions: Occasion[] = [
  {
    id: "day.patron-offering",
    label: "Offering to a patron",
    scope: { years: ALL },
    evidence: "inferred",
    when: [{ type: "patron" }, { type: "observance", levels: ["devout", "regular"] }, { type: "adult" }],
    weight: 3,
    part: "morning",
    place: "sanctuary",
    activity: "visit",
    minutes: 25,
    carry: "basket",
    text: "Bring a small offering to {patron}.",
    note: "The patron is drawn from the powers this tradition actually addressed.",
    sources: [],
    fallback: true,
  },
  {
    id: "day.craft-power",
    label: "Asking favour for the work",
    scope: { years: ALL },
    evidence: "inferred",
    when: [{ type: "craft-power" }, { type: "observance", levels: ["devout", "regular", "occasional"] }, { type: "adult" }],
    weight: 3,
    part: "morning",
    place: "hearth",
    activity: "visit",
    minutes: 15,
    text: "Ask {craftPower} to look kindly on the day's work.",
    sources: [],
    fallback: true,
  },
  {
    id: "day.elder-kin",
    label: "Sitting with an old parent",
    scope: { years: ALL },
    evidence: "inferred",
    when: [{ type: "kin", kind: "parent", minAge: 60 }],
    weight: 4,
    part: "evening",
    place: { kin: "parent" },
    activity: "visit",
    minutes: 40,
    text: "Sit a while with {parent}, who is {age} now.",
    serves: ["elder-kin"],
    sources: [],
    fallback: true,
  },
  {
    id: "day.teach-child",
    label: "Teaching a child the work",
    scope: { years: ALL },
    evidence: "inferred",
    when: [{ type: "kin", kind: "child", minAge: 7, maxAge: 15 }, { type: "adult" }],
    weight: 3,
    part: "midday",
    place: "work",
    activity: "work",
    minutes: 40,
    text: "Show {child} how the work is done.",
    serves: ["raise-kin", "child-future"],
    sources: [],
    fallback: true,
  },
  {
    id: "day.partner-walk",
    label: "An evening with a partner",
    scope: { years: ALL },
    evidence: "inferred",
    when: [{ type: "kin", kind: "partner" }, { type: "trait", key: "agreeableness", above: 45 }],
    weight: 2,
    part: "evening",
    place: "gathering",
    activity: "visit",
    minutes: 35,
    text: "Spend the evening in company with {partner}.",
    serves: ["shared-future"],
    sources: [],
    fallback: true,
  },
  {
    id: "day.friend",
    label: "Calling on a friend",
    scope: { years: ALL },
    evidence: "inferred",
    when: [{ type: "kin", kind: "friend" }, { type: "trait", key: "extraversion", above: 40 }],
    weight: 2,
    part: "evening",
    place: { kin: "friend" },
    activity: "visit",
    minutes: 35,
    text: "Call on {friend} to hear how things stand.",
    sources: [],
    fallback: true,
  },
  {
    id: "day.mend-home",
    label: "Mending the house",
    scope: { years: ALL },
    evidence: "inferred",
    when: [{ type: "adult" }, { type: "chance", p: 0.5 }],
    weight: 1.5,
    part: "midday",
    place: "home",
    activity: "work",
    minutes: 45,
    carry: "bundle",
    text: "Mend what the weather has loosened on the house.",
    serves: ["household-home", "new-settlement", "restore-household"],
    sources: [],
    fallback: true,
  },
  {
    id: "day.check-store",
    label: "Going over the stores",
    scope: { years: ALL },
    evidence: "inferred",
    when: [{ type: "adult" }, { type: "trait", key: "neuroticism", above: 55 }],
    weight: 1.5,
    part: "evening",
    place: "home",
    activity: "haul",
    minutes: 20,
    text: "Go over the stores again for damp and mice.",
    serves: ["household-home", "restore-household"],
    sources: [],
    fallback: true,
  },
  {
    id: "day.death-day",
    label: "Keeping a death day",
    scope: { years: ALL },
    evidence: "inferred",
    when: [{ type: "anniversary", kind: "died" }],
    weight: 12,
    part: "evening",
    place: "edge",
    activity: "visit",
    minutes: 40,
    text: "Mark the day your {dead} died, {years} years ago.",
    serves: ["remember-dead", "widowed-household"],
    note: "Most traditions keep some memory of a death on its day; the form varies more than the fact.",
    sources: [],
    fallback: true,
  },
  {
    id: "day.speak-of-dead",
    label: "Speaking of the dead",
    scope: { years: ALL },
    evidence: "inferred",
    when: [{ type: "anniversary", kind: "died" }, { type: "chance", p: 0.3 }],
    weight: 2,
    part: "evening",
    place: "hearth",
    activity: "warm",
    minutes: 30,
    text: "Tell the young ones about your {dead}.",
    serves: ["remember-dead"],
    sources: [],
    fallback: true,
  },
  {
    id: "day.match",
    label: "Seeking a match",
    scope: { years: ALL },
    evidence: "inferred",
    when: [{ type: "seek-match" }],
    weight: 4,
    part: "midday",
    place: "door",
    activity: "visit",
    minutes: 40,
    text: "Call on a family with a son or daughter of age, about {child}.",
    serves: ["marriage-hope"],
    sources: [],
    fallback: true,
  },
  {
    id: "day.borrow",
    label: "Borrowing to get by",
    scope: { years: ALL },
    evidence: "inferred",
    when: [{ type: "fortune", below: 0.35 }, { type: "adult" }],
    weight: 2,
    part: "morning",
    place: "door",
    activity: "visit",
    minutes: 25,
    carry: "basket",
    text: "Ask a neighbour for a loan of food until better days.",
    serves: ["restore-household", "widowed-household"],
    sources: [],
    fallback: true,
  },
  {
    id: "day.quarrel",
    label: "A quarrel with a neighbour",
    scope: { years: ALL },
    evidence: "inferred",
    when: [{ type: "trait", key: "agreeableness", below: 40 }, { type: "chance", p: 0.3 }, { type: "adult" }],
    weight: 2,
    part: "midday",
    place: "door",
    activity: "visit",
    minutes: 20,
    text: "Have it out with a neighbour over the boundary.",
    serves: ["household-home"],
    sources: [],
    fallback: true,
  },
  {
    id: "day.wander",
    label: "Walking out to look",
    scope: { years: ALL },
    evidence: "inferred",
    when: [{ type: "trait", key: "openness", above: 62 }, { type: "chance", p: 0.4 }],
    weight: 1.5,
    part: "evening",
    place: "wild",
    activity: "visit",
    minutes: 30,
    text: "Walk out past the last houses, just to see.",
    sources: [],
    fallback: true,
  },
  {
    id: "day.idle",
    label: "Putting the work off",
    scope: { years: ALL },
    evidence: "inferred",
    when: [{ type: "trait", key: "conscientiousness", below: 38 }, { type: "chance", p: 0.4 }, { type: "adult" }],
    weight: 1.5,
    part: "midday",
    place: "gathering",
    activity: "visit",
    minutes: 45,
    text: "Put off the afternoon's work and sit in the sun.",
    sources: [],
    fallback: true,
  },
  {
    id: "day.linger",
    label: "Staying for the talk",
    scope: { years: ALL },
    evidence: "inferred",
    when: [{ type: "trait", key: "extraversion", above: 62 }, { type: "chance", p: 0.5 }],
    weight: 1.5,
    part: "evening",
    place: "gathering",
    activity: "visit",
    minutes: 45,
    text: "Stay out late for the talk, whoever is there.",
    sources: [],
    fallback: true,
  },
  {
    id: "day.debt",
    label: "Collecting a debt",
    scope: { years: ALL },
    evidence: "inferred",
    when: [{ type: "adult" }, { type: "chance", p: 0.1 }],
    weight: 2,
    part: "midday",
    place: "door",
    activity: "visit",
    minutes: 20,
    text: "Go and ask for what a neighbour has owed you since the last season.",
    sources: [],
    fallback: true,
  },
  {
    id: "day.toothache",
    label: "A toothache",
    scope: { years: ALL },
    evidence: "inferred",
    when: [{ type: "adult" }, { type: "chance", p: 0.04 }],
    weight: 5,
    part: "morning",
    place: "market",
    activity: "visit",
    minutes: 30,
    text: "Find someone to see to an aching tooth.",
    sources: [],
    fallback: true,
  },
  {
    id: "day.bathe",
    label: "Bathing in the heat",
    scope: { years: ALL },
    evidence: "inferred",
    when: [{ type: "season", any: ["summer"] }, { type: "chance", p: 0.35 }],
    weight: 1.5,
    part: "evening",
    place: "wild",
    activity: "draw-water",
    minutes: 30,
    text: "Wash off the day's heat at the water.",
    sources: [],
    fallback: true,
  },
];
