import type { Festival, Occasion } from "./types";

type Bounds = [number, number, number, number];
const IE = ["inner-eurasian" as const];

const RUSSIAN_PLAIN_PALAEO = { years: [-25000, -12000] as [number, number], bounds: [25, 44, 60, 58] as Bounds };
const BOTAI = { years: [-3700, -3000] as [number, number], bounds: [60, 48, 75, 56] as Bounds };
const YAMNAYA = { years: [-3300, -2600] as [number, number], bounds: [28, 43, 60, 55] as Bounds };
const SINTASHTA = { years: [-2100, -1750] as [number, number], bounds: [55, 48, 66, 56] as Bounds };
const SCYTHIAN = { years: [-750, -250] as [number, number], bounds: [25, 42, 60, 55] as Bounds, cultures: IE };
const IRON_STEPPE = { years: [-750, 500] as [number, number], bounds: [25, 38, 110, 56] as Bounds, cultures: IE };
const XIONGNU = { years: [-209, 100] as [number, number], bounds: [90, 38, 125, 54] as Bounds, cultures: IE };
const SOGDIAN = { years: [300, 1000] as [number, number], bounds: [60, 35, 105, 45] as Bounds, cultures: IE };
const TURKIC = { years: [552, 850] as [number, number], bounds: [70, 40, 125, 55] as Bounds, cultures: IE };
const UYGHUR_KHAGANATE = { years: [762, 840] as [number, number], bounds: [95, 44, 110, 52] as Bounds, cultures: IE };
const LIAO = { years: [907, 1125] as [number, number], bounds: [110, 38, 128, 50] as Bounds, cultures: ["inner-eurasian" as const, "east-asian" as const] };
const MONGOLIA = { years: [1200, 1950] as [number, number], bounds: [87, 41, 120, 53] as Bounds, cultures: IE };
const MONGOL_EMPIRE = { years: [1206, 1370] as [number, number], bounds: [55, 36, 125, 56] as Bounds, cultures: IE };
const TURKESTAN = { years: [900, 1920] as [number, number], bounds: [55, 36, 75, 44] as Bounds, cultures: IE };
const BUKHARA = { years: [1500, 1920] as [number, number], bounds: [62, 38, 66, 41] as Bounds, cultures: IE };
const TIBET = { years: [1000, 1950] as [number, number], bounds: [78, 27, 103, 37] as Bounds, cultures: IE };
const SIBERIA = { years: [1000, 1950] as [number, number], bounds: [60, 50, 180, 75] as Bounds, cultures: IE };
const OB_UGRIC = { years: [1600, 1950] as [number, number], bounds: [60, 58, 80, 67] as Bounds, cultures: IE };
const FUR_FRONTIER = { years: [1600, 1950] as [number, number], bounds: [60, 50, 180, 72] as Bounds, cultures: ["inner-eurasian" as const, "european" as const] };
const RUSSIAN = { years: [1450, 1918] as [number, number], bounds: [27, 45, 180, 70] as Bounds, cultures: ["european" as const] };
const KAZAKH_KYRGYZ = { years: [1450, 1930] as [number, number], bounds: [46, 39, 87, 55] as Bounds, cultures: IE };
const SOVIET = { years: [1920, 1950] as [number, number], bounds: [30, 36, 180, 72] as Bounds, cultures: ["inner-eurasian" as const, "european" as const] };

export const innerEurasiaOccasions: Occasion[] = [
  {
    id: "day.palaeo.mammoth-bones",
    label: "Mending the mammoth-bone house",
    scope: RUSSIAN_PLAIN_PALAEO,
    evidence: "documented",
    when: [{ type: "adult" }, { type: "chance", p: 0.25 }],
    weight: 5,
    part: "midday",
    place: "home",
    activity: "work",
    minutes: 50,
    text: "Wedge fresh mammoth jaws, chin down, into the base of the house wall.",
    note: "One Mezhyrich hut used some 95 mammoth mandibles stacked in a herringbone ring.",
    sources: ["https://en.wikipedia.org/wiki/Mezhyrich"],
    serves: ["household-home"],
  },
  {
    id: "day.palaeo.bone-drum",
    label: "Beating the painted bones",
    scope: RUSSIAN_PLAIN_PALAEO,
    evidence: "hypothesis",
    when: [{ type: "observance", levels: ["devout", "regular"] }, { type: "chance", p: 0.3 }],
    weight: 4,
    part: "evening",
    place: "hearth",
    activity: "warm",
    minutes: 35,
    text: "Beat the ochre-painted mammoth shoulder blade by the fire while the others sing.",
    note: "Bibikov read the red-painted mammoth bones from Mezin as a set of percussion instruments.",
    sources: ["https://en.wikipedia.org/wiki/Mezine_(archaeological_site)"],
  },
  {
    id: "day.botai.mare-milk",
    label: "Milking the mares",
    scope: BOTAI,
    evidence: "documented",
    when: [{ type: "season", any: ["spring", "summer"] }, { type: "chance", p: 0.4 }],
    weight: 6,
    part: "morning",
    place: "work",
    activity: "tend",
    minutes: 40,
    carry: "vessel",
    text: "Milk the tethered mares and set the milk to sour in a clay pot.",
    note: "Mare's-milk fats were found in Botai potsherds, among the earliest evidence of horse keeping.",
    sources: ["https://en.wikipedia.org/wiki/Botai_culture"],
  },
  {
    id: "day.yamnaya.kurgan-feast",
    label: "Feasting on the kurgan",
    scope: YAMNAYA,
    evidence: "hypothesis",
    when: [{ type: "anniversary", kind: "died" }],
    weight: 14,
    part: "evening",
    place: "edge",
    activity: "visit",
    minutes: 60,
    carry: "vessel",
    text: "Pour milk and share meat on the kurgan of your {dead}, {years} years under the earth.",
    note: "Animal bones and broken pots at kurgan edges point to feasts at the mound; recurring ones are our guess.",
    sources: ["https://en.wikipedia.org/wiki/Yamnaya_culture"],
    serves: ["remember-dead"],
  },
  {
    id: "day.sintashta.chariot",
    label: "Bending chariot spokes",
    scope: SINTASHTA,
    evidence: "documented",
    when: [{ type: "work", match: /horse|chariot|wheel|wright|carpent|wood/i }, { type: "chance", p: 0.4 }],
    weight: 7,
    part: "midday",
    place: "work",
    activity: "work",
    minutes: 60,
    text: "Bend steamed birch into spokes for a new chariot wheel.",
    note: "Sintashta graves hold the oldest known spoke-wheeled chariots, buried with their horses.",
    sources: ["https://en.wikipedia.org/wiki/Sintashta_culture"],
    serves: ["mastery"],
  },
  {
    id: "day.scythia.oath",
    label: "A Scythian oath",
    scope: SCYTHIAN,
    evidence: "documented",
    when: [{ type: "kin", kind: "friend" }, { type: "sex", is: "male" }, { type: "chance", p: 0.06 }],
    weight: 6,
    part: "evening",
    place: { kin: "friend" },
    activity: "visit",
    minutes: 30,
    text: "Swear brotherhood with {friend}: blood in the wine, arrows dipped, both of you drinking.",
    note: "Herodotus 4.70: they dip a sword, arrows, an axe and a javelin in the cup before drinking.",
    sources: ["https://en.wikipedia.org/wiki/Scythians"],
  },
  {
    id: "day.scythia.hemp",
    label: "The hemp tent",
    scope: IRON_STEPPE,
    evidence: "documented",
    when: [{ type: "adult" }, { type: "chance", p: 0.08 }],
    weight: 5,
    part: "evening",
    place: "home",
    activity: "rest",
    minutes: 45,
    text: "Throw hemp seed on the red-hot stones inside the closed felt tent.",
    note: "Herodotus describes it after a funeral; Pazyryk burials held braziers with charred hemp seed.",
    sources: ["https://en.wikipedia.org/wiki/Pazyryk_burials", "https://en.wikipedia.org/wiki/Scythians"],
  },
  {
    id: "day.steppe.tamga",
    label: "Branding the tamga",
    scope: IRON_STEPPE,
    evidence: "inferred",
    when: [{ type: "season", any: ["spring"] }, { type: "work", match: /horse|herd|groom|stable/i }],
    weight: 6,
    part: "morning",
    place: "work",
    activity: "tend",
    minutes: 45,
    text: "Burn your clan's tamga into the flanks of this year's colts.",
    note: "Sarmatian tamgas survive on stones, mirrors and horse gear; branding with them is widely assumed.",
    sources: ["https://en.wikipedia.org/wiki/Tamga"],
  },
  {
    id: "day.xiongnu.sun",
    label: "Bowing to the sun",
    scope: XIONGNU,
    evidence: "documented",
    when: [{ type: "observance", levels: ["devout", "regular"] }],
    weight: 5,
    part: "morning",
    place: "home",
    activity: "visit",
    minutes: 10,
    text: "Bow to the rising sun at the tent door, as the chanyu does.",
    note: "Sima Qian: the chanyu goes out each morning to salute the sun, and each evening the moon.",
    sources: ["https://en.wikipedia.org/wiki/Xiongnu"],
  },
  {
    id: "day.sogdian.letter",
    label: "Letter home by caravan",
    scope: SOGDIAN,
    evidence: "documented",
    when: [{ type: "kin", kind: "parent" }, { type: "work", match: /merchant|trad|caravan|camel|pedl/i }, { type: "chance", p: 0.2 }],
    weight: 6,
    part: "evening",
    place: "home",
    activity: "rest",
    minutes: 30,
    text: "Dictate a letter to {parent} in Samarkand, for the next caravan going west.",
    note: "The Sogdian Ancient Letters, lost in the post near Dunhuang around 313, include one from a stranded wife to her mother.",
    sources: ["https://en.wikipedia.org/wiki/Sogdian_Ancient_Letters"],
    serves: ["elder-kin"],
  },
  {
    id: "day.sogdian.fire-temple",
    label: "Sandalwood for the fire",
    scope: SOGDIAN,
    evidence: "documented",
    when: [{ type: "observance", levels: ["devout", "regular"] }, { type: "chance", p: 0.3 }],
    weight: 5,
    part: "morning",
    place: "sanctuary",
    activity: "visit",
    minutes: 25,
    carry: "bundle",
    text: "Bring sandalwood to the fire temple, where the priests veil their mouths before the flame.",
    note: "Panjikent had two temples in its town centre; priests wore a mouth veil to keep the fire pure.",
    sources: ["https://en.wikipedia.org/wiki/Panjakent"],
  },
  {
    id: "day.sogdian.reckon",
    label: "Teaching a boy to reckon",
    scope: SOGDIAN,
    evidence: "documented",
    when: [{ type: "kin", kind: "child", minAge: 5, maxAge: 14 }, { type: "work", match: /merchant|trad|caravan|shop|pedl/i }],
    weight: 5,
    part: "evening",
    place: "home",
    activity: "play",
    minutes: 30,
    text: "Teach {child} to reckon weights and coin: every Sogdian learns trade young.",
    note: "Tang writers say Sogdians put honey on a newborn's tongue for sweet words, and sent sons to trade at twenty.",
    sources: ["https://en.wikipedia.org/wiki/Sogdia"],
    serves: ["child-future", "raise-kin"],
  },
  {
    id: "day.turk.kurultai",
    label: "Riding to the kurultai",
    scope: TURKIC,
    evidence: "inferred",
    when: [{ type: "rank", any: ["gentry", "elite"] }, { type: "sex", is: "male" }, { type: "chance", p: 0.1 }],
    weight: 6,
    part: "midday",
    place: "gathering",
    activity: "visit",
    minutes: 90,
    text: "Ride to the kurultai, where the begs will speak for or against the next campaign.",
    sources: ["https://en.wikipedia.org/wiki/Kurultai", "https://en.wikipedia.org/wiki/G%C3%B6kturks"],
  },
  {
    id: "day.turk.smith",
    label: "Forging arrowheads",
    scope: TURKIC,
    evidence: "documented",
    when: [{ type: "work", match: /smith|iron|metal|forge|armou?r/i }, { type: "chance", p: 0.4 }],
    weight: 6,
    part: "midday",
    place: "work",
    activity: "work",
    minutes: 60,
    text: "Hammer out iron arrowheads, the work your people once did as smiths for the Rouran.",
    note: "Chinese annals call the early Türks the Rouran khagan's ironworkers in the Altai.",
    sources: ["https://en.wikipedia.org/wiki/Ashina_tribe"],
    serves: ["mastery"],
  },
  {
    id: "day.turk.balbal",
    label: "A balbal for the dead",
    scope: TURKIC,
    evidence: "inferred",
    when: [{ type: "anniversary", kind: "died" }],
    weight: 14,
    part: "midday",
    place: "edge",
    activity: "visit",
    minutes: 50,
    text: "Ride out to the stone enclosure of your {dead} and set the balbal stones straight.",
    note: "Rows of balbals, each said to stand for an enemy the dead man killed, line Türk memorial enclosures.",
    sources: ["https://en.wikipedia.org/wiki/Balbal"],
    serves: ["remember-dead"],
  },
  {
    id: "day.uyghur.elect",
    label: "Alms for the Elect",
    scope: UYGHUR_KHAGANATE,
    evidence: "documented",
    when: [{ type: "observance", levels: ["devout", "regular"] }, { type: "chance", p: 0.3 }],
    weight: 5,
    part: "midday",
    place: "sanctuary",
    activity: "visit",
    minutes: 30,
    carry: "basket",
    text: "Carry melons and bread to the Manichaean Elect, who may not pick them themselves.",
    note: "Bögü Qaghan made Manichaeism the khaganate's religion in 762; the Elect ate the light held in fruit.",
    sources: ["https://en.wikipedia.org/wiki/Uyghur_Khaganate", "https://en.wikipedia.org/wiki/Manichaeism"],
  },
  {
    id: "day.khitan.willows",
    label: "Shooting the willows",
    scope: LIAO,
    evidence: "documented",
    when: [{ type: "date", dayOfYear: 157 }, { type: "sex", is: "male" }, { type: "adult" }],
    weight: 14,
    part: "midday",
    place: "edge",
    activity: "visit",
    minutes: 60,
    text: "Shoot from the saddle at a peeled willow branch, praying for rain.",
    note: "The Liao history records the sheliu rite; the day here stands in for the fifth lunar month.",
    sources: ["https://en.wikipedia.org/wiki/Liao_dynasty"],
  },
  {
    id: "day.mongol.kumis",
    label: "Churning the kumis",
    scope: MONGOLIA,
    evidence: "documented",
    when: [{ type: "season", any: ["summer"] }, { type: "chance", p: 0.4 }],
    weight: 5,
    part: "morning",
    place: "home",
    activity: "cook",
    minutes: 40,
    carry: "vessel",
    text: "Churn the mare's milk in the hide bag by the door, a thousand strokes.",
    note: "William of Rubruck describes kumis beaten in a great skin until it bubbles and turns sharp.",
    sources: ["https://en.wikipedia.org/wiki/Kumis"],
  },
  {
    id: "day.mongol.ovoo",
    label: "Round the ovoo",
    scope: MONGOLIA,
    evidence: "documented",
    when: [{ type: "chance", p: 0.2 }],
    weight: 4,
    part: "morning",
    place: "edge",
    activity: "visit",
    minutes: 25,
    text: "Walk three times sunwise round the ovoo and add a stone and a splash of milk.",
    sources: ["https://en.wikipedia.org/wiki/Ovoo"],
  },
  {
    id: "day.mongol.yam",
    label: "Sending a courier",
    scope: MONGOL_EMPIRE,
    evidence: "documented",
    when: [{ type: "rank", any: ["gentry", "elite"] }, { type: "chance", p: 0.15 }],
    weight: 5,
    part: "morning",
    place: "edge",
    activity: "visit",
    minutes: 20,
    text: "Send a rider with a paiza down the yam road with word for the khan's camp.",
    note: "Relay stations a day's ride apart kept fresh horses for anyone showing the tablet.",
    sources: ["https://en.wikipedia.org/wiki/Yam_(route)", "https://en.wikipedia.org/wiki/Paiza"],
  },
  {
    id: "day.mongol.relay",
    label: "Riding the relay",
    scope: MONGOL_EMPIRE,
    evidence: "documented",
    when: [{ type: "work", match: /courier|messeng|rider|post|relay|horse/i }, { type: "chance", p: 0.3 }],
    weight: 6,
    part: "midday",
    place: "edge",
    activity: "visit",
    minutes: 40,
    text: "Show the paiza at the yam station for a fresh horse.",
    sources: ["https://en.wikipedia.org/wiki/Yam_(route)"],
  },
  {
    id: "day.turkestan.madrasa",
    label: "Lessons in the madrasa",
    scope: TURKESTAN,
    evidence: "documented",
    when: [{ type: "work", match: /scholar|student|teach|scribe|mullah|imam|qadi|clerk/i }],
    weight: 5,
    part: "morning",
    place: "sanctuary",
    activity: "visit",
    minutes: 60,
    text: "Recite your lesson to the mudarris in the madrasa courtyard.",
    note: "Ulugh Beg's madrasa in Samarkand taught astronomy and mathematics beside law.",
    sources: ["https://en.wikipedia.org/wiki/Ulugh_Beg_Madrasa,_Samarkand"],
    serves: ["mastery"],
  },
  {
    id: "day.turkestan.chaikhana",
    label: "The tea house",
    scope: { years: [1600, 1950] as [number, number], bounds: [55, 36, 80, 44] as Bounds, cultures: IE },
    evidence: "documented",
    when: [{ type: "sex", is: "male" }, { type: "trait", key: "extraversion", above: 45 }, { type: "adult" }],
    weight: 5,
    part: "evening",
    place: { venue: "coffee-house" },
    activity: "visit",
    minutes: 60,
    text: "Sit cross-legged on the chaikhana platform over green tea and the news off the road.",
    sources: ["https://en.wikipedia.org/wiki/Chaikhana"],
  },
  {
    id: "day.bukhara.hauz",
    label: "Water from the hauz",
    scope: BUKHARA,
    evidence: "documented",
    when: [{ type: "adult" }, { type: "chance", p: 0.35 }],
    weight: 4,
    part: "morning",
    place: "well",
    activity: "draw-water",
    minutes: 20,
    carry: "vessel",
    text: "Draw water from the neighbourhood hauz before the sun warms it.",
    note: "Bukhara's standing pools spread the guinea worm, rishta, until the Soviets drained them.",
    sources: ["https://en.wikipedia.org/wiki/Lyab-i_Hauz"],
  },
  {
    id: "day.bukhara.trading-dome",
    label: "Under the trading domes",
    scope: BUKHARA,
    evidence: "documented",
    when: [{ type: "rank", any: ["middling", "gentry"] }, { type: "chance", p: 0.25 }],
    weight: 4,
    part: "midday",
    place: "market",
    activity: "visit",
    minutes: 45,
    carry: "bundle",
    text: "Haggle over Kashmir shawls under the domed crossing of the jewellers' bazaar.",
    note: "Bukhara's sixteenth-century trading domes, Toqi Zargaron among them, still stand.",
    sources: ["https://en.wikipedia.org/wiki/Bukhara"],
  },
  {
    id: "day.turkestan.mazar",
    label: "At the saint's mazar",
    scope: TURKESTAN,
    evidence: "documented",
    when: [{ type: "observance", levels: ["devout", "regular"] }, { type: "chance", p: 0.15 }],
    weight: 5,
    part: "midday",
    place: "sanctuary",
    activity: "visit",
    minutes: 40,
    text: "Fasten a strip of cloth to the tree over the saint's mazar, praying for a child.",
    note: "Rag-hung trees and sheep sacrifice at saints' tombs were common across Turkestan.",
    sources: ["https://en.wikipedia.org/wiki/Mazar_(mausoleum)"],
    serves: ["raise-kin"],
  },
  {
    id: "day.tibet.butter-lamp",
    label: "Filling the butter lamps",
    scope: TIBET,
    evidence: "documented",
    when: [{ type: "observance", levels: ["devout", "regular"] }],
    weight: 5,
    part: "morning",
    place: "home",
    activity: "tend",
    minutes: 15,
    text: "Fill the butter lamps on the household altar before the morning tea.",
    sources: ["https://en.wikipedia.org/wiki/Butter_lamp"],
  },
  {
    id: "day.tibet.prayer-flags",
    label: "New prayer flags",
    scope: TIBET,
    evidence: "documented",
    when: [{ type: "chance", p: 0.15 }],
    weight: 4,
    part: "morning",
    place: "home",
    activity: "work",
    minutes: 25,
    text: "Hang new wind-horse flags on the roof so the wind carries their prayers.",
    sources: ["https://en.wikipedia.org/wiki/Prayer_flag"],
  },
  {
    id: "day.tibet.kora",
    label: "Walking the kora",
    scope: TIBET,
    evidence: "documented",
    when: [{ type: "observance", levels: ["devout", "regular"] }, { type: "chance", p: 0.35 }],
    weight: 5,
    part: "evening",
    place: "sanctuary",
    activity: "visit",
    minutes: 45,
    text: "Walk the kora clockwise round the temple, turning every prayer wheel on the way.",
    sources: ["https://en.wikipedia.org/wiki/Kora_(pilgrimage)"],
  },
  {
    id: "day.tibet.bon-kora",
    label: "The Bon circuit",
    scope: TIBET,
    evidence: "documented",
    when: [{ type: "tag", any: ["traditionalist"] }, { type: "chance", p: 0.2 }],
    weight: 4,
    part: "evening",
    place: "sanctuary",
    activity: "visit",
    minutes: 45,
    text: "Walk the circuit anticlockwise, as the Bon faithful do, and bow to Tonpa Shenrab.",
    sources: ["https://en.wikipedia.org/wiki/Bon"],
  },
  {
    id: "day.tibet.sky-burial",
    label: "Juniper for the dead",
    scope: TIBET,
    evidence: "inferred",
    when: [{ type: "anniversary", kind: "died" }],
    weight: 14,
    part: "morning",
    place: "sanctuary",
    activity: "visit",
    minutes: 40,
    carry: "bundle",
    text: "Burn juniper and offer lamps for your {dead}, given to the vultures {years} years ago.",
    note: "Sky burial is documented from at least the twelfth century; a yearly rite for the dead is our extrapolation.",
    sources: ["https://en.wikipedia.org/wiki/Sky_burial"],
    serves: ["remember-dead"],
  },
  {
    id: "day.tibet.yak-wool",
    label: "Combing the yaks",
    scope: TIBET,
    evidence: "documented",
    when: [{ type: "season", any: ["spring"] }, { type: "work", match: /herd|yak|drok|nomad/i }],
    weight: 6,
    part: "morning",
    place: "work",
    activity: "tend",
    minutes: 50,
    carry: "basket",
    text: "Comb the soft winter down from the yaks before they shed it on the grass.",
    sources: ["https://en.wikipedia.org/wiki/Domestic_yak"],
  },
  {
    id: "day.siberia.reindeer",
    label: "Harnessing the reindeer",
    scope: { years: [1000, 1950] as [number, number], bounds: [60, 58, 180, 75] as Bounds, cultures: IE },
    evidence: "documented",
    when: [{ type: "season", any: ["winter", "autumn"] }, { type: "work", match: /reindeer|herd|nomad/i }],
    weight: 6,
    part: "morning",
    place: "work",
    activity: "tend",
    minutes: 45,
    text: "Lasso the draught reindeer from the herd for the sledges.",
    sources: ["https://en.wikipedia.org/wiki/Reindeer_herding", "https://en.wikipedia.org/wiki/Nenets_people"],
  },
  {
    id: "day.siberia.bear-feast",
    label: "Singing to the bear",
    scope: OB_UGRIC,
    evidence: "documented",
    when: [{ type: "season", any: ["winter"] }, { type: "adult" }, { type: "chance", p: 0.15 }],
    weight: 6,
    part: "evening",
    place: "gathering",
    activity: "visit",
    minutes: 90,
    text: "Sing to the bear's head at the bear feast, begging its pardon for the killing.",
    note: "Khanty and Mansi bear feasts ran for nights of songs and masked plays before the guest was sent home.",
    sources: ["https://en.wikipedia.org/wiki/Bear_Festival", "https://en.wikipedia.org/wiki/Khanty"],
  },
  {
    id: "day.siberia.kamlanie",
    label: "The shaman's night",
    scope: SIBERIA,
    evidence: "documented",
    when: [{ type: "observance", levels: ["devout", "regular"] }, { type: "chance", p: 0.08 }],
    weight: 6,
    part: "evening",
    place: "door",
    activity: "warm",
    minutes: 120,
    text: "Sit up through the night while the shaman drums, travelling to find a sick soul.",
    note: "The Altaic and Evenki kamlanie was a public séance, and neighbours filled the tent to watch.",
    sources: ["https://en.wikipedia.org/wiki/Siberian_shamanism"],
  },
  {
    id: "day.siberia.trapline",
    label: "Walking the trapline",
    scope: FUR_FRONTIER,
    evidence: "documented",
    when: [{ type: "season", any: ["winter"] }, { type: "work", match: /trap|hunt|fur|sable/i }],
    weight: 7,
    part: "morning",
    place: "wild",
    activity: "gather",
    minutes: 90,
    text: "Walk your sable trapline on skis, resetting the deadfalls.",
    note: "Sable pelts paid the yasak, the fur tribute the tsars levied on Siberian men.",
    sources: ["https://en.wikipedia.org/wiki/Yasak"],
  },
  {
    id: "day.russia.banya",
    label: "Saturday banya",
    scope: RUSSIAN,
    evidence: "documented",
    when: [{ type: "cycle", every: 7, on: 3 }, { type: "adult" }],
    weight: 8,
    part: "evening",
    place: "home",
    activity: "rest",
    minutes: 60,
    text: "Heat the banya for a steam and a birch switching: it is Saturday.",
    sources: ["https://en.wikipedia.org/wiki/Banya_(sauna)"],
  },
  {
    id: "day.russia.icon-corner",
    label: "The beautiful corner",
    scope: RUSSIAN,
    evidence: "documented",
    when: [{ type: "observance", levels: ["devout", "regular"] }],
    weight: 4,
    part: "morning",
    place: "home",
    activity: "visit",
    minutes: 10,
    text: "Bow before the icons in the beautiful corner, crossing yourself as the lamp flickers.",
    sources: ["https://en.wikipedia.org/wiki/Icon_corner"],
  },
  {
    id: "day.russia.name-day",
    label: "Name day",
    scope: RUSSIAN,
    evidence: "documented",
    when: [{ type: "anniversary", kind: "born-self" }],
    weight: 14,
    part: "evening",
    place: "home",
    activity: "cook",
    minutes: 50,
    text: "Bake the name-day pie and light a candle to your name saint.",
    note: "Russians kept the saint's day of their baptismal name rather than their birthday; here the two stand in for each other.",
    sources: ["https://en.wikipedia.org/wiki/Name_day"],
  },
  {
    id: "day.steppe.migration",
    label: "Moving to the jailau",
    scope: KAZAKH_KYRGYZ,
    evidence: "documented",
    when: [{ type: "season", any: ["spring"] }, { type: "work", match: /herd|horse|sheep|shep|camel|nomad/i }, { type: "chance", p: 0.35 }],
    weight: 7,
    part: "morning",
    place: "home",
    activity: "haul",
    minutes: 70,
    carry: "bundle",
    text: "Load the yurt lattice and felts onto the camels for the move to the jailau.",
    sources: ["https://en.wikipedia.org/wiki/Jailoo"],
  },
  {
    id: "day.steppe.beshbarmak",
    label: "A sheep for the guests",
    scope: KAZAKH_KYRGYZ,
    evidence: "documented",
    when: [{ type: "adult" }, { type: "fortune", above: 0.4 }, { type: "chance", p: 0.12 }],
    weight: 5,
    part: "evening",
    place: "hearth",
    activity: "cook",
    minutes: 70,
    text: "Boil a sheep for beshbarmak, its head kept for the eldest guest.",
    sources: ["https://en.wikipedia.org/wiki/Beshbarmak"],
    serves: ["household-home"],
  },
  {
    id: "day.steppe.aytys",
    label: "An aytys contest",
    scope: KAZAKH_KYRGYZ,
    evidence: "documented",
    when: [{ type: "trait", key: "extraversion", above: 55 }, { type: "chance", p: 0.12 }],
    weight: 5,
    part: "evening",
    place: "gathering",
    activity: "visit",
    minutes: 60,
    text: "Answer a rival akyn verse for verse in the aytys, dombra on your knee.",
    sources: ["https://en.wikipedia.org/wiki/Aytys"],
  },
  {
    id: "day.steppe.felt",
    label: "Rolling felt",
    scope: KAZAKH_KYRGYZ,
    evidence: "documented",
    when: [{ type: "season", any: ["summer", "autumn"] }, { type: "work", match: /felt|wool|weav|spin|carpet/i }],
    weight: 7,
    part: "midday",
    place: "work",
    activity: "work",
    minutes: 70,
    text: "Roll the wet wool in a reed mat, back and forth, until it fulls into felt.",
    note: "Kyrgyz shyrdak and ala-kiyiz felts are still made this way, sometimes dragged behind a horse.",
    sources: ["https://en.wikipedia.org/wiki/Shyrdak"],
    serves: ["mastery"],
  },
  {
    id: "day.steppe.caravan",
    label: "Counting camel loads",
    scope: { years: [1740, 1900] as [number, number], bounds: [50, 38, 70, 53] as Bounds, cultures: IE },
    evidence: "documented",
    when: [{ type: "work", match: /caravan|camel|merchant|trad/i }, { type: "chance", p: 0.3 }],
    weight: 6,
    part: "morning",
    place: "edge",
    activity: "haul",
    minutes: 50,
    carry: "bundle",
    text: "Count the camel loads of cotton for the caravan to Orenburg.",
    note: "Orenburg's exchange yard was the main door of Bukhara's trade with Russia.",
    sources: ["https://en.wikipedia.org/wiki/Orenburg"],
  },
  {
    id: "day.steppe.eagle",
    label: "Hunting with the eagle",
    scope: { years: [1450, 1950] as [number, number], bounds: [46, 39, 100, 55] as Bounds, cultures: IE },
    evidence: "documented",
    when: [{ type: "season", any: ["winter"] }, { type: "work", match: /falcon|eagle|hunt|trap/i }],
    weight: 7,
    part: "morning",
    place: "wild",
    activity: "gather",
    minutes: 90,
    text: "Carry the hooded golden eagle up the ridge to fly at foxes.",
    sources: ["https://en.wikipedia.org/wiki/Berkutchi"],
  },
  {
    id: "day.soviet.labour-days",
    label: "Labour-days in the book",
    scope: { years: [1930, 1950] as [number, number], bounds: SOVIET.bounds, cultures: SOVIET.cultures },
    evidence: "documented",
    when: [{ type: "work", match: /farm|field|herd|milk|sow|plough|reap|kolkhoz|shep/i }, { type: "chance", p: 0.35 }],
    weight: 6,
    part: "evening",
    place: "gathering",
    activity: "visit",
    minutes: 20,
    text: "Get your labour-days marked in the brigade book, arguing if they are short.",
    note: "Kolkhoz members were paid by the trudoden, a unit shared out of whatever was left after state deliveries.",
    sources: ["https://en.wikipedia.org/wiki/Trudoden"],
  },
  {
    id: "day.soviet.club",
    label: "An evening at the club",
    scope: SOVIET,
    evidence: "documented",
    when: [{ type: "trait", key: "openness", above: 45 }, { type: "adult" }, { type: "chance", p: 0.2 }],
    weight: 4,
    part: "evening",
    place: "gathering",
    activity: "visit",
    minutes: 90,
    text: "Go to the club for the film and sit through the lecture before it.",
    sources: ["https://en.wikipedia.org/wiki/Workers%27_club"],
  },
];

export const innerEurasiaFestivals: Festival[] = [
  {
    id: "fest.xiongnu.longcheng",
    label: "the Longcheng assembly",
    scope: XIONGNU,
    evidence: "documented",
    date: { dayOfYear: 160 },
    rest: false,
    place: "sanctuary",
    minutes: 90,
    text: "It is the fifth month: the chiefs gather at Longcheng to sacrifice to their ancestors, Heaven and Earth.",
    sources: ["https://en.wikipedia.org/wiki/Longcheng"],
  },
  {
    id: "fest.xiongnu.dailin",
    label: "the Dailin count",
    scope: XIONGNU,
    evidence: "documented",
    date: { dayOfYear: 270 },
    rest: false,
    place: "gathering",
    minutes: 90,
    text: "It is autumn and the horses are fat: people and herds are counted at the forest assembly.",
    sources: ["https://en.wikipedia.org/wiki/Xiongnu"],
  },
  {
    id: "fest.scythia.bowl",
    label: "the district bowl",
    scope: SCYTHIAN,
    evidence: "documented",
    date: { dayOfYear: 280 },
    rest: false,
    place: "gathering",
    minutes: 60,
    text: "It is the governor's yearly bowl: only men who have killed an enemy may drink from it.",
    note: "Herodotus 4.66; the day of the year is our choice.",
    sources: ["https://en.wikipedia.org/wiki/Scythians"],
  },
  {
    id: "fest.turkestan.nowruz",
    label: "Nowruz",
    scope: { years: [900, 1926] as [number, number], bounds: [46, 35, 87, 55] as Bounds, cultures: IE },
    evidence: "documented",
    date: { dayOfYear: 80 },
    rest: true,
    place: "gathering",
    minutes: 120,
    text: "It is Nowruz, the spring equinox: sumalak stirred all night, new clothes, visits and games.",
    sources: ["https://en.wikipedia.org/wiki/Nowruz", "https://en.wikipedia.org/wiki/Samanu"],
  },
  {
    id: "fest.mongol.tsagaan-sar",
    label: "Tsagaan Sar",
    scope: MONGOLIA,
    evidence: "documented",
    date: { dayOfYear: 40 },
    rest: true,
    place: "hearth",
    minutes: 120,
    text: "It is Tsagaan Sar, the White Month: greet your elders arm under arm and eat buuz till evening.",
    note: "A lunar new year that falls from late January to early March; the day here is representative.",
    sources: ["https://en.wikipedia.org/wiki/Tsagaan_Sar"],
  },
  {
    id: "fest.mongol.naadam",
    label: "the Naadam",
    scope: MONGOLIA,
    evidence: "documented",
    date: { dayOfYear: 192 },
    rest: false,
    place: "gathering",
    minutes: 150,
    text: "It is the Naadam: wrestling, archery and the children's horse race across the steppe.",
    note: "Fixed on 11 July only after 1921; before that, naadams followed summer ovoo rites.",
    sources: ["https://en.wikipedia.org/wiki/Naadam"],
  },
  {
    id: "fest.tibet.losar",
    label: "Losar",
    scope: TIBET,
    evidence: "documented",
    date: { dayOfYear: 45 },
    rest: true,
    place: "sanctuary",
    minutes: 120,
    text: "It is Losar, the Tibetan new year: offerings at the monastery, then chang and khapse at home.",
    note: "A lunar new year, usually February; the day here is representative.",
    sources: ["https://en.wikipedia.org/wiki/Losar"],
  },
  {
    id: "fest.russia.maslenitsa",
    label: "Maslenitsa",
    scope: RUSSIAN,
    evidence: "documented",
    date: { dayOfYear: 55 },
    rest: false,
    place: "gathering",
    minutes: 90,
    text: "It is Butter Week before Lent: bliny, sledging, fist-fights on the ice and a straw figure burned.",
    note: "Moveable with Easter; the day here is representative.",
    sources: ["https://en.wikipedia.org/wiki/Maslenitsa"],
  },
  {
    id: "fest.siberia.sunday",
    label: "Sunday",
    scope: { years: [1600, 1918] as [number, number], bounds: [45, 48, 180, 72] as Bounds, cultures: ["european"] },
    evidence: "documented",
    date: { every: 7, on: 4 },
    rest: true,
    place: "sanctuary",
    minutes: 90,
    text: "It is Sunday: go to the liturgy in the ostrog church, and keep the day from work.",
    sources: ["https://en.wikipedia.org/wiki/Divine_Liturgy"],
  },
  {
    id: "fest.soviet.may-day",
    label: "May Day",
    scope: SOVIET,
    evidence: "documented",
    date: { dayOfYear: 121 },
    rest: true,
    place: "gathering",
    minutes: 120,
    text: "It is May Day, the workers' holiday: march under red banners to the speeches.",
    sources: ["https://en.wikipedia.org/wiki/International_Workers%27_Day"],
  },
];
