import type { Festival, Occasion } from "./types";

type Box = [number, number, number, number];
const MESO: Box = [-106, 12, -84, 24];
const MAYA: Box = [-94, 13, -86, 22];
const YUCATAN: Box = [-91, 17.5, -86.5, 22];
const MAYA_HIGHLAND: Box = [-92.5, 14, -90, 15.8];
const BASIN: Box = [-100, 18.5, -98, 20.5];
const OAXACA: Box = [-99, 15, -95, 18.5];
const ANDES: Box = [-82, -25, -62, 2];
const NORTH_COAST: Box = [-81, -10, -77.5, -5];
const CUSCO: Box = [-73.5, -15, -70.5, -12.5];

const MESO_ARCHAIC = { years: [-8000, -1600] as [number, number], bounds: MESO, cultures: ["mesoamerican" as const] };
const OLMEC = { years: [-1600, -400] as [number, number], bounds: [-96, 17, -93, 19] as Box, cultures: ["mesoamerican" as const] };
const ZAPOTEC = { years: [-500, 1000] as [number, number], bounds: OAXACA, cultures: ["mesoamerican" as const] };
const TEOTIHUACAN = { years: [50, 650] as [number, number], bounds: BASIN, cultures: ["mesoamerican" as const] };
const TOLTEC = { years: [900, 1200] as [number, number], bounds: [-100.5, 19, -98.5, 21] as Box, cultures: ["mesoamerican" as const] };
const MAYA_CLASSIC = { years: [250, 950] as [number, number], bounds: MAYA, cultures: ["mesoamerican" as const] };
const MAYA_LONG = { years: [-600, 1950] as [number, number], bounds: MAYA, cultures: ["mesoamerican" as const] };
const MEXICA = { years: [1325, 1530] as [number, number], bounds: BASIN, cultures: ["mesoamerican" as const] };
const NEW_SPAIN = { years: [1530, 1950] as [number, number], bounds: MESO, cultures: ["mesoamerican" as const, "european" as const] };
const CARAL = { years: [-3000, -1800] as [number, number], bounds: [-78.5, -11.5, -76.5, -10] as Box, cultures: ["andean" as const] };
const INCA = { years: [1438, 1535] as [number, number], bounds: ANDES, cultures: ["andean" as const] };
const ANDEAN_LONG = { years: [1000, 1950] as [number, number], bounds: ANDES, cultures: ["andean" as const] };
const COLONIAL_ANDES = { years: [1535, 1950] as [number, number], bounds: ANDES, cultures: ["andean" as const, "european" as const] };

/** Veintena dates assume the year opened with Atlcahualo about 14 February (Sahagún's correlation). */
export const mesoamericaAndesOccasions: Occasion[] = [
  {
    id: "day.meso-archaic.agave",
    label: "Roasting agave",
    scope: MESO_ARCHAIC,
    evidence: "inferred",
    when: [{ type: "adult" }, { type: "season", any: ["spring", "summer"] }, { type: "chance", p: 0.25 }],
    weight: 5,
    part: "morning",
    place: "edge",
    activity: "cook",
    minutes: 60,
    text: "Bury agave hearts in the earth oven to roast for two days.",
    note: "Charred agave quids are among the commonest plant remains in the dry caves of Oaxaca and Tehuacán.",
    sources: ["https://en.wikipedia.org/wiki/Guil%C3%A1_Naquitz_Cave"],
  },
  {
    id: "day.meso-archaic.squash",
    label: "Tending the squash",
    scope: MESO_ARCHAIC,
    evidence: "inferred",
    when: [{ type: "adult" }, { type: "season", any: ["summer"] }, { type: "chance", p: 0.3 }],
    weight: 5,
    part: "midday",
    place: "wild",
    activity: "tend",
    minutes: 45,
    text: "Weed round the squash and bottle gourds sprouting on the old camp midden.",
    note: "Domesticated squash seeds at Guilá Naquitz are about ten thousand years old, far older than maize farming.",
    sources: ["https://en.wikipedia.org/wiki/Guil%C3%A1_Naquitz_Cave"],
  },
  {
    id: "day.olmec.celt",
    label: "Burying a greenstone offering",
    scope: OLMEC,
    evidence: "documented",
    when: [{ type: "observance", levels: ["devout"] }, { type: "rank", any: ["gentry", "elite"] }, { type: "chance", p: 0.15 }],
    weight: 5,
    part: "morning",
    place: "sanctuary",
    activity: "work",
    minutes: 40,
    text: "Bury polished greenstone celts in rows beneath the plaza floor.",
    note: "At La Venta, Offering 4 set sixteen jade figurines and six celts in a buried scene.",
    sources: ["https://en.wikipedia.org/wiki/La_Venta"],
  },
  {
    id: "day.olmec.rubber",
    label: "Making rubber balls",
    scope: OLMEC,
    evidence: "documented",
    when: [{ type: "adult" }, { type: "chance", p: 0.2 }],
    weight: 4,
    part: "midday",
    place: "work",
    activity: "work",
    minutes: 50,
    text: "Stir morning-glory juice into the latex to cure it into bouncing rubber.",
    note: "Rubber balls were laid as offerings in the spring at El Manatí from about 1600 BCE.",
    sources: ["https://en.wikipedia.org/wiki/Mesoamerican_rubber_balls", "https://en.wikipedia.org/wiki/El_Manat%C3%AD"],
  },
  {
    id: "day.zapotec.tomb",
    label: "Opening the family tomb",
    scope: ZAPOTEC,
    evidence: "inferred",
    when: [{ type: "anniversary", kind: "died" }],
    weight: 12,
    part: "morning",
    place: "home",
    activity: "visit",
    minutes: 40,
    carry: "vessel",
    text: "Lift the stone over the tomb beneath the patio and set food beside {dead}.",
    note: "Monte Albán households buried their dead in tombs under their own houses and reopened them for each new burial.",
    sources: ["https://en.wikipedia.org/wiki/Monte_Alb%C3%A1n"],
    serves: ["remember-dead"],
  },
  {
    id: "day.zapotec.naming",
    label: "Asking the calendar priest",
    scope: ZAPOTEC,
    evidence: "inferred",
    when: [{ type: "kin", kind: "child", maxAge: 1 }, { type: "adult" }],
    weight: 8,
    part: "morning",
    place: "sanctuary",
    activity: "visit",
    minutes: 30,
    text: "Ask the calendar priest which day of the piye {child} should be named for.",
    note: "Zapotec names, like Mixtec and Nahua ones, were taken from the day of the 260-day count.",
    sources: ["https://en.wikipedia.org/wiki/Zapotec_civilization"],
    serves: ["child-future"],
  },
  {
    id: "day.teotihuacan.altar",
    label: "The compound altar",
    scope: TEOTIHUACAN,
    evidence: "inferred",
    when: [{ type: "observance", levels: ["devout", "regular"] }, { type: "adult" }, { type: "chance", p: 0.3 }],
    weight: 4,
    part: "morning",
    place: "hearth",
    activity: "visit",
    minutes: 20,
    text: "Burn copal in the three-footed censer on the altar in your compound's patio.",
    note: "Each apartment compound had a central patio with a small temple-altar, and ladle and theatre censers turn up in them.",
    sources: ["https://en.wikipedia.org/wiki/Teotihuacan"],
    serves: ["household-home"],
  },
  {
    id: "day.teotihuacan.obsidian",
    label: "Knapping green obsidian",
    scope: TEOTIHUACAN,
    evidence: "documented",
    when: [{ type: "work", match: /knap|stone|obsidian|tool|craft/i }],
    weight: 6,
    part: "midday",
    place: "work",
    activity: "work",
    minutes: 60,
    text: "Press long blades off a core of green Pachuca obsidian for the traders.",
    sources: ["https://en.wikipedia.org/wiki/Obsidian_use_in_Mesoamerica"],
  },
  {
    id: "day.teotihuacan.oaxaca-barrio",
    label: "Visiting the Oaxaca barrio",
    scope: TEOTIHUACAN,
    evidence: "documented",
    when: [{ type: "adult" }, { type: "trait", key: "openness", above: 55 }, { type: "chance", p: 0.1 }],
    weight: 3,
    part: "evening",
    place: "door",
    activity: "visit",
    minutes: 45,
    text: "Eat with the Zapotec families of Tlailotlacan, who still bury their dead in Oaxaca tombs.",
    sources: ["https://en.wikipedia.org/wiki/Teotihuacan"],
  },
  {
    id: "day.toltec.chacmool",
    label: "An offering on the chacmool",
    scope: TOLTEC,
    evidence: "inferred",
    when: [{ type: "observance", levels: ["devout", "regular"] }, { type: "adult" }, { type: "chance", p: 0.15 }],
    weight: 4,
    part: "morning",
    place: "sanctuary",
    activity: "visit",
    minutes: 25,
    carry: "basket",
    text: "Lay tortillas and copal in the bowl on the chacmool's lap in the colonnaded hall.",
    note: "The reclining chacmool figures at Tula hold a dish on the belly, read as a receptacle for offerings.",
    sources: ["https://en.wikipedia.org/wiki/Chacmool", "https://en.wikipedia.org/wiki/Tula_(Mesoamerican_site)"],
  },
  {
    id: "day.maya.bloodletting",
    label: "Letting blood",
    scope: MAYA_CLASSIC,
    evidence: "documented",
    when: [{ type: "rank", any: ["gentry", "elite"] }, { type: "observance", levels: ["devout", "regular"] }, { type: "chance", p: 0.12 }],
    weight: 6,
    part: "evening",
    place: "sanctuary",
    activity: "visit",
    minutes: 40,
    text: "Pierce your tongue with a stingray spine and burn the bloodied bark paper.",
    note: "Yaxchilan Lintel 24 shows Lady K'abal Xook drawing a thorned rope through her tongue.",
    sources: ["https://en.wikipedia.org/wiki/Bloodletting_in_Mesoamerica", "https://en.wikipedia.org/wiki/Yaxchilan_Lintel_24"],
  },
  {
    id: "day.maya.burn-milpa",
    label: "Burning the milpa",
    scope: MAYA_LONG,
    evidence: "documented",
    when: [{ type: "season", any: ["spring"] }, { type: "work", match: /farm|maize|grow|cultivat/i }, { type: "chance", p: 0.4 }],
    weight: 7,
    part: "midday",
    place: "work",
    activity: "tend",
    minutes: 60,
    text: "Fire the felled bush on next year's milpa before the rains come.",
    sources: ["https://en.wikipedia.org/wiki/Milpa"],
  },
  {
    id: "day.maya.plant-milpa",
    label: "Planting the milpa",
    scope: MAYA_LONG,
    evidence: "documented",
    when: [{ type: "season", any: ["summer"] }, { type: "work", match: /farm|maize|grow|cultivat/i }, { type: "chance", p: 0.4 }],
    weight: 7,
    part: "morning",
    place: "work",
    activity: "tend",
    minutes: 60,
    carry: "bundle",
    text: "Plant maize with the digging stick, five kernels to a hole, beans and squash between.",
    sources: ["https://en.wikipedia.org/wiki/Three_Sisters_(agriculture)", "https://en.wikipedia.org/wiki/Milpa"],
  },
  {
    id: "day.maya.cha-chaak",
    label: "The ch'a chaak",
    scope: { years: [1000, 1950], bounds: YUCATAN, cultures: ["mesoamerican"] },
    evidence: "inferred",
    when: [{ type: "season", any: ["spring", "summer"] }, { type: "work", match: /farm|maize|grow|cultivat/i }, { type: "sex", is: "male" }, { type: "chance", p: 0.2 }],
    weight: 6,
    part: "evening",
    place: "edge",
    activity: "visit",
    minutes: 60,
    carry: "vessel",
    text: "Carry sakab' maize drink to the h-men's altar in the forest to call the Chaaks.",
    note: "Ethnographers since Redfield record boys crouched under the altar croaking like frogs while the h-men prays for rain.",
    sources: ["https://en.wikipedia.org/wiki/Chaac"],
  },
  {
    id: "day.maya.tzite",
    label: "Consulting the daykeeper",
    scope: { years: [1000, 1950], bounds: MAYA_HIGHLAND, cultures: ["mesoamerican"] },
    evidence: "inferred",
    when: [{ type: "fortune", below: 0.4 }, { type: "adult" }, { type: "chance", p: 0.2 }],
    weight: 5,
    part: "morning",
    place: "door",
    activity: "visit",
    minutes: 40,
    text: "Ask the ajq'ij for a reading of your trouble in the tz'ite seeds and day-signs.",
    sources: ["https://en.wikipedia.org/wiki/Maya_calendar", "https://en.wikipedia.org/wiki/Erythrina"],
  },
  {
    id: "day.maya.wajxaqib-batz",
    label: "Waqxaqib' B'atz'",
    scope: { years: [1500, 1950], bounds: MAYA_HIGHLAND, cultures: ["mesoamerican"] },
    evidence: "inferred",
    when: [{ type: "cycle", every: 20, on: 11 }, { type: "observance", levels: ["devout", "regular"] }, { type: "adult" }],
    weight: 10,
    part: "morning",
    place: "edge",
    activity: "visit",
    minutes: 60,
    carry: "bundle",
    text: "Climb to the hill shrine with copal and candles: it is 8 B'atz', the daykeepers' day.",
    note: "The twenty-day cycle stands in for the 260-day tzolk'in, whose days the game calendar compresses.",
    sources: ["https://en.wikipedia.org/wiki/Tzolk%CA%BCin"],
  },
  {
    id: "day.maya.cozumel",
    label: "Pilgrimage to Ix Chel",
    scope: { years: [1000, 1550], bounds: YUCATAN, cultures: ["mesoamerican"] },
    evidence: "documented",
    when: [{ type: "sex", is: "female" }, { type: "adult" }, { type: "kin", kind: "partner" }, { type: "chance", p: 0.04 }],
    weight: 4,
    part: "morning",
    place: "edge",
    activity: "visit",
    minutes: 60,
    carry: "bundle",
    text: "Set out for the canoe crossing to Ix Chel's shrine on Cozumel to pray for a child.",
    sources: ["https://en.wikipedia.org/wiki/Ixchel", "https://en.wikipedia.org/wiki/Cozumel"],
    serves: ["raise-kin"],
  },
  {
    id: "day.maya.cacao-match",
    label: "Sending the go-between",
    scope: MAYA_LONG,
    evidence: "inferred",
    when: [{ type: "seek-match" }],
    weight: 6,
    part: "evening",
    place: "door",
    activity: "visit",
    minutes: 40,
    carry: "basket",
    text: "Send the go-between with cacao and cloth to ask for the girl's hand.",
    note: "Landa describes marriages arranged through professional matchmakers and a bride-service in the wife's father's house.",
    sources: ["https://en.wikipedia.org/wiki/Diego_de_Landa"],
    serves: ["marriage-hope"],
  },
  {
    id: "day.mexica.sweep",
    label: "Sweeping before dawn",
    scope: MEXICA,
    evidence: "documented",
    when: [{ type: "sex", is: "female" }, { type: "adult" }, { type: "chance", p: 0.35 }],
    weight: 5,
    part: "morning",
    place: "home",
    activity: "work",
    minutes: 20,
    text: "Sweep the house and patio before light: sweeping keeps the filth of disorder out.",
    note: "A Nahua midwife told the newborn girl her work was the hearth, the broom and the metate.",
    sources: ["https://en.wikipedia.org/wiki/Aztec_society"],
    serves: ["household-home"],
  },
  {
    id: "day.mexica.fire-share",
    label: "Feeding the fire",
    scope: MEXICA,
    evidence: "documented",
    when: [{ type: "observance", levels: ["devout", "regular"] }, { type: "adult" }, { type: "chance", p: 0.3 }],
    weight: 4,
    part: "evening",
    place: "hearth",
    activity: "cook",
    minutes: 15,
    text: "Throw the first scrap of tortilla into the hearth for Xiuhtecuhtli before anyone eats.",
    sources: ["https://en.wikipedia.org/wiki/Xiuhtecuhtli"],
  },
  {
    id: "day.mexica.chinampa",
    label: "Mudding the chinampa",
    scope: MEXICA,
    evidence: "documented",
    when: [{ type: "work", match: /farm|maize|grow|cultivat|garden/i }, { type: "chance", p: 0.4 }],
    weight: 6,
    part: "morning",
    place: "work",
    activity: "tend",
    minutes: 60,
    text: "Scoop lake mud onto your chinampa and set out seedlings from the nursery bed.",
    sources: ["https://en.wikipedia.org/wiki/Chinampa"],
  },
  {
    id: "day.mexica.telpochcalli",
    label: "The telpochcalli",
    scope: MEXICA,
    evidence: "documented",
    when: [{ type: "kin", kind: "child", minAge: 12, maxAge: 15 }, { type: "rank", any: ["destitute", "labouring", "middling"] }],
    weight: 6,
    part: "morning",
    place: "gathering",
    activity: "visit",
    minutes: 30,
    text: "Hand {child} over to the masters of youth at the ward's telpochcalli.",
    note: "Every commoner boy of the calpolli was schooled there in war and public labour.",
    sources: ["https://en.wikipedia.org/wiki/Telpochcalli"],
    serves: ["child-future"],
  },
  {
    id: "day.mexica.calmecac",
    label: "The calmecac",
    scope: MEXICA,
    evidence: "documented",
    when: [{ type: "kin", kind: "child", minAge: 7, maxAge: 15 }, { type: "rank", any: ["gentry", "elite"] }],
    weight: 6,
    part: "morning",
    place: "sanctuary",
    activity: "visit",
    minutes: 30,
    text: "Take {child} to the calmecac priests to learn the painted books and the songs.",
    sources: ["https://en.wikipedia.org/wiki/Calmecac"],
    serves: ["child-future"],
  },
  {
    id: "day.mexica.tonalpouhqui",
    label: "Reading the day-sign",
    scope: MEXICA,
    evidence: "documented",
    when: [{ type: "kin", kind: "child", maxAge: 0 }, { type: "adult" }],
    weight: 10,
    part: "morning",
    place: "door",
    activity: "visit",
    minutes: 40,
    carry: "basket",
    text: "Ask the tonalpouhqui to read {child}'s birth sign in the tonalamatl for a good naming day.",
    note: "A child born on an ill sign could be named on a kinder day later in the same thirteen.",
    sources: ["https://en.wikipedia.org/wiki/Tonalpohualli"],
    serves: ["child-future"],
  },
  {
    id: "day.mexica.pochteca",
    label: "The merchants' banquet",
    scope: MEXICA,
    evidence: "documented",
    when: [{ type: "work", match: /merchant|trader|pochte/i }, { type: "chance", p: 0.2 }],
    weight: 6,
    part: "evening",
    place: "door",
    activity: "visit",
    minutes: 60,
    text: "Feast the elder pochteca on the eve of your caravan's departure for Xicalanco.",
    note: "Sahagún's merchants set out on a lucky day, One Serpent, and kept the departure quiet.",
    sources: ["https://en.wikipedia.org/wiki/Pochteca"],
  },
  {
    id: "day.mexica.pulque-elders",
    label: "Pulque for an elder",
    scope: MEXICA,
    evidence: "documented",
    when: [{ type: "kin", kind: "parent", minAge: 52 }, { type: "chance", p: 0.25 }],
    weight: 5,
    part: "evening",
    place: { kin: "parent" },
    activity: "visit",
    minutes: 30,
    carry: "vessel",
    text: "Pour pulque for {parent}, who is old enough to be allowed it.",
    note: "Drunkenness was punished among the young; the old, past a cycle of 52 years, might drink.",
    sources: ["https://en.wikipedia.org/wiki/Pulque"],
    serves: ["elder-kin"],
  },
  {
    id: "day.mexica.toxcatl",
    label: "Toxcatl",
    scope: MEXICA,
    evidence: "documented",
    when: [{ type: "date", dayOfYear: 135 }, { type: "observance", levels: ["devout", "regular", "occasional"] }],
    weight: 14,
    part: "evening",
    place: "sanctuary",
    activity: "visit",
    minutes: 60,
    text: "Wear a garland of popped maize and dance for Tezcatlipoca: it is Toxcatl.",
    sources: ["https://en.wikipedia.org/wiki/Toxcatl"],
  },
  {
    id: "day.mexica.etzalcualiztli",
    label: "Etzalcualiztli",
    scope: MEXICA,
    evidence: "documented",
    when: [{ type: "date", dayOfYear: 155 }, { type: "adult" }],
    weight: 14,
    part: "midday",
    place: "door",
    activity: "visit",
    minutes: 40,
    carry: "vessel",
    text: "Cook etzalli of maize and beans and share a bowl at each door for Tlaloc.",
    sources: ["https://en.wikipedia.org/wiki/Aztec_calendar"],
  },
  {
    id: "day.mexica.ochpaniztli",
    label: "Ochpaniztli",
    scope: MEXICA,
    evidence: "documented",
    when: [{ type: "date", dayOfYear: 255 }, { type: "adult" }],
    weight: 14,
    part: "morning",
    place: "gathering",
    activity: "work",
    minutes: 40,
    text: "Sweep the road and the ward shrine for Toci: it is Ochpaniztli, the sweeping.",
    sources: ["https://en.wikipedia.org/wiki/Ochpaniztli"],
  },
  {
    id: "day.mexica.tepeilhuitl",
    label: "Tepeilhuitl",
    scope: MEXICA,
    evidence: "documented",
    when: [{ type: "date", dayOfYear: 295 }, { type: "adult" }],
    weight: 14,
    part: "evening",
    place: "hearth",
    activity: "cook",
    minutes: 40,
    text: "Shape little mountains of amaranth dough with bean eyes for the rain-hills.",
    note: "The dough images, tzoalli, were later broken open and eaten like the flesh of the mountains.",
    sources: ["https://en.wikipedia.org/wiki/Aztec_calendar"],
  },
  {
    id: "day.mexica.quecholli",
    label: "Quecholli",
    scope: MEXICA,
    evidence: "documented",
    when: [{ type: "date", dayOfYear: 315 }, { type: "sex", is: "male" }, { type: "adult" }],
    weight: 14,
    part: "morning",
    place: "wild",
    activity: "gather",
    minutes: 60,
    text: "Fletch reed arrows for Mixcoatl's great hunt on Zacatepetl.",
    sources: ["https://en.wikipedia.org/wiki/Mixcoatl"],
  },
  {
    id: "day.newspain.ofrenda",
    label: "Building the ofrenda",
    scope: NEW_SPAIN,
    evidence: "documented",
    when: [{ type: "date", dayOfYear: 304 }, { type: "adult" }],
    weight: 14,
    part: "evening",
    place: "home",
    activity: "work",
    minutes: 60,
    carry: "basket",
    text: "Build the ofrenda: cempasúchil, pan de muerto, copal and your dead's favourite dishes.",
    sources: ["https://en.wikipedia.org/wiki/Day_of_the_Dead"],
    serves: ["remember-dead"],
  },
  {
    id: "day.newspain.vigil",
    label: "Keeping vigil at the graves",
    scope: NEW_SPAIN,
    evidence: "documented",
    when: [{ type: "date", dayOfYear: 306 }],
    weight: 14,
    part: "evening",
    place: "sanctuary",
    activity: "visit",
    minutes: 90,
    carry: "bundle",
    text: "Carry marigolds and candles to the churchyard and sit up with your dead.",
    sources: ["https://en.wikipedia.org/wiki/Day_of_the_Dead"],
    serves: ["remember-dead"],
  },
  {
    id: "day.newspain.posada",
    label: "Las Posadas",
    scope: { ...NEW_SPAIN, years: [1590, 1950] },
    evidence: "documented",
    when: [{ type: "date", dayOfYear: 352 }],
    weight: 12,
    part: "evening",
    place: "door",
    activity: "visit",
    minutes: 50,
    text: "Walk with the candles behind Mary and Joseph, singing for lodging at each door.",
    sources: ["https://en.wikipedia.org/wiki/Las_Posadas"],
  },
  {
    id: "day.newspain.mayordomo",
    label: "Cofradía accounts",
    scope: NEW_SPAIN,
    evidence: "documented",
    when: [{ type: "rank", any: ["middling", "gentry"] }, { type: "adult" }, { type: "chance", p: 0.08 }],
    weight: 4,
    part: "evening",
    place: "sanctuary",
    activity: "visit",
    minutes: 45,
    text: "Reckon the cost of the saint's fiesta with the other officers of the cofradía.",
    note: "The mayordomo who paid for candles, fireworks and pulque rose a rung in the village's cargo ladder.",
    sources: ["https://en.wikipedia.org/wiki/Cargo_system", "https://en.wikipedia.org/wiki/Confraternity"],
  },
  {
    id: "day.newspain.repartimiento",
    label: "Repartimiento labour",
    scope: { years: [1550, 1640], bounds: MESO, cultures: ["mesoamerican"] },
    evidence: "documented",
    when: [{ type: "sex", is: "male" }, { type: "rank", any: ["destitute", "labouring"] }, { type: "chance", p: 0.08 }],
    weight: 5,
    part: "morning",
    place: "edge",
    activity: "haul",
    minutes: 60,
    text: "Report to the Spanish farm for your repartimiento week of forced wage labour.",
    sources: ["https://en.wikipedia.org/wiki/Repartimiento"],
  },
  {
    id: "day.oaxaca.tequio",
    label: "The tequio",
    scope: { years: [1550, 1950], bounds: OAXACA, cultures: ["mesoamerican"] },
    evidence: "documented",
    when: [{ type: "sex", is: "male" }, { type: "adult" }, { type: "chance", p: 0.12 }],
    weight: 5,
    part: "morning",
    place: "gathering",
    activity: "work",
    minutes: 60,
    text: "Turn out for the tequio to clear the village water channel.",
    sources: ["https://en.wikipedia.org/wiki/Usos_y_costumbres"],
    serves: ["shared-future"],
  },
  {
    id: "day.newspain.temazcal",
    label: "The birth sweat",
    scope: { years: [-1200, 1950], bounds: MESO, cultures: ["mesoamerican"] },
    evidence: "documented",
    when: [{ type: "sex", is: "female" }, { type: "kin", kind: "child", maxAge: 0 }],
    weight: 8,
    part: "evening",
    place: { venue: "bath" },
    activity: "visit",
    minutes: 60,
    text: "Take the temazcal steam with the midwife after the birth.",
    sources: ["https://en.wikipedia.org/wiki/Temazcal"],
  },
  {
    id: "day.mexico.rural-school",
    label: "The rural school",
    scope: { years: [1922, 1950], bounds: MESO, cultures: ["mesoamerican"] },
    evidence: "documented",
    when: [{ type: "kin", kind: "child", minAge: 6, maxAge: 12 }, { type: "rank", any: ["destitute", "labouring", "middling"] }],
    weight: 5,
    part: "morning",
    place: "gathering",
    activity: "visit",
    minutes: 20,
    text: "Walk {child} to the new federal school the maestro rural has opened.",
    note: "Vasconcelos's Secretariat of Public Education sent teachers out to build village schools from 1921.",
    sources: ["https://en.wikipedia.org/wiki/Secretariat_of_Public_Education_(Mexico)"],
    serves: ["child-future"],
  },
  {
    id: "day.caral.shicra",
    label: "Carrying a shicra",
    scope: CARAL,
    evidence: "documented",
    when: [{ type: "adult" }, { type: "chance", p: 0.3 }],
    weight: 5,
    part: "midday",
    place: "sanctuary",
    activity: "haul",
    minutes: 50,
    carry: "bundle",
    text: "Heave a shicra bag of stones, netted from reed, into the platform mound's fill.",
    note: "The Caral mounds were built up from thousands of these mesh bags of stone.",
    sources: ["https://en.wikipedia.org/wiki/Caral"],
  },
  {
    id: "day.caral.anchovy",
    label: "Trading dried anchovies",
    scope: CARAL,
    evidence: "inferred",
    when: [{ type: "work", match: /fish/i }, { type: "chance", p: 0.25 }],
    weight: 5,
    part: "morning",
    place: "market",
    activity: "haul",
    minutes: 50,
    carry: "bundle",
    text: "Carry dried anchovies up the valley to trade for cotton for your nets.",
    note: "Moseley's maritime hypothesis: coast fish fed the inland towns, and inland cotton made the nets.",
    sources: ["https://en.wikipedia.org/wiki/Norte_Chico_civilization"],
  },
  {
    id: "day.chavin.oracle",
    label: "Pilgrimage to Chavín",
    scope: { years: [-900, -200], bounds: [-79.5, -11, -76, -7], cultures: ["andean"] },
    evidence: "inferred",
    when: [{ type: "observance", levels: ["devout"] }, { type: "adult" }, { type: "chance", p: 0.05 }],
    weight: 4,
    part: "morning",
    place: "edge",
    activity: "visit",
    minutes: 60,
    carry: "bundle",
    text: "Set out over the passes for Chavín de Huántar, to hear the Lanzón roar in the galleries.",
    note: "Conch trumpets found in the galleries echo through the stone ducts beneath the temple.",
    sources: ["https://en.wikipedia.org/wiki/Chav%C3%ADn_de_Hu%C3%A1ntar"],
  },
  {
    id: "day.paracas.mantle",
    label: "Embroidering a mantle",
    scope: { years: [-800, -100], bounds: [-76.8, -15, -75.5, -13.5], cultures: ["andean"] },
    evidence: "documented",
    when: [{ type: "adult" }, { type: "chance", p: 0.3 }],
    weight: 5,
    part: "midday",
    place: "home",
    activity: "work",
    minutes: 60,
    text: "Stitch another border of flying figures on the mantle meant for a burial bundle.",
    sources: ["https://en.wikipedia.org/wiki/Paracas_textile"],
  },
  {
    id: "day.nazca.line",
    label: "Clearing a line",
    scope: { years: [-100, 700], bounds: [-75.6, -15.2, -74.6, -14.3], cultures: ["andean"] },
    evidence: "hypothesis",
    when: [{ type: "adult" }, { type: "chance", p: 0.1 }],
    weight: 3,
    part: "morning",
    place: "wild",
    activity: "work",
    minutes: 60,
    text: "Rake the dark desert stones aside to lengthen the line across the pampa.",
    note: "Walking the lines in procession is the favoured reading; broken pots lie along many of them.",
    sources: ["https://en.wikipedia.org/wiki/Nazca_Lines"],
  },
  {
    id: "day.nazca.puquio",
    label: "Cleaning the puquio",
    scope: { years: [400, 1950], bounds: [-75.6, -15.2, -74.6, -14.3], cultures: ["andean"] },
    evidence: "documented",
    when: [{ type: "work", match: /farm|grow|cultivat|maize/i }, { type: "chance", p: 0.2 }],
    weight: 5,
    part: "morning",
    place: "edge",
    activity: "work",
    minutes: 60,
    text: "Climb down the spiral well to dig silt out of the puquio's underground channel.",
    sources: ["https://en.wikipedia.org/wiki/Puquios"],
    serves: ["shared-future"],
  },
  {
    id: "day.moche.portrait",
    label: "Moulding a portrait jar",
    scope: { years: [100, 800], bounds: NORTH_COAST, cultures: ["andean"] },
    evidence: "documented",
    when: [{ type: "work", match: /pot|ceram|clay/i }],
    weight: 6,
    part: "midday",
    place: "work",
    activity: "work",
    minutes: 60,
    text: "Press clay into the two-piece mould for another stirrup-spout portrait of the lord.",
    sources: ["https://en.wikipedia.org/wiki/Moche_culture"],
  },
  {
    id: "day.north-coast.caballito",
    label: "Paddling a caballito",
    scope: { years: [-200, 1950], bounds: NORTH_COAST, cultures: ["andean"] },
    evidence: "documented",
    when: [{ type: "work", match: /fish/i }],
    weight: 6,
    part: "morning",
    place: "work",
    activity: "work",
    minutes: 60,
    text: "Paddle your caballito of totora reed out through the surf to the nets.",
    note: "Moche pots show fishermen astride the same reed rafts still used at Huanchaco.",
    sources: ["https://en.wikipedia.org/wiki/Caballito_de_totora"],
  },
  {
    id: "day.tiwanaku.raised-fields",
    label: "Rebuilding the raised fields",
    scope: { years: [500, 1100], bounds: [-70, -18, -67.5, -15], cultures: ["andean"] },
    evidence: "documented",
    when: [{ type: "work", match: /farm|grow|cultivat|potato|quinoa/i }, { type: "chance", p: 0.3 }],
    weight: 6,
    part: "morning",
    place: "work",
    activity: "tend",
    minutes: 60,
    text: "Dig out the canal between the raised fields to heap the muck on the potato beds.",
    note: "The water in the suka kollus canals held the day's heat and kept frost off the crop.",
    sources: ["https://en.wikipedia.org/wiki/Waru_Waru"],
  },
  {
    id: "day.tiwanaku.kero",
    label: "The Akapana feast",
    scope: { years: [500, 1100], bounds: [-70, -18, -67.5, -15], cultures: ["andean"] },
    evidence: "inferred",
    when: [{ type: "adult" }, { type: "chance", p: 0.1 }],
    weight: 4,
    part: "evening",
    place: "sanctuary",
    activity: "visit",
    minutes: 60,
    text: "Drink chicha from a flaring kero at the feast below the Akapana.",
    sources: ["https://en.wikipedia.org/wiki/Tiwanaku", "https://en.wikipedia.org/wiki/Kero"],
  },
  {
    id: "day.wari.molle",
    label: "Brewing molle chicha",
    scope: { years: [600, 1000], bounds: [-76, -18, -70, -12], cultures: ["andean"] },
    evidence: "inferred",
    when: [{ type: "sex", is: "female" }, { type: "adult" }, { type: "chance", p: 0.2 }],
    weight: 4,
    part: "midday",
    place: "gathering",
    activity: "cook",
    minutes: 50,
    carry: "vessel",
    text: "Mash molle berries in the lord's brewery for the feast jars.",
    note: "The Wari brewery on Cerro Baúl was burned with its jars after a last feast about 1000 CE.",
    sources: ["https://en.wikipedia.org/wiki/Cerro_Ba%C3%BAl", "https://en.wikipedia.org/wiki/Schinus_molle"],
  },
  {
    id: "day.chimu.storerooms",
    label: "Delivering to Chan Chan",
    scope: { years: [900, 1470], bounds: NORTH_COAST, cultures: ["andean"] },
    evidence: "inferred",
    when: [{ type: "work", match: /weav|smith|metal|gold|silver|craft/i }, { type: "chance", p: 0.2 }],
    weight: 5,
    part: "midday",
    place: "edge",
    activity: "haul",
    minutes: 50,
    carry: "bundle",
    text: "Hand your finished work into the storerooms of the lord's ciudadela at Chan Chan.",
    sources: ["https://en.wikipedia.org/wiki/Chan_Chan"],
  },
  {
    id: "day.inca.mita",
    label: "The mit'a turn",
    scope: INCA,
    evidence: "documented",
    when: [{ type: "sex", is: "male" }, { type: "rank", any: ["destitute", "labouring"] }, { type: "chance", p: 0.08 }],
    weight: 5,
    part: "morning",
    place: "edge",
    activity: "haul",
    minutes: 60,
    text: "Report to the curaca for your mit'a turn on the Inca's road.",
    sources: ["https://en.wikipedia.org/wiki/Mit%27a"],
  },
  {
    id: "day.inca.khipu",
    label: "Keeping the khipu",
    scope: INCA,
    evidence: "documented",
    when: [{ type: "rank", any: ["gentry", "elite"] }, { type: "chance", p: 0.2 }],
    weight: 5,
    part: "midday",
    place: "work",
    activity: "work",
    minutes: 50,
    text: "Record this year's herd count in the khipu cords for the decimal lord.",
    sources: ["https://en.wikipedia.org/wiki/Quipu"],
  },
  {
    id: "day.inca.mallqui",
    label: "Feeding the mallqui",
    scope: { years: [1000, 1650], bounds: ANDES, cultures: ["andean"] },
    evidence: "documented",
    when: [{ type: "date", dayOfYear: 310 }, { type: "adult" }],
    weight: 13,
    part: "midday",
    place: "edge",
    activity: "visit",
    minutes: 60,
    carry: "vessel",
    text: "Bring the ayllu's mallqui out of their cave and give them chicha and new clothes.",
    note: "November was Aya Marcay Quilla, the month of carrying the dead; Arriaga still found the practice in 1621.",
    sources: ["https://en.wikipedia.org/wiki/Religion_in_the_Inca_Empire"],
    serves: ["remember-dead"],
  },
  {
    id: "day.andes.ayni",
    label: "Ayni",
    scope: ANDEAN_LONG,
    evidence: "documented",
    when: [{ type: "kin", kind: "friend" }, { type: "adult" }, { type: "chance", p: 0.2 }],
    weight: 5,
    part: "morning",
    place: { kin: "friend" },
    activity: "tend",
    minutes: 60,
    text: "Work {friend}'s field today: they owe you the same days in ayni.",
    sources: ["https://en.wikipedia.org/wiki/Ayni"],
    serves: ["shared-future"],
  },
  {
    id: "day.andes.muko",
    label: "Brewing chicha",
    scope: { years: [-500, 1950], bounds: ANDES, cultures: ["andean"] },
    evidence: "documented",
    when: [{ type: "sex", is: "female" }, { type: "adult" }, { type: "chance", p: 0.25 }],
    weight: 5,
    part: "midday",
    place: "hearth",
    activity: "cook",
    minutes: 60,
    carry: "vessel",
    text: "Chew maize flour into muko and set the mash to boil for the work party's chicha.",
    sources: ["https://en.wikipedia.org/wiki/Chicha"],
  },
  {
    id: "day.andes.challa",
    label: "The ch'alla",
    scope: ANDEAN_LONG,
    evidence: "documented",
    when: [{ type: "observance", levels: ["devout", "regular", "occasional"] }, { type: "adult" }, { type: "chance", p: 0.3 }],
    weight: 4,
    part: "evening",
    place: "hearth",
    activity: "visit",
    minutes: 10,
    carry: "vessel",
    text: "Spill the first drops of chicha on the earth for Pachamama before drinking.",
    sources: ["https://en.wikipedia.org/wiki/Pachamama"],
  },
  {
    id: "day.andes.apacheta",
    label: "The apacheta",
    scope: ANDEAN_LONG,
    evidence: "documented",
    when: [{ type: "adult" }, { type: "chance", p: 0.15 }],
    weight: 4,
    part: "morning",
    place: "edge",
    activity: "visit",
    minutes: 40,
    text: "Add a stone and a quid of coca to the apacheta at the pass for the apus.",
    sources: ["https://en.wikipedia.org/wiki/Apacheta", "https://en.wikipedia.org/wiki/Apu_(god)"],
  },
  {
    id: "day.andes.huaca",
    label: "Visiting the huaca",
    scope: ANDEAN_LONG,
    evidence: "documented",
    when: [{ type: "observance", levels: ["devout", "regular"] }, { type: "adult" }, { type: "chance", p: 0.2 }],
    weight: 4,
    part: "morning",
    place: "wild",
    activity: "visit",
    minutes: 30,
    text: "Leave coca, fat and a pinch of red shell at the huaca stone by the spring.",
    note: "Mullu, ground Spondylus shell from Ecuador, was the huacas' favourite food.",
    sources: ["https://en.wikipedia.org/wiki/Huaca", "https://en.wikipedia.org/wiki/Spondylus"],
  },
  {
    id: "day.andes.kintu",
    label: "Sharing coca",
    scope: ANDEAN_LONG,
    evidence: "inferred",
    when: [{ type: "kin", kind: "friend" }, { type: "trait", key: "extraversion", above: 40 }, { type: "chance", p: 0.25 }],
    weight: 4,
    part: "evening",
    place: { kin: "friend" },
    activity: "visit",
    minutes: 30,
    text: "Share coca with {friend}, blowing on each k'intu of three leaves toward the apus.",
    sources: ["https://en.wikipedia.org/wiki/Coca"],
  },
  {
    id: "day.andes.rutuchikuy",
    label: "The first haircut",
    scope: ANDEAN_LONG,
    evidence: "documented",
    when: [{ type: "kin", kind: "child", minAge: 1, maxAge: 3 }, { type: "adult" }, { type: "chance", p: 0.1 }],
    weight: 7,
    part: "midday",
    place: "hearth",
    activity: "visit",
    minutes: 60,
    text: "Invite the kin to cut a lock each of {child}'s first hair, each pledging a gift.",
    sources: ["https://en.wikipedia.org/wiki/Inca_society"],
    serves: ["child-future", "raise-kin"],
  },
  {
    id: "day.andes.servinakuy",
    label: "Starting servinakuy",
    scope: ANDEAN_LONG,
    evidence: "documented",
    when: [{ type: "seek-match" }],
    weight: 6,
    part: "evening",
    place: "door",
    activity: "visit",
    minutes: 40,
    carry: "vessel",
    text: "Bring coca and cane liquor to your chosen's parents to ask leave for servinakuy.",
    note: "A trial marriage of a year or more, which colonial priests condemned and never stamped out.",
    sources: ["https://en.wikipedia.org/wiki/Trial_marriage"],
    serves: ["marriage-hope"],
  },
  {
    id: "day.andes.herd-marking",
    label: "Marking the herd",
    scope: COLONIAL_ANDES,
    evidence: "documented",
    when: [{ type: "date", dayOfYear: 206 }, { type: "work", match: /herd|llama|alpaca|shep/i }],
    weight: 14,
    part: "midday",
    place: "work",
    activity: "graze",
    minutes: 60,
    text: "Sew coloured wool tassels in your llamas' ears for Santiago, the herds' saint.",
    sources: ["https://en.wikipedia.org/wiki/Llama"],
  },
  {
    id: "day.andes.potosi",
    label: "The Potosí mita",
    scope: { years: [1573, 1812], bounds: [-72, -22, -64, -13], cultures: ["andean"] },
    evidence: "documented",
    when: [{ type: "sex", is: "male" }, { type: "rank", any: ["destitute", "labouring"] }, { type: "chance", p: 0.03 }],
    weight: 5,
    part: "morning",
    place: "edge",
    activity: "haul",
    minutes: 60,
    carry: "bundle",
    text: "Set out with your village's draft for a year's mita in the Potosí silver mines.",
    note: "Toledo's mita drew one in seven tributary men from sixteen highland provinces.",
    sources: ["https://en.wikipedia.org/wiki/Potos%C3%AD"],
  },
  {
    id: "day.andes.qoyllur-riti",
    label: "Qoyllur Rit'i",
    scope: { years: [1780, 1950], bounds: CUSCO, cultures: ["andean"] },
    evidence: "documented",
    when: [{ type: "date", dayOfYear: 152 }, { type: "observance", levels: ["devout", "regular"] }],
    weight: 14,
    part: "morning",
    place: "edge",
    activity: "visit",
    minutes: 90,
    carry: "bundle",
    text: "Walk up to the Sinakara glacier with your nation's dancers for Qoyllur Rit'i.",
    note: "A moveable feast in the week before Corpus Christi; the date here is representative.",
    sources: ["https://en.wikipedia.org/wiki/Quyllurit%27i"],
  },
  {
    id: "day.andes.wawa",
    label: "Baking t'anta wawa",
    scope: COLONIAL_ANDES,
    evidence: "documented",
    when: [{ type: "date", dayOfYear: 304 }, { type: "adult" }],
    weight: 14,
    part: "midday",
    place: "hearth",
    activity: "cook",
    minutes: 60,
    text: "Bake t'anta wawa bread babies for the table where the souls will eat.",
    sources: ["https://en.wikipedia.org/wiki/Guagua_de_pan"],
    serves: ["remember-dead"],
  },
  {
    id: "day.andes.wool",
    label: "Selling alpaca fleece",
    scope: { years: [1850, 1950], bounds: [-73, -18, -68, -13], cultures: ["andean"] },
    evidence: "documented",
    when: [{ type: "work", match: /herd|alpaca|llama/i }, { type: "chance", p: 0.15 }],
    weight: 5,
    part: "midday",
    place: "market",
    activity: "haul",
    minutes: 50,
    carry: "bundle",
    text: "Carry your fleeces to the Arequipa house's buyer at the fair.",
    note: "Alpaca wool went by rail from the southern highlands to Arequipa and out through Mollendo to Bradford.",
    sources: ["https://en.wikipedia.org/wiki/Alpaca_fiber"],
  },
];

export const mesoamericaAndesFestivals: Festival[] = [
  {
    id: "fest.mexica.panquetzaliztli",
    label: "Panquetzaliztli",
    scope: MEXICA,
    evidence: "documented",
    date: { dayOfYear: 335 },
    rest: true,
    place: "sanctuary",
    minutes: 150,
    text: "It is Panquetzaliztli, the raising of banners: paper flags on every house and fruit tree, and Huitzilopochtli's feast at the Templo Mayor.",
    note: "Veintena dates follow one correlation of the Mexica year with the Julian; others shift it by weeks.",
    sources: ["https://en.wikipedia.org/wiki/Panquetzaliztli"],
  },
  {
    id: "fest.mexica.nemontemi",
    label: "the nemontemi",
    scope: MEXICA,
    evidence: "documented",
    date: { dayOfYear: 42 },
    rest: true,
    place: "hearth",
    minutes: 60,
    text: "It is the nemontemi, the five empty days: nobody works, quarrels or leaves the house if they can help it.",
    sources: ["https://en.wikipedia.org/wiki/Nemontemi"],
  },
  {
    id: "fest.maya.wayeb",
    label: "the Wayeb' days",
    scope: { years: [1000, 1600], bounds: YUCATAN, cultures: ["mesoamerican"] },
    evidence: "documented",
    date: { dayOfYear: 192 },
    rest: true,
    place: "hearth",
    minutes: 60,
    text: "It is Wayeb', the five nameless days before 1 Pop: stay home, leave your hair uncombed and do no heavy work.",
    note: "Landa, writing about 1566, put 1 Pop on 16 July.",
    sources: ["https://en.wikipedia.org/wiki/Haab%CA%BC"],
  },
  {
    id: "fest.americas.sunday",
    label: "the Lord's Day",
    scope: { years: [1540, 1950], bounds: [-107, -25, -62, 25], cultures: ["mesoamerican", "andean", "european"] },
    evidence: "documented",
    date: { every: 7, on: 4 },
    rest: true,
    place: "sanctuary",
    minutes: 90,
    text: "It is Sunday: the fiscal rings the bell for mass, and the market fills after it.",
    sources: ["https://en.wikipedia.org/wiki/Sabbath_in_Christianity"],
  },
  {
    id: "fest.newspain.todos-santos",
    label: "Todos Santos",
    scope: NEW_SPAIN,
    evidence: "documented",
    date: { dayOfYear: 305 },
    rest: true,
    place: "sanctuary",
    minutes: 120,
    text: "It is All Saints: the little dead come home first, to ofrendas of sweets, toys and white candles.",
    sources: ["https://en.wikipedia.org/wiki/Day_of_the_Dead"],
  },
  {
    id: "fest.mexico.guadalupe",
    label: "the feast of Our Lady of Guadalupe",
    scope: { years: [1737, 1950], bounds: MESO, cultures: ["mesoamerican", "european"] },
    evidence: "documented",
    date: { dayOfYear: 346 },
    rest: false,
    place: "sanctuary",
    minutes: 90,
    text: "It is the day of the Virgin of Guadalupe: mañanitas at dawn, dancers in the atrium and candles before her image.",
    sources: ["https://en.wikipedia.org/wiki/Our_Lady_of_Guadalupe"],
  },
  {
    id: "fest.mexico.independence",
    label: "Independence Day",
    scope: { years: [1825, 1950], bounds: MESO, cultures: ["mesoamerican", "european"] },
    evidence: "documented",
    date: { dayOfYear: 259 },
    rest: true,
    place: "gathering",
    minutes: 120,
    text: "It is the Sixteenth of September: flags, rockets, a parade and the grito for Hidalgo.",
    sources: ["https://en.wikipedia.org/wiki/Cry_of_Dolores"],
  },
  {
    id: "fest.inca.inti-raymi",
    label: "Inti Raymi",
    scope: INCA,
    evidence: "documented",
    date: { dayOfYear: 175 },
    rest: true,
    place: "gathering",
    minutes: 150,
    text: "It is Inti Raymi, the Sun's feast at the winter solstice: fires put out, the new fire lit, llamas offered and chicha poured.",
    sources: ["https://en.wikipedia.org/wiki/Inti_Raymi"],
  },
  {
    id: "fest.inca.capac-raymi",
    label: "Capac Raymi",
    scope: INCA,
    evidence: "documented",
    date: { dayOfYear: 355 },
    rest: true,
    place: "gathering",
    minutes: 150,
    text: "It is Capac Raymi: the youths who ran the race are given their breechcloths and pierced ears.",
    note: "The huarachicuy initiation of noble boys was the core of the December solstice feast.",
    sources: ["https://en.wikipedia.org/wiki/Religion_in_the_Inca_Empire"],
  },
  {
    id: "fest.andes.corpus-christi",
    label: "Corpus Christi",
    scope: COLONIAL_ANDES,
    evidence: "documented",
    date: { dayOfYear: 160 },
    rest: true,
    place: "sanctuary",
    minutes: 150,
    text: "It is Corpus Christi: the parish saints are carried in procession on litters, as the mallqui once were.",
    note: "A moveable feast in late May or June; the date here is representative.",
    sources: ["https://en.wikipedia.org/wiki/Corpus_Christi_(feast)"],
  },
];
