import type { Festival, Occasion } from "./types";

const ROMAN = { years: [-300, 380] as [number, number], bounds: [-10, 30, 42, 56] as [number, number, number, number], cultures: ["european" as const] };

/** The Roman month is about nine game days; the Kalends fall on the first. */
export const romanOccasions: Occasion[] = [
  {
    id: "day.rome.lares-kalends",
    label: "The Lares on the Kalends",
    scope: ROMAN,
    evidence: "documented",
    when: [{ type: "cycle", every: 9, on: 0 }, { type: "adult" }],
    weight: 8,
    part: "morning",
    place: "hearth",
    activity: "visit",
    minutes: 20,
    text: "Hang a garland on the hearth and pray to the Lar of the household: it is the Kalends.",
    note: "Cato has the farm's housekeeper garland the hearth and pray to the Lar familiaris on the Kalends, Nones and Ides.",
    sources: ["https://en.wikipedia.org/wiki/Lares"],
    serves: ["household-home"],
  },
  {
    id: "day.rome.nundinae",
    label: "Market on the nundinae",
    scope: ROMAN,
    evidence: "documented",
    when: [{ type: "cycle", every: 8, on: 3 }, { type: "adult" }],
    weight: 6,
    part: "midday",
    place: "market",
    activity: "visit",
    minutes: 45,
    carry: "basket",
    text: "Go to the market: it is the nundinae.",
    note: "Every eighth day country people came into town to sell, and the children had no school.",
    sources: ["https://en.wikipedia.org/wiki/Nundinae"],
  },
  {
    id: "day.rome.genius",
    label: "Birthday offering to the Genius",
    scope: ROMAN,
    evidence: "documented",
    when: [{ type: "anniversary", kind: "born-self" }, { type: "sex", is: "male" }],
    weight: 14,
    part: "morning",
    place: "hearth",
    activity: "visit",
    minutes: 25,
    carry: "basket",
    text: "Offer wine, incense and a cake to your Genius: it is your birthday.",
    sources: ["https://en.wikipedia.org/wiki/Genius_(mythology)"],
  },
  {
    id: "day.rome.juno",
    label: "Birthday offering to her Juno",
    scope: ROMAN,
    evidence: "documented",
    when: [{ type: "anniversary", kind: "born-self" }, { type: "sex", is: "female" }],
    weight: 14,
    part: "morning",
    place: "hearth",
    activity: "visit",
    minutes: 25,
    carry: "basket",
    text: "Offer wine and a cake to your Juno: it is your birthday.",
    note: "A woman's guardian spirit was her Juno, as a man's was his Genius.",
    sources: ["https://en.wikipedia.org/wiki/Juno_(mythology)"],
  },
  {
    id: "day.rome.parentalia",
    label: "The Parentalia",
    scope: ROMAN,
    evidence: "documented",
    when: [{ type: "date", dayOfYear: 44 }, { type: "adult" }],
    weight: 12,
    part: "midday",
    place: "edge",
    activity: "visit",
    minutes: 45,
    carry: "basket",
    text: "Bring bread, salt and violets to the family tomb on the road out of town.",
    note: "Ovid lists the modest gifts: a tile with garlands, scattered grain, salt, bread soaked in wine, violets.",
    sources: ["https://en.wikipedia.org/wiki/Parentalia"],
    serves: ["remember-dead"],
  },
  {
    id: "day.rome.vestalia",
    label: "The Vestalia",
    scope: ROMAN,
    evidence: "documented",
    when: [{ type: "date", dayOfYear: 160 }, { type: "work", match: /bak|mill|bread|oven/i }],
    weight: 14,
    part: "morning",
    place: "work",
    activity: "tend",
    minutes: 30,
    text: "Garland the mill-donkeys and let the millstones rest for Vesta.",
    sources: ["https://en.wikipedia.org/wiki/Vestalia"],
  },
  {
    id: "day.rome.parilia",
    label: "The Parilia",
    scope: ROMAN,
    evidence: "documented",
    when: [{ type: "date", dayOfYear: 111 }, { type: "work", match: /herd|shep|flock|goat/i }],
    weight: 14,
    part: "evening",
    place: "edge",
    activity: "visit",
    minutes: 40,
    text: "Sweep the fold, light the straw fires and leap them for Pales.",
    sources: ["https://en.wikipedia.org/wiki/Parilia"],
  },
  {
    id: "day.rome.salutatio",
    label: "The morning call on a patron",
    scope: ROMAN,
    evidence: "documented",
    when: [{ type: "rank", any: ["labouring", "middling"] }, { type: "chance", p: 0.25 }, { type: "adult" }],
    weight: 3,
    part: "morning",
    place: "door",
    activity: "visit",
    minutes: 30,
    text: "Stand in the line of clients at your patron's door for the morning greeting.",
    sources: ["https://en.wikipedia.org/wiki/Salutatio"],
  },
  {
    id: "day.rome.baths",
    label: "The baths",
    scope: ROMAN,
    evidence: "documented",
    when: [{ type: "chance", p: 0.25 }],
    weight: 3,
    part: "evening",
    place: { venue: "bath" },
    activity: "visit",
    minutes: 60,
    text: "Go to the baths once the work is done.",
    sources: ["https://en.wikipedia.org/wiki/Thermae"],
  },
];

export const romanFestivals: Festival[] = [
  {
    id: "fest.rome.saturnalia",
    label: "the Saturnalia",
    scope: ROMAN,
    evidence: "documented",
    date: { dayOfYear: 351 },
    rest: true,
    place: "gathering",
    minutes: 150,
    text: "It is the Saturnalia: no work, gifts, gambling in the open, and a feast.",
    sources: ["https://en.wikipedia.org/wiki/Saturnalia"],
  },
  {
    id: "fest.rome.compitalia",
    label: "the Compitalia",
    scope: ROMAN,
    evidence: "documented",
    date: { dayOfYear: 4 },
    rest: true,
    place: "gathering",
    minutes: 90,
    text: "It is the Compitalia: hang a woollen doll for each of the household at the crossroads shrine.",
    sources: ["https://en.wikipedia.org/wiki/Compitalia"],
  },
];
