import type { Festival, Occasion } from "./types";

type Bounds = [number, number, number, number];
type Years = [number, number];
const cultures = ["south-asian" as const];
const SUBCONTINENT: Bounds = [60, 5, 93, 37];

const MEHRGARH = { years: [-7000, -2600] as Years, bounds: [62, 25, 70, 31] as Bounds, cultures };
const DECCAN_ASH = { years: [-3000, -1200] as Years, bounds: [74, 13, 79, 17.5] as Bounds, cultures };
const INDUS = { years: [-2600, -1900] as Years, bounds: [62, 22, 77, 33] as Bounds, cultures };
const VEDIC = { years: [-1500, -500] as Years, bounds: [68, 23, 88, 34] as Bounds, cultures };
const MAGADHA = { years: [-600, -185] as Years, bounds: [72, 20, 90, 31] as Bounds, cultures };
const BUDDHIST_NORTH = { years: [-450, 1200] as Years, bounds: [72, 18, 90, 30] as Bounds, cultures };
const LANKA = { years: [-250, 1950] as Years, bounds: [79, 5, 82.5, 10] as Bounds, cultures };
const JAIN = { years: [-300, 1950] as Years, bounds: [68, 19, 78, 28] as Bounds, cultures };
const HINDU = { years: [300, 1950] as Years, bounds: SUBCONTINENT, cultures };
const NORTH = { years: [800, 1950] as Years, bounds: [68, 21, 90, 32] as Bounds, cultures };
const TAMIL = { years: [600, 1950] as Years, bounds: [76.9, 8, 81, 14] as Bounds, cultures };
const CHOLA = { years: [850, 1280] as Years, bounds: [77, 9, 81, 13.5] as Bounds, cultures };
const KERALA = { years: [800, 1950] as Years, bounds: [74.5, 8, 76.9, 12.8] as Bounds, cultures };
const BENGAL = { years: [1200, 1950] as Years, bounds: [85.5, 20.5, 93, 27] as Bounds, cultures };
const PUNJAB = { years: [1540, 1950] as Years, bounds: [72, 29, 78, 33] as Bounds, cultures };
const MUGHAL = { years: [1560, 1760] as Years, bounds: [73, 25, 81, 32] as Bounds, cultures };
const MUSLIM = { years: [1200, 1950] as Years, bounds: SUBCONTINENT, cultures };
const BIDAR = { years: [1420, 1950] as Years, bounds: [76.5, 17.3, 78, 18.5] as Bounds, cultures };
const KONKAN = { years: [1600, 1950] as Years, bounds: [72.5, 15, 73.5, 21] as Bounds, cultures };
const COLONIAL = { years: [1860, 1950] as Years, bounds: SUBCONTINENT, cultures };
const MILL_TOWNS = { years: [1870, 1950] as Years, bounds: [72, 18.8, 73.2, 23.3] as Bounds, cultures };

export const southAsiaOccasions: Occasion[] = [
  {
    id: "day.mehrgarh.granary",
    label: "Sweeping the granary cells",
    scope: MEHRGARH,
    evidence: "inferred",
    when: [{ type: "season", any: ["spring"] }, { type: "adult" }, { type: "chance", p: 0.35 }],
    weight: 5,
    part: "morning",
    place: "home",
    activity: "haul",
    minutes: 40,
    carry: "basket",
    text: "Sweep out the mud-brick storage cells before the new barley goes in.",
    note: "Mehrgarh's compartmented mud-brick buildings are read as granaries for six-row barley and wheat.",
    sources: ["https://en.wikipedia.org/wiki/Mehrgarh"],
    serves: ["household-home"],
  },
  {
    id: "day.mehrgarh.molar",
    label: "The bead-driller's dentistry",
    scope: MEHRGARH,
    evidence: "documented",
    when: [{ type: "adult" }, { type: "chance", p: 0.06 }],
    weight: 4,
    part: "midday",
    place: "door",
    activity: "visit",
    minutes: 30,
    text: "Sit still while the bead-driller bores out your rotten molar with a flint bit.",
    note: "Eleven drilled molars from Mehrgarh graves, about 7000-5500 BCE, are the oldest known dentistry.",
    sources: ["https://en.wikipedia.org/wiki/Mehrgarh"],
  },
  {
    id: "day.mehrgarh.grave",
    label: "Beads for the dead",
    scope: MEHRGARH,
    evidence: "hypothesis",
    when: [{ type: "anniversary", kind: "died" }],
    weight: 16,
    part: "evening",
    place: "edge",
    activity: "visit",
    minutes: 35,
    text: "Leave a string of beads and a smear of red ochre at the grave of your {dead}.",
    note: "Burials with beads, ochre and even young goats are documented; returning on a death's day is a guess.",
    sources: ["https://en.wikipedia.org/wiki/Mehrgarh"],
    serves: ["remember-dead"],
  },
  {
    id: "day.deccan.ash-mound",
    label: "Firing the dung heap",
    scope: DECCAN_ASH,
    evidence: "hypothesis",
    when: [{ type: "work", match: /herd|cattle|cow|drover|pastor/i }, { type: "season", any: ["spring", "autumn"] }],
    weight: 6,
    part: "evening",
    place: "edge",
    activity: "tend",
    minutes: 50,
    text: "Heap up the cattle dung by the pen and set the whole mound burning.",
    note: "The Neolithic ash mounds of Utnur and Budihal are layers of burnt dung; a seasonal fire rite is one reading.",
    sources: ["https://en.wikipedia.org/wiki/Southern_Neolithic"],
  },
  {
    id: "day.indus.seal",
    label: "Sealing the bales",
    scope: INDUS,
    evidence: "documented",
    when: [{ type: "work", match: /merchant|trad|seller|dealer|caravan/i }, { type: "chance", p: 0.4 }],
    weight: 6,
    part: "morning",
    place: "work",
    activity: "work",
    minutes: 30,
    carry: "bundle",
    text: "Press your unicorn seal into the clay tag on every bale before it leaves.",
    note: "Clay sealings with cord and cloth impressions on their backs show seals were stamped on tied goods.",
    sources: ["https://en.wikipedia.org/wiki/Indus_script"],
  },
  {
    id: "day.indus.weights",
    label: "Checking the weights",
    scope: INDUS,
    evidence: "documented",
    when: [{ type: "work", match: /merchant|trad|seller|dealer|market/i }, { type: "chance", p: 0.3 }],
    weight: 5,
    part: "midday",
    place: "market",
    activity: "work",
    minutes: 25,
    text: "Check your chert cube weights against the city's standard set.",
    note: "Harappan weights double from 1 to 64 and then run in decimals, the same from Sindh to Gujarat.",
    sources: ["https://en.wikipedia.org/wiki/Indus_Valley_Civilisation"],
  },
  {
    id: "day.indus.beads",
    label: "Drilling carnelian",
    scope: INDUS,
    evidence: "documented",
    when: [{ type: "work", match: /bead|jewel|lapid|stone|craft/i }],
    weight: 6,
    part: "midday",
    place: "work",
    activity: "work",
    minutes: 50,
    text: "Bore a long carnelian bead with an Ernestite drill, a little water at a time.",
    note: "Workshops at Chanhu-daro drilled beads up to 13 cm long with a hard stone called Ernestite.",
    sources: ["https://en.wikipedia.org/wiki/Chanhudaro"],
    serves: ["mastery"],
  },
  {
    id: "day.indus.bath",
    label: "Bathing at the great tank",
    scope: INDUS,
    evidence: "hypothesis",
    when: [{ type: "observance", levels: ["devout", "regular"] }, { type: "adult" }, { type: "chance", p: 0.25 }],
    weight: 4,
    part: "morning",
    place: "sanctuary",
    activity: "visit",
    minutes: 30,
    text: "Bathe in the bitumen-lined tank on the citadel mound before the day's work.",
    note: "The Great Bath is certain; that it served ritual purification is the usual, unproven reading.",
    sources: ["https://en.wikipedia.org/wiki/Great_Bath,_Mohenjo-daro"],
  },
  {
    id: "day.vedic.agnihotra",
    label: "The agnihotra",
    scope: VEDIC,
    evidence: "documented",
    when: [{ type: "sex", is: "male" }, { type: "adult" }, { type: "observance", levels: ["devout", "regular"] }],
    weight: 6,
    part: "morning",
    place: "hearth",
    activity: "tend",
    minutes: 20,
    carry: "vessel",
    text: "Pour hot milk into the household fire at sunrise: the agnihotra to Agni and Surya.",
    sources: ["https://en.wikipedia.org/wiki/Agnihotra"],
    serves: ["household-home"],
  },
  {
    id: "day.vedic.new-moon",
    label: "The new-moon offering",
    scope: VEDIC,
    evidence: "documented",
    when: [{ type: "cycle", every: 9, on: 0 }, { type: "adult" }, { type: "observance", levels: ["devout", "regular", "occasional"] }],
    weight: 8,
    part: "morning",
    place: "hearth",
    activity: "cook",
    minutes: 40,
    text: "Bake rice cakes on potsherds for the fire: it is the new moon.",
    note: "The darsha-purnamasa offerings of cakes (purodasha) fell on each new and full moon.",
    sources: ["https://en.wikipedia.org/wiki/Shrauta"],
  },
  {
    id: "day.vedic.upanayana",
    label: "Taking a son to his teacher",
    scope: { ...VEDIC, years: [-1000, 1950] as Years, bounds: SUBCONTINENT },
    evidence: "documented",
    when: [{ type: "kin", kind: "child", minAge: 8, maxAge: 12 }, { type: "rank", any: ["middling", "gentry", "elite"] }, { type: "chance", p: 0.1 }],
    weight: 5,
    part: "morning",
    place: { venue: "school" },
    activity: "visit",
    minutes: 45,
    text: "Walk {child} to the teacher's house to settle the day of the sacred thread.",
    sources: ["https://en.wikipedia.org/wiki/Upanayana"],
    serves: ["child-future"],
  },
  {
    id: "day.magadha.karshapana",
    label: "Counting punch-marked silver",
    scope: MAGADHA,
    evidence: "documented",
    when: [{ type: "work", match: /merchant|trad|seller|dealer|caravan|money/i }, { type: "chance", p: 0.35 }],
    weight: 5,
    part: "evening",
    place: "home",
    activity: "work",
    minutes: 30,
    text: "Count your bent-bar and punch-marked silver before the caravan leaves for Taxila.",
    sources: ["https://en.wikipedia.org/wiki/Punch-marked_coins"],
  },
  {
    id: "day.maurya.edict",
    label: "Hearing the edict",
    scope: { years: [-260, -230] as Years, bounds: [66, 12, 90, 35] as Bounds, cultures },
    evidence: "documented",
    when: [{ type: "cycle", every: 9, on: 4 }, { type: "adult" }],
    weight: 8,
    part: "midday",
    place: "gathering",
    activity: "visit",
    minutes: 30,
    text: "Stand at the pillar while the officer reads out Devanampiya's edict on the Tishya day.",
    note: "The Kalinga edicts ask that they be read aloud on Tishya days, and even in between to a single listener.",
    sources: ["https://en.wikipedia.org/wiki/Edicts_of_Ashoka"],
  },
  {
    id: "day.buddhist.uposatha",
    label: "The uposatha day",
    scope: BUDDHIST_NORTH,
    evidence: "documented",
    when: [{ type: "cycle", every: 9, on: 4 }, { type: "adult" }, { type: "observance", levels: ["devout", "regular"] }],
    weight: 8,
    part: "evening",
    place: "sanctuary",
    activity: "visit",
    minutes: 60,
    text: "Keep the eight precepts and go to hear the monks recite: it is uposatha.",
    sources: ["https://en.wikipedia.org/wiki/Uposatha"],
  },
  {
    id: "day.buddhist.alms",
    label: "Filling the alms bowls",
    scope: BUDDHIST_NORTH,
    evidence: "documented",
    when: [{ type: "adult" }, { type: "observance", levels: ["devout", "regular", "occasional"] }, { type: "chance", p: 0.3 }],
    weight: 4,
    part: "morning",
    place: "home",
    activity: "cook",
    minutes: 20,
    carry: "vessel",
    text: "Spoon rice into the monks' bowls as they pass your door in silence.",
    sources: ["https://en.wikipedia.org/wiki/Pindapata"],
  },
  {
    id: "day.lanka.poya",
    label: "Poya at the dagoba",
    scope: LANKA,
    evidence: "documented",
    when: [{ type: "cycle", every: 9, on: 4 }, { type: "adult" }, { type: "observance", levels: ["devout", "regular", "occasional"] }],
    weight: 9,
    part: "evening",
    place: "sanctuary",
    activity: "visit",
    minutes: 50,
    carry: "basket",
    text: "Dress in white and carry jasmine to the dagoba: it is the full-moon poya.",
    sources: ["https://en.wikipedia.org/wiki/Poya"],
  },
  {
    id: "day.lanka.tank",
    label: "Clearing the tank sluice",
    scope: LANKA,
    evidence: "documented",
    when: [{ type: "season", any: ["autumn"] }, { type: "work", match: /farm|cultivat|paddy|rice|labour|plough/i }],
    weight: 6,
    part: "morning",
    place: "well",
    activity: "haul",
    minutes: 50,
    text: "Pull weed from the sluice of the village tank before the Maha sowing.",
    note: "The Maha rice season is sown with the north-east monsoon in October, from water held in the village wewa.",
    sources: ["https://en.wikipedia.org/wiki/Tank_cascade_system"],
  },
  {
    id: "day.jain.samayika",
    label: "Samayika",
    scope: JAIN,
    evidence: "documented",
    when: [{ type: "observance", levels: ["devout"] }, { type: "adult" }],
    weight: 5,
    part: "evening",
    place: "sanctuary",
    activity: "rest",
    minutes: 48,
    text: "Sit forty-eight minutes in samayika, still and even-minded towards every creature.",
    note: "One samayika lasts a muhurta, 48 minutes.",
    sources: ["https://en.wikipedia.org/wiki/S%C4%81m%C4%81yika"],
  },
  {
    id: "day.jain.paryushana",
    label: "Paryushana",
    scope: JAIN,
    evidence: "documented",
    when: [{ type: "date", dayOfYear: 245 }, { type: "adult" }],
    weight: 14,
    part: "evening",
    place: "sanctuary",
    activity: "visit",
    minutes: 60,
    text: "Ask forgiveness of neighbours and kin for the year's wrongs: Micchami dukkadam, it is Paryushana.",
    note: "Falls in Bhadrapada, late August to mid-September; the day here is a representative one.",
    sources: ["https://en.wikipedia.org/wiki/Paryushana"],
  },
  {
    id: "day.hindu.tulsi",
    label: "The lamp at the tulsi",
    scope: { ...NORTH, bounds: SUBCONTINENT },
    evidence: "documented",
    when: [{ type: "sex", is: "female" }, { type: "adult" }, { type: "observance", levels: ["devout", "regular"] }],
    weight: 5,
    part: "evening",
    place: "home",
    activity: "tend",
    minutes: 15,
    text: "Light a ghee lamp at the tulsi plant in the courtyard and walk round it.",
    sources: ["https://en.wikipedia.org/wiki/Ocimum_tenuiflorum"],
    serves: ["household-home"],
  },
  {
    id: "day.hindu.ekadashi",
    label: "Fasting for ekadashi",
    scope: { ...HINDU, years: [600, 1950] as Years },
    evidence: "documented",
    when: [{ type: "cycle", every: 9, on: 3 }, { type: "adult" }, { type: "observance", levels: ["devout", "regular"] }],
    weight: 7,
    part: "evening",
    place: "home",
    activity: "rest",
    minutes: 30,
    text: "Eat no grain and sing Vishnu's names instead: it is ekadashi.",
    note: "The eleventh day of each lunar fortnight; the game's short month keeps only one of the two.",
    sources: ["https://en.wikipedia.org/wiki/Ekadashi"],
  },
  {
    id: "day.hindu.shraddha",
    label: "The death-day shraddha",
    scope: HINDU,
    evidence: "documented",
    when: [{ type: "anniversary", kind: "died" }],
    weight: 16,
    part: "midday",
    place: "home",
    activity: "cook",
    minutes: 60,
    text: "Set out rice balls and sesame for your {dead}, {years} years gone, before feeding a Brahmin.",
    sources: ["https://en.wikipedia.org/wiki/Shraddha"],
    serves: ["remember-dead", "widowed-household"],
  },
  {
    id: "day.hindu.pitru-paksha",
    label: "Water for the fathers",
    scope: HINDU,
    evidence: "documented",
    when: [{ type: "date", dayOfYear: 262 }, { type: "adult" }],
    weight: 13,
    part: "morning",
    place: { venue: "washing-place" },
    activity: "visit",
    minutes: 30,
    carry: "vessel",
    text: "Pour water and black sesame from your cupped hands for the fathers: it is Pitru Paksha.",
    note: "The dark fortnight of Bhadrapada, usually in September.",
    sources: ["https://en.wikipedia.org/wiki/Pitru_Paksha"],
    serves: ["remember-dead"],
  },
  {
    id: "day.hindu.annaprashana",
    label: "The first rice",
    scope: HINDU,
    evidence: "documented",
    when: [{ type: "kin", kind: "child", maxAge: 1 }, { type: "chance", p: 0.1 }],
    weight: 8,
    part: "midday",
    place: "home",
    activity: "cook",
    minutes: 40,
    text: "Feed {child} a first mouthful of rice and milk, while the family watches.",
    sources: ["https://en.wikipedia.org/wiki/Annaprashana"],
    serves: ["raise-kin"],
  },
  {
    id: "day.hindu.horoscope",
    label: "Matching horoscopes",
    scope: HINDU,
    evidence: "documented",
    when: [{ type: "seek-match" }],
    weight: 6,
    part: "midday",
    place: "door",
    activity: "visit",
    minutes: 45,
    text: "Carry {child}'s horoscope to the astrologer to test it against the other family's.",
    sources: ["https://en.wikipedia.org/wiki/Hindu_astrology"],
    serves: ["marriage-hope"],
  },
  {
    id: "day.hindu.karva-chauth",
    label: "Karva Chauth",
    scope: { ...NORTH, years: [1600, 1950] as Years, bounds: [70, 24, 80, 33] as Bounds },
    evidence: "documented",
    when: [{ type: "date", dayOfYear: 300 }, { type: "sex", is: "female" }, { type: "kin", kind: "partner" }],
    weight: 14,
    part: "evening",
    place: "home",
    activity: "rest",
    minutes: 50,
    text: "Fast from dawn until the moon rises, for {partner}'s long life.",
    note: "Falls on the fourth after the Kartik full moon, October or November.",
    sources: ["https://en.wikipedia.org/wiki/Karva_Chauth"],
  },
  {
    id: "day.hindu.pilgrims",
    label: "Seeing off the pilgrims",
    scope: { ...NORTH, bounds: SUBCONTINENT },
    evidence: "documented",
    when: [{ type: "adult" }, { type: "chance", p: 0.06 }],
    weight: 5,
    part: "morning",
    place: "edge",
    activity: "visit",
    minutes: 30,
    text: "See the neighbours off to the road on their pilgrimage to Kashi, and ask for Ganga water.",
    sources: ["https://en.wikipedia.org/wiki/Varanasi"],
  },
  {
    id: "day.hindu.potter",
    label: "The goddess's pot",
    scope: HINDU,
    evidence: "inferred",
    when: [{ type: "work", match: /pott|kiln|clay/i }, { type: "chance", p: 0.35 }],
    weight: 5,
    part: "morning",
    place: "sanctuary",
    activity: "visit",
    minutes: 20,
    carry: "vessel",
    text: "Carry the first pot from the kiln to the village goddess's stone.",
    note: "Potters often serve as priests of village goddesses and make their horse and pot offerings.",
    sources: ["https://en.wikipedia.org/wiki/Gramadevata"],
  },
  {
    id: "day.hindu.jajmani",
    label: "Collecting the harvest share",
    scope: { ...HINDU, years: [1000, 1950] as Years },
    evidence: "documented",
    when: [{ type: "season", any: ["autumn"] }, { type: "work", match: /pott|smith|carpent|barber|wash|launder|leather|cobbl|sweep/i }],
    weight: 7,
    part: "midday",
    place: "door",
    activity: "haul",
    minutes: 50,
    carry: "basket",
    text: "Go round your patron households for your yearly share of the grain heap.",
    note: "Under jajmani ties, service castes were paid a fixed share at the threshing floor rather than by the job.",
    sources: ["https://en.wikipedia.org/wiki/Jajmani_system"],
  },
  {
    id: "day.monsoon.transplant",
    label: "Transplanting rice",
    scope: { years: [-1000, 1950] as Years, bounds: SUBCONTINENT, cultures },
    evidence: "documented",
    when: [{ type: "season", any: ["summer"] }, { type: "work", match: /farm|cultivat|paddy|rice|labour|share|tenant/i }],
    weight: 6,
    part: "morning",
    place: "work",
    activity: "tend",
    minutes: 90,
    text: "Transplant rice seedlings knee-deep in the flooded field, singing with the others.",
    sources: ["https://en.wikipedia.org/wiki/Monsoon_of_South_Asia"],
  },
  {
    id: "day.monsoon.teej",
    label: "The rain swings",
    scope: { ...NORTH, years: [1200, 1950] as Years, bounds: [68, 22, 85, 31] as Bounds },
    evidence: "documented",
    when: [{ type: "season", any: ["summer"] }, { type: "sex", is: "female" }, { type: "chance", p: 0.25 }],
    weight: 5,
    part: "evening",
    place: "gathering",
    activity: "play",
    minutes: 45,
    text: "Ride the swing hung from the neem tree with the other women: the rains have come.",
    sources: ["https://en.wikipedia.org/wiki/Teej"],
  },
  {
    id: "day.tamil.kolam",
    label: "Drawing the kolam",
    scope: TAMIL,
    evidence: "documented",
    when: [{ type: "sex", is: "female" }, { type: "adult" }, { type: "chance", p: 0.5 }],
    weight: 5,
    part: "morning",
    place: "home",
    activity: "tend",
    minutes: 15,
    text: "Draw a kolam of rice flour on the swept, wetted threshold before sunrise.",
    note: "Rice flour feeds ants and birds: the design is also an alms.",
    sources: ["https://en.wikipedia.org/wiki/Kolam"],
    serves: ["household-home"],
  },
  {
    id: "day.chola.lamp",
    label: "Ghee for the undying lamp",
    scope: CHOLA,
    evidence: "documented",
    when: [{ type: "work", match: /herd|shep|cow|cattle|milk/i }, { type: "chance", p: 0.3 }],
    weight: 6,
    part: "morning",
    place: "sanctuary",
    activity: "haul",
    minutes: 35,
    carry: "vessel",
    text: "Carry the temple's measure of ghee for the perpetual lamp: the endowment's sheep are in your care.",
    note: "Chola inscriptions record gifts of 90 or 96 sheep to shepherds, who owed ghee for a lamp in perpetuity.",
    sources: ["https://en.wikipedia.org/wiki/Brihadisvara_Temple,_Thanjavur"],
  },
  {
    id: "day.south.warp",
    label: "Stretching the warp",
    scope: { years: [600, 1950] as Years, bounds: [74, 8, 81, 17] as Bounds, cultures },
    evidence: "documented",
    when: [{ type: "work", match: /weav|loom|silk|cotton|spin/i }, { type: "chance", p: 0.4 }],
    weight: 5,
    part: "morning",
    place: "gathering",
    activity: "work",
    minutes: 60,
    text: "Brush rice starch into the warp stretched down the lane, before the sun is high.",
    sources: ["https://en.wikipedia.org/wiki/Kanchipuram_silk_sari"],
    serves: ["mastery"],
  },
  {
    id: "day.bengal.haat",
    label: "The weekly haat",
    scope: BENGAL,
    evidence: "documented",
    when: [{ type: "cycle", every: 7, on: 6 }, { type: "adult" }],
    weight: 6,
    part: "midday",
    place: "market",
    activity: "visit",
    minutes: 50,
    carry: "basket",
    text: "Carry your gourds and greens to the haat under the banyan: it is Tuesday.",
    note: "A village haat met on one or two fixed weekdays; Tuesday is a stand-in.",
    sources: ["https://en.wikipedia.org/wiki/Haat_bazaar"],
  },
  {
    id: "day.bengal.hilsa",
    label: "Rowing out for hilsa",
    scope: BENGAL,
    evidence: "documented",
    when: [{ type: "season", any: ["summer"] }, { type: "work", match: /fish|boat|net/i }],
    weight: 6,
    part: "morning",
    place: "work",
    activity: "work",
    minutes: 80,
    text: "Row out with the drift net after a bow to Ganga: the hilsa are running upriver.",
    sources: ["https://en.wikipedia.org/wiki/Ilish"],
  },
  {
    id: "day.konkan.narali",
    label: "A coconut for the sea",
    scope: KONKAN,
    evidence: "documented",
    when: [{ type: "date", dayOfYear: 225 }, { type: "work", match: /fish|boat|net|sail/i }],
    weight: 15,
    part: "morning",
    place: "edge",
    activity: "visit",
    minutes: 40,
    text: "Throw a coconut to the sea so the boats may go out again after the monsoon.",
    note: "Narali Purnima, the Shravan full moon of the Koli fishers, falls in August.",
    sources: ["https://en.wikipedia.org/wiki/Narali_Purnima"],
  },
  {
    id: "day.sikh.langar",
    label: "Rolling rotis for the langar",
    scope: PUNJAB,
    evidence: "documented",
    when: [{ type: "adult" }, { type: "observance", levels: ["devout", "regular"] }, { type: "chance", p: 0.3 }],
    weight: 5,
    part: "midday",
    place: "sanctuary",
    activity: "cook",
    minutes: 60,
    text: "Roll rotis for the langar, where everyone sits in one line.",
    sources: ["https://en.wikipedia.org/wiki/Langar_(Sikhism)"],
    serves: ["shared-future"],
  },
  {
    id: "day.sikh.sangrand",
    label: "Sangrand at the gurdwara",
    scope: PUNJAB,
    evidence: "documented",
    when: [{ type: "cycle", every: 9, on: 0 }, { type: "observance", levels: ["devout", "regular", "occasional"] }],
    weight: 7,
    part: "morning",
    place: "sanctuary",
    activity: "visit",
    minutes: 40,
    text: "Go to the gurdwara to hear the new month's Barah Maha verse: it is sangrand.",
    note: "Sangrand is the first of the solar month, when Guru Nanak's verse for that month is sung.",
    sources: ["https://en.wikipedia.org/wiki/Sankranti"],
  },
  {
    id: "day.muslim.dargah",
    label: "Thursday night at the dargah",
    scope: MUSLIM,
    evidence: "documented",
    when: [{ type: "cycle", every: 7, on: 1 }, { type: "tag", any: ["mystical", "devout"] }, { type: "chance", p: 0.4 }],
    weight: 5,
    part: "evening",
    place: "sanctuary",
    activity: "visit",
    minutes: 60,
    text: "Listen to the qawwali at the saint's tomb and leave a thread on its screen: it is Thursday night.",
    note: "Qawwali and visits to shrines are customary on Thursday evening, the eve of Friday.",
    sources: ["https://en.wikipedia.org/wiki/Dargah"],
  },
  {
    id: "day.mughal.karkhana",
    label: "At the imperial karkhana",
    scope: MUGHAL,
    evidence: "documented",
    when: [{ type: "work", match: /weav|paint|jewel|smith|embroider|carpet|goldsmith|armou?r/i }, { type: "chance", p: 0.3 }],
    weight: 5,
    part: "midday",
    place: "work",
    activity: "work",
    minutes: 60,
    carry: "bundle",
    text: "Hand in the week's piece at the karkhana, to be entered and weighed by the daroga.",
    note: "The Ain-i-Akbari describes the emperor's workshops, each under a daroga keeping accounts.",
    sources: ["https://en.wikipedia.org/wiki/Karkhana"],
  },
  {
    id: "day.deccan.bidri",
    label: "Blackening the bidri",
    scope: BIDAR,
    evidence: "documented",
    when: [{ type: "work", match: /smith|metal|found|cast|craft/i }, { type: "chance", p: 0.4 }],
    weight: 6,
    part: "midday",
    place: "work",
    activity: "work",
    minutes: 50,
    text: "Rub a paste of Bidar fort soil into the inlaid bowl until the zinc turns black.",
    note: "Bidriware's black comes from soil taken from under the fort walls, mixed with sal ammoniac.",
    sources: ["https://en.wikipedia.org/wiki/Bidriware"],
    serves: ["mastery"],
  },
  {
    id: "day.colonial.train",
    label: "Third class to the village",
    scope: { ...COLONIAL, years: [1870, 1950] as Years },
    evidence: "inferred",
    when: [{ type: "kin", kind: "parent" }, { type: "adult" }, { type: "chance", p: 0.04 }],
    weight: 4,
    part: "morning",
    place: "edge",
    activity: "visit",
    minutes: 60,
    carry: "bundle",
    text: "Squeeze into a third-class carriage to go and see {parent}.",
    sources: ["https://en.wikipedia.org/wiki/History_of_rail_transport_in_India"],
    serves: ["elder-kin"],
  },
  {
    id: "day.colonial.money-order",
    label: "Sending a money order",
    scope: { ...COLONIAL, years: [1880, 1950] as Years },
    evidence: "documented",
    when: [{ type: "rank", any: ["labouring", "destitute"] }, { type: "cycle", every: 9, on: 0 }, { type: "chance", p: 0.3 }],
    weight: 5,
    part: "midday",
    place: "market",
    activity: "visit",
    minutes: 40,
    text: "Queue at the post office to send a money order home to the village.",
    note: "Money orders from migrant labourers were a large share of Indian postal traffic by 1900.",
    sources: ["https://en.wikipedia.org/wiki/Money_order"],
    serves: ["restore-household"],
  },
  {
    id: "day.colonial.jobber",
    label: "Paying the jobber",
    scope: MILL_TOWNS,
    evidence: "documented",
    when: [{ type: "work", match: /mill|spinn|jute|cotton|factory|hand/i }, { type: "cycle", every: 9, on: 0 }],
    weight: 7,
    part: "evening",
    place: "door",
    activity: "visit",
    minutes: 25,
    text: "Pay the jobber his cut of your month's mill wages, to keep the place.",
    note: "In Bombay's cotton mills the jobber hired, fired and took a dasturi from each hand's pay.",
    sources: ["https://en.wikipedia.org/wiki/Girangaon"],
  },
  {
    id: "day.colonial.charkha",
    label: "The daily yarn",
    scope: { years: [1920, 1948] as Years, bounds: SUBCONTINENT, cultures },
    evidence: "documented",
    when: [{ type: "tag", any: ["reformist", "revolutionary", "civic", "ascetic"] }, { type: "adult" }],
    weight: 5,
    part: "evening",
    place: "home",
    activity: "work",
    minutes: 30,
    text: "Spin your half hour of khadi yarn on the charkha, as Gandhiji asks.",
    sources: ["https://en.wikipedia.org/wiki/Khadi"],
  },
];

export const southAsiaFestivals: Festival[] = [
  {
    id: "fest.south-asia.diwali",
    label: "Diwali",
    scope: { years: [500, 1950] as Years, bounds: [66, 8, 93, 35] as Bounds, cultures },
    evidence: "documented",
    date: { dayOfYear: 305 },
    rest: true,
    place: "gathering",
    minutes: 120,
    text: "It is Diwali: clay lamps on every ledge, sweets for the neighbours, and Lakshmi welcomed in.",
    note: "The new moon of Kartika, which falls between mid-October and mid-November.",
    sources: ["https://en.wikipedia.org/wiki/Diwali"],
  },
  {
    id: "fest.north-india.holi",
    label: "Holi",
    scope: { years: [700, 1950] as Years, bounds: [68, 20, 90, 32] as Bounds, cultures },
    evidence: "documented",
    date: { dayOfYear: 75 },
    rest: true,
    place: "gathering",
    minutes: 120,
    text: "It is Holi: last night's bonfire is ash, and everyone is throwing coloured powder and water.",
    note: "The Phalguna full moon, late February to late March.",
    sources: ["https://en.wikipedia.org/wiki/Holi"],
  },
  {
    id: "fest.tamil.pongal",
    label: "Pongal",
    scope: { ...TAMIL, years: [1000, 1950] as Years },
    evidence: "documented",
    date: { dayOfYear: 14 },
    rest: true,
    place: "hearth",
    minutes: 90,
    text: "It is Pongal: new rice boils over in a new pot, and the cattle get painted horns.",
    sources: ["https://en.wikipedia.org/wiki/Pongal_(festival)"],
  },
  {
    id: "fest.north-india.sankranti",
    label: "Makar Sankranti",
    scope: { years: [800, 1950] as Years, bounds: [68, 15, 90, 32] as Bounds, cultures },
    evidence: "documented",
    date: { dayOfYear: 14 },
    rest: false,
    place: "edge",
    minutes: 60,
    text: "It is Makar Sankranti: bathe in the river, eat sesame sweets, and fly kites.",
    sources: ["https://en.wikipedia.org/wiki/Makar_Sankranti"],
  },
  {
    id: "fest.bengal.durga-puja",
    label: "Durga Puja",
    scope: { ...BENGAL, years: [1600, 1950] as Years },
    evidence: "documented",
    date: { dayOfYear: 285 },
    rest: true,
    place: "sanctuary",
    minutes: 150,
    text: "It is Durga Puja: the goddess stands in the pandal, and there are drums until late.",
    note: "Ashvin, late September to October; household pujas of zamindars came first, public ones from the 1790s.",
    sources: ["https://en.wikipedia.org/wiki/Durga_Puja"],
  },
  {
    id: "fest.lanka.vesak",
    label: "Vesak",
    scope: LANKA,
    evidence: "documented",
    date: { dayOfYear: 135 },
    rest: true,
    place: "sanctuary",
    minutes: 120,
    text: "It is Vesak: lanterns hang at every door and there is free food by the road.",
    note: "The full moon of Vesak, usually May.",
    sources: ["https://en.wikipedia.org/wiki/Vesak"],
  },
  {
    id: "fest.punjab.vaisakhi",
    label: "Vaisakhi",
    scope: PUNJAB,
    evidence: "documented",
    date: { dayOfYear: 104 },
    rest: true,
    place: "gathering",
    minutes: 120,
    text: "It is Vaisakhi: the wheat is ready, and the gurdwara fair runs with bhangra.",
    note: "A solar date, 13 or 14 April; the Khalsa was founded on it in 1699.",
    sources: ["https://en.wikipedia.org/wiki/Vaisakhi"],
  },
  {
    id: "fest.kerala.onam",
    label: "Onam",
    scope: KERALA,
    evidence: "documented",
    date: { dayOfYear: 240 },
    rest: true,
    place: "gathering",
    minutes: 120,
    text: "It is Onam: flower carpets at the doors, a feast on banana leaves, and boat races.",
    note: "Thiruvonam in the month of Chingam, August to September.",
    sources: ["https://en.wikipedia.org/wiki/Onam"],
  },
  {
    id: "fest.awadh.muharram",
    label: "Muharram",
    scope: { years: [1750, 1950] as Years, bounds: [79, 25, 83.5, 28.5] as Bounds, cultures },
    evidence: "documented",
    date: { dayOfYear: 200 },
    rest: false,
    place: "gathering",
    minutes: 90,
    text: "It is Ashura: the taziya go by in procession to the karbala ground, to mourning chants.",
    note: "The Hijri calendar moves through the whole solar year every 33 years; the day here is arbitrary.",
    sources: ["https://en.wikipedia.org/wiki/Mourning_of_Muharram"],
  },
  {
    id: "fest.sindh-punjab.eid",
    label: "Eid al-Fitr",
    scope: { years: [1200, 1950] as Years, bounds: [66, 23, 75, 34] as Bounds, cultures },
    evidence: "documented",
    date: { dayOfYear: 110 },
    rest: true,
    place: "gathering",
    minutes: 120,
    text: "It is Eid: prayers at the idgah, sweet vermicelli, and new clothes for the children.",
    note: "The Hijri date drifts through the solar year; the day here is arbitrary.",
    sources: ["https://en.wikipedia.org/wiki/Eid_al-Fitr"],
  },
];
