import type { Festival, Occasion } from "./types";

type Box = [number, number, number, number];
const SEA = ["southeast-asian" as const];
const PAC = ["australian-pacific" as const];

const HOABINHIAN = { years: [-12000, -2500] as [number, number], bounds: [97, 8, 110, 25] as Box, cultures: SEA };
const BETEL = { years: [-2500, 1950] as [number, number], bounds: [92, -11, 130, 25] as Box, cultures: SEA };
const ISLAND_NEOLITHIC = { years: [-2500, 900] as [number, number], bounds: [95, -11, 130, 22] as Box, cultures: SEA };
const PHILIPPINE_JARS = { years: [-1000, 1000] as [number, number], bounds: [117, 5, 127, 20] as Box, cultures: SEA };
const DONG_SON = { years: [-1000, 43] as [number, number], bounds: [102, 17, 109, 23.5] as Box, cultures: SEA };
const FUNAN = { years: [100, 650] as [number, number], bounds: [99, 8, 107, 14] as Box, cultures: SEA };
const ANGKOR = { years: [800, 1432] as [number, number], bounds: [102, 10, 107, 15.5] as Box, cultures: SEA };
const CHAMPA = { years: [400, 1472] as [number, number], bounds: [107, 10.5, 109.5, 16.5] as Box, cultures: SEA };
const DAI_VIET = { years: [1010, 1950] as [number, number], bounds: [102, 17, 108.5, 23.5] as Box, cultures: SEA };
const THERAVADA = { years: [1050, 1950] as [number, number], bounds: [92, 9, 103, 28] as Box, cultures: SEA };
const BURMA = { years: [1050, 1950] as [number, number], bounds: [92, 10, 98.5, 28] as Box, cultures: SEA };
const SIAM = { years: [1350, 1950] as [number, number], bounds: [98.5, 6, 105, 20.5] as Box, cultures: SEA };
const SRIVIJAYA = { years: [650, 1300] as [number, number], bounds: [98, -6, 107, 4] as Box, cultures: SEA };
const JAVA = { years: [700, 1950] as [number, number], bounds: [105, -9, 114.4, -5] as Box, cultures: SEA };
const CENTRAL_JAVA = { years: [760, 860] as [number, number], bounds: [109, -8.3, 111.5, -6.5] as Box, cultures: SEA };
const JAVA_BALI = { years: [900, 1950] as [number, number], bounds: [105, -9, 116, -5] as Box, cultures: SEA };
const BALI = { years: [1000, 1950] as [number, number], bounds: [114.4, -8.9, 115.8, -8] as Box, cultures: SEA };
const MALAY_ISLAM = { years: [1400, 1950] as [number, number], bounds: [95, -9, 114.4, 7] as Box, cultures: SEA };
const PHILIPPINES = { years: [900, 1950] as [number, number], bounds: [117, 5, 127, 20] as Box, cultures: SEA };
const SPANISH_PHILIPPINES = { years: [1590, 1950] as [number, number], bounds: [117, 9, 127, 20] as Box, cultures: SEA };
const COLONIAL_SEA = { years: [1880, 1950] as [number, number], bounds: [95, -9, 120, 20] as Box, cultures: SEA };

const AUSTRALIA = { years: [-60000, 1950] as [number, number], bounds: [112, -44, 154, -10] as Box, cultures: PAC };
const AUSTRALIAN_ALPS = { years: [-2000, 1900] as [number, number], bounds: [145, -38, 150.5, -34.5] as Box, cultures: PAC };
const BUDJ_BIM = { years: [-4700, 1950] as [number, number], bounds: [140.5, -39, 144, -36.5] as Box, cultures: PAC };
const COLONIAL_AUSTRALIA = { years: [1814, 1920] as [number, number], bounds: [140, -39, 154, -25] as Box, cultures: PAC };
const NG_HIGHLANDS = { years: [-7000, 1950] as [number, number], bounds: [141, -7.5, 147, -4.5] as Box, cultures: PAC };
const TROBRIANDS = { years: [1200, 1950] as [number, number], bounds: [150.5, -9.5, 151.5, -8] as Box, cultures: PAC };
const LAPITA = { years: [-1500, -500] as [number, number], bounds: [145, -23, 180, -2] as Box, cultures: PAC };
const TONGA_SAMOA = { years: [1000, 1950] as [number, number], bounds: [-176.5, -22.5, -168, -13] as Box, cultures: PAC };
const TONGA = { years: [1875, 1950] as [number, number], bounds: [-176.5, -22.5, -173, -15] as Box, cultures: PAC };
const HAWAII = { years: [1000, 1950] as [number, number], bounds: [-161, 18, -154, 23] as Box, cultures: PAC };
const AOTEAROA = { years: [1300, 1950] as [number, number], bounds: [165, -48, 179, -34] as Box, cultures: PAC };
const YAP = { years: [1400, 1950] as [number, number], bounds: [137.5, 8.5, 138.5, 10] as Box, cultures: PAC };
const CAROLINES = { years: [1000, 1950] as [number, number], bounds: [143, 5, 154, 10] as Box, cultures: PAC };

export const southeastAsiaPacificOccasions: Occasion[] = [
  {
    id: "day.hoabinh.snails",
    label: "Snails from the shallows",
    scope: HOABINHIAN,
    evidence: "documented",
    when: [{ type: "chance", p: 0.35 }],
    weight: 4,
    part: "midday",
    place: "wild",
    activity: "gather",
    minutes: 40,
    carry: "basket",
    text: "Gather river snails from the shallows, to roast with their tips snapped off.",
    note: "Hoabinhian rock-shelter middens are thick with freshwater snail shells, their spires broken off to suck out the meat.",
    sources: ["https://en.wikipedia.org/wiki/Hoabinhian"],
  },
  {
    id: "day.sea.betel",
    label: "Betel with a friend",
    scope: BETEL,
    evidence: "documented",
    when: [{ type: "kin", kind: "friend" }, { type: "adult" }, { type: "chance", p: 0.3 }],
    weight: 4,
    part: "evening",
    place: { kin: "friend" },
    activity: "visit",
    minutes: 30,
    text: "Share areca nut, lime and betel leaf with {friend}.",
    note: "Betel-stained teeth from Duyong Cave in Palawan date to about 3000 years ago.",
    sources: ["https://en.wikipedia.org/wiki/Areca_nut"],
  },
  {
    id: "day.austronesian.outrigger",
    label: "Lashing the outrigger",
    scope: ISLAND_NEOLITHIC,
    evidence: "inferred",
    when: [{ type: "work", match: /fish|boat|canoe|sail/i }, { type: "chance", p: 0.3 }],
    weight: 5,
    part: "morning",
    place: "edge",
    activity: "work",
    minutes: 50,
    carry: "bundle",
    text: "Lash a new float to your canoe's outrigger with rattan.",
    sources: ["https://en.wikipedia.org/wiki/Outrigger_boat"],
  },
  {
    id: "day.philippines.jar-burial",
    label: "The bones to the jar",
    scope: PHILIPPINE_JARS,
    evidence: "inferred",
    when: [{ type: "anniversary", kind: "died" }],
    weight: 14,
    part: "midday",
    place: "edge",
    activity: "visit",
    minutes: 50,
    carry: "vessel",
    text: "Lay the washed bones of your {dead} in the burial jar.",
    note: "The Manunggul jar from Palawan held cleaned bones in a second burial; the lid shows two souls rowing to the afterworld.",
    sources: ["https://en.wikipedia.org/wiki/Manunggul_Jar"],
    serves: ["remember-dead"],
  },
  {
    id: "day.dongson.drum",
    label: "Beating the bronze drum",
    scope: DONG_SON,
    evidence: "hypothesis",
    when: [{ type: "season", any: ["spring", "summer"] }, { type: "chance", p: 0.15 }],
    weight: 5,
    part: "evening",
    place: "gathering",
    activity: "visit",
    minutes: 40,
    text: "Beat the bronze drum with the others to call the rains.",
    note: "Later drums carry cast frogs on the tympanum, and frogs call the rain in the region's folklore.",
    sources: ["https://en.wikipedia.org/wiki/Dong_Son_culture"],
  },
  {
    id: "day.funan.oc-eo",
    label: "Trading at Oc Eo",
    scope: FUNAN,
    evidence: "documented",
    when: [{ type: "work", match: /merchant|trade|bead|jewel|gold/i }, { type: "chance", p: 0.35 }],
    weight: 6,
    part: "midday",
    place: "market",
    activity: "visit",
    minutes: 45,
    carry: "bundle",
    text: "Trade glass beads and gold rings with the Indian ships at the Oc Eo quay.",
    note: "Oc Eo has yielded Indian seals, Chinese mirrors and a gold medallion of Antoninus Pius.",
    sources: ["https://en.wikipedia.org/wiki/Oc_Eo"],
  },
  {
    id: "day.angkor.temple-rice",
    label: "Rice for the temple",
    scope: ANGKOR,
    evidence: "documented",
    when: [{ type: "rank", any: ["labouring", "destitute"] }, { type: "adult" }, { type: "chance", p: 0.2 }],
    weight: 5,
    part: "morning",
    place: "sanctuary",
    activity: "haul",
    minutes: 45,
    carry: "basket",
    text: "Carry your village's due of husked rice to the temple storehouse.",
    note: "The Ta Prohm stele lists 3,140 villages bound to supply the temple.",
    sources: ["https://en.wikipedia.org/wiki/Ta_Prohm"],
  },
  {
    id: "day.champa.linga",
    label: "Water over the linga",
    scope: CHAMPA,
    evidence: "documented",
    when: [{ type: "observance", levels: ["devout", "regular"] }, { type: "adult" }, { type: "chance", p: 0.3 }],
    weight: 5,
    part: "morning",
    place: "sanctuary",
    activity: "visit",
    minutes: 25,
    carry: "vessel",
    text: "Pour water over the linga in the brick kalan and carry some home.",
    note: "Cham kings called Shiva's linga Bhadreshvara; the water ran off through a spout in the pedestal.",
    sources: ["https://en.wikipedia.org/wiki/Champa"],
  },
  {
    id: "day.vietnam.altar-first",
    label: "The ancestor altar on the first",
    scope: DAI_VIET,
    evidence: "documented",
    when: [{ type: "cycle", every: 9, on: 0 }, { type: "adult" }],
    weight: 8,
    part: "morning",
    place: "home",
    activity: "visit",
    minutes: 15,
    text: "Set fruit and incense on the ancestor altar: it is the first of the month.",
    sources: ["https://en.wikipedia.org/wiki/Vietnamese_folk_religion"],
    serves: ["remember-dead"],
  },
  {
    id: "day.vietnam.gio",
    label: "The giỗ feast",
    scope: DAI_VIET,
    evidence: "documented",
    when: [{ type: "anniversary", kind: "died" }],
    weight: 16,
    part: "evening",
    place: "home",
    activity: "cook",
    minutes: 60,
    text: "Cook the giỗ feast for your {dead}, {years} years gone, and call the kin.",
    note: "The death-day, not the birthday, was the date a Vietnamese family kept for each ancestor.",
    sources: ["https://en.wikipedia.org/wiki/Vietnamese_folk_religion"],
    serves: ["remember-dead"],
  },
  {
    id: "day.vietnam.dinh",
    label: "The guardian spirit at the đình",
    scope: { ...DAI_VIET, years: [1450, 1950] },
    evidence: "documented",
    when: [{ type: "sex", is: "male" }, { type: "rank", any: ["middling", "gentry", "elite"] }, { type: "cycle", every: 9, on: 4 }],
    weight: 5,
    part: "evening",
    place: "sanctuary",
    activity: "visit",
    minutes: 50,
    text: "Take your seat by age and rank at the đình feast for the village guardian.",
    note: "Seating at the communal house followed a strict order of age, office and degree.",
    sources: ["https://en.wikipedia.org/wiki/Vietnamese_folk_religion"],
  },
  {
    id: "day.theravada.alms",
    label: "Rice for the monks' bowls",
    scope: THERAVADA,
    evidence: "documented",
    when: [{ type: "observance", levels: ["devout", "regular"] }, { type: "adult" }],
    weight: 6,
    part: "morning",
    place: "home",
    activity: "visit",
    minutes: 15,
    carry: "vessel",
    text: "Kneel at your door with rice for the monks' bowls as they file past at dawn.",
    sources: ["https://en.wikipedia.org/wiki/Alms"],
  },
  {
    id: "day.burma.shinbyu",
    label: "The shinbyu",
    scope: BURMA,
    evidence: "documented",
    when: [{ type: "kin", kind: "child", minAge: 7, maxAge: 14 }, { type: "fortune", above: 0.4 }, { type: "chance", p: 0.04 }],
    weight: 8,
    part: "morning",
    place: "sanctuary",
    activity: "visit",
    minutes: 90,
    text: "Dress {child} as Prince Siddhartha for the walk to the monastery as a novice.",
    sources: ["https://en.wikipedia.org/wiki/Shinbyu"],
    serves: ["child-future"],
  },
  {
    id: "day.siam.spirit-house",
    label: "Rice for the spirit house",
    scope: SIAM,
    evidence: "documented",
    when: [{ type: "observance", levels: ["devout", "regular", "occasional"] }, { type: "chance", p: 0.4 }],
    weight: 4,
    part: "morning",
    place: "home",
    activity: "visit",
    minutes: 10,
    text: "Set rice, a garland and a candle at the spirit house of the land's guardian.",
    sources: ["https://en.wikipedia.org/wiki/Spirit_house"],
    serves: ["household-home"],
  },
  {
    id: "day.siam.wai-khru",
    label: "Paying respect to the master",
    scope: SIAM,
    evidence: "documented",
    when: [{ type: "kin", kind: "master" }, { type: "chance", p: 0.1 }],
    weight: 6,
    part: "morning",
    place: { kin: "master" },
    activity: "visit",
    minutes: 25,
    text: "Bring flowers, candles and incense to {master} and bow for the wai khru.",
    sources: ["https://en.wikipedia.org/wiki/Wai_khru"],
    serves: ["mastery"],
  },
  {
    id: "day.srivijaya.camphor",
    label: "Camphor for the monsoon ships",
    scope: SRIVIJAYA,
    evidence: "documented",
    when: [{ type: "work", match: /merchant|trade|clerk|scribe/i }, { type: "chance", p: 0.35 }],
    weight: 6,
    part: "midday",
    place: "market",
    activity: "visit",
    minutes: 45,
    carry: "bundle",
    text: "Weigh Barus camphor and benzoin for the ships waiting on the monsoon.",
    note: "Srivijaya controlled the straits and forwarded Sumatran forest resins to China and India.",
    sources: ["https://en.wikipedia.org/wiki/Srivijaya"],
  },
  {
    id: "day.java.dewi-sri",
    label: "The rice harvest for Dewi Sri",
    scope: JAVA,
    evidence: "documented",
    when: [{ type: "work", match: /farm|rice|paddy|field/i }, { type: "chance", p: 0.25 }],
    weight: 6,
    part: "morning",
    place: "work",
    activity: "gather",
    minutes: 50,
    carry: "basket",
    text: "Cut the rice one stalk at a time with the ani-ani, so as not to frighten Dewi Sri.",
    note: "The small palm-held blade was used because a sickle was thought to offend the rice goddess.",
    sources: ["https://en.wikipedia.org/wiki/Dewi_Sri", "https://en.wikipedia.org/wiki/Ani-ani"],
  },
  {
    id: "day.java.borobudur",
    label: "Stones for the great stupa",
    scope: CENTRAL_JAVA,
    evidence: "documented",
    when: [{ type: "rank", any: ["labouring"] }, { type: "adult" }, { type: "chance", p: 0.25 }],
    weight: 5,
    part: "midday",
    place: "edge",
    activity: "haul",
    minutes: 60,
    text: "Haul andesite blocks from the river up to the terraces of Borobudur.",
    sources: ["https://en.wikipedia.org/wiki/Borobudur"],
  },
  {
    id: "day.java.wayang",
    label: "Up all night for the wayang",
    scope: JAVA_BALI,
    evidence: "documented",
    when: [{ type: "chance", p: 0.15 }],
    weight: 4,
    part: "evening",
    place: { venue: "theatre" },
    activity: "visit",
    minutes: 180,
    text: "Sit up through the night as the dalang works the shadow puppets of the Mahabharata.",
    sources: ["https://en.wikipedia.org/wiki/Wayang"],
  },
  {
    id: "day.bali.canang",
    label: "The day's canang",
    scope: BALI,
    evidence: "documented",
    when: [{ type: "sex", is: "female" }, { type: "adult" }],
    weight: 6,
    part: "morning",
    place: "home",
    activity: "visit",
    minutes: 20,
    carry: "basket",
    text: "Set canang trays of flowers and rice at the house shrine and the gate.",
    note: "Small palm-leaf offerings are laid out every morning, including on the ground for the lower spirits.",
    sources: ["https://en.wikipedia.org/wiki/Canang_sari"],
    serves: ["household-home"],
  },
  {
    id: "day.bali.subak",
    label: "Offerings at the water temple",
    scope: BALI,
    evidence: "documented",
    when: [{ type: "work", match: /farm|rice|paddy|field/i }, { type: "chance", p: 0.25 }],
    weight: 6,
    part: "morning",
    place: "sanctuary",
    activity: "visit",
    minutes: 35,
    carry: "basket",
    text: "Carry offerings to the subak's water temple before the channels are opened.",
    note: "Water temples set the schedule by which each subak floods and plants its terraces.",
    sources: ["https://en.wikipedia.org/wiki/Subak_(irrigation)"],
  },
  {
    id: "day.malay.jumaat",
    label: "Friday prayer",
    scope: MALAY_ISLAM,
    evidence: "documented",
    when: [{ type: "cycle", every: 7, on: 2 }, { type: "sex", is: "male" }, { type: "adult" }, { type: "observance", levels: ["devout", "regular", "occasional"] }],
    weight: 8,
    part: "midday",
    place: "sanctuary",
    activity: "visit",
    minutes: 45,
    text: "Go to the mosque for the congregational prayer: it is Jumaat.",
    sources: ["https://en.wikipedia.org/wiki/Friday_prayer"],
  },
  {
    id: "day.malay.mengaji",
    label: "Qur'an lessons at the surau",
    scope: MALAY_ISLAM,
    evidence: "documented",
    when: [{ type: "kin", kind: "child", minAge: 6, maxAge: 14 }, { type: "observance", levels: ["devout", "regular"] }],
    weight: 5,
    part: "evening",
    place: "sanctuary",
    activity: "visit",
    minutes: 40,
    text: "Walk {child} to the surau to recite the Qur'an with the guru.",
    sources: ["https://en.wikipedia.org/wiki/Surau"],
    serves: ["child-future"],
  },
  {
    id: "day.java.slametan",
    label: "A slametan for the dead",
    scope: { ...JAVA, years: [1500, 1950] },
    evidence: "documented",
    when: [{ type: "anniversary", kind: "died" }],
    weight: 16,
    part: "evening",
    place: "home",
    activity: "cook",
    minutes: 60,
    text: "Hold a slametan with a cone of rice and prayers for your {dead}.",
    note: "Javanese households kept slametan on set days after a death, and then yearly.",
    sources: ["https://en.wikipedia.org/wiki/Slametan"],
    serves: ["remember-dead"],
  },
  {
    id: "day.java.cultuurstelsel",
    label: "The government's coffee",
    scope: { ...JAVA, years: [1830, 1870] },
    evidence: "documented",
    when: [{ type: "work", match: /farm|rice|paddy|field|grow/i }, { type: "chance", p: 0.2 }],
    weight: 6,
    part: "midday",
    place: "market",
    activity: "haul",
    minutes: 60,
    carry: "basket",
    text: "Deliver your village's quota of coffee to the government warehouse at a fixed price.",
    note: "Under the Cultivation System villages owed a fifth of their land, or its labour, to export crops.",
    sources: ["https://en.wikipedia.org/wiki/Cultivation_System"],
  },
  {
    id: "day.philippines.cockfight",
    label: "The cockfight",
    scope: PHILIPPINES,
    evidence: "documented",
    when: [{ type: "sex", is: "male" }, { type: "adult" }, { type: "chance", p: 0.15 }],
    weight: 4,
    part: "evening",
    place: "gathering",
    activity: "visit",
    minutes: 60,
    text: "Carry your fighting cock to the pit, with a wager on its bout.",
    note: "Pigafetta saw cockfighting with wagers on Palawan in 1521.",
    sources: ["https://en.wikipedia.org/wiki/Cockfight"],
  },
  {
    id: "day.philippines.simbang-gabi",
    label: "The dawn mass",
    scope: SPANISH_PHILIPPINES,
    evidence: "documented",
    when: [{ type: "date", dayOfYear: 354 }, { type: "observance", levels: ["devout", "regular", "occasional"] }],
    weight: 14,
    part: "morning",
    place: "sanctuary",
    activity: "visit",
    minutes: 60,
    text: "Walk to church before cockcrow for the Simbang Gabi, then eat bibingka outside.",
    note: "Nine dawn masses ran from 16 to 24 December, early so farmers could hear them before work.",
    sources: ["https://en.wikipedia.org/wiki/Simbang_Gabi"],
  },
  {
    id: "day.colonial.rubber",
    label: "Tapping rubber",
    scope: COLONIAL_SEA,
    evidence: "documented",
    when: [{ type: "work", match: /rubber|plantation|estate|tapper|coolie/i }],
    weight: 6,
    part: "morning",
    place: "work",
    activity: "work",
    minutes: 90,
    carry: "vessel",
    text: "Tap your row of rubber trees before dawn, while the latex runs freely.",
    sources: ["https://en.wikipedia.org/wiki/Rubber_tapping"],
  },
  {
    id: "day.australia.fire-stick",
    label: "Burning the country",
    scope: AUSTRALIA,
    evidence: "documented",
    when: [{ type: "season", any: ["autumn", "winter"] }, { type: "adult" }, { type: "chance", p: 0.25 }],
    weight: 6,
    part: "midday",
    place: "wild",
    activity: "work",
    minutes: 60,
    text: "Burn off a patch of old grass so green pick brings the kangaroos back.",
    note: "Cool, patchy burning kept open grassland and was read by early colonists as parkland.",
    sources: ["https://en.wikipedia.org/wiki/Fire-stick_farming"],
  },
  {
    id: "day.australia.songline",
    label: "Teaching the song of the country",
    scope: AUSTRALIA,
    evidence: "documented",
    when: [{ type: "kin", kind: "child", minAge: 8, maxAge: 16 }, { type: "chance", p: 0.25 }],
    weight: 6,
    part: "midday",
    place: "wild",
    activity: "visit",
    minutes: 60,
    text: "Walk with {child} and sing the verses for each waterhole along the track.",
    note: "A songline's verses name, in order, the landmarks and water along an ancestor's route.",
    sources: ["https://en.wikipedia.org/wiki/Songline"],
    serves: ["child-future"],
  },
  {
    id: "day.australia.corroboree",
    label: "Painting up for the corroboree",
    scope: AUSTRALIA,
    evidence: "documented",
    when: [{ type: "adult" }, { type: "chance", p: 0.12 }],
    weight: 5,
    part: "evening",
    place: "gathering",
    activity: "visit",
    minutes: 120,
    text: "Paint up with white clay and red ochre and dance at the corroboree.",
    sources: ["https://en.wikipedia.org/wiki/Corroboree"],
  },
  {
    id: "day.australia.bogong",
    label: "Bogong moths on the high rocks",
    scope: AUSTRALIAN_ALPS,
    evidence: "documented",
    when: [{ type: "season", any: ["summer"] }, { type: "chance", p: 0.4 }],
    weight: 7,
    part: "morning",
    place: "wild",
    activity: "gather",
    minutes: 60,
    carry: "bundle",
    text: "Smoke bogong moths out of the granite cracks, to roast in the ashes.",
    note: "Groups gathered in the high country each summer to feast on the aestivating moths.",
    sources: ["https://en.wikipedia.org/wiki/Bogong_moth"],
  },
  {
    id: "day.australia.budj-bim",
    label: "The eel traps at Budj Bim",
    scope: BUDJ_BIM,
    evidence: "documented",
    when: [{ type: "season", any: ["autumn"] }, { type: "chance", p: 0.4 }],
    weight: 7,
    part: "morning",
    place: "edge",
    activity: "tend",
    minutes: 50,
    carry: "basket",
    text: "Clear the stone channels and set the woven eel traps for the autumn run.",
    note: "The Gunditjmara channels in the Budj Bim lava flows are dated to at least 6,600 years ago.",
    sources: ["https://en.wikipedia.org/wiki/Budj_Bim"],
  },
  {
    id: "day.australia.blanket-day",
    label: "Blanket day",
    scope: COLONIAL_AUSTRALIA,
    evidence: "documented",
    when: [{ type: "date", dayOfYear: 144 }, { type: "adult" }],
    weight: 12,
    part: "morning",
    place: "gathering",
    activity: "visit",
    minutes: 60,
    text: "Line up at the police station for the government blanket: it is the Queen's Birthday.",
    note: "Colonial governments handed out blankets to Aboriginal people each year, in NSW on the monarch's birthday.",
    sources: ["https://en.wikipedia.org/wiki/History_of_Indigenous_Australians"],
  },
  {
    id: "day.newguinea.kuk",
    label: "Draining the swamp garden",
    scope: { ...NG_HIGHLANDS, years: [-7000, 1650] },
    evidence: "documented",
    when: [{ type: "work", match: /farm|garden|grow|field/i }, { type: "chance", p: 0.3 }],
    weight: 5,
    part: "morning",
    place: "work",
    activity: "work",
    minutes: 60,
    text: "Dig out the drainage ditch so the taro and bananas do not stand in water.",
    note: "Ditches at Kuk Swamp show wetland gardening in the highlands by about 7000 years ago.",
    sources: ["https://en.wikipedia.org/wiki/Kuk_Early_Agricultural_Site"],
  },
  {
    id: "day.newguinea.mounds",
    label: "Heaping the sweet potato mounds",
    scope: { ...NG_HIGHLANDS, years: [1650, 1950] },
    evidence: "documented",
    when: [{ type: "work", match: /farm|garden|grow|field/i }, { type: "chance", p: 0.3 }],
    weight: 5,
    part: "morning",
    place: "work",
    activity: "work",
    minutes: 60,
    text: "Heap grass compost into the mounds for the sweet potato vines.",
    note: "Sweet potato reached the highlands in the last few centuries and fed a great increase in pigs and people.",
    sources: ["https://en.wikipedia.org/wiki/Sweet_potato"],
  },
  {
    id: "day.newguinea.moka",
    label: "Counting pigs for the moka",
    scope: { ...NG_HIGHLANDS, years: [1700, 1950] },
    evidence: "documented",
    when: [{ type: "kin", kind: "friend" }, { type: "sex", is: "male" }, { type: "adult" }, { type: "chance", p: 0.2 }],
    weight: 5,
    part: "evening",
    place: { kin: "friend" },
    activity: "visit",
    minutes: 40,
    text: "Reckon with {friend} the pigs owed back, and more, at the next moka.",
    note: "In Hagen moka a return had to exceed the gift, and the surplus made a big man's name.",
    sources: ["https://en.wikipedia.org/wiki/Moka_exchange"],
  },
  {
    id: "day.trobriand.kula",
    label: "An armshell for the kula",
    scope: TROBRIANDS,
    evidence: "documented",
    when: [{ type: "sex", is: "male" }, { type: "adult" }, { type: "rank", any: ["middling", "gentry", "elite"] }, { type: "chance", p: 0.1 }],
    weight: 6,
    part: "midday",
    place: "edge",
    activity: "visit",
    minutes: 60,
    carry: "bundle",
    text: "Hand a mwali armshell to your kula partner from the next island, with the proper words.",
    note: "Armshells travelled one way round the ring and red shell necklaces the other.",
    sources: ["https://en.wikipedia.org/wiki/Kula_ring"],
  },
  {
    id: "day.trobriand.yam-house",
    label: "Yams for a sister's household",
    scope: TROBRIANDS,
    evidence: "documented",
    when: [{ type: "work", match: /farm|garden|grow|yam/i }, { type: "sex", is: "male" }, { type: "chance", p: 0.15 }],
    weight: 5,
    part: "midday",
    place: "door",
    activity: "haul",
    minutes: 50,
    carry: "basket",
    text: "Stack your finest yams in your sister's husband's yam house for all to see.",
    note: "A man's harvest went largely to his sister's household, displayed in its decorated yam house.",
    sources: ["https://en.wikipedia.org/wiki/Trobriand_Islands"],
    serves: ["raise-kin"],
  },
  {
    id: "day.lapita.dentate",
    label: "Stamping a Lapita pot",
    scope: LAPITA,
    evidence: "documented",
    when: [{ type: "work", match: /pot|clay|cera/i }],
    weight: 6,
    part: "midday",
    place: "work",
    activity: "work",
    minutes: 60,
    text: "Press the toothed stamp into the wet clay in bands of faces and curves.",
    sources: ["https://en.wikipedia.org/wiki/Lapita_culture"],
    serves: ["mastery"],
  },
  {
    id: "day.samoa.ava",
    label: "The 'ava circle",
    scope: TONGA_SAMOA,
    evidence: "documented",
    when: [{ type: "sex", is: "male" }, { type: "rank", any: ["gentry", "elite"] }, { type: "chance", p: 0.25 }],
    weight: 6,
    part: "evening",
    place: "gathering",
    activity: "visit",
    minutes: 60,
    text: "Take your place in the chiefs' circle and wait for your cup of 'ava to be called.",
    note: "Cups went round in order of rank, each called by the holder's title.",
    sources: ["https://en.wikipedia.org/wiki/Kava"],
  },
  {
    id: "day.hawaii.loi",
    label: "Tending the taro pond",
    scope: HAWAII,
    evidence: "documented",
    when: [{ type: "work", match: /farm|taro|garden|grow|field/i }, { type: "chance", p: 0.35 }],
    weight: 5,
    part: "morning",
    place: "work",
    activity: "tend",
    minutes: 60,
    text: "Weed the flooded taro patch and check the water flowing in from the ditch.",
    note: "Taro ponds were fed by stream channels, the water shared along the valley's ahupua'a.",
    sources: ["https://en.wikipedia.org/wiki/Taro"],
  },
  {
    id: "day.maori.hangi",
    label: "Laying the hāngī",
    scope: AOTEAROA,
    evidence: "documented",
    when: [{ type: "adult" }, { type: "chance", p: 0.12 }],
    weight: 5,
    part: "midday",
    place: "gathering",
    activity: "cook",
    minutes: 90,
    text: "Heat stones for the hāngī pit, to feed the visitors at the marae.",
    sources: ["https://en.wikipedia.org/wiki/H%C4%81ng%C4%AB", "https://en.wikipedia.org/wiki/Marae"],
  },
  {
    id: "day.yap.rai",
    label: "A rai stone changes hands",
    scope: YAP,
    evidence: "documented",
    when: [{ type: "fortune", above: 0.6 }, { type: "adult" }, { type: "chance", p: 0.05 }],
    weight: 6,
    part: "midday",
    place: "gathering",
    activity: "visit",
    minutes: 45,
    text: "Agree before witnesses that the great rai stone by the path now counts as your household's.",
    note: "The largest stones were never moved; ownership passed by common knowledge of their story.",
    sources: ["https://en.wikipedia.org/wiki/Rai_stones"],
  },
  {
    id: "day.carolines.star-compass",
    label: "Learning the star compass",
    scope: CAROLINES,
    evidence: "documented",
    when: [{ type: "kin", kind: "master" }],
    weight: 6,
    part: "evening",
    place: { kin: "master" },
    activity: "visit",
    minutes: 50,
    text: "Sit while {master} lays out the star compass in a ring of stones and quizzes you.",
    note: "Carolinian navigators taught the rising and setting points of stars with coral pieces on a mat.",
    sources: ["https://en.wikipedia.org/wiki/Mau_Piailug", "https://en.wikipedia.org/wiki/Polynesian_navigation"],
    serves: ["mastery"],
  },
];

export const southeastAsiaPacificFestivals: Festival[] = [
  {
    id: "fest.vietnam.tet",
    label: "Tết",
    scope: DAI_VIET,
    evidence: "documented",
    date: { dayOfYear: 36 },
    rest: true,
    place: "gathering",
    minutes: 120,
    text: "It is Tết: sweep the house, offer to the ancestors and call on kin in new clothes.",
    note: "The lunar new year falls between late January and mid-February.",
    sources: ["https://en.wikipedia.org/wiki/T%E1%BA%BFt"],
  },
  {
    id: "fest.burma.thingyan",
    label: "Thingyan",
    scope: BURMA,
    evidence: "documented",
    date: { dayOfYear: 104 },
    rest: true,
    place: "gathering",
    minutes: 150,
    text: "It is Thingyan: throw water on everyone to wash away the old year, and wash the Buddha images.",
    sources: ["https://en.wikipedia.org/wiki/Thingyan"],
  },
  {
    id: "fest.siam.songkran",
    label: "Songkran",
    scope: SIAM,
    evidence: "documented",
    date: { dayOfYear: 104 },
    rest: true,
    place: "gathering",
    minutes: 150,
    text: "It is Songkran: pour scented water on the hands of elders and heap sand at the monastery.",
    sources: ["https://en.wikipedia.org/wiki/Songkran_(Thailand)"],
  },
  {
    id: "fest.siam.loy-krathong",
    label: "Loy Krathong",
    scope: SIAM,
    evidence: "documented",
    date: { dayOfYear: 318 },
    rest: false,
    place: "edge",
    minutes: 60,
    text: "Float a banana-leaf boat with a candle and incense on the river at the full moon.",
    note: "Full moon of the twelfth lunar month, usually in November.",
    sources: ["https://en.wikipedia.org/wiki/Loy_Krathong"],
  },
  {
    id: "fest.bali.nyepi",
    label: "Nyepi",
    scope: BALI,
    evidence: "documented",
    date: { dayOfYear: 80 },
    rest: true,
    place: "hearth",
    minutes: 240,
    text: "It is Nyepi: no fire, no work, no going out, so the demons pass over a silent island.",
    note: "The Saka new year moves with the moon through March.",
    sources: ["https://en.wikipedia.org/wiki/Nyepi"],
  },
  {
    id: "fest.bali.galungan",
    label: "Galungan",
    scope: BALI,
    evidence: "documented",
    // The 210-day pawukon year is about 64 game days.
    date: { every: 64, on: 20 },
    rest: true,
    place: "sanctuary",
    minutes: 120,
    text: "It is Galungan: bamboo penjor arch over the street and the ancestors come home.",
    sources: ["https://en.wikipedia.org/wiki/Galungan"],
  },
  {
    id: "fest.trobriand.milamala",
    label: "the milamala",
    scope: TROBRIANDS,
    evidence: "documented",
    date: { dayOfYear: 244 },
    rest: false,
    place: "gathering",
    minutes: 120,
    text: "It is milamala: the baloma spirits are back in the village for the harvest dances.",
    sources: ["https://en.wikipedia.org/wiki/Trobriand_Islands"],
  },
  {
    id: "fest.hawaii.makahiki",
    label: "the Makahiki",
    scope: { ...HAWAII, years: [1500, 1819] },
    evidence: "documented",
    date: { dayOfYear: 320 },
    rest: true,
    place: "gathering",
    minutes: 180,
    text: "It is the Makahiki of Lono: war is forbidden, tribute is paid, and the games begin.",
    note: "It opened when the Pleiades rose at sunset and ended with the kapu system in 1819.",
    sources: ["https://en.wikipedia.org/wiki/Makahiki"],
  },
  {
    id: "fest.maori.matariki",
    label: "Matariki",
    scope: AOTEAROA,
    evidence: "documented",
    date: { dayOfYear: 178 },
    rest: false,
    place: "gathering",
    minutes: 90,
    text: "Matariki has risen before dawn: name the year's dead and feast from the stores.",
    sources: ["https://en.wikipedia.org/wiki/Matariki"],
  },
  {
    id: "fest.tonga.sabbath",
    label: "the Sabbath",
    scope: TONGA,
    evidence: "documented",
    date: { every: 7, on: 4 },
    rest: true,
    place: "sanctuary",
    minutes: 120,
    text: "It is Sunday, and by the law of the 1875 constitution no one in Tonga may work.",
    sources: ["https://en.wikipedia.org/wiki/Constitution_of_Tonga"],
  },
];
