import type { Festival, Occasion } from "./types";

type Span = [number, number];
type Box = [number, number, number, number];
const NAFWA = ["north-african-west-asian" as const];

const NATUFIAN = { years: [-13000, -9500] as Span, bounds: [34, 29, 38, 37] as Box };
const PPN = { years: [-9500, -6500] as Span, bounds: [34, 30, 42, 39] as Box };
const MESOPOTAMIA = { years: [-3000, -300] as Span, bounds: [40, 29, 49, 37.5] as Box, cultures: NAFWA };
const SUMER = { years: [-3000, -2000] as Span, bounds: [43, 29, 49, 34] as Box, cultures: NAFWA };
const OLD_BABYLON = { years: [-2000, -1500] as Span, bounds: [40, 29, 50, 37] as Box, cultures: NAFWA };
const ASSYRIA = { years: [-1000, -600] as Span, bounds: [38, 33, 46, 38] as Box, cultures: NAFWA };
const HATTI = { years: [-1650, -1180] as Span, bounds: [30, 36, 40, 42] as Box, cultures: NAFWA };
const CANAAN = { years: [-1500, -300] as Span, bounds: [34.5, 31, 37, 37] as Box, cultures: NAFWA };
const JUDAH = { years: [-1000, -586] as Span, bounds: [34, 30, 37, 34] as Box, cultures: NAFWA };
const SECOND_TEMPLE = { years: [-500, 136] as Span, bounds: [34, 30, 37, 34] as Box, cultures: NAFWA };
const ZOROASTRIAN = { years: [-550, 700] as Span, bounds: [44, 25, 63, 40] as Box, cultures: NAFWA };
const IRAN = { years: [-550, 1950] as Span, bounds: [44, 25, 63, 40] as Box, cultures: NAFWA };
const SYRIAC = { years: [350, 650] as Span, bounds: [35, 32, 44, 38] as Box, cultures: NAFWA };
const ARMENIA = { years: [301, 1950] as Span, bounds: [43, 38.5, 47, 41.5] as Box };
// East of 34E, so the Nile and the Maghreb keep their own.
const ISLAMIC = { years: [650, 1950] as Span, bounds: [34, 12, 63, 42] as Box, cultures: NAFWA };
const ANATOLIA = { years: [1080, 1950] as Span, bounds: [26, 36, 34, 42] as Box, cultures: NAFWA };
const OTTOMAN = { years: [1400, 1923] as Span, bounds: [26, 36, 45, 42.5] as Box, cultures: NAFWA };
const ARABIA = { years: [-900, 1950] as Span, bounds: [37, 12, 60, 33] as Box, cultures: NAFWA };
const SHII_IRAN = { years: [1501, 1950] as Span, bounds: [44, 25, 63, 40] as Box, cultures: NAFWA };

/**
 * Lunar feasts drift about eleven days a year against the sun; the Islamic
 * dates here are pinned to one year (1445 AH, 2024) and the Jewish ones to a
 * typical year.
 */
export const westAsiaOccasions: Occasion[] = [
  {
    id: "day.natufian.wild-barley",
    label: "Cutting wild barley",
    scope: NATUFIAN,
    evidence: "documented",
    when: [{ type: "season", any: ["spring"] }, { type: "adult" }],
    weight: 6,
    part: "morning",
    place: "wild",
    activity: "gather",
    minutes: 60,
    carry: "basket",
    text: "Cut the ripe wild barley with your bone-hafted flint sickle.",
    note: "Natufian sickle blades carry the gloss that comes only from cutting cereal stems.",
    sources: ["https://en.wikipedia.org/wiki/Natufian_culture"],
  },
  {
    id: "day.natufian.tortoise-feast",
    label: "Feast at a grave",
    scope: NATUFIAN,
    evidence: "hypothesis",
    when: [{ type: "anniversary", kind: "died" }],
    weight: 14,
    part: "evening",
    place: "home",
    activity: "cook",
    minutes: 45,
    text: "Roast tortoises and share them over the grave of your {dead}.",
    note: "At Hilazon Tachtit a woman was buried with the shells of some seventy tortoises eaten at her funeral.",
    sources: ["https://en.wikipedia.org/wiki/Natufian_culture"],
    serves: ["remember-dead"],
  },
  {
    id: "day.ppn.plastered-skull",
    label: "Plastering a skull",
    scope: { ...PPN, years: [-8500, -6500] as Span },
    evidence: "hypothesis",
    when: [{ type: "anniversary", kind: "died" }],
    weight: 16,
    part: "evening",
    place: "home",
    activity: "tend",
    minutes: 40,
    text: "Mould fresh plaster over the skull of your {dead}, with cowrie shells for eyes.",
    note: "Plastered skulls with cowrie-shell eyes were found at Jericho; tending them on a death-day is our guess.",
    sources: ["https://en.wikipedia.org/wiki/Plastered_human_skulls", "https://en.wikipedia.org/wiki/Jericho"],
    serves: ["remember-dead"],
  },
  {
    id: "day.ppn.enclosure-feast",
    label: "Feast at the enclosures",
    scope: { years: [-9600, -8000] as Span, bounds: [37, 36, 41, 38.5] as Box },
    evidence: "hypothesis",
    when: [{ type: "adult" }, { type: "chance", p: 0.2 }],
    weight: 5,
    part: "midday",
    place: "sanctuary",
    activity: "haul",
    minutes: 60,
    carry: "vessel",
    text: "Carry porridge and gazelle meat up to the pillar enclosures for the builders' feast.",
    note: "Göbekli Tepe's grinding stones and gazelle bones suggest feasts that drew people to raise the pillars.",
    sources: ["https://en.wikipedia.org/wiki/G%C3%B6bekli_Tepe"],
    serves: ["shared-future"],
  },
  {
    id: "day.sumer.ration",
    label: "Drawing the barley ration",
    scope: SUMER,
    evidence: "documented",
    when: [{ type: "cycle", every: 9, on: 0 }, { type: "rank", any: ["destitute", "labouring"] }, { type: "adult" }],
    weight: 8,
    part: "morning",
    place: "sanctuary",
    activity: "haul",
    minutes: 40,
    carry: "basket",
    text: "Collect your month's barley ration and oil from the temple storehouse.",
    note: "Ur III ration lists give labourers about sixty litres of barley a month, women and children less.",
    sources: ["https://en.wikipedia.org/wiki/Third_Dynasty_of_Ur"],
  },
  {
    id: "day.sumer.beer-straw",
    label: "Beer with a friend",
    scope: MESOPOTAMIA,
    evidence: "documented",
    when: [{ type: "kin", kind: "friend" }, { type: "chance", p: 0.3 }],
    weight: 4,
    part: "evening",
    place: "door",
    activity: "visit",
    minutes: 45,
    text: "Drink beer through reed straws from one jar with {friend}.",
    note: "Seals show drinkers sharing a jar through long straws that filtered out the husks.",
    sources: ["https://en.wikipedia.org/wiki/Ninkasi"],
  },
  {
    id: "day.sumer.eshshesh",
    label: "The eššešu feast",
    scope: MESOPOTAMIA,
    evidence: "documented",
    when: [{ type: "cycle", every: 9, on: 4 }, { type: "observance", levels: ["devout", "regular"] }, { type: "adult" }],
    weight: 6,
    part: "morning",
    place: "sanctuary",
    activity: "visit",
    minutes: 35,
    carry: "basket",
    text: "Bring dates and fine flour to the temple for the eššešu feast.",
    note: "The eššešu fell on set days of each month, the fifteenth among them, with extra offerings to the gods.",
    sources: ["https://en.wikipedia.org/wiki/Babylonian_calendar"],
  },
  {
    id: "day.mesopotamia.kispum",
    label: "The kispum for the dead",
    scope: MESOPOTAMIA,
    evidence: "documented",
    when: [{ type: "cycle", every: 9, on: 8 }, { type: "adult" }],
    weight: 7,
    part: "evening",
    place: "home",
    activity: "visit",
    minutes: 25,
    carry: "vessel",
    text: "Pour water down the clay pipe and set out bread for the family dead.",
    note: "The kispum was held at the dark of the moon; some houses at Ur had libation pipes over family graves.",
    sources: ["https://en.wikipedia.org/wiki/Ancient_Mesopotamian_religion"],
    serves: ["remember-dead"],
  },
  {
    id: "day.mesopotamia.canal",
    label: "Clearing the canal",
    scope: MESOPOTAMIA,
    evidence: "documented",
    when: [{ type: "season", any: ["winter", "autumn"] }, { type: "work", match: /farm|field|plough|peasant|labour|till/i }, { type: "chance", p: 0.35 }],
    weight: 6,
    part: "morning",
    place: "edge",
    activity: "work",
    minutes: 70,
    text: "Dig the silt out of the field canal before the flood water comes.",
    note: "Canal clearing was the commonest labour levy in Mesopotamian records.",
    sources: ["https://en.wikipedia.org/wiki/Irrigation_in_Mesopotamia"],
  },
  {
    id: "day.mesopotamia.shearing",
    label: "The shearing",
    scope: MESOPOTAMIA,
    evidence: "documented",
    when: [{ type: "season", any: ["spring"] }, { type: "work", match: /herd|shep|flock|goat/i }],
    weight: 8,
    part: "morning",
    place: "sanctuary",
    activity: "graze",
    minutes: 60,
    text: "Drive your flock to the shearing pen, where the temple scribes count the fleeces.",
    note: "Sheep were plucked or sheared in spring under the eye of temple and palace accountants.",
    sources: ["https://en.wikipedia.org/wiki/Economy_of_ancient_Mesopotamia"],
  },
  {
    id: "day.babylon.contract",
    label: "Drawing up a contract",
    scope: OLD_BABYLON,
    evidence: "documented",
    when: [{ type: "work", match: /scrib|clerk|writ|notar/i }, { type: "chance", p: 0.4 }],
    weight: 6,
    part: "midday",
    place: "work",
    activity: "work",
    minutes: 50,
    text: "Write out a loan of silver, each witness's seal rolled across the wet clay.",
    note: "Old Babylonian loans name the lender, the god of the oath and several witnesses, each with his seal.",
    sources: ["https://en.wikipedia.org/wiki/Cylinder_seal"],
  },
  {
    id: "day.babylon.alewife",
    label: "At the alewife's",
    scope: OLD_BABYLON,
    evidence: "documented",
    when: [{ type: "adult" }, { type: "sex", is: "male" }, { type: "chance", p: 0.2 }],
    weight: 4,
    part: "evening",
    place: { venue: "tavern" },
    activity: "visit",
    minutes: 50,
    text: "Drink date beer on credit until harvest at the alewife's house.",
    note: "Hammurabi's laws fix what a tavern-keeper may charge and oblige her to report outlaws who meet there.",
    sources: ["https://en.wikipedia.org/wiki/Code_of_Hammurabi"],
  },
  {
    id: "day.assur.kanesh-letter",
    label: "A letter to Assur",
    scope: { years: [-1950, -1700] as Span, bounds: [34, 35, 44, 40] as Box, cultures: NAFWA },
    evidence: "documented",
    when: [{ type: "work", match: /merchant|trad|caravan|donkey/i }, { type: "chance", p: 0.4 }],
    weight: 6,
    part: "evening",
    place: "home",
    activity: "work",
    minutes: 40,
    text: "Seal a letter to your partners in Assur about the tin and textiles on the donkeys.",
    note: "Over twenty thousand such letters survive from the Assyrian merchants' quarter at Kanesh.",
    sources: ["https://en.wikipedia.org/wiki/K%C3%BCltepe"],
    serves: ["mastery"],
  },
  {
    id: "day.assyria.pazuzu",
    label: "An amulet for the cradle",
    scope: { ...ASSYRIA, years: [-1000, -300] as Span, bounds: [38, 29, 49, 38] as Box },
    evidence: "documented",
    when: [{ type: "kin", kind: "child", maxAge: 1 }],
    weight: 8,
    part: "evening",
    place: "home",
    activity: "tend",
    minutes: 15,
    text: "Hang a Pazuzu head over {child}'s cradle to drive off Lamashtu.",
    note: "Lamashtu stole infants; the demon Pazuzu was her enemy and his bronze heads were hung for protection.",
    sources: ["https://en.wikipedia.org/wiki/Pazuzu", "https://en.wikipedia.org/wiki/Lamashtu"],
    serves: ["raise-kin"],
  },
  {
    id: "day.hatti.thick-bread",
    label: "Baking for the gods' festival",
    scope: HATTI,
    evidence: "documented",
    when: [{ type: "season", any: ["spring", "autumn"] }, { type: "observance", levels: ["devout", "regular"] }, { type: "chance", p: 0.3 }],
    weight: 6,
    part: "morning",
    place: "sanctuary",
    activity: "haul",
    minutes: 45,
    carry: "basket",
    text: "Bake thick loaves and carry them to the temple for the gods' festival.",
    note: "The spring crocus festival and the autumn haste festival each ran over weeks, with breads listed by the hundred.",
    sources: ["https://en.wikipedia.org/wiki/Hittite_mythology_and_religion"],
  },
  {
    id: "day.hatti.old-woman",
    label: "The Old Woman's rite",
    scope: HATTI,
    evidence: "documented",
    when: [{ type: "fortune", below: 0.35 }, { type: "chance", p: 0.15 }],
    weight: 5,
    part: "evening",
    place: "home",
    activity: "visit",
    minutes: 45,
    text: "Call the Old Woman to wave a piglet and red wool over your troubled household.",
    note: "Rituals of the Old Woman (MUNUS ŠU.GI) such as Tunnawiya's use piglets, dough and coloured wool as substitutes.",
    sources: ["https://en.wikipedia.org/wiki/Hittite_mythology_and_religion"],
    serves: ["restore-household"],
  },
  {
    id: "day.canaan.marzeah",
    label: "The marzeah banquet",
    scope: CANAAN,
    evidence: "documented",
    when: [{ type: "rank", any: ["middling", "gentry", "elite"] }, { type: "sex", is: "male" }, { type: "chance", p: 0.2 }],
    weight: 5,
    part: "evening",
    place: "door",
    activity: "visit",
    minutes: 60,
    text: "Recline and drink with your marzeah fellowship in its banquet house.",
    note: "Ugaritic tablets record marzeah societies with their own houses and vineyards; Amos condemns their couches.",
    sources: ["https://en.wikipedia.org/wiki/Marzeah"],
  },
  {
    id: "day.phoenicia.murex",
    label: "Working the purple vats",
    scope: { years: [-1200, -64] as Span, bounds: [34.8, 32.5, 36.5, 36] as Box, cultures: NAFWA },
    evidence: "documented",
    when: [{ type: "work", match: /dye|purple|cloth|weav/i }, { type: "chance", p: 0.4 }],
    weight: 7,
    part: "morning",
    place: "work",
    activity: "work",
    minutes: 60,
    text: "Crack murex shells and set the glands to steep in the stinking purple vats.",
    note: "Heaps of broken murex shells still lie outside Tyre and Sidon.",
    sources: ["https://en.wikipedia.org/wiki/Tyrian_purple"],
    serves: ["mastery"],
  },
  {
    id: "day.phoenicia.adonis-garden",
    label: "A garden of Adonis",
    scope: { years: [-500, 400] as Span, bounds: [34.8, 32.5, 37, 35.5] as Box, cultures: NAFWA },
    evidence: "documented",
    when: [{ type: "season", any: ["summer"] }, { type: "sex", is: "female" }, { type: "chance", p: 0.3 }],
    weight: 5,
    part: "morning",
    place: "home",
    activity: "tend",
    minutes: 20,
    text: "Sow lettuce and fennel in a potsherd to spring up and wither for Adonis.",
    note: "Lucian describes the women of Byblos mourning Adonis each year.",
    sources: ["https://en.wikipedia.org/wiki/Gardens_of_Adonis"],
  },
  {
    id: "day.judah.new-moon",
    label: "The new moon",
    scope: JUDAH,
    evidence: "documented",
    when: [{ type: "cycle", every: 9, on: 0 }, { type: "adult" }],
    weight: 7,
    part: "evening",
    place: "hearth",
    activity: "cook",
    minutes: 40,
    text: "Feast with your household for the new moon, when no grain is sold.",
    note: "Amos has the grain dealers impatient for the new moon to be over so they can sell again.",
    sources: ["https://en.wikipedia.org/wiki/Rosh_Chodesh"],
    serves: ["household-home"],
  },
  {
    id: "day.judah.sabbath-lamp",
    label: "Lighting the Sabbath lamp",
    scope: SECOND_TEMPLE,
    evidence: "documented",
    when: [{ type: "cycle", every: 7, on: 2 }, { type: "sex", is: "female" }, { type: "adult" }],
    weight: 9,
    part: "evening",
    place: "hearth",
    activity: "cook",
    minutes: 30,
    text: "Light the Sabbath lamp before sunset and set tomorrow's food to keep warm.",
    note: "The Mishnah tractate Shabbat assigns the lighting of the lamp to women.",
    sources: ["https://en.wikipedia.org/wiki/Shabbat_candles"],
    serves: ["household-home"],
  },
  {
    id: "day.judah.firstfruits",
    label: "Bringing the first fruits",
    scope: { ...SECOND_TEMPLE, years: [-500, 70] as Span },
    evidence: "documented",
    when: [{ type: "date", dayOfYear: 160 }, { type: "work", match: /farm|field|vine|orchard|peasant|garden/i }],
    weight: 14,
    part: "morning",
    place: "sanctuary",
    activity: "haul",
    minutes: 60,
    carry: "basket",
    text: "Carry a basket of first figs and grapes up to the Temple for Shavuot.",
    note: "Mishnah Bikkurim describes the procession, an ox with gilded horns leading; Shavuot moves with the moon.",
    sources: ["https://en.wikipedia.org/wiki/Bikkurim_(first-fruits)"],
  },
  {
    id: "day.judah.sukkah",
    label: "Building the sukkah",
    scope: SECOND_TEMPLE,
    evidence: "documented",
    when: [{ type: "date", dayOfYear: 290 }, { type: "adult" }],
    weight: 14,
    part: "midday",
    place: "home",
    activity: "work",
    minutes: 60,
    text: "Build a booth of palm fronds and willow on your roof for Sukkot.",
    note: "Nehemiah has booths put up on roofs and in courtyards; the date moves with the moon.",
    sources: ["https://en.wikipedia.org/wiki/Sukkot"],
    serves: ["household-home"],
  },
  {
    id: "day.iran.fire-temple",
    label: "Feeding the sacred fire",
    scope: ZOROASTRIAN,
    evidence: "documented",
    when: [{ type: "observance", levels: ["devout", "regular"] }, { type: "chance", p: 0.25 }],
    weight: 5,
    part: "morning",
    place: "sanctuary",
    activity: "visit",
    minutes: 30,
    carry: "bundle",
    text: "Bring dry wood and incense to the fire temple for the priest to feed the fire.",
    sources: ["https://en.wikipedia.org/wiki/Atar"],
  },
  {
    id: "day.iran.fravardigan",
    label: "Welcoming the fravashis",
    scope: { ...IRAN, years: [-550, 1100] as Span },
    evidence: "documented",
    when: [{ type: "date", dayOfYear: 72 }],
    weight: 14,
    part: "evening",
    place: "home",
    activity: "visit",
    minutes: 30,
    carry: "basket",
    text: "Set food and a lamp on your roof for the returning spirits of the dead.",
    note: "Biruni describes food laid on roofs for the fravashis in the last days before Nowruz.",
    sources: ["https://en.wikipedia.org/wiki/Fravashi"],
    serves: ["remember-dead"],
  },
  {
    id: "day.iran.gahambar",
    label: "The gahambar feast",
    scope: ZOROASTRIAN,
    evidence: "documented",
    when: [{ type: "date", dayOfYear: 123 }, { type: "adult" }],
    weight: 14,
    part: "evening",
    place: "gathering",
    activity: "cook",
    minutes: 60,
    carry: "basket",
    text: "Bring bread and wine to the gahambar that the neighbours eat together.",
    note: "Maidyozarem, mid-spring, is the first of the six seasonal gahambars; all are expected to contribute.",
    sources: ["https://en.wikipedia.org/wiki/Gahambar"],
    serves: ["shared-future"],
  },
  {
    id: "day.iran.sadeh",
    label: "The Sadeh fire",
    scope: { ...IRAN, years: [200, 1300] as Span },
    evidence: "documented",
    when: [{ type: "date", dayOfYear: 30 }],
    weight: 13,
    part: "evening",
    place: "gathering",
    activity: "warm",
    minutes: 50,
    carry: "bundle",
    text: "Carry brushwood to the great Sadeh bonfire, fifty days before Nowruz.",
    sources: ["https://en.wikipedia.org/wiki/Sadeh"],
  },
  {
    id: "day.iran.mehregan",
    label: "Mehregan",
    scope: IRAN,
    evidence: "documented",
    when: [{ type: "date", dayOfYear: 280 }, { type: "kin", kind: "friend" }],
    weight: 12,
    part: "evening",
    place: "door",
    activity: "visit",
    minutes: 45,
    carry: "basket",
    text: "Take pomegranates and sweets to {friend} for the feast of Mehr.",
    sources: ["https://en.wikipedia.org/wiki/Mehregan"],
  },
  {
    id: "day.iran.qanat",
    label: "Clearing the qanat",
    scope: IRAN,
    evidence: "documented",
    when: [{ type: "work", match: /farm|field|well|dig|qanat|labour|garden/i }, { type: "chance", p: 0.2 }],
    weight: 5,
    part: "morning",
    place: "edge",
    activity: "work",
    minutes: 70,
    text: "Crawl down the qanat shaft to dig out the silt that choked the flow.",
    note: "The muqanni, the qanat digger, was a hereditary trade; channels ran for kilometres underground.",
    sources: ["https://en.wikipedia.org/wiki/Qanat"],
  },
  {
    id: "day.iran.chaharshanbe-suri",
    label: "Leaping the fires",
    scope: { ...SHII_IRAN, years: [1000, 1950] as Span },
    evidence: "documented",
    when: [{ type: "date", dayOfYear: 76 }],
    weight: 13,
    part: "evening",
    place: "gathering",
    activity: "play",
    minutes: 40,
    text: "Jump the bonfires in the lane and give the fire your sickly pallor.",
    note: "On the last Tuesday night before Nowruz people leap fires saying 'my yellowness to you, your redness to me'.",
    sources: ["https://en.wikipedia.org/wiki/Chaharshanbe_Suri"],
  },
  {
    id: "day.iran.rowzeh",
    label: "A rowzeh for Husayn",
    scope: SHII_IRAN,
    evidence: "documented",
    when: [{ type: "date", dayOfYear: 190 }, { type: "adult" }],
    weight: 13,
    part: "evening",
    place: "door",
    activity: "visit",
    minutes: 60,
    text: "Weep with the neighbours as the rowzeh-khan recites Husayn's martyrdom.",
    note: "Mourning gatherings fill the first ten days of Muharram; placed here for 1446 AH.",
    sources: ["https://en.wikipedia.org/wiki/Mourning_of_Muharram"],
  },
  {
    id: "day.syriac.stylite",
    label: "Visiting the pillar saint",
    scope: SYRIAC,
    evidence: "documented",
    when: [{ type: "fortune", below: 0.4 }, { type: "chance", p: 0.1 }],
    weight: 4,
    part: "midday",
    place: "wild",
    activity: "visit",
    minutes: 60,
    text: "Walk out to the stylite's pillar and ask his blessing on your household.",
    note: "Simeon spent thirty-seven years on his pillar near Aleppo and judged villagers' disputes from it.",
    sources: ["https://en.wikipedia.org/wiki/Simeon_Stylites"],
    serves: ["restore-household"],
  },
  {
    id: "day.syriac.qurbana",
    label: "Sunday Qurbana",
    scope: SYRIAC,
    evidence: "documented",
    when: [{ type: "cycle", every: 7, on: 4 }, { type: "observance", levels: ["devout", "regular", "occasional"] }],
    weight: 7,
    part: "morning",
    place: "sanctuary",
    activity: "visit",
    minutes: 60,
    text: "Stand for the Qurbana while the choir sings Ephrem's hymns: it is Sunday.",
    note: "Ephrem wrote his madrashe for women's choirs.",
    sources: ["https://en.wikipedia.org/wiki/Ephrem_the_Syrian"],
  },
  {
    id: "day.armenia.vardavar",
    label: "Vardavar",
    scope: ARMENIA,
    evidence: "documented",
    when: [{ type: "date", dayOfYear: 196 }, { type: "kin", kind: "friend" }],
    weight: 13,
    part: "midday",
    place: "gathering",
    activity: "play",
    minutes: 30,
    carry: "vessel",
    text: "Throw water over {friend} for Vardavar.",
    note: "Vardavar falls fourteen weeks after Easter, so it moves; roses were once thrown too.",
    sources: ["https://en.wikipedia.org/wiki/Vardavar"],
  },
  {
    id: "day.islam.iftar",
    label: "Iftar",
    scope: ISLAMIC,
    evidence: "documented",
    when: [{ type: "date", dayOfYear: 82 }, { type: "observance", levels: ["devout", "regular", "occasional"] }],
    weight: 15,
    part: "evening",
    place: "hearth",
    activity: "cook",
    minutes: 45,
    text: "Break the Ramadan fast with dates and water at the sunset call.",
    note: "Ramadan drifts through the solar year; one of its thirty evenings stands here for 1445 AH.",
    sources: ["https://en.wikipedia.org/wiki/Iftar"],
  },
  {
    id: "day.islam.grave",
    label: "At a grave",
    scope: ISLAMIC,
    evidence: "documented",
    when: [{ type: "anniversary", kind: "died" }],
    weight: 12,
    part: "morning",
    place: "edge",
    activity: "visit",
    minutes: 40,
    text: "Recite Ya-Sin over the grave of your {dead}, dead {years} years now.",
    sources: ["https://en.wikipedia.org/wiki/Ya-Sin"],
    serves: ["remember-dead"],
  },
  {
    id: "day.islam.kuttab",
    label: "Walking a child to the kuttab",
    scope: ISLAMIC,
    evidence: "documented",
    when: [{ type: "kin", kind: "child", minAge: 5, maxAge: 11 }, { type: "chance", p: 0.3 }],
    weight: 5,
    part: "morning",
    place: "sanctuary",
    activity: "visit",
    minutes: 20,
    text: "Walk {child} to the kuttab to chant the day's sura with the other children.",
    sources: ["https://en.wikipedia.org/wiki/Kuttab"],
    serves: ["child-future"],
  },
  {
    id: "day.islam.hammam",
    label: "The hammam",
    scope: ISLAMIC,
    evidence: "documented",
    when: [{ type: "chance", p: 0.2 }],
    weight: 4,
    part: "evening",
    place: { venue: "bath" },
    activity: "visit",
    minutes: 70,
    text: "Spend the afternoon in the hammam, scrubbed down with a rough mitt.",
    sources: ["https://en.wikipedia.org/wiki/Hammam"],
  },
  {
    id: "day.ottoman.bride-hammam",
    label: "Looking for a bride",
    scope: OTTOMAN,
    evidence: "documented",
    when: [{ type: "seek-match" }, { type: "sex", is: "female" }],
    weight: 8,
    part: "midday",
    place: { venue: "bath" },
    activity: "visit",
    minutes: 70,
    text: "Look over the girls at the women's hammam for a bride for {child}.",
    note: "Mothers and aunts vetted brides in the bath, where nothing could be hidden.",
    sources: ["https://en.wikipedia.org/wiki/Turkish_bath"],
    serves: ["marriage-hope"],
  },
  {
    id: "day.ottoman.meddah",
    label: "The meddah's tale",
    scope: { ...OTTOMAN, years: [1550, 1923] as Span },
    evidence: "documented",
    when: [{ type: "sex", is: "male" }, { type: "adult" }, { type: "chance", p: 0.25 }],
    weight: 5,
    part: "evening",
    place: { venue: "coffee-house" },
    activity: "visit",
    minutes: 60,
    text: "Hear the meddah do all the voices of a tale over a cup of coffee.",
    note: "The meddah worked with only a handkerchief and a stick.",
    sources: ["https://en.wikipedia.org/wiki/Meddah"],
  },
  {
    id: "day.syria.hakawati",
    label: "The hakawati",
    scope: { years: [1550, 1950] as Span, bounds: [35, 29, 48, 37.5] as Box, cultures: NAFWA },
    evidence: "documented",
    when: [{ type: "sex", is: "male" }, { type: "adult" }, { type: "chance", p: 0.25 }],
    weight: 5,
    part: "evening",
    place: { venue: "coffee-house" },
    activity: "visit",
    minutes: 60,
    text: "Listen to the hakawati read the next night's part of the Sirat Antar.",
    note: "Storytellers left a cliffhanger each night to bring the audience back.",
    sources: ["https://en.wikipedia.org/wiki/Hakawati"],
  },
  {
    id: "day.islam.waqf",
    label: "Seeing to the waqf",
    scope: ISLAMIC,
    evidence: "documented",
    when: [{ type: "rank", any: ["gentry", "elite"] }, { type: "chance", p: 0.2 }],
    weight: 5,
    part: "midday",
    place: "market",
    activity: "visit",
    minutes: 45,
    text: "Collect the shop rents of your family's waqf that keeps the fountain running.",
    note: "Pious endowments paid for fountains, schools and soup kitchens out of shop and bath rents.",
    sources: ["https://en.wikipedia.org/wiki/Waqf"],
    serves: ["elder-kin"],
  },
  {
    id: "day.islam.ziyara",
    label: "Visiting a saint's tomb",
    scope: { ...ISLAMIC, years: [900, 1950] as Span },
    evidence: "documented",
    when: [{ type: "fortune", below: 0.45 }, { type: "chance", p: 0.15 }],
    weight: 5,
    part: "midday",
    place: { venue: "shrine" },
    activity: "visit",
    minutes: 40,
    text: "Visit the local saint's tomb to knot a rag to its grille with your petition.",
    sources: ["https://en.wikipedia.org/wiki/Ziyarat"],
    serves: ["restore-household"],
  },
  {
    id: "day.islam.caravanserai",
    label: "Lodging at the caravanserai",
    scope: ISLAMIC,
    evidence: "documented",
    when: [{ type: "work", match: /merchant|trad|caravan|camel|muleteer/i }, { type: "chance", p: 0.35 }],
    weight: 6,
    part: "evening",
    place: "market",
    activity: "haul",
    minutes: 45,
    carry: "bundle",
    text: "Bargain with the khan-keeper for a room and stabling for your bales and beasts.",
    sources: ["https://en.wikipedia.org/wiki/Caravanserai"],
  },
  {
    id: "day.islam.scribe",
    label: "Copying for the bookseller",
    scope: ISLAMIC,
    evidence: "documented",
    when: [{ type: "work", match: /scrib|copy|clerk|calligra|writ/i }, { type: "chance", p: 0.4 }],
    weight: 6,
    part: "morning",
    place: "work",
    activity: "work",
    minutes: 60,
    text: "Copy a quire in clean naskh for the bookseller in the paper market.",
    note: "Baghdad's warraqin copied and sold books from the paper market by the ninth century.",
    sources: ["https://en.wikipedia.org/wiki/Naskh_(script)"],
    serves: ["mastery"],
  },
  {
    id: "day.islam.dyer",
    label: "Working the indigo vats",
    scope: ISLAMIC,
    evidence: "inferred",
    when: [{ type: "work", match: /dye|cloth|weav|textile/i }, { type: "chance", p: 0.4 }],
    weight: 6,
    part: "morning",
    place: "work",
    activity: "work",
    minutes: 60,
    text: "Dip the cloth in the indigo vats until it comes up deep blue.",
    sources: ["https://en.wikipedia.org/wiki/Indigo_dye"],
  },
  {
    id: "day.islam.potter",
    label: "Firing the kiln",
    scope: ISLAMIC,
    evidence: "inferred",
    when: [{ type: "work", match: /pot|tile|kiln|ceram/i }, { type: "chance", p: 0.35 }],
    weight: 6,
    part: "midday",
    place: "work",
    activity: "work",
    minutes: 60,
    text: "Stack glazed bowls on their tripod spurs in the kiln, ready for firing.",
    note: "Three-legged kiln spurs kept glazed pots apart; their scars show under medieval bowls.",
    sources: ["https://en.wikipedia.org/wiki/Islamic_pottery"],
  },
  {
    id: "day.anatolia.iznik",
    label: "Painting Iznik tiles",
    scope: { years: [1480, 1700] as Span, bounds: [29, 39.5, 30.5, 41] as Box, cultures: NAFWA },
    evidence: "documented",
    when: [{ type: "work", match: /pot|tile|kiln|ceram|paint/i }],
    weight: 8,
    part: "morning",
    place: "work",
    activity: "work",
    minutes: 60,
    text: "Paint tulips and carnations in cobalt and tomato red on tiles for a new mosque.",
    sources: ["https://en.wikipedia.org/wiki/Iznik_pottery"],
    serves: ["mastery"],
  },
  {
    id: "day.arabia.date-pollination",
    label: "Pollinating the palms",
    scope: { years: [-3000, 1950] as Span, bounds: [40, 12, 60, 33] as Box, cultures: NAFWA },
    evidence: "documented",
    when: [{ type: "season", any: ["spring"] }, { type: "work", match: /farm|date|palm|garden|orchard|peasant/i }],
    weight: 8,
    part: "morning",
    place: "work",
    activity: "tend",
    minutes: 60,
    text: "Climb your date palms to bind sprigs of male flowers into the female blossoms.",
    note: "Hand-pollination of date palms is shown on Assyrian palace reliefs and still done today.",
    sources: ["https://en.wikipedia.org/wiki/Date_palm"],
  },
  {
    id: "day.arabia.guest",
    label: "Feeding a guest",
    scope: ARABIA,
    evidence: "documented",
    when: [{ type: "work", match: /herd|camel|shep|flock|goat|pastor/i }, { type: "chance", p: 0.15 }],
    weight: 6,
    part: "evening",
    place: "hearth",
    activity: "cook",
    minutes: 60,
    text: "Slaughter a sheep for the guest at your tent and ask no business for three days.",
    note: "A guest was owed three days' food and protection before being asked his errand.",
    sources: ["https://en.wikipedia.org/wiki/Bedouin"],
  },
  {
    id: "day.arabia.qahwa",
    label: "Pounding the coffee",
    scope: { ...ARABIA, years: [1550, 1950] as Span },
    evidence: "documented",
    when: [{ type: "sex", is: "male" }, { type: "adult" }, { type: "chance", p: 0.3 }],
    weight: 5,
    part: "evening",
    place: "hearth",
    activity: "warm",
    minutes: 40,
    text: "Roast coffee beans over the fire, the brass mortar ringing out to call the neighbours.",
    note: "The rhythm of the brass mihbash was an invitation heard across the camp.",
    sources: ["https://en.wikipedia.org/wiki/Arabic_coffee"],
  },
];

export const westAsiaFestivals: Festival[] = [
  {
    id: "fest.judah.sabbath",
    label: "the Sabbath",
    scope: SECOND_TEMPLE,
    evidence: "documented",
    date: { every: 7, on: 3 },
    rest: true,
    place: "sanctuary",
    minutes: 90,
    text: "It is the Sabbath: no fire is kindled and no work done, and the Law is read in the synagogue.",
    sources: ["https://en.wikipedia.org/wiki/Shabbat"],
  },
  {
    id: "fest.judah.pesach",
    label: "Passover",
    scope: SECOND_TEMPLE,
    evidence: "documented",
    date: { dayOfYear: 110 },
    rest: true,
    place: "hearth",
    minutes: 120,
    text: "It is Passover: eat the roast lamb with unleavened bread and bitter herbs.",
    note: "Pesach falls on the full moon of Nisan, so it moves by weeks against the solar year.",
    sources: ["https://en.wikipedia.org/wiki/Passover"],
  },
  {
    id: "fest.judah.yom-kippur",
    label: "the Day of Atonement",
    scope: SECOND_TEMPLE,
    evidence: "documented",
    date: { dayOfYear: 284 },
    rest: true,
    place: "sanctuary",
    minutes: 120,
    text: "It is Yom Kippur: a day of fasting and no work while the high priest enters the Holy of Holies.",
    note: "The tenth of Tishri moves with the moon; placed here in early autumn.",
    sources: ["https://en.wikipedia.org/wiki/Yom_Kippur"],
  },
  {
    id: "fest.mesopotamia.akitu",
    label: "the akītu festival",
    scope: { ...MESOPOTAMIA, years: [-2000, -100] as Span },
    evidence: "documented",
    date: { dayOfYear: 90 },
    rest: false,
    place: "sanctuary",
    minutes: 90,
    text: "It is the akītu of Nisannu: Marduk's statue is carried out to the akītu house as the year begins.",
    note: "In Babylon the king was struck by the priest and had to weep before his kingship was renewed.",
    sources: ["https://en.wikipedia.org/wiki/Akitu"],
  },
  {
    id: "fest.iran.nowruz",
    label: "Nowruz",
    scope: IRAN,
    evidence: "documented",
    date: { dayOfYear: 80 },
    rest: true,
    place: "gathering",
    minutes: 120,
    text: "It is Nowruz, the new year at the equinox: new clothes, visits, and sprouted wheat on the cloth.",
    sources: ["https://en.wikipedia.org/wiki/Nowruz"],
  },
  {
    id: "fest.islam.eid-al-fitr",
    label: "Eid al-Fitr",
    scope: ISLAMIC,
    evidence: "documented",
    date: { dayOfYear: 101 },
    rest: true,
    place: "gathering",
    minutes: 120,
    text: "It is Eid al-Fitr: the fast is over, the prayer is said in the open, and sweets go round.",
    note: "The date moves eleven days earlier each solar year; placed for 1445 AH.",
    sources: ["https://en.wikipedia.org/wiki/Eid_al-Fitr"],
  },
  {
    id: "fest.islam.eid-al-adha",
    label: "Eid al-Adha",
    scope: ISLAMIC,
    evidence: "documented",
    date: { dayOfYear: 168 },
    rest: true,
    place: "gathering",
    minutes: 120,
    text: "It is Eid al-Adha: those who can slaughter a sheep and a third of the meat goes to the poor.",
    note: "The date moves eleven days earlier each solar year; placed for 1445 AH.",
    sources: ["https://en.wikipedia.org/wiki/Eid_al-Adha"],
  },
  {
    id: "fest.anatolia.seker-bayrami",
    label: "the Sugar Feast",
    scope: ANATOLIA,
    evidence: "documented",
    date: { dayOfYear: 101 },
    rest: true,
    place: "gathering",
    minutes: 120,
    text: "It is Şeker Bayramı: kiss your elders' hands, and children go door to door for sweets.",
    note: "The end of Ramadan moves eleven days earlier each solar year; placed for 1445 AH.",
    sources: ["https://en.wikipedia.org/wiki/Eid_al-Fitr"],
  },
  {
    id: "fest.anatolia.kurban-bayrami",
    label: "the Feast of Sacrifice",
    scope: ANATOLIA,
    evidence: "documented",
    date: { dayOfYear: 168 },
    rest: true,
    place: "gathering",
    minutes: 120,
    text: "It is Kurban Bayramı: the ram is sacrificed after the morning prayer and its meat shared out.",
    note: "The date moves eleven days earlier each solar year; placed for 1445 AH.",
    sources: ["https://en.wikipedia.org/wiki/Eid_al-Adha"],
  },
  {
    id: "fest.iran.ashura",
    label: "Ashura",
    scope: SHII_IRAN,
    evidence: "documented",
    date: { dayOfYear: 198 },
    rest: true,
    place: "gathering",
    minutes: 120,
    text: "It is Ashura: the shops are shut, and the mourning processions beat their breasts for Husayn.",
    note: "The tenth of Muharram moves with the moon; placed for 1446 AH.",
    sources: ["https://en.wikipedia.org/wiki/Ashura", "https://en.wikipedia.org/wiki/Ta%27zieh"],
  },
];
